### ISSUE TITLE
Machine in use?

### ISSUE THREAD

**Issue by GanddahBeast** [raoulvdberge/refinedstorage#1000]
#### Steps to reproduce:
1. Trying to make an advanced processor from scratch using crafters, patterns, and solderers doesn't work
2. Crafting Monitor says "Machine is in use"
3. I expected Solderers to start and the Refined Storage system to make an advanced processor
... 
![2017-02-18_19 42 55](https://cloud.githubusercontent.com/assets/25873076/23098096/fa52d708-f612-11e6-9513-d9998706d93e.png)

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge: 12.18.3.2215
- Refined Storage:

Does this issue occur on a server? [yes/no] No.... SinglePlayer World

#### If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here]

![]

**Comment by raoulvdberge** [comment]
You are doing it wrong.

https://refinedstorage.raoulvdberge.com/wiki/automating-the-solderer

**Comment by GanddahBeast** [comment]
Thanks very much!

**Comment by raoulvdberge** [comment]
Also, you opened issue number #1000. Congrats!
