### ISSUE TITLE
FR: Empty Storage Upgrade

### ISSUE THREAD

**Issue by dredhorse** [raoulvdberge/refinedstorage#1002]
#### Issue description:

If you have more than one automatic recipes in an external system dual crafting tasks can feed different recipes into that external crafting system. I guess this mainly only happens with chests as crafting system in-betweens like for the Actually Additions Empowerer Setup. Or if you only want to export items into a chest if it is empty.

#### What happens:

Crafting breaks because items for two different recipes are in the chest.

#### What you expected to happen:

A way to block using the chest if it is not empty.

#### Do You have a suggestion?

Yes :-) An empty Storage Upgrade, recipe (chest, redstore, upgrade in solderer) which will check the adjunct storage to be empty before new item / recipe will be pushed into it.

So the upgrade can be used in an exporter and in a crafter and behaves the following way.

a) exporter = checks if storage is empty, passes either one item or stack (if also stack upgrade) into storage, otherwise does nothing
b) crafter = checks if storage is empty, passes recipe items into the storage, otherwise shows machine is busy in crafting monitor.

**Comment by raoulvdberge** [comment]
I don't think this is for RS to handle
