### ISSUE TITLE
[1.10.2] Ore Dictionary recipes not working (manual crafting)

### ISSUE THREAD

**Issue by xSparky911x** [raoulvdberge/refinedstorage#1004]
#### Issue description:
I noticed when crafting somethings (particularly chests and Tinkers blank patterns) the crafting grid is not respecting the ore dictionary properly. Im pretty sure it is not a JEI issue because if I use a Vanilla Crafting Table, or a Tinkers Crafting Station the recipes work fine

#### What happens:
If I view the recipe for the Tinkers Construct Blank Pattern or a regular Minecraft Chest in JEI and then click the "+" button to transfer the items to the crafting grid any wood planks, other than Vanilla ones, do not transfer to the grid. I have the items in my storage system and have also tried having them in my personal inventory.
#### Steps to reproduce:
1. Put Fir Wood Planks and regular sticks into a storage system
2. Look up the recipe for a simple Minecraft Chest
3. Click the plus to transfer items into the crafting grid from JEI
...

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge: 2221
- Refined Storage: 1.2.22

Does this issue occur on a server? [yes/no]
Yes as well as single player

**Comment by xSparky911x** [comment]
Any luck on this issue? I have having issues with any recipe that uses ore dictionary items like planks, slabs and so on...

**Comment by raoulvdberge** [comment]
Didn't have time to look at this yet, it's low-priority.

**Comment by raoulvdberge** [comment]
Unfortunately we can't fix this because we can't detect if the recipe is an oredict one.

**Comment by PapiDimmi** [comment]
Aw, man. This bug is really annoying. It sucks that you won’t fix it. 😕
