### ISSUE TITLE
[1.10.2] Major lag, crafting grid crash

### ISSUE THREAD

**Issue by Leon1236** [raoulvdberge/refinedstorage#1005]
#### Issue description:
I get form 40 FPS to 5 FPS when i reconect my controller to network. I have 50ish cables, 4-5 importers, 2 external storage plugs, 3 exporters and 2 solderers in network 
Plus it crashes sometimes upon opening crafting grid

#### What happens:
It lags like hell
crashes

#### What you expected to happen:
Not to lag so much

#### Steps to reproduce:
1. Dissconect controller ( FPS boost)
2. Connect controller ( FPS hell)

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge: 12.18.32221
- Refined Storage: 1.2.22

Does this issue occur on a server? [yes/no]
Singleplayer

#### If a (crash)log is relevant for this issue, link it here:

crash log upon opening grid
http://pastebin.com/FkJk2cts

**Comment by hypernova132** [comment]
What are the external storage plugs connected to?

**Comment by raoulvdberge** [comment]
For performance issues we need a profiling report: https://refinedstorage.raoulvdberge.com/wiki/profiling

**Comment by raoulvdberge** [comment]
I'll close this, since you're not sending the report. The crash you got is already reported: #898
