### ISSUE TITLE
[1.11.2 1.4.1] Guaranteed Client Crash

### ISSUE THREAD

**Issue by kreezxil** [raoulvdberge/refinedstorage#1007]
#### Issue and the what descripton:
Client crashes when you place a bucket in the middle left hand slop of any crafting grid

#### What you expected to happen:
Client not to crash

#### Steps to reproduce:
1. open any 3x3 crafting grid
2. place standard minecraft bucket in middle left slot
3. get popcorn
4. enjoy the crash

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.11.2
- Forge: 2235
- Refined Storage: 1.4.1

Does this issue occur on a server? yes

#### If a (crash)log is relevant for this issue, link it here:
http://pastebin.com/kW1MNZzq

I have tried this with multiple players and on both Forge builds 2233 and 2235

**Comment by way2muchnoise** [comment]
Try removing what ever `pw.prok.realbench.WorkbenchInventory` is

**Comment by kreezxil** [comment]
Did that then got a crash while creating a sticky piston on the upper left two vertical slots.. I'm still using other combinations.

-----Original Message-----

**Comment by raoulvdberge** [comment]
Send us that crash you just got with the pistons.

**Comment by kreezxil** [comment]
fml client latest: https://gist.github.com/kreezxil/97234f7de4943fb4ae674552225691aa

client crash report: https://gist.github.com/kreezxil/bb122d9039fdfd3b453a4b48db2661aa

**Comment by raoulvdberge** [comment]
Doesn't look like an RS issue, more of a bad recipe issue. Can you reproduce it with just RS?

**Comment by kreezxil** [comment]
no, it has me perplexed too, that is why I shared it with as your mod is mentioned at least once. I've loaded the mods in pack in halves and quarters and it doesn't reproduce, but when they are all together it reproduces reliably. I'm thinking that I might've exceeded my id limit for items. If you have any ideas let me know, otherwise you can close the thread.

**Comment by raoulvdberge** [comment]
Since the issue occurs with (sticky?) pistons, it might be an oredict issue with the slime balls perhaps?

**Comment by kreezxil** [comment]
that's a thought

**Comment by kreezxil** [comment]
I've been removing mod groups and testing against the sticky piston crafting recipe and got the following with new information involving refined storage.

https://paste.ee/p/FvsnW

**Comment by kreezxil** [comment]
And yes, real bench is not in it.

**Comment by raoulvdberge** [comment]
Cana you repro it in a normal crafting bench?

**Comment by kreezxil** [comment]
ok, thanks for your persistence, I found the issue, turns it out the slime issue was/is a conflict between random things and ye olde tanks. Now to find the bucket issue.

https://github.com/shadowfacts/YeOldeTanks/issues/24
