### ISSUE TITLE
Game crash when using constructor/destructor

### ISSUE THREAD

**Issue by SeanTheSheep04** [raoulvdberge/refinedstorage#1008]
#### Issue description:
Game crash when using constructor/destructor
#### What happens:
I set up an obsidian generator using a constructor to place lava in the path of flowing water with a destructor to collect the obsidian that is created. I set the constructor to only work without a redstone signal and I have a detector set to send a redstone signal when my system contains more than 64 obsidian. I connected this setup to my storage system using cables and a few seconds later, the game crashed and now when I attempt to load the world it crashes before it finishes loading.
#### What you expected to happen:
I expected it to automatically produce obsidian when I had less than 64 in my system using the constructor to place lava that will be turned into obsidian by a stream of water and then having a destructor destroy the obsidian and put it in my system. I have seen this setup used in a video and it should be functional.
#### Steps to reproduce:
1. Place a constructor and a destructor opposite each other,  facing the same block between them.
2. Place a water source block with one block between it and the block the constructor and destructor are facing.
3. Set the constructor to only work without a redstone signal and filter the destructor to only break obsidian.
4. Place a detector in the block beneath the constructor and set it to emit a redstone signal when the storage system contains more than 64 obsidian.
5. Connect the constructor and destructor to the storage system with cables and wait a few seconds for the game to crash.
...

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.11.2
- Forge: 13.20.0.2228
- Refined Storage: 1.4.1

Does this issue occur on a server? [yes/no] no

#### If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here]
[crash-2017-02-21_17.02.43-server.txt](https://github.com/raoulvdberge/refinedstorage/files/791698/crash-2017-02-21_17.02.43-server.txt)

**Comment by raoulvdberge** [comment]
I'm actually pretty sure this is a Forge bug, where a fake player doesn't have a current hand assigned.

**Comment by raoulvdberge** [comment]
Nevermind, this is an RS bug.
