### ISSUE TITLE
1.10.2 Disk Drive bug/crash 

### ISSUE THREAD

**Issue by Toxoplasmosis** [raoulvdberge/refinedstorage#1009]
#### Issue description:
When ever i look at disk drive game instantly crashes or says Connection lost "A fatal error has occurred, this connection is terminated
#### What happens:
Instant crash when i look at disk drive supper annoying 
#### What you expected to happen:
To be able to look at that block lol
#### Steps to reproduce:
1. Install 192 mods
2. store 300,000 items
3. crash
...

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge: 12.18.3.2234
- Refined Storage: 1.2.22 (tried older ones also)

Does this issue occur on a server? [yes/no]
no (single player and lan)
#### If a (crash)log is relevant for this issue, link it here:

https://www.mediafire.com/?qx3u1jr707xpg7q (log file don't know if it helps)

**Comment by raoulvdberge** [comment]
Update HWYLA

**Comment by Toxoplasmosis** [comment]
Genius!

**Comment by raoulvdberge** [comment]
You have an interesting Github username...
