### ISSUE TITLE
Creative Controller Texture is incorrect in 1.10.2

### ISSUE THREAD

**Issue by BrisingrAerowing** [raoulvdberge/refinedstorage#1010]
#### Issue description:

The creative controller uses the normal controller offline texture, instead of the online texture. This is only when the controller is in block form, in the inventory the texture is correct.

#### What happens:

The block uses the wrong texture.

#### What you expected to happen:

The block uses the online texture

#### Steps to reproduce:
1. Go into creative
2. Get a Creative Controller
3. Place it down
...

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge: 12.18.3.2221
- Refined Storage: 1.2.22

Does this issue occur on a server? [yes/no]

#### If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here]

**Comment by raoulvdberge** [comment]
Does this happen on a server?

**Comment by raoulvdberge** [comment]
I can't reproduce this:

![x](https://raoulvdberge.com/vXBvlp)

**Comment by BrisingrAerowing** [comment]
I can't reproduce this now, either. 😕 Weird.

I did remove some mods I wasn't using. Might have been one of them goofing something up.
