### ISSUE TITLE
AE2 + RS replicatable dupe bug.

### ISSUE THREAD

**Issue by Duncyn** [raoulvdberge/refinedstorage#1011]
#### Issue description:
I found a dupe bug with the ae2 interface and refind storadge interfaces. It dupes when they try to keep the same items in them and are conected with storage busses. They dupe items when ae2 tries to extract the items to the refind storage interface.
#### What happens:
If you try to keep 1 stone in 2 seperate slots in the rs interface and 1 stone in one of the slots in the ae2 interface and export stone from the tiny ae system to the tiny rs system there will be a stone increase in the rs interface. (Can work with larger numbers.)
#### What you expected to happen:
To dupe any stackable item.
#### Steps to reproduce:
Steps below pictures.
![ae_export](https://cloud.githubusercontent.com/assets/25965012/23231310/a35eb7fe-f947-11e6-9acb-ed44cf1684e3.png)
![ae_interface](https://cloud.githubusercontent.com/assets/25965012/23231311/a360b324-f947-11e6-905e-0e522c6c7d06.png)
![ref_interface](https://cloud.githubusercontent.com/assets/25965012/23231312/a3619eec-f947-11e6-9478-71cb54302669.png)
![total_setup](https://cloud.githubusercontent.com/assets/25965012/23231313/a362d55a-f947-11e6-8dfb-2e90a341974f.png)

1.Set up an ae2 controller and an rs controller with power.
2.Hook up an interface to the two systems. With on the ae2 interface an external storage and on the rs interface a storage bus.
3.Let the rs interface try to keep one stone in two of its slots and the ae2 interface keep one stone.
4.Use an export bus with at least 2 acceleration cards to export stone to the rs interface.
5.Put three stone in the rs interface and see the number increase.
(6.)Can do with entire stacks and if you use a second external storage with a higher priority on a craft it will fill up the crate.

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge:
- Refined Storage:

Does this issue occur on a server? [yes/no]
yes, also single player

**Comment by VT-14** [comment]
AppliedEnergistics/Applied-Energistics-2#2813

In the other topic, he said he was using RS 1.2.14 (current is 1.2.22), and Forge 12.18.3.2185 (Also out of date).

**Comment by VT-14** [comment]
I managed to reproduce this issue on Refined Storage 1.2.22, AE2 rv4-alpha11, and Forge 12.18.3.2239

I think this setup picture is slightly easier to understand.  The GUIs are set up identical to the original post.
![2017-02-23_22 36 02](https://cloud.githubusercontent.com/assets/12564251/23289661/3fa954d0-fa19-11e6-8ab5-620937434949.png)

I decided to try to figure out which direction items were going.  Setting the Refined Storage External Storage to Extract only caused... well... this:
![2017-02-23_22 42 30](https://cloud.githubusercontent.com/assets/12564251/23289692/85dd0960-fa19-11e6-9df1-3e3bf68bc323.png)
![2017-02-23_22 42 32](https://cloud.githubusercontent.com/assets/12564251/23289694/8850c254-fa19-11e6-88ee-4133e91cb784.png)
![2017-02-23_22 42 34](https://cloud.githubusercontent.com/assets/12564251/23289697/8adbc12c-fa19-11e6-83b9-21aab62c98cf.png)

**Comment by Duncyn** [comment]
Yea sorry about the versions not being completely correct, just wanted this bug to be out there so it wont be abused too much.

**Comment by tyler489** [comment]
This is an issue with ae interfaces in general

**Comment by raoulvdberge** [comment]
Isn't this an AE bug?

**Comment by tyler489** [comment]
Yes.. ae interfaces dupe item infinity in that version
