### ISSUE TITLE
Export bus + external storage.

### ISSUE THREAD

**Issue by AugustoAmaral** [raoulvdberge/refinedstorage#1013]
In AE2 I usually make an item cache system that works like this: I export with the "export bus" in the option (craft to export that apperas when you add export card to export bus) an item to a chest/drawer and I put an "external storage" in that same drawer/Chest, then every time I need an item, I pull it out of the chest and then the system starts it to craft automatically.
And in Refined Storage i can't do this cause i don't have the option craft to export, and when i do thism the game crash due looping (not really crash, just drop down all tps and you can't connect)

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge: 12.18.3.2215
- Refined Storage: 1.2.18

Does this issue occur on a server? [yes/no]
yes

**Comment by timotree3** [comment]
If you'd like to keep a certain amount of an item in your network at all times, you can use a detector which triggers a crafter.
