### ISSUE TITLE
(Potential overloaded) "Lost connection to server" when playing in single player

### ISSUE THREAD

**Issue by soerenkk** [raoulvdberge/refinedstorage#1014]
#### Issue description:
First of all, the issue might not be with Refined Storage, however i was working with RS when the issue occurred, and I'm not sure where the problem is at, when I read through the Game Output (the game doesn't crash, so that is all i got, since no crash log seems to be generated).

I was playing the Sky Factory 3 modpack from the Curse client.
When the initial issue occurred, i was working on automation with RS. I had a way to automating the Mystical Agriculture essence's, but as it is known, when using the Master crystal (the one with unlimited uses), the recipes are acting up. I then decided to change it to something more reliable.

I then changed it to using a RS Crafter pointing to a Crafter from RFTools (on top, if that helps). Under the RFTolls Crafter I've placed an RS Importer (the issue occurred after I've inserted a stack upgrade and 3 speed upgrades in the RS Importer). The RFTools Crafter was set in fast mode. It kept putting content to the RFTools Crafter output buffer as the RS Importer was importing (it kept pulling from the top right slot in the RFTools Crafter's output buffer, since it kept crafting items), which is why I might suspect that this new setup might got overloaded somewhere. When I've noticed that the RS Importer couldn't clear the output buffer on the RFTools Crafter, I've headed over to my Grid's to check if it was actually importing and crafting (about 3 seconds away from the location the setup where). But when i was about to right click (didn't made it) my Crafting Grid (my pointer was looking at an RS Network Transmitter, not clicking or interacting with), at that moment the game froze for like a halt second, and then I was presented with a "disconnect" screen like it I was playing on a multiplayer server (I know the single player creates a local server that you connect to, and then you just play on your own, until you open it up to the LAN). When I click the button on the "disconnect" screen, I then get the screen where I can choose a server to join. The client searched for local and LAN servers, but find none.

When I then exit the multiplayer screen, and try to load up the world from single player, then it joins the world, and almost instantly I get the "disconnect" screen again. That keeps happening, and I've tried to restart minecraft, but no luck.

#### What happens:
It seems like the local server crashes, however the client, doesn't. But I get presented with a "disconnect" screen. Read the section above for more details on how I've got there

#### What you expected to happen:
That I could keep playing.

#### Steps to reproduce:
Written in details in the issue description.

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge: 12.18.3.2215
- Refined Storage: 1.2.18 (default in the Sky Factory 3 modpack on the Curse launcher).
- Sky Factory 3: 3.0.6

I've added "InventoryTweaks-1.61-58" to the pack I'm playing, using the Curse client (it have been working for days without issues).

#### Does this issue occur on a server? [yes/no]
no (haven't tested, in an actual multiplayer server).

#### If a (crash)log is relevant for this issue, link it here:

This log is from a single session. Unfortunately I didn't copy the Game Output from the session where the issue occurred, but when I try to play the world, the same thing keeps happening when the world is loaded.
[https://gist.github.com/soerenkk/0a743421a81ae5cf6142a114ccbba02c](url)
Notice: Complete "Game Output" log, replaced my player name and UUID, beside that, it is unaltered.

**Comment by raoulvdberge** [comment]
Can you try updating HWYLA?

**Comment by raoulvdberge** [comment]
In fact, just update SF3. The latest SF3 version is 3.0.7, you're on 3.0.6.

**Comment by soerenkk** [comment]
SF3 3.0.7 is marked as beta, but I'll give it a go. I'll let you know.

**Comment by soerenkk** [comment]
Well that seems to have done the job, I can load my world again, and it seems to work now.

Thank you very much. And I really like this mod 👍
