### ISSUE TITLE
Server crash when using a constructor with any kind of skull.

### ISSUE THREAD

**Issue by timotree3** [raoulvdberge/refinedstorage#1015]
#### Issue description:

When I have configured a constructor to place skulls the game crashes instantly. I have tested this on singleplayer and on a server and the crash seems to be server side.
#### What happens:
The game crashes and my world is unenterable.

#### What you expected to happen:
Regular constructor behavior: Placing the skull if there are any in the network.

#### Steps to reproduce:
1. Place a creative controller
2. Place a grid
3. Place a 1k storage block
4. Place a filler block with one block between your controller
5. Place a constructor facing into that block
6. Break the filler block
7. Set the constructor to place any of the vanilla skulls
8. Put skulls in your system
9. Crash

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge: Not sure but server .jar is named `FTBserver-1.10.2-12.18.3.2185-universal` if that helps.
- Modpack: Direwolf20 1.10.2 (v1.5.1)
- Refined Storage: 1.2.20

Does this issue occur on a server? yes

#### If a (crash)log is relevant for this issue, link it here:

https://gist.github.com/timotree3/7bff97f11da8f51d67beaa407eac44c5

**Comment by raoulvdberge** [comment]
Make sure you are on the latest version before reporting
