### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by soerenkk** [raoulvdberge/refinedstorage#1016]
#### Issue description:
The game crashed, when I tried to clear out my inventory.

#### What happens:
I've filled my inventory with stuff from my chicken farm, when I tried to put it into my RS system, the game crashed. Not sure if it was while I put it in, or when I tried to open the grid (crafting grid, not trying to craft anything).

#### What you expected to happen:
To clean up my inventory.

#### Steps to reproduce:
See "What happens".

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge: 12.18.3.2234
- Refined Storage: 1.2.22
- Sky Factory 3: 3.0.7
- InventoryTweaks: 1.61-58

#### Does this issue occur on a server? [yes/no]
No.

#### If a (crash)log is relevant for this issue, link it here:

https://gist.github.com/soerenkk/35dd922e012fcf6d60174c8e7f973f94

**Comment by raoulvdberge** [comment]
I don't think this crash still happens on 1.11+.
