### ISSUE TITLE
Hotkey for selecting search bar.

### ISSUE THREAD

**Issue by TRumy** [raoulvdberge/refinedstorage#1019]
#### Issue description:
The hotkey for selecting the search/filter bar is TAB, a popular(my) inventory key - player can't exit out Grid GUI using inventory key. This is just a request, not necessary - perhaps make the hotkeys configurable?
#### What happens:
When trying to exit out of a grid (any grid as they all have search bars) by using TAB(inventory key), the grid highlights the search bar so the player can start typing.
#### What you expected to happen:
Player exits the grid GUI.
#### Steps to reproduce:
1. In the grid GUI, press TAB key, assuming said key is the set inventory key.

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge: 12.18.3.2185
- Refined Storage: 1.2.22

Does this issue occur on a server? [yes/no]
Unknown - More Than Likely
#### If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here]

**Comment by IamAlathe** [comment]
Is that why I can't exit RS monitors using tab?  I had no idea!  I'm glad I stumbled across this one!

**Comment by Spongman** [comment]
tab stops working when the caret is in a text box.
