### ISSUE TITLE
Pattern grid displays machine from one mod, creates pattern for a different mod.

### ISSUE THREAD

**Issue by varukasalt** [raoulvdberge/refinedstorage#102]
Trying to create a pattern for an IC2 generator. Pattern grid displays correct materials and output for IC2 machine, but it will create a pattern for a RS machine.

**Comment by raoulvdberge** [comment]
![screenshot](http://i.imgur.com/G2l1g1F.png)

???

**Comment by varukasalt** [comment]
https://drive.google.com/open?id=0Bwtrqbm8rR01SmZXdWFMdzIzOGs

**Comment by Harith163** [comment]
That is not a problem! It just says that the pattern disc belongs to the RS mod. Put it into a crafter and it will work as intended.

**Comment by raoulvdberge** [comment]
Like @Harith163 said, that is just the WAILA mod reporting that the pattern item belongs to RS.

**Comment by varukasalt** [comment]
Sorry.

**Comment by raoulvdberge** [comment]
No problem!
