### ISSUE TITLE
i think solderer is too slow to make tons of things

### ISSUE THREAD

**Issue by syrun97** [raoulvdberge/refinedstorage#1020]
#### Issue description:
need fast solderer
#### What happens:
no fast solderer
#### What you expected to happen:
fast solderer that can craft items per tick
#### Steps to reproduce:
1.craft 8 64k disk
2.I CANNOT WAIT
3.plz
...

#### Version (Make sure you are on the latest version before reporting):
using skyfactory 3.0.6
- Minecraft: 1.10.2
- Forge:
- Refined Storage:

Does this issue occur on a server? [yes/no]
nope
#### If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here]

**Comment by raoulvdberge** [comment]
I disagree. You can:
- Have multiple solderers for different parts
- In 1.11, multiple solderers can work together on the same recipe

**Comment by IamAlathe** [comment]
Also there are speed upgrades which help a lot. :)
