### ISSUE TITLE
Question: Refined Storage Systems... Exploding?

### ISSUE THREAD

**Issue by linktlh** [raoulvdberge/refinedstorage#1021]
#### Question
Randomly Random Refined Storage Systems are just disappearing when we aren't looking leaving a giant hole in the base I've seen it 4 times on our server... is this refined storage or is it something else happening?

Currently, It COULD be a griefer using a type of explosive that is placeable through FTB utilities protections but that's unlikely since 1 case was in an isolated area no one, (That I know of) had access to.
#### Steps to reproduce:
1. Unknown

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge: 12.18.3.2234
- Refined Storage: 1.2.22

Does this issue occur on a server? yes

#### If a (crash)log is relevant for this issue, link it here:
![2017-02-26_02 13 09](https://cloud.githubusercontent.com/assets/15271738/23338199/d22c56ac-fbc9-11e6-886b-b06ca67b07ae.png)
![2017-02-26_02 18 27](https://cloud.githubusercontent.com/assets/15271738/23338201/e49b3592-fbc9-11e6-92f5-1d5d9f3c3fe5.png)

can't find the other bases currently Sorry :(

This occurs on: Skyfactory 3 Version: 3.0.7 Relase

**Comment by raoulvdberge** [comment]
Impossible
