### ISSUE TITLE
Multiple sources won't work

### ISSUE THREAD

**Issue by Tenchu98** [raoulvdberge/refinedstorage#1022]
#### Issue description:
I have recipes setup to get a resource from multiple sources and it will only look at one of them. I have mystical agriculture and quantum quarry getting me :redstone essence, redstone ore, and redstone nether ore.

#### What happens: 
I setup autocrafting with block placers and breakers, as well as simple crafting the essence, and the system only looks at one of the recipe when auto crafting.

#### What you expected to happen: 
I would hope it would check one source, and if it's missing try the next and so on.

#### Steps to reproduce:
1. create autocrafting recipe for essence
2. create autocrafting using a block placer to place an ore, then a breaker to break the ore
3. try to request more redstone than a single source can supply, but all 3 could supply together.
...

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge:12.18.2.2185
- Refined Storage: 1.2.18

Does this issue occur on a server? [yes/no] yes

#### If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here]

**Comment by raoulvdberge** [comment]
Can you explain it in a bit less of an abstract/general way?

**Comment by Tenchu98** [comment]
Basically the system only checks one source type for a resource.
I have mystical agriculture gathering quartz essence, and a quantum quarry gathering nether quartz ore. If I have 30 ore, and enough essence to make 30 quartz, the system only sees 30 craftable quartz available.
I have a crafter feeding an actually additions block placer quartz ore, then a block breaker breaks it to gather the quartz. I can request 30 quartz, then wait for it to finish with that before requesting 30 more to get the 60, but this is a pain when you get into the thousands or want to autocracy something that tries to request more than a single source can produce.

**Comment by dmb1881** [comment]
@Tenchu98 would placing an autocrafting card in the crafter would perchance?

**Comment by Tenchu98** [comment]
I had a card for each source, but would have to do multiple smaller requests, and wait for the previous one to complete. I absolutely love this mod, it has helped automate so much stuff.

**Comment by itanshi** [comment]
Sounds like you'd benefit from the 'limiter' i forget what RS calls it. Let's you have X handy at all times.

**Comment by Tenchu98** [comment]
I don't understand how that would resolve this issue?

**Comment by itanshi** [comment]
Its a workaround, tbh

**Comment by Tenchu98** [comment]
I was doing that manually, until I tried to make a void miner.

**Comment by raoulvdberge** [comment]
Well, you're essentially expecting that RS predicts recipes. But this isn't possible. Closing.
