### ISSUE TITLE
Autocrafting crash on large (recursive) request.

### ISSUE THREAD

**Issue by jbmmhk** [raoulvdberge/refinedstorage#1024]
#### Issue description:
When auto crafting large/recursive requests such as Solar Flux panels or Mystical Crops, the game lags/eventually crashes. Seemingly similar to #902 and #838. 

#### What happens:
Crash with "java.lang.RuntimeException: Tried to read NBT tag that was too big; tried to allocate: 2097160bytes where max allowed: 2097152". Sometimes the game stops responding, other times it gives "Connection Lost. A fatal error has occurred, this connection is terminated". 

#### What you expected to happen:
Auto crafting to complete the requested item.

#### Steps to reproduce:
1. Create patterns to fully auto craft top tier solar panel from Solar Flux Reborn. (This also occurred when auto crafting mystical crops supremium.)
2. Request top tier solar panel.
3. Crash. 

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge: 12.18.3.2215
- Refined Storage: Initial crash happened with 1.2.18, upgrading to 1.2.22 did not resolve.

Does this issue occur on a server? Not tested, single player only. 

#### If a (crash)log is relevant for this issue, link it here:

http://pastebin.com/AQH5e0Mv

**Comment by raoulvdberge** [comment]
update hwyla
