### ISSUE TITLE
Items from full and semi-full disks not available

### ISSUE THREAD

**Issue by xeesus** [raoulvdberge/refinedstorage#1025]
#### Issue description:
I left my server running overnight with a quantum quarry's (from ExtraUtils2) output going into the RS system and cobblestone and dirt going into quantum storage units (from QuantumStorage) using external storage cables. Next day, I have my system only with possible crafting orders and dirt and cobble in it, all other items gone. Also, I was unable to either put or retrieve items to the system. I checked the disks, and their description said they had items in them, so I tried to put them in the disk manipulator, but it treated them like empty ones.
#### What happens:
Items disappeared, unable to use RS system.
#### What you expected to happen:
The opposite of that
#### Steps to reproduce:
¯\_(ツ)_/¯
The setup I had (quantum quarry + RS system) has been working perfectly before, so I have absolutely no idea why would the system break

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge: 1.10.2-12.18.3.2221
- Refined Storage: 1.2.22

Does this issue occur on a server? Yes

**Comment by raoulvdberge** [comment]
duplicate. #821

restore from backup
