### ISSUE TITLE
Rs wants to use multiple Master infusion crystals from mystical agriculture when crafting a high tier essence

### ISSUE THREAD

**Issue by dmb1881** [raoulvdberge/refinedstorage#1027]
#### Steps to reproduce:
1.setup crafter
2.put patterns with the master infusion crystal in there.
3.Try to craft a high tier essence (Such as supremium) or multiple intermidium essence.
...

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge: 12.18.3.2221
- Refined Storage: 1.2.21

Does this issue occur on a server? [yes/no]
I believe it will happen both on both singleplayer and multiplayer (It was on multiplayer when it did happen though)

**Comment by raoulvdberge** [comment]
use an oredict pattern
