### ISSUE TITLE
Crash After using custom resource pack, then switching back

### ISSUE THREAD

**Issue by 23Link89** [raoulvdberge/refinedstorage#1028]
#### Issue description: 
I installed a resource pack that didn't have any modding support which then after switching back to the default I get a crash

#### What happens: 
Whenever I load the world my game crashes

#### What you expected to happen: 
For my game to not crash

#### Steps to reproduce:
1. Install this resource pack: https://mods.curse.com/texture-packs/minecraft/r3d-craft-64px
2. Set your resource pack to this
3. Load up your world
4. Crash - After crash, if you switch back to default it won't fix it

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge: 12.18.3.2221
- Refined Storage: 1.2.22

Does this issue occur on a server? [yes/no]
Haven't checked

#### If a (crash)log is relevant for this issue, link it here: 

http://pastebin.com/vdS7n0mM

**Comment by raoulvdberge** [comment]
This looks like a Codechicken issue... Did you put a Reader/Writer in your world?

**Comment by covers1624** [comment]
Can we get some details on how to reliably reproduce this?
This has absolutely nothing to do with resource pack stuff, Seems its chunk loading related with WirelessRedstone and FMP.

**Comment by 23Link89** [comment]
@raoulvdberge Not sure I understand what you mean by "Reader/Writer" in your world. If it's a block from Refined Storage, then no. I have no blocks from Refined Storage placed.

@covers1624 I do have a few wireless redstone transmitters and receivers placed but thing is, I have a copy of the world before I ran the texture pack, and it runs like a dream. If you want I can send you a copy of my pack and world.

**Comment by raoulvdberge** [comment]
The stack trace shows that you have a BlockWriter in your world. BlockWriter is a block from Refined Storage.

**Comment by 23Link89** [comment]
@raoulvdberge Unless there's randomly generated BlockWriters, I don't have a block writer in my world.

**Comment by raoulvdberge** [comment]
Weird, then I wonder why that block appears in the stacktrace...

**Comment by raoulvdberge** [comment]
Please report this issue to MCMP. And do say that the reported block in the stacktrace is not present in your world.
