### ISSUE TITLE
Able to craft gold ingots out of iron blocks and iron ingots out of gold blocks

### ISSUE THREAD

**Issue by JaSpr** [raoulvdberge/refinedstorage#1029]
#### Issue description:
When crafting gold blocks into gold ingots, if you run out of gold blocks, it lets you use iron blocks instead.

#### What happens:
RS Crafting pattern defaults to a different type of block to fulfill its crafting requirements.

#### What you expected to happen:
If you don't have gold blocks, you don't get gold ingots

#### Steps to reproduce:
1. Craft gold block to gold ingot pattern with `Oredict` box checked.
2. Put pattern in crafter
3. Have lots of iron blocks in refined storage
4. Attempt to craft more gold ingots than you should be able to (e.g. if you only have 1 gold block, try to craft 10 gold ingots, and it will use the 1 gold, then pull in 1 iron block to compensate)

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge: 12.18.3.2234
- Refined Storage: 1.2.22

#### Example: 
Trying to craft 64 gold ingots when I only have 4 gold blocks, it pulls in another 4 iron blocks to complete the request:
http://i.imgur.com/IO2mXxq.png

**Comment by raoulvdberge** [comment]
are those oredict patterns?

**Comment by JaSpr** [comment]
Yes.  Both gold and iron blocks have oreDict name "blockMetal"

**Comment by raoulvdberge** [comment]
that would cause it yeah...

**Comment by raoulvdberge** [comment]
i don't think forge + vanilla do this. some other mod adds that oredict name i think

**Comment by JaSpr** [comment]
I think it might be Tinkers' Construct. Although we still might want to block such a generic ore dict entry.

**Comment by JaSpr** [comment]
https://github.com/SlimeKnights/TinkersConstruct/blob/f709f4085206c81d602f2f003b383db16163dc58/src/main/java/slimeknights/tconstruct/common/TinkerOredict.java
Lines 162-164

**Comment by raoulvdberge** [comment]
Interesting

**Comment by bonii-xx** [comment]
The issue here is that blockMetal is used,  when there is no blockMetal -> goldIngot recipe.
I assume you're using the oredictionary to automatically discover potential replacement blocks? Doing it like that is simply not supported by the oredictionary design, since it only states equality within one entry, but is not transitive via multiple entries. You'll run into a lot of trouble with Pam's if you're doing that ;o

**Comment by raoulvdberge** [comment]
This is no longer possible on RS for 1.11+, since we use the new MC ingredient system now instead of raw oredict. Only processing patterns still call oredictionary directly, as those a) have no ingredient system and b) don't matter, as you have to process it and get a result back yourself.
