### ISSUE TITLE
Crafting tasks not persisting when reloading world

### ISSUE THREAD

**Issue by dmb1881** [raoulvdberge/refinedstorage#1030]
#### Steps to reproduce:
1. Autocraft essence
2. Have low power
3. let network run out of power
...

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge:12.18.3.2221
- Refined Storage: 1.2.21

Does this issue occur on a server? [yes/no]
Yes the issue did happen on a server (Not sure if replicable on singleplayer)
#### If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here]

**Comment by raoulvdberge** [comment]
is the crafting task still active?

**Comment by dmb1881** [comment]
No it clears the crafting task.

**Comment by raoulvdberge** [comment]
Confirmed on 1.10.2
