### ISSUE TITLE
Autocrafting vanilla fireworks causes a crash

### ISSUE THREAD

**Issue by doidie** [raoulvdberge/refinedstorage#1031]
#### Issue description:
Set up autocrafting for vanilla fireworks, specifically just a piece of paper and a piece of gunpowder. I set up an exporter for fireworks with a crafting card on a weather obelisk.
#### What happens:
Minecraft crashes.
#### What you expected to happen:
The weather obelisk to fill with fireworks.
#### Steps to reproduce:
1. Set up autocrafting for fireworks (specifically 1 paper and 1 gunpowder)
2. Set up exporter to export them
3. Add crafting card
4. Fill weather obelisk

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge: 12.18.3.2185
- Refined Storage: 1.2.22

Does this issue occur on a server? [yes/no]
No
#### If a (crash)log is relevant for this issue, link it here:

http://pastebin.com/UP3YBpb0

**Comment by doidie** [comment]
#### UPDATE
I deleted the blocks with MCedit however when I set this up again it continues to crash. In a different world with the same mode pack I am not able to duplicate this bug.

When i try to request autocrafting fireworks through the grid I hit start then the start button just greys out and nothing happens.

**Comment by raoulvdberge** [comment]
Cannot reproduce in 1.12, works fine for me

![x](https://raoulvdberge.com/sOBGq7)
