### ISSUE TITLE
Core does not accept power from Mekanism

### ISSUE THREAD

**Issue by JacobMuken** [raoulvdberge/refinedstorage#1032]
#### Issue description:
Core does not accept power from Mekanism's Universal Cables.
#### What happens:
Nothing
#### What you expected to happen:
Something
#### Steps to reproduce:
1. Put down a core
2. Put down a power source
3. Connect with a Universal Cable
4. Pat yourself on the back for a job well done

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge: 12.18.3.2239
- Refined Storage: 1.2.22

Does this issue occur on a server? [no]

#### Extra Notes

The cable physically connects to the core and power flows into the cable, but nothing enters the core.

**Comment by raoulvdberge** [comment]
mekanism bug
