### ISSUE TITLE
Machines do not function. (Issue #104).

### ISSUE THREAD

**Issue by xChitose** [raoulvdberge/refinedstorage#1036]
As referenced in Issue #104, running Refined Storage 1.2.22 for MC 1.10.2, and essentially, I came back from the nether and every machine, cable, exporter, etc, we're not working, and the toggle redstone buttons, or any of the buttons, also weren't working. <br /><br />The controller sees all of the items connected, and I even tried to break / replace the controller, but everything else on the network still didn't function.<br /><br />Edit: A tedious workaround was to leave and reenter world, and toggle the redstone buttons on the machines that didn't respond.

Edit: Ghost clicking the buttons when they were unresponsive seems to make them trigger randomly once you reenter the world.

**Comment by raoulvdberge** [comment]
Duplicate
