### ISSUE TITLE
Single player: "a fatal error has occurred, this connection is terminated" opening disk drive

### ISSUE THREAD

**Issue by Insight1400** [raoulvdberge/refinedstorage#1037]
#### Steps to reproduce:
1. Fill refined storage with a lot of stuff
2. Have creepers blow up your drive with disks
3. Put disks back into a new disk drive
4. Open disk drive
...

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge: 12.18.3.2215
- Refined Storage: 1.2.18

Does this issue occur on a server? [yes/no] No

#### If a (crash)log is relevant for this issue, link it here:
http://pastebin.com/Gcm8yVZQ

[pastebin/gist/etc link here]

**Comment by raoulvdberge** [comment]
"This is a private paste. If you created this paste, please login to view it."

**Comment by Insight1400** [comment]
Sorry, i changed, now it's public

**Comment by raoulvdberge** [comment]
I need the crashlog of the server, not your FML clientside log. It tells me nothing, only the fact that you were kicked from the game.

**Comment by Insight1400** [comment]
I'm not very familiar with it. I play in a single player world and I have no crash report. Only the message "fatal error has occurred ecc". After that sends me to the multiplayer menu. Sorry again, I may not get something

**Comment by raoulvdberge** [comment]
Then i can't do much.

**Comment by raoulvdberge** [comment]
Try updating HWYLA if you have it installed. There is not much I can do, because I don't have the crashreport.
