### ISSUE TITLE
[documentation] emphathise chunckloaders

### ISSUE THREAD

**Issue by Quezler** [raoulvdberge/refinedstorage#1038]
#### Issue description:

Its not 100% obvious that you need both the network transmitter and receiver chunckloaded while setting up the link.

#### What happens:

Receiver does not glow.

#### What you expected to happen:

Receiver glowing.

#### Steps to reproduce:
1. Attempt to link to a receiver while the receiver is not loaded

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge: latest
- Refined Storage: latest

Does this issue occur on a server? [**yes**/no]

#### Suggested fix:

Empathize on [this page](https://refinedstorage.raoulvdberge.com/wiki/networks-over-long-distances) that both need to be chunkloaded during pairing, as well as normal during use, as currently it can be confused that linking will work regardless (since the card has the coords and the network transmitter shows that is has connected to the receiving dimension successfully)

**Comment by raoulvdberge** [comment]
![x](https://raoulvdberge.com/eLPzw4)

**Comment by Quezler** [comment]
That is literally the line i meant was incomplete.

Normal people will read that that is for normal operation, not including the linking procedure.

**Comment by raoulvdberge** [comment]
Changed!

**Comment by Quezler** [comment]
👍
