### ISSUE TITLE
many Lags after connecting my RS-System to a Colosal-Chest

### ISSUE THREAD

**Issue by Curse187** [raoulvdberge/refinedstorage#1039]
#### Issue description:
Lags after connecting my RS-system to a   ##colosal-chest
#### What happens:
s.a.
#### Steps to reproduce:
1. I connect a colosal-chest to my system with an external storage bus.
2.
3.
...

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge: 12.18.2234
- Refined Storage: 1.2.22

Does this issue occur on a server? [yes/no]
no
#### If a (crash)log is relevant for this issue, link it here:

[stall-2017-03-06_18.13.02-2.txt](https://github.com/raoulvdberge/refinedstorage/files/821939/stall-2017-03-06_18.13.02-2.txt)
[crash-2017-03-06_17.54.48-client.txt](https://github.com/raoulvdberge/refinedstorage/files/821941/crash-2017-03-06_17.54.48-client.txt)

**Comment by raoulvdberge** [comment]
https://refinedstorage.raoulvdberge.com/wiki/profiling

**Comment by Curse187** [comment]
i hope this helps.

[Uploading report.zip…]()

**Comment by Curse187** [comment]
damn -_- wrong button sorry

**Comment by raoulvdberge** [comment]
And you're saying the lag starts just *after* connecting the Collosal Chest? There is *NO* lag before that?

**Comment by Curse187** [comment]
Yes i mean that. The more stuff is stored in the chest, the slower is my RS-system. btw. the chest is only 1% full.
Now I can't even more craft a couple Stacks of compressed cobblestone, without getting minecraft to freeze.

**Comment by raoulvdberge** [comment]
Do you have Common Capabilities installed?

**Comment by Curse187** [comment]
Yes, not by hand but it's in the modpack.

**Comment by raoulvdberge** [comment]
It looks like it isn't detecting Collosal Chests.

**Comment by raoulvdberge** [comment]
@Curse187 Don't connect the External Storage to the "Collosal Chest Interface", but to the "Collosal Chest Core".
