### ISSUE TITLE
Detectors not give off redstone signal to craft item if it is part of another items recipe

### ISSUE THREAD

**Issue by GenSmicer** [raoulvdberge/refinedstorage#1047]
Issue description: Detector not recognise item being crafted if it's not the direct recipe that is requested. It works when crafting the component straight away, but when doing the recipe where components need to meet, it not crafts components that are put behind a detector. 

 What happens:

So I set up a bunch of Detectors for each of the Crystal variants(Palis, Restonia, Void, Diamante, any of the Atomic recipe's really) that Actually additions can make through the Atomic Reconstructor. I have a redstone torch that will get deactivated as soon as the detectors give off a signal. This saves power since otherwise the Reconstructor would just keep running.

If I request these crystals alone, there's no problem, but once I need to make a block of the variant, it not gives out a redstone signal and just keeps waiting until the crystals are made, which never happens since it not gives the signal for the atomic Reconstructor to activate. So it just drops the items and then the items just sit there waiting to be beamed into shape. 

What you expected to happen:

That no matter what recipe I issue from the system it gives off a redstone signal as soon as it needs to craft items that the detectors are setup for. Even if they are component parts for some bigger recipe.

Steps to reproduce:

1. Make a recipe for a crystal of Actually addition (all of them can be made in block form too) with the processing pattern encoder and then a normal recipe for the block version of said crystal and put them in a crafter(WEll block version recipe can go anywhere since it not needs to be made from the processing pattern Encoder) that is above a dropper like block(I used the automatic Precision dropper of Actually Additions since it not needs any signal to drop stuff, and since the exporter will only export when item is crafted, it not really matters) and place it in a position where the beam of the Atomic reconstructor will go over them.
2. place down a detector that is set to the mode when item is autocrafted to put out a signal
3. Request the block item and then wait for it to be done, which will likely be never. 
...

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge: 12.18.3.2239
- Refined Storage: 1.2.22

Does this issue occur on a server? yes

**Comment by way2muchnoise** [comment]
Just use a pressure plate and put the AA reconstructor in pulse mode. The whole point of detectors is to keep track of a certain amount in the system.

**Comment by raoulvdberge** [comment]
Intended behavior.

**Comment by GenSmicer** [comment]
Well then why it gives no autocraft signal when it is autocrafted as part of another recipe then? Isn't that supposed to be considered as autocrafting too then? It works normally if the item directly is crafted, yet as part of a component it not does it, while that is also considered autocrafting hen right?

**Comment by raoulvdberge** [comment]
It only cares about the root tasks, not child elements.

**Comment by rawuza** [comment]
I just stumbled across the same bug. I tried to use it for autcrafting with Actually Additions infuson, for which I need to know which item is currently crafting. But this is not possible because of this bug.

What's the actual use case then, if it only works for the root task?

**Comment by raoulvdberge** [comment]
Subtasks did not seem significant enough for me at first. But thinking about it now, I can probably make this configurable.

**Comment by raoulvdberge** [comment]
Not gonna make it configurable anymore.
