### ISSUE TITLE
[1.11.2] Drives randomly disappearing from Disk Drive

### ISSUE THREAD

**Issue by CadevsGaming** [raoulvdberge/refinedstorage#1049]
I'm playing on an SMP with about 30 mods with some friends, and when we updated to Refined Storage 1.4. Some people will just randomly lose there drives in there disk drive. The disk drive itself stays, just the items completely vanish.

Can't figure out how to reproduce it.

- Minecraft: 1.11.2
- Forge: forge-13.20.0.2226
- Refined Storage: 1.4

Does this issue occur on a server? Yes

**Comment by raoulvdberge** [comment]
duplicate
