### ISSUE TITLE
External storage power counting compacting drawers as three drawers

### ISSUE THREAD

**Issue by RealGrep** [raoulvdberge/refinedstorage#105]
My power draw just shot through the roof as I added an external storage block to my drawer controller. It has 17 drawers, which should be 34 RF/t, which is reasonable. However, it's drawing 70 RF/t. I believe the compacting drawers are being counted as three, though not sure if this is even fixable (or unintended).

I have 8 x single drawers, and 9 x compacting drawers. Seems to be working out like this:

(8 + 9x3) * 2 RF/t = 35 * 2 RF/t = 70 RF/t.

Would obviously be far happier if it counted drawers with multiple slots or compacting drawers as one drawer, as I'd expect. Large drawer arrays using other than single item drawers will draw a quite disproportionate amount of energy, making them barely worth it, if at all.

**Comment by raoulvdberge** [comment]
Not much I can do about that, drawer controllers are IDrawerGroup's and compacting drawers are being counted as IDrawerGroup's as well, can't detect if it's a compacting drawer.

Do you have a better idea for the RF/t math?

**Comment by RealGrep** [comment]
Yeah, thought that might be the case. Nothing really comes to mind, though 70 is pretty high for a modest drawer setup like this. Hm. Other than a flat reduction, like making it 1 RF/t or something, I don't really have any brilliant ideas. heh

**Comment by RealGrep** [comment]
Could also, if a drawer controller is detected, use some higher flat amount of RF/t. That's about all I've got, at the moment. I'll pipe in if I think of something I like.

**Comment by raoulvdberge** [comment]
I'll just let it use 1 RF/t instead of 2 RF/t..
