### ISSUE TITLE
"Wirless" crafting grid won't sync

### ISSUE THREAD

**Issue by eslachance** [raoulvdberge/refinedstorage#1051]
#### Issue description:
The Wireless Crafting Grid (in-game called "Wirless" with a typo) will not sync with the controller. 

#### What happens:
Shift+right-clicking on the controller does nothing. Crafting the wireless crafting grid with an already synced Wireless Grid removes the sync.

#### What you expected to happen:
Shift+right-clicking on the controller would sync it to that network.

#### Steps to reproduce:
1. Craft "Wirless Crafting Grid" (#9621/0)
2. Shift+Right-Click on Controller
3. Try to right-click grid

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge: 12.18.3.2254
- Refined Storage: 1.2.22

Does this issue occur on a server? Yes. 
Modpack Used: FTB Beyond (1.0.1)

#### If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here]

**Comment by VT-14** [comment]
I'm 90% certain Refined Storage doesn't have, nor will ever add, a Wireless Crafting Grid.  It does have a Wireless Grid, and a Wireless Crafting Monitor.  However, a "Wirless Crafting Grid" is almost certainly from some other mod and you will need to report to them.  You may also want to mention this on the FTB Beyond issue tracker.

Both RS and AE2 have always been against adding wireless access devices with built in crafting grids.  AE2 says it undermines the auto-crafting portion of the mod.  I think RS's view is fairly similar, though I haven't seen the exact statement from Raoulvdberg.

**Comment by raoulvdberge** [comment]
This is not an item added by RS...

**Comment by eslachance** [comment]
Oh would you look at that, it is indeed another mod that I hadn't seen before added to FTB Beyond. Apologies for the bother!

**Comment by Volondil** [comment]
To link the "Wirless crafting grid", i tryed to shift+right-click on my crafting grid, not on the controller and it worked well (The tooltip say that this item come from refined storage, not other mod).
