### ISSUE TITLE
Single item crafting (feature request)

### ISSUE THREAD

**Issue by Zimon88** [raoulvdberge/refinedstorage#1052]
#### Issue description:
When requesting multiple items of same type, and inventory can accept it from craffter (ex. chest), all items for all requested item are pushed if available in system. 

#### What happens:
Some machines can craft only one item per time, but have more items slots in inventory and this broke recipe for crafting, or buffor is required before crafting ex: Runic Altar from Botania or items need to be split through few inventories (ex. Fusion Crafting from Draconic evolution or Empowerment from Actaully Additions)

#### What you expected to happen:
Option in crafter or module for crafter that allow single item craft when multiple of them is requested.
Items for next operation are pushed when previous crafting is done and crafted item is in system.

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge: 12.18.3.2254
- Refined Storage: 1.2.22

Does this issue occur on a server? [yes/no] yes

**Comment by raoulvdberge** [comment]
already in 1.11. might get on 1.10 eventually
