### ISSUE TITLE
Redstone signal to craft

### ISSUE THREAD

**Issue by MrOysterMeister** [raoulvdberge/refinedstorage#1053]
I would like to emit a redstone signal to start an external crafting process.
Is this possible at the moment? I cannot find a way to tell the system to emit a signal to craft.

**Comment by way2muchnoise** [comment]
You could use a crafter to insert some signal item i guess? Eg. 1 cobble -> x of external craft

**Comment by raoulvdberge** [comment]
use the "trigger autocrafting on redstone signal" option
