### ISSUE TITLE
(suggestion, for 1.11.2 and 1.10.2,please!) add a restriction upgrade/option

### ISSUE THREAD

**Issue by NarigudoBR** [raoulvdberge/refinedstorage#1054]
#the thing is, when you try to do something like this: https://www.youtube.com/watch?v=TFcFD54RwwI ; you end up with a loop, because the invenotry that you are trying to fill is providing to itself.So, to fix this, it would be nice to have a restriction upgrade/option that allow us to put rules in a rs device/bus ex.: only crafting/storage/both  allowed.

**Comment by raoulvdberge** [comment]
No
