### ISSUE TITLE
Feature Request - Single Crafting upgrade

### ISSUE THREAD

**Issue by miksbricks** [raoulvdberge/refinedstorage#1060]
What it says - upgrade that when multiples of an item are requested the system waits for one to complete before attempting the next. An example use would be with Botania's rune crafting. If 500 of a rune is requested it would supply items for one then wait for that to be returned to the system before supplying items for the second. 

Another use case would be with tiered items such as vibrant alloy from EnderIO. Request 64 vibrant alloy. One energetic alloy is smelted then one vibrant alloy is started. Second energetic alloy is not started until the first vibrant is in the system. This would supply a smaller number of items back to user even though the full craft might take longer.

**Comment by raoulvdberge** [comment]
already in 1.11 might get backported to 1.10
