### ISSUE TITLE
[Request] Quartz enriched iron Block

### ISSUE THREAD

**Issue by JaSpr** [raoulvdberge/refinedstorage#1061]
#### Issue description: 
Request for QEI ingots to be craftable into QEI Block, for better storage

**Comment by raoulvdberge** [comment]
Already exists

**Comment by JaSpr** [comment]
Oh cool. I see this was added on 23 January.  We're running 1.2.22 (released 19 Feb), which doesn't include that block.  Is the QEI block going to be released with 1.4?

**Comment by raoulvdberge** [comment]
Maybe, there are loads of features to backport to 1.10.

**Comment by JaSpr** [comment]
thanks
