### ISSUE TITLE
Feature Request: Crafting Patterns in loot tables

### ISSUE THREAD

**Issue by miksbricks** [raoulvdberge/refinedstorage#1062]
One balance issue is that auto-crafting is relatively easy and removes incentive to explore. By removing the crafting recipe and making the patterns only available via loot tables it would force exploration and make RS a better fit for exploration centered mod packs. Would obviously need to be done via config so it could be disabled on packs where exploration isn't the focus.

**Comment by way2muchnoise** [comment]
All of that can be done by a pack author, doesn't seem like something we should add imo.

**Comment by raoulvdberge** [comment]
Agreed.
