### ISSUE TITLE
Importer break

### ISSUE THREAD

**Issue by Ravix-** [raoulvdberge/refinedstorage#1064]
**Issue description:**

Occasionally the importers that I have placed on various blocks, Alloy Smelters/Ender chests/etc, will all stop working.  I have to break and replace them if i want them to work again.

**What happens:**

Importers occasionally stop functioning.

**What you expected to happen:**

Importers that don't need to be replaced.

**Steps to reproduce:**

Make importers

Place them on a block

Wait until they stop working

Replace and they work again

**Version (Make sure you are on the latest version before reporting - Did this):**

Minecraft: 1.10.2
Forge: 12.18.3.2215
Refined Storage: 1.2.23
Does this issue occur on a server? [yes]

If a (crash)log is relevant for this issue, link it here:

**Comment by Ravix-** [comment]
Didn't see the other one, would you mind linking the issue #?

**Comment by way2muchnoise** [comment]
The fix involves a rather large rewrite that happened in the 1.11 branch. But see #370

**Comment by Ravix-** [comment]
Will there be any chance of it being fixed for 1.10.2 beyond?
