### ISSUE TITLE
Refined storage importer and exporter dont work any more after returning (or while beeing) in another dimension (Nether and deep dark tried).

### ISSUE THREAD

**Issue by DietmarKrause** [raoulvdberge/refinedstorage#1065]
#### Issue description:
Refined storage importer and exporter dont work any more after returning (or while beeing) in another dimension (Nether and deep dark tried). After returning you have to brake and rebuild importer and exporter or better yet leave and restart world. After restarting everything wors again. Tested in Single player. Base with refined storage is chunc loaded via FTB chunkloader. So is Nether and Deep Dark. 
#### What happens:
Importer and Exporter dont work. You can access the grid normally
#### What you expected to happen:
Importer and Exporter should work after returning from another dimension
#### Steps to reproduce:
1.
2.
3.
...

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge: 12.18.3.2239
- Refined Storage: refinedstorage-1.2.22

Does this issue occur on a server? [yes/no]
Not tested
#### If a (crash)log is relevant for this issue, link it here:
no crash
[pastebin/gist/etc link here]

**Comment by raoulvdberge** [comment]
did you even read previous closed issues befoer making a new one?

**Comment by way2muchnoise** [comment]
The fix involves a rather large rewrite that happened in the 1.11 branch. But see #370

**Comment by raoulvdberge** [comment]
Cool, the fix will most likely not end up in 1.10.2 anymore.
