### ISSUE TITLE
Item duplication while dragging multiple items into crafting grid.

### ISSUE THREAD

**Issue by Renari** [raoulvdberge/refinedstorage#1067]
The issue can be seen here: https://my.mixtape.moe/hoaegw.mp4

In the above link we start with 66 silver, I then drag a stack of silver to evenly distribute them across the crafting grid to make a block. However when I remove the block from the crafting grid no items get consumed and I get +9 silver leaving me at 75.

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge: 12.18.3.2239
- Refined Storage: 1.2.21 (this isn't the latest version but the patch notes don't mention this anywhere, I'll do an update later tonight/tomorrow to see if this is resolved in 22 or 23)

Does this issue occur on a server? [yes]

**Comment by way2muchnoise** [comment]
Is this a public mod pack? Or any other mods that can interfere with it, in other words does this happen in like a tinkers table or so?

**Comment by raoulvdberge** [comment]
I'm 99% sure this is an issue with the recipe / other mods interfering. From which mod is this silver?

**Comment by Renari** [comment]
> I'm 99% sure this is an issue with the recipe / other mods interfering. From which mod is this silver?
There's a number of mods that add silver, the ingot is from Thermal Foundation. However it appears the block is from ProjectRed Exploration.
> Is this a public mod pack? Or any other mods that can interfere with it, in other words does this happen in like a tinkers table or so?
This is a private pack for >10 people. I tried this in a Tinker's Construct table and it crashed the client. That crash log can be found [here](https://openeye.openmods.info/crashes/e7b6d372ff6c1a4364d857484964f7e2) however I don't believe this to be a mantle issue as the stack trace implies. I don't believe this is a refined storage issue either.

**Comment by Renari** [comment]
This appears to be a problem with project red. It seems the mod registers a number of block forms of the ores it adds. JEI lists no recipe for these blocks however trying to craft them the usual way appears to work. All crafting tables actually crash the recipe however Refined Storage seems to make the resulting item without using resources instead.
