### ISSUE TITLE
suggestion for a pattern comprassor

### ISSUE THREAD

**Issue by TY-Logic** [raoulvdberge/refinedstorage#1069]
#### Issue description:
using patterns to automate tasks on the go is all well and nice, but not an option if i want it to just do it regularly non stop. unless i missed some something of course.

#### What happens:
 in modded minecraft sometimes you can collect too many items. 10k - 100k of the same item and more (e.g. sky factory 3). unless i use an automated crafter of a different mod with an import/export system its not possible. having 999 redstone or 111 redstone blocks can make a difference in storage. 

#### What you expected to happen:
i don't expect anything :). this is a suggestion from something i had personal issue with.

i would suggest maybe adding a "pattern comprassor" to be added to this mod thats all about storing items. a comprasor thats all about using patterns the player decides in order to get and control what he wants instead of using the help of other mods. maybe implement some of the upgrades to it too.

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge: 12.18.3.2254
- Refined Storage: 1.2.22

Does this issue occur on a server? no

#### If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here]

**Comment by raoulvdberge** [comment]
nah
