### ISSUE TITLE
Fluid autocrafting

### ISSUE THREAD

**Issue by MrOysterMeister** [raoulvdberge/refinedstorage#1071]
With TE now available on 1.10.2 it would be great if autocrafting of liquids was possible. 
For example the signalum recipe requires a bucket of destabilized redstone. 
At the moment it does not seem possible to create a recipe for 1000mb of destabilized redstone. If I add a recipe : 10 redstone -> 1 bucket of destabilized redstone in the magma crucible and send the output to fluid storage the crafting request will stop and wait for the bucket.
If no crafting recipe is available but 1000mb is stored in the system the crafting of signalum will work.

I see two ways this could be improved.
1) Crafting of fluids. Add the possibility to create recipes for fluids, e.g. 10 redstone -> 1000mb of destabilized redstone. This could then be used with other crafting as a fluid from storage.
2) Use buckets. Keep the pattern model as it is now, but integrate pulling from fluid storage in the middle in a crafting request. The pattern would then be : 10 redstone -> bucket of destabilized redstone.

**Comment by raoulvdberge** [comment]
duplicate #461
