### ISSUE TITLE
Feature Request: Processing Crafter Single Craft & Redstone Pulse

### ISSUE THREAD

**Issue by drrk** [raoulvdberge/refinedstorage#1072]
Hi,  It would be pretty cool if processing patterns could be setup to work one craft at a time, and to emit a redstone pulse from the crafter when they start to process.  This would make a lot of crafts considerable more automatable.

**Comment by raoulvdberge** [comment]
already in 1.11. might get backported at some time. also PLEASE read previous (closed) issues before reporting anything -.-.

**Comment by drrk** [comment]
Apologies, the blocking pattern does exist, I didn't see that when I looked, however the other part of my request doesn't seem to exist, where the crafter will give out a redstone pulse when it wants the craft to start.

Thanks

**Comment by raoulvdberge** [comment]
that is too specific for a feature in RS. you can detect when a craft starts by using a comparator on a chest or machine and seeing if items are inserted (by connecting the crafter to said chest or machine)
