### ISSUE TITLE
Extra Utilities Golden lasso

### ISSUE THREAD

**Issue by Daihok41** [raoulvdberge/refinedstorage#1073]
#### Steps to reproduce:
1.
2.
3.
...

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge:
- Refined Storage:

Does this issue occur on a server? [yes/no]

#### If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here]

**Comment by raoulvdberge** [comment]
duplicate of #649
