### ISSUE TITLE
[1.10.2 - Beyond] Opinium (Pathetic) [Red Coal] Extra Utilities 2

### ISSUE THREAD

**Issue by Ravix-** [raoulvdberge/refinedstorage#1074]
#### Issue description:
Trying to autocraft  Opinum cores, i have 100k+ red coal in my storage but when i go to autocraft it tells me that I still need more.  Ctrl+Shift forcing the craft still does not allow it to craft.  

I have tried both Oredict/non Oredict and the same result occurs.  I can craft the item manually in the crafting grid without an issue.
#### What happens:
Won't autocraft Opinium (Pathetic) out of Red Coal
#### What you expected to happen:
It to accept the Red Coal and autocraft.
#### Steps to reproduce:
1. Get a bunch of red coal
2. Make a pattern for Opinium (Pathetic)
3. Try to autocraft it
...

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Beyond: 1.1 (Release)

Does this issue occur on a server? [yes/no]
Yes
#### If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here]

**Comment by raoulvdberge** [comment]
Does this need XP to craft?

**Comment by kimeradelf** [comment]
Remake the pattern with a red coal you have created as a product and it should work. 
I had that problem by importing the recipe for red coal from JEI, the item and the crafting pattern were reconize as diferents stacks.

**Comment by raoulvdberge** [comment]
There you go!
