### ISSUE TITLE
[1.10.2] Weird interaction with Storage Drawers

### ISSUE THREAD

**Issue by SnowShock35** [raoulvdberge/refinedstorage#1076]
#### What happens:

When connecting to Storage Drawers that have void upgrades using an external storage bus, that's set on a higher priority than disk drives, the drawer will full up and then instead of continuing to fill the drawers and just void the excess it starts filling the drives on the system leading to filling the drives with unwanted items.

#### What you expected to happen:

The items should not reach the disk drives and should always be pushed through the highest priority first. Therefore, letting the items get voided

#### Steps to reproduce:
1. Connect RS system to storage drawer (with void upgrade) via external storage and set the priority higher than your disk drives
2. have items input into the system either using interface/importer with 3 speed upgrades and 1 stack upgrade
3. wait until the drawer fills up and wait for it to overfill (Could be chunks loading/unloading causing the issue)
4. #blameEllpeck
...

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge: 12.18.3.2254
- Refined Storage: 1.2.23 

Does this issue occur on a server? [yes/no]

Yes, the issue is occurring server side, have yet to test single player.

#### If a (crash)log is relevant for this issue, link it here:

**Comment by raoulvdberge** [comment]
I can't reproduce this:

![x](https://raoulvdberge.com/NyeG0j)

**Comment by SnowShock35** [comment]
@raoulvdberge You're not adding them quick enough, therefore it's not technically a accurate reproduction of the issue

**Comment by SnowShock35** [comment]
Lemme see if I can't video it

**Comment by SnowShock35** [comment]
@raoulvdberge So, it seems the bug occurs when the loading of the chunks happens. e.g. server restart or world load the import busses are either being loaded before or priorities are being loaded later than the busses

**Comment by raoulvdberge** [comment]
It might be possible that the Drawers aren't loaded yet at that point. Not much I can do about that then, just specify a blacklist on your Disk Drive in that case.

**Comment by SnowShock35** [comment]
Is there no way around that? Like even from @jaquadro 's side of things?
