### ISSUE TITLE
Tesselating block in world Clint crash

### ISSUE THREAD

**Issue by IchigoGames** [raoulvdberge/refinedstorage#1077]
#### Issue description:
Crash On Joining server and loading chunk

#### What happens:
Clint of player crash

#### What you expected to happen:
for the player not to crash

#### Steps to reproduce:
1.not sure how to reproduce
2.
3.
...

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.11.2
- Forge:2255
- Refined Storage:-1.4.1

Does this issue occur on a server? [yes/no]
Yes

#### If a (crash)log is relevant for this issue, link it here:

http://pastebin.com/3Qm69JEH

**Comment by micheldewit** [comment]
This issue is being persistent in older versions, however, not in the build version from Github (1.4.2). 
Could version 1.4.2 be pushed to Curse, in order to fix the issue?

**Comment by raoulvdberge** [comment]
1.4.2 is not ready yet
