### ISSUE TITLE
Storage disk won't empty completely (or at least showing a buggy amount)

### ISSUE THREAD

**Issue by Ravix-** [raoulvdberge/refinedstorage#1078]
#### Issue description:
Storage disk shows a postive (or negative) number after using the disk manipulator to sort it back into the system 
#### What happens:
Setting disk manipulator to insert items to system causes disks to show random numbers upon completion (3 speed, 1 stack).
#### What you expected to happen:
All items to go into system and disk to read 0 items left.
#### Steps to reproduce:
1. Take disk with items
2. Place in Disk Manipulator
3. Watch disk numbers upon completion
...

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- FTB Beyond
- Refined Storage: 1.2.23

Does this issue occur on a server? [yes/no]
Yes
#### If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here]

**Comment by raoulvdberge** [comment]
Duplicate #520
