### ISSUE TITLE
Destructor + Dimensional Shard Ore server corruption

### ISSUE THREAD

**Issue by Ravix-** [raoulvdberge/refinedstorage#1079]
#### Issue description:
Destructor + Refined Storage block "Destructor" have a bad interaction that causes a server crash.
#### What happens:
When you place a destructor facing a Dimensional Shard Ore block it crashes and prevents the server from rebooting, mandating a backup.
#### What you expected to happen:
It to destroy the block and collect the drops, not crash the server.
#### Steps to reproduce:
1. Place Dimensional Shard Ore
2. Place Destructor, connected to RS system, on space where Ore is
3. Watch your server crash and need a backup
...

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Refined Storage: 1.2.23

Does this issue occur on a server? [yes/no]
Yes
#### If a (crash)log is relevant for this issue, link it here:

http://pastebin.com/1mvtz1K0

**Comment by raoulvdberge** [comment]
Where is your crashreport?

**Comment by Ravix-** [comment]
Updated post w/ crashlog.  

Looks like it was: Name: refinedstorage:destructor // com.raoulvdberge.refinedstorage.tile.TileDestructo

**Comment by raoulvdberge** [comment]
It seems like this is an FTB Utilities issue. Please report it to them.

**Comment by Ravix-** [comment]
Roger.
