### ISSUE TITLE
Right click in grid search field should clear contents of field

### ISSUE THREAD

**Issue by RealGrep** [raoulvdberge/refinedstorage#108]
Hope you don't mind this small flurry of PRs. :)

I'm very used to being able to right click in a search field to clear the field contents, as are most people. And it would sure be nicer than hitting backspace a bunch of times. Small thing that would really improve usability.

Thanks! Having much fun automating things right now.

**Comment by raoulvdberge** [comment]
Do you want it to focus / select again when doing right  click, or just remove stuff? Maybe only select in autoselected mode?

**Comment by RealGrep** [comment]
Hm, I guess I'd expect it to select the field if it isn't already as well as clear it. Typical workflow would be you searched for something, now you want to find something else, so you right click it and start typing again.
