### ISSUE TITLE
Server Crash with External Storage and Drying Basin

### ISSUE THREAD

**Issue by AshIndigo** [raoulvdberge/refinedstorage#1083]
#### Issue description:
Placing an external storage on a Integrated Dynamics Drying basin crashes the server and if the chunk is loaded it will crash the server again.
#### What happens:
I attached an external storage to the basin with a simple network.
#### What you expected to happen:
The empty inventory to be read or nothing to actually happen.
#### Steps to reproduce:
1. Place down a creative controller, grid, and Drying Basin
2. Connect an external storage to the basin
3. Crash

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge: 12.18.3.2239
- Refined Storage: 1.2.22

Does this issue occur on a server? Yes

#### If a (crash)log is relevant for this issue, link it here:

http://pastebin.com/7Rn6c5UA

**Comment by raoulvdberge** [comment]
This is a problem with the Cyclops integration code. But I removed support for the Cyclops integration, so this issue is no longer relevant.
