### ISSUE TITLE
Lag just having installed

### ISSUE THREAD

**Issue by ecoay** [raoulvdberge/refinedstorage#1084]
I saw a spotlight and decided to use refined storage in my modpack instead of AE2. I uninstalled AE2 and AE2 stuff and installed refined storage. I created a new world to test the balance etc. Every 5 seconds i began to lock up or freeze without even placing a single block. I checked my mem and cpu usage and it has mem using 6gb of my total 4gb allocated and CPU approaching 90%.  I rebooted and double checked all configs and repaired mine craft install etc. Still the same thing happened.  I downloaded all the mods directly then launched multimc instead of curse and self installed 1 by 1 and again same thing happened.

I uninstalled refined storage and reinstalled AE2 and AE2 Stuff and sit about 2.3 out or 4gb allocated again with no stuttering or peak usage moments, even when fully utilizing the blocks.

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge: 12.18.3.2254
- Refined Storage: 1.2.24

Does this issue occur on a server? [yes/no]

#### If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here]

**Comment by raoulvdberge** [comment]
https://refinedstorage.raoulvdberge.com/wiki/profiling

**Comment by ecoay** [comment]
https://www.dropbox.com/s/y07rtxwofcqyrik/testcopy.nps?dl=0
https://www.dropbox.com/s/9vvk7nlc67wtoi2/startup.nps?dl=0

watchdog generated tons of stall reports while I was attempting to play.

**Comment by ecoay** [comment]
So I decided "Hey I have a bunch of custom json and cfg files running with ae2 loot tables and while I opened all config and json files in modpack with notepad+ to search for anything lingering from ae2... I figured I could have missed something."  So I decided that this may not be installing refined storage as the issue but the removal of ae2 being the issue. I decided to test this theory by running neither mod. As soon as I removed refined storage everything ran with no problems.

**Comment by ktole1999** [comment]
and you have the issues with only these mods installed?

Minecraft: 1.10.2
Forge: 12.18.3.2254
Refined Storage: 1.2.24

**Comment by ecoay** [comment]
Nope just tested that. No issues at all with only refined storage. Something in the modpack doesnt play well with it and I wish there was an easy way to tell what that is.

**Comment by way2muchnoise** [comment]
Well there kinda is, just remove half the mods and see if it still is there. That way you can eliminate half the mods each iteration.

**Comment by SubsterNL** [comment]
RS is definitely causing massive TPS increase and lag. Reproduction is easy. Start a somewhat larger crafting task and look at tps via /cofh tps. Bumps to 80 tps etc. 

As soon as the task is cancelled, the lag goes away. This is not another mods fault. It's been a problem with RS for a long time. 

Asking people to remove all mods is just silly. Talk to the modpack owners and ask them to remove RS from them then.

**Comment by raoulvdberge** [comment]
@SubsterNL Please don't be an idiot here. This issue is not about autocrafting lag, it's about general idle lag. Two different things. Also, I didn't have time to look at this specific issue because I'm on a goddamn vacation.

**Comment by SubsterNL** [comment]
Nice attitude but enjoy your vacation

**Comment by BrianEdmonds** [comment]
Gotta say, that was kind of a jerky comment, @SubsterNL. If you don't like RS, why are you following comments here? Save your cycles for something more productive than sniping.

**Comment by raoulvdberge** [comment]
@SubsterNL Don't expect me to react friendly if you're being a jerk on an issue tracker.

**Comment by raoulvdberge** [comment]
@ecoay 

I checked your profiling report but I can't seem to find any traces of RS... I suspect this is a crossmod issue still, though.

Please use the method that @way2muchnoise described to troubleshoot your issue.

**Comment by ecoay** [comment]
Found what it was. btw in case others are experiencing. Uses different multipart than Project Red Core. When both are installed they fight. No lag or hiccups since removing Project Red Core and Multipart CBE
