### ISSUE TITLE
Suggestion: Fire ItemCraftedEvent when auto crafting

### ISSUE THREAD

**Issue by modmuss50** [raoulvdberge/refinedstorage#1087]
Either fire ItemCraftedEvent when an item has been auto-crafted or, add your own event to allow me to trigger achievements with auto crafting.

Would be amazing if you could do this for 1.10.2

**Comment by raoulvdberge** [comment]
Why? Who would receive the achievement?

**Comment by modmuss50** [comment]
It's not for normal minecraft achievements, is for use in my custom mod.

**Comment by raoulvdberge** [comment]
This is an issue for @way2muchnoise, but it will be for 1.11, like usual.
