### ISSUE TITLE
Fluid crafting patterns

### ISSUE THREAD

**Issue by dovahkiin4991** [raoulvdberge/refinedstorage#1090]
With several mods now involving fluid, and item recipes, adding recipes that allow precise millibucket amounts, per item, such as the magma crucible from thermal expansion, which could produce 100mb of destabilized redstone per redstone dust. Please implement this update in 1.10.2 as well as in 1.11. If you ever need assistance testing this I would be happy to help

**Comment by raoulvdberge** [comment]
#461
