### ISSUE TITLE
Using a Pattern with oredict and a Crafter, it is possible to get wood planks of one type using wood of another type

### ISSUE THREAD

**Issue by calloatti** [raoulvdberge/refinedstorage#1091]
#### Issue description:

Using a Pattern with oredict and a Crafter, it is possible to get wood planks of one type using wood of another type

#### What happens:

Using a Pattern with oredict and a Crafter, it is possible to get wood planks of one type using wood of another type.

#### What you expected to happen:

The resulting wood planks should be the same type as the wood blocks used as raw material

#### Steps to reproduce:

Create a pattern using one spruce wood as source, resulting in 4 spruce wood planks. Check the "Oredict" check box.

Get rid of all the spruce wood in your storage and add 64 oak wood blocks

Craft the created pattern, you will get 4 spruce wood planks from one oak wood block, automagically converting wood from one type to another.

The result should be 4 oak planks I guess.

I discovered this bug trying to create storage drawers basic drawers with patterns for all the raw materials and the crafter went crazy into a loop converting all my wood from one type to another and never crafting the basic drawer. (all the patterns using oredict)

I guess fixing the simple test case will solve the more complicated problem that lead me to discover the bug.

...

#### Version (Make sure you are on the latest version before reporting):

Java is version 1.8.0_121, using 64-bit architecture.

Minecraft: 1.10.2

Mods:
  MCMultiPart-1.4.0-universal
  refinedstorage-1.2.25

 MinecraftForge v12.18.3.2254

Does this issue occur on a server? [yes/no]

Using single player

#### If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here]

**Comment by raoulvdberge** [comment]
#1029

**Comment by calloatti** [comment]
In the other Issue you discuss that maybe other mods are causing this by messing with the oredict.

Notice I tested with just Refined Storage.

**Comment by VT-14** [comment]
It's still the same problem.  The Ore Dictionary is being used to make something it shouldn't.
