### ISSUE TITLE
Problem crafting basic drawers from storage drawers using patterns (not an oredict issue)

### ISSUE THREAD

**Issue by calloatti** [raoulvdberge/refinedstorage#1092]
#### Issue description:

Creating patterns for Storage Drawers Basic Drawers with different wood types is not possible.

#### What happens:

  Storage Drawers Basic Drawers can be crafted from the six different types of wood, each resulting drawer will be of the wood used when crafting.
  
  When creating patterns of each wood type, the icon displayed by the pattern when pressing shift is always the oak wood Basic Drawer.
  
  If you create six different patterns for each type of wood, the crafting grid only displays one pattern, using oak wood.
  
  This is not using oredict option.
  
  This may be happening because all six basic drawers have the same id: 4349/0, but they all have 1 NBT tag that probably determines wood type.
  
  The trim blocks (similar block) from the same mod have different ids for each wood type: 4354/0 to 4354/5 with no NBT tags at all.

#### What you expected to happen:

Refined Storage should read the NBT tags?

#### Steps to reproduce:

Setup with all six wood type planks, create patterns for each basic drawer type.

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge:
- Refined Storage:

Java is version 1.8.0_121, using 64-bit architecture.

Mods:
  Chameleon-1.10-2.2.2
  MCMultiPart-1.4.0-universal
  refinedstorage-1.2.25
  StorageDrawers-1.10.2-3.6.1
  
  Forge Mod Loader version 12.18.3.2254

Does this issue occur on a server? [yes/no]

Only tested single player

#### If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here]

EDIT:

http://imgur.com/a/pg2IQ shows Basic Drawers created by crafter  with no NBT tag and compares with "normal" Basic Drawers.

**Comment by raoulvdberge** [comment]
Is it possible that it just renders the icon wrongly, but is still able to craft?

**Comment by BrianEdmonds** [comment]
The bit about making six different patterns, one for each wood type, but having the crafting grid only show one pattern sounds like a clear problem somewhere. I have no idea if RS is expected to handle recipes that have identical metadata, and differ only in NBT.

**Comment by calloatti** [comment]
The icon is rendered wrongly and the crafted drawer is always the default oak drawer (image wise) but with no material and no NBT tag (Check the images for details).

**Comment by PapiDimmi** [comment]
I was just about to report this bug.

![storage drawers refined storage bug](https://cloud.githubusercontent.com/assets/25916106/24828609/f5ff57a2-1c60-11e7-9cc4-8953e5a77491.png)

It’s not just the icons that are incorrect. When auto-crafting, Refined Storage always crafts the oak drawer, no matter what wood type is used.

**Comment by raoulvdberge** [comment]
^ That issue is already reported.

**Comment by PapiDimmi** [comment]
I know it was already reported. I commented on the existing issue. What are you talking about?

**Comment by raoulvdberge** [comment]
I thought you commented on another issue

**Comment by PapiDimmi** [comment]
Oh, I see.

**Comment by MokuJinJin** [comment]
Same issues here.
Auto-crating always give the same version.

I have to add, on mouse hover, before the drawer is used in the world, the material is not specified.
After using the drawer, on mouse hover, the material is Oak.
i suppose it is the default Material.

Happened in mutilplayer.

**Comment by ogredude** [comment]
Same issue here. Singleplayer.  Sky Factory 3 3.0.15

I thought I had a clever plan to get around this limitation by creating a Processing recipe demanding birch and chests and returning birch drawers, installing that into a RS Crafter pointed into a RFTools Crafter set to manufacture birch drawers, and an RS Importer to pull the result back into the system.

Newp.  I select the quantity to craft and hit the Start button, and the button greys out but the quantity control buttons are still active and we never get to the crafting preview screen.  Thankfully I can cancel out, it's only the one birch drawer recipe affected and it doesn't break anything permanently.

Darnit.  I guess I'll just dump a couple stacks of planks and chests into this RFTCrafter for now.

**Comment by raoulvdberge** [comment]
This issue has been fixed for RS 1.5.25

**Comment by PapiDimmi** [comment]
It’s about time.

JK. Thanks.

**Comment by PapiDimmi** [comment]
Great. Thanks.
