### ISSUE TITLE
Ore Dictionary causing loops, later versions can't handle

### ISSUE THREAD

**Issue by SavageMe55iah** [raoulvdberge/refinedstorage#1094]
#### What happens:

  I had input a recipe to use glass to make a different kind of glass so when I tried to craft a 1k storage with ore dictionary on it stated "Circular dependency! loop in processing...", the crafting wasn't a loop but it was reading as such, the 2nd problem is this message only popped on version Refined Storage: 1.2.14.

With versions Refined Storage: 1.2.25, 22 and 18 that area was blanked and the server would enter a state of non responsiveness while consuming more resources.

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge: 12.18.3.2239
- Refined Storage: 1.2.25

Does this issue occur on a server? [yes/no] yes

#### If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here]

**Comment by way2muchnoise** [comment]
The issue shouldn't be ore dict here. Usually it is some ingot <-> nugget/block conversion.

**Comment by raoulvdberge** [comment]
Working as intended, like @way2muchnoise said.
