### ISSUE TITLE
FTB Beyond. Export bus won't work in -5 dimension (Simple-Void-World mod)

### ISSUE THREAD

**Issue by SubsterNL** [raoulvdberge/refinedstorage#1098]
#### Issue description:
FTB Beyond. Export bus won't work in -5 dimension (

#### What happens:
The crafting grid hooked up to the receiver works but an export bus doesn't do anything.

#### What you expected to happen:
That the items set on the export bus are exported to a chest
#### Steps to reproduce:
1. Go to -5 dimension  (dimension from Simple-Void-World-1.10.2-1.1.0.4 mod)
2. Setup a network receiver in -5 and a network transmitter in the overworld with the interdim. upgrade
3. Export bus on chest in -5 dimension won't work reliable

Both sides are chunkloaded with FTBU
...

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
FTB Beyond

>>update: on a MC restart it did work and I cannot reproduce it so not sure what was going on.

**Comment by raoulvdberge** [comment]
Duplicate #370
