### ISSUE TITLE
Performance issues with big auto crafting requests

### ISSUE THREAD

**Issue by flubbes** [raoulvdberge/refinedstorage#1099]
#### Issue description:
Performance issues with big auto crafting requests. The modpack I use is skyfactory 3.0.8.
https://i.shnig.de/z7ueT9

The CPU is a quad core Intel CPU running @ 2.40GHz.

Normally the server runs at around 40% load on a single core. With autocrafting of large quantities it raises to 100%.

#### What happens:
Lag and position reset ingame.
https://i.shnig.de/4Bka2d

#### What you expected to happen:
No lag.

#### Steps to reproduce:
1. Queue large amounts of autocrafting (~20.000)
2. Experience lag

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge: 
- Refined Storage:

Does this issue occur on a server? [yes/no]
yes

#### If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here]

**Comment by Joshwoo70** [comment]
eurgh.. i think this is a duplicate...pls search -_-

**Comment by SubsterNL** [comment]
I think similar comments were made months ago and nothing was changed so I guess these reports are still valid.

**Comment by KaneHart** [comment]
it's not a duplicate. Nothing got fixed before keep reporting issues what github is for :)

**Comment by raoulvdberge** [comment]
It is a duplicate. This issue is already open

**Comment by KaneHart** [comment]
Maybe you are not finished but you did not link to it correctly.

**Comment by raoulvdberge** [comment]
What?!

**Comment by way2muchnoise** [comment]
@KaneHart Duplicate of #838 there is no need to keep opening issue that have the same report. Rather post .nps profiling to the original issue stating you have the same issue.
