### ISSUE TITLE
Using Quark feature to put items into adjacent inventories causes a crash with the solderer

### ISSUE THREAD

**Issue by ChaoticTabris** [raoulvdberge/refinedstorage#110]
Sorry, forgot to save the crashlog (Or is it automatically saved somewhere in my computer?). Basically i  decided to test if the feature in Quark where you click the new icon in your inventory with a open chest and a green arrow going into it would work with the crafting grid, i also happened to be close to my solderer. Upon clicking the icon my game froze and i had to kill it in Task Manager. Crash log gave an error related to the solderer block.

**Comment by raoulvdberge** [comment]
The crashreport should be saved in your MC instance folder.

**Comment by ChaoticTabris** [comment]
It was not saved. Maybe because it did not really crash, i had to kill the task in Task Manager.

**Comment by raoulvdberge** [comment]
Okay, thanks for reporting. Will take a look in the morning.

**Comment by raoulvdberge** [comment]
This is fixed for the next version!
