### ISSUE TITLE
External Storage on Storage Drawers Controller

### ISSUE THREAD

**Issue by terrigan** [raoulvdberge/refinedstorage#1100]
#### Issue description:
Refined storage with External Storage module not sorting into Drawer Controller. Everything is getting dumped randomly into drawers.

#### What happens:
RS network has Storage Drawers drawer controller on it with External Storage attached to it. Have Void Chests pulling in items from multiple locations and prior to switching to combining storage drawers and refined storage, Ender IO conduits would dump into Drawer Controller and sort into appropriate drawers with like items. Removed all Ender IO item conduit and replaced everything with RS Cable and Import modules going back to RS controller. Priority of External Storage module set to anything but a negative number makes Drawer controller dump items randomly in Empty drawers.

#### What you expected to happen:
Making External Storage module a higher priority should sort items into their respective drawers.

#### Steps to reproduce:
1. Hook External Storage module to Drawer Controller
2. Set priority to any positive number.
3. Hook module to RS system.
...

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge:
- Refined Storage:
(Skyfactory 3)

Does this issue occur on a server? [yes/no] Local LAN server.

#### If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here]

**Comment by raoulvdberge** [comment]
This is intended behavior, you're supposed to lock the drawers.
