### ISSUE TITLE
System breaks if spread over multiple chunks

### ISSUE THREAD

**Issue by Lethann** [raoulvdberge/refinedstorage#1101]
#### Issue description:

We have two systems on our server. One is entirely continained within a single chunk and has no issues (currently). The second system is spread over 4 chunks. If the chunk without the controller loads first it seems to break the system and we have to break the pieces, place them elsewhere before putting them back. If you break it and put it back it doesn't work.

#### What happens:

Various problems that have happened:
- Grids show as un-powered. Breaking and putting it back it still shows as unpowered. Have to move it to another area where it shows as powered before moving it back to it's proper place.
- grids show as powered but frozen. 
- Items on disk are static allowing for duping of items and loss of things put into the system.
- Solderer doesn't work, shows as unpowered
- crafters stop functioning. A crafting recipe shows up in the grid, allows us to order a job, but it never starts and doesn't show up in the crafting monitor.

#### Steps to reproduce:
1. log off of server
2. wait for chunks to unload
3. log back in
4. Go check the system

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge: 12.18.3.2254
- Refined Storage: 1.2.25
This is a custom modpack. Not sure how to get a full modlist without manually typing it out.

Does this issue occur on a server? Yes, have not encountered this on Single Player.

#### If a (crash)log is relevant for this issue, link it here:

N/A

#### Note:

I had a similar issue with the single chunk loaded system once but after pulling everything from it and replacing it all, moving it away from other blocks the system has been working fine since.

**Comment by Lethann** [comment]
Here are some screenshots. This morning is when we noticed that it was on the chunklines so that's why we're believing it's due to chunk loading. However, when I logged in, the chunk with the core should have loaded first before the one with the broken Fluid Grid so I'm not sure what's going on exactly.

![2017-03-28_07 15 12](https://cloud.githubusercontent.com/assets/25929754/24404302/8030cd36-1386-11e7-85ef-34b0785954c4.png)
![2017-03-28_07 13 41](https://cloud.githubusercontent.com/assets/25929754/24404306/848eb6fe-1386-11e7-841f-de1799d46871.png)
![2017-03-28_07 14 51](https://cloud.githubusercontent.com/assets/25929754/24404313/882572b2-1386-11e7-9715-9336e8eb095d.png)

**Comment by Lethann** [comment]
That is a possible workaround, yes, but this wasn't an issue for our SF3 server so I'm not sure if something's changed or if there is a conflict with a mod in our modpack. If this is simply as intended then that's fine but considering we've only run into this issue recently I was considering it a bug and thought it should be reported as I know many players like to have a core system with grids located throughout their base for ease of access.

**Comment by Lethann** [comment]
Apparently this is apart of a wider issue? While looking into issues with Ender I/O conduits breaking found this thread:

https://www.reddit.com/r/feedthebeast/comments/5m8q0y/dw20_110_having_to_breakreplace_refined_storage/

**Comment by way2muchnoise** [comment]
It was fixed for 1.11.2, see #370 for more info

**Comment by Lethann** [comment]
Ah, I didn't see it despite searching.  We're still on 10.2 while most mods are still updating to 11. Guess we'll just tough it out.
