### ISSUE TITLE
Disk Drive lighting glitch

### ISSUE THREAD

**Issue by PapiDimmi** [raoulvdberge/refinedstorage#1102]
![2017-03-28_16 25 38](https://cloud.githubusercontent.com/assets/25916106/24410828/5e2c2124-13d4-11e7-8252-0634b7fce1dd.png)

This only happens when the Disk Drive is placed up against a wall. It happens with and without shaders.

**Comment by ktole1999** [comment]
does it happen if you remove shaders mod completely?

**Comment by PapiDimmi** [comment]
I disabled my shaders, and it still happens, so it has nothing to do with my shaders mod.

![2017-03-28_18 56 53](https://cloud.githubusercontent.com/assets/25916106/24417352/574969e8-13e8-11e7-8820-3fcc70ad60a8.png)

**Comment by PapiDimmi** [comment]
It got even worse after placing a block on top of it.

![2017-03-29_01 03 42](https://cloud.githubusercontent.com/assets/25916106/24431337/9d828e02-141b-11e7-8603-ac3307510e6b.png)

**Comment by SubsterNL** [comment]
Tbh.. Disk drives have never rendered correctly for me. I figured it was something that couldn't be fixed. It looks totally borked.

**Comment by PapiDimmi** [comment]
I doubt it can’t be fixed.

**Comment by raoulvdberge** [comment]
Duplicate....... #970

**Comment by PapiDimmi** [comment]
@raoulvdberge Will you fix this?

**Comment by raoulvdberge** [comment]
Of course. If I wouldn't fix it, the other issue would be tagged as wontfix.

**Comment by PapiDimmi** [comment]
The same glitch occurs with the disk manipulator.

![2017-04-02_12 47 48](https://cloud.githubusercontent.com/assets/25916106/24586491/9dfb44d4-17a2-11e7-9a42-c3a434baab51.png)

**Comment by PapiDimmi** [comment]
@raoulvdberge You said [here](https://github.com/raoulvdberge/refinedstorage/issues/603#issuecomment-259185469) that it’s an OptiFine issue. You tagged it as invalid, which means that you won’t fix it, right?

**Comment by raoulvdberge** [comment]
that was another issue

**Comment by PapiDimmi** [comment]
@raoulvdberge Oh, really? My bad.
