### ISSUE TITLE
found an old bug that is recrashing again

### ISSUE THREAD

**Issue by feralspeedy** [raoulvdberge/refinedstorage#1104]
#### Issue description:
well everytime i go into the crafting grid it crashes me back to the launcher i have had a few people watch me on stream and they have help , so they suggested for me to come here, 
i was searching through google and found the same report from last year  heres the link : https://github.com/raoulvdberge/refinedstorage/issues/230
#### What happens:
crash back to launcher
#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge:
- Refined Storage:

Does this issue occur on a server? [yes/no]

#### If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here]
https://gist.github.com/feralspeedy/292b57744d7251fc24a4787bf575709d

**Comment by Joshwoo70** [comment]
pls put your forge version and refined storage version... thanks. -_-

**Comment by feralxmad** [comment]
Refined storage 1.2.22
Forge 12.18.3.2254

**Comment by feralspeedy** [comment]
FIXED IT
