### ISSUE TITLE
Quark’s food tooltip does not display in Refined Storage grids

### ISSUE THREAD

**Issue by PapiDimmi** [raoulvdberge/refinedstorage#1106]
I’m not sure if this is an issue with Refined Storage or Quark.
![quark or refined storage bug](https://cloud.githubusercontent.com/assets/25916106/24470419/26ea2c42-14bf-11e7-8d07-f4aab870fee9.png)

This happens with _all_ food items.

I am playing Minecraft 1.10.2, using the latest 1.10.2 version of Forge (12.18-3-2254), using the latest 1.10.2 version of Refined Storage (1.2.25), and using the latest 1.10.2 version of Quark (r1.1-70).

**Comment by PapiDimmi** [comment]
I’ve been told that this is because Refined Storage doesn’t render graphical tooltips. I hope @raoulvdberge fixes this.

**Comment by raoulvdberge** [comment]
Thanks @PapiDimmi, I'll look into this tomorrow.

**Comment by PapiDimmi** [comment]
Thanks!

**Comment by PapiDimmi** [comment]
@raoulvdberge Thanks for the fix!

**Comment by raoulvdberge** [comment]
???

**Comment by PapiDimmi** [comment]
You fixed the bug.

**Comment by PapiDimmi** [comment]
You fixed the bug. Thanks. It was an annoying bug.

**Comment by raoulvdberge** [comment]
You thanked me twice, 30th march and today, which is why I was confused.

**Comment by PapiDimmi** [comment]
You hadn’t fixed it yet on March 30th.

**Comment by raoulvdberge** [comment]
Ah, true...
