### ISSUE TITLE
Crafted pattern not visible in the storage

### ISSUE THREAD

**Issue by krike** [raoulvdberge/refinedstorage#1107]
#### Issue description:
Craft pattern in crafter cannot be found in the storage as long as there is 1 item in the storage that matches the pattern. I don't know if this is a bug or a feature but I thought I would post it here anyway. If this is a feature it is a bit confusing as I did not expect this and spend HOURS trying to figure out why I could not find the pattern in the storage.

#### What happens:
Created pattern cannot be found in the storage

#### What you expected to happen:
The item for which I made a pattern should be visible in the storage to be clicked on and craft the item regardless of items already existing in the storage

#### Steps to reproduce:
1 - Create a pattern
2 - Add the pattern in the crafter
3 - Look for created pattern in the grid (item with 'craft' label)

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2 (Skyfactory 3)
- Forge: forge-12.8.3.2254
- Refined Storage: 1.2.22

Does this issue occur on a server? [no] - playing on single player

Here is my setup:
https://s30.postimg.org/xo69hqfap/2017-03-29_20.22.22.png

Here an example where the storage contains 1 16k Storage part but the craft pattern is not visible:
https://s15.postimg.org/uubab85hn/2017-03-29_22.10.34.png

Here an example where the storage DOES NOT contain 1 16k Storage part but the craft pattern IS  visible:
https://s2.postimg.org/535cnfpyx/2017-03-29_22.12.00.png

**Comment by BrianEdmonds** [comment]
This sounds like it's working as intended. The pattern does not show when there are items in the storage, but you can Ctrl-Shift click on the items (or Cmd, or whatever is appropriate for your platform) to get the crafting interface instead of pulling out items.

**Comment by way2muchnoise** [comment]
It can be found @krike, it just uses the same thing. You can start crafting by using ctrl+shift+left click even when items are in the system. [See wiki for more info](https://refinedstorage.raoulvdberge.com/wiki/grid)

Anyway very good report :+1:

**Comment by Lethann** [comment]
Glad I checked in here because I didn't know about the Ctrl-Shift clicking.

But to add to this, there is an option on one of the side buttons to change the viewable items in the grid. The second button on the left of the grid is for "display". If you click through that until it's "only craftables" it makes it easier to find these patterns.

**Comment by krike** [comment]
I didn't know about the shortcut as well. Not that I did not read the wiki but i just didn't read everything :D. What I usually do is watch a quick video to get the basics and then start playing with it. I will be reading through the wiki now as I found another problem (machine not found for a normal craft pattern). Thank you for the info!

**Comment by way2muchnoise** [comment]
Machine not found is usually when you made a processing pattern instead of a crafting pattern. [See the wiki on autocrafting for more info about the difference](https://refinedstorage.raoulvdberge.com/wiki/autocrafting).

**Comment by krike** [comment]
No no, I'm pretty sure I used the crafting pattern. if you see my setup the pattern for regular crafting is in one of the crafters all the way to the left, they don't need any machine to work. also I'm trying to craft a construction core which (if i'm not mistaken) is one basic processor combined with quartz. Once I pressed start it create the printed the basic processor required because I did not have enough and once it got to the construction core it said no machine found but there is no machine required ... I think

**Comment by way2muchnoise** [comment]
Regular crafting patterns can't have the "machine not found" error. Make sure you made them in the pattern grid and not the pattern encoder.

**Comment by BrianEdmonds** [comment]
Yeah, just try remaking the pattern in the pattern grid. I've done it a few times myself, where I've made the pattern in the wrong grid and then scratched my head for a few minutes.

**Comment by Lethann** [comment]
The OP isn't saying they are getting a "machine not found" error. They were confused by the fact that the word "Craft" doesn't appear on an item if at least ONE of that item is in the system. It's default behavior of RS but someone new to the mod might not realize it. 

Would be nice if there was some indicator that the item CAN be crafted even if there is at least one in the system. A border or indicator or something. Early game it's easy to remember what you have patterns for but later on there's so many patterns I forget what I have. The "Only Craftables" display helps at least.

**Comment by krike** [comment]
@Lethann no I did mention 'machine not found' error in one of my later comments. and ... I recreated the patterns and seem to be working now so I guess I did do a dumb :P I must have mixed Advanced processor with the construction core, they look very similar

**Comment by raoulvdberge** [comment]
@Lethann 

> Would be nice if there was some indicator that the item CAN be crafted

I don't think that is needed, it'd be mostly GUI noise. Just press CTRL SHIFT and see if the GUI responds.

**Comment by BrianEdmonds** [comment]
I think this could be a nice feature, if it could be done without GUI noise, that @raoulvdberge mentioned. I'm not a UI person, and have no particular thoughts it, but I'd hope it wouldn't be rejected out of hand if a concrete, and attractive proposal were offered.

**Comment by raoulvdberge** [comment]
I think the "only show craftables" button combined with the "try pressing CTRL SHIFT" solution is helpful enough to not warrant a GUI change.
