### ISSUE TITLE
Latency with External Storage & Stoage Drawers Contoller

### ISSUE THREAD

**Issue by oguzp1** [raoulvdberge/refinedstorage#1108]
#### Issue description:
Storage Controller from Storage Drawers (connected by an External Storage) responds to the RS system a little late.
#### What happens:
The Detectors do not detect the items inside the Drawers for a short amount of time when I start my SSP world up.
#### What you expected to happen:
The Detectors should detect the items inside the Drawers before setting off a redstone signal based on what it has inside the Disk Drives.
#### Steps to reproduce:
Here's a link to a simple way to reproduce this:
http://imgur.com/a/Sx7G6

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge: 12.18.3.2254
- Refined Storage: 1.2.25 (pictures are from 1.2.23, but the same applies)
- Storage Drawers: 3.6.2

Does this issue occur on a server? [yes/no]
Occurs on a singleplayer world, I haven't tested it for a server.

**Comment by BrianEdmonds** [comment]
Are you certain the problem is in RS? Storage Drawer controllers only update their state of all the drawers every so often[1], so what you're seeing may be that interim period before their state update is complete.

[1] Every five seconds, per https://github.com/jaquadro/StorageDrawers/wiki/Drawer-Controller

**Comment by oguzp1** [comment]
> Are you certain the problem is in RS? Storage Drawer controllers only update their state of all the drawers every so often[1], so what you're seeing may be that interim period before their state update is complete.

I've removed the controller and attached the External Storage directly to the Drawer itself, and the issue appears to be fixed. Didn't know about Controllers updating their state every 5 seconds. Thank you for the answer.
