### ISSUE TITLE
Feature Request: Indicator light on Crafting Monitor.

### ISSUE THREAD

**Issue by calloatti** [raoulvdberge/refinedstorage#1109]
Can we have an indicator light on the front of the Crafting Monitor indicating status?

You could just reuse the disk drive indicator:

Red: Houston we have a problem!

Orange : working on it.

Blue: Idle/finished.

**Comment by raoulvdberge** [comment]
No! This was requested already, please look for previous issues before making an issue!

**Comment by BrianEdmonds** [comment]
It would be nice to know which issue it is a duplicate of. I just did a search for "crafting indicator" and didn't see any useful results. I tried a search for just "monitor", and saw nothing obvious. With 1000+ issues it's non-trivial to simply scan them all.

**Comment by raoulvdberge** [comment]
Agreed, I will look this up for you in a second.

**Comment by raoulvdberge** [comment]
Duplicate of #197

**Comment by BrianEdmonds** [comment]
Thanks for the update.
