### ISSUE TITLE
Feature suggestion: Add the ability to access items in the crafting grid

### ISSUE THREAD

**Issue by PapiDimmi** [raoulvdberge/refinedstorage#1111]
Let’s say I have two crafting grids in separate locations in my base. I want to craft a crafting table, and I have three planks, which is almost enough. I put the three planks in the crafting window, and I leave the crafting grid and go to my _other_ crafting grid in a separate location, because I have some extra planks there. I get my one extra block of planks, but I still don’t have enough, because the three planks that I had are stuck in my other crafting grid.

It would be very useful if items couldn’t be stuck in crafting windows; they should be accessible from other grids (not just crafting grids), and items in a crafting window should count as items on the disk rather than items stuck in the crafting window.

This could just be a config option, so people can choose whether to use this method or the current one.

**Comment by BrianEdmonds** [comment]
I've definitely found myself wanting for something like this more than
once, when I've left a scarce item in a remote crafting grid.  How
feasible it would be to implement is a different question, of course.

**Comment by PapiDimmi** [comment]
Here’s an idea: When you close a crafting grid, the items that were in the crafting window are automatically placed in the grid, so that they’re available elsewhere, but when you re-open that specific crafting grid, it remembers the items that were in the crafting window and puts them back, so that it’s exactly like you left it. The best of both worlds!

I’m not sure if this would be hard to code, but I would really appreciate @raoulvdberge if he did this.

**Comment by BrianEdmonds** [comment]
I like the sound of that. I don't know how hard it would be to code. The
grid has to remember what was in it already, so doing that while moving
the items in and out of storage doesn't sound horrible to me. One edge
case that comes to mind is if the items that are remembered are no
longer in storage when the grid is reopened, but that doesn't sound hard
to deal with. Now it's just a question of Raoul liking it. :)

**Comment by PapiDimmi** [comment]
>One edge case that comes to mind is if the items that are remembered are no longer in storage when the grid is reopened

If that’s the case, the crafting grid would fill up the crafting window with all the items it still has.

Let’s say you’re trying to craft a diamond pickaxe and only have three diamonds. You leave the three diamonds and two sticks in the crafting grid, take out one diamond from another grid, and come back. When you open the crafting grid again, the crafting window automatically be filled up with two diamonds and two sticks, since it’s missing one diamond.

I don’t think that this would be _too_ problematic to code. It would be a super useful feature.

**Comment by raoulvdberge** [comment]
No. The grid has to behave like other crafting grids, once you take items out, they are technically unavailable to the system. Besides, this system would break if you would have other people watching a grid.

**Comment by PapiDimmi** [comment]
>Besides, this system would break if you would have other people watching a grid.

What do you mean? Can people open the GUI of a crafting grid at the same time as you and see what you’re crafting? If so, this feature could either be disabled on servers, or the grids could just not show what’s being crafted, just like vanilla crafting tables.

**Comment by raoulvdberge** [comment]
> this feature could either be disabled on servers

I don't make such small features disable-able in RS. Never have, never will.

> or the grids could just not show what’s being crafted, just like vanilla crafting tables.

Nope.

**Comment by PapiDimmi** [comment]
>>or the grids could just not show what’s being crafted, just like vanilla crafting tables.

>Nope.

Why not?

**Comment by raoulvdberge** [comment]
Because that's not the way I want it to work. And especially not for this feature, which I don't like in the first place.
