### ISSUE TITLE
”RF got a little hungry”

### ISSUE THREAD

**Issue by PapiDimmi** [raoulvdberge/refinedstorage#1113]
![refined storage wtf](https://cloud.githubusercontent.com/assets/25916106/24571314/a6a13482-1670-11e7-9033-9701cf6acc54.png)

This just started happening every time I put food in my Refined Storage system. It’s really annoying. It doesn’t actually consume food, though.

Since this _conveniently_ started happening on the first of April, I assume it’s an April Fools’ prank. April Fools’ pranks are supposed to be _funny_, not _infuriating_. If this only happened once, that would be strange and funny, but this happening every time I put food into my RS system is extremely frustrating.

**Comment by raoulvdberge** [comment]
It looks like RS can't resist the food you're inserting in the system :-(

**Comment by PapiDimmi** [comment]
Screw RS. I’m switching to AE2. ^^/s

**Comment by Joshwoo70** [comment]
how to ruin everyone... 
"Happy april fools"

**Comment by ktole1999** [comment]
did you even bother to check if it was missing or was it just a message when <food> was inserted.

**Comment by way2muchnoise** [comment]
@ktole1999 it was just a message, it wouldn't be so much fun if it actually delete items. 😆
