### ISSUE TITLE
Quite clear glass turns back to vanilla glass when placed in refined storage

### ISSUE THREAD

**Issue by krike** [raoulvdberge/refinedstorage#1114]
#### Issue description:
Quite clear glass turns back to vanilla glass when placed in refined storage

#### What happens:
When I autocraft 3 regular glass to quite clear glass using an alloy smelter, when the items are imported into the system they are changed back to regular glass.

#### What you expected to happen:
Quite clear glass should be added to the system and not turned back to regular vanilla glass

#### Steps to reproduce:
1. Place glass in the alloy smelter 
2. Get the smelted Quite clear glass
3. Place the items into the system

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2 (Skyfactory 3)
- Forge: forge-12.8.3.2254
- Refined Storage: 1.2.22

Does this issue occur on a server? [no] Single player

Small screencast to show it in action:
http://screencast-o-matic.com/watch/cbfV226Lhp (Sorry for the loud noise at the beginning of the video)

**Comment by raoulvdberge** [comment]
duplicate

**Comment by Anaerin** [comment]
If you are storing your glass in storage drawers, they can (and will) accept anything that's ore dictionaried. And as Quite Clear Glass is ore dictionaried to blockGlass it will accept it and convert it. The screencast you have there doesn't show all your network, so I can't tell if that's an issue here or not.

**Comment by krike** [comment]
Not storing anything in storage drawers. The alloy smelter was connected to refined storage and kept turning it back into glass when inserting in RS, also I manually added the Quite clear glass in to RS system so why would storage drawers have any effect on that?

**Comment by raoulvdberge** [comment]
But will the block end up in your drawers due to an external storage connection?

**Comment by Anaerin** [comment]
If you don't have any storage drawers with glass in attached to this network, then this doesn't apply. If you do, however, then that may be what you're running into.

RS will prioritise putting items with like items in storage. Storage Drawers "advertise" they have the items within, and all items that are oredicted to those items. So if you have a drawer with glass in it, RS will look to see where it can place Quite Clear Glass, and the Storage Drawer will report it has items and can accept it, so RS will place it there.

If this is not what you want, you can set the external storage attached to the storage drawer to "Export only". To see if this is a RS bug or a Storage Drawers issue, I'd suggest re-creating this with an independent network, with just a Controller, Alloy Smelter, Storage block (or Disk Drive and disk), Importer and EIO Alloy furnace. If it still does it with just RS and EIO, nothing else in the network, then it's a RS bug.

**Comment by calloatti** [comment]
I was having the opposite problem, vanilla glass turning to quite clear, and also using storage drawers.

I solved it by adding a 1k storage block and using it only for vanilla glass storage.

**Comment by way2muchnoise** [comment]
This is likely cause Storage Drawers manage their own stuff, might be a solution to turn off oredict matching on your external storage facing the drawer(s).

**Comment by krike** [comment]
mmm so i had it linked using an external storage pipe and network, would that still cause this problem? anyway I removed all the storage drawers anyway and put all in RS, I'll test it again later

**Comment by raoulvdberge** [comment]
If you insert the glass manually in the drawer controller, what happens? Will it transform to the normal glass as well?

**Comment by raoulvdberge** [comment]
Yep. If I insert the "Quite Clear Glass" in a Drawer Controller connected to a drawer with "Glass", Storage Drawers converts it to regular glass. Thus, this is not an RS issue. Please report over at the Storage Drawers issue tracker. This can be intended behavior as well.

**Comment by krike** [comment]
I also tested this again yesterday and it's indeed not an RS issue. I did have a drawer that contained glass. sorry about that.
