### ISSUE TITLE
Silicon Not ore dictionaryed

### ISSUE THREAD

**Issue by Salnex** [raoulvdberge/refinedstorage#1119]
#### Issue description:
Silicon not ore dictionaryed for Solderer. In FTB Beyond 1.2.1

#### What happens:
Ender IO Silicon not accepted by solderer
#### What you expected to happen:
Any silicon accepted by Solderer
#### Steps to reproduce:
1. Sag Mill Sand
2. Insert Silicon by hand into solderer
3. Nothing! :(

#### Version (Make sure you are on the latest version before reporting):
- FTB Beyond: 1.2.1
- Minecraft: 1.10.2
- Forge: 12.18.3.2254
- Refined Storage: 1.2.23

Does this issue occur on a server? [yes/no]:
Unsure

**Comment by PapiDimmi** [comment]
Ender IO works fine in a solderer to make printed silicon for me.

**Comment by calloatti** [comment]
I can use EnderIO silicon with no problem in solderer

**Comment by raoulvdberge** [comment]
I can't reproduce this with just RS. I assume some other mod is messing up the oredict.

**Comment by way2muchnoise** [comment]
Or some (Mine|Craft|Mod) Tweaker scripts
