### ISSUE TITLE
Insanely slow FPS when opening crafting grid.

### ISSUE THREAD

**Issue by drewbit** [raoulvdberge/refinedstorage#112]
When I open the crafting grid my client lags like absolutely crazy. It goes away if I keep it open long enough but it takes quite some time. 

Here's a screenshot of the entire setup:
http://imgur.com/ZFa1cb6

Refined Storage Version: refinedstorage-0.7.11
Forge Version: forge 1.9.4-12.17.0.1950

**Comment by raoulvdberge** [comment]
What stuff is in your grid? Can you reproduce this issue with *just* Refined Storage installed?

**Comment by drewbit** [comment]
Tried a separate instance with just Refined Storage, Forge and Optifine installed. Not getting the issue anymore so I guess it's something cross mod related. Here's what was in the grid if you still need it:

http://imgur.com/Dn0U0pu

Any ideas what it could be? Not looking forward to removing 1 mod at a time.

**Comment by raoulvdberge** [comment]
Do you have this issue also on normal grid?

To debug this, remove everything from your grid and inventory, move everything to a chest and slowly add items back. Once the grid starts lagging when you add an item, you know the mod that does it.

**Comment by drewbit** [comment]
Alright, sorry for the late reply.

I can confirm the issue is not present when using a normal grid. This only happens in a crafting grid.

Also tried the debugging method you asked for, it didn't really do anything. As you can see I have literally nothing in my inventory or in the grid. My FPS is still dropping like a stone.

**Comment by Rumpelstiltskinny** [comment]
I also had this problem in a previous world (gone now). As I added more items to storage the crafting grid GUI progressively caused my FPS to drop. With a few items it wasn't bad. Thousands of items stored and it was excessively affecting my FPS. This was with 70+ mods and 1.9.4-1954.

**Comment by raoulvdberge** [comment]
@Rumpelstiltskinny And you weren't having that issue with a normal grid?

**Comment by raoulvdberge** [comment]
Can you guys retry this in the latest version?

**Comment by drewbit** [comment]
The new version fixed the issue for me.

**Comment by raoulvdberge** [comment]
Great to hear, I heard the same response from someone else that also had this issue so I'm confident to close this now.

For later reference, this was fixed in 0.7.13.
