### ISSUE TITLE
Autocrafter Crafting Upgrade

### ISSUE THREAD

**Issue by thegamehunter09** [raoulvdberge/refinedstorage#1120]
#### Steps to reproduce:
1.
2.
3.
...

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge:12.18.3.2254
- Refined Storage:1.2.23

Does this issue occur on a server? [yes]

#### If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here]

**Comment by raoulvdberge** [comment]
Share some screenshots of your setup pls

**Comment by thegamehunter09** [comment]
I hope I attached these right. Here ya go I took four screenshots of the system.

![2017-04-02_11 06 06](https://cloud.githubusercontent.com/assets/12162492/24588382/e472dd9a-1794-11e7-8cf1-bf69cdebb7d7.png)
![2017-04-02_11 06 13](https://cloud.githubusercontent.com/assets/12162492/24588383/e47356d0-1794-11e7-9f9a-a579f208160a.png)
![2017-04-02_11 06 31](https://cloud.githubusercontent.com/assets/12162492/24588384/e473a752-1794-11e7-91ad-d98d36b21ba3.png)
![2017-04-02_11 06 44](https://cloud.githubusercontent.com/assets/12162492/24588385/e474616a-1794-11e7-8951-2b24147dd059.png)

**Comment by way2muchnoise** [comment]
And the autocrafting setup? the patterns used?

**Comment by raoulvdberge** [comment]
- Can you request the item normally and will it craft?
- Are you missing any items to craft, what does the Crafting Monitor say?
- Is it valid to export to the bottom side of a Storage Drawers controller?
- Does it work when you let the Exporter face a chest?

**Comment by thegamehunter09** [comment]
@way2muchnoise 
![2017-04-02_12 12 02](https://cloud.githubusercontent.com/assets/12162492/24588842/440dd0da-179e-11e7-8914-849c123f73f7.png)
![2017-04-02_12 12 10](https://cloud.githubusercontent.com/assets/12162492/24588843/440ef1ea-179e-11e7-82e6-3c89568202a3.png)

**Comment by thegamehunter09** [comment]
@raoulvdberge  Yeah I can request the items normally. No I am not missing any items in the system. I am using a network connector and transmitter not sure if there is a problem with it. I am not sure if its valid I feel like it is a valid face sense I have put external interfaces to them before. I haven't tried the exporter to the chest on this system.

**Comment by raoulvdberge** [comment]
Please try it, the drawer might not accept from the bottom.

**Comment by thegamehunter09** [comment]
@raoulvdberge Just attached it to a chest and nothing happened. Also this system is separate from my main storage. Its connected via a network transmitter and reciever

**Comment by Timmeh74** [comment]
Hey, from the setup this seems to be inspired by Direwolf20's LP series, where he had a similar problem. Can the Livingrock/-wood in the drawer be accessed from the network you are crafting from? If so, the exporter might take them from inventory instead of crafting and just loop the items.

**Comment by thegamehunter09** [comment]
@Timmeh74  No I can't access the drawers from the main system. I can request living rock and wood but its not doing it automatic sense I have a crafting upgrade in the exporter

**Comment by Timmeh74** [comment]
@raoulvdberge 
The Drawer Controller can accept items from the bottom afaik.

@thegamehunter09 
Have you set Living Wood/Rock as a filter on the exporter?

**Comment by thegamehunter09** [comment]
@Timmeh74 Sorry for the real late response. I think I tried that before and that didn't yield any result. It just never requested any living wood or living rock. Recently I checked the drawers and saw they were full so I emptied it but the system didn't try fill it back up.

**Comment by thegamehunter09** [comment]
@Timmeh74 @raoulvdberge I am not sure what is causing this but I am noticing that the controller I have place to make the livingwood and livingrock system its own separate network but for whatever reason the controller just pops of the wire. It will just pop off and become a item in the world. Could this be apart of the problem.

**Comment by BrianEdmonds** [comment]
Are you certain your Botania RS system really is separate? The
controller popping off is what happens when you get more than one
controller in a system, IIRC. Better than not long ago, when extra
controllers blew up instead.

**Comment by Timmeh74** [comment]
Hi! I looked at your screenshots again and it might be the crafter that is connecting both networks.
