### ISSUE TITLE
Does crafters support secondary outputs?

### ISSUE THREAD

**Issue by PapiDimmi** [raoulvdberge/refinedstorage#1123]
_E.g._, a 20% chance of getting gold dust in an Actually Additions crusher or 50% chance of getting silicon in an Ender IO SAG mill.

The reason I’m asking this is that in one of his videos, direwolf20 says that Refined Storage doesn’t support secondary outputs, so he couldn’t create a pattern for silicon from sand in a SAG mill, but when I crush iron ores using Refined Storage’s crafter, I _do_ get the secondary output, so I am a bit confused.

**Comment by way2muchnoise** [comment]
you can get secondary output, but RS doesn't know about percentage so it can get stuck if it doesn't actually make it. Things like 4 sand -> 1 silicone will work sometimes, but if you really have bad luck it might still go wrong.

**Comment by PapiDimmi** [comment]
@way2muchnoise Exactly what happens when doing that? I’m a bit confused. What happens if RS doesn’t know the percentage?

**Comment by raoulvdberge** [comment]
You have a pattern of 4 sand -> 1 silicon. RS inserts 4 sand in the machine. It uses up the 4 sand, but the silicon isn't made because you were out of luck. RS is now stuck, and it won't insert any more sand because it inserted the 4 already.

RS won't have support for percent-based crafting, though.

**Comment by PapiDimmi** [comment]
>RS won't have support for percent-based crafting, though.

**Comment by raoulvdberge** [comment]
>  every machine
Don't exaggerate!

**Comment by PapiDimmi** [comment]
I said “_almost_ every machine.”

**Comment by way2muchnoise** [comment]
So the SAG mill and the pulverizer, almost all machine Kappa

**Comment by PapiDimmi** [comment]
The SAG mill, pulverizer, crusher (Actually Additions), crusher (Extra Utilities 2), and the induction smelter.

**Comment by raoulvdberge** [comment]
Those are not even *almost* all machines in modded MC

**Comment by PapiDimmi** [comment]
I meant almost every machine that I use. Besides, most of the machines that can smelt things have some sort of secondary output. It’s unfortunate that RS doesn’t support that.

**Comment by BrianEdmonds** [comment]
RS doesn't *not* support it, it just cannot count on it as an 
intermediate crafting step. If I had to rely on a non-100% secondary 
output, I'd use a detector/crafter pair to maintain a minimum number in 
the system.
