### ISSUE TITLE
Can you add a way to clear patterns?

### ISSUE THREAD

**Issue by PapiDimmi** [raoulvdberge/refinedstorage#1124]
I know that you can change the recipe of a pattern, but it would be useful if you could put one in a crafting table to clear its NBT data so that you can stack it with other blank patterns.

**Comment by raoulvdberge** [comment]
This is already possible. Please consult the wiki first: https://refinedstorage.raoulvdberge.com/wiki/pattern

![x](https://raoulvdberge.com/r2VMzb)

**Comment by BrianEdmonds** [comment]
Just right click while holding it in hand.

**Comment by PapiDimmi** [comment]
Whoops, I’d no idea.

Funnily enough, I’ve actually done this before, but I had completely forgotten about this feature. My apologies.
