### ISSUE TITLE
Servercrash caused by refined storage and techreborn interaction

### ISSUE THREAD

**Issue by dragonbabyfly** [raoulvdberge/refinedstorage#1127]
#### Version (Make sure you are on the latest version before reporting): I am playing the latest version of all the mods 1.10.2

- Minecraft: 1.10.2
- Forge: forge-12.18.3.2254
- Refined Storage: 1.2.24
- Techreborn : 1.10.2-2.1.10.207-universal

Does this issue occur on a server? [yes/no] yes 

#### If a (crash)log is relevant for this issue, link it here: https://pastebin.com/aVBGFrxZ

[pastebin/gist/etc link here]

**Comment by raoulvdberge** [comment]
This is not a crash caused by RS, the crashlog doesn't even mention RS
