### ISSUE TITLE
[Feature Request] - Single crafter block that can store plain crafting recipes

### ISSUE THREAD

**Issue by JaSpr** [raoulvdberge/refinedstorage#1128]
Currently, for every 9 crafting recipes, the user has to create another Crafter.  It'd  be nice if there were a (very expensive) super-crafter block that could store much more than 9 patterns. Additionally, this crafter would only be able to craft things that are craftable using a normal crafting grid.  Nothing that requires interaction with another machine.

**Comment by way2muchnoise** [comment]
[Reborn Storage](https://minecraft.curseforge.com/projects/rebornstorage?gameCategorySlug=mc-mods&projectID=256662) will be your friend then.

**Comment by JaSpr** [comment]
Doesn't help much when using an existing modpack.  The modpack updates regularly though, so if an update to Refined was to contain such a thing, it would be quite helpful.

**Comment by BrianEdmonds** [comment]
If you haven't already, I'd suggest Reborn Storage to the modpack you're playing. It really is very nice.
