### ISSUE TITLE
facades {FeatureRequest}

### ISSUE THREAD

**Issue by Harith163** [raoulvdberge/refinedstorage#113]
Have you thought of making facades that can mask a cable?
Would it have to depend on/be compatible with mcmultipart?

**Comment by raoulvdberge** [comment]
If mcmultipart is merged, I'll add support for it.

**Comment by psychofad** [comment]
Could you perhaps make a block similar to the Conduit Facades from Enderio that could be painted to look like another block and could be right clicked onto the cables and perhaps shift-right clicked to remove them?  I have seen mods in the past that had a tool that could copy a blocks texture and apply it to another block.  While I would love to have mcmultipart support, it would be nice to have some sort of alternate covering in the mean time to hide the cables.

**Comment by ThexXTURBOXx** [comment]
There is a deobf-version already: http://minecraft.curseforge.com/projects/mcmultipart/files/2312808
I hope you can add support for it soon (I like the mod so much, but I don't like, that you can't hide the cables :(
If you want, here is another useful mod (SimpleCovers): http://minecraft.curseforge.com/projects/simple-covers?gameCategorySlug=mc-mods&projectID=242498
There are covers, but they aren't compatible with the cables yet...

**Comment by raoulvdberge** [comment]
This is done for the next version!

**Comment by ThexXTURBOXx** [comment]
Wow, thanks! :)

**Comment by raoulvdberge** [comment]
It works with the Simple Covers but also with Chisel & Bits ;)

**Comment by ThexXTURBOXx** [comment]
This is even cooler :O You are a god \(^_^)/
