### ISSUE TITLE
Silicon OreDict

### ISSUE THREAD

**Issue by xXJamieXx** [raoulvdberge/refinedstorage#1131]
#### Issue description:
I know this has been reported before but... I'm still experiencing the issue where autocrafting using silicon doesn't use multiple types of silicon to craft with. For example it's only seeing the EnderIO silicon when I have enough RS silicon to complete the craft.
#### What happens:
I click to craft a 64k storage part and it says its missing some silicon.
#### What you expected to happen:
Actually allow me to craft the item using both types of silicon.
#### Steps to reproduce:
1. Setup a pattern to make 64k parts.
2. Put in 2 types of silicon.
3. Try to autocraft
4. Fail

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge: 2254
- Refined Storage: 1.2.25

Does this issue occur on a server? [yes/no]
Yes
#### If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here]

**Comment by raoulvdberge** [comment]
Change the patterns that use silicon to be an "oredict" pattern, toggle-able in the Pattern Grid/Processing Pattern Encoder GUIs.

**Comment by xXJamieXx** [comment]
Fixed it, forgot to OreDict the Printed Silicon! (someone helped me on the FTB Reddit)
