### ISSUE TITLE
Feature Request: A crafting history list to easily retrieve recently crafted items.

### ISSUE THREAD

**Issue by calloatti** [raoulvdberge/refinedstorage#1134]
Scenario:

You want to build an Inmmersive Engineering Excavator, that requires 9 diferent parts in various quantities.

You already have all the patterns for each of the parts.

You get into the crafting grid, and search for each part by typing part of the part name, and craft the required quantity for each part.

**What happens now:** 

You check from time to time the Crafting Monitor to see if everything is done.

When all the parts are finished, you get into the grid again and again search for each part by typing part of the part name to actually get the parts into your inventory.

**What would be really great:**

You get into the crafting monitor where you have a "Crafting History" tab that lists all the recently manually crafted items,  most recent first, and you get your parts from there.

Or any other way to implement it.

**Comment by ktole1999** [comment]
you could look at it from a different angle. if you need x item that requires a,b,c items. have the autocraft make the a,b,c items if the resources are already available. never used RS so not sure if this is implemented.

**Comment by way2muchnoise** [comment]
I like this idea of a "recently crafted" list

**Comment by raoulvdberge** [comment]
Me too

**Comment by raoulvdberge** [comment]
We will have to think a bit on how to incorporate this in the GUI

**Comment by raoulvdberge** [comment]
I like this idea:

![x](https://raoulvdberge.com/fhXz8c)

But unfortunately this makes the GUI just too big.

I like the idea of a tab less, since it seems kinda out of place since no other RS GUIs have tabs.

**Comment by ktole1999** [comment]
what about a 3x3 dot button that opens history list.

**Comment by raoulvdberge** [comment]
I'm a bit against having buttons to switch the GUI, because then it feels like suddenly the monitor does too much for a single block.

But unfortunately, I think I'll have no other chance to make this with a toggle-switch button like you suggested.

**Comment by BrianEdmonds** [comment]
How about having a text box where the user can enter a number, and it
keeps that many completed crafting jobs in the UI, just like when
they're active, but greyed out or somesuch to indicate that they're
complete. It could default to zero, and would thus be nearly no change
at all for users not using the feature.

**Comment by raoulvdberge** [comment]
And when you click the task it pushes the items to your inventory and removes it from the list? I like it

**Comment by BrianEdmonds** [comment]
I wasn't thinking you'd have to explicitly release the items, it would
just be there as a record of recently completed tasks. But if you'd
prefer to implement it as a click to release, I'm just fine with
that. Then it could be even simpler. Just a checkbox for "hold items
upon crafting completion", and you could go to the monitor to retrieve
them as you describe. You'd presumably need to allow intermediate
crafting steps to be available to the system though, or it would get
painful to use very quickly.

Or, I suppose, have a checkbox in the autocraft interface when you craft
something, to have the result held in the crafting monitor as described.
Then most crafting could be done as usual, and there would be no
confusion with intermediate autocrafting steps, but if you wanted things
held for collection you could easily flag them as such.

**Comment by calloatti** [comment]
Another way to implement it (that I am not entirely convinced about but maybe someone else can think of similar alternatives)

Add a "craft time" sorting type to Grids. With that and using the "Only craftables"  Display option you will have a grid with the crafted items ordered by craft time. But it seems kind of complicated, maybe.

**Comment by raoulvdberge** [comment]
The problem with a "Recently crafted" display option in the Grid is that you still have to switch from Crafting Monitor to Grid (and then perhaps even change the Display Option if not set correctly yet).

**Comment by VT-14** [comment]
JEI shows your previous searches when you press the up arrow key with the searchbar selected.  Would it be easier to do something like that in the grid's searchbar?

**Comment by raoulvdberge** [comment]
Then you still have to switch from Grid to Crafting Monitor. But it's a good idea either way, so I'll implement that as well.

**Comment by calloatti** [comment]
Another option to implement this with minimal changes: In the Crafting Monitor, when a craft finishes instead of deleting everything from the grid, leave one line with the finished item(s) and allow to retrieve the crafted items from there by the usual means (middle click, Shift click, etc.) if all the items are removed delete the line.

The finished item(s) line could include some text like "x items crafted" or something like that

**Comment by raoulvdberge** [comment]
I don't like this idea anymore, the crafting monitor would do too much.
