### ISSUE TITLE
[1.11.2] Crash after placing Cake from storage system

### ISSUE THREAD

**Issue by Deylendor** [raoulvdberge/refinedstorage#1135]
#### Issue description:
After the ingame crash the server won't start anymore.
#### What happens:
The server crashed after a Constructor attempted to place a cake from the storage system.
#### What you expected to happen:
Constructor placing the cake into the game world.
#### Steps to reproduce:
1. Place a constructor downwards into the ground and correct its position ( to face towards the player) with the interaction wheel
https://minecraft.curseforge.com/projects/interaction-wheel?gameCategorySlug=mc-mods&projectID=256287
2.
Set the item to be constructed by the constructor to a cake
3.
Place a cake into your storage system.

#### Version:

- Minecraft: 1.11.2
- Forge: 1.11.2 - 13.20.0.2265
- Refined Storage: Refined Storage 1.4.2

Does this issue occur on a server? -- Yes

#### If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here]

latest.log
https://pastebin.com/q5F8xyef

fml-server-latest.log
https://gist.github.com/Deylendor/66ebff1742ee2acc33463de6ae4b7500

**Comment by raoulvdberge** [comment]
This is a problem with `com.minecolonies`, please report the bug to them. You could also try updating Forge if you're not on the latest version yet, as I heard this bug is prevented with newer Forge versions.

**Comment by Deylendor** [comment]
I am running the latest forge.

I made the server playable by temporary setting
B:removeErroringTileEntities=false to true in the forge.cfg file. 

I'll report this error to the Minecolonies team as well.  
Thank you very much for looking into this for me. Was worth it to make a github account.
