### ISSUE TITLE
[Suggestion] Have a display option of "craft only"

### ISSUE THREAD

**Issue by carstorm** [raoulvdberge/refinedstorage#1136]
On the display button have an option called "craft only" (with a potentially different name) that only allows you to craft stuff. Right now the "craftables only" option only says craft if there are none of said item in the system. There are times where I already have (i.e.) thousands of iron in my system but want to use RS auto crafting to turn say 1500 iron ore into ingots.

**Comment by way2muchnoise** [comment]
ctrl + shift + left click, will start the crafting window. [More info on the wiki page about the grid](https://refinedstorage.raoulvdberge.com/wiki/grid).
