### ISSUE TITLE
Feature request: IndustrialCraft Classic integration

### ISSUE THREAD

**Issue by Daenara** [raoulvdberge/refinedstorage#1137]
Hello,

I'm opening this issue on behalf of the small community for the now closed beta, soon released industrial craft classic mod for 1.10. It has this neat feature called cfoam where you can just spray cables with cfoam and then dry them with sand or wait for them to dry and you can then paint it over or use any texture on it. It's a great way to hide cable management and I would like this feature to be possible for refined storage cable, too. IndustrialCraft classic comes with an API for that, and quite a few other things that can be found [here](https://github.com/TinyModularThings/IC2Classic/tree/master/src/main/java/ic2/api). 

Refined Stroage already is partly compatible to ic2c, I can power the storage system with EU. I think that is because it shares much code and a good bit of the API with IndustrialCraft Experimental. 

I do hope you will think about it and possibly add it in. My hope is that on release it has good compatibility with many mods so it has a good launch and will be played by many people because it is a great mod.

Daenara

**Comment by raoulvdberge** [comment]
No, for these reasons:
1) In 1.11 the normal IC2 integration is removed because the API doesn't support capabilities
2) I don't like "special" mod facades, those mods should just support the standard MCMultiPart API instead of implementing their own facades. It's the same reason I'm not adding integration for EnderIO facades.

**Comment by Speiger** [comment]
1: First its event based. So no Capabilities needed.
2: MCMultipart and other things like that are laggy. TileEntity  compression is not a good idea.
3: 1.10.2 and 1.11 are the two main versions. I mean thaumcraft and other big mods are still going there.

**Comment by raoulvdberge** [comment]
I do not care.

**Comment by raoulvdberge** [comment]
I'm not debating about this, I've said no.
