### ISSUE TITLE
[Suggestion] NBT data for crafters

### ISSUE THREAD

**Issue by PapiDimmi** [raoulvdberge/refinedstorage#1139]
It would be very useful for moving or storing crafters if they had NBT data and thus kept their patterns upon breaking.

**Comment by raoulvdberge** [comment]
Use the wrench in dismantling mode (1.11, before you ask, not coming to 1.10)

**Comment by PapiDimmi** [comment]
Aww, come on! Why not for 1.10? 1.10 has a much bigger modding community than 1.11.

**Comment by raoulvdberge** [comment]
@PapiDimmi Quit the 1.10 nagging, I'm going to start banning people from the tracker who do this.
