### ISSUE TITLE
Crash in 1.9.4 either on world load or startup

### ISSUE THREAD

**Issue by Dragnier** [raoulvdberge/refinedstorage#114]
I have two crash reports for you. The first is with Quantum Storage installed. I thought it might have been the culprit but I still crashed with it removed so the second crash report is without Quantum Storage installed. All other mods stayed the same. No crashes since removing Refined Storage.

Report 1:
https://gist.github.com/Dragnier/65eeddc17ffbd4f242c9883e069683f8

Report 2:
https://gist.github.com/Dragnier/01a089e6787f084d6fb15fe61832145e

**Comment by raoulvdberge** [comment]
Some other mod is interfering with the RF api and is possibly having an outdated version of it installed.

**Comment by raoulvdberge** [comment]
To explain this further:
```
Caused by: java.lang.IllegalAccessError: tried to access field net.minecraft.item.ItemStack.field_77990_d from class cofh.api.energy.ItemEnergyContainer
```
This means some other mod is straight up trying to access `field_77990_d` (which is `stackTagCompund`) without using the getter.

The RF API bundled with RS is doing it correctly, using the getter:
```java
 @Override
    public int getEnergyStored(ItemStack container) {

        if (container.getTagCompound() == null || !container.getTagCompound().hasKey("Energy")) {
            return 0;
        }
        return container.getTagCompound().getInteger("Energy");
    }
```

**Comment by raoulvdberge** [comment]
Ah
```
* CoFHAPI (1.7.10R1.0.2) from [1.9.4] MachinePowerCraft-1.1.2.jar
```
MachinePowerCraft is using the CoFH 1.7.10 API...

**Comment by Dragnier** [comment]
Thanks for letting me know.
