### ISSUE TITLE
Importer whitelist does not work with the interface

### ISSUE THREAD

**Issue by PapiDimmi** [raoulvdberge/refinedstorage#1140]
I set an importer to import a specific item from an interface, but it imports all items.

**Comment by raoulvdberge** [comment]
Show me your setup.

**Comment by PapiDimmi** [comment]
An interface with an importer underneath it, along with some cables to my network.

The interface gets items and imports them to my RS system, but the whitelist on the importer is ignored.

**Comment by raoulvdberge** [comment]
Screenshots, please

**Comment by PapiDimmi** [comment]
![2017-04-07_23 35 29](https://cloud.githubusercontent.com/assets/25916106/24820745/ec2cb95c-1bea-11e7-8fe4-fdfe0a844c5f.png)

**Comment by VT-14** [comment]
The Interface itself is importing the items.

**Comment by PapiDimmi** [comment]
Oh, I didn’t think it could do that. Welp.

**Comment by VT-14** [comment]
@PapiDimmi Why are you downvoting Raoul's requests for more information in order to help you?

**Comment by PapiDimmi** [comment]
Because he asked for screenshots even though screenshots are unnecessary, as I thoroughly explained the situation.

I don’t see why I need to go into detail about why I gave a thumbs down emoji to his comments. It’s not a big deal, is it?

**Comment by raoulvdberge** [comment]
I always prefer to have screenshots of the situation so I can see what is going on. The reporter could've set the RS devices up in the wrong way, so I need to be sure it's an actual bug before I look into it further.

**Comment by PapiDimmi** [comment]
I set it up exactly as I explained to you. I thought you’d be able to give me the answer that @VT-14 gave me, but whatever.

**Comment by raoulvdberge** [comment]
In this case, you did set it up like described. But that is not always the case with everyone.

**Comment by PapiDimmi** [comment]
All right. This arguing is pretty pointless, considering how I’ve already solved my problem and we’re arguing over an emoji.

**Comment by PapiDimmi** [comment]
@raoulvdberge I don’t understand how you can set a whitelist or blacklist for interfaces.

**Comment by raoulvdberge** [comment]
You dont. Interfaces are for exporting given items.

**Comment by PapiDimmi** [comment]
Okay, then. Not a big deal.
