### ISSUE TITLE
[1.11.2] Add support of TechReborn energy

### ISSUE THREAD

**Issue by valentin616** [raoulvdberge/refinedstorage#1141]
The controller does not accept techReborn energy. It would be nice to add support.

**Comment by raoulvdberge** [comment]
RS 1.11.2 supports Forge Energy. I imagine their could be a problem with TR. Can you try with Actually additions for example and see if that works?

**Comment by valentin616** [comment]
Yes that work with Actually Additions. It's just for TechReborn. Cables do not connect.

**Comment by raoulvdberge** [comment]
Yep, then this is a TR issue.

TechReborn should emit Forge Energy, so this is an issue on their side. Please report it on their bug tracker.

**Comment by modmuss50** [comment]
TR doesn't push FE atm, this is an issue on our end.

**Comment by VT-14** [comment]
Definitely not my area of expertise, but aren't RF, Tesla, and Forge Energy push-based systems?

**Comment by modmuss50** [comment]
Yes, I just didn't get around to doing it for FE because I'm lazy :P

**Comment by VT-14** [comment]
Oh.  Sorry, I saw you were a contributor to RS and thought were saying it was on this end.  I didn't realize you were from Tech Reborn.

**Comment by alvarocastro** [comment]
How is the status of this? Just made a modpack with buildcraft + tech reborn + refined storage and while testing it I noticed I can't connect my TR battery with the RS controller.

**Comment by modmuss50** [comment]
It will be done when it's done.
