### ISSUE TITLE
Refined Storage thinks that I have double of everything in my drawers when using two external storages busses

### ISSUE THREAD

**Issue by PapiDimmi** [raoulvdberge/refinedstorage#1144]
I had one external storage bus connected to a drawer controller from Storage Drawers, and everything worked fine. I connected another external storage bus to the same drawer controller—so that I could get more whitelist slots—but then my Refined Storage system started thinking that I had double of everything in my drawers. Rather than 25 ender lillies, for example, Refined Storage said that I had 50. When I took one ender lilly out, 48 were remaining, so I don’t _actually_ had double of the items; Refined Storage just thought that I did.
****
**Minecraft version**: 1.10.2
**Refined Storage version**: 1.2.25 (latest for 1.10.2)
**Storage Drawers version**: 3.7.0 (latest for 1.10.2)
**Forge version**: 12.18.3.2272 (latest for 1.10.2)

**Comment by BrianEdmonds** [comment]
Why are you using a whitelist on the external storages? If the ender
lily is whitelisted on only one, it's still showing up as doubled inside
RS? I'd be unsurprised to see things doubled with a couple of
unconfigured external storages.

**Comment by PapiDimmi** [comment]
>Why are you using a whitelist on the external storages?

I figured that I didn’t really need to, so I stopped doing that.

>If the ender lily is whitelisted on only one, it's still showing up as doubled inside RS?

Yup.

**Comment by DarkHelmet433** [comment]
I've found one way around this is to have the external interfaces in separate modes.  eg: interface 1 is in insert-only mode with a whitelist. Interface 2 is in insert-only mode with a separate whitelist.  interface 3 is in extract-only mode, no whitelist.  RS seems to only "see" the items once via the extract-only mode interface.

Also, it's easier to use a drawer key and lock the entire drawer grid.  You can allocate drawer slots by manually inserting an item then the slot becomes available to RS.

When expanding high priority drawer grids myself, I place the drawer on the ground, lock it, use packing tape on it then break it. When reattached to the drawer grid it'll remember the lock state and won't accidentally have items put in it that I didn't intend.

**Comment by PapiDimmi** [comment]
>Also, it's easier to use a drawer key and lock the entire drawer grid. You can allocate drawer slots by manually inserting an item then the slot becomes available to RS.

Yeah, that’s what I started doing.

**Comment by raoulvdberge** [comment]
Note to self, this is caused by:

- Having multiple of the same storages in the list
- Having the `detectChanges` call in `NetworkNodeExternalStorage#update` which also calls it, even if it doesn't appear in the list

**Comment by raoulvdberge** [comment]
This is actually intended behavior. It doesn't cause any issues (no dupe bugs).

Also, if you set one of the external storage devices to insert only, the other to extract-only, you get the correct item counts.

It's the only way to get separate import/export priorities for external storage devices.
