### ISSUE TITLE
Security

### ISSUE THREAD

**Issue by rcistano** [raoulvdberge/refinedstorage#1148]
How would someone prevent someone else from accessing their system?

**Comment by raoulvdberge** [comment]
By using the Security Manager.

https://refinedstorage.raoulvdberge.com/wiki/security-manager

1.11 only.

**Comment by rcistano** [comment]
I am using 1.10.2 

The only Security Manager is the one from RFTools, nothing from this mod.

**Comment by raoulvdberge** [comment]
On 1.10.2 this functionality is not present.

**Comment by rcistano** [comment]
....OK

**Comment by rcistano** [comment]
Perhaps it should be, as not everyone is on 1.11+

**Comment by raoulvdberge** [comment]
Backporting 1.11 features is a lot of work.
