### ISSUE TITLE
Feature Request: Low Resource indicator on Crafting Grid

### ISSUE THREAD

**Issue by Dracon1023** [raoulvdberge/refinedstorage#115]
I think it would be nice if there was some way for the grid to indicate to you while you are crafting that the current recipe you are crafting will be the last one you are able to craft given resources. i.e. I am crafting chests and it tells me I am low on wood when I am only able to craft one more.

**Comment by JohnC94** [comment]
To add on to this, if you attempt to execute an autocraft that the system doesn't have resources for, can there be a warning or maybe show a list of required resources?

**Comment by RealGrep** [comment]
Really would like it to show you the materials it will require, and tell you if it's missing some ingredients it can't craft. That would be quite useful.

**Comment by Harith163** [comment]
@RealGrep that already exists it is called the crafting monitor.

**Comment by RealGrep** [comment]
Well, yeah, I know that. XD  I mean before you actually start the crafting itself. As it is, you place the order, then see it's missing resources. You also don't know what it will really require until the order is placed.

**Comment by Harith163** [comment]
How much would that functionality change? Not much IMO. If you see you that you lack a resource after placing a request you can always just cancel it.

**Comment by RealGrep** [comment]
It would be more efficient and clearer. You could also then see the material requirements for a certain number of items autocrafted before you start, and perhaps decide to order a different number. You would know what it takes to craft what you're requesting. Perhaps you would also have some idea of how much of certain resources you need to go out and get to accomplish your autocrafting.

When you go to a restaurant, do you order your food, not knowing the price, then cancel the order the cook has already started on when you see the price tag is too high? Would the cook like to know what ingredients he needs before he starts cooking it, gets part way through, then realizes he's missing something to complete the order?

**Comment by Harith163** [comment]
I get your point. It is a fair one.

However, from personal experience, by the time I have a full RS setup done, I have way more material than I need, If it is some lower level crafting OR I will be missing a few things that are essential for teh recipes (eg. a couple heads or nether stars) and I can keep that in mind. Since I would be resource gathering anyway, the "how much to make" decision would be made at a different point in the line to getting said Item.

**Comment by RealGrep** [comment]
I've autocrafted ultimate solars that require insane amounts of materials, before. Believe me, it's not so simple with such large recipes. Becomes an issue long before that. Not to mention, RS is much easier to get than what I was using at the time. You can get it fairly early, before you have tons of materials available for large crafting jobs. And estimating the raw materials you need is actually quite a task, if you try and do it by hand.

Ultimately, I think the way I'm proposing is plain superior. Is it strictly, absolutely necessary? No. Is it almost certainly better and a significant improvement? Probably, yes, in my opinion.

**Comment by Harith163** [comment]
Hey I am not arguing with you. It would certainly be a welcome addition to
the mod. I think that the crafting monitor would then loose it's purpose
and maybe we could ask Raoul to make it do something else. Maybe it could
be the sole way we can auto craft items? But that sort of defeats the
purpose. Dunno, I lost my train of thought somewhere there.

**Comment by RealGrep** [comment]
hehe No problem. :)

That's true, though, that the crafting monitor would be less useful at that point. Using it to autocraft items might not be a bad idea. It gives the block a single purpose, to handle autocrafting. But then, you'd probably want to make the crafting request from the crafting grid, or you'd have to move to another block to do it, which would break the workflow. Perhaps it could be considered simply a crafting CPU that manages and accomplishes the autocrafting. Perhaps multiple ones could have an advantage, like doing more things at once to speed things up.

Oh well, some ideas for Raoul to consider, anyway. :)

**Comment by Harith163** [comment]
aha! that's where I was. The crafting monitor could be destroyed completely, introducing the functionality that you suggested. A Good Idea would be to integrate what you said with another feature request of multi-threaded processing. We could get a multiblock structure that would enable a system to craft a given number of Items simultaneously, simulating multiple cpu's.

**Comment by RealGrep** [comment]
Yeah, I was sort of thinking in that direction. I like the idea.

**Comment by raoulvdberge** [comment]
Decided I'm not going to add this
