### ISSUE TITLE
Further API Support

### ISSUE THREAD

**Issue by LousyLynx** [raoulvdberge/refinedstorage#1151]
Hey, guys. I am writing a mod and would like support for further API support. For example, the ability to add custom API implementations to different things, or events for specific things. Right now, I want to make an addon to Refined Storage which adds channels. To do this, I would need to edit the NetworkNodeGraph. Being able to add a custom API implementation would be optimal because then I would be able to get all of the nodes, then check to see which ones should be connected. This is just something that I would like to be able to use, so it is not urgent, but I would like to be able to use it soon 😄

**Comment by raoulvdberge** [comment]
Being able to change the network graph is dangerous. What if another mod comes in and changes the network graph as well?

**Comment by LousyLynx** [comment]
That is why I threw out the events idea. Maybe rather than completely changing out the whole deal, what if there was a modular like system? Like the way that worlds are generated, and can be generated with different ones. I suppose it would be kind of like events but would handle more of the process so that someone __could__ make channels, for example. Still not entirely sure how this could work, but maybe a sort of a priority system. Like for something like channels, it is run last and ensures that the channels are 100% added.

**Comment by raoulvdberge** [comment]
We do have `INetworkNeighborhoodAware` these days:

https://github.com/raoulvdberge/refinedstorage/blob/mc1.11/src/main/java/com/raoulvdberge/refinedstorage/api/network/INetworkNeighborhoodAware.java

**Comment by LousyLynx** [comment]
Interesting. Is there somewhere more private we can talk about this in a more direct way?

**Comment by raoulvdberge** [comment]
Sure on IRC #refinedstorage on esper.net, I'm not on all the time though.

**Comment by raoulvdberge** [comment]
I'm closing this for now, we can talk about this on IRC.
