### ISSUE TITLE
Mod needs an code optimization BAD

### ISSUE THREAD

**Issue by Railgun69** [raoulvdberge/refinedstorage#1152]
#### Issue description:
mod slows down server tps super hard, even the devco ftb community had to ban most automation items and blocks including autocrafting in order to keep the server tps barely manageable
#### What happens:
the more complex the system the more badly the server laggs
#### What you expected to happen:
less lag
#### Steps to reproduce:
1. Make a server with both forge and bukkit
2. Make a system with lots of the mod's blocks with cables stretching across chunks
3. check the server's tps
...

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge: idk
- Refined Storage: idk
- Modpack: Sky factory 3 version 3.0.8

Does this issue occur on a server? [yes/no]
YES
#### If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here]

**Comment by raoulvdberge** [comment]
Fuck off
