### ISSUE TITLE
[Suggestion] Clear disk NBT data

### ISSUE THREAD

**Issue by PapiDimmi** [raoulvdberge/refinedstorage#1153]
Can you add a recipe where you put the disk in a crafting window and it clears its NBT data, allowing you to void all the items or fluids in a disk?

**Comment by raoulvdberge** [comment]
No

**Comment by PapiDimmi** [comment]
Why not?

**Comment by BrianEdmonds** [comment]
If you take the disk apart and put it back together again, doesn't that do the trick?

**Comment by PapiDimmi** [comment]
@BrianEdmonds What does “take the disk apart” mean?

**Comment by BrianEdmonds** [comment]
IIRC, can't you craft a disk somehow to separate the storage part from the housing?

**Comment by PapiDimmi** [comment]
I don’t see what that has to do with anything. I want to clear an existing disk, removing all items or fluids inside of it.

**Comment by BrianEdmonds** [comment]
And if you take it apart, and put it back together again, is it not 
cleared? It may not work, as I've not tried it, of course.

**Comment by PapiDimmi** [comment]
How do you take it apart? You can’t put a disk in a crafting table to clear it, which is what I’m suggesting here.

**Comment by BrianEdmonds** [comment]
RTFM, please. No really, spend a bit of time on the wiki, I found it 
enlightening when I did. As it says, sneak right click while holding a 
disk, and you'll get the parts.

**Comment by PapiDimmi** [comment]
I _did_ read the wiki, and I _did_ sneak-right-click with a disk, but nothing happened.

Either the wiki is wrong, or this only works in the 1.11.2 version of Refined Storage.

**Comment by BrianEdmonds** [comment]
It's definitely worked for me in the past, on 1.10.2. I don't have a 
system up currently I can double check on.

**Comment by PapiDimmi** [comment]
Sneak-right-clicking with a disk in my hand does absolutely nothing. I’ve tried it multiple times.

I am using the latest version of Refined Storage for Minecraft 1.10.2 (v. 1.2.25).

**Comment by raoulvdberge** [comment]
The disk has to be empty.

**Comment by PapiDimmi** [comment]
Oh, I see. That defeats the entire purpose of what I’m trying to do, which is remove all the items or fluids on a disk.

I don’t mind that you don’t want to add a feature like this, because you’re the developer, and you decide what you do with your mod (obviously), but I’d like to know _why_ you don’t want to add a feature like this, rather than just a vague “No” answer.

Is it because players could accidentally clear their disks? If that’s the case, you could either make this feature a config option that’s disabled by default, or you could add a verification step, so that players have to use a command or press a button or something in order to clear a disk. Either way, it would be super useful if you could clear disks, which, as far as I’m aware, you cannot do in the current version of the mod (for 1.10.2).

**Comment by raoulvdberge** [comment]
> Is it because players could accidentally clear their disks? 
Yes. It's a an easy thing to do and extremely destructive. So it's dangerous and will not be added.

> If that’s the case, you could either make this feature a config option that’s disabled by default
By this point you should know I don't add config options for those kind of things.

**Comment by PapiDimmi** [comment]
It’s extremely tedious to clear a disk manually, so I was hoping that you’d add something like this. Maybe it could be an option in the disk manipulator.

Oh well. It’s unfortunate that you won’t add it.

**Comment by BrianEdmonds** [comment]
Actually, having a "format disk" option in the manipulator sounds like 
a reasonable feature to me.

**Comment by PapiDimmi** [comment]
Yeah, I thought it might. It makes more sense than just sneak-right-clicking a disk whilst it’s in your hand, and it’s also safer.
