### ISSUE TITLE
Ore Change Using Interface

### ISSUE THREAD

**Issue by Peace7904** [raoulvdberge/refinedstorage#1156]
#### What you expected to happen:
Change the ore being processed for smelting
#### Steps to reproduce:
1. Place desired ore in middle slot of interface
2. Replace middle slot ore with ore not of value
3. Watch as first ingot continues to increase while second ore decreases using the second ore to produce the ingot
...

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge:
- Refined Storage:

Does this issue occur on a server? [yes/no]
Yes
#### If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here]
Video of process, tested in Single Player
https://youtu.be/3KcxM5fte0Q

**Comment by raoulvdberge** [comment]
This has been fixed as of b3ca4360e821f9102a71806df32cb6ab5352ca28.
