### ISSUE TITLE
Feature Request: Make Patterns editable.

### ISSUE THREAD

**Issue by calloatti** [raoulvdberge/refinedstorage#1157]
Make patterns editable by loading the pattern when inserting a used pattern in the Pattern Grid or the Processing Pattern Encoder.

Why? Sometimes a pattern need to be changed because of special cases or you just want to check/uncheck the OreDict checkbox.

Either do it automagically when a used Pattern is inserted or add a "Load Pattern" button?

**Comment by raoulvdberge** [comment]
nah, it's easy enough to just remake the pattern

**Comment by BrianEdmonds** [comment]
Unless it's particularly hard to implement, I think this would be a 
nice feature to have to. I've definitely wanted to change an existing 
pattern more than once.
