### ISSUE TITLE
One pattern on autocraft triggering the other pattern in a different crafter

### ISSUE THREAD

**Issue by Scatropolis** [raoulvdberge/refinedstorage#1159]
#### Issue description:
One pattern in a crafter on autocraft with redstone signal is triggering the other recipe.

#### What happens:
I have two recipes for Vibrant Alloy, one to smelt it in the alloy smelter and one to craft it from Vibrant Alloy Essence.  The second one is set to auto craft in a crafter but never seemed to work.  I finally realizing the other recipe was being triggered and ALL my materials were being used to create it from materials.  

#### What you expected to happen:
If I have the pattern that uses essence in the crafter and autocraft I expect it to use that one instead of the other one in a completely different crafter (not set to autocraft);

#### Version (Make sure you are on the latest version before reporting):
Foolcraft modpack 1.2.2

- Minecraft: 1.10.2
- Forge: 12.18.3.2254
- Refined Storage: 1.2.24

Does this issue occur on a server? [yes/no]  Don't know

#### If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here]

**Comment by raoulvdberge** [comment]
How much Patterns does the Crafter that is set to trigger on redstone hold?

**Comment by Scatropolis** [comment]
It's almost full.  I have other essence patterns and four loot bag patterns set to always run.

**Comment by way2muchnoise** [comment]
Well, it is auto crafting and works exactly like you would manually. It isn't just making stuff with that exact pattern. Although that would make more sense, but would make it so that it can't do more complex crafts. But food for thoughts a least.
