### ISSUE TITLE
[Feature Request] IC2 EU Support

### ISSUE THREAD

**Issue by NinjaKap** [raoulvdberge/refinedstorage#116]
Hello!
We've been messing around with Refined Storage for a while now, and recently reset our Map and included IC2. After making my system (Powering it with RF from an Electrical Engine), I figured why not try to power it with EU. Unfortunately, it didn't work. In AE1/AE2, the ME Systems can be powered with EU, so why not let Refined Storage do the same?

Thank You!

**Comment by raoulvdberge** [comment]
Thank you for the suggestion, but this is a duplicate of #98

I'll for sure add IC2 support. For now you could indeed use an electrical engine until support has been added.
