### ISSUE TITLE
Some blocks disconnect from the grid.

### ISSUE THREAD

**Issue by patrix87** [raoulvdberge/refinedstorage#1160]
#### Issue description:

Usually after server restart, some block are still passing energy but are disconnected from the grid.

![image](https://cloud.githubusercontent.com/assets/2144502/25008175/ed745cb2-2030-11e7-852c-fb27a39059a0.png)

#### What happens:

The grid will still work but the crafter won' t.

Switching the controller on and off won't affect the on / off status of the blocks in the group.

Removing and replacing the block fixes the issue.

It also affects importer.

#### Steps to reproduce:
1. unsure, it only happens in one group of crafters.

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge: 12.18.3.2254 ?
- Refined Storage: 1.2.25

Does this issue occur on a server? [yes/no]

yes, Feed The Beast : Beyond 1.3.0 vanilla setup.

**Comment by raoulvdberge** [comment]
#370 dupe
