### ISSUE TITLE
Mekanism's oxygen

### ISSUE THREAD

**Issue by forestbat** [raoulvdberge/refinedstorage#1162]
#### What you expected to happen:Using oxygen in network to deal with many mines。
And RS fluid storage disk is too small，than extracells。

#### Steps to reproduce:
1.
2.
3.
...

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge:12.18.3.2254
- Refined Storage:1.2.25

Does this issue occur on a server? [yes/no] No

#### If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here]

**Comment by raoulvdberge** [comment]
Make sure the importer is in fluid mode

And oxygen isn't a fluid

**Comment by calloatti** [comment]
> And oxygen isn't a fluid

It is.

**Comment by raoulvdberge** [comment]
Then his importer wasn't in fluid mode. Or, the inventory he's importing from doesn't provide a fluid handler.

**Comment by way2muchnoise** [comment]
Mekanism has its own fluid stuff, which aren't actually Forge Fluids. So no oxygen is likely not a "fluid"
