### ISSUE TITLE
Can't do auto order auto crafting

### ISSUE THREAD

**Issue by dancoool** [raoulvdberge/refinedstorage#1164]
#### Issue description:
I want to use same exact way auto order auto crafting in this video : https://www.youtube.com/watch?v=3Tc9cx1j6kM
use feature in refined storage. But i can't do it because external storage can't detect Interface

#### Steps to reproduce:
1. put Interface
2. put external storage on one of it's side

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge:
- Refined Storage: 1.2.22

Does this issue occur on a server? [yes/no] no

#### If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here]

**Comment by raoulvdberge** [comment]
RS does things differently than AE.

To keep a certain amount of items in stock, look at https://refinedstorage.raoulvdberge.com/wiki/autocrafting under "Always keep a certain amount of items in stock"
