### ISSUE TITLE
Weird bug in Wireless Grid when crafting tanks from EnderIO

### ISSUE THREAD

**Issue by calloatti** [raoulvdberge/refinedstorage#1166]
Use Wireless Grid to craft 2 EnderIO Tanks

![image](https://cloud.githubusercontent.com/assets/12817862/25064569/0cb3e2d4-21d3-11e7-8328-041b9650f174.png)

![image](https://cloud.githubusercontent.com/assets/12817862/25064552/d186210e-21d2-11e7-9a39-3a58d5d0960a.png)

![image](https://cloud.githubusercontent.com/assets/12817862/25064558/dc3aebac-21d2-11e7-9628-a63ad881d920.png)

Notice the 2 tanks are a new separate item:

![image](https://cloud.githubusercontent.com/assets/12817862/25064559/e3382d0c-21d2-11e7-957c-d59f3083a035.png)

Drag the 2 new tanks. Notice the quantities numbers: 2 and -2

![image](https://cloud.githubusercontent.com/assets/12817862/25064561/eb0c8dc0-21d2-11e7-9902-45349030ded2.png)

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge:12.18.3.2281
- Refined Storage:1.2.25

**Comment by calloatti** [comment]
Update: Recreated the pattern and now works as intended. Old pattern was no different than new pattern at least viasually.

**Comment by raoulvdberge** [comment]
Did you use JEI to make the first pattern?

**Comment by calloatti** [comment]
Yes I did. But I also used it to make the second one. I fact I use it 99.99% of the times I make a pattern. Even in the Pattern Encoder.

**Comment by HenryLoenwind** [comment]
Di the first pattern have oredict on and the second have it off? This seems to be what I am seeing, patterns with oredict on don't match with their own output.

**Comment by raoulvdberge** [comment]
I'm closing this issue as I think this has been fixed in 1.12, and also, 1.10.2 is unsupported.
