### ISSUE TITLE
Fluid Grid does not format quantity numbers resulting in text overflow

### ISSUE THREAD

**Issue by calloatti** [raoulvdberge/refinedstorage#1167]
Unlike The items Grid, the Fluid Grid does not format numbers with "K", resulting in too large numbers to fit the display width:

![image](https://cloud.githubusercontent.com/assets/12817862/25064675/7445de3c-21d5-11e7-96a8-15e68c97bf89.png)

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge:12.18.3.2281
- Refined Storage:1.2.25

**Comment by PapiDimmi** [comment]
x

**Comment by PapiDimmi** [comment]
x
