### ISSUE TITLE
[Suggestion] An “only disks” option for grids

### ISSUE THREAD

**Issue by PapiDimmi** [raoulvdberge/refinedstorage#1168]
Sometimes, I want to see how many items are in my disk, but the grid’s filled up with all the items in my storage drawers.

An option for the “Display” button in grids that _only_ shows items stored on the disks itself, not other containers using external storage buses, called “Only disks” or “No external storage,” for crafting grids, fluid grids, and regular grids would be a super useful feature. This would save players from having to remove their external store buses and then replace and reconfigure them later—which is pretty tedious.

I use the 1.10.2 version of this mod, by the way. If you were going to add this, I don’t know if you backport new features or not, but either way, I’m sure it’d be a useful feature for many people.

**Comment by raoulvdberge** [comment]
No, just filtering disks is too specific. Sometimes, you may also just want to see ext storage data. But I still don't like this feature either way.

**Comment by PapiDimmi** [comment]
What do you mean by “too specific”?

An option to only see external storage items would be nice as well.

Why don’t you like this feature? 😕

**Comment by raoulvdberge** [comment]
It's way too specific, meaning: it's not general enough.

**Comment by PapiDimmi** [comment]
I don’t understand what you mean.

Autocrafting is a feature of Refined Storage. You can choose to hide items that can be crafted—or show them only.

External storage is a feature of Refined Storage. I’m proposing a feature where you can choose to hide items stored outside of disks—or show them only.

How is that “too specific”? Just to clarify: I don’t want an option that only shows items in drawers from Storage Drawers; just items stored in any kind of external inventory.

**Comment by raoulvdberge** [comment]
The problem here is that when I add this feature (for both disks and external storages), that a new problem arises: what if you only want to see a specific storage?

What if I want to hide a specific storage?

What if I want to only see multiple storages?

What if I want to hide multiple storages?

So, if I introduce this very specific feature suddenly it would be incomplete because the above features aren't implemented.

What you want is something very specific, and to solve this I'd have to implement all above features as well, which is not worth it.

If you really want to see what is in a single specific disk, move the disk temporarily to a new RS network.

Or, disable all external storages at once by using a Relay.

**Comment by PapiDimmi** [comment]
I don’t understand why you “have” to add all these specific options just to add a more general option.

Here’s an idea: _just_ add the option to hide or only show items in external inventories, rather than adding all the more specific options that you mentioned. That’s much more simple.

By your logic, you _have_ to add an option to only see craftable items that have patterns in a specific crafter—or hide them. Each crafter would have to have a specific name or ID, and you’d have to be able to choose to show or hide each of them. No, that’s not how it goes. Just because X exist doesn’t mean that Xa, Xb, Xc, Xd, and Xe have to exist.

I’m not requesting something “very specific.” I’m just requesting an option to hide anything in any external inventory using external storage buses from Refined Storage. That way it’s much easier to tell exactly what is on a disk. It’s very annoying seeing all these items that are not on a disk when trying to identify what kind of items are on a specific disk. This is a feature that I, and probably many others, would find very useful, and it’s not specific at all.

Like I said, this option would be related to _one_ block in Refined Storage, just like the “Only craftables “ and “No craftables” are options that are related to _one_ block in Refined Storage.

If you were to add this option, you wouldn’t have to add anything else that’s remotely related to external storage; I don’t get why you think that. This would just be a general option that’d be useful in scenarios in which you want to clean up a disk or disks and don’t want to see items that are _not_ stored on the disk or disks.

**Comment by PapiDimmi** [comment]
I don’t understand why you “have” to add all these specific options just to add a general option.

Here’s an idea: _just_ add the option to hide or only show items in external inventories, rather than adding all the more specific options that you mentioned. That’s much more simple.

By your logic, you _have_ to add an option to only see craftable items that have patterns in a specific crafter—or hide them. Each crafter would have to have a specific name or ID, and you’d have to be able to choose to show or hide each of them. No, that’s not how it goes. Just because X exist doesn’t mean that Xa, Xb, Xc, Xd, and Xe have to exist.

I’m not requesting something “very specific.” I’m just requesting an option to hide anything in any external inventory using external storage buses from Refined Storage. That way it’s much easier to tell exactly what is on a disk. It’s very annoying seeing all these items that are not on a disk when trying to identify what kind of items are on a specific disk. This is a feature that I, and probably many others, would find very useful, and it’s not specific at all.

Like I said, this option would be related to _one_ block in Refined Storage, just like the “Only craftables “ and “No craftables” are options that are related to _one_ block in Refined Storage.

If you were to add this option, you wouldn’t have to add anything else that’s remotely related to external storage; I don’t get why you think that. This would just be a general option that’d be useful in scenarios in which you want to clean up a disk or disks and don’t want to see items that are _not_ stored on the disk or disks.

**Comment by raoulvdberge** [comment]
> I don’t understand why you “have” to add all these specific options just to add a general option.

I'd have to add them to make your non-general option general enough for inclusion in RS.

> Here’s an idea: just add the option to hide or only show items in external inventories, rather than adding all the more specific options that you mentioned. That’s much more simple.

That makes the feature incomplete, which is the point I'm trying to make the entire time already. I don't add incomplete features.

> By your logic, you have to add an option to only see craftable items that have patterns in a specific crafter—or hide them. Each crafter would have to have a specific name or ID, and you’d have to be able to choose to show or hide each of them. No, that’s not how it goes. Just because X exist doesn’t mean that Xa, Xb, Xc, Xd, and Xe have to exist.

No, a Crafter is something different than items stored. You can't compare the two.

> I’m not requesting something “very specific.” I’m just requesting an option to hide anything in any external inventory using external storage buses from Refined Storage. That way it’s much easier to tell exactly what is on a disk. It’s very annoying seeing all these items that are not on a disk when trying to identify what kind of items are on a specific disk. This is a feature that I, and probably many others, would find very useful, and it’s not specific at all.

You *are* requesting something very specific though.

> Like I said, this option would be related to one block in Refined Storage, just like the “Only craftables “ and “No craftables” are options that are related to one block in Refined Storage.

That's irrelevant.

> If you were to add this option, you wouldn’t have to add anything else that’s remotely related to external storage; I don’t get why you think that. This would just be a general option that’d be useful in scenarios in which you want to clean up a disk or disks and don’t want to see items that are not stored on the disk or disks.

Like I said, this is not a general option. 

> I don’t get why you think that.

I think that because this feature is too specific. To make it less specific and more general, the above features would have to be implemented.

But since I don't like this idea in the first place, I can't justify adding those features.

**Comment by PapiDimmi** [comment]
>>I don’t understand why you “have” to add all these specific options just to add a general option.

>I'd have to add them to make your non-general option general enough for inclusion in RS.

“Show/Hide external storages” = not specific.

Show/Hide a specific external storage, show/hide multiple ones, bla, bla, bla = very specific and totally unnecessary.

>>Here’s an idea: just add the option to hide or only show items in external inventories, rather than adding all the more specific options that you mentioned. That’s much more simple.

>That makes the feature incomplete, which is the point I'm trying to make the entire time already. I don't add incomplete features.

What do you mean by incomplete‽ Is the crafter incomplete because it doesn’t have an upgrade system—so you cannot upgrade it to add more slots? No, that’s just a feature that doesn’t exist; it doesn’t mean that the crafter is incomplete.

General = good.
Too specific = bad.
General but not too specific ≠ incomplete.

>>I’m not requesting something “very specific.” I’m just requesting an option to hide anything in any external inventory using external storage buses from Refined Storage. That way it’s much easier to tell exactly what is on a disk. It’s very annoying seeing all these items that are not on a disk when trying to identify what kind of items are on a specific disk. This is a feature that I, and probably many others, would find very useful, and it’s not specific at all.

>You _are_ requesting something very specific though.

I’m requesting something similar to something that already exists: the crafter and the grids’ ability to show or hide craftable items.

External storage is a feature of Refined Storage. Hell, by your logic, that feature is incomplete, because there’s no way to only show or hide items in external inventories in grids.

I’m just requesting a feature that’d be very useful, in my opinion. What do you do when you _just_ want to see a disk’s (or multiple disks’) contents, rather than being forced to see a bunch of things that aren’t even in the disk or disks? You _have_ to break every single external storage bus that you have and then replace them all later, in addition to reconfiguring them all. That’s just tedious and not worth it.

>>If you were to add this option, you wouldn’t have to add anything else that’s remotely related to external storage; I don’t get why you think that. This would just be a general option that’d be useful in scenarios in which you want to clean up a disk or disks and don’t want to see items that are not stored on the disk or disks.

>Like I said, this is not a general option.

Explain, please.

>>I don’t get why you think that.

>I think that because this feature is too specific. To make it less specific and more general, the above features would have to be implemented.

No offence, but I’m not quite sure you know what “general” means.

”General” = affecting all or most things.
“Specific” = the opposite of general; affecting a single, defined thing.

A general option would be the ability to hide or only show items in external inventories attached to an external storage bus. Specific options would be the ability to choose exactly which external inventories to show or hide, which, again, is very unnecessary and, most likely, totally useless.

**Comment by PapiDimmi** [comment]
>>I don’t understand why you “have” to add all these specific options just to add a general option.

>I'd have to add them to make your non-general option general enough for inclusion in RS.

“Show/Hide external storages” = not specific.

Show/Hide a specific external storage, show/hide multiple ones, bla, bla, bla = very specific and totally unnecessary.

>>Here’s an idea: just add the option to hide or only show items in external inventories, rather than adding all the more specific options that you mentioned. That’s much more simple.

>That makes the feature incomplete, which is the point I'm trying to make the entire time already. I don't add incomplete features.

What do you mean by incomplete‽ Is the crafter incomplete because it doesn’t have an upgrade system—so you cannot upgrade it to add more slots? No, that’s just a feature that doesn’t exist; it doesn’t mean that the crafter is incomplete.

General = good.
Too specific = bad.
General but not too specific ≠ incomplete.

>>I’m not requesting something “very specific.” I’m just requesting an option to hide anything in any external inventory using external storage buses from Refined Storage. That way it’s much easier to tell exactly what is on a disk. It’s very annoying seeing all these items that are not on a disk when trying to identify what kind of items are on a specific disk. This is a feature that I, and probably many others, would find very useful, and it’s not specific at all.

>You _are_ requesting something very specific though.

I’m requesting something similar to something that already exists: the crafter and the grids’ ability to show or hide craftable items.

External storage is a feature of Refined Storage. Hell, by your logic, that feature is incomplete, because there’s no way to only show or hide items in external inventories in grids.

I’m just requesting a feature that’d be very useful, in my opinion. What do you do when you _just_ want to see a disk’s (or multiple disks’) contents, rather than being forced to see a bunch of things that aren’t even in the disk or disks? You _have_ to break every single external storage bus that you have and then replace them all later, in addition to reconfiguring them all. That’s just tedious and not worth it.

>>If you were to add this option, you wouldn’t have to add anything else that’s remotely related to external storage; I don’t get why you think that. This would just be a general option that’d be useful in scenarios in which you want to clean up a disk or disks and don’t want to see items that are not stored on the disk or disks.

>Like I said, this is not a general option.

Explain, please.

>>I don’t get why you think that.

>I think that because this feature is too specific. To make it less specific and more general, the above features would have to be implemented.

No offence, but I’m not quite sure you know what “general” and “specific” mean.

”General” = affecting all or most things.
“Specific” = the opposite of general; affecting a single, defined thing.

A general option would be the ability to hide or only show items in external inventories attached to an external storage bus. Specific options would be the ability to choose exactly which external inventories to show or hide, which, again, is very unnecessary and, most likely, totally useless.

**Comment by raoulvdberge** [comment]
At this point, I have the feeling that you are ignoring some points I've been making just to proceed the conversation.

I'm all for discussion about features, but if a modder says they won't implement a given feature, then you need to learn to respect that. Accepting a "no" isn't that difficult.

**Comment by PapiDimmi** [comment]
The reason I think that this feature would be useless is this: What if you have a _bunch_ of external inventories connected to external storage buses from Refined Storage, and you have some disks in which you’d really like to remove some items. You have no idea which items are in the disks and which are in external inventories. What if you have 50k cobblestone in a disk and 50k cobblestone in an external drawer? You can’t tell, since there’s no option to aid you.

Anyway, if you don’t want to implement a feature, that’s fine. It’s _your_ mod.

I continued arguing, however, because I don’t understand your reasoning.

I’m not ignoring any of your points; I replied to every single one of them. I’d appreciate if you replied to _my_ points. I just want to understand what you mean.

**Comment by raoulvdberge** [comment]
Your responses indicate that you don't understand what I'm talking about.

Since I'm pretty sure that you *do* know what I mean, I won't proceed the discussion.

I could respond to every point you're making, but let's get to the fundemental problem:

>> I'd have to add them to make your non-general option general enough for inclusion in RS.

> “Show/Hide external storages” = not specific.
Show/Hide a specific external storage, show/hide multiple ones, bla, bla, bla = very specific and totally unnecessary.

There is a difference between specific and general.

When implementing a feature, I want it to be as general as possible. This is a design pattern that you see through RS. If a feature is not general enough, it will not be used by enough people to justify the addition.
