### ISSUE TITLE
suggestion(refined storage 1.11.2)

### ISSUE THREAD

**Issue by SDUBZ** [raoulvdberge/refinedstorage#1169]
i would like to hide all my cables so i was just wonder if you could add some support to cover them with chisel and bits covers or any multipart cover due to exports and importers not being compat with any type of cover or maybe add a facade system so we can hide the components we dont want exposed to the viewing eye

**Comment by raoulvdberge** [comment]
1.11.2 already has support for MCMultipart. We're now just waiting until it comes out.
