### ISSUE TITLE
Feature Request: a way to clear patterns

### ISSUE THREAD

**Issue by JohnC94** [raoulvdberge/refinedstorage#117]
Can we have a method to clear patterns? Maybe something like AE2, throw it in a crafting grid to clear it?

**Comment by raoulvdberge** [comment]
There you go :)

**Comment by JohnC94** [comment]
Thank you! Started really getting into refined storage yesterday, loving it so far.

**Comment by raoulvdberge** [comment]
Good to hear, an update is coming out in a few minutes. :)
