### ISSUE TITLE
R/S Crafting: Infinite Glass cutters

### ISSUE THREAD

**Issue by Hawkeye50Cal** [raoulvdberge/refinedstorage#1170]
Found an issue in my system where you can infinitely craft glass cutters in SkyFactory 3.
if  you try and fix 1 glass cutter with another one in the crafting grid, it will just continuously make glass cutters without taking resources.
All mods are up-to-date with current skyfactory 3 modpack version

o/ 
Hawkeye50Cal

**Comment by raoulvdberge** [comment]
This is an Extra Utilities bug.
