### ISSUE TITLE
Wireless crafting terminal and other dimension issues

### ISSUE THREAD

**Issue by jeridan** [raoulvdberge/refinedstorage#1173]
#### Issue description:
Wireless crafting terminal doesn't work in other dimensions
#### What happens:
When in another dimension, using the terminal does not open
#### What you expected to happen:
Use terminal and access storage system
#### Steps to reproduce:
1.Setup network transmitter in overworld.  Have wireless terminal linked to terminal in the overworld
2.Setup network receiver and wireless transmitter in another dimension.  I tested the nether and aroma's mining world.
3.Can use wireless terminal in overworld.  Doesn't work in other dimension.  Have placed terminal in other dimension and it does access storage.  Another note, you get no wireless transmitter error when there isn't one.  No error with one.
...

#### Version (Make sure you are on the latest version before reporting):
- Modpack: FTB Beyond 1.5.3
- Minecraft: 1.10.2
- Forge: 12.18.3.2254
- Refined Storage: refinedstorage-1.2.25

Does this issue occur on a server? [yes/no]
On SSP, no server to test.
#### If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here]

**Comment by raoulvdberge** [comment]
Both areas have to be chunkloaded

**Comment by jeridan** [comment]
Really wish you wouldn't close this because both areas are chunkloaded.

**Comment by jeridan** [comment]
Would have been a much better response to say that the wireless crafting terminal must linked to a normal crafting terminal on the same network segment your wirelessly connecting to.

**Comment by raoulvdberge** [comment]
That speaks for itself.

**Comment by raoulvdberge** [comment]
Wait... The wireless crafting terminal is not even from RS. RS only has normal terminals.

You are probably using this mod: https://minecraft.curseforge.com/projects/wireless-crafting-grid

In that case, you even made the issue on the wrong issue tracker. -.-

**Comment by jeridan** [comment]
That does appear to be the case.  I apologize, but in my defense the item information doesn't identify that it is from a separate mod.

![2017-04-24_21 00 19](https://cloud.githubusercontent.com/assets/5779504/25365937/d4b84d32-2931-11e7-958f-8e7ff1ad930d.png)
