### ISSUE TITLE
Autocrafting null deref (1.2.22 ... )

### ISSUE THREAD

**Issue by sithrak** [raoulvdberge/refinedstorage#1174]
Realized after I opened that I'm way behind on version, but it would still be nice to know what causes this so I can avoid it in the future. gonna kill the crafter blocks with MCEdit to recover my server for now

#### Issue description:
Was doing some autocrafting, server crashed, now crashes on load.
#### What happens:
Null dereference...

#### What you expected to happen:
The server not to crash...

#### Steps to reproduce:
We were autocrafting compressed cobble, redstone blocks, and added glowstone dust -> glowstone a few seconds before the crash occured. 
...

#### Version (Make sure you are on the latest version before reporting):
refinedstorage-1.2.22.jar
FTB SkyFactory 3 download from their website, no mod changes from that configuration.

Does this issue occur on a server? [yes]

#### If a (crash)log is relevant for this issue, link it here:
`
`---- Minecraft Crash Report ----

WARNING: coremods are present:
  literalascension (literalascension-1.10.2-1.0.1.1.jar)
  Brandon's Core (BrandonsCore-1.10.2-2.1.4.92-universal.jar)
  BookshelfLoadingPlugin (Bookshelf-1.10.2-1.4.3.340.jar)
  ShetiPhian-ASM (shetiphiancore-1.10.0-3.3.7.jar)
  SurgeLoadingPlugin (Surge-1.10.2-1.1.0.68.jar)
  SFRCore (SolarFluxReborn_1.10.2-2.6r.jar)
  ForgelinPlugin (Forgelin-1.4.0.jar)
  LoadingPlugin (RandomThings-MC1.10.2-3.7.7.jar)
  LoadingPlugin (ResourceLoader-MC1.9.4-1.5.1.jar)
  NWRTweak (redstonepaste-mc1.9.4-1.7.4.jar)
  CCLCorePlugin (CodeChickenLib-1.10.2-2.5.6.233-universal.jar)
  TransformerLoader (OpenComputers-MC1.10.2-1.6.2.7.jar)
  RebornCoreASM (RebornCore-1.10.2-2.13.4.128-universal.jar)
  ChiselCorePlugin (Chisel-MC1.10.2-0.0.8.12.jar)
  NEICorePlugin (NotEnoughItems-1.10.2-2.1.3.201-universal.jar)
  AppleCore (AppleCore-mc1.10.2-2.1.1.jar)
  Default Options (DefaultOptions_1.10.2-6.1.5.jar)
  EnderCorePlugin (EnderCore-1.10.2-0.4.1.65-beta.jar)
  llibrary (llibrary-1.7.4-1.10.2.jar)
  Do not report to Forge! Remove FoamFixAPI (or replace with FoamFixAPI-Lawful) and try again. (foamfix-0.6.1-anarchy.jar)
  BiomeTweakerCore (BiomeTweaker-1.10.2-2.1.230.jar)
Contact their authors BEFORE contacting forge

// On the bright side, I bought you a teddy bear!

Time: 4/17/17 1:40 AM
Description: Ticking block entity

java.lang.NullPointerException: Ticking block entity
        at java.util.ArrayList.removeIf(ArrayList.java:1405)
        at com.raoulvdberge.refinedstorage.apiimpl.autocrafting.task.CraftingTask.update(CraftingTask.java:393)
        at com.raoulvdberge.refinedstorage.tile.TileController.func_73660_a(TileController.java:275)
        at net.minecraft.world.World.func_72939_s(World.java:1804)
        at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:620)
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:709)
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387)
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
        at java.lang.Thread.run(Thread.java:745)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
        at java.util.ArrayList.removeIf(ArrayList.java:1405)
        at com.raoulvdberge.refinedstorage.apiimpl.autocrafting.task.CraftingTask.update(CraftingTask.java:393)
        at com.raoulvdberge.refinedstorage.tile.TileController.func_73660_a(TileController.java:275)

-- Block entity being ticked --
Details:
        Name: refinedstorage:controller // com.raoulvdberge.refinedstorage.tile.TileController
        Block type: ID #2437 (block.refinedstorage:controller // com.raoulvdberge.refinedstorage.block.BlockController)
        Block data value: 0 / 0x0 / 0b0000
        Block location: World: (1141,41,12), Chunk: (at 5,2,12 in 71,0; contains blocks 1136,0,0 to 1151,255,15), Region: (2,0; contains chunks 64,0 to 95,31, blocks 1024,0,0 to 1535,255,511)
        Actual block type: ID #2437 (block.refinedstorage:controller // com.raoulvdberge.refinedstorage.block.BlockController)`

[pastebin/gist/etc link here]

**Comment by raoulvdberge** [comment]
#1016
