### ISSUE TITLE
[Suggestion] External Storage with Interface and Single-Craft upgrade.

### ISSUE THREAD

**Issue by Yusunoha** [raoulvdberge/refinedstorage#1175]
I'd love being able to use an external storage onto an interface and access the inventory of the interface like that. what I'd like to be able to do is set the interface to autocraft an item and keep a certain number of it in the interface, and through the external storage I'd be able to access those autocrafted items.

for this to work though 2 things would need to be changed. currently an external storage isn't able to read the inventory of the interface at all. for this suggestion that does need to happen, but you'd need to set the external storage to extract only. second thing what would need to be changed is if you use an crafting upgrade in the interface, another button would need to show up in the GUI where you'd be able to select the interface to autocraft the requested items only, otherwise you'd create a loop between the external storage and interface where the interface would only craft 1 item which will endlessly get looped between the interface and the external storage.

with this you'll have a compact way of keeping a certain number of crafted items in the system.

another suggestion I'd like to see is a single-craft upgrade. with this upgrade the system will try to craft a requested item only one at a time. with this upgrade you'll be able to craft items from other mods that can only handle 1 crafting process at a time (for example Botania with the runes and the terrasteel, crafting more than 1 at a time will interrupt the crafting process).

if for example you'd want to craft 64 stone bricks and use this upgrade, the system will export 4 stone and wait for 4 stone bricks to be put into the system before it sends out another 4 stone, and it'll continue this until the crafting job is done.

**Comment by raoulvdberge** [comment]
Both are already implemented in 1.11
