### ISSUE TITLE
[1.10.2 - 1.2.25] External Storage slows down interaction with crafting grid

### ISSUE THREAD

**Issue by neoc666** [raoulvdberge/refinedstorage#1176]
Sky Factory 3 with RS updated to 1.2.25 in a single player game; 6GB of RAM reserved for Minecraft

I'm using an external storage interface (whitelisted to 3 items) connected to a drawer controller from Storage Drawers which again is connected to one compacting drawer and two 1x1 drawers, all locked to specific items.

Pulling out items (which are NOT those stored externally) via crafting grid and manually putting items in it is very slow, also crafting items multiple times (clicking quickly on the output slot will halt every seven items or so for a moment). Inserting items via JEI (+) can be very slow for the first time (repeating the same recipe is faster, probably because of some caching going on). This all happens even if the external storage is configured to insert only - in which case it would never have to check the storage drawers for items when pulling items. In fact external storage which is configured insert only ONLY has to be checked when inserting items into the grid which are whitelisted in the external storage. Clearly this optimization doesn't take place.

**Comment by raoulvdberge** [comment]
https://refinedstorage.raoulvdberge.com/wiki/profiling

**Comment by raoulvdberge** [comment]
Missing profiling report.
