### ISSUE TITLE
[1.11.2] Adding a recipe with Craft Tweaker using .reuse() doubles items in the Crafting Grid

### ISSUE THREAD

**Issue by dirk251272** [raoulvdberge/refinedstorage#1177]
#### Issue description:
Items that are supposed to be reused instead of consumed are doubled when the actual recipe is crafted in RS's Crafting Grid.
#### What happens:
I've added a new recipe with Craft Tweaker like this:
`recipes.addShaped(<woot:skull:0>, [[<woot:yahhammer>.reuse(), <minecraft:iron_block>, null], [<ore:itemSkull>, <woot:dye:4>.reuse(), <ore:itemSkull>], [null, <minecraft:obsidian:*>.reuse(), null]]);`
.reuse() indicates that the item is not consumed but given back after crafting.
Using the recipe in a regular crafting bench has the expected result of the items with the .reuse() function not being consumed.
Using the same recipe in the Crafting Grid will produce the result of the recipe but also doubles the items with the .reuse() function (in my example the <woot:yahhammer> and <minecraft:obsidian:*>
#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.11.2
- Forge:1.11.2-13.20.0.2282
- Refined Storage: 1.4.2

Does this issue occur on a server? [yes/no]
It occurs on a server.
#### If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here]

**Comment by raoulvdberge** [comment]
RS supports items that stay in the crafting grid, maybe this is a Craft Tweaker issue.

Does this bug with a normal crafting table as well?

**Comment by dirk251272** [comment]
It works on vanilla and modded tables just fine.

**Comment by raoulvdberge** [comment]
This is a Craft Tweaker problem. RS handles remaining items properly.
