### ISSUE TITLE
Cable Facades [Feature Request]

### ISSUE THREAD

**Issue by meeshabeez** [raoulvdberge/refinedstorage#1178]
I hope I'm posting this to the right place.  I apologize in advance if it doesn't belong here and will happily take it down and move it to a more appropriate place.

I love that Refined Storage is compatible with Storage Drawers because sometimes I like seeing what resources I have available without having to click into a GUI.    What I don't love is having an exposed conduit system, but sometimes there's just no getting around it.   I think that it would be really rad if Refined Storage offered cable facades (to disguise any extra cabling that might be exposed) for a seamless fit and finish.

(Also, I will admit that that I hadn't looked too hard into wireless options.  I tinkered a little, but wasn't having any luck/success.  If the external storage node words wirelessly, can someone let me know?)

That said, I love, love, love Refined Storage and its ease of use.  Thank you for making such an awesome (and fun) mod!  Cheers!

**Comment by calloatti** [comment]
In 1.10.2 I use Simple Covers mod to hide the RS cables. Just create covers of the material you want.

**Comment by way2muchnoise** [comment]
You can use any mcmultipart or Chisel and Bits piece, so that should cover all your covering needs. *pun intended*
