### ISSUE TITLE
Extreme reactors items not showing in storage

### ISSUE THREAD

**Issue by hom3gr0wn** [raoulvdberge/refinedstorage#1180]
#### Steps to reproduce:
1. place yellowrite into storage
2. type yellow into search
3.
...

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge:
- Refined Storage:

Does this issue occur on a server? [yes/no] n/a

#### If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here]

**Comment by raoulvdberge** [comment]
Incomplete bug report.

**Comment by hom3gr0wn** [comment]
how is it incomplete i see people with hardly anything in there.
