### ISSUE TITLE
items disapearing from RS

### ISSUE THREAD

**Issue by hom3gr0wn** [raoulvdberge/refinedstorage#1181]
#### Steps to reproduce:
1. place ER2 item into grid
2. search for item placed
3. even smelting from ender io and piping into RS it disapears
...

#### Version (Make sure you are on the latest version before reporting):
Direwolf 2.0
- Minecraft: 1.10.2
- Forge:  12.18.3.2254
- Refined Storage: 1.2.23

Does this issue occur on a server? [yes/no] yes

**Comment by way2muchnoise** [comment]
Forge version, RS version, ER2 version and "even smelting from ender io and piping into RS it disapears" what does that sentence even mean?

**Comment by hom3gr0wn** [comment]
I smelted yelowrite ore into Ender io and it goes int rs but nothing shows up there from extreme reactors

**Comment by raoulvdberge** [comment]
Are there any storages that are in "Insert-only" mode?

**Comment by hom3gr0wn** [comment]
no just a basic storage system nothing automated other than transfering from chests to grid

**Comment by raoulvdberge** [comment]
I doubt it. Double-check, please.

**Comment by hom3gr0wn** [comment]
ive checked everything and nothing is set to insert only

**Comment by hom3gr0wn** [comment]
i can see 3 things from extreme reactors in the grid but yellowrite, reactor casings, acces ports, don't show up in the grid they just disapear

**Comment by raoulvdberge** [comment]
Sorry, I can't reproduce this nor do I think this is an issue on RS' end.
