### ISSUE TITLE
[1.11.2] GUI conflict with CraftingTweaks installed

### ISSUE THREAD

**Issue by kwpugh** [raoulvdberge/refinedstorage#1184]
#### Issue description:
Updated to the latest Refined Storage.   When in a crafting terminal, the extra buttons from CraftingTweaks are overlaid onto the player inventory.

#### What happens:
See above

#### What you expected to happen:
CraftingTweaks buttons should align to crafting grid in crafting terminal

#### Steps to reproduce:
1. Load latest RS
2. click into crafting terminal
3.
...

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.11.2
- Forge: forge-1.11.2-13.20.0.2282-universal.jar
- Refined Storage: refinedstorage-1.4.3.jar

Does this issue occur on a server? [yes/no]
YES

#### If a (crash)log is relevant for this issue, link it here:
Server does not crash

[pastebin/gist/etc link here]

Screenshot of crafting terminal:  http://imgur.com/a/FM7OJ

**Comment by raoulvdberge** [comment]
This is because of the resizable grid, it doesn't adapt. I'm thinking of removing CraftingTweaks support entirely from the mod. It conflicts with the grid keybindings.

**Comment by raoulvdberge** [comment]
@blay09 Is it possible to reposition the buttons / have dynamic button position? Also, how can I make it stop conflicting with RS keybindings?

**Comment by blay09** [comment]
There's the `GetGridStartFunction` tag that can be set to a function class name (similar to `ContainerValidPredicate`) which should return the slot number of the first slot in the crafting grid.

For the hotkey issue Forge added [these boolean flags](https://github.com/MinecraftForge/MinecraftForge/pull/3438) you can set to true if you do not wish `GuiScreenEvent.xxx.Post` to be fired. That said, Crafting Tweaks is currently still using `.Pre` events, so I'll have to fix that on my side too.

I'll send a PR with the above later today if you don't beat me to it.

**Comment by raoulvdberge** [comment]
This bug has been fixed as of 3d9c7890b68a0e46e02305812eae2a4f64cbfbcc
