### ISSUE TITLE
Foolcraft Too Many Tileentities Produced By Refined Storage Badly Lags Server

### ISSUE THREAD

**Issue by theaardvarker** [raoulvdberge/refinedstorage#1185]
#### Issue description:
When I start the server the tile entities begin low and start increasing.  This causes lag and the server is unplayable.  If I remove refined storage the tileentities do not increase and lag is not present.  If I keep refined storage but remove all mods that external storage can hook into then the tileentities and lag is still present.

#### What happens:
Refined storage causes ever-increasing tileentities and a bunch of lag.

#### What you expected to happen:
I expected the server to be playable.

#### Steps to reproduce:
Start server and wait.

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge: 12.18.3.2281
- Refined Storage: 1.1.25

Does this issue occur on a server? [yes/no]
yes

#### If a (crash)log is relevant for this issue, link it here:

Here is an issue report I opened on the foolcraft page about this.  A lot of information is posted there.
https://github.com/scalda/FoolCraft/issues/350

**Comment by raoulvdberge** [comment]
tps://refinedstorage.raoulvdberge.com/wiki/profiling

**Comment by theaardvarker** [comment]
@raoulvdberge Okay, I ran it.
[samplerreport.zip](https://github.com/raoulvdberge/refinedstorage/files/952983/samplerreport.zip)

**Comment by raoulvdberge** [comment]
Looking at your sampler report, Refined Storage barely appears in it.

![x](https://raoulvdberge.com/qpz22T)

Looks like chickens are causing a lot of lag.

![x](https://raoulvdberge.com/KpLQHM)

Here it looks like ExU is causing some issues.

The External Storage isn't contributing any significant load as compared to chickens, for example (50ms vs 1ms)

I'm gonna go ahead and assume this is not an RS issue.

**Comment by raoulvdberge** [comment]
Also, it looks like you do not know what you are talking about. Tile entities don't "increase", tile entities only increase when a player places one (a block).

**Comment by theaardvarker** [comment]
@raoulvdberge When I remove refined storage and nothing else the tps is 20 and the tileentities decrease from whatever tens of thousands number they are in to one thousand.  When I remove chickens the lag stays and the tileentities stay. RS is definitely the problem even if it isn't showing up in the report.

**Comment by raoulvdberge** [comment]
RS doesn't cause increasing tile entities. It's not possible. Also, I'm basing it off the report since I basically have nothing else to base myself on.

**Comment by theaardvarker** [comment]
https://pastebin.com/EPYd7g6Y  This is what happens when I start the server and run the tps command.  The tileentities clearly shoot up.  When I take rs out and do this they are constant.

**Comment by raoulvdberge** [comment]
I never used TickProfiler, so I don't know what those numbers mean. But tile entities don't just get magically added, there is literally 0 code in RS that does that.

**Comment by theaardvarker** [comment]
Yeah, it doesn't make sense to me it's generating tileentities.  But even the standard /cofh tps command agrees with the large numbers and if anyone logs on the tps is very erratic.  If I take rs off of the server the lag is gone and the tileentities low.  I haven't run this specific profiler before you recommended it, but from every test before when rs is not present the problem doesn't happen.  Anyway, thanks for trying, I hope this doesn't become an issue for a lot of people.

**Comment by raoulvdberge** [comment]
I wish I could fix it, but the profiling report you sent me doesn't contain anything RS related (well it does, but nothing significant). Did you generate the report when the lag was the worst?

**Comment by theaardvarker** [comment]
@raoulvdberge No, I generated it when only I was on the server.  When more people try to play and load more rs systems at once it gets worse.

**Comment by raoulvdberge** [comment]
Well, when that happens, make sure to send me a NPS file again.

**Comment by theaardvarker** [comment]
@raoulvdberge Hey, I never ran the sampler again, but I did end up finding the issue and am able to replicate it in any new world.  It is a foolcraft specific issue.  Network transmitters are the cause of the increasing tileentities and lag.  If I remove them and have other blocks from refined storage the issues do not occur.  If I do not use foolcraft and just install refined storage and storagedrawers then the problem does not occur when the transmitters are present.  There must be some mod conflict or something.  Anyway, just thought I'd let you know this information and I'll be asking about it on the foolcraft github issue page.

**Comment by raoulvdberge** [comment]
Cool. It is most likely a chunk that keeps loading/unloading and thus causes network rebuilds and that causes lag again.
