### ISSUE TITLE
Auto Crafting Bug

### ISSUE THREAD

**Issue by Neptitude** [raoulvdberge/refinedstorage#1186]
#### Issue description:
Bug with the auto crafting system
#### What happens:
My iron blocks are disappearing when I put my Gold Block to Gold Ingot Pattern in.
#### What you expected to happen:
To make gold ingots
#### Steps to reproduce:
1. Make Pattern saying to craft Gold Ingots from Gold blocks
2. Put in Crafter and trigger autocraft with redstone to true
3. Put Iron blocks in Storage System
...

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge: 12.18.3.2254
- Refined Storage: 1.2.25

Does this issue occur on a server? [yes/no]
Unaware
#### If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here]

**Comment by raoulvdberge** [comment]
#1029
