### ISSUE TITLE
Feature Request: rebind grid click functions, nevermind

### ISSUE THREAD

**Issue by JohnC94** [raoulvdberge/refinedstorage#119]
Would it be possible to add the click inputs to the controls/keybindings gui so we could rebind them to something else?

another request in the same day, i know, sorry :)

**Comment by raoulvdberge** [comment]
What specific inputs do you want to rebind?

**Comment by raoulvdberge** [comment]
You mean this table?

https://github.com/raoulvdberge/refinedstorage/wiki/Grid#inputs
