### ISSUE TITLE
MC 1.11.2 RS 1.4.3: Filter problem

### ISSUE THREAD

**Issue by Knito58** [raoulvdberge/refinedstorage#1191]
#### Issue description:
Cannot set filter to accept all kinds of enchanted books in external storage.

#### What happens:
Only the enchanted book which is put into the filter goes to the crate.

#### What you expected to happen:
All enchanted books I insert go to the crate.

#### Steps to reproduce:
1. External crate from actually additions
2. External storage from RS with high prio (20)
3. Filter in external storage (crafted) with enchanted book knockback II and a nametag
4. Doesn't matter whether nbt or dam val is on or not
...

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.11.2
- Forge: 13.20.0.2285
- Refined Storage: 1.4.3

Does this issue occur on a server? No, single player

#### If a (crash)log is relevant for this issue, link it here:

didn't crash - I'm happy!

**Comment by valentin616** [comment]
You just have to set "Compare NBT" in the left side to no ;)

**Comment by raoulvdberge** [comment]
That is what I'm thinking as well. Can you double check? "Compare NBT" has to be set to "Yes".

**Comment by valentin616** [comment]
I tried and it must be set to  "No" so that all enchanted books can be stored.

**Comment by Knito58** [comment]
Still doesn't work. I set the hook at nbt or I clear it: same result. The filter does not respect nbt checkbox in any way. @Those who commented: You have the same version as the one I reported?

**Comment by valentin616** [comment]
I have 1.4.4 and it work.

**Comment by Knito58** [comment]
Thank you Valentin616. I updated to 1.4.4. Still not working for me. What am I possibly doing wrong in this case? Should nbt be checked or not? No matter what I chose, its always the same result for me. 

@offtopic
The filter's interface gives no hint what each switch should do. Of course its obvious - for the programming guy. Poor user me has to fuddle through mystic configuration options. Does NBT need to be checked to respect NBT values? Or checked to ingore them? Some little mouse-over text lines might possibly enlight the user's mind. 

For me, both options - the checked and the unchecked nbt in the filter's menu - do not work as expected.

Beside this bug I'm totally content with RS. Will not start MC without this mod in the future.

**Comment by raoulvdberge** [comment]
I can't reproduce your problem. This is my configuration, with an external storage connected to a chest:

![x](https://raoulvdberge.com/3haUpt)
(with "Compare nbt" toggled to "No")

I can add any book now:
![x](https://raoulvdberge.com/CjDkJn)

**Comment by Knito58** [comment]
Ah ok. I put a *crafted* filter into the filter list and did try to configure there. An image may tell what I did more clearly. This does not work.

![Uploading rf-filter-problem.png…]()

I said "crafted filter" not the interface of the external storage itself.

**Comment by raoulvdberge** [comment]
Wow, you should have been more clear that you were using the actual filter item in your initial post. This is a bad report, really.

**Comment by Knito58** [comment]
Sorry.

**Comment by Knito58** [comment]
@raoulvdberge 
Should I reopen this as a new issue? Or is that known now and not necessary any more?

**Comment by raoulvdberge** [comment]
This is intended behavior.
