### ISSUE TITLE
Sorting settings not shared between different / re-placed grid blocks.

### ISSUE THREAD

**Issue by Rebmes** [raoulvdberge/refinedstorage#1196]
I use the grid, and it defaults to sort things by quantity, descending. I change it to name, ascending. I build a crafting grid and have to fix it again. Then with the wireless grid. Then all my items are packed up and I move to my new house, and with each block I plop down again, I have to set the settings again.

I would expect it to remember, to some degree, what my sorting preferences are. It just feels like I have to set it over and over - though I understand that once I stop moving things around it'll no longer require fixing.

As a note, thanks for a really cool storage mod. You've managed to eliminate the headaches of AE2 while keeping things feeling balanced, making it much more accessible. Your mod is different enough to not feel like any kind of copy or clone, and has a unique and awesome look and feel. I'm glad I was able to get started in minutes instead of hours (AE2).

**Comment by way2muchnoise** [comment]
Would be interesting to keep preferences for the grid sorting stored client side, no to sure if it would work tho.

**Comment by raoulvdberge** [comment]
No, this is what the "dismantling mode" is for with the wrench.
