### ISSUE TITLE
Crafter starts making bonemeal for no reason

### ISSUE THREAD

**Issue by HairyDragonBeck** [raoulvdberge/refinedstorage#1197]
#### Issue description:
The crafter makes bonemeal when it is not needed/nor in the recipe
#### What happens:
The crafter makes bones when it is not needed/nor in the recipe. So far, it has made like 189000 bonemeal
#### What you expected to happen:
Not make bonemeal
#### Steps to reproduce:
1.
2.
3.
...

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge: 1.10.2
- Refined Storage: 1.2.25

Does this issue occur on a server? [yes/no]
Yes
#### If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here]

**Comment by way2muchnoise** [comment]
Redstone

**Comment by HairyDragonBeck** [comment]
What? What do you mean by _redstone_

**Comment by way2muchnoise** [comment]
If the crafter gets a redstone signal it starts crafting, or some exporter/interface with a crafting upgrade.

**Comment by HairyDragonBeck** [comment]
I mean it doesnt do it on its own, it starts making bonemeal when we start something

**Comment by raoulvdberge** [comment]
Can be an oredict issue as well

**Comment by way2muchnoise** [comment]
Any idea as to which crafting tasks start a bone task?

**Comment by HairyDragonBeck** [comment]
Yeah, Solar Flux Reborn stuff. And i messed with the oredict a little, that isn't the issue

**Comment by Rayzr522** [comment]
Hairy and I were doing this in a multiplayer world, and I checked all the crafting steps - none of them required bones, bonemeal, or white dye.

**Comment by raoulvdberge** [comment]
Oredict can be an issue, if you messed if up. RS might think an equivalent for an item is bones.

**Comment by raoulvdberge** [comment]
We can't do much with this report, it's most likely caused by the user side and not us.

**Comment by Rayzr522** [comment]
Thanks anyways. Sorry for taking your time.
