### ISSUE TITLE
1.11.2 Server crash 1.4.2

### ISSUE THREAD

**Issue by seba84** [raoulvdberge/refinedstorage#1199]
#### Issue description:
Just Checked the logs from the server that's running and found a crash 
#### What happens:
Server crash
#### What you expected to happen:
not crash
#### Steps to reproduce:
there were no players online, so there are no steps to reproduce the server was left running 
and after a couple of hours it crashed.
...

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.11.2
- Forge:  forge-1.11.2-13.20.0.2265-universal
- Refined Storage: 1.4.2

Does this issue occur on a server? [yes/no]
yes
#### If a (crash)log is relevant for this issue, link it here:

[crash-2017-05-04_07.46.54-server.txt](https://github.com/raoulvdberge/refinedstorage/files/977087/crash-2017-05-04_07.46.54-server.txt)

**Comment by raoulvdberge** [comment]
This is a stall report. While it says RS in the stacktrace, this crash was generated *while* the server was stalling. This means that *any* code could be causing the stall, and not just RS.

Thus, this report is rather useless and I'd have to close this.
