### ISSUE TITLE
External Storages cannot properly read Quantum Storage Units from Quantum Storage

### ISSUE THREAD

**Issue by JohnC94** [raoulvdberge/refinedstorage#120]
There are a few issues and I don't know of way to tell if it's RS's problem or not but, the external storages are not adding the quantum storage unit's inventory to the network properly. There also seems to be an issue with them inserting/extracting items from the qsu even when it is set to 99 priority.

Oh and the items in the pictures were inserted via the external inventory block after being imported from a quarry, so it's not an issue of them being oriented incorrectly.

Album with pictures.
http://imgur.com/a/qMEhT

If you need me to provide anymore information, just let me know.

**Comment by raoulvdberge** [comment]
Aha, quantum storage uses deep storage unit API. I can add that for next version, thanks for reporting.
