### ISSUE TITLE
Unnecessary JEI version constraint

### ISSUE THREAD

**Issue by falkreon** [raoulvdberge/refinedstorage#1200]
#### Issue description:

Even though JEI needs no particular load order with respect to JEI (JEI classloads RS's compat classes via annotations), the dependencies string has an unnecessary "after:jei@[4.3.0,);" tacked onto the end. While this doesn't actually create a hard dependency, when JEI **is** present, it enforces a fairly strict version restriction. In reality, the JEI API is stable enough that any JEI for the same minecraft version should interpret RS information correctly.

#### What happens:

Running an empty environment with just the latest RefinedStorage, and any JEI 4.2.x version, causes the Minecraft load process to halt, citing RefinedStorage's "need" for newer JEI.

#### What you expected to happen:

RefinedStorage was expected to have no special dependency on JEI.

#### Steps to reproduce:
1. Set up a Forge 2282+ Minecraft environment
2. Put RefinedStorage 1.4.4 or newer into the Mods folder
3. Put JEI 4.2.6.235 into the Mods folder
4. Run Minecraft. The game will halt unexpectedly.

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.11.2
- Forge: 13.20.0.2282
- Refined Storage: 1.4.4

Does this issue occur on a server?  Unknown

#### If a (crash)log is relevant for this issue, link it here:
n/a

#### Known workarounds
Updating JEI to the most recent version (obviously) removes the problem

**Comment by raoulvdberge** [comment]
Ummm, RS uses new JEI api methods, replacing deprecated ones from JEI 4.2. If I would be using those on a 4.2 installation, you'll crash.

I don't specify version constraints without reason...

**Comment by unascribed** [comment]
(To be fair, a lot of people do.)

**Comment by raoulvdberge** [comment]
Do what?

**Comment by unascribed** [comment]
Add useless version constraints.

**Comment by raoulvdberge** [comment]
Sure, but does that make this issue any more valid?

**Comment by unascribed** [comment]
...no, and I'm not entirely sure why I replied. Ignore me.
