### ISSUE TITLE
"Machine is in use" when it isn't

### ISSUE THREAD

**Issue by Erro88** [raoulvdberge/refinedstorage#1201]
#### Issue description:

I am receiving the "Machine is in use" error when auto-crafting in a solderer.  I originally had the Solderer working properly in one location, with a crafter block feeding into it a recipe for a few things (e.g. Advanced Processor).  I moved the solderer and crafter, as well as many other machines with their functioning crafters, to another location.  Now, only the solderer doesn't work.  Other machines next to the solderer work.

When I move the Solderer back to NEAR its original location & set up the crafter again, it works properly again (it doesn't have to be in the exact location).  The layout of the blocks is the same (crafter feeding into same side of solderer, cables feeding into same sides of both blocks).  Only the solderer is affected.

#### What you expected to happen:

The solderer should receive the auto craft recipe & not display "Machine is in use."

#### Steps to reproduce:
1. Create RS system with crafter block (and patterns) feeding into a solderer.
2. Craft some items automatically.
3. Move the solderer, crafter block, and pattern(s), to another location over 15 blocks away, connected via cable.
4. Attempt to auto-craft item & check the crafting monitor.

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge: 12.18.3.2254
- Refined Storage: 1.2.25 (modpack is FTB Beyond)

Does this issue occur on a server? yes

**Comment by raoulvdberge** [comment]
Did you connect the crafters to the correct side of the solderer in your new setup?

**Comment by Erro88** [comment]
Yes.  I believe I tracked down the problem after posting this.  I have the importer on the top face of the solderer.  This causes any items placed into the solderer to be sucked out of it before the final product can be made.  I'm not sure of any reason why inputs would need to be removed from the machine before the output is created, maybe this should be disabled.  Is this working as intended?

**Comment by raoulvdberge** [comment]
The solderer in 1.10 is still sided, in 1.11 extracting from any side will extract from the output slot.
