### ISSUE TITLE
Rs system unlinks when chunks unload

### ISSUE THREAD

**Issue by tyler489** [raoulvdberge/refinedstorage#1202]
#### Issue description:
When ever the chunk unloads  all rs machines unlink from the controller and unpower
#### What you expected to happen:
They should reconect to eachother when the chunk loads
#### Steps to reproduce:
1.make a rs system linked wither eather cables or directly to the cotroler
2.leave the chunk
3.come back. Everything is disconected
...

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge:johnfg10: forge 12.18.3.2234 
- Refined Storage: 1.2.25

Does this issue occur on a server? [yes/no]
Yes
#### If a (crash)log is relevant for this issue, link it here:
No
[pastebin/gist/etc link here]

This may be a spongeforge issue 
Playing the foolcraft modpack
If this is a spongeforge issue do you mind listing classes so i can report it

**Comment by raoulvdberge** [comment]
#370
