### ISSUE TITLE
Ticking block entity crash

### ISSUE THREAD

**Issue by 23Link89** [raoulvdberge/refinedstorage#1203]
#### Issue description:
I'm not quite sure what happened, I just loaded up my world and flew over to my Refined Storage system and received this crash

#### What happens:
I'm really not sure

#### What you expected to happen:
Not crash?

#### Steps to reproduce:
I'm not sure if this is the problem, however, I looked through the crash file and found the block being ticked in my world, and the culprit SEEMS to be a bugged pattern, the pattern is for a regular Minecraft wooden chest with ore dictionary. When I press shift the icon for a chest doesn't show up, it does however still craft vanilla chests when qued. I've tried removing or dictionary and the icon still doesn't show up.

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge: 12.18.3.2254
- Refined Storage: 1.2.25

Does this issue occur on a server? [yes/no]
Haven't checked yet

#### If a (crash)log is relevant for this issue, link it here:

https://pastebin.com/Mc0PinSS

**Comment by raoulvdberge** [comment]
The icon not showing is just a visual bug.

**Comment by raoulvdberge** [comment]
This bug is not present on 1.11+.
