### ISSUE TITLE
Items not movine

### ISSUE THREAD

**Issue by Destroyer5266** [raoulvdberge/refinedstorage#1204]
Issue description: I have 1 interface, 2 exporters and they export and inport fine one min and then the next they arent doing what i have them setup to do

What happens: The items dont got in or out of the storage system

What you expected to happen: items to go in then get moved out crafted then smelted then back in

...

Version (Make sure you are on the latest version before reporting): 1.10.2 (FTB Sky Factory 3)

Minecraft: 1.10.2
Forge:
Refined Storage:
Does this issue occur on a server? yes

**Comment by raoulvdberge** [comment]
Bad report, not even any reproduction steps. Are you kidding me?
