### ISSUE TITLE
Portable Grid

### ISSUE THREAD

**Issue by raoulvdberge** [raoulvdberge/refinedstorage#1205]
Kind of like a bag.

- Craft a portable grid
- Charge it with energy
- Open it
- Get a Grid view presented
- Insert a storage disk
- Have access to your storage disk in a Grid view!

**Comment by BrianEdmonds** [comment]
> Kind of like a bag.

A potentially really, really big bag. Yes please. :)

**Comment by raoulvdberge** [comment]
@BrianEdmonds Working on it as we speak! :-)

**Comment by calloatti** [comment]
Did the storage blocks get some love too?
