### ISSUE TITLE
No tooltips for filtered fluids in Disk Drive GUI in fluid mode.

### ISSUE THREAD

**Issue by calloatti** [raoulvdberge/refinedstorage#1209]
#### Issue description:

The disk drive filter in fluid mode does not display tooltips for filtered fluids.

#### What happens:

When hovering the cursor over a fluid added to the filter in the disk drive GUI in fluid mode, no tooltip is shown.

#### What you expected to happen:

The disk drive in fluid mode should display tooltips for fluids added to the filter

#### Steps to reproduce:
1. Self evident.
2.
3.
...

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge: 12.18.3.2281
- Refined Storage: refinedstorage-1.2.25

Does this issue occur on a server? [yes/no]

Tested on single player only

#### If a (crash)log is relevant for this issue, link it here:

No tooltip:

![image](https://cloud.githubusercontent.com/assets/12817862/25879428/09461868-3508-11e7-9a52-9f1f0c675f8a.png)

This is what should happen (edited screenshot)

![image](https://cloud.githubusercontent.com/assets/12817862/25879510/6db817d8-3508-11e7-9b7a-b518d1378058.png)

**Comment by raoulvdberge** [comment]
From which mod is this biodiesel?

**Comment by calloatti** [comment]
Biodiesel and Creosote (not shown) both from [Immersive Engineering](https://github.com/BluSunrize/ImmersiveEngineering)

**Comment by calloatti** [comment]
FYI the Fluid Grid displays all the tooltips correctly for all fluids.

The Disk drive does not display tooltips for any fluid, not even vanilla water. The drive in the screenshot has Biodiesel, Plant Oil, Ethanol (all from IE) and water. No tooltips for any of them.

![image](https://cloud.githubusercontent.com/assets/12817862/26028418/46be0bb0-37f6-11e7-9da5-03cdf94be51d.png)

**Comment by raoulvdberge** [comment]
There were no tooltips for *any* fluid filter slot, wow!

Fixed now:

![x](https://raoulvdberge.com/hiqLSW)

Thanks for reporting.

**Comment by calloatti** [comment]
>Thanks for reporting.

No problem at all, glad to contribute something. Expect more nitpicking OCD bug reports like these from now on :-)
