### ISSUE TITLE
Disk Manipulator filter in fluid mode displays fluid bucket instead of fluid.

### ISSUE THREAD

**Issue by calloatti** [raoulvdberge/refinedstorage#1210]
#### Issue description:

Disk Manipulator filter in fluid mode displays fluid bucket instead of fluid.

#### What happens:

![image](https://cloud.githubusercontent.com/assets/12817862/25879557/aad744b8-3508-11e7-92eb-7bb68c371aa0.png)

#### What you expected to happen:

![image](https://cloud.githubusercontent.com/assets/12817862/25879596/e2f64de4-3508-11e7-9fd1-c76bb24cbdc0.png)

#### Steps to reproduce:
1.
2.
3.
...

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge: 12.18.3.2281
- Refined Storage: refinedstorage-1.2.25

Does this issue occur on a server? [yes/no]

Not tested.

#### If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here]

**Comment by raoulvdberge** [comment]
What happens if you close and reopen the GUI? Does the liquid correctly show up then?

**Comment by calloatti** [comment]
Closing and reopening the Disk Manipulator GUI has no effect, it is still shown as the first screenshot.

**Comment by raoulvdberge** [comment]
Can you confirm that the Disk Manipulator is in fact in fluid mode by testing if it actually uses fluids to import/export disk data?
