### ISSUE TITLE
Item duplicating and voiding

### ISSUE THREAD

**Issue by UberAffe** [raoulvdberge/refinedstorage#1211]
Playing in Sky factory 3.0.8 

#### Steps to reproduce:
1. Create a simple storage/crafting grid/transmitter
2. travel far enough for the original system to unload
3. build a second system using the receiver and crafting grid
4. link the systems
5. Items that you put into the secondary system get voided
6. Items that you take out of the secondary system get duplicated
...

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge: 12.18.3.2254
- Refined Storage: 1.2.22

Does this issue occur on a server? [yes/no]
Yes, have not tested in smp.

**Comment by raoulvdberge** [comment]
Should be fixed in RS for latest MC versions.
