### ISSUE TITLE
Issue or Bug Grid eat items

### ISSUE THREAD

**Issue by Superguz72** [raoulvdberge/refinedstorage#1212]
#### Steps:

1.Put items directly in the grid
2.It eat them
...

#### Version:

- Minecraft: 1.10.2
- Forge: Minecraft forge-12.18.3.2202
- Refined Storage: 1.2.16
- Modpack: On Twitch launcher: WeCraft
- 64 blocks of 64k items which is all empty
- 16 Disk drive all full with 64k storage disks
- 2 Disk drive full with 4k storage disks and 16k storage disks
- Don't cheatted. With none creative storages 
- 8 Disk Manipulator
I wait for the Answer by the Author

**Comment by ktole1999** [comment]
might check to see if they were exported to chest or voided. check all inventories connected to network

**Comment by raoulvdberge** [comment]
Are your storages in insert+extract mode? If you have a storage in insert only mode items won't show up in the grid if you insert them.

**Comment by raoulvdberge** [comment]
I think this is a user error. So I'll close this.
