### ISSUE TITLE
OpenComputers API for Software-Defined Assets

### ISSUE THREAD

**Issue by AJMansfield** [raoulvdberge/refinedstorage#1214]
In addition to tracking items and fluids in auto-crafting recipes, it would be useful if Refined Storage was able to keep track of some type of software-defined assets to keep track of intermediate storage in a system, and allow tracking things that aren't actually blocks but that are still generated or consumed in recipes.

For instance, in one setup I have, I have a system that can only be filled 9 units at a time, but can be drained in much smaller portions to craft items. Currently I'm using named items (e.g. a piece of cobblestone called 'blast furnace steel content') to keep track of this, by adding and removing the items from the storage system to represent the current system contents, and then use dummy crafting patterns between the different named items to allow me to automatically trigger the correct processes using the detectors, but this is a rather expensive and fragile way to do this, and it causes a lot of issues when the count gets desynchronized from the actual process.

Ideally, I'd like to just have a way for a OpenComputers script to just _tell_ the system how much of these different assets exist, and then define the crafting recipes for them with something like what I proposed in #1213.

**Comment by raoulvdberge** [comment]
No.
