### ISSUE TITLE
[Possible Bug][1.10.2] Unable to use EnderIO Silicon for Printed Silicon

### ISSUE THREAD

**Issue by Deal-or-die** [raoulvdberge/refinedstorage#1215]
#### Issue description:
As the title states, It may not be a bug however unlike the 'Storage parts', 'Printed Silicon' is unable to crafted/soldered using the EnderIO Silicon.

#### What happens:
N/A
#### What you expected to happen:
N/A
#### Steps to reproduce:
1. Place 1x EnderIO silicon in solderer

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge: 12.18.3.2185
- Refined Storage: refinedstorage-1.2.25.jar

Does this issue occur on a server? [**yes**]

#### If a (crash)log is relevant for this issue, link it here:
N/A

Note:
If this has been updated in later versions (EG 1.11) would you be so kind to supply me with a fixed(or changed) 1.10.2 as I would really appreciate the change. Greatly appreciated. 
(I believe it just needs to accept any 'itemSilicon')

**Comment by Deal-or-die** [comment]
https://github.com/raoulvdberge/refinedstorage/blob/mc1.10/src/main/java/com/raoulvdberge/refinedstorage/apiimpl/solderer/SoldererRecipePrintedProcessor.java

**Comment by raoulvdberge** [comment]
Not an RS problem. Your oredict in your pack is messed up.
