### ISSUE TITLE
No tooltips for filtered fluids in 512k Fluid Storage Block

### ISSUE THREAD

**Issue by calloatti** [raoulvdberge/refinedstorage#1218]
#### Issue description:

Similar to https://github.com/raoulvdberge/refinedstorage/issues/1209 but for Fluid Storage Block instead of Disk Drive in fluid mode.

#### What happens:

No tooltips for filtered fluids in 512k Fluid Storage Block

![image](https://cloud.githubusercontent.com/assets/12817862/26029274/3de79716-3807-11e7-93aa-fea9de4dd269.png)

Fluid in screenshot is Biodiesel from IE, but I guess all fluids will be missing the tooltip...

#### What you expected to happen:

Tooltips  for filtered fluids in 512k Fluid Storage Block

#### Steps to reproduce:
1. Place a  512k Fluid Storage Block, add a fluid filter, hover over it. No tooltip.
2.
3.
...

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge: 12.18.3.2297
- Refined Storage:refinedstorage-1.2.25

Does this issue occur on a server? [yes/no]

Not tested.

#### If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here]

**Comment by raoulvdberge** [comment]
This happens to every fluid slot. It's already fixed for every fluid slot.

**Comment by calloatti** [comment]
I thought so but reported anyway just in case. Thank you.
