### ISSUE TITLE
Crafter load balancing issue

### ISSUE THREAD

**Issue by Karmacopper** [raoulvdberge/refinedstorage#1219]
#### Steps to reproduce:
1. Place the same recipe into to crafters
2. Call items 
3. Wait longer than you should
...

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge: 12.18.3.2185
- Refined Storage: 1.2.25

Does this issue occur on a server? [yes/no]

#### If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here]

**Comment by raoulvdberge** [comment]
This isn't a bug, but intended behavior on 1.10.

Also, this works correctly on 1.11.
