### ISSUE TITLE
Multithreaded crafting

### ISSUE THREAD

**Issue by raoulvdberge** [raoulvdberge/refinedstorage#122]

**Comment by RealGrep** [comment]
Yep, this would be very nice to have. I wanted to process ores, so I requested a bunch. Then I needed something and sent it for crafting, but it wouldn't run until the large number of ores got processed, which is a significant issue, IMO. So yep, this would be very nice!

Would also be nice if it was a little more asynchronous. It sends, for example, one ore to the SAG, waits for the result, pauses, then repeats that until done. This makes it extremely slow, to say the least.

**Comment by JohnC94** [comment]
Will we have a way to increase the number of threads our systems can use to whatever number we want?

**Comment by choekstr** [comment]
When crafting something like octatic capacitors it takes longer than I can do myself just shift clicking and pulling items out of the grid.  It's fine for a 'schedule and walk away, come back in a few minutes' function but if you do any bulk it takes so long that I tend to have to have great foresight into what I will need in the future and that isn't always possible.  

I am commenting to add my vote to this feature being added, in whatever method it is implemented.

**Comment by Zettt** [comment]
All of this said, I recently discovered how nice the current auto-crafting method is for Botania. When the Crafter inserts items for a rune, it does one rune recipe at a time, which is exactly what the Botania machines expect. My hope is you'll find an easy way to accomplish multithreaded operation with single-threadedness.

**Comment by raoulvdberge** [comment]
This is done for 1.0!
