### ISSUE TITLE
Crafting upgrade not working in exporters

### ISSUE THREAD

**Issue by wlsnbilyb** [raoulvdberge/refinedstorage#1221]
#### Issue description:
2 exporters which function normally with items in the system do not ask for an autocraft of item (crystallized/empowered canola), both of which are processing patterns. Able to manually ask for autocraft which is properly exported, but will not function otherwise.

Worked in previous versions without issue.

#### What happens:
Nothing.

#### What you expected to happen:
Export of autocrafted item.

#### Steps to reproduce:
1. Build exporter with crafting upgrade.
2. Have functioning processing pattern.
3. Attempt to export when none of item are in system.

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge: 12.18.3.2554
- Refined Storage: 1.2.25

Does this issue occur on a server? [yes/no]

Yes

**Comment by raoulvdberge** [comment]
So if you ask the item manually it works???

This sentence is rather cryptic
> Able to manually ask for autocraft which is properly exported, but will not function otherwise.

**Comment by wlsnbilyb** [comment]
Sorry, I mean like the exporter will function normally i.e. export items that are already in the system, and the crafting process itself works and I can manually request that, but the exporter itself will not request the craft.
