### ISSUE TITLE
Under certain conditions, setting "Void excess..." on a Disk Drive starts voiding when one disk is full.

### ISSUE THREAD

**Issue by calloatti** [raoulvdberge/refinedstorage#1222]
#### Issue description:
In a Disk drive with two 64k storage disks, setting "Void excess items and fluids" on and adding a whitelist filter for one item, the items get voided when only one disk is full.

#### What happens:
Items get voided in a disk drive when one disk gets full.

#### What you expected to happen:
Items should get voided when all disks are full, not just one.

#### Steps to reproduce:
1. Setup a disk drive.
2. insert 2 empty 64k storage disks
3. add a whitelist filter for one item
4. Set up a way to import large numbers of that item into the system
5. Watch how the item starts getting voided when the first disk gets full

![image](https://cloud.githubusercontent.com/assets/12817862/26089755/8e91632e-39d6-11e7-9cca-215c4c135863.png)

![image](https://cloud.githubusercontent.com/assets/12817862/26089530/eb41f176-39d4-11e7-919d-59b100b50758.png)

![image](https://cloud.githubusercontent.com/assets/12817862/26089534/f5493efe-39d4-11e7-8296-97a3a933b7fe.png)

Industrial Hemp Fiber is being inserted into the system:

![image](https://cloud.githubusercontent.com/assets/12817862/26089545/0edd0b52-39d5-11e7-9332-764c51541a74.png)

RS Interface getting Hemp Fiber:

![image](https://cloud.githubusercontent.com/assets/12817862/26089553/291b4f7e-39d5-11e7-8047-d47a72a892d3.png)

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge:12.18.3.2297
- Refined Storage:refinedstorage-1.2.25

Does this issue occur on a server? [yes/no]

Not tested.

#### If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here]

**Comment by calloatti** [comment]
If I disable "Void excess items..." the second disk starts to fill up. As soon as I enable "Void excess items..." again, the voiding restarts and no new items get into the second disk.

**Comment by calloatti** [comment]
Setting "Compare ore dictionary" to **Yes** makes the second disk accept items... weird.

![image](https://cloud.githubusercontent.com/assets/12817862/26103654/e5b8f75e-3a10-11e7-875a-5262b3c9e859.png)

**Comment by raoulvdberge** [comment]
This is intended behavior.
