### ISSUE TITLE
Crash when trying to autocraft an item from Scannable mod.

### ISSUE THREAD

**Issue by calloatti** [raoulvdberge/refinedstorage#1224]
#### Issue description:

When trying to autocraft an item from [Scannable](https://minecraft.curseforge.com/projects/scannable) the game crashes.

This may be a Scannable issue, posting here just in case.

#### What happens:

When trying to autocraft a "Scanner module:block" from the mod Scannable the game crashes when hovering or clicking the mouse on the pattern in a crafting grid.

The patterns are stored in a RebornStorage crafter.

#### What you expected to happen:

Not crashing.

#### Steps to reproduce:

1. Create a pattern for "Blank scanner module" from Scannable
2. Create a pattern for "Scanner module:block" from Scannable
3. Place both patterns in RebornStorage crafter
4. Open Crafting Grid GUI, scroll to find "Scanner module:block" item
5. Hover mouse or click over item, game crashes

![image](https://cloud.githubusercontent.com/assets/12817862/26113981/7a0457ca-3a32-11e7-8508-07b65c208be2.png)

![image](https://cloud.githubusercontent.com/assets/12817862/26114001/8a7ab16c-3a32-11e7-88e0-a51118378f05.png)

![image](https://cloud.githubusercontent.com/assets/12817862/26114088/ca50d1ea-3a32-11e7-8ea4-9688cc923b2f.png)

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge:v12.18.3.2297
- Refined Storage:refinedstorage-1.2.25
- Scannable: Scannable-MC1.10.2-1.3.0.15

Does this issue occur on a server? [yes/no]

Not tested

#### If a (crash)log is relevant for this issue, link it here:

https://paste.ee/p/shWjf

https://paste.ee/p/WlMv2

**Comment by way2muchnoise** [comment]
`java.lang.IllegalArgumentException: Module not supported by this provider: 0xitem.scannable.module_block@0
	at li.cil.scannable.client.scanning.ScanResultProviderBlock.getEnergyCost(ScanResultProviderBlock.java:110)`

Might be something with scannable not supporting stacksizes of zero.

**Comment by calloatti** [comment]
It seems like it only works with the blank scanner module. All the other modules based on the blank one seem to crash. (only tested one more since it takes forever to reload MC in my PC)

![image](https://cloud.githubusercontent.com/assets/12817862/26118516/97774cf0-3a40-11e7-9a3e-3763ba36ec92.png)

**Comment by fnuecke** [comment]
Ah yeah, for empty stacks my "is this an item of this type" check fails (because it checks isEmpty), and then it falls through to the exception. Will add a check to prevent this.

**Comment by raoulvdberge** [comment]
@fnuecke in 1.11 RS doesn't use 0 stacks anymore, but this bug report is for 1.10.

**Comment by fnuecke** [comment]
Right. I have a wrapper that basically does what `isEmpty` does in 1.10 to make it easier to maintain the two versions alongside each other. I'll add a check in both MC versions either way, just in case.
