### ISSUE TITLE
Can't fill and export filled buckets

### ISSUE THREAD

**Issue by Viper007Bond** [raoulvdberge/refinedstorage#1229]
#### Issue description:

I'm attempting to fill and export filled buckets. For testing, I'm using water

#### What happens:

It exports any already filled buckets in my storage system but it won't fill any ones as needed.

#### What you expected to happen:

A bucket gets filled and is placed into the chest.

#### Steps to reproduce:
A controller, a grid, a fluid grid, some type of both item and fluid storage, an exporter into a chest, some buckets, and some water.

A crafter doesn't seem to be needed in this scenario since a fluid grid can do it, but I've tried various crafter setups too without any success.

Here's my testing setup: 

![2017-05-17_19 04 25](https://cloud.githubusercontent.com/assets/406254/26183475/c48b91bc-3b33-11e7-8135-682ebe4b334a.png)
![2017-05-17_19 04 32](https://cloud.githubusercontent.com/assets/406254/26183474/c4851260-3b33-11e7-860a-3381612d4d56.png)

I'm not sure if the Crafting Upgrade is needed or not but I have it in there just incase.

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 10.10.2
- Forge: 12.18.3.2254
- Refined Storage: 1.2.25

Using version 1.10.0 of the Direwolf20 10.10.2 pack.

Does this issue occur on a server? Yes

**Comment by raoulvdberge** [comment]
The Exporter doesn't export filled buckets. This functionality is only available in the autocrafting.

You can however export the fluid itself.

**Comment by Viper007Bond** [comment]
Right, it can't be exported because no filled buckets exist but wouldn't slapping the crafting upgrade on the exporter be some type of workaround? I guess with a requirement that there be enough empty buckets or the system knowing how to craft buckets.

Anyway, I ended up exporting the fluid into an Ender IO tank that had buckets in it and was in turn told to push/pull into the inventory. It was easier overall because it automatically handled the used empty buckets.

**Comment by raoulvdberge** [comment]
No, I meant that the "filling existing empty buckets with fluids" functionality doesn't exist for the Exporter. Thus, putting on a Crafting Upgrade or not doesn't matter.

**Comment by Viper007Bond** [comment]
Gotcha. It seems like this be worth a specia use case for this since there's no way to define such a pattern (fill a bucket).

**Comment by calloatti** [comment]
Not an actual solution using RS, but there is one popular mod that has a bottling machine that maybe you could use.

**Comment by bookerthegeek** [comment]
Mods with things that fill bottles:
- Forestry
- Immersive engineering
- Ender IO
- Railcraft (if your good)
