### ISSUE TITLE
1.4.6 machines stop working in smp

### ISSUE THREAD

**Issue by kreezxil** [raoulvdberge/refinedstorage#1230]
#### Issue description:

machines randomly stop working, for example the solderer

#### What happens:

machines randomly stop working, for example the solderer

#### What you expected to happen:

expected the solderer to keep working

#### Steps to reproduce:
1. attach more than one solderer
2. I used hoppers on top and below to automate them
3. then without rhyme or reason they stop working
4. tested it in ssp, no issues
...

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.11.2
- Forge: 2296
- Refined Storage: 1.4.6

Does this issue occur on a server? yes

#### If a (crash)log is relevant for this issue, link it here:

There are no crashes or server console spam do you have a switch to make this verbose so I can help debug this better?

**Comment by raoulvdberge** [comment]
Bad reproduction steps.
