### ISSUE TITLE
Solderer recipe mismatch

### ISSUE THREAD

**Issue by OrdinatorStouff** [raoulvdberge/refinedstorage#1231]
#### Issue description:
Solderer recipe mismatch
Just parroting the report here from the one just made to ATM2 github: https://github.com/AllTheMods/ATM-2/issues/7

#### What happens:
Using a gold block in solderer outputs "Printed Basic Processor" 

#### What you expected to happen:
Should be "Printed Improved Processor" 

#### Steps to reproduce:
1. compare JEI vs machine output?
2.
3.
...

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.11.2
- Forge: 2298
- Refined Storage: 1.4.6

Does this issue occur on a server?
Unsure

**Comment by raoulvdberge** [comment]
This is because the oredict in your pack says that iron and gold blocks are similair, so RS thinks they can make a Printed Basic Processor when in reality it should make the Printed Improved Processor.

**Comment by OrdinatorStouff** [comment]
Thanks for pointing that out, I'm looking more into that. I'm curious if you plan to make any change to RS regarding this? If not we'll just fix the oredict stuff from unidict and our pack but before we do I just wanted to see if you planned anything on your end.

**Comment by raoulvdberge** [comment]
I'm not sure what I can do about it RS-side.

**Comment by OrdinatorStouff** [comment]
Ok, no problem. I'd rather RS continue to support OreDict for it's recipes 👍 
We'll just address this on the pack side, then. Thanks!

**Comment by bookerthegeek** [comment]
Most likely tinkers ad they ordict both iron and gold as a metal block.
