### ISSUE TITLE
NBT data wipe on storage blocks

### ISSUE THREAD

**Issue by LittleODie** [raoulvdberge/refinedstorage#1232]
#### Steps to reproduce:
1. This issue is persistent and repeatable with the modpack "The New Frontier" for 1.11.2 Minecraft.
2. The pack comes with servers that host the pack, issue found originally on server "SummerCrest"
3. Unknown if its a mod incompatibility, but no other mods are part of the RS system.
...

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.11.2
- Forge: 13.20.0.2296
- Refined Storage: 1.4.5

Does this issue occur on a server? [yes/no]
yes
#### If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here]

**Comment by raoulvdberge** [comment]
You are not on the latest RS version, please update before making an issue!!!

> Version (make sure you are on the latest version before reporting):
