### ISSUE TITLE
Feature Request: Redstone Crafting request modem 

### ISSUE THREAD

**Issue by GameKnyte** [raoulvdberge/refinedstorage#1234]
Simple idea that been needed for autocrafting for a long time. Some crafting systems can be automated in very convoluted ways and usually have some kind of Redstone trigger.y idea is a block that can be given a patter and when the request for that item is sent it transfers the items and triggers a redstone signal. This can be used to notify outside sytems to craft or what to be crafting. An additional feature would be a number of crafts possible for mods like botania where you can only do one at a time. The system would be aware of this and only send one group and with for the return before the next is sent.

**Comment by raoulvdberge** [comment]
> when the request for that item is sent it transfers the items

This is literally what a processing pattern does.

> triggers a redstone signal

Use a comparator

> An additional feature would be a number of crafts possible for mods like botania where you can only do one at a time

Already exists
