### ISSUE TITLE
[1.10.2] after updating RS from 1.2.4, Constructor does not place block anymore (no FTB installed)

### ISSUE THREAD

**Issue by Ioandar** [raoulvdberge/refinedstorage#1236]
#### Issue description:
Constructor does not place block (anymore after update from old RS version)

#### What happens:
No Block is being placed
If I select drop, the correct item(s) drops
If I try "/ftb team config ftbu.fake_players true" All I get is an error message because I dont use FTB...

#### What you expected to happen:
That a block will be placed

#### Steps to reproduce:
1. Create 1.10.2 world with current RS
2. Setup a basic RS system and try to use the constructor to place a block in the world
3.
...

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge: 1.10.2 - 12.18.3.2185 (recommended version)
- Refined Storage: 1.2.25 (latest version for 1.10.2, no change if using others down to 1.2.5)

If I use the old 1.2.4 version of RS again, IT AGAIN WORKS AS IT SHOULD!

Does this issue occur on a server? [yes/no]
no, this is a local game

#### If a (crash)log is relevant for this issue, link it here:
no crashlog, all works fine, only constructor does not work

[pastebin/gist/etc link here]

**Comment by raoulvdberge** [comment]
Show me your setup with some screenshots, including the Constructor GUI.

**Comment by Ioandar** [comment]
Dropping cobble works fine but when I switch to placing nothing happens...

I can place a block manually, but my constructor can not. Any hint welcome

[url=https://postimg.org/image/5ts0i64av/][img]https://s7.postimg.org/5ts0i64av/2017-05-25_14.07.51.png[/img][/url]

[url=https://postimg.org/image/eq2sm3ux3/][img]https://s7.postimg.org/eq2sm3ux3/2017-05-25_14.07.58.png[/img][/url]

[url=https://postimg.org/image/sl134kpc7/][img]https://s7.postimg.org/sl134kpc7/2017-05-25_14.08.02.png[/img][/url]

[url=https://postimg.org/image/5yvrrublz/][img]https://s7.postimg.org/5yvrrublz/2017-05-25_14.10.11.png[/img][/url]

**Comment by raoulvdberge** [comment]
That is weird. What I do know is that RS fires a block placement event, any external mod can block it, and then no blocks will be placed.

**Comment by Ioandar** [comment]
ty for checking. strange, I will try with RS only and report back...

**Comment by raoulvdberge** [comment]
Does it work if you place the Constructor somewhere else?

**Comment by Ioandar** [comment]
nope, nojoy. only going back to 1.24. then blocks get places (but destructor still fails)

I will reduce mods and check if its a cross mod thing... I have mineconlonies relatively new. I will check and report

**Comment by raoulvdberge** [comment]
Ah, 1.2.4 didn't have the block placement event check yet. Later versions do.

1.2.4 did have the block removal event check, that explains why it won't remove even in 1.2.4.

**Comment by Ioandar** [comment]
tested my new save without 'minecolonies' and my old backup before I tested minecolinies and RS works just perfect!

Seems like 'minecolonies' does something to RS that break the place/break.. 

I will report it on their github. I think we can close this here. thanks for the superfast help and all the work you put into RS!

cheers

**Comment by raoulvdberge** [comment]
No problem! I wouldn't exactly say superfast, it took me 4 days to respond on this issue :-)

**Comment by Ioandar** [comment]
Hmm, posted issue over at minecolonies github and got response 

> There are two chances:
>
>    Disable colony protection in the config.
>    As we spoke with the forge team, fakePlayers should inherit the players UUID, I guess refinedStorage does that wrong

**Comment by raoulvdberge** [comment]
The fake player of RS can't inherit from the player, since there is no player data associated to a block.

**Comment by Ioandar** [comment]
Hmm, the block does not place itself but the constructor does.  The constructor should have the UUID of the player that placed the constructor and then use it when placing a block. same with destructor, no?

I will check other block placers and how they behave in protected areas where only the allowed players are able to place or remove blocks...

**Comment by raoulvdberge** [comment]
Let me see if I can make RS blocks store the UUID of the placer.

**Comment by Ioandar** [comment]
just checked 'machnical user' from extra utilities 2'... It CAN place blocks in the protected area of minecolonies...

[picture](https://s7.postimg.org/s0htw6qvv/2017-05-26_11.24.27.png)

**Comment by raoulvdberge** [comment]
Gonna tag this as wontfix. I don't want to store any UUIDs in network nodes.
