### ISSUE TITLE
Strange bug with network and unloading chunks

### ISSUE THREAD

**Issue by HardwareAccelerated** [raoulvdberge/refinedstorage#1237]
#### Issue description:
Whenever I leave my base for a couple minutes and come back there's a chance all of my refined storage machines stop working, the controller is still lit up but it doesn't show much in the GUI, when I replace the controller everything shows in the gui but only cables, drives and external storages work, machines only start working again after I replace them and the controller.
#### What happens:
I leave my base, when I come back there's a chance RS machines will not be lit up and will stop working, the controller stays lit but the things that show up in the gui are incomplete. I have to replace the controller and all grids, crafters, solderers, importers, exporters, disk manipulators for them to work BUT I don't have to replace any drives, external storages or cables, those work and show up in the controller after I just replace the controller.
Here's a video for clarification: [[Link]](https://www.dropbox.com/s/zrldr3spdo04zon/bug.mp4?dl=0)

#### What you expected to happen:
I come back to my base and everything just works

#### Steps to reproduce:
1. Setup a small system with a variety of RS devices
2. Leave the area for a few minutes or disconnect for a few minutes
3. Come back and there's a chance things will look as I described

#### Version (make sure you are on the latest version before reporting):
- Minecraft: 1.10.2
- Forge: 12.18.3.2281
- Refined Storage: 1.2.25
*FTB Beyond 1.6.1

Does this issue occur on a server? [yes/no] Yes (I haven't seen it happen offline)

#### If a (crash)log is relevant for this issue, link it here:
The server admin says nothing showed up in the console when this happens

**Comment by raoulvdberge** [comment]
I suppose you don't read closed issues or use the GH search function

#370
