### ISSUE TITLE
Controller requires replacing after power loss

### ISSUE THREAD

**Issue by Shadows-of-Fire** [raoulvdberge/refinedstorage#1238]
When using the redstone controls of the Controller, turning it off momentarily while cycling through to the "only active without signal" setting caused it to require a break/replace before the controller functions again.  Upon further investigation, this happens completely whenever the controller shuts off, whether it be power loss or due to redstone control.  Restoring the signal so the grid is on makes it consume power and act like it is on, but all components remain dark and do not function.

https://i.imgur.com/471QQE9.png
https://i.imgur.com/q1hUMHs.png

Steps to reproduce:
1. Create a system in the world.
2. Cause the controller to shut off for whatever reason.
3. Reactivate said controller, and watch as no components activate.

Versions:
- Minecraft: 1.11.2
- Forge: 13.20.0.2299
- Refined Storage: 1.4.6

This issue does occur on a server.

**Comment by LittleODie** [comment]
This happens on "The New Frontier" 1.11.2 modpack as well on the SummerCrest server. Same versions.
