### ISSUE TITLE
Crash when loading world.

### ISSUE THREAD

**Issue by BootyToast** [raoulvdberge/refinedstorage#124]
I'm not sure what is happening, but after getting into Refined Storage and using it for a while I found I wasn't able to load my world the next time I joined it. Looking through the crash report it looked to be something with either Refined Storage or, for some reason, FastLeafDecay.

Crash Report: http://pastebin.com/nZRKP7Xx

**Comment by BootyToast** [comment]
After uninstalling FastLeafDecay, I was able to load the world. I have a tree farm right next to my Refined Storage system, so I think there's some weird issue with there.

**Comment by raoulvdberge** [comment]
Fixed in the mentioned PR, probably. If it still occurs, let me know.
