### ISSUE TITLE
Server Crash

### ISSUE THREAD

**Issue by Mattabase** [raoulvdberge/refinedstorage#1240]
#### Issue description:
Server crashes when world loads with RF stuff in it.

#### Steps to reproduce:
1. Boot Server
2. Load World

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge: 2297
- Refined Storage: 1.0.3

**Does this issue occur on a server? [yes/no]**

Yes
#### If a (crash)log is relevant for this issue, link it here:

https://goo.gl/qJVPxB

**Comment by raoulvdberge** [comment]
1) You're on RS 1.2.25, not 1.0.3
2) This is a stall report. I can't do anything with it. This is just the code that was running when MC exited due to a task taking too long.

**Comment by Mattabase** [comment]
Yeah sorry about the incorrect versioning.
