### ISSUE TITLE
Crashing server on login

### ISSUE THREAD

**Issue by CamaroKing59** [raoulvdberge/refinedstorage#1241]
#### Issue description:
try to log into server and it crashes server
#### What happens:
just log in and time out then crashes server
#### What you expected to happen:
log in and not crash the server 
#### Steps to reproduce:
1.load minecraft
2.click multiplayer
3.click login
...

#### Version (make sure you are on the latest version before reporting):

- Minecraft:1.10.2
- Forge: 12.18.3.2281
- Refined Storage:1.2.25

Does this issue occur on a server? [yes/no]

#### If a (crash)log is relevant for this issue, link it here:
https://pastebin.com/zbJXK5T6
[pastebin/gist/etc link here]

**Comment by raoulvdberge** [comment]
Same as #1240
