### ISSUE TITLE
Up Facing Crafter Won't Link with Machines

### ISSUE THREAD

**Issue by TheGreatNaj** [raoulvdberge/refinedstorage#1242]
Issue description:
To make an auto crafting set up, the crafter will work facing a machine in any direction but up. Maybe this is some sort of feature for some reason but from everything I've looked up it seems it should work this way as well.

What happens:
I request crafting of something using a machine (Personally using solderers and alloy smelters). The crafting monitors say that the machine is in use. Go over to the machine and nothings happening in the machine. Its not in use with some other recipe, just no items going in. Doing the same in any other direction works fine. 
 
What you expected to happen:
The item should be crafted.

Steps to reproduce:
Place an upwards facing crafter with any machines on top (such as solderers and alloy smelters) and set it to craft something that uses the machine. 

Version:
- Minecraft: 1.10.2
- Forge: 12.18.3.2254
- Refined Storage: 1.2.25

Does this issue occur on a server? [yes/no]
I'm in single player, wouldn't know if it happens on servers as well.

**Comment by way2muchnoise** [comment]
What machine is it you are trying to automate? Also "the crafter will work facing a machine in any direction but up" is not really thing. It still care about the side it faces, like every other pipe or hopper.

**Comment by TheGreatNaj** [comment]
Alloy smelters from Ender IO and Solderers from Refined Storage. Works any other direction just fine.

**Comment by TheGreatNaj** [comment]
This is what my set up if a screenshot helps in any way. On the left is what I was planning for a bunch of auto crafting, smelting and soldering. Smelting on bottom with the downward facing crafters and solderers on the top with upward facing crafters. Since it wouldn't work facing up I temporarily set up how it is on the right. Everything was set up the same other than the direction it was facing but it just wouldn't work on the left set up. 
![2017-05-23_22 46 25](https://cloud.githubusercontent.com/assets/25763105/26384817/b96878ce-4009-11e7-94d4-26a1e89e4a3d.png)

**Comment by raoulvdberge** [comment]
I don't know how much I have to repeat this: https://refinedstorage.raoulvdberge.com/wiki/solderer

Solderer doesn't accept items from the bottom in 1.10. You have to insert through the top side.

**Comment by TheGreatNaj** [comment]
:I Sorry. I mean I hate being like every other kid who reports before looking up, just didn't think it'd be a solderer issue. Seems like an odd feature though, which makes sense as to why you have to repeat it. It's not really obvious. Thanks.

**Comment by raoulvdberge** [comment]
I know it's not obvious, which I am partly to blame for, but it's fixed in the 1.11 version to not be sided anymore.
