### ISSUE TITLE
world crash when accessing crafting grid

### ISSUE THREAD

**Issue by bpaw215** [raoulvdberge/refinedstorage#1243]
#### Issue description:
whenever i click on crafting grid world either crashes or internal server shutdown. have rs hooked up to colossal chest.
#### What happens:
unable to access rs due to crash or internal server shutdown whenever i click on crafting grid. everything else seems to be fine just cant click on grid without some kind of crash. can access controller and alloy smelter, solderer etc..just fine.
#### What you expected to happen:
access colossal chest thru refined stored grid
#### Steps to reproduce:
1.click on crafting grid to access storage reproduces problem every time
2.
3.
...

#### Version (make sure you are on the latest version before reporting):
running latest version of foolcraft pack on 1.10.2
- Minecraft:
- Forge:
- Refined Storage:

Does this issue occur on a server? [yes/no]
playing singleplayer
#### If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here]

**Comment by bpaw215** [comment]
also can access my disk drive fine and not crash, just not colossal chest 9x9

**Comment by raoulvdberge** [comment]
Send me your crash report

**Comment by raoulvdberge** [comment]
Missing crash report!
