### ISSUE TITLE
[1.11.2] Disk Drive texture issue

### ISSUE THREAD

**Issue by Endmateria** [raoulvdberge/refinedstorage#1244]
#### Steps to reproduce:
1.
2.
3.
...

#### Version (make sure you are on the latest version before reporting):

- Minecraft:1.11.2
- Forge:2304
- Refined Storage:1.4.6

Does this issue occur on a server? [yes/no] yes

#### If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here]

**Comment by raoulvdberge** [comment]
#970
