### ISSUE TITLE
Cannot put cables in storage drawers

### ISSUE THREAD

**Issue by Renadarain** [raoulvdberge/refinedstorage#1246]
Hi :)

#### Issue description:
I have RS hooked up to my storage drawer system and it works great.  Problem arises when you try to store excess cables in a drawer - they won't go in.

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.11.2
- Forge: forge-1.11.2-13.20.0.2304
- Refined Storage: refinedstorage-1.4.6

Does this issue occur on a server? [yes/no]
Yes

Regards,
Renada

**Comment by raoulvdberge** [comment]
That would be because your drawer is full, obviously.

**Comment by raoulvdberge** [comment]
I'm not sure if I understand your report, what do you mean with "Problem arises when you try to store excess cables in a drawer"?

**Comment by Renadarain** [comment]
No my drawer is not full it is empty.

I made a bunch of cables - used some and had a load left over as I made too many.  The leftover calbes, in fact none of the Refined Storage components that I've tried, will go into a storage drawer, they only go into chests.

**Comment by Renadarain** [comment]
I was reporting a bug, there was no need for your sarcasm.

**Comment by raoulvdberge** [comment]
I don't see where my sarcasm is.

How are you trying to store the cables? With a External Storage through RS or manually when opening the Drawer GUI?

**Comment by Renadarain** [comment]
It's nothing to do with RS mechanics.  I have surplus cables and want to store them in my sorting system of Jacquadro's Storage Drawers - they will not go into a drawer. 

You pick them up
You walk to the storage drawer (which is empty)
You right click the drawer
It does not enter the drawer

**Comment by raoulvdberge** [comment]
That sounds weird. It's not a RS issue though. Report it to the Storage Drawers dev.
