### ISSUE TITLE
crash on player join

### ISSUE THREAD

**Issue by SDUBZ** [raoulvdberge/refinedstorage#1247]
#### Issue description:
joined server after updating to refinedstorage-1.4.7
#### What happens:
server straight up crashes 
#### What you expected to happen:
i could join server and it would work fine
#### Steps to reproduce:
1.add RS 1.4.7 to server then join it with following mods mentioned in crash
2.then join server 
3.profit?
...

#### Version (make sure you are on the latest version before reporting):

- Minecraft:1.11.2
- Forge:1.11.2-2296
- Refined Storage: 1.11.2-1.4.7

Does this issue occur on a server? [yes/no]
yes
#### If a (crash)log is relevant for this issue, link it here:
[crash-2017-05-24_14.14.00-server.txt](https://github.com/raoulvdberge/refinedstorage/files/1026655/crash-2017-05-24_14.14.00-server.txt)

[pastebin/gist/etc link here]

**Comment by raoulvdberge** [comment]
Okay, let's fix this. I'll first need you to do some things:

1) Put this build on your server and client: https://drive.google.com/file/d/0B2PrXMobPWvWWUpmWTB3eXYzQWM/view?usp=sharing
2) Turn the "debugLog" config option on, on the server
3) Start up your server and client
4) Join the server

I'll then need the crashreport and the `refinedstorage_debuglog_<date_here>.txt` file that has been created on your server.
