### ISSUE TITLE
Taking random items out of storage?

### ISSUE THREAD

**Issue by ProfessorProspector** [raoulvdberge/refinedstorage#125]
When I spam shift-click on one item in a storage system, it sometimes gives me random items in my system. Here's a gif example: https://gfycat.com/SoulfulFavoriteHerald (Ignore the fact that my mouse is way off in the gif). I started the gif late on accident, but you can see I'm clicking charcoal and for some reason I got a stack of peridot

**Comment by RealGrep** [comment]
Pretty sure I've had that happen too. I remember checking to make sure it was sorting by name and not count, to see if that was it (it wasn't). Just hadn't gotten to testing it more systematically so I could file a bug. But yeah, seems to be an issue there. I'll poke it tomorrow and see if I can replicate it on demand.

**Comment by raoulvdberge** [comment]
@RealGrep That should be fixed in latest

@ProfessorProspector Was there peridot in your system? If you sort based on itemcount, items change their places and you may get something else because of that.

**Comment by ProfessorProspector** [comment]
There is peridot in my system, however I have the search filter set to charcoal, so no peridot is listed at the time. It only happens when I rapidly shift-click the items out, it seems to give me a random item from my system every now and then.

**Comment by raoulvdberge** [comment]
Were you sorting on itemcount?

**Comment by ProfessorProspector** [comment]
Yes

**Comment by raoulvdberge** [comment]
If you sort based on itemcount, items change their places because your itemcount is changing.

That means that if you spam shift click, you might get something else if the place is changed.

**Comment by ProfessorProspector** [comment]
No that's not what is happening here. It's sorted based on item count, but when I type "charcoal" charcoal is the only item that is showing up. When I spam shift-click, why would I get peridot one of the times?

**Comment by raoulvdberge** [comment]
That is a different story :p

**Comment by ProfessorProspector** [comment]
Watch the gif https://gfycat.com/SoulfulFavoriteHerald

You can see that charcoal is in the search bar, and that when I spam-click on charcoal, I got a stack of peridot from my system one of the times. It's happening every time I spam-click it. Doesn't happen when I click like once a second.

**Comment by varukasalt** [comment]
Same thing is happening to me. Even when I sort for a single item. Still on 0.7.15 Haven't tried with .16 I'm also having major crafting issues. Constantly asking to craft one item, and it starts making something completely different. Sometimes I have to stop and start crafting a few times to get the right item.

**Comment by ProfessorProspector** [comment]
Okay, it's getting worse. I don't even need to shift-click quickly, I just need to click it. I think it gets worse the larger your system is. https://gfycat.com/AdventurousSnivelingBluetickcoonhound

In the above gif you can see that I click on wood and it moves everything around and gives me gold.

**Comment by ProfessorProspector** [comment]
Yeah the system is completely unusable now. Same thing happens on sorted by name mode. It certainly gets worse the more items you have in your system.

**Comment by ProfessorProspector** [comment]
Okay it gets weirder. Breaking and replacing the controller completely fixes the issue temporarily

**Comment by Mohron** [comment]
I have this same issue.

**Comment by raoulvdberge** [comment]
I'm working on it!

**Comment by ProfessorProspector** [comment]
Got a question. I think there were two bugs we were experiencing here. The one that got fixed by replacing the controller is a different one I think. The original bug in this issue is the one I assume you fixed (the shift-clikcing it)

**Comment by raoulvdberge** [comment]
I think the first bug is fixed too, I hope

**Comment by ProfessorProspector** [comment]
alright, cool.
