### ISSUE TITLE
Other cables dosn't connect to Controller

### ISSUE THREAD

**Issue by Bu1ld3rGGs** [raoulvdberge/refinedstorage#1250]
I've wanted to power the controller by connecting IC2 cables next to it. The only problem is that they won't connect to the Controller. I don't know if this is a bug from the other mods or from this.

The cables don't transfer their energy to the controller.

I would really like if Cables of other mods would connect to the Controller.

#### Steps to reproduce:
1. Maybe add a energy accepter.
2. Ask the other modders if they could fix it, if it is a problem by their Mods...

#### Version:
- Minecraft: 1.11.2
- Forge: 1.11.2-13.20.0.2822
- Refined Storage: 1.4.10

**Comment by raoulvdberge** [comment]
Unfortunately, IC2 EU power isn't supported. Try using Forge Energy (RF) or Tesla instead.
