### ISSUE TITLE
Cross dimension wireless transmitter not working

### ISSUE THREAD

**Issue by Xingor** [raoulvdberge/refinedstorage#1252]
#### Steps to reproduce:
1. Set up grid in overworld.
2. Set up crafting grid in nether
3. Set up wireless transmitter in nether. (Doesn't work.)
...

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge: 12.18.3.2297
- Refined Storage: 1.2.25

Does this issue occur on a server? yes

#### If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here]

**Comment by way2muchnoise** [comment]
Are both side chunkloaded?

**Comment by Xingor** [comment]
Yes. The Crafting grid works in the nether and the other side has a chunk loader on. The transmitter is blue like it's working but it doesn't open up the wirless crafting grid.

**Comment by Xingor** [comment]
the transmitter and the grid are both attached to a network receiver btw.

**Comment by raoulvdberge** [comment]
Did you insert the interdimensional upgrade?

**Comment by Xingor** [comment]
Yes. It has the upgrade. As I said the crafting grid works in the nether but not the wireless transmitter. That's why I'm so confused.
