### ISSUE TITLE
Every connection in the network dies

### ISSUE THREAD

**Issue by Malgior** [raoulvdberge/refinedstorage#1253]
#### Issue description:

All import, export, external storage, crafters, terminals randomly lose connection to the network.

#### What happens:

After moving my base and setting up my craftin and production area's everything was fine. it was only after a couple of days things started becomming weird. My enderchest wasn't being emptyed any more. The only solution was destroying the importer and placing it back wich solved the issue. After this happened the other ones began to fail as well. I had to reconnect my storage drives 4 times, my enderchest 6 times and now my autocrafting area is starting to die. Everything is chunkloaded.

#### What you expected to happen:

everything to keep working :)

#### Steps to reproduce:
I have no idea how to reproduce it. I'm using the direwolf modpack and have a pretty extensive network setup. I haven't had any issues for weeks but it recently started. I'm guessing the only way to reproduce is to setup a giant network.

#### Version (make sure you are on the latest version before reporting):

I use the latest stable build of direwolf 20 but not sure wich version are in there

Does this issue occur on a server? 

No

#### If a (crash)log is relevant for this issue, link it here:

No crash occurs everything just stops working.

**Comment by raoulvdberge** [comment]
#370
