### ISSUE TITLE
Feature Request: An Ability to change colors on screens

### ISSUE THREAD

**Issue by zeed86** [raoulvdberge/refinedstorage#1256]
Soo lets say a red screen in my blood magic room, and a Green screen in my botania area, ....
i think that would look awesome if thats could work,

Thx Zeed

**Comment by way2muchnoise** [comment]
I like the sound of this

**Comment by raoulvdberge** [comment]
I don't

**Comment by VT-14** [comment]
Roul, would you have a problem if I spent the better part of a day playing with Hue sliders to try to make a few simple recolored texture packs for those of us who are abnormally obsessed with other colors?

Something along the lines of this:
![2017-05-30_21 22 34](https://cloud.githubusercontent.com/assets/12564251/26611888/36f279a0-457f-11e7-958f-b83cd15e1dd4.png)

**Comment by raoulvdberge** [comment]
I wouldn't mind!

**Comment by calloatti** [comment]
> I wouldn't mind!

Good to know!

![image](https://cloud.githubusercontent.com/assets/12817862/26655975/7bfe67d4-4633-11e7-9f25-dfa38816baf2.png)

**Comment by raoulvdberge** [comment]
@calloatti Interesting, show me more! :D
