### ISSUE TITLE
[Suggestion] Show/Transfer Empty Buckets in the Fluid Grid

### ISSUE THREAD

**Issue by VT-14** [raoulvdberge/refinedstorage#1258]
I think it would be a nice QOL improvement for the Fluid Grid to directly handle empty (Forge/Vanilla?) buckets.

- Show how many are in the system
- Allow empty buckets to be inserted into the system
- Allow empty buckets to be extracted directly from the system
- Potentially allow ordering autocrafting of empty buckets

Currently using Refined Storage 1.4.10 on Minecraft 1.11.2.

**Comment by raoulvdberge** [comment]
The more I think about it, the less I  like it.
