### ISSUE TITLE
Items duplicating and inaccurate disc drive reading

### ISSUE THREAD

**Issue by BootyToast** [raoulvdberge/refinedstorage#126]
I don't really know how to properly explain or demonstrate this, but after transferring all the items from my chests into an interface and into the refined storage network, I have thousands of random things like baked potatoes and even lapis. 

My disc drive is also reading that I have about -6,000,000% disc space used.
![2016-06-19_02 20 09](https://cloud.githubusercontent.com/assets/10050188/16175685/98c084ae-35c4-11e6-930b-d92059cbf3a4.png)

**Comment by Harith163** [comment]
WUT

**Comment by raoulvdberge** [comment]
Okay, I've fixed this bug before. Are you sure you are on the latest version?

**Comment by BootyToast** [comment]
Yep, I'm sure. 0.7.15, right?

**Comment by raoulvdberge** [comment]
Yup. Is the disk drive the only storage medium you have installed, or are there any other devices connected?

**Comment by BootyToast** [comment]
I have an external storage connected to a storage drawer controller with a few drawers branching from that.

**Comment by raoulvdberge** [comment]
Then I have a fix for you coming out in a few minutes ;)
