### ISSUE TITLE
Autocrafting can duplicate items

### ISSUE THREAD

**Issue by Aroma1997** [raoulvdberge/refinedstorage#1260]
#### Issue description:
Autocrafting can duplicate items

#### What happens:
When requesting n of a item to be autocrafted (crafting recipe),  I can take more items out (most of the times 2n-2) items out of the rs system.

#### What you expected to happen:
When requesting n of a item to be autocrafted (crafting recipe),  I expect to be able to get n items.

#### Steps to reproduce:
1. Setup simple autocrafting for crafting recipes
2. Request n items ( n > 1)
3. Try to take out n items from the RS system and see that you got more than that.

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.11.2
- Forge: 13.20.0.2296
- Refined Storage: 1.4.10

Does this issue occur on a server? yes

#### If a (crash)log is relevant for this issue, link it here:

N/A

**Comment by raoulvdberge** [comment]
Did you have this bug with processing patterns on regular patterns?

And does it happen with every item or only a limited set of items that are requested?

**Comment by Aroma1997** [comment]
It definitely happens with crafting patterns. I don't think I observed it with processing patterns.
It happens with all items 90% of the time I request something.

**Comment by winsrp** [comment]
Also I think this is happening with items requested on crafting that have durability. For example:

Using actually additions you can use a knife with a seed in a crafting bench to make bio-mash, the more seeds you use the more durability it takes out of the knife.

When doing autocrafting, and making a crafting recipe such as "knife+seed = biomash" (regular pattern), it will always reuse the same knife, without taking durability from it.

**Comment by raoulvdberge** [comment]
I can not reproduce this.
