### ISSUE TITLE
Fluid disk refuses to empty

### ISSUE THREAD

**Issue by invisusira** [raoulvdberge/refinedstorage#1261]
#### Issue description:
I have a 128k fluid disk that always empties to 3 instead of zero.

#### What happens:
No matter how much extra space is available, the disk always ends at 3 and goes to the "out" section of the disk manipulator. I've filled the disk all the way back up multiple times but it still will not empty to zero.

#### What you expected to happen:
The disk to go to zero.

#### Steps to reproduce:
1. Disk in disk manipulator
2. empty
3. still has 3
...

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge: 12.18.3.2254
- Refined Storage: 1.2.25
- Direwolf20 Mod pack: 10.1.0-10.1.2

Does this issue occur on a server? [yes/no] yes

#### If a (crash)log is relevant for this issue, link it here:
http://i.imgur.com/Cwmjj4L.png

[pastebin/gist/etc link here]

**Comment by raoulvdberge** [comment]
The disk is empty, the display is just wrong.

#908
