### ISSUE TITLE
Storage Capacity goes up TPS goes down

### ISSUE THREAD

**Issue by LittleODie** [raoulvdberge/refinedstorage#1262]
#### Issue description:
Refined Storage causes server to cease working, lowering tps as discs fill up.
#### What happens:
TPS drops to nothing, freezing the server.
#### What you expected to happen:
For TPS to not be affected regardless of storage capacity.
#### Steps to reproduce:
1. Setup some sort of automated farm and input it via Importer to RS system, fill up 8 64k drives.
2. Watch as TPS slows to a hault.
3. Remove RS controller, watch TPS jump back to 20 as if nothing happened.
...

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.11.2
- Forge: 13.20.0.2304
- Refined Storage: 1.4.10

Does this issue occur on a server? yes

#### If a (crash)log is relevant for this issue, link it here:
It doesnt crash it freezes.
[pastebin/gist/etc link here]

**Comment by coderecess** [comment]
You may want to check out this issue: (https://github.com/raoulvdberge/refinedstorage/issues/1041).

I had a similar issue and was going to try this, but I ended up having to start a new world before I could try. So, I don't know if it will work. But, it's worth a shot.

**Comment by LittleODie** [comment]
Interesting.. We started stress testing this again and tps is holding. I've only had the issue when logging back in after a while of being gone (today was getting messages that the server stopped for over an hour) got in where tps was @1 and removed the controller and poof tps 20. However plugging back in the controller and letting the system run again for over 10 minutes now and TPS is holding at 20. I know how to "fix" the issue via removing the controller but not how to replicate, apparently.

**Comment by LittleODie** [comment]
Again had the tps drop resulting in a crash this time with a different user. Once we broke the controller tps stabilized. Ask how long the system was up before this happened and was informed that it was up for days, tps began to drop as they teleported back from someplace.

**Comment by coderecess** [comment]
That's intriguing. I was teleporting also, which seemed to cause the problem to occur quicker. But, the problem did still occur even if I just ran the distance.

Do you know about [Sampler](<https://refinedstorage.raoulvdberge.com/wiki/profiling>)? I've seen them ask for a profile in several posts.

_Sent from my Motorola XT1254 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by raoulvdberge** [comment]
#1041

**Comment by raoulvdberge** [comment]
Also I'd appreciate it if you posted your performance report in there as well. Because reports as these without report are useless and wasting my time.

https://refinedstorage.raoulvdberge.com/wiki/profiling
