### ISSUE TITLE
Crash Minecraft 1.11.2

### ISSUE THREAD

**Issue by manoelps** [raoulvdberge/refinedstorage#1263]
Hi!

I tried installing the refinedstorage, but my minecraft was closing.
After performing several tests I have diagnosed that this only happens if it is used together with the mods:

- Not-Enough-Items-1.11.2-Recommended.jar
- Jei_1.11.2-4.3.5.277.jar
- CodeChickenLib-1.11.2-universal.jar

Follow the log: http://pasted.co/c50d9b92

- Minecraft: 1.11.2
- Forge:  forge-1.11.2-13.20.0.2228
- Refined Storage: Refined-Storage-Mod-1.11.2.jar

Does this issue occur on a server? [yes/no] : NO

**Comment by raoulvdberge** [comment]
Your mc ran out of memory.

**Comment by manoelps** [comment]
Sorted out!

I added more 1GB of memory to the minecraft.

Now:  -Xmx2G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M


"Resolvido!

Eu adicionei mais 1GB de memória para o minecraft.

Agora: -Xmx2G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M"
