### ISSUE TITLE
Refined Storage kicks me from Server trying to open the "Refined Storage Item Inventory." Only

### ISSUE THREAD

**Issue by IDKZAL** [raoulvdberge/refinedstorage#1264]
#### Issue description:
Every time I want to open the Refined Storage GUI ( Doesn't matter in what Console/Wireless stuff) I get kicked from the Server and get this error on the Client. I can still open every other Interface of Refined Storage just not the "main" Item Inventory. 

#### Steps to reproduce:
1. Join Server 
2. Tries to open the Refined Storage Inventory 
3. Gets kicked from the Server with an error.

- Minecraft: 1.10.2
- Forge: forge-12.18.3.2297
- Refined Storage: 1.2.25

Does this issue occur on a server? [yes/no]
No errors on the server side. 

#### If a (crash)log is relevant for this issue, link it here:
Client Console log: https://pastebin.com/raw/f4yP74kh
Server Console log: https://pastebin.com/raw/jCbCmQQC
Ingame Crash Code: https://i.imgur.com/R4fPsTK.jpg

**Comment by IDKZAL** [comment]
Video showing it.: https://www.youtube.com/watch?v=towcwvYZBDo
I tested now further and found out Moving my Refined Storage system fixed it, could it be something with that specific chunk?  I can use everything just fine every inventory works.

**Comment by ktole1999** [comment]
did your RS system cross a chunk border? you can hit F3+g to see borders

**Comment by IDKZAL** [comment]
yes it did.

**Comment by ktole1999** [comment]
that could have contributed to the issue due to chunk load/unload

**Comment by raoulvdberge** [comment]
I'm not really sure what's going on here...
