### ISSUE TITLE
[1.10.2] Added crafting recipes don't showing on JEI

### ISSUE THREAD

**Issue by PanSzelescik** [raoulvdberge/refinedstorage#1265]
**Issue description:**
Added crafting recipes with MineTweaker Recipe Maker don't showing on JEI, but after typing: /minetweaker reload recipes are visible.

**What happens:**
Added crafting recipes for items from Refined Storage with MineTweaker Recipe Maker don't showing on JEI, but after typing: /minetweaker reload recipes are visible. Other crafting recipes added by me for items from other mods are visible normally.

**Version**
- Minecraft: 1.10.2
- Forge: 2297 (latest)
- Refined Storage: 1.2.25
- CraftTweaker: 3.0.25
- MTLib: 1.0.3
- MineTweakerRecipeMaker: 1.2.1.26

**Does this issue occur on a server?**
I don't know

minetweaker.log: [https://pastebin.com/Ap01UGNQ](url)
MineTweakerRecipeMaker.zs: [https://pastebin.com/LgARWVrT](url)
fml-client-latest.log: 
[fml-client-latest.txt](https://github.com/raoulvdberge/refinedstorage/files/1039007/fml-client-latest.txt) (log converted to txt)

**Recipe for Cable:**
![2017-05-30_18 06 21](https://cloud.githubusercontent.com/assets/26679785/26593432/50a23efa-4564-11e7-9450-11a920357d56.png)

**I pressed R on a Cable:**
![2017-05-30_18 06 _28](https://cloud.githubusercontent.com/assets/26679785/26593459/68fdb632-4564-11e7-9825-6d82d7a70325.png)

_*My english isn't perfect. Sorry_

**Comment by raoulvdberge** [comment]
Not an RS problem. Consult MineTweaker.
