### ISSUE TITLE
[1.11.2] Crash with Storagedrawers and Mekanism

### ISSUE THREAD

**Issue by marcin212** [raoulvdberge/refinedstorage#1266]
#### More info:
https://github.com/jaquadro/StorageDrawers/issues/492
https://github.com/aidancbrady/Mekanism/issues/4407

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.11.2
- Forge: 1.11.2-13.20.0.2310
- Refined Storage: 1.4.10

Does this issue occur on a server? 
yes
#### If a (crash)log is relevant for this issue, link it here:
https://hastebin.com/gijinejifa.cs

**Comment by raoulvdberge** [comment]
Not an RS issue
