### ISSUE TITLE
Inverter card needs to return

### ISSUE THREAD

**Issue by bryanspears** [raoulvdberge/refinedstorage#1267]
#### Issue description:
We don't have an inverter card (like the AE/ME system of old)
#### What happens:
Anything with a filter rule set (exporter, importer, interface, etc.) cannot be inverted
#### What you expected to happen:
Ability to invert filter sets

Feature request! :smile:

**Comment by raoulvdberge** [comment]
no

**Comment by way2muchnoise** [comment]
There is black and whitelist what more would you need?

**Comment by bryanspears** [comment]
Ya know. I had been staring at the docs for two weeks and assumed I had seen it all. For anyone else in my situation: https://refinedstorage.raoulvdberge.com/wiki/importer
