### ISSUE TITLE
1.11.2- 1.4.10 Give Back Recipe Not Working Properly

### ISSUE THREAD

**Issue by TwitchtvCarbs** [raoulvdberge/refinedstorage#1268]
#### Issue description:
When crafting the flat transfer nodes from EU2 using a custom recipe with the anvil return back to the player on the craft. (.giveBack) It is returning 2 anvils instead of just one.

#### What happens:
Getting 2x the amount of return item when crafting a flat transfer node from EU2.
#### What you expected to happen:
Should only return 1 anvil and the output item.
#### Steps to reproduce:
1.Open crafting grid
2.Place anvil and transfer node in crafting grid (as the recipe calls for)
3.Take out the output from the recipe and 2 anvils (instead of 1) are given back to the player.

Here is a clip of me showing this bug:
https://clips.twitch.tv/VainHungryOysterHeyGirl

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.11.2
- Forge: 13.20.0.2282 (Recommended)
- Refined Storage: 1.4.10

Does this issue occur on a server? [yes/no]
Happens on both single player and multiplayer.

**Comment by raoulvdberge** [comment]
thx for reading previous issues

#1177

**Comment by TwitchtvCarbs** [comment]
Just thought I'd report, no need to be sassy man gees :/ I guess I didn't see that one. Anyways glad its a know bug though.

**Comment by raoulvdberge** [comment]
you know how much time it takes to process all duplicate issues on an issue tracker? i'm here to fix things, not to close duplicate issues..
