### ISSUE TITLE
Refined Storage Crashes browsing the Inventory. 

### ISSUE THREAD

**Issue by IDKZAL** [raoulvdberge/refinedstorage#1270]
#### Issue description:
Refined Storage Crashes Client while browsing Items.
#### What happens:
Just open the Inventory with Wireless Crafting Terminal and then its crashes randomly. I don't know what it triggers it just happen. It's now the 5th time in a day so idk what it is. 
#### Steps to reproduce:
1. Opens inventory with Wireless Crafting Terminal/Normal Terminal < Doesn't matter wich one.
2. Game Freezes,
3. Game crashes.
...

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge: 12.18.3.2297
- Refined Storage: 1.2.25

Does this issue occur on a server? 
Yes I play on a Server.

#### If a (crash)log is relevant for this issue, link it here:
OpenEye Report: [Link](https://openeye.openmods.info/crashes/a0a64859513b6ef1a85401ca5168934a)
Full Log: [crash-2017-06-01_17.38.24-client.txt](https://github.com/raoulvdberge/refinedstorage/files/1045323/crash-2017-06-01_17.38.24-client.txt)

**Comment by raoulvdberge** [comment]
error while rendering item tooltip

not an rs problem, but of the mod  of the item

**Comment by IDKZAL** [comment]
Thanks for the Info. I thought it is RS because i Transferd all my items to Applied Energistics and it didnt crash.
