### ISSUE TITLE
Refill jetpack fuel / damga compare how to?

### ISSUE THREAD

**Issue by victoroos** [raoulvdberge/refinedstorage#1271]
Hi all

I was working on a system I thought, to let my jetpack (mekanism) when I used it, to go to the refill machine (electrolytic) refill, and then get pushed back to the storage system.
I thought using compare damage no etc, that it would work, (when fitlering)
However, It still only adds the jetpack with excactly that fuel.
I tried external storage (which actually adds it) and the importer export 9which does nothing.

Any tips?

vkr vic

**Comment by raoulvdberge** [comment]
Maybe compare nbt off?

**Comment by victoroos** [comment]
As well as damage?

**Comment by raoulvdberge** [comment]
not an rs problem
