### ISSUE TITLE
Solderer autocrafting 

### ISSUE THREAD

**Issue by wilsondgonzales** [raoulvdberge/refinedstorage#1272]
#### Issue description:

Problem with autocrafting placement (advanced processor)

#### What happens:

the diamond gets slotted in the wrong slot in the solderer, causing a stall. it gets slotted on the top slot instead of the middle

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.11.2
- Forge: 
- Refined Storage: 1.4.10

**Comment by raoulvdberge** [comment]
with a hopper or something?

**Comment by wilsondgonzales** [comment]
@raoulvdberge no the items are in a chest connected via external storage bus. an autocrafter facing a solderer has a processing pattern for the advanced processor. it works to the point until the crafter feeds the diamond to the solderer. it gets slotted on the top slot of the solderer inputs. other processors work fine with the autocrafting except for the advanced processor

**Comment by wilsondgonzales** [comment]
also i notice that when this happens sometimes the grid listing shows a bunch of air #0000. it disappears after a reload of the map

**Comment by raoulvdberge** [comment]
Can't repro

![first](https://raoulvdberge.com/aJayNY)
![second](https://raoulvdberge.com/B91bpH)

I suppose your oredict is messed up, stating equivalency between diamonds and some other ingredient for a solderer recipe that goes in the top slot.

In that case, fix your ore dictionary.
