### ISSUE TITLE
Lag when shift-click crafting with Crafting Grid

### ISSUE THREAD

**Issue by piepie62** [raoulvdberge/refinedstorage#1273]
#### Issue description:
This may not be fixable easily, but when I craft a bunch of modded blocks (Tiny Progressions bone block, Extreme Reactors reactor casing, Mystical Agriculture inferium block, etc) with shift-click on the crafting grid, the server lags for a while; a couple times it has lagged for over 40 seconds.
NOTE: I have tested with vanilla blocks (gold, iron, diamond) and this has not occurred.

#### What happens:
Lag
#### What you expected to happen:
No lag
#### Steps to reproduce:
1. Craft a lot of blocks (iron, gold, diamond, etc)

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge: 12.18.3.2281
- Refined Storage: 1.2.25

Does this issue occur on a server? yes

#### If a (crash)log is relevant for this issue, link it here:
This is happening in SkyFactory 3.0.10

**Comment by raoulvdberge** [comment]
missing profling report

**Comment by piepie62** [comment]
Sorry, didn't know how to do that. Looking through issues allowed me to figure it out, but I suggest that you add the link to that one thread into your response in the future. :)
Here is a [profiling report](http://www.filehosting.org/file/details/669938/craftinglag.nps).

**Comment by piepie62** [comment]
Just noticed, some other things, like vanilla spider eyes, are doing this too.

**Comment by piepie62** [comment]
Here is another [report](https://github.com/raoulvdberge/refinedstorage/files/1049089/CraftingLag2.nps.zip), this time using bones to Tiny Progressions bone blocks. From what I can understand from my very limited and literally picked up about ten minutes ago understanding, most of the overhead is coming from your ExternalStorage.detectChanges() method? I'm going to try doing it with something that isn't in my bank of drawers.

**Comment by piepie62** [comment]
Looking at this [report](https://github.com/raoulvdberge/refinedstorage/files/1049102/CraftingLag3.nps.zip), this time converting dirt to compressed dirt, it seems that the most lag is coming from ItemStorageCache.remove().

**Comment by piepie62** [comment]
Oh, now I managed to get a 
[stall report](https://github.com/raoulvdberge/refinedstorage/files/1049744/stall-2017-06-03_13.14.15.txt) about this. Just thought it might be helpful.

**Comment by raoulvdberge** [comment]
This lag is caused by #1245.
