### ISSUE TITLE
[Feature Request] Larger drive sizes

### ISSUE THREAD

**Issue by piepie62** [raoulvdberge/refinedstorage#1276]
I know this is supposed to be a mod that is basically "AE2 simplified", but right now I feel like the drives have been nerfed excessively between the two. In AE2, the 1k storage cell can hold up to 8128 of a single item, and if it has all 63 item types used, up to 4160 items. Comparing that to RS 1k drives, that is quadruple the item amount for about the same cost. I think that the drive sizes of RS drives should be larger, because in some modpacks (SkyFactory), one can easily get over a couple million items, and, if any mod adds a quarry, the amount of packs for which this would be possible would expand.
For these reasons, I think that the size of the cells should be increased: maybe not quadrupling size, but doubling? I think it would still be balanced well if this happened.

**Comment by raoulvdberge** [comment]
no
