### ISSUE TITLE
Interface stops working after chunks unloaded in 1.10.2 (FTB Beyond 1.8.1)

### ISSUE THREAD

**Issue by cheesecakegangster** [raoulvdberge/refinedstorage#1277]
#### Issue description:

Unloading chunks stops the interface from processing items; I have to break it and place it again for it to start working again.

#### What happens:

Interface works -> disconnect from server -> come back -> interface no work (does accept items, just doesn't process them).

#### Steps to reproduce:

no idea lol worked fine when i tried it in ssp

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge: 12.18.3.2297 for Minecraft 1.10.2
- Refined Storage: 1.2.25

Does this issue occur on a server? 
Yes.

**Comment by raoulvdberge** [comment]
#370

**Comment by cheesecakegangster** [comment]
right, sorry
