### ISSUE TITLE
Botania/Epic Bacon Crafting Bug

### ISSUE THREAD

**Issue by metaphoricalstate** [raoulvdberge/refinedstorage#1279]
#### Issue description: 
Can't autocraft epic bacon

#### What happens: 
When you put an order in for epic bacon, where it would have to craft botania dyes(going mystical agriculture essence > botania flower > botania floral powder) then craft the epic bacon, it ends up just infinitely crafting the dye.

#### What you expected to happen:
The bacon to be crafted

#### Steps to reproduce:
1. Setup autocrafting from mystical ag essence to botania flowers to botania petals to botania floral powder(dye)
2. setup autocrafting of epic bacon
3. attempt to order epic bacon
4. dye is either stuck going up and down or increasing until recipes are removed.

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge: forge-12.18.3.2281
- Refined Storage: 1.2.25

Does this issue occur on a server? yes. my personal skyfactory 3 server

#### If a (crash)log is relevant for this issue, link it here:

not relevant

**Comment by raoulvdberge** [comment]
I don't believe this issue is reproduceable in 1.11+.
