### ISSUE TITLE
Crash on game startup (Needs an Unnamed Mod)

### ISSUE THREAD

**Issue by UnsolvedMysteryMC** [raoulvdberge/refinedstorage#1280]
#### What happens: Whenever i startup the game without the mod its fine, but when i do with the mod it says this: 
![image](https://cloud.githubusercontent.com/assets/29167114/26756613/444e96d4-486c-11e7-94bd-0992e977751a.png)
 Loading entity renderer is where it crashed

#### Steps to reproduce:
1.use those mods and forge 12.18.3.2297
2.startup game
3. it wants supposed core mods
...

#### Version (make sure you are on the latest version before reporting):
Im on the latest 1.10.2 version
- Minecraft: 1.10.2
- Forge:12.18.3.2297
- Refined Storage: 1.2.25

Does this issue occur on a server? [yes/no] no, whenever i startup

#### If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here] no crash, only wants new mods
<img width="512" alt="1" src="https://cloud.githubusercontent.com/assets/29167114/26756650/1cbea61c-486d-11e7-80c2-6636fb4637fc.PNG">
<img width="502" alt="2" src="https://cloud.githubusercontent.com/assets/29167114/26756651/1f064c04-486d-11e7-9b4d-7811ace86d4b.PNG">
<img width="427" alt="plz help" src="https://cloud.githubusercontent.com/assets/29167114/26756652/20cb70d2-486d-11e7-9652-8d988b6e0558.PNG">

**Comment by raoulvdberge** [comment]
You're missing MCMultiPart. I'm not sure why Forge doesn't tell anything about it though

**Comment by UnsolvedMysteryMC** [comment]
Thank you :)
