### ISSUE TITLE
Crash on World tick in deobf environment

### ISSUE THREAD

**Issue by beepbeat** [raoulvdberge/refinedstorage#1281]
#### Steps to reproduce:
1. Start Minecraft with deobf version loaded
2. Load a world
3. ...
4. Crash!

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.11.2
- Forge: 13.20.0.2294
- Refined Storage: commit 81ee28955a9e26fb61b58d84238a43efd31d96fb self-compiled deobf

Does this issue occur on a server? [yes/no]
yes
#### If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here]
https://gist.github.com/beepbeat/8bec47f1faf290f98f11c4ebd176e621

If this has to do with my code/setup, most of it is at https://github.com/beepbeat/RefinedBotania

//Edit: After overriding the point of failure, I encountered another NoSuchFieldError in the GUI classes therefore its possibly a problem with the obfuscation when running the deobfuscated version outside of its gradle environment (or other stuff)

**Comment by raoulvdberge** [comment]
No, your mappings are probably mismatching with the mappings that RS is using.

**Comment by beepbeat** [comment]
You are right, didnt think of that, because I never ever had problems with that
Thank you so much for your help
