### ISSUE TITLE
Sky Factory 3 1.10.2 Refined Storage: Multiple Machines for same material?

### ISSUE THREAD

**Issue by marciox25** [raoulvdberge/refinedstorage#1286]
#### Issue description:
Well I have set 3 Alloy Smelters to craft Glass  automaticaly, but when I request Glass, only one of those Alloy Smelters goes into work of making the Glass. Is this supposed to happen or am I doing something wrong? 
#### What happens:
Multiple alloy smelters setted up with the same recipe, Only one get used.
#### What you expected to happen:
I expected all alloy smelters with the given recipe in it, to craft the requested resource
#### Steps to reproduce:
1.
2.
3.
...

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge: 12.18.3.2281
- Refined Storage: refinedstorage-1.2.25

Does this issue occur on a server? [yes/no]
Yees
#### If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here]

**Comment by raoulvdberge** [comment]
intended

works like you describe in 1.11
