### ISSUE TITLE
True Type Font Replacement Render Issue

### ISSUE THREAD

**Issue by misterfixit** [raoulvdberge/refinedstorage#129]
http://puu.sh/pyKbM.png

That picture displays the problem, basically the true type font replacer is rendering beneath certiain items most notably with the flint. Is there a chance you could add compatibility with this I am posting this on the True Type Font github as well.

**Comment by misterfixit** [comment]
https://github.com/cubex2/BetterFonts/issues/3

**Comment by raoulvdberge** [comment]
Unfortunately, this is not a RS issue. Only thing I'm doing is rescaling the text.
