### ISSUE TITLE
Autocrafting problems for Modular Routers modules

### ISSUE THREAD

**Issue by desht** [raoulvdberge/refinedstorage#1290]
#### Issue description:

I received a report from a user of my mod (Modular Routers) that he wasn't able to set up a crafting pattern to make one of the module items from my mod.  The problem appears to occur when the pattern has an ingredient which is a Modular Routers module item.

#### What happens:

When trying to craft the Sender Module Mk2, Refined Storage claims that there is no Sender Module Mk1 in the system, even though there is.

#### What you expected to happen:

That the Sender Module Mk2 would be craftable.

#### Steps to reproduce:
1. Set up a crafting pattern for a "Sender Module Mk1" (shapeless: blank module, bow, arrow).  This one works and the module can be autocrafted by RS.
2. Set up a crafting pattern for a "Sender Module Mk2" (shapeless: sender module mk1, eye of ender)
3. Try to craft the Sender Module Mk2, ensuring that both the Sender Module Mk1 and an eye of ender are in the RS system.  Refined Storage will show the Sender Module Mk1 as missing (item with red background in the crafting preview).

Additional notes: I'm not certain whether this is a problem with Modular Routers or Refined Storage.  My module items do have NBT tags as soon as they're crafted, but I verified that the NBT on the module in the pattern matches exactly the NBT on the actual module in the RS system.  Also, my module items (~18 of them) all have the same item ID, and use metadata to distinguish them.

Crafting with either a regular crafting table or the RS crafting area _does_ work, when using JEI to move the items into the table.
 
So this issue is partly a request for info - perhaps you've seen problems like this before and I'm doing something wrong...?

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.11.2
- Forge: 13.20.0.2284
- Refined Storage: 1.4.11

Does this issue occur on a server? [yes/no] yes

#### If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here]

**Comment by raoulvdberge** [comment]
Might be fixed by 32b3575a0e6415af2b1b4d92e35200d81f5bc8cd.
