### ISSUE TITLE
Dupe Items (Durability)

### ISSUE THREAD

**Issue by K4kn0K** [raoulvdberge/refinedstorage#1291]
#### Issue description:
U can dupe Items, whene u have a crafting recipe with a tool with durability.
The tool lose his durability until 0 and at this point u must move one item out and in the crafting grid and it´s dupe.

#### What happens:
The Tool with zero durability don´t delete out of the system.

#### What you expected to happen:
The Tool with zero durability delete out of the system.

#### Steps to reproduce:
1. Have one Item with zero durablility
2. Crafting something with it.
3. Do the same thing every time again.
...

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge: 1.10.2-2281-5.2.0-BETA-2353
- Refined Storage: 1.2.25

Does this issue occur on a server?
Yes

#### If a (crash)log is relevant for this issue, link it here:

**Comment by raoulvdberge** [comment]
Which tool?

**Comment by K4kn0K** [comment]
At the moment the Forge Hammer from IC2 and Infusion Crystal from Mystical Agriculture

**Comment by raoulvdberge** [comment]
And this is with autocrafting?

**Comment by K4kn0K** [comment]
No Autocrafting doesn´t work i can only craft it manuel. I can craft one thing and then i must replace the items and craft another thing, one by one. The resources doesn´t consume and the tool don´t go away. ;-)

**Comment by raoulvdberge** [comment]
Duplicate #1170
