### ISSUE TITLE
[1.11.2] CPU spike when player viewing grid, crafting grid or controller GUI

### ISSUE THREAD

**Issue by kwpugh** [raoulvdberge/refinedstorage#1295]
#### Issue description:
CPU utilization on the server is too high

#### What happens:
When any player right clicks to view a grid or crafting grid, the server's CPU utilization for the thread spikes to over 120%

#### What you expected to happen:
Not overuse the CPU

#### Steps to reproduce:
1. Open TOP on the server console to view the java instance
2. have any player right click into a grid or crafting grid
3. watch the CPU utilization jump from 15-20% up to 120%+

...

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.11.2
- Forge: 1.11.2-13.20.0.2315
- Refined Storage: refinedstorage-1.4.11 

Does this issue occur on a server? [yes/no]
YES

#### If a (crash)log is relevant for this issue, link it here:
No crash log or server messages

[pastebin/gist/etc link here]

**Comment by raoulvdberge** [comment]
https://refinedstorage.raoulvdberge.com/wiki/profiling

**Comment by kwpugh** [comment]
I took a sample while a player was in the grid GUI and CPU on the server CPU was 120%+

https://dl.dropboxusercontent.com/u/1949756/pughland.nps

**Comment by AlexiyOrlov** [comment]
It happens also in singleplayer - I can hear my CPU's cooler running on max speed while viewing the GUIs.

**Comment by croftyraider** [comment]
I can confirm this behavior a well. I'm using 1.4.18 on minecraft 1.11.2 with forge 13.20.0.2313

**Comment by raoulvdberge** [comment]
Create a profiling report, these comments are worthless.

**Comment by croftyraider** [comment]
As you wish.

[refinedlag.zip](https://github.com/raoulvdberge/refinedstorage/files/1128890/refinedlag.zip)

**Comment by Volen1** [comment]
Opened June 10th, Dev is an ass. And still no fix out yet. This mod literally crashes our server, and creates unneeded lag that affects everyone playing.

**Comment by kwpugh** [comment]
I originally reported this June 11 and after subsequent updates, the problem has gone away.   Just an FYI.

Raoul is doing a good job on what has matured into a real nice mod, keep up the good work.

**Comment by croftyraider** [comment]
The problem has not gone away for singleplayer. Version 1.4.18 (for minecraft 1.11.2) still exhibits this issue.

**Comment by adih2001** [comment]
I can confirm this. Every time i open crafting grid and even the solder the cpu fan starts spinning very fast. This must be fixed.

**Comment by raoulvdberge** [comment]
@adih2001 NPS file or it didn't happen

**Comment by Volen1** [comment]
Why is it so difficult for you to believe that your shit is fucked. Look into fixing it instead of repeatedly asking for the same thing you've ALREADY been giving. All you're doing is giving yourself, and RS a bad reputation. Your issue obviously hasn't been resolved, and I seriously doubt that MULTIPLE people are going to comment that they have the issue, if they don't actually have the issue.

**Comment by raoulvdberge** [comment]
Every system is different and the issue can be something else different times.

I never said I don't believe this issue exists - I need enough reports for a good fix.

Also I'd recommend you to tone down your foul mouth or you can enjoy a nice ban from this tracker.

**Comment by Volen1** [comment]
Feel free to ban me. Doesn't seem like reporting issues here does anything anyway.

**Comment by raoulvdberge** [comment]
That is obviously false with over 1200 closed issues and 1,5 years of bugfixes.

**Comment by raoulvdberge** [comment]
And those are bugfixes done by me over all that time, not by some idiotic entitled prick like you who comes to tell my on my own issue tracker that I don't fix bugs which I obviously do.

The mod is entirely free and I do this in my spare time as a hobby, I don't need ANYONE telling me that I don't fix bugs.

**Comment by adih2001** [comment]
@raoulvdberge Sorry for the drama.... The problem is that there is no sampler for 1.12 https://refinedstorage.raoulvdberge.com/wiki/profiling
Also it would be awsome if you could make a discord server.

**Comment by AlexiyOrlov** [comment]
There, another nps: [report](http://www.mediafire.com/file/vok2tmz9yfk927m/report.nps)

**Comment by Evert79** [comment]
Minecraft 1.11.2
refinedstorage-1.4.20

inventory.nps with default minecraft inventory gui and no problems.
controller.nps with rf controller gui and high server cpu usage.

[profiles.zip](https://github.com/raoulvdberge/refinedstorage/files/1181068/profiles.zip)

**Comment by raoulvdberge** [comment]
Thanks, I'll look into these later this week.

@adih2001 I added a section for MC 1.12 to the wiki. Don't mind the "drama", you didn't cause it. Some idiots just like to big-mouth me on the issue tracker from time to time.

**Comment by FireEgl** [comment]
@raoulvdberge I'm wondering, did you try to reproduce this yourself?  It's so simple..just place down any RS block with an interface window, and open the interface window while watching task manager to see the CPU usage go up..  You don't even have to provide power to it.

Here's what I can add about this bug:
I noticed it in v1.5.14, and it still exists in 1.5.16.
I'm using Minecraft Forge 14.21.1.2443.
I've tried RS with it as the only mod, and with my full modpack, same results.
It happens both in singleplayer (Windows), and server (Linux).  (The server is the one that experiences the high CPU usage in a client/server combo)
Oddly, Wireless Grid's don't cause the high CPU usage.
The high CPU usage appears to happen in its own thread, as it doesn't lag the server as long as you have enough CPU cores.

And here's my NPS file from the server.. I started sampler before I opened the interface to a Controller in this case, and stopped it maybe 4 seconds later while it was still open.
[highcpu.zip](https://github.com/raoulvdberge/refinedstorage/files/1213468/highcpu.zip)

**Comment by kwpugh** [comment]
Hi @raoulvdberge,

I had this problem on my 1.11.2 server and it went away with some updates.   Now it is on my 1.12 server.   Same behavior as before: player clicks in to a grid and the server CPU spikes up from 2-5% to over %100 on the java thread, as seen through Top and felt by users.

Here is the NPS file: 

[pughland.nps.zip](https://github.com/raoulvdberge/refinedstorage/files/1216636/pughland.nps.zip)

Using: refinedstorage-1.5.14.jar

I will update shortly to the 1.5.16 and see if it happens there.

**Comment by kwpugh** [comment]
I was able to confirm that the CPU spiking does NOT happen in either the Wireless Grids or the Portable Grids.   Any other GUI the player clicks into does cause a CPU spike.

If there is any other additional data or measurement you need to track this down, or if you would like to runs some tests with one of my servers, I would be happy to assist.

**Comment by FireEgl** [comment]
To be clear.. it's not actually a spike, it's sustained high CPU load for as long as a GUI is open.

**Comment by raoulvdberge** [comment]
Thanks for all the profiling reports guys, and sorry for the long wait. I've identified the issue and I'm working on a fix now, coming to the next RS release.
