### ISSUE TITLE
Crash when making Thermal Dynamics duct patterns

### ISSUE THREAD

**Issue by TheChaosKing771** [raoulvdberge/refinedstorage#1296]
#### Issue description: 

The game crashes when rendering a pattern with any recipe for a duct from Thermal Dynamics.

#### What happens:

Game crashes when holding shift to render pattern

#### What you expected to happen:

No crash, working pattern.

#### Steps to reproduce:
1. Make crafting pattern with Thermal Dynamics ducts
2. Hold shift with pattern in inventory

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge: 12.18.3.2316
- Refined Storage: 1.2.26
- Thermal Dynamics: 1.10.2-2.0.1.33

Does this issue occur on a server? [yes/no]

Don't know, probably no.

#### If a (crash)log is relevant for this issue, link it here:

https://pastebin.com/1WsJbabb

**Comment by raoulvdberge** [comment]
Cofh issue.

**Comment by KingLemming** [comment]
Well, sort of. Here's the thing - it doesn't crash anywhere else, and the line it's crashing on suggests that you're passing in a null item.

Are you doing anything special with rendering?

**Comment by way2muchnoise** [comment]
@KingLemming It is an [override of a model](https://github.com/raoulvdberge/refinedstorage/blob/mc1.11/src/main/java/com/raoulvdberge/refinedstorage/render/BakedModelPattern.java#L83-L96)
