### ISSUE TITLE
[Suggestion] Importer import craft results

### ISSUE THREAD

**Issue by Jomik** [raoulvdberge/refinedstorage#1299]
Is it possible to make it so that the importer will only import items that are being auto-crafted? Perhaps even hook into a Crafter. Kind of like the exporter only exports auto-crafted items?

I ran into needing this when I was setting up Blood Magic auto-crafting. Since the same item is used again to craft the next tier of slate, I need the importer to not pull out items that are used for crafting, but only the results.

**Comment by raoulvdberge** [comment]
Yes, it's possible in 1.11

**Comment by Jomik** [comment]
@raoulvdberge As I said, I can't just put the importer in blacklist mode...
I want it to accept Blank Slate, Reinforced Slate, Imbued Slate, etc. out of the Blood Magic altar.
Blank Slate is used for Reinforced Slate. Reinforced Slate is used for Imbued Slate and so on.
So I can't just blacklist those items.
I don't want to import items that are used in auto-crafting.

**Comment by way2muchnoise** [comment]
Redstone logic, a buffer, ... There are tons of other solution, RS isn't here to make every process as easy as crafting a pattern. For some more ideas [see direwolf's video](https://www.youtube.com/watch?v=-sK_UCnCfjo), he solves it using storage drawers and redstone mainly.

**Comment by Jomik** [comment]
@way2muchnoise You're correct. Thanks for the video. It results in having a bit different setup, rather than requesting an amount, I'll just need to have a set amount in stock, I suppose.

I just felt that it made sense to put the feature into the importer, when it's one the exporter has, logically equivalent at least.
