### ISSUE TITLE
[1.11.2] Client-side crash: "java.lang.NoClassDefFoundError: cah"

### ISSUE THREAD

**Issue by kwpugh** [raoulvdberge/refinedstorage#1300]
#### Issue description:
Updating to latest version causes client-side crash at start-up

#### What happens:
Client crashes

#### Steps to reproduce:
1. Update to refinedstorage-1.4.12.jar
2. Start client
3. Crash
...

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.11.2
- Forge: forge-13.20.0.2315
- Refined Storage: refinedstorage-1.4.12.jar

Does this issue occur on a server? [yes/no]
No

#### If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here] https://gist.github.com/kwpugh/4711ff71a37bbde49e1b585149988593

**Comment by raoulvdberge** [comment]
That is weird. It doesn't look like a crash caused by RS.

RS doesn't even appear in the stacktrace.

It works fine for me:
![x](https://raoulvdberge.com/3EucnE)

**Comment by way2muchnoise** [comment]
It seems like an obfuscated - deobfuscated issue.

**Comment by kwpugh** [comment]
For the lay person, what does ob-deob mean?   Any suggestions where to look next?

**Comment by way2muchnoise** [comment]
Is this a modpack you put together yourself? Are you using some client?
