### ISSUE TITLE
Block of gold in solderer produces basic circuits not advanced

### ISSUE THREAD

**Issue by katecw** [raoulvdberge/refinedstorage#1301]
#### Issue description:

If you put a block of gold in a Refined Storage solderer it produces nine Printed Basic Processors instead of 9 Printed Improved Processors. One gold ingot works as expected (a single improved processor).

#### What happens:

See above. Tested twice in two different solderers.

#### What you expected to happen:

That a block of gold produces 9 Printed Improved Processors. JEI shows this recipe.

#### Steps to reproduce:
1. Put a block of gold in a powered solderer.
2. Wait.
3. Observe output.

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.11.2
- Forge: 13.20.0.2315
- Refined Storage: 1.4.12

Does this issue occur on a server? [yes/no]

Yes. Not tested in single player.

#### If a (crash)log is relevant for this issue, link it here:

n/a

**Comment by way2muchnoise** [comment]
Is this with only RS installed or a pack? Cause it sounds like an oreDict mess up.

**Comment by katecw** [comment]
It is with Farscapes, which we're testing in alpha (https://github.com/Beyond-Reality/Beyond-Realty-Farscapes).

Block of gold has oredicts blockGold & blockMetal. Block of iron has blockIron & blockMetal. Will it be that blockMetal which is confusing RS?

**Comment by katecw** [comment]
Closing since this seems to be a pack issue.

**Comment by raoulvdberge** [comment]
I need to rewrite the API for this to take "ingotIron" instead of an actual stack.

**Comment by raoulvdberge** [comment]
@katecw This was fixed in 1.4.13, you don't need to do any changes on your pack.
