### ISSUE TITLE
[1.12] How to test without energy mods?

### ISSUE THREAD

**Issue by donqixot** [raoulvdberge/refinedstorage#1305]
#### Issue description:
Thank you very much for updating to 1.12. I am not sure how to test anything yet since I find no mod which produces energy. Is there any alternative inside the mod itself? I tried to set energy usage to zero in config for every machine, but that does not help. Of course, I could just wait, but curious if there is a way.

#### Version (make sure you are on the latest version before reporting):
- Minecraft: 1.12
- Forge: 1.12-14.21.0.2322
- Refined Storage: 1.5

**Comment by raoulvdberge** [comment]
You could spawn in a Creative Controller, or, you could change the `controllerUsesEnergy` value to `false`. That way, every controller will have infinite power supply.

**Comment by donqixot** [comment]
Thank you!

**Comment by raoulvdberge** [comment]
No problem! If you find any bugs, do not hesitate to report them here :-)
