### ISSUE TITLE
Impossibility to craft in 1.12

### ISSUE THREAD

**Issue by Brandcraf06** [raoulvdberge/refinedstorage#1306]
#### Issue description:
It's impossible to craft all things who created in a crafting table

#### What happens:
Impossibility to craft all things by a crafting table, like Quartz Enriched Iron, Controller... 

I think this is due to recipe book in 1.12
![crafting rs](https://user-images.githubusercontent.com/16505254/27185788-ace3d8a2-51e6-11e7-9315-ddee62dc3123.jpg)

#### What you expected to happen:
The possibility to craft all thing who created normally in a crafting table

#### Steps to reproduce:
1.Place the elements of the craft in crafting table (Like 3 Irons and 1 Quartz for Quartz Enriched Iron)
2.The result don't appear

Or if you have JEI, the craft don't appear directely

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12
- Forge: 14.21.0.2327
- Refined Storage: 1.5

Does this issue occur on a server? [yes/no]
I didn't have tested on a server,

**Comment by raoulvdberge** [comment]
Read the changelog 

https://refinedstorage.raoulvdberge.com/releases/134

"Removed crafting recipes, until Forge adds the recipe system back (raoulvdberge)"
