### ISSUE TITLE
(1.11.2) java.lang.ClassCastException: com.raoulvdberge.refinedstorage.apiimpl.network.node.NetworkNodeGrid cannot be cast to com.raoulvdberge.refinedstorage.apiimpl.network.node.NetworkNodeSolderer

### ISSUE THREAD

**Issue by SDUBZ** [raoulvdberge/refinedstorage#1307]
#### Issue description:
crash on server when placed soldier next to controller

#### What happens:
it crashes server
#### What you expected to happen:
it operate normally
#### Steps to reproduce:
1.have controller powered
2.connect soldier directly to controller
3.profit
...

#### Version (make sure you are on the latest version before reporting):

- Minecraft:1.11.2
- Forge: 2315
- Refined Storage:1.4.16

Does this issue occur on a server? [yes/no]
yes

#### If a (crash)log is relevant for this issue, link it here:
[crash-2017-06-15_11.01.23-server.txt](https://github.com/raoulvdberge/refinedstorage/files/1078050/crash-2017-06-15_11.01.23-server.txt)

[fml-server-latest.txt](https://github.com/raoulvdberge/refinedstorage/files/1078056/fml-server-latest.txt)

[pastebin/gist/etc link here]

**Comment by SDUBZ** [comment]
it was the grid the solderer is connected too

**Comment by raoulvdberge** [comment]
Sorry, can't reproduce.

**Comment by FiveEYZ** [comment]
Everything have been working fine for a long time, but now I keep getting this crash as soon the overworld is done loading:
-  https://gist.github.com/FiveEYZ/446a995726813b20f7da318e7115d7f8

Here is a fml.log:
-  http://paste.ubuntu.com/25178171/ crash start at 17696 (more of them keeps popping up after it!)

Please tell if i need to go somewhere else and report.

**Comment by raoulvdberge** [comment]
@FiveEYZ Can you report this in a new issue? Thanks
