### ISSUE TITLE
Crash when holding a pattern then holding shift

### ISSUE THREAD

**Issue by Starwort** [raoulvdberge/refinedstorage#1308]
#### Issue description:
If you pick up an encoded pattern (i.e. one that has a result, and assumes the texture of a block/item when shift is held), and press shift while still holding it, the server crashes
#### What happens:
Server crash
#### What you expected to happen:
Held item assumes different texture
#### Steps to reproduce:
1. Encode a pattern
2. Pick it up
3. Hold Shift
4. Crash server

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge: 12.18.3.2284
- Refined Storage: 1.2.25
- Modpack: DW20 1.10 + Tinker Tool Leveling and VeinMiner
Does this issue occur on a server? Yes

#### If a (crash)log is relevant for this issue, link it here:
[crash-2017-06-17_18.40.22-server.txt](https://github.com/raoulvdberge/refinedstorage/files/1082681/crash-2017-06-17_18.40.22-server.txt)

**Comment by raoulvdberge** [comment]
Hrm, interesting. The pattern that you pick up, was it in your system before and was a crafting task running for said pattern?

**Comment by Starwort** [comment]
Actually, after looking over the crashlog myself it does seem that it was an autocrafting issue, I had removed the pattern because it was causing a circular dependency, so it could have been the cicular dependency causing the crash.
