### ISSUE TITLE
[Suggestion] Configuration File

### ISSUE THREAD

**Issue by Mohron** [raoulvdberge/refinedstorage#131]
A configuration file is needed for this mod:
- Enable/disable blocks/features
- Adjust power usage of entire mod(multiplier) and/or individual blocks

**Comment by raoulvdberge** [comment]
I will never add a way in the config to disable certain blocks. Thats useless. The whole mod is meant to be played with all the blocks. It doesn't make sense to disable say the importer. Of course, pack makers are free to remove recipes to make the item / blocks unobtainable.

Energy cost config is doable, yes.

**Comment by Mohron** [comment]
I actually only care about the energy costs but in the spirit of completeness I thought I would add what most people end up asking for anyways :)

**Comment by raoulvdberge** [comment]
```
    public int cableRfUsage;
    public int constructorRfUsage;
    public int crafterRfUsage;
    public int craftingMonitorRfUsage;
    public int destructorRfUsage;
    public int detectorRfUsage;
    public int diskDrivePerDiskRfUsage;
    public int externalStoragePerStorageRfUsage;
    public int exporterRfUsage;
    public int importerRfUsage;
    public int interfaceRfUsage;
    public int processingPatternEncoderRfUsage;
    public int relayRfUsage;
    public int soldererRfUsage;
    public int storageRfUsage;
    public int wirelessTransmitterRfUsage;
    public int gridRfUsage;
    public int craftingGridRfUsage;
    public int patternGridRfUsage;

    public int wirelessTransmitterBaseRange;
    public int wirelessTransmitterRangePerUpgrade;

    public int rangeUpgradeRfUsage;
    public int speedUpgradeRfUsage;
    public int craftingUpgradeRfUsage;
    public int stackUpgradeRfUsage;
```
Any more suggestions for config options?

**Comment by Mohron** [comment]
Looks good the RF usage was the main thing I could think of.

Only thing I could think of is the speed upgrades effect could be configurable like the range upgrades.

**Comment by raoulvdberge** [comment]
Fixed
