### ISSUE TITLE
MC 1.12 RS 1.5.2 Only Solderer Recipes craftable

### ISSUE THREAD

**Issue by Knito58** [raoulvdberge/refinedstorage#1312]
I understood the changelog for 1.5.1 as if you made all recipes craftable again. With Forge 14.21.0.2340 I can only see solderer-recipes in JEI. Controller or cable is still not craftable in survival mode.

**Comment by raoulvdberge** [comment]
I think that Forge bug is still present...

**Comment by Knito58** [comment]
Mhhh - Other mods did re-implant their recipes successfully....

**Comment by raoulvdberge** [comment]
Yes, they arent using json recipes. I am

**Comment by raoulvdberge** [comment]
Should be fixed as of latest Forge

https://github.com/MinecraftForge/MinecraftForge/commit/f1881453bee8326c306d519f1fede0b7cf1c0777

**Comment by Knito58** [comment]
With Forge 2343 I can confirm this issue to be fixed:
All recipes are back and running.

**Comment by raoulvdberge** [comment]
Nice!
