### ISSUE TITLE
Autocrafting doesn't start when taking half stack from storage

### ISSUE THREAD

**Issue by HalcyonSpectre** [raoulvdberge/refinedstorage#1313]
#### Issue description:
Autocrafting doesn't start when taking half stack from storage.

#### What happens:
Autocrafting is set like from wiki for 1.11
Interface is set to keep 10 items in stock.
Taking 10 items starts autocrafting as expected.
Taking 5 times doesn't start autocrfating.
Taking another 2 items start autocrafting but it stops at 7 items total.

Breaking and placing cable fixes the issue - crafter crafts missing items.

#### Version:

- Minecraft: 1.11.2
- Forge: 13.20.0.2315
- Refined Storage: 1.4.16

Does this issue occur on a server? [yes/no] no

**Comment by raoulvdberge** [comment]
Errrrr, I thought I fixed this....
