### ISSUE TITLE
Destructor don't destroy snow block

### ISSUE THREAD

**Issue by PanSzelescik** [raoulvdberge/refinedstorage#1316]
#### Issue description:
Destructor don't destroy snow block even with the filter set up.

#### What happens:
I have a system with pure daisy, which turns water into snow. Water is set by the constructor correctly, but destructor don't destroy snow block.
#### Steps to reproduce:
1. I give water to the system
2. Constructor puts water.
3. Wait
4. Snow block don't destroyed by destructor.
...

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.10.2 
- Forge: 2316 
- Refined Storage: 1.2.26

Does this issue occur on a Server? I don't know

Yes, I have FTB utilities and enable fake players interaction option to true

![2017-06-21_20 10 27](https://user-images.githubusercontent.com/26679785/27400153-8541ce0c-56bf-11e7-8686-1b4e7ce2d377.png)
![2017-06-21_20 10 31](https://user-images.githubusercontent.com/26679785/27400154-8545a7d4-56bf-11e7-80a9-baf973fd12f0.png)
![2017-06-21_20 10 58](https://user-images.githubusercontent.com/26679785/27400156-854c44e0-56bf-11e7-8a87-8946d11fba61.png)
![2017-06-21_20 11 19](https://user-images.githubusercontent.com/26679785/27400155-854c084a-56bf-11e7-96b5-dbb22cf08907.png)

**Comment by raoulvdberge** [comment]
![x](https://raoulvdberge.com/DJbsaH)

Works fine here. I'm guessing some permission mod is blocking the destruction of blocks.

**Comment by PanSzelescik** [comment]
Intetesting, I will have to look more closely at this as it happens on my modpack.

**Comment by PanSzelescik** [comment]
This only happens with snow, even when the filter is empty
