### ISSUE TITLE
1.11.2 Solder refuses to make crafting grid (server)

### ISSUE THREAD

**Issue by captcookie** [raoulvdberge/refinedstorage#1319]
#### Steps to reproduce:
1. Recipe just does not work.
2.
3.
...

#### Version (make sure you are on the latest version before reporting):

- Minecraft:
- Forge: 2315
- Refined Storage: Latest

Does this issue occur on a server? [yes/no] Yes.

#### If a (crash)log is relevant for this issue, link it here: N/A

[pastebin/gist/etc link here]

**Comment by captcookie** [comment]
https://cdn.discordapp.com/attachments/325415352949276672/327611877255413762/ScreenHunter_872_Jun._22_19.52.jpg

**Comment by captcookie** [comment]
I had to use the tinkers table for it to work. 💃

**Comment by raoulvdberge** [comment]
Already fixed by https://github.com/raoulvdberge/refinedstorage/commit/8cb0b9181158b0fb801593b14fea8555204a2d49
