### ISSUE TITLE
Craft Only feature for Exporters

### ISSUE THREAD

**Issue by JohnC94** [raoulvdberge/refinedstorage#132]
Can we have a option in exporters (when a crafting upgrade is installed) to only export crafted items instead of items in stock?

**Comment by raoulvdberge** [comment]
Why do you need this?

**Comment by RealGrep** [comment]
I know I've needed that functionality in the past. I was feeding crafting tables to a hungry node, and had to enable that because it kept stealing crafting tables I was making for other recipes. It's useful, sometimes. There are other examples, but that one comes to mind.

**Comment by JohnC94** [comment]
The reason @RealGrep mentioned, as well as it is a nice way to keep a certain amount of items stocked in the system. Detector facing an exporter set to active on redstone signal is a way to keep X amount of items stocked in the system. Is there another way that I've missed?

**Comment by tivec** [comment]
I'm going to necro this feature request and ask for a craft-only upgrade to the exporter. There is no good way of keeping an object that you have to craft stocked.
