### ISSUE TITLE
autocrafting will not "concurrently craft"

### ISSUE THREAD

**Issue by SHOVELL** [raoulvdberge/refinedstorage#1320]
#### Issue description:
auto crafter recipes will not run multiple recipes to craft more, faster
#### What happens:
see above
#### What you expected to happen:
have 3 recipes in 3 crafters it should use them to produce the item needed faster
#### Steps to reproduce:
1.setup crafting for 64k storage disks
2.multiple crafters for each recipe along the way
3.ask for 64k disks(ie i made 256 of them)
4. will only use one of each recipe
...

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge:12.18.3.2281
- Refined Storage:1.2.25

Does this issue occur on a server? [yes/no]
yes
#### If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here]

**Comment by raoulvdberge** [comment]
Fixed in 1.11+

**Comment by SHOVELL** [comment]
No chance of getting this fixed in 1.10.2? Or are you only supporting the
current mc version?

**Comment by raoulvdberge** [comment]
yep
1.10 is unmaintained.

**Comment by way2muchnoise** [comment]
The concurrent crafting has always been a 1.11+ feature that wasn't going to be backported anyways.
