### ISSUE TITLE
1.12 refined storage crash on startup

### ISSUE THREAD

**Issue by ItzKdoge20YT** [raoulvdberge/refinedstorage#1325]
i installed rs even more mods, i run then it crash with Caught exception from Refined Storage Error

crash reports : https://pastebin.com/xEVDTTYn
minecraft version : 1.12
forge : 1.12-14.21.0.2350
refined storage : 1.5.2

**Comment by ItzKdoge20YT** [comment]
i need to close this, just checking.. if mods is missing

**Comment by ItzKdoge20YT** [comment]
ok, it wasn't a problem because some mods i installed was missing, i close this issue now sorry it was movingworld from other mod is missing... i thought was real problem :)

**Comment by raoulvdberge** [comment]
Already known, the latest RS version doesn't work yet on the latest Forge version (2348+)

I'm working on it

**Comment by raoulvdberge** [comment]
Fixed as of d8b3bcca40b9c6dd5c1f1e8dc55d789bb868cb85

**Comment by raoulvdberge** [comment]
RS 1.5.3 is published on Curse which fixes this. May take a while till it appears for you, it's still waiting for approval.
