### ISSUE TITLE
importer does not update texture after rotating

### ISSUE THREAD

**Issue by Darkere** [raoulvdberge/refinedstorage#1327]
#### Issue description: 
When rotating an Importer/exporter/external storage the texture stays the same as when it was first placed.

#### What happens:
 ugly gaps in the cable texture

#### What you expected to happen: 
connected cables

#### Steps to reproduce:
1. place an importer facing onto something it should connect to
2. rotate with wrench
3.
...

#### Version (make sure you are on the latest version before reporting):

- Minecraft:1.11.2
- Forge:2315
- Refined Storage:1.4.17

Does this issue occur on a server? [yes/no] yes

**Comment by raoulvdberge** [comment]
Works fine for me.

**Comment by Darkere** [comment]
Just made a new instance and only installed JEI and RS. Could this be causes by a jvm parameter?

Video of it. https://gfycat.com/GenuineHopefulBetafish

**Comment by raoulvdberge** [comment]
BAD bug report. You make it seem like the texture doesn't rotate at all. Please be more clear next time.

**Comment by raoulvdberge** [comment]
Works fine in 1.6
