### ISSUE TITLE
[1.11.2] Disk Drive / Creative Disks quirk (minor)

### ISSUE THREAD

**Issue by BrisingrAerowing** [raoulvdberge/refinedstorage#1328]
First off, sorry if this is a duplicate, I couldn't find any related issues.

#### Issue description:

Placing two creative drives into a disk drive causes the quantity to initially display as 0 / -2. The system is still functional, it just looks a bit odd.

#### What happens:

Quantity is displayed as 0 / -2

#### What you expected to happen:

Quantity is displayed as 0

#### Steps to reproduce:
1. Place a disk drive
2. Place two creative disks into it (tested with 1 item and 1 fluid disk)
3. Observe the quantity display
...

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.11.2
- Forge: 13.20.0.2315
- Refined Storage: 1.4.17

Does this issue occur on a server? [yes/no]

Untested on server.

#### If a (crash)log is relevant for this issue, link it here:

No logs.

**Comment by raoulvdberge** [comment]
https://refinedstorage.raoulvdberge.com/releases/140

Fixed Disk Drive giving incorrect capacity for creative and debug storage disks (raoulvdberge)

Already fixed. Please use the latest version.
