### ISSUE TITLE
[1.11.2] Chisels&Bits bit placed in a RS cable block-space visually removes the cable & bit

### ISSUE THREAD

**Issue by Lordmau5** [raoulvdberge/refinedstorage#1329]
#### Issue description:
When placing down a Chisels&Bits ... bits block into the same block-space as a RS cable, the block-space vanishes and it's impossible to remove those blocks manually.
Not even re-entering the world / server makes them re-appear.

#### What happens:
Now look at this GIFV, that I just found (and can't embed sadly):
https://i.imgur.com/0wVgcdV.gifv

#### What you expected to happen:
Considering both RS and Chisels&Bits rely MCMultipart I would expect them to work fine in combination and thus also render just fine.

#### Steps to reproduce:
1. Place down RS Cable
2. Try to put bits from Chisels&Bits into the same block-space
3. The whole block-space isn't being rendered anymore, thus also not able to remove the blocks from it.

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.11.2
- Forge: 1.11.2-13.20.0.2315
- Refined Storage: 1.4.18

#### Does this issue occur on a server?
Yes

#### If a (crash)log is relevant for this issue, link it here:
When the Chisels&Bits bit is placed down, this appears in the console:
https://pastebin.com/3ZRvBrmT
It doesn't fully crash the game, it just shows that error.

**Comment by way2muchnoise** [comment]
Does that also happen without a shader?

**Comment by Lordmau5** [comment]
I'll completely remove OptiFine for a minute and see if it happens as well, give me a few minutes :)

**Comment by Lordmau5** [comment]
Can confirm, same thing happens without OptiFine, and thus without shaders, as well:
http://i.imgur.com/qfECmg1.gifv

**Comment by Lordmau5** [comment]
Alright, I downgraded MCMultipart to 2.0.0 (was 2.0.1 before) and the bug disappeared?
![img](https://i.lordmau5.com/1498393882-10842.png)

Seems like I need to bug @amadornes about this 👀 
I've stumbled upon this and someone was mentioning that things were disappearing as well...
https://github.com/Beyond-Reality/Beyond-Realty-Farscapes/issues/31

**Comment by raoulvdberge** [comment]
AFAIK  this is a MCMP issue:

```java
    @Override
    @Nonnull
    @SuppressWarnings("unchecked")
    public N getNode() {
        if (world.isRemote) {
            if (clientNode == null) {
                clientNode = createNode(world, pos);
            }

            return clientNode;
        }
```
The tile has no world set. RS needs a world in order to get the network node.

**Comment by amadornes** [comment]
No world? I thought I fixed that bug the other day... :/

**Comment by raoulvdberge** [comment]
Additional note: this is 1.11.

**Comment by raoulvdberge** [comment]
This is a Chisel & Bits issue. Please open it on their issue tracker, @Lordmau5
