### ISSUE TITLE
RS 1.3.x/1.4.x/1.5.x does not list MCMultiPart as required library on CurseForge

### ISSUE THREAD

**Issue by JamiesWhiteShirt** [raoulvdberge/refinedstorage#1330]
#### Issue description:
It seems all 1.3.x/1.4.x/1.5.x releases of Refined Storage do not list MCMultiPart as a required library. When added as a required library, MCMultiPart is automatically installed when Refined Storage is installed with the Twitch client. It will also be listed on the page of the file.

#### What happens:
![image](https://user-images.githubusercontent.com/5446387/27518847-1c18bc92-59e9-11e7-8b08-3f4cd4f522b3.png)

#### What you expected to happen:
Not the above.

#### Steps to reproduce:
1. Install a 1.3.x/1.4.x/1.5.x version of Refined Storage in a clean instance with the Twitch client.
2. Launch the game.

#### Version (make sure you are on the latest version before reporting):

- Minecraft: N/A
- Forge: N/A
- Refined Storage: 1.3.x/1.4.x/1.5.x

Does this issue occur on a server? N/A

---

I'm guessing there is something wrong with your publishing task, assuming you have a build server. If you publish files manually, you can remove the tedium using CurseGradle. It is a Gradle plugin that allows you to publish artifacts with descriptions, changelogs and dependencies.

**Comment by raoulvdberge** [comment]
1.3.x/1.4.x/1.5.x doesn't require MCMultiPart...

**Comment by raoulvdberge** [comment]
1.4.x:
```java
public static final String DEPENDENCIES = "required-after:forge@[13.19.1.2188,);after:jei@[4.5.0,);";
```
Doesn't have a MCMP requirement.

1.5.x:
```java
public static final String DEPENDENCIES = "required-after:forge@[14.21.0.2363,);after:mcmultipart@[2.2.1,);";
```
Has a MCMP requirement, but only if MCMP is installed in the first place (hence the `after` and not `required-after`)

**Comment by JamiesWhiteShirt** [comment]
I reported this for someone else and it seems there was a slight misunderstanding. MCMultiPart is missing from the dependencies page of the project because the latest files do not use the dependency. It turns out to be an issue with CurseForge's dependency resolution and not an issue with the Refined Storage project.

Sorry for bothering you!

**Comment by raoulvdberge** [comment]
Only the 1.10 version is dependant on MCMP. I'd appreciate it if you first validated your claims before making them.
