### ISSUE TITLE
Suggestion: Show Ctrl+Shift force crafting shorcut hint as text in dialog instead of tooltip

### ISSUE THREAD

**Issue by scifibob** [raoulvdberge/refinedstorage#1331]
I recently searched for a solution for autocrafting Mystical Agriculture essences, and in the comments I saw that it was possible to press Ctrl+Shift to force the crafting operation anyway.

I must admit that I never knew that this was possible (sorry for not reading the wiki thorough enough), but it never occurred to me that hovering over a disabled button could show a tooltip.

Maybe it would be a good idea to show this specific tooltip in a label (as text) below the buttons instead?
The crafting preview window isn't that large, so there should be room for it.

**Comment by raoulvdberge** [comment]
No.
