### ISSUE TITLE
Constructor not placing block with Security Manager and Card present in system

### ISSUE THREAD

**Issue by Bakamon0** [raoulvdberge/refinedstorage#1332]
#### Steps to reproduce:
1. Setup basic RS system with Security Manager and Card
2. Setup Constructor and Destructor with desired block
3. Item will not place unless Card is removed from Security Manager
...

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.11.2
- Forge: 13.20.0.2345
- Refined Storage: 1.4.18

Does this issue occur on a server? [yes/no] Yes

#### If a (crash)log is relevant for this issue, link it here: N/A

[pastebin/gist/etc link here]

**Comment by raoulvdberge** [comment]
Can I see your setup?

**Comment by raoulvdberge** [comment]
Nevermind, figured it out!
