### ISSUE TITLE
[1.10.2] Pattern grid/encoder blank pattern automation (feature request + bug report)

### ISSUE THREAD

**Issue by pdohogne** [raoulvdberge/refinedstorage#1334]
#### Issue description:
**Feature request:** I want to be able to automate keeping my pattern grid and encoder stocked with blank patterns.  The pattern grid isn't recognized as an inventory, so putting the patterns in has to be done manually.  

**Bug:** The encoder, on the other hand, will accept piped-in patterns, which is good, but attempting to insert more than a stack puts the excess in the output slot (which you can't manually insert anything into and shouldn't accept items).

#### What happens:
Piping in blank patterns does not work for Pattern Grids, and can put blank patterns in the output slot of Pattern Encoders.

#### What you expected to happen:
Pattern Grid to accept automated insertion of blank patterns and the Pattern Encoder to only accept insertion of patterns into the input/blank slot.

#### Steps to reproduce:
**Pattern Grid:**
1.  Create a Pattern Grid and hook an importer or other means of inserting an item into a container set to insert blank patterns.
2.  Observe that patterns no not get into the input/blank slot of the grid.

**Pattern Encoder:**
1.  Create a Pattern Encoder and hook an importer or other means of inserting an item into a container set to insert blank patterns.
2.  Attempt to insert two stacks of blank patterns into the encoder via the importer/conduit/pipe/node/etc.
3.  Observe that the second stack of blank patterns end up in the output/encoded pattern slot.

...

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge: 12.18.3.2316
- Refined Storage: 1.2.26

Does this issue occur on a server? Unknown, playing single-player.

**Comment by pdohogne** [comment]
Is there any way this could be backported to 1.10.2?

**Comment by raoulvdberge** [comment]
How 'bout no

**Comment by pdohogne** [comment]
Just curious, thanks.  If I were to do so and submit a pull request, would you consider it?

**Comment by raoulvdberge** [comment]
No, 1.10 isn't getting updates.
