### ISSUE TITLE
Autocrafting with External Storage Drawers not working properly. (SF3)

### ISSUE THREAD

**Issue by RavenHeng** [raoulvdberge/refinedstorage#1339]
#### Issue description:
External storage on Drawer controller not working with autocrafting, despite it working fine with dispensing the items into machines. I have read other posts about the autocrafting issues with storage drawers on External storage however it does not work with oredict checked or not.
#### What happens:
When trying to autocraft with a crafter, if the required items are in storage drawers it is does not autocraft.
#### What you expected to happen:
Crafter to craft the item specified
#### Steps to reproduce:
1.Have your required crafting items in a drawer that is connected to a drawer controller.
2.Link the drawer controller up to the RS system with a external storage.
3.Have a crafter with any crafting pattern that is linked with the RS system.
4.Try to craft with the crafter in the RS system.
5. Crafter will not craft the item.
#### Version (make sure you are on the latest version before reporting):
1.2.25( Looked at 1.2.26 the latest 1.10.2 version for refined storage and it is not fixed)
- Minecraft: 1.10.2
- Forge: 12.18.3.2281
- Refined Storage: 1.2.25

Does this issue occur on a server? [yes/no]
Yes
#### If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here]

**Comment by raoulvdberge** [comment]
1.10 is unsupported.
