### ISSUE TITLE
CTRL clicking item pulls one single item out of the system

### ISSUE THREAD

**Issue by ProfessorProspector** [raoulvdberge/refinedstorage#134]
A feature from AE that I miss a lot. Like when you normally click it pulls a stack out, if you're holding control it would only pull out one item.

**Comment by raoulvdberge** [comment]
In RS you use middle click

**Comment by ProfessorProspector** [comment]
Can ctrl+click move a single item to your inventory then? Like a shift-click but with only one item?

**Comment by raoulvdberge** [comment]
Use shift + ctrl click :p

**Comment by ProfessorProspector** [comment]
If you middle click more than once it doesn't give you multiple items FYI

**Comment by RealGrep** [comment]
Now that would actually be a very good improvement. It really should give you an item on your cursor every time you do it, in my opinion.

**Comment by raoulvdberge** [comment]
I could do that, yeah.
@RealGrep Btw, real quick, is the issue with the machines dying fixed?

**Comment by RealGrep** [comment]
I've got the new version in, but haven't ran any tests yet. I'll remove the chunk loaders temporarily and run some tests later tonight and let you know in the "Solderer dying" PR. Thanks for all the excellent work. :)
