### ISSUE TITLE
Ticks skipped / Massive lag

### ISSUE THREAD

**Issue by Tydesson** [raoulvdberge/refinedstorage#1341]
#### Issue description:
Every XX seconds, a massive lag occurs on the server, and the logs are always the same. The server just freeze for XX seconds, and then skips about 800 ticks and goes on, and then it happens again. Same logs, always, repeated. Not sure if it's related to Refined Storage or Forge / IC2.

#### What happens:
Massive lag, ticks skipping

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge: 12.18.3.2316
- Refined Storage: 1.2.26

Does this issue occur on a server? yes

#### If a (crash)log is relevant for this issue, link it here:

https://pastebin.com/MHczHPik

**Comment by raoulvdberge** [comment]
It's IC2

**Comment by aelfwyne** [comment]
To the original poster of this bug: Check your server for any kind of entities that there are too many of. The most common is xp orbs, or items collecting on the ground from errant mob farms. You can use Minimally Correct's Tick Profiler to find the entities with the highest count on your server. Anything in the thousands will certainly cause lag, and left long enough, can hardlock the server to where you can't even issue commands.
