### ISSUE TITLE
"No external storage" Display feature

### ISSUE THREAD

**Issue by RussellChamp** [raoulvdberge/refinedstorage#1343]
I frequently augment my refined storage system with a series of drawers, chests, etc as external storage options due to a number of nice features (more efficient storage, voiding, aesthetic pleasure, etc). However, when my RS drives fill up, I would like a way to identify what types of items are taking up the most space in the disks. To that end I propose the following:

- Add a grid "Display" option to hide all inventories linked with "External Storage" interfaces
- Add a grid "Display" option to show only inventories linked with "External Storage" interfaces

![image](https://user-images.githubusercontent.com/242294/27802357-5e2340f4-5ff1-11e7-9707-15c9fcc7e4db.png)

Thanks for the awesome mod, Raoul! I've been enjoying it a lot on Skyfactory 3. While I've not done any MC modding of my own, I may try to work on a pull request for this.

**Comment by raoulvdberge** [comment]
Someone suggested this before and I didn't want it, see #1168

Additionally, in RS for 1.11 and 1.12 you could use a "portable grid" to see individual disks.
