### ISSUE TITLE
[1.10] FTB Beyond ver. 1.9.0 - connecting controller to a crafting grid and disk drive causes FPS drops

### ISSUE THREAD

**Issue by lasiecz** [raoulvdberge/refinedstorage#1344]
#### Issue description:

When I connect controller to a crafting grid and disk drive my FPS drop from 60 to 20, making the game unplayable. Placing the controller somewhere else is not a problem only when connected with grid and drive.

#### What happens:

FPS drop from 60 to 20.

#### What you expected to happen:

Nothing.

#### Steps to reproduce:

1. Connect the controller to a crafting grid, disk drive, solderer and power source.

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge: 12.18.3.23
- Refined Storage: 1.2.26

Does this issue occur on a server? [yes/no]

No.

#### If a (crash)log is relevant for this issue, link it here:

No.

[pastebin/gist/etc link here]

![2017-07-04_09 30 25](https://user-images.githubusercontent.com/12786747/27819791-1864bbdc-609c-11e7-99c0-dd65bfbe192c.png)
![2017-07-04_09 30 33](https://user-images.githubusercontent.com/12786747/27819793-18690340-609c-11e7-91ae-66b8a9ff863a.png)
![2017-07-04_09 30 47](https://user-images.githubusercontent.com/12786747/27819792-1865e228-609c-11e7-9c4f-36545a0eb176.png)

**Comment by lasiecz** [comment]
Okey, that was fast because somehow this setup solved it:

![2017-07-04_09 45 41](https://user-images.githubusercontent.com/12786747/27820139-a731de02-609d-11e7-858b-e7afbd21506f.png)

Just restarted the game and rebuilt it.

**Comment by raoulvdberge** [comment]
1.10 is unsupported
