### ISSUE TITLE
crashed when clicking on crafting grid

### ISSUE THREAD

**Issue by IchigoGames** [raoulvdberge/refinedstorage#1347]
#### Steps to reproduce:
1.  click on a crafting grid
2. with invar in your hand
3.
...

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.11.2
- Forge: 2393
- Refined Storage: refinedstorage-1.4.18

Does this issue occur on a server? [yes/no] yes

#### If a (crash)log is relevant for this issue, link it here:

https://pastebin.com/znsf9VFC

**Comment by raoulvdberge** [comment]
Duplicate of #1338, will be backported to 1.11 soon.
