### ISSUE TITLE
Refined Storage EnderIO Conduits

### ISSUE THREAD

**Issue by ProfessorProspector** [raoulvdberge/refinedstorage#135]
Now I know that this cannot be done on your side, it must be done on enderio's side, however they have said they don't have time to add more conduits, but they would be happy for someone to PR it in. https://github.com/SleepyTrousers/EnderIO/issues/3422

If you have any extra time one day this might be a project that would be cool. It's kinda annoying having to run two sets of cables under our base lol

**Comment by plumpudding** [comment]
I guess I will give it a try.. Don't expect anything though..

**Comment by raoulvdberge** [comment]
Technically EIO can ship the API, however I want to get the API on a central Maven / Gradle repo first, so you don't need to bundle it in by copy-pasting.

But you can start on it I guess, just look how existing cables work (they basically have to  be an INetworkNode).

**Comment by EvilNotion** [comment]
I'm dying for this -- or even if Refined Storage conduit could be made to work with Conduit Facades..  I realize it uses MCMultiPart - so Chisel & Bits could be done to hide conduit, but that's just an additional hassle.  

PS. Thank you guys for all the work you do on Refined Storage, it's an amazing mod without the complexity of AE.

**Comment by Joshwoo70** [comment]
...RS uses MCMultipart? wut.... i thin you got it wrong man...

**Comment by way2muchnoise** [comment]
Nope @Joshwoo70 RS indeed uses multipart, so you can chisel and bits all around it

**Comment by FancyBanana** [comment]
Any progress on this feature? I really prefer your mod to ae2 and these feature would be a really great addition. Also, since EnderIO is basically core mod for modpacks, this will be a huge plus in your feature list.

**Comment by raoulvdberge** [comment]
This feature is planned for EiO in 1.11, the EiO devs will be adding it there.

**Comment by raoulvdberge** [comment]
Closing this, as the EiO guys will do this on their end.
