### ISSUE TITLE
MC 1.12 RS 1.5.8 hard dependency to Storage Drawers 1.12-5.2.2 ??

### ISSUE THREAD

**Issue by Knito58** [raoulvdberge/refinedstorage#1350]
On loading the MC loader stops with this message:

Refined Storage is missing mods it depends on.
Include the following mods or remove Refined Storage.

storagedrawers 1.12-5.2.2 or above

I upgraded forge to 2402 because Storagedrawer 5.2.2 was stuck. But it still was stuck after the upgrade of Forge. So I re-enabled the 5.2.1 version. Now RS is stuck :P

Maybe this is not a bug in RS because if SD is there it would have to check for the correct version. Now I already wrote too much to not send it as I feel there should be some hint on curseforge about a possible dependency when SD was installed.

:)
How could I know what I think before I had read what I wrote?
:)

**Comment by raoulvdberge** [comment]
RS had no hard dep on SD. If SD is installed, we require version 5.2.2 because of API changes. And yes, I'm aware that SD 5.2.2 crashes. But that is not an RS issue.

**Comment by Knito58** [comment]
Yes. No dep. When removing SD everything works just fine.

**Comment by raoulvdberge** [comment]
Should be fixed with SD 5.2.3
