### ISSUE TITLE
[1.12] Thermal Expansion compatibility

### ISSUE THREAD

**Issue by Skillotic0703** [raoulvdberge/refinedstorage#1351]
Could you add support for the crescent hammer in Thermal Expansion please? It would be cool if it was able to dismantle all blocks and cables in RS!

**Comment by raoulvdberge** [comment]
No.

**Comment by Skillotic0703** [comment]
Ok thank you for your answer!

**Comment by raoulvdberge** [comment]
The wrench of TE should only rotate foreign blocks. To dismantle RS blocks you need an RS wrench, which makes the most sense. Also TE wrench doens't have a toggle to toggle between rotation mode and dismantling mode, which makes it impossible. The two wrenches have two different goals.

**Comment by Skillotic0703** [comment]
Ok I understand!

**Comment by Skillotic0703** [comment]
But the wrench of TE when used on TE blocks can be used to rotate them but can also dismantle them when you shift-click! But I know that you're wrench works differently so I understand that it may be annoying for you to add!

**Comment by KingLemming** [comment]
Yeah the TE wrench just makes the assumption that if you are sneaking, you want to dismantle. It's not an unfair assumption and makes the wrench a lot more intuitive to use.

**Comment by raoulvdberge** [comment]
The intuitiveness of that mechanic is only relative, and I still think a basic wrench should only do rotation and for more specialization (e.g. dismantling) you'd need the mod-specific wrench.

**Comment by KingLemming** [comment]
Your opinion on what x-mod wrenches should do is reasonable. If you don't want x-mod compatibility, that is fair.

However, given that I've had the same dismantle mechanic in place for 5 years, the intuitiveness of it is widespread over the community. It's relative only in the sense of it being relatively well understood to most of modded Minecraft.
