### ISSUE TITLE
Grid unusable for 64k disks

### ISSUE THREAD

**Issue by Symbai** [raoulvdberge/refinedstorage#1352]
#### Issue description:

If I place 1k disk in my drive, the storage works fine. If I place 64k fluid disk in my drive, the grid is unusable. Means I cannot put any items into it. The grid controller has full energy...

#### Steps to reproduce:
1. Create a new world, place a grid, disk storage and controller next to each other
2. Insert a single 64k disk into disk storage
3. Place 6 windmills  (512k FE output each) and connect them with gold cable to controller
4. Open grid and try to place an item into it, it won't work
5. Insert a 1k storage disk, and inserting items will work

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12
- Forge: 14.21.1.2396
- Refined Storage: refinedstorage-1.5.8

Does this issue occur on a server? [yes/no]

Playing single player

#### If a (crash)log is relevant for this issue, link it here:

No crash

**Comment by way2muchnoise** [comment]
[**Fluid** disk](https://refinedstorage.raoulvdberge.com/wiki/64k-fluid-storage-disk), it is meant to store fluids using the [Fluid Grid](https://refinedstorage.raoulvdberge.com/wiki/fluid-grid), you need to make a [regular disk](https://refinedstorage.raoulvdberge.com/wiki/64k-storage-disk) to store items.
