### ISSUE TITLE
[1.12] [Bug] Stuff deleted

### ISSUE THREAD

**Issue by Dijkstra1** [raoulvdberge/refinedstorage#1354]
#### Issue description:
Put some compacting drawer on an external to get things out of the RS system like the 50k coal, so I run all my disk through a disk manipulator, and now some of the drives say they got stuff on them but nothing shows up in the terminal when there are in drive 

#### What happens:
Stuff appears to be gone forever

#### What you expected to happen:
All that could go into the drawers go and ever thing else left on drives

#### Steps to reproduce:
1. hook up some external storage 
2. run drives through disk manipulator
3. cry
...

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12
- Forge: 14.21.1.2404
- Refined Storage: 1.5.8

Does this issue occur on a server? [yes/no] YES

#### If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here]

**Comment by raoulvdberge** [comment]
That is a storage drawers bug (which I warned everyone on ATM about), you have to update storage drawers.
