### ISSUE TITLE
Some Hatchery Eggs causing Refined Storage Crashes

### ISSUE THREAD

**Issue by ayla2656** [raoulvdberge/refinedstorage#1355]
#### Issue description:
Since the Skyfactory 3.0.13 update some hatchery eggs when in refined storage will cause it to crash for the player.
#### What happens:
we had a 10 10 10 lava chicken egg in our refined storage before the update and no issues but after the server updated to the 3.0.13 version of skyfactory when we looked into the refined storage using any grid it would crash instantly.  We used a disk manipulator to take all items off the disk until we located the item that was causing the crash.
#### What you expected to happen:
hopefully it can be fixed to allow hatchery eggs to be put into the refined storage system without any issues
#### Steps to reproduce:
1. place a 10 10 10 lava chicken egg from hatchery into a refined storage system using any method
2.open any refined storage grid (ie, crafting, wireless, or just grid)
3.your character will freeze and crash
...
we were able to reproduce several times, not sure if other hatchery eggs as there are 1000's but the one we were able to determine with 100% accuracy is the 10 10 10

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge: 12.18.3.2281
- Refined Storage: 1.2.26
- Hatchery: 1.10.2-0.3.17

Does this issue occur on a server? [yes/no]
yes
#### If a (crash)log is relevant for this issue, link it here:
not sure if it is relevent
https://pastebin.com/Jc51CbBd

**Comment by raoulvdberge** [comment]
Looking at the crashlog, that would be a Hatchery issue

**Comment by ayla2656** [comment]
k i will report this exact on hatchery as well tyvm
