### ISSUE TITLE
Make JSON Solderer recipes available for other modders

### ISSUE THREAD

**Issue by GazbonicAcid** [raoulvdberge/refinedstorage#1356]
Does the Solderer and what-not use the JSON recipe system in the MC 1.12 version?

**Comment by raoulvdberge** [comment]
No, not yet

**Comment by raoulvdberge** [comment]
In version 1.5.10 they will use JSON recipes, as the above commit.

**Comment by SirWindfield** [comment]
Is it possible for other mods to make usage of the json recipes loader? Like, just putting some files under `assets/mymod/solderer_recipes`?

**Comment by raoulvdberge** [comment]
Not yet, I still have to make that happen somehow.

**Comment by SirWindfield** [comment]
Don't want to open up another issue for this simple question. Was there a reason why the removeRecipe method has been removed from the API?

**Comment by raoulvdberge** [comment]
Yes, because the `getRecipes` method in `ISoldererRegistry` is modifiable, so `removeRecipe` is unneeded.

**Comment by raoulvdberge** [comment]
The solderer is getting removed.
