### ISSUE TITLE
[1.12] Autocrafting stopping

### ISSUE THREAD

**Issue by 016Nojr** [raoulvdberge/refinedstorage#1357]
#### Issue description: 
While autocrafting with solderers, RS tends to stop/pause the autocrafting

#### What happens: 
In this specific case (there are multiple) I issued a request for 3 Crafters (RS). I have 3 crafters. All of them are being used in this operation, one of them handles the printed silicon and the advanced processor, the second handles printed basic processor, and the third handles basic processor and a printed advanced processor. The finished results are transferred through a Signalum-Played Impulse Itemduct to a Interface.

When I started this, it crafted the silicon (Smelting quartz in a furnace), and then after a minute, it crafted the printed silicon, then stopped. I have tried taking the patterns in and out of the crafters, but that just moves it from "Items processing" to "Items crafting", without actually doing anything.

#### What you expected to happen: 
Expected the system to craft 3 crafters without pausing/stopping

#### Steps to reproduce:
1. Follow the first paragraph in "What happens:"

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12
- Forge: 14.21.1.2406
- Refined Storage: 1.5.9

Complete modlist: http://www.modlister.com/user/016Nojr

Does this issue occur on a server? Not known, playing alone in a singleplayer world

**Comment by 016Nojr** [comment]
What did you edit @way2muchnoise?

**Comment by way2muchnoise** [comment]
Some formatting, nothing content related. You should be using a new line after the titles (`###`) otherwise the whole things is in bold. Bold is kinda annoying to read imo.

**Comment by 016Nojr** [comment]
ah, I didnt even think about that.

**Comment by 23Link89** [comment]
Same thing happens in 1.10.2 but instead, says "Machine is in use" and can happen on machines other than solderers. But it happens consistently with solderers that have to make bigger recipes. Less often with smaller recipes etc

**Comment by Xeavior** [comment]
I've run into the same issue. 

Version (make sure you are on the latest version before reporting):
Minecraft: 1.12.2
Forge: 14.23.2.2641
Refined Storage: 1.5.32
ModPack: All The Mods 3: 5.9.2

This setup is running on a server. I got the crafter to work with the solderer. However, once I had logged off to do something else and came back, the crafting monitor states that all recipes for the solderer are unable to complete due to "Machine In Use"

**Comment by 23Link89** [comment]
I've solved my issue, I figured out what was happening. So I had an alloy smelter that turned quarts into silicon, though if three quarts was in the input slot it would make fuzed quarts. I've solved this by having only my alloy smelter smelt alloys and a Redstone furnace for everything else

**Comment by raoulvdberge** [comment]
I rewrote autocrafting in v1.6, so this should be fixed there...
