### ISSUE TITLE
Allow use of regex in search bar

### ISSUE THREAD

**Issue by ProfessorProspector** [raoulvdberge/refinedstorage#136]

**Comment by raoulvdberge** [comment]
@ and # are in already, not sure about regex search. Does anyone actually use that?

**Comment by ProfessorProspector** [comment]
Or at least allow a | to add multiple search queries at once

**Comment by tyler489** [comment]
For some reason @pam doesnt work but @harvestcraft works for 
Pam's harvestcraft

**Comment by raoulvdberge** [comment]
That is because the mod ID of Pam's Harvestcraft is just harvestcraft.

**Comment by ProfessorProspector** [comment]
maybe it could search modid and name?

**Comment by raoulvdberge** [comment]
Mod name of Pam's is still harvestcraft :(

Also, I won't be adding multiple search queries. It'll be possible to use view cells, which have similair functionality in the future
