### ISSUE TITLE
[minor][curseforge][dependency] ES requires mcmultipart but does not have it marked as a dependency on curseforge

### ISSUE THREAD

**Issue by macks2008** [raoulvdberge/refinedstorage#1361]
#### Issue description:

while mostly harmless, as a simple Google search can find the associated project, it's much faster to go to the dependency's project via the relations tab on the project page. Furthermore, this means that people who download ES via the Twitch Launcher (formerly known as the Curse Launcher) will have to manually grab the dependency. While it's simple enough to do so (aside from having to run the game once if one didn't know about the dependency otherwise), it's probably equally simple for you to just list it properly in the first place.
#### What you expected to happen:
I expected the Twitch launcher to either download all dependencies automatically, as it usually does based on what mods are marked as dependencies  on CF, Or for CF to at least list any dependencies somewhere on the project page Overview. Did I miss it? I even tried searching the overview page with Find  for anything mentioning the dependency...
#### What happens:
as the dependency was not downloaded automatically as expected, the game started up and immediately stopped when it noticed a missing dependency. That's fine on its own, but then I noticed the dependency wasn't even listed on the overview CurseForge, so I came here to report the discrepancy.
#### Steps to reproduce:
1. make any attempt to find what dependencies the mod requires without launching the game
2. get zilch and, unless you have some level of foreknowledge, assume there are no dependencies
3. oh look! There's a dependency that you had no way of knowing about! Congratulations, start launching all over again 😜. (The sarcasm might be slightly excessive, but I'm in one of those moods right now)
...

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge: forge-1.10.2-12.18.3.2281-universal
- Refined Storage: 1.2.26

Does this issue occur on a server? [yes/no]
no (that would require the game starting, though I understand you have to ask this question to help you screen  your issues more effectively)
#### If a (crash)log is relevant for this issue, link it here:
I mean I could give you the client log, but the issue itself is straightforward enough: missing dependency. Again, I understand you say this just to make the process faster if there does happen to be one relevant, but no, a log would probably not help.
[pastebin/gist/etc link here]

**Comment by raoulvdberge** [comment]
The last 1.10 version of Refined Storage has MCMultiPart listed as a dependency:

https://minecraft.curseforge.com/projects/refined-storage/files/2431884

The 1.11 and 1.12 versions don't need MCMultiPart anymore, so it's not listed as a dependency there.

I guess CurseForge looks at the latest file dependencies and assumes RS for 1.10 doesn't need MCMultiPart.

**Comment by macks2008** [comment]
huh, so it does. Weird...
I guess Curseforge needs to fix its shit

**Comment by macks2008** [comment]
@raoulvdberge are you sure you didn't add that as a required dependency after the file was _already uploaded to and cached by curseforge_ or anything like that? I've had similar problems when developing my modpack where a change didn't take effect right away because the cache wasn't updated.

**Comment by macks2008** [comment]
Either way, that doesn't change the fact that the dependency is not mentioned anywhere on the project overview. While the dependency is no longer needed for 1.11, maybe you should at least note that "Versions prior to [version here] will additionally require [dependency name here]" at the top of the page

**Comment by raoulvdberge** [comment]
I don't care about this, Forge already gives a message that MCMultiPart is required. I'm not gonna pollute the project description to leave a note about an unsupported version.

**Comment by macks2008** [comment]
@raoulvdberge Ah, okay, I understand. Unsupported version. No need to be so harsh

**Comment by raoulvdberge** [comment]
AFAIK that comment wasn't harsh

**Comment by macks2008** [comment]
I guess it just felt harsh to me. Anyway, no matter.
