### ISSUE TITLE
Communication Problem RS /Storage Drawers?

### ISSUE THREAD

**Issue by Medusalem** [raoulvdberge/refinedstorage#1362]
#### Issue description:

On Minecraft 1.11.2 When using RS in combination with an Storage Buss, some Items can not be taken out. The Number of the Item in the Storage network Dekreses BUT the player cant get them in the Inventory at all. Happens with all kinds of Storage Drawers! But it is also not happening with ALL items yust with some random items. 

I tried to Resinc client and server by Reseting the Network on Both sides. Replacing the Storage Controler from Storage drawers helps for a short ammount of time, than the problem ocurse again.

Replacing the Storage Bus or replacing the Netowork controler does not change something.

Server Restart does not Change the Problem, Relogging does not either.

#### What happens:

Can't descrip without Issue description so see Issue Description,

#### What you expected to happen:

I Would like to be able to get Items out or in the Storage Drawer system via the Grid.

#### Steps to reproduce:
1.  Put Stuff in Storage Drawer Network
2. Put Storage Buss on it
3. take items out. BUT i do not know When exactly it happens or what is trigering it.
...

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.11.2
- Forge:  13,20,0,2299
- Refined Storage:  1,4,18

Does this issue occur on a server? [yes/no]

Yes

#### If a (crash)log is relevant for this issue, link it here:

No Crashlog.

[pastebin/gist/etc link here]

**Comment by way2muchnoise** [comment]
That forge version isn't [the recommend nor the latest](http://files.minecraftforge.net/maven/net/minecraftforge/forge/index_1.11.2.html) you might wanna update that.

**Comment by raoulvdberge** [comment]
Can you record a video of this happening?

**Comment by Medusalem** [comment]
yeah

**Comment by Medusalem** [comment]
Give me a few moments

**Comment by Medusalem** [comment]
https://www.youtube.com/watch?v=PNAqdKlaSWE&feature=youtu.be

There you go

**Comment by raoulvdberge** [comment]
Are you on the latest version of Storage Drawers and Forge? It's weird, I haven't seen this bug before.

**Comment by Medusalem** [comment]
I will Update forge, Give me a moment

**Comment by raoulvdberge** [comment]
Recommended. Also check if Storage Drawers is up to date.

**Comment by Medusalem** [comment]
Did not Changed something about the Problem, Tried recommended and than latest.

**Comment by Medusalem** [comment]
would one of the server logs Help you somehow?

**Comment by raoulvdberge** [comment]
I don't think so. Let me see if I can reproduce it myself in a 1.11 instance.

**Comment by Medusalem** [comment]
Do you want to get the Modpack in the state we are using it?

**Comment by raoulvdberge** [comment]
I guess, yes.

**Comment by Medusalem** [comment]
a wish to where to upload it?

**Comment by Medusalem** [comment]
https://drive.google.com/file/d/0B8QEVNWP3nhleV91NkU3cnZhLUU/view?usp=sharing

**Comment by Medusalem** [comment]
Its a twitch launcher profil

**Comment by Medusalem** [comment]
It could, by i do not know how the storage scan thing work, have something to do with storage drawers sometimes not displaying items corectly

**Comment by raoulvdberge** [comment]
Must be a SD issue then.
