### ISSUE TITLE
Removing Enchanted Books often extracts wrong enchanted book

### ISSUE THREAD

**Issue by lrwerewolf** [raoulvdberge/refinedstorage#1363]
#### Issue description:
I have multiple hundreds of enchanted books of dozens of different types in my Refined Storage system.  Attempting to remove a specific book from the crafting grid and pattern grid often returns the wrong book.

#### What happens:
When I find the book I want and try to extract it (tried: dragging, shift+click), more often than not, I get the wrong book.  If I consistently choose the same book, I consistently get the same wrong book in my inventory.  It properly decrements the count of the number of that wrong book in storage.

For example, in my current world, any time I search for "#sharpness", it displays my books that contain sharpness.  If I remove Sharpness IV, I get Knockback III -- and it properly decreases the number of Knockback III books.

Current testing shows that if I pick book with only the level I enchant, it consistently pulls the correct book.  Looks like impact is limited to higher levels.  Tested with a wide variety of enchants from mods and from vanilla, and appears to only affect vanilla enchants (ie: Pulling Reaper IV from Draconic Evolution gives Reaper IV).

#### What you expected to happen:
When removing a specific Enchanted Book, I should get that specific enchanted book regardless of level or source of the enchant.

#### Steps to reproduce:
1. Populate storage system with a wide variety of enchanted books from vanilla and other mods
2. Attempt to remove various books considering various levels and various vanilla mod sources for the enchanants
3. Observe book obtained
...

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.11.2
- Forge: 13.20.1.2393
- Refined Storage: 1.4.18

Does this issue occur on a server? [yes/no]
Occurring single player

#### If a (crash)log is relevant for this issue, link it here:

Checked logs for any relevant information, none found.

**Comment by lrwerewolf** [comment]
Extra information:
In subsequent testing, I have found that in my current world, removing an enchanted book with "Sweeping Edge I" results in the wrong book being pulled (Fiery Aspect III).  This invalidates my initial finding that it seems limited to level II+ vanilla enchantments.

**Comment by lrwerewolf** [comment]
Extra information:
Not sure if related or not, but I am finding that adding certain enchanted books results in the enchanted book being deleted.  In my specific case, adding an Enchanted Book with Looting I to the system results in the book vanishing.

**Comment by lrwerewolf** [comment]
Had added a comment about certain books disappearing.  Forgot I had a system exporting those.  Deleted the comment to keep the thread on-point.

**Comment by raoulvdberge** [comment]
Thanks for reporting, I made the hashcode for item extraction a bit stronger.
