### ISSUE TITLE
[1.11.2] Crash when placing multipart cover over External Storage

### ISSUE THREAD

**Issue by BrisingrAerowing** [raoulvdberge/refinedstorage#1364]
#### Issue description:

MC Crashes when I try to place a multipart cover (Chisels & Bits) over an external storage.

#### What happens:

Crash and close.

#### What you expected to happen:

The cover places.

#### Steps to reproduce:
1. Place an external storage
2. Try to place a multipart compatible cover over it
3. ???
4. Crash

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.11.2
- Forge: 13.20.1.2393
- Refined Storage: 1.4.18

Does this issue occur on a server? [yes/no] Untested

#### If a (crash)log is relevant for this issue, link it here:
[Crash Log](https://gist.github.com/BrisingrAerowing/fabb6ec86ab1f58e64163933e01842af)

**Comment by raoulvdberge** [comment]
This bug was already fixed for 1.12, I've now fixed it for 1.11.2 as well.

**Comment by BrisingrAerowing** [comment]
Awesome.
