### ISSUE TITLE
[1.12] Quartz Unable To be Smelted Into Silicon

### ISSUE THREAD

**Issue by Leonan8995** [raoulvdberge/refinedstorage#1365]
#### Issue description:
When adding nether quartz to a fueled furnace, silicon is not produced. The furnace remains inactive.

#### What happens:
A fueled furnace with nether quartz in the input slot remains inactive.

#### What you expected to happen:
Unless I'm mistaken, smelting nether quartz should produce silicon in a furnace.

#### Steps to reproduce:
1. Fuel a furnace
2. Insert nether quartz in the furnace's input slot
3. Observe that the quartz does not smelt into silicon

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12
- Forge: 14.21.2413
- Refined Storage: 1.5.10

Does this issue occur on a server? [yes/no]
Only tested in singleplayer.

**Comment by raoulvdberge** [comment]
I'm an idiot.

https://github.com/raoulvdberge/refinedstorage/commit/d1722c5458e8104bd4dd5b3ddfbf040d6b5b373f#diff-5c4e8a728d627eccfef5f997aad32f6eL225
