### ISSUE TITLE
Unable to insert into Crafter with pipes.

### ISSUE THREAD

**Issue by Darkere** [raoulvdberge/refinedstorage#1369]
#### Issue description: 
In earlier versions, I was able to connect the crafter to pipes so that I could just dump all my patterns into a chest and insert them via pipes. I was also able to see the contents of the Crafter via Storage Scanner to quickly find specific patterns.

#### What happens:
Pipes do not connect to Crafter

#### What you expected to happen:
Crafter to work as Inventory (like a chest).

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12
- Forge: 2413
- Refined Storage: 1.5.9

Does this issue occur on a server? yes

**Comment by raoulvdberge** [comment]
This is intended, so other people can't just extract your patterns if your network is secured.
