### ISSUE TITLE
FPS Drop In Grid

### ISSUE THREAD

**Issue by Trcx528** [raoulvdberge/refinedstorage#137]
Currently using version 0.7.16 in FTB Unstable.  

I've been using forestry and playing with bees.  I've been storing bees in refined storage.  Now when I open a grid, I get a large FPS drop, from 40+ fps to barely 5.  I've noticed that if I search for something (like coal) the fps returns to the expected 40 fps.  If I search for drone the fps drops down to around 5.  

I suspect this is because bees are expensive to render.  One solution could be to only render the current "screen" of items rather than the whole inventory.  Regardless of whether bees are expensive to render I feel a feature like this would greatly benefit refined storage as a whole.

**Comment by raoulvdberge** [comment]
>  One solution could be to only render the current "screen" of items rather than the whole inventory. 

That is already what is happening, it only renders what is visible.

This is clearly a Forestry issue, their bees aren't rendered efficiently. You can reproduce this by searching for bees in JEI for example.

**Comment by Trcx528** [comment]
While I understand that it is forestry's fault for rendering bees poorly I still believe there is a bug in refined storage. 

In my initial scenario, with all my bees in RS, when I open my grid, I have only one bee visible on screen (as I sort by quantity) and my fps would drop to 3-5.  

Moving all the bees (except for my "top" bees as they exceed 1k and I have nowhere else to put them) out of RS results in my fps returning to normal.  This is why I assumed they were being rendered regardless of if they are visible.  If nothing else this behavior odd since it sounds like items that are not visible are not rendered.  

I have since moved all my bees into other storage devices and am using an ender io inventory panel to access them without issue or any noticeable fps drop.

**Comment by knoxz** [comment]
I guess you are playing on singleplayer and not on a server?
If this is correct this issue might be related to: https://github.com/raoulvdberge/refinedstorage/issues/145

**Comment by raoulvdberge** [comment]
I'm assuming this FPS drop is caused by sending all the bee NBT data over the network everytime the storage changes. So, not really related I guess.

**Comment by Trcx528** [comment]
This is on a server, not single player.

**Comment by raoulvdberge** [comment]
Fixed!
