### ISSUE TITLE
Detector "Signal on being Autocrafted" does not work as Subcraft

### ISSUE THREAD

**Issue by TheBattleRooster** [raoulvdberge/refinedstorage#1371]
#### Issue description:
When using the Detector in "Signal on being Autocrafted" Mode, the signal is only active when i request that item. It does not work when the item is a subcraft for another request. I am not sure if this is intended or not but it would be cool to have this feature.

#### Version :

- Minecraft:1.12
- Forge:14.21.1.2413
- Refined Storage:1.5.12

**Comment by raoulvdberge** [comment]
@way2muchnoise How hard would this be to implement?

**Comment by way2muchnoise** [comment]
I have no clue how that works exactly, but I'm guessing it shouldn't be to hard.

**Comment by raoulvdberge** [comment]
This is how it currently works:

```java
                        boolean found = false;

                        for (ICraftingTask task : network.getCraftingManager().getTasks()) {
                            for (ItemStack output : task.getPattern().getOutputs()) {
                                if (API.instance().getComparer().isEqualNoQuantity(slot, output)) {
                                    found = true;

                                    break;
                                }
                            }

                            if (found) {
                                break;
                            }
                        }

                        powered = found;
```

Not sure how easy it is to include the subtasks as well...

**Comment by raoulvdberge** [comment]
This is intended.
