### ISSUE TITLE
Crafters autocrafting when they shouldn't be

### ISSUE THREAD

**Issue by bbran21** [raoulvdberge/refinedstorage#1372]
#### Issue description:
Crafters auto crafting when not set to auto craft
#### What happens:
In my system I have all ingots being auto crafted to block form (redstone blocks, gold blocks, etc) but I also have patterns to convert them back to ingot form in a separate crafter that does not have auto crafting on for other patterns that would require them.(video of the issue https://youtu.be/LFTg8sKrZiM ) and yes there is some redstone coming from any other source but it is also just crafting back and forth as you can see from the amount of blocks going up and down.
#### What you expected to happen:
All ingots would be made into blocks and only converted back to ingots when patterns that require them are started.
#### Steps to reproduce:
1. Have two separate crafters one auto crafting with the pattern to make the block and one not auto crafting with the pattern to make the ingot
2. Fill the system with the ingot and watch as it crafts it all to blocks but then crafts back and forth between a block and 9 ingots when its done

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge: 12.18.3.2281
- Refined Storage: 1.2.25 (Skyfactory 3)

Does this issue occur on a server? [yes/no] Not Tested

#### If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here]

**Comment by way2muchnoise** [comment]
The problem here is the fact that it wants to make a block, thus it needs ingots/dusts. For which it needs a block (which is in the system), so it makes ingots/dusts and then crafts it back into a block, for ever.

**Comment by bbran21** [comment]
I see, I feel like items shouldn't auto uncraft themselves just to auto craft again

**Comment by way2muchnoise** [comment]
Yeah, it is one of the quirks that auto crafting has. Better to use compacting drawers our a like to store ingots as blocks, and easier to use anyways. It is also the quirk that allows for crafting that uses X + Y's to create more X.

**Comment by raoulvdberge** [comment]
Will this quirk be fixed or will this remain intended behavior?

**Comment by john-sp** [comment]
I have this problem, but it is happening with enderio capacitors. Any Ideas
