### ISSUE TITLE
1.10.2 Solderer bug

### ISSUE THREAD

**Issue by garlicy** [raoulvdberge/refinedstorage#1373]
#### Issue description: When i try to use Solderer the progress does not start

![2017-07-19_02 57 06](https://user-images.githubusercontent.com/29414200/28344870-1bdff256-6c2f-11e7-9a70-9fb3c2c36423.png)
![2017-07-19_02 57 11](https://user-images.githubusercontent.com/29414200/28344871-1be34dac-6c2f-11e7-9243-a841f24c0b37.png)

#### Steps to reproduce:
1. Place a solderer
2. Try to craft something
...
that's just what i did

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge: 12.18.3.2316
- Refined Storage: 1.2.26

Does this issue occur on a server? [yes/no] idk sorry

#### If a (crash)log is relevant for this issue, link it here: the game didn't crash

[pastebin/gist/etc link here]

Am i doing something wrong? Should i include my mod list or something else?

**Comment by raoulvdberge** [comment]
1.10 is not supported.

**Comment by raoulvdberge** [comment]
Also you need to connect the solderer to a controller -.-
