### ISSUE TITLE
[Feature Request] Exporter priority

### ISSUE THREAD

**Issue by winsrp** [raoulvdberge/refinedstorage#1374]
Hi, love this mod and have been using it a lot, its great, but one thing that is kind of weird is the fact that there is no priority setup on the exporter block (for example to keep feeding important items to the generators so that the whole network wont shut off and I won't be able to access my items anymore!! =D)

This would be a great addition and since you already have a priority setup on other blocks this shouldn't be something so hard? right? =D

thanks for a great great mod!

**Comment by raoulvdberge** [comment]
No!

**Comment by winsrp** [comment]
uh... ok....
