### ISSUE TITLE
"No Machine found" iron ingot

### ISSUE THREAD

**Issue by Symbai** [raoulvdberge/refinedstorage#1375]
#### Issue description:

When I'm trying to auto craft iron ingots in the grid, the crafting monitors says "No machine found".

#### Steps to reproduce:
1. Create a pattern for iron ingot using the pattern grid, checking the "Processing" checkbox as its the only way to create an iron ingot pattern.
2. Put pattern into Crafter, connect crafter with cables
3. Place electric furnace below crafter and an importer at the bottom (furnace has 100% power)
4. Try to craft iron ingots

What am I doing wrong? Google says that I should create the pattern in pattern grid instead of pattern encoder but the pattern encoder no longer exist. And the "processing" checkbox is the only way for me to put iron ore at the right and iron ingot at the left and create a pattern.

On older versions this has worked flawless but when I created a new world and updated refined storage it no longer works.

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12
- Refined Storage: refinedstorage-1.5.12

**Comment by raoulvdberge** [comment]
You are doing it right, the processing pattern encoder is removed indeed and you should select processing.

Can the crafter insert items through the top side though?
