### ISSUE TITLE
Automating Solderer

### ISSUE THREAD

**Issue by Master-Jynx** [raoulvdberge/refinedstorage#1376]
#### Issue description:
I tried to automate the solderer by placing it, then pacing a crafter and rotating it to face the solderer,
then connecting the crafter to the controller with cable, placing an importer on the solderer's
left side and connecting it to the controller.
I then inserted 7 patterns for making processors and tested the the setup by autocrafting 1 advanced 
processor.

The crafting request's progress could be viewed in the crafting monitor and no ingredients were missing, but nothing was being sent to the solderer.

I tried many setups but it only works when the crafter is behind the solderer and the importer is attached to it's bottom side.

This is contrary to what the wikki and the various spotlights say, which is that the importer and crafter 
can both be placed on any side of the solderer and it will work as long as the crafter is facing it.

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge: 2297
- Refined Storage: 1.2.26

Does this issue occur on a server? [yes/no]
yes
#### If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here]

**Comment by way2muchnoise** [comment]
https://refinedstorage.raoulvdberge.com/wiki/solderer

> In RS for MC 1.10.2 it is sided: bottom side for output slot and other sides for input slots.
