### ISSUE TITLE
Fluidcrafting not working with TE fluids.

### ISSUE THREAD

**Issue by Darkere** [raoulvdberge/refinedstorage#1378]
#### Issue description:
Pretty sure this worked in 1.11.2 but using the destabilized redstone bucket in a recipe does not cause RS to recognize it as a liquid and use fluid from storage. All other liquids seem to work fine (tested water and IE creosote)

#### Steps to reproduce:
1. make a recipe for signalum blend
2.put destabilzed redstone into the system.
3.try to craft it
...

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12
- Forge:2420
- Refined Storage: 1.5.13

Does this issue occur on a server? yes

**Comment by raoulvdberge** [comment]
That is weird. Will investigate later.

**Comment by raoulvdberge** [comment]
Works for me.
![x](https://raoulvdberge.com/5LHsj1)
