### ISSUE TITLE
[1.11.2] Dupe in crafting grid (refinedstorage-1.4.20)

### ISSUE THREAD

**Issue by cragrim** [raoulvdberge/refinedstorage#1379]
#### Issue description:
Shift clicking on an item that is in the crafting grid should insert it, instead it is duped in the RS system.
I just updated from 1.4.18 and noticed this when inserting items into the crafting grid. Woops.

#### What happens:
Item is duped.

#### What you expected to happen:
Item should be deposited into the RS system

#### Steps to reproduce:
1. Open crafting grid
2. Shift click item that is already inside the RS system
3. Item is duped.

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.11.2
- Forge: forge-1.11.2-13.20.1.2391-installer.jar
- Refined Storage: refinedstorage-1.4.20.jar

**Does this issue occur on a server? [yes/no]**
Yes!

**Animated gif**
http://i.imgur.com/SjKmUVs.gif
![Gif animation of issue](http://i.imgur.com/SjKmUVs.gif)

**List of installed mods:**
https://paste.ee/p/JlLHx

**Comment by cragrim** [comment]
**More info:**
Downgrading to refinedstorage-1.4.18.jar again fixed it! 

So if you're hosting a server avoid running 1.4.20 for now. I have not tried if 1.4.19 is safe.

Love this mod, keep up the great work smashing bugz!
Cheers :)

**Comment by raoulvdberge** [comment]
That doesn't make sense, 1.4.18 <-> ,1.4.20 didn't change anything related to grids... I'm suspecting this is a serverside mod interaction issue.

**Comment by cragrim** [comment]
Any clues what I can test? Anything I can check to try to figure out the cause?
I suspected JEI but toggled cheat mode without any change.

**Comment by raoulvdberge** [comment]
I have no idea.

**Comment by raoulvdberge** [comment]
Maybe some mod like InvTweaks or MouseTweaks? Anything that could manipulate the inventory.

**Comment by cragrim** [comment]
I did not change any other mod aside from Refined Storage, still using the same version of InvTweaks and MouseTweaks.

**Comment by Morpheus1101** [comment]
Im getting something very similar on a server using Refined storage but in 1.12 .. If i have 1 of an item in the RS system and shift click it out i end up with 2 stacks of that item which you can repeat and use on any item that stacks more then 1 of itself.

Forge *.2420
RS 1.5.13

Although with your prev replies raoul, i fully suspect it has something to do with mousetweaks perhaps since it was only recently added an this started to occur.

**Comment by raoulvdberge** [comment]
Sorry, I can't reproduce this.
