### ISSUE TITLE
Magic Wood Crafting /w Grid

### ISSUE THREAD

**Issue by popemichael** [raoulvdberge/refinedstorage#138]
Magic wood is uncraftable in a crafting grid. The same magic wood is craftable in a vanilla crafting table AND a tinkerer's crafting station (see screenshot #2)

Dependencies: Refined Storage v0.7.16 - Used in part of the Feed The Beast unstable 1.9.4 VIA the Curse launcher & Extra Utilities 2 v1.0.0a (available from the FTB unstable pack)

To replicate: 

1. Create a network (Place a controller, then drive, then crafting grid, then provide the drive a 64k disk)
2. Place a bookself in the upper left corner (see screenshot #1)
3. Place a gold ingot to the right of the bookshelf
4. Note the Magic wood is not craftable

I'm not sure if this an extra utilities issue or an issue with Refined Storage. I wanted to make sure you were made aware of the issue.

(edit: Wrong screen shot uploaded)

![no_magic_wood_2](https://cloud.githubusercontent.com/assets/17892373/16327608/ec7edee6-399e-11e6-9e7f-220f755c7067.png)

![no_magic_wood_3](https://cloud.githubusercontent.com/assets/17892373/16341078/53613730-39f9-11e6-8b64-6a898b5850e3.png)

**Comment by raoulvdberge** [comment]
Small question, on the scrshot of the tinkers table your old is on the left. In the RS grid your gold is on the right. Shouldn't the gold be on the left in your RS grid too?

**Comment by popemichael** [comment]
Yeah, that one is on me. I uploaded the wrong screenshot. Edited the original post.

**Comment by tyler489** [comment]
Its because magical wood requires xp to craft. Some sort of dependency needs to be added.

**Comment by choekstr** [comment]
I ran into this just last night and had to revert to a tinkers table to craft.  Definitely needs XP to craft now so perhaps just need to check for that?  Using RS 0.7.19 on MC 1.9.4 when it occurred.

**Comment by raoulvdberge** [comment]
This requires grid inventories to be player-unique, which they aren't.
