### ISSUE TITLE
Feature Request: "Wireless Block Picker" tool

### ISSUE THREAD

**Issue by saulrh** [raoulvdberge/refinedstorage#1381]
If I want to extend a part of my base, it's annoying to have to go into my wireless grid, search out the appropriate block, retrieve a few stacks, especially when I have to repeat it because I didn't grab enough blocks or I'm doing multiple expansions.

To alleviate this, I propose a wireless tool that duplicates the "pick block" vanilla functionality, but pulls from refined storage instead of hotbar or creative mode. Using it on a block in the world figures out what you're looking for and drops a stack of it into your inventory. Even more featureful would be a mode that maintains a stack of that block in your inventory, somewhat like the Inventory Tweaks feature that maintains a full stack of something in your hotbar. A fluid-mode version of this might work like the Thermal Dynamics FluiVac, sucking fluids straight out of the world and into RS or pulling fluids out of RS and placing them directly into the world.

Use cases:

- When using a Builder's Wand to fill a ton of space, you don't have to go back into your wireless grid every thirty seconds to refill your inventory.
- If you have an extra fancy base with multiple blocks used for trim and finishing, you can get the blocks you need for an expansion without having to remember what every one of them is called.
- When building machine arrays, if you run low on cables or conduits or wires (or whole machines!) you can grab more with a single click and go right back to building.
- Suck up (or make!) ponds without having to wrangle buckets and the fluid grid.

**Comment by bookerthegeek** [comment]
So basically, forestry backpacks that aslo deal with liquids

**Comment by raoulvdberge** [comment]
This would be a great addition for  Refined Storage Addons!

**Comment by raoulvdberge** [comment]
Implementing this for RS addons instead.
