### ISSUE TITLE
[1.12] Silicon smelting recipe registered too late (can't remove via CraftTweaker)

### ISSUE THREAD

**Issue by oitsjustjose** [raoulvdberge/refinedstorage#1383]
#### Issue description:
When attempting to remove the smelting recipe for Silicon from Quartz in the furnace, I'm consistently unable to with CraftTweaker

#### What happens:
Nothing short of a thrown error on CT's side

#### What you expected to happen:
The smelting recipe to vanish!

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12
- Forge: 14.21.1.2423
- Refined Storage: 1.5.13

Does this issue occur on a server? [yes/no]
yes

#### Proposed (and tested) solution:

Move [this](https://github.com/raoulvdberge/refinedstorage/blob/mc1.12/src/main/java/com/raoulvdberge/refinedstorage/proxy/ProxyCommon.java#L221) to PreInit. I've done this & compiled it, and it worked flawlessly with and without CraftTweaker changing the recipe - and was done early enough for CT to access and remove it. Could this be remedied by CraftTweaker too? Probably - might be worth investigating if this is an issue with many other mods, because it's not uncommon to register recipes in init or even - if you're insane - postInit, but I thought this might be a simple "bandaid" for now.. if you decide to forego this and redirect me to jaredlll08 I'd totally understand.

**Comment by oitsjustjose** [comment]
CC'ing @jaredlll08 - this is what I was talking about today with Ellpeck during his stream.

**Comment by raoulvdberge** [comment]
Smelting recipes aren't a registry and aren't locked down, so technically I can register them when I want but point taken, I'll move the call.

**Comment by jaredlll08** [comment]
This has already been fixed anyway... yesterday though, @raoulvdberge you can register them anywhere before postinit

**Comment by raoulvdberge** [comment]
Lol
