### ISSUE TITLE
ATM3 Massive CPU usage 

### ISSUE THREAD

**Issue by gefailter71** [raoulvdberge/refinedstorage#1384]
MC: 1.12
Forge: 2420
RS: 1.5.13

On the official ATM3 server, VisualVM points to NetworkNodeGraph.rebuild() are taking >98% CPU time

![](https://cdn.discordapp.com/attachments/315675935053709312/338882162075893762/unknown.png)
ATM3_NetworkNodeGraph.nps:
https://cdn.discordapp.com/attachments/328230851584458773/339089021667901441/ATM3_NetworkNodeGraph.nps

----------------------------------------------------------------------------------------------------------------------

Might be unrelated but today RS auto crafting has been using 98% CPU.

![](https://cdn.discordapp.com/attachments/330056560904634368/339448180309491715/unknown.png)
ATM3_AutoCrafting.nps:
https://cdn.discordapp.com/attachments/328230851584458773/339455108528078849/ATM3_AutoCrafting.nps

**Comment by raoulvdberge** [comment]
I'm looking into this later this week.

**Comment by ProsperCraft** [comment]
We are pushing 1 tps suddenly, remove refined storage and tps goes to 20.


[refined1tps.zip](https://github.com/raoulvdberge/refinedstorage/files/1181937/refined1tps.zip)

Find attached sampler nps file.

Here is our warmroast
https://i.gyazo.com/f8929f9cfa3644c1f69dd870451b480d.png

**Comment by ProsperCraft** [comment]
Problem located- use this

/sampler find @.TileExternalStorage

We found a bank of external storages connected to quantum storage blocks.

https://i.gyazo.com/3730cc8c37a294e8560f32349de334c2.png

removed the controller and tps shot from 1 to 20.

**Comment by raoulvdberge** [comment]
Thanks for these NPS files - I identified the cause of the problem and I'm working on a fix.
