### ISSUE TITLE
IC2 and RS

### ISSUE THREAD

**Issue by q123600** [raoulvdberge/refinedstorage#1385]
#### Issue description:
I had tested for few times, but RS couldn't receive electronic(EU) from IC2. 
#### What happens:
can't share IC2's energy(EU) to mod RS.
#### What you expected to happen:
RS could receive EU from IC2 and able to use it.

#### Version (make sure you are on the latest version before reporting):

- Minecraft:1.11.2
- IC2: 2.7.74
- RS: 1.4.20
- Forge:13.20.1.2393

Does this issue occur on a server? [yes/no]
yes

**Comment by raoulvdberge** [comment]
No support for ic2 as long as the api isnt capability based.
