### ISSUE TITLE
[1.12] Controller on chunk load not always updates it's neighbors

### ISSUE THREAD

**Issue by roboderpy** [raoulvdberge/refinedstorage#1386]
#### What happens:
Controller "freezes"
![3df3a89afc_javaw_2017-07-26_08-14-09](https://user-images.githubusercontent.com/6339511/28600318-7ceb9742-71db-11e7-8aa4-fe453aeeff9d.png)
Inventories are still working, importing, exporting, etc. BUT Crafting is not avaliable (nothing happens)

Before https://github.com/raoulvdberge/refinedstorage/commit/7a41c7b0aaeab80cf9d414175ff7b7c11ebb7473 controller was bugging differently, it was working as expected but **it wasn't consuming energy at all** in case where *this* bug happens

#### What you expected to happen:
Controller updates it's neighbors and constructs network configuration

Issue can be solved by removing and placing controller back

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12
- Forge: Build 2423
- Refined Storage: 1.5.13 (was tested before on 1.5.9)

Listen server and Multiplayer servers are affected

**Comment by roboderpy** [comment]
or it never updates it

When i enter overworld from nether this bug occurs in 100% cases

**Comment by roboderpy** [comment]
Some investigation - place controller near edge of chunkloaded area (like chunkloaded spawn area), but *not* on chunk that is always loaded. Then build up a average, or huge (under *huge* i mean network that consumes ~1300 FE/t without any wireless stuff), that overs **both spawn chunkloaded chunks and non-loaded chunks**. Then trigger momental chunk unload - build up a nether portal and travel to nether. After some time, come back. If all is done correctly, there is a very high chance to reproduce the issue

**Comment by BaneOfSerenity** [comment]
I created defect #1048 not knowing this was here, just some notes with what i have found. Going to the nether and back doesn't break the setup 100% of the time for me (might be because I have a smaller setup). Also even after removing the controller I was still able to access the crafting grid and attached inventory.

**Comment by raoulvdberge** [comment]
I made an attempt to fix this in 1.5.15. Please try that version and let me know if you can still reproduce this bug.

**Comment by roboderpy** [comment]
Currently not at home, but will check asap

**Comment by BaneOfSerenity** [comment]
I am running 1.5.16 (I assume it has the code that 15 has) and this still happens. One thing that was interesting is when I came back from the nether everything seemed fine even checked the controller and everything was showing up. Walked away for a second and came back to craft something. Couldn't craft and everything is unlinked again.

**Comment by roboderpy** [comment]
Doesn't seem to happen anymore

**Comment by BaneOfSerenity** [comment]
I'm not sure why this was closed, this still happens every time I come back from the nether on build 1.5.16.

**Comment by roboderpy** [comment]
@BaneOfSerenity please investigate. When we created new world, it doesn't happened for me and my friend.

**Comment by roboderpy** [comment]
Doesn't seem to happen anymore at any case

**Comment by raoulvdberge** [comment]
Thanks for the follow up!
