### ISSUE TITLE
[1.12] Problem with Storage Drawers mod

### ISSUE THREAD

**Issue by JustHmm** [raoulvdberge/refinedstorage#1387]
#### Issue description & What happens: 
When i connect external storage to drawer control it causes this spam messages: Running x ms behind, skipping x tick(s) 
Also refine storage inventory is blinking, i mean the hole inventory disappearing couple ms  and being visible again and it is happening every couple seconds. 

#### What you expected to happen: 
Refined Storage Drawers

#### Steps to reproduce:
Storage Drawers setup example: http://prntscr.com/g0bztc
Just make a storage drawers system like in screenshot and connect your refined storage system with external storage to drawer control block.

#### Version:

- Minecraft: 1.12
- Forge: 1.12-14.21.1.2424
- Refined Storage: 1.5.13
- Storage Drawers: 5.2.9

*This issue occured on a server.

**Comment by raoulvdberge** [comment]
This is most likely a Storage Drawers performance issue, since RS just interacts with the API.

Can you please follow these steps and send me a NPS file:

https://refinedstorage.raoulvdberge.com/wiki/profiling

Then we know for sure who's side is doing it.

**Comment by JustHmm** [comment]
https://ufile.io/ds1zc

**Comment by raoulvdberge** [comment]
Weirdly enough, RS nor SD appear in the file:

![x](https://raoulvdberge.com/pCf4sK)

![x](https://raoulvdberge.com/Cbz5f1)

**Comment by JustHmm** [comment]
I switched to Quantum Storage Unit there is no inventory blinking issue or server behind error it was definetely storage drawers issue im sorry to bother you. Thank you for your time.
