### ISSUE TITLE
[Suggestion] 1.12 Refined Storage

### ISSUE THREAD

**Issue by llloyd4** [raoulvdberge/refinedstorage#1388]
Hello! I was noticing there was a certain lack of a feature that's available in AE2 and, if memory serves, was in AE1. A grind stone, a way to hand crank ore double early game. AE2 isn't available for 1.12 so this feature is missing and sorely missed. Could you, please, add your own version of the grindestone?

**Comment by raoulvdberge** [comment]
No

**Comment by calloatti** [comment]
Many open source projects consider it ok to be abrasive on the tracker. I think it’s never ok. 

Kindness and firmness are not mutually exclusive.

I am old. You are probably young. Be more polite. It will help you in your work and in your personal life. You will need things from people sometimes. It helps if you are not an asshole to them.

**Comment by raoulvdberge** [comment]
First off, while you might be older, you have 0 experience in managing an open source project at this scale.

You are in no position to tell me how I should behave on my own tracker.

Also, I don't consider my response to be rude. User requests a feature, I don't want said feature so I reply with a simple "no". Nothing more.

I get lots of feature suggestions and I don't always have time to provide justification for the "no". Not that a justification would matter, if I don't like something I won't do effort to implement said suggestion.

Managing an issue tracker (and OSS project) is tiring and draining, so again, I don't have time for big responses. Not that you'd know.

**Comment by raoulvdberge** [comment]
In fact, I might just keep interaction with the issue submitters to a minimum and close the issues with no explanation at all. I'm tired of dealing with people on here, and the abuse that comes with it.

I'm going to concentrate on the thing I like most: coding. Having this tracker and dealing with people like you only ruins the experience for me.

**Comment by llloyd4** [comment]
@calloatti I wasn't going to respond to this. Though, in general, I tend to agree with you, it was a bit brusque, it is Raoul's project, what he says goes, so a no means no. We may not always agree with what a mod author does to their mod, even think some ideas (not for RS, mind you, other mods, RS is great) are terrible ideas, but, at the end of the day, it is the mod author's mod. We can politely suggest and politely protest terrible changes, but ultimately it's their mod and their say so. They're giving us the mods for free.

**Comment by BrianEdmonds** [comment]
Aside from Raoul's succint answer, I don't see how a "grindstone" has
any place being in a mod like Refined Storage, whether it's in any
version of Applied Energistics or not.  This mod is about storage, and
there are more than enough other mods that allow early game ore
doubling.  Tinkers Construct is my personal preference, but it's hardly
alone in the field.

**Comment by llloyd4** [comment]
As far as I know TC is, everything else that I know of needs some form of ore smelting with out doubling first. As RS is the spiritual successor of AE1, the better version IMHO, I suggested it in that light. But Raoul said no so that is that. End of story.
