### ISSUE TITLE
Shift clicking items into the solderer dupes items if you have >64 in your inventory + solderer inventory

### ISSUE THREAD

**Issue by ahze** [raoulvdberge/refinedstorage#139]
If you shift click items into the solderer and the total in your inventory + the solderer inventory is >64, it fills the solderer with that item and does not remove it from the players inevntory.

**Comment by raoulvdberge** [comment]
![gif](http://i.imgur.com/o4SnWrX.gif)

**Comment by raoulvdberge** [comment]
Not having that issue? Missing critical information here. Are you on a server, which version, ...

**Comment by ahze** [comment]
Ah yeah, it looks like I'm running a fairly old version.  0.7.13 on FTB unstable.

**Comment by raoulvdberge** [comment]
Yeah, I thought I fixed this already. Closing then, go bug FTB team  to update :P
