### ISSUE TITLE
[1.12] Networks are connecting now matter how 

### ISSUE THREAD

**Issue by dragon3025** [raoulvdberge/refinedstorage#1391]
#### Steps to reproduce:
1. Set up a Refined Storage System and give it a Network Transmitter and Wireless Receiver.
2. Teleport 100,000 in any direction and Setup the Receiving Storage System and link it to the Transmitting Storage System.
3. The Receiving System will work even though it's past the max Transmitting Range.
...

#### Version (make sure you are on the latest version before reporting): 

- Minecraft: 1.12
- Forge: 14.21.1.2420
- Refined Storage: 1.5.13

Does this issue occur on a server? No

**Comment by raoulvdberge** [comment]
I'm not sure what you mean... Network transmitter/receivers are separate from the Wireless transmitters and have no limit. Networks can connect infinitely long, power consumption will just increase.

**Comment by dragon3025** [comment]
Sorry, I got mixed up. I see in the wiki Wireless Transmitters connect to Wireless Grids. I was thinking they give Network Transmitters the power to connect to Network Receivers.
