### ISSUE TITLE
Immersive bug with Refined storage import

### ISSUE THREAD

**Issue by cmspeedau** [raoulvdberge/refinedstorage#1392]
#### Issue description:
immersive bug
#### What happens:
 if an item like coal coke or copper wires so on enter the rs system they get deleted
#### What you expected to happen:
not to delete automaticly
#### Steps to reproduce:
1. build a coke oven and rs system automate with an interface and enderio item cable keep a stack of coal in interface for coal export
2. use export on for coal on green channel and brown channel to import coal coke
3. using network receiver and transmitter to connect it up
...

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge: 12.18.3.2185
- Refined Storage: 1.2.26

Does this issue occur on a server? [yes/no] yes

#### If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here]

**Comment by raoulvdberge** [comment]
1.10 is unsupported.
