### ISSUE TITLE
Griefprevention Plugin and Fakeplayers

### ISSUE THREAD

**Issue by nightstick24** [raoulvdberge/refinedstorage#1394]
I'm playing on an All the Mods 2 server, with the Griefprevention plugin. The destructor won't break stuff because it's on my Griefprevention claim. With other mods, there was a fake player you could /trust to allow it to work. I can't find a name for what to trust to allow the Refined Storage fakeplayer to build/break in my claim.

Does this exist, and if so what might the name be? If not, would it be possible for you to implement this feature in a future release of Refined Storage?

Thanks,
Night

**Comment by raoulvdberge** [comment]
RS uses the default Forge fake player, allow that with the Griefprevention plugin.

**Comment by nightstick24** [comment]
Much appreciated!
