### ISSUE TITLE
Fix JEI transfer on grids

### ISSUE THREAD

**Issue by raoulvdberge** [raoulvdberge/refinedstorage#1395]
Machine recipes also work on regular grids...

**Comment by way2muchnoise** [comment]
*slow clap*

**Comment by raoulvdberge** [comment]
Since I removed Processing pattern encoder and merged it with the pattern grid we can't have a specialized transfer handler anymore since "nice" JEI API design binds it to a container class >.>

**Comment by way2muchnoise** [comment]
Might be something @mezz can help with

**Comment by raoulvdberge** [comment]
Wontfix. Since we can't detect machine recipes at the transfer level.

**Comment by way2muchnoise** [comment]
Well anything that doesn't have the category "crafting" is a "machine" recipe.

**Comment by raoulvdberge** [comment]
@way2muchnoise How do I get the category from the transfer handler? We only get `IRecipeLayout` which AFAIK doesn't have any methods to check if it's a regular recipe.

**Comment by Darkere** [comment]
Honestly, don't fix this. I thought it was a feature. Getting all required items for a non crafting recipe proved useful quite a few times. Especially if I need like 5 different items. Otherwise I have to remember and look up every item individually.

**Comment by raoulvdberge** [comment]
Yeah, I see how it could be handy.
