### ISSUE TITLE
Change the way JEI integration works

### ISSUE THREAD

**Issue by ProfessorProspector** [raoulvdberge/refinedstorage#140]
Right now, JEI transfer integration works even if you don't have all the available items in your system. In a vanilla crafting table, it shows the red overlay on items you're missing, and doesn't let you click the button. Both are useful, so I suggest a comprimise. Allow people to always click the button as you can right now, but also display the red overlay to show what you're missing in the system. You might have to contact mezz to see if this is possible with JEI currently, or if he can change something to make it possible.

**Comment by raoulvdberge** [comment]
I prefer the way how it currently works, just blocking the transfering when something is missing is annoying IMHO (maybe the player wants to schedule an autocraft AFTER they've autofilled items?).

**Comment by Garagoth** [comment]
IS it possible to display red overlay on items in JEI but not block "+" icon? Would be super-mega useful, few people we play together are complaining on this...

**Comment by raoulvdberge** [comment]
I don't think so.
