### ISSUE TITLE
power loss on teleport require block replacement (1.10.2)

### ISSUE THREAD

**Issue by falizure** [raoulvdberge/refinedstorage#1400]
While playing on my 1.10 server using refined storage we encounter a bug where teleporting back to your base often cause the refined storage system blocks to no longer receive power, usually requiring breaking and replacing of the blocks inorder for them to properly work again, if RS blocks are connected to the controller directly they will need broken and replaced as well however if you have RS cables running from the controller down to the rest of your blocks its typically only the controller which needs broken and replaced, while not a major bug it is a hassle, and in 1 such case so far someone lost items they had in the crafting grid inside their grid when they broke and replaced it to get it connected to the network again. edit (i also noticed this occuring sometimes when you log into the server as well)

Ideally the blocks should update their status and start receiving power again immediately when they are loaded.

#### Steps to reproduce:
1. leave the area far enough for it to unload, the bug typically occurs when you travel back from another dimension.
2. teleport home via any available method.
while this does not seam to occur every time it its well over half in my experience, and as i said usually more frequent when returning from another dimension.
edit-(3. log into the server at your base and it will also often be unpowered)
#### Version (make sure you are on the latest version before reporting):

- Minecraft:1.10.2
- Forge:-1.10.2-12.18.3.2422
- Refined Storage: 1.2.26]
- spongeforge-1.10.2-2281-5.2.0-BETA-2464

**Comment by raoulvdberge** [comment]
1.10 is unsupported.
