### ISSUE TITLE
Crafting stops working when coming back from the nether

### ISSUE THREAD

**Issue by BaneOfSerenity** [raoulvdberge/refinedstorage#1408]
#### Issue description:
Cannot craft items once i come back from the nether.
Doesn't happen every time.
Seems to be similar to issue #1255 maybe?
#### Steps to reproduce:
1. Setup system with a controller, crafter (with patterns in it), monitor
2. Go to nether
3. Come back
4. Try to craft one of the patterns in the crafter
5. Doesn't craft anything. When right clicking on the controller, the interface is empty as if no devices were connected to it. Storage monitors and everything work though, even once disconnecting the controller o.0
6. Break and replace the controller
7. You can now craft again.

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12.0
- Forge: 14.21.1.2443
- Refined Storage: 1.5.14

Does this issue occur on a server? [yes/no]
Not sure haven't tried it on a server yet.

**Comment by raoulvdberge** [comment]
#1386
