### ISSUE TITLE
NPE Render Crash referencing TileNode/TileBase/MCMP

### ISSUE THREAD

**Issue by OrdinatorStouff** [raoulvdberge/refinedstorage#1411]
#### Issue description:
TileNode NullPointerException casuing a render-related crash-to-desktop

#### What happens:
When user gets within render distance of their base they get a "Batching Chunks" CodeChickenLib render crash. latest.log shows an MCMP and RefinedStorage NPE stacktrace:
```css
Caused by: java.lang.NullPointerException
	at com.raoulvdberge.refinedstorage.tile.TileNode.getNode(TileNode.java:85) ~[TileNode.class:?]
	at com.raoulvdberge.refinedstorage.tile.TileNode.readUpdate(TileNode.java:72) ~[TileNode.class:?]
	at com.raoulvdberge.refinedstorage.tile.TileBase.handleUpdateTag(TileBase.java:90) ~[TileBase.class:?]
	at mcmultipart.api.multipart.IMultipartTile.handlePartUpdateTag(IMultipartTile.java:121) ~[IMultipartTile.class:?]
	at mcmultipart.block.TileMultipartContainer.readParts(TileMultipartContainer.java:348) ~[TileMultipartContainer.class:?]
	at mcmultipart.block.TileMultipartContainer.handleUpdateTag(TileMultipartContainer.java:276) ~[TileMultipartContainer.class:?]
```

#### What you expected to happen:
Render

#### Steps to reproduce:
1. Uncertain
2. Possibly (maybe not) related to taking a chisel bit out of a RS cable/connector and getting an invisible/invalid bit of it
3. Player recalls no changes from last time he was able to successfully log in. He logged out one day, logged in another immediately to this crash. Can play fine if player location moved but once within render distance of base, any player gets the same crash.
4. A server update occurred between log sessions but RS version has stayed the same

#### Version (make sure you are on the latest version before reporting):
- Minecraft: 1.12
- Forge: 14.21.1.2443
- Refined Storage: refinedstorage-1.5.14

Does this issue occur on a server? [yes/no]
YES -- Official ATM3

#### If a (crash)log is relevant for this issue, link it here:
[Crashlog](http://paste.ubuntu.com/25271390/) (only references CodeChickenLib render/Batching Chunks)
[Full Latest ](http://paste.ubuntu.com/25271384/) (shows RS NPE stacktrace)

**Comment by OrdinatorStouff** [comment]
[region and rsnodes.zip](https://github.com/raoulvdberge/refinedstorage/files/1209187/region.and.rsnodes.zip)

If this helps I've attached the region file containing those chunks. Player base centered approx around [242, 71, -410] (or chunk ~15,-26 and surrounding)

**Comment by OrdinatorStouff** [comment]
Update:

I deleted about 5 or 6 blocks from the region file with registry `mcmultipart:multipart.nonticking` that contained a RS cable as one of the "parts" and users are now able to login again without crashing.

According to @TheCodedOne this is fixed in MCMP experimental in : 2.2.2_38 onwards.
https://github.com/amadornes/MCMultiPart/issues/86

**Comment by raoulvdberge** [comment]
This is a MCMP issue. They're sending block updates when no world exists yet, and RS expects a world to be present to receive the block update.

**Comment by raoulvdberge** [comment]
cc @amadornes
