### ISSUE TITLE
Cannot pull out mekanism fluid tanks from Grid

### ISSUE THREAD

**Issue by tgstyle** [raoulvdberge/refinedstorage#1415]
#### Issue description:
Trying to remove a mekanism (any type) fluid tank from the grid does not work.

Using mekanism 9.4.0.318

#### What happens:
Clicking, shift clicking does not pull the tank out. Normal crafting of the tank in a crafting table works fine.

#### What you expected to happen:
Obtain the tank.

#### Steps to reproduce:
1. Auto-Craft the tank
2. Try to remove it from the grid
...

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12
- Forge: 2443
- Refined Storage: 1.5.16

Does this issue occur on a server? [yes/no]
Yes and in singleplayer

**Comment by roboderpy** [comment]
On 1.11.2 i was being unable to remove Mekanism Bins

**Comment by raoulvdberge** [comment]
That was a difficult bug to debug! But I found the cause.

**Comment by tgstyle** [comment]
Thanks for keeping at it.
