### ISSUE TITLE
CTD randomly when opening the Crafting Grid

### ISSUE THREAD

**Issue by llloyd4** [raoulvdberge/refinedstorage#1416]
#### Issue description:

Open Crafting Grid and BOOM! CTD! 

#### What happens:

When I go to open the Crafting Grid to craft / get stuff from my RS network at seeming random it CTDs

#### What you expected to happen:

It to not CTD but let me get my stuff / craft

#### Steps to reproduce:
1. Open Crafting Grid
2. Randomly CTD
3.
...

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12
- Forge: 1.12-14.21.1.2443
- Refined Storage: 1.5.16

Does this issue occur on a server? [yes/no]

No idea, I play single player

#### If a (crash)log is relevant for this issue, link it here:

https://pastebin.com/85s8FahZ

**Comment by raoulvdberge** [comment]
That's not a CTD, but a NPE... are you linking the right crashreport?

**Comment by llloyd4** [comment]
Umm, that is minecraft/crash-reports/crash-2017-08-10_13.0650.txt that was generated, presumably because of the time and date, after it froze and I found myself staring at the FTB Client. Let me check. Yeap, the NPE caused a CTD I guess? I am no programmer. But the date and time all coincide.

**Comment by llloyd4** [comment]
Well, thought I'd fixed it, I swapped out from using Yabba Barrels for external storage to Drawers, like I used when I played on the Direwolf20 1.10 mod pack, and indeed, it's been pretty stable until today when I got a NPE that caused a CTD. Taking a quick peek, the version I am using is indeed the latest, 1.5.16, so... >.< Here is the newest crash report.

https://pastebin.com/MhuZTFiC

**Comment by raoulvdberge** [comment]
Thanks, I was a bit confused. I thought with "CTD" you meant ConcurrentModificationException, but I had to think twice that you actually meant "Crash to desktop"? (I think?)

I'll look into it later today.

**Comment by llloyd4** [comment]
Right, sorry, I am not a programmer, CTD in computer terms means Crash to
Desktop.

**Comment by raoulvdberge** [comment]
Well, most crashes will make MC quit, which makes the "to desktop" part a bit superfluous..

**Comment by llloyd4** [comment]
True, you do have a point.

**Comment by llloyd4** [comment]
You fixed it? Cool!

**Comment by raoulvdberge** [comment]
Yes in 1.5.17
