### ISSUE TITLE
1.12 Dupe

### ISSUE THREAD

**Issue by MadRatSRP** [raoulvdberge/refinedstorage#1417]
#### What happens:
I pulled 1 piece of Red Matter from ProjectE into normal Storage Drawer. Then i opened Grid and shiftclicked to take it. 
#### What you expected to happen:
I expected to get 1 piece of Red Matter but instead of that i got 2 stacks of it.
#### Steps to reproduce:
1.
2.
3.
...

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12
- Forge: 2443
- Refined Storage: the latest one

Does this issue occur on a server? [yes/no] no

#### If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here]

**Comment by raoulvdberge** [comment]
Can't reproduce this.
![x](https://raoulvdberge.com/fdXMSx)

Also don't create issues with "the latest one" as RS version, it's bad ™.
