### ISSUE TITLE
Feature request - 'Crafter Grid'

### ISSUE THREAD

**Issue by pha3l** [raoulvdberge/refinedstorage#1420]
I'm wondering what your thoughts are for adding something equivalent to AE2's Interface Terminal.  Effectively what I'm looking for is a grid that allows me to see all of the crafters on the network and insert/extract patterns from them without physically accessing the crafter.  This is most useful for processing pattern crafters which I like to hide behind or under the machines they utilize, thus it's slightly annoying to manipulate the stored patterns.

My guess is that this has been brought up before, but i didn't find it in a cursory search of old feature requests.

Edit: After another look I did find an old feature request for this, to which the response was a suggestion to use an RFTools Storage Scanner.  I agree that this is a great solution for a bunch of crafters all stuck in the same spot.  My counterargument for the usefulness of this feature is that processing pattern crafters are often spread out throughout the base.

Thanks for your contribution to my modded experience!

**Comment by Darkere** [comment]
Yeah the rftools Storage scanner was a great idea and it worked back then. Unfortunately, with the introduction of the security system this does not work anymore.

**Comment by raoulvdberge** [comment]
No
