### ISSUE TITLE
Holding enchantment?

### ISSUE THREAD

**Issue by roboderpy** [raoulvdberge/refinedstorage#1421]
So, yea, like Holding enchantment from Thermal Expansion
![4eb42610f3_javaw_2017-08-13_18-06-18](https://user-images.githubusercontent.com/6339511/29249068-2429d79c-8052-11e7-8973-178241137f23.png)
![36970e79d5_javaw_2017-08-13_18-06-43](https://user-images.githubusercontent.com/6339511/29249071-37541aee-8052-11e7-9872-a2032ef75d36.png)
Creating 2,5 M item storage isn't fun, even with Mekanism installed (sand -> silicon)

**Comment by calloatti** [comment]
There is a mod out there that adds larger capacity disks to RS

**Comment by raoulvdberge** [comment]
No

**Comment by roboderpy** [comment]
@calloatti fixed phrase - There is a mod that adds dead loop in server tick
![b004138c0b_javaw_2017-08-14_10-39-39](https://user-images.githubusercontent.com/6339511/29257528-074b1a9c-80dd-11e7-9206-d74bc4f55c37.png)
