### ISSUE TITLE
server lag when power is out

### ISSUE THREAD

**Issue by violetkitty87** [raoulvdberge/refinedstorage#1422]
#### What happens: power runs out
                                  system flickers
                                  server's tps is at 2%

#### Steps to reproduce:
1.make a system
2. give it power
3.cut off power
...

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge: 1.10.2-12.18.3.2281-universal
- Refined Storage:1.2.26

Does this issue occur on a server? yes

#### If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here]

**Comment by raoulvdberge** [comment]
1.10.2 is unsupported.

**Comment by violetkitty87** [comment]
why is it unsupported in 1.10.2 that makes running a server with that mod nearly impossible
it is in fool craft please try to fix it

**Comment by raoulvdberge** [comment]
Unfortunately, I don't care. It is fixed in RS for 1.11 and 1.12 though.
