### ISSUE TITLE
Minor bug 1.12.1, animation flickers on storage monitor

### ISSUE THREAD

**Issue by winsrp** [raoulvdberge/refinedstorage#1424]
#### Issue description:

When an item with animation is placed in the storage monitor the animated image flickers on screen

#### What happens:

animation flickers

#### What you expected to happen:

animation loads properly or at least there is no animation, to be honest I don't see the point of looking at the animation on the storage monitor, a static image would just be more then fine.

#### Steps to reproduce:
1. place a storage monitor in a system that stores liquids with some water in it.
2. set the storage monitor to scan liquids and set it to water
3. the image of a bucket of water shows up, but the image starts to flicker due to the animation.
...

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12.1
- Forge: 2456
- Refined Storage: 1.5.16

Does this issue occur on a server? [yes/no] playing single player hardcore ATM

**Comment by raoulvdberge** [comment]
RS doesn't have a storage scanner...

**Comment by winsrp** [comment]
My bad, it is your mod it is just that I put the wrong name lol.... it was the storage monitor

**Comment by raoulvdberge** [comment]
And which item are we talking about here that flickers?

**Comment by winsrp** [comment]
in this case I set the storage monitor to check for water levels in the network (check for liquid and the set water as the liquid), when I do, a water bucket icon shows up on the monitor, and it seems it has some sort of animation, and that is the one that flickers.

**Comment by raoulvdberge** [comment]
Works fine for me.

![x](https://raoulvdberge.com/sh6p3m)

**Comment by way2muchnoise** [comment]
Might be optifine (just guessing here)

**Comment by boneskull** [comment]
I am seeing this now with Enigmatica 6 0.3.13 and RS 1.9.11. No OptiFine installed; MC 1.16.5, Forge 36.0.10.

It's not the items that flicker; it's the text.  When viewed at some angles, the text is cut off or disappears.


https://user-images.githubusercontent.com/924465/107681222-a3bba080-6c53-11eb-97c4-c1090b5c60ad.mp4
