### ISSUE TITLE
[suggestion] make relay send info to a detector on top of the block even when off

### ISSUE THREAD

**Issue by winsrp** [raoulvdberge/refinedstorage#1425]
So I was testing some setups today, and the most common use I have on the detector is for the relay, probably everyone agrees on that. 

Here is the setup I did.

Cable -> relay - > cable, and on top of the relay a detector.

In this specific case I wanted it to collect water from a nearby source using the destructor. So I set the relay to only be ON on redstone signal, I set the detector to check if water is under 10.000 millibuckets then send a signal.

Of course at this point the relay is off, and the detector on top (that looks absolutely awesome on top of the relay) is not getting any information from the network since the relay is off... and I said.. bummer.

I had to change my setup to 

cable -> detector -> relay - > cable

but to be honest the cable going into the detector is not the prettiest setup there is, visually it just looks like its not connecting... but the detector itself is a beautiful block and very useful. So here is when I wondered, if the relay would send network information to the detector when it is on top, even when the relay is off, then this should work fine, and look pretty at the same time.

=D, still just a thing to make it look pretty, something maybe for one of those days when you say.. hmm... nothing to do, lets work on making things prettier..

**Comment by raoulvdberge** [comment]
no
