### ISSUE TITLE
[1.12.1][1.12]Disks not loaded on game start

### ISSUE THREAD

**Issue by chrisisonwildcode** [raoulvdberge/refinedstorage#1426]
#### Issue description:

When going into single player world from client start the disks in the drives are not active and requires them to be removed then placed to become active. Inv of each disk is not accessible unless they have been reloaded into drive.

Controller and drives are in the spawn chunk, aka the world spawn chunk.

#### What you expected to happen:

I expect disks to be active on world load from client start.

#### Steps to reproduce:
1. have disks in drive (don't need to have inv on disk) and quit game.
2. restart client
3. load world
...

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12.1 & 1.12
- Forge: 14.22.0.2456
- Refined Storage: 1.5.16

Does this issue occur on a server? [yes/no]
??
#### If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here]

**Comment by raoulvdberge** [comment]
#1386
