### ISSUE TITLE
[1.12] Problem using Chisel & Bits on Cables

### ISSUE THREAD

**Issue by konradBalcerzak** [raoulvdberge/refinedstorage#1427]
#### Issue description:
When placing a bit from Chisel & Bits modin the same block as a cable, everything in this blockspace vanishes. Anything placed there afterwards gets destroyed.
#### What happens:
Cable and bits dissapear.
#### What you expected to happen:
Cable and bits exist in the same blockspace.
#### Steps to reproduce:
1. Place a cable
2. Place a bit from Chisel & Bits mod in the same block al the cable

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12
- Forge: 14.21.1.2443
- Refined Storage: 1.5.16
- Chisel & Bits: 14.6

Does this issue occur on a server? [yes/no]

#### If a (crash)log is relevant for this issue, link it here:

https://pastebin.com/mcq08yRm

**Comment by raoulvdberge** [comment]
Missing logs.

**Comment by konradBalcerzak** [comment]
Added.

**Comment by raoulvdberge** [comment]
Most likely a MCMultiPart issue. Please report on their tracker.
