### ISSUE TITLE
Sometimes non-existing Ores show up in Refined Storage

### ISSUE THREAD

**Issue by nekoexmachina** [raoulvdberge/refinedstorage#1428]
#### Issue description:

I have a setup that includes Digital Miner mining ore*, feeding it into Importer, exporting most of it into processing chain via Exporter with OreDict filters. 

Sometimes, Refined Storage system displays "Ghost" items - that is, Ore items that already were processed, and are not in the system anymore. Such items are unclickable, I can not do anything with them, they just consume screen space and mess up searches. Only way to fix it that I've discovered is to remove the Drive on which the items in questions are, then connect it back (or remove and place back the storage disks). 
Unfortunately, I have no clear way to reproduce. My experience was that item that is exact item in Exporter is not showing in Grid anymore, but any other type of item that is sharing OreDict entry with said item will show in the Grid in described state. Means that probably it needs more then 1 mod to generate different types of Ores. 

I've only tested that in singleplayer. 

Testing environment was: 192 units of Copper ore from each of the following:

Embers, Forestry, Immersive Engineering, Mekanism, NuclearCraft, Railcraft, Thermal Foundation. 

That was put into Refined Storage system with 64k disks. All of that was exported through Exporter into Mekanism processing chain, consisting of 1 Elite Enriching Factory, followed by 2 Elite Smelting Factories. 

Exporter was set to:

Compare NBT, Damage - No

Compare OreDict - Yes

Export Mekanism Copper Ore.

all of the ores were exported and processed, and exporter stopped working. Refined storage Grid still was showing several types of Copper Ore (Railcraft, IE, Forestry) with varying numbers from 10 to 80 of each. Each of the Ores were unclickable. After removing and placing back the 1st disk on which it all was stored, system was back to normal.

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge:  12.18.3.2422
- Refined Storage: refinedstorage-1.2.26.jar, latest from Curseforge.

**Comment by raoulvdberge** [comment]
1.10 is unsupported.
