### ISSUE TITLE
[1.10.2] solderer auto crafting issue. 

### ISSUE THREAD

**Issue by Firefly1029** [raoulvdberge/refinedstorage#1429]
#### Issue description:
When trying to auto craft something that requires using the solderer is gets suck because the solderer wont do anything.

#### What happens:
http://prntscr.com/ga8yt5
http://prntscr.com/ga8z3u
http://prntscr.com/ga8z91
http://prntscr.com/ga90ux

Says the machine is in use, I even tried moving everything then can be done in a furnace to one that i have setup for auto crafting. 

#### What you expected to happen:
I expected it to make the processors 

#### Steps to reproduce:
1. Solderer with crafter and import bus 
2. Auto craft processors 
3. Machine is use
...

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge: Unsure, playing sky factory 3
- Refined Storage: 1.10.2(i assume)

Does this issue occur on a server? [yes/no]
yes

#### If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here]

**Comment by way2muchnoise** [comment]
Can you post a screenshot of the crafter-solderer-importer setup?

**Comment by Firefly1029** [comment]
@way2muchnoise Thanks for the reply but as of right now I think I have it working, or at least some what. When I made the post the crafter was importing through the bottom which probably caused most of my issues. For the most part I think I have it working other then when attempting some higher numbers but I haven't tested much. If I run into more problems I'll update the post.

**Comment by way2muchnoise** [comment]
The crafter should be on the side or top, while the importer is on the bottom. From the [wiki](https://refinedstorage.raoulvdberge.com/wiki/solderer):

> In RS for MC 1.10.2 it is sided: bottom side for output slot and other sides for input slots.
