### ISSUE TITLE
Inv Tweaks sorting issue

### ISSUE THREAD

**Issue by roboderpy** [raoulvdberge/refinedstorage#1431]
#### Issue description:
Sorting inventory while in inventory that is not Crafting Grid sorts the hotbar.
https://dbot.serealia.ca/sharex/2017/08/302dfb22e9_%25pn_-2017-08-19_20-45-07.webm

**Comment by raoulvdberge** [comment]
Please report this on the InvTweaks tracker.

**Comment by Galaxy2Alex** [comment]
Has been reported, let me quote here: 
"[...]it's their fault if they aren't correctly marking what slots correspond to what parts of the inventory."

**Comment by raoulvdberge** [comment]
I'm not sure what he means by that.
