### ISSUE TITLE
Crafting is crashing the game

### ISSUE THREAD

**Issue by cybercronx** [raoulvdberge/refinedstorage#1432]
I dont know if this is a Reborn Storage Problem or a refined storage problem, as it states both mod names in the log.

Tried to craft something using the Reborn Storage crafter multiblock and it crashes the game.

What you expected to happen: It to craft something.

Steps to reproduce:
1. Try to autocraft using the Reborn Storage Crafter

- Minecraft: 1.12
- Forge: 1.12-14.21.1.2442
- Refined Storage: Does it on both 1.5.16 and 1.5.17

Does this issue occur on a server? [yes/no] IDK

https://pastebin.com/NMxZj6g3

**Comment by raoulvdberge** [comment]
This is not an Refined Storage issue (and I don't think this is a RebornStorage issue either).
