### ISSUE TITLE
Proposal: Storage Block Manipulator

### ISSUE THREAD

**Issue by Knito58** [raoulvdberge/refinedstorage#1433]
After derping with the settings one of my 20 16k-Storage Blocks is filled up wrongly. I want to use them as single item storage with the void funktion enabled. But now every non-farmed item ( about 9k ) went to a Storage Block during the last disk manipulation run.

It would be great if there was an easy way to pour the items back to disk. Maybe a Storage Block Manipulator could do this for Storage Blocks like a Disk Manipulator does it for disks.

**Comment by raoulvdberge** [comment]
#988
