### ISSUE TITLE
Crafting Grid Duplication

### ISSUE THREAD

**Issue by rakkfalen** [raoulvdberge/refinedstorage#1435]
#### Issue description:
The newest version seems to have a weird duplication glitch where when you are crafting and you run out of something, the crafting grid magically makes more. Seen here when trying to craft seeds from Mystical Agriculture, but I have seen it with other mods/items too...
https://youtu.be/O-r4xGaOJyQ
This does NOT happen all the time though... I have had it happen with Mystical Agriculture recipes, Actually Additions recipes, and once while making vanilla iron pickaxes, but it is infrequent.

#### What happens:

Crafting Grid makes additional ingredients for recipes when you run out.

#### What you expected to happen:

You can't craft any more when you are missing ingredients.

#### Steps to reproduce:

Unsure... It only happens occasionally. See video above.

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12
- Forge: 1.12-14.21.1.2443
- Refined Storage: 1.5.17

Does this issue occur on a server? [yes/no]

Haven't tried, I don't have a server.

**Comment by raoulvdberge** [comment]
Might be a crossmod issue... (like MouseTweaks or InvTweaks messing up the inventory)

**Comment by rakkfalen** [comment]
That could be. I do have Inventory Tweaks. Do you want a list of all the mods I'm using?

**Comment by raoulvdberge** [comment]
Wouldn't be of much use, that would be like finding a needle in a haystack.

**Comment by zlainsama** [comment]
I'm having this kind of item duplication simply by pulling all the items out from a external storage connected drawer controller with compacting drawer attached.
This happens a lot when multiple empty not-locked compacting drawers are attached to a drawer controller.
But not all the times.

**Comment by zlainsama** [comment]
![2017-08-28_14 18 19](https://user-images.githubusercontent.com/3251859/29761498-f169b042-8bfb-11e7-99d1-4b80624af09c.png)
![2017-08-28_14 18 29](https://user-images.githubusercontent.com/3251859/29761503-f17f3390-8bfb-11e7-8646-2a69d20bd00a.png)
![2017-08-28_14 18 37](https://user-images.githubusercontent.com/3251859/29761499-f16b242c-8bfb-11e7-9319-765ea28b844c.png)
![2017-08-28_14 18 42](https://user-images.githubusercontent.com/3251859/29761502-f1755aa0-8bfb-11e7-973e-d8e24723a7a4.png)
![2017-08-28_14 18 44](https://user-images.githubusercontent.com/3251859/29761501-f171ea50-8bfb-11e7-922a-5d97f293ffe2.png)
![2017-08-28_14 18 48](https://user-images.githubusercontent.com/3251859/29761500-f1719316-8bfb-11e7-8338-a368ef421408.png)
![2017-08-28_14 18 50](https://user-images.githubusercontent.com/3251859/29761504-f19b41ca-8bfb-11e7-83fe-b82fccb9d68d.png)
![2017-08-28_14 18 54](https://user-images.githubusercontent.com/3251859/29761505-f19d2864-8bfb-11e7-8a60-8733d7ae465a.png)
![2017-08-28_14 18 59](https://user-images.githubusercontent.com/3251859/29761506-f1a4b2c8-8bfb-11e7-9072-a92399bb30e2.png)
![2017-08-28_14 19 02](https://user-images.githubusercontent.com/3251859/29761507-f1a5b7fe-8bfb-11e7-92a3-8fe47a022676.png)
![2017-08-28_14 19 04](https://user-images.githubusercontent.com/3251859/29761508-f1a9f09e-8bfb-11e7-91c1-f1b7018f50f2.png)

**Comment by zlainsama** [comment]
Sorry for those long images.
Through some basic testing.
This can be done intentionally.

1. setup a controller with a grid.
2. connect a external storage to a drawer controller with a compacting drawer attached.
3. place 1 iron ingot into the system, which will go into the compacting drawer.
4. pull the iron ingot out, will result in 127 iron ingots.

**Comment by raoulvdberge** [comment]
I'm not even sure if this is an RS issue, RS just calls the SD API method:

https://github.com/raoulvdberge/refinedstorage/blob/mc1.12/src/main/java/com/raoulvdberge/refinedstorage/integration/storagedrawers/StorageItemItemRepository.java#L58-L68

**Comment by zlainsama** [comment]
I just tried AE2 with the exact setup, it doesn't duped items but items were disappearing.
Like RS, when the compacting drawer is locked, everything works fine.
Looks like this is SD's issue.

**Comment by jaquadro** [comment]
It was an SD problem, and it's fixed in 5.3.1.  Thanks for reporting.

**Comment by way2muchnoise** [comment]
Nice, closing this as it is fixed of SD's side.
