### ISSUE TITLE
Crash when right clicking crafting grid: "Comparison method violates its general contract!"

### ISSUE THREAD

**Issue by calloatti** [raoulvdberge/refinedstorage#1436]
#### Issue description:

Crash when right clicking crafting grid

#### What happens:

Right click crafting grid, crash

#### What you expected to happen:

Not crash

#### Steps to reproduce:
1.Right click crafting grid
2.Crash
3.
...

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.11.2
- Forge:13.20.1.2454
- Refined Storage:1.4.20

Does this issue occur on a server? [yes/no]

Not tested

#### If a (crash)log is relevant for this issue, link it here:

https://paste.ee/p/tYzNG

**Comment by raoulvdberge** [comment]
Duplicate #898
