### ISSUE TITLE
[Feature Request] Changing colors on grids

### ISSUE THREAD

**Issue by GameSlayar** [raoulvdberge/refinedstorage#1437]
#### Feature description:
Allow the user to right-click on any grid with a colored dye, and be able to change the color of any kind of grid to one of the 16 colors, so it can fit with the aesthetic of a room, for example.

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Refined Storage: 1.2.26

I apologize in advance if this has already been added in a 1.11 or 1.12 release, this post will be deleted promptly if that is the case.

**Comment by raoulvdberge** [comment]
No.

**Comment by GameSlayar** [comment]
Any particular reason?

**Comment by Tahakk** [comment]
Maybe more important things to do? If you really want it codes are here at the open. Do it yourself.
