### ISSUE TITLE
RS doesn't divide work over all crafters that are available

### ISSUE THREAD

**Issue by MachoPikacho** [raoulvdberge/refinedstorage#1438]
#### Issue description:
I have 2 crafters with the same pattern Iron Ore -> Iron ingot  and they are connected to furnace when i request 64 iron ingots all of the ore is getting to only one of the furnaces
#### What happens:
RS system doesn't divide work between all available crafters
#### What you expected to happen:
RS system do divide work between all available crafters

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge: 8.0.99.99
- Refined Storage: 1.2.26

Does this issue occur on a server? yes

**Comment by way2muchnoise** [comment]
That is a 1.11+ feature, you'll have to use other solutions in 1.10.2 (eg. chest and EIO conduits with roundrobin).
