### ISSUE TITLE
Suggestion: Sort option to show what storage mode/location for items

### ISSUE THREAD

**Issue by illiath** [raoulvdberge/refinedstorage#1441]
As mentioned in the issue title, this is an improvement suggestion, so not a priority.

Ever since first using AE1 one of the issues I have had is figuring out if something is on one of the storage disks or one of the (many) external storage options I have hooked into the network. As RS is a spiritual successor to AE1 it has kept most of the original UI flavour, including this little quirk from the original.

I'd love to be able to quickly glance at a grid (even if it is a special "storage grid" or something) that shows me at the very least what 'type' of storage items are stored in (internal/external, storage disk/block, something like that whatever works easiest). Just some way so I can look at the item storage and go "Oh, I should move all those into external storage that is 'cheaper' to store them in", or vice-versa.

**Comment by raoulvdberge** [comment]
I don't think this is needed.

**Comment by illiath** [comment]
You do not think this is needed, I agree it is not necessary. The same as it is not necessary to use any mod for minecraft as the game is entirely playable without mods. However, this was a suggestion for an improvement to the mod, that I see no current way to to find this information out in RS, and there was a method in AE1 (the ME chest could be used to look at each disk manually, but RS has no equivalent item) thought the method was complex and annoying it could have been done. With RS there is no way to tell other than getting a complete list of your items out of game and looking at each and every item stored in the external storage units.

This is all I have to add in case others come searching through the archive of issues for a similar request.

**Comment by raoulvdberge** [comment]
We both agree that it's not necessary. We do not agree on if it is needed.

You think it is needed because there is not a current way of viewing what items belong to what storage mediums.

I think it is not needed because I don't feel such a feature belongs in RS.

**Comment by raoulvdberge** [comment]
(You can also use a Portable Grid and insert your disks in there - as a workaround)
