### ISSUE TITLE
Request: InventoryTweaks interaction in 1.12.1

### ISSUE THREAD

**Issue by donqixot** [raoulvdberge/refinedstorage#1443]
#### Issue description:
InventoryTweaks mod has feature to drop everything from inventory to an opened storage by pressing [spacebar]+[leftclick]. This feature works nicely with most storage providing mods. I tried this with Refined Storage in Grid or Crafting Grid, it doesn't work. I am not sure if this request should be for InventoryTweaks team or for your team, please let me know. I am using refinedstorage-1.5.17, forge 14.22.0.2467, InventoryTweaks-1.63+beta.108. Thanks.

**Comment by raoulvdberge** [comment]
api doesn't allow it
