### ISSUE TITLE
[1.11.2] Incompatibility with CarryOn

### ISSUE THREAD

**Issue by Tschipp** [raoulvdberge/refinedstorage#1444]
#### Issue description:
Blocks from RS crash the game when the are placed via CarryOn
#### What happens:
Carry On tries to rotate every block before it is placed. It does this by going through all the Properties and then determining if the prop is instanceof PropertyDirection. Your blocks seem to have this PropertyDirection, so a flag is set to true.
Later, if that flag is true, it tries to adjust the rotation by calling 
`state.withProperty(BlockDirectional.FACING, facing.getOpposite()`.
This then crashes the game and claims that there is no PropertyDirection on the block. I'm not sure why this is happening. Is the error on CarryOn's end? It works with most other mods.
#### What you expected to happen:
It places the block and adjusts the rotation.
#### Steps to reproduce:
1. Pick up Block like Controller with Carry On
2. Place

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.11.2
- Forge: 13.20.1.2386
- Refined Storage: 1.4.20

Does this issue occur on a server? [yes/no]
Yes, but also on SP
#### If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here]
https://pastebin.com/Ske200uL

**Comment by Tschipp** [comment]
Found that the issue was partially on side of CarryOn. Should work now

**Comment by raoulvdberge** [comment]
I do not know what CarryOn is

**Comment by Tschipp** [comment]
Edit 2:
You should probably make sure that the TileEntity is not null in BlockDiskDrive.breakBlock, because it's throwing a null pointer exception, because CarryOn removes the TileEntity before the block is removed.

**Comment by raoulvdberge** [comment]
Dont do that! This is the type of shit that breaks worlds and mods. RS does critical stuff in breakBlock.

**Comment by Tschipp** [comment]
The thing is, I don't want it to drop the contained items. Carry On retains the items inside. Would you know of another way of removing the block but not dropping the contents of the TE?

**Comment by raoulvdberge** [comment]
Nope, but your current way is much worse than having the item drops.

Im 100% sure this mod gave lots of modders headaches already x.x

**Comment by Tschipp** [comment]
Well, i did a workaround now.
