### ISSUE TITLE
AutoCrafting Corrupted my World?

### ISSUE THREAD

**Issue by Diverse123** [raoulvdberge/refinedstorage#1445]
#### Steps to reproduce:
1. Have a ton of autocrafters
2. Maybe have some loops
3. Start Crafting alot
...

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge: 12.18.3.2316
- Refined Storage: 1.2.26

Does this issue occur on a server? [yes/no] yes

#### If a (crash)log is relevant for this issue, link it here:
https://pastebin.com/8yaG1Q06
[pastebin/gist/etc link here]

**Comment by raoulvdberge** [comment]
Delete your controller through mcedit.

1.10.2 is unsupported

**Comment by Diverse123** [comment]
Hello, i am not sure where to respond. But how do i use mcedit with
SkyFactory 3? or RefinedStorage? Ive never used mcedit

**Comment by Tahakk** [comment]
[MCEdit](http://www.mcedit.net/) is software that will open you MC map out of Minecraft and let you edit the world. At this case you are supposed to use it to delete Controller which I guess will turn off your Refined Storage PC meaning that you should be able to load back to your world / start you server.
