### ISSUE TITLE
External storage and autocrafting

### ISSUE THREAD

**Issue by Paul17041993** [raoulvdberge/refinedstorage#1446]
The autocrafting should be able to proceed with pending craft requests, even if the required number of items isn't met. Such as if 64 is available via an external storage source but the pending requests require 92, the system currently waits until that specific number becomes available before proceeding.

A simple example of how this issue occurs is if you had a single igneous extruder (or other cobble gen) attached directly to an external storage interface, so that the system would see up to 64 cobble available. But if you were to tell it to craft a stack of furnaces, it will never do so due to it then needing 8*64, despite the fact that more cobble will be available after pulling the stack.

**Comment by raoulvdberge** [comment]
You can still start a crafting task even if the items are not available.

**Comment by Paul17041993** [comment]
But it never _completes_ the tasks, that's the problem.

**Comment by Paul17041993** [comment]
ok so, something else horribly wrong happened in testing instead...
<img width="240" alt="screenshot_7" src="https://user-images.githubusercontent.com/3912867/30084506-0e89ce38-92d6-11e7-87ef-9f41a1872d41.png">

**Comment by Paul17041993** [comment]
ok so, external storage of limited capacity does work, but extremely sporadically and randomly locks up for no reason unless you give it the exact number required, it can even block half-way...

<img width="180" alt="screenshot_8" src="https://user-images.githubusercontent.com/3912867/30084938-cb335846-92d7-11e7-86bc-ff2ac3bd6e1d.png">
<img width="178" alt="screenshot_9" src="https://user-images.githubusercontent.com/3912867/30084940-ccddfbec-92d7-11e7-9380-22246ffd06e8.png">

The sand is in local storage, and it already made some glass, so I don't really know what's blocking it there...
