### ISSUE TITLE
[1.12][1.5.18-1357] ProjectE integration knowledge handling error

### ISSUE THREAD

**Issue by ACSD** [raoulvdberge/refinedstorage#1450]
#### Issue description:
items teaching behavior of grid is vastly different from item teaching behavior of tablet
#### What happens:
items with damage are taught to the table as their own knowledge
#### What you expected to happen:
put in a tool (sword for example) of any material (stone for example) and you already know the tool's (stone sword) --> you only get the emc of the item put in your tablet
put in a tool (sword for example) of any material (stone for example) and you don't know the tool's (stone sword) --> you learn the tool without damage value
#### Steps to reproduce:
1. damage any damageable item
2. put damaged item in grid
3. repeat for any damage value

- Minecraft: 1.12.1
- Forge: any version
- Refined Storage: 1.5.18-1357

**Comment by raoulvdberge** [comment]
Thanks for testing, so what you mean is that it learns "damaged" tools instead of "regular" tools?

**Comment by ACSD** [comment]
put a stone sword in any grid with a damage value and it will force the table to have that knowledge
minecraft:stone_sword with durability 130 / 131 will be taught to the tablet with its damage value intact instead of checking for minecraft:stone_sword

**Comment by ACSD** [comment]
while we are on the topic of projecte integration i strongly reccomend you fork the integration out to a separate addon or move it to rsaddons

also probably going to keep posting bugs here as i find them because if i started a thread for each of them the issues page would get clustered.
i found few more really difficult to describe bugs so i will probably end up just creating a supper flat world of all the replicatable ones and zipping it.

**Comment by raoulvdberge** [comment]
Your first bug would be attributed to: https://github.com/sinkillerj/ProjectE/issues/1592

**Comment by raoulvdberge** [comment]
Why would this integration go into a separate mod?

**Comment by ACSD** [comment]
just personal advice, pack makers might not want something this broken happening between these two mods, at least make it configurable

**Comment by raoulvdberge** [comment]
This is not broken, it is the exact same behavior as ProjE.
