### ISSUE TITLE
Autocrafting with liquids wants to make buckets

### ISSUE THREAD

**Issue by llloyd4** [raoulvdberge/refinedstorage#1455]
#### Issue description:

I have milk in an external tank with an External Storage Bus set to fluid, it shows up in the Fluid Grid, I go to autocraft a cake and it wants to make 3 buckets even though 3000mb of milk is available.

#### What happens:

I have milk in an external tank with an External Storage Bus set to fluid, it shows up in the Fluid Grid, I go to autocraft a cake and it wants to make 3 buckets even though 3000mb of milk is available.

#### What you expected to happen:

To craft the cake with the available milk with out needing 3 buckets in inventory

#### Steps to reproduce:
1. Create a cow milking system
2. Put External Storage Bus on the output tank, set it to fluid and extract only
3. Create a pattern for cake using 3 milk, 2 sugar, 1 egg, and three wheat (vanilla recipe) 
4. Attempt to autocraft the cake.
...

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12.1
- Forge: 14.22.0.2467
- Refined Storage: 1.5.17

Does this issue occur on a server? [yes/no]

No idea, I play single player.

#### If a (crash)log is relevant for this issue, link it here:

https://i.imgur.com/cH5yGNN.png

**Comment by way2muchnoise** [comment]
You should have at least one bucket in the system if you want to do fluid crafting. RS doesn't just use the liquid, it will fill a bucket and then use that. This is intended behaviour.

**Comment by raoulvdberge** [comment]
Please, read the wiki carefully.
