### ISSUE TITLE
Circular dependency! loop in processing with nether stars

### ISSUE THREAD

**Issue by cham326** [raoulvdberge/refinedstorage#1456]
#### Issue description:
when ever it try to auto craft with anything related with nether stars it says Circular dependency! loop in processing
#### What happens:
when ever I try to start it shows me Circular dependency! loop in processing
#### What you expected to happen:
show me the list of things I need and starting auto crafting 
#### Steps to reproduce:
1.try to start auto crafting awaken cores
2. shows Circular dependency! loop in processing
3.
...

#### Version (make sure you are on the latest version before reporting):

- Minecraft:1.10.2
- Forge: 12.18.3.2316
- Refined Storage: 1.2.26

Does this issue occur on a server? [yes/no]
lan server
#### If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here]

**Comment by way2muchnoise** [comment]
This usually is related to ingots -> blocks -> ingots  or the same process with dusts. You'll have to fix that one yourself by eliminating the pattern that creates the loop.

**Comment by cham326** [comment]
but im auto crafting waken cores, im not turning waken ingots back to blocks

**Comment by way2muchnoise** [comment]
Dust to ingots and ingots to dust? You'll just have to think.

**Comment by cham326** [comment]
I use essence

**Comment by cham326** [comment]
but anyway I figured it out, my brother did not use the essence to create gold he used nuggets
