### ISSUE TITLE
Crash - Stack can not be invalid

### ISSUE THREAD

**Issue by DeiusShrab** [raoulvdberge/refinedstorage#1457]
#### Issue description:
Game crashed while crafting some IC2 items in crafting grid, now instantly crashes on world load
Several crafting processes were going on at the time
- Crafting Tin/Copper plates via crafter and Immersive Engineering metal press
- Crafting Heat Exchanger with crafting grid
- Crafting circuits and advanced circuits via crafter and Mekanism infusing/enriching factories

#### What happens:
Game crashes on world load

#### What you expected to happen:
Crafting and/or mining

#### Steps to reproduce:
1. Set up a crafter to produce plates with an IE metal press, queue up a couple dozen
2. Set up a crafter (with copper chest, opaque itemducts, servos, and filters) to produce Mekanism circuits, queue up a couple dozen
3. Attempt to craft IC2 Nightvision goggles, manually crafting components as needed. Be sure to use as many different mods oredict-ed together as possible to maximize chance of error

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.11.2
- Forge: 13.20.1.2393
- Refined Storage: 1.4.20

Does this issue occur on a server?
No, singleplayer

#### If a (crash)log is relevant for this issue, link it here:

https://pastebin.com/BXLuMv8d

**Comment by raoulvdberge** [comment]
Sorry, 1.11 is unsupported.
