### ISSUE TITLE
Large crafting jobs bring server to a halt

### ISSUE THREAD

**Issue by tgstyle** [raoulvdberge/refinedstorage#1458]
#### Issue description:
Trying to craft over 2000 steel ingots with processing patterns.

#### What happens:
Server slows down to a crawl.

#### What you expected to happen:
Server to remain stable while processing the crafting job.

#### Steps to reproduce:
1. Set up the proper patterns to make steel with external machines.
2. Start a job with 2000+ ingots.
3. Server will slow down and may eventually crash.
...

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12.1
- Forge: 14.22.1.2479
- Refined Storage: 1.5.18

Does this issue occur on a server? [yes/no]

#### If a (crash)log is relevant for this issue, link it here:

Some NPS samples here
https://www.dropbox.com/s/phso0cgs3rkungx/samples.zip?dl=1

**Comment by raoulvdberge** [comment]
#838

**Comment by tgstyle** [comment]
FYI I have noticed spikes on auto-crafting jobs with export bus using a crafting card. It seems to happen when the RS has none of the items to craft in it's storage. Putting a detector on to craft when it has the items helps, but it seems there may be some code causing lag when there is not enough of the items?
