### ISSUE TITLE
Autocrafting crashing server

### ISSUE THREAD

**Issue by Serifina** [raoulvdberge/refinedstorage#1459]
#### Issue description:
Autocrafting crashes the server
#### What happens:
When trying to autocraft something it lacks the items for
#### What you expected to happen:
Not craft it and not crash?
#### Steps to reproduce:
1. Have too few ender essence (Mystical Agriculture) and try to craft ender pearls or have too few ender pearls and try to autocraft Resonant Conversion Kits from Thermal Expansion
...

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12.1
- Forge: 2463
- Refined Storage: 1.5.18

Does this issue occur on a server? [**yes**/no]

#### If a (crash)log is relevant for this issue, link it here:
[crash-2017-09-14_15.59.46-server.txt](https://github.com/raoulvdberge/refinedstorage/files/1304954/crash-2017-09-14_15.59.46-server.txt)

[pastebin/gist/etc link here]

**Comment by raoulvdberge** [comment]
Sorry, the crash report doesn't tell me anything about the watchdog crash.
