### ISSUE TITLE
[ProjectE] No Covalence Loss

### ISSUE THREAD

**Issue by pupnewfster** [raoulvdberge/refinedstorage#1461]
#### Issue description:

Refined storage does not respect projecte's covalenceLoss config option when putting an item in the transmutation table. I believe it retrieves the value of the item instead of retrieving the "sell value" of the item. https://github.com/sinkillerj/ProjectE/blob/master/src/main/java/moze_intel/projecte/utils/EMCHelper.java#L258

#### What happens:

EMC ratio is one to one.

#### What you expected to happen:

Loss of EMC

#### Steps to reproduce:
1. In the ProjectE/ProjectE.cfg change the covalenceLoss to be something below 1.0
2. Put an item in the refined storage system (no other storage locations so it has to go into the transmutation table) I used a diamond.
3. There is no loss in emc for pulling the item out and putting it back in through the refined storage system.

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12.1
- Forge: 14.22.1.2480
- Refined Storage: 1.5.18

Does this issue occur on a server? [yes/no]

Probably, did not bother setting one up to test.

#### If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here]

**Comment by raoulvdberge** [comment]
That class you linked isn't part of the API, so I can't use it.

Furthermore, I already opened an issue for this at ProjE's issue tracker long time ago:

https://github.com/sinkillerj/ProjectE/issues/1593
