### ISSUE TITLE
[1.12] Quartz Unable To be Smelted Into Silicon 

### ISSUE THREAD

**Issue by Umbreon831** [raoulvdberge/refinedstorage#1462]
#### Issue description:
When adding nether quartz to a fueled furnace, silicon is not produced. The furnace remains inactive.
#### What happens:
A fueled furnace with nether quartz in the input slot remains inactive.
#### What you expected to happen:
Unless I'm mistaken, smelting nether quartz should produce silicon in a furnace.
#### Steps to reproduce:
1.Fuel a furnace
2.Insert nether quartz in the furnace's input slot
3.Observe that the quartz does not smelt into silicon
...

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12
- Forge:14.21.1.2443
- Refined Storage:1.5.18

Does this issue occur on a server? [yes/no]
yes

**Comment by raoulvdberge** [comment]
Are you on the latest RS? Your earlier comment refers to RS 1.5.10.

**Comment by Umbreon831** [comment]
i am using twitch

**Comment by Umbreon831** [comment]
also i am using JEI and when i hover over a  item form RS It Says Tooltip Error. see log

**Comment by raoulvdberge** [comment]
You need to be on the latest RS version before you report things to me. Check the RS version by pressing thr mods button in MC.

**Comment by raoulvdberge** [comment]
I cannot reproduce this issue, your modpack is probably messed up, or you're running an outdated version of Refined Storage.
