### ISSUE TITLE
Game crash on opening crafting grid

### ISSUE THREAD

**Issue by EtherG** [raoulvdberge/refinedstorage#1464]
#### Issue description:
the game crashed on opening a crafting grid
#### What happens:
it crashes
#### What you expected to happen:
not crash

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12.1
- Forge: 2467
- Refined Storage: 1.5.18

Does this issue occur on a server? [yes/no]
yes
#### If a (crash)log is relevant for this issue, link it here:

https://paste.ee/p/Jg0Cq

**Comment by raoulvdberge** [comment]
This looks like a Minecraft bug. I cannot reproduce it either.
