### ISSUE TITLE
I can't recipe storage part

### ISSUE THREAD

**Issue by forestbat** [raoulvdberge/refinedstorage#1466]
#### Issue description:
I can't recipe 64k storage part，there is a flint always inserting，and there is not any tweak to the recipe of storage part。
#### What happens:
![2017-09-19_22 11 07](https://user-images.githubusercontent.com/23413915/30596864-fa0d9716-9d87-11e7-9517-a35e615e72fb.png)

#### What you expected to happen:
I hope I can recipe the storage part without the f**king flint。
#### Steps to reproduce:
1.
2.
3.
...

#### Version (make sure you are on the latest version before reporting):

- Minecraft:1.11
- Forge:
- Refined Storage:1.4.20

Does this issue occur on a server? [yes/no]

#### If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here]

**Comment by raoulvdberge** [comment]
1) There is a tweak on the recipe
2) You made the recipe as a processing pattern, then only will it "insert". Make it as a regular recipe.
