### ISSUE TITLE
Crash when craft only exporter tries to ignore metadata on damaged Item.

### ISSUE THREAD

**Issue by Darkere** [raoulvdberge/refinedstorage#1467]
#### Issue description:
Apparently ignore metadata conflicts with autocrafting.

#### What happens:
Everyone on the server got timed out. After restart Exporter was reset to the previous setting and thus fine.

#### Steps to reproduce:

1. Set up autocrafting for stone sword.
2. Set an exporter to export a damaged stone sword( craft only ).
3. Click the Ignore Metadata Button.
...

#### Version (make sure you are on the latest version before reporting):

- Minecraft:1.12.1
- Forge:2485
- Refined Storage:1.5.8

Does this issue occur on a server? yes

#### If a (crash)log is relevant for this issue, link it here:
No crashlog. Log has no Info on the Issue. 
https://pastebin.com/6sp0rK0T

**Comment by raoulvdberge** [comment]
The crashlog tells me nothing about the problem, the actual crash is not even in there.

**Comment by raoulvdberge** [comment]
I will attempt to reproduce this issue, however.

**Comment by raoulvdberge** [comment]
The craft-only option has been removed, so this issue can be closed.
