### ISSUE TITLE
Disk Manipulator is painfully slow with fluid storage disks

### ISSUE THREAD

**Issue by misterhaan** [raoulvdberge/refinedstorage#1468]
#### Issue description:
I tried to use the Disk Manipulator to empty a smaller Fluid Storage Disk (256k) into the larger one (512k) in a Disk Drive.  It has been going for a full real-life day and is only half done.  I didn’t use any Speed Upgrades but this seems unreasonably slow.

#### What happens:
Disk Manipulator transfers fluid very slowly; approximately 2 millibuckets per second.

#### What you expected to happen:
Transfer fluids treating a bucket like an item rather than a millibucket as as item.

#### Steps to reproduce:
1.  Put at least a bucket of a fluid into a Fluid Storage Disk (i had 254 buckets of lava and 1 bucket of destabilized redstone).
2.  With an empty Fluid Storage Disk in a Disk Drive on the network, place the filled Fluid Storage Disk into a Disk Manipulator set to empty fluids.
3.  See the millibuckets tick down very slowly.

#### Version (make sure you are on the latest version before reporting):

- Minecraft:  1.11.2
- Forge:  13.20.1.2476
- Refined Storage:  1.4.20

Does this issue occur on a server? [yes/no] yes

#### If a (crash)log is relevant for this issue, link it here:
n/a
[pastebin/gist/etc link here]
n/a

**Comment by calloatti** [comment]
Add at least a stack upgrade maybe?

**Comment by raoulvdberge** [comment]
The disk manipulator is meant to be used with a stack upgrade and speed upgrades.
