### ISSUE TITLE
[1.10.2] Solderer not working at all

### ISSUE THREAD

**Issue by oftheNorthWind** [raoulvdberge/refinedstorage#1470]
1.10.2 Issue description: When playing FTB infinity lite, I noticed that my solderer suddenly stopped working. I haven't been able to make any parts with it since.

What happens: My solderer flat out doesn't work.

Does this issue occur on a server? [yes/no]
Yes

**Comment by Tahakk** [comment]
As 1.10.2 is no supported anymore and you didn't even followed prepared issue description good luck
