### ISSUE TITLE
[1.12.2] pattern grid crashes server with SpongeForge

### ISSUE THREAD

**Issue by hunter688** [raoulvdberge/refinedstorage#1471]
#### Issue description:
whem manipulate with pattern grid can crash server

#### What happens:
server crashes

#### What you expected to happen:
no crash

#### Steps to reproduce:
use SpongeForge
see: https://github.com/SpongePowered/SpongeForge/issues/1775

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12.2
- Forge: 2481
- Refined Storage: 1.5.18

Does this issue occur on a server? [yes/no]
yes

#### If a (crash)log is relevant for this issue, link it here:
https://github.com/SpongePowered/SpongeForge/issues/1775

I think yu can help SpongeForge to resolve issue.

**Comment by raoulvdberge** [comment]
This is an issue for SpongeForge to fix.
