### ISSUE TITLE
Incompatible w/Ender IO Conduits(?)

### ISSUE THREAD

**Issue by TheGreatNaj** [raoulvdberge/refinedstorage#1472]
#### Issue description:
I have a set up for auto crafting including with solderers. When I try to request something made by solderer it shows "Machine in use" but if you check the machines nothing is being crafted. Sometimes its worked for a couple components but its not really consistent. I had been trying to figure out why this wasn't working when I had it set up like this in another mod pack but I realized before I was using RS importers instead of Ender IO item conduits. Once I switched them out they worked fine. Personally I wanted to use the conduits because they have facades and RS cables don't.

#### Steps to reproduce:
1. Set up like in image https://imgur.com/a/hDofu
2. Request item needing multiple pieces crafting in a solderer (Personally was trying to make a 512 fluid storage disk)
3. The machines might make the first couple components but then stall without completing the requested item. Monitor says "machine in use" while machines are empty.

- Minecraft: 1.10.2
- Forge: 12.18.3.2422
- Refined Storage: 1.2.26

Does this issue occur on a server? [yes/no]
Single player

Just a minor thing. Mostly I want to make sure Im not doing anything stupid and they actually work fine lol

**Comment by raoulvdberge** [comment]
1.10.2 is unsupported
