### ISSUE TITLE
Portable Grid disapearing

### ISSUE THREAD

**Issue by TweekinDragon** [raoulvdberge/refinedstorage#1473]
#### Issue description:
was moveing stuff from a chest to my main system so i put all my gear in my portable grid and placed it on the ground so my invantory was empty forgot i could acsess it like that so i used my empty hand to pick it up but it went POOF!! instead over half of a 64K worth of stuff gone bye bye no comeing back. DX
#### What happens:
when i placed my grid on the ground went to pick it up useing my empty hand it completely broke 
#### What you expected to happen:
it to go in to my invantory 
#### Steps to reproduce:
1.put on ground 
2.break with empty hand
3.
...

#### Version (make sure you are on the latest version before reporting):

- Minecraft:1.12.1
- Forge: 1.12.1-14.22.1.2485
- Refined Storage: 1.5.18

Does this issue occur on a server? [yes/no]

#### If a (crash)log is relevant for this issue, link it here:
no crash just rage

**Comment by raoulvdberge** [comment]
Do you have any logs of when this happened?

**Comment by raoulvdberge** [comment]
Every RS block does this, I probably should change that.

**Comment by TweekinDragon** [comment]
yeah that would be a good idea lol thank you
