### ISSUE TITLE
1.11.2 Mekanism Sawmill auto-crafting enters some kind of infinite loop

### ISSUE THREAD

**Issue by LordHellscream** [raoulvdberge/refinedstorage#1474]
#### Issue description:
Mekanism Sawmill kept running by auto crafter 
#### What happens:
When I have some items that need wood planks, and have auto-crafter recipe for wood planks coming from Mekanism Sawmill, it just kept going. I needed to create 1 wooden chest, and it sawed over 1000 wood planks and wouldn't stop.

Note: Other mekanism blocks works fine (As far as i know) with auto crafting

The crafting recipe is: (ore dict enabled, actual crafting is using redwood blocks for Biomes o plenty)
(Material) : Wood x 1
(Output) : Wood Plank x 6, wood dust x 1  

#### What you expected to happen:
crafting stops when enough material to finish the crafting request
#### Steps to reproduce:
1. Set up process auto crafting for Mekanism sawmill (see recipe above), - (note: I've done refined storage auto craft for a long time, so I am pretty confident to know what I am doing)
2. Setup regular auto craft for a wooden chest (ore dict enabled)
3. request some wooden chest ( i did 2 )
NOTE: the auto craft will start even if i already have enough wood to craft those chests to begin with
If I remove the pattern from sawmill autocrafter, everything works fine.

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.11.2
- Forge: 2454
- Refined Storage: 1.4.20

Does this issue occur on a server? [yes/no]

#### If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here]

**Comment by raoulvdberge** [comment]
1.11.2 is unsupported.
