### ISSUE TITLE
Negative Fluid values 

### ISSUE THREAD

**Issue by mrdeadlocked** [raoulvdberge/refinedstorage#1475]
#### Steps to reproduce:
1. RS Network connected to 2 quantum tanks. Fill quantum tanks with steam. RS Fluid grid shows  negative amount of steam.

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12.2
- Forge: 14.23.0.2493
- Refined Storage: refinedstorage-1.5.18.jar

Does this issue occur on a server? Yes

#### If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here]
![image](https://user-images.githubusercontent.com/461352/31040334-37f18258-a554-11e7-89af-517c8c7d49e9.png)
![image](https://user-images.githubusercontent.com/461352/31040337-425a612e-a554-11e7-8629-eaefdc19140d.png)
![image](https://user-images.githubusercontent.com/461352/31040341-498fc812-a554-11e7-83e2-9958d248149b.png)

**Comment by raoulvdberge** [comment]
That is because you are overflowing a 32 bit integer value.

**Comment by mrdeadlocked** [comment]
It does a similiar issue with the Quantum Storage Disks ina  drive.


![image](https://user-images.githubusercontent.com/461352/31498191-58ac8d64-af2f-11e7-95ec-fcfbf713bcb9.png)
