### ISSUE TITLE
Ore dictionary registration timing...

### ISSUE THREAD

**Issue by PongoSapiens** [raoulvdberge/refinedstorage#1476]
#### Issue description:
I'm trying to use Mystical Agriculture to "grow" silicon, but the recipe isn't available, and the author of that mod said "This is because refined storage registers oredictionary entries during the same event as I register recipes, so load order becomes an issue." and then "The refined storage devs could register items in the oredictionary when they register items".
https://github.com/BlakeBr0/MysticalAgriculture/issues/105

#### What happens:
Unable to craft silicon from silicon essence.

#### What you expected to happen:
Recipe to craft silicon from silicon essence would be available.

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12.1
- Forge: 2478
- Refined Storage: 1.5.18
- Mystical Agriculture: 1.6.4

Does this issue occur on a server? [yes/no]
yes

**Comment by raoulvdberge** [comment]
When you register recipes that are other mod dependant you probably need to be registering recipes in postInit.

**Comment by BlakeBr0** [comment]
The issue with that is then you have to mess with load order because of mods like crafttweaker. Registering items in the oredictionary during RegistryEvent.Register<Item> has no downsides from what I can tell..
