### ISSUE TITLE
Minecraft crashes when i open wireless grid

### ISSUE THREAD

**Issue by Diamond45123** [raoulvdberge/refinedstorage#1477]
#### Steps to reproduce:
1.
2. IDK
3.
...

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.11.2
- Forge: 13.20.1.2425
- Refined Storage: 1.4.20

Does this issue occur on a server? [yes/no] IDK

#### If a (crash)log is relevant for this issue, link it here: https://pastebin.com/uAigUfg9

[pastebin/gist/etc link here]

**Comment by raoulvdberge** [comment]
Mekanism messed up their get item name implementation. This is a Mekanism bug.

**Comment by Diamond45123** [comment]
@raoulvdberge Well, i did what you said, and reported to mekanism, they fixed it here : https://github.com/aidancbrady/Mekanism/issues/4731, but after that i got the same crash but for galactic craft, i gone ahead and made an issue there too : https://github.com/micdoodle8/Galacticraft/issues/3002, but then he said : 

> The root cause of this problem is:

This Refined Storage contains an invalid item: the item id + damage combo does not exist

Either it's a bug in Refined Storage, or another possible cause is that you added or removed a mod or updated a mod which added new items to the game, and so some of the item ids assigned by Forge changed - I think that can happen, not sure how common it is though

Refined Storage can fix this problem for all mods simply by including try ... catch error trapping in GridStackItem.getName() at line 60, or some other sensible place

It is NOT a Galacticraft bug. The other bug was NOT a Mekanism bug. @raoulvdberge was wrong to say that Mekanism messed up the naming system.

I do not see any advantage in coding a workaround for this specific item in Galacticraft, as that will not fix the issue - i.e. wrong item id and damage value - it would just prevent this specific crash for this specific item, but it won't stop a similar crash for any of 100s of other Galacticraft items.

It is not a bug in our mod if the mod crashes when you try to pass in an item with a damage value which is outside the range of registered sub-types for that item. < 
I'm sorry for bothering you again.
