### ISSUE TITLE
Crafting pattern to simply wait for resources

### ISSUE THREAD

**Issue by TvL2386** [raoulvdberge/refinedstorage#1479]
Hi guys,

I have a feature request:
I'm using a Thermal Expansion Igneous Extruder to generate obsidian. The machine will generate a stack of obsidian and then stops because the output slot is full.

I've put an RS External Storage on the machine so I always have 64 obsidian in my RS network.
However, when I craft something that needs more then 64 obsidian, it will not work of course, because there aren't enough resources. It would be cool if there is some way to tell the RS network that obsidian is automatically created. Just pull whatever there is and wait for more to appear.

I'm thinking of some kind of a hack where you use the Processing Pattern Encoder to tell input: none, output: 1 obsidian. Maybe put it on the Igneous Extruder in this case, or maybe put it in a crafter (not attached to any machine).

Let me know what you think :-)

**Comment by TvL2386** [comment]
Hmmmzzzz... Now that I think of it, maybe it's the same as starting a job with CTRL+SHIFT

**Comment by raoulvdberge** [comment]
Yep.
