### ISSUE TITLE
Importer should be able to import from disk drive

### ISSUE THREAD

**Issue by Zettt** [raoulvdberge/refinedstorage#148]
When placing a disk drive with a storage inside in front of an importer, it should import the contents on disk. 

To make it a little less comfortable, you can make it necessary for the disk drive to be powered for the items to import.

**Comment by raoulvdberge** [comment]
Huh? Why would you try to import something that is already in the system (on the disks)? Or you mean from one storage system to another?

**Comment by raoulvdberge** [comment]
Huh? Why would you try to import something that is already in the system (on the disks)? Or you mean from one storage system to another?

**Comment by Zettt** [comment]
Thanks for labeling it as a feature request. I can't do that. 

Yes, I meant importing from another system. Basically I want to replace my 4k disk with 16k one's, and I can't figure out how to do that, other that "re-importing" the disk.

**Comment by raoulvdberge** [comment]
That wouldn't be possible, as the importer would connect to the storage network of the storage disks.

However, what I could do is implement #39 in the future.
