### ISSUE TITLE
Is there a fix/workaround for disks suddenly becoming unreadable?

### ISSUE THREAD

**Issue by PurpleHel** [raoulvdberge/refinedstorage#1480]
As described in https://github.com/raoulvdberge/refinedstorage/issues/821 and others, I have a 64k disk that isn't readable after being moved. I have a save of the world from several hours previously, before the move, where the disk is readable. However, I did a lot of building and landscaping in those several hours, and really don't want to go back to the save and lose that work. I tried saving the disk drive with the disk in it via a structure block, and then restoring from the structure block in the current version of the world, but there's no disks in the drive when I restore the structure.

**Comment by raoulvdberge** [comment]
And which version are you on? Don't remove the issue template, it's there for a reason.

**Comment by PurpleHel** [comment]
MC1.12.1, RS 1.5.18, forge 14.22.1.2485
But since this is a problem ppl are having across a bunch of versions for more than a year now, if there is a workaround, I wouldn't expect it to be version specific.

**Comment by raoulvdberge** [comment]
Ah, but you're using a structure block in this case?

**Comment by PurpleHel** [comment]
Not initially. The structure block was my failed attempt at a workaround.

Initially I broke the disk drive to move it, and then when I put the disk back in at the new location, it didn't read, exactly as in 821 and 712 and every other post of the problem. So I went to my backup, confirmed the disk still read in the backup, and so used a structure block to save the whole array from the backup. When I restored from the structure block into the current version of the world, the disk drive in the array had no disks in it. So the structure block was not a successful workaround.

**Comment by raoulvdberge** [comment]
> Initially I broke the disk drive to move it, and then when I put the disk back in at the new location, it didn't read, exactly as in 821 and 712 and every other post of the problem.

That is a Forge bug, like I said earlier in those threads. I think they attempted to fix it but it didn't work out maybe?

>  So I went to my backup, confirmed the disk still read (as in my items showed up in the grid) in the backup, and so used a structure block to save the whole array from the backup. When I restored from the structure block into the current version of the world, the disk drive in the array had no disks in it. So the structure block was not a successful workaround.

That makes sense, RS doesn't support structure blocks, since the data of the disk isn't stored in the block itself (offloaded to somewhere else).

Closing because it's a Forge bug.

**Comment by PurpleHel** [comment]
So where's the data offloaded to? Can it be copied from there?

**Comment by raoulvdberge** [comment]
The data is offloaded to a NBT file called refinedstorage_nodes.dat in your world directory.

However, I suggest you to just go to your backup, put the relevant disks in your inventory, close your backup. Then copy your player file from the backup to your actual world. That way, you retain your disks.

**Comment by PurpleHel** [comment]
Ah, I'll give that a shot, thanks!

**Comment by raoulvdberge** [comment]
No problem! If you have any further trouble, let me know.

**Comment by PurpleHel** [comment]
Yup, that did the trick perfectly! Thanks!
