### ISSUE TITLE
Slower Auto Crafting (no, seriously ... come back, its useful!)

### ISSUE THREAD

**Issue by temp1029** [raoulvdberge/refinedstorage#1481]
Not a bug report, more of a general question/feature request.

When requesting more than quantity one of an item to be autocrafted via a Processing Pattern, in some cases it would be beneficial to only craft one at a time, versus just outputting all needed components.  This is mostly useful where the other "machine" doesn't have an internal buffer (i.e. Draconic Evolution fusion crafting or Actually Additions empowering) or the items are dropped into the world (i.e. Botania Terra Steel, Runic Alter, Apothecary).

I saw this functionality referenced in another feature request, here: [https://github.com/raoulvdberge/refinedstorage/issues/1234](https://github.com/raoulvdberge/refinedstorage/issues/1234)  I also saw the response saying this should already exist but after scouring the manual, internet and source code I couldn't figure out how to use it.

So I guess I'm asking, if this does exist how do I utilize it and if it doesn't exist can it be considered?

Thanks for taking the time to read/respond and keep up the great work, this mod is awesome!

**Comment by temp1029** [comment]
So apparently I was somehow I missed the change in 1.4 for Blocking mode, which is exactly what I'm looking for.  Requires 1.11, so doesn't solve my issue for current play-through but nice to know its there for future use.

Sorry to be a pain!

**Comment by raoulvdberge** [comment]
No problem!
