### ISSUE TITLE
Possible issue with Funky Locomotion and RS

### ISSUE THREAD

**Issue by Buggy123** [raoulvdberge/refinedstorage#1484]
#### Issue description:

I recently had a issue with one of my SP worlds having constant, severe lag due to a extremely large refinedstorage_nodes.dat file, even when the dimension it was from was completely unloaded. I _think_ this was because I had a Funky locomotion miner with it's own RS controller and a 9x9 plane of Destructors, which mined a 10000 block long tunnel before I shut it down.

#### Steps to reproduce:

Not certain. Assuming I'm right that it was caused by a Funky Locomotion miner, make a large Funky Locomotion platform of some sort with the controller and other stuff on the platform and have it move for a while.

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12.2
- Forge: 14.23.0.2497
- Refined Storage: 1.5.18

Does this issue occur on a server? [yes/no]

Does it occur while running a server? It doesn't change when I open to lan, but I haven't tried actually running it on a server.

**Comment by Buggy123** [comment]
I forgot to mention, I can post more details, a save, etc if desired. Just let me know, I'm not sure what you need here but I have everything backed up just in case.

**Comment by raoulvdberge** [comment]
RS is incompatible with Funky Locomotion. Official support is coming soon.

**Comment by raoulvdberge** [comment]
#1336
