### ISSUE TITLE
[1.12] client crash on startup

### ISSUE THREAD

**Issue by 5t0rmr1d3r** [raoulvdberge/refinedstorage#1485]
#### Issue description:
client crash's on startup

#### What happens:
yep, the client crash's on startup

#### What you expected to happen:
loading of mod... ;-)

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12
- Forge: 14.21.1.2443
- Refined Storage: 1.5.19

Does this issue occur on a server? [yes/no]
didn't test it, error was on starting client.

#### If a (crash)log is relevant for this issue, link it here:
[crash-2017-10-09_08.57.29-client.txt](https://github.com/raoulvdberge/refinedstorage/files/1367724/crash-2017-10-09_08.57.29-client.txt)

**Comment by raoulvdberge** [comment]
Update your Forge. I should probably set a minimum version.

**Comment by 5t0rmr1d3r** [comment]
okay, but sorry for asking.
am i blind or isn't the 14.21.1.2443 the latest for 1.12.0?
[forge 1.12](https://files.minecraftforge.net/maven/net/minecraftforge/forge/index_1.12.html)
is there a way to use later forge versions on 1.12.0? (1.12.2 - 14.23.0.2512 for example)

**Comment by raoulvdberge** [comment]
Oh, indeed, it seems like I broke 1.12.0 compatibility... I will push a new version that brings back compatibility with 1.12.0 later today.

**Comment by raoulvdberge** [comment]
Fixed in RS 1.5.20

**Comment by 5t0rmr1d3r** [comment]
thanks a lot!
