### ISSUE TITLE
Pattern Grid cant register patterns through JEI

### ISSUE THREAD

**Issue by Wyn-Price** [raoulvdberge/refinedstorage#1486]
#### Issue description:
Pattern grid isn't registering any patterns through JEI.
 
#### What happens:
The Pattern Grid dosn't let the player make a pattern through JEI. There isnt an item appearing in the output slot.

#### What you expected to happen:
The output slot to contain the JEI output and the pattern to be able to process

#### Steps to reproduce:
1. Install JEI and create a normal station (creative controller and pattern grid)
2. Try and make a pattern using the JEI autofill feature
[Link To Video](http://www.wynprice.com/minecraft/rs-jei-error.mp4)

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12.1
- Forge: 14.22.0.2469
- JEI version: 4.8.0.105
- Refined Storage: 1.5.20

Does this issue occur on a server? [yes/no]
Yes, as well as on client

**Comment by raoulvdberge** [comment]
You have to tick the "processing" box, since a Solderer recipe isn't a regular crafting recipe.
