### ISSUE TITLE
Disk Drive and Disk Manipulator 

### ISSUE THREAD

**Issue by Dietz8** [raoulvdberge/refinedstorage#1487]
#### Steps to reproduce:
1. Get Disk Drive and Disk Manipulator block and place them.
2. Surround the mentioned block with others
3.*Proof* they turn almost completely black to the point you can not see if they're powered or not.
![2017-10-12_11 49 53](https://user-images.githubusercontent.com/27781167/31506356-325958ac-af45-11e7-8534-6aa36fc54ab2.png)
![2017-10-12_12 01 33](https://user-images.githubusercontent.com/27781167/31506357-32823538-af45-11e7-9589-89207c85a4d8.png)
![2017-10-12_12 01 49](https://user-images.githubusercontent.com/27781167/31506358-32a5bda0-af45-11e7-8816-57f91bc83a41.png)
![2017-10-12_12 02 02](https://user-images.githubusercontent.com/27781167/31506359-32c77a3a-af45-11e7-8666-e67e44a55798.png)
![2017-10-12_12 02 07](https://user-images.githubusercontent.com/27781167/31506361-32e48eae-af45-11e7-9889-099f0da4a16e.png)

...

#### Version (make sure you are on the latest version before reporting):

- Minecraft:
- Forge:
- Refined Storage:

Does this issue occur on a server? [yes/no]

#### If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here]

**Comment by raoulvdberge** [comment]
#970
