### ISSUE TITLE
On server restart, controllers appear to be powered off.

### ISSUE THREAD

**Issue by marx1** [raoulvdberge/refinedstorage#1488]
#### Steps to reproduce:
1. Place controller in a chunk that is not normally loaded on start up.
2. Resart server.
3. Re-join server and controller is off.

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge: 8.0.99.99
- Refined Storage: 1.2.26

Does this issue occur on a server? YES

Issues is similar to issue #370  that has been fixed, but not back ported to 1.10.2 This issue makes any 1.10.2 pack with Refined storage problematic forcing server owners to give/sell chunk loaders from other mods. As issue #370  was locked to comments, and not fixed in this version a new issue was created.

**Comment by marx1** [comment]
So I guess you're not going to fix it?

**Comment by Tahakk** [comment]
1.10.2 is no supported anymore, so no
