### ISSUE TITLE
Referencing Disk Drives not showing content in grid after moving

### ISSUE THREAD

**Issue by kulflame** [raoulvdberge/refinedstorage#1489]
#### Steps to reproduce:
1. Put items into a disk,
2.  Breakdown RS system and rebuild
3. **NOTE** The way I could reproduce this issue was to switch in and out of creative...  hold the disks in your inventory, type /gamemode 1 then /gamemode 0, put the disks back into the drive and the grid will show nothing.

...

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12
- Forge: 2512
- Refined Storage: 1.5.20

Does this issue occur on a server? [yes/no] YES

#### If a (crash)log is relevant for this issue, link it here: N/A

[pastebin/gist/etc link here] N/A

**Comment by raoulvdberge** [comment]
This might be a Forge bug.

**Comment by ToolB0xx** [comment]
I did the exact same thing. I also went into creative and held the disks in my inventory, I think that is what corrupted them, as it's the only thing that seems to stay the same when looking across the issues that are still occurring.

**Comment by raoulvdberge** [comment]
Why do you guys go into creative?

**Comment by kulflame** [comment]
If you run a server with multiple players, there’s going to be times when you need to switch to creative. 


Sent from Yahoo Mail for iPhone


On Thursday, November 2, 2017, 3:29 AM, Raoul <notifications@github.com> wrote:


Why do you guys go into creative?

**Comment by raoulvdberge** [comment]
This is a Forge issue.

See https://github.com/MinecraftForge/MinecraftForge/pull/4594

Also https://github.com/MinecraftForge/MinecraftForge/issues/4580
