### ISSUE TITLE
some items not going into crafting grid when shift clicking with JEI

### ISSUE THREAD

**Issue by bdudek** [raoulvdberge/refinedstorage#149]
this has been mainly from EnderIO but when i shift click a recipe from JEI int to crafting Grid the system never seams to pull the crystal type Items from the storage. i cant even seem to pull the pulsating crystals from the system aswell.

Currently Useing RS 0.8.1
forge: 12.18.0.2005
MC 1.10.2

**Comment by raoulvdberge** [comment]
Duplicate of #147
