### ISSUE TITLE
[1.12.2 - v1.5.18] Server crash on startup possible interaction w/Thermal suite

### ISSUE THREAD

**Issue by VallenFrostweaver** [raoulvdberge/refinedstorage#1490]
#### Issue description:
Server crashing on startup
#### What happens:
Server crashes on startup
#### What you expected to happen:
Server to start without crashing >.>
#### Steps to reproduce:
Unsure. Crash report is all I have to go on as this is a server. I asked players to log out for a reboot so I could check entity count and loaded chunks after a reboot then it crashed out.

#### Version (make sure you are on the latest version before reporting):
- Minecraft: 1.12.2
- Forge: 14.23.0.2491
- Refined Storage: 1.5.18
- Modpack: Radon 1.3.0
Related Mods in Crash report:
- Thermal Dynamics 1.12.2 - 3.5.12
- Thermal Foundation 1.12.2 - 2.3.5.14
- Thermal Expansion 1.12 - 5.3.5.19

Does this issue occur on a server? [yes]

#### If a (crash)log is relevant for this issue, link it here:
https://pastebin.com/k52h48nH

EDIT: Removing the blocks being ticked resulted using NBT Editor results in another crash and more +1 more block effected and 1 less: https://pastebin.com/8r96F0qG

EDIT Update: Removing these blocks lead to world corruption and many blocks being exchanged for others. Had to revert to previous backup.

**Comment by VallenFrostweaver** [comment]
Thank you!

**Comment by raoulvdberge** [comment]
No problem!
