### ISSUE TITLE
On server restart, controllers appear to be powered off.

### ISSUE THREAD

**Issue by marx1** [raoulvdberge/refinedstorage#1491]
Issue description: On server restart, controllers appear to be powered off.

What happens: When the server restarts, and the chunk is not loaded on start, the controller will appear to be powered off. Breaking and re-placing the controller fixes it. Also happens with Interfaces.

What you expected to happen: The controller to be powered on.

Steps to reproduce:

Place controller in a chunk that is not normally loaded on start up.
Resart server.
Re-join server and controller is off.
Version (make sure you are on the latest version before reporting):

Minecraft: 1.10.2
Forge: 8.0.99.99
Refined Storage: 1.2.26
Does this issue occur on a server? YES

**Comment by raoulvdberge** [comment]
1.10 is unsupported
