### ISSUE TITLE
Minecraft Controller AutoCraft crashes Server

### ISSUE THREAD

**Issue by nxarmada** [raoulvdberge/refinedstorage#1495]
#### Issue description:
When I place a crafter and add patterns to it, it crashes the server.
Description: Ticking block entity

It only happens with this one Crafter.  Not with any others on the system, it happens ether with Direct interaction or when it attempts a task

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge: 12.18.3.2488
- Refined Storage: 1.2.26

Does this issue occur on a server? [yes/no]

Yes

#### If a (crash)log is relevant for this issue, link it here:

https://pastebin.com/ZPffZ0eq

**Comment by raoulvdberge** [comment]
1 . 1 0 . 2 i s u n s u p p o r t e d
