### ISSUE TITLE
[1.12.x] Fluid Autocrafting

### ISSUE THREAD

**Issue by Odysseius** [raoulvdberge/refinedstorage#1497]
I have come accross a strange issue with autocrafting certain Items that include buckets in the recipe. I am aware that this may be an insulated issue with a specific mod - Thermal Foundation - however, right now, I think it's a Refined Storage issue.

When I try to auto-craft the special TF blends (Signalum, Lumium, Enderium), the process gets stuck on the crafting part with the message "No Machine Found" in the Crafting Monitor. Then, after I remove the pattern from the crafter for a short moment, the crafting instantly finishes and the output can be found in the system.

Crafting Preview (lets me press Start without complaints):
https://i.imgur.com/NxzMaws.png
Crafting Monitor - shows "No Machine Found" for a simple crafting recipe:
https://i.imgur.com/47J13KG.png

- Minecraft: 1.12.2
- Forge: 14.23.0.2512
- Refined Storage: 1.5.20

Issue occurs on a server.

**Comment by raoulvdberge** [comment]
Is the pattern a processing pattern or regular pattern?

**Comment by Odysseius** [comment]
I have tried with both variants, and got the same result.

**Comment by raoulvdberge** [comment]
Are you having a duplicate pattern in one of your crafters?

**Comment by Odysseius** [comment]
Just thoroughly checked through the whole system, and haven't found any duplicates

**Comment by Odysseius** [comment]
I'm not sure if you worked with structures before, but here is a structure file with all the parts needed. Should work with just Refined Stroage and Thermal Foundation installed, however, I don't know how well structures work with mods.
[refinedstorage.zip](https://github.com/raoulvdberge/refinedstorage/files/1399700/refinedstorage.zip)

**Comment by raoulvdberge** [comment]
Refined Storage doesn't support exporting to structure files.

**Comment by Odysseius** [comment]
Ah, I wasn't aware of that. In any case, I reproduced it in a creative world on an insulated system.

**Comment by Odysseius** [comment]
Making new report with detailed issue description - it's a critical issue.

**Comment by Szum123321** [comment]
I had the same issue, but when I disable oredictionary mark in pattern grid, it repairs!
