### ISSUE TITLE
Exporter's Regulator Mode doesn't work with Auto Crafting

### ISSUE THREAD

**Issue by jnyl42** [raoulvdberge/refinedstorage#1498]
#### Issue description:
I am trying to keep a chest stocked with one of each of some auto-craftable items using an Exporter with Regulator Mode

#### What happens:
-If I set Regulator Mode to Yes and Craft-only Mode to No, it will export the correct quantity of items to the chest, but it will not craft a new item if none are left in RS inventory
-If I set Regulator Mode to Yes and Craft-only Mode to Yes, it will craft and export the desired items, but it ignores Regulator Mode quantity limits and keeps crafting/exporting endlessly

#### What you expected to happen:
I was expecting the exporter to stop crafting after reaching the desired amount of items while in Regulator Mode.  Ideally, the exporter should be able to export the correct number of items, existing ones first, then crafting more to meet the export demand if necessary.

#### Steps to reproduce:
1.  Set an exporter to export an item that can be autocrafted, but none are in your RS inventory
2.  Set Regulator Mode to Yes  (nothing exports)
3.  Set Craft-only Mode to Yes (RS system will craft and export, but will not stop)

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.11.2
- Forge: 1.11.2-13.20.1.2476-universal
- Refined Storage: 1.4.20

Does this issue occur on a server?  Yes

**Comment by raoulvdberge** [comment]
1.11.2 is unsupported!
