### ISSUE TITLE
Item loss when returning from the end

### ISSUE THREAD

**Issue by Trcx528** [raoulvdberge/refinedstorage#150]
Playing on FTB Unstable 4.1.1 (Refined Storage 0.8)

Playing on my server I noticed some strangeness that is somewhat hard to pin point exactly.  For the most part I think I have it narrowed down.  

When returning from the end (or other dimensions) to my base in the overworld, sometimes my crafting grids all have their views changed, they revert to their default view of sorting by name and no JEI integration (vs what I have previously set them to.)  This happens around 50% of the time when returning from another dimension, regardless of method used (nether portal, end portal, rf tools teleporter, etc).  The buttons next to the grid are not functional and do not allow me to change the views.  Even a relog and completely closing/re opening the client wont fix it.  The only option to fix is to break the grids and place them back down.  

When the above behavior happens, items inserted into the grids are only there until I leave (presumably when the chunk reloads).  For example returning from the end I deposited a large number of ender pearls to the RS system.  They are there and I can craft with them, but when I go to the nether and come back (or even just wander far enough away in the overworld, or re-log) the ender pearls and the items crafted from them are no where to be found.  

Breaking the grids and replacing them seem to fix this issue, but it is strange behavior indeed.   I have no clue what could cause it as it seems to be somewhat intermittent.

**Comment by Trcx528** [comment]
Tonight when this occurred while returning from the nether.  Once I saw the grids had reverted to their default views I cleanly restarted the server and my client and the issue was fixed, pointing to this being a bug on the server half.  Hopefully this helps narrow it down.

**Comment by bgarrison25** [comment]
I'm having exactly the same issue (see the referenced issue above). I'm glad you narrowed it down so much more than me. At least I can use my stuff by breaking and replacing the block. Sounds like a block update isn't happening. maybe if I place something down that forces a block update on the crafting grid every minute? :)

**Comment by raoulvdberge** [comment]
This issue will be most likely fixed in the next version, as I've written a new machine network algorithm

**Comment by bgarrison25** [comment]
Awesome. I am looking forward to it :D. BTW is there a place where we can see your most recent builds?

**Comment by raoulvdberge** [comment]
Not really,  I don't like to do that because the dev branch can be very buggy and there are times where broken stuff is committed. You can always build yourself if you want.

**Comment by APolarBaer** [comment]
This issue seems to be plaguing storage network too or at least the loss of items lol, glad to hear you believe you fixed it though, I'll have to add this to my testing pack and try it out

**Comment by raoulvdberge** [comment]
The loss of items is probably a desync issue requiring a world reload the see the items again, so no real loss should occur.

**Comment by APolarBaer** [comment]
It wasn't temporary though with storage network at least even after I restarted the server I was missing about half the stuff I stored in it but it's okay

**Comment by raoulvdberge** [comment]
Weird, we'll see if it's fixed in the next version

**Comment by APolarBaer** [comment]
It's not in your mod I was referring to storage network so no worries here, I'm just going to try out your mod when that release comes out

**Comment by bgarrison25** [comment]
@raoulvdberge not 100% sure how to build mods from source just yet....any cool tips or links to show me how ;)

**Comment by Trcx528** [comment]
Assuming RS follows a traditional mod setup and if my memory serves correctly, it should go something as follows: 
```
git clone https://github.com/raoulvdberge/refinedstorage.git
cd refinedstorage
./gradlew build

```
The resulting jar should appear in the build/libs directory.

**Comment by raoulvdberge** [comment]
^ Assuming you  have git, gradle and java installed

**Comment by raoulvdberge** [comment]
Here, I did a build for you. Keep in it mind that it is buggy, and make a back up!

Let me know if you still have the issue (rename .zip to .jar)
[refinedstorage-0.8.6.zip](https://github.com/raoulvdberge/refinedstorage/files/352778/refinedstorage-0.8.6.zip)

**Comment by bgarrison25** [comment]
i have git and java installed....ill look into installing gradle. Thanks for the build @raoulvdberge I will put it up on my server tonight and test it out.

**Comment by raoulvdberge** [comment]
Is the issue still present in 0.8.6?
