### ISSUE TITLE
[1.12.x] Critical Autocrafting Duplicating Bug

### ISSUE THREAD

**Issue by Odysseius** [raoulvdberge/refinedstorage#1500]
This relates to https://github.com/raoulvdberge/refinedstorage/issues/1497

It's hard to explain, but there is currently a "duplication" bug involving autocrafting with any fluids (bucket of fluid in pattern recipe). Every time you request an item that requires any type of fluid crafting, it gets stuck at "No Machine Found". However, when you remove the Pattern from the Crafter, and then put it back in, the crafting is continuing. The big issue is that, after replacing the pattern, it does not check for validity of the crafting recipe, making you able to essentially do "Dirt (and a fluid) to Diamonds" recipes, or - in my example video - just randomly make Nether Stars appear.

What seems to happen is that is completely ignores the recipe, or the machine it is pointing to (also tested it with autocrafting fluxducts in a Fluid Transposer, and it didn't input the items into the Transposer, but just "magically" finished the crafting, not checking the validity of the recipe.

This is a clip of this problem:
https://clips.twitch.tv/BoxySmellyThymeGOWSkull

- Minecraft: 1.12.2
- Forge: 14.23.0.2512
- Refined Storage: 1.5.20

Issue occurs on a server, but also has been tested in Singleplayer.

**Comment by Odysseius** [comment]
I assume this should not be shouted out publicly?

**Comment by raoulvdberge** [comment]
It's just Minecraft, so it's not that big of a deal if people know about it but I'll try looking for a fix (not this weekend since I'm not home).

Cc @way2muchnoise - could you help with this one?

**Comment by SnowShock35** [comment]
@raoulvdberge A quick work around would probably be to check if the pattern was removed from the crafter and if so void the entire crafting operation. Whether that's possible or not I'm not sure. Thanks for looking into this issue Raoul. 🙂

**Comment by Odysseius** [comment]
Quick Update: It does also happen with non-fluid recipes.
