### ISSUE TITLE
[1.12.2] Server crash on autocrafting attemp

### ISSUE THREAD

**Issue by 5t0rmr1d3r** [raoulvdberge/refinedstorage#1501]
#### Issue description:
user tried to autocraft a recipe whitch worked in former version.

#### What you expected to happen:
craftin of recipe (it was an easy draconic evolution core)

- Minecraft: 1.12.2
- Forge: 1.12.2-14.23.0.2512
- Refined Storage: 1.5.21

Does this issue occur on a server? [yes/no]
yep, server

#### If a (crash)log is relevant for this issue, link it here:
[crash-2017-10-22_18.12.15-server.txt](https://github.com/raoulvdberge/refinedstorage/files/1405082/crash-2017-10-22_18.12.15-server.txt)

**Comment by mrdeadlocked** [comment]
We are having server crashes on auto crafting as well. The crash-2017-11-01_09.55.21-server.txt was an attempt to craft 10 crafters.
[crash-2017-10-31_16.27.38-server.txt](https://github.com/raoulvdberge/refinedstorage/files/1434466/crash-2017-10-31_16.27.38-server.txt)
[crash-2017-10-31_16.37.20-server.txt](https://github.com/raoulvdberge/refinedstorage/files/1434467/crash-2017-10-31_16.37.20-server.txt)
[crash-2017-11-01_09.55.21-server.txt](https://github.com/raoulvdberge/refinedstorage/files/1434468/crash-2017-11-01_09.55.21-server.txt)

**Comment by MrManNo1** [comment]
Not sure if it is related to this issue (seems like it might be?), but I've recently started having autocrafting lock up my client (SSP), and when I restart, it hasn't autocrafted. Then I'll go into my system and try to remove items that were involved in the autocraft, and some random item will completely crash the game. Neither gives me a crash report. When I then go back into the game, the offending item will be completely gone from my system. I've had it affect both modded items and vanilla items.

It appears as though it only effects items saved in the disk drives, not things attached to external storage, but that could obviously just be a coincidence.
