### ISSUE TITLE
Autocrafting with Pam's Presser improper functionality

### ISSUE THREAD

**Issue by AndrewR73** [raoulvdberge/refinedstorage#1502]
#### Issue description: Autocrafting w/ Pam's Presser improper functionality
[https://prnt.sc/h1223v](url)

#### Steps to reproduce:
1. Place a Crafter and Presser into an RS system (importer on the bottom of the Presser set to Items)
2. Create a Pattern for Silken Tofu from the Pattern Encoder and place into the Crafter
3. From a Crafting Grid, request more than one Silken Tofu (10, 20, a stack, etc.)
...

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge: forge-12.18.3.2488
- Refined Storage: 1.2.26

Does this issue occur on a server? No

#### If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here]

**Comment by raoulvdberge** [comment]
1.10.2 is unsupported
