### ISSUE TITLE
Interdimensional network card always shows "Dimension 1"

### ISSUE THREAD

**Issue by viveleroi** [raoulvdberge/refinedstorage#1503]
#### Issue description:

I've setup an interdimensional network from my overworld base to The End. I've followed the correct steps, yet the network transmitter always shows "Dimension 1".

#### What happens:

The network transmitter always shows "Dimension 1", the remote receiver doesn't light up, the power consumption of my system doesn't increase.

#### What you expected to happen:

The remote receiver should light up, my system should consume 1k extra power for interdimensional use.

#### Steps to reproduce:
1. Place a network transmitter in the overworld, attached to an RS system.
2. Use a chunk-loader to ensure overworld RS system is loaded.
3. Place a network receiver in another dimension. 
4. Use a chunk-loader to ensure receiver is loaded.
5. Right-click it with a new network card.
6. Place the network card and an interdimensional upgrade in the network transmitter.
...

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge: 1.10.2-12.18.3.2422 (SkyFactory 3)
- Refined Storage: 1.2.26

Does this issue occur on a server? yes

**Comment by raoulvdberge** [comment]
I'm not sure if you heard this, but 1.10.2 RS is unsupported.
