### ISSUE TITLE
[1.12.2] [AllTheMods 3] Attempt on covering cables destroyed my base

### ISSUE THREAD

**Issue by MrEvilCookie** [raoulvdberge/refinedstorage#1504]
#### Issue description:
I'm playing on a private server that's running the latest version of AllTheMods (this means that forge and RS is up to date). Some players had bugs with RS, but not that critical.
#### What happens:
When I place a Chisels and bits' bit/chiseled block it freezes the game and later it crashes, block, that had wire in it goes invisible, but you can't place any blocks in that block, IE connectors and relays reset their orientation, IE wires disappear/float, IndustrialWires' control panel resets orientation, and RS system changes every texture to Off state, but still works and doesn't spend energy. After relog/restart/unloading chunk even if I fix stuff it breaks again. Only one chunk is broken.
I found a way to fix invisible blocks, by placing some more bits there, but interesting that only random blocks disappear.
Screenshot: http://prntscr.com/h2ccpl P.S. I know, it looks like clickbait
#### What you expected to happen:
I expected, that I will have a nice wall with no cables visible
#### Steps to reproduce:
1. place an RS cable
2.try to place a bit of any material in that block
3.It crashes

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12.2
- Forge: 14.23.0.2512
- Refined Storage: 1.15.21
- Modpack: 4.3

Does this issue occur on a server? [yes/no]
Yep
#### If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here]
https://gist.github.com/MrEvilCookie/07ccecd8bc3e3f22ff8a69d2ebbe3129

**Comment by MrEvilCookie** [comment]
http://prntscr.com/h2ch6i Also this is how base looks from outside now

**Comment by raoulvdberge** [comment]
This is a MCMultiPart and/or Chisel & Bits issue. Please report it on their tracker.

**Comment by MrEvilCookie** [comment]
thnx
