### ISSUE TITLE
Detector Suggestion: Emit signal when item is being used for autocrafting

### ISSUE THREAD

**Issue by ejektaflex** [raoulvdberge/refinedstorage#1505]
I just had a simple feature request: There is a detector option labelled "Emit signal when item is being autocrafted". I'm currently automating Sulfur crafting with RS by having a detector only pump soul sand out of the network via interface when Sulfur is being crafted. Because sulfur only has a chance of being dropped, this was the best method I could come up with. But now, if I craft something else that requires sulfur, the system blocks because it will only emit a redstone signal when *sulfur* is being autocrafted. It would be great if there was an option so that it would only emit a signal when the item is next in the autocrafting queue.

**Comment by raoulvdberge** [comment]
#1371
