### ISSUE TITLE
Controller depowering when save is first opened

### ISSUE THREAD

**Issue by Toadsmash** [raoulvdberge/refinedstorage#1507]
#### Steps to reproduce:
1. Just open the save and check the controller.

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12.2
- Forge: 14.23.0.2515
- Refined Storage: 1.5.21
- Reproduced in Modern Skyblock 2 installed through Twitch launcher, both versions 2.6.0.2 and 2.6.0.3
- foamfix anarchy edition is installed

Does this issue occur on a server? [yes/no]

This is in SSP.

I attached the save file.  You'd have to open it in Modern Skyblock 2 2.6.0.3 for it to work, though.
[2017-10-25-21-58-06.zip](https://github.com/raoulvdberge/refinedstorage/files/1422915/2017-10-25-21-58-06.zip)

**Comment by raoulvdberge** [comment]
Mekanism issue
