### ISSUE TITLE
[Request] Add some functions to the OC Crafting Pattern driver thing

### ISSUE THREAD

**Issue by BrisingrAerowing** [raoulvdberge/refinedstorage#1508]
#### Issue description:

I am working on an OC / RS autocrafting program that would benefit from being able to determine if a Crafting Pattern is a Processing Pattern or an OreDict pattern (So that it can perform special handling for those), but those values (and some related things like OreDict inputs) aren't exposed in the API.

Is there a reason for them not being exposed? Could they be added?

#### What happens:
 N/A
#### What you expected to happen:
N/A
#### Steps to reproduce:
1. N/A
2.
3.
...

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12.2
- Forge: 14.23.0.2515
- Refined Storage: 1.5.21

Does this issue occur on a server? [yes/no] N/A

#### If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here] N/A

**Comment by raoulvdberge** [comment]
I've added following values to the API:
- oreInputs: oredict inputs
- processing: if it's a processing pattern
- blocking: if it's a blocking pattern
- oredict: if it's an oredict pattern

**Comment by BrisingrAerowing** [comment]
Thanks! Those will work quite well.
