### ISSUE TITLE
Mass Crafting Lag

### ISSUE THREAD

**Issue by Trcx528** [raoulvdberge/refinedstorage#151]
Playing FTB Unstable 4.1.1 (Refined Storage 0.8)
Possibly Related to #122, it is unclear if that ticket refers to autocrafting only or not.  

For example assume the player wants to craft a stack of chests.  In a RS crafting grid you can put 8 stacks of planks arranged in a the right pattern and shift click the result to craft a whole stack instantly.  However if you put your 8 stacks of planks in RS and in the grid only put 1 plank in each slot and shift click the result, the server process seems to come to a halt for several seconds.  The GUI is unresponsive and nothing appears to happen. The client seems to stay alive and does not lock. 

I believe what is happening is for each item in the grid RS is searching the attached storage for matching items and withdrawing one item.  It does this 8 times to complete the pattern, and then continues on to repeat 64 times in order to make a complete stack.  I assume the search for items is expensive and repeating it 512 times (8x64) exacerbates this expense.  

The RS system in my play testing has 3 disk drives each full of 1k storage cells and are about 70% full of various items overall, with around 425 unique items.

**Comment by Trcx528** [comment]
I got the 0.8.5 update today and that seems to fix this issue.  As this issue is still open I'm not sure if the fix was intentional or not....

**Comment by raoulvdberge** [comment]
Completely forgot about this issue. >0.8.4 got massive performance improvements, so yeah, that would indeed cause a fix. :D

**Comment by HugoZink** [comment]
I'm still getting this issue in the latest version.
