### ISSUE TITLE
P2P Tunnels / Colored Networks / AE2-style Interface Terminal

### ISSUE THREAD

**Issue by AnZaNaMa** [raoulvdberge/refinedstorage#1510]
These are a few of the things from Applied Energistics 2 that I haven't seen in RS. I understand it is not the mod's goal to completely emulate AE2, but I'm just curious if these are features that were decisively omitted or if they were just never implemented. 

The ability to access all your crafters from one grid would be amazing (and maybe also to name your crafters to make finding the right one easier). 

I really enjoy the ability to color-code subnetworks that you can also find in AE - or even just to color code a single network. The default interface starts to get bland after a while, so it'd be nice to be able to change it up.

Love the mod! Keep up the great work.

**Comment by raoulvdberge** [comment]
They are decisively omitted
