### ISSUE TITLE
[1.12.2] Casue lag on server!

### ISSUE THREAD

**Issue by yuanjie000** [raoulvdberge/refinedstorage#1511]
#### Issue description:
once using rs to autocraft something, the sever become lag.
used **hundreds of** _crafting pattern_ 

![tps](https://user-images.githubusercontent.com/20902900/32207451-e17e4c98-be36-11e7-8d77-f846f9e08e33.png)

#### Version (make sure you are on the latest version before reporting):
- Minecraft:1.12.2
- Forge:14.23.0.2517
- Refined Storage:refinedstorage-1.5.21

Does this issue occur on a server? [yes/no]
yes
#### If a (crash)log is relevant for this issue, link it here:
here is an nps file of the server
[lowtps.zip](https://github.com/raoulvdberge/refinedstorage/files/1429604/lowtps.zip)

**Comment by 3TUSK** [comment]
![image](https://user-images.githubusercontent.com/9113033/32207703-f90ec184-bdba-11e7-90b3-8bbc92a66866.png)

Sorry for jumping in. I was asked for giving a rough analysis on the profiling report. As you can see, I stunk on these abnormal behaviors:
![image](https://user-images.githubusercontent.com/9113033/32207737-260442f4-bdbb-11e7-9016-3b46046b23c1.png)
![image](https://user-images.githubusercontent.com/9113033/32207742-385be7cc-bdbb-11e7-98ff-e74746a25238.png)
![image](https://user-images.githubusercontent.com/9113033/32207750-43ea29b4-bdbb-11e7-8f10-168bdbcd7824.png)

[`isOreDict` should not be that time-consuming.](https://github.com/raoulvdberge/refinedstorage/blob/mc1.12/src/main/java/com/raoulvdberge/refinedstorage/item/ItemPattern.java#L143) Moreover, searching all previous issues in the issue tracker does not reveal any similar issue(s) in the past. The most-matching issue is #838 which has been duplicated multiple times, but according to the profiling result submitted, it is unlikely to connect #838 to this issue. 
Therefore, this issue shall be considered as a separate issue, as it may point out a new underlying design flaw.

**Comment by raoulvdberge** [comment]
A network is turning off and on, causing the crafting pattern chain to rebuild constantly. Make sure enough power is supplied to the controller. This is not caused by autocrafting.
