### ISSUE TITLE
Modern Sky Block 2 Modpack  2.6.2.1

### ISSUE THREAD

**Issue by Cordovan1011** [raoulvdberge/refinedstorage#1513]
Hi,
 
i dunno if this the right spot for my question but i have a problem in the pack. i demolished my whole base and placed all items into a refined storage system with a quantum disk. in the old base everything was available. now i moved to a new location and no items show up after setting up refined storage again. what can i do about that? the disk still shows 310k+ items but they are not shown in the grid.
 
thanks in advance

**Comment by raoulvdberge** [comment]
#1489
