### ISSUE TITLE
Questions about cable covers.

### ISSUE THREAD

**Issue by calloatti** [raoulvdberge/refinedstorage#1515]
Refined Storage 1.5.21
MC 1.12.2

Is there a way to use cable covers in the latest 1.12.x version?
I used Simple Covers and MC Multipart in MC 1.10, but Simple Covers has not been updated to 1.12.x
I have not been able to find documentation on how to cover cables in 1.12.x

If there is no solution implemented, maybe you would be willing to implement facade blocks in RS? The way [XNet](https://github.com/McJty/XNet) implements them seem simple enough that they could maybe be ported for RS?

**Comment by raoulvdberge** [comment]
> Is there a way to use cable covers in the latest 1.12.x version?
Yes

> I used Simple Covers and MC Multipart in MC 1.10, but Simple Covers has not been updated to 1.12.x
Use Chisel & Bits

> I have not been able to find documentation on how to cover cables in 1.12.x
https://refinedstorage.raoulvdberge.com/wiki/hiding-the-cable-blocks

> If there is no solution implemented, maybe you would be willing to implement facade blocks in RS?
No.

**Comment by calloatti** [comment]
Thank you. I cannot use C&B since my FPS goes from 50 to 4 when I include it. Guess I will wait for simple covers to be updated.
