### ISSUE TITLE
Crafting Grid - Shift Crafting Multiples.

### ISSUE THREAD

**Issue by moneyblind** [raoulvdberge/refinedstorage#1517]
#### Issue description:
When creating LOTS of something. The server lags.

> Can't keep up! Did the system time change, or is the server overloaded? Running xxxx behind. Skipping yyyy tick(s)

The X and Y are proportionate to the number of times that I rapidly click while holding shift.

For instance, if you hold shift and left click on COMPRESSED COBBLESTONE, it should create 64 while pulling extra from the system.

The system is in the MINING WORLD of Aromas 1997 Dimensional mod.

#### What happens:
Server Lag while rapidly SHIFT+Left Clicking to create stacks of items from crafting grid.

#### What you expected to happen:
No lag, similar to rapidly clicking while NOT holding shift to get single items rather than stacks.

#### Steps to reproduce:
1. Setup network including Drive, 64k disks, crafting monitor.
2. Place 1000's of cobble into the machine.
3. Attempt to create stacks and stacks of compressed cobble using the SHIFT+LEFT CLICK method (or any other recipe)

#### Version (make sure you are on the latest version before reporting):

- FTB Beyond - 1.11.0
- Minecraft: 1.10.2
- Forge: 12.18.3.2422
- Refined Storage: 1.2.26

Does this issue occur on a server? Yes

**Comment by raoulvdberge** [comment]
Hey! Did you know that 1.10.2 is unsupported?

**Comment by moneyblind** [comment]
Did not! Thanks!
