### ISSUE TITLE
Smooth Lighting issue with Disk Drives

### ISSUE THREAD

**Issue by ConnorPr** [raoulvdberge/refinedstorage#1518]
#### Steps to reproduce:
1. Place multiple Disk Drives and Disk Manipulators on top of each other with blocks on either side

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12.2
- Forge: 1.12.2-forge1.12.2-14.23.0.2512
- Refined Storage: 1.5.21

**Comment by raoulvdberge** [comment]
#970
