### ISSUE TITLE
Refined/Reborn Storage Lag and Error Message

### ISSUE THREAD

**Issue by jusjudge** [raoulvdberge/refinedstorage#1519]
#### Issue description:
Reborn Storage crafting/Refined Storage crafters
#### What happens:
Since I built the crafter from Reborn, whenever I open into it and exit out,
it constantly makes my world do this whole "**waiting for server**" thing. I use
to come across that a lot but awhile ago and for 1.12.1 but now it happens
when I use that. Even when I use the crafters from Refined, it does the same
exact thing. It also drops my FPS for a bit. Now, at this very moment, when I 
enter my world, it doesn't let do anything at all. All I did was exit the client to
update other mods and forge and it doesn't let me do anything. Everything gets
stuck in place. I even tried pushing the mods and forge back to where I had them
and nothing changed. I also tried using one of the Aroma backups but it takes me
to the same spot every single time as if it's disregarding that I loaded up a back up.
#### What you expected to happen:
I don't understand why I am even getting a "**waiting for server**" message on
my screen because I've never had that until I started playing 1.12.x. Maybe if
someone knows what that's about and can help me I'll appreciate it. Regardless
I would want the crafters to stop making my world lag.
#### Steps to reproduce:
1. Build the crafter from Reborn. Connect it to the controller.
2. Build crafters from refined, also connect them to the controller
   but through the network rec/trans and have them on machines.
3. Try placing patterns in the machines and you'll most likely start
    lagging or get the error I was getting.
...

#### Version (make sure you are on the latest version before reporting):

- Minecraft: **1.12.2**
- Forge: **14.23.0.2529**
- Refined Storage: **1.5.21**
(Maybe it's useful to know but I also have about **200+ mods** loaded/active).
Does this issue occur on a server? [yes/no]
I'm not sure exactly.
#### If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here]

**Comment by raoulvdberge** [comment]
https://refinedstorage.raoulvdberge.com/wiki/profiling

**Comment by jusjudge** [comment]
@raoulvdberge , it doesn't let me type anything in the chat either. I tried starting up a new world and things work fine so I'm sure it isn't because of me updating any of the mods. When I click save and quit, it just goes into the whole "Not Responding" so I have to force close every time.

**Comment by raoulvdberge** [comment]
Then I can't do much. Do you have this issue when Reborn Storage is removed?
