### ISSUE TITLE
Command to give Storage Drives.

### ISSUE THREAD

**Issue by Keaton1188** [raoulvdberge/refinedstorage#1520]
#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12.2
- Forge: 14.23.0.0215
- Refined Storage: refinedstorage-1.5.21.jar

Does this issue occur on a server? [yes/no]

Yes

**Comment by raoulvdberge** [comment]
`/give Player257 refinedstorage:storage_disk 1 1` for a 1k, `/give Player257 refinedstorage:storage_disk 1 2` for a 4k, etc...
