### ISSUE TITLE
[1.12+] Add configuration option to change energy capacity of items

### ISSUE THREAD

**Issue by OneEyeMaker** [raoulvdberge/refinedstorage#1521]
Hello.
Firstly, thank you for your mods.
I've have simple suggestion. It's possible to change energy usage of different items in mod (such as Wireless Grid), but energy capacity value is hardcoded:

https://github.com/raoulvdberge/refinedstorage/blob/mc1.12/src/main/java/com/raoulvdberge/refinedstorage/item/ItemEnergyItem.java#L19

Please, add configuration option to change energy storage of items, which can store/use energy.

/* MC 1.12+ */

**Comment by raoulvdberge** [comment]
True, I've wanted to do this... But I do need to add client <-> server config syncing for that.

**Comment by Saklad5** [comment]
Any progress on this? I’d like to be able to adjust the hard-coded energy storage value of Writers.
