### ISSUE TITLE
[1.12+] Refined Storage, MCMultiPart, and ThermalExpansion covers

### ISSUE THREAD

**Issue by kvgeorge1** [raoulvdberge/refinedstorage#1522]
I am using the latest versions of RefinedStorage, MCMultiPart, and ThermalExpansion.  When I attempt to use a TE cover on the RS cables, it will not attach.  I can use those covers on TE pipes, just not RS cables.  I was under the impression that RS supports MCMultiPart (I am also under the impression that TE uses MCMultiPart) and that something like this should work.

Is this a bug or am I doing this wrong?

**Comment by raoulvdberge** [comment]
> I am also under the impression that TE uses MCMultiPart

You are under the wrong impression, TE doesn't use MCMultiPart for their covers.

**Comment by kvgeorge1** [comment]
Ok, then this explains why it isn't working.  Thank you for clearing this up for me.
