### ISSUE TITLE
Odd problems with RS machines & their state

### ISSUE THREAD

**Issue by SirTwsted** [raoulvdberge/refinedstorage#1524]
#### Issue description:
Whenever I leave the immediate area of RS, they seem to shut off the entire network.
All the machines seem to get this dark color and/or full metal casing.... view picture to see.

#### What happens:
Leaving area or dimension puts the RS machines / system into an off state with a GUI that 
makes the machines fully encapsulated into a metal frame... view picture.

#### What you expected to happen:
I expect the RS system to be self sustaining as a chunkloader for any machines connected to the controller. (its a wish)

#### Steps to reproduce:
1. - Leave immediate area or go into another deminsion
2. - Return to the RS system where the controller and other RS machines are at 
3. - You will notice all machines are turned off & a metal casing is wrapped around them
view picture.
...

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12.2
- Forge: 14.23.0.2529
- Refined Storage: 1.5.21

Does this issue occur on a server? [yes/no]
Not playing on server, - Its single player private.

#### If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here]
This is with the machines on before leaving area or to another dimension.
https://imgur.com/a/JXJKi

This is when I return to the RS system after being away.
IMAGE <<<-----  https://imgur.com/a/cvCuQ

These are showing the machines completely turned off, even though power is running through system.
A - https://imgur.com/a/0BzSF
B - https://imgur.com/a/GDmBO

NOTE:::::::
In order for me to place the machines back into its on state after this happens..
I have to break the controller, and place it back down again.....
Thats when the system will turn completely back on and everything works fine,
So long as I dont leave the area or go to another dimension...  
Its a bit frustrating that every time I come back home, I have to get into  the habit of breaking the controller and placing it back down again to get the system working like it should.
.
PS>> 
I dont know if its my game itself, or the mod, so thats why I am posting here just incase .
also, love your mod  :P
.

**Comment by raoulvdberge** [comment]
Erm, looking at your screenshots, looks like your chunk is corrupted during saving (direction of the blocks is reset). Any logs of when this happens (on leaving / entering chunk)?

**Comment by SirTwsted** [comment]
no so far no logs.... it just happens.... Is there any way of fixing a corrupted chunk?
or is my game just screwed ?  
:/

**Comment by raoulvdberge** [comment]
As long as there are no logs, there is not much I can do. :/
