### ISSUE TITLE
Bug/Feature request: Limit crafters to one pattern per slot

### ISSUE THREAD

**Issue by calloatti** [raoulvdberge/refinedstorage#1527]
#### Issue description:

Limit crafters to one pattern per slot.

#### What happens:

If you have a stack of patterns (they are the same pattern so they stack) if you shift click the stack in the crafter GUI, the whole stack gets added to one crafter slot.

#### What you expected to happen:

Only one of the patterns to be added to a crafter slot.

#### Steps to reproduce:

Create a stack of patterns of the same recipe (This is a common use case, when for example adding a pattern for printed silicon to multiple crafters attached to solderers)

Click a crafter to open its GUI

Shift click the stack of patterns in your inventory to move a pattern to one of the empty crafter slots, the whole stack is moved.

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12.2
- Forge:
- Refined Storage:refinedstorage-1.5.21

Does this issue occur on a server? [yes/no]

N/A

**Comment by raoulvdberge** [comment]
I already implemented this for the next version.

https://github.com/raoulvdberge/refinedstorage/blob/mc1.12/CHANGELOG.md#1522
