### ISSUE TITLE
Multipart crash in cable blockspace

### ISSUE THREAD

**Issue by Guybrush0** [raoulvdberge/refinedstorage#1529]
#### Issue description:
Client Crash when placing multiparts(chisels&bits bits) in same block space as cable, also causes cosmetic visual artifacts after re-loading

#### What you expected to happen:
place chisels and bits bits and not crash

#### Steps to reproduce:
1. place bit in cable space
2. crash
3. profit?
...

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12.2
- Forge: 14.23.0.2531
- Refined Storage: 1.5.21

Does this issue occur on a server? [yes/no]
yes
#### If a (crash)log is relevant for this issue, link it here:

https://pastebin.com/9tE2ieWv
https://i.imgur.com/61CJCkt.png

**Comment by raoulvdberge** [comment]
C&B issue, report it on their tracker
