### ISSUE TITLE
Item filters are lost when breaking exporters

### ISSUE THREAD

**Issue by HappyMealToy** [raoulvdberge/refinedstorage#1531]
#### Issue description:
Item filters do not drop/are destroyed when breaking exporters
#### What happens:
When breaking an exporter with a filter installed, the filter does not drop and is lost.
#### What you expected to happen:
The filter should drop with the broken exporter.
#### Steps to reproduce:
1. Place an item filter in an exporter
2. Break exporter
3.
...

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12.2
- Forge: 1.12.2-14.23.0.2537 (although have had this happen on several older versions as well)
- Refined Storage: 1.5.22 (again have noticed this on older versions as well)

Does this issue occur on a server? [yes/no]
Unsure, single player only.
#### If a (crash)log is relevant for this issue, link it here:
No crash.
[pastebin/gist/etc link here]

**Comment by raoulvdberge** [comment]
That is intended. Item filters aren't meant to be retained when the inventory is broken, even if you can get them out again.
