### ISSUE TITLE
1.12.2: Crafting the crafter does not find a machine

### ISSUE THREAD

**Issue by Knito58** [raoulvdberge/refinedstorage#1532]
#### Issue description:

Using the crafting grid to craft a crafter. Other users may find this issue with an other pattern.

#### What happens:

Using the crafting monitor to follow the process. After all the ingredients are done, there are 3 lines in the monitor:

(symbol of crafter) 1 x Crafter (no mouse hint)
Items processing (no mouse hint)
(symbol of crafter) 1 x Crafter (mouse hint: No machine found)

To finish the process I go to the crafter with the crafter pattern. Left click on the pattern (get it) and again left click on it to immediatly put it back. Now the crafting monitor is empty and the crafter is crafted.

#### What you expected to happen:

Count of crafters increases in the crafting grid and the crafting monitor is empty without the need of grabbing the crafter's pattern and putting it back again.

#### Steps to reproduce:

Not possible.
In other worlds I had the same issue with other recipes/patterns.
But now... "Cannot craft crafter" seems tellworthy to me.
This error persists over many versions of Forge and Refined Storage.

I checked all the patterns if there is a wrong "processing" setting. All needed items become crafted from solderers and crafters as they should.

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12.2
- Forge: 14.23.0.2515
- Refined Storage: 1.5.22

Does this issue occur on a server? [no] SSP normal, no cheats

#### If a (crash)log is relevant for this issue, link it here:

No crash no log.

**Comment by raoulvdberge** [comment]
Sorry, if I cannot reproduce this reliably I cannot do much.

**Comment by Knito58** [comment]
Found a fix:

Setting the "Oredict" option in the pattern made the pattern work. 
How does this fit to "no machine found"?

Doesn't matter. I'm happy it works now.

**Comment by Dafubar** [comment]
Same here for me. I often use on solderer with 2 autocrafter in the beginning. After losing energy for the core and repowering it, the issue very often appears. After that only the fix Knito posted works for me.

**Comment by Knito58** [comment]
Ok power loss happens very often to me when starting RS in a world as I can not use creative energy sources. That would be the same reason for me. Thanks @Dafubar now I know what I need to try to avoid.
