### ISSUE TITLE
[Feature Request] External Storage multiple fluid handling

### ISSUE THREAD

**Issue by Beannsss** [raoulvdberge/refinedstorage#1534]
#### Steps to reproduce: (with Integrated dynamics)
1.  Hook up multiple fluid interfaces to tanks
2. Point an external storage to one of the fluid interfaces on the network
3. 
...

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12.2
- Forge: 14.23.0.2532
- Refined Storage: 1.5.22

Does this issue occur on a server? [yes/no] N/A

#### If a (crash)log is relevant for this issue, link it here: N/A

Again, I feel this could be a really cool and useful feature if it possible/plausible. I'm not sure how different handling items and liquids is. No sweat if this would be implausible. 

Thanks

**Comment by raoulvdberge** [comment]
It would be really, really cool if you'd read previous issues before opening a new one.
#1034

**Comment by Beannsss** [comment]
Ah, that's my fault, I tried searching multiple different keywords and looking for an existing issue. Apparently I'm too tired since it was right in front of my face. I apologize.
