### ISSUE TITLE
Breaking Exporters doesnt drop installed filters

### ISSUE THREAD

**Issue by NosajDraw** [raoulvdberge/refinedstorage#1535]
#### Issue description:
Breaking Exporters doesn't drop installed filters

#### What happens:
No filters drop

#### What you expected to happen:
Filters to drop

#### Steps to reproduce:
1. Place Exporter
2. Insert filter
3. Break Exporter

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12.2
- Forge: 14.23.0.3532
- Refined Storage: 1.15.21

Does this issue occur on a server? [yes/no]
Yes

**Comment by raoulvdberge** [comment]
Read before creating an issue. Literally 3 issues under you: #1531 -.-
