### ISSUE TITLE
[1.12.2] Incorrect patterns crashes

### ISSUE THREAD

**Issue by KingCruzIII** [raoulvdberge/refinedstorage#1537]
#### Issue description:
When auto crafting if a pattern has no input the game will crash when trying to autocraft that item. 
This issue seems to only happy when using the "processing" option.
When this does happy the only solution I found is to delete the controller with mcedit. Otherwise, it will crash when I load the world.

#### What happens:
Example: If I have a crafter facing a solderer with a pattern that inputs nothing and outputs an Printed Advanced Processor. It will show up as being able to be crafted in a grid, but it will crash the game if you actually try to craft it. 
I have also gotten it to crash with a pattern that inputs nothing and outputs 4 pulverized obsidian(facing a pulverizer).

#### What you expected to happen:
Either nothing when it tries to craft it, or it does not show up in the crafting grid.
#### Steps to reproduce:
1. Obtain a pattern with no input.
2. Insert into Crafter
3. Autocraft item
4. Crash
...

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12
- Forge: 14.23.0.2531
- Refined Storage: 1.5.23

Does this issue occur on a server? [yes/no]

Not sure. Running in Single Player 

#### If a (crash)log is relevant for this issue, link it here:

https://pastebin.com/sTyGSgG6

**Comment by raoulvdberge** [comment]
How did you create a pattern with no inputs?

**Comment by KingCruzIII** [comment]
Actually messing around with it I see that it won't let you just make one with no input. I'm not sure how I ended up with patterns with missing input. I made a storage disk autocraft setup and when I went to craft a 64k disk my game crashed. When I went poking around I found the advanced processor pattern with no inputs. I don't know how i got it but i know it crashes the game if it's in a crafter and you try to craft it. 
![missing input](https://user-images.githubusercontent.com/18471324/32798913-bc8d9758-c93b-11e7-9324-039956b39ab5.png)

**Comment by raoulvdberge** [comment]
That is so weird. The Pattern Grid doesn't allow creation of patterns without input.

**Comment by KingCruzIII** [comment]
I'm pretty sure I used the the advanced processor in an autocraft before, and then later on it lost its inputs. I really don't know. I would suggest maybe checking to make sure it has inputs when you try to autocraft something. If it doesn't just turn it into an invalid pattern.

**Comment by raoulvdberge** [comment]
The pattern says its an oredicted pattern; did you use another diamond for the advanced processor than the Minecraft one?

**Comment by KingCruzIII** [comment]
No I used a minecraft one. I just usually have it checked.

**Comment by raoulvdberge** [comment]
Weird, I'll add a check for the inputs.
