### ISSUE TITLE
Refined Storage Pattern Grid Block EATS Disks & Patterns

### ISSUE THREAD

**Issue by SirTwsted** [raoulvdberge/refinedstorage#1538]
**#### Issue description:**
Refined Storage Pattern Grid Block EATS Disks & Patterns
**#### What happens:**
Placing a pattern disk of any kind with a disk, pattern or empty pattern
will be consumed by Refined Storage Pattern Grid when directly dropping the disks or patterns within the pattern grid inventory.
I created a storage disk and when I directly took the disk and dropped it within the Pattern Grid block inventory 
It eats it and did not inventory the pattern for use within the system.
I checked Reborn Storage to see if Refined Storage took the disk and it did not.
I also checked Refined Storage system itself, and its not there either.

**#### What you expected to happen:**
When I drop a pattern or disk into the Pattern Grid block inventory, It should automatically be inventoried within Refined Storage System for automated crafting use. And / or
If someone has Reborn Storage mod Installed, dropping a pattern or disk in the Refined Storage Pattern Grid
should let Reborn Storage inventory the pattern or disk within the Reborn Storage housing for use in automated crafting.

**#### Steps to reproduce:**
1. - Open Refined Storage Pattern Grid GUI
2. - Take a Pattern or Disk and directly drop it in the inventory of the Pattern Grid system
3. - Refined Storage will consume the Pattern or disk and it will not inventory the item for crafting.
...

**#### Version (make sure you are on the latest version before reporting):**

- Minecraft: 1.12.2
- Forge: Forge v14.23.0.2529
- Refined Storage: 1.5.23
- Reborn Storage: 2.1.1.16
- Reborn Core: 3.4.12.155
- Tech Reborn: 2.9.0.349

**Does this issue occur on a server? [yes/no]**
Dont Know - Im On A Private Single Player
**#### If a (crash)log is relevant for this issue, link it here:**

**[pastebin/gist/etc link here]**

**Comment by raoulvdberge** [comment]
Can you create a gif or video of this happening?
