### ISSUE TITLE
Auto-fill recipes with plankWood is not working

### ISSUE THREAD

**Issue by roboderpy** [raoulvdberge/refinedstorage#1541]
#### Issue description:
Auto-fill recipes with plankWood is not working either for crafting grid, ~~and crafters are 🤔 there is no wood in system if attempt to craft a recipe with `is oredict` enabled and there is `plankWood` in recipe~~ ![ugh](https://i.dbot.serealia.ca/2017/11/bc56f4d2b4_javaw_2017-11-23_20-42-24.png)

#### What happens:
https://i.dbot.serealia.ca/2017/11/7bdcb36ec8_%25pn_-2017-11-20_07-19-08.webm

#### What you expected to happen:
Auti-refill works in crafting grid and crafters craft stuff

#### Steps to reproduce:
watch video

#### Version:

- Minecraft: 1.12.2
- Forge: almost latest build (2538)
- Refined Storage: 1.5.22

Does this issue occur on a server? yes

**Comment by raoulvdberge** [comment]
There is a limit on how much "oredicted" wood RS can send over the network for oredicted recipes (to avoid overflowing the network packet). Unfortunately, on larger packs this limit is easier to reach.
