### ISSUE TITLE
Inventory Tweaks sorts one’s inventory grids and crafting grids

### ISSUE THREAD

**Issue by PapiDimmi** [raoulvdberge/refinedstorage#1542]
When you press middle click in a grid or crafting grid to get an item, your inventory gets sorted.

****

**Minecraft version**: 1.12.2
**Forge version**: 14.23.0.2531
**Refined Storage version**: 1.5.23
**Inventory Tweaks version**: 1.63

**Comment by raoulvdberge** [comment]
Could this be an InventoryTweaks bug? Can you also file this on their issue tracker?

**Comment by raoulvdberge** [comment]
I'm assuming this is an InventoryTweaks bug.

**Comment by PapiDimmi** [comment]
@Kobata still hasn’t replied. 😕
