### ISSUE TITLE
1.12.2 Clicking on crafting monitor  crashes

### ISSUE THREAD

**Issue by ntn6371** [raoulvdberge/refinedstorage#1543]
It's really frustrating. If I click on the craft monitor and click on the crafting grid and click on a item and try to get item out it just crashes.  But if I click a recipe it is fine, and I don't have any crafting recipes going on....

---- Minecraft Crash Report ----

WARNING: coremods are present:
  Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  IELoadingPlugin (ImmersiveEngineering-0.12-74-core.jar)
  AppleCore (AppleCore-mc1.12.2-2.2.2.jar)
  HammerCoreCore (HammerCore-1.12.2-1.9.5.3.jar)
  SFRCore (SolarFluxReborn_1.12.2-3.42r.jar)
  LoadingPlugin (RandomThings-MC1.12.2-4.0.8.jar)
  CTMCorePlugin (CTM-MC1.12-0.2.3.9.jar)
  Plugin (NotEnoughIDs-1.5.4.2.jar)
Contact their authors BEFORE contacting forge

// Hey, that tickles! Hehehe!

Time: 11/20/17 6:29 PM
Description: Rendering Block Entity

java.lang.IllegalArgumentException: Cannot get property PropertyDirection{name=facing, clazz=class net.minecraft.util.EnumFacing, values=[north, south, west, east]} as it does not exist in BlockStateContainer{block=minecraft:air, properties=[]}
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_177229_b(BlockStateContainer.java:209)
	at com.arclighttw.tinyreactors.client.render.RenderTileEntityReactorEnergyPort.render(RenderTileEntityReactorEnergyPort.java:35)
	at com.arclighttw.tinyreactors.client.render.RenderTileEntityReactorEnergyPort.func_192841_a(RenderTileEntityReactorEnergyPort.java:23)
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_192854_a(TileEntityRendererDispatcher.java:180)
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_180546_a(TileEntityRendererDispatcher.java:148)
	at net.minecraft.client.renderer.RenderGlobal.func_180446_a(RenderGlobal.java:1001)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1781)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1606)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1377)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1117)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_177229_b(BlockStateContainer.java:209)
	at com.arclighttw.tinyreactors.client.render.RenderTileEntityReactorEnergyPort.render(RenderTileEntityReactorEnergyPort.java:35)
	at com.arclighttw.tinyreactors.client.render.RenderTileEntityReactorEnergyPort.func_192841_a(RenderTileEntityReactorEnergyPort.java:23)

-- Block Entity Details --
Details:
	Name: tinyreactors:reactor_energy_port // com.arclighttw.tinyreactors.tiles.TileEntityReactorEnergyPort
	Block type: ID #2029 (tile.reactor_energy_port // com.arclighttw.tinyreactors.blocks.BlockReactorEnergyPort)
	Block data value: 0 / 0x0 / 0b0000
	Block location: World: (-1003,69,972), Chunk: (at 5,4,12 in -63,60; contains blocks -1008,0,960 to -993,255,975), Region: (-2,1; contains chunks -64,32 to -33,63, blocks -1024,0,512 to -513,255,1023)
	Actual block type: ID #0 (tile.air // net.minecraft.block.BlockAir)
	Actual block data value: 0 / 0x0 / 0b0000
Stacktrace:
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_192854_a(TileEntityRendererDispatcher.java:180)
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_180546_a(TileEntityRendererDispatcher.java:148)
	at net.minecraft.client.renderer.RenderGlobal.func_180446_a(RenderGlobal.java:1001)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1781)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1606)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['Tohno'/28, l='MpServer', x=-1002.60, y=68.00, z=974.36]]
	Chunk stats: MultiplayerChunkCache: 624, 624
	Level seed: 0
	Level generator: ID 07 - voidworld, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (0,88,0), Chunk: (at 0,5,0 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 4171234 game time, 1834038 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 21 total; [EntityCow['Cow'/32, l='MpServer', x=-950.26, y=86.00, z=991.28], EntitySheep['Sheep'/33, l='MpServer', x=-946.48, y=86.00, z=991.79], EntityItem['item.item.egg'/34, l='MpServer', x=-952.57, y=86.00, z=990.79], EntitySheep['Sheep'/35, l='MpServer', x=-949.30, y=86.00, z=1002.17], EntityChickensChicken['Log Chicken'/36, l='MpServer', x=-953.11, y=86.00, z=996.61], EntitySheep['Sheep'/37, l='MpServer', x=-949.37, y=86.00, z=996.68], EntitySheep['Sheep'/38, l='MpServer', x=-951.00, y=86.00, z=994.58], EntityPig['Pig'/39, l='MpServer', x=-949.43, y=86.00, z=1004.29], EntitySheep['Sheep'/40, l='MpServer', x=-953.30, y=86.00, z=1002.77], EntityChicken['Chicken'/41, l='MpServer', x=-955.50, y=86.00, z=997.50], EntityChicken['Chicken'/42, l='MpServer', x=-945.78, y=86.00, z=995.41], EntityPig['Pig'/43, l='MpServer', x=-949.23, y=86.00, z=995.36], EntityItem['item.tile.log.oak'/44, l='MpServer', x=-952.89, y=86.00, z=996.15], EntityItem['item.tile.reactor_energy_port'/1356, l='MpServer', x=-1003.00, y=69.16, z=971.95], EntityFancyItemFrame['Fancy Item Frame'/24, l='MpServer', x=-1009.97, y=86.50, z=1002.50], EntityFancyItemFrame['Fancy Item Frame'/25, l='MpServer', x=-1009.97, y=87.50, z=1002.50], EntityFancyItemFrame['Fancy Item Frame'/26, l='MpServer', x=-1009.97, y=88.50, z=1002.50], EntityFancyItemFrame['Fancy Item Frame'/27, l='MpServer', x=-1009.97, y=89.50, z=1002.50], EntityPlayerSP['Tohno'/28, l='MpServer', x=-1002.60, y=68.00, z=974.36], EntityChicken['Chicken'/30, l='MpServer', x=-953.50, y=86.00, z=990.50], EntityChicken['Chicken'/31, l='MpServer', x=-945.83, y=86.00, z=990.45]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:532)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2748)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:418)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 2655299160 bytes (2532 MB) / 7298088960 bytes (6960 MB) up to 7516192768 bytes (7168 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx7G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=16M
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP 9.42 Powered by Forge 14.23.0.2520 Optifine OptiFine_1.12.2_HD_U_C6 97 mods loaded, 96 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State     | ID                             | Version                  | Source                                          | Signature                                |
	|:--------- |:------------------------------ |:------------------------ |:----------------------------------------------- |:---------------------------------------- |
	| UCHIJAAAA | minecraft                      | 1.12.2                   | minecraft.jar                                   | None                                     |
	| UCHIJAAAA | mcp                            | 9.42                     | minecraft.jar                                   | None                                     |
	| UCHIJAAAA | FML                            | 8.0.99.99                | forge-1.12.2-14.23.0.2520.jar                   | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | forge                          | 14.23.0.2520             | forge-1.12.2-14.23.0.2520.jar                   | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | mercurius_updater              | 1.0                      | MercuriusUpdater-1.12.2.jar                     | None                                     |
	| UCHIJAAAA | actuallyadditions              | 1.12.1-r122              | ActuallyAdditions-1.12.1-r122.jar               | None                                     |
	| UCHIJAAAA | applecore                      | 2.2.2                    | AppleCore-mc1.12.2-2.2.2.jar                    | None                                     |
	| UCHIJAAAA | architecturecraft              | @VERSION@                | architecturecraft-1.12-1.20.jar                 | None                                     |
	| UCHIJAAAA | autoreglib                     | 1.3-14                   | AutoRegLib-1.3-14.jar                           | None                                     |
	| UCHIJAAAA | autoverse                      | 1.1.0                    | autoverse-1.12.2-1.1.0.jar                      | 2b03e1423915a189b8094816baa18f239d576dff |
	| UCHIJAAAA | baubles                        | 1.5.1                    | Baubles-1.12-1.5.1.jar                          | None                                     |
	| UCHIJAAAA | betterbuilderswands            | 0.11.1                   | BetterBuildersWands-1.12-0.11.1.245+69d0d70.jar | None                                     |
	| UCHIJAAAA | bibliotheca                    | 1.1.0-1.12.2             | bibliotheca-1.1.0-1.12.2.jar                    | None                                     |
	| UCHIJAAAA | bookshelf                      | 2.2.479                  | Bookshelf-1.12.2-2.2.479.jar                    | d476d1b22b218a10d845928d1665d45fce301b27 |
	| UCHIJAAAA | codechickenlib                 | 3.1.3.313                | CodeChickenLib-1.12-3.1.3.313-universal.jar     | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCHIJAAAA | redstoneflux                   | 2.0.1                    | RedstoneFlux-1.12-2.0.1.2-universal.jar         | d4f1503fbacd9b9fb767720420c5395104239ec9 |
	| UCHIJAAAA | brandonscore                   | 2.3.3                    | BrandonsCore-1.12-2.3.3.132-universal.jar       | None                                     |
	| UCHIJAAAA | cd4017be_lib                   | 6.0.2                    | CD4017BE_lib-1.12.2-6.0.2.jar                   | None                                     |
	| UCHIJAAAA | chameleon                      | 1.12-4.1.3               | Chameleon-1.12-4.1.3.jar                        | None                                     |
	| UCHIJAAAA | chickens                       | 6.0.2                    | chickens-6.0.2.jar                              | None                                     |
	| UCHIJAAAA | ctm                            | MC1.12-0.2.3.9           | CTM-MC1.12-0.2.3.9.jar                          | None                                     |
	| UCHIJAAAA | chisel                         | MC1.12-0.0.14.18         | Chisel-MC1.12-0.0.14.18.jar                     | None                                     |
	| UCHIJAAAA | chiselsandbits                 | 14.9                     | chiselsandbits-14.9.jar                         | None                                     |
	| UCHIJAAAA | cofhcore                       | 4.3.6                    | CoFHCore-1.12-4.3.6.14-universal.jar            | None                                     |
	| UCHIJAAAA | cofhworld                      | 1.0.1                    | CoFHWorld-1.12-1.0.1.8-universal.jar            | None                                     |
	| UCHIJAAAA | corail_pillar_extension_chisel | 4.0.0                    | corail_pillar_extension_chisel-4.0.0-1.12.jar   | None                                     |
	| UCHIJAAAA | crafttweaker                   | 4.0.9                    | CraftTweaker2-1.12-4.0.9.jar                    | None                                     |
	| UCHIJAAAA | ctgui                          | 1.0.0                    | CraftTweaker2-1.12-4.0.9.jar                    | None                                     |
	| UCHIJAAAA | jei                            | 4.8.0.110                | jei_1.12.2-4.8.0.110.jar                        | None                                     |
	| UCHIJAAAA | crafttweakerjei                | 2.0.0                    | CraftTweaker2-1.12-4.0.9.jar                    | None                                     |
	| UCHIJAAAA | cucumber                       | 1.0.2                    | cucumber[1.12]-1.0.2.jar                        | None                                     |
	| UCHIJAAAA | cultivatedtech                 | 17w47-A-1.12.2           | Cultivated Tech-17w47-A-1.12.2.jar              | None                                     |
	| UCHIJAAAA | cyclicmagic                    | 1.9.13                   | Cyclic-1.12.2-1.9.13.jar                        | None                                     |
	| UCHIJAAAA | waila                          | 1.8.21                   | Hwyla-1.8.21-B36_1.12.jar                       | None                                     |
	| UCHIJAAAA | darkutils                      | 1.7.176                  | DarkUtils-1.12.2-1.7.176.jar                    | d476d1b22b218a10d845928d1665d45fce301b27 |
	| UCHIJAAAA | ptrmodellib                    | 1.0.0                    | Decocraft-2.5.2_1.12.2.jar                      | None                                     |
	| UCHIJAAAA | props                          | 2.5.2                    | Decocraft-2.5.2_1.12.2.jar                      | None                                     |
	| UCHIJAAAA | draconicevolution              | 2.3.4                    | Draconic-Evolution-1.12-2.3.4.265-universal.jar | None                                     |
	| UCHIJAAAA | elevatorid                     | 1.3.5                    | ElevatorMod-1.12.2-1.3.5.jar                    | None                                     |
	| UCHIJAAAA | valkyrielib                    | 1.12-2.0.1a              | valkyrielib-1.12.1-2.0.2c.jar                   | None                                     |
	| UCHIJAAAA | environmentaltech              | 1.12.1-2.0.2d            | environmentaltech-1.12.1-2.0.2d.jar             | None                                     |
	| UCHIJAAAA | exnihilocreatio                | 1.12-0.1.5               | exnihilocreatio-1.12-0.1.5.jar                  | None                                     |
	| UCHIJAAAA | excompressum                   | 3.0.9                    | ExCompressum_1.12.2-3.0.9.jar                   | None                                     |
	| UCHIJAAAA | mantle                         | 1.12-1.3.1.21            | Mantle-1.12-1.3.1.21.jar                        | None                                     |
	| UCHIJAAAA | tconstruct                     | 1.12-2.7.4.34            | TConstruct-1.12-2.7.4.34.jar                    | None                                     |
	| UCHIJAAAA | extrautils2                    | 1.0                      | extrautils2-1.12-1.6.7.jar                      | None                                     |
	| UCHIJAAAA | zerocore                       | 1.12-0.1.1.0             | zerocore-1.12-0.1.1.0.jar                       | None                                     |
	| UCHIJAAAA | bigreactors                    | 1.12-0.4.5.44            | ExtremeReactors-1.12-0.4.5.44.jar               | None                                     |
	| UCHIJAAAA | fastleafdecay                  | v14                      | FastLeafDecay-v14.jar                           | None                                     |
	| UCHIJAAAA | sonarcore                      | 5.0.2                    | sonarcore-1.12.2-5.0.2.jar                      | None                                     |
	| UCHIJAAAA | fluxnetworks                   | 3.0.1                    | fluxnetworks-1.12.2-3.0.1.jar                   | None                                     |
	| UCHIJAAAA | forestry                       | 5.7.0.212                | forestry_1.12.2-5.7.0.212.jar                   | None                                     |
	| UCHIJAAAA | gravestone                     | 1.10.0                   | gravestone-1.10.0.jar                           | None                                     |
	| UCHIJAAAA | hammercore                     | 1.9.5.3                  | HammerCore-1.12.2-1.9.5.3.jar                   | None                                     |
	| UCHIJAAAA | immersiveengineering           | 0.12-74                  | ImmersiveEngineering-0.12-74.jar                | 4cb49fcde3b43048c9889e0a3d083225da926334 |
	| UCHIJAAAA | immersivetech                  | 1.3.4                    | immersivetech-1.12-1.3.4.jar                    | None                                     |
	| UCHIJAAAA | indlog                         | 1.0.2                    | InductiveLogistics-1.12.2-1.0.2.jar             | None                                     |
	| UCHIJAAAA | inventorytweaks                | 1.63+release.109.220f184 | InventoryTweaks-1.63.jar                        | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
	| UCHIJAAAA | journeymap                     | 1.12.2-5.5.2b1           | journeymap-1.12.2-5.5.2b1.jar                   | None                                     |
	| UCHIJAAAA | justenoughbuttons              | 1.12-1.2.1               | justenoughbuttons-1.12-1.2.1.jar                | None                                     |
	| UCHIJAAAA | limelib                        | 1.7.9                    | limelib-1.12.2-1.7.9.jar                        | None                                     |
	| UCHIJAAAA | mcmultipart                    | 2.3.3                    | MCMultiPart-2.3.3.jar                           | None                                     |
	| UCHIJAAAA | mob_grinding_utils             | 0.3.2                    | MobGrindingUtils-0.3.2.jar                      | None                                     |
	| UCHIJAAAA | storagedrawers                 | 1.12-5.2.5               | StorageDrawers-1.12.1-5.3.3.jar                 | None                                     |
	| UCHIJAAAA | refinedstorage                 | 1.5.21                   | refinedstorage-1.5.21.jar                       | None                                     |
	| UCHIJAAAA | thermalfoundation              | 2.3.6                    | ThermalFoundation-1.12-2.3.6.16-universal.jar   | None                                     |
	| UCHIJAAAA | morechickens                   | 3.0.0                    | morechickens-1.12.2-3.0.0.jar                   | None                                     |
	| UCHIJAAAA | mysticalagriculture            | 1.6.6                    | mysticalagriculture-1.12-1.6.6.jar              | None                                     |
	| UCHIJAAAA | neid                           | 1.5.4.2                  | NotEnoughIDs-1.5.4.2.jar                        | None                                     |
	| UCHIJAAAA | nei                            | ${mod_version}           | NotEnoughItems-1.12-2.4.0.231-universal.jar     | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCHIJAAAA | quantumlights                  | 1.12.1-0.0.0.1           | QuantumLights-1.12.1-0.0.0.1.jar                | None                                     |
	| UCHIJAAAA | randomthings                   | 4.0.8                    | RandomThings-MC1.12.2-4.0.8.jar                 | d72e0dd57935b3e9476212aea0c0df352dd76291 |
	| UCHIJAAAA | reborncore                     | 3.4.9.143                | RebornCore-1.12.2-3.4.9.143-universal.jar       | 8727a3141c8ec7f173b87aa78b9b9807867c4e6b |
	| UCHIJAAAA | rebornstorage                  | 1.0.0                    | RebornStorage-1.12.2-2.1.1.16.jar               | None                                     |
	| UCHIJAAAA | rftools                        | 7.12                     | rftools-1.12-7.12.jar                           | None                                     |
	| UCHIJAAAA | roost                          | 1.1.0                    | roost-1.12-1.1.0.jar                            | None                                     |
	| UCHIJAAAA | simplemagnet                   | 1.12.0-1.2.6             | simplemagnet-1.12.2-1.2.7.jar                   | None                                     |
	| UCHIJAAAA | skyresources                   | 2.0.23                   | skyresources-2.1.0.jar                          | None                                     |
	| UCHIJAAAA | solarfluxreborn                | 3.42r                    | SolarFluxReborn_1.12.2-3.42r.jar                | None                                     |
	| UCHIJAAAA | thermaldynamics                | 2.3.6                    | ThermalDynamics-1.12-2.3.6.13-universal.jar     | None                                     |
	| UCHIJAAAA | thermalexpansion               | 5.3.6                    | ThermalExpansion-1.12-5.3.6.20-universal.jar    | None                                     |
	| UCHIJAAAA | thutcore                       | 5.11.7                   | thutcore-5.11.7.jar                             | None                                     |
	| UCHIJAAAA | tp                             | 1.12                     | tinyprogressions-1.12-3.2.10 - Beta.jar         | None                                     |
	| UCHIJAAAA | tinyreactors                   | 1.12                     | tinyreactors-1.12-0.5.2.jar                     | None                                     |
	| UCHIJAAAA | transprot                      | 1.5.0                    | transprot-1.12-1.5.0.jar                        | None                                     |
	| UCHIJAAAA | treegrowingsimulator           | 0.0.4                    | TreeGrowingSimulator2017-1.0.1.jar              | None                                     |
	| UCHIJAAAA | veinminer                      | 0.38.1                   | VeinMiner-1.12-0.38.1.639+134fb1e.jar           | None                                     |
	| UCHIJAAAA | veinminermodsupport            | 0.38.1                   | VeinMiner-1.12-0.38.1.639+134fb1e.jar           | None                                     |
	| UCHIJAAAA | voidislandcontrol              | 1.2.5                    | voidislandcontrol-1.2.5.jar                     | None                                     |
	| UCHIJAAAA | wanionlib                      | 1.12.2-1.0               | WanionLib-1.12.2-1.0.jar                        | None                                     |
	| UCHIJAAAA | wawla                          | 2.5.246                  | Wawla-1.12.2-2.5.246.jar                        | d476d1b22b218a10d845928d1665d45fce301b27 |
	| UCHIJAAAA | woot                           | 1.12.2-0.0.1             | woot-1.12.2-0.0.1.jar                           | None                                     |
	| UCHIJAAAA | xnet                           | 1.4.1                    | xnet-1.12-1.4.1.jar                             | None                                     |
	| UCHIJAAAA | xtones                         | 1.12-1.0.6-9             | Xtones-1.12-1.0.6-9.jar                         | None                                     |
	| UCHIJAAAA | corail_pillar                  | 4.0.0                    | corail_pillar-4.0.0-1.12.jar                    | None                                     |
	| UCHIJAAAA | unidict                        | 1.12.2-1.0               | UniDict-1.12.2-1.0.jar                          | None                                     |
	| UD        | solarfluxreborncore            | 3.42r                    | minecraft.jar                                   | None                                     |

	Loaded coremods (and transformers): 
Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  invtweaks.forge.asm.ContainerTransformer
IELoadingPlugin (ImmersiveEngineering-0.12-74-core.jar)
  blusunrize.immersiveengineering.common.asm.IEClassTransformer
AppleCore (AppleCore-mc1.12.2-2.2.2.jar)
  squeek.applecore.asm.TransformerModuleHandler
HammerCoreCore (HammerCore-1.12.2-1.9.5.3.jar)
  com.pengu.hammercore.asm.HammerCoreTransformer
SFRCore (SolarFluxReborn_1.12.2-3.42r.jar)
  com.pengu.solarfluxreborn.core.SFRSerializedTransformer
LoadingPlugin (RandomThings-MC1.12.2-4.0.8.jar)
  lumien.randomthings.asm.ClassTransformer
CTMCorePlugin (CTM-MC1.12-0.2.3.9.jar)
  team.chisel.ctm.client.asm.CTMTransformer
Plugin (NotEnoughIDs-1.5.4.2.jar)
  ru.fewizz.neid.asm.Transformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 388.13' Renderer: 'GeForce GTX 980 Ti/PCIe/SSE2'
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
		- chiselIntegration (Enabled/Not Forced)
		- chiselsandbitsIntegration (Enabled/Not Forced)
		- wailaIntegration (Enabled/Not Forced)

	RebornCore: 
		Plugin Engine: 0
		RebornCore Version: 3.4.9.143
		Runtime Debofucsation 1
		RenderEngine: 1
	Launched Version: 1.12.2-forge1.12.2-14.23.0.2520
	LWJGL: 2.9.4
	OpenGL: GeForce GTX 980 Ti/PCIe/SSE2 GL version 4.6.0 NVIDIA 388.13, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: Flows HD (1.12) 64x.zip
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 8x Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz
	OptiFine Version: OptiFine_1.12.2_HD_U_C6
	Render Distance Chunks: 12
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 NVIDIA 388.13
	OpenGlRenderer: GeForce GTX 980 Ti/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 8

**Comment by raoulvdberge** [comment]
That is a TinyReactors bug. Are you sure that you gave the correct crashreported?

**Comment by ntn6371** [comment]
updated.

**Comment by raoulvdberge** [comment]
..Where is your correct crashlog?

**Comment by ntn6371** [comment]
It won't produce a crash log. It just disconnects me from the server saying fatal error. I check the logs and there was no crash report. There wasn't anything in the general latest.log either...
