### ISSUE TITLE
Ticking Block Entity on world load (NetworkNodeGraph$Visitor.visit)

### ISSUE THREAD

**Issue by rigerc** [raoulvdberge/refinedstorage#1544]
#### Issue description:

The server crashes on my singleplayer world when I load in. I've played this world for lots of hours and this started happening all of a sudden.

#### What happens:

Server crash with a Ticking Block Entity error in the log on the Controller block. When I remove the Controller with MCEdit the world loads in OK - but when I place a new one it immediately crashes again. Making a new creative world everything works fine.

#### Steps to reproduce:

So I can't really reproduce it on a new world, I'm guessing the problem is somewhere in the network but I can't really tell where. 

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12.2
- Forge: 14.23.0.2549
- Refined Storage: 1.5.23

Does this issue occur on a server? [yes/no]

Yes

#### If a (crash)log is relevant for this issue, link it here:

https://pastebin.com/sLxZwv9b

**Comment by raoulvdberge** [comment]
Weird. That shouldn't really happen. Can you send me your world along with the coords of the bad controller?

**Comment by rigerc** [comment]
Sure. The controller is at X: 87 / Y: 71 / Z: 140

https://wetransfer.com/downloads/1ca562aae76b48c81569db0612f8706620171123143659/3f27f37c01cbb58d5b72e912c58c4ea320171123143659/6a64e1

**Comment by raoulvdberge** [comment]
Weird, your world works fine for me:

![x](https://raoulvdberge.com/xFOOuH)

**Comment by raoulvdberge** [comment]
Even though I couldn't reproduce the problem, I added a small safety check.

**Comment by rigerc** [comment]
Tried the new update and world now loads in! Thanks! Pretty weird though, must've been some weird mod interaction?

**Comment by raoulvdberge** [comment]
Probably, because you got a NPE and the problematic method can't possibly return null in vanilla RS code.

Some mod might be implementing the API in a bad way. Are you using RS together with some other mod that adds integration?

**Comment by rigerc** [comment]
I'm using it together with a few machines from Immersive Engineering and Compact Machines, which recently updated its Refined Storage cable compatibility. Maybe that's the problem? Although when I removed those machines it still crashed.

**Comment by raoulvdberge** [comment]
Could you try something for me? Launch your previous crashy world which you posted on the previous RS version that crashed. It should crash. OK, then, just **remove** CompactMachines. Don't remove the machines manually, just remove the mod and launch your world. Does it still crash then?

**Comment by rigerc** [comment]
Tried it and it works when I remove Compact Machines with the older version of RS, so it's definitely CM then.
