### ISSUE TITLE
Items ocasionally not appearing after putting into grid

### ISSUE THREAD

**Issue by RacerDelux** [raoulvdberge/refinedstorage#1545]
#### Issue description:
Has happened on two different occasions:
1) System is inside compact machine. Person 1 in the overworld has a grid on the top of the compact machine, person 2 is inside the compact machine using a grid attached directly to the system. Person 2 puts an item in, but it does not show up for person 1 until they mine the grid and place it back.
2) Put an item in an AE2 grid (using a bus to connect to a refined storage interface - storage is all done using Refined Storage drives). The item failed to appear as being in the system until I mined and replaced the interface.
#### What happens:
Items fail to appear in the grid
#### What you expected to happen:
When I put items in the grid, they should always appear
#### Steps to reproduce:
The issue does not seem to always happen, but the simplest is to setup a system where you access the storage from AE2 grid, but use Refined Storage drives. Put items in and out over and over, and you may eventually see this happen.
...

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12.2
- Forge: 14.23.0.2531
- Refined Storage: 1.5.23
- Applied Energistics 2: rv5-stable-2
- ATM 3 v5.1

Does this issue occur on a server? [yes/no]
Yes

**Comment by raoulvdberge** [comment]
I'm sorry, I really can't reproduce this issue.

**Comment by RacerDelux** [comment]
No worries... It seems to be rather random. Probably a very specific corner case.
