### ISSUE TITLE
[1.12.2]Constructor crashing servers

### ISSUE THREAD

**Issue by Niuttuc** [raoulvdberge/refinedstorage#1546]
#### Issue description:
A Constructor placing wood logs made the server crash. Loading a backup of the map containing the constructor did not fix the issue, as it seems it arises for world/data/refinedstorage_nodes.dat When this file was rewinded, the server started to work fine again for a while, then started to crash again, until we finally found the problematic constructor.

#### What happens:
The server crashes a first time, then crashes on startup.

#### What you expected to happen:
The world loads and the server starts.

#### Steps to reproduce:
I don't know of an easy way to reproduce this currently, as the system worked for a while multiple times without any problem then started to crash everything.

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12.2
- Forge:14.23.0.2512
- Refined Storage:  1.5.23

Does this issue occur on a server? [yes/no]
Yes

#### If a (crash)log is relevant for this issue, link it here:

[Crash Report](https://pastebin.com/NkFj7xpi)

**Comment by raoulvdberge** [comment]
Thanks for the report, I'm looking into it.
