### ISSUE TITLE
Crafting upgrades not working

### ISSUE THREAD

**Issue by PapiDimmi** [raoulvdberge/refinedstorage#1547]
My exporter exports items from my Refined Storage system into an inventory even though it has a crafting upgrade.

The thing is, it stops exporting if I enable “Craft-only mode” in the exporter, but then, I don’t need a crafting upgrade. I am extremely confused right now.

****

**Minecraft version**: 1.12.2
**Forge version**: 14.23.0.2531
**Refined Storage version**: 1.5.23

**Comment by Tahakk** [comment]
Crafting upgrade is upgrade that will do as followed for example:

You have Mekanism's Metallurgic Infuser in which you need redstone or those redstone plate-ish things.

1. Now... If you would export **only redstone** you would just need exporter set with **redstone**.

2. If you would need to export those redstone plates and you don't have any in your system, you will create recipe. Then you take **redstone plate** and **crafting upgrade** and set it into the exporter. 
    
    What will that do, if machine can accept another redstone plate, RF will craft it and export it right away.

Out of my head cannot come with this Crafting only button usage. But as far as you put it, you don't really need it.

**Comment by PapiDimmi** [comment]
Yeah, that makes sense. Thanks.

I haven’t played modded Minecraft in a while. I realize I used the crafting upgrade incorrectly.

That said, I really want to know what the “Craft-only mode” button does. If it does the same thing as the crafting upgrade, what’s the point of the crafting upgrade? I don’t think it does the same thing as the crafting upgrade, though. For some reason, it stopped exporting items from my system once I enabled “Craft-only mode.”

Does it mean that the exporter will only function if the items are used in a crafting recipe?

@raoulvdberge

**Comment by raoulvdberge** [comment]
Craft-only will only exported **newly crafted** items, not using any previous items from storage.

**Comment by PapiDimmi** [comment]
How does the mod determine which items were newly crafted, and what are the uses of this option?

**Comment by raoulvdberge** [comment]
See #132.

I removed the craft-only option for 1.5.24 because it was implemented in a buggy way.
