### ISSUE TITLE
Advancements resetting

### ISSUE THREAD

**Issue by PapiDimmi** [raoulvdberge/refinedstorage#1548]
I, and the other players on my server, keep getting the same Refined Storage advancements over and over again, even though we’ve already gotten them before.

**Minecraft version**: 1.12.2
**Forge version**: 14.23.0.2552
**Refined Storage version**: 1.5.23

**Comment by raoulvdberge** [comment]
Not an RS problem.

**Comment by PapiDimmi** [comment]
@raoulvdberge It hasn’t happened with other mods.

**Comment by Tahakk** [comment]
Than reproduce this with only RS and if it happens report it back here. Otherwise remove mods until it will happen and than report it to correct project issues.
