### ISSUE TITLE
Server crash on auto crafting for storage

### ISSUE THREAD

**Issue by Hasselpoof** [raoulvdberge/refinedstorage#1549]
#### Issue description:

Server is crashing when telling a export buss (in craft only mode) to craft ingots and export into a 2*2 drawer that also have external storage buss on it

i have other export busses with crafting upgrade on them and they work just fine

#### What happens:

once export buss is told what to export the server stops

#### What you expected to happen:

to have ingots premade for faster crafting later on when those materials are needed for another crafting

#### Steps to reproduce:
1. export buss (in crafting only mode) + storage buss (this have -1 priority on it) on a 2*2 drawer

2. drawer is preconfiged with ingots

3. tell export buss what materials to craft and put into the drawer
...

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1,12,2

- Forge: 14,23,0,2431

- Refined Storage: 1,5,23

Does this issue occur on a server? [yes/no] YES

#### If a (crash)log is relevant for this issue, link it here:

https://pastebin.com/hqXejpNA

[pastebin/gist/etc link here]

**Comment by raoulvdberge** [comment]
That is a watchdog crash, not much I can do with that.
