### ISSUE TITLE
The One Probe crashes world when looking at Storage drive.

### ISSUE THREAD

**Issue by ExpensiveKoala** [raoulvdberge/refinedstorage#1550]
#### Issue description:
When The One Probe tries to display the inventory inside the storage drive, it crashes the client/world.
"Tried to read NBT tag that was too big; tried to allocate: 2097154bytes where max allowed: 2097152"
#### What happens:
Crash world. Not the entire client
#### What you expected to happen:
Not Crash.
#### Steps to reproduce:
1. Have both Refined Storage and The One Probe
2. Have a drive that has a lot of different item types in it.
3. Look at the drive while holding shift/showing advanced
...

#### Version (make sure you are on the latest version before reporting):

- Minecraft:1.12.2
- Forge:forge-14.23.0.2549
- Refined Storage:1.5.23

Does this issue occur on a server? [yes/no]

#### If a (crash)log is relevant for this issue, link it here:

https://pastebin.com/4behY5Vu

**Comment by raoulvdberge** [comment]
The One Probe needs to send the NBT share tag instead of the actual NBT tag. Closing as this is not an RS issue.
