### ISSUE TITLE
[1.12.2] Auto-crafting crash: Stack can not be invalid!

### ISSUE THREAD

**Issue by JonathanxD** [raoulvdberge/refinedstorage#1556]
#### Issue description:

I've updated all mods recently and removed IC2 (I know, I lost a lot of ores and ingots, but I don't care at all), DeepResonance and some other mods (4 or 5. I don't remember exactly), then I launched the game and tried to craft a wireless transmitter, the game crashed.

#### What happens:

Game crash.

#### What you expected to happen:

Wireless transmitter be created successfully.

#### Steps to reproduce:
I don't have idea, probably if you remove some mods that there are blocks stored in disks may cause this problem.

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12.2
- Forge: 1.12.2-14.23.1.2559
- Refined Storage: 1.5.25

Does this issue occur on a server? I haven't tested it on a server.

#### If a (crash)log is relevant for this issue, link it here:

[Full log](https://gist.github.com/JonathanxD/52847b4992e96d17bc3208095b7abf8f)
[Stacktrace and below](https://gist.github.com/JonathanxD/dcb702e85b7381d0c2620868fd2f479f)

**Comment by raoulvdberge** [comment]
Should be fixed indev already with 571c2b18afdb9680ea1a4eb0383ea3410c81e403.
