### ISSUE TITLE
[1.12.2] Auto-crafting with fluid; Prioritizing stored fluid over crafted

### ISSUE THREAD

**Issue by LordPinkerton** [raoulvdberge/refinedstorage#1557]
#### Steps to reproduce:
1. Pattern created for Enderium Blend 3 lead dust, 1 platinum dust, 1 bucket Resonant Ender(imported as non-processing with Oredict active) for Crafter.
2. Pattern created for Resonant Ender from four Ender Pearls to 1000mb (imported as processing with Oredict active) for Crafter attached to Magma Crucible.
3. I have 128,000mb of Resonant Ender in storage drive.
4. Attempt to craft Enderium Blend.
5. Crafting Preview says Resonant Ender To Craft: 1.
6. Crafting crafts new Resonant Ender to make recipe.
7. Attempt to craft Enderium Blend after disabling pattern for Resonant Ender.
8. Crafting Preview says Resonant Ender Available: 1000 mB
9. Crafting uses stored Resonant Ender to make recipe.
...

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12.2
- Forge: 14.23.1.2555
- Refined Storage: 1.5.25

Does this issue occur on a server? [yes/no] No

#### If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here]

**Comment by Gravlok** [comment]
I have similar issue. I wanted to create signallum blend which requires bucket of destabilized redstone. When I don't have neither stored fluid or bucket of DR it gets stuck on filling the bucket with DR. (The recipe is set like so: 10 redstone dust -> bucket of destabilized redstone, processing enabled. Inserted into crafter attached do magma crucible with importer which sucks up the created fluid into system)

**Comment by tristo7** [comment]
Seeing this same issue for destabilized redstone and other liquids as well.

**Comment by raoulvdberge** [comment]
This can be closed, as there will be a new system.

**Comment by Spongman** [comment]
did this ever get fixed in 1.12? i'm still seeing it in FTB academy.
