### ISSUE TITLE
Air displaying in RS grid

### ISSUE THREAD

**Issue by AnkaraSoulreaver** [raoulvdberge/refinedstorage#1561]
#### Steps to reproduce:
1.  Highly variable, always present but varies in number of air slots at any given time.
2.  I have not yet identified a specific trigger.
3.
...

#### Version (make sure you are on the latest version before reporting):

- Minecraft:  1.12, Direwolf20 mod pack with current updates installed
- Forge:
- Refined Storage:

Does this issue occur on a server? [yes/no] Unknown, I play on a solo instance.

#### If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here]

**Comment by Nagshell** [comment]
It's been happening to me too. Mostly after doing some auto-crafting, and effect was disappearing after finishing craft and letting RS count everything.

It's also possible to "pump out" air using disk manipulator.
