### ISSUE TITLE
GUI for crafting grid randomly failed to initialize

### ISSUE THREAD

**Issue by noahc3** [raoulvdberge/refinedstorage#1562]
#### Issue description:

The GUI on the crafting grid failed to fully initialize

#### What happens:
Note that the world is running on a server.

When trying to open the crafting grid, only some functionality of the crafting grid worked, I could view, extract and insert items. However: 
- The scroll bar was not visible or functioning
- The search bar was not functioning 
- The configuration buttons for the grid did not appear 
- The slots for the player inventory were not created, thus the itemstacks did not render and the slots could not be interacted with.

(screenshots attached)

I could also not press escape to exit the GUI. JEI was fully functional, and **the game did not crash** despite throwing a fatal error on the client log (see below).

#### What you expected to happen:

The crafting grid should have fully initialized the GUI and should have worked as expected.

#### Steps to reproduce:

Not sure what to say here. Right click a crafting grid with lots of items in the network and get lucky?
It should be noted that I had just recently imported many items from Actually Additions barrels into the network.

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12.2
- Forge: 14.23.1.2555 (both client and server, server did not run any form of Sponge/Bukkit/etc)
- Refined Storage: 1.5.25

Does this issue occur on a server? I've only had it occur on a server.

#### Crash log

This is the log from the client. I dont have the server log as I had restarted the server when the issue happened without making a copy of the log file. 
The relevant error can be found on line 9947 of the log (NoSuchElementException when trying to clear the grids container): https://paste.ee/p/QEuMu

#### Screenshots:

Half-initialized Crafting Grid GUI:
![image](https://user-images.githubusercontent.com/6082749/33681935-931397fe-da8b-11e7-8ff0-0134445357d1.png)

Can still interact with items in network: 
![image](https://user-images.githubusercontent.com/6082749/33681957-a84148e2-da8b-11e7-9fc8-520389665a65.png)

Edit: Wiped drive is an issue with duplicating a drive with middle-mouse click. Unrelated to this so I removed the information connected to that.

**Comment by SDUBZ** [comment]
this also happens in single player

**Comment by raoulvdberge** [comment]
This is a crossmod issue. Something (an external mod) is modifying the slot list. I don't know which mod does this by just looking at the crashreport.
