### ISSUE TITLE
Autocrafting not netting full output for Quartz Iron

### ISSUE THREAD

**Issue by jadeonking** [raoulvdberge/refinedstorage#1564]
Quartz Iron auto crafting doesn't net proper amount

Start Autocrafting for 10 Quartz Iron which should be 40 since you get 4 per output

[Video showcasing the issue](https://youtu.be/rEd-nNn6Z2s)

- Minecraft: 1.10.2
- Forge: 12.18.3.2511
- Refined Storage: 1.2.26

FTB SkyFactory 3 Modpack

Does this issue occur on a server? Yes

**Comment by raoulvdberge** [comment]
1.10

**Comment by number65259** [comment]
Not a bug. The crafting system is asking how many ingots you need. When you enter 10, it keeps crafting the x4 recipe until you have at least 10 ingots. 4, not enough. 8, not enough. 12, satisfies request. Look at the materials used in the summary screen - nothing was lost.
