### ISSUE TITLE
Item conversion bug with exporter

### ISSUE THREAD

**Issue by Lordeath19** [raoulvdberge/refinedstorage#1565]
#### Issue description:

DISCLAIMER: this only happens when inventories filter their own inventories
(for example redstone furnaces from thermal expansion that only accept smelt-able items
i.e. it won't accept wool as it can't be smelted)

If an exporter is set to no damage filtering (doesn't care about the damage of the item)
and the inventory is also self-filtering all items with the same id will be converted to the filtered
item
#### What happens:

When putting an item, let's say **pulverized silver**, in the filter with no damage filtering
all **silver ingots** will be converted into pulverized silver in order to be inserted to the inventory

as a refrence:

silver ingot - id 5148, damage value 130
pulverized silver - id 5148, damage value 66

#### What was expected to happen:

only pulverized silver should enter the inventory (and no conversions should happen)

#### Steps to reproduce:

1. place an exporter adjacent to a self filtering inventory (in the example a redstone furnace)
2. set the exporter to disregard damage
3. place an item in the filter list (like pulverized silver)
4. populate your refined storage system with an item with the same id (silver ingot)
5. watch how all your silver ingots magically convert into pulverized silver

**images below:**

https://user-images.githubusercontent.com/21251680/33726004-79dd952c-db7c-11e7-90e4-33f697700a72.png

pulverized silver is the left-most filtered item

https://user-images.githubusercontent.com/21251680/33726005-79fc92ce-db7c-11e7-9073-019e1762ed38.png

only **silver ingots** exist in the network so that it isn't possible for pulverized silver to be there

https://user-images.githubusercontent.com/21251680/33726006-7a1e64f8-db7c-11e7-9158-96b7c8b3f9a6.png

silver ingots are converted into pulverized silver so they could fit the redstone furnace's inventory

#### Version:

- Minecraft: 1.12.2
- Forge: 14.23.1.2555
- Refined Storage: 1.5.25

Didn't try it on servers

**Comment by zintak** [comment]
I had this same issue, but the inventory doesn't need to be self-filtering for it to do something similar.
If you point an exporter into a vanilla chest and set it to an item of a certain item id, then tell it to ignore damage values, it will input all items of the same id into the chest. (but not convert them into a different item.) I don't know if that, without the item conversion, is technically a bug, but it will certainly appear as such to some, and it is detrimental to gameplay.

For example: What happened to me is I had a very large amount of an unwanted item. (thousands of Actually Additions Bat Wings: id 4207:15 from my mob farm) so naturally, I set up an exporter going out of my system, and into a trash can (from Extra Utilities 2.) I also was getting a large amount of unwanted armor from my mob farm, so I used the same exporter for some of that and set it to ignore damage values (I didn't want to only get rid of one damage value of armor.) At some point after this, I needed to craft some items using more items from Actually Additions (Black Quartz: id 4207:5 and Basic Coil: id 4207:7) but I had the issue that any time I made these items and put them in my system, they would vanish. I had this issue repeatedly, consistently, but I checked over my entire system and could not find anything to explain it, so I worked around it. Finally today, I was about to report it as a bug, when I thought to look at the item id and discovered the culprit. I used an exporter that was not set to ignore damage values to be rid of the bat wings and now everything is working as expected, I then found this bug report and tested it with a vanilla chest, as mentioned earlier.

Versions:
Minecraft: 1.10.2
Forge: 12.18.3.2477
Refined Storage: 1.2.26
I'm using the Twitch launcher, version: 7.5.6585.2139
to launch Sky Factory 3, version: 3.0.15

P.S. I realize this may have been unnecessarily long, that's an issue I have, and I'm sorry for the inconvenience.

**Comment by raoulvdberge** [comment]
@Lordeath19 I can no longer reproduce this today. I assume this was an Thermal Expansion bug, since they are the ones to "accept" items in an inventory and possibly convert it.

@zintak  
> If you point an exporter into a vanilla chest and set it to an item of a certain item id, then tell it to ignore damage values, it will input all items of the same id into the chest. 

That is exactly what the "ignore damage" button does. If you don't want that, disable that option.
