### ISSUE TITLE
Odd interface Interaction

### ISSUE THREAD

**Issue by skeough** [raoulvdberge/refinedstorage#1568]
#### Issue description:  
Odd Interaction between Interfaces and Thermal Expansion Machines

#### What happens:
Machines seem to be able to auto-pull directly from the network anything that they can process, however when they have a specialization places in the machine that limits the processing capabilities, the machine will still be allowed to pull the same items, even if it cannot process them.

Also reported on CoFH git, King Lemming suggested I bring it up here too: [https://github.com/CoFH/Feedback/issues/705](https://github.com/CoFH/Feedback/issues/705)

#### What you expected to happen: 
Machine should only pull what it can process at the time.

#### Steps to reproduce:
1. Place machine next to interface and set to auto push/pull on it.
2. Place Specialization in machine that limits what can be processed.

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12.2
- Forge: 14.23.1.2555
- Refined Storage: 1.5.25
- Thermal Expansion: 5.3.7.31

Direwolf20 pack (1.3.0)

Does this issue occur on a server? Not Tested

**Comment by raoulvdberge** [comment]
Refined Storage Interface does not auto pull or auto insert. It provides an inventory as-is.

**Comment by KingLemming** [comment]
Is it a standard inventory though or is it doing some strange behind-the-scenes stuff?

I can't make this happen with any sort of "standard" inventory. Now to be fair, I haven't confirmed it happening with RS yet either.

**Comment by skeough** [comment]
This can be closed out, addressed in Thermal Expansion
