### ISSUE TITLE
[1.12.2] Non-oredict patterns produces items from nothing

### ISSUE THREAD

**Issue by wamc2017** [raoulvdberge/refinedstorage#1570]
#### Issue description:
Updated Refined Storage today to 1.5.26 and all Non-oredict patterns doesn't use resources to craft...

#### What happens:
The crafting process doesn't use the needed resources and creates the item from the void.
1.5.25 works fine after downgrading! (Tried it with only JEI and Refined Storage installed)

#### What you expected to happen:
The RS system should use the appropriate resources.

#### Steps to reproduce:
1. Start a new world
2. Build basic infrastructure (Controller, Disk Drive, Disk, Pattern Interface, Pattern, Crafter)
3. Create a pattern (non-oredict) put it into the crafter and let the system craft the item

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12.2
- Forge: 14.23.1.2562
- Refined Storage: 1.5.26 

Does this issue occur on a server? [yes/no]
Only tested in singleplayer.

#### If a (crash)log is relevant for this issue, link it here:
No crashlog.

Thanks for looking into it. :)

**Comment by raoulvdberge** [comment]
I can't believe this didn't pop up while testing... I was only testing with oredict patterns -_- 

Fixed it, thanks for reporting.

**Comment by raoulvdberge** [comment]
I published 1.5.27 which fixes this issue, will be up in a few. Thanks again.

**Comment by wamc2017** [comment]
Thanks for the quick fix, compiled and tried it, works fine so far. :+1:
