### ISSUE TITLE
MC v 1.12.2 RS v 1.5.25 Constructor/Destructor Issues

### ISSUE THREAD

**Issue by danielconrad2011** [raoulvdberge/refinedstorage#1574]
#### Steps to reproduce:
1.Stet up constructor to place Coal ore.
2.See if constructor will place Coal ore.
3.See if destructor will break Coal ore constructor places or place block manually.
...

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12.2 
- Forge:14.23.2566
- Refined Storage:1.5.28, 1.5.27 and Release v 1.5.25 

{Note: Both still work on MC v 1.12.1 - refined storage 1.5.28}

Does this issue occur on a server? [yes/no] Single Player (Testing) in Survival 

#### If a (crash)log is relevant for this issue, link it here: NA

[pastebin/gist/etc link here]

**Comment by danielconrad2011** [comment]
I have the same mods in MC v1.12.1 and in the MC v1.12.2. It still works in MC v1.12.1. I did just move my save file from MC v1.12.1 to MC v1.12.2. That may have broken something? I take it that they work fine for everyone else? I will create a new game and try with all of the mods I have loaded and try to see which mod is causing the problem. If I find it I will comment again...

Thank you for your response, your mod and your time!

**Comment by danielconrad2011** [comment]
So, tested a creative MC v1.12.2 with all mods loaded and both constructor and destructor works fine...I think just moving a MC v1.12.1 save to MC v1.12.2 does not work and has caused the problem. Any thoughts of what may cause that to happen? 

Well sorry for the time drain and appreciate any thoughts on how to fix moved save,

**Comment by danielconrad2011** [comment]
OK, found it at this link https://github.com/Minecolonies/minecolonies/issues/1086 
Following this sugestion; I did disable colony protection and it worked.

Raycoms posted this response to the same problem I was having.
"It seems like refinedStorage uses fakePlayers.
There are two chances:Disable colony protection in the config. (Works!)
"As we spoke with the forge team, fakePlayers should inherit the players UUID, I guess refinedStorage does that wrong" - Is this true? Can you change change how fakePlayers work in your Mod?

I would suggest to note in mod description that Refined storage is not entirely compatible with Minecolonies.

Thanks again,
--

**Comment by danielconrad2011** [comment]
Just found a response you had given on this very issue.

"Gonna tag this as wontfix. I don't want to store any UUIDs in network nodes."

Apparently you knew this issue before but neglected to ask if I had Minecolonies loaded...

PLease just give people a heads up that they need to disable colony protection or constructor and destructor wont work when Mincolonies is loaded.

Just happy to find what the problem was. Thanks again...Great!!! Mod,

**Comment by raoulvdberge** [comment]
Uhm, you can't expect me to remember the resolution of every single issue posted here, I didn't neglect anything, saying that is ridiculous.

**Comment by danielconrad2011** [comment]
Sorry, not meant to insult you..Thanks for your insight to what it could be.
