### ISSUE TITLE
Adding an MCMultiPart cover resets importers/exporters

### ISSUE THREAD

**Issue by trittimo** [raoulvdberge/refinedstorage#1576]
#### Issue description:
Importer/Exporter is reset

#### What happens:
If I have an importer or an exporter configured with a few items, and then place a Chisels & Bits cover on the block, the block is reset to having no configured items. You can configure them again after the cover is placed, but this is not ideal.

#### What you expected to happen:
The importer/exporter should keep its configuration when I place a multipart over it

#### Steps to reproduce:
1. Place down an exporter
2. Add "cobblestone" to the exporter
3. Place a Chisels & Bits cover (crafted via the bit saw) over the side of the exporter
4. The exporter's configuration is reset

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12.2
- Forge: 14.23.1.2566
- Refined Storage: 1.5.28

Does this issue occur on a server?
Unknown. I play on a single player instance.

**Comment by raoulvdberge** [comment]
What is your chisel and bits version? And your mcmultipart version?

**Comment by trittimo** [comment]
Chisels and Bits: 14.11
MCMultiPart: 2.4.0

Those are the latest versions on Curseforge.

**Comment by raoulvdberge** [comment]
Any logs?

**Comment by trittimo** [comment]
Nope. I watched the console window as I placed the block and there were no messages. So unless the error occurs during initialization of the mods, no logs.

**Comment by raoulvdberge** [comment]
This is a mcmultipart issue.

See https://github.com/amadornes/MCMultiPart/issues/112
