### ISSUE TITLE
[1.12.2 Direwolf20 pack] rendering issues

### ISSUE THREAD

**Issue by skylersa** [raoulvdberge/refinedstorage#1578]
#### Issue description:
I am have been having a lot of trouble with textures including drawers, energy cells, thermal piping and of course refined storage piping. Thermal machines are glitching out too. the only modification i've made to the pack is adding some mt scripts.
#### What happens:
null tiles are created
#### What you expected to happen:
for the block no to freak out
#### Steps to reproduce:
1. place refined storage cable
2. place chisel and bits cover in the same block

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12.2
- Forge:14.23.1.2555
- Refined Storage: 1.5.25

Does this issue occur on a server? 
not sure, have not tried

#### If a (crash)log is relevant for this issue, link it here:
https://pastebin.com/dkj7FdJx

Extra info:
I submitted this bug report to codechickenlib repository and that developer told me to come here

**Comment by raoulvdberge** [comment]
How is this even remotely an RS issue, your pack is just messed up and I see no RS in the logs... (Not that your explanation would indicate that it's RS)

**Comment by raoulvdberge** [comment]
Update mcmp and chisel n bits!
