### ISSUE TITLE
Feature Request: Multi-faced crafting grid block

### ISSUE THREAD

**Issue by Drachlox** [raoulvdberge/refinedstorage#1579]
First off, apologize if this is the completely wrong area to post this.

The crafting grid is a block that has one interface facade and the rest of the block is skinned as panels (you can click on them to bring up the one crafting grid, but..).
My request is for a way to craft a crafting grid block that has four separate crafting grid interfaces. 

In my builds i sometimes like to put the grid in the centre of a room and organize the different machines on each of the four walls. If a block would exist that had one interface for each side, operating separate from eachother, it would make me very happy. 
Currently, i have to either arrange the grids in a plus-pattern or find another way to place them. Replacing this with one block would be alot more elegant.

Thank you for a great mod.

**Comment by raoulvdberge** [comment]
No
