### ISSUE TITLE
Feature Request: Crafting upgrade in Interfaces

### ISSUE THREAD

**Issue by dunkfordyce** [raoulvdberge/refinedstorage#158]
Would be nice to put a crafting upgrade into an interface so it can request an item to be crafted for export

**Comment by cjburkey01** [comment]
Like in AE2

**Comment by raoulvdberge** [comment]
Implemented in 29a309b202158a47c888f927cc548e27c81c607b

**Comment by dunkfordyce** [comment]
Yay! Good work!

**Comment by raoulvdberge** [comment]
Thanks to the new autocrafting I can easily traverse the crafting task list, and schedule based on that (instead of the ugly NBT save hack that caused more issues than it was worth) :-)
