### ISSUE TITLE
Refined Storage - Crash 

### ISSUE THREAD

**Issue by Keaton1188** [raoulvdberge/refinedstorage#1580]
#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12.2
- Forge: 14.23.1.2555
- Refined Storage: refinedstorage-1.5.25.jar

Does this issue occur on a server? [yes/no]
Yes
#### If a (crash)log is relevant for this issue, link it here:

https://gist.github.com/Keaton1188/5c18ee61c85ee9f8dd1c4dd91c0f546f

From the user "last thing i did was place a RS crafter down, and before that I was trying to get the Reborn storage crafter to work"

**Comment by Keaton1188** [comment]
![untitled](https://user-images.githubusercontent.com/24898745/34186368-072fec72-e523-11e7-9fc8-f42438fbb647.png)

Msg from a user as well.

**Comment by raoulvdberge** [comment]
This is most likely a Reborn Storage issue.

**Comment by raoulvdberge** [comment]
I added protection to avoid this crash but the root cause is really at Reborn Storage's side.

https://github.com/TechReborn/RebornStorage/issues/70
