### ISSUE TITLE
Interdimensional Network not Working on Venus

### ISSUE THREAD

**Issue by yazzledore** [raoulvdberge/refinedstorage#1582]
#### Issue description:
Playing with Galacticraft, but this seemed similar to https://github.com/raoulvdberge/refinedstorage/issues/623, and not sure which mod is the issue: same version, same circumstances, similar dimensions, but the fix there doesn't work for me, and the dimension isn't RFtools created (so not sure if it is the same thing).  The interdimensional network doesn't work on Venus (dim -31) only.  Both areas are chunkloaded and the transmitter has an interdimensional upgrade, as well as being linked to the appropriate receiver with the network card (says so in the tooltip).  The same system works fine on Mars and the Moon.

#### What happens:
The network transmitter lights up and consumes power, so it is working.  However, the receiver on Venus doesn't light up and isn't working.

#### What you expected to happen:
Items galore.

#### Steps to reproduce:
1. Place receiver on Venus (dim -31); link network card.
2. Set up network transmitter with interdimensional upgrade, and insert network card linked to the receiver.
3. Make sure both areas are chunkloaded and appropriate redstone mode for the transmitter is selected.
4. No items on Venus :(
...

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge: 12.18.23.2511
- Refined Storage: 1.2.26 (Latest)

Does this issue occur on a server? [yes/no]
Not playing on a server.

#### If a (crash)log is relevant for this issue, link it here:
No crashing :)

**Comment by yazzledore** [comment]
Nevermind, restarting the computer fixed it.  No idea why it happened in the first place but appears to be an easy fix.  Sorry!

**Comment by raoulvdberge** [comment]
Weird. I think this is not a galacticraft issue, but a chunkloading one.
