### ISSUE TITLE
[Feature request] Copy filter configurations

### ISSUE THREAD

**Issue by ivandardi** [raoulvdberge/refinedstorage#1584]
It would be nice if we could copy Filters so that we can have multiple filters with the same configuration without needing to manually set each one up.

There are two ways of going at it:

1. Put a configured filter and a blank filter in unshaped crafting grid, and it gives a configured filter without consuming the original one (just like Integrated Dynamics).

2. Put a configured filter and a blank filter in unshaped crafting grid, and it gives two configured filters.

3. Use the Disk Manipulator to somehow copy the filter.

**Comment by raoulvdberge** [comment]
Might also want to be able to copy patterns.

**Comment by DarkHelmet433** [comment]
The customary way to copy patterns for people coming from an AE2 background is to place a pattern in the output of the pattern terminal which causes the stored pattern to be read.  The pattern being copied is removed from the output slot and the previously loaded pattern can then be imprinted on a new pattern.

However, it would be nice to be able to do this in the field.  The proposed mechanism above would be convenient and consistent.

**Comment by mrlamb** [comment]
Came here to request this feature as well. I love the way filters work and would love to be able to drop on into every grid more easily.

**Comment by raoulvdberge** [comment]
Since the filters in filter slot feature will be removed soon, this won't be needed as the only use filters will have is in the Grid.
