### ISSUE TITLE
Detectors not working with Crafter/Solderer combo

### ISSUE THREAD

**Issue by Chunkimunki** [raoulvdberge/refinedstorage#1588]
#### Issue description:
Not Auto crafting to min number set in Detector
#### What happens:
Nothing
#### What you expected to happen:
Crafting of Refined St. item to stock level set
#### Steps to reproduce:
1.installed on single player with McMultiPart 2.4.1 / JEI
2.
3.
...

#### Version (make sure you are on the latest version before reporting):

- Minecraft:1.12.2
- Forge:2577
- Refined Storage:1.5.29

Does this issue occur on a server? [yes/no]
Not tested
#### If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here]

**Comment by raoulvdberge** [comment]
No understand issue too brief

**Comment by Chunkimunki** [comment]
Ok- Setting up a solderer with crafter on top and then detector. Set detector to fire when there are less than 10 processors - pattern for item in crafter and set to activate on signal. Detector lit up but no crafting in solderer.

**Comment by raoulvdberge** [comment]
The crafter doesn't work with the detector. Read the wiki

**Comment by Chunkimunki** [comment]
Apologies - hadn't realised the process had changed from 1.10.2
Great mod btw
