### ISSUE TITLE
Itemducts pulling Disks/Patterns out. 

### ISSUE THREAD

**Issue by McMasterx** [raoulvdberge/refinedstorage#1592]
#### Issue description:. 
Retrievers and Servos from Thermal Expansion are pulling Disks and patterns out of the Drive and Pattern Grid. 
#### What happens:
 Item duct shouldnt be capable of pulling any disks out of RS machines.

#### What you expected to happen:
For that to not pull items

#### Steps to reproduce:
1. Item ducts connecting to Drive and storage
2. Retriever or Servo on one end, Turn on.
3. Disks/Patterns move through ducts.
...

#### Version (make sure you are on the latest version before reporting): 

- Minecraft: 1.12.2
- Forge: 14.23.1.2566
- Refined Storage: 1.5.28

Does this issue occur on a server? Don't know.

#### If a (crash)log is relevant for this issue, link it here:
Image of Disk moving through duct.
http://prntscr.com/hsoap6

**Comment by raoulvdberge** [comment]
I thought about this further and decided the inventory can stay accessible. I also made crafter pattern slots accesible again for consistency.
