### ISSUE TITLE
Autocrafting bug

### ISSUE THREAD

**Issue by raoulvdberge** [raoulvdberge/refinedstorage#1595]
User didn't feel like coming to github

[crash-2017-12-27_20.08.04-server.txt](https://github.com/raoulvdberge/refinedstorage/files/1591068/crash-2017-12-27_20.08.04-server.txt)

**Comment by hugeblank** [comment]
yeah screw github anyways.
In other news, in case you needed confirmation that this is occuring:

[crash-2018-01-07_23.16.02-server.txt](https://github.com/raoulvdberge/refinedstorage/files/1610313/crash-2018-01-07_23.16.02-server.txt)

**Comment by dragon076** [comment]
Have something similar with the (All The Mods 3) mod-pack.
Didn't get a crash log but copied the log output.
Game didn't seem to crash as much as just exit single player world.
Had issues in the last week with trying to auto-craft any liquid buckets into normal crafting recipes.
With the liquid being stored by RS that is, buckets are craft-able and even had a stack available.
After crash game says connection lost.
[Crash.11.01.18.txt](https://github.com/raoulvdberge/refinedstorage/files/1621082/Crash.11.01.18.txt)
If u need any other info i can try to help.

P.S.
Awesome mod and thank you for your work.

**Comment by raoulvdberge** [comment]
I can't reproduce this issue.

**Comment by Opicka879** [comment]
I can upload pack of mods and world folder for you if you want. It will be easy to reproduce then.
