### ISSUE TITLE
Interface Grid

### ISSUE THREAD

**Issue by wesker1213** [raoulvdberge/refinedstorage#1596]
Any chance of have this block that allows us to see all of our patterns that are connected to the network, thus allowing us to place our patterns remotely rather than running to the machine, similar to AE2's interface terminal?

**Comment by zintak** [comment]
The ability to add speed upgrades to and/or configure connected crafters and/or importers/exporters/etc. from within the system would be nice too.

**Comment by Saklad5** [comment]
Having both a wireless pattern grid and a wireless interface grid would make automation much nicer, too.

**Comment by Saklad5** [comment]
Of course, having an interface grid would create UI problems unless you could label crafters, like AE (one of the most criminally underused features in that mod).

**Comment by raoulvdberge** [comment]
This has been implemented for v1.5.33.

**Comment by Saklad5** [comment]
Will it work for other things that implement the API, like the Reborn Storage multi-block?

**Comment by raoulvdberge** [comment]
Yes
