### ISSUE TITLE
Circular dependency! Loop in processing

### ISSUE THREAD

**Issue by wesker1213** [raoulvdberge/refinedstorage#1598]
Regarding environmental tech parts for the vein ore miner.

I craft just 1 at a time, this is fine. The problem lies when I try to craft 5+ of these that I get the above error. I've redid the recipes multiple times just to ensure that things were on the up and up, and still this happens. I can create 1 stack plus at a time of many other things, but the vein ore miner sub components for Environmental Tech.

Anyone able to help?

I am using a modded DW20 pack for 1.12.2 with version 1.5.25 of Refined Storage with the forge version 14.23.1.2555

**Comment by raoulvdberge** [comment]
You have a recipe that requires itself. Autocrafting can't handle that, as it would lead to an infinite loop.
