### ISSUE TITLE
Exporter pulling items not listed

### ISSUE THREAD

**Issue by chemban** [raoulvdberge/refinedstorage#1599]
#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12.2
- Forge: 14.23.1.2570
- Refined Storage: 1.5.28

Does this issue occur on a server? [yes/no]
single player
#### If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here]

**Comment by raoulvdberge** [comment]
That is not possible.
