### ISSUE TITLE
Extreme FPS Drop when in any Grid

### ISSUE THREAD

**Issue by Ilecyutal** [raoulvdberge/refinedstorage#1601]
#### What happens:
When in a grid or a crafting grid FPS drops down to 2-1
#### What you expected to happen:
Smooth movement
#### Steps to reproduce:
1. Have ProjectE installed i guess?
2. Uninstall ProjectE from modpack?
...

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12.2
- Forge: 14.23.1.2566
- Refined Storage: 1.5.28

This is on a single player world
Refined Storage was smooth before installing ProjectE and I uninstalled it cause I suspected it to be the reason the game lags but it still is and now it happens on every modpack. it mostly happens when items are being imported into the system

**Comment by raoulvdberge** [comment]
1) Are there any ProjectE items in your system?
2) "I guess" isn't a valid reproduction step. Does this issue always occur with ProjectE or not? Be sure of this before reporting.
3) Are you using an External Storage on a Transmutation Table?

**Comment by Ilecyutal** [comment]
@raoulvdberge When ProjecTE was installed there weren't any ProjectE related items in or hooked to the system, I uninstalled ProjectE cause I suspected that the EMC values are the ones lagging it but after uninstalling the whole modpack itself it kept on lagging even in other modpacks.

**Comment by raoulvdberge** [comment]
I installed Project E myself and I can't reproduce the lag issue you're having. It's probably caused by something else.

**Comment by Morpheus1101** [comment]
1 way i was able to re-produce this was hooking up External Storage to an EMC Tablet whilst having maxed out the EMC the tablet can hold, my FPS drop was very significant, in this instane i had 0 items existing in the RS system of EMC value as i have a seperate system strictly for connecting to the EMC tablet an everything else on another system
