### ISSUE TITLE
Refined Storage controllers breaking randomly (even if chunkloaded)

### ISSUE THREAD

**Issue by uehlbran** [raoulvdberge/refinedstorage#1602]
#### Steps to reproduce:
1. Create RS system in overworld, chunkload, also set up a wireless receiver, transmitter, network card, and interdimensional upgrade.
2. Create RS system in the end, chunkload, wireless receiver, transmitter, network card, and interdimensional upgrade.
3. Link everything up as you would to get it all working.
4.  Wait at least a couple mins and the controller will have broken.

This only happens when you link a network card to a network receiver in the over world, then you take that card and stick it in a wireless transmitter in the end with a dimensional upgrade.
...

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12.2
- Forge: 2555
- Refined Storage: 1.5.30

Does this issue occur on a server? [yes/no] SP world

#### If a (crash)log is relevant for this issue, link it here: None

[pastebin/gist/etc link here]

**Comment by uehlbran** [comment]
This was due to me not understanding a feature.

**Comment by TheIrishWolf** [comment]
Uehlbran never explained the "feature" that causes this. Could someone please explain?

**Comment by TheIrishWolf** [comment]
Ok, if anyone else has this problem, the trick is thus: the controller is breaking cause the network can only have one controller. The receiver is supposed to receive power from the transmitter and does not need an independent power source or controller.

**Comment by thehackedone** [comment]
I still don't understand the issue... mine keeps breaking i am so confused on this
