### ISSUE TITLE
Server crash and corrupts chunk upon placing a crafter

### ISSUE THREAD

**Issue by BiggyThePanda** [raoulvdberge/refinedstorage#1603]
#### Steps to reproduce:
I don't know if you can recreate it but here is what i did
1. Build a room about 24x24x4
2.place crafters on the 2 walls of the room
3.after i placed the last one on the second side and it was always the same block i retried it like 5 times
4. crash and the chunk is corrupt you can stand near it but it wont load and you crash upon going in 
if you want i can provide you a worldmap download
...

#### Version (make sure you are on the latest version before reporting):
Direwolf20 1.12 1.4.0
- Minecraft: 1.12.2
- Forge:14.23.1.2555
- Refined Storage: 1.5.28

Does this issue occur on a server? yes

#### If a (crash)log is relevant for this issue, link it here:
https://gist.github.com/SirFlip/25e2aa24680ad760bc36b6be9933b8fb
https://gist.github.com/SirFlip/f79464b0e5663427592fb4d9b7d52eab#file-latest-log-L146

**Comment by raoulvdberge** [comment]
>  make sure you are on the latest version before reporting
