### ISSUE TITLE
RS + Simply Jetpacks.

### ISSUE THREAD

**Issue by Moobien** [raoulvdberge/refinedstorage#1605]
Hey guys i have both Rs and SJ up to date and having issues with autocrafting.

Leadstone: claims that steam dynamo is missing even though pattern is correct. Jetpack must be manually crafted. Basic flux cap can autocraft.

Hardened: claims reactant dynamo and hardened flux capacitor missing. Autocrafting fails even when these 2 items are crafted as it still demands them. Manual crafting works

Reinforced: claims dynamo and flux cap for this tier plus all previous tiers missing.....

Have posted the same on their git. https://github.com/Tomson124/SimplyJetpacks-2/issues/52

**Comment by calloatti** [comment]
Don't use JEI to create the patterns that have problems. Autocraft the problematic items, use those items to create the patterns that use them.

**Comment by raoulvdberge** [comment]
RS has specific NBT tag ignore lists (internally in code) for various mods in autocrafting. It has one for Simply Jetpacks, but I guess it's out of date. I will take a look later this week.

**Comment by raoulvdberge** [comment]
I tested this on the latest SimplyJetpacks and RS version and couldn't reproduce this.

I tried crafting all the tiers incrementally (one at a time) and one dry run for the last tier with all previous tiers missing. Both worked fine.

**Comment by woutwoot** [comment]
I'm having the same (or a Similar) issue with the Stoneblock 2 modpack. Whenever trying to do autocrafting with Flux capacitors (for Simply Jetpacks 2) it always fails to pick up the capacitors being there. Both when I've crafted them manually or when they were crafted by the system.

**Comment by eschoenawa** [comment]
If you have the same issue try disabling Oredict for the pattern. It fixed the issue in my case.

**Comment by CommanderLouiz** [comment]
I disabled oredict, which allowed the dynamo crafting to work and be recognized, but RS still can't see the leadstone flux capacitor, even though I autocrafted it, and used it in the pattern for the jetpack.

**Comment by eschoenawa** [comment]
Have you created a pattern using the actual crafted flux capacitor or by using the JEI-integration to automatically fill the pattern? I found the autofilled patterns to cause some problems. This applies to the pattern for crafting the capacitor as well as the one using it. So when creating these patterns remove the autofilled capacitor and replace it with a crafted one manually.

**Comment by CommanderLouiz** [comment]
Yes, I created the pattern for the leadstone jetpack with a flux capacitor that the system crafted, manually making the pattern. I also manually made the pattern for the flux capacitor. Still can't craft the leadstone jetpack, as it still claims the capacitor is missing, despite the one i used for the pattern sitting in the system.

**Comment by yajiedesign** [comment]
same issue with CommanderLouiz,

refinedstorage-1.6.16
SimplyJetpacks2-1.12.2-2.2.15.69
ThermalExpansion-1.12.2-5.5.7.1-universal
