### ISSUE TITLE
IE Revolver doesn't work in Autocrafting

### ISSUE THREAD

**Issue by erindalc** [raoulvdberge/refinedstorage#1606]
#### Steps to reproduce:
1. Create an RS system with a crafter that has a recipe for something that uses the revolver (ex: gun turret)
2. Place all the necessary components in the RS system
3. Request 1 gun turret
4. The revolver will be shown as missing

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12.2
- Forge: 14.23.1.2583
- Refined Storage: 1.5.31
- Immersive Engineering: 0.12-76

Does this issue occur on a server? No

#### If a (crash)log is relevant for this issue, link it here:

No crash

**Comment by ineternet** [comment]
Can not reproduce in 1.5.30, is your revolver loaded? Does it have any attachments on it?

**Comment by erindalc** [comment]
Unloaded, no attachments. The revolver itself was autocrafted, it didn't recognize it after I took it out and put it back either.
