### ISSUE TITLE
crafting preview (Grid) text size is too small

### ISSUE THREAD

**Issue by Van9i** [raoulvdberge/refinedstorage#1607]
How to change text size in crafting preview (Grid)?
I am using russian language, words is very small
help?

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge:
- Refined Storage:

Does this issue occur on a server? [yes/no]
no
#### If a (crash)log is relevant for this issue, link it here:
no

**Comment by Tahakk** [comment]
Try define what is _very small_ (screenshot would be helpful). Otherwise try to get bigger GUI in Video settings, that could help.

**Comment by Van9i** [comment]
https://snag.gy/zVnmvB.jpg hope this helpful now
you can see thats only in crafting preview, not in all grid https://snag.gy/bGIz9e.jpg
and finally, if i set on Auto GUI, sure its helps, but its very huge now https://snag.gy/dw1csU.jpg

**Comment by raoulvdberge** [comment]
This is fixed in RS for 1.12.

Stop using a version that hasn't updated in over half a year.

**Comment by Van9i** [comment]
for 1.12... tell it to people who making modpacks
anyway, thanks for your help

**Comment by raoulvdberge** [comment]
Enough modpacks and mods for 1.12.
