### ISSUE TITLE
Overwriting patterns in the Pattern Grid require atleast one blank pattern existing

### ISSUE THREAD

**Issue by ineternet** [raoulvdberge/refinedstorage#1609]
#### Issue description:
The Pattern Grid contains no option to overwrite patterns when supplied with a written one that is supposed to be overwritten.

To reproduce, open a Pattern Grid, put in a written Pattern in the bottom slot and keep the top slot empty.

#### What happens:
The "write" button is disabled without any blank patterns inside.
#### What is expected to happen:
As long as theres a written pattern to overwrite, the "write" button should enable aswell.

#### Version:

- Minecraft: 1.12.2
- Forge: 14.23.1.2575
- Refined Storage: 1.5.30 (confirmed broken in 1.5.31)

This issue occurs on servers.

![Pattern Grid UI](https://i.imgur.com/xG3Oyxz.png)

**Comment by raoulvdberge** [comment]
This has been fixed by #1610.
