### ISSUE TITLE
Wireless Access from controller not transmitter

### ISSUE THREAD

**Issue by dannydjdk** [raoulvdberge/refinedstorage#161]
When placing a wireless transmitter, the range is calculated with respect to the controller, not the transmitter. So, if I run cables, and place a transmitter over 16 blocks from the controller, I can only use the wireless grid when I am near the controller, and not when I am near the transmitter.

Not sure whether to call this a bug or feature request. If the behavior is intended, then this is a feature request, though I think the general expectation would be that the signal would be transmitted from the transmitter, not the controller.

**Comment by raoulvdberge** [comment]
Ah, will fix this for the next version
