### ISSUE TITLE
add portable grid to 1.10.2 mod possible?

### ISSUE THREAD

**Issue by Wodong77** [raoulvdberge/refinedstorage#1611]
#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge:12.18.3.2511
- Refined Storage:1.2.26

I'm playing a modpack that requires Minecraft 1.10.2, and I'm sorely missing having the portable grid in the current Refined Storage for 1.10.2.  Would it be possible/worthwhile for you to add it, since it doesn't seem to be present?  (I love using it in 1.12.2, by the way)

**Comment by raoulvdberge** [comment]
No
