### ISSUE TITLE
Crafting Upgrade does not request items that have durability

### ISSUE THREAD

**Issue by Codewolf** [raoulvdberge/refinedstorage#1614]
#### Issue description:
When an item has: durability (in this use case IC2 Quad Fuel Rod), the exporter has NBT set to false, and a crafting upgrade is installed in the exporter the system does not craft these items on demand.  

The crafting works fine if the item is manually requested (ie asking it to craft x number via the Grid)

#### What happens:
No items are requested to be crafted, Crafting monitor is empty (view automated tasks = yes)

#### What you expected to happen:
Items should be crafted at the request of the crafting upgrade.

#### Steps to reproduce:
1. Create the patterns required to create a quad fuel rod (uranium), this includes both processing patterns and regular patterns.
2. point an exporter at a chest (for testing purposes), set NBT to false (compare nbt = no), regulator mode = default
...

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12.2
- Forge: 1.12.2-14.23.1.2582
- Refined Storage:1.5.30

Does this issue occur on a server? [yes/no]
Unsure, testing on local world

**Comment by raoulvdberge** [comment]
What happens if you disable metadata / damage comparison?

**Comment by Codewolf** [comment]
Sorry, forgot to include that one.  Compare damage is set to no.

The component items are available in the system but it never requests them to be crafted.

After a little testing with other items have noticed that patterns sometimes do not craft when an item has durability or damage, for example creating the IC2 Wrench always fails even with oredict on.

**Comment by raoulvdberge** [comment]
I think that is because RS checks for damage value, not metadata. I'm a little wary of making this change, as it can potentially cause a lot of problems.

**Comment by Codewolf** [comment]
Additionally something that has been selected from the 'creative' menu seems to be seen as a separate item to that which has been created via a pattern.

for example In the grid: Quad  Fuel Rod (Uranium) with full durability but created via a pattern is the seen as a different to the same item picked from the creative menu.

This particular edge case seems to be a metadata issue rather than a damage issue.

**Comment by raoulvdberge** [comment]
The Quad Fuel Rod that you want to autocraft, is it the same fuel rod as configured in the pattern?

**Comment by Codewolf** [comment]
Interestingly enough That prompted me to use the one generated from the pattern in the exporter and that worked.

This seems to be more to do with my previous comment where an item created by a pattern is recognised as a different item to one selected from the 'Creative' menu.

**Comment by raoulvdberge** [comment]
I don't believe this is an issue related to NBT data. I think it's damage value/metadata related.

If providing the exact item is the fix, I'd prefer to keep the status quo and tag this as wontfix to avoid further problems with making a drastic change like that.

**Comment by Codewolf** [comment]
No problem at all, Possibly worth mentioning/documenting that an item selected from the creative menu !== one created from a crafting pattern.
