### ISSUE TITLE
Mod Filter doesn't work on External Storage?

### ISSUE THREAD

**Issue by joselitosn** [raoulvdberge/refinedstorage#1615]
Not sure if I'm doing something wrong or that's how it is supposed to work, but placing a Filter configured with only one item from any mod only works for that specific item on an External Storage.

How to replicate:

1) Get a Controller, a Disk Drive with at least one Storage Disk, a Grid and an External Storage.
2) Connect all together with an External Storage connected to a Chest.
3) Get a Filter and select the "Mod filter" option.
4) Place any item from a specific mod (even vanilla Minecraft works).
5) Place the Filter in the External Storage and set the priority higher than the Disk Drive.
6) Get a couple of different items from the same mod and dump then into the Grid.

All items from the same mod should have appeared on the Chest, but instead I only got the one used to mark the Filter.

If you take the filter from the External Storage and place it in the Grid, it correctly shows only items from the specific mod.

Tested with the Exporter and got the same results.

- Minecraft: 1.12.2
- Forge: 14.23.1.2582
- Refined Storage: 1.5.31

**Comment by raoulvdberge** [comment]
You can't place a filter in an external storage, it only works on the exporter and importer.
