### ISSUE TITLE
Item Filter Blacklist option only works as Whitelist

### ISSUE THREAD

**Issue by joselitosn** [raoulvdberge/refinedstorage#1617]
If you set an item Filter with the Blacklist option and insert it on an Exporter or Importer, only that item will be exported or imported.

If you put the Filter on to a Grid, the item is correctly not shown.

- Minecraft: 1.12.2
- Forge: 14.23.1.2582
- Refined Storage: 1.5.31

Also related, if you set an empty Filter on a Grid, all items are still shown when no items should match a blank Whitelist.

**Comment by raoulvdberge** [comment]
That is intended behavior. Filter only adds extra filter slots, if you insert it into a machine the machine settings are used.
