### ISSUE TITLE
[feature request] Crafters as inventories

### ISSUE THREAD

**Issue by UberAffe** [raoulvdberge/refinedstorage#1618]
#### Issue description:
In minecraft 1.10 I came up with a system of automating automation by having a chest and item conduits roundrobin distribute patterns into crafters. In minecraft 1.12 (RS 1.5.30) this no longer seems to be possible.

#### What happens:
I tested with RS exporters, thermal dynamics itemducts, simple storage network, minecraft hoppers, xnet, and integrated dynamics/tunnels. None of them connect to the crafter or consider it a valid inventory.

#### What you expected to happen:
Though the use case is minor I would want the ability to use some form of item transport to insert into the crafters again.

#### Steps to reproduce:
1.
2.
3.
...

#### Version (make sure you are on the latest version before reporting):

- Minecraft:1.12.2
- Forge: 14.23.1.2573
- Refined Storage: 1.5.30

Does this issue occur on a server? [yes/no]

#### If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here]

**Comment by raoulvdberge** [comment]
(make sure you are on the latest version before reporting):
