### ISSUE TITLE
Oredict Autocrafting manipulates items in your system

### ISSUE THREAD

**Issue by ineternet** [raoulvdberge/refinedstorage#1619]
#### Issue description:
Setting a pattern to ore dictionary and then using it in a crafter causes RS to output ore dictionary equalivants into machines, not the actual stuff you have in your system, effectively changing the item (if they have the same oredict) - similar to a Forge Lexicon or such.

#### What happens:
The RS system outputs ore dictionary equalivants of items into ore-dict pattern-using crafters.

#### What you expected to happen:
The RS system should *find* the next best oredict item to use thats available in your system, not convert it.

#### Steps to reproduce:
1. Make a pattern with any item you dont have in your system (e.g. Red Sand instead of Sand), set it to oredict mode.
2. Put this pattern in a crafter and utilize it.
3. Check your machine. It should now have red sand in the input inventory, even if you don't have any red sand.
...

#### Version:

- Minecraft: 1.12.2
- Forge: 14.23.1.2575
- Refined Storage: 1.5.30

This issue occurs on servers.

**Comment by ineternet** [comment]
Upon further investigation, this happens when the educt items are in a drawer from Storage Drawers, so it could be a problem on their side, or a bug with the External Storage block.

**Comment by Paril** [comment]
StorageDrawers has automatic conversion of OreDict equivalents. This is probably on their end.

**Comment by DnielMC** [comment]
It gets even worse, if you don't have that oredict item at all, it uses something completely different.
Like Invar instead of Silver when making Electrum.

Right now, my solution is to remove the Ore dict tag in the Recipes and that seems to work for now.

**Comment by raoulvdberge** [comment]
Is this a Storage Drawers issue?

**Comment by Paril** [comment]
I've never seen it pull invar instead of nickel.. Storage drawers used to have automatic oredict conversion I think but now it's an upgrade item. Can you list the versions, mod that is supplying the invar and nickel, and any applicable crafttweaker scripts that add them to oredict?

**Comment by raoulvdberge** [comment]
Storage drawers integration has been removed and is now interacted with as a regular inventory, so this can be closed.
