### ISSUE TITLE
[Issue] Crash while pulling resonnant Ore from storage

### ISSUE THREAD

**Issue by Moustik2002** [raoulvdberge/refinedstorage#162]
Hi,

here is the crash log : http://pastebin.com/GBvnijmm

By the way i have downgraded to 0.8.3 because the fix to resolve the storage drawers is working but as soon as you close and restart your SP save, the link between external storage and drawer controller doesn't work anymore (it needs the external storage to be removed and put back in place to work again  :'( )

Anyway you're doing an amazing job keep going ;)

**Comment by raoulvdberge** [comment]
This is already fixed for the next version (i've reworked the searchController stuff)

Thanks for reporting anyway
