### ISSUE TITLE
Manually set non-processing crafting output

### ISSUE THREAD

**Issue by KirbyQK** [raoulvdberge/refinedstorage#1620]
#### Steps to reproduce:
1. Go to a pattern grid with a blank pattern ready
2. Put 9 charcoal filling each black spot for a non-processing recipe
3. Pattern grid fills in the output
...

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12.2
- Forge: 8.0.99.99 or 14.23.1.2566 *I'm using the latest version of the DW20 1.12.2 pack
- Refined Storage:1.5.28 *Addons  0.2

Does this issue occur on a server? No

#### If a (crash)log is relevant for this issue, link it here:

Nope!

**Comment by raoulvdberge** [comment]
You have a recipe conflict then. Some mod is overriding the charcoal block recipe. Not an RS problem.
