### ISSUE TITLE
[1.12.2] Items Being Voided - Mod Interaction w/ Not Enough Wands 

### ISSUE THREAD

**Issue by SnowShock35** [raoulvdberge/refinedstorage#1622]
#### Issue Details

- Minecraft 1.12.2
- Minecraft Forge 14.23.1.2587
- Refined Storage 1.5.31
- Other Mods:
  - Not Enough Wands 1.12-1.6.0

#### Issue Description

Using the displacement wand on Refined Storage's Crafter Blocks leads to loss of inventory (of patterns)

###### What should happen?

The inventory is retained when being displaced (NBT?)

###### What actually happens?

The patterns are voided.

###### Steps to Reproduce

1. Place down a Refined Storage Crafter
2. Place some patterns in it
3. Close the GUI and use the displacement wand on the tile
4. Re-Open the GUI to find the patterns are no longer there

*** 

Issue reported to romelo333/notenoughwands/issues/72.

**Comment by raoulvdberge** [comment]
Don't use the displacement wand on RS blocks. RS stores its data off the tile entity, and the displacement wand just takes the TE data while no relevant data is there.

**Comment by SnowShock35** [comment]
I obviously know not to do this - you know me. However, since your mod handles it the way it does I'm hoping @McJty / @Romelo333 will add a blacklist for the displacement wand. Or to disallow displacement of tiles via a config.

**Comment by raoulvdberge** [comment]
Or I could add integration with that mod if it were possible, but it's not

**Comment by raoulvdberge** [comment]
(Also when I said "don't use" I was not talking about you, but about the original reporter of that bug)

**Comment by SnowShock35** [comment]
Kinda figured that was the case. Just ensuring it was though. As you know I don't even play this Mincecraft :P

**Comment by McJty** [comment]
What is the registry name of this block so I can add it to the blacklist? Thanks

**Comment by raoulvdberge** [comment]
You should block every RS block since they all use the same system.

**Comment by McJty** [comment]
What's your modid?

**Comment by raoulvdberge** [comment]
`refinedstorage`
