### ISSUE TITLE
I have a feature suggestion for refined storage

### ISSUE THREAD

**Issue by joshuasuperboy** [raoulvdberge/refinedstorage#1623]
I want to know if you can implement another wireless grid. This grid can be a wireless crafting grid that has a a couple new features. That grid can have tabs for the certain things. The first tab can be the wireless crafting grid. The second tab can be a wireless fluid grid. The last tab can be a wireless crafting monitor. The way how to get the grid can be like this. First you craft the wireless grid. Then you craft the wireless crafting grid. Then you craft the wireless crafting monitor. Then you craft the wireless fluid grid. Then you can combine the wireless crafting grid, wireless fluid grid, and the wireless crafting monitor in the soldier. It’s so you don’t have to carry multiple grids that fills up inventory slots. Can all of that be combined into one grid? If it can that will be great. I think you would like that new feature to be implemented into refined storage. I came up with that my self hope you like that idea.

**Comment by raoulvdberge** [comment]
No, sorry. I thought about this before and decided to not do it.
