### ISSUE TITLE
I want to say something

### ISSUE THREAD

**Issue by joshuasuperboy** [raoulvdberge/refinedstorage#1625]
I can see why you don’t want to make that all in one wireless grid that I suggested. I was almost done putting the first two items in the recipe. I just noticed how long it will take. So yea I can see why you did not want to do it. Also I just gave up it’s way to much to do.

**Comment by raoulvdberge** [comment]
Please, don't make a new issue for every sentence you want to say.

Head over to the Discord instead:
https://discord.gg/ta8Uzm8
