### ISSUE TITLE
Defrag/Transfer items from smaller Storage Blocks to bigger ones?

### ISSUE THREAD

**Issue by Woif1990** [raoulvdberge/refinedstorage#1628]
Would it be possible to add the ability to use the storage blocks in the disk manipulator? I went straight with those since I liked how they looked, but when it came time to upgrade to bigger ones, it was a massive pain to move everything into the bigger ones.
Unless I missed some easier other way of doing it at least.

Thank you very much!

**Comment by raoulvdberge** [comment]
No, sorry.

**Comment by Enverex** [comment]
In the same vein then; how are you supposed to move items out of storage blocks? They don't work in the disk manipulator and there doesn't appear to be any way to just "export everything" out of an RS system so you can't just put them on their own system and pipe everything out.
