### ISSUE TITLE
JEI autoselect does not autoselect

### ISSUE THREAD

**Issue by Trcx528** [raoulvdberge/refinedstorage#163]
Launching a minecraft and opening a grid with the JEI Autoselect option, does not auto select JEI search bar.  Subsequent openings of the grid do auto select as expected.  Re logging does not cause this issue again, only when initially launching minecraft.  I suspect something just needs to be initialized on the client before opening the first grid.

**Comment by raoulvdberge** [comment]
JEI autoselect is meant to autoselect the grid search bar and synchronize the search query with JEI, not for actually autoselecting the JEI search bar...

**Comment by Trcx528** [comment]
I recognize that.  I guess I failed to properly described the issue.  

On the first grid opened after the minecraft client launching, neither search bar is selected.  An additional click is required.  It acts as if the mode is JEI Synchronized (without auto select).  Subsequent grid opens do not require this additional click.

**Comment by raoulvdberge** [comment]
I cannot reproduce this, unfortunately

**Comment by Trcx528** [comment]
I'll try to put together a video or something.

**Comment by Trcx528** [comment]
I too am struggling to reproduce this as well.  Perhaps I don't understand the conditions well enough or a recent update fixed this....

**Comment by raoulvdberge** [comment]
Hmmm, maybe, after all, it was just an *i l l u s i o n*
