### ISSUE TITLE
Need some help here

### ISSUE THREAD

**Issue by Killaheala** [raoulvdberge/refinedstorage#1632]
#### Steps to reproduce:
1.
2.
3.
...

#### Version (make sure you are on the latest version before reporting):

- Minecraft:
- Forge:
- Refined Storage:

Does this issue occur on a server? [yes/no]

#### If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here]

**Comment by raoulvdberge** [comment]
That is not an RS issue.
