### ISSUE TITLE
Storage Blocks should be set to "off" by default.

### ISSUE THREAD

**Issue by Nightcaste** [raoulvdberge/refinedstorage#1633]
#### Issue description:
Storage blocks should be in a disabled state when placed, and require UI interaction before the system starts putting items in it.

#### What happens:
It just starts filling as soon as it's placed.

#### What you expected to happen:
I would expect to be able to set the filters and such so I have a given block *only* holding the given item I want it to hold.

#### Steps to reproduce:
1.  Place a storage block connected to your network
2.  Watch it fill up with items you don't want in there
3.  Frown
...

#### Version (make sure you are on the latest version before reporting):

- Minecraft:  Multiple
- Forge: Multiple
- Refined Storage: Multiple

Does this issue occur on a server? [yes/no] Both

#### If a (crash)log is relevant for this issue, link it here:

N/A

**Comment by raoulvdberge** [comment]
No, not allowing items until the GUI is opened is just plain confusing and would lead people to think the mod is broken or buggy.

**Comment by Nightcaste** [comment]
That's disappointing to hear, because I don't think it would be confusing at all.  I mean... Patch notes are a thing for a reason.  It would certainly be better than the frantic rush to get it set up before it fills up with items or fluids that you don't want in it, because I've had that interfere with builds in every version of RS that I have ever used.

**Comment by Tahakk** [comment]
It would be nice to have some kind of delayed blocking at least at fluid storage blocks, where most of the times you are building storage with intention to store just one fluid in it.

So after connecting fluid storage without any filters to network have some kind of delay (lets say 5 seconds) before it start filling up.

Cheers

**Comment by raoulvdberge** [comment]
No.
