### ISSUE TITLE
Error java.lang.NullPointerException: Rendering screen

### ISSUE THREAD

**Issue by JoelC14** [raoulvdberge/refinedstorage#1634]
#### Issue description:
When I open the new version of Labymod Minecrafft closes me
#### What happens:
Minecraft closes
#### What you expected to happen:
That the Labymod was very good
#### Steps to reproduce:
1.
2.
3.
...

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12.2
- Forge: 
[crash.txt](https://github.com/raoulvdberge/refinedstorage/files/1649807/crash.txt)
1.12.2
- Refined Storage:

Does this issue occur on a server? [yes/no]
No
#### If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here]

**Comment by raoulvdberge** [comment]
I have no idea why you think this is an RS issue.
