### ISSUE TITLE
Autocrafting with Catalysts

### ISSUE THREAD

**Issue by 7OOTnegaTerces** [raoulvdberge/refinedstorage#1635]
#### Issue description:
Pattern maker has no way to register catalysts, items (generally from mods) that are used in a recipe but not consumed to make the output.  Even thought the catalyst need only be present in the recipe for it to work and won't actually be consumed, RS doesn't know this, and so demands a separate catalyst for each iteration of the recipe.

#### What happens:
I discovered this when attempting to autocraft Prudentium Essene from Mystical Agriculture.  This recipe uses four Inferium Essenes (the elements to be consumed in making the Prudentium( and an (Master) Infusion Crystal (the catalyst).  If I only want to make one Prudentium at at time, this recipie works, but if I want 64 then RS demands 64 Infusion Crystals because it doens't know that it can just keep on re-using the same crystal in each recipe.
Project E is another example of a mod that has a catalyst element in many of its recipes.

#### What you expected to happen:
The pattern maker needs to be upgraded with a way to flag or identify catalysts so it knows that that element won't be consumed in the recipe and will be available for future iterations.

#### Steps to reproduce:
1. Install RS and Mystical Agriculture or Project E
2. Set up autocrafting with a recipe in either one using Infusion Crystals or the Philosopher's Stone.
3. Attempt to autocraft more than one copy of said recipe at a time, with only one Infusion Crystal or Stone in the inventory.
...

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12.2
- Forge: Latest (I don't want to stop MC just to check this since it's clearly not related to this issue)
- Refined Storage: 1.5.25

Does this issue occur on a server? [yes/no]
Only played in Single-Player, but I'd assume so...

#### If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here]

**Comment by raoulvdberge** [comment]
Refined Storage does have code to detect catalysts. Flagging is not required.

**Comment by 7OOTnegaTerces** [comment]
How???
What do I need to do?

**Comment by 7OOTnegaTerces** [comment]
If the catalyst detection code is all internal (i.e. you note what mods have what catalysts and register it in your mod), might I suggest a supplemental user end augmentation that allows them to register catalysts as well so that you don't have to be solely responsible for making catalysts work with your mod, there by allowing you to focus on more important things than every last new mod that comes out?

**Comment by raoulvdberge** [comment]
The catalyst code is internal, but doesn't require mod specific checks. The crafting task calculation handles it by checking the remainder items in the recipe.

**Comment by 7OOTnegaTerces** [comment]
Good dynamic solution!!!  Then something must be broken in your catalyst code for Mystical Agriculture.  I just did a double check with Project E, and your catalyst check does seem to work there, so it's just this mod.  I am trying to use the Master Infusion Crystal (it was the first thing I worked towards getting), since it doesn't have a usage limit (which also begs the question of if your mod can recognize that a regular Infusion Crystal doesn't have enough uses left for the requested number of autocrafts and can intelligently autocraft another one when needed if it has the recipe and materials.  If it doesn't, can it show the user how many autocrafts it can perform with the current crystal?).

**Comment by raoulvdberge** [comment]
It must be a bug, indeed.

**Comment by tyler489** [comment]
Works correctly in 1.5.31.

**Comment by raoulvdberge** [comment]
No longer relevant with the new autocrafting

**Comment by xiagu** [comment]
The Mystical Agriculture example works better now, but isn't perfect. The crafting system recognizes that it can reuse the Master Infusion Crystal when upgrading 1 tier (i.e., Inferium -> Prudentium) but if I request it to upgrade 2 tiers at once (Inferium -> Prudentium -> Intermedium) it wants 2 Master Infusion Crystals.

I could file a new bug if that'd be better.

**Comment by kamigi** [comment]
Hi there, i am using ATM6-1.7.11 modpack, with refined storage version 1.9.15 (with addons 0.7.3 and also rsrequestify 1.16.5-2.1.3) and i have exactly the same issue than described in first post years ago...
Mystical Agriculture Master Crystal is required more than one time on a stack request ( for example 64 )
I even tried to process it with different options available, and it's not working ...
Are you sure the problem is solved ? 

Thanks a lot for your reading and answer!

Kamigi
