### ISSUE TITLE
Oredict cannot be specified for specific items

### ISSUE THREAD

**Issue by Saklad5** [raoulvdberge/refinedstorage#1636]
#### Issue description:
Oredict can only be toggled for all items at once in a vanilla crafting recipe, rather than specific ingredients.

I recognize that adding customization like this could introduce substantial complexity to the existing interface, so I understand if you decide not to implement it. Since no one else appears to have suggested such a feature, however, I would like to propose it.

#### What happens:
A cake recipe can only use wheat, rather than using flour (which requires a crafting step), if I want other components to be oredicted. The desired behavior is technically possible, but only by making a recipe for literally every combination of item that could be used in the recipe.
#### What you expected to happen:
When making a cake with Refined Storage and Pam’s HarvestCraft, I want Flour to always be used (despite being oredicted with Wheat). However, I want Soy Milk to be used if present before crafting Fresh Milk from the Milk stored as a fluid, and I want Eggs to be used if present before crafting Tofeeg.

#### Steps to reproduce:
1. Create and set a crafting pattern that has more than one oredicted component, of which only some should use OreDict.
2. Request the product.

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12.2
- Forge: 14.23.1.2585
- Refined Storage: 1.5.31

**Comment by ineternet** [comment]
This seems pretty complicated, considering you need buttons/a functionality for every crafting slot. Could you propose how it might look in the pattern grid?

**Comment by Saklad5** [comment]
While Oredict is checked, a button for choosing slots would appear. When clicked, a blank 3x3 grid (the crafting grid) would appear, and you could click slots to highlight them and mark them as using oredict). You could then exit that and fill in the crafting recipe as normal.

I’m no UX specialist, but that’s my best shot.

**Comment by raoulvdberge** [comment]
No.
