### ISSUE TITLE
Vanilla crafting with a fluid is not prioritized over processing an item

### ISSUE THREAD

**Issue by Saklad5** [raoulvdberge/refinedstorage#1637]
#### Issue description:
Given two recipes for an item, one that requires an item crafted from a bucket of fluid and one that requires an item processed from another item, the processing recipe is used.
#### What happens:
I have two recipes for making a cake: one which needs Fresh Milk (craftable from a bucket of Milk, which is stored as a fluid in the system), and one which needs Soy Milk (a byproduct of making Tofu in a Presser). When neither Fresh Milk nor Soy Milk is in the system, Soy Milk is produced for the crafting request.
#### What you expected to happen:
Since vanilla crafting is always faster than processing, I expected Fresh Milk to be created and used.
#### Steps to reproduce:
1. Create a vanilla crafting recipe for an item that requires an item crafted from a bucket of fluid.
2. Create a vanilla crafting recipe for the same item that requires an item crafted using a processing recipe and an item.
3. Ensure that neither of the items that are directly required already exist in the system, but the components for making them do exist.
4. Request the product.

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12.2
- Forge: 14.23.1.2585
- Refined Storage: 1.5.31

**Comment by raoulvdberge** [comment]
#1557

**Comment by Saklad5** [comment]
This isn’t quite the same. I read that issue, and it seems to be about crafting buckets of a fluid you have stored. This is about crafting an item (with a processing recipe) that can be used for a recipe instead of  crafting another item (with a crafting recipe and a fluid) that can be used.

**Comment by tristo7** [comment]
Seeing this same issue for destabilized redstone dust.

The system does not use the crafted destabilized redstone after creating it through a magma crucible.

Minecraft 1.12.2
Forge 14.23.2.2627
Refined Storage 1.5.32

This is version 1.10 of the Direwolf20 pack.

**Comment by raoulvdberge** [comment]
I'm going to redo this for 1.6.x, so this can be closed.
