### ISSUE TITLE
Ticking Block Entity Crash

### ISSUE THREAD

**Issue by Knuxer** [raoulvdberge/refinedstorage#1638]
#### Steps to reproduce:
1. Unsure, it's an issue that suddenly revealed itself
2.
3.
...

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12.2
- Forge: 14.23.1.2587
- Refined Storage: 1.5.31

Does this issue occur on a server? no
#### If a (crash)log is relevant for this issue, link it here:

https://pastebin.com/DCqnTEw2

**Comment by raoulvdberge** [comment]
Duplicate of #1567
