### ISSUE TITLE
Disk Drive with more than MAX_INT of storage on combined disks shows wrong value

### ISSUE THREAD

**Issue by Lordmau5** [raoulvdberge/refinedstorage#1639]
#### Issue description:
If you have disks in the Disk Drive that exceed `MAX_INT` of total storage, it wraps back to `MIN_INT` showing negative values in the GUI.

#### What happens:
![image](https://user-images.githubusercontent.com/1345036/35306530-83d1f090-009e-11e8-997e-8e6c5c5326b7.png)

#### What you expected to happen:
It should show a properly formatted value, but it can't due to exceeding `MAX_INT`.
A suggestion would be to use `long` for solely this calculation (perhaps more if it's needed).

#### Steps to reproduce:
1. Use a mod like [Quantum Storage](https://minecraft.curseforge.com/projects/quantumstorage) that adds disks that exceed `MAX_INT` if combined
2. Place 2 in the Disk Drive

#### Version (make sure you are on the latest version before reporting):
- Minecraft: 1.12.2
- Forge: 14.23.1.2599
- Refined Storage: 1.5.31

#### Does this issue occur on a server?
- Yes
- No

**Comment by Saklad5** [comment]
I’m a fan of BigInteger myself.

**Comment by Lordmau5** [comment]
I just read up on [BigInteger](https://docs.oracle.com/javase/7/docs/api/java/math/BigInteger.html) myself and it seems to be a better fit.

Also, I just realized that this would additionally need to address the Grids to show the value in BigInteger, too.
![image](https://user-images.githubusercontent.com/1345036/35355242-fdcc7196-014c-11e8-97c4-74a4084b8d16.png)

**Comment by raoulvdberge** [comment]
Long will do fine, I don't see why BigInteger is needed here.

**Comment by raoulvdberge** [comment]
Will tag this as wontfix as this is not possible to do in RS due to ItemStack's being limited to int size.
