### ISSUE TITLE
Retrieval of items

### ISSUE THREAD

**Issue by abdullamu** [raoulvdberge/refinedstorage#1640]
I was wondering why did you sperate the interface from as into two machines crafter and interface?
Plus why interface is slow at taking items ? (I understand you can place speed +stacking upgrade but it's not fast enough as ae2 one where its instant by default which is useful if you are dumping huge amount of items in big packs especially skyblock packs where you need lot of resources input.)

I'm going to list the advantages of one interface and crafter.
1. Easy to use and setup with zero confusion.

2.Space if I want to make compact build its great, especially if you need more than one side of machines for other uses e.g. i use interfaces on my pulverizer on all its side so I don't need extra pulverizer and make the world lagger than its. Or I place machines next to each other wall behind them floor under them so my only accessible sides are back and below machines one for energy other for crafter now how I'm going to output items ?!.

3.lot of machines might cause lag in huge world so less machines the better.

4.Another easy of setup since the machines nowadays uses one side to input and output like thermal expansion, techreborn and ender io.

Plus lot more .

I hope you consider this.
Thank you

**Comment by raoulvdberge** [comment]
You are not playing AE2. If you want AE2 features, play AE2.
