### ISSUE TITLE
crafting grid began storing air for some reason

### ISSUE THREAD

**Issue by coolgaza16** [raoulvdberge/refinedstorage#1642]
#### Steps to reproduce:
1. unsure as just noticed it this afternoon
2.
3.
...

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12.2
- Forge: 14.23.1.2560
- Refined Storage: 1.5.25

Does this issue occur on a server? [yes/no] no

#### If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here]

**Comment by raoulvdberge** [comment]
> (make sure you are on the latest version before reporting)
