### ISSUE TITLE
Server Crash on Disk Manipulation/Controller removal

### ISSUE THREAD

**Issue by PiggyWhiskey** [raoulvdberge/refinedstorage#1645]
I've got an extensive Refined Storage system in an RF Tools Void Dimension.
Large quantities of items are stored in Storage Drawers using a single External Storage.
I have 4 64k Disks that I occasionally run through the Disk Manipulator when I add a new Drawer.
Recently the local Server I've got running is crashing when putting disks in the Manipulator,
To check if it was an issue, I tried to remove the controller and see how the system goes, and it still crashed.

DW20 1.12 Version 1.80.
Refined Storage Version 1.5.31
Forge Version 14.23.1.2601

crash-report: http://puu.sh/zbbhh/8e7b2668cb.txt
latest.log: http://puu.sh/zbbib/543c3a8932.log
fml-junk-earlystartup.log: http://puu.sh/zbbku/4e08358b77.log

**Comment by raoulvdberge** [comment]
This is not an RS issue but an RFtools issue.
