### ISSUE TITLE
Unknown server tick loop crash

### ISSUE THREAD

**Issue by jc2xs** [raoulvdberge/refinedstorage#1648]
Issue description:  Server crashed when starting with an exception in the server tick loop.  Mod pack is EOD: Newcomer - v1.1.1

What happens:  Server crash started right after the nightly reboot.  Restoring the server from a backup about 24 hours prior to the crash fixed the issue.

Steps to reproduce:  It is due to something one of the players did in the world.  I can provide a copy of the world download if needed.

Version (make sure you are on the latest version before reporting):
- Minecraft: 1.12.2
- Forge:  14.23.1.2583
- Refined Storage: 1.5.31 

Does this issue occur on a server? yes

#### If a (crash)log is relevant for this issue, link it here:
https://pastebin.com/Dng9f6U9

Anyway, I hope this helps.  Normally if I have a block location I can the issue without resorting to backup.  But there is no indication of where the issues is.  Just a general crash in the server tick loop.

**Comment by ineternet** [comment]
What version of MCMultiPart are you using?

**Comment by jc2xs** [comment]
MC Multipart is 2.4.1.  You think that might be the issue?

**Comment by raoulvdberge** [comment]
I don't think.

**Comment by raoulvdberge** [comment]
In fact, I know what causes this. I will take a closer look later.

**Comment by jc2xs** [comment]
Cool.  Let me know if you need anything more from me.  I saved a copy of the world off of the server that has this issue.  So I can reproduce the crash if needed.
