### ISSUE TITLE
Filter disappears when breaking blocks where it is in. 

### ISSUE THREAD

**Issue by fekke** [raoulvdberge/refinedstorage#1649]
#### Issue description:
Filter item disappears when taking down blocks where it can fit, ex. Disk Drive, Exporter, Storageblock.

#### What you expected to happen:
To get my filter back, as i got the Speed Upgrades and Stack Upgrades when i broke the block. 

#### Steps to reproduce:
1. Put filter in Disk Controller or Storageblock
2. Create a Filter and set in slot
3. Break Disk Controller or Storageblock
...

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12.2
- Forge: 14.23.1.2587
- Refined Storage: 1.5.31

Does this issue occur on a server? [yes/no]
No

#### If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here]

**Comment by raoulvdberge** [comment]
intended
