### ISSUE TITLE
External Storage - Can't se items

### ISSUE THREAD

**Issue by marduvGitHub** [raoulvdberge/refinedstorage#165]
Hi
In the lastes update 0.8.5, I can't se the items form a chest or Draw Controller in Storage Drawers mod.
Extrernal Storage do draw power and show storage capacity.

I did update form 0.8.3 so I can't tell if this happen in between, but it works in 0.8.3

**Comment by marduvGitHub** [comment]
After several hours it works, I have not done any canges to the setup....

**Comment by marduvGitHub** [comment]
It did not show all items, so I did try remove the Storage Drawers controller now and it stil show the items...
But the External Storage do update and says there is none items to find.

**Comment by raoulvdberge** [comment]
This is already fixed in dev
