### ISSUE TITLE
Wireless Grid items ignore player distance

### ISSUE THREAD

**Issue by ineternet** [raoulvdberge/refinedstorage#1654]
#### Issue description:
Opening a Wireless Grid of any kind requires a nearby wireless transmitter. You can distance yourself from the nearest transmitter by falling, getting damaged, pushed, etc.

#### What happens:
The grid remains open and useable.

#### What you expected to happen:
The GUI should close when you leave the range of the transmitter.

#### Steps to reproduce:
1. Have a functional wireless grid.
2. Open it in valid range.
3. Push yourself - pistons, other players, etc.

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12.2
- Forge: 14.23.1.2575
- Refined Storage: 1.5.30

This occurs on servers.

**Comment by raoulvdberge** [comment]
This is intended, and doesn't really matter.
