### ISSUE TITLE
Location inaccessible when breaking disk drive with drives

### ISSUE THREAD

**Issue by Aphyxia** [raoulvdberge/refinedstorage#1655]
#### Issue description:
This error and disconnect https://i.gyazo.com/e095de303aa896ff92c2bcaec153dab2.png
when broke disk drive with disks. 
Restarting server doesn't fix it.
When another player approached the location, they were disconnected with the same error.
Me, being away from the location, was unaffected.

Repeating this from a server backup while first taking the drives out of the disk drive was fine.

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12.2
- Forge: 2608
- Refined Storage: refinedstorage-1.5.31

Does this issue occur on a server? [yes/no]
yes

**Comment by raoulvdberge** [comment]
Not an RS issue, some external mod is causing it.
