### ISSUE TITLE
[1.12.2] Stalls with large amounts of patterns

### ISSUE THREAD

**Issue by Paril** [raoulvdberge/refinedstorage#1656]
Profiling the 1.12.2 crafting issue with Sampler atm, but it also generated these stall reports that may be of use to you:

[stall-2018-02-03_23.10.25-1.txt](https://github.com/raoulvdberge/refinedstorage/files/1692458/stall-2018-02-03_23.10.25-1.txt)
[stall-2018-02-03_23.11.25-2.txt](https://github.com/raoulvdberge/refinedstorage/files/1692459/stall-2018-02-03_23.11.25-2.txt)
[stall-2018-02-03_23.09.55.txt](https://github.com/raoulvdberge/refinedstorage/files/1692460/stall-2018-02-03_23.09.55.txt)

This is probably due to Modern Skyblock 2 having a crapload of OreDict entries, but, who knows!

**Comment by raoulvdberge** [comment]
Need sampler files..

**Comment by Paril** [comment]
[stall-2018-02-04_21.38.54.txt](https://github.com/raoulvdberge/refinedstorage/files/1693659/stall-2018-02-04_21.38.54.txt)

This is the best I can give you because I can't do a Sample as the game is loading. I might be able to capture a profile from Netbeans by hand.

**Comment by raoulvdberge** [comment]
Sorry, I really need a profiler report.

**Comment by Paril** [comment]
There's no way to use Sampler to generate a report at startup, but it's easy to reproduce with recipes that have a lot of different paths/oredict entries.
