### ISSUE TITLE
[Suggestion] Fluid Regulator?

### ISSUE THREAD

**Issue by Paril** [raoulvdberge/refinedstorage#1659]
Would be amazing if the Regulator Mode would regulate fluids by specifying how much of the fluid should be kept in stock. Would make automating alloys with Tinkers for instance much less painful.

**Comment by Saklad5** [comment]
I currently accomplish this with Thermal Foundation endgame fluids by using Detectors next to Exporters attached to dedicated Magma Crucibles. I imagine a similar system would work for a series of minimum-size Smelteries.

Speaking of which, if you have Thermal Expansion installed, you can use the Induction Smelter to produce Tinker’s Construct alloys.

**Comment by Saklad5** [comment]
This feature would necessitate an interface change to specify the amount of mB to keep in stock, unless you want to click a thousand times per bucket. I think that’s overdue anyway, since specifying the amount of items to keep in stock is also tedious.

**Comment by ineternet** [comment]
Clicking a thousand times to get a bucket in the regulator mode could quite indeed be a pain. There would be the need to implement either more keybinds for fluids (shift - 1000 mB, ctrl 100 mB (as an example)), or only allow for exactly buckets to be regulated.

**Comment by Saklad5** [comment]
Alternatively, there could be a keybind that allows you to click on an item or fluid to bring up a text box, in the same way that requesting a crafting operation brings up such a box. This would have the added benefit of allowing non-integer levels to be set. IndustrialCraft 2’s UU-Matter uses nanobuckets, for example.

**Comment by Paril** [comment]
@Saklad5 Thanks for the suggestion! Unfortunately the mod pack I'm playing with only allows Enderium to be made by the Smeltery. I don't think any mod has any sort of regulator that will work for only allowing, say, 16 mb of a fluid at a time through. I thought maybe Integrated Tunnels maybe but I don't think even it supports this, even with it's down-to-the-wire operators.

**Comment by raoulvdberge** [comment]
Wontfix. I'm planning to remove this feature for 1.13.

**Comment by Saklad5** [comment]
I thought it was getting changed to be an upgrade, not removed entirely.
