### ISSUE TITLE
JEI Paging

### ISSUE THREAD

**Issue by Trcx528** [raoulvdberge/refinedstorage#166]
I suppose this could be a bug in JEI, but I suspect it is in RS.

The easiest way to reproduce this bug is to open your inventory and scroll to the last page of JEI.  Next open a grid (that has synchronized JEI search) and search for something, lets say stone.  In my FTB unstable world there are a total of 41 pages of items, searching for stone returns only 4 pages.  Since we scrolled to the last page (41), JEI is now displaying page 41 of 4, which results in no items being displayed.  

Attempting similar searches directly in the JEI search box (even from within RS grids) resulted in proper behavior, leading me to think that RS needs to raise some kind of event in JEI, or manually reset the current page to page one after searching.

**Comment by raoulvdberge** [comment]
This is a JEI bug, `IItemListOverlay#setFilterText` has to handle that.
