### ISSUE TITLE
Get items for free glitch

### ISSUE THREAD

**Issue by Diamond45123** [raoulvdberge/refinedstorage#1660]
#### Steps to reproduce:
1. Get a pattern
2. Make a recipe using the Pattern Processing Encoder
3.And now put it in a crafter so it appears in the wireless grid
4. so it says [Craft] now remove the pattern from the crafter and boom you have a free item in your storage system

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.11.2
- Forge: 2563
- Refined Storage: latest version

Does this issue occur on a server? [yes/no] dont know

#### If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here]

**Comment by raoulvdberge** [comment]
1.11 is unsupported.

**Comment by Diamond45123** [comment]
I know this isn't a place for questions but why isn't my crafter inserting items to mekanism's metallargic infuser
