### ISSUE TITLE
Crash when rotating an External Storage

### ISSUE THREAD

**Issue by Alex-hawks** [raoulvdberge/refinedstorage#1661]
#### Issue description:
I was rotating an External Storage, and it pointed at the Interface below it when I wanted the External Storage to point up, and the aforementioned Interface was the External Storage's sole link to the Controller for the network it was on
#### What happens:
It crashes.
#### What you expected to happen:
It to not crash, probably by disconnecting from the network, then rotating, then reconnecting to the network as a new node with the existing location and configuration data.
#### Steps to reproduce:
1. Place down Interface
2. Connect Interface to powered Controller 
3. Place External storage above Interface pointing at a chest
4. Put stuff in Interface's import slots
5. Decide that you want to rotate the External Storage, and accidentally make it point at the Interface

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12.2
- Forge: 14.23.1.2554
- Refined Storage: 1.5.31

Does this issue occur on a server? yes

#### If a (crash)log is relevant for this issue, link it here:
https://gist.github.com/Alex-hawks/39300520fe44c384a43988824ea9e833

#### Additional Data:
It was not a world corrupting crash, and [this](http://puu.sh/ziYTP/2e2740f6b9.png) is what it looks like when I load back into the world. And [this](http://puu.sh/ziYYq/6a95ced2de.png) is a screenshot showing the filter data for the External Storage.

**Comment by raoulvdberge** [comment]
Fixed in 1.6
