### ISSUE TITLE
[MC 12.2] Fake player?

### ISSUE THREAD

**Issue by ilFau** [raoulvdberge/refinedstorage#1663]
#### Issue description:
On server I have a mod for second ‎authentication. I have already had a problem with this mod, whose was blocking others mod (like turtle of computercraft). The issue was solved with know the name of mod's fake player.
Does your mod use a fake player? If it does, what's the name?

#### What happens:
Constructor don't place/drop item

#### What you expected to happen:
Constructor place/drop item

#### Steps to reproduce:
1. Install Authmod and RefinedStorage
2. Start server
3. Try the constructor

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12.2
- Forge: 2575
- Refined Storage:

Does this issue occur on a server? yes

Thank you for your work!

**Comment by raoulvdberge** [comment]
It uses the default Forge fake player.
