### ISSUE TITLE
Storage Disk Not Completely emptying out

### ISSUE THREAD

**Issue by Bruches** [raoulvdberge/refinedstorage#1667]
Version (Make sure you are on the latest version before reporting):
Minecraft: 1.12.2
Forge:  14.23.1.2601
Refined Storage: 1.5.31
Does this issue occur on a server? Yes, on a FTB Direwolf 20 Server. Version 1.8

If a (crash)log is relevant for this issue, link it here: no crash log

#### Issue description:
When I place several of my 4k storage disks in the disk manipulator I cannot get it to dump everything on the disk into the system. One disk has 1/4000 and the other 2/4000

#### What happens:
The disk just stops at a certain point and moves from the "in" slot to the "out" slot. 

#### What you expected to happen:
Dump everything in the disk into my system, letting me get the 4k storage part and the storage housing

#### Steps to reproduce:

1. Place full 4k disk into disk manipulator in the "in" section. Use default settings in the disk manipulator. 
2. Insert 1 stack upgrade and 3 speed upgrades while items are already in progress of moving.

At a certain point the disk stops inserting items into the system and then the disk moves to the "out" section. 

*The system has room for the items.
*I checked the 2 disks that wouldn't empty in the disk drive and no items were shown in the crafting grid.

**Comment by ineternet** [comment]
duplicate or atleast relevant to #908 possibly?
