### ISSUE TITLE
[1.12.2] Losing items when using wireless grid and grids attached to network recievers

### ISSUE THREAD

**Issue by TheHuntrod** [raoulvdberge/refinedstorage#1668]
#### Issue description:
Losing items when putting them into the refined storage system.

#### What happens:
I am losing items when shift-clicking full stacks of items into the wireless grid, or even manually placing items inside. Just tried to put in all my items from a fully filled crystal chest of items gotten with my digital miner. All the items are gone. I've already tried replacing the controller, restarting the server, and anything else I could think of doing to try to fix it. It just keeps eating all my items. I have 1 64k storage block, 1 64k disk, 1 Quantum storage disk, along with some external storage Colossal chests, none of them have the missing items, and storage space did not increase when trying to insert test items.

#### What you expected to happen:
All my items to go into the system

#### Steps to reproduce:
1. Use latest version of All the Mods 3
2. Setup a controller and crafting grid, 64k storage block, quantum storage disk, and 64k
3. Setup a wireless transmitter with 4 range upgrades, and use Wireless grid
4. Input items into the Wireless grid, through shift-clicking
5. Possibly lose items

#### Version (make sure you are on the latest version before reporting):
Modpack: All the Mods 3
- Minecraft: 1.12.2
- Forge: 14.23.1.2587
- Refined Storage: 1.5.31

Does this issue occur on a server? [yes/no]
Yes, I am hosting the server

**Comment by TheHuntrod** [comment]
Another update... I just went to check the 64k storage cell which was full. It is currently at 0%...

**Comment by ineternet** [comment]
Did you actually try reproducing it, or did you just state the already known issue in your "steps to reproduce"? Something in your specific system or server might be bugged, try it on other servers on in a singleplayer testing world.
