### ISSUE TITLE
Filter not working in detector.

### ISSUE THREAD

**Issue by dvance12** [raoulvdberge/refinedstorage#1669]
#### Issue description:
When using the detector to detect autocrafting, if you put items in the filter the detector doesn't detect when those items are crafting.

#### What happens:
The detector won't put out a redstone signal when crafting items in the filter.

#### What you expected to happen:
I expected the detector to put out a redstone signal when it detects the items in the filter are crafting.

#### Steps to reproduce:
1. Use a detector on a network with autocrafting and try to use the filter to detect more than one item.
...

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12.2
- Forge: 8.0.99.99
- Refined Storage: 1.5.31

Does this issue occur on a server? [yes/no] 
I am on single player. I haven't tested it on a server.

#### If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here]

**Comment by raoulvdberge** [comment]
Not possible. Use multiple detectors.
