### ISSUE TITLE
Crash when autocrafting signalum fluxduct

### ISSUE THREAD

**Issue by PaulMurrayCbr** [raoulvdberge/refinedstorage#1672]
#### Issue description:

Crash when autocrafting signalum fluxduct.

#### What happens:

Game crashes

#### What you expected to happen:

Signalum fluxduct gets autocrafted

#### Steps to reproduce:
1. Set up a complicated system to pulverise ingots, destabilize redstone, craft electrum and signalum blend, fill fluxducts, etc etc
2. Craft some stuff, cancel crafting, try again - that kind of thing

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12.2
- Forge: 14.23.1.2573
- Refined Storage:

Does this issue occur on a server? [yes/no]

#### If a (crash)log is relevant for this issue, link it here:

https://pastebin.com/wfgfceR0

**Comment by raoulvdberge** [comment]
Duplicate #1629
