### ISSUE TITLE
Severe lag when viewing Grid

### ISSUE THREAD

**Issue by jediminer543** [raoulvdberge/refinedstorage#1674]
#### Issue description:

Upon opening a grid, FPS drops to about zero, and everything dies in a fire. It seems to occur when Items are being imported into the system (i.e. from quary)

#### What happens:

Lagging to death

#### What you expected to happen:

Not lagging to death

#### Steps to reproduce:

Testing apatatus (Importer on redstone toggle; enderchest to infinate item source):
![image](https://user-images.githubusercontent.com/6341928/36346055-daf33ef8-142e-11e8-8711-f3ac8a93d7e1.png)

Have importer off

Turn importer on

Lag ensues

#### Version (make sure you are on the latest version before reporting):

Direwolf20 Pack 1.7.1 from twitch launcher, running with 12G of ram to attempt to stop issues (which doesn't work)

- Minecraft: 1.12.2
- Forge: 14.23.1.2587
- Refined Storage: 1.5.31

(also has addons of: Refined Storage addons: 0.2, and Reborn storage 3.6.2.187)

Does this issue occur on a server? yes (Ran local server with copy of same world to test against)

#### In Game Time analasys Pi chart thing:

The Pi-O-Lag indicates that tick time is eating most of minecraft's compute time while in grids:

##### In my main world:

In Grid:
![image](https://user-images.githubusercontent.com/6341928/36345882-5e4b7b02-142b-11e8-8463-459ce0b85beb.png)

Not in grid:
![image](https://user-images.githubusercontent.com/6341928/36345860-23b0ea68-142b-11e8-823d-9af18713a6d9.png)

Errors from debug while doing this:
![image](https://user-images.githubusercontent.com/6341928/36345900-9ece15cc-142b-11e8-9d40-a708249a9593.png)
 
(Note the 6s respose time)

##### On the test rig:

Grid while importer is on
![image](https://user-images.githubusercontent.com/6341928/36346077-4aa24988-142f-11e8-99c1-4b1522426381.png)

Grid while importer not on:
![image](https://user-images.githubusercontent.com/6341928/36346084-626bb39c-142f-11e8-8ade-2bdbad45bc3f.png)

**Comment by raoulvdberge** [comment]
https://refinedstorage.raoulvdberge.com/wiki/profiling

**Comment by jediminer543** [comment]
Here are the files; run on the testing rig; one pair on the client, and another on the server.

Client:
[Client.zip](https://github.com/raoulvdberge/refinedstorage/files/1734222/Client.zip)
Server:
[Server.zip](https://github.com/raoulvdberge/refinedstorage/files/1734225/Server.zip)

This is in the test world described.

**Comment by gigabit101** [comment]
I have been noticing this issue myself recently,
It only seems to happen when inserting items into the network via any means.

**Comment by raoulvdberge** [comment]
I've attempted to fix this in the latest commit. The nps report didn't give me much, besides that is was spending a lot of time in the sorting code, so I optimized it a bit more so sorting calls are made less often.

**Comment by gigabit101** [comment]
Just as a side note for this updating java helped massively.

**Comment by raoulvdberge** [comment]
Weird..
