### ISSUE TITLE
Thermal Expansion Flux capacitors issue

### ISSUE THREAD

**Issue by GizliKodcu** [raoulvdberge/refinedstorage#1676]
#### Issue description:
Thermal Expansion flux capacitor auto-crafting and auto craft completing problem
#### What happens:
When i hit plus button i doesn't auto places flux capacitor and also eventhough i set up patterns with oredict i can't auto craft flux capacitors except lead one.
#### Steps to reproduce:
1. This issue happened with reborn storage but i tried it with crafters and didn't work
2.
3.
...

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12.2
- Forge: 14.23.1.2601
- Refined Storage: 1.5.31

Does this issue occur on a server? [yes/no]
No
#### If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here]

**Comment by ineternet** [comment]
Newly crafted capacitors are initially given metadata (because they are empty, damage value indicates the stored energy). RS patterns don't work with that, as you set your pattern to use a metadata of 0. If you make the pattern with a capacitor you crafted (and not just the NEI copying), it should work.

**Comment by raoulvdberge** [comment]
I think we can add a NBT ignore tag for this to the ignore list.

**Comment by GizliKodcu** [comment]
Well i used the one i crafted and still didn't work.

**Comment by raoulvdberge** [comment]
It worked for me, I tried it out a few weeks ago. But maybe something changed. I'm going to try to reproduce later.

**Comment by raoulvdberge** [comment]
I can't reproduce this, it works fine for me. Using JEI autocomplete to make the patterns.

**Comment by Bruches** [comment]
Hello, I just tried this on my world and the same problem occured. The leadstone flux capacitor will not auto craft. I created the pattern with JEI autocomplete as well. Is there a log file that I can provide that can be of assistance?

**Comment by raoulvdberge** [comment]
How does your autocrafting window look like?

**Comment by Bruches** [comment]
@raoulvdberge Sorry about that. I erased my post because it was my own error causing the problem. Manually crafting the flux capacitors first and placing it in the next tier of recipe fixed the problem as you stated.

**Comment by Slyklaw** [comment]
Can we re-open this issue? I'm still investigating the extent, but it's somewhat reproducible.

For example, if a Flux Capacitor has had energy, it cannot be used in auto-crafting. Is there any way to clear the Capacitor back to the pre-used state?

Could there be a difference between single and multi-player? In a single-player creative world, I can use JEI to create the patterns and they will auto-craft correctly. Doing the same thing on my server doesn't work.

**Comment by raoulvdberge** [comment]
This is intended. Autocrafting uses exact matches.

**Comment by raoulvdberge** [comment]
You shouldn't ask that to me.
