### ISSUE TITLE
Autocrafting recipes that have items with durability sometimes stop working.

### ISSUE THREAD

**Issue by Maximal-am** [raoulvdberge/refinedstorage#1677]
#### Issue description:
Autocrafting recipes that have items with durability sometimes stop working.

#### What happens:
I noticed this with 2 items. iChisel from chisel mod and empowerer from actually additions mod.
I set up full autocrafting chain for this items and it worked for some time.
At some point it stop working saying in case of ichisel - that dimond chisel is missing, in case of empowerer - double battery is missing.
To make them work again i had to remake ichisel and empowerer patterns with newly crafted dimond chisel and double battery (using items created by JEI didn't work)

#### What you expected to happen:
The recipes above must work.

#### Steps to reproduce:
I don't know what exactly causes the recipe to stop working.
...

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12.2 
- Forge: forge-14.23.1.2585
- Refined Storage: refinedstorage-1.5.31

I play singleplayer.

**Comment by ineternet** [comment]
sounds like #1676

**Comment by raoulvdberge** [comment]
@Maximal-am Respond in issue #1676 with all the items that are not working. Thanks.
