### ISSUE TITLE
unable to create patterns for Draconic Evolution

### ISSUE THREAD

**Issue by JelleDijkhuizen** [raoulvdberge/refinedstorage#1678]
#### Issue description:

unable to create draconic elevolution patterns and crafting of items is very slow.

#### What happens:
When trying to make a pattern. the result does not show so when you then make a patters it is invallid.

#### What you expected to happen:
be able to make a pattern. Or see the result from a recepie

#### Steps to reproduce:
1. try to make a pattern for a draconium block

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12.2
- Forge: 14.23.2.2611
- Refined Storage: 1.5.31

Does this issue occur on a server? yes

#### If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here]

**Comment by raoulvdberge** [comment]
Screenshot of the pattern grid screen please?

**Comment by JelleDijkhuizen** [comment]
![image](https://user-images.githubusercontent.com/2893952/36356987-d3f6d004-14f8-11e8-943e-e968db72b2e7.png)

**Comment by JelleDijkhuizen** [comment]
i just founf out it also happens whit other mods:
![image](https://user-images.githubusercontent.com/2893952/36356998-1087fdb8-14f9-11e8-95fe-860ab8a4bd1c.png)

**Comment by ineternet** [comment]
So you click on the "make pattern" button and it makes an invalid one? Can you send a screenshot before clicking on that button?

**Comment by raoulvdberge** [comment]
The button shouldn't be enabled if the pattern has no output.

**Comment by JelleDijkhuizen** [comment]
@raoulvdberge The pattern has an output before you hit the make pattern button.
Also if you make it in the crafting grid the result is sometimes visible sometimes not.

**Comment by raoulvdberge** [comment]
I'm going to take an educated guess, and think that your recipes are probably messed up on your modpack.

I will still try to reproduce howeveR.

**Comment by JelleDijkhuizen** [comment]
The modpack is all the mods 3. But if there is a problem with the recipes shouldn't AE2 also give an error/problem or even just a normal crafting table?

**Comment by tyler489** [comment]
Unidict installed?

**Comment by JelleDijkhuizen** [comment]
@tyler489 yes i have

**Comment by raoulvdberge** [comment]
Works on my side. It's a unidict bug.
