### ISSUE TITLE
Machines not updating GUI after return from Nether

### ISSUE THREAD

**Issue by c0rn3j** [raoulvdberge/refinedstorage#168]
I can't seem to be able to reproduce this.
My network is set like this, with disk drive and crafting grid set to activate on redstone signal.
http://i.imgur.com/YLUbXE5.png
After returning from the Nether(for like the third time) the machines GUIs supposedly froze, I could click on the  icons like Redstone Mode, which seemingly worked but it didn't show anything. I could see no items in the grid even after activating the pressure plate.
This was fixed by relogging to the server.

**Comment by raoulvdberge** [comment]
Duplicate
