### ISSUE TITLE
Crafting calculation causing stall

### ISSUE THREAD

**Issue by jediminer543** [raoulvdberge/refinedstorage#1680]
#### Issue description:

Crafting calculation causes server side stall

#### What happens:

A crafting request is made by an exporter, which results in a stuck server thread

#### What you expected to happen:

My game to not die in a fire

#### Steps to reproduce:
1. Placed an export bus down with a crafting card, told to craft wooden planks
2. Game immediatly dies

It is possible that this is due to the exporter having OreDict enabled, and all the wood crafting recipes having OreDict enabled, but that should throw an error to the user not hang the server

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12.2
- Forge: 14.23.1.2587
- Refined Storage: 1.5.31

Does this issue occur on a server? Haven't checked

#### Logs:

[stall-2018-02-19_21.43.51-3.txt](https://github.com/raoulvdberge/refinedstorage/files/1738277/stall-2018-02-19_21.43.51-3.txt)
[stall-2018-02-19_21.41.50-2.txt](https://github.com/raoulvdberge/refinedstorage/files/1738279/stall-2018-02-19_21.41.50-2.txt)
[stall-2018-02-19_21.40.50-1.txt](https://github.com/raoulvdberge/refinedstorage/files/1738281/stall-2018-02-19_21.40.50-1.txt)
[stall-2018-02-19_21.40.19.txt](https://github.com/raoulvdberge/refinedstorage/files/1738283/stall-2018-02-19_21.40.19.txt)

Etc.

They all show an issue in `apiimpl.autocrafting.CraftingManager.hasPattern` is causing hang, if I am interpreting them correctly.

NOTE: This cannot be profiled, as the server side immediately hangs on occurance

**Comment by raoulvdberge** [comment]
I can't do much with this report.

**Comment by jediminer543** [comment]
Sorry, is there anything else I can add to make it more usefull?

**Comment by raoulvdberge** [comment]
No.

**Comment by raoulvdberge** [comment]
These set of performance issues will be fixed later anyway if I ever rewrite the autocrafting.
