### ISSUE TITLE
[1.12.2] Disks Disappearing

### ISSUE THREAD

**Issue by DrewCarter0** [raoulvdberge/refinedstorage#1681]
#### Issue description:
Disks disappearing - Looks like possibly the same issue as [986](https://github.com/raoulvdberge/refinedstorage/issues/986)

#### What happens:
Disks and surrounding RS system information is wiped - Crafters, disk drives, upgrades all disappear. What is unique is that isn't not just within a chunk, some RS machines within a chunk are wiped, while some are not. I am not sure if it happened on restart, although that would be my best guess. Figured it could be issue with FTB utilities chunk loading but after reviewing older issue, could be re-occurrence.
Pack is ATM3

#### What you expected to happen:
Disks/Information to persist after restart.

#### Steps to reproduce:
Unable to reproduce at the moment.

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12.2
- Forge: 14.23.2.2617
- Refined Storage: 1.5.31

Does this issue occur on a server? [yes/no]
Yes
#### If a (crash)log is relevant for this issue, link it here:
N/A

**Comment by raoulvdberge** [comment]
This bug doesn't exist anymore. You, someone else, or another mod has most likely corrupted the refinedstorage_nodes.dat file. This is not an RS issue.

**Comment by Boomflex** [comment]
Raoul, my man, is there a way to tell what mod interacted with the refinedstorage_nodes.dat file?

We just had this appear on our Patreon Server

**Comment by raoulvdberge** [comment]
No

**Comment by rey-grschel** [comment]
I've gotten the same issue, but with various other mods installed. I understand that there's many other factors at play, but I've had this happen several times on my server, once when a creeper blew up our system which only contained cobblestone. I don't think there's anything intermod going on here.

**Comment by raoulvdberge** [comment]
Known forge issue.

**Comment by rey-grschel** [comment]
I get that it's an issue with Forge but it's completely catastrophic and results in complete deletion of storage systems. Until this is fixed, I'm not going to be using this mod on my server because of the risk of data losses. If there's anything I can do to help you fix it, I'd be more than willing to try,
