### ISSUE TITLE
processing patterns immediatly turning into crafting patterns???

### ISSUE THREAD

**Issue by johnetegtmeier** [raoulvdberge/refinedstorage#1683]
#### Issue description:
processing patterns immediatly turning into crafting patterns
#### What happens:
I added a link to a video I just made on 1. in steps to reproduce if that dose not work than here it is again   https://youtu.be/Nia6UzQyaZc
#### Steps to reproduce:
[1.](https://youtu.be/Nia6UzQyaZc)
2.
3.
...

#### Version (make sure you are on the latest version before reporting):

- Minecraft:
- Forge:
- Refined Storage:

Does this issue occur on a server? [yes/no]

#### If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here]

**Comment by johnetegtmeier** [comment]
my apologies if this post is not done right this is my first time trying to report an issue I'm having. Thank you for any help you can offer :)

**Comment by Tahakk** [comment]
I have no idea what are you trying to do by looking at the video.

You have two types of pattern recipes:
1. Classic: when don't have checked _Processing_ -> items that can be crafted in crafting table, thus are being crafted in RS Crafter
2. Processing: e.g. when you want your speed upgrade crafted in solderer (or Iron dust in furnace etc.) - items that cannot be crafted in crafting table

If you want to know how to make autocrafting work I suggest you go on [YT](https://youtu.be/pMHww6qpABA?t=169) (bit older but you should get the idea) or read [RS Wiki](https://refinedstorage.raoulvdberge.com/wiki/autocrafting)

**Comment by johnetegtmeier** [comment]
Tahakk what I was trying to do in the video is to show that I made a processing pattern in the pattern grid and as soon as I take the pattern out of the grid it turns into a crafting pattern NOT the processing pattern I started out trying to make. point being I cannot make processing patterns it will ONLY make crafting patterns

**Comment by Tahakk** [comment]
I'm not sure if there is written _Processing pattern_ somewhere. That patter you created should be good to go.

**Comment by johnetegtmeier** [comment]
after some more tinkering I think the patterns are working even they show up as crafting not processing but I'm still having problems with the solderer's getting jammed up I'm thinking of putting a crafter and import bus on each solderer instead of a single crafter/buffer chest/and itemducts. Do you see any problems with that idea? and Thank You very much for your input :)

**Comment by Tahakk** [comment]
My guess is that you are transferring items with TE itemducts, use filter that is set up to let just one item of each in, it is slower when you are using 1 solderer per crafted item, but if you will have like 5 for one item (1 type of processor), it should easy enought to set up at the end
