### ISSUE TITLE
OpenComputers API - Crafting items with metadata

### ISSUE THREAD

**Issue by aequasi** [raoulvdberge/refinedstorage#1684]
I'm trying to craft Niter from Thermal Foundation, and i'm having a little bit of trouble with `hasPattern(stack:table):boolean`

I've tried putting in `{name = thermalfoundation:material, damage = 772, label = "Niter"}` and im always getting `false` from `hasPattern`. 

Am I missing something?

**Comment by raoulvdberge** [comment]
I never use OC so I don't know myself, but you might need to look what the .getItems() method gives back.

**Comment by raoulvdberge** [comment]
I'm closing this as this isn't really a bug, I'm sure the community can help you further. I don't know much about the OC integration.
