### ISSUE TITLE
[1.12.2] Exporters and Filters: Filter for a Stack of Items?

### ISSUE THREAD

**Issue by MokahTGS** [raoulvdberge/refinedstorage#1686]
#### Issue description:
I'm trying to get an exporter to pull a stack of every food out of the network and insert it into the cooking for blockheads refrigerator.  I'd like the system to keep the "kitchen" stocked at all times, but I can't get this to work.  

Exporters only have 9 slots for items and filters don't seem to work with the exporter in regulator mode.  If I turn off regulator mode it just dumps everything that is in the filter into the refrigerators.

Is there any way to tell a filter to grab a stack of an item only?

Either filters need to be made to work correctly with regulator mode or Exporters need a way of expanding the number of items it can export.

- Minecraft: 1.12.2

**Comment by raoulvdberge** [comment]
Regulator mode doesn't work with the filter.
