### ISSUE TITLE
Server can't keep up & massive lag spikes

### ISSUE THREAD

**Issue by sanegaming** [raoulvdberge/refinedstorage#1687]
#### Issue description:
After connecting the autocrafting multiblock and removing my crafters I noticed a huge performance issue.  16x6x7 in size.
#### What happens:
I constantly get server cant keep up messages, over 8k MS most of the time and when opening grids I time out.
#### What you expected to happen:
I expect a smooth play through (for the most part)
#### Steps to reproduce:
1. Craft 16x6x7 auto crafting block, 44 pages of recipies avail with 4 pages used
2. connect to a fairly large system, with furnaces, etc.
3. look for the recipies you have in the large crafter, they take forever to show up in a grid if you manage to not time out. 
...

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge: 12.18.3.2477 / forge loader version 8.0.99.99 
- Skyfactory 3 version 3.0.15
- Refined Storage: 1.2.26

Does this issue occur on a server? [yes/no]
Yes, this is on a server.
#### If a (crash)log is relevant for this issue, link it here:
This is a sampler for the lag that happens when it first boots up and I reconnect the crafter block to get recipes to show.
[StartupLag.zip](https://github.com/raoulvdberge/refinedstorage/files/1754138/StartupLag.zip)

[pastebin/gist/etc link here]

**Comment by raoulvdberge** [comment]
1.10 is unsupported.
