### ISSUE TITLE
Server can't keep up 1.10.2

### ISSUE THREAD

**Issue by ButtonBright0907** [raoulvdberge/refinedstorage#1688]
#### Issue description:
extreme server lag started about a week ago out of the blue.
#### What happens:
Server lags 3 to 5 seconds when opening the grid, and longer if you close and reopen grid

#### What you expected to happen:
No lag
#### Steps to reproduce:
1. open grid
...

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 10.2
- Forge: 
- Refined Storage:1.2.26

Does this issue occur on a server? [yes/no]
yes

#### If a (crash)log is relevant for this issue, link it here:
I was able to run sampler, but i have no idea how to read the output.
[samplerrefined.zip](https://github.com/raoulvdberge/refinedstorage/files/1754750/samplerrefined.zip)

Thanks

**Comment by Tahakk** [comment]
1.10.2 is no longer supported
