### ISSUE TITLE
Wireless Crafting Monitor crash

### ISSUE THREAD

**Issue by GizliKodcu** [raoulvdberge/refinedstorage#1689]
#### Issue description:
Wireless Crafting Monitor crash
#### What happens:
When i open the wireless crafting monitor my game crasher
#### What you expected to happen:
I expect to see my crafting processes. (And expect this bug to be fixed of course)
#### Steps to reproduce:
1.
2.
3.
...

#### Version (make sure you are on the latest version before reporting):

- Minecraft:1.12.2
- Forge:14.23.2.2618
- Refined Storage:1.5.31

Does this issue occur on a server? [yes/no]
no
#### If a (crash)log is relevant for this issue, link it here:
[pastebin/gist/etc link here]
https://gist.github.com/GizliKodcu/fe31c8f1f8fe213a19b697e8519a41e7
**Note:I have infinite wireless transmitter**

**Comment by raoulvdberge** [comment]
What item was crafting at the time?

**Comment by GizliKodcu** [comment]
Sorry i forgot :(

**Comment by Tahakk** [comment]
Then if it is still happening you can take a look or try to make it happen again please

**Comment by GizliKodcu** [comment]
Ok i will do

**Comment by raoulvdberge** [comment]
Closed due to inactivity
