### ISSUE TITLE
External Storage syncing issues with Grid

### ISSUE THREAD

**Issue by JohnPark234** [raoulvdberge/refinedstorage#169]
Using:
Minecraft: 1.10
Mod Version: 1.9.4-3.1.11
Other Mod: Storage Drawers

Issue:
There seems to be a desync issue where the grid numbers is unable to update on drawers but external storage numbers are synced when pulling out items/blocks manually from the drawer.

How to reproduce:
1. Have a grid
2. Put down an external storage block in the system
3. Put down a drawer in front of it (make sure the external storage block is facing the right way
4. Put items in.
5. Open Grid
6. Be shocked that the item isnt in the system
7. Check the external storage to see if it is being recognized
8. Be puzzled as to why the grid isnt updating

:+1:

**Comment by raoulvdberge** [comment]
Already fixed in dev
