### ISSUE TITLE
"Multicore/spreaded" processing autocrafting only using one machine

### ISSUE THREAD

**Issue by KatouMegumi-osu** [raoulvdberge/refinedstorage#1691]
#### Steps to reproduce:
1. Set up a few solderers with crafters ontop and importers at bottom
2. Insert the EXACT similar processing patterns into the crafters
3. Request the item from autocrafting and expect only one machine being used.
...

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12.2
- Forge: 2601
- Refined Storage: 1.5.31

Does this issue occur on a server? 
I don't know. Maybe irrelevant

P.S: I also made a bad quality video, showcasing the bug.
https://youtu.be/x0ayNR5WzP0 Maybe that would be helpful

**Comment by Tahakk** [comment]
I think this is not the bug, but it just don't work like that, sadly. It would be great if it would tho.

**Comment by raoulvdberge** [comment]
It should work like that. I'm going to look into it.

**Comment by raoulvdberge** [comment]
I can't reproduce this. It works fine for me.
