### ISSUE TITLE
Precise numbers in the Storage Monitor?

### ISSUE THREAD

**Issue by wrincewind** [raoulvdberge/refinedstorage#1693]
#### Issue description:

Would it be possible to add a setting to the Storage Monitor so that it can display a precise number rather than a number rounded to the nearest thousand/million/etc? I want to see if the exact number of a few resources is going up or down over time, but there's no easy way to do that short of mousing over them and holding shift, or waiting for a change in the thousands range. Currently it displays, e.g. a picture of cobblestone and '137k', i'd like to see '137,096'.

**Comment by raoulvdberge** [comment]
No, current way is fine.
