### ISSUE TITLE
Allow Crafting Grid to accept Crafting Upgrade for enhanced functionality

### ISSUE THREAD

**Issue by Monstrel** [raoulvdberge/refinedstorage#1695]
This is a feature request to make workflows with the Crafting Grid more streamlined at the cost of an existing upgrade.

It is tedious to have to deal with recipe components that are not in stock that the RS system knows how to auto-craft. Workflows typically involve searching for components to invoke auto crafting or direct crafting in the case of crafting table recipes and then searching again for the original recipe desired once the recipe components are known to exist.

With this proposed functionality, the Crafting Grid could accept a Crafting Upgrade that would offer to craft missing recipe components automatically.

Take this example of crafting a a wooden pickaxe when only logs are stored in the RS system, but it knows how to autocraft sticks and planks.  My current workflow looks like this:

1. Search for pickaxe
2. Click wooden pickaxe in JEI
3. Click + in JEI to move recipe to Crafting Grid
4. Note no components were moved because the system doesn't have stick or planks
5. Search for planks
6. Request 3 planks
7. Search for sticks
8. Request 2 sticks
9. Repeat steps 1-3

With a Crafting Upgrade in the Crafting Grid, I propose the following workflow:

1. Search for pickaxe
2. Click wooden pickaxe in JEI
3. Click + in JEI to move recipe to Crafting Grid
4. Observe ghost items in Grid indicating the components do not exist (possibly with a green overlay or border indicating the items can be auto-crafted, or a red overlay or border indicating they cannot)
5. Click a new "Craft Missing Components" button in the Crafting Grid interface to invoke auto-crafting of the missing sticks and planks (using the same UI as current auto-crafting)
6. Wait for the components to be crafted at which point they automatically fill into the ghost slots
7. Craft the pickaxe

This new feature would greatly ease the tedium of descending deeply nested recipe trees that may be already auto-craftable save for a useful UI.

Thanks for reading!

**Comment by ineternet** [comment]
Well, I agree that this has been kind of a annoyance a bunch of times for me, but this is what patterns are for. If you just need a single wooden pickaxe, making the sticks extra shouldnt be a big deal. If the recipe is more complicated or you need more than one pickaxe, just make a pattern for it. Even if you only need it once, you can delete and reuse the pattern afterwards.

**Comment by raoulvdberge** [comment]
Agreed with the person above me.

This idea has been suggested multiple times on the tracker and has been shot down for exactly that reason. 

Also, I don't like the idea of a "upgradeable" grid.
