### ISSUE TITLE
Question - Is there some unwritten maximum number of devices you can have on a network?

### ISSUE THREAD

**Issue by trogarus** [raoulvdberge/refinedstorage#1696]
#### Steps to reproduce:
1. Create a basic system
2. Add a bunch of transmitters and receivers along with import, export, constructor, destructor, etc.
3. Eventually the system shuts down
...

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1-12-2
- Forge: 2611
- Refined Storage:  1.5.31

Does this issue occur on a server? [yes/no] Single Player World

#### If a (crash)log is relevant for this issue, link it here:

No crash log as the game doesn't crash, and nothing evident in the logs to show what the issue is either.

**Comment by KatouMegumi-osu** [comment]
Well there is no limit on the devices. Do you have a sufficient power generation?

**Comment by ineternet** [comment]
Try switching out the controller for a creative controller to eliminate that its some weird problem with energy.

**Comment by tyler489** [comment]
Energy mode is off controler should not effect it.

**Comment by trogarus** [comment]
OK, further information. Must have missed something about power in configs because cheating in a creative controller solves the issue. HOWEVER, this does present another problem. Before doing that, I had 8 RF tool energy cells connected on 5 sides of the survival controller with the maximum flux ducts available (can't remember the name but it's the big ones requiring cryotheum in the crafting). The creative cells were set to output on all sides as well, and output, I believe 40k rf per tick if memory serves me correctly.

However, 8 of these attached to 5 sides of the controller with max size fluxduct was not able to keep the thing powered to stay on. I was at a point where when I added one more device, the network would shut off.

I have one more thing I want to try to nail this issue down, but will be a bit before I can do it. I want to change the energy storage amount in the survival controller after looking at the present energy requirements to see if that might be the cause of the issue. I will report back after I can test the idea,

**Comment by trogarus** [comment]
So, at defauls the controller will store like 32000 rf. It would seem that I was at a point where maintenance power upkeep required 33k plus. As such, the controller could not get enough energy to maintain the system. Although I know this is an edge case (I have well over 100 exporters at this point and at least 50 transmitters), something to indicate a bit more easily to people that their present system exceeds the controller capacity might be in order. However, the other downside with this is how many are going to know to change a config to fix the issue? Wonder if there might be some other solution to this potential issue.

**Comment by raoulvdberge** [comment]
You can increase the controller energy capacity in the configs. The controllers have a max throughput of the max energy capacity, so you can insert only 32k at a time by default (since that's the capacity).

Furthermore, changing the `controllerUsesEnergy` config entry to `false` will also fix this issue.

**Comment by trogarus** [comment]
Yeah, I didn't want to cheese it like that though. Already set the controller input to 100k for now. If I run into it again, I'll know to look at the maintenance use and see if it's over 100k =) Thanks again for the mod and your work on it. =)
