### ISSUE TITLE
Crafting Terminal messes with IRecipes and IRecipeshaped

### ISSUE THREAD

**Issue by jaredlll08** [raoulvdberge/refinedstorage#1697]
#### Issue description:

Your Crafting Terminal doesn't want to show the output item for recipes that do not extend the provided recipe classes but instead use their own implementation of the IRecipe / IRecipeShaped class.

This issue ONLY happens on a server and is only a visual glitch, @kindlich has tested that and may have more info.

####  What happens:

Recipes added via CraftTweaker now use their own IRecipe implementation, so any recipe added via CraftTweaker will cause RS to glitch out and not display an item in the output slot.

#### What you expected to happen:

An item to be displayed in the output slot.

#### Steps to reproduce:
1. Add recipe with CraftTweaker
2. Start server
3. try and craft said recipe in a RS crafting grid

#### Version (make sure you are on the latest version before reporting):

- Minecraft:1.12.2 
- Forge: 14.23.2.2624
- Refined Storage: 1.5.31

Does this issue occur on a server? [yes/no]
yes
#### If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here]

**Comment by raoulvdberge** [comment]
Did you look in the code to confirm this? Your comment comes over as you're sure about this theory.

**Comment by kindlich** [comment]
I checked the code, didn't find anything out of place there.
Here's what's happening with a shaped recipe:

![rsrecipegrid](https://user-images.githubusercontent.com/10351787/36915776-2a2459d0-1e52-11e8-97c1-d61fd98e54bf.gif)


If I make the recipe class extend the `ShapedRecipes` class, it works as expected.

**Comment by raoulvdberge** [comment]
Can I see your recipe implementation?

**Comment by kindlich** [comment]
We've narrowed it down to it being most likely an issue on our side, since we were calculating recipe names from the ingredient. Turns out MC doesn't override `toString` or `hashcode`

Can most likely be closed
