### ISSUE TITLE
Redstone Comparator function for Reader

### ISSUE THREAD

**Issue by TvL2386** [raoulvdberge/refinedstorage#1699]
Hey all,

I am playing with the Reader/Writer for the first time. Awesome :)
I've been using it in several places currently and I would like to use the Reader as a comparator.

In my case I want it to read the amount of mana in a Botania mana pool by attaching it to the bottom of the pool.

Kind regards,
TvL23836

**Comment by raoulvdberge** [comment]
No

**Comment by raoulvdberge** [comment]
You can connect a comparator and then a reader
