### ISSUE TITLE
Crash when opening grid with Mouse Tweaks mod

### ISSUE THREAD

**Issue by Aphyxia** [raoulvdberge/refinedstorage#1703]
#### Issue description:
Game crashed when accessing crafting grid. Unable to reproduce, rare issue.
Crash log seems to imply something with Mouse Tweaks mod.

Also see issue on Mouse Tweaks bitbucket: https://bitbucket.org/YaLTeR/mouse-tweaks/issues/19/crash-to-desktop-opening-refined-storage

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12.2
- Forge: 14.23.2.2624
- Refined Storage: refinedstorage-1.5.31

Does this issue occur on a server? [yes/no]
**yes**

#### If a (crash)log is relevant for this issue, link it here:

https://pastebin.com/JYYKP06h

**Comment by YaLTeR** [comment]
As far as I can see, MT called `getSlotAtPosition()` on one of the Refined Storage's `GuiContainer`s, and that threw an exception (which shouldn't normally happen).

**Comment by raoulvdberge** [comment]
Refined Storage doesn't override `getSlotAtPosition` or `func_146981_a` (which is `mouseOverSlot`), therefore I don't believe this is an RS issue.

**Comment by raoulvdberge** [comment]
If this does appear to  be an RS issue, I'll gladly reopen.
