### ISSUE TITLE
Exporter not autocrafting w/ crafting card

### ISSUE THREAD

**Issue by Bruches** [raoulvdberge/refinedstorage#1704]
Issue description:
Multiple exporters each with a crafting card and setup to export a set of items will not prompt the system to autocraft the required items on demand when attached to a bio fuel generator. I am able to request the item from the system using the grid and the item is crafted as expected.

What happens:
Nothing.

What you expected to happen:
I expect the system to autocraft rose red from beet root and then export the rose red to the Industrial forgoing bio reactor

Steps to reproduce:
1. Build exporter with crafting upgrade.
2. Setup exporter with the correct item to export. In this instance the item to export was rose red.
3. Place functioning crafting pattern in a crafter (this was not a processing pattern). - 1 beetroot = 1 rose red.
4. Remove all of the crafted item (rose red) from the system so that it has to craft on demand. 
5. Empty the target inventory of the specified item

Version (Make sure you are on the latest version before reporting):
Minecraft: 1.12.2
Forge: 14.23.2.2618
Refined Storage: 1.5.31
Industrial Foregoing 1.12.2-1.8.4-124 (not sure if this matters, but this is one version newer than the one shipped with the direwolf pack)

Does this issue occur on a server? Yes. a FTB Direwolf Server Version 1.12 pack version 1.9.0-1

![bio-reactor_no rose red](https://user-images.githubusercontent.com/14340388/37177445-53946aa4-22d4-11e8-9a55-3e2e95d6a1ff.png)
![crafting upgrade in exporter](https://user-images.githubusercontent.com/14340388/37177446-53b30540-22d4-11e8-9b52-cbe7217ff608.png)
![rose red in exporter](https://user-images.githubusercontent.com/14340388/37177447-53cf4566-22d4-11e8-9ccb-add8d8f3bf94.png)
![beetroot to rose red pattern in crafter](https://user-images.githubusercontent.com/14340388/37177448-53eb153e-22d4-11e8-91c1-97da69de27b0.png)

**Comment by Bruches** [comment]
With further testing I determined that the problem only seems to exist for the vanilla minecraft beetroot to rose red recipe. The exporter successfully crafted melon seeds on demand using the 1 melon to 1 seed recipe.

**Comment by Bruches** [comment]
With the compare ore dictionary option turned on the system works. Not sure why ore dictionary is needed for the item though.

**Comment by raoulvdberge** [comment]
I can no longer reproduce this in v1.6, so I assume this has been fixed.

**Comment by Grimjahk** [comment]
I'm running into this right now while playing Skyopolis 4. 
My first few exporters are calling to craft just fine, now the new ones don't work. I have 54 of them on my network now, but only around half have crafting modules.

**Comment by Kuperus** [comment]
i`m playing the encrypted modpack, and am running into the same problem,

i have an exporter on a drawer (also tried other containers) to autocraft and export lava cake, i can manually give a production order and it works (also exports those cakes) but somehow the exporter is not requesting any new batches...

**Comment by nogi1** [comment]
Just ran into this while trying to use exporter with Balloon recipe from Immersive Engineering, i able to order the craft using grid just fine. But exporter with crafting upgrade doesn't work.
