### ISSUE TITLE
Unable to Extract Items via Disk Manipulator with empty disk

### ISSUE THREAD

**Issue by SteveKnowless** [raoulvdberge/refinedstorage#1705]
#### Issue description:
Unable to Extract Items via Disk Manipulator with empty disk

#### What happens:
The disk goes directly to Out

#### What you expected to happen:
Items to start filling the disk

#### Steps to reproduce:
1. Take an inventory system with items in it
2. Place an empty disk in the Disk Manipulator configured to Extract Items
3. Disk will go directly to Out with no items transfered

...

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12.2
- Forge: 1.12.2 - 14.23.2.2611
- Refined Storage: refinedstorage-1.5.32

Does this issue occur on a server? [yes/no]
Yes, and SP

Also, this does not happen with the previous version. I did test and confirm that 1.5.31 works as expected but when upgraded to 1.5.32 this issue happens

#### If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here]

**Comment by raoulvdberge** [comment]
@ineternet Do you want to check this out?

**Comment by Knito58** [comment]
Forge 14.23.2.2624 MC 1.12.2 RS 1.5.32 Single Player

Again I derped with the storage block by re-placing the disk drive and then forgot to reset the priority from 0 to 1. Now after the next cleaning with disk manipulator everything (5000+ items) has gone to a prio 0 spare block.

I even set the IO mode to extract from network and set the block to extract only and the prio to 40. But the empty 64k disk goes immediatly to the out slot.

A while ago you said that the disk manipulator was planned to be compatible with the storage blocks. Thats 2 months now. Maybe that would not be necessary if the extract from network would work.

Grretings, Konitor

**Comment by raoulvdberge** [comment]
This has been fixed.
