### ISSUE TITLE
auto Crafting desc. string

### ISSUE THREAD

**Issue by Timsuper** [raoulvdberge/refinedstorage#1706]
Can you make an option in the config to overwrite the string shown in the matrix that says it is craftable?

The german word "Fertigungsmatrix" is quite long, and I would replace that by a simple "F" or "FM" in the config. Otherwise the word is so long that it overlapps the other items.

**Comment by raoulvdberge** [comment]
On which version are you?

**Comment by raoulvdberge** [comment]
I fixed this a long time ago on 1.12:

https://github.com/raoulvdberge/refinedstorage/blob/mc1.12/src/main/resources/assets/refinedstorage/lang/de_de.lang#L6

It just says "Craft" in German on 1.12.

1.10.2 is unmaintained.

**Comment by Timsuper** [comment]
I'm on 1.11.2. And sadly we will stay for the moment. (most compatible)

**Comment by Timsuper** [comment]
Because the author likes to close issues, rather than doing something here the answer:

Take WinRar and edit the e.g. de_DE.lang.

**Comment by raoulvdberge** [comment]
1.11.2 is unmaintained. There is nothing else I can do. Now, show your big mouth somewhere else, but not on my issue tracker.

**Comment by Timsuper** [comment]
Dude, you're a bit overreacting. But you are indeed really fast at closing issues.
