### ISSUE TITLE
Scheduled Crafting resets with loss of items when server restart

### ISSUE THREAD

**Issue by slidingmike** [raoulvdberge/refinedstorage#171]
Forge 2007
1.10.2 MC
Refined Storage 0.8.5

**Comment by raoulvdberge** [comment]
can  you explain this issue a bit better?

**Comment by daevien** [comment]
I have crafting recipes setup in crafter for all solar flux items. Left system making all necessary parts for highest level solar panel (many, many subcombines), it had gotten through to solar panel IVs when I was online and was still working. Server is set to restart automatically every few hours. After the reset, the crafting queue was empty but all of the items used in process were gone. Not in queue, not in storage system.

**Comment by raoulvdberge** [comment]
Is the server forcefully shut down? The system needs to get a chance to save

**Comment by slidingmike** [comment]
It is not.

**Comment by raoulvdberge** [comment]
Related error

http://pastebin.com/5TzG1iun
