### ISSUE TITLE
[1.12.2] Autocrafting bug with enchanted books

### ISSUE THREAD

**Issue by wamc2017** [raoulvdberge/refinedstorage#1710]
#### Issue description:
I tried to setup the Auto-Anvil from Openblocks to combine two enchanted books of the same kind (2x Protection I = Protection II) with a processing pattern. The problem is, if I click on start during the crafting process, nothing happens (the button stays gray and nothing happens)
![2018-03-12_21 45 17](https://user-images.githubusercontent.com/33242447/37309401-265d0ea4-2641-11e8-91aa-9a55704685e0.png)

For the output I used a book (protection II) combined in an anvil, which got the following two nbt tags:
RepairCost:1
StoredEnchantments:[{lvl:2s,id:0s}]

If I use a cheated book without the RepairCost nbt tag the crafting process works fine!

I could reproduce this with only Refined Storage (version 1.5.32) and JEI (version 4.8.5.159) on forge (14.23.2.2625) installed, by using a chest (as a placeholder) next to the crafter instead of an Auto-Anvil. (for the screenshots I added Actually Additions, but tested it also without it...)

Here you could see the nbt tags of the working recipe (with the cheated book):
![2018-03-12_21 51 26](https://user-images.githubusercontent.com/33242447/37309738-1b23e82c-2642-11e8-8edd-5490232caba0.png)

And that's the one with the book created in an anvil (with the RepairCost nbt tag):
![2018-03-12_21 51 32](https://user-images.githubusercontent.com/33242447/37309774-333b5d8c-2642-11e8-85a8-1df3abb5c8c1.png)

There is nothing in the log file, but I've uploaded it anyway.

#### What happens:
Tried to combine two enchanted books, autocrafting doesn't work.

#### What you expected to happen:
Autocrafting doesn't hang there forever... :smile:

#### Steps to reproduce:
1. Build some basic RS system to autocraft
2. Combine two Protection I books in an Anvil to get a Protection II book (also tested other enchantments, same thing there...)
3. Set up a processing recipe 2x Prot. I = Prot. II
4. Try to craft the book

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12.2
- Forge: 14.23.2.2625
- Refined Storage: 1.5.32

Does this issue occur on a server? maybe (only tested in singleplayer)

#### If a (crash)log is relevant for this issue, link it here:
https://pastebin.com/FZ7kKLnu
(No crashlog, not really much information... :/)

**Comment by raoulvdberge** [comment]
Don't autocraft with enchanted books, it's not meant for that. RS specifically ignores the enchanted book tag so enchanted books work with other recipes.
