### ISSUE TITLE
Ore of same type but different mod/block is rapidly taken out/put in interfaces if compared with ore dictionary

### ISSUE THREAD

**Issue by 343N** [raoulvdberge/refinedstorage#1711]
#### Issue description:
Ore is rapidly taken out/put in interfaces

#### What happens:
Ore of the same type from a different mod of the one you specified in an interface will constantly be inserted and exited from the interface, if you allow comparisons with the ore dictionary
Here's a gif of what I mean:
![2018-03-14_00-50-54](https://user-images.githubusercontent.com/10753324/37346127-a7f07cf8-2722-11e8-9e13-a70b340e1c25.gif)

Note that this DOESN'T happen if the block is the same (i.e from the same mod) as the one put in the export slot (so for instance, in the gif, that wouldn't happen with Mekanism Copper)

#### What you expected to happen:
For it to just sit in the interface as it should(?)

#### Steps to reproduce:
1. Get an ore block from one mod, put it in the export space of an interface
2. Get a block of the same type of ore but from a different mod and put it in your system/storage
3. Watch the interface rapidly insert/extract 

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12.2
- Forge: 14.23.2.2624
- Refined Storage: 1.5.31

#### Does this issue occur on a server?
This happens in singleplayer, server is untested.

**Comment by ineternet** [comment]
Should be fixed in 1.5.32, Have you tried updating?

**Comment by raoulvdberge** [comment]
Update.
