### ISSUE TITLE
1 item in disk storage, can't remove it

### ISSUE THREAD

**Issue by bochen415** [raoulvdberge/refinedstorage#1712]
Issue description: 
Disk says there's one item in it, no item found, can't remove it.

What happens: 
I've got one item in my disk. No idea how that item got there, can't remove it when I place only this disk in a drive, a network with only this disk doesn't show any items.

What you expected to happen:
 the item to show up or the network to remove it if it's not valid.

~~Steps to reproduce:~~
No idea how it got there and when.

Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12.2
- Forge: 14.23.2.2624
- Refined Storage: refinedstorage-1.5.32

Does this issue occur on a server? singleplayer, no way to reproduce on a server

Screenshot with NBT data from the disk with the item
![](https://i.imgur.com/AH9yxRh.png)

**Comment by raoulvdberge** [comment]
#908
