### ISSUE TITLE
Interface auto exporting random items

### ISSUE THREAD

**Issue by eashonk** [raoulvdberge/refinedstorage#1714]
#### Issue description: 
When connecting an item duct to an interface and setting it to auto output via a servo the interface starts exporting random items from different mods.  

#### What happens:
Random items are exported.

#### What you expected to happen:
Nothing.

#### Steps to reproduce:
1. connect an interface to a network containing items.  
2. create a loop via item ducts from one side of the interface to another
3. Put a servo on one side and set it to auto export 
...

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12.2
- Forge: 14.23.2.2618
- Refined Storage: 1.5.31

Does this issue occur on a server? [yes/no]
don't know

#### If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here]
Here's a link to a video demonstrating.
https://youtu.be/3OAxzsv3AdY

**Comment by raoulvdberge** [comment]
It's not a bug, it's a feature.

When you don't configure any items, the Interface will expose your RS inventory and the itemduct will suck the first available item up.
