### ISSUE TITLE
Tinker Tank fluids don't all show in system

### ISSUE THREAD

**Issue by arm32x** [raoulvdberge/refinedstorage#1715]
#### Issue description:
The Refined Storage system doesn't recognise all fluids in the Tinkers' Construct Tinker Tank.

#### What happens:
It only recognises the bottom fluid, and ignores all others.

#### What you expected to happen:
It should recognise and show all fluids in the Fluid Grid.

#### Steps to reproduce:
1. Build a Tinker Tank.
2. Attach an External Storage to a Smeltery Drain on the Tinker Tank.
3. Look in a fluid grid.

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12.2
- Forge: 14.23.2.2615
- Refined Storage: 1.5.31

Does this issue occur on a server? Have not tested.

**Comment by ineternet** [comment]
I'm gonna guess this is because of tinkers, the drain will only expose one fluid inventory: the bottom fluid. Things like Waila will also tell you that only the bottom fluid is exposed. Either RS can do something to support tinkers, or you're in bad luck.

**Comment by raoulvdberge** [comment]
Duplicate: #1034
