### ISSUE TITLE
Document indirect autocrafting mechanic and reader/writer inheritance

### ISSUE THREAD

**Issue by danielhickman** [raoulvdberge/refinedstorage#1716]
[The wiki](https://refinedstorage.raoulvdberge.com/wiki) has a lot of helpful information that lead me to discover these two amazing mechanics but don't see a repo to PR so I figured this was the best place to suggest adding.

1. You can point an infinite amount of crafters onto one processing machine (i.e. furnace)

My use case here is having multiple furnaces far away from where I'd like to input patterns with many crafters talking to all of the furnaces on the same channel without having to use a chest as a middle-man.

2. You can "inherit" another channel's buffer by reading from it and writing to the "child"

My use case here is having those furnaces look cleaner by not having to use another side for power. It also allows me to skip a step in adding another writer on the power channel for each furnace, powering another reader on the furnace channel, or using a tesseract/quantum entangloporter.

In this [simplified demo](https://gfycat.com/EnergeticBigHogget), I use network receivers to illustrate they could be many blocks away. Also, the readers/writers connect to blocks on their face but don't look connected when they are.

**Comment by raoulvdberge** [comment]
> You can "inherit" another channel's buffer by reading from it and writing to the "child"

I have no idea what you mean by this. I can see what you do in your GIF, but don't see how it relates to the description above.

Also, why would that need to be explained in the wiki? The crafter outputs to a inventory next to it, and a Reader happens to be a valid inventory.

**Comment by danielhickman** [comment]
Inheriting is probably not a good word, but it was supposed to illustrate how I could use the buffers from other channels when making another. A power channel can read from a battery, another could read from that and another source, and so on. It's nothing too special but helps me when I need, say, a bunch of crafters, a fluid, and power.

And you're right, the behavior is already explained I just thought it had a place in a guide of some sort. The main one for me would've been being able to access crafters from my main base and have then process somewhere else easily but I see the crafters on the network are now being exposed through a GUI like AE. The second would be using more than the number of crafters than sides or the machine or chest without using item conduits from another mod. I think this still deserves a mention in the autocrafting guide if you do.

**Comment by raoulvdberge** [comment]
I think it's fine how it is.
