### ISSUE TITLE
Arbitrary/dynamic enchantments for Destructor upgrades

### ISSUE THREAD

**Issue by Saklad5** [raoulvdberge/refinedstorage#1718]
Would it be possible to rework the enchantment-based upgrades for Constructors such that any enchantment could be used, instead of having them hard-coded? This would be particularly helpful for mods like Astral Sorcery, which adds both new enchantments (Scorching Heat, which makes mined blocks drop their smelted products) and new maximum levels for existing enchantments (Fortune Ⅶ, which is rather self-explanatory).

I recognize that allowing _any_ enchantment might be more difficult than just calling a standardized method (though the worst-case scenario could just be nothing being applied), but judging by the existing code it should be fairly straightforward to allow any level of Fortune and such.

**Comment by raoulvdberge** [comment]
No, it's just not worth it.

**Comment by Saklad5** [comment]
Thank you for the quick response.
