### ISSUE TITLE
Conversion bug with Refined Storage exporters

### ISSUE THREAD

**Issue by Dreytac** [raoulvdberge/refinedstorage#1721]
#### Issue description:
Eggs passing through an exporter are converted to a different type of egg when using Hatchery

#### What happens:
Putting a Refined Storage exporter on a chest, filtering with any Hatchery egg and setting "Compare ore dictionary" to "Yes" will export normal eggs as the filtered Hatchery egg allowing conversion from ordinary egg into whatever Hatchery egg you're filtering on.

#### What you expected to happen:
Eggs should be taken from a Refined Storage system and be placed in the chest as the same type of egg.

#### Steps to reproduce:
1. Put Refined Storage exporter on a chest.
2. Set the filter to any type of Hatchery egg.
3. Set "Compare ore dictionary" to "Yes".
4. Chest will fill up with the filtered Hatchery egg instead of normal Minecraft eggs.

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12.2
- Forge: 14.23.2.2624
- Refined Storage: 1.5.31
- Hatchery: 2.1.2
- Chickens: 6.0.4

Does this issue occur on a server? Yes

![1 refined storage inventory](https://user-images.githubusercontent.com/861156/37867483-19a5872e-2fe5-11e8-929d-093824ade673.png)
![2 refined storage exporter](https://user-images.githubusercontent.com/861156/37867484-19d3ea10-2fe5-11e8-8ebd-6808ca62f5de.png)
![3 chest inventory](https://user-images.githubusercontent.com/861156/37867485-1a01ded4-2fe5-11e8-8b66-c79c244c4fe9.png)
![4 refined storage inventory](https://user-images.githubusercontent.com/861156/37867486-1a2fd6ea-2fe5-11e8-8a27-912da1a359fa.png)

Cross-posted as a Hatchery issue as well: https://github.com/GenDeathrow/Hatchery/issues/147

**Comment by Dreytac** [comment]
Just did a little more testing and it only seems to export as the incorrect type when the original egg comes from a Compact Drawer via a Refined Storage External Storage.

Having the eggs in a Refined Storage system itself doesn't seem to be an issue.

**Comment by ineternet** [comment]
#1619
