### ISSUE TITLE
Disk drives changing color when placed

### ISSUE THREAD

**Issue by jusjudge** [raoulvdberge/refinedstorage#1724]
#### Issue description:
Disk drive's show a dark tint-black color when placed
#### What happens:
For some reason, when I place the disk drives a certain way, they change color. At least, the front panel changes color.
#### What you expected to happen:
For it to show it's original shade.
#### Steps to reproduce:
1. I'm having a hard time trying to explain it so just look at the link to check out the screenshots. It has something to do with it being placed with the front panel facing south (player facing north).
2. Actually it happens facing any direction. Especially when you put multiple disk drive next to each other. It's worse when the player is facing north. I added a new link for the screenshots.
3.
...

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12.2
- Forge: 14.23.2.2638
- Refined Storage: 1.5.32

Does this issue occur on a server? [yes/no]
I'm not sure
#### If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here]
https://imgur.com/a/0pKHm
https://imgur.com/a/mkCjy

**Comment by raoulvdberge** [comment]
This is an optifine issue.
