### ISSUE TITLE
Crafting any ducts from thermal dynamics doesn't work.

### ISSUE THREAD

**Issue by Nostras** [raoulvdberge/refinedstorage#1728]
#### Issue description:
Crafting any ducts from thermal dynamics doesn't work.
#### What happens:
You click craft but the result disappears nor can you continue crafting. Nothing is lost.
#### What you expected to happen:
Crafting the actual item.
#### Steps to reproduce:
Just craft some ducts. I tried the leadstone fluxduct and itemduct.

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12.2
- Forge: 14.23.2.2624
- Refined Storage: 1.5.32

https://i.snag.gy/soqm5H.jpg
https://i.snag.gy/F6UT4W.jpg

**Comment by raoulvdberge** [comment]
I doubt this one, but I'll double check.

**Comment by raoulvdberge** [comment]
Works for me on 1.6...
