### ISSUE TITLE
Damage reset when crafting with items in a Storage Drawer

### ISSUE THREAD

**Issue by dannydjdk** [raoulvdberge/refinedstorage#1731]
#### Issue description:
When setting up a crafting recipe in the Crafting Grid using the JEI "+" button, items taken from Storage Drawers for the recipe will be placed in the grid fully repaired, thus negating all damage.

#### What happens:
Any damaged item that is used in a crafting recipe can be fully repaired for free by placing it in a storage drawer connected to an RS system using an External Storage block.

#### What you expected to happen:
The item should be placed in the grid without changing the damage value.

#### Steps to reproduce:
1. Set up an RS System with an external storage connected to a Drawer Controller on a Storage Drawer network.
2. Place a damaged bow in a storage drawer.
3. In JEI, click on the Dispenser and click "+" to set up the recipe.
The bow will appear in the crafting grid fully repaired.
This will work for any item in a recipe, an IE hammer, a diamond sword, etc.

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12.2
- Forge: 14.23.2.2611
- Refined Storage: 1.5.32

Does this issue occur on a server? yes

**Comment by ineternet** [comment]
#1619
