### ISSUE TITLE
Sub-nets and an inability to create them

### ISSUE THREAD

**Issue by GreatGameGal** [raoulvdberge/refinedstorage#1732]
#### Issue description:
 There is an inability to create sub-nets, this also appears exporting to, and importing from another network, though this report will focus on sub-nets.
#### What happens:
 When you place an external storage on an interface connected to a network, it will destroy one of the controllers and integrate it all into one network.
#### What you expected to happen:
 A sub-net to be created and for the inventory of the sub-network to become visible to the upper-network, both networks co-existing.
#### Steps to reproduce:
1. Create a network with an interface.
2. Create another network in close proximity to the first.
3. Connect external storage from second network to interface of the first.
4. Watch as everything burns to the ground.
...

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12.2
- Forge: 14.23.2.2652
- Refined Storage: 1.5.32

Does this issue occur on a server? [yes/no]
yes

**Comment by raoulvdberge** [comment]
No

**Comment by raoulvdberge** [comment]
No
