### ISSUE TITLE
[1.12.2] Recipes with more then 1 of an item stack in the 1 slot

### ISSUE THREAD

**Issue by Morpheus1101** [raoulvdberge/refinedstorage#1733]
#### Issue description:

When shift clicking a recipe from JEI into the crafting grid, if the recipe has 2 of the 1 item or more, instead of placing the item into the individual slots, it stacks them

#### Steps to reproduce:
In this instance i crafter mekanism speed//power upgrades and when shift clicked from the Crafting grid the Glass & Alloy stack 

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12.2
- Forge: *.2653
- Refined Storage: 1.5.32

Does this issue occur on a server? [yes/no] Yes

**Comment by raoulvdberge** [comment]
Screenshot of the recipe and crafting grid please?

**Comment by Morpheus1101** [comment]
https://puu.sh/zWm8P/1de68f85fe.png

**Comment by raoulvdberge** [comment]
I can't reproduce this in 1.6.

![x](https://drive.google.com/uc?id=1lfRlk-TXlMBZJUbJWmpN_bgCFZhYxH-w)
