### ISSUE TITLE
Disk Manipulator not removing items from disk

### ISSUE THREAD

**Issue by NewtonAppolonius** [raoulvdberge/refinedstorage#1734]
#### What happens: The disk in the Disk manipulator just goes back into the Disk Drive. 
Do not lose any items, just disappears from the Manipulator and reappears in the Disk Drive 

#### What you expected to happen:
Disk to empty and items placed in storage
#### Steps to reproduce:
1. Remove disk with items in it
2. Place in the Manipulator
3. See what happens
...

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge: 12.18.3.2511
- Refined Storage: 1.2.26

Does this issue occur on a server? [yes/no] Single Player Survival 

#### If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here]

**Comment by NewtonAppolonius** [comment]
Apologies but can I ask why this is closed? Is a duplicate? I searched Open/Closed issues but could not see any relevant posts.
Thank you.

**Comment by raoulvdberge** [comment]
> Version (make sure you are on the latest version before reporting):

**Comment by NewtonAppolonius** [comment]
What version are you referring to?
I have the version for 1.10.2 and the Refined Storage jar is 1.2.26 which is the last version deployed.
Are you referring to the Forge version?

**Comment by raoulvdberge** [comment]
The last version is 1.5.32 for MC 1.12.2.
