### ISSUE TITLE
Crash With FTB Utilities

### ISSUE THREAD

**Issue by JoJoDeveloping** [raoulvdberge/refinedstorage#1738]
Hello.
I am playing the latest (stock) version of the FTB Pyramid Reborn modpack (singleplayer). This bug has crashed my game twice. As far as I can see from the stacktrace, it happens when the "Constructor" places a block. The chunk the block is placed in is claimed by me - which means that it is protected by me and only I am allowed to place things in it or something like that. Note that the bug only happens **sometimes** a block is placed, often times it works flawlessly.

Crash Log: https://pastebin.com/H29YiqkF
I have also opened an issue over at FTB Utils, see it here: https://github.com/LatvianModder/FTBUtilities/issues/685

**Comment by raoulvdberge** [comment]
Not an RS issue
