### ISSUE TITLE
Ender IO powder isn't filtered correct

### ISSUE THREAD

**Issue by BigBauf** [raoulvdberge/refinedstorage#174]
verison: 0.8.5.
I do not know if it's a RS bug or something that needs to be fixed on Ender IO's site
If you set an
 interface to export only _ender iogold powder_ it pulls any kind of _ender io powder iron/copper/coal/etc_.
Chaning "compare NBT" doesn't change this behaviour.

![well](https://cloud.githubusercontent.com/assets/4630276/16701303/31d8867e-455f-11e6-94a7-85262b890272.png)

PS: Love your mod. Great work!

**Comment by raoulvdberge** [comment]
You have to compare on damage

**Comment by BigBauf** [comment]
well...that was a waste of your time :-(
sorry

**Comment by raoulvdberge** [comment]
No problem
