### ISSUE TITLE
[1.12.2] Refined Storage isn't accepting liquid from different mod.

### ISSUE THREAD

**Issue by Okimo** [raoulvdberge/refinedstorage#1741]
#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12.2
- Forge: 14.23.2.2632
- Refined Storage: 1.5.32
- FTB Pyramid Reborn: 2.1.1

Does this issue occur on a server? [yes/no] no

**Comment by raoulvdberge** [comment]
Is your importer in fluid mode?

**Comment by Okimo** [comment]
Now I feel like Idiot. I'm sure I had it set to accept liquids and had space for the liquid. 
But when I was trying to reproduce it in test world today... it works. 
I will check the game and try to find out what's messing with it.

**Comment by Okimo** [comment]
So I was in my game world and all was set right. Importing Fluids and I had valid space for the liquids.
Yet it didn't work. So I restarted game, broke everything down, reworked it a bit and now it works. 
I don't know why it didn't work before everything seemed to be right set as it should be.
I'm sorry for bothering you :/
