### ISSUE TITLE
Duping issue with RFTools Storage Tablet and Storage Scanner and Refined Storage Interface

### ISSUE THREAD

**Issue by poutrosgit** [raoulvdberge/refinedstorage#1744]
Minecraft: 1.12.2  
Forge: 14.23.3.2676  
McJtyLib: 1.12-2.6.7-SNAPSHOT (2.6.7)  
Rftools: 1.12-7.33  
Refined Storage: 1.5.33  

The storage tablet is linked to a storage scanner which is scanning an interface from Refined Storage. As long as at least one item of the crafting recipe that is specified in the tablet is in the Refined Storage system, I am able to craft as many as I want of the resulting crafting recipe.

Steps to reproduce:
1. Setup an Refined Storage System with an interface.  
2. Put one item in it.  
3. Setup a storage scanner.  
4. Link the storage scanner to the storage tablet.  
5. Try to craft a recipe using the item in either a storage table or in the storage scanner.  

This will, at first, use the required items. However, when the number of required items drops below the necessary, it will no longer consume items inside of the refined storage system but will still give the resulting item from the crafting recipe. If there are any items outside of it and recheable to the storage tablet (like in the player inventory or a a chest caught by the storage scanner), they will still be used. Likewise, if no items are in the Refined Storage system but there are some in the inventory (like the player's or a chest) but below the necessary amount, the crafting operation won't happen.

**Comment by poutrosgit** [comment]
Latest update seems to have made it substantially harder to replicate this but it has increased the chance of a certain bug to happen which makes it impossible for some items to be extracted from the storage tablet. 

#1769

**Comment by poutrosgit** [comment]
So, this feature relies on the interface exposing the entire rs inventory. Since that is getting removed, does that mean this issue can be closed?

**Comment by raoulvdberge** [comment]
Yep, thank you for following up
