### ISSUE TITLE
[1.12.2]  Crash during load.

### ISSUE THREAD

**Issue by MokahTGS** [raoulvdberge/refinedstorage#1745]
#### Issue description:
Game crashing during load.

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12.2
- Forge: 2657
- Refined Storage: 1.5.32

Does this issue occur on a server? [yes/no]
SP

#### If a (crash)log is relevant for this issue, link it here:

https://pastebin.com/QTLZ0mjS

**Comment by raoulvdberge** [comment]
Downgrade Forge
