### ISSUE TITLE
refined storage/thermal dynamics crash

### ISSUE THREAD

**Issue by redgoblin88** [raoulvdberge/refinedstorage#1746]
#### Issue description:
the modpack i was playing was running perfectly fine until i added enderio. upon testing numerous methods i could not find what was wrong with the hundreds of mods i have so i decided to make a fresh instance with only the two key mods that were causing the issue: thermal dynamics and refined storage.

#### What happens:
upon having the two mods, attempting to launch the game will always crash you

#### What you expected to happen:
well.... the game to actually finish launching for one. around stage 3

#### Steps to reproduce:
1. download the latest refined storage
2. download the latest thermal dynamics (have tested with older versions, same result)
3. launch game

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12
- Forge: 14.23.3.2657 (have tested down to 2653)
- Refined Storage: 1.5.32
- Thermal Dynamics: 1.12.2-2.3.11.7

Does this issue occur on a server? Assume so yes

#### If a (crash)log is relevant for this issue, link it here:

https://pastebin.com/8Umps0p6

quick note, sorry if this seemed a bit of a cocky response. i did not intend it to be, its just how you asked for the information yielded to the point straight answers

**Comment by raoulvdberge** [comment]
Downgrade Forge.
