### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by DylexionTV** [raoulvdberge/refinedstorage#1748]
#### Steps to reproduce:
1. install no mods other than refined storage
2.try to launch the game
3.(N/A)
...

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12.2
- Forge: 14.23.3.2657
- Refined Storage: 1.5.32

Does this issue occur on a server? [yes/no]

#### If a (crash)log is relevant for this issue, link it here: https://pastebin.com/LDUKPh2s

[pastebin/gist/etc link here]

**Comment by DylexionTV** [comment]
am I missing something here? is there some requirement that the twitch launcher just isn't installing? I've used this mod before, and the mod seems to work in DW20 1.12.2 but not in any of my packs, and I haven't a clue why.

**Comment by wamc2017** [comment]
Forge version 2657 has some issues with capatibilitys: https://github.com/MinecraftForge/MinecraftForge/issues/4865

Downgrade to 2655 or upgrade to 2661.

**Comment by DylexionTV** [comment]
alright, thank you, i'll give it a shot

**Comment by DylexionTV** [comment]
actually downgrading all the way to 2618 is what worked the best, so I'll be doing that. thank you!
