### ISSUE TITLE
Item Dupe

### ISSUE THREAD

**Issue by TheBattleRooster** [raoulvdberge/refinedstorage#175]
When you have your storage far away, so it is not chunk laoded any more, connected with cables and then access it, all items start to double up after the numbers weirdly glitching out. You can pull these items out and use them to some extend place the blocks even. After a restart, items in the Grid are back to normal put placed blocks are still there.

**Comment by raoulvdberge** [comment]
Is the issue still present in 0.8.6?

**Comment by TheBattleRooster** [comment]
I am running the modpack on curse 0.8.6 is not available there yet

**Comment by raoulvdberge** [comment]
Well, I just released it so as soon as you have the release, let me know :)

**Comment by TheBattleRooster** [comment]
Jup, it's fixed in the new version. Very nice Update!

**Comment by raoulvdberge** [comment]
Amazing! Thanks
