### ISSUE TITLE
[1.12.2] Crash upon loading the game

### ISSUE THREAD

**Issue by ApexModder** [raoulvdberge/refinedstorage#1750]
#### Issue description:
Crashing during game load up, NPE

#### What happens:
When starting the game, it crashes with a NPE from RS EnergyCapability

#### What you expected to happen:
For the game to load so i could play it lulz

#### Steps to reproduce:
1. Install Forge
2. Install RS
3. Start game

#### Version (make sure you are on the latest version before reporting):
- Minecraft: 1.12.2
- Forge: 14.23.3.2657
- Refined Storage: 1.5.32

Does this issue occur on a server? Untested, mainly a solo player

#### If a (crash)log is relevant for this issue, link it here:
[crash-2018-04-15_01.13.44-client.txt](https://github.com/raoulvdberge/refinedstorage/files/1911492/crash-2018-04-15_01.13.44-client.txt)
[2018-04-15-1.log.gz](https://github.com/raoulvdberge/refinedstorage/files/1911495/2018-04-15-1.log.gz)

**Comment by raoulvdberge** [comment]
Downgrade Forge

**Comment by hron84** [comment]
@raoulvdberge could you please specify which version you recommend? It would greatly appreciated.

**Comment by ApexModder** [comment]
@hron84 i downgraded to Forge: 14.23.2.2653 and that seems to work fine, no crashing

**Comment by hron84** [comment]
@ApexModder thanks, I'll check it tonight
