### ISSUE TITLE
Grid search not showing items

### ISSUE THREAD

**Issue by Nike020410** [raoulvdberge/refinedstorage#1751]
Issue description:
The grid search for enchantments doesn't work. (and probably many other items having their name tooltip based, potions aren't really affected, but you couldn't search for "3:00" now) 
To name another case where this is "a mild annoyance": Chisel and block variants.

What happens:
The result is none, no items found, while they are still there and can be seen before typing the search.

What I expected to happen:
All items, having the searched string, even in their tooltip, should appear, just like in JEI. So a search for "silk touch" could show tinkers tools with that effect (sponge) and the books and tools with that enchantment.

Steps to reproduce:
0. you really don't need all of the mentioned mods, but I thought they illustrate the problem
1. set up the most basic grid (controller, grid, disk drive, ...)
2. take some different enchanted books and put them into the grid
3. search for any enchantment name - result should be a none
4. search for "enchanted book" - every book should appear

Version
- Minecraft: 1.12.2
- Forge: 14.23.2.2655
- Refined Storage: 1.5.32

Does this issue occur on a server? [yes/no]
I don't know and can't test it (without creating a local server, which would take my potato ages), but it should happen on servers too, it would be very surprising if not.

**Comment by raoulvdberge** [comment]
Use # or read the wiki before coming here
