### ISSUE TITLE
Constructor + Deconstructor CTD

### ISSUE THREAD

**Issue by ArmageddonX430** [raoulvdberge/refinedstorage#1753]
#### Issue description:
A combination of constructor and destructor with a fortune III upgrade results in a crash to desktop.

#### What happens:
It crashes to desktop.  When loading back into game everything works fine and constructor/destructor performs as expected.

#### What you expected to happen:
It to not crash to desktop.

#### Steps to reproduce:
1. Seed constructor with an ore - tested with both Biomes O' Plenty amber ore and Draconic Evolution draconic ore - likely to occur with any ore.
2. Flip destructor to ignore redstone mode.
3. Flip constructor to ignore redstone mode.
...
4. Profit?

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12.2
- Forge: 14.23.2.2619
- Refined Storage: 1.12.2-3.0.5.41

Does this issue occur on a server? [yes/no] no

#### If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here] https://pastebin.com/3Hvh5QSh

**Comment by raoulvdberge** [comment]
Feed the beast utils error

**Comment by ArmageddonX430** [comment]
Oh, should this bug report be routed to FTBUtils?

**Comment by raoulvdberge** [comment]
Yes
