### ISSUE TITLE
Make Reader/Writer RF capacity configurable

### ISSUE THREAD

**Issue by omgimanerd** [raoulvdberge/refinedstorage#1754]
#### Issue description:
RS Readers and writers throttle the RF transfer limit

#### What happens:
When inputting a large amount of RF into a RS Reader, the corresponding RS Writer on the same channel can only output around 16,000 RF/t.

#### What you expected to happen:
RS Reader and writer does not throttle the RF transfer rate (like AE2 P2P tunnels).
If this is an intended feature and part of design, would it be possible to make this limit configurable in the settings or upgradable via some in-game item?

#### Steps to reproduce:
1. Set up a network with a reader and writer on the same channel
2. Output a large amount of RF into the reader (from an Extreme Reactor or similar)
3. Extract RF from the writer (into something like a Draconic Evolution Energy Core)
4. Check the RF/t transfer rate out of the writer

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12.2
- Forge: 14.23.2.2627
- Refined Storage: 1.5.32

Does this issue occur on a server? yes

**Comment by raoulvdberge** [comment]
The  cap is intended. I will make it so it's configurable though, and changed your issue title to reflect that.
