### ISSUE TITLE
Unable to craft certain recipes

### ISSUE THREAD

**Issue by thelapisfox** [raoulvdberge/refinedstorage#1758]
#### Issue description: 
I am unable to craft certain recipes. This occurs within the Modern Skyblock 3 mod pack.

#### What happens: 
I open the crafting grid and search (jei synchronized) for say MV Wire Connectors from Immersive Engineering. I click the item in JEI and then click the plus button. The components fill into the appropriate slots within the crafting grid. I then click on the item to pull it out, but I don't get anything. It disappears and even the output box goes blank. The only way to get it to reappear is to go through the process again. So far, this has occurred for about 3 recipes. The only way around it is to pull the components out of the system and make it within a standard crafting table.

#### What you expected to happen: 
What should normally happen. The item should craft without issues

#### Steps to reproduce:
1. All steps listed above
2.
3.
...

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12.2
- Forge: 14.23.2.2654
- Refined Storage: 1.5.33

Does this issue occur on a server? [yes/no] Unknown

**Comment by thelapisfox** [comment]
New information. In an attempt to bypass whatever is going on here, I made two patterns. One for MV Wire Connector and another for MV Wire Relay, both from Immersive Engineering and the crafter spits the patterns out.

**Comment by raoulvdberge** [comment]
A crafter cannot spit patterns out.

**Comment by thelapisfox** [comment]
But it is doing that. Even the Crafting Manager is doing it too. I just tried adding two more patterns, hopper and an iron casing from Actually Additions and the Manager spit both of those out.

**Comment by raoulvdberge** [comment]
What do you mean by "spitting" out?

**Comment by raoulvdberge** [comment]
> EDIT: So far, about 60% of modded items (and about 20% of vanilla items) I have tried are not able to be made with this mod, at least in my game.

Are you talking about JEI autocompletion or crafting patterns?

**Comment by thelapisfox** [comment]
Just recipes period. Doesn't matter if I use JEI auto-completion or not. As for the 'spitting' out, I put the pattern into the crafter or crafting manager and instead it ends up on the ground.

**Comment by raoulvdberge** [comment]
Do you have this issue in 1.5.32?

Also, there is literally no code that makes patterns drop on the ground. I'm guessing your modpack is doing weird.

**Comment by thelapisfox** [comment]
Ok, downgraded to 1.5.32 and also addons 0.2 . The issue with patterns spitting out goes away, completely; however, the issue with some recipes not being able to be created, does not.

**Comment by raoulvdberge** [comment]
It works fine in my dev environment. I'm assuming something is wrong with your pack.
