### ISSUE TITLE
Bug with the Grids

### ISSUE THREAD

**Issue by Rams59** [raoulvdberge/refinedstorage#1760]
#### Steps to reproduce:
1. No idea how it happened, just simply started after i searched and crafted seconds before
2.
3.
...

#### Version (make sure you are on the latest version before reporting):

- Minecraft:1.12.2
- Forge:14.23.2.2627
- Refined Storage:1.5.32

Does this issue occur on a server? [yes/no]
No
#### If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here]

**Comment by raoulvdberge** [comment]
I can't do anything with bugs without reproduction steps.

**Comment by Rams59** [comment]
hard to tell when there where no certain steps

**Comment by Rams59** [comment]
it apeard out of the blue, the last thing i did was attach an exporter and importer to it, to get lootbags out of the system and pump the items bag in the system

**Comment by Tahakk** [comment]
Then try to reproduce and then report back. Easy as that
