### ISSUE TITLE
[Bug] [1.10.2] Priority not working

### ISSUE THREAD

**Issue by Keridos** [raoulvdberge/refinedstorage#1763]
#### Issue description:
Priority external Storage (Storage Drawer) vs Disk Drive not working
#### What happens:
Items are imported into disk drive instead of the external storage (drawer)
#### What you expected to happen:
Priority having an effect on where the items land
#### Steps to reproduce:
1. Set any priority for both storages
2. Import an item
3. Check where it landed
...

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge: 12.18.3.2511
- Refined Storage: 1.2.26

Does this issue occur on a server? [yes/no]
yes

**Comment by Keridos** [comment]
Why do you consider this an invalid bug?

**Comment by Tahakk** [comment]
Because 1.10.2. Move up if you want updates.
