### ISSUE TITLE
Certain items can't be extracted through an rftools storage tablet connected to an RS system through an interface

### ISSUE THREAD

**Issue by poutrosgit** [raoulvdberge/refinedstorage#1769]
#### Issue description:

Some items can't be extracted through a storage tablet connected to an RS system through an interface.

I have no idea what kinds of items do this. It seems random because different enchanted books can be extracted at random occasions just fine and not be extracted at other times.  

The issue happens if the item is inserted through the interface directly.  
The issue happens if the item is inserted through the storage tablet.  
The issue happens if the item is inserted through the crafting grid/normal grid.  
The issue happens if the item is exported into the system with an exporter.  

This issue doesn't seem to happen with other storage options from others mods/minecraft.

This issue only happenned to me in the previous version of RS (1.5.32) if the item being extracted had recently been autocrafted but it would go away after some time meaning if I waited a few minutes, I could extract the item normally.

#### What happens:

I can't extract certain items through a storage tablet connected to an RS system through an interface.  

#### What you expected to happen:

For the item to be extracted normally through the storage tablet.  

#### Steps to reproduce:
1. Setup an Refined Storage System with an interface.  
2. Put an item in it.  
3. Setup a storage scanner.  
4. Link the storage scanner to the storage tablet.  
5. Try to remove the item from the system through the storage tablet.  

#### Version:

- Minecraft: 1.12.2  
- Forge: 14.23.3.2676  
- Refined Storage: 1.5.33  
- McJtyLib: 1.12-2.6.7-SNAPSHOT (2.6.7)  
- Rftools: 1.12-7.33

**Comment by poutrosgit** [comment]
So, this feature relies on the interface exposing the entire rs inventory. Since that is getting removed, does that mean this issue can be closed?

**Comment by raoulvdberge** [comment]
Yep, thank you for following up
