### ISSUE TITLE
[1.10.2] Feature Request

### ISSUE THREAD

**Issue by kwpugh** [raoulvdberge/refinedstorage#177]
Hello,

Would it be possible to add a height-expand button to the grids for players with large screens.   It would mean less scrolling.

AE2 hand a similar feature, a button along the left side panel, it doubled the height of the screen.

BTW: I like the new textures.   Great work.

Regards

**Comment by raoulvdberge** [comment]
thanks for the compliment, however this is a duplicate of #130
