### ISSUE TITLE
[Suggestion] Importing solderer

### ISSUE THREAD

**Issue by winsrp** [raoulvdberge/refinedstorage#1772]
So 99% of the time you use the solderer you want it to import back it's stuff since normally we end up putting a crafter on it so it will auto craft, but it also needs an importer... so in order to not break your code I would suggest making an importing solderer as an upgraded block, recipe is solderer + importer, and the thing will just auto import things back to the network (if there is no storage linked it will just sit on the result slot)

Thanks for your time.

**Comment by raoulvdberge** [comment]
No.

**Comment by ineternet** [comment]
While I agree that it would be impractical to make an extra machine just for an extra mechanism, the idea behind this is actually not bad. Maybe something like a "importing crafter" instead, that also has filter options for importing (and crafted by soldering together a crafter and an importer with a diamond processor) to save that one block space that an importer would take up? You could essentially save on a third of your space and one machine face when automating on large scale.
