### ISSUE TITLE
Timed out after searching @ in grid

### ISSUE THREAD

**Issue by tedmihu** [raoulvdberge/refinedstorage#1774]
#### Issue description:
Any time a player on the server searches @ the client will freeze and the player times out. Possible related issue, any time I teleport to my base which has a lot of auto-crafters, 64k disks that are fairly full, and autocrafters pointed into machines.

#### What happens:
The client freezes and times out after searching @ in the grid

#### What you expected to happen:
Being able to search @modname and finding the item

#### Steps to reproduce:
1.Open a wireless crafting grid with a significant amount of items in it and begin typing @
...

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12.2
- Forge: 14.23.3.2655
- Refined Storage: 1.5.33

Does this issue occur on a server? [yes/no]
Yes

#### If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here]

**Comment by ineternet** [comment]
Ask your clients to provide a log

**Comment by raoulvdberge** [comment]
I need better reproducation steps and perhaps even a profiling report.

https://refinedstorage.raoulvdberge.com/wiki/profiling

**Comment by mlpcoder** [comment]
I realize this has been closed but I'm having the same issue on the current version of stoneblock. Typing @ (to search by mod) in the Crafting Grid, or # to search by tooltip immediately locks up the client to the point where I have to forcefully shut it down.  

It happens consistently.  Don't see anything especially helpful in the log, and there is no actual crash log.  Here's the last few lines of the log.

[12:05:39] [Server thread/WARN]: Can't keep up! Did the system time change, or is the server overloaded? Running 2034ms behind, skipping 40 tick(s)
[12:05:42] [JM-task-4/FATAL]: A CCL controlled model has been improperly handled by someone and will NOT be rendered. No more information available.
[12:05:53] [main/INFO]: [CHAT] §eJourneyMap:§f Press [§bJ§f]
[12:05:53] [main/INFO]: JourneyMap: Press [J]
[12:05:57] [Server thread/WARN]: Can't keep up! Did the system time change, or is the server overloaded? Running 4049ms behind, skipping 80 tick(s)

I updated RS to the latest version (1.6.8) this morning, stoneblock 1.0.22r1. Same issue.

**Comment by BuggaNoia** [comment]
I have the issue on SevTech Ages 3.0.8 in the Wiresless Crafting Grid (Addons) 
RefinedStorage 1.5.34 RefinedStorageAddOns 0.3

**Comment by raoulvdberge** [comment]
It's already fixed in dev

**Comment by ImNotIfDumb** [comment]
I'm playing version 1.6.15 and i'm also having the issue with the "#" and "$" prefixes
