### ISSUE TITLE
AutoCrafting doesnt return to Grid until its finished

### ISSUE THREAD

**Issue by bufu1337** [raoulvdberge/refinedstorage#1780]
#### Issue description / What happens:
I am waitng a long time when i craft something with 1+ stacks and he doesnt return to the Grid until its finished the crafting process. I cant get out of the GUI until its finished, so i cant autocraft in the background.

#### What you expected to happen:
In the previous version i could autocraft something, and even if it takes a long time he return to the Grid and i could close the Grid and come back later to the Matrix to pick it up.

#### Steps to reproduce:
1. Make a pattern, f.e. 9x Coal = 1x Coalblock
2. Put it into an autocrafter
3. Craft 1 Stack Coalblocks or more

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12
- Forge: 14.23.3.2676
- Refined Storage: 1.5.33

Does this issue occur on a server? no

**Comment by raoulvdberge** [comment]
Intended.
