### ISSUE TITLE
Loading Grid again when coming back from JEI

### ISSUE THREAD

**Issue by bufu1337** [raoulvdberge/refinedstorage#1781]
#### Issue description:
Loading Grid again when coming back from JEI

#### What happens:
I open up the Crafting Grid, it takes about 30sec to open up because i have millions and billions of items in the system.
On the right is also JEI and i want to get a receipt from there to make a pattern.
I press the button + there and then i have to wait again about 30sec

#### What you expected to happen:
In the previous version he gets back to the grid instantly without any waiting time when i press the + button in JEI

#### Steps to reproduce:
1. Open up the Crafting Grid
2. Click on an item in JEI
3. Press the + button at the receipt

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12
- Forge: 14.23.3.2676
- Refined Storage: 1.5.33

Does this issue occur on a server? no

**Comment by raoulvdberge** [comment]
Need a sampling dump.

https://refinedstorage.raoulvdberge.com/wiki/profiling

**Comment by xxMattewxx** [comment]
Just a small tip. If you have such a high amount of items resulting in your game lagging (when opening the grid), make another network. That network probably won't lag and you should be able to make patterns on it without problems!
