### ISSUE TITLE
High process time when using Ender Chests with refined storage

### ISSUE THREAD

**Issue by RacerDelux** [raoulvdberge/refinedstorage#1782]
Not sure where the issue lies, so reporting it in both places. This is the reported process time for the ender chest when hooked to refined storage import buss.
![image](https://user-images.githubusercontent.com/2667344/39932709-7e466608-5506-11e8-9c86-2268d453a744.png)
Adding a hopper or any other buffer between the ender chest and the refined storage import buss fixes the issue.

MC 1.12.2 ATM3
https://github.com/TheCBProject/EnderStorage/issues/82

**Comment by raoulvdberge** [comment]
Need a sampling dump.
