### ISSUE TITLE
Weirdness with EnderIO Soul Binders

### ISSUE THREAD

**Issue by trittimo** [raoulvdberge/refinedstorage#1786]
#### Issue description:
Soul binders have some sort of strange behavior going on in Refined Storage.

https://youtu.be/OPQMqXUimDs

#### What happens:
If you have a soul binder that you have performed at least one operation with, you will not be able to extract it from a network using a grid (of any kind). This is a really strange bug. So far I have not found any other EnderIO items that are acting like this.

If you have an exporter and another soul binder, you can get the soul binder into a chest... but there seems to be a ghost item that stays in the drive. Since this is a such a strange bug, I have attached a video (see above).

Another thing: if you get two soul binders (both having been used), they seem to condense into one item. This is one of the weirder bugs I've seen.

#### What you expected to happen:
There is no weirdness. They behave like other items and can be extracted through a grid. They don't leave ghost items behind.

#### Steps to reproduce:
1. Get a soul binder from EnderIO.
2. Charge it up and perform at least one operation (this does not work without this step!)
3. Put the soul binder into a drive and attempt to do things with it in a crafting grid.
4. Voila.

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12.2
- Forge: 14.23.3.2689 (most recent as of 5/13/18)
- Refined Storage: 1.5.33 (most recent as of 5/13/18)
- EnderIO: 5.0.24 (most recent as of 5/13/18)
- EnderCore: 0.5.22 (most recent as of 5/13/18)

I also have Refined Storage Addons version 0.3 (most recent as of 5/13/18)

Does this issue occur on a server? No.

#### If a (crash)log is relevant for this issue, link it here:
There are no logs.

**Comment by trittimo** [comment]
I also filed an issue for this on [the EnderIO side](https://github.com/SleepyTrousers/EnderIO/issues/4628), since I'm not certain who is causing the bug.

**Comment by trittimo** [comment]
@wamc2017 Seems to have [identified the problem](https://github.com/SleepyTrousers/EnderIO/issues/4628#issuecomment-388659896). Apparently the soul binder has a float "experience" tag that is set as NaN rather than 0 or another expected value. Somehow this is preventing normal behavior on the Refined Storage side.

**Comment by raoulvdberge** [comment]
@HenryLoenwind Are they valid in JSON?
