### ISSUE TITLE
System doesn't accept crafting using charged solar panels.

### ISSUE THREAD

**Issue by xxMattewxx** [raoulvdberge/refinedstorage#1787]
(The panels I'm talking about are from the Solar Flux Reborn mod. "Using" a panel is actually placing it down in a place with sun, letting it charge and then breaking it.)

#### Issue description:
I'm trying to make my system craft Solar Panels tier V using used (i.e charged) Solar Panels IV.

#### What happens:
If I insert newly crafted Solar Panels (i.e panels recently made, with no charge in them), all the crafting goes well. However, if I insert used Solar Panels (the charged ones) the system will tell me that solar panels are missing. All the recipes were made using the oredict thingy.

#### What you expected to happen:
System to recognize the used panels the same way as the newly made panels.

#### Steps to reproduce:
1. Make patterns using solar panels, enable ore dictionary.
2. Insert newly made solar panels into the system and try crafting the pattern you've made (this won't work for the first tier of solar panels as there are no tiers before that), the crafting will work.
3. Insert used solar panels into the system (you know if it is charged or not by looking at the item description, it will show up as charged. The system will probably tell you that resources are missing!
...

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12.2
- Forge: 14.23.3.2676
- Refined Storage: 1.5.33

Does this issue occur on a server? [yes/no] Yes.

**Comment by raoulvdberge** [comment]
RS only accepts the exact item used in the recipe, not "used" versions.
