### ISSUE TITLE
Refined Storage 1.7.10

### ISSUE THREAD

**Issue by kekko9994** [raoulvdberge/refinedstorage#1789]
it's possible to have a Refined Storage version 1.7.10???

**Comment by ReasonablySelenium** [comment]
Hello. I've started work on my own backport called StorageCraft, based on the mc.1.7.10 branch of this repo.

An alpha build is available here:
https://github.com/ReasonablySelenium/StorageCraft/releases

Cheers! :tada:

**Comment by raoulvdberge** [comment]
The 1.7.10 branch is highly technically inferior to the current versions. It was made during a time where I wasn't that good in modding and I wouldn't recommend anyone to use it.
