### ISSUE TITLE
Disappearance of storage disk elements 1.12.2

### ISSUE THREAD

**Issue by epeeforteyt** [raoulvdberge/refinedstorage#1796]
#### Description of the problem:
When using the terminal that it is the crafting or the fluid, by moment and that has just made me 2 times today, the disappearance of the items in the terminal, but the storage disk is filled but not completely.

I transfer everything in the records of applied energitics for the reviews and I can recover them

#### What happens:
Disappearance of visual elements but still in disk storages

#### Steps to reproduce:
1. I do not know unfortunately, that makes me that twice

#### Version (make sure you are on the latest version before creating a report):

- Minecraft: 1.12.2
- Forge: Forge-14.23.3.2673
- Refined storage: refinedstorage-1.5.33.jar

Is this problem occurring on a server? [Yes No] Yes

#### If a crash is relevant to this problem, link it here:
picture link:

http://w.epeeforte.ovh/CONRG9.png
http://w.epeeforte.ovh/1vhYAp.png
http://w.epeeforte.ovh/C4AnNd.png
http://w.epeeforte.ovh/Y2eZyj.png

**Comment by guardianzozo** [comment]
thats the same issue ive been having i was putting things into my grid and it blanked out but the drives still had the contents i just cannot access them

**Comment by raoulvdberge** [comment]
This is a Forge bug. Recover from backup.

Also, read previous closed issues before opening a new one.
