### ISSUE TITLE
Mekanism Mechanical Pipe disconnect from Refined Storage Reader/Writer

### ISSUE THREAD

**Issue by tehMorag** [raoulvdberge/refinedstorage#1797]
Also reported on [SevTech ages](https://github.com/DarkPacks/SevTech-Ages/issues/2529) and [Mekanism](https://github.com/aidancbrady/Mekanism/issues/5059) trackers

#### Issue description:
Rebooting the game causes the majority of "Mekanism" item "xxx Mechanical Pipe" and "xxx Universal Cable" to disconnect from "Refined Storage" item "Reader" & "Writer".

#### What happens:
[Liquid example](https://puu.sh/Ap7uB/1cd3c8ba07.png)
[Energy example](http://puu.sh/ArEKw/bd760fb2bf.png)

#### What you expected to happen:
Pipes to always stay connected

#### Steps to reproduce:
1. Set up a Reader and Writer with the same channel
2. Connect a "Mekanism" item "xxx Mechanical Pipe" to a source into the Reader
3. Set up a tank to pump the liquid out of the Writer
4. Reboot game
5. Pipes(s) would have disconnected from the Reader and Writer

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12.2
- Forge: 14.23.3.2679
- Refined Storage: 1.5.33

Does this issue occur on a server? [yes/no]
N/A (not tested)

**Comment by raoulvdberge** [comment]
As of 2f691814f40f305aeef27569b2cae6a541e9bd00 it always returns a capability however it still doesn't appear to connect.

I'm not sure who's fault it is, but it should work from my side.

**Comment by thiakil** [comment]
Your null capability tells us that we cant do anything with it (canExtract/Receive), so our pipes don't connect.
