### ISSUE TITLE
[NPE] Crafting Manager / Network Packets

### ISSUE THREAD

**Issue by artdude543** [raoulvdberge/refinedstorage#1798]
#### Issue description:
A maker of SevTech: Ages here! Got an issue posted on our tracker about the usage of BWM Recipes on RS Pattern. Full details about the issue and how to reproduce it can be found on our ticket: https://github.com/DarkPacks/SevTech-Ages/issues/2629 _(Saves on copy/paste)_

Seems to be an interaction issue with Extended Crafting.

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12.2
- Forge: 14.23.3.2690
- Refined Storage: 1.5.33

Does this issue occur on a server? [yes/no] yes

#### If a (crash)log is relevant for this issue, link it here:
Server log for accessing crafter directly: https://pastebin.com/q6ZJQHMA
Server log for accessing Crafter Manager: https://pastebin.com/24VjBTsV

**Comment by raoulvdberge** [comment]
This has been fixed in c164213edcc3b06c9c1f0b08dc446112f2baa37d
