### ISSUE TITLE
Server Bootloop

### ISSUE THREAD

**Issue by DarkestDreams24** [raoulvdberge/refinedstorage#1799]
#### Issue description:
When conduit facade was accidentally placed in front of block destroyer
#### What happens:
Server enters boot loop
#### What you expected to happen:
Block breaks everything goes normally...
#### Steps to reproduce:
1.Create block placer/destroyer setup as anyone would for ore fortune block handling.
2. Place Conduit facade (painted to be futura blocks) in between placer/destroyer..
3.
...

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12.2
- Forge: 14.23.3.2678
- Refined Storage: 1.5.33

Does this issue occur on a server? [yes/no]
Yes
#### If a (crash)log is relevant for this issue, link it here:
I dont have access to crash log for the server
[pastebin/gist/etc link here]

**Comment by raoulvdberge** [comment]
I need logs.
