### ISSUE TITLE
Drives and patterns disappeared 

### ISSUE THREAD

**Issue by killermelon1458** [raoulvdberge/refinedstorage#1801]
#### Steps to reproduce:
1.leave world afk
2.unplug computer
3.reload game
The Thing is that this has happened before without any issues 
...

#### Version (make sure you are on the latest version before reporting):

- Minecraft:
- Forge:
- Refined Storage:
I am
Does this issue occur on a server? [yes/no]
No
#### If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here]

**Comment by killermelon1458** [comment]
I would like to know what the deal is, I did not get any explaination or
help for what happened.

**Comment by Tahakk** [comment]
Maybe part of it coul be because you didn't even fill up Versions of MC, Forge and RS + there are some reports of missing pieces of computer, read those first
