### ISSUE TITLE
Autocrafting Task Crash

### ISSUE THREAD

**Issue by DoctorJew** [raoulvdberge/refinedstorage#1803]
#### Issue description:

Crash with certain autocrafting task.

#### What happens:

Server hangs up and times everyone out upon inserting items for an ongoing crafting task. 

Attempting to cancel the task also hangs up the server and times everyone out.

In both cases, the server does not exactly crash, but instead stops doing anything. No output, nobody can join. I have to stop the server manually.

#### What you expected to happen:

RS not to crash the server when doing anything with the system and finish tasks. (See steps below)

#### Steps to reproduce:

The specific task in question was an exporter requesting refined obsidian from Mekanism. 

Obsidian is being pulled from RS and enriched in enrichment chamber and then infused in Metallurgic Infuser with diamond dust. 

However, when the diamonds get used up, an exporter on that system also starts pulling diamond dust which must crafted. 

I ran out of diamonds, and tried putting more into the system but that causes one of the crashed mentioned. 

Trying to cancel all tasks created by the exporters also crashed the server.

Should note I was also attempting to create refined iridium plates through crafting tasks as well at the time.

I checked multiple times and it seems to only crash when I insert any needed materials into RS or try cancelling tasks.

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12.2
- Forge: 14.23.4.2705
- Refined Storage: 1.5.34

Does this issue occur on a server? [yes/no] yes (All the Mods 3)

#### If a (crash)log is relevant for this issue, link it here:

[latest.log](https://gist.github.com/DoctorJew/ff11d531721691bf35932cf45b3b1330)
[debug.log (has way more info)](https://gist.github.com/DoctorJew/ef144509d59458d658f1c3febd7ab0fe)

[Here is also the stuff in the crafting monitor for context](https://i.imgur.com/VH83x6Y.gifv)

**Comment by raoulvdberge** [comment]
You don't have a crashlog?

**Comment by DoctorJew** [comment]
As I mentioned, there is no crash log. The server hangs up permanently and never actually crashes. I am forced to manually close the server each time. I linked what server logs I could.

**Comment by raoulvdberge** [comment]
This makes it quite hard for me to debug.

In any case, I rewrote autocrafting for the next release. So who knows, maybe it's fixed now.
