### ISSUE TITLE
Possible dupe bug with Storage Drawers

### ISSUE THREAD

**Issue by Jeffcole1** [raoulvdberge/refinedstorage#1806]
#### Issue description:
Moving an External Storage attached to Storage Drawers causes ores pulled out to the RS system to not register as being removed from the drawers, thus duplicating them.

#### What happens:
When items are removed from the drawer network via the RS Grid, the corresponding Storage drawer continues to contain the original amount, but you still get the removed items in hand.  Then, when you put the removed items directly into the drawer, they join with what's in the drawer, and the items are doubled.

#### What you expected to happen:
Removing items via the Grid should update their counts in the drawers, so that when you put them back in the drawers, you end up with the same amount you started with.

#### Steps to reproduce:
1. Start with a drawer network with a Drawer Controller, with an External Storage attached to the Controller and connected to an RS system.  Break the Controller and External Storage, and move them somewhere so that they're (still) connected to the drawer network, reconnecting to the RS system as needed.
2. Choose an item in one of the connected Drawers, and use the RS Grid to remove all of it from the system.
3. Check the quantity of the item still in the drawer.  If the bug is in effect, the drawer should still have the same number of items it started with, even though you have the same amount of that item in your inventory.
4. Insert the items from your inventory directly into the drawer (not the RS grid).  The drawer should now contain double the items it started with (or less than double if you didn't remove them all in step 2).
...

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12.2
- Forge: 14.23.2.2618
- Refined Storage: 1.5.31 (no mention of this issue in changelogs after this version)
- Storage Drawers: 1.12.2-5.3.4

Does this issue occur on a server? yes

#### If a (crash)log is relevant for this issue, link it here:

no crash

**Comment by raoulvdberge** [comment]
No longer relevant in the latest RS
