### ISSUE TITLE
Crash on testing with ProjectE with EMC storade in Longs

### ISSUE THREAD

**Issue by VladoCC** [raoulvdberge/refinedstorage#1807]
I am testing version of ProjectE from pull request with your mod.
And it crashed when I placed External Storage with Transmutation table.

It is okey, ofcourse, but I thinked that I can fix it without your help.
In stacktrace I found thar problem were in this class:
com.raoulvdberge.refinedstorage.integration.projecte.StorageItemTransmutationTable.getStacks
Where can I find it? Here on main branch of your repository no files with this name.

**Comment by VladoCC** [comment]
I had downloaded virsion from GitHub andd compiled it. As I expected no support of ProjectE here.

**Comment by raoulvdberge** [comment]
Project e integration is removed, so don't except support for it.

**Comment by VladoCC** [comment]
Can you just give me link for sources with ProjectE api? Everything after that is my problem

**Comment by raoulvdberge** [comment]
Go the project E github

**Comment by VladoCC** [comment]
No, I mean your mod with integration code.
