### ISSUE TITLE
Wireless Transmitter Range

### ISSUE THREAD

**Issue by MachinegunMarty** [raoulvdberge/refinedstorage#181]
Noticed on 0.8.7 that having multiple transmitters with or without range updates doesn't add to the total range anymore ?

I have 3 Wireless transmitters with 4 Range upgrades each.

Tested:

1 Wireless Transmitter without range updates --> Before i get outside my house i lose signal
1 Wireless Transmitter with  4x range update --> I can get one chunk outside my house before loosing signal.

Now i added: 
1 Wireless Transmitter extra without range upgrade --> Loose signal at same place as with 1 transmitter.
1 Wireless Transmitter extra with  4x range upgrade --> Loose signal at same place as with 1 transmitter.
2 Wireless Transmitters extra with or without range upgrade --> Loose signal at same place as with 1 transmitter.

So the Wireless Transmitters don't add to each other anymore neither do the range upgrades you place on them.

If you would make the range upgrades to be able to stack on each other in the transmitter (like in ae2) that would solve it or make them add to each other again like it was.

I do feel the range is a little underwhelming tho.
I see myself having a lot of Wireless Transmitters with 4 range upgrades max. on all the spots i can find.

I think i would look allot neater if it was one Wireless transmitter with stack-able range upgrades.

btw: Love what you did with the textures !

Turned all the blocks into nice buss types now.

Looks awesome thanx !!

**Comment by raoulvdberge** [comment]
Glad to hear you like the textures. About the range: it's configurable in the config!

Also, the signal of the transmitter now starts at the location of the transmitter, not at the controller anymore, so, you'll have to spread out your transmitters :)
