### ISSUE TITLE
[1.12.2] [FTB Continuum] Chisels and Bits Cannot Be Placed on Cables

### ISSUE THREAD

**Issue by Pirateboy04** [raoulvdberge/refinedstorage#1810]
#### Issue description:
When attempting to place any bit or structure on an RS cable, the placing fails
#### What happens: 
Nothing
#### What you expected to happen:
As said on wiki, the bits can be used as facades.
#### Steps to reproduce:
1. Place a cable
2. Try to place any bit/structure from Chisels and Bits
3. Nothing happens

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12.2
- Forge: 14.23.4.2705
- Refined Storage: 1.5.34

**Comment by raoulvdberge** [comment]
Wontfix. MCMultipart has been removed anyway.

**Comment by acanady** [comment]
but why tho?

**Comment by techdude** [comment]
Is there currently an alternative for making cable fascades then? C&B was a nasty workaround, but at least it worked. Did I miss the inclusion of covers/fascades under some other name?
