### ISSUE TITLE
Issue: Unable to autocraft pure crystals from AE2?

### ISSUE THREAD

**Issue by SharkFire** [raoulvdberge/refinedstorage#1811]
#### Issue description:
So I help run a Foolcraft 3 multiplayer server and we have encountered something we can only reproduce on our server it appears and have been unsuccessful in reproducing on a single player world. Basically we can't get our refined storage system to correctly understand how to craft pure crystals.

#### What happens:
So we set up our system to interact with three things to create pure crystals from AE2. Our sag mill from EnderIO to understand how to get the dust for the crystals,
Certus Quartz + Sag mill = Certus Quartz Dust
Fluix Crystal + Sag mill = Fluix dust
Nether Quartz + Sag mill = Nether Quartz Dust

If we place these patterns in, it will understand how to do them all with no issue and work perfectly fine.

Step 2 of telling it how to turn the dust into a seed is where things can potentially mess up.

Step two is using the dust plus sand to get the seed of the respective type of pure crystal. On almost all times when we que up a seed inside our system it will understand how to do the respective seed type with the respective material. Yet on some occasions it will mix up the material and ask for nether quartz for a certus or fluix seed, or any other combo from the three.

Step three is using the seed and a crystal growth chamber to speed up the growth of the seed into a pure crystal, this stage seems to always work with no issue. The only issue that can occur in this stage is that if you order a pure crystal from the system and do not check what it is requesting it will end up looping infinitely because it will be requesting use of fluix crystal/certus quartzz/nether quartz for the incorrect pure crystal. The other issue that can occur is that it will attempt to use a different seed besides the respective seed to craft the seed you desire.

#### What you expected to happen:
To be able to order a pure crystal of the respective type and for it to understand how to take the material needed and turn it into the pure crystal

#### Steps to reproduce:
Unsure of how to reproduce outside of the server I help run, as i can only seem to get it to happen on this server.

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12.2
- Forge:  1.12.2.-2.4.2.58
- Refined Storage: 1.5.33

Does this issue occur on a server? yes

#### If a (crash)log is relevant for this issue, link it here:

No crash log as it doesn't crash.

If any other info can be of use, just let me know. I can post the entire server files here if need be (of course removing player data).

**Comment by raoulvdberge** [comment]
Please try again on RS v1.6 when it comes out
