### ISSUE TITLE
Crash from exporter with damaged item in whitelist and crafting upgrade

### ISSUE THREAD

**Issue by TheRedMelon** [raoulvdberge/refinedstorage#1812]
#### Issue description:

Only tested with flint and steel, exporter into a dispenser.  The flint and steel used for the whitelist had some damage, and the exporter was set to ignore damage, all other settings default.  Crashed as soon as crafting upgrade added.

#### What happens:

When on a server, it times out.  When on singleplayer, the client crashes.

#### What you expected to happen:

Fill the dispenser with flint and steel, crafted using a crafter.

#### Steps to reproduce:

1. Set up crafter with flint and steel pattern.
2. Set up exporter with a damaged flint and steel, (item damage not compared, don't know if this changes anything).
3. Add a crafting upgrade to the exporter.
...

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12.2
- Forge: 14.23.4.2705
- Refined Storage: 1.5.34

Does this issue occur on a server? [yes/no]

Yes.

#### If a (crash)log is relevant for this issue, link it here:

No errors, the log just stops.

**Comment by raoulvdberge** [comment]
Fixed in 1.6, where it's no longer possible to initiate tasks with damaged items through the exporter or interface.
