### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by tyler489** [raoulvdberge/refinedstorage#1813]
Forgive me for not filling out the issue discription but i dont know what that info is as this was reported to the enderio guys. https://github.com/SleepyTrousers/EnderIO/issues/4699

https://pastebin.com/Eh6Umk1S

Quote from henry 
That's a bug in refined storage. He's calling getPickBlock() with null for the target parameter, but that parameter is annotated @Nonnull.

https://github.com/raoulvdberge/refinedstorage/blob/mc1.12/src/main/java/com/raoulvdberge/refinedstorage/apiimpl/network/node/NetworkNodeDestructor.java#L105

**Comment by Gamer95875** [comment]
looks like you beat me to the post xd.
