### ISSUE TITLE
Problem with silicon

### ISSUE THREAD

**Issue by Oleksandrigo** [raoulvdberge/refinedstorage#1814]
#### What happens:
Silicon (RS) not work in inscriber(AE).
#### Steps to reproduce:
It will be easier if I give you a link.

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12.1
- Forge:14.23.4.2707
- Refined Storage: 1.5.34

Does this issue occur on a server? [yes/no] --- No

#### If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here]

**Comment by raoulvdberge** [comment]
That is an AE problem and not my one. RS silicon is correctly oredicted.

**Comment by Tahakk** [comment]
https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/3534 @fscan said it is fault of RS 😞
