### ISSUE TITLE
Disk unreadable after moving the network [Duplicate][1.12.2]

### ISSUE THREAD

**Issue by Fungie2134** [raoulvdberge/refinedstorage#1815]
#### Issue description:
I had a little network in my base (Fluid grid + Grid + Controller + Disk drive) with 1 4K storage disk, and a 64k Fluid storage disk. And I just decided to change my base's location, so I took my drives in the disk drive, and moved. Then, I reinstalled the entire network, putted the disks back in, and opened the grid.
#### What happens:
The items didn't show up. I tough I did it wrong, but no. Note that If i add new items they show up and no issue with them. But all the old ones are totally out of reach. I even tried in creative mode to get the items out of this cell trough a disk manipulator, nothing. (Note that the items inserted after the bug occurs had been transferred, it only locks on the others.
#### What you expected to happen:
I expect the items stored in the disk to show up.
#### Steps to reproduce:
I don't know. It only happens a very few times.

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12.2
- Forge:14.23.4.2707
- Refined Storage:1.5.34

Does this issue occur on a server? yes

#### Others infos 
I tried using the latest version compiled from github on the server, nothing changed.

Here is the complete mod list (serverside) : 
_Chisel-MC1.12.2-0.2.0.31.jar
CoFHCore-1.12.2-4.5.2.19-universal.jar
CoFHWorld-1.12.2-1.2.0.5-universal.jar
CodeChickenLib-1.12.2-3.1.9.344-universal.jar
ExtremeReactors-1.12.2-0.4.5.49.jar
LuckPerms-Sponge-4.2.25.jar
Mantle-1.12-1.3.2.24.jar
Nucleus-1.4.0-S7.0-MC1.12.2-plugin.jar
OpenComputers-MC1.12.2-1.7.2.67.jar
RedstoneFlux-1.12-2.0.2.3-universal.jar
SimplyJetpacks2-1.12.2-2.2.7.45.jar
TConstruct-1.12.2-2.10.1.DEV.GITBORK.jar
ThermalDynamics-1.12.2-2.5.1.14-universal.jar
ThermalExpansion-1.12.2-5.5.0.29-universal.jar
ThermalFoundation-1.12.2-2.5.0.19-universal.jar
environmentaltech-1.12.2-2.0.11a.jar
foamfix-0.9.9.1-1.12.2-law.jar
jei_1.12.2-4.9.2.196.jar
refinedstorage-1.5.34.jar
spongeforge-1.12.2-2705-7.1.0-BETA-3151.jar
valkyrielib-1.12.2-2.0.11a.jar
woot-1.12.2-1.3.0.jar
zerocore-1.12-0.1.2.2.jar_

**Comment by raoulvdberge** [comment]
Don't make duplicate issues if you know you're making a duplicate issue.

This is a Forge bug.

But I've worked around it in development versions. Coming soon.
