### ISSUE TITLE
Scroll picks item up. 

### ISSUE THREAD

**Issue by CrossVas** [raoulvdberge/refinedstorage#1819]
#### Issue description:
Scroll down/up pick up items.

#### What happens:
When your cursor is on items and you scroll down/up in *any* Grid it automatically pick up those items. 

#### Steps to reproduce:
1. Set up a RS system with *any* grids. 
2. Make sure that you have a lot of items to be able to scroll up\down to see them all.
3. Scroll up\down.

#### Version:
- Minecraft: 1.12.2
- Forge: 1.12.2-14.23.4.2703
- Refined Storage: 1.5.34

![rs](https://user-images.githubusercontent.com/25727222/41457544-b468c810-708c-11e8-9e33-1773409735d9.gif)

**Comment by raoulvdberge** [comment]
Those are fake slots. RS has no scrolling to inventory code. So this is caused by a bad integration mod.
