### ISSUE TITLE
crafting grid item count display issue

### ISSUE THREAD

**Issue by adelayde** [raoulvdberge/refinedstorage#182]

**Comment by adelayde** [comment]
Looks like I missed an external storage connection to an RFTools modular storage.  Removed this, and the problem disappeared.

Interestingly, I was also losing items.  Attempted to craft compressed cobble that was in modular storage via the refined storage crafting grid using shift-click for stacks, and managed to convert 8k of cobble into only 4 stacks of compressed (2k worth).  Something is not right...

**Comment by raoulvdberge** [comment]
I don't think you are losing items, it's just a desync issue...

**Comment by raoulvdberge** [comment]
Why did you remove all your comments? Makes it kinda hard for me to debug...

**Comment by raoulvdberge** [comment]
The itemcount display issue is fixed. Were there any other problems you've been having or can I close this?
