### ISSUE TITLE
Suggestion: RS API Extension - Network Energy Core

### ISSUE THREAD

**Issue by Samtrion** [raoulvdberge/refinedstorage#1823]
Hi,

I'm currently thinking about an Extension Mod for RefinedStorage. The basis for the idea is the ability to make refined storage significantly heavier in terms of energy consumption, both in early and in late game.

I already have some ideas for this, but I fail because of the fact that I'm struggling with the access of the energystorage of the refined storage network. At the Moment i can only access through Reflection, which would be a total impact on performance.

So I would suggest an extension of the RS API that makes it possible

e.g. place additional energy cells in the network and the sum then gives the network energy capacity. 100000 RF controller + 2x 50,000 RF power cell = 200000 total capacity.
The ability to consume more energy sources via connector blocks, several blocks away from the controller block.
And many more Ideas about this topic.

If you would agree, I would take on the development and send you a PR upon completion.

**Comment by raoulvdberge** [comment]
I think it's a good idea.

If you do want to do this however, keep in mind:

- a simple getter that returns an `EnergyStorage` object isn't sufficient;
- the extension point needs to be able to hook into the point where Refined Storage machines extract energy (perhaps remove the `INetworkNode#getEnergyUsage` method and make every `INetworkNode#update` call a method in `INetwork` (something like `INetwork#extractEnergy`?)

**Comment by Samtrion** [comment]
A simple getter is definitely not enough, I have here something like a proxy per node in mind.
Because the controller behaves quite differently than a power connector or a power cell.
In addition, it is completely open at this time, whether an energy cell receives at all the ability `CapabilityEnergy.ENERGY`.

The idea of removing the `INetworkNode#getEnergyUsage` method and replacing it with a slightly more complex logic is not bad.

This would make it possible to differentiate between active and passive energy consumers.
For example: An importer passively consumes x RF / t and actively y RF per item.

**Comment by raoulvdberge** [comment]
I initiated a little poll on Twitter to check if we should maybe move to active energy only.

https://twitter.com/vdbergeraoul/status/1009187099361366018

**Comment by Samtrion** [comment]
Have already voted. But the option "Configurable per node type" would be my current wish option.

This would allow to configure some basic consumption for the network and at the same time direct consumption spikes for massive operations such as Quarry Imports or Disk Manipulator.

This would significantly affect the gameplay depending on the modpack.
