### ISSUE TITLE
Fix your trash mod

### ISSUE THREAD

**Issue by Shybella** [raoulvdberge/refinedstorage#1825]
![download](https://user-images.githubusercontent.com/4436776/41562384-fb7c58a6-7326-11e8-9185-086325221b28.png)

**Comment by Shybella** [comment]
you gotta survive off copying outdated versions of ae2 lol

**Comment by shinzoop1** [comment]
Can you please fix this issue its causing me lots of lag as well when people start mass crafting.

**Comment by shinzoop1** [comment]
why close this its not fixed

**Comment by Samtrion** [comment]
With the upcoming version 1.6 the crafting system will be improved.
At the same time, it is understandable that this issue was closed. See the author's behavior.
