### ISSUE TITLE
Hide the cables

### ISSUE THREAD

**Issue by wandersonbrazdf** [raoulvdberge/refinedstorage#1830]
Hello everyone, I would like to know how to hide the cables of the Refined storage I tried using the chisels & bits as I saw in some forums but I have experienced great difficulties I am putting 2 prints one of a video that I saw this being done and one of my map where I can not slip the cables.

https://imgur.com/a/z0o0r7k

...

#### Version (make sure you are on the latest version before reporting):

chiselsandbits-14.16
MCMultiPart-2.5.1
Minecraft 1.12.2 - MultiMC
refinedstorage-1.5.33
forge-1.12.2-14.23.3.2655-universal

**Comment by raoulvdberge** [comment]
What's the problem?

**Comment by wandersonbrazdf** [comment]
Hello I can not hide the cables using the chisels & bits covers as I showed in the screenshots.

**Comment by raoulvdberge** [comment]
Please head over to our Discord to ask your question there, this issue tracker is merely for bugs.
