### ISSUE TITLE
I can put in Pattern into disconnected MutliBlock Crafter

### ISSUE THREAD

**Issue by PanSzelescik** [raoulvdberge/refinedstorage#1836]
#### Issue description:
I can put in Pattern into disconnected MutliBlock Crafter
#### What happens:
I see disconnected MutliBlock Crafter in Crafter Manager
#### What you expected to happen:
I was expecting in step 4. that I would not see him
#### Steps to reproduce:
1. Plug MultiBlock Crafter to your system
![image](https://user-images.githubusercontent.com/26679785/41979891-6ef2a5b0-7a25-11e8-8c81-6d2d5380bc5e.png)
2. Look into Crafter Manager
![image](https://user-images.githubusercontent.com/26679785/41979904-7a846328-7a25-11e8-9db9-4fb7661299fe.png)
3. Unplug MultiBlock Crafter
4. Look into Crafter Manager
![image](https://user-images.githubusercontent.com/26679785/41979936-8a7df050-7a25-11e8-8728-900b54f0d102.png)
5. Try to put a Pattern
![image](https://user-images.githubusercontent.com/26679785/41980002-b49d96e2-7a25-11e8-87e4-98bb96141961.png)
6. Is in MutliBlock Crafter 
![image](https://user-images.githubusercontent.com/26679785/41979990-abfcf596-7a25-11e8-9080-3d482a20e712.png)

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12.2
- Forge: 2613
- Refined Storage: 1.6
- Reborn Storage 3.1.0.56
- EnderIO 5.0.541-nightly
- EnderCore 0.5.33

Does this issue occur on a server? [yes/no]
I don't know
#### If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here]

**Comment by raoulvdberge** [comment]
Does the item appear as craftable in your Grid?

**Comment by PanSzelescik** [comment]
I did not check it because this error does not work anymore :/

**Comment by PanSzelescik** [comment]
![image](https://user-images.githubusercontent.com/26679785/41980564-0a55b7d0-7a27-11e8-8186-f1cefdc33093.png)
What? This conduit is disconnected

**Comment by PanSzelescik** [comment]
![image](https://user-images.githubusercontent.com/26679785/41980924-02f28b02-7a28-11e8-93bb-da672891eb66.png)
Here, where is cobble, i placed RS Conduit, and I break it

**Comment by raoulvdberge** [comment]
But your screenshots in the initial posts show an RS cable, not an EiO cable? So you can reproduce this with both?

**Comment by PanSzelescik** [comment]
But before I placed in the same place Refined Storage Conduit

**Comment by PanSzelescik** [comment]
It works that way:
https://youtu.be/EMiTQeel0Co
Reborn Storage has nothing to do with it and Refined Storage Cable

**Comment by raoulvdberge** [comment]
Lol! And you can't reproduce this with just RS cables? It only happens with EiO conduits?

**Comment by PanSzelescik** [comment]
yes, i think this is a bug with conduit

**Comment by raoulvdberge** [comment]
Then I would suggest reporting this to the EiO devs on their issue tracker! :)
