### ISSUE TITLE
Solderer grabbing incorrect number of items when autocrafting/not autocrafting pre-requisits before future recipes

### ISSUE THREAD

**Issue by SplitInfinitive** [raoulvdberge/refinedstorage#1837]
#### Issue description:
The crafting system is inserting the incorrect number of ingredients to make circuits when the ingredients don't exist in the system but it can craft them.  It's trying to craft materials out of order (making the full circuits without all the required bits).  This combines with the removal of blocking mode to cause solderers (and possibly other machines with multiple inputs) to jam your crafting recipes.

#### What happens:
Solderer has incorrect number of items in it

#### What you expected to happen:
Solderer crafts per-requisits before final steps

#### Steps to reproduce:
1. add all relevant recipes to the system
2. ask system to make something complicated (4k disk for example)
3. baby sit the solderers

#### Version (make sure you are on the latest version before reporting):

- Minecraft:1.12.2
- Forge: 2705
- Refined Storage: 1.6

Does this issue occur on a server? [yes/no]
yes

#### If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here]

**Comment by raoulvdberge** [comment]
Wait. You are kind of phrasing it in a weird way. It probably makes the correct number of items, but it just jams when making the different processors, right?

So the issue here is that it jams the solderers?

**Comment by SplitInfinitive** [comment]
sorry about my wording.  When asked to make 4 circuits and it has to make the printed silicon or other parts it tries to make all 4 of the circuits but can't because it hasn't got all the input requirements so it just inputs what it can, ending up with 3 of some of the ingredient and 4 of the other.  when it finishes there's leftover and it can't continue until you clear it.

**Comment by raoulvdberge** [comment]
Ah. Well, this issue sounds like a solderer specific issue. Can you try to reproduce it with other machines from other mods?

**Comment by SplitInfinitive** [comment]
I'll get back to you if we can reproduce with another machine.

**Comment by raoulvdberge** [comment]
Thanks!

**Comment by raoulvdberge** [comment]
Should be fixed by

fb19aa2983930169f8ffdab1db4dae7fe2f08ad7
b231641b1b094ab2974570ba94f0536628732113
a908cbdaf0b735c5903b33bb1ec0809e5571f8d2
