### ISSUE TITLE
Crash using CTM (1.12.2)

### ISSUE THREAD

**Issue by xhatz** [raoulvdberge/refinedstorage#1838]
#### Issue description:
The game crashes when clicking on the creative tab for Refined Storage, while CTM is installed.

#### What happens:
The game crashes ;-;

#### What you expected to happen:
Just the inventory tab working properly!

#### Steps to reproduce:
1. Install CTM
2. Install Refined Storage
3. Click on the Refined Storage tab in the creative menu
(I'm using a custom modpack though, I don't know if it's linked only to CTM or other mods too...)

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12.2
- Forge: 14.23.4.2725
- Refined Storage: 1.5.34

Does this issue occur on a server? [yes/no]
I don't know, probably.

#### If a (crash)log is relevant for this issue, link it here:
https://paste.dimdev.org/ukoromidap.mccrash

**Comment by raoulvdberge** [comment]
That is a Chisel/ CTM issue.

**Comment by PanSzelescik** [comment]
https://github.com/Chisel-Team/ConnectedTexturesMod/issues/63
