### ISSUE TITLE
Autocraft upgrade no longer works

### ISSUE THREAD

**Issue by SplitInfinitive** [raoulvdberge/refinedstorage#1839]
#### Issue description:
See title

#### What happens:
When putting autocraft upgrades into exporters so that the system can just "fill to capacity" a machine, the system doesn't autocraft.  it will export if the item is in the system but will not make more if it isn't (even though it knows how to make the item)

#### What you expected to happen:
autocraft the item when it runs out in the system

#### Steps to reproduce:
1. Put autocraft upgrade on exporter.
2. Put recipe for the item in question in the appropriate crafter

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12.2
- Forge: 2705
- Refined Storage: 1.6

Does this issue occur on a server? [yes/no]
yes

#### If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here]

**Comment by raoulvdberge** [comment]
With which item do you have this? And does it occur with every item?

**Comment by raoulvdberge** [comment]
Can you try this build and let me know if it's fixed:

https://jenkins.raoulvdberge.com/job/refinedstorage/141/

Thank you.

**Comment by raoulvdberge** [comment]
I'm assuming this is fixed, @SplitInfinitive ?

If the issue persists, feel free to re-open.
