### ISSUE TITLE
Portable Grid Huge FPS loss

### ISSUE THREAD

**Issue by ShaCraft** [raoulvdberge/refinedstorage#1840]
#### Issue description: 
When holding the Portable my frames drop from 250 to 70-125.
If I put it back in my inventory so I can not see it they go back up. This is with and with out a disk of any size in it.  Tested in void world also.

#### What happens:
Frames drop in half or worst depending on surroundings. 

#### What you expected to happen:
no loss?

#### Steps to reproduce:
1. Hold portable grid in had or have it on the hot bar.

#### Version (make sure you are on the latest version before reporting):
- Minecraft: 1.12.2
- Forge: 14.23.4.2705
- Refined Storage: 1.5.34

Does this issue occur on a server? [yes/no]
Yes

***Notes its fine when placed or not rendered.

**Comment by raoulvdberge** [comment]
https://refinedstorage.raoulvdberge.com/wiki/profiling

Thank you.

**Comment by ShaCraft** [comment]
Here is an export:


[PortableGrid.zip](https://github.com/raoulvdberge/refinedstorage/files/2157250/PortableGrid.zip)

**Comment by raoulvdberge** [comment]
Should be fixed in 1.6.
