### ISSUE TITLE
[Feature Request] Add a priority for processing patterns.

### ISSUE THREAD

**Issue by CrossVas** [raoulvdberge/refinedstorage#1841]
#### Issue description:
If you have two recipes which use the same machine to make their parts, Crafter with Processing Pattern inside will try to insert all the "raw" ingredients to process them. 

#### What happens:
It will block the process (and machines as well) until the player will clean the machines manually helping them to finish the crafting process.

#### What you expected to happen:
Crafter must try to insert ingredients only from one Processing Pattern not from all at once. 

#### Steps to reproduce:
1. Set up a RS system with crafters and machines (I used Induction Smelter from Thermal Expansion) 
2. Encode some processing pattern to make alloys (bronze, invar, electrum)
3. Encode some recipes which use these alloys (I encode Upgrade Kits from Thermal Expansion)
4. Request 2xHardened Kits and 2xReinforced Kits at the same time.
...

#### Version:

- Minecraft: 1.12.2
- Forge: 1.12.2-14.23.4.2703
- Refined Storage: 1.6

![image](https://user-images.githubusercontent.com/25727222/42131972-e5cbdf3c-7d16-11e8-938e-42dd5d2d97cb.png)
![image](https://user-images.githubusercontent.com/25727222/42131974-f1ffb468-7d16-11e8-83ca-c1db353fc60d.png)
![image](https://user-images.githubusercontent.com/25727222/42131975-f786fc02-7d16-11e8-9827-326ba909dd81.png)

**Comment by CrossVas** [comment]
I can confirm. [#_135](https://jenkins.raoulvdberge.com/job/refinedstorage/135/) work fine!!

**Comment by raoulvdberge** [comment]
Thank you!
