### ISSUE TITLE
Server crash, shut down by server watchdog, single tick taking too long.

### ISSUE THREAD

**Issue by TheDarkPreacher** [raoulvdberge/refinedstorage#1843]
Version: 1.5.34
Forge: 14.23.4.2705

Issue is in Coop Life 2 server. Server watchdog shut down the server due to a single tick taking too long. Also reported to Tech Reborn team (https://github.com/TechReborn/TechReborn/issues/1564). Paste of crash report: https://pastebin.com/LAZndHfy

**Comment by raoulvdberge** [comment]
Fixed for 1.6!
