### ISSUE TITLE
Cable Covers

### ISSUE THREAD

**Issue by raoulvdberge** [raoulvdberge/refinedstorage#1845]
- [x] Add covers for Constructor / Destructor / Reader / Writer
- [x] JEI integration
- [x] Performance of the baked block model
- [x] Hollow covers
- [x] Narrow Hollow Covers

**Comment by axoxelol1** [comment]
Any way you could add support for the Thermal Expansion/Dynamics covers? those support connected textures and are easy to use. I have no idea if this is even possible just tossing an idea out

**Comment by raoulvdberge** [comment]
No.

**Comment by raoulvdberge** [comment]
Implemented for 1.6
