### ISSUE TITLE
Major TPS drop when using colossal chests as external storage

### ISSUE THREAD

**Issue by tiffit** [raoulvdberge/refinedstorage#1847]
#### Issue description:
When the refined storage is connected to a large colossal chest using an external storage, the TPS drops from 20 to down to 4. I used WarmRoast to find out that this was the problem ([as seen here](https://i.imgur.com/9sqyysT.png)). The colossal chest has a storage space of over 9M (according to the external storage), so it seems that every tick, the external storage attempts to copy every itemstack. 

#### What happens:
TPS falls down to a constant 4.

#### What you expected to happen:
TPS to stay at 20.

#### Steps to reproduce:
1. Create a 11x11x11 diamond colossal chest
2. Connect it to a RS using an external storage

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12.2
- Forge: 14.23.4.2715
- Refined Storage: 1.5.34

Does this issue occur on a server? yes

#### If a (crash)log is relevant for this issue, link it here: 

https://i.imgur.com/9sqyysT.png

**Comment by raoulvdberge** [comment]
Don't use a collosal chest as storage.

**Comment by ShayBox** [comment]
That's not really an acceptable solution, this is an RS issue as AE2 doesn't have this problem with colossal chests, or any other large slot based storage container like RS does, and just "Don't use a collosal chest as storage." is more of a lazy cop out instead say, "I don't want to fix it" or "I don't know how to fix it".
