### ISSUE TITLE
functions extractItem and extractFluid return "Method com/raoulvdberge/refinedstorage/tile/TileController.getPos()Lnet/minecraft/util/math/BlockPos; is abstract" in OpenComputers

### ISSUE THREAD

**Issue by KerJoe** [raoulvdberge/refinedstorage#1855]
#### Issue description:
Unable to extract anything via OpenComputers using functions
extractItem and  extractFluid

#### What happens:
Trying to extract items or fluids from network results in a table

```
nil

"Method com/raoulvdberge/refinedstorage/tile/TileController.getPos()Lnet/minecraft/util/math/BlockPos; is abstract"
```

#### What you expected to happen:
Expected items and fluids to appear

#### Steps to reproduce:
1. Create an OC computer with a case, a screen, a keyboard and an adapter
2. Place RS controller next to the OC adapter, connect a grid, a fluid grid and a disk drive to the controller
3. Insert a storage disk and a fluid storage disk
4. Execute these commands in lua interpreter:
```
a=component.energy_device.getItems()[1]
component.energy_device.extractItem(a, 10, sides.up)
```
or 
```
a=component.energy_device.getFluid()[1]
component.energy_device.extractFluid(a, 1000, sides.up)
```

#### Version:

- Minecraft: 1.12.2
- Forge: 14.23.4.2705 
- Refined Storage: 1.5.34
- OpenComputers: 1.7.2.67

![2018-07-07_16 19 37](https://user-images.githubusercontent.com/40915672/42411070-6f333380-8206-11e8-96f1-f97eb0f53b0c.png)

![2018-07-07_16 19 18](https://user-images.githubusercontent.com/40915672/42411069-6722f4c8-8206-11e8-8c7a-7b1276f60a8c.png)

**Comment by raoulvdberge** [comment]
Can you report this to open computers? I can't figure out the issue and I think this is an issue on their end. Thanks.

**Comment by raoulvdberge** [comment]
This has been fixed. Don't connect it to the controller, but connect it to another network block.
