### ISSUE TITLE
Semi-Corrupt world when adding interface to RS network

### ISSUE THREAD

**Issue by PiggyWhiskey** [raoulvdberge/refinedstorage#1861]
I attempted to create a Crafting pattern of 2 Fortune I books = 1 Fortune II
I placed it in an Interface with a Crafting Card and External Storage connected (Keep in stock)
This corrupted my world.

I removed the Interface and External Storage using MCEdit

I can load the game and play perfectly fine.
I can place standard blocks (Types of brick etc) in the place where the Interface/External Storage was and remove them perfectly fine.

The moment I place another interface there, all Tile Entities freeze up and refuse to work.
I can continue to move around the world without issue.
I cannot Save/Quit without killing the process.

MC: 1.12.2
Forge:  14.23.4.2729
RS: 3.1.0.50

Modpack: FTB Revelation 2.2.0 SSP

---

No entries show up in Debug/latest logs at the time the Interface is placed and breaks the world.
I have tried removing the Controller to rebuild the RS network, both in game, and from MCEdit with no change to the above issue.

World Save:  https://www.dropbox.com/s/n27fgs6vq9yqyrf/2018-07-09-16-44-01.zip?dl=0
This is from after removing the Interface/External Storage.

The problem location is at the location of my player (PiggyWhiskey)
DIM3
Interface:
x: -365, y: 66, z: -237
External Storage:
x: -366, y: 66, z: -237

---

I'm wondering what I need to do to recover the existing world/save to be playable.

Edit: After some additional testing, only those 2 blocks are causing issues.
I can add/remove from anywhere else on the network without issues.

**Comment by raoulvdberge** [comment]
1) "3.1.0.50" is a non existant RS version
2) Can you check if you have any crash reports or logs?

**Comment by PiggyWhiskey** [comment]
My mistake, not sure where I got that version number from.

1. refinedstorage-1.5.34
2. Thank you :)
3. After the issue I looked up other issues people had and found your other comments on it.
4. That fix worked.

Thank you for your help :)

👍
