### ISSUE TITLE
External Storage not seeing Compacting Drawers

### ISSUE THREAD

**Issue by mikeskey** [raoulvdberge/refinedstorage#187]
I am not sure if this is intended or if it's supposed to work. I have an external storage placed on my drawer controller and then have my compacting drawers around the drawer controller but it seems as the external storage isn't seeing the compacting drawers through the controller. Is this a known bug/issue or something that hasn't been noticed yet? Btw I am able to see and interact with them on a single basis if I put an external storage on each drawer but that seems rather costly and unneccessary if there is a work around.

**Comment by raoulvdberge** [comment]
version please..

**Comment by mikeskey** [comment]
Minecraft 1.9.4 Refined Storage is 0.7.19 and Storage Drawers is 1.9.4-3.1.11

**Comment by raoulvdberge** [comment]
You are running 10 versions behind, try the latest one for 1.10 and let me know if it works.

**Comment by mikeskey** [comment]
The server isn't 1.10 so I guess this will have to wait till we update everything else to 1.10 then because as far as I know a 1.10 mod won't work on a 1.9.4 server. Thanks though.

**Comment by raoulvdberge** [comment]
1.9 mods work on 1.10 also worlds are compatible between versions, so updating is easy.
