### ISSUE TITLE
Minecraft 1.10.2 Lag issue after creating large numbers of patterns.

### ISSUE THREAD

**Issue by PL3BAN** [raoulvdberge/refinedstorage#1872]
I know you don't accept bugs for 1.10.2 but this is rather performance issue :)
#### Issue description:
After setting up a large amount of Crafters and filling them with patters any new patterns start to disappear, tickrate lag start, autocrafting speed falls downs.

Putting patterns in a Multiblock Crafter fixes the issue with disappearing patterns and kind of fixes the tickrate issue. Minning blocks still lags but now after opening the Grid or any other inventory and letting it fully "load" (around 5s) you can move items in and out without any lag or delay, however after reopening the storage you need to wait for the items to "load" again.

#### What happens:
Tickrate lag block take around 5s to mine, taking out things from any kind of storage takes also around 5s, opening any kind of inventory and especially Grid takes up to 15s if you have some autofarms going. Autocrafting slows significantly.

#### What you expected to happen:
None of the above, this might be fixed in later releases but I'm using it on Sky Factory 3 and sadly no way to upgrade it higher that 1.2.26

#### Steps to reproduce:
1. Create a simple item grid with the following: Grid, Pattern Grid, 1k storage block, Controller.
2. Add 56 Crafters and fill them up with patterns (add one Crafting Table patter for tests).
They should be filled with different patterns as the ones of same type simply stack.
3. Try to mine blocks, take out planks or insert them into the Grid, open and close the Grid, try to insert more patterns and try to craft some Crafting Tables or other things you desire.

You can also try to create system with Multiblock Crafter to test my results for yourself.

#### Version (make sure you are on the latest version before reporting):
- Minecraft: 1.10.2
- Forge: 12.18.3.2477
- Refined Storage: 1.2.26

Does this issue occur on a server? [yes/no]
No. 

#### If a (crash)log is relevant for this issue, link it here:
[Sky_Factory.zip](https://github.com/raoulvdberge/refinedstorage/files/2190789/Sky_Factory.zip)

[pastebin/gist/etc link here]

**Comment by PL3BAN** [comment]
Also my specs:
CPU: Intel Core i5 - 4670k 2x 3,4GHz
GPU: AMD Radeon R9 200 Series 3GB GDDR5
RAM: 16GB
OS: Win 7 Pro

**Comment by raoulvdberge** [comment]
1.10 is unmaintained, don't open issues for it.
