### ISSUE TITLE
Crafters outputting wrong items

### ISSUE THREAD

**Issue by tritechnik** [raoulvdberge/refinedstorage#1874]
#### Issue description:
Crafters are changing what is input into them.
#### What happens:
Lapis turns to yellow dye, and cobble to flint in any crafter outputting to a machine.  There are a few others I've noticed so far. Exporters work as expected (lapis exported to a chest is lapis).  I've done some further testing and yellow dye also takes over coal dust. Autocrafting recipes in crafters works fine, it's just when exporting to a machine. Most crafting recipes still work fine so far.

#### What you expected to happen:
Crafters producing the item as in the pattern.

#### Steps to reproduce:
1.make a pattern of Cobble=gravel
2.Put in to crafter pointing to a pulverizer
3.flint is input
...

#### Version (make sure you are on the latest version before reporting):

- Minecraft:1.12.2
- Forge:2715
- Refined Storage:1.5.34

Does this issue occur on a server? [yes/no] yes

Just a added note, and I don't know if its related, but I am running notenoughids on the clients/server as this is a very large custom modpack. I don't know if its your mod causing it, but I though I'd try here first.

Thanks in advance!

**Comment by raoulvdberge** [comment]
This is most likely fixed for RS 1.6 ! Coming out soon
