### ISSUE TITLE
Crash When Power Controller 

### ISSUE THREAD

**Issue by CrossVas** [raoulvdberge/refinedstorage#1875]
#### Issue description:
Client Crash when you try to power controller. 

#### Steps to reproduce:
1. Place Controller.
2. Power it. 
3. Voila!
...

#### Version:

- Minecraft: 1.12.2
- Forge: 1.12.2-14.23.4.2732
- Refined Storage: 1.6-201

#### If a (crash)log is relevant for this issue, link it here:

[Crash-report](https://pastebin.com/MgN0dDjB)

**Comment by raoulvdberge** [comment]
Eh, I can't reproduce this. What mods are you using?

**Comment by raoulvdberge** [comment]
Are you using Optifine?

**Comment by raoulvdberge** [comment]
Ah, I was able to reproduce with Optifine installed. It will no longer crash now. Unfortunately, you want be able to enjoy fullbright textures with Optifine installed.
