### ISSUE TITLE
Can I share this mod with the minecraft forum in China?

### ISSUE THREAD

**Issue by 6Bpencle** [raoulvdberge/refinedstorage#1879]
The mod is very interesting ,I very like it.I think you can do it better.So I want to share this mod with the minecraft forum in China and let more friends use it.I hope you can agree!
I can abide by the following terms：
1.Clarified origin author name which is YOU(I just a "reposter")
2.Clarified origin URL link could reach this mod‘s’ official web/Curse Forge directly
3.Never re-compile/re-package/re-distribute this mod
4.A free/AD-free Chinese net-disk download link to boost download speed(No cent could be earn)

**Comment by raoulvdberge** [comment]
I'm not very familiar with China, but why do you have to provide your own download link? Is CurseForge unavailable there?

**Comment by raoulvdberge** [comment]
It's fine for me though. The mod is licensed under MIT, so you can do what you want.

**Comment by 6Bpencle** [comment]
Sometimes projects on CurseForge cannot be downloaded in China.Thank you give me this mod's licensed.
