### ISSUE TITLE
Unable to remove item

### ISSUE THREAD

**Issue by utoc** [raoulvdberge/refinedstorage#188]
Greetings,

This bug I am reporting was a one-off issue and we could not duplicate it.  Reporting it for ya'll to examine and close as needed.

FML 8.0.99.99
Refined Storage 0.8.9
on Minecraft 1.10.2

The item in question was a blank soul shard from the [SS-TOW](http://minecraft.curseforge.com/projects/soul-shards-the-old-ways) mod and you just couldn't remove the item.  Click it. Shift click.  Stare angrily.  Nothing.  To resolve the issue, the disk was isolated, all other items removed and then the disk was destroyed in the fires of Mount Doom.  When a new soul shard was created, we were able to add/remove it from the grid without any issue.

I did take a few screenshots of the NBT data if there is any good to them as can be seen here: http://imgur.com/a/zByvV

Love your mod!  Have a nice day.

**Comment by raoulvdberge** [comment]
hey, thanks for reporting but this is a duplicate

for now i recommend to export the stuck item without comparing on nbt and damage
