### ISSUE TITLE
Performance

### ISSUE THREAD

**Issue by mrjoes** [raoulvdberge/refinedstorage#1880]
#### Issue description:
Refined Storage is slowing down a fairly perfomant server with a relatively large RS network (dozens of exporters, importers, crafters, etc). I also have fully-upgraded void miner (environmental tech) pumping items into the network via interfaces, ore is automatically processed using various mods, etc. Just in case, the RS is a part of the All the Mods 3 modpack.

I'm not very familiar with the source code of this mod, but one thing was interesting - most of the time was spent in the `invalidate()` function and I'm not sure why my network is rebuilding on almost every tick.

It's very possible that the network is running out of power and turning on and off, but it's hard for me to test that at the moment - client just times out. Even with a stable power supply, `invalidate()` took most of the time when items were inserted or removed from the network.

See attached profiling log.
[2.zip](https://github.com/raoulvdberge/refinedstorage/files/2196406/2.zip)
 
#### What happens:
Server is less than 1 TPS (0.36) on an overclocked i7-4790k.

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12.2
- Forge: 14.23.4.2175
- Refined Storage: 1.5.34

Does this issue occur on a server? YES.

**Comment by raoulvdberge** [comment]
The network is constantly turning on and off, thjat is the problem.

>  Even with a stable power supply, invalidate() took most of the time when items were inserted or removed from the network.

I need a profiling report for that too then.

**Comment by mrjoes** [comment]
Sure, here's the updated dump. Point of interest `invalidate()` that's called as a result of `onChanged` handler in the following functions: `StorageCacheItem.remove()` and `StorageCacheItem.add()`.

I'm not sure if that's a feedback loop - I have quite a few quantum storage units and it seems to invalidate the cache if the qty of the items changed in a storage unit. So inserting/removing item from the external storage invalidates the cache and I have quite a few items in my network.

[5.zip](https://github.com/raoulvdberge/refinedstorage/files/2199621/5.zip)

**Comment by raoulvdberge** [comment]
You are drawing the wrong conclusions here, please stop assuming things when you haven't properly read the code. No, it doesn't invalidate the entire cache if an external source changes:

https://github.com/raoulvdberge/refinedstorage/blob/mc1.12/src/main/java/com/raoulvdberge/refinedstorage/apiimpl/storage/externalstorage/StorageExternalItem.java#L67-L102

It only updates the changes, but never invalidates entirely.

Also, your profiling report doesn't mention `invalidate()`, so I'm not sure what you are talking about.

**Comment by mrjoes** [comment]
Well, I just suggested it might be a problem.

Are we talking about the same sampling report?

Here's one of the traces in a screenshot form:
![image](https://user-images.githubusercontent.com/179880/42789799-41fedaa0-8935-11e8-8b22-dea6ad5e08c2.png)

You can see that the RF takes most of the server tick time. Individual Importer, Exporter and Interface updates take most of it and if I dig into the call tree - it's always spent in `ItemHandlerInterface.invalidate()` as a result of the `ItemHandlerInterface.onChanged()` after adding or removing the item to/from the StorageCacheItem. And `invalidate()` spends most of the time in `java.util.AbstractCollection.toArray()`.
