### ISSUE TITLE
Duplication Glitch from Redstone Control and Drive Disconnecting

### ISSUE THREAD

**Issue by NinjaKap** [raoulvdberge/refinedstorage#1881]
#### Issue description:
Odd Duplication Glitch, with different functions on Server/SP
#### What happens:
Duplicates items. If you disconnect drives (untested with other storage options) and use redstone control on the controller, it creates these "ghost items" which you can take.
#### What you expected to happen:
Not duplicate items. When you disconnect drives, it shouldn't show the items.
#### Steps to reproduce:
On Server:
1. Disable Controller using Redstone Control
2. Disconnect Drives from System
3. Re-Enable Controller
4. Take items and done! System re-syncs if you re-connect cables or place/break controller. (Possibly also syncs if you do anything to the system itself, untested)

On SP:
1. Disable Controller using Redstone Control.
2. Disconnect Drives from System
3. Take Storage Disks out from Drives
4. Re-Enable Controller
5. Take items!
6. Place Disks back in Drives and re-connect Drives.

In SP, if you don't take the storage disks out from the drives, the ghost items still appear, but taking them out still takes them out of the drives. (Even though the drives are NOT connected to the system). Taking Disks out from Drives still allows you to duplicate items.
...

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12.2
- Forge: 14.23.4.2732
- Refined Storage: 1.5.34

#### Does this issue occur on a server? [yes/no]
- Yes, it occurs on Servers and Single Player, with slight differences.

**Comment by raoulvdberge** [comment]
Fixed, thx for reporting!
