### ISSUE TITLE
Ore Dictionary gets confused

### ISSUE THREAD

**Issue by VukZlatkovic** [raoulvdberge/refinedstorage#1883]
#### Steps to reproduce:
1. Create a processing recipe for electrum with ore dictionary
2. Any processing recipe using silver will instead use invar wich isnt intended behaviour
3. Recipe is stuck due to there being invar processed instead of silver
...

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12 (direwolf20 modpack version 2.1.0)
- Forge: 14.23.4.2732
- Refined Storage: 1.5.34

Does this issue occur on a server? [yes/no] Dont know.

#### If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here]

**Comment by raoulvdberge** [comment]
Try it on RS 1.6

**Comment by Tahakk** [comment]
Just unlock your modpack. Go to Modpack Options and uncheck **Locked**
