### ISSUE TITLE
Item quantity quirk (1.6)

### ISSUE THREAD

**Issue by BrisingrAerowing** [raoulvdberge/refinedstorage#1885]
#### Issue description:

Grids show a minimum of 96 items, even if only one of any item is in the system.

#### What happens:

Grid shows more items than it should.

#### What you expected to happen:

Grid shows actual amount of items.

#### Steps to reproduce:
1. Put items in the system.
2....
3. Weird numbering.
...

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12.2
- Forge: 2739
- Refined Storage: 1.6

Does this issue occur on a server? [yes/no] Untested.

#### If a (crash)log is relevant for this issue, link it here:

![2018-07-20_22 20 22](https://user-images.githubusercontent.com/250409/43031233-82381558-8c6b-11e8-9b4c-f6948ae71866.png)

**Comment by BrisingrAerowing** [comment]
The ones in external storage (storage drawers) show fine. I disconnected the storage drawers and it still did this. It seems to be related to the number of disks in the system (I had 96 disks). I'll do some testing.

**Comment by raoulvdberge** [comment]
To what are you connecting an External Storage?

**Comment by raoulvdberge** [comment]
Also, give me exact reproduction steps. What do I have to do, place, etc.

**Comment by BrisingrAerowing** [comment]
Any kind of inventory can be connected.

Simply set up an RS system with some disks (> 1) and put a single item in it. Then place some kind of inventory (e.g. a chest) and attach it to the system with an External Storage. The item in the system should now show the quantity as the number of disks in the system.

**Comment by raoulvdberge** [comment]
I can't reproduce.

![x](https://drive.google.com/uc?id=10MVhScLgH6_XagO1aUW5ZA_zVIP3ugN_)

![x](https://drive.google.com/uc?id=1oTl7znzzbfspyItM4DXtqazkJL-R0iBi)

**Comment by raoulvdberge** [comment]
Are you sure your reproduction steps are correct?

**Comment by BrisingrAerowing** [comment]
Let me do some more testing.

**Comment by BrisingrAerowing** [comment]
It looks like Reborn Storage is breaking something. I'll poke them.

**Comment by BrisingrAerowing** [comment]
It only happens when that's installed. With just RS it doesn't happen.

**Comment by raoulvdberge** [comment]
@BrisingrAerowing  I just tried the exact same setup with Reborn Storage, and I can't reproduce it?

Can you, please, be more specific? This is getting frustrating.

**Comment by BrisingrAerowing** [comment]
Weird... I'll mess with it some more.

**Comment by BrisingrAerowing** [comment]
I was able to replicate this with just RS. Here's an image of my testing setup:
![2018-07-25_18 04 21](https://user-images.githubusercontent.com/250409/43230151-41e82d3a-9035-11e8-8dac-cae246d13d93.png)

The external storage needs to be added last. There are 8 64K disks in the drive.

**Comment by BrisingrAerowing** [comment]
Here's a couple more screenshots:
![2018-07-25_18 05 59](https://user-images.githubusercontent.com/250409/43230209-720140f6-9035-11e8-93fc-19d104a5bf1f.png)
![2018-07-25_18 06 02](https://user-images.githubusercontent.com/250409/43230210-722ef28a-9035-11e8-9d08-7085363951d5.png)

**Comment by BrisingrAerowing** [comment]
The item that gets 'duplicated' needs to be in the system before the external storage is added, BTW. Anything added after doesn't duplicate unless another ES is added.

**Comment by raoulvdberge** [comment]
Weird:

![x](https://drive.google.com/uc?id=1E-Uu5ND08_6yT453mkHUOMaKbR1QcEG6)

![x](https://drive.google.com/uc?id=1joj61EPrvjrsBq6bO08pBzA6lZfFW714)

![x](https://drive.google.com/uc?id=1mWDo5tCvQ-nhs5eKE6TRQ0y31146c3tD)

![x](https://drive.google.com/uc?id=1A99ZQzk0_OC2Zv61ZI0x4XwPLQ72pxBK)

My flow:

- Place Controller
- Place Disk Drive
- Place Grid
- Insert 8 64k disks into disk drive
- Insert 1 chest into the Grid
- Place chest
- Connect External Storage

**Comment by BrisingrAerowing** [comment]
Still happens even after a complete recreation of that instance. Something is messed up. Might be an issue with MultiMC itself. I'll try rebuilding my entire setup.

**Comment by BrisingrAerowing** [comment]
Even a complete nuke and rebuild of my setup didn't fix it. I'm at a loss as to what could be broken.

**Comment by BrisingrAerowing** [comment]
Also, what Forge version are you using? Mine is 2739.

**Comment by raoulvdberge** [comment]
Can you reproduce this with only RS installed? No other mods.

**Comment by BrisingrAerowing** [comment]
Yup. That's the image above. Only RS is installed.

**Comment by CrossVas** [comment]
I was able to reproduce this.
It seems to be a block update visual bug.

Minecraft Setup:
Minecraft: 1.12.2
Forge: 1.12.2-14.23.4.2739
Refined Storage: refinedstorage-1.6.2-256

> https://imgur.com/a/8BqAYGo

**Comment by BrisingrAerowing** [comment]
Well, at least someone else has figured something out. This was beginning to run me up the wall. I even did a refresh of my Win10 install to see if that would work (I needed to do one anyways as I had accumulated a ton of crap since the last time I did a refresh. My system runs about 90% faster now).

**Comment by BrisingrAerowing** [comment]
I just noticed something. When this issue occurs, ALL of the disks get the same UUID. I'm guessing that's the core of this issue.

**Comment by raoulvdberge** [comment]
I still can't reproduce the issue. I'm suspecting (aka i'm almost sure) that you guys aren't running a RS vanilla instance to test this.

![x](https://drive.google.com/uc?id=1E7msD8s354T3xsNuuXnZQs-Mv-Z51dGv)

**Comment by raoulvdberge** [comment]
@CrossVas 

See my post above.

Are you running any other mods in the testing instance?

How did you obtain those disks? Did you create unique ones or duplicate them with middle click (so they end up having the same ID)

**Comment by BrisingrAerowing** [comment]
My instance contained Forge and RS. That's it.

**Comment by BrisingrAerowing** [comment]
I just noticed that disks get their IDs when crafted / put into the inventory. I was middle click dragging them in the drives to fill them, as shift middle clicking a drive does not include the disks in it. That's the cause of this issue here.
