### ISSUE TITLE
Pack Comparer Not Found

### ISSUE THREAD

**Issue by LordHarkon** [raoulvdberge/refinedstorage#1889]
#### Issue description:
When I accessing https://refinedstorage.raoulvdberge.com/packcomparer.php it says 404 Not Found
#### What happens:
The webpage is not found
#### What you expected to happen:
For the webpage to appear and let me compare modpacks
#### Steps to reproduce:
1. Enter https://refinedstorage.raoulvdberge.com/packcomparer.php
2. Look at the webpage

#### Version (make sure you are on the latest version before reporting):

- Google Chrome: v67.0.3396.99

**Comment by raoulvdberge** [comment]
Works again!
