### ISSUE TITLE
[1.10.2] Crafting fails on multi step processing recipes...

### ISSUE THREAD

**Issue by Kazzamkablam** [raoulvdberge/refinedstorage#189]
For example trying to make glass via cobblestone->gravel (ender io sag mill)->sand (ender io sag mill) -> glass (ender io alloy smelter) recipe gets stuck midway and refuses to complete, if you order more than few.

Refined storage 0.8.10
Forge 18.0.2010

**Comment by raoulvdberge** [comment]
and only requesting one works?

**Comment by raoulvdberge** [comment]
also does it occur 100% of the time or only sometimes?

**Comment by JohnC94** [comment]
I'm encountering this problem as well. It's weird though, it's only happening on 1 thing so far. Whenever I tell my system to craft advanced processors, it will hang, but basic/improved will craft just fine. All the recipes are in crafters touching chests with EIO conduits routing the items to solderers, only thing different is the recipes.

**Comment by JohnC94** [comment]
Perhaps it's an issue with crafting jobs, I have an exporter with a crafting upgrade exporting the printed silicon for the solderers, if I remove the crafting upgrade, the issue seems to go away.

**Comment by raoulvdberge** [comment]
Are you having a similar setup, @Kazzamkablam ?

**Comment by Kazzamkablam** [comment]
I'm using crafters to directly request stuff, it works if i request only one item but if use multiples it craps itself and doesn't do anything.

It happens pretty much every time theres more than few items to request.

**Comment by varukasalt** [comment]
I have several high level items that either refuse to start crafting at all, say they start and finish, but nothing actually happens, or stall out half way through asking for an item it thinks it doesn't have or can't craft but actually has or can craft.

**Comment by BootyToast** [comment]
We had the same problem on our server. With a crafting upgrade in an exporter requesting cake, you've got to request one in the grid first to kickstart the exporter's autocrafting itself.

**Comment by JohnC94** [comment]
> We had the same problem on our server. With a crafting upgrade in an exporter requesting cake, you've got to request one in the grid first to kickstart the exporter's autocrafting itself.

In my situation, the exporter was working with no issues, it was the jobs I started that would halt. I'd tell the system to craft 10 advanced processors, when the crafting jobs for the exporter started popping up, the job for the advanced processors would halt.

**Comment by BootyToast** [comment]
Hopefully this makes sense and I'm not sure if this is an intended feature, but it seems it will only craft one item at a time even when requesting crafting tasks from patterns in two different crafters. If your crafting operations are getting hung up, this may be the first thing you should take into account.
