### ISSUE TITLE
Mekanism Autocrafting

### ISSUE THREAD

**Issue by PessimisticBastard** [raoulvdberge/refinedstorage#1891]
#### Issue description:

Autocrafting system no longer recognizes various Mekanism machines as the correct crafting item.
#### What happens:

Say I want to craft an elite level machine (ex: elite energized smelter). The RS system doesn't recognize previous tiers as the correct component, and will not craft. This was not an issue in previous RS versions.

#### What you expected to happen:

I expected the machine to craft without issues.

#### Steps to reproduce:
1. Tell crafter to create basic/advanced/elite level Mekanism machine
2. System will say previous tier item does not exist.

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12.2
- Forge: 14.23.4.2739
- Refined Storage: 1.6

Does this issue occur on a server? [yes/no]

No.

#### If a (crash)log is relevant for this issue, link it here:

N/A

**Comment by raoulvdberge** [comment]
That is because the mekanism recipes are nbt sensitive. RS can't account for that.
