### ISSUE TITLE
RS 1.6 Crashes/Incompatible With FTB Revelations Pack

### ISSUE THREAD

**Issue by kylerh15** [raoulvdberge/refinedstorage#1893]
#### Issue description: 
I Updated RS And RS Addons In FTB Revelations Pack And Game Crashes On Launch Ive Tried Removing Mods But Cant Seem To Figure Out Whats Going On 1.5 Worked Fine.
#### What happens: 
Game Crashes On Startup

#### What you expected to happen: 
Game To Run With The New RS Update

#### Steps to reproduce:
1. Download FTB Revelations
2. Replace RS 1.5.34 And RS Addons 0.3 With Updated RS 1.6 And RS Addons 0.4
3. Start Game
...

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12.2
- Forge: forge-1.12.2-14.23.4.2729-installer-win
- Refined Storage: 1.6

Does this issue occur on a server? Yes

#### If a (crash)log is relevant for this issue, link it here:

https://pastebin.com/LzSK83LF

**Comment by raoulvdberge** [comment]
Update reborn storage

**Comment by kylerh15** [comment]
Thanks forgot reborn storage was a addon works now
