### ISSUE TITLE
Crash after update

### ISSUE THREAD

**Issue by kellixon** [raoulvdberge/refinedstorage#1894]
Crash after update.
Minecraft: 1.12.2
Forge: 14.23.4.2739
Versions (new) - **crash**:
Refined Storage 1.6+Refined Storage Addons 0.4
Versions (old) - **very good work**:
Refined Storage 1.5.34+Refined Storage Addons 0.3
Crash report - https://gist.github.com/kellixon/c0388ca5cd0bc04ddf6602a59fa9ce7f

**Comment by raoulvdberge** [comment]
Problem in storage tech
