### ISSUE TITLE
crash with RealWorld

### ISSUE THREAD

**Issue by Hypsellis** [raoulvdberge/refinedstorage#1897]
#### Issue description:
Refined Storage seems to try to cast realworld.block.BlockRWSlabDouble into net.minecraft.block.BlockSlab for using them as covers, which causes the game to crash.

#### Version (make sure you are on the latest version before reporting):
- Minecraft: 1.12.2
- Forge: 14.23.4.2739
- Refined Storage: 1.6

Does this issue occur on a server? 
Yes

#### If a (crash)log is relevant for this issue, link it here:
https://pastebin.com/CT67fq5r

**Comment by raoulvdberge** [comment]
RealWorld issue. RS doesn't cast, but RealWorld casts, something which the stacktrace shows.
