### ISSUE TITLE
[1.6] Interface no longer pulls items when empty output filter

### ISSUE THREAD

**Issue by ViRb3** [raoulvdberge/refinedstorage#1901]
#### Issue description:
Prior to 1.6, I used to have one interface with an empty output filter. When I connected EnderIO Item Conduits or XNet cables, I would have the cables specify what item they want to pull, and the Interface would magically pull those items from the connected storage.

#### What happens:
Nothing. I need to exclusively put the items I want to be pulled in the Interface's output filter.

#### What you expected to happen:
The items the cables request to be pulled from the storage.

#### Version (make sure you are on the latest version before reporting):
- Minecraft: 1.12.2
- Forge: 14.23.4.2705
- Refined Storage: 1.6

Does this issue occur on a server? [yes/no]
yes

**Comment by raoulvdberge** [comment]
that feature has been removed for performance reasons

**Comment by ViRb3** [comment]
Is there any way to work around this limitation? It makes item automation quite a tedious task.

**Comment by calloatti** [comment]
This was a great feature to have, and I used it extensively and never had performance issues in my potato computer.

Could you please evaluate about adding it again? Maybe make it a config option disabled by default?

No all of us are such purists when it comes to performance vs features.

If you are not willing to compromise, maybe there could be a way to extend the interface filter beyond nine items?

**Comment by raoulvdberge** [comment]
locked because I gave reasoning, this can't be re-added. I don't like the alternatives either.
