### ISSUE TITLE
Inconvenient placement of items in pattern grid processing matrix

### ISSUE THREAD

**Issue by Cydhra** [raoulvdberge/refinedstorage#1902]
#### What happens:
When trying to create a pattern using the "Processing" option (for external machines), right clicking with a full item stack will place the ghost copy of the full item stack instead of a single item in the matrix. 

#### What you expected to happen:
Since left clicking also places the full item stack, and right clicking with an item stack in a default inventory also just places one item in the slot, it is expected (and would be convenient) when only one item is placed instead. Especially, because clicking once into the grid takes a full item stack from the storage, so it is essentially always the case, that you are trying to create a pattern with a full stack in move.

#### Steps to reproduce:
1. Take an item stack
2. Right click in the processing matrix of the pattern grid
3. Get a full ghost stack placed instead of one item

#### Version (make sure you are on the latest version before reporting):
- Minecraft: 1.12.2
- Refined Storage: 1.6

(This is an enhancement proposal)

**Comment by raoulvdberge** [comment]
This is fixed with new functionality: now a dialog opens when using left/right click to enter an amount manually.
