### ISSUE TITLE
Really? Of all the options at your disposal on how to react that is the path you chose?

### ISSUE THREAD

**Issue by calloatti** [raoulvdberge/refinedstorage#1906]
You need to brush up on your social skills my man, that is not the way a normal person acts.

It's a hobby, you do this for fun, and we are just posting here because we like and use your mod.

We are not angry customers or the enemy, we are people like you enjoying our free time playing a game with a mod you created in your free time.

We are supposed to interact and discuss and talk about things and have fun while doing it, not act like socially inept retards that locks a topic just because.

Grow the fuck up and learn to enjoy life. Try getting laid, for starters.

**Comment by raoulvdberge** [comment]
Relevant issue: #1901
