### ISSUE TITLE
Crafting: Start Button disables and then the "Crafting Initializer GUI" stays put

### ISSUE THREAD

**Issue by Knito58** [raoulvdberge/refinedstorage#1908]
#### When initializing a crafting job the Start Button turns into disabled state. 
The GUI with the amount selectors stays open. Pressing Cancel works like expected. The job is not started.

#### Happens probably because there are not enough crafting items in the system.
But you never get a message about that when the starting GUI hangs.

#### What I expected to happen: 
The pre-crafting GUI opens and shows me what items / blocks are missing. (Or in the best of worlds, I see what is needed and start the job and it works)

I wanted to craft 54 heat conducters for a 5x5x5 Reborn Storage Multiblock structure. Reborn Storage is not connected to the system yet and not working. The GUI freeze occured also when I wanted to craft more than 10 blocks. I slowly tested with small amounts and saw it all would work well for 5 blocks. I crafted one. Then the GUI froze for 5 blocks. For 4 blocks it would have started. I crafted another one. Now it froze for 4 blocks. There seems to be a problem with showing the  missing items. Ok I wanted to start a crafting process having not enough resources by far. But the system should tell me about that and not be buffy. Suggestion: Let the system insult people like me who obviously don't have enough resources to do 10% of the job. :)

#### Steps to reproduce:
1. Set up new RS system
2. Try to craft something were recipes or items are missing
3. But: This does not happen all the time. Crafting the Reborn Storage Crafting Frame with missing items just worked fine. The second GUI told me what was missing. In the 4th attempt I successfully started a crafting job for 44 crafting frame blocks.
...

#### Version 

- Minecraft: 1.12.2
- Forge: 14.23.4.2739
- Refined Storage: 1.6

Does this issue occur on a server? NO, SSP

I like the new recipes without solderers. Now the importer is clearly for RS-foreign systems. I never understood, why the solderer as part of the RS-system needed an importer.

**Comment by raoulvdberge** [comment]
Are there any logs?

**Comment by Knito58** [comment]
Where to look for them? The logs folder seems to have nothing from RS.

**Comment by Knito58** [comment]
Restarted. Now "cut silicon" is not being able to be produced and "hangs the GUI". Every "cut" recipe hangs. Iron bars (vanilla) and feral flare (torchmaster) can be produced as expected.

**Comment by raoulvdberge** [comment]
I do need logs to solve the issue. They are in your Minecraft directory of your instance. If you can't find them, you can also look in the console output of the launcher you're using.

**Comment by Knito58** [comment]
Trying to paste some log info from the vanilla launcher.

22:42:54 | game |   | info | [20:42:54] [RS crafting preview calculation/ERROR] [FML]: Exception caught during firing event net.minecraftforge.event.entity.player.PlayerDestroyItemEvent@bf43d69:
-- | -- | -- | -- | --
22:42:54 | game |   | info | java.lang.NullPointerException: null
22:42:54 | game |   | info | at mrriegel.playerstorage.ExInventory.destroy(ExInventory.java:696) ~[ExInventory.class:?]
22:42:54 | game |   | info | at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_296_ExInventory_destroy_PlayerDestroyItemEvent.invoke(.dynamic) ~[?:?]
22:42:54 | game |   | info | at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
22:42:54 | game |   | info | at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182) [EventBus.class:?]
22:42:54 | game |   | info | at net.minecraftforge.event.ForgeEventFactory.onPlayerDestroyItem(ForgeEventFactory.java:179) [ForgeEventFactory.class:?]
22:42:54 | game |   | info | at net.minecraftforge.common.ForgeHooks.getContainerItem(ForgeHooks.java:1016) [ForgeHooks.class:?]
22:42:54 | game |   | info | at net.minecraftforge.common.ForgeHooks.defaultRecipeGetRemainingItems(ForgeHooks.java:994) [ForgeHooks.class:?]
22:42:54 | game |   | info | at net.minecraft.item.crafting.IRecipe.func_179532_b(IRecipe.java:20) [akt.class:?]
22:42:54 | game |   | info | at com.raoulvdberge.refinedstorage.apiimpl.autocrafting.CraftingPattern.getByproducts(CraftingPattern.java:209) [CraftingPattern.class:?]
22:42:54 | game |   | info | at com.raoulvdberge.refinedstorage.apiimpl.autocrafting.task.CraftingTask.calculateInternal(CraftingTask.java:315) [CraftingTask.class:?]
22:42:54 | game |   | info | at com.raoulvdberge.refinedstorage.apiimpl.autocrafting.task.CraftingTask.calculate(CraftingTask.java:165) [CraftingTask.class:?]
22:42:54 | game |   | info | at com.raoulvdberge.refinedstorage.apiimpl.network.grid.handler.ItemGridHandler.lambda$onCraftingPreviewRequested$0(ItemGridHandler.java:196) [ItemGridHandler.class:?]
22:42:54 | game |   | info | at com.raoulvdberge.refinedstorage.apiimpl.network.grid.handler.ItemGridHandler$$Lambda$2182/919851075.run(Unknown Source) [ItemGridHandler.class:?]
22:42:54 | game |   | info | at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51]
22:42:54 | game |   | info | [20:42:54] [RS crafting preview calculation/ERROR] [FML]: Index: 1 Listeners:
22:42:54 | game |   | info | [20:42:54] [RS crafting preview calculation/ERROR] [FML]: 0: NORMAL
22:42:54 | game |   | info | [20:42:54] [RS crafting preview calculation/ERROR] [FML]: 1: ASM: class mrriegel.playerstorage.ExInventory destroy(Lnet/minecraftforge/event/entity/player/PlayerDestroyItemEvent;)V
22:42:54 | game |   | info | [20:42:54] [RS crafting preview calculation/ERROR] [FML]: 2: ASM: mob_grinding_utils.events.ChickenFuseEvent@1a7a2323 startChickenFuse(Lnet/minecraftforge/event/entity/living/LivingEvent;)V
22:42:54 | game |   | info | Exception in thread "RS crafting preview calculation" [20:42:54] [RS crafting preview calculation/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: java.lang.NullPointerException
22:42:54 | game |   | info | [20:42:54] [RS crafting preview calculation/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at mrriegel.playerstorage.ExInventory.destroy(ExInventory.java:696)
22:42:54 | game |   | info | [20:42:54] [RS crafting preview calculation/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_296_ExInventory_destroy_PlayerDestroyItemEvent.invoke(.dynamic)
22:42:54 | game |   | info | [20:42:54] [RS crafting preview calculation/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
22:42:54 | game |   | info | [20:42:54] [RS crafting preview calculation/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
22:42:54 | game |   | info | [20:42:54] [RS crafting preview calculation/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraftforge.event.ForgeEventFactory.onPlayerDestroyItem(ForgeEventFactory.java:179)
22:42:54 | game |   | info | [20:42:54] [RS crafting preview calculation/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraftforge.common.ForgeHooks.getContainerItem(ForgeHooks.java:1016)
22:42:54 | game |   | info | [20:42:54] [RS crafting preview calculation/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraftforge.common.ForgeHooks.defaultRecipeGetRemainingItems(ForgeHooks.java:994)
22:42:54 | game |   | info | [20:42:54] [RS crafting preview calculation/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraft.item.crafting.IRecipe.func_179532_b(IRecipe.java:20)
22:42:54 | game |   | info | [20:42:54] [RS crafting preview calculation/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at com.raoulvdberge.refinedstorage.apiimpl.autocrafting.CraftingPattern.getByproducts(CraftingPattern.java:209)
22:42:54 | game |   | info | [20:42:54] [RS crafting preview calculation/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at com.raoulvdberge.refinedstorage.apiimpl.autocrafting.task.CraftingTask.calculateInternal(CraftingTask.java:315)
22:42:54 | game |   | info | [20:42:54] [RS crafting preview calculation/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at com.raoulvdberge.refinedstorage.apiimpl.autocrafting.task.CraftingTask.calculate(CraftingTask.java:165)
22:42:54 | game |   | info | [20:42:54] [RS crafting preview calculation/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at com.raoulvdberge.refinedstorage.apiimpl.network.grid.handler.ItemGridHandler.lambda$onCraftingPreviewRequested$0(ItemGridHandler.java:196)
22:42:54 | game |   | info | [20:42:54] [RS crafting preview calculation/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at com.raoulvdberge.refinedstorage.apiimpl.network.grid.handler.ItemGridHandler$$Lambda$2182/919851075.run(Unknown Source)
22:42:54 | game |   | info | [20:42:54] [RS crafting preview calculation/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.lang.Thread.run(Thread.java:745)

**Comment by raoulvdberge** [comment]
That's enough for me to see what's going on!

The issue appears to happen in mrriegel.playerstorage.ExInventory. I don't know which mod that is, but you might want to report to them.
