### ISSUE TITLE
Too many Covers

### ISSUE THREAD

**Issue by Fortist** [raoulvdberge/refinedstorage#1909]
After blacklisting both sets of covers in JEI, I found that a few blocks do not work for covers (Flat colored blocks), so I suggest there be a separate config for blacklisting blocks that cannot be covers.

**Comment by raoulvdberge** [comment]
The next version will have a config to disable covers in JEI.

Unfortunately, from a code standpoint the Flat Colored Blocks ARE compatible. They just render wrongly, and I can't detect that.
