### ISSUE TITLE
Feature Request - Interface Needs a Match / Ignore Metadata Option

### ISSUE THREAD

**Issue by ozhound** [raoulvdberge/refinedstorage#191]
This is because all of your processors have the same name with the meta data being different. i.e If you set a printed basic processor in the export grid it treats all processors as the same. I would assume this would be common to all items sharing the same name but different metadata.

**Comment by raoulvdberge** [comment]
ummm, there is literally a side button in that GUI called "compare NBT" and "compare damage" (damage being metadata)

**Comment by ozhound** [comment]
Compare NBT Doesn't work for the interface. it does work for the export buses though. I have a video of it.

Perhaps i should have listed this as a bug reqeust

**Comment by raoulvdberge** [comment]
You don't need to match NBT, but match damage. In the video you weren't matching on damage, but on NBT. And on the exporter you were matching on damage, but not NBT (thats why it was working)
