### ISSUE TITLE
Unable to autocraft IC2 Cables when requesting larger machines. (oreDictionary issue)

### ISSUE THREAD

**Issue by Tirco** [raoulvdberge/refinedstorage#1912]
#### Issue description / What happens / Expections:
When requesting a machine to be autocrafted from IC2, the machine will tell you it doesn't have access to the cables from IC2, even tho the machine should be able to automatically craft them.

#### Relevant screenshots:
Request of larger machine: https://prnt.sc/kaysq2
Pattern in crafter: https://prnt.sc/kayth3
Item shows up as craftable in system: https://prnt.sc/kaytmu
Can craft Insulated Copper Cable: https://prnt.sc/kayttz
Can craft copper Cable: https://prnt.sc/kaytyo

#### Steps to reproduce:
1. Add all patterns to automate the cration of a larger machine from IC2.
2. Request for the machine to autocraft the item.
3. The machine will tell you that it doesn't have the cables. (even tho in theory it should be able to autocraft them)

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12.2
- Forge: 14.23.4.2739
- Refined Storage: 1.6
- Industrial Craft 2: 2.8.93-ex112

#### Does this issue occur on a server? [yes/no]^
Yes.

#### If a (crash)log is relevant for this issue, link it here:
No crash.

#### Edit:
It appears that even if i have 9 copper cables in the system, the autocrafter doesn't see them as the correct cables. I've attempted to have the pattern for the larger machines subparts without oreDictionary and then it seems to work.

Cables in system: http://prntscr.com/kaz13g
Machine still needs cables: http://prntscr.com/kaz1b4

**Comment by raoulvdberge** [comment]
#1954
