### ISSUE TITLE
Crashes server/game when connecting reinforced drum containing fluids to fluid interface

### ISSUE THREAD

**Issue by kibmcz** [raoulvdberge/refinedstorage#1913]
#### Issue description:

Crash when connecting a reinforced drum to a fluid interface via both enderio fluid conduit and extra utilities transfer pip with fluid transfer node. Happened first on server then on client with same world.

#### What happens:
Crashes server/game when connecting reinforced drum containing fluids (lava in my case) to fluid interface (via either ender:io fluid conduit or extra utilities transfer pipe).

#### What you expected to happen:
Fluids to transfer xD

#### Steps to reproduce: Not 100% sure as it seems to effect that map so i'm hoping you can figure out what's gone odd in the log.

1.
2.
3.
...

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12.2
- Forge: 14.23.4.2705 (recommended version)
- Refined Storage: 1.6

Does this issue occur on a server? yes

#### If a (crash)log is relevant for this issue, link it here:

https://paste.dimdev.org/orulogezet.mccrash

**Comment by kibmcz** [comment]
Well due to the crash i can't show it connected but was able to recreate the setup (and the crash) in client due to using AromaBackup on server.

![2018-07-25_15 40 15](https://user-images.githubusercontent.com/857986/43229239-624e74f8-9021-11e8-83b3-72b79c7f3abb.png)

**Comment by raoulvdberge** [comment]
It appears your fluid storage disk is disguising itself as an item storage disk. Very weird!

**Comment by kibmcz** [comment]
Did further testing in a clean world.. possibly related to the custom disks from storage tech (https://minecraft.curseforge.com/projects/storage-tech) due to how using the disk api it seems to show as a rs issue.  Will contact them and get back to you.

**Comment by raoulvdberge** [comment]
That is most likely the issue. Tell them that they are returning the wrong value in `IStorageDiskProvider#getType`.

I can't seem to find their (up-to-date) source code on their Bitbucket repo, so I can't confirm unfortunately.

**Comment by kibmcz** [comment]
The issue is fixed. 

Thanks for providing pointer for getting it fixed :).
