### ISSUE TITLE
[1.6, 1.12.2] Crash while startup

### ISSUE THREAD

**Issue by TheSnowyChickens** [raoulvdberge/refinedstorage#1915]
#### Issue description:
Crash on startup.

In the crash log, you can see all my mods and more.
With 1.5.34 it worked, then I updated to 1.6 and RIP. (maybe its not a RS issue, but I cant analyze good the crash logs^^)
![grafik](https://user-images.githubusercontent.com/29357962/43297451-babb3992-9151-11e8-986b-4c71bc619873.png)

#### What happens:
MC crashed while the game is starting.

#### What you expected to happen:
No crash. :D 

#### Steps to reproduce:
1. Install RS 1.6 (in my custom Modpack)
2. Start MC.
3. After a while it crash.

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12.2
- Forge: 2739
- Refined Storage: 1.6

Does this issue occur on a server? [yes/no]
Client/Singleplayer

#### If a (crash)log is relevant for this issue, link it here:
https://paste.dimdev.org/ojimodibom.mccrash

**Comment by raoulvdberge** [comment]
Update RS add-ons
