### ISSUE TITLE
BUG: Interface Compare NBT Doesnt work

### ISSUE THREAD

**Issue by ozhound** [raoulvdberge/refinedstorage#192]
Putting items (i.e Silicon from EnderIO) into the interface export pulls any item matching the name (i.e Conduit Binder) when the actual item requested is not present regardless if Compare NBT is on or off

Refer to this video for an example

https://youtu.be/tpgGPKSx81o

**Comment by raoulvdberge** [comment]
You need to compare on damage, like I said in the other issue!
