### ISSUE TITLE
Feature Request: Autocrafting Blocking

### ISSUE THREAD

**Issue by dannydjdk** [raoulvdberge/refinedstorage#1921]
It would be most useful to have a feature which would allow only one item in a crafting recipe to be crafted at a time. This would greatly simplify automation of in-world crafting and complex crafting recipes involving multiple machines.

When this feature was first added to RS, there was much rejoicing among my friends an me. The removal of this feature is preventing me from upgrading Refined Storage in my modpacks, because it will break too much existing automation.

Please?

**Comment by raoulvdberge** [comment]
This feature has been removed for a reason.
