### ISSUE TITLE
Question to 1.6.1 Storage Blocks: Void button missing

### ISSUE THREAD

**Issue by Knito58** [raoulvdberge/refinedstorage#1925]
#### Steps to reproduce:
1. Craft a storage block
2. try to configure it
3.
...

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12.2
- Forge:  14.23.4.2738
- Refined Storage: 1.6.1

Does this issue occur on a server? No

Is there a new strategy to protect the system from overload which I didn't see? Or will the button come back?

**Comment by raoulvdberge** [comment]
Has been removed

**Comment by Knito58** [comment]
Is there anything else that mimics the old behaviour? Do I have to do something to achieve the voiding of items?

**Comment by raoulvdberge** [comment]
It's no longer possible to do that with RS alone. You could connect an external storage to an inventory that supports voiding though.

**Comment by Knito58** [comment]
Thank you.
