### ISSUE TITLE
Feature Request:Bucket Filler Block

### ISSUE THREAD

**Issue by Trinsdar** [raoulvdberge/refinedstorage#1926]
#### Issue description:
Now that crafting with liquids the old way has been removed, would you be able to add a block that basically fills buckets when a recipe is put inside it? It would be useful as you wouldn't have to add other mods to fill buckets for recipes, like in a pack where the only tech mods are immersive engineering and refined storage.

**Comment by raoulvdberge** [comment]
No sorry

**Comment by rrbrussell** [comment]
You now have a hard requirement on one of the Thermal Expansion Fluid Transposer, the IC2 Canner, the Forestry Bottler, or the Ender IO Tanks without a filler block from this mod.
