### ISSUE TITLE
Problem with autocrafting with cutting tool.

### ISSUE THREAD

**Issue by MindCaged** [raoulvdberge/refinedstorage#1927]
#### Issue description:
The system gets stuck when autocrafting processors.

#### What happens:
When I try to autocraft processors with the cutting tool, it works only until it reaches 0 durability and then gets stuck. It doesn't craft a new one, it doesn't destroy the used up tool, it just locks up the crafting process. 

#### What you expected to happen:
The cutting tool should destroy itself when it reaches 0 durability so the system can make a new one, or it should have 1 more use at 0 at which point it destroys itself.

#### Steps to reproduce:
1. Add a recipe for the cutting tool.
2. Add recipes for the cut processors to the rs system.
3. Try to autocraft more than 49 cut processors.
...

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12.2
- Forge: 14.23.4.2745
- Refined Storage: 1.6.2

Does this issue occur on a server? [yes/no]
Not tested

#### If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here]

*** Update:

I think I've tracked down the problem, for some reason there's a conflict with playerstorage, though I'm not sure why as I'm not using its crafting grid to do the crafting.

https://paste.dimdev.org/ubecuvorec.mccrash

**Comment by raoulvdberge** [comment]
This is not an rs bug. Please report it to the other mod :)

**Comment by joshuasuperboy** [comment]
just make it auto craft with the cutting tool with ore dic it works fine when i do it like that
