### ISSUE TITLE
Wrenches open inventories instead of rotating blocks

### ISSUE THREAD

**Issue by angelnc1989** [raoulvdberge/refinedstorage#1929]
#### Issue description:
The wrenches I tested for rotating Crafters and Grids only rotate them when a tool is equipped in the offhand.

#### What happens:
When shift-rightclicking a Grid or Crafter with a wrench item (Immersive Engineering Engineer's Hammer and Botania Wand of the Forest were used) the GUI opens.
When another tool, for example a sword, is equipped in the offhand slot the block rotates.

#### What you expected to happen:
Instead of the GUI opening the block should rotate without a tool in the offhand slot.

#### Steps to reproduce fail state:
1. Shift-rightclick with an Engineer's Hammer on a Crafter
2. The GUI opens

#### Steps to reproduce success state:
1. Equip another tool in the offhand slot (like a sword)
2. Shift-rightclick with an Engineer's Hammer on a Crafter
3. The block rotates

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12.2
- Forge: 14.23.4.27.39
- Refined Storage: 1.6.2

Does this issue occur on a server? [yes/no]
Probably yes. Didn't test.

**Comment by raoulvdberge** [comment]
RS has a wrench again, so this issue is fixed.

https://github.com/raoulvdberge/refinedstorage/commit/70f96a4b028cf636013265f2d54073d90e4572be
