### ISSUE TITLE
0.8.10 - Can't retrieve items from grid

### ISSUE THREAD

**Issue by BootyToast** [raoulvdberge/refinedstorage#193]
Still having the same issue, but this time it's happening with the Chisels & Bits chisel.

**Comment by Meller127** [comment]
LOL

**Comment by BootyToast** [comment]
Haha, I know it must be a pain trying to figure out what the issue is. Especially if it's difficult to reproduce. If it helps any this has only ever happened to items that aren't a part of a stack.

**Comment by loveliss** [comment]
Sigh...Ender IO Vibrant and Pulsating Crystals x1 each, can't pull them out of the crafting grid system. Even when trying to craft items using the + in the NEI to automatically pull the items from your stock, it pulls everything but those. Ended my night right there. Was making a Vibrant Capacitor Bank :'(

**Comment by raoulvdberge** [comment]
@BootyToast @loveliss I have an experimental build, can you try it out and let me know if it works now? I reworked the grid update / delta system a bit to allow for sending ID's instead of real itemstacks.

Rename .zip to .jar

[refinedstorage-testing.zip](https://github.com/raoulvdberge/refinedstorage/files/370189/refinedstorage-testing.zip)

**Comment by loveliss** [comment]
I'm currently at work (I work second shift and get off at 10pm EST) I don't run the server I play on so I'm not really sure how I would test this out for you. Any suggestions?

**Comment by raoulvdberge** [comment]
Maybe ask the world download and test it locally?

**Comment by BootyToast** [comment]
I just tested it. I'm able to pull out things I wasn't able to before. Multi-step crafting tasks with crafting upgrades work. Everything looks good. I found that an exporter with a crafting upgrade will always keep an item in your drive stocked with at least one of whatever thing you had set in the exporter. Is that intended?

**Comment by raoulvdberge** [comment]
So the exporter always schedules a crafting task even when not needed?

**Comment by loveliss** [comment]
Thanks for testing that BootyToast.. Thanks raoulvdberge for taking the time to look at this :)

**Comment by raoulvdberge** [comment]
No problem. Surprising what a day of wellness can do to bugs, right?

**Comment by BootyToast** [comment]
I had an exporter hooked up to a Slice n Splice exporting shears and iron axes and shears were scheduled once more after the machine already contained one, and axes got crafted 3 more times. Maybe the higher number of crafting steps the more it will stock the system with?

**Comment by raoulvdberge** [comment]
Are you sure these errors exist since you upgraded? They might be dead crafting upgrades that were still there from the previous version.

**Comment by BootyToast** [comment]
I reattached the exporter after I had updated, but it wasn't even consistent. Just something I noticed from time to time.
