### ISSUE TITLE
inventory tweaks sorts hotbar when grids are open

### ISSUE THREAD

**Issue by SplitInfinitive** [raoulvdberge/refinedstorage#1933]
#### Steps to reproduce:
1. Open grid GUI
2. press sort hotkey
3. profit...?

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12.2
- Forge: 2705
- Refined Storage: 1.6.2 build 256

Does this issue occur on a server? [yes/no]
yes

#### If a (crash)log is relevant for this issue, link it here:
n/a

**Comment by raoulvdberge** [comment]
Might be (most likely?) a InvTweaks issue. I just add the `@InventoryContainer(showOptions = false)` annotation to the container (tell them this too when reporting to them).

If this turns out to be a RS issue, I'll reopen.
