### ISSUE TITLE
crash while importing fluids into system

### ISSUE THREAD

**Issue by JasonKillsUs** [raoulvdberge/refinedstorage#1934]
Issue description:
What happens:
crash while importing fluids from mods

What you expected to happen:
importing fluids from thermal expansion into system "Furnace+Tank above+Importer set to fluids"

Steps to reproduce:
...

Version (make sure you are on the latest version before reporting):
1.12.2
2747
1.6.2

Minecraft:
Forge:
Refined Storage:
Does this issue occur on a server? [yes/no]
no

If a (crash)log is relevant for this issue, link it here:
https://pastebin.com/bnU8zJ58

**Comment by PanSzelescik** [comment]
Crash log?

**Comment by raoulvdberge** [comment]
Please still link your crash log.

**Comment by raoulvdberge** [comment]
Was a QuantumStorage issue. I reverted your initial message, please don't get rid of that for future context reasons.

**Comment by raoulvdberge** [comment]
Don't forget to report to Quantum Storage!
