### ISSUE TITLE
Corrupting Exporter

### ISSUE THREAD

**Issue by TheBlackLuigi** [raoulvdberge/refinedstorage#1935]
#### Issue description:
Exporter corrupted the save file

#### What happens:

When adding an item to the filter of the exporter the game crashes and the save file got corrupted.

#### What you expected to happen:

The game does not crash,

#### Steps to reproduce:
1. place an exporter
2. add an item to the list
3. watch your game crash

####Note: 
This happened on 1.6 although 1.6.2 was already available.
When I removed refined storage the save file was alright. Then I updated to 1.6.2 where the exporter
apparently works well. I even removed the exporter via MC-Edit but the world is still corrupted.
#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12.2
- Forge: 1.12.2-14.23.4.2745
- Refined Storage: 1.6

Does this issue occur on a server? [yes/no]
no

[crash-2018-08-02_17.06.57-client.txt](https://github.com/raoulvdberge/refinedstorage/files/2254978/crash-2018-08-02_17.06.57-client.txt)

**Comment by raoulvdberge** [comment]
This is caused by another mod. There is a stack null when it shouldn't be.

**Comment by raoulvdberge** [comment]
(Also, this isn't a "corruption" issue. Your save file still works and has all the data. You're just stuck in a crash loop.)

**Comment by raoulvdberge** [comment]
I have a feeling there are more crashreports to this. Where is the rest?

**Comment by TheBlackLuigi** [comment]
These are all the crashes related to this issue
[crash-2018-08-02_17.06.57-client.txt](https://github.com/raoulvdberge/refinedstorage/files/2256355/crash-2018-08-02_17.06.57-client.txt)
[crash-2018-08-02_17.14.26-client.txt](https://github.com/raoulvdberge/refinedstorage/files/2256356/crash-2018-08-02_17.14.26-client.txt)
[crash-2018-08-02_17.24.09-server.txt](https://github.com/raoulvdberge/refinedstorage/files/2256357/crash-2018-08-02_17.24.09-server.txt)
[crash-2018-08-02_17.28.00-server.txt](https://github.com/raoulvdberge/refinedstorage/files/2256358/crash-2018-08-02_17.28.00-server.txt)
[crash-2018-08-02_17.53.11-server.txt](https://github.com/raoulvdberge/refinedstorage/files/2256359/crash-2018-08-02_17.53.11-server.txt)
[crash-2018-08-02_17.54.32-client.txt](https://github.com/raoulvdberge/refinedstorage/files/2256360/crash-2018-08-02_17.54.32-client.txt)
[Uploading crash-2018-08-02_20.35.45-client.txt…]()
[Uploading crash-2018-08-02_20.53.35-server.txt…]()
[Uploading crash-2018-08-02_21.16.42-server.txt…]()

**Comment by TheBlackLuigi** [comment]
The last 3 are not uploaded correctly
[crash-2018-08-02_20.35.45-client.txt](https://github.com/raoulvdberge/refinedstorage/files/2256367/crash-2018-08-02_20.35.45-client.txt)
[crash-2018-08-02_20.53.35-server.txt](https://github.com/raoulvdberge/refinedstorage/files/2256368/crash-2018-08-02_20.53.35-server.txt)
[crash-2018-08-02_21.16.42-server.txt](https://github.com/raoulvdberge/refinedstorage/files/2256369/crash-2018-08-02_21.16.42-server.txt)

**Comment by raoulvdberge** [comment]
I looked at all your crash reports. You have to update Reborn Storage.

**Comment by TheBlackLuigi** [comment]
Thank you man.
How do you see this?
With that knowledge, fixing crashes wihtout help will be much easier.

**Comment by raoulvdberge** [comment]
As a user you probably won't understand crashlogs, you'll have to learn how to program or read up on what Java exceptions mean in relation to modding.
