### ISSUE TITLE
Common registry crash

### ISSUE THREAD

**Issue by victoroos** [raoulvdberge/refinedstorage#1936]
Hi all

I just remade my modpack for 1.12
However,when adding refined storage, i get a common.registry.GameRegistry
This seems to be forge overhauling registry systems? But I just updated everything.
Forge version is latest: 1.12.2 - 14.23.4.2747
Refined storage is: 1.6.3 

vkr
vic

https://pastebin.com/EyJGPSND

**Comment by raoulvdberge** [comment]
Hi, your Forge version is older than my grandmother. You'll have to update that
