### ISSUE TITLE
Patterns randomly fail to detect resources I have available

### ISSUE THREAD

**Issue by viveleroi** [raoulvdberge/refinedstorage#1938]
#### Issue description:

Patterns (processing and normal crafting) randomly fail to detect resources I have available (at least for draconic evolution items).

#### What happens:

I've somewhat automated Draconic Evolution fusion crafting. I have a crafter with processing patterns in it, facing a chest. When I choose the product, the crafting menu randomly fails to detect available ingredients.

For example right this moment it's claiming that I don't have enough draconium ingots. It says I have 54 available, 26 missing. Yet when I look in the crafting grid, I have 830 available. Those are stored in an external storage (storage drawers). When I disconnect the external storage, the draconium disappears from my list.

Sometimes the problem goes away when I add more of the "missing" item.

So far tonight this has happened with awakened draconium blocks, awakened draconium ingots, draconium ingots, and basic crafting injectors (although these were used, so may have had energy or other metadata that made them unrecognizeable).

I can't pin down when or why this happens. I wasn't having this problem until today, but I was only doing minimal crafting with draconium. 

Here's what changed today:

- I updated to RS 1.6
- I added RebornStorage and moved patterns there
- I added new patterns/processing patterns for higher-tier draconic stuff

#### What you expected to happen:

It should fully detect the quantity I have in storage.

#### Steps to reproduce:
1. Load any recipe (possibly limited to draconic evolution) into a crafter.
2. Craft.
3. ?? It happens randomly.

#### Version (make sure you are on the latest version before reporting):

Minecraft 1.12
RebornStorage-1.12.2-3.2.1.63
RebornCore-1.12.2-3.9.3.324-universal
refinedstorage-1.6.3
forge-1.12.2-14.23.4.2705-universal (Current 1.12 recommended)
Draconic-Evolution-1.12.2-2.3.13.306-universal
BrandonsCore-1.12.2-2.4.4.173-universal

Does this issue occur on a server?
Yes

**Edit:**

I've also tried disconnecting my storage drawer system and moving my draconium into the RS system entirely, that didn't help.

I tried redefining my patterns with the "oreDict" option enable and that didn't help.

Any *new* draconium is available for crafting but eventually it all just becomes ignored.

**Comment by raoulvdberge** [comment]
This is because RS does some weird calculation to see "in use" items. This is fixed for the next version.
