### ISSUE TITLE
1.6.1-3: Filter is only an item

### ISSUE THREAD

**Issue by Knito58** [raoulvdberge/refinedstorage#1939]
#### Issue description:
The filter ist treated as a normal item, but not as filter. Put in any filter list, the filter of the block filters the item "filter", but not the content of the filter. The filter cannot be taken out of the filter list. Like all the other items it just vanishes when clicked on it. The filter has no use quite now.

#### Test:
Put baked potatoes as filter item into the filter. Put the filter into an importer (you actually put a dupe image) and drop some baked potatoes into the importer's chest. The baked potatoes are never pulled out. Drop the filter into the chest and it gets imported. Click on the filter list to get back your filter and it vanishes.

**Comment by Knito58** [comment]
Filter works in crafting / pattern grid as expected.

**Comment by raoulvdberge** [comment]
intended

**Comment by Knito58** [comment]
Why?

**Comment by bob-anthony** [comment]
This is not invalid and I can't imagine it being intended functionality unless the mod is being oversimplified. The filter was being used by many to add additional items to filter list of the exporter/importer.

**Comment by raoulvdberge** [comment]
Still invalid, since it's intended.
