### ISSUE TITLE
1.10.0 External Storage does not allow access to inventories without redstone ticks

### ISSUE THREAD

**Issue by wylker** [raoulvdberge/refinedstorage#194]
The block will not count the attached inventory as part of the storage network without a redstone update. This can be accomplished either by providing a redstone signal or by changing the redstone behavior in the GUI. Otherwise the RS inventory will not show new or removed items from the external inventory accesssed by the External Storage

**Comment by raoulvdberge** [comment]
To what is the external storage connected?

**Comment by wylker** [comment]
Sorry I've been doing some troubleshooting with this issue and I've updated my original post. I did test with vanilla chests and a variety of mod storage including iron chests.

**Comment by raoulvdberge** [comment]
May I ask which version you are running? Are you on the latest version?

**Comment by wylker** [comment]
Actually I'm so sorry this is on version 0.8.5, which is clearly not the latest. This pack is supposed to be bleeding edge so I didn't look for an update. If this bug has since been resolved accept my apologies.

**Comment by raoulvdberge** [comment]
This bug has since been resolved indeed
