### ISSUE TITLE
Recipe using lava bucket fails with lava fluid in storage

### ISSUE THREAD

**Issue by viveleroi** [raoulvdberge/refinedstorage#1940]
#### Issue description:

Crafting won't recognize lava fluid in place of lava buckets. That was one of the major new features with 1.6, I believe?

#### What happens:

Trying to make a Mekanism Crusher (default recipe). I added the pattern, which uses lava buckets, to the reborn storage crafting unit.

When trying to actually initiate a craft, the systems says I have no lava buckets available. However, when looking in my fluid monitor it says I have 50+ of lava.

#### What you expected to happen:

It should recognize the lava instead of an actual lava bucket.

#### Steps to reproduce:
1. Add pattern with lava bucket recipe
2. Import lava into fluid disk
3. Try crafting

#### Version (make sure you are on the latest version before reporting):

Minecraft 1.12
RebornStorage-1.12.2-3.2.1.63
RebornCore-1.12.2-3.9.3.324-universal
refinedstorage-1.6.3
forge-1.12.2-14.23.4.2705-universal (Current 1.12 recommended)

Does this issue occur on a server? Yes

**Comment by raoulvdberge** [comment]
that system has been replaced

read the wiki

thank you

**Comment by viveleroi** [comment]
My bad, thanks.

I assumed the autocrafting would recognize the liquid without a processing pattern. However, I'm still not clear because the wiki says the processing pattern needs an input of "one empty bucket, 1000 mB of the fluid of your choice". Are those meant for *one* pattern? I don't know how to set an item *and* a fluid into the same pattern.

Also, this appears to *require* a third party "bottling" machine, so I need that before this will even work, correct?

**Comment by raoulvdberge** [comment]
those are meant for one pattern

you can toggle between fluid and item mode in the pattern grid

and you will need a bottling machine indeed
