### ISSUE TITLE
Refined Storage Items on disk not showing in Grid

### ISSUE THREAD

**Issue by DarkDon** [raoulvdberge/refinedstorage#1941]
#### Issue description:
Crafting Grid, Pattern Grid and every other Grid wont show the items on the disk
#### What happens:
No item view in the Grid, Disk have content.
#### What you expected to happen:
To see the items in the Grids
#### Steps to reproduce:
Dont know how to reproduce, happened in a normal playthrough
#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12.2
- Forge: latest
- Refined Storage: latest

Does this issue occur on a server? [yes/no]
yes
#### If a (crash)log is relevant for this issue, link it here:
no crashlog
[pastebin/gist/etc link here]

**Comment by raoulvdberge** [comment]
Bad issue report.

**Comment by anmcn** [comment]
I believe I experienced the same thing with 1.6.4. Moved disks to another RS system, still did not show up in grid. I had just set up a "keep in stock" mechanism, and was about to add the crafting recipe for the item I wanted to keep in stock (vanilla torches). Was running in single player. Quitting back to menu and reloading the map did not fix the issue, but restarting completely did (whew!)
