### ISSUE TITLE
Regulator Mode for Exporter

### ISSUE THREAD

**Issue by Trellinane** [raoulvdberge/refinedstorage#1942]
#### Issue description:
The Exporter no longer has the regulator function on the bottom left of the gui.
#### What happens:
I cannot keep a certain number of items in an inventory any more.
#### What you expected to happen:
That I would be able to keep a certain number of items in an inventory as I could in previous versions.
#### Steps to reproduce:
1.Attach exporter to inventory
2.Add item(s) to exporter GUI
3.Look for regulator mode on GUI, not found
...

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12.2
- Forge:  14.23.4.2739
- Refined Storage: 1.6.3

Does this issue occur on a server? [yes/no]
Yes
#### If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here]

**Comment by CrossVas** [comment]
### 1.6
- Removed Regulator mode in the Exporter (raoulvdberge)

From 1.6 and above, this function was removed. You can use interface for your needs.
