### ISSUE TITLE
Blocking check box gone from Pattern Grid GUI

### ISSUE THREAD

**Issue by Trellinane** [raoulvdberge/refinedstorage#1943]
#### Issue description:
The check box to make add blocking to a pattern in the Pattern Grid is gone.
#### What happens:
When I try to create a new pattern and add blocking to the pattern I am unable to do so because the check box is no longer there in the Pattern Grid GUI
#### What you expected to happen:
That I would be able to add blocking to a pattern so the auto crafting does not send more items to an inventory until the previous crafting process completes.
#### Steps to reproduce:
1.Open Pattern Grid GUI
2.Add items to Pattern Grid GUI to create a crafting pattern,
3.Look for check box to make pattern a blocking pattern (Checkbox not there)
...

#### Version (make sure you are on the latest version before reporting):

- Minecraft:1.12.2
- Forge:14.23.4.2739
- Refined Storage:1.6.3

Does this issue occur on a server? [yes/no]yes

#### If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here]

**Comment by raoulvdberge** [comment]
Can you for crying out loud first read the changelogs before making an issue.

**Comment by Trellinane** [comment]
Ok, so I read the change log and it says blocking was removed.  It does not indicate why or what feature was added to replace blocking on the pattern.  What is the alternative?  This was a really important feature for certain crafting functions like autocrafting runes from Botania.  Without this feature it is easy for crafting ingredients to get mixed between different recipes.  Please advise.  Thank you.

**Comment by OfficialStamper** [comment]
@raoulvdberge 

I also use the 'blocking' functionality for the following:
- Botania Runic Altar
- Botania Terrestrial Conglomeration Plate
- Draconic Evolution Fusion Crafting

Can you please indicate if the 'blocking' feature is to be re-introduced, or if there is an alternate workaround?

Thanks in advance
