### ISSUE TITLE
Controller  occupying too much server tickrate

### ISSUE THREAD

**Issue by andb-1** [raoulvdberge/refinedstorage#1945]
#### Issue description:

The controller is occupying too many tickrate from server, you can see in the timings [here](https://timings.aikar.co/?id=ce6e8a3e61494acb8d03efdc3a0823b3)

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12.2
- Forge: 1.12.2 - 14.23.4.2705
- Sponge: 1.12.2-2705-7.1.0-BETA-3361
- Refined Storage: 1.6.3

Does this issue occur on a server? [yes/no]

Yes

**Comment by raoulvdberge** [comment]
https://refinedstorage.raoulvdberge.com/wiki/profiling

**Comment by andb-1** [comment]
[sampler-snapshot.zip](https://github.com/raoulvdberge/refinedstorage/files/2279079/sampler-snapshot.zip)

**Comment by raoulvdberge** [comment]
The nps report shows that the Controller doesn't take up that much:

![x](https://drive.google.com/uc?id=1YUhcGjg0wvaVZUbKJFGinssES8UGAJOD)

I'm guessing the profiling snapshot you linked earlier isn't that accurate.
