### ISSUE TITLE
auto craft stop working with fluid stored in the disk

### ISSUE THREAD

**Issue by Mikeyzy** [raoulvdberge/refinedstorage#1946]
#### Issue description:
auto craft stop working with fluid stored in the disk

#### What happens:
you have to manually bucket the fluid out to auto-craft item you want.

#### What you expected to happen:
before I update today (1.5.x), it does not require any manual operation when the fluid is in the storage.
after the update(1.6.3), it stopped working.
there are plenty of empty buckets in the storage.

#### Steps to reproduce:
nothing much to say here, just do any auto crafting with fluid involved will show this problem
![2018-08-08_15 13 12](https://user-images.githubusercontent.com/29261153/43859146-dbbb188a-9b1d-11e8-80a9-8eeafd8bd062.png)

#### Version (make sure you are on the latest version before reporting):

- Minecraft:1.12.2
- Forge:1.12.2-14.32.4.2733
- Refined Storage:1.6.3

Does this issue occur on a server?
single player

#### If a (crash)log is relevant for this issue, link it here:
no crash
[pastebin/gist/etc link here]

**Comment by raoulvdberge** [comment]
read the changelog and wiki

**Comment by Mikeyzy** [comment]
what about the recipes that require a bucket of fluid in a crafting grid? I think the new native fluid insert has nothing to do with crafting table recipe (e.g. immersive engineering treated wood and more). this makes auto craft those recipes way more complicated than before.

**Comment by raoulvdberge** [comment]
https://refinedstorage.raoulvdberge.com/wiki/autocrafting-with-filled-buckets

**Comment by Mikeyzy** [comment]
yeah, that is what I have currently set up. but still, the old mechanic is still preferred since it does not require any extra modules which reduced craft time(and lag). anyways, I guess it's a trade-off for other new features.

**Comment by raoulvdberge** [comment]
so this was a feature request hidden as a bug report?

**Comment by Mikeyzy** [comment]
if we could have both the old bucket and the new mechanic, that would be great. I'm pretty sure that I'm not the only one want the old bucket feature back. 
I didn't see the changelog on the curse forge so I thought it was bugged or something.
