### ISSUE TITLE
Feature Request: Give options for truncating numeric amounts after 999, 9999, or 99999.

### ISSUE THREAD

**Issue by ArmageddonX430** [raoulvdberge/refinedstorage#1947]
#### Issue description:

You open your grid and see objects totaling 600, 900, and 1.2k.

#### What happens:

My OCD gets triggered and I throw away anything whose quantity is greater than 999.  I like exact numbers.  O_o

#### What you expected to happen:

An option in the config to make it so the number isn't truncated until 10k, or maybe even 100k.  Four digits should easily fit and would be a huge boon.  Five would be amazing, but might be a bit sqwoahsh'd.  Obviously you don't have to implement this change, and I'll continue loving you and this mod forever and ever, but maybe I'll love it just a teensy bit more.  ^_^

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12.2
- Refined Storage: 1.5.34

P.S.: It is also keenly possible I am an idiot and there is already a config option for this and my stupid posterior is too dumb to find it.

**Comment by raoulvdberge** [comment]
I would say treat the OCD
