### ISSUE TITLE
Crash on startup due to Refined Storage

### ISSUE THREAD

**Issue by Sirzuki** [raoulvdberge/refinedstorage#1948]
#### Issue description: Game crash when opening minecraft. Is there some way for me to run minecraft with Refined Storage; I was thinking maybe forge update but I don't want to do that unless it fixes the problem. Have a look at the crash log idk if that helps but it shows that Refined Storage is the root of the problem. It runs fine withour refined storage but I really want the mod ): . Any fixes?
--PC STATS--
64bit windows 10
ryzen 3 1200
gtx 1060 3GB
8GB DDR4 RAM 2400mhz

(idk if that helps)

#### Steps to reproduce:
1. Have Refined Storage in mods folder
2. Run Minecraft

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12.2
- Forge: -14.23.3.2678
- Refined Storage: 1.6.3 (but have tried with older versions)

Does this issue occur on a server? [yes/no] N/A

#### If a (crash)log is relevant for this issue, link it here: [https://pastebin.com/7UfcQkcc]

Thanks!

**Comment by raoulvdberge** [comment]
update forge

**Comment by Sirzuki** [comment]
OMG it worked thank you so much!
