### ISSUE TITLE
Network transmitter with Galacticraft/Extra Planets doesn't work

### ISSUE THREAD

**Issue by luxxboy** [raoulvdberge/refinedstorage#1952]
#### What happens: 
When I place Network transmitter in my base w/ dimensional upgrade, Network Transmitter doesn't light up on my space station . Both Chunks are loaded, lots of other transmitter for RF Dim and others on the same chunks. Tried to break blocks and place it again. 

#### What you expected to happen:
 I expected to have my stuff on spatial station :)

#### Steps to reproduce:
1. Place Receiver in spatial base
2. Place Network Transmitter in my main base, with Network card and Interdimensional upgrade 
3. Nothing happens :'(
...

#### Version (make sure you are on the latest version before reporting):

FTB Revelation modpack based 

- Minecraft: 1.12.2
- Forge: 14.23.4.2705
- Refined Storage: 1.5.34 

Does this issue occur on a server? [yes/no] Yes

**Comment by luxxboy** [comment]
Ok, Weird issues about chunk loading, after unload, reload chunk works very well.

Sorry !

**Comment by raoulvdberge** [comment]
No problem
