### ISSUE TITLE
Pattern Grid can only accept 1Bucket of Fluid per slot

### ISSUE THREAD

**Issue by Darkere** [raoulvdberge/refinedstorage#1953]
#### Issue description:
When making a Fluid auto crafting pattern trying to insert more than 1 buckets worth will result in it reverting to just 1B. 

#### Steps to reproduce:
1.Make Pattern Grid
2.Change to Fluidcrafting and processing
3.insert a bucket of water. 
4. Try to increase the amount of water.
...

#### Version (make sure you are on the latest version before reporting):

- Minecraft:1.12.2
- Forge:2750
- Refined Storage:1.6.3

Does this issue occur on a server? [yes/no] 
yes

**Comment by raoulvdberge** [comment]
That is intended. You can reuse other slots too to include the same fluid.

For what do you need so much?

**Comment by Darkere** [comment]
The Issue only came up because the Cryotheum Coolant Units from Simply jetpack require 4 Buckets of Cryotheum. Using JEI to insert it resulted in no Fluid input at all. I just manually added it later.

For now, I've not had any big issues with the limitation but it seemed like something that might be an unnoticed sideeffect.

**Comment by raoulvdberge** [comment]
I'll leave it as it is.

**Comment by jerry1333** [comment]
It's an issue when trying to make pattern to fill Meat Feeder from Industrial Foregoing (can accept 128 buckets of Liquid Meat)

**Comment by raoulvdberge** [comment]
It CAN accept 128 buckets, but do you need 128 buckets at once?

**Comment by jerry1333** [comment]
Well let it be 64 per pattern or configurable (default 1, max 128) so anyone can decide.
In most cases it should be enough.
