### ISSUE TITLE
Ore Dict recipe crafting in crafting issue

### ISSUE THREAD

**Issue by Chupp4-Jo3** [raoulvdberge/refinedstorage#1954]
When trying to make an item with an OreDict enabled pattern it won't auto craft items for it.

So in this instance I'm trying to make empty redstone fluxducts:

(THIS IS VERT BAD _PSEUDO_ CODEY GUESS WORK)

When crafting items with patterns without OreDict the system seems to do some kind of check storage for item modname:item_name:<meta data as number> and if that returns an integer it tells you how much of the item is in the system and if that integer is less than the amount for the recipe it refuses to craft. But, if the item has a recipe set up in a crafter then it checks the items recipe and returns that as well. Rinse and repeat.

However, if the pattern has OreDict enabled it seems to do a check for it's ore dict entry itemtypeGenericNameForItem then if anything matches that it gives the number unless all the results return 0 then it looks to see if the first item in the list of OreDict items is craftable (when making redstone fluxducts it needs hardened glass which has the first entry, item with the lowest meta data and I assume first alphabetically, as hardened copper glass) which as I don't have a recipe for that only normal Hardened Glass the system says no Hardened Copper Glass is available so the recipe can't be made

I assume it's meant to check if any item matching the OreDict entry is craftable then use the first one it finds based off something arbitrary (like mod name alphabetically followed by item meta data lowest first) and check that for each recipe saved in the system.

Steps to reproduce:
1. have RS system with recipe for item made of an ore dictionaried item which the system is set up to craft. 

2. give system recipe for the OreDict item that is not the first in the list (Hardened Glass from TF when Hardened Copper Glass comes up first) 

3. remove all other items that are supported so it has to default to crafting the OreDict'd component.
...

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12.2
- Forge: 14.23.4.2749
- Refined Storage: 1.6.3

https://imgur.com/a/ZkuXbE4 <-- Imgur library of screenshots showing issue

**Comment by md5i** [comment]
Could https://github.com/davqvist/Exoria/issues/332 be a different symptom of the same problem?

**Comment by raoulvdberge** [comment]
This issue should be fixed now in the development build thanks to my commit above.

Could you guys test this, please? Remember that you're playing a dev version, so take a backup.

(IMPORTANT) You want build 293: https://jenkins.raoulvdberge.com/job/refinedstorage/293/

Thanks!

@Chupp4-Jo3 
@md5i 
@dralom
@UnstableCodeScarlet
@Tirco

(Disclaimer: Chances are it might still be broken, in that case we can work further.)

**Comment by Chupp4-Jo3** [comment]
Thanks for the update! I'll try and test this tonight. :)

**Comment by raoulvdberge** [comment]
Any updates??

**Comment by raoulvdberge** [comment]
Assuming that this is fixed. If it's not, let me know.
