### ISSUE TITLE
All items are gone

### ISSUE THREAD

**Issue by Carl42O** [raoulvdberge/refinedstorage#1955]
#### Issue description:
I changed my game to jar instead of native in twitch launcher settings to get around a crashing issue with another mod and when i loaded my world my disk drive where messed up I cant see how many items are in them and when i put them into a disk drive they act like they are not there 
#### What happens:
Nothing 
#### What you expected to happen:
Access my items 
#### Steps to reproduce:
unknown
#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12
- Forge: 14.23.4.2739
- Refined Storage: 1.6

Does this issue occur on a server? [yes/no]
no

Screenshot
https://media.discordapp.net/attachments/479745424220094476/479745556303052811/unknown.png?width=959&height=323

**Comment by raoulvdberge** [comment]
You corrupted your world. Restore from backup.

**Comment by Carl42O** [comment]
is there nothing else i can do my last back up was from 2 days ago
