### ISSUE TITLE
cant craft with buckets

### ISSUE THREAD

**Issue by DarkxAnger** [raoulvdberge/refinedstorage#1956]
#### Issue description:
unable to auto craft with buckets. ie ender buckets, glowstone buckets redstone buckets.

(on a side note, possibly related, even when in a crafting grid, crafting with buckets is annoying. even when the system has plenty of buckets of ender the empty bucket stays in the crafting window. so i have to replace the recipe for every bucket.)

#### What happens:
im playing fbt revelation and it just updated to RS 1.6.3. im assuming the mod pack tweeked the configs a bit cuz solderers have been removed so a bunch of my recipies were changed. i fixed most of my auto crafting patters but iv tried and tried to fix the bucket patterns and my system just wont see them avalable to craft or in storage.

#### What you expected to happen:

when i call for enderium dust to be crafted together my system is suposed to combine the materials 3lead dust 1 plat dust and one bucket of ender. always says missing bucket of ender. so i call for a bucket of ender, the system makes it no problem. i have 8 buckets in my system. still says its missing. i have triple checked patters remade them twice checking ore directory was on and that the buckets i have in storage are the exact same as the ones in the pattern. still cant find it

#### Steps to reproduce:
1. make pattern for 3 lead dust 1 plat dust and one bucket of ender
2. call for the recipe.
3.
...

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12.2
- Forge: 2750
- Refined Storage: 1.6.3

Does this issue occur on a server? yes im running a server locally

#### If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here]

**Comment by raoulvdberge** [comment]
Read the changelog and Wiki. There is new fluid autocrafting.

**Comment by DarkxAnger** [comment]
I know there is. And I have been using the new system. Still doesn't change the fact that there are recipies that can't work
