### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by dragonriderworld** [raoulvdberge/refinedstorage#1959]
Issue description:
Its not an real issue but will there be a projectE integration coming anywhen like in 1.11??

Minecraft: 1.12.2
Forge: 14.23.4.2756
Refined Storage: 1.6.3

You said no. But why pls explain it to me. I know its your decision what you make with this mod but i want to know why.

**Comment by dragonriderworld** [comment]
And whats the last Minecraft-/RS- Version where it is implementated.

**Comment by raoulvdberge** [comment]
no need to make a new issue

and 1.5.34

**Comment by raoulvdberge** [comment]
It was removed for stability reasons.
