### ISSUE TITLE
Refined Storage Battery

### ISSUE THREAD

**Issue by VT-14** [raoulvdberge/refinedstorage#1962]
This is a request to be able to store additional energy in the RS system.

Currently, energy is only stored in the Controller, and you can only have 1 controller per network.  The Controller's capacity is controlled by a config value, and defaults to 32,000 FE.  This puts a hard limit on how much power the RS system can store.

With some items using as much as 1,000 FE/t, exceptionally large systems may exceed the size of the Controller's buffer every tick.

In addition, it may be desirable to have additional energy capacity in the RS system in case of a power failure.

**Comment by DuelMonster** [comment]
I second this feature request.

I've been using the "Capacitor Banks" from EnderIO to achieve something similar but they can only transfer 25,000 FE/t maximum.

It would be great if RS had its own UPS _( uninterruptible power supply )_ style battery system.

**Comment by raoulvdberge** [comment]
I'm not sure if this problem is realistic.

**Comment by DuelMonster** [comment]
If, for example, I have a collection of Network Transmitters in various locations around my world all running 1 FE/t per block distance and the total distance equates to 30,000 blocks and I also have three additional Network Transmitters with Interdimensional upgrades running at 1,000 FE/t, I am now running at a total of 33,000 FE/t and RS can't keep up with the power demand.
All this bearing in mind that the rest of the system is drawing additional power for the drives, wireless transmiters, grids etc. etc...

Yes I could up the capacity in the config, but if I was on a server where that wasn't an option, I'd be stuck and would have to downsize my system.

**Comment by raoulvdberge** [comment]
But that use case is unrealistic.

**Comment by DuelMonster** [comment]
I beg to differ.  My personal server is currently running at at least 24,000 FE/t...
I have several users and they all want access to a single storage system and they are all dotted about the world.

**Comment by DuelMonster** [comment]
That's a good idea. It would make more sense to have them draw the power on demand.

However I'd still expect them to require a small amount passively just to keep things more consistent.

**Comment by raoulvdberge** [comment]
I've thought about it and I think a centralized energy place that the controller is is much cleaner and simpler.
