### ISSUE TITLE
Feature request: Config option to disable check for server strain.

### ISSUE THREAD

**Issue by dpsbrdi** [raoulvdberge/refinedstorage#1964]
As nice as the check is to avoid server strain from complex crafting, the ability to either disable or increase the timeout time would be nice.

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12.2
- Forge: 14.23..4.2749
- Refined Storage: 1.6.3

Does this issue occur on a server? yes

**Comment by raoulvdberge** [comment]
Are you hitting this limit?

**Comment by dpsbrdi** [comment]
Yep when trying to auto craft draconic solar panels from solar flux reborn. I have to do it in 2 stages when trying to do it from scratch.

**Comment by raoulvdberge** [comment]
I could make it a config option, yeah.
