### ISSUE TITLE
Server crashes every 5min/nobody is able to join it

### ISSUE THREAD

**Issue by TheHeavenOnMoon** [raoulvdberge/refinedstorage#1966]
#### Issue description:
After the server starts up it wont let anyone join it and crahses shortly after. We are using addons with RS so that might be an issue too?
#### What happens:
Server wont respond after startup. 
#### Steps to reproduce:
1. Start server
2. Try to join/do anything in console
3. Wait till it crashes

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12
- Forge: 1.12.2-14.23.4.2705
- Refined Storage: 1.6.3

Does this issue occur on a server? [yes/no]
yes
#### If a (crash)log is relevant for this issue, link it here:
https://pastebin.com/VcuUC3SZ
[pastebin/gist/etc link here]

**Comment by raoulvdberge** [comment]
Are you using QuantumStorage disks?

**Comment by raoulvdberge** [comment]
https://github.com/gigabit101/QuantumStorage/issues/154
