### ISSUE TITLE
Issue: Items incorrectly recorded

### ISSUE THREAD

**Issue by Hirschney** [raoulvdberge/refinedstorage#1967]
#### Issue description:
Items showing more in inventory than actually exist
#### What happens:
Occasionally some items will randomly show more than are actually in the system.  Often it is double the actual amount
#### What you expected to happen:
correct numbers
#### Steps to reproduce:
1.grab something from inventory
2.less than what is shown comes out
3.
...

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12.2
- Forge: 14.23.4.2757
- Refined Storage: 1.6.3

Does this issue occur on a server? [yes/no] yes

#### If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here]

**Comment by CrossVas** [comment]
#1885

**Comment by raoulvdberge** [comment]
Crappy reproduction steps. Can you make a better case, or I'll have to close this. Thank you.

**Comment by Hirschney** [comment]
I do not know how else to describe it.  It does not happen every time.  All I know is you go to the console, open it up and let's say you want widgets.  You see in the system 100 widgets but when you grab them you only get 50 as opposed to 64 as you would expect to find with more than a stack in.  It still shows 50 available.  If you close the console and go back the same item it still shows 50.  If you take the drive out and put it back in the phantom 50 widgets is gone.

**Comment by Hirschney** [comment]
If I knew that I would stop doing whatever it was that caused it.  I am just here to tell you it is happening.  The creator of the modpack I play on asked me to come to report the problem here.  I play on a public server of World of Dragons.  Kreezxil runs it.  He is the one that asked me to report it so here I am doing my due diligence.

**Comment by raoulvdberge** [comment]
Do you have any external storages connected?

**Comment by Hirschney** [comment]
I do not.  I have a chest with an importer but that hasn't been used in a while

**Comment by raoulvdberge** [comment]
Can you report me the IDs of your storage disks (turn on advanced tooltips to see them and hover over the disks)

**Comment by Hirschney** [comment]
e58e6a15-0fa5-42b3-8594-e3f490f6b652 has most of the stuff in it
8d6d69bc-aa16-474f-99aa-16dcf64e897a is the other one.

**Comment by raoulvdberge** [comment]
Sorry, I can't do anything with this report.  Closing.
