### ISSUE TITLE
Drive contents being wiped in creative mode

### ISSUE THREAD

**Issue by DemonScythe45** [raoulvdberge/refinedstorage#1968]
#### Issue description:
While in creative mode, moving an rs drive from one inventory slot to another clears the contents on all drives currently held in player inventory.

Before moving drive in inventory:
![image](https://user-images.githubusercontent.com/28666229/44679459-4508fa80-a9f8-11e8-86c7-4797f2256af2.png)

After moving drive in inventory:
![image](https://user-images.githubusercontent.com/28666229/44679525-741f6c00-a9f8-11e8-95ce-b73b6e66b092.png)

This is only an issue in creative, drives are not cleared in survival.

#### What happens:
The "Items" NBT tag is cleared while the "Stored" tag is left intact.

#### What you expected to happen:
The "Stored" and "Item" NBT tags should remain intact.

#### Steps to reproduce:
1. Get any number of storage drives, the capacity does not matter.
2. Put items into the drives, either using a full RS system or a portable grid.
3. Move the drives back into your inventory.  At this point the drives should all still be intact.
4. Move one drive to a different slot in your inventory.  At this point the "Items" tag will have been cleared on all drives in your inventory.

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12.2
- Forge: 14.23.4.2715-universal
- Refined Storage: 1.5.34
- Modpack: All The Mods 3 v5.9.8d

Does this issue occur on a server? [yes/no]
Yes

**Comment by raoulvdberge** [comment]
> (make sure you are on the latest version before reporting)
