### ISSUE TITLE
[ISSUE] RS system won't autocraft correctly with metallurgic infuser?

### ISSUE THREAD

**Issue by Icerith** [raoulvdberge/refinedstorage#1969]
#### Issue description:
In an attempt to autocraft solar panels, which in certain recipes can require Enriched Alloys and Basic and Advanced Control Circuits, I tried to set up the Metallurgic Infuser to craft them. It shouldn't be too difficult, considering all of the spots are set to what can even be put in them(i.e. redstone can only go in a certain spot, or at least defaults to a certain spot), but I'm having issues.

#### What happens:
When choosing to autocraft one of the two(Enriched Alloy or Basic Control Circuit), nothing will come of it. It won't even inject anything into the Metallurgic Infuser.

#### What you expected to happen:
I expected items to be injected into the Metallurgic Infuser via the Crafter, and be imported into the system via the Importer on the other side.

#### Steps to reproduce:
1. Set Crafter next to Metallurgic Infuser with Importer on other side. It might be possible that you have to recreate my entire system, or at least that portion of it that's seen in the pictures.

2. Set up the Crafter to autocraft Enriched Alloy and Basic Control Circuits using a processing pattern, inserting a piece of redstone and an iron ingot, and inserting a piece of redstone and an osmium ingot respectively. Outputs being the above two.

3. See if your system can effectively craft the two items.

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12.2
- Forge: 14.23.4.2715
- Refined Storage: 1.5.34
- Mekanism: 1.12.2 - 9.4.13.349

Does this issue occur on a server?: Unknown.

EDIT: https://imgur.com/a/ieFwm2o

**Comment by Icerith** [comment]
(Well, that's really fun, right? Dying of laughter and embarrassment.)

**Comment by raoulvdberge** [comment]
I can edit your post if you want, so noone saw it.

**Comment by Icerith** [comment]
Only if you'd like. Not a big deal, doubt anybody would look that closely anyway.

**Comment by raoulvdberge** [comment]
Can you reproduce this issue on RS 1.6.3 (the latest version)?

**Comment by Icerith** [comment]
Took me a bit, had some crashes when trying to update, but fixed those. The problem doesn't seem any different when updating.

**Comment by PanSzelescik** [comment]
Mekanism doesn't have Input/Extra mode in one side

**Comment by macdrack** [comment]
Pan is right, so if anything this is a Mekanism issue.  Although it's not really as Pan points out Mekanism blocks don't typically have Input/Extra on one side.
What you want here is a Mekanism RFC so it may behave a bit more like EnderIO machines.
You can implement what you want using a chest and a Mekanism Logistical Sorter.
I've done this and can use just one Infuser with all the different types of recipes.
Still struggling with the energy tablet recipes though, but that's another issue....
