### ISSUE TITLE
Pattern for salt automatically ejects from crafter

### ISSUE THREAD

**Issue by Zupami** [raoulvdberge/refinedstorage#1970]
#### Issue description:
When putting the pattern to make salt (pot + bucket of water, from Pam's Harvestcraft) in the crafter, it auto ejects it.

#### What happens:
The pattern ends up either on the ground or back in my inventory.

#### What you expected to happen:
The pattern stays in the crafter, allowing me to craft salt.

#### Steps to reproduce:
1. Create the pattern for salt (pot + bucket of water)
2. Put it in the crafter

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12.2
- Forge: 14.23.4.2715
- Refined Storage: 1.5.34
- Pam's Harvestcraft: 1.12.2

#### Does this issue occur on a server? [yes/no]
yes

#### Video as further explanation:
https://youtu.be/n_vft-T_ClU

**Comment by raoulvdberge** [comment]
You are not on the latest Refined Storage version. Reporting a bug, and that should be obvious, requires the user to be on the latest version.

**Comment by NoLoginFound** [comment]
Same thing happens on the same version with botania's hovering hourglass. If that helps.

**Comment by Zupami** [comment]
Just tested it with the following versions:

- Minecraft: 1.12.2
- Forge: 14.23.4.2705
- Pam's Harvestcraft: 1.12.2y
- Refined Storage: 1.6.3

And it does work.
It must be either fixed in a later version, or it is a conflict with another mod from my modpack.
It's quite impossible to test this, so I guess we'll never know...
