### ISSUE TITLE
Bad Timings. Low performance refinedstorage:controller.

### ISSUE THREAD

**Issue by Mr-Krab** [raoulvdberge/refinedstorage#1971]
**** Issue description:
Timings https://timings.aikar.co/?id=c16508c091194f0b8ac20e3c6ad191e0
Profiler https://sparkprofiler.github.io/?vPVyfVZ9J7

- Minecraft: 1.12.2
- Forge: 14.23.4.2747
- SpongeForge: 1.12.2-2705-7.1.0-BETA-3422
- Refined Storage: 1.6.3

This problem occurs on the server. On the client it was not tested.

The logs are clean.

**Comment by raoulvdberge** [comment]
Should be fixed for the next release.
