### ISSUE TITLE
cover shenanigans supposedly interfere with GTCE recipes

### ISSUE THREAD

**Issue by Yoghurt4C** [raoulvdberge/refinedstorage#1972]
#### Issue description:
cover compliance detector is producing weird serverside crashes. I was able to suppress it on the gtce side for a while but now it's completely broken no matter what I try
#### What happens:
when performing any crafting action with "pipelike" gtce blocks, RS is preventing them from being crafted, sometimes producing fatal crashes. this ONLY happens serverside. all pipelike gtce blocks have "clientside-only" renderer checks added.
this DOES NOT happen without refined storage present.
#### Steps to reproduce:
1. get gtce and rs
2. put them on a server
3. try to craft a gtce fluid pipe or cable
... 

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12.2
- Forge: 2757
- Refined Storage: built from https://github.com/raoulvdberge/refinedstorage/commit/21973ad4c19aa12a447da7b6fe5eb8540ba2ab48

Does this issue occur on a server? [yes/no]
serverside-only 

what usually happens: https://pastebin.com/j3TSxA8H
what happens on a fatal crash: https://pastebin.com/KqD4eTa1

**Comment by Archengius** [comment]
Please take note that you should NEVER, NEVER try to call clientside-only methods on server side. It breaks variety of mods that use CCL which adds additional BlockRenderType values as example. If you try to do such kind of things and it is necessary, just use try/catch and don't except that client-side things will magically work on server side without any errors.

**Comment by raoulvdberge** [comment]
Report to Gregtech. Not a RS issue.

**Comment by raoulvdberge** [comment]
I wonder why this didn't break earlier/before.

**Comment by codewarrior0** [comment]
IMO, It's a shortcoming of CCL that it doesn't give you an easy way to add those additional BlockRenderType values on the server side, since the code path leading to adding the values is all client-only code.

**Comment by raoulvdberge** [comment]
Then the question is whether RS should fix CCL's shortcomings.

I don't believe so.

**Comment by Archengius** [comment]
If you can't understand the fact that method that returns render-related information shouldn't work flawlessly on dedicated server, it's not my issue.
Neither it is my issue it isn't flagged as client-side only. As long as it is direct correlation with rendering purpose, it should not be used on server-side.
Still, i don't get what prevents you from at least try-catching that kind of code? Heightened self-esteem compared to other mods?

**Comment by InsomniaKitten** [comment]
The issue here is not with CCL or RS, it is that GregTech is storing their custom BlockRenderType in a class that implements client interfaces. The simple solution would be to store the BlockRenderType elsewhere, so that referencing it does not load client code.
