### ISSUE TITLE
Feature request: adding Expose Upgrade that allows interface to expose the whole network

### ISSUE THREAD

**Issue by WillisShek** [raoulvdberge/refinedstorage#1973]
*** Issue Description
From 1.6, interface no longer exposes to whole network. It prevents a lot of interaction with other mods. Things like Storage scanner from rftools, Controller from Xnet can no longer read the system and perform the automation job.

*** Suggestions
Adding a Network Expose Upgrade, which can be disable in config, to interface so players can choose whether to allow certain interface to expose the whole network. If it does cause performance issues, server admin can disable it in config.

Also a Limited Network Expose Upgrade can be added so that it only exposes certain items (eg. 9) in the networks. It may help the performance in certain cases.

**Comment by raoulvdberge** [comment]
Nope!
