### ISSUE TITLE
Please fix the cutting tool!

### ISSUE THREAD

**Issue by Twotusktommy** [raoulvdberge/refinedstorage#1974]
#### Issue description:  Since the removal of the solderer in refined storage the cutting tool was implemented. I am currently auto crafting reborn storage storage disks and it is requiring more than 10000 cutting tools for one of the 16mill disks. this is a lot of iron and quartz just for the tool that is used to replace the solderers not even the storage disks themselves. Please make the cutting tool like the Pam's items or the philosophers stone. i.e. no durability. Also, it seems to be causing a lot of lag due to the crafting and inserting of all the cutting tools. Thank you for listening.
~Tommy

#### Steps to reproduce:
1. Auto craft any high end refined/reborn storage items
2. If you do the math 10000 cutting tools is 3333 quartz, 10000 iron, and 20000 sticks. This is added to the already massive component list. 
3. 
...

#### Version (make sure you are on the latest version before reporting):1.16

- Minecraft:1.12
- Forge: twitch forge Version 7.5.6815.39912
- Refined Storage:1.16

Does this issue occur on a server? [yes/no] yes

#### If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here]

**Comment by Ravalli03** [comment]
I agree, the cutting tool is way too expensive and lags down the system. I can suggest maybe making an unbreakable version that we can craft.

**Comment by raoulvdberge** [comment]
Duplicate
