### ISSUE TITLE
GUI cut off

### ISSUE THREAD

**Issue by Ravalli03** [raoulvdberge/refinedstorage#1975]
#### Issue description:

Crafting overview and crafting monitor GUI are cut off on the right side Pic below

#### What you expected to happen:

To be center

#### Steps to reproduce:
1. Open Crafting Monitor screen or craft overview 
2.
3.
...

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12.2
- Forge: 14.23.4.2715
- Refined Storage: 1.6.4

Does this issue occur on a server? [yes/no]

No

#### If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here]

https://imgur.com/a/LSZ94We

**Comment by CrossVas** [comment]
It seems to be an issue from your Resource pack that you are using.

**Comment by Ravalli03** [comment]
oh, ok. Thanks for the info.
