### ISSUE TITLE
World not loading

### ISSUE THREAD

**Issue by Casper1123** [raoulvdberge/refinedstorage#1977]
#### Issue description:
World not loading
#### What happens:
It loads until valkrielib and then stops. The devs of EnderIO say its due to this mod sadly
#### What you expected to happen:
Just for the world to load
#### Steps to reproduce:
1. Load world
2. Wait
3. Wait
... oh shit it doesnt work
?personal?

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge: 
- Refined Storage:

Does this issue occur on a server? [yes/no]
Nope
#### If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here]

Link to post on EnderIO forum with (hopefully) all the needed details:
https://github.com/SleepyTrousers/EnderIO/issues/4858#issuecomment-418853366
Notify me if there are critical details missing

**Comment by Casper1123** [comment]
Forge version is in the post description on the enderio forum.

I really hope i dont need to start another world tbh

**Comment by raoulvdberge** [comment]
Not interested in 1.10 issue reports.
