### ISSUE TITLE
Feature request: Crafter Compatibility with the EnderIO enchanter and Keyword Filter

### ISSUE THREAD

**Issue by Casper1123** [raoulvdberge/refinedstorage#1978]
#### Steps to reproduce:
1.
2.
3.
...

#### Version (make sure you are on the latest version before reporting):

- Minecraft:
- Forge:
- Refined Storage:

Does this issue occur on a server? [yes/no]

#### If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here]

So it would be cool if for example you could put an external storage for liquid xp on an exp obelisk. Then when crafting enchanted books it could pull out the required experience. Thus is for example very usefull for the mod Woot wich i like. 

Idea 2: making an option for searching for example :food: to see all the edible items in your storage / grid. I know we have for example @EnvironmentalTech to get all items from that mod, but for example typing :alloy-smelter: would show everything craftable by the alloy smelter in your storage. :alloy: would then for example show Redstone Alloy and Vibrant alloy but also Pulsating Iron

Thank you
- Casper

**Comment by raoulvdberge** [comment]
No
