### ISSUE TITLE
Autocrafter crashing the server

### ISSUE THREAD

**Issue by kerts93** [raoulvdberge/refinedstorage#1983]
#### Issue description:
Something in regards with Refined Storage autocraft is crashing our server constantly, we haven't fiqured out which setup is causing this.

#### What happens:
Server crashing
#### What you expected to happen:
Server not crash
#### Steps to reproduce:
N/A
We are gathering info about the setups people have and will post them here: https://minecraft.curseforge.com/projects/the-society-transportcraft/issues/18

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12.2
- Forge: 14.23.4.2759  
- Refined Storage: refinedstorage-1.6.4.jar 
It happens on our modpack (https://minecraft.curseforge.com/projects/the-society-transportcraft), full list of mods and their versions can be found in the crashlogs.

Does this issue occur on a server? yes

#### If a (crash)log is relevant for this issue, link it here:

[crash-reports.zip](https://github.com/raoulvdberge/refinedstorage/files/2363727/crash-reports.zip)

```
java.lang.IllegalStateException: Can't fill up inventory even though we could
	at com.raoulvdberge.refinedstorage.apiimpl.autocrafting.task.CraftingTask.updateProcessing(CraftingTask.java:694)
	at com.raoulvdberge.refinedstorage.apiimpl.autocrafting.task.CraftingTask.update(CraftingTask.java:762)
	at com.raoulvdberge.refinedstorage.apiimpl.autocrafting.CraftingManager.update(CraftingManager.java:166)
	at com.raoulvdberge.refinedstorage.tile.TileController.func_73660_a(TileController.java:203)
	at net.minecraft.world.World.func_72939_s(World.java:1832)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by kerts93** [comment]
One idea is that this is the reason it crashes:
https://minecraft.curseforge.com/projects/the-society-transportcraft/issues/19

**Comment by StarSmasher44** [comment]
For mine it seemed to be different, I used a crafting table (The type that holds items even when you close it, not sure the mod), Activating a processing crafting task with 1 cutter, 50 silicon = 50 cut silicon. It just seemed to try and fill every box available with shit in the hopes that it worked I guess? 
That or I may need an explanation on how to autocraft cut silicon and further..

**Comment by raoulvdberge** [comment]
Cut silicon is a regular recipe. You *don't* need to automate that with a processing recipe. You create a regular recipe.

**Comment by nssatlantis** [comment]
The issue I had with that was its weird use of the cutter (since it has a durability) and only using it once

**Comment by ibdoomed** [comment]
> > The problem is that the inventory connected to the Crafter reports that it can accept (all) items during a simulation, but when actually performing an operation there is remainder and not all items are inserted.
> > Refined Storage needs some better handling for this, but the root cause is with the inventory.
> 
> Ok, so the problem lies with the inventory, meaning Storage Drawers (since I assume you don't mean the RS disks and that's the only other inventory I'm using)?

Using world backups and restores I was able to duplicate the issue and once storage drawers was removed, the problem no longer occurs.

**Comment by raoulvdberge** [comment]
No. With "inventory connected" I mean the inventory connected to a crafter for a processing pattern.
