### ISSUE TITLE
patterns in the crafting grid

### ISSUE THREAD

**Issue by quietreaper** [raoulvdberge/refinedstorage#1986]
#### Steps to reproduce:
1.went into pattern grid and make an iron ingot pattern
2.went into crafter and placed the pattern inside
3.went into crafting grid and put iron ingot in the search bar but nothing appears that says craft
...

#### Version (make sure you are on the latest version before reporting):

- Minecraft:
- Forge:
- Refined Storage:

Does this issue occur on a server? [yes/no]

#### If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here]

**Comment by CrossVas** [comment]
Any screenshots would be useful to understand your problem.
