### ISSUE TITLE
Crafter doesn't work with multiple patterns that all use a single, unlimited item

### ISSUE THREAD

**Issue by breadbull** [raoulvdberge/refinedstorage#1987]
#### Issue description:
  In the mystical agriculture mod I have created patterns to create supremium essence, which requires 3 intermediate recipes that all use a master infusion crystal. This crystal is infinite and will not be used up.

#### What happens:
  The system tells me that I need more infusion crystals, one for each pattern.

#### What you expected to happen:
  The system should realise that the infusion crystal can be used for multiple patterns.

#### Steps to reproduce:
1. Have mystical agriculture
2. Make patterns for prudentium, intermedium, superium and supremium essence
3. Attempt to create supremium essence.

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12
- Forge: 14.23.4.2715
- Refined Storage: 1.5.34

Does this issue occur on a server? [unknown, probably]

![Screenshot](https://user-images.githubusercontent.com/35699509/45414451-f9b84280-b6ad-11e8-9f22-4924e4bc7256.png)

**Comment by raoulvdberge** [comment]
Intended and you are on an old version.
