### ISSUE TITLE
Autocraft crashes

### ISSUE THREAD

**Issue by felixletsplayYT** [raoulvdberge/refinedstorage#1988]
#### Issue description:
Autocrafting crashes Server when autocrafting pure certus with mekanism enriching factory.
#### What happens:
Server crashes and will crash on every start.
#### What you expected to happen:
Autocrafting crafts pure certus.
#### Steps to reproduce:
1. Make recipe which generates pure certus by putting pure certus seeds in mekanism enriching factory.
2. Start recipe
...

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12.2
- Forge: 14.23.4.2707
- Refined Storage: 1.6.3 (Changelog in mods menu goes up to 1.6.5)

Does this issue occur on a server? yes

#### If a (crash)log is relevant for this issue, link it here:

Crash log: https://pastebin.com/NCeLDVdc

Thanks for helping

**Comment by raoulvdberge** [comment]
Update
