### ISSUE TITLE
dup bug

### ISSUE THREAD

**Issue by Brukiler** [raoulvdberge/refinedstorage#1989]
#### Issue description:
You can dupe everything that can be stacked
#### What happens:
free items
#### What you expected to happen:
no dupe 
#### Steps to reproduce:
1.just put up a crafting grid no power
2. Enter what you want more from in crafting grid
and shift click-right mouse button or
 shift click left mouse button the item 
until you get a stack

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12.2
 Forge:-14.23.4.2760
- Refined Storage:-1.6.5.jar

Does this issue occur on a server? [yes/no]
yes 
#### If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here]
![2018-09-14_13 05 12](https://user-images.githubusercontent.com/43268780/45546895-0c9e5480-b81f-11e8-9b3b-88abb7abbc30.png)

**Comment by raoulvdberge** [comment]
My change made it so you can't shift click from crafting inv -> system. Have to fix that.

**Comment by 016Nojr** [comment]
Dupe bug in action

https://clips.twitch.tv/SneakySweetBibimbapM4xHeh

**Comment by raoulvdberge** [comment]
Fixed for real now.
