### ISSUE TITLE
External Storage Priority Not Retaining

### ISSUE THREAD

**Issue by Darkosto** [raoulvdberge/refinedstorage#199]
I have an External Storage connected to a Storage Drawers Drawer Controller, I have set my priority to be 9. When I leave my base (it is chunkloaded) and fly back, the priority has reset back to zero. I'm not sure if this is just a visual glitch and the priority maintains or if it actually gets reset.

Mod Version: 0.8.10
MC Version: 1.10.2

**Comment by raoulvdberge** [comment]
Weird, can definitely not reproduce that

**Comment by Darkosto** [comment]
I can show you on stream if you're able to stop by :)

**Comment by raoulvdberge** [comment]
I know the cause of this and I'm working on a fix :)
