### ISSUE TITLE
GameStages compatibility bug - Can't craft gated items in RS crafting grid

### ISSUE THREAD

**Issue by Gamertech** [raoulvdberge/refinedstorage#1991]
#### Issue description:
Some recipes can't be crafted in the RS crafting grid, but are crafted fine in any other crafting table.

#### What happens:
Example: 9x osmium into a block crafts fine

9x lapis shows the block on the right side, but the block vanishes when clicking on it. Shift clicking to craft multiple of a problem recipe has no response at all. Working recipes react as normal.

Clearing the grid puts all recipe mats back into the system uncrafted.

Restarting the client or changing worlds has no effect, and it's always the same recipes.

Affected recipes are a mix of both vanilla and modded.

#### What you expected to happen:
Valid recipes should be craftable in the RS crafting grid.

#### Steps to reproduce:
1. Gate a recipe using GameStages
2. Place the recipe into the crafting grid
3. Click to take the completed item
4. Item vanishes and can't be crafted using RS

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12.2
- Forge: 14.23.4.2759
- Refined Storage: 1.6.5
- Refined Storage Addons 0.4.2
- Refined Avaritia 1.12.2-2.3

Does this issue occur on a server? [yes/no]
Yes

#### If a (crash)log is relevant for this issue, link it here:
No info or errors are shown in the debug relating to RS or the affected items.

**Comment by raoulvdberge** [comment]
Can you reproduce this with just RS (all other mods deinstalled)?

**Comment by Gamertech** [comment]
No, with just RS it works fine.

I've narrowed it down, it seems to be an incompatibility between RS and GameStages. Any recipe that isn't gated with GS works fine, any recipe that is gated (even after it's been unlocked) fails to craft.

If I remove the staging on an item it can craft as normal, so it seems that RS isn't reading recipes after they've been unlocked.

Again, RS shows the working recipe when items are placed into the crafting grid, and plays the crafting event sound effect, but the completed item can't be taken out of the grid, it just vanishes. If I attempt to craft the item before it's unlocked, the completed recipe doesn't show, which is intended.

**Comment by raoulvdberge** [comment]
Intended. RS doesn't provide a player to the crafting container as it can be used by multiple people at the same time.

**Comment by Gamertech** [comment]
I'd see this as an issue though. More and more modpacks are coming out using GameStages after SevTech, and RS is the only well-known crafting/storage mod that has any real issue with it.

Possible fix: GameStages is already doing all the work with controlling recipes. If the recipe isn't unlocked then the finished product won't be visible or able to be interacted with in the GUI, so if the craft successfully shows in the GUI, then bypass any blocks and allow the craft as per normal.

You wouldn't need to send the player, or interact with GS at all and can keep the existing multi-user behaviour.

Ofc it might not be possible, but if it is would be a relatively easy way to cheese GS compatibility without changing RS in any major way.
