### ISSUE TITLE
Stacked crafters do not share redstone control state

### ISSUE THREAD

**Issue by DarkHelmet433** [raoulvdberge/refinedstorage#1992]
#### Issue description:

When stacking multiple crafters onto one machine for extra processing pattern slots, they do not coordinate their redstone control activity.

#### What happens:

Suppose you have an output-regulated Botania altar system where you're using the collection of the crafted items to generate a 'Next!' pulse.  If you feed this pulse to both crafters in the stack, both will initate their next queued recipe at once.

If you have an input regulation system where the emptying of an inbound ingredients buffer chest generates the 'Next!' pulse, sending the signal to both crafters will trigger two crafts being pushed.

#### What you expected to happen:

I'm not sure what I expected, but this does not seem a particularly useful behavior.

The least astonishing behavior that I can think of is to have the bottom-most crafter's redstone mode control the entire stack, including 'locked' status, and disable the redstone mode control on the other stacked crafters.  One pulse to the bottom-most crafter should enable one single craft of the entire stack.  If the bottom-most crafter is the only one with redstone controls enabled, it is a hint that that is the crafter that should receive the redstone signals.

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12.2
- Forge: 14.23.4.2759
- Refined Storage: 1.6.6-289 (Jenkins build)

Does this issue occur on a server? yes (both server and single player)

#### Additional comments:

I do not feel this is a particularly burdensome problem.  While the present behavior is understandable it is inconvenient.

Automation of a Botania Altar requires 16 patterns, some of which have byproducts that match lower tier recipe outputs.  The creation of one of the lower tier items can't be used to select which crafter in a stack to trigger.  It can be done with two altar setups, with is not necessarily a bad thing anyway.

The setup I used: https://i.imgur.com/Dh5ttEB.png
The eight tier-1 and 2 runes are produced on the right, and the 8 tier-3 runes on the left.
The altar throws items into the world after completion, the range collector picks them up.  The comparator on the chest provides the 'Next!' pulse.  The importer on the chest is redstone controlled to make sure the items are not grabbed before the pulse is triggered.

Output based blocking is quite useful as it avoids the unreliable "signal block" mechanic that other systems have to resort to.  It's just that redstone control doesn't interact well with stacked crafters.

**Comment by eihns** [comment]
what about crafter -> chest -> stuff you want to do? u can redstone the conduits?

**Comment by raoulvdberge** [comment]
This has been fixed.

The new behavior:

- If the crafter isn't a root (head) crafter, there is no "crafter redstone mode" sidebutton available;
- All the redstone operations are supposed to happen on the root crafter;
- The child crafters ignore redstone;
- The child crafters inherits it's "crafter redstone mode" from the root crafter.
