### ISSUE TITLE
[1.6.4] Stack Crafting Lag.

### ISSUE THREAD

**Issue by KaneHart** [raoulvdberge/refinedstorage#1994]
Issue:
When crafting in stacks or even single items but harder to see it seems to go through the entire array for every item so 64 times.

Suggestions:
Check this mod out:
https://minecraft.curseforge.com/projects/fastworkbench
https://minecraft.curseforge.com/projects/fastfurnace

They might offer suggestions on how to make refined storage a lot less laggy when it comes to crafting via the Interface. This happens sadly to most mods out there don't assume it's your fault here this the way it handles it in Minecraft really annoying. 

- Minecraft: 1.12.2
- Forge: 14.23.4.2760
- Refined Storage: 1.6.4

Does this issue occur on a server?
Yes

**Comment by raoulvdberge** [comment]
RS does what it can to avoid this problem (caching the recipe), just like fast workbench does.

**Comment by raoulvdberge** [comment]
RS doesn't change the vanilla bench.
