### ISSUE TITLE
Auto-Crafting does not detect Items correctly / Ignores Ore-Dict Settings

### ISSUE THREAD

**Issue by a20eac1d** [raoulvdberge/refinedstorage#1996]
#### Issue description:
I am trying to craft [TE Capacitors](https://teamcofh.com/docs/thermal-expansion/flux-capacitor/). Every Capacitor requires another Capacitor of the tier below it. Even though Refined Storage knows the patterns for all of the items required, it does not detect them and gives an error ("missing items").
Toggling Ore-Dict on/off does absolutely nothing.

#### What happens:
I request a Capacitor and it complains because it is not detecting the items correctly.

#### What you expected to happen:
I expect RF to detect the patterns correctly and to craft all required items.

#### Steps to reproduce:
1. Make patterns for all Thermal Expansion Capacitors
2. Request highest level Capacitor

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12.2
- Forge: 14.23.4.2760
- Refined Storage: 1.6.5

Does this issue occur on a server? [yes/no]
- Yes

**Comment by raoulvdberge** [comment]
Read older issues (like the one just closed 2 days ago)
