### ISSUE TITLE
Request: If possible, allow External Storage to fill the storage it's attached to using that block's whitelist.

### ISSUE THREAD

**Issue by Imrtltrtl** [raoulvdberge/refinedstorage#1997]
I've just tried to use an External Storage on a Storage Drawers 'Drawer Controller' and it worked well enough by depositing blocks put into the Grid into the Drawers before the disks as well as pulling from the drawers first when pulling out of the Grid. 

The behavior I'd like to see though is the External Storage filling the storage from the disks as much as possible to keep that external storage full. 

For example, I have a room full of storage drawers from the Storage Drawers mod and I link them all with the Drawer Controller. I would like the Refined Storage system to fill those drawers using the External Storage attached to the Drawer Controller. Keep the pulling from storage function, but place any system blocks into the storage bin/chest/drawer to fill it as much as possible. 

In the end I'm looking for a Storage Drawers room to be stocked with the excess blocks stored in the Refined Storage system without having to link an Exporter to each drawer with that block whitelisted inside each Exporter. When I pull items from the drawers, I'd like to keep them stocked using the Drawer Controller pulling from the External Storage.

**Comment by raoulvdberge** [comment]
Remove all your disks and use the disk manipulator to fill the external connection as much as possible.

**Comment by Imrtltrtl** [comment]
You would have to cycle through each disk at least once every time I pull an item from the external storage making any other item on those disks unavailable to the network. Not to mention how tedious it would be manually placing each disk into a manipulator, at most, 3 at a time. Even with a stack upgrade and 3 speed upgrades this takes a long time. That is not a viable solution to the idea I was asking for, but thanks for the response.

**Comment by Tahakk** [comment]
It does not take that long of time, I transfered biggest store from Reborn Storage just fine. Sure it takes some time. And I believe that you can pipe in/out the storage discs, not sure on that one tho.
