### ISSUE TITLE
Energy Tablet from Mekanism Not able to be used in auto crafting

### ISSUE THREAD

**Issue by davo97** [raoulvdberge/refinedstorage#1998]
#### Issue description:
Energy Tablet from Mekanism Not able to be used in auto crafting.

#### What happens:
When going to auto craft it says missing item.

#### What you expected to happen:
Energy tablet in storage and auto craft to happen.

#### Steps to reproduce:
1. Pattern an energy tablet.
2. Pattern an item that uses the tablet in a recipe (induction casing)
3. Try to craft.
...

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12.2
- Forge: 14.23.4.2760
- Refined Storage: 1.6.4 (one behind)

Does this issue occur on a server? [yes/no]
More than likely
 
PS: I did notice the NBT tags are different from the crafted item to the JEI item. Even when creating the pattern from a crafted Energy tablet, the craft still says missing item. 

so my guess is once the craft is stored on a pattern, the NBT tag goes back to the JEI tag 

{mekData:{energyStored:0.0d}} is the NBT tag when crafted and in the system
{mekData:{}} is the NBT tag from JEI

**Comment by raoulvdberge** [comment]
Read prev issues
