### ISSUE TITLE
Crafting a recipe in a TE Induction Smelter causes the server to crash

### ISSUE THREAD

**Issue by a20eac1d** [raoulvdberge/refinedstorage#1999]
#### Issue description:
I have setup a recipe for (Iron + Nickel = Invar in Induction Smelter) and tried crafting it.
The RS Crafter is directly facing the TE Induction Smelter's Input-Side.

#### What happens:
The Server crashes when I request the Item to be crafted.

#### What you expected to happen:
The machine to craft it.

#### Steps to reproduce:
1. Create a recipe for the Invar Ingots.
2. Put it into the Crafter facing the Induction Smelter
3. Request the Item

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12.2
- Forge: 14.23.4.2760
- Refined Storage: 1.6.5

#### Server
- Yes

#### If a (crash)log is relevant for this issue, link it here:

PLEASE NOTICE THE LONG NBT STRING ON LINE 32.
https://paste.ee/p/JOdlj

**Comment by a20eac1d** [comment]
Some screenshots to make things clear. They have been taking after the crash and after restarting the server.

[The machine setup.](https://i.imgur.com/mc18lCB.png)
[The Crafter and recipe being used.](https://i.imgur.com/iosffE3.png)
[The Induction Smelter. Apparently, the Nickel Ingot could be inserted before crashing.](https://i.imgur.com/ONu2tWG.png)
[The Status-Monitor shows that it is stuck.](https://i.imgur.com/Zyf9YG9.png)

Also, you might have noticed the left most slot in the Induction Smelter being locked. That has nothing to do with the crash. I have tried all possible settings inside of the TE Induction Smelter, including locking, unlocking and even Redstone Settings.

**Comment by Tahakk** [comment]
Now I'm not sure if you have unlocked slot that is used for 2nd material (try to put it there by hand) and we cannot see if you have IS side setup as input side.

**Comment by raoulvdberge** [comment]
Fixed in v1.6.6. Use a development build or wait till its released.
