### ISSUE TITLE
New Processing Pattern Mode

### ISSUE THREAD

**Issue by tgstyle** [raoulvdberge/refinedstorage#2000]
I have a machine that can switch modes depending on the items inserted and will not remove them until the output is finished. However the output of the machine only needs the first items inserted for the mode to continue processing the output. Refined storage however thinks in order to get the output it needs to build all the machine needs for its mode in order to get the product. When it only needs 1 set of the items for the mode, and many for the output.

Suggestion, a pattern that can wait for the "mode items" to come back before continuing with 2nd item. Or a way to tell it that it only needs one set of "mode items" but many product items to continue making the same item.

I know this can be worked around by setting the product in the pattern to a higher amount. It would just be nice if refined storage had some granularity in processing patterns.

**Comment by raoulvdberge** [comment]
no
