### ISSUE TITLE
An unknown problem occured!

### ISSUE THREAD

**Issue by a20eac1d** [raoulvdberge/refinedstorage#2001]
I am not sure if this problem is caused by RefinedStorage, but I can only reproduce it by opening the RS Terminal. It  does not happen with AE2.

#### Issue description:
When I open the RS Crafting Terminal, I spammed with messages in the top right corner that "An unknown problem occured!".

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12.2
- Forge: 2760
- Refined Storage: 1.6.5

Does this issue occur on a server? [yes/no]
- Yes

#### If a (crash)log is relevant for this issue, link it here:
[https://paste.dimdev.org/tudasarelo.mccrash](https://paste.dimdev.org/tudasarelo.mccrash)

**Comment by raoulvdberge** [comment]
I don't know. The crash report tells me nothing.
