### ISSUE TITLE
[Suggestion] Key bind to stop grid from sorting

### ISSUE THREAD

**Issue by Darkere** [raoulvdberge/refinedstorage#2002]
When a grid set to sort by item amounts there is the unfortunate issue that pulling out items moves them to another slot. Because of this, I frequently end up with stacks of other items when pulling out multiple stacks. 

The Idea is to add a keybind that stops the system from rearranging the items. 
Shift would be a good candidate as it already gets pressed when relevant. 

Loving the new updates thanks for all your work.

**Comment by raoulvdberge** [comment]
Shift might be a good idea.

**Comment by raoulvdberge** [comment]
Done for 1.14.4
