### ISSUE TITLE
[IDEA] New type of Upgrade "Stockupgrade" (Autocrafting + external Storage)

### ISSUE THREAD

**Issue by eihns** [raoulvdberge/refinedstorage#2003]
Hello,

Im not sure if this is the correct way to suggest something, but i try.

**What i want to do?**
1.) I would like to keep stock of some items (this can be done via Interface, i know)
2.) I want to keep stock inside an external storage (this time storage drawlers)
I want to use storage drawlers because the compacting drawers are very aesthetic and also you dont need to add recipes for every block and nugget, having a easy way to keep stock of all the things u need

**Problem?**
I have a external storage in export only mode attached to a storage drawler controller together with an export (with crafting upgrade).

<img width="1920" alt="45689188-9ddd3600-bb53-11e8-94ae-11b5ad1376ad" src="https://user-images.githubusercontent.com/43281991/45825466-9902b880-bcf2-11e8-8236-7c4666fc9cb4.png">

_ofc this loops._

**What i want?**
I would suggest a new type of bus, a stockupgrade bus, it acts like a combined external storage + export bus - but WITHOUT the loop. (dont fullfill export requests to his self - if nothing else is in the network, craft it)

Alternative 1 would be that export buses dont improt into external storage if its connected to the same block (see picture). (dont use the external storage bus to fullfill requests of the exporter if its connected to the same block)

(worser ideas)

Alternative 2 would be that external storages can give out a redstone signal when requesting something, so this could shutoff the other exporters. (or the other way around)

Alternative 3 add a new option to the external storage ("only for manual use" - when you take soemthing out of the grid, or click in JEI items into the grid)

**Comment by raoulvdberge** [comment]
no

**Comment by eihns** [comment]
Why?
