### ISSUE TITLE
Cover face that is facing north doesn't render correctly.

### ISSUE THREAD

**Issue by halvors** [raoulvdberge/refinedstorage#2004]
#### Issue description:
Cable with covers is not looking like the block the cover is made from on the surface facing north.

#### What happens:
Face of block that is facing north direction doesn't render correctly.

#### What you expected to happen:
The face tha tis facing north to render normally like the other faces for south etc.

#### Steps to reproduce:
1. Cable going up coverd with covers.
2. Look at the north face.

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12.2
- Forge: 14.23.4.2759
- Refined Storage: 1.6.5

Does this issue occur on a server? [yes/no]
Yes.

Here is a screenshot of the rendering problem:
https://www.dropbox.com/s/46hujnls0rxdxvo/2018-09-22_05.50.04.png

**Comment by raoulvdberge** [comment]
I don't understand your screenshot.

With what blocks can I reproduce this, and can you reproduce it with vanilla block covers?
