### ISSUE TITLE
Crashed when filtering the exporter

### ISSUE THREAD

**Issue by Edwinchen1** [raoulvdberge/refinedstorage#2007]
#### Issue description:
just as the topic said

#### What happens:
wanted to export emerald ore from system to smeltry controller from tinker, when i open the ui of the exporter, it is fine, but when i filter the emerald ore, game crashes. 

#### What you expected to happen:
just filter the emerald ore without game crashing.

#### Steps to reproduce:
sorry, no idea how i should write this so i just skipped.
...

#### Version (make sure you are on the latest version before reporting):

- Minecraft:1.12.2
- Forge:14.23.4.2750
- Refined Storage:1.5.32,1.5.34(both the same error)

Does this issue occur on a server? [yes/no]
no. singleplayer world
#### If a (crash)log is relevant for this issue, link it here:
[crash-2018-09-22_10.39.35-client.txt](https://github.com/raoulvdberge/refinedstorage/files/2407648/crash-2018-09-22_10.39.35-client.txt)
[crash-2018-09-22_17.13.18-client.txt](https://github.com/raoulvdberge/refinedstorage/files/2407649/crash-2018-09-22_17.13.18-client.txt)
this two are 2 different version of rs, but with exact the same issue.

[pastebin/gist/etc link here]

**Comment by Edwinchen1** [comment]
"Version (make sure you are on the latest version before reporting):"
emmmmmm...... i cannot do that because on the latest version of rs addon , it doesn't corporate with projecte mod which is a huge bummer and i just don't know why.(it would be also cool for me if anyone can tell me how to make this work just in case i accidentally did something wrong or it just doesn't work as the older version did)
sorry for my creepy english.

**Comment by Edwinchen1** [comment]
by "i cannot do...." i mean if anyone could help me with this issue it would be extreme cool but if i must install the latest version to post issues here, just plz ignore this.
thanks in advance.

**Comment by Edwinchen1** [comment]
hope someone would read the crash reports and find the solution for me....

**Comment by raoulvdberge** [comment]
Update

**Comment by Edwinchen1** [comment]
> Update
but the thing is, if i update to the newest version of rs and rs addon, i would never be able to interact with projecte mod any more and that is a huge bummer for me. do you have any advice for that?
