### ISSUE TITLE
Crash on server

### ISSUE THREAD

**Issue by jerry1333** [raoulvdberge/refinedstorage#2008]
#### Issue description:
Server is crashing at startup when build from latest source code (up to commit 6a3a8e5)
#### What happens:
Encountered an unexpected exception
net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Refined Storage (refinedstorage)
Caused by: java.lang.BootstrapMethodError: java.lang.IllegalAccessError: no such constructor: com.raoulvdberge.refinedstorage.tile.TileCrafter.<init>()void/newInvokeSpecial
#### What you expected to happen:
Server not crashing?
#### Steps to reproduce:
1. Build from source
2. Run server (client works fine)

#### Version (make sure you are on the latest version before reporting):
source code at version 6a3a8e5
- Minecraft: 1.12.2
- Forge: 1.12.2-14.23.4.2760
- Refined Storage: 6a3a8e5

Does this issue occur on a server? [yes/no]
Yes
#### If a (crash)log is relevant for this issue, link it here:
https://pastebin.com/rTFjeXDn

**Comment by raoulvdberge** [comment]
From where did you get that build??

**Comment by jerry1333** [comment]
Download source and build it (like it's written in Steps to reproduce).

**Comment by raoulvdberge** [comment]
You just need to download  refinedstorage-1.6.6-294.jar from there. It's that simple. Did you do that?

**Comment by jerry1333** [comment]
I think it's 511104c94831acd002d1924cccce84085e1819e2 issue since it tries to use Gui on server side (GuiContainer is @SideOnly(Side.CLIENT))? 

Also build https://jenkins.raoulvdberge.com/job/refinedstorage/291/ is loading fine on servers.

**Comment by raoulvdberge** [comment]
Aha thx! Should be fixed on the latest build.
