### ISSUE TITLE
Refined Storage Recipe crashes the server on startup

### ISSUE THREAD

**Issue by a20eac1d** [raoulvdberge/refinedstorage#2009]
#### Issue description:
Refined Storage crashes the game. The world has become unplayable.

#### What happens:
When I try to start the server, Refined Storage crashes.

#### Version (make sure you are on the latest version before reporting):
- Minecraft: 1.12.2
- Forge: 2760
- Refined Storage: 1.6.5

#### Does this issue occur on a server?
Yes

#### If a (crash)log is relevant for this issue, link it here:
[Crash log 1](https://pastebin.com/raw/z76jSA4j)
[Crash log 2](https://pastebin.com/raw/41qzUpvN)

**Comment by a20eac1d** [comment]
I have also noticed RS Recipes disappearing randomly.
Items that could be crafted previously simply disppear.
This might or might not be related.

**Comment by raoulvdberge** [comment]
Watchdog crashes are not regular crashes! This may or may not be RS. There is no way to tell of this report.

**Comment by raoulvdberge** [comment]
Looking at your earlier comment, your pack seems kinda unstable. So closing this as not an RS problem. If it is, I can reopen.

**Comment by a20eac1d** [comment]
It is a problem caused by Refined Storage.

The pack is perfectly fine, it's only Refined Storage causing issues. 

If you are unable to fix your own mod you should look into getting an experienced developer on board instead of closing helpful issues left and right.

Removing RebornStorage does not fix the issue so it is not the cause.

**Comment by way2muchnoise** [comment]
You don't have to use RS it is a free addon provided without any warranty. Giving comments like this will only make it less likely that anyone would even be remotely interested into fixing your issue.

Also you say "start the server", does this mean an existing world? Or a new world? Does this also happen with only RS? Any way you would be able to track down which other mods might cause it? Or be involved in this issue (it might be an interaction between multiple mods). These are some of the questions you should think about before/while reporting issues as they might be helpful.

**Comment by raoulvdberge** [comment]
Given your tone I have no interest in helping you. Please don't return to the tracker.
