### ISSUE TITLE
Feature Request: Wireless Crafting Terminal

### ISSUE THREAD

**Issue by blockbreaker1361** [raoulvdberge/refinedstorage#201]
I don't know if you've seen the wireless crafting terminal for AE2 on 1.7.10, but it would be nice if we could craft/auto-craft on the go. I am usually always on the go and it's a bit of a nuisance to have to go all the way back to the terminal to craft something. Also, how about an upgrade for the wireless extenders to allow for cross-dimensional access? I believe the cross-dimensional upgrade would solve the need for multiple extenders.

**Comment by raoulvdberge** [comment]
1) If you are at the point where you have wireless, get autocrafting set up for the stuff you need on the go. Having a crafting grid in the wireless grid is way too OP.

2) Cross-dimensional access is OP as well

**Comment by blockbreaker1361** [comment]
Ok. It was just a suggestion.
