### ISSUE TITLE
Forestry Botteler crash

### ISSUE THREAD

**Issue by crazyivan532** [raoulvdberge/refinedstorage#2011]
#### Steps to reproduce:
1. open crafting grid
2. find bottler for forestry mod
3. click auto craft icon and wait
...

#### Version (make sure you are on the latest version before reporting): 1.6.5

- Minecraft: 1.12.2
- Forge: 14.23.4.2760
- Refined Storage: 1.6.5

Does this issue occur on a server? [yes/no] yes, a local hosted one.

#### If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here]

**Comment by raoulvdberge** [comment]
hey, this is duplicate!

#1790
