### ISSUE TITLE
Crafting is not re-using damaged items

### ISSUE THREAD

**Issue by tgstyle** [raoulvdberge/refinedstorage#2012]
#### Issue description:
Using the cutting tool to make cut items, RS keeps crafting new undamaged ones.

#### What happens:
System fills up with 1 use cutting tools.

#### What you expected to happen:
Crafting to reuse tools until they are destroyed.

#### Steps to reproduce:
1. Pattern Using an item that damages
2. Craft using item that damages
3. Watch them get used only once
...

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12.2
- Forge: 2760
- Refined Storage: 1.6.6-295

Does this issue occur on a server? yes

**Comment by Darkere** [comment]
https://github.com/raoulvdberge/refinedstorage/issues/1993#issuecomment-422866682
