### ISSUE TITLE
Server Crash: java.lang.IllegalStateException: Can't fill up inventory even though we could

### ISSUE THREAD

**Issue by OfficialStamper** [raoulvdberge/refinedstorage#2013]
#### Issue description:
Server crashes with:
```java.lang.IllegalStateException: Can't fill up inventory even though we could``` 
(crash report attached)

#### What happens:
Upgrading from 1.63 to 1.65, autocrafting using crafter inserting into botania:opencrate crashes server.

Edit: having tried this a few times, each time the server does crash, upon restart the first item in the recipe has been successfully inserted.

#### What you expected to happen:
crafter should insert ingredients into botania:opencrate 
this works fine with 1.63, but not with 1.65

#### Steps to reproduce:
1. Create pattern for a botania rune, (replace the botania:runicalter with living rock)
2. Point crafter at botania:opencrate and insert pattern
3. Request auto craft for created pattern
4. Server crash
...

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12.2
- Forge: forge-1.12.2-14.23.4.2760-universal
- Refined Storage: refinedstorage-1.6.5

Does this issue occur on a server? [yes/no] YES

#### If a (crash)log is relevant for this issue, link it here:
Crash Log
https://gist.github.com/OfficialStamper/a5ad5e3e810ef1f4b48a4598796f42b7

**Comment by raoulvdberge** [comment]
fixed indev
