### ISSUE TITLE
Non-Immediate "Hey btw" kinda bug, already fixed just throwing it out there.

### ISSUE THREAD

**Issue by bloorocksDotD** [raoulvdberge/refinedstorage#2015]
#### Issue description:
Display? Bug, made it seem like items in drives were gone
#### What happens:
It appeared as though all the items in my disk drive were gone, I couldn't view any items or take any items out, drive still read as 23k filled
#### What you expected to happen:
Items to still be there
#### Steps to reproduce:
Unsure if this will reproduce since I'm not willing to test it cuz my game takes ~15mins to relaunch. but this is what happened leading up to the issue
1. I dumped ~4k Inferium Essence into the system
2. I used the crafting grid + JEI Shift+ key repeatedly to turn them all into blocks, then dumped em back in the system
3. Repeated step 2 all the way up the tiers
4. Searched "essence" (still in the crafting grid) and the system showed that I still had 4k inferium essence, but none of the higher tier essences or blocks were showing under that search terms
5. Delete the search term expecting to see all my items again
6. Display is empty
7. Check wireless grid, grid, crafting grid, everything is showing empty
8. Panic
9. Save & quit then relaunch the game
10. Items now displaying as normal
...

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12
- Forge:
- Refined Storage:
Latest version of the Stoneblock pack
Does this issue occur on a server? [yes/no]
no
#### If a (crash)log is relevant for this issue, link it here:
I can link it if you want it, but this isn't really an immediate issue.
[pastebin/gist/etc link here]

**Comment by bloorocksDotD** [comment]
Basically just a display bug(or so I hope, I have to actually check and see if ALL my items are still there) Just throwing it out here in case other users experience it and it's something fixable :)

**Comment by raoulvdberge** [comment]
Sorry, I can't do anything with those reproduction steps!

**Comment by instinxx** [comment]
I have 2 different users on my server that reported this issue to me today.  In both cases a client restart fixed it. There is nothing in the server log. Unsure of client logs as they have not sent them. We also attempted pulling out the drives to reinitialize, remove/replace all the system components but it did not help. Would be happy to give more info if it happens again. In both cases for me the users had been playing for hours when this occurred. We are using Forge .2760 and Refined Storage 1.6.5, Refinedstorageaddons0.4.2 and in case it matters... rebornstorage 1.12.2-3.2.2.65. Happy to help diagnose if you need something specific.

**Comment by bloorocksDotD** [comment]
Oh I forgot about this thread until that notification popped up, I did have the issue happen to me again on the stoneblock pack(latest version as of yesterday so 1.0.9) and I tried removing & replacing drives, removing the controller, I tore the entire network down and put it back and still nothing, interacted with different grids & wireless grids and still nothing, changed dimensions, re-built it in the nether, and still nothing displayed, then a quick relog fixed it.

**Comment by instinxx** [comment]
In order to further compile data on this issue and hopefully help @raoulvdberge find the bug, my modlist is here https://pastebin.com/jPJhn0KP. I would be more then willing to run a version that can give verbose logging if that exists.
