### ISSUE TITLE
dupe bug 

### ISSUE THREAD

**Issue by avidgamer5918** [raoulvdberge/refinedstorage#2017]
#### Steps to reproduce:
1.have a unpowered rs crafting grid 
2.put in a stackable item in the grid
3.then shift click the item in the grid not the output 
...

#### Version (make sure you are on the latest version before reporting):

- Minecraft:1.12.2
- Forge:14.23.4.2706
- Refined Storage:1.6.5

Does this issue occur on a server? yes

here is a clip of how to do it:
https://clips.twitch.tv/WiseFancyNuggetsCoolStoryBro

**Comment by raoulvdberge** [comment]
Fixed in dev.
