### ISSUE TITLE
Crafting with multiple fluids only works with special tanks.

### ISSUE THREAD

**Issue by Darkere** [raoulvdberge/refinedstorage#2019]
#### Issue description:
When trying to autocraft something that requires multiple Fluids only one of the fluids gets inserted unless the accepting machine is able to accept multiple Fluids at once. 

#### What happens: 
Autocrafting gets stuck when trying to craft with multiple fluids.

#### What you expected to happen:
First, one fluid gets inserted, then the other afterwards.

#### Steps to reproduce:
1. Make a pattern that uses multiple fluids. (Molten Dawnstone in my case it uses Molten Copper and Gold)
2. Setup the crafter looking at a tank.
3. Craft 
...

#### Additional Comments
The Craft also is very slow due to the fact that it stalls for a bit whenever it cannot insert the fluid.

The only solution I found is using a tank that accepts multiple liquids. A tinker's smeltery was the only thing I could think of.

On version 1.6.4 where I initially encountered this, the complete system would get reset when it encountered this issue.

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12.2
- Forge:2760
- Refined Storage: 1.6.6-300 ( from jenkins).

Does this issue occur on a server? [yes/no]
yes

**Comment by raoulvdberge** [comment]
But isn't that the fault of the mod? Most fluid tanks only support 1 fluid at a time. I can't do anything about that.

**Comment by Darkere** [comment]
Kind of yeah, the embers alloy mixer needs the gold in one side and the copper on another. That means I already have to use a different tank as a buffer and then sort the fluid later. 

The idea is that RS would insert one fluid and then waits until I empty the tank while it is unable to insert the other. Instead of what it currently does, where if a fluid cannot be inserted it will just be skipped.

This allows working around the issue outside of RS.

**Comment by raoulvdberge** [comment]
What do you mean with "skipped"? It shouldn't skip the fluid. The crafting task blocks until the fluid can enter again. It should insert fluid 1 and when fluid 1 is gone it should insert fluid 2. It does that, right?

**Comment by raoulvdberge** [comment]
Refined Storage needs to be able to insert all the fluids (or even items) at once, to avoid mixing issues. So this will be a won'tfix!
