### ISSUE TITLE
[Suggestion] An item to copy/paste filter settings

### ISSUE THREAD

**Issue by c0rn3j** [raoulvdberge/refinedstorage#202]
It's annoying to set up 10 furnaces, put exporters on them and then define settings in each exporter, an item to help with that would be nice.

**Comment by raoulvdberge** [comment]
I was thinking about adding shift click support to specimen slots. Maybe that is a better alternative?

**Comment by raoulvdberge** [comment]
![http://i.imgur.com/RJTbaqQ.gif](http://i.imgur.com/RJTbaqQ.gif)

This is how it can work now

**Comment by c0rn3j** [comment]
While this is certainly better but still doesn't solve when I'm adding more machines and  don't have the items on me, and it'd be very annoying to figure out which items I'm missing exactly and see if I even have any. 

I still think that a tool to copy and paste settings across exporters and such is needed.

**Comment by raoulvdberge** [comment]
I don't think such a tool belongs in RS
