### ISSUE TITLE
Suggestion: Configuration options to add risk and maintenance

### ISSUE THREAD

**Issue by Crowfooted** [raoulvdberge/refinedstorage#2020]
For risk, I'd really love to be able to enable a config that causes all (or some) data to be lost if the controller ever completely runs out of power.

For maintenance, I'd like individual disk drives (or individual disks) to have a chance to be disconnected occasionally from the system and need to be checked and reconnected in order to work again. (Edit: Preferably, without notification, so that players have to check their system every once in a while to make sure everything's working.)

**Comment by raoulvdberge** [comment]
Nice idea but we don't do config options for features.
