### ISSUE TITLE
Processing + external storage = duplication + dellusion

### ISSUE THREAD

**Issue by Lejoni** [raoulvdberge/refinedstorage#2021]
#### Issue description:
Doing any processing where the result is supposed to end up in an external storage (drawers), duplicates the result + duplicates again but the last duplicated items are not usable and disappears if game is restarted or a disk in disk drive is removed and then inserted again (even though nothing is stored on it)

#### What happens:
Duplication is of course wrong. But the main issue is the erroneous amount in the RS grid later as autocrafts can get stuck on that thinking there was enough resources when there was non.
I have confirmed that the duplication occurs when items are imported to the RS system. Whatever external process is used is not relevant.

#### What you expected to happen:
No duplication and correct number listed in RS grid.

#### Steps to reproduce:
Uploaded an unlisted video where I demonstrate how to reproduce it in a creative test world:
https://youtu.be/Vc55ZUzDdkg

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12.2
- Forge: 14.23.4.2760
- Refined Storage: Tested with 1.6.4, 1.6.5 and 1.6.6-300

Does this issue occur on a server? [yes/no]
Don't know but game says it runs an internal server?

#### If a (crash)log is relevant for this issue, link it here:
Its not crashing.

**Comment by jaylamping** [comment]
bump.. I am experiencing this issue as well when i introduce the external storage interface into my system.

**Comment by raoulvdberge** [comment]
I am able to reproduce this issue

**Comment by raoulvdberge** [comment]
Thank you for reporting. There was still some code in RS that handles expectations for the OLD autocrafting system. Since it didn't cause any syntax errors, this was overlooked.

Caused by fix for issue: https://github.com/raoulvdberge/refinedstorage/issues/1725

Caused by commit: https://github.com/raoulvdberge/refinedstorage/commit/2d1745235f165c85000436f6b3abf4901402e1d6

**Comment by Lejoni** [comment]
Glad I could help :)
