### ISSUE TITLE
Machine does not accept item while busy, does not try again

### ISSUE THREAD

**Issue by UnstableCodeScarlet** [raoulvdberge/refinedstorage#2023]
#### Issue description:
I have a crafter hooked up to a Fluid transposer (Also tested it with EIO fluid tank) with a pattern with 1000 mb and a bucket, for lava and water. They work independently, but in the event a autocraft requires both the machine is busy while it's doing one, and so the other task fails. Usually this is fine as it'll try again when it's not busy, but it doesn't seem to be trying at all. (I was crafting Material Stoneworks Factories)

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12 
- Forge: 14.23.4.2759
- Refined Storage: 1.6.5

Does this issue occur on a server? [yes/no]
Yes, a Spongeforge one, I am unaware of the spongeforge version.

**Comment by raoulvdberge** [comment]
Can you try the latest devbuild on our Jenkins? It should be fixed there.

**Comment by raoulvdberge** [comment]
Duplicate #2016
