### ISSUE TITLE
AE dont connects with RS after update

### ISSUE THREAD

**Issue by MineProjectZ** [raoulvdberge/refinedstorage#2025]
#### Issue description:
After i updated Refined Storage from 1.5 to 1.6 i have a problem with Applied Energiestics compatiblity.
#### What happens:
When i connect an Applied Energiestics Storage Bus to a Refined Storage Interface, the ME System dont shows the items stored in the Refined Storage System.
#### What you expected to happen:
The items from the Refined Storage System should show up in the ME System (it worked with Refined Storage 1.5)
#### Steps to reproduce:
1.Update from Refined Storage 1.5 to 1.6
2.Connect an Applied Energiestics Storage Bus to a Refined Storage Interface

#### Version:

- Minecraft: 1.12.2
- Forge: 14.23.4.2767
- Refined Storage: 1.6.5

**Comment by Darkere** [comment]
Intended the feature produced a lot of lag. Read the changelogs.
