### ISSUE TITLE
System consuming power while turned off.

### ISSUE THREAD

**Issue by npollender** [raoulvdberge/refinedstorage#2026]
#### Issue description:
Auto crafting system uses power while the controller is turned off.

#### What happens:
I turn off my controller to prevent power loss, the controller continues to use power even though my system is off. The power is being used by the auto-crafting blocks (Crafting frame, heat conductor, etc).

#### What you expected to happen:
No power is used.

#### Steps to reproduce:
1. Make an auto-crafting system.
2. Turn off your controller.
3. Power continues to be used.
...

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12.2
- Forge: 14.23.4.2759
- Refined Storage: 1.6.5

Does this issue occur on a server? Yes

#### If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here]

**Comment by raoulvdberge** [comment]
The autocrafting blocks you mention are from Reborn Storage. Can you reproduce this with just Refined Storage blocks?

**Comment by raoulvdberge** [comment]
Relevant: https://github.com/TechReborn/RebornStorage/issues/122
