### ISSUE TITLE
Disk get deleted if storage drive is picked up with moving wand

### ISSUE THREAD

**Issue by KyVarment** [raoulvdberge/refinedstorage#2027]
#### Issue description:
I'm playing on a Stoneblock server, the problem is disk get deleted if storage drive is picked up with moving wand from not enough wands.

#### What happens:
I had a moving wand in my hand when I clicked to open the storage drive and I picked it up I set it back down and all the drives were gone. 

#### What you expected to happen: 
not to have the disk deleted when drive was put down

We tried to rollback the region and everything reset except the disk in the drive, is RS data stored in a way it could be restored?

#### Steps to reproduce:
1. (stoneblock modpack) put disk in a drive
2. pick it up with a moving wand (not enough wands 1.12-1.7.1)
3. put it back down and poof the disk are gone
...

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 12.2.2
- Forge: 14.23.4.2760
- Refined Storage: 1.6.5

Does this issue occur on a server? [yes/no] 
Yes

#### If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here]

**Comment by raoulvdberge** [comment]
yes, that's because RS tiles don't use a tile entity behind the scenes. Don't use a wand on RS blocks..

**Comment by Darkere** [comment]
You might be able to figure out the ID of the missing disks by loading a backup. Then you can use the /createdisk command to restore it.

**Comment by raoulvdberge** [comment]
Yes, forgot to mention that. /createdisk <TAB> gives a list of all IDs.

**Comment by raoulvdberge** [comment]
You'd also want to rollback refinedstorage_nodes.dat.

**Comment by KyVarment** [comment]
Ok, thank you. I wasn't planning on using the wand on the drive it was just a mistaken click from being in a hurry. Thank you for replying . I'm playing on a server over at requiem, I'm assuming rollingback refinedstorage_nodes.dat. effects everyone so I probably shouldn't ask for that to be rolled back, they rolled back me region without effecting other players, I'll have to chock this one up as lessened learned.

**Comment by Darkere** [comment]
I always make a screenshot of the disk when I insert a new disk into the system. But honestly, it would be nice if the ID had the name of its creator at the beginning (and maybe a way to identify what size disk it is?).
