### ISSUE TITLE
Refined Storage API for OC - getItem

### ISSUE THREAD

**Issue by bufu1337** [raoulvdberge/refinedstorage#2028]
How to search for a specific Item which has a tag?
for example output from crafttweaker: <"tconstruct:pick_head">.withTag({Material: "stone"}) 

i tried different ways with a refined storage system with only this item in it... 

```
component.block_refinedstorage_grid_2.getItem({name="tconstruct:pick_head", withTag={material="stone"}}, true, true)
component.block_refinedstorage_grid_2.getItem({name="tconstruct:pick_head", Tag={material="stone"}}, true, true)
component.block_refinedstorage_grid_2.getItem({name="tconstruct:pick_head", nbt={material="stone"}}, true, true)
component.block_refinedstorage_grid_2.getItem({name="tconstruct:pick_head", meta={material="stone"}}, true, true)
component.block_refinedstorage_grid_2.getItem({name="tconstruct:pick_head", material="stone"}, true, true)
``` 

  

everything results in nil, but: 

component.block_refinedstorage_grid_2.getItems() 

finds it... but I cant use getItems() in my original system because it will result in a too long list

**Comment by raoulvdberge** [comment]
You want `tag` (lowercase), your examples list `Tag` with uppercase `T`.

**Comment by bufu1337** [comment]
can you give me an full example? no working:

`component.block_refinedstorage_grid_2.getItem({name="tconstruct:pick_head", withtag={material="stone"}}, true, true)
component.block_refinedstorage_grid_2.getItem({name="tconstruct:pick_head", tag={material="stone"}}, true, true)`

**Comment by raoulvdberge** [comment]
I suggest you go to the OpenComputers community, I don't use the integration myself so I can't help you.

**Comment by raoulvdberge** [comment]
Note: the tag={} param probably wants an EXACT match, so not specifying all tags would be problematic.

**Comment by bufu1337** [comment]
i wrote ther and the only answer was: go to refined storage, they can help you

https://oc.cil.li/index.php?/topic/1740-refined-storage-api-getitem/

**Comment by raoulvdberge** [comment]
I gave you the answer in the post above you. The tag parameter requires ALL relevant tags, not only part of it.

If you still have more questions, please join our Discord or ask someone else on OC.

Like I said, I can't help you further.
