### ISSUE TITLE
Revert Issue: Remove autocrafting check in detector #1910

### ISSUE THREAD

**Issue by rrbrussell** [raoulvdberge/refinedstorage#2029]
#### Issue description:

I cannot determine when a something is being crafted by Refined Storage.

#### What happens:

Several redstone based external processing pipelines no longer function because they are missing their controlling redstone signals. 

#### What you expected to happen:

I expected the Refined Storage system to autocraft an item requiring external redstone signals to control the processing machines. The timers that synchronize these inputs are controlled by a master enable signal from the Refined Storage system. That master enable signal no longer exists.

#### Steps to reproduce:
1. Place Detector
2. Put item in Detector
3. Click mode to find emit redstone signal when autocrafted it is missing.
...

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12.2
- Forge: 14.23.5.2769
- Refined Storage: 1.6.5

Does this issue occur on a server? [yes/no]

Doesn't matter.

**Comment by raoulvdberge** [comment]
It's not coming back

**Comment by rrbrussell** [comment]
Care to explain your logic for why this feature isn't needed or is to difficult to keep?
