### ISSUE TITLE
[Question?] Best way to keep item in stock in another inventory

### ISSUE THREAD

**Issue by Paril** [raoulvdberge/refinedstorage#2030]
Since Regulator Mode has been removed, my main method of stocking an item in another inventory is gone. I'm wondering if there's a "best method" for keeping stock of a certain item in an inventory that isn't an Interface.

As an example, I have a mod that requires I use a certain chest for items. I want to always keep stock of 1 each of a certain list of items (for example, Iron Sword, Shield, Stone Hoe). They can't pull items from other containers, only these specific containers. Exporters provided a super convenient method of doing this (and was, from what I can tell, the only mod to provide this kind of feature) with regulator mode but with that gone I'm not sure what I can do that would be equivalent to this.

**Comment by tgstyle** [comment]
An interface + a Translocator in regulator mode has done the trick for me.

**Comment by Paril** [comment]
I've never used Translocators, are they that handy? It seems silly to have to use two blocks for this kinda thing. I ended up using a buffer of Storage Drawers and EnderIO conduits with Limited Item Filters.

**Comment by tgstyle** [comment]
I agree it's silly to have to use 2 mods to do what you need. There needs to be a regulator mode upgrade or something for the exporter. Translocators are a nice upgrade for hoppers, the move items much faster and have some decent modes.

**Comment by DarkHelmet433** [comment]
Translocators have been at the epicenter of server tps problems on the MP server I've been playing on to the point that they were banned. EnderIO limited item filters have been a bit less of a server burden.  But I miss regulator mode terribly.  Regulator mode would have solved the problem of keeping cutting knives restocked in rftools crafters, for example.

Unfortunately, EnderIO RS conduits don't work with Limited Item Filters for this either.

I wish we could have a "Regulator" block in RS Addons.  Looks like an exporter, except regulates the output.

**Comment by raoulvdberge** [comment]
Let's take it here:

https://github.com/raoulvdberge/refinedstorageaddons/issues/43

Might be a thing for RS addons.
