### ISSUE TITLE
Game crashes on auto craft.

### ISSUE THREAD

**Issue by devilishhero** [raoulvdberge/refinedstorage#2031]
#### Steps to reproduce:
1.
2.
3.
...

#### Version (make sure you are on the latest version before reporting):

- Minecraft:1.12.2
- Forge:14.23.4.2765
- Refined Storage:1.6.5

Does this issue occur on a server? unknown.

#### If a (crash)log is relevant for this issue, link it here:

https://pastebin.com/UMYskaAV

**Comment by raoulvdberge** [comment]
This has been fixed in the dev builds. Coming soon to a RS release near you.
