### ISSUE TITLE
IllegalStateException: Can't fill up inventory even though we could

### ISSUE THREAD

**Issue by jaylamping** [raoulvdberge/refinedstorage#2033]
#### Issue description:

The game crashes whenever modifying the I/O properties for the Induction Smelter (Thermal Expansion)

#### What happens:

Game crashes with the below exception thrown in stack.

#### What you expected to happen:

No crash.

#### Steps to reproduce:
1. Add Induction Smelter block from Thermal Expansion mod
2. Open block GUI
3. Modify the I/O configuration settings
...

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12.2
- Forge: 14.23.4.2759
- Refined Storage: 1.6.5

Does this issue occur on a server? Yes.

#### If a (crash)log is relevant for this issue, link it here:

Console	: [17:00:55] 0 [ERROR] Encountered an unexpected exception
Console	: net.minecraft.util.ReportedException: Ticking block entity
Console	: 	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:773) ~[MinecraftServer.class:?]
Console	: 	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397) ~[nz.class:?]
Console	: 	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) ~[MinecraftServer.class:?]
Console	: 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
Console	: 	at java.lang.Thread.run(Unknown Source) [?:1.8.0_181]
Console	: Caused by: java.lang.IllegalStateException: Can't fill up inventory even though we could
Console	: 	at com.raoulvdberge.refinedstorage.apiimpl.autocrafting.task.CraftingTask.updateProcessing(CraftingTask.java:694) ~[CraftingTask.class:?]
Console	: 	at com.raoulvdberge.refinedstorage.apiimpl.autocrafting.task.CraftingTask.update(CraftingTask.java:762) ~[CraftingTask.class:?]
Console	: 	at com.raoulvdberge.refinedstorage.apiimpl.autocrafting.CraftingManager.update(CraftingManager.java:166) ~[CraftingManager.class:?]
Console	: 	at com.raoulvdberge.refinedstorage.tile.TileController.func_73660_a(TileController.java:203) ~[TileController.class:?]
Console	: 	at net.minecraft.world.World.func_72939_s(World.java:1832) ~[amu.class:?]
Console	: 	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613) ~[oo.class:?]
Console	: 	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767) ~[MinecraftServer.class:?]
Console	: 	... 4 more

**Comment by Darkere** [comment]
For next time please use a site like pastebin.com to post crashlogs (the full one). 

This particular issue is already fixed indev.

**Comment by jaylamping** [comment]
Will do! Thanks for the quick response.
