### ISSUE TITLE
Storage Bus Lag

### ISSUE THREAD

**Issue by Yamza** [raoulvdberge/refinedstorage#2034]
#### Issue description:
Storage Buses seem to use an excessive amount of tick time
https://i.imgur.com/7h34zMc.png
https://i.imgur.com/ps0DtsO.png

#### Steps to reproduce:
1. Attach storage bus to chest
2. Check event log

#### Version (make sure you are on the latest version before reporting):
- Minecraft: 1.12.2
- Forge: 2760
- Refined Storage: 1.6.5
- Modpack: ATM3 - Remix 0.1.2

Does this issue occur on a server? [yes/no]
Yes

Not sure what kind of specific info you need but if you can walk me through getting it I would be happy to try.

Possibly unrelated but the controller is also quite excessive: https://i.imgur.com/iDc4qCe.png

**Comment by raoulvdberge** [comment]
https://refinedstorage.raoulvdberge.com/wiki/performance

**Comment by Darkere** [comment]
Oh someone beat me to it. 
Some additional info. I cannot reproduce this with just RS installed. Was looking into going through some potential candidates for mods that might be the cause today but maybe you can point me in the right direction.
Heres the sample file for it in ATM3:remix https://www.dropbox.com/s/0005hx76udrlkcj/sampler-snapshot.nps?dl=0
Newly genned world with just a creative controller and like 15 external storages on empty chests.

Also your link leads to an emtpy page. 
https://refinedstorage.raoulvdberge.com/wiki/profiling is the page.

**Comment by Yamza** [comment]
On a test world, for reference: https://i.imgur.com/3VhfUsp.png
Before placing storage bus: `8 micro-s/t: EVENT_BUS_LISTENER: {EVENT_BUS_LISTENER=Refined Storage `
After: 1506 micro-s/t: `EVENT_BUS_LISTENER: {EVENT_BUS_LISTENER=Refined Storage`

Sampler: https://www.dropbox.com/s/bubr64hregfaxij/RS1.nps?dl=0
Spark: https://sparkprofiler.github.io/?WlhDcL4nBm

**Comment by raoulvdberge** [comment]
Thank you, will take a look later.

**Comment by raoulvdberge** [comment]
@Yamza 
I looked at your Spark/Sampler report:

![image](https://user-images.githubusercontent.com/10358424/46919696-3fd13080-cfe3-11e8-8782-b7eea9e3d481.png)

RS shows 0.09% usage.  Are you sure this is a real issue? Are you experiencing any lag, or are you just looking for ANY minimal tick rate usage?

**Comment by Yamza** [comment]
The initial report is REAL usage on a REAL server where I REALly removed 6 RS external storage's and got REAL significant tps improvement. I do not currently have the ability to acquire a REAL report from the REAL server so what I have given you is all I am currently able to provide.

**Comment by raoulvdberge** [comment]
Okay, I'll be happy to handle a report of a REAL server with REAL usage then!

To clarify: I want to see if the TPS issues scale upwards, or if it stays static. This requires real server usage, not some hypothetical setup.

Your Sampler/Spark report didn't show anything significant either, so I'm curious to see if it escalates.

**Comment by Yamza** [comment]
Evidence of it scaling has already been provided.
![image](https://user-images.githubusercontent.com/25225145/46947819-b3a22600-d041-11e8-892d-540d603b53e8.png)

**Comment by Darkere** [comment]
So I just had an idea...
So I ran Sampler once just looking at 20 storage busses.
https://www.dropbox.com/s/4rv0318675embwx/checkwithoutlaggoggles.nps?dl=0

And then I ran the same thing but during the 45s or so I ran 30seconds of Laggoggles profiling.
https://www.dropbox.com/s/jiw448kjiywbc0v/checkwithlaggoggles.nps?dl=0

And I found this:
![image](https://user-images.githubusercontent.com/4283717/46952645-bf1a3f00-d08b-11e8-8a78-a4fe7c5bc65b.png)

Someone please tell me I didn't spend all that time looking for a false positive....
Gonna check if that is there with just RS and laggoggles as well.
