### ISSUE TITLE
Server Crash "Can't fill up inventory even though we could"

### ISSUE THREAD

**Issue by kroeberk** [raoulvdberge/refinedstorage#2035]
#### Issue description:
Crashes the server on autocraft

#### What happens:
When I try to autocraft, the server crashes. 

#### What you expected to happen:
Not to crash the server

#### Steps to reproduce:
Can't reproduce but issue now crashes the server consistently. Can't play on the server right now. Happens for all players.

#### Version (make sure you are on the latest version before reporting):

FTB Revelation 2.5.0

Does this issue occur on a server? yes

#### If a (crash)log is relevant for this issue, link it here:

https://pastebin.com/naT9LPvN

**Comment by Darkere** [comment]
It happens when RS tries to insert Items into an inventory but cannot find enough slots(either they don't exist or are locked). It is already fixed indev.

**Comment by raoulvdberge** [comment]
Small correction: it only happens if RS doesn't find enough slots after the mod in question told us we DID have enough slots.

I added some special handling for this in development builds. Coming to a release soon. You can get it earlier from our Jenkins, but beware for instability! Take backups.

**Comment by kroeberk** [comment]
Thanks :)
