### ISSUE TITLE
Items are deleted during autocrafting when controller loses power

### ISSUE THREAD

**Issue by Kezaraux** [raoulvdberge/refinedstorage#2039]
#### Steps to reproduce:
1. Que lengthy autocrafting task (example: Elite Induction Cell from Mekanism)
2. Wait until machine has processed some items (view-able in crafting monitor)
3. Remove power supply from Controller
4. Resupply power to Controller
5. Attempt to find items

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12.2
- Forge: 14.23.4.2760
- Refined Storage: 1.6.5

Does this issue occur on a server? Yes

#### If a (crash)log is relevant for this issue, link it here:

Not applicable

**Comment by Darkere** [comment]
Was fixed about 4 hours ago. #1995
