### ISSUE TITLE
Crafting Grid Not Showing Correct Amount of Items

### ISSUE THREAD

**Issue by ColBaskerville** [raoulvdberge/refinedstorage#2040]
#### Steps to reproduce:
1.
2.
3.
...

#### Version (make sure you are on the latest version before reporting):

- Minecraft:
- Forge:
- Refined Storage:

Does this issue occur on a server? [yes/no]

#### If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here]

**Comment by Darkere** [comment]
The template is there for a reason! Please fill it out. It allows figuring out what bugs appear in what version.

That issue is known though and should be fixed in the upcoming versions.
