### ISSUE TITLE
oreDict missing for silicon and slimeballs

### ISSUE THREAD

**Issue by DarkHelmet433** [raoulvdberge/refinedstorage#2041]
#### Issue description:

Processors and the new binding don't accept oredict slimeballs and silicon.

#### What happens:

Switching to a rice slimeball, or EnderIO or Advanced Rocketry silicon causes the recipe to become uncraftable.  You can use EnderIO silicon for the controller and first tier storage parts, but not for processors.

#### What you expected to happen:

I expected silicon and slimeballs to work, like it used to with 1.6.5 and earlier.

#### Steps to reproduce:
1. Copy Processor Binding recipe to crafting table/grid
2. Change slimeball to blue or rice, watch recipe become uncraftable.
3. Same for silicon - see RS controller accepts oredict silicon, but processors do not.

There are no recipe tweaker mods in this custom pack.

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12.2
- Forge: 14.23.5.2768
- Refined Storage: 1.6.6

Does this issue occur on a server? yes

**Comment by raoulvdberge** [comment]
Fixed by https://github.com/raoulvdberge/refinedstorage/commit/fc138b22ee352dd2081644eb9c18e17e8d278748
