### ISSUE TITLE
In the Grid: Show items that has a description of the search entry

### ISSUE THREAD

**Issue by kenlauescuadro** [raoulvdberge/refinedstorage#2043]
#### Issue description: 
The grids don't scan descriptions of items in order to show them.

#### What happens:
When you search "Unbreaking" hoping to find an Enchanted Book with Unbreaking (at any level), nothing shows

#### What you expected to happen:
Instead of showing nothing, I thought that the grid will show Enchanted Books with Unbreaking.

#### Steps to reproduce:
1. Open the grid that has Enchanted Books with Unbreaking
2. Search "Unbreaking"
Result: Nothing shows (or at least no enchanted books with Unbreaking show)

#### Version (make sure you are on the latest version before reporting)
- Minecraft: 1.12.2
- Forge: 1.12.2-14.23.5.2768
- Refined Storage: 1.6.6

#### Does this issue occur on a server?
No.

**Comment by Darkere** [comment]
Refined storage doesn't by default search through the description of items.
The reason for that seems to be that it can be very laggy when there are a lot of items.

Use the "#" symbol to search for them. e.g. "#unbreaking"  will find your unbreaking books and tools.

**Comment by kenlauescuadro** [comment]
Oh my, I really see it now. My Minecraft just froze and it didn't respond for around 10 minutes. Thanks for the answer, @Darkere!
