### ISSUE TITLE
Crafting Pattern for Flux Network energy storage units contains no recipe 

### ISSUE THREAD

**Issue by Aadrik** [raoulvdberge/refinedstorage#2044]
#### Issue description:
Unable to auto-craft Flux Network basic, herculean, gargantuan storage units. 
#### What happens:
When creating the recipe for the storage units in the pattern grid the pattern is created but it holds no recipe just the resulting item.
#### What you expected to happen:
The recipe to contain the actual recipe for the storage unit to allow for auto-crafting.
#### Steps to reproduce:
1. Open pattern grid
2. Copy pattern for any storage flux network energy storage unit onto the crafting grid
3. Create a pattern
...

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12.2
- Forge: 14.23.5.2768
- Refined Storage: 1.6.8

Does this issue occur on a server? [yes/no]
No idea, I only play single player.
#### If a (crash)log is relevant for this issue, link it here:
No crash log is generated.
[pastebin/gist/etc link here]

**Comment by isirlincoln** [comment]
Same issue here, it seems only with the energy storage units.

**Comment by raoulvdberge** [comment]
This is just a rendering issue, the pattern itself works.
 I would've at least expected you tried out the pattern before coming here.

#609
