### ISSUE TITLE
Possible incompatibility with Refined Storage's Patterns and Ender Chest, and Quark's "Oak Chest" and "Oak Trapped Chest"

### ISSUE THREAD

**Issue by kenlauescuadro** [raoulvdberge/refinedstorage#2047]
#### Title clarification:
What I meant by the title is that the Refined Storage Patterns might be incompatible with:
- Ender Chest
- Oak Chest (was originally "Chest" in Minecraft and is renamed by Quark [another Minecraft mod])
- Oak Trapped Chest (was originally "Trapped Chest" in minecraft and is also renamed by Quark)

#### Issue description:
Patterns don't show textures of Oak Chest, Oak Trapped Chest, and Ender Chest.

#### What happens:
When sneaking with the Oak Chest/Oak Trapped Chest/Ender Chest pattern in inventory (or on the ground), it shows nothing.

#### What you expected to happen:
Instead of the pattern showing nothing, it must show the Oak Chest/Oak Trapped Chest/Ender Chest

#### Steps to reproduce:
1. Create a Pattern for Oak Chest (or any of the previously mentioned chests)
2. Sneak
3. See no texture

#### What I think happens (for the Oak Chest and Oak Trapped Chest):
The Pattern searches for the name of the item that is to show when sneaking. It can't find "Chest" and "Trapped Chest" (since it was renamed by Quark) so it doesn't show anything when sneaking.

#### Mods' Versions:
- Minecraft: 1.12.2
- Forge: 14.23.5.2768
- Refined Storage: 1.6.8
- Quark: r1.5-129

#### Does this issue occur on a server?
I can't tell (because I don't play RF in a server)

#### Pictures:
A picture showing two patterns (Oak Chest pattern at the left, Wooden Planks at the right) at the middle of the inventory (not sneaking):

![Picture showing two patterns (Oak Chest pattern at the left, Wooden Planks at the right) at the middle of the inventory (not sneaking)](https://user-images.githubusercontent.com/6565795/47261953-0598ef00-d50d-11e8-96fe-85c4d92cac6c.png)

A picture of the two patterns when sneaking:

![Picture of the two patterns when sneaking](https://user-images.githubusercontent.com/6565795/47261962-3b3dd800-d50d-11e8-9856-aa67142e004b.png)

**Comment by CrossVas** [comment]
But you still can craft them?
Seems to be a #609 duplicate.

**Comment by kenlauescuadro** [comment]
@CrossVas Yes, you can still craft the three chests I have mentioned.
