### ISSUE TITLE
Using the OpenComputer API to extract Forestry bees results in 'nil  "unknown error"'

### ISSUE THREAD

**Issue by Zantox** [raoulvdberge/refinedstorage#2049]
#### Issue description:
Using the OpenComputer API 'extractItem' command with forestry bees will result in an unknown error.
#### What happens:
OpenComputer monitor will just output 'nil  "unknown error"', and the interface that is supposed to output the item will not output anything.
#### What you expected to happen:
The interface should output the item, and the OpenComputer monitor should output the number of items outputted.
#### Steps to reproduce:
1. Set up a refinedstorage interface connected to a refinedstorage system with bees in them.
2. Connect an adapter to the interface
3. Use the "extractItem" function to extract a bee from the system into an inventory.

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12.2
- Forge: 14.23.5.2772
- Refined Storage: 1.6.8

Does this issue occur on a server? [yes/no]
This happened in singleplayer.
#### If a (crash)log is relevant for this issue, link it here:
No crash log, as the game did not crash.
[pastebin/gist/etc link here]

**Comment by Zantox** [comment]
https://pastebin.com/fG2Q0QPP

**Comment by raoulvdberge** [comment]
Should be fixed for the next version.

If you want to play around with the fix sooner, try the dev builds: https://jenkins.raoulvdberge.com/
