### ISSUE TITLE
Blocks Facing Wrong Direction

### ISSUE THREAD

**Issue by lilrichy** [raoulvdberge/refinedstorage#205]
Blocks like the importer and exporter face the player when shift clicking onto another block. To make it easier to set up they should face the block the player shift clicks, the same way hoppers work.

**Comment by raoulvdberge** [comment]
Which version are you running? I already removed this functionality in later versions

**Comment by raoulvdberge** [comment]
I don't know, I removed this functionality in later versions because it was annoying

**Comment by lilrichy** [comment]
Only some blocks need this like the importer and exporter for example other blocks like the solderer and grids should face the player when placed
