### ISSUE TITLE
[Server thread/WARN] and Crafter Fail inserting into Botania OpenCrate

### ISSUE THREAD

**Issue by OfficialStamper** [raoulvdberge/refinedstorage#2051]
#### Issue description:
Crafter inserting into _botania:opencrate_ gives the following warning in server log and autocraft stalls without completing:

`[Server thread/WARN] [com.raoulvdberge.refinedstorage.apiimpl.autocrafting.task.CraftingTask]: In a simulation, vazkii.botania.common.block.tile.TileSimpleInventory$SimpleItemStackHandler@5204242d reported that we could insert 1xitem.manaResource@1 but we got 1xitem.manaResource@1 as a remainder`

I appreciate the dev team have done a lot of work around the way autocrating works recently.  It used to be possible to autocraft into botania opencrates in previous versions, it would be great if this could be made possible again.

#### What happens:
(as above)

#### What you expected to happen:
Crafter inserts each ingredient into _botania:opencrate_ as per pattern recipe.

#### Steps to reproduce:
1. Create a crafting pattern for either botania petal apothecary, botania runic altar or botania agglomeration table
2. Place crafter to insert into botania:opencrate and insert crafting pattern into crafter
3. Order required item
...

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12.2
- Forge: forge-1.12.2-14.23.5.2768-universal
- Refined Storage: refinedstorage-1.6.7.jar

Does this issue occur on a server? [yes/no] yes

#### If a (crash)log is relevant for this issue, link it here:
`[Server thread/WARN] [com.raoulvdberge.refinedstorage.apiimpl.autocrafting.task.CraftingTask]: In a simulation, vazkii.botania.common.block.tile.TileSimpleInventory$SimpleItemStackHandler@5204242d reported that we could insert 1xitem.manaResource@1 but we got 1xitem.manaResource@1 as a remainder`

[pastebin/gist/etc link here]

**Comment by OfficialStamper** [comment]
No, just the one message

**Comment by raoulvdberge** [comment]
Can I see a screenshot of the pattern that is causing the problem? The inputs/outputs/etc.

**Comment by OfficialStamper** [comment]
Hope this works and helps...
https://imgur.com/zeWc0d3

**Comment by raoulvdberge** [comment]
Blocking is in again, with the crafter redstone mode. 

https://refinedstorage.raoulvdberge.com/wiki/locking-and-unlocking

**Comment by OfficialStamper** [comment]
Yes thanks, I have been trying it out.  Complicated redstone required, but works well otherwise.  I have been using ComputerCraft turtles as the crafter receivers, which can easily return the redstone pulse required for the next recipe items.  I would welcome your thoughts on how you intended it to work.  BTW I had already read your wiki page, which helped a lot.  Great work :)

**Comment by raoulvdberge** [comment]
Thx!

Can you reproduce your problem 100% of the time?

**Comment by OfficialStamper** [comment]
Yes.  Any recipe that attempts to insert more than one item into a botania:opencrate produces the problem (unless the recipe only consists of one item).

**Comment by raoulvdberge** [comment]
I know what causes this. I am working on a fix.

**Comment by jamesfoster** [comment]
I'm having a similar issue: I'm on RS v1.6.5 and attempting to insert a recipe into a machine with a single inventory slot. I would expect each different item stack in the recipe to be inserted one at a time (due to lack of space) but instead the recipe aborts. It also kills the RS subnet the crafter is attached to and I need to reconnect it.

**Comment by tyler489** [comment]
This is because vaskiis open hopper says it can take the item but doesnt have an inventory

**Comment by jamesfoster** [comment]
@raoulvdberge Doesn't seem ideal to void items. is it possible to only remove items from storage if they will fit in the destination inventory. Or return to storage anything that wouldn't fit?

**Comment by raoulvdberge** [comment]
It doesn't void items. Please don't make these uninformed comments if you don't understand the code.
