### ISSUE TITLE
Duplication Glitch with Pattern Grid

### ISSUE THREAD

**Issue by cowslayer7890** [raoulvdberge/refinedstorage#2052]
#### Issue description:
You can duplicate any stackable item you have with a pattern grid
#### What happens:
if the grid is in processing mode and you put items into input or output, double-clicking with a stackable item of the same type will take items out of the pattern grid slots and into the hand of the user
#### What you expected to happen:
either the items in the grid disappear or they stay where they are instead
#### Steps to reproduce:
1. Place down a pattern grid, connected or disconnected from a system.
2. Put the grid in processing mode
3. Put any stackable item into one of the open slots
4. In your actual inventory, double-click on the same type of item to see it take items from the pattern grid and fill it up to a stack
...

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12.2
- Forge: 14.23.4.2760
- Refined Storage: 1.6.4

Does this issue occur on a server? yes

#### If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here]

**Comment by raoulvdberge** [comment]
"(make sure you are on the latest version before reporting):"

Can you reproduce this on  1.6.8?
