### ISSUE TITLE
Extracting Certain Items Breaking Most World Interactions

### ISSUE THREAD

**Issue by ConnorMiner** [raoulvdberge/refinedstorage#2055]
#### Issue description:
Whenever extracting all of certain items from storage, the items do not appear on the cursor or in the inventory, and almost nothing works correctly. (When some of the items are extracted, all the other items are deleted.)

#### What happens:
After the items fail to appear where they should, anything with a GUI (except some inventory items for whatever reason, though actually doing anything through it doesn't work properly) fails to work properly, and the inventory goes into stasis. Normal world objects behave as though nothing is wrong, however. Killing the player (e.g. /kill) results in a server-side crash.

#### What you expected to happen:
The items to go into the inventory as intended.

#### Steps to reproduce:
1. Auto-craft the item in question (or insert it).
2. Pull all the instances of the item out of storage.
3. The player becomes completely glitched.

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12.2
- Forge: 14.23.5.2768
- Refined Storage: 1.6.8

Does this issue occur on a server? [Probably]

#### Extra Notes:

This issue occurred whilst playing the StoneBlock modpack with ChickenChunks added in.

#### If a (crash)log is relevant for this issue, link it here:

World: https://drive.google.com/file/d/1kEDtGIMrz6UFhpExpxm0q3yp66pghqSC/view?usp=sharing
Example Video: https://drive.google.com/file/d/1QBcdVg01ZgTTRw0exiQtjkUpWCp7EJlL/view?usp=sharing
Crashlog after /kill: [crash-2018-10-25_14.40.04-server.txt](https://github.com/raoulvdberge/refinedstorage/files/2517007/crash-2018-10-25_14.40.04-server.txt)

**Comment by ConnorMiner** [comment]
I just found out that a Drawer Controller connected through an Actually Additions Item Laser Network was a part of the issue.

**Comment by raoulvdberge** [comment]
Are you able to test dev builds? There is something I want to try.

Also, can you reproduce the issue 100% of the time?
