### ISSUE TITLE
Autocrafting with philosophers stone from Project E

### ISSUE THREAD

**Issue by IrationalReticulatingAugment** [raoulvdberge/refinedstorage#2056]
#### Issue description:
Previously, it was possible to 'force start' an autocraft that contained more than one recipe using the philo stone, which would cause the autocrafter to complain about "missing" a philo stone. 

#### What happens:
The "force start" option seems to have been removed in 1.6.6.

#### What you expected to happen:
I expected RS autocrafting to not require multiple philo stones, or to let me tell it that I understand it's missing a catalyst and to just start anyway.

#### Steps to reproduce:
1. Setup autocrafting for multiple philo stone recipes (here I'm crafting 4x coal 1x Philo -> Alchemical Coal, and then 4x Alchemical Coal 1x philo -> Mobius Fuel for nova catalyst TNT)
2. https://i.imgur.com/R0Oh3fF.png

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12.2
- Forge: 14.23.5.2768
- Refined Storage: 1.6.8

Does this issue occur on a server? 
It occurs in a LAN world, I can't test a proper server.

**Comment by raoulvdberge** [comment]
RS no longer handles reusable tools or missing items.
