### ISSUE TITLE
Everything (except the Controller and some blocks) doesn't work upon opening up the world save file

### ISSUE THREAD

**Issue by kenlauescuadro** [raoulvdberge/refinedstorage#2059]
#### Issue description:
Every block, except some, from Refined Storage doesn't work even though the Controller is right besides them (grids, disk manipulators, wireless transmitters, all that stuff). This issue randomly showed up and I don't think it can't be fixed with removing placed blocks or the like.

#### What happens:
Upon opening a world with the Refined Storage mod:
- Everything except the Controller and the Wireless Transmitter doesn't work. In fact, they don't seem to get power too, even though the Controller consumes Crystal Flux (also Redstone Flux and Tesla). A way to fix this is destroy the controller and place it again.
- Disk Drives are always not reading the disks in them, even though there are disks inside them. The only way to fix this is manually remove the disks from their respective drives and put it back in.
- Grids (Normal, Crafting, Fluid) don't show anything and just shows black squares instead of squares that have items inside them.
- Wireless Transmitters work as if it doesn't have range upgrades even though it has. It, also, only shows external storages and crafters' recipes (This happens because there's no disks being read, but even if you fixed the disks, it will still show external storages and crafters' recipes.)

#### What you expected to happen:
Upon opening a world with the Refined Storage mod:
- Everything works.
- Disk drives read the disks inside them.
- Every block functions.
- Wireless Transmitters "act correctly" and shows all items in the disks.

#### Steps to reproduce:
1.
2.
3.
4. I have no idea.

I really have no idea. It just happened and I don't know what causes it.

Because of that, I made a downloadable copy of my world so that you can see what needs to be fixed (even though it might not be that helpful).

Also, I just want to say: The map's size is almost 250 MB. Maybe consider downloading first because you might not specifically and really fix the problem with only a map as a reference? Maybe? Just wanted to say that.

[Download the map](http://www.mediafire.com/file/a21kbr7c0cpmtqj/some_world.zip/file)

#### Version (make sure you are on the latest version before reporting):
- Minecraft: 1.12.2
- Forge: 14.23.5.2768
- Refined Storage: 1.6.9

**Comment by raoulvdberge** [comment]
I'm sorry, I really need reproduction steps.

250mb is a bit rough on my connection, and, I don't even have the set of mods you have.

Closing this as I expect a bit more effort (minimal reproduction case, does it happen with just RS installed, etc.)
