### ISSUE TITLE
Massive search lag with external storage

### ISSUE THREAD

**Issue by iAreEddie** [raoulvdberge/refinedstorage#2062]
#### Issue description:

When '@' searching for mod specific items there is immense lag, to the point of crashing, if you have an external storage system set up. I am playing on StoneBlock modpack if that is relevant info.

#### What happens:

The game drops from 70-100 fps to 0-1 fps (or less) and crashes 1/2 the time

#### What you expected to happen:

Some fps drop while crafting/in inventory is normal in Minecraft Java from what I can tell, but not this much 

#### Steps to reproduce:
1. Have an external storage (item specifically, fluids do not seem to create the same issue) set up to any storage system (Storage drawers, quantum storage, crate etc)
2. Open crafting grid, wireless or not
3. Use Refined storage search bar to @ search (JEI synchronization on/off doesn't matter)

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12.2
- Forge: 14.23.5.2768
- Refined Storage: 1.6.9 (Updated after posting this thread, still having issue)

Does this issue occur on a server? 

Not sure, I am playing single-player though

#### If a (crash)log is relevant for this issue, link it here:  

This is the last two entries before the crash; block at x=-662, y=124, z=-996 was an external storage hooked up to a quantum storage.

https://pastebin.com/2edJfRjn

**Comment by iAreEddie** [comment]
NVM didn't realize there was the 1.6.9 update. Issue was resolved by updating mod....

**Comment by raoulvdberge** [comment]
That doesn't make much sense, I didn't change anything related to that.

**Comment by iAreEddie** [comment]
Someone responded to me on reddit saying that updating it would fix the problem.. I updated it and you were right, it didn't fix the issue..

**Comment by raoulvdberge** [comment]
https://refinedstorage.raoulvdberge.com/wiki/profiling

**Comment by iAreEddie** [comment]
The first was ran with /sampler
This one was /csampler
http://www.filedropper.com/refinedstoragetestcsampler

**Comment by gantz123** [comment]
I'm having the same issue, once I disconnect the line going to my Quantum Storage chest everything is fine.

**Comment by raoulvdberge** [comment]
@gantz123 This is about searching with @ (mod search). Are you talking about the same thing?

**Comment by iAreEddie** [comment]
This may be relevant, I didn't realize I had 2 external storages connected to the same quantum storage (top and back,) with the same settings, (priority 10 with only cobblestone whitelisted.) Removing one stopped the crashes, but fps still drops from 70-100 to 3-5 fps.

**Comment by gantz123** [comment]
I figured out what was causing it, for me at least. I had a exporter and a external storage hooked up to a Quantum Storage Unit, once I took the exporter off I haven't had the issue. Originally I kept the exporter on because it wouldn't put the item in thru the external storage connector but then I realized that it's set to blacklist by default.

**Comment by OfficialStamper** [comment]
um, connecting an exporter and also external storage to the same storage will create an infinite loop.  Why would you do that?  The exporter is constantly exporting from your quantum storage and the remote storage is putting it back in again.......doh

**Comment by OfficialStamper** [comment]
um, connecting an exporter and remote storage to the same storage unit will create an infinite loop.  The exporter will request the same item from the remote storage only to insert the item straight back in the quantum storage unit. Rinse and repeat.

**Comment by raoulvdberge** [comment]
Yes ok but that loop doesn't cause problems when using @

**Comment by raoulvdberge** [comment]
This has been fixed!
