### ISSUE TITLE
Mekanism: Solar Generator not craftable

### ISSUE THREAD

**Issue by Kratzwurst** [raoulvdberge/refinedstorage#2064]
hello

Recipes with the energy tablet from mekanism can't be craftable automatically.
On the cafting preview locks the tablet at as full storage with energy.
I figured out with oredict and without, same problem

https://imgur.com/a/cgUnvF4

#### What happens:

The Tablet was not found correctly

#### Steps to reproduce:

1. I ceate a recipe with JEI and no work
2. I create a recipe manually don't work
3. I create a recipe with oredict that's be also don't work.

- Modpack StoneBlock 1.0.25 (Dev was informed)
- Minecraft:1.12.2
- Forge:14.2.5.2768
- Refined Storage: 1.6.8

Does this issue occur on a server? [yes/no] yes

**Comment by Kratzwurst** [comment]
Notice: I turned off all my wireless charging things and capacitors.

**Comment by Darkere** [comment]
Mekanism Items have an additional NBT tag once they are created. This means that when RS pulls the Recipe via JEI it does not match the actual item. You can circumvent this by manually overwriting the item in the recipe.

I think Raoul is still trying to figure out a good way to do this kind of stuff better.

**Comment by raoulvdberge** [comment]
I'm not, this is on mekanism to fix.

**Comment by thiakil** [comment]
@raoulvdberge the recipe itself is not NBT-sensitive (in the sense it doesn't care what the NBT is / is a standard `Ingredient`), but the tablet *can* have nbt (and this is used to modify the output NBT).

What exactly are you expecting us to do?

**Comment by raoulvdberge** [comment]
Not to assign tags when nothing is done with the tablet (aka not assigning tags when it is just sitting in your inventory, newly crafted).

**Comment by thiakil** [comment]
So you don't care about the case where someone might want it to use a partially charged tablet?
