### ISSUE TITLE
Crashes when loading into game

### ISSUE THREAD

**Issue by kenshin2666** [raoulvdberge/refinedstorage#2065]
#### Issue description:
After selecting my world, when I load into the game my FPS tanks and the game freezes before crashing.
#### What happens:
When I load in to my world in StoneBlock (https://github.com/Sunekaer/stoneBlock/issues/503) my FPS tanks down to about 9 before the game locks up and crashes.
#### What you expected to happen:
Game to load and progress normally.
#### Steps to reproduce:

1. Select game world
2. Allow to load
3. Attempt to move
4. Crash

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12.2 (modded)
- Forge: forge-14.23.5.2768
- Refined Storage: refinedstorage-1.6.8.jar

Does this issue occur on a server? [yes/no]
No
#### If a (crash)log is relevant for this issue, link it here:
https://gist.github.com/kenshin2666/a470d6c247c7a0db22f088be79151399
[pastebin/gist/etc link here]

**Comment by raoulvdberge** [comment]
Seems like you have a corrupt crafting task. You'll have to remove your controller (through MCEdit or something else...)

**Comment by kenshin2666** [comment]
I'm not sure if this information has to do with what is causing this issue or if its something else entirely but I started to transfer my items from the RS storage over to AE2 and whenever I step in to the area, my FPS drops to 1 from my 100+ elsewhere.

https://gist.github.com/kenshin2666/19ba940bef878dbc29af3c678f04ff99
![mc1](https://user-images.githubusercontent.com/44624535/47957042-74525f80-df85-11e8-9b44-5e8fdd6c0ca5.png)
![mc2](https://user-images.githubusercontent.com/44624535/47957043-74525f80-df85-11e8-8df2-1b161d2adb1c.png)

**Comment by VallenFrostweaver** [comment]
I'm having a similar issue where a crafting task appears to be causing the issue (though sadly I don't have a location to go on so I have to revert to a previous save). This is StoneBlock v1.0.25 Refined Storage v1.6.8 Addons v0.4.2  
Pastebin here: https://pastebin.com/bBZZmcg7

The server runs fine until a player logs in and loads an area then the server crashes.

**Comment by VallenFrostweaver** [comment]
Will do. Ran outta time. I will later.

**Comment by raoulvdberge** [comment]
Closing as I don't have enough reproduction steps
