### ISSUE TITLE
Exporter w/ Crafting card disrupts crafting queue

### ISSUE THREAD

**Issue by Scors4** [raoulvdberge/refinedstorage#207]
When autocrafting the processors for this mod, I've noticed that occasionally the crafting queue gets stuck trying to build one. (Autocrafting a 64k storage part for a disk).  I've narrowed it down to the export bus requesting silicon while the processor is being built, causing the system to miss when the processor itself is finished and imported.
Minor thing, but I'd figure I'd say something anyway.

**Comment by raoulvdberge** [comment]
already fixed
