### ISSUE TITLE
Mystical Aggriculture essence recepies spam make infusion crystals with 1000 uses, only uses them once before making new ones.

### ISSUE THREAD

**Issue by Runisco** [raoulvdberge/refinedstorage#2074]
#### Issue description:
Combining essence creation from mystical aggriculture, which requires a crystal to transform between tiers, means that even though the crystal has 1000 uses, the storage system will create one for each, leaving each on 999 uses, whilst tying to make more
#### Steps to reproduce:
1. Using a refined storage system, create a recipie for an infusion crystal
2. Make recepies for the essences
3. Try to make 10 essences of tier 2. The storage system will want to create 10 crystals, even though it would only need 1 before for each tier.
...

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12.2
- Forge: 14.23.5
- Refined Storage: 1.6.9

Does this issue occur on a server? [yes/no]
No

**Comment by raoulvdberge** [comment]
Intended

**Comment by Simplycabe** [comment]
Why is this intended?
