### ISSUE TITLE
Server crash when "+" from JEI to Crafting Grid on some items (one recipe found in my case)

### ISSUE THREAD

**Issue by bugreporter0** [raoulvdberge/refinedstorage#2075]
#### Issue description:
Server crash when trying to use "+" sign on some recipes.

#38 is very same issue from 2 years ago. 

#### What happens:
Server crash. 

#### What you expected to happen:
No crash.

#### Steps to reproduce:
1. Click + on some recipes when having crafting terminal opened. Decently sized network, big modpack. One recipe that 100% reproduced the issue was Botania's lexica botania book.

...

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12.2
- Forge: 2772
- Refined Storage: 1.6.9

Does this issue occur on a server? [yes/no]
Yes
#### If a (crash)log is relevant for this issue, link it here:

https://gist.github.com/bugreporter0/6238629d8b128afe999812b9e1c5bf61

**Comment by raoulvdberge** [comment]
Don't create duplicate issues!

#1790

**Comment by bugreporter0** [comment]
Whoops. Sorry! only found #38 which was already closed.
