### ISSUE TITLE
exporter exporting random items

### ISSUE THREAD

**Issue by tntxdirtnasty** [raoulvdberge/refinedstorage#2077]
#### Issue description:
Using QSUs to store items i have a ton of and the exporter is exporting random items, also i am on the pack StoneBlock
#### What happens:
trying to store iron and other items, it exports everything in the inventory even with the exporter filtered
#### What you expected to happen:
just want iron to go into the QSU
#### Steps to reproduce:
1. dont know, maybe have a large bank qsu's and try to store items in them i will attach a video showing what is going on

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12.2
- Forge: 14.23.5.2768
- Refined Storage:1.6.9 
-refined storage addons 0.4.3

Does this issue occur on a server? [yes/no]
not sure
#### If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here]

https://youtu.be/5RPTYylrq5E

**Comment by raoulvdberge** [comment]
those aren't exporters, those are external storages

**Comment by tntxdirtnasty** [comment]
I’m aware I have both an exporter and a external storage unit to export items that are produced to the QSU

**Comment by raoulvdberge** [comment]
did you filter the external storages too?

**Comment by tntxdirtnasty** [comment]
Looks like changing it from blacklist to whitelist fixed it. but when you place down the external storage it starts as blacklist.

**Comment by tntxdirtnasty** [comment]
i can still send the screen shots if you still want them

**Comment by raoulvdberge** [comment]
it's fine
