### ISSUE TITLE
Missing items badly positionned in crafting preview GUI

### ISSUE THREAD

**Issue by Ant95** [raoulvdberge/refinedstorage#2078]
#### Issue description:
A picture explains it better than any word:
![Screenshot](https://image.ibb.co/c70tdV/Minecraft.png)

#### Steps to reproduce:
Try to craft something without having the required items

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12.2
- Forge: 14.23.4.2739
- Refined Storage: 1.6.9 (also tested with 1.6.5)

Does this issue occur on a server? Yes

**Comment by raoulvdberge** [comment]
Update your texture pack.
