### ISSUE TITLE
[1.12.2-1.6.8] Server crash when right clicking 256k fluid blocks

### ISSUE THREAD

**Issue by kreezxil** [raoulvdberge/refinedstorage#2082]
#### Issue description:
Server crash when right clicking 256k fluid blocks

#### What happens:
Dedicated server crashes

#### What you expected to happen:
to not crash

#### Steps to reproduce:
1. place 256k fluid block
2. right click while holding any item
3. enjoy the dedicated server crash

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12.2
- Forge: 14.23.5.2770
- Refined Storage: 1.6.8

Does this issue occur on a server? [yes/no]
yes

#### If a (crash)log is relevant for this issue, link it here:
http://paste.ubuntu.com/p/45bnVDrg28/
http://paste.ubuntu.com/p/YZt6ZVjHvK/

**Comment by raoulvdberge** [comment]
That shouldn't be possible. Did you mess with your refinedstorage_nodes.dat file?

**Comment by raoulvdberge** [comment]
How are you placing the fluid storage block?

**Comment by raoulvdberge** [comment]
Can you reproduce this 100% of the time?

**Comment by kreezxil** [comment]
you would have to ask the FTB: Sky Adventures team if they modified that, because I did not touch it one bit.

**Comment by kreezxil** [comment]
and yes I was doing it 100% of the time, if you want to see it for yourself open up FTB: sky adventures latest version and enjoy crashing a dedicated server.

**Comment by Darkere** [comment]
Can not confirm. Installed FTB Skyadventures and placed down a 256k Fluidstorage Block. Rightclicking it does not crash. Neither does powering it, inserting a fluid and then rightclicking.

**Comment by raoulvdberge** [comment]
Did you try running it as a server @Darkere  ?

**Comment by raoulvdberge** [comment]
This has been fixed in 5bc750812e210a3ad0faae893ab66cf3191e8bda
