### ISSUE TITLE
Suggestion: More Compat+ Spatial Storage

### ISSUE THREAD

**Issue by CTH999** [raoulvdberge/refinedstorage#2083]
So, I personally like this mod a bit more than Ae2 (It actually get's updated...), but, I do have a few ideas, and a few ideas on how to do said Ideas!

One thing I would like is a way to store EMC from equivalent exchange, essential from thaumcraft, mana from botania… However, you don't have those disks. I came up with three (Logical) ideas

1. You Addition- This idea is that you could make the disks in this mod. You install thamcraft, then the essential disk appears, botania, same thing. Problem is, that would make it _Your_ job to update it. That could be good, or bad.
2. API- This idea is that instead, you put an API in. That way, if a mod author wants a energy-storage disk, they can just use this API to add it in, with all their features. I think this could be more helpful, since other modders could easily add in discs
3. The combo idea- this one is the more useful one. In this one, the API is there, but you also have a few discks (Maybe thaumcraft) That way, it's there as an example, and, for instance, since thamcraft is a magic mod, I could see him (Aznonor) Not wanting to use the API. Now it has the disk, and he doesn't need the API, _And_ it's an example!

Now, There is one feature of Ae2 that I wish was in this mod. That's the spatial storage cells. So, my suggestion, is add those in. Kinda

For instance, instead of making it use a pylon, maybe a single block that you adjust the range of
And, maybe the system for extracting said disk is more automatable

However, the one feature of it that (I think) you should keep, is making it to where it's designed for you to go inside! that way, you can make a base, in a single item! Then, using teleporters, teleport in, holding the bases's disk... (Try wrapping your head around _That_! The base is inside of the base, stored within it's self...)

And, there are a few more ideas for this one that I forgot, so, it might be back with more!

However, It's just a suggestion. Since it's your mod, it's your choice!

Sincerely, CTH2004

**Comment by raoulvdberge** [comment]
1) RS already has an API.
2) No, not adding spatial storage.
