### ISSUE TITLE
Searching "#" causes game to crash

### ISSUE THREAD

**Issue by Ravalli03** [raoulvdberge/refinedstorage#2085]
#### Issue description:
Game crashes as soon as I type "#" to search enchanted books. It was working fine when I had a system with less then 1000 items, but have moved my enchanted books into main system with over 1mil items.

#### What happens:
Game crashes to desktop. I have tried 3 times and same result.

#### What you expected to happen:
Search enchanted books 

#### Steps to reproduce:
1. Open Crafting grid
2. Type "#"
3. Game crashes

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12.2
- Forge: 14.23.5.2770
- Refined Storage: 1.6.9

Does this issue occur on a server? [yes/no] no

#### If a (crash)log is relevant for this issue, link it here:

Does not create a crash log. 

[pastebin/gist/etc link here]

**Comment by raoulvdberge** [comment]
First of all, the item count doesn't matter.

Secondly, I need a crash report. Did you search good enough?

**Comment by Ravalli03** [comment]
It didn't create a crash log , as I don't even have a folder, will a normal log file work?

**Comment by Ravalli03** [comment]
Actually let me reexplain it, the game is not crashing, it's stops responding as soon as I press #, and then I go to the task manger to end task ie why I don't have a crash log. Sorry for not explaining it right. I have let it sit for 5 min. and the game still does not respond.

I have removed the storage disk with about 700k (reborn storage) of items and search it on a RS system with nothing connected, ie imports/exports/external etc and it works fine. 

The only time I have issues are when trying to do the same search on my main system with everything connected. Hope this helps.

**Comment by gp3t1** [comment]
I have exactly the same problem on stoneblock 1.0.27r2 (solo).
    Minecraft: 1.12.2
    Forge: 14.23.5.2768
    Refined Storage: 1.6.9
    (Refined storage addons: 0.4.3)
    (Reborn storage: 1.12.2-3.2.2.65)

My crafting grids are synchronized with jei. When i log back after the crash, i can see that the character '#' is present in the JEI search bar but not in the crafting grid search bar.

**Comment by Ravalli03** [comment]
I just tested it on my main system with JEI not synced (normal mode), and still get the crash/not responding.

**Comment by gp3t1** [comment]
I also realized that my recipes with enchanted books as ingredients don't work anymore. The crafting GUI tells me i don't have the books but i can see them in the grid.

**Comment by raoulvdberge** [comment]
Which recipes? What do you mean "don't have the books"? It doesn't autofill from JEI or something?

**Comment by Ravalli03** [comment]
Thank you sir
