### ISSUE TITLE
Refined Storage System Won't Export Completely To Black Hole Controller

### ISSUE THREAD

**Issue by Brittank88** [raoulvdberge/refinedstorage#2087]
#### Issue description:
Note: To make things easier I'll focus on one of the items this occurs with (cobblestone).
My refined storage system won't export all of the currently stored cobblestone stored within its disk drives.

- The system contains 1.7 million cobblestone:
![2018-11-14_06 42 45](https://user-images.githubusercontent.com/24266948/48438636-84194180-e7d8-11e8-9d2a-32689e003544.png)
- I have attached a black hole controller unit from Industrial Foregoing as external storage.
- The external storage unit is configured correctly, and cobblestone does flow in (however the issue lies with when the flow stops, which I'll describe below).

#### What happens:
- The cobblestone count inside of the black hole controller stops at approximately just over 1 million items:
![2018-11-14_06 28 25](https://user-images.githubusercontent.com/24266948/48438671-90050380-e7d8-11e8-99d9-50361de12887.png)
- I notice that the external storage device reads the black hole controller as "1,024,902 / 576" or "177934% full":
![2018-11-14_06 41 21](https://user-images.githubusercontent.com/24266948/48438731-b6c33a00-e7d8-11e8-86cb-cf75f2f024fe.png)

#### What you expected to happen:
- I expected all 1.7 million of my cobblestone to be placed within the black hole controller.
- I expected the external storage unit to read the actual storage space of items based on the black hole units present and the orange row beneath them which stores one stack per slot (I understand this responsibility may lie with the developer of Industrial Foregoing and not you, depending on where the root cause of this lies).

#### Steps to reproduce:
1. Set up a basic refined storage system with enough 64k item drives connected to store millions of cobblestone.
2. Place a black hole controller and fill each of its appropriate slots with a black hole unit.
3. Connect the controller to the refined storage system via an external storage device.
4. Enter cobblestone into the eternal storage device filter.
5. Allow the system some time to finish inserting cobblestone into the unit.
6. Hold shift and hover over the first black hole unit and notice that the value of items stored is less than the original value of items stored in the refined storage system.

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12.2
- Forge: forge-1.12.2-14.23.5.2768
- Refined Storage: 1.6.8
I'm aware this is one version behind latest but I still wish to submit this report as the chances are this issue hasn't been brought to your attention / resolved yet - there isn't a single previously reported issue even relating to the the mod the black hole controller is a part of (Industrial Foregoing), let alone the issue with exporting items to a black hole controller itself.

Does this issue occur on a server? [yes/no]
Yes, though I believe this also occurs in singleplayer.

#### If a (crash)log is relevant for this issue, link it here:
No crash occurs, just unwanted behavior.

#### Final notes:
Thank you for your time. If this turns out to be an issue that I must take up with the developer/s of Industrial Foregoing, I'm sorry for wasting your time and grateful for your patience. I'm just not sure if this is something that refined storage can be made to support correctly, or if the issue must be fixed by the creators of the black hole controller, and so would rather cover all bases, so to speak.

**Comment by Brittank88** [comment]
Update: This is actually also occurring with the exporter device and machines with more basic internal storage. As you can see:
- There's 2.7 million coal in the system:
![2018-11-14_07 13 28](https://user-images.githubusercontent.com/24266948/48440377-e7a56e00-e7dc-11e8-8a67-e201034114f3.png)

- There's not even a full stack (and different amounts) in each of the 2 generators I'm exporting to:
![2018-11-14_07 13 38](https://user-images.githubusercontent.com/24266948/48440415-fa1fa780-e7dc-11e8-84e5-7accc783a4b1.png)
![2018-11-14_07 13 43](https://user-images.githubusercontent.com/24266948/48440417-fbe96b00-e7dc-11e8-861a-65ed65c3756c.png)

However, the exporters are set up identically, each with one stack upgrade and three speed upgrades, and coal entered into the filter.

**Comment by raoulvdberge** [comment]
How are you exporting cobble from your RS system to the black hole thing?

Also, the stack upgrade will only insert when the inventory is empty again, as it has no space for a full stack.

**Comment by Brittank88** [comment]
Ah, thanks for helping me out with the stack upgrades. That's fixed the coal issue, though the original cobble issue is still present.

I'm exporting cobble from my RS system using an external storage device:
![2018-11-14_07 20 42](https://user-images.githubusercontent.com/24266948/48440743-cf821e80-e7dd-11e8-98df-e162d8427235.png)
![2018-11-14_07 20 57](https://user-images.githubusercontent.com/24266948/48440753-d741c300-e7dd-11e8-971b-4747489f31c2.png)

**Comment by raoulvdberge** [comment]
I believe there is a misunderstanding here. The external storage doesn't export anything, it will merely act as a storage device and only route new items into there. It doesn't do any active exporting of existing items. Use a disk manipulator for that.

**Comment by Brittank88** [comment]
Man, if I've been making a huge mistake the whole time I'm sorry for wasting your time. I'll check if that works and come back to you so we can see if this issue can be closed or not.

Regardless though, reading 1 million out of just over 500 items is a bit of an anomaly, but I guess that's just a visual thing.

**Comment by raoulvdberge** [comment]
It's just a visual thing.

**Comment by Brittank88** [comment]
Apologies, just one last question; is a disk manipulator the only way to do this? I have 168 64k drives, it might take a while.

Thanks!

**Comment by raoulvdberge** [comment]
No problem! Happy to help.

**Comment by Brittank88** [comment]
Sorry man, it turns out the exporter _isn't_ working; it just stopped. Even with just speed upgrades and no stack upgrade, the item flow is static. Is there a reason for this or is this truly a bug?

**Comment by raoulvdberge** [comment]
It's because you're creating a loop. The exporter will start exporting from the external storage inventory, which will make items export into themselves. Disconnect the external storage from the network and reconnect when the exporting is finished.

**Comment by Brittank88** [comment]
I replaced the external storage with the exporter though.

**Comment by Brittank88** [comment]
Okay, now the exporter just isn't exporting into any storage at all, not even a basic chest.

**Comment by raoulvdberge** [comment]
Make sure the exporter is actually connected to the network, and cobblestone is specified in it's exporting configuration.

**Comment by Brittank88** [comment]
Done and done, not sure why this isn't working.

**Comment by Brittank88** [comment]
Nevermind, somehow in an instant there's no cobblestone in the system at all.

**Comment by Brittank88** [comment]
Okay, there's 1.1 million granite in the system and the exporter is moving none of it into the controller for that item. I've tested it with a normal chest too and it won't export it there either.

Sorry for constantly coming back, this is really strange to me.

**Comment by Brittank88** [comment]
Breaking a single disk drive and replacing the 64k storage units in it with fresh ones has caused the anomalous items to disappear. Not sure if this fix is permanent, but I'll see how it goes. I think the system is having trouble working with all 168 64k drives and as a result is exhibiting odd behaviour.
