### ISSUE TITLE
Grid does not update Patterns without opening and closing it.

### ISSUE THREAD

**Issue by Darkere** [raoulvdberge/refinedstorage#2088]
#### Issue description:
When a grid is open and a pattern is inserted (via automation) it is necessary to close and reopen the grid to be able to see it.

#### Steps to reproduce:
1. Create a hopper line that inserts into a crafter.
2. Insert a pattern into the hopper and wait for the pattern to appear in the grid.
3.
...

#### Version (make sure you are on the latest version before reporting):

- Minecraft:1.12
- Forge:2772
- Refined Storage:1.6.9

#### Extra Info
IIRC inserting patterns via automation should not be possible because of security? 
It would be nice to see this fixed regardless as the Reborn Storage Multiblock does have the ability for insertion via automation.

**Comment by raoulvdberge** [comment]
This is really minor and doesn't really matter.

**Comment by Darkere** [comment]
It allows for a really nice setup where instead of searching for a recipe, making the pattern, inserting the pattern and then searching for the item again, you can instead throw the item on the ground, have it collected and inserted via automation. 

It saves on typing out the search twice. (I know about the history feature but the down button is nowhere close to where my hands are when playing..).
