### ISSUE TITLE
[Issue] While leaving chunkloaded chunk part of network disconnects

### ISSUE THREAD

**Issue by Moustik2002** [raoulvdberge/refinedstorage#209]
Hi, 
It's a little pain in the ass to describe my problem. when i leave my session or move to another place and left my chunkloaded base, when i come back some time to time i've encountered some parts of my network disconnected.

At first thougt i was thinking about interaction between EnderIo conduits and RS cables, but i'm not sure( interraction with Redston Signal ?)

here is a screen of what i'm talking about :

Normal behavior : 
http://puu.sh/q7hzk/8708f5162f.jpg

When i come back : (look at the crafters)
http://puu.sh/q7hSe/b54a268e16.jpg

**Comment by raoulvdberge** [comment]
Is the chunk with the crafters chunkloaded?

**Comment by Moustik2002** [comment]
yes it is, i've a 7x7 chunkloader

**Comment by q009** [comment]
I can confirm, happens here as well

**Comment by Moustik2002** [comment]
hopefully since the last update, issue seems to be old story. do you tried to update q009 ?

**Comment by q009** [comment]
No, I'm afraid I have no way of trying the update myself right now, I'm gonna have to wait.

**Comment by BootyToast** [comment]
I found out what causes this. I went weeks with no problems but as soon as I connected a second external storage to my system and left the area, my main storage disconnected. It's like it tries to decide which storage to prioritize and then just fails completely.

**Comment by raoulvdberge** [comment]
@BootyToast Have you got any error logs when this happened?

**Comment by BootyToast** [comment]
There are no error logs and I can't seem to reproduce it at all. It's just every so often I'll come around and the items in my system confuse me until I realize everything I have connected to External Storage isn't connected. Breaking and replacing the controller fixes the issue. Weird!

**Comment by raoulvdberge** [comment]
Maybe the tile entity doesn't send an update packet (where it says the machine is connected, so the client knows) when you enter a loaded chunk...

If the controller says the block is connected in its GUI, but the block itself is in a disconnected state, then that would be the cause.

**Comment by BootyToast** [comment]
Hmm, yeah. I'm still not sure. I have been getting some crashes with storage drawers so obviously something isn't right!

**Comment by raoulvdberge** [comment]
Did you report it to the Storage Drawers dev or is it an RS fault according to the log?

**Comment by BootyToast** [comment]
Every now and again I get a tesselating block model crash and other people seem to have that problem as well. Might as well hold out to see if the storage disconnecting has to do with the drawers specifically. Seeing as this is very rare, I'll just make sure to keep an eye out and look at everything else connected to my system next time!

**Comment by raoulvdberge** [comment]
Yes... I heard about that crash before. The author of SD took a look at my integration code and couldn't find anything special, so it might really be an SD issue.

Although the latest commit in his repository seems to have fixed a "rare render crash", so I don't know.

**Comment by Utildayael** [comment]
Same issue as Booty. Seems to follow chunk lines. I had at one point a importer working and a grid literally 1 block over but it was on other side of chunk so... no worky. Every time I log in to the server at least half of my base doesn't seem to work anymore. The area around the controller seems to always be fine but it goes out to lunch as you get away from that.... sometimes randomly. I've had two grids equi-distance from the controller and one works, one doesn't... different chunks tho so definitely a chunk-related issue.

**Comment by Moustik2002** [comment]
I've no longer this issue since i use PersistentBit Chunkloading instead of ExtraUtilities one. However use the 1.0.2 version, the ones above and below are impacting RS network.

**Comment by raoulvdberge** [comment]
Does the controller list the "unconnected" machine in its GUI?

**Comment by Utildayael** [comment]
It does not. It's like it doesn't exist as far as refined storage is concerned.

**Comment by raoulvdberge** [comment]
Are you 100% sure? My question is very crucial as then I know if its a client side or server side bug.

**Comment by Moustik2002** [comment]
from what i've encountered it happens on server. And like i told earlier you can simulate this issue using Persistent bit, version 1.0.2 works like a charm above and below reproduce the problem.

**Comment by oitsjustjose** [comment]
I'll look into it when I'm not at work, but I don't believe I changed a single thing about the actual chunk loading mechanics in quite a while.

On my server I'm having no problems with Persistent Bits and Refined Storage. I come and go, disconnect and reconnect, travel to RFTools Dimensions, and have never had a single problem with my network. At this point my network has one of every single block / utility that Refined Storage adds...

**Comment by Utildayael** [comment]
I will double check tonight. 99% sure. :)

**Comment by Utildayael** [comment]
Well so as luck would have it, server crashed so can't test on the MP world. Did however make a new SP world and ran some tests.

I made a controller with a grid and a disk drive. Tossed some items in. Ran cables in all 4 cardinal directions putting 1 grid on the wire in the center of each chunk. Once I placed my 10th grid, it stopped working. Went back to the controller and saw it still said "10 grids" as expected but 3 of them didn't work. I broke the one on top of the controller and replaced it and then IT didn't work. Controller still reported 10 but the one attached to the controller itself refused to work. 

I tried to break some of the other ones and couldn't get one on controller working again. There was some odd update behavior as I moved around breaking grids and replacing them as different ones started working or stopped working.

Hope that helps. The whole time the controller seemed to know about all the blocks [grids/cables/etc] but the grids themselves did not consistently work. I've seen this same thing on my MP world with import/export and crafters so seems to be not really tied to any one block in particular.

**Comment by Utildayael** [comment]
Hrm cant edit last post. Did more testing and my above is now invalid. I have 16 grids on the network and controller only shows 14. 5 of these grids do not work.

On a whim I broke the controller and replaced it. That seemed to send a full update out and the controller shows 16 grids [proper] and all 16 work!

**Comment by raoulvdberge** [comment]
Please try 0.9.3 and let me know if it works
