### ISSUE TITLE
[1.12.2] Something with a Signature ?

### ISSUE THREAD

**Issue by TheSnowyChickens** [raoulvdberge/refinedstorage#2090]
#### Issue description:
Red messages are bad (I think), thats why I open this "issue". (close it, if it is not relevant)
![grafik](https://user-images.githubusercontent.com/29357962/48509342-2412b180-e851-11e8-9bf3-682a14d46dcc.png)

#### What happens:
No crash, no problems, only that in the picture.

#### Steps to reproduce:
1. Create a Server
2. Install RS (in my case, I have more mods)
3. Start the Server and look in the console

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12.2
- Forge: 2772
- Refined Storage: 1.6.9

Does this issue occur on a server? [yes/no]
Server
#### If a log is relevant for this issue, link it here:

[2018-11-14-4.log.gz](https://github.com/raoulvdberge/refinedstorage/files/2582442/2018-11-14-4.log.gz)

**Comment by raoulvdberge** [comment]
Where did you get that jar from?

**Comment by TheSnowyChickens** [comment]
Curse Forge. (download via Twitch / Curse App Modpack creation tool)

**Comment by raoulvdberge** [comment]
That is very weird. I will investigate.

**Comment by raoulvdberge** [comment]
Fixed for the next version, thx for reporting!

**Comment by TheSnowyChickens** [comment]
Np
