### ISSUE TITLE
Problem hiding covers

### ISSUE THREAD

**Issue by luyiming7** [raoulvdberge/refinedstorage#2091]
#### Issue description:
Hiding covers in creative tab and JEI doesn't actually work
#### What happens:
The tab still exist, but everything is hidden under the tab except for stone brick cover(also the hollow version), also the same situation in JEI.
#### What you expected to happen:
Hide all the covers from JEI/creative tab and remove the tab for covers.
#### Version (make sure you are on the latest version before reporting):

- Minecraft:1.12.2
- Forge:1.12.2-14.23.5.2768
- Refined Storage:1.6.9

**Comment by raoulvdberge** [comment]
Yes, that is intended. One cover is still displayed so players at least know how to craft it.

Is it that big of a problem?
