### ISSUE TITLE
Wireless Grid binding ignores protections

### ISSUE THREAD

**Issue by Sir-Will** [raoulvdberge/refinedstorage#2092]
When binding a Wireless Grid to a controller it doesn't check if it's allowed to interact with that block which allows to bypass protection mods like FTBUtilities.

**Comment by raoulvdberge** [comment]
Not an RS issue. Before `ItemNetworkItem#onItemUse` is called on my mod, Forge calls the player interact event, which FTBUtilities can cancel.

**Comment by Sir-Will** [comment]
Just did some more testing and it seems to check player interact item instead of block. I only block interactions to blocks to allow the usage of food and similar items.
