### ISSUE TITLE
Large lag spikes between EnderIO and RS

### ISSUE THREAD

**Issue by PoroUsedSnax** [raoulvdberge/refinedstorage#2093]
#### Issue description:
So, I'm not 100% on what exactly is causing this issue, or whether it would be RS or EnderIO, but we've been noticing lag on our server, and finally tracked it down to what seems to be an issue between a player's RS system and EnderIO conduits. A spark profile was reporting issues from EnderIO conduit bundles down to RS (Profile attached)

https://sparkprofiler.github.io/?Q0mPalWOLX
![Spark Profile](https://i.gyazo.com/422bea8d6a90d70a73da401ba4f9ff81.png)
(image attached in case spark link goes down)

We turned off that RS System and the lag stopped from that point on

Also another odd part in all this, is that this lag only seemed to happen when the player's area was **not** chunk loaded, they had one chunkloader near but it wasn't keeping the area loaded we believe, and it was also deleted during investigating with no more around, and this lag continued

#### Steps to reproduce:
I'm guessing:
1. Build up an RS system
2. Connect to it using EnderIO conduits
...

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12.2
- Forge: 14.23.4.2718
- Refined Storage: 1.6.9

Does this issue occur on a server? [yes/~~no~~]

**Comment by raoulvdberge** [comment]
This issue is equivalent to #2144

**Comment by raoulvdberge** [comment]
This is fixed for MC 1.14. This issue was caused by EnderIO sending out too many block updates to neighbor blocks. The external storage now checks if the block update is received from the block it's connected to instead of any neighbor.
