### ISSUE TITLE
Offline crafting grid dupe bug

### ISSUE THREAD

**Issue by Sunekaer** [raoulvdberge/refinedstorage#2094]
Another shift click dupe bug in an offline crafting grid...

Here an video of soaryn finding it 
https://clips.twitch.tv/ConcernedFastCaribouDBstyle

insert an recipe in the 3x3 crafting grid, it show the result in the output box, shift click the items out of the 3x3 crafting grid and the item in the output box is still there and can be taken out
#### Version (make sure you are on the latest version before reporting):

- Minecraft:1.12.2
- Forge:2768
- Refined Storage:1.6.9

Does this issue occur on a server? [yes/no]
havent tested

#### If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here]

**Comment by raoulvdberge** [comment]
Thx for reporting. These duplication issues stem from my container rewrite and grid optimization code I wrote quite some time ago.
