### ISSUE TITLE
GTCE tools ore dictionary failure

### ISSUE THREAD

**Issue by ptk2003** [raoulvdberge/refinedstorage#2096]
If 'ore dictionary' not set, the autocrafting system did 1 craft and report about missing tool (because it got damage?), but that should not.
https://i.imgur.com/LFeKmSJ.png
https://i.imgur.com/hXyvTii.png

If 'ore dictionary' setup, the autocrafting system report about missing tool from best material.
https://i.imgur.com/G21mBaC.png
https://i.imgur.com/x7ZPPRv.png

For example hammer from any material have oredict name 'craftingToolHardHammer'
With other tools (wrench etc) same.
RS 1.6.9
GTCE 1.12.2-1.0.124
forge 1.12.2-14.23.5.2772

**Comment by CrossVas** [comment]
From 1.6.6 and above Handling of reusable items was removed from RS.

**Comment by ptk2003** [comment]
It's a pity... will have to return to AE2.
