### ISSUE TITLE
Server crash-loop

### ISSUE THREAD

**Issue by preceptor-teeth** [raoulvdberge/refinedstorage#2097]
#### Issue description:
Server goes into crash-loop

#### What happens:
On boot, server hangs for a bit, then the watchdog service reboots the server for ticks taking longer than 60 seconds.

#### What you expected to happen:
No crashing

#### Steps to reproduce:
1.boot server
2.wait a minute
3. server reboots
...

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12.2
- Forge: 14.23.5.2775 (and also 14.23.5.2768 tested both)
- Refined Storage: 1.6.9 

Does this issue occur on a server? [yes/no] yes

#### If a (crash)log is relevant for this issue, link it here:

https://pastebin.com/gi4KF9iC

**Comment by PABessero** [comment]
I'm currently also experiencing the issue on the ATM3 modpack, did you launch a big autocraft before it crashed?
