### ISSUE TITLE
Blocks broken after coming back from other dim.

### ISSUE THREAD

**Issue by Sunekaer** [raoulvdberge/refinedstorage#2101]
#### Issue description:
After leaving the mining dimension I found that my RS disk drive, crafter, and monitor had been broken. After rearranging the RS block around and traveling back and forth between the overworld and mining dimension, I found that the controller is breaking any RS block or cable that is directly touching it. Chunkloading the area seemed to fix the issue. It happens when traveling to the nether as well, but not the end.

#### What happens:
RS disk drive, crafter, and monitor had been broken after coming back from other dim.

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12.2
- Forge: 2768
- Refined Storage: 1.6.10

Does this issue occur on a server? [yes/no]
not tested

no crash log
latest.log: https://paste.feed-the-beast.com/view/a16c8379

https://github.com/Sunekaer/stoneBlock/issues/647

**Comment by Sunekaer** [comment]
I tested it in my own world and had to go to another dim and back a few times for it to happen, latest log is from my test

**Comment by preceptor-teeth** [comment]
This is also happening for players on my server.

**Comment by raoulvdberge** [comment]
That's no good! I will look into this tomorrow.

**Comment by raoulvdberge** [comment]
This has been fixed for RS 1.6.11 which is going to be published on Curse now.

**Comment by raoulvdberge** [comment]
Published!
