### ISSUE TITLE
Game hang with RS and RebornStorage autocrafter

### ISSUE THREAD

**Issue by stonecold913** [raoulvdberge/refinedstorage#2103]
#### Steps to reproduce:
1.build large Reborn Storage autocrafter. (mine is 16x16x16 with only 64 cpus and rest storage)
2.connect to RS system
3. Open RS crafter manager
...

#### Version (make sure you are on the latest version before reporting):

- Minecraft:1.12.2
- Forge:14.23.5.2768
- Refined Storage:1.6.10

Does this issue occur on a server? Haven't tried.

**Comment by raoulvdberge** [comment]
#2061
