### ISSUE TITLE
Crafter read performance issue

### ISSUE THREAD

**Issue by Sir-Will** [raoulvdberge/refinedstorage#2106]
Once the world gets loaded RefinedStorage does create all networks and doesn't only do it for chunk loaded systems. If there are a lot of networks/systems in the world it does freeze the server and can take more then 2 minutes until it's over and players are able to join the server.

This also causes issues with wrappers as the server doesn't respond for too long.

Version 1.6.5-1.6.12

![](https://i.imgur.com/BzGyM4F.jpg)

**Comment by Sir-Will** [comment]
Still taking almost 1 minute until it is completed.

**Comment by raoulvdberge** [comment]
make a new performance report then...

**Comment by Sir-Will** [comment]
![](https://i.imgur.com/Vca6FC3.jpg)
