### ISSUE TITLE
Processing Patterns and multi OreDict entries (un)expected results 

### ISSUE THREAD

**Issue by flapee** [raoulvdberge/refinedstorage#2109]
#### Issue description:
lack of ore specificity in Patterns

#### What happens:
crafting task results in (mis)matched input ingredients

- Let's make OreDict enabled processing pattern : lapis + rose red = purple dye
- RS contains only 2 lapis

Crafting preview shows that target is craftable with the 2 lapis

#### What you expected to happen:
Crafting preview shows that target is NOT craftable with the 1 roseRed missing

unfortunatelly all the ore:dyeRed, ore:dyeBlue,etc. are united into ore:dye
and current Pattern ingredient is represented (in NBT) by a specific item (minecraft:dye:4) rather than oreDict name (ore:dyeBlue)

another real example (enderIO and ThermalExp ):
- Induction smelter recipe: ore:dust*Metal* + ore:blockGlassHardened = Hardened *Metal* glass
- resulting processing pattern: copper dust + Quite Clear Glass = Hardened copper glass
- RS contains only minecraft:glass (ore:blockGlass )

would result into:
- Crafting task will commence but will result into "Machine does not accept item" error
- OreDict entries for Quite Clear Glass: ore:blockGlassHardened, ore:blockGlass, etc ... 

the underlying issue is the same, the lack of ore specificity in Patterns

#### Version
- Minecraft: 1.12.2
- Forge: 14.23.4.2766
- Refined Storage: 1.6.10

**Comment by raoulvdberge** [comment]
wontfix
