### ISSUE TITLE
Crafting task stuck on processing

### ISSUE THREAD

**Issue by flapee** [raoulvdberge/refinedstorage#2111]
#### Issue description:
CT stuck on processing ingredient, yet the machine is idle

#### What happens:
Monitor shows a sub-craft as "processing" , the affected machine is idle 
and the sub-craft to be processed has already "leaked" onto storage network

#### What you expected to happen:
CT products should have gone through [internal storage of auto-crafting](https://refinedstorage.raoulvdberge.com/wiki/how-autocrafting-works-internally)
and hence provide input for scheduled sub-crafts
this happens regardless of the means of importing of the items, interface, importer, destructor 

#### Steps to reproduce (occurs irregularly)
multi step processing patter chain

sometimes Monitor shows sub-crafts as "machine does not accept item/fluid" for a brief period, might warrant a mention

current patterns setup, and requested craft of 16.0 units of G
machineA(still resonant): products go into importer
.2A -> .8 B
.2B -> .8 C
.5E -> 1.0 F
machineB(imbuer basic): products go into interface
.5C -> 1.0 D
.5D -> 1.0 E
.5F -> 1.0 G

failure can occur for sub-products for both machines 
the observed "leaks"
- quantities are either 0.5 ,1.0, 2
- even two sub-crafts in a row
- for 2nd 3rd 5th pattern in the chain

can happen regardless of the source of the request ( user or crafting upgrade in interface) 
seems to occur more frequently if MC window looses focus

seems not to occur if the demand for the final product is staggered through contraption:
interface (+ex store) with crafting upgrade exporting one final product+
interface (+ex store) without crafting upgrade exporting all final product

sounds like [#189](https://github.com/raoulvdberge/refinedstorage/issues/189) 

#### Version 
- Minecraft: 1.12.2
- Forge: 14.23.4.2766
- Refined Storage: 1.6.11

Test world for easier reproduction ( uses UltimateAlchemy 0.0.9 pack )
[UltimateAlchemyChainedCraftingTester.zip](https://github.com/raoulvdberge/refinedstorage/files/2618172/UltimateAlchemyChainedCraftingTester.zip)

**Comment by SReject** [comment]
Getting this same issue with 1.6.12

In my case its Thermal Expansion's Signalum:
After pulverizing the required Copper and Tin ingots into powders, the next step in my crafting setup is another Processing Recipe which should output to a TE Sequence Fabricator('TESF'). The crafting hangs at "Processing". No items(the powders in this case) are output into the TESF's inventory, nor a middle-man buffer chest.

**Comment by raoulvdberge** [comment]
Can you guys make an ISOLATED use case?

Can you reproduce it 100% of the time with said isolated usecase?

**Comment by Hellaciouss** [comment]
Not sure if this is related:

If I chain 2 crafters to the back of a solderer the patterns in the back crafter will not build and the crafting monitor will say "machine in use".

If I put 1 crafter behind the solderer and 1 crafter on top the patterns produce normally and it doesn't get stuck.
