### ISSUE TITLE
Oak Wood being sent to craft Sand instead of Cobblestone

### ISSUE THREAD

**Issue by bigyihsuan** [raoulvdberge/refinedstorage#2112]
#### Issue description:
I'm using a processing pattern with OreDict on in a Nuclearcraft Manufactory to convert cobblestone to sand. Instead, it sends Oak Wood, despite the recipe being set to Cobblestone instead, leading to the system being stuck on a "Machine won't accept item" error.

I've also noticed this with the Thermal Expansion Pulverizer, but there is no error and RS sends the wood in, making sawdust instead of the expected sand.

#### What happens:
Oak Wood is being sent to craft Sand.

#### What you expected to happen:
Cobblestone should be sent to craft Sand.

#### Steps to reproduce:
**Pulverizer**
1. Set up a Pulverizer to accept the items from a Crafter.
2. Create a processing pattern to make Sand from Gravel. Turn OreDict on.
3. Place into the Crafter, and request some sand.
4. Logs will be placed into the Pulverizer instead of Gravel, making Sawdust instead of Sand..

**Manufactory**
1. Repeat steps 1-3 above for a Manufactory, and replace Gravel with Cobblestone.
2. The system will give a "Machine won't accept item" error for the Wood it's trying to place into the Manufactory.

#### Workaround
Turn off OreDict when making processing patterns.

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12.2
- Forge: 14.23.5.2784
- Refined Storage: 1.6.11

Does this issue occur on a server? Yes, and happens on single-player worlds as well.

**Comment by ViciousGamer** [comment]
> I'm using a processing pattern with OreDict on in a Nuclearcraft Manufactory to convert cobblestone to sand.
Oredict, huh.
Is there any change that wood and cobble are in the same oredict group?
Nonetheless, maybe turning Oredict off might help.

**Comment by raoulvdberge** [comment]
I can't reproduce this.

![image](https://user-images.githubusercontent.com/10358424/49178915-580dcc80-f351-11e8-981a-aa2e4ff9f4f9.png)

![image](https://user-images.githubusercontent.com/10358424/49178921-5fcd7100-f351-11e8-97dc-979b354c94d6.png)

There is wood, so if it could use that, it would:

![image](https://user-images.githubusercontent.com/10358424/49179004-9efbc200-f351-11e8-9e48-dbf934445cf2.png)

Furthermore, when actually debugging, the debugger only tells me sand is allowed:

![image](https://user-images.githubusercontent.com/10358424/49178964-8a1f2e80-f351-11e8-8266-dcd1f0a0485a.png)

This makes me think your oredictionary is configured wrongly in your pack, and thus is not an RS issue.

**Comment by bigyihsuan** [comment]
Now that I'm thinking about it, Immersive Railroading adds an OreDict tag to all forms of Wood and Cobble as railbed filler. Maybe the bug is due to both being OreDict'd as railbed filler and RS is autocrafting based on that.

**Comment by raoulvdberge** [comment]
Yes, this is a limitation in the Forge ore dictionary. RS can only base itself on that, so the data has to be correct.

**Comment by minakitty** [comment]
Bit of a necro, but google may help someone else one day.  I had the same issue trying to make glass from gravel.  Oredict was causing it to try to grind cobblestone for the exact same reason.  Turning off oredict for that one recipe seems to have fixed it
