### ISSUE TITLE
Sorting via Inventory Tweaks with lots of items in system freezes game.

### ISSUE THREAD

**Issue by gggg336** [raoulvdberge/refinedstorage#2113]
#### Issue description:
Sorting according to Inventory Tweaks freezes the game if there are a lot of items in the system.
#### What happens:
When going through the sorting categories, once it gets to Inventory Tweaks, the game freezes and quitting via task manager is the only option.
#### What you expected to happen:
Game not freezing.
#### Steps to reproduce:
1. Have more than 300+ item types in a system
2. Toggle sorting categories to inventory tweaks
3. Game freezes
#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12.2
- Forge: 2776
- Refined Storage: 1.6.11

Does this issue occur on a server? [yes/no]
Playing Singleplayer

Config to disable InvTweaks option would be an easy fix.

**Comment by raoulvdberge** [comment]
Report to invtweaks
