### ISSUE TITLE
Interface with Crafting Upgrade stuck

### ISSUE THREAD

**Issue by flapee** [raoulvdberge/refinedstorage#2114]
#### Issue description:
interface with multiple exported slots wont craft all craftable exports 

#### What happens:
if there is a needed unavailable uncraftable item ( missing items, pattern or ingredients) , 
then the following needed items will be satisfied only if they are present on the network

#### What you expected to happen:
for any needed unavailable item, a crafting task should be scheduled
hence skip to the next  exported slot(s) 

#### Steps to reproduce:
- interface + crafting upgrade
- 1st export slot set so that the request can not be met
- 2nd export slot set so that the request can not be met fully using items on network
- crafter with recipe for requested item in step above and sufficient ingredients on the net

#### Version
Minecraft: 1.12.2
Forge: 14.23.4.2766
Refined Storage: 1.6.11

related to #1864

**Comment by raoulvdberge** [comment]
cryptic "what happens" and "What you expected to happen" parts. Please  clarify yourself.

**Comment by flapee** [comment]
-1st slot target: 10 chests 
-2nd slot target: 10 torches 

if 1st slot has less than 10 chests present (for what ever reason),
then 2nd slot wont be filled, even though the torches are craftable
expected the torches to be crafted and the target met regardless of chests ...
