### ISSUE TITLE
Drives Vanish on server restart/crash

### ISSUE THREAD

**Issue by UkeArie** [raoulvdberge/refinedstorage#2117]
#### Steps to reproduce:
1. Set up RS system with drives
2. Crash server
...

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12.2
- Forge: 14.23.4.2759
- Refined Storage: 1.6.5

Does this issue occur on a server? [yes/no]
Yes
#### If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here]

**Comment by raoulvdberge** [comment]
Duplicate #1846

**Comment by Darkere** [comment]
You might be able to restore the disks with the /createdisk command although it might be difficult to determine who they belong to on a server.
