### ISSUE TITLE
Issue with GUIs and RAM usage

### ISSUE THREAD

**Issue by scottwilson0308** [raoulvdberge/refinedstorage#2123]
#### Issue description:

RS uses almost as much RAM as my other 90 mods do, and I cannot click in a certain area whenever I have a GUI open.

#### What happens:

If I even just hover my mouse in the afflicted area, not even the slot is highlighted. Nothing at all happens. Includes both Vanilla and modded GUIs, and even affects JEI area.

Memory used when launching MCF goes from just over 2G to about 3.8G.

#### What you expected to happen:

Self-explanitory

#### Steps to reproduce:
1. Launch Minecraft Forge with RS installed
2. Watch RAM get hungry
3. Open GUI in-game, no clicking in the affected area.
...

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12.2
- Forge:
- Refined Storage: 1.6.12, but noticed it back on 1.6.9

Does this issue occur on a server? [yes/no] Unknown, only played locally.

#### If a (crash)log is relevant for this issue, link it here: 

Doesn't crash. I'd just love to be able to click normally in GUIs, and use RS on both computers so the two of us can play locally. Laptop gets fussy when RS is installed.

Crossing my fingers that these issues are a simple fix for one of us, I really enjoy using RS.

[pastebin/gist/etc link here]

**Comment by raoulvdberge** [comment]
You can't attribute ram usage to a single mod that easy, and I doubt your methods of finding out are unreliable.

**Comment by scottwilson0308** [comment]
Hey,

The GUI problem was only temporarily solved by removing RS, it's back now so apologies for wasting your time with that part.

The only method I used was running MCF with Launch options allowing 3GB with and without RS. Without RS, I cap off at about 2.2GB Memory Used during the Forge Initialization screen. With RS installed, it crashes from lack of memory. I increase allowance to 4GB, and now it'll actually make it to the main menu, capping off at about 3.8GB... with and without RS, my debug screen memory usage is about 4.1GB and 5.3GB respectively.

I hope you didn't think I was trying to come off as impatient or rude, that's not my intention.. just wondering if you know of any reason at all as to why this would be the case.
