### ISSUE TITLE
autocraft problem

### ISSUE THREAD

**Issue by demon57730** [raoulvdberge/refinedstorage#2127]
#### Issue description:
here I have craft or an item can be used several times in the same craft (durability or no durability) so that the auto craft says that it must be full of item that we want craft while he only 1 example Mystical Agriculture. in the old version we could do ctrl + maj to launch the autocraft even if we do not give the craft of this item because the craft wanted to recreate the item while it needs only 1 except in the Refined version Storage 1.6.12 we can no longer force the craft which block.

- Minecraft: 1.12.2
- Forge: 1.12.2-14.23.5.2772
- Refined Storage: refinedstorage-1.6.12

Does this issue occur on a server? [yes/no] yes

**Comment by demon57730** [comment]
help

**Comment by raoulvdberge** [comment]
RS no longer handles damaged items during autocrafting. Please read previous issues about this, I've closed enough of these already!
