### ISSUE TITLE
[behavior change request] stack upgrade currently makes exporter not insert, ever, if 64 items can't fit in inventory

### ISSUE THREAD

**Issue by Azutte** [raoulvdberge/refinedstorage#2128]
Inventory has, for example, a space of 63 items left. Exporter has 3 speed upgrades and 1 stack upgrade. It just doesn't try and put anything in.

More often than not this is fine, but where it falls apart is when I try to use anything that intentionally leaves 1 remaining item in a slot so for automation purposes no new and incorrect item can go in that slot.

In practice: 
 * in [the newest dw20 pack](https://ftb.gamepedia.com/Direwolf20_1.12), 
 * running Refined Storage 1.6.9, 
 * with Extra Utilities 2's Analog Crafter set to ✔️Sticky, 
...the block stops it from using the last one(intentionally), which makes an exporter not be able to stick a full stack in at once. 
![2018-12-05_13 08 21](https://user-images.githubusercontent.com/6581284/49544382-98a8a100-f88f-11e8-8eba-cf618acdd38b.png)
![2018-12-05_13 08 25](https://user-images.githubusercontent.com/6581284/49544385-98a8a100-f88f-11e8-9016-6fd3b7146ea1.png)
![2018-12-05_13 08 28](https://user-images.githubusercontent.com/6581284/49544386-98a8a100-f88f-11e8-8d2b-e7ea9caddcb3.png)

In this _admittedly extremely specific example_, the setup I want to work doesn't. Any chance of changing it to "attempts 64, or less if it can't"?

**Comment by natedogith1** [comment]
A vanilla setup that also reproduces this issue:
1) fill a chest with cobble
2) put some cobble in the RS system
3) put exporter on chest
4) place stack upgrade in exporter
5) configure exporter to export cobble
6) remove half a stack from the chest
