### ISSUE TITLE
[Request] JEI-style sorting for Grids

### ISSUE THREAD

**Issue by oitsjustjose** [raoulvdberge/refinedstorage#213]
First let me say BEAUTIFUL mod, I absolutely love using it!

So, my only request thus far is some type of either ModID / InvTweaks style sorting like AE2 had, where it sorted almost identically to how JEI sorts things. Any possibility of that happening?

**Comment by raoulvdberge** [comment]
You can use @ to filter on mod id?

**Comment by raoulvdberge** [comment]
And great to hear you like the mod!

**Comment by oitsjustjose** [comment]
Right, I know you can filter by ModID, but I was wondering if you could add a sort by ModID for Grids, which starts by displaying everything from Minecraft, then sorts everything else by ModID Alphabetically, similar to how JEI sorts its items in the Item Lists.

**Comment by raoulvdberge** [comment]
Sure, i'll try to get this in for the next version

**Comment by raoulvdberge** [comment]
Unfortunately I won't be able to implement this as JEI sorting depends on item register order, and RS has no such concept.
