### ISSUE TITLE
Not accounting for drawers with more than one drawer

### ISSUE THREAD

**Issue by oliverrook** [raoulvdberge/refinedstorage#2133]
#### Issue description:
When using storage drawers that have more than one slot, ie the ones that can hold two or more sets of items, the system doesn't seem to account for the additional space. It currently says that it is using 4.9k/2.3k, and using 215% of the available storage. The additional items are also not showing up in the system.
#### What happens:
As stated above, what happens is it detects that there are more items in the drawers, but doesn't account for drawers with more than one slot, resulting in it saying that the external inventory is more than 100% full and not showing the additional items.
#### What you expected to happen:
I expected it to just account for the multiple slots in the drawers and to adjust itself accordingly.
#### Steps to reproduce:
1. Setup a RS system.
2. Make a bank of Storage Drawers that are not just the single slot ones (Ie ones that can have two or more kinds of items in them)
3. Hook them up to a Drawer Controller
4. Hook up the Drawer Controller to the system via an External Storage bus.

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12.2
- Forge: 14.23.5.2768
- Refined Storage: 1.6.11

Does this issue occur on a server? [yes/no] no

**Comment by Darkere** [comment]
This is not an RS issue and also happens with single item drawers.

The storage drawer controller itself does not report correct numbers. It reports a Stack of inventory for every drawer connected regardless of upgrades. I assume that this is needed for the internal logic of the storage drawers. As such it would need some major rewriting (+performance issues) with storage drawers to fix this. 

Combine this with the fact that the Fullness of the drawer system is not actually useful as you cannot tell which drawer is how full, I don't think this is something that can be or should be fixed.

You can divide the amount of possible storage that the external storage shows by 64 to get the number of drawers you have connected. But RS has no way to know what upgrade status the drawers have and thus can't calculate total storage in any way.

**Comment by raoulvdberge** [comment]
The % percentage is only for rendering, it has no effect whatsoever on the logic of item I/O.
