### ISSUE TITLE
Crafter putting in wrong number of item and wrong item

### ISSUE THREAD

**Issue by TungVoid** [raoulvdberge/refinedstorage#2138]
#### Issue description:
I have a crafter for organic industrial dye from enderio.I can not auto-craft it because it keeps putting in the wrong number of item and sometimes the wrong item
#### What happens:
Pattern says put in 2 oredict dyeBrown,a slimeball and pulverized coal,but only put in 1 dye and sometimes try to put in lapis
#### What you expected to happen:
It will put in the correct number of item
#### Steps to reproduce:
1.Make a pattern of the organic brown dye
2.Put it in a crafter and have an alloy smelter in front of it
3.Try to craft the dye
...

#### Version (make sure you are on the latest version before reporting):

- Minecraft:1.12.2
- Forge:14.23.4.2760
- Refined Storage:1.6.12

Does this issue occur on a server? [yes/no]

#### If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here]

**Comment by Darkere** [comment]
Check if you enabled oredict on the recipe. That would explain the lapis at least.

**Comment by TungVoid** [comment]
i think i figured out the problem.The organic brown dye is dyeBrown in oredict,so it is trying to craft something using itself
