### ISSUE TITLE
[1.12.2] Galacticraft Fluid Buckets gets deleted if you have more than 1 in the Storage Disk.

### ISSUE THREAD

**Issue by Z-Tunic** [raoulvdberge/refinedstorage#2139]
Refer'd Issue:
https://github.com/micdoodle8/Galacticraft/issues/3570

Minecraft: 1.12.2
Forge: 14.23.5.2795

Mods: 5
GalacticraftCore-1.12.2-4.0.1.181
Galacticraft-Planets-1.12.2-4.0.1.181
MicdoodleCore-1.12.2-4.0.1.181
RedstoneFlux-1.12-2.1.0.6-universal
refinedstorage-1.6.12

-----

Not sure why but if you have more than 1 Bucket of Oil, Fuel, Sulfuric Acid, or Bacterial Sludge from Galacticraft stored in a Storage Disk... it deletes all but 1 of each item. This doesn't happen if stored in a Fluid Disk. Here are some images...

![](https://cdn.discordapp.com/attachments/377171551155650560/523818218763059219/refinedstoragegalaticcraft1.PNG)
Crafting grid with 9 Oil Buckets ready to be stored.

![](https://cdn.discordapp.com/attachments/377171551155650560/523818240900857859/refinedstoragegalaticcraft2.PNG)
Oil Buckets have been stored.

![](https://cdn.discordapp.com/attachments/377171551155650560/523818259871694858/refinedstoragegalaticcraft3.PNG)
Alright I need the Oil Buc- wait... what happened to the other Oil Buckets? I put in 9 but I only have 1? I didn't take them out otherwise they would be in my inventory.

**Comment by Z-Tunic** [comment]
***UPDATE***

Apparently the items ARE there but only if you remove the item and then re-open the interface. Also not only Galacticraft is affected but items from the Cyclic mod are effected as well such as the Ender Book.

**Comment by raoulvdberge** [comment]
This is fixed for 1.14

**Comment by Z-Tunic** [comment]
Would it be fixed in the 1.12.2 version?
