### ISSUE TITLE
RS Storage disks do not show any items on it or any indicator of capacity. Items are locked inside.

### ISSUE THREAD

**Issue by Murdurtroll** [raoulvdberge/refinedstorage#2140]
Hi there,

maybe I have posted this on the wrong page?;

https://github.com/FTBTeam/FTB-Presents-Direwolf20-1.12/issues/87

Modpack Version: Refined Storage 1.6.4 (Direwolf20-1.12.2)

Issue: I have a refined storage system setup, with 6 64K disk drives, furthermore I have an external storage bus connected to a drawer controller, which is connected to several drawers for items I have in bulk. The following issue occured; I decided to go AFK for some time to let all mining run etc. Therefore I put all my armor/rings/inventory into the RS system. At my returnal I wanted to get my items out, but it appeared that everything which was stored on the disks is not visible in the RS system. All items which were are in the external storage drawers are visible.

Thus, I tried to check what the problem was, broke the RS controller and replaced it, no difference.
I took the disks out of the disk drive, broke the disk drive, put the disks back in but no items visible in the system. I did notice that new items which came in via my ender chest onto which an importer was connected were not placed in the RS system. In matter of fact, I cannot place any item in the RS system (I can place items in which are connected through the drawer system).

At last, I checked my disk drive, it says 0/0 space used/available, whilst 6 64K disks were inside. I manually made a 1K disk, put it in and it showed 0/1000. Thus, the issue seems to be that the 64K disks which were inside are suddenly not recognized anymore, and all my items are locked.

Link to Log or Crash File Paste:

Is it Repeatable?: The issue is still occuring.

Mod/s Affected: I think it is only Refined Storage 1.6.4, maybe the Refined Storage Addons as well, but do not know for sure.

Known Fix: I have read several threads and forums, but did not find any simmular issue. Anyone can help about this?

I tried my best provide all information, if any is lacking please let me know.

 @Murdurtroll
 
Murdurtroll commented 13 days ago
Update:
Still not working, but I found some interesting things. Importers are not working, exporters are working if I E.G. make a crafter recipe it does output the item into the furnace, but than it does not import the finished product, as the 64K storage disks seem broken.

**Comment by Bircko** [comment]
same thing happend to me after updating stoneblock to newest version (beta)

**Comment by Darkere** [comment]
You can recreate the disks with the /createdisk (Might be named slightly differently) command.

**Comment by raoulvdberge** [comment]
please try on the latest version
