### ISSUE TITLE
Feature Request: Exporter White List/Black List & Priority level.

### ISSUE THREAD

**Issue by Hellaciouss** [raoulvdberge/refinedstorage#2142]
#### Why: As a means of getting rid of excess items. The way I imagine it would work is the following:

Say you have an external storage system connected and it has a priority of 50 (so it goes to the external storage first rather then your disks) and your cobble drawer is full and you don't want more cobble stored. Normally the excess would flow into your RF storage system.

To prevent that from happening you could set up a white list filter on an exporter to include cobble. You could then set your grid to -2 priority (what this does is sends makes your grid the lowest priority storage ((if you don't have anything else set lower)) to go to any storage it can with a priority above -2 before it settle into your RF storage system) and set your exporter to 0. Now seeing as your external storage for that item is full it will search for the next highest priority storage which would be the exporter that has cobble white listed and is set to priority level 2.

1) Set up an exporter connected to a block that voids/destroys/whatever.
2) Set it to white list cobble and add the priority level so that it is above your grid storage but below your external storage for cobble (the cobble you want to keep).
3) Once your external storage fills with your set amount of cobble, it will seek the next highest priority storage.
4) Since your internal storage priority is lower then the exporter that has cobble white listed (so it only lets the cobble through of course) it will send the cobble to the block connected to the exporter, destroying it instead of storing it.

This system has some risks of course. If you click black list over white list on accident your internal system will quickly begin voiding your entire internal storage. If you don't set priorities throughout your system correctly it could also begin voiding what you don't want it to void.

**Comment by Darkere** [comment]
Not sure if I'm misunderstanding something but this seems totally possible by just using another external storage? 

If you need to remove the items from your disks actively, set it up and run your disks through the disk manipulator with appropriate whitelist settings.

**Comment by Hellaciouss** [comment]
You're right. I set up just another external storage (connected to a trash can) with a priority set between disks and the other external storage and it voids excess.
