### ISSUE TITLE
Feature Request: config file option for inverted priority extraction

### ISSUE THREAD

**Issue by son0fether** [raoulvdberge/refinedstorage#2145]
#### Issue description:
I've read through the previous issues and I'm aware of the author's personal preference for the current implementation of priority, which is highest priority gets first extract and first insert.  I would like to request a config file option to invert that, with default of false, so that inserts go to highest priority and extracts come from the lowest priority.  Nothing in the UI, nothing that would affect existing players.

The specific use case where this affects me is external storage blocks connected to containers such as storage drawers or other deep storage that can hold many items of one kind.  It's normal to set the disk drives to lower priority than the storage so that items go into the storage containers.

#### What happens:
With non-inverted priority, and the disk drives are lower priority, there's no way to get the items out of the disks without lengthy manual steps such as switching the disks to a disk manipulator or setting up an exporter, etc.

#### What you expected to happen:
With inverted priority on extract, if you have items in disks, and the disk drives are lower priority, inverted priority makes the disk drives empty themselves of those items as items are inserted and extracted.  If there are many items, removing large numbers of them and re-adding them via a grid moves the items to the desired storage.

#### Steps to reproduce:
1. Have an external storage block, a storage drawer, and a disk drive all connected to the system.
2. Determine that an item is clogging your disks and should go to the deep storage.
3. (easy to fix with inverted priority on extract, hard without)

#### Version (make sure you are on the latest version before reporting):
(in Sevtech Ages 3.0.8)
- Minecraft: 1.12.2
- Forge: 14.23.4.2707
- Refined Storage: 1.5.34

Thank you for this wonderful mod.  I really enjoy using it, and I simply want this aspect of using it to become even easier.

**Comment by raoulvdberge** [comment]
No, making this a config option would make it super confusing as priority settings would be dependant on pack/environment. Definitely a no-go on that one.

**Comment by raoulvdberge** [comment]
And good to hear that you're enjoying the mod :-)
