### ISSUE TITLE
Autocrafting crashes server and breaks server entirely

### ISSUE THREAD

**Issue by TheFridgeMaster** [raoulvdberge/refinedstorage#2146]
#### Issue description:
I have been building a modpack based around GalictiCraft and myself and a few mates have been playtesting for around 40ish hours. After updating and installing some new mods, we now have this issue when attempting to autocraft most recipe's, the server insta crashes and you have to restore the world from backup to launch the server again as it just continues to crash with the same error after the event. Not all recipes are broken. I have attempting recreating a bunch of issued recipes, but it still happens.

#### What happens:
The server crashes and needs to be restored from backup to function again.

#### What you expected to happen:
The recipes were previously autocrafting without issue. Might be a mod conflict?

#### Steps to reproduce:
1. Join server
2. Launch autocraft in either reborn multiblock or refined storage crafter
3. server crashes immediately, rendering the server broken until world is restore from backup
...

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12.2
- Forge: 1.12.2-14.23.5.2772
- Refined Storage: 1.6.12

Does this issue occur on a server? [yes/no]
yes

#### If a (crash)log is relevant for this issue, link it here:

https://pastebin.com/jcJHxNSx

I hope I am not doing something wrong that is painfully obvious :S this is my first modpack and so far, it has been going well.

**Comment by raoulvdberge** [comment]
Remove refined exchange

**Comment by TheFridgeMaster** [comment]
Without sounding too brash, to what end? I can get the server working after restoring from backup and refined storage works perfectly in all other aspects, it is only when trying to launch an autocraft that it breaks and you have to revert the server again.

**Comment by TheFridgeMaster** [comment]
oh shit. that is a good point. I was disappointed by the lack of emc mods tying into RS, but if it is inherently busted, I'm not gonna stress about it's inclusion as it's features were fairly lack luster to begin with. 

Yes that absolutely fixed the problem. Thank you so much!

Was there something in the log that indicated that was the issue or do you just know it has incompatibility?

**Comment by raoulvdberge** [comment]
```
    at com.bartz24.refinedexchange.features.network.NetworkNodeEMCCrafter.update(NetworkNodeEMCCrafter.java:140)
    at com.raoulvdberge.refinedstorage.apiimpl.network.NetworkNodeListener.onWorldTick(NetworkNodeListener.java:23)
```
