### ISSUE TITLE
When autocrafting EnderIO Vibrant Capacitor Bank, system doesn't detect Capacitor Bank.

### ISSUE THREAD

**Issue by Deiskos** [raoulvdberge/refinedstorage#2148]
#### Issue description:
I am using Stoneblock 1.0.31 modpack. When autocrafting EnderIO Vibrant Capacitor Bank, system doesn't detect and cannot craft Capacitor Bank (even though correct pattern is in the crafter).

#### What happens:
Storage system doesn't detect Capacitor Bank even though it can be crafted and/or already in the system. Capacitor Bank itself can be autocrafted without a problem. Here are recordings of both cases  [recordings.zip](https://github.com/raoulvdberge/refinedstorage/files/2717256/recordings.zip) (in zip because Github doesn't allow mp4)

#### What you expected to happen:
For system to craft Vibrant Capacitor Bank.

#### Steps to reproduce:
1. Create crafting pattern for Vibrant Capacitor Bank.
2. Put required items into storage system.
3. Try to place order.
...

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12.2
- Forge: 1.12.2-2.6.0.79
- Refined Storage: 1.6.12

Does this issue occur on a server? [yes/no]
n/a

#### If a (crash)log is relevant for this issue, link it here:
n/a

**Comment by Darkere** [comment]
Intended (kind of). You should be able to fix this by manually replacing the Capacitor Bank in the Vibrant Capacitor Bank Recipe.

This happens because the capacitor bank has different data in the recipe than when it's actually crafted.

**Comment by Deiskos** [comment]
That worked, thanks
