### ISSUE TITLE
Crafting Monitor GUI turns brown

### ISSUE THREAD

**Issue by emannotava** [raoulvdberge/refinedstorage#2149]
#### Issue description:
Graphical error in the crafting monitor

#### What happens:
I had my refined storage system set to craft 8 range upgrades for my wireless transmitters, and at one point i decided to take a look at how far it was with crafting them and when i opened the crafting manager it's GUI was suddenly brown whilst the tab of another recipe i was doing was still gray

#### What you expected to happen:
The Crafting Monitor GUI should've stayed gray

#### Steps to reproduce:
unfortunately haven't been able to reproduce it, so that's not of much help :-(
...

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12.2
- Forge: forge-14.23.4.2766
- Modpack: Ultimate Alchemy by RWTema
- Refined Storage: 1.6.5
- Refined Storage Addons:
	- Refined Storage Addons 0.4.2
	- Reborn Storage 1.12.2-3.3.2.79
	- EnderIO Conduits Refined Storage 1.12.2-5.0.33

In the process of making range upgrades in this modpack my RS system had to use Regular crafting, a Redstone furnace for smelting the processors and an Induction Smelter to create some Quartz Enriched Iron(which is made with Iron and Silver in an induction smelter in this pack), and the cut proccesors are made in ExtraUtils2 Mechanical crafters because RS keeps crafting new cutting tools instead of using a already made one

Last bot not least, i don't know if this is necessary to know but here is everything that is in my RS system:
3x Network Transmitter
3x Network Receiver
10x Crafters for regular crafting recipes
6x Importers
4x Wireless Transmitter
1x Crafting Grid
1x Crafting Manager
1x Pattern Grid
1x Disk Drive(with 2x 4K Disks inside)
1x Crafting Monitor
3x External Storage(attached to 3 infinite barrels from YABBA)
1x External Storage(attached to a drawer controller with around 15 compacting drawers for al my materials)
18x Cables
7x Refined Storage Conduit

Does this issue occur on a server? - This occurred in my singleplayer world, but i suspect that this is a Client-Side bug, it could probably happen if you're playing on a server as well

I've got a screenshot of brown GUI here:
![2019-01-01_10 13 27](https://user-images.githubusercontent.com/16382632/50571676-1b4e4e80-0db1-11e9-858d-8998cc16278e.png)

**Comment by emannotava** [comment]
Well I didn't think it was a big issue to be honest, but I thought I'd
share it anyway.

Thanks for replying so fast btw, good to know that there's a newer version
of RS available,
because I had loads of bugs with "ghost items" in my storage system which
caused the system to think it can could craft something whilst it's really
unable to because items don't actually exist.

So I'll be sure to check out the changelog and test if that happened to be
fixed.

Anyway before I turn this one reply into a whole new issue/thread, once
again thank you for the quick response. And keep up the awesome work👍🏻

Anthony Langendoen(eman_not_ava)

**Comment by raoulvdberge** [comment]
Closing this as ancient RS version
