### ISSUE TITLE
A particular pattern causes the game to crash to title screen

### ISSUE THREAD

**Issue by Damien-Reave** [raoulvdberge/refinedstorage#2151]
#### Issue description:

Making a pattern where any wire or cable from GregTech Community Edition is the sole output (meaning the image of the wire or cable will display when shift is held) causes a crash when the game tries to render the wire or cable. This happen when shift is held when the pattern is in the player's inventory, or if the pattern is sitting on the ground in the world and is in the player's view, or if the pattern is stored inside of a crafter.

#### Steps to reproduce:

Reproducible by creating a pattern as so described and hitting shift.

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12.2
- Forge: 14.23.5.2796
- Refined Storage: 1.6.12

Does this issue occur on a server? [yes/no]

Unknown, tested only in SP

#### If a (crash)log is relevant for this issue, link it here:

Here's a couple of the crash reports

https://paste.dimdev.org/acajesenak.mccrash

https://paste.dimdev.org/wakahuwuya.mccrash

https://paste.dimdev.org/wakahuwuya.mccrash

https://paste.dimdev.org/fociwajibu.mccrash

https://paste.dimdev.org/owisilanuf.mccrash

**Comment by Damien-Reave** [comment]
Here's another crash report from a similar pattern (tin ingot into tin wires) that has some more useful looking information.

https://paste.dimdev.org/wakahuwuya.mccrash

**Comment by raoulvdberge** [comment]
Not an RS problem
