### ISSUE TITLE
Interaction with Storage Drawers via External Controller over 100% Full

### ISSUE THREAD

**Issue by ingrac42** [raoulvdberge/refinedstorage#2154]
#### Issue description:

I think this may be the same issue a couple other reports I read, but nothing was an exact match.

External Storage to a Storage Drawer Controller is reporting the Storage Drawers as well over 100% full, even though void upgrades and storage upgrades mean the drawers can still accept items.  Because the External Storage thinks the drawers are full, items are being placed on storage disks instead of in the storage system.

If I remove all disks and drop them in the disk manipulator, in this system the only storage destination is the drawer controller.  The disk manipulator will extract items and place them in the drawers regardless of how "full" they are, but under normal operation the disk fills with items.

Disk controller priority is 0, External Storage is 2500, so it's not a priority issue.

#### What happens:

Items are going to storage disks despite higher priority on the external storage because the external storage thinks the drawers are unable to accept more items.

#### What you expected to happen:

Accurately report the utilization of the storage drawers.

#### Steps to reproduce:
1.  Controller with connected disk drive and external storage
2.  Storage drawers with drawer controller connected to external storage
3.  Start adding items

#### Version (make sure you are on the latest version before reporting):

- Minecraft:  1.12.2
- Forge: 14.23.5.2772
- Refined Storage:  1.6.12
- Storage Drawers: 1.12.2-5.3.8
- Reborn Storage: 1.12.2-3.3.2.79 (I'm using the large disks, but I don't think it's relevant, providing just in case)
- Reborn Core: 1.12.2-3.12.1.385-universal

Does this issue occur on a server? Yes

Image showing storage drawers in External Controller are over 100% full:
![2019-01-05_09 40 54](https://user-images.githubusercontent.com/18634682/50726866-139fea00-10d0-11e9-811f-a36fac95aeab.png)

**Comment by Darkere** [comment]
As far as I know, the numbers on the external storage are entirely visual and don't get considered when inserting items at all. That means it's likely the error comes from somewhere else. 

Considering you have (if my math is correct) 355 drawers connected to this external storage chances are that either the drawers are actually full or that you maybe ran into the maximum range of the drawer controller.

**Comment by ingrac42** [comment]
> As far as I know, the numbers on the external storage are entirely visual and don't get considered when inserting items at all. That means it's likely the error comes from somewhere else.
> 
> Considering you have (if my math is correct) 355 drawers connected to this external storage chances are that either the drawers are actually full or that you maybe ran into the maximum range of the drawer controller.

I did have some issues with range when I set the drawers up initially, and I redesigned the storage drawers to avoid that problem.  Some drawers are full, but not all of them, and there are void upgrades on every drawer, so it shouldn't ever stop accepting items.  However, if I flip the drawers to "input only" I can still find items that ought to be in the drawers in my RS system.

**Comment by raoulvdberge** [comment]
RS doesn't care about the capacity number, it's purely visual.
