### ISSUE TITLE
Small problem with refined storage and V0id's Smart Backpacks

### ISSUE THREAD

**Issue by SirAron111** [raoulvdberge/refinedstorage#2157]
#### Issue description:
Can’t pull out backpacks from refined storage if they are empty or newly created

#### What happens:
Can’t pull out backpacks from refined storage if they are empty/newly created thats it tehy are stuck in there if they have items inside you can get them out just fine must be some problem with how data gets grabbed there

#### What you expected to happen:
Being able to pull out my backpack just fine like all other items as V0id's Smart Backpacks is Is basically the new and better version of iron backpacks that many people will be using in the future.

#### Steps to reproduce:
1.Install V0id's Smart Backpacks and refined storage (or just use the Modpack “Dimension Zero” that has them both)
2.Make the storage system just a controller grid the disk drive etc and put some empty backpacks inside
3.Try pulling them out of the system with the grid or crafting grid or shift click nothing works
4.Put a filled backpack in this one gets pulled out
5.Wonder why this happens?????
...

#### Version (make sure you are on the latest version before reporting):

- Minecraft:1.12.2
- Forge:14.23.5.2796 
- Refined Storage:Refined Storage 1.6.12
-V0id's Smart Backpacks-1.0.6.jar

Does this issue occur on a server? [yes/no]
On Single palyer and Server

#### If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here]

**Comment by raoulvdberge** [comment]
This bug is only present in MC 1.12.2 and should be fixed in MC 1.14. I will leave this as won'tfix for 1.12.
