### ISSUE TITLE
Invalid (expired) cert for repo 

### ISSUE THREAD

**Issue by lehjr** [raoulvdberge/refinedstorage#2159]
Just a heads up, the cert for https://repo.raoulvdberge.com expired on Sunday. I know it's not specific to Refined Storage, but it was something I hit when refreshing my project and using it as a dependency.

**Comment by fspijkerman** [comment]
@lehjr thanks for letting us know, I've fixed the problem, next time the letsencrypt renewal should work.

**Comment by raoulvdberge** [comment]
Thank you for the report! :)
