### ISSUE TITLE
Storage disk still lists capacity when empty

### ISSUE THREAD

**Issue by Loothor** [raoulvdberge/refinedstorage#216]
Hi there,

I emptied all of my 4k and 16k disks manually to move onto 64k disks. (Manually because there's no disk manipulator yet ;))

I found that the disks still show storage, but I cannot see any items in the grid. Assuming this is a bug, but I cannot break these disks down to components unless they are empty.

![2016-07-21](https://cloud.githubusercontent.com/assets/8557476/17029219/6a8d08c2-4f38-11e6-8e20-3ba17c42a247.png)
![2016-07-21 1](https://cloud.githubusercontent.com/assets/8557476/17029221/6c113362-4f38-11e6-9b65-068df1dac447.png)

**Comment by raoulvdberge** [comment]
Maybe a hard Q to answer, but since which version do you have that storage disk approximately?

**Comment by Loothor** [comment]
I would say the server has been running for about 3 weeks now. We use Spilled Juice mod pack from AT Launcher. We started with 0.8.5 and are now on 0.8.12.

Hope this helps!

**Comment by raoulvdberge** [comment]
Gonna close this as this is probably related to #227
