### ISSUE TITLE
java.lang.IllegalArgumentException: Cannot accept empty stack

### ISSUE THREAD

**Issue by mr2013** [raoulvdberge/refinedstorage#2162]
#### Issue description:
Server crashes immediately after boot due to "Cannot accept empty stack" error

#### What happens:
Boot server. Get fatal error.

#### What you expected to happen:
1. Treat as soft error instead of fatal and discard invalid stack, or
2. Display location of erroring controller or grid so as to permit analysis and recovery via mcedit/nbtexplorer

#### Steps to reproduce:
1. Cause unknown

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12.2
- Forge: 2795
- Refined Storage: 1.6.12

Does this issue occur on a server? yes

#### If a (crash)log is relevant for this issue, link it here:
https://pastebin.com/8Gzy1Jw7

A copy has been made of the crashing world, should it be desired for inspection.

**Comment by raoulvdberge** [comment]
@mr2013  I might be a bit late, but if you still have the world laying around, feel free to send it to me along with a list of mods. I'll reopen if you do.

**Comment by Lunetouche** [comment]
Also had this crash, although it didnt want to crash the server properly (had the forge erroring entity removal options turned on) so ended up with a huge server log.
using the All the Mods 3 modpack v5.12.1 with minecolonies updated to build 259 release. containsrefined storage  1.6.14

Not sure if its a refined storage or quantum storage bug, as restoring from a backup my checks of everything showed the quantum fluid disks with a negative value for their contained fluids and im guessing that the crash started when it finished looping back to 0 of the fluids.

able to supply a world file from when it was broken though its 800mb compressed.

**Comment by dkambersky** [comment]
Still present. SevTech 3.1.2 Hotfix 1 pack. Am able to supply a world file (though it's 6GB compressed...)

**Comment by dkambersky** [comment]
Update: a likely culprit might be an overflow in Quantum Storage's Fluid Disk. After removing the crashing controller and putting it back in, I realized the connected disk drive had a Fluid Disk with a large negative fluid storage amount.

**Comment by DizzyDJW** [comment]
No point in creating a new issue if I'm experiencing this exact issue here still in 2023 now. I have no QuantumStorage in the modpack and nothing is connected via External Storage that I haven't connected a million times in the past before. 

This closed before it was ever fixed

**Comment by Pultex** [comment]
for me it was having Occultism storage connected with external storage
that mod must holds items strange

worked for around an hour then crashes the server
did not know why the crash happened as it was fine for a whole day then started to crash
after I was adding loot from a dungeon
maybe the way occultism updates stacks is odd

**Comment by efrainesquivel** [comment]
This appears to be happening with storage controllers from the Functional Storage mod as well. I was crashing multiple times sporadically until I removed the external storage attached to the FS controller.

**Comment by spinshock** [comment]
> This appears to be happening with storage controllers from the Functional Storage mod as well. I was crashing multiple times sporadically until I removed the external storage attached to the FS controller.

I am having the exact same issue.
It happens randomly. I constantly store a huge amount of items coming from a quarry through the external storage hooked to a Functional Storage Storage Controller.

Version (make sure you are on the latest version before reporting):
Minecraft: 1.19.2
Forge: 43.2.3
Refined Storage: 1.11.4
Does this issue occur on a server? no, single player world

If a (crash)log is relevant for this issue, link it here:
https://pastebin.com/Z5X0daPC

**Comment by dkambersky** [comment]
@raoulvdberge can this issue be re-opened? definitely still happening, people can provide logs/worlds

**Comment by raoulvdberge** [comment]
There is an existing issue about this open. Use the search function

**Comment by LOR1A** [comment]
Hello,
I have the same crash problem but couldn't find a solution in the opened ticket (related to fluid grid)...
On my side it happens on sevtech ages (1.12.2) with refined storage (1.6.16) and Refined storage addons (0.4.5)
[crash-2023-02-03_08.50.55-server.txt](https://github.com/refinedmods/refinedstorage/files/10576802/crash-2023-02-03_08.50.55-server.txt)
Thanks for your help.

**Comment by LOR1A** [comment]
I found some possible explanation, I deleted the refinedstorage_nodes.dat of my main dimension, this solved the problem, but. all refined storage blocks are facing north, I have no  more disks etc.
now I'll try to figure out which entry in the .dat has broken my party...

**Comment by raoulvdberge** [comment]
#3454

**Comment by raoulvdberge** [comment]
Don't delete refinedstorage_nodes.dat. That has nothing to do with it.
