### ISSUE TITLE
[Bug] Recipes not properly queued on crafters

### ISSUE THREAD

**Issue by q009** [raoulvdberge/refinedstorage#217]
While trying to automate all the processor recipes using a single Solderer I noticed that recipes aren't properly queued on the same crafter. When I request a processor to be made it first creates the printed processors and then immediately proceeds to putting it back in along with redstone to make the full assembly. As a result it then fails to produce printed silicon, which is also required, because it had already put other things in.

**Comment by raoulvdberge** [comment]
The crafter doesn't care nor knows what order stuff is placed in a machine, solderer automation is always done with 2 solderers.

**Comment by q009** [comment]
Would it be too much to ask for to make it a thing then? It would solve all kinds of issues with multi-stage recipes that work on the same machine.

**Comment by raoulvdberge** [comment]
I'll look into it, but no promises
