### ISSUE TITLE
[1.12.2] Server crash Ticking player

### ISSUE THREAD

**Issue by bigenergy** [raoulvdberge/refinedstorage#2172]
- Minecraft: 1.12.2
- Forge: forge-1.12.2-14.23.5.2796
- Refined Storage: Refined Storage 1.6.12

Does this issue occur on a server? [yes/no] yes

#### If a (crash)log is relevant for this issue, link it here:

https://pastebin.com/yLzExrwX

**Comment by bigenergy** [comment]
UP

**Comment by raoulvdberge** [comment]
Discussion continues in #2235
