### ISSUE TITLE
[request] Make network transmitter be placed on any side

### ISSUE THREAD

**Issue by kreezxil** [raoulvdberge/refinedstorage#2173]
It feels odd that the network antenna has to always face up and be placed on top of the cable. Would like to see be placed on any side of the cable and pointing out from the side it was placed on.

Thanks for a wonderfully great mod!

We're using version 1.6.12

And it's many of my packs but right now [CobbleBlock](https://minecraft.curseforge.com/projects/kreezcraft-presents-cobbleblock?gameCategorySlug=modpacks&projectID=311931) and [World of Dragons](https://minecraft.curseforge.com/projects/world-of-dragons?gameCategorySlug=modpacks&projectID=270244)

**Comment by raoulvdberge** [comment]
![2020-04-26_15 37 43](https://user-images.githubusercontent.com/10358424/80309295-860c7000-87d4-11ea-8020-b3cbac54061d.png)

More than a year later, here you go!

**Comment by kreezxil** [comment]
Thank COVID!!! At least something good has come from that pandemic!

**Comment by raoulvdberge** [comment]
LOL
