### ISSUE TITLE
Server hanging somewhere related to external storages

### ISSUE THREAD

**Issue by CyaNox** [raoulvdberge/refinedstorage#2175]
#### Issue description:

I've been tasked by some friends to try and fix one of their server worlds. I however have come to the conclusion that I can't. The error is not perse an error but rather a hang or near infinite loop in refined storages external storage handling. Looking at the source code I'm unable to detirmine what is actually happening and the traces that I've tried (jstack / warmroast) don't really point to a particular integration either. Here is some information that may shed light on the situation:

A watchdog "crash" report: https://pastebin.com/mx7GaCxN (this also shows all the other mods in the pack).
A warmroarst snapshot post startup but at the point it hangs: http://cyanox.nl/sc/chrome_2019-02-06_11-06-09.png

The world itself is about 4.5GB and I have no idea where to start looking since there are several bases spread around with RS systems.

Do you have any ideas on what I could try? Or should we consider this world doomed?

#### Steps to reproduce:
Unknown.

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12.2
- Forge: 14.23.5.2810
- Refined Storage: 1.6.12 

Does this issue occur on a server: Yes

**Comment by Darkere** [comment]
I have in the past been able to find all external storages using a mod called Blood Debug. I am however not sure if that will work if the server is hanging like that.

Mcedit also appears to have an option to search for specific tile entities. I have no experience with that though.

Most packs nowadays also include a backup mod that automatically does backups every few hours. I would be interesting to know if this bug is reproducible.

**Comment by CyaNox** [comment]
> Mcedit also appears to have an option to search for specific tile entities. I have no experience with that though.

MCedit also breaks most modded worlds on its own.
 
> Most packs nowadays also include a backup mod that automatically does backups every few hours. I would be interesting to know if this bug is reproducible.

Unfortunately the backup thread that was responsible ... kept running even-though the main thread was dead ... resulting in all backups over time being overwritten with the "bad" world.

I am very familiar with NBT and the region format so could in theory peruse all them 4.5GB of data and remove all external storage busses ... but this is probably a multi day operation and still wouldn't actually solve the problem and just hide it.

**Comment by raoulvdberge** [comment]
Something is causing the network to constantly unload/reload, unfortunately I'm not able to know what is going on based off the provided information.
