### ISSUE TITLE
RS breaks JEI

### ISSUE THREAD

**Issue by HydrogenC** [raoulvdberge/refinedstorage#2176]
#### Steps to reproduce:
1. Add JEI/RS and some other tech mods (such as TE, MEK, IE) to MC
2. Press U to look up the usages of Iron Ore in JEI
3. Open the Redstone Furnace tab and the bug would be seen

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12.2
- Forge: 14.23.5.2811
- Refined Storage: 1.6.12
- JEI: 4.14.4.264

Does this issue occur on a server? [yes/no] nope

I don't think that this is related to RS. However, only if I remove RS will the issue be fixed. 

It shows that there are two pages about this machine (Redstone Furnace for example in the image).
![2019-02-09_10 28 35](https://user-images.githubusercontent.com/33123710/52515400-08ebee00-2c56-11e9-94a7-3218afd05add.png)
But if I click to the next page, I found it empty and I cannot click back.
![2019-02-09_10 28 40](https://user-images.githubusercontent.com/33123710/52515403-1a34fa80-2c56-11e9-8b61-064e40973c5d.png)
The same issue also happens to other mods, such as Ender IO.
![2019-02-09_10 29 27](https://user-images.githubusercontent.com/33123710/52515414-2a4cda00-2c56-11e9-88fb-499431295549.png)
![2019-02-09_10 29 31](https://user-images.githubusercontent.com/33123710/52515413-2a4cda00-2c56-11e9-87c9-16f2db0df5a0.png)

**Comment by schiegirl** [comment]
Just wanted to jump in here and state, we have this issue on our server as well, but it was well before we ever added Refined Storage. It actually started for us after we added Ender IO.

**Comment by raoulvdberge** [comment]
I can't reproduce this with only RS. Perhaps you do need to report this to Ender IO. However, first try updating Ender IO to see if the issue has been fixed already.
