### ISSUE TITLE
Server Crash with IC2 API

### ISSUE THREAD

**Issue by wylker** [raoulvdberge/refinedstorage#218]
Hey not sure if this is on your end or IC2 but I get daily server crashes with logs like this:

https://paste.ee/p/UOeOp

If it's on IC2 side I'll report it to them too.

**Comment by raoulvdberge** [comment]
I'm using the prefab energy net, I think you should report this on IC2's side as well.

**Comment by Lanse505** [comment]
Yup, I can Second this issue.
The sheer amount of console spam kills our testing server also :P

**Comment by raoulvdberge** [comment]
AFAIK this is an IC2 bug, but it might also be on my side. I'd have to talk to Player about this

**Comment by raoulvdberge** [comment]
Turns out this WAS an RS issue after all. Anyhow, it's fixed now :)
