### ISSUE TITLE
Inventory Tweaks inventory move items hotkey (s) not working

### ISSUE THREAD

**Issue by Mattthebum** [raoulvdberge/refinedstorage#2180]
#### Steps to reproduce:
1. Open Crafting Grid with multiple number of an item in inventory (oak planks, for e.g.)
2. Holding LShift and LCtrl, left click on any of item in player's inventory. 
3.
...

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12.2
- Forge: 14.23.5.2810
- Refined Storage: 1.6.12
- Inventory Tweaks: 1.64 + dev.145

Does this issue occur on a server? [yes/no] no

#### If a (crash)log is relevant for this issue, link it here:
n/a

**Comment by raoulvdberge** [comment]
should be fixed now
