### ISSUE TITLE
AutoCrafter makes items disappear from storage

### ISSUE THREAD

**Issue by Kirthbongar** [raoulvdberge/refinedstorage#2181]
#### Issue description:
When crafting items or have items in autocrafter they disappear from the gird.

#### What happens:
Place Iron ore in redstone smelter -> Importer pulls item -> Item is not in the grid and all previous amounts of the item are no longer there

#### What you expected to happen:
Put item in smelter -> Importer pulls items -> show up in grid.
Search for items -> see said items

#### Steps to reproduce:
1.I dont know when this issue started and when I go to my latest backup it is still happening with no errors on the server.
2.Pull recipe from autocrafter and missing item shows up along with previous quantity 
3. Add recipe back into autocrafter and items disappear from grid
...

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12
- Forge: 14.23.5.2768 
- Refined Storage: 1.6.8
-Mod pack All the Mods 3.

Does this issue occur on a server? [yes/no]
Yes. Total 3 players with only 1 player using refined storage.
#### If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here]

-Basic setup with grid, network storage, crafting grid, pattern grid, 12 Autocrafters.
-Break Controller 
-remove recipe from Autocrafter allows item to be seen. moving recipe to different autocrafter does not fix issue
-remove storage and break network drive then add drives back 
-Break all autocrafters and add recipes back removes all items tied to recipes from grid again

If further information is required please let me know.

Thank you.

**Comment by zhykzhykzhyk** [comment]
Is there an autocrafting task running? You can check it from a crafting monitor. Resource that are required by an autocrafting task will go into autocrafting buffer instead of the storage.

**Comment by raoulvdberge** [comment]
Please create a new issue with more detailed reproduction steps. Do try the new version while doing that as well, thank you.
