### ISSUE TITLE
Random crash with mrcrayfishvehicle.blockBlockVehicleCrate

### ISSUE THREAD

**Issue by Njet75** [raoulvdberge/refinedstorage#2185]
Random crash with mrcrayfishvehicle.blockBlockVehicleCrate

Crashes to Windows

1.Random crash when opening inventory
2.
3.
...

- Minecraft:1.12.2
- Forge:2468
- Refined Storage:refinedstorage-1.6.11
[crash-2019-02-23_18.47.57-client.txt](https://github.com/raoulvdberge/refinedstorage/files/2897122/crash-2019-02-23_18.47.57-client.txt)

Does this issue occur on a server? [yes/no] Dont know

#### If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here]

**Comment by raoulvdberge** [comment]
Hi, this is a MrCrayfishVehicle bug. Please report it to them, thanks.
