### ISSUE TITLE
Ignored NBT

### ISSUE THREAD

**Issue by cyber01** [raoulvdberge/refinedstorage#2189]
#### Issue description:
When you try to use Autocraft, to create a higher level of Mystical Agriculture Essential - Autocraft always requires the crystal specified in the recipe, and not its presence at all. This behavior is also when using other objects (and mods) that have a meta value (like energy, strength)
In this case, oreDict is enabled in the template.

#### Steps to reproduce:
1. For example with Mystical Agriculture
2. Make a template for autocraft from infurium essences to prudentum (cross essence, in the middle of the crystal)
3. Request a Prudential Essence in Autocrafts
4. The system will request exactly the crystal (with the same state as indicated in the recipe)

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12.2
- Forge: 2807
- Refined Storage: 3.3.2.79

Does this issue occur on a server? [yes / no]
Server and client

**Comment by raoulvdberge** [comment]
Yes, this intended.

**Comment by cyber01** [comment]
But because of this, autocraft is in most cases useless.

**Comment by raoulvdberge** [comment]
I think "most cases" is an overstatement. For NBT sensitive things you can use other crafting methods.

**Comment by cyber01** [comment]
Like what? How do you propose to solve the problem described above without using Autocraft?

**Comment by raoulvdberge** [comment]
You can insert only the dusts in a RFtools autocrafter with autocrafting, and the crystals with an RS exporter.

**Comment by cyber01** [comment]
That sounds like a way to get around the problem, not solve it.

**Comment by raoulvdberge** [comment]
That's why I said "you can use other crafting methods".
