### ISSUE TITLE
Allow processing patterns with big stacksizes

### ISSUE THREAD

**Issue by raoulvdberge** [raoulvdberge/refinedstorage#219]

**Comment by BootyToast** [comment]
I really tried to resist the urge to comment, but this got me excited.

**Comment by raoulvdberge** [comment]
@BootyToast 

Wtf is this hackery?!

![hackery](http://i.imgur.com/ZZDsBRd.png)

**Comment by BootyToast** [comment]
I need it now.

**Comment by raoulvdberge** [comment]
I wish I could give you an early build (official release is tomorrow), but it's untested and I'd rather give you something that I at least tested on a real world.

**Comment by BootyToast** [comment]
Awesome, man. I can't wait!

**Comment by Bartz24** [comment]
Yes! Need it now! xD

**Comment by raoulvdberge** [comment]
Official release for today is postponed unfortunately :(

Working on interdimensional networks as an additional feature...

**Comment by BootyToast** [comment]
Go ahead and implement one of the most requested features of all time, see if I care! :P

**Comment by Bartz24** [comment]
Nice! Do they take massive power :P

**Comment by raoulvdberge** [comment]
Network transmitter takes <base energy usage in config, default is 20> + (distance * <multiplier in config, default is 2>) energy usage per tick.

And the network receivers take <energy in config, default is 4>.

Also it's pretty expensive :P

**Comment by Bartz24** [comment]
2 RS/t seems a little low (20 + 2 * 500 blocks = 1020 RS/t)
Yeah, it's a lot at first, but mid-game most people are generating 600-800 and could easily add another 200

But, there's a config and the recipe better be expensive :)

**Comment by raoulvdberge** [comment]
Sure, I could make it higher really.  What about 4 as a multiplier and 50 as base?

50 + 4 * 500 blocks = 2050 RS/t

**Comment by BootyToast** [comment]
How will that multiplier work with different dimensions.

**Comment by raoulvdberge** [comment]
I won't add in support for cross dimensions just yet, but it'll be a thing in a later update
