### ISSUE TITLE
Having multiple crafting recipes for same item

### ISSUE THREAD

**Issue by wafebreaker** [raoulvdberge/refinedstorage#2192]
Hey, why is it not possible to have like 2 crafting recipes for the same Item? For Example: Either I make a chest through 8 planks or 4 chests through 8 logs. The Crafter only takes the last (i think) recipe and do it like that. So when i have 2 pattern, 1 with logs and 1 with normal wood it only would take the woods and if there is no wood it cant craft.

Is it a feature or just not possible to implement? Or am i to stupid to know how?

**Comment by raoulvdberge** [comment]
For regular recipes, RS only uses 1 crafting pattern. For processing patterns, it uses multiple to spread the processing.

**Comment by wafebreaker** [comment]
I do know that this is not possible at the moment. But this is not my question. Why is this feature not implemtend? Is it to hard to code? I mean this would be a great feature if the system would look which crafting pattern would be the best to use.

**Comment by raoulvdberge** [comment]
Ah, no, the current system is as it will stay.
