### ISSUE TITLE
[1.12.2]Mayor tps lag 

### ISSUE THREAD

**Issue by CraftalotReloaded** [raoulvdberge/refinedstorage#2193]
#### Issue description:
My storage system delays the server by about 70 to 80 sec when the server loads and about half of that when i edit any part of my storage system even if i disconnect everything aside from disk drives, fluid storage and grids

Additional info: 
-This issue remains the same with all forge optimizations turned off and with only refinedstorage installed
#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12.2
- Forge: 14.23.5.2811
- Refined Storage: refinedstorage-1.6.12

Does this issue occur on a server? [yes/no]
yes
#### If a (crash)log is relevant for this issue, link it here:

This crash report was generated before i raised the watchdog timer which allowed the server to load: https://gist.github.com/CraftalotReloaded/62de6f84a0bd67bee9e326d21942f09c

**Comment by lab3** [comment]
Also seeing alot of lag.  Here is a screenshot showing where the CPU is getting eaten up

![Screenshot 2019-03-19 21 41 22](https://user-images.githubusercontent.com/1099358/54656812-230abe80-4a95-11e9-90f2-912d75115790.png)

**Comment by CraftalotReloaded** [comment]
It doesn't really cause much constant lag, only when editing certain storage systems regardless of their size and when they get loaded

**Comment by lab3** [comment]
The cpu is constantly churning on that whenever the server is running.  It's not when editing.

**Comment by CraftalotReloaded** [comment]
That is showing that it is constantly running, but now how much it uses, show the thread cpu time tab

**Comment by raoulvdberge** [comment]
Hi please create a new issue with an included NPS performance report. Thank you

https://refinedstorage.raoulvdberge.com/wiki/profiling
