### ISSUE TITLE
Server Crash after starting a crafting operation (Requestify)

### ISSUE THREAD

**Issue by BrainInBlack** [raoulvdberge/refinedstorage#2197]
#### Issue description: Don't know if that is an issue on your end or on the Requestify end. But the server crashes as soon as i kick off a crafting operation with resources that are kept in storage via Requestify.

The reason why i bring this up here, is this line in the crashlog:

`java.lang.NoSuchMethodError: com.raoulvdberge.refinedstorage.api.autocrafting.ICraftingManager.request(Lcom/raoulvdberge/refinedstorage/api/network/node/INetworkNode;Lnet/minecraft/item/ItemStack;I)Lcom/raoulvdberge/refinedstorage/api/autocrafting/task/ICraftingTask; [...]`

#### Steps to reproduce:
1.  Start a crafting operation with something that is "refilled" via Requestify

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12.2
- Forge: 14.23.5.2814
- Refined Storage: 1.6.14

Does this issue occur on a server? yes

#### If a (crash)log is relevant for this issue, link it here:

https://gist.github.com/BrainInBlack/fa9af312def63dd523153231b75d7daa

**Comment by raoulvdberge** [comment]
Report it to Requestify please

**Comment by BrainInBlack** [comment]
So it's an issue on their end, thank you for the information.
