### ISSUE TITLE
What are your plans

### ISSUE THREAD

**Issue by plumpudding** [raoulvdberge/refinedstorage#220]
I really like your mod.
Basic question:
What are your plans? 
Do you want to re-implement every feature of AE2? 
Or do you want to stick to unlimited networks and your current storage space logic?
Do you want to implement multipart stuff?

As this is an issue I will demand a specific thing: 
Could you please write a roadmap / what the mod should be like in the future?

Thanks for your time..

**Comment by raoulvdberge** [comment]
My plans is to implement everything that is on the issue tracker at the moment. The goal of the mod is not to implement EVERY AE2 feature, but the most important ones (this is already done).

Every machine will stay a block, no multiparts. Of course Forge Multipart will work on cable parts in the future.

As for roadmap; read the issue tracker tickets with label "feature request".
