### ISSUE TITLE
Pattern Grid

### ISSUE THREAD

**Issue by Notlucky101** [raoulvdberge/refinedstorage#2200]
#### Issue description:
Empty patterns do not appear until I click on them.

**Comment by Darkere** [comment]
Please fill out the entire template. Your description is not enough to even start to figure out what is wrong.

**Comment by raoulvdberge** [comment]
I will close this issue. Please open a new issue where you follow the issue template.

**Comment by raoulvdberge** [comment]
Reopening this as I was able to confirm the issue myself.

**Comment by BrainInBlack** [comment]
The same behavior can be observed with filters in a Grid.

The strange thing is that as soon as you "fix" the issue by clicking on the seemingly empty spot, it will stay fixed for a while but after a random amount of time they disappear again.

**Comment by BrainInBlack** [comment]
After some further testing, it looks like the issue returns as soon as the client unloads the affected grid, in other words if the client moves far enough away, the issue returns (same for changing dimensions and so on).

**Comment by boosterdev** [comment]
this also happends when an area is chunkloaded

**Comment by boosterdev** [comment]
> After some further testing, it looks like the issue returns as soon as the client unloads the affected grid, in other words if the client moves far enough away, the issue returns (same for changing dimensions and so on).

this also happends when an area is chunkloaded

**Comment by boosterdev** [comment]
after downgrading refined storage to 1.6.12 the filters reappear inplace, so basicly they are hidden and not functioning, but still there.

**Comment by Tntdruid** [comment]
I get that too, using Refined Storage 1 6 14

**Comment by raoulvdberge** [comment]
Finally fixed! This one was difficult to find.
