### ISSUE TITLE
Unable to remove Environmental Tech's Pladium from system

### ISSUE THREAD

**Issue by xenoflot** [raoulvdberge/refinedstorage#2201]
#### Issue description:
Playing Sky Odyssey. I put some of Environmental Tech's Pladium blocks into the RS but I'm unable to get them back out. I'll cross post to S:O's git in case it's one for them.

#### Steps to reproduce:
1. Put Pladium block into RS
2. Try to remove
3. Fail to remove
...

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12.2
- Forge: 14.23.5.2815
- Refined Storage: 1.6.12
- Refstor Addons 0.4.3

Does this issue occur on a server? [yes/no]

#### If a (crash)log is relevant for this issue, link it here:

Nothing interesting in the log

**Comment by raoulvdberge** [comment]
Closing this as your issue seems resolved from the FTB thread.
