### ISSUE TITLE
Lag accessing items in wireless grid after creating Reborn Storage 9x9x9

### ISSUE THREAD

**Issue by timepieces141** [raoulvdberge/refinedstorage#2204]
#### Issue description:

I created a Reborn Storage 9x9x9 and connected it to my Refined Storage. Now there is a lag when trying to take/place items from/to the wireless grid. I have verified that there is not such a lag when using the Crafting Grid directly. However, when I first access the Crafting Grid, it appears to be empty for a few seconds.

#### What happens:

Lag when using the Wireless Grid

#### What you expected to happen:

Less or no lag, like it was before building the Reborn Storage

#### Steps to reproduce:
1. Have a RS setup with about 2M items (includes 24 64K discs and about 20 Quantum Storage units holding items with more than 30k count)
2. Create and hookup a 9x9x9 Reborn Storage with 274 CPUs and 69 Storage
3. Craft a wireless grid and try to exchange items to/from personal inventory
...

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge: 12.18.3.2477
- Refined Storage: 1.2.26
- RebornCore: 2.13.6.140
- reborncore-MCMultiPart: 2.13.6.142
- RebornStorage: 1.0.3.30

Does this issue occur on a server? no, single player world

#### If a (crash)log is relevant for this issue, link it here:

I have an .nps file per the RS wiki instructions, but I am not sure where to put it. So, for now I have put it here: https://drive.google.com/open?id=1wsTKbtGyZq_YvZB3RxqTvLIsCCzEwnvk

**Comment by Aang23** [comment]
If I remember correctly a related issue was fixed in 1.12.2.

**Comment by raoulvdberge** [comment]
1.10.2 is not supported.
