### ISSUE TITLE
(Suggestion) Auto Request items

### ISSUE THREAD

**Issue by Feewe** [raoulvdberge/refinedstorage#2206]
It would be fitting for the mod to have some kind of always have x amount of this crafted in your system.. I can with confidence say that me and many others would love to have this function in RS.. It could be another monitor like or somekind of block/multiblock, what you think would be best and easiest to add in and maintain.. It's just a hassle to use the interface mechanic.

**Comment by Darkere** [comment]
With just RS you can do this by combining an interface with a crafting card and an external storage.

There is also an addon mod called Requestify that does exactly what you are looking for.

**Comment by Tntdruid** [comment]
https://minecraft.curseforge.com/projects/rs-requestify
