### ISSUE TITLE
AE2 and RS integration not possible?

### ISSUE THREAD

**Issue by Milii20** [raoulvdberge/refinedstorage#2207]
#### Issue description:

Rs and AE2 cannot work together, this includes:
RS cant read ae2's storage
ae2 cant read RS storage
RS CAN deposit items on ae2's network but not take them out since it cannot see the contents of said network
ae2 CAN deposit items on RS network but not take them out since it cannot see the contents of said network

#### What happens:

tried all the combinations i could thing:
RS interface on AE2 Storage bus, ae2 cant see RS network (but ae2 can deposit stuff into RS network using said interface)
AE2 interface on RS External Storage, RS cant see AE2 Network (but same as before, RS can deposit stuff into AE2's network)
Interface on Interface (had to try it, no resoults)
External Storage on Storage Bus, same as before

The only contents they see is what's displayed on the interface itself, i mean, if i say on the RS Interface "Export Bread" then the AE network can see said bread, and works the same the other way arround, bread on the AE interface can be seen by RS external storage, but nothing aside from that

#### What you expected to happen:

AE2's network seeing RS items, and viceversa

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12.2
- Forge: forge-1.12.2-14.23.5.2814-universal
- Refined Storage:  refinedstorage-1.6.14
- AE2: appliedenergistics2-rv6-stable-6

Does this issue occur on a server? Yes

If there is something i am doing wrong, please tell me, i may not be connecting this right

**Comment by Darkere** [comment]
Yes, this is not possible. The amount of work going into such a feature is much better spent elsewhere disregarding all other factors.

**Comment by halvalla01** [comment]
It would be cool if you could put an AE storage bus on the RS controller and vice versa. Or maybe an addon requiring both mods which would act as a storage bridge. That'd be neat to see
