### ISSUE TITLE
(Suggestion) Make redstone mode only available for players with build security permission.

### ISSUE THREAD

**Issue by halvors** [raoulvdberge/refinedstorage#2208]
Make redstone mode only available for players with build security permission.

**Comment by Darkere** [comment]
Can you elaborate on your reasoning?

**Comment by halvors** [comment]
Well, some machines might only be supposed to be accessed by users with permission.

Like the Grid, i want users to be able to deposit items, but not alter redstone mode as it should only be active when i send a redstone signal from a computer controlling when it should be available.

Another thing is that in the security manager a user with "Change" permission might disable the security manager completely giving access to all other security permissions by setting "only active when redstone signal".

**Comment by raoulvdberge** [comment]
Sorry, this will be a wontfix. If I do redstone mode, there is no clear line of what other side "configuration" buttons need protecting.
