### ISSUE TITLE
[Suggestions] Some more JEI integration

### ISSUE THREAD

**Issue by Darkere** [raoulvdberge/refinedstorage#2210]
For recipes that are not available in JEI I often find myself having to craft everything until that point to creste the recipe. This is especially annoying for fluids.

My idea is to make it possible to drag and drop items from JEI into the pattern grid.

In a similar vein with the new bookmark feature from JEI I often find myself typing in itemnames  of items that I can already see on the left side screen. 

Idea here is to add a shorcut for inserting itemnames. For example control  + click on an item inserts the name into the search bar. Drag and drop onto the searchbar might be more intuitive though.

**Comment by raoulvdberge** [comment]
The drag and drop JEI code is already there, but due to a bug in JEI unfortunately this cannot work. When there is dragging code present, you can no longer look up recipes and usages.

**Comment by raoulvdberge** [comment]
https://github.com/mezz/JustEnoughItems/issues/1307
