### ISSUE TITLE
Make fluids work with JEI shortcuts 

### ISSUE THREAD

**Issue by Darkere** [raoulvdberge/refinedstorage#2211]
#### Issue description:
 Pressing the JEI recipe button on fluids does not lead to the JEI page of that fluid.

#### What happens:
Nothing
#### What you expected to happen:
Opening of JEI
#### Steps to reproduce:
1. Insert fluid into pattern grid 
2. Hover over and press JEI shortcut
3.
...

#### Version (make sure you are on the latest version before reporting):

- Minecraft:1.12.2
- Forge:2815
- Refined Storage:1.6.14

Does this issue occur on a server? [yes/no]
Yes

### Addional notes 

~~Just realized I should check if it works in the Fluid Grid. Will check once I have the time.~~
It does work in the Fluid grid.

**Comment by raoulvdberge** [comment]
Good point!
