### ISSUE TITLE
[1.12.2] Poor performance with high item counts

### ISSUE THREAD

**Issue by CraftalotReloaded** [raoulvdberge/refinedstorage#2212]
An rs system with just drives and a few million items is already enough to easely delay a tick by 40 seconds or more upon being loaded or edit(if you take out drives with items in them).
This makes rs worthless for real mass storage as about 10 million items are sufficient to time everyone out before it loads and thus nobody can ever get near that system anymore, even removing the controller causes this delay for some reason.

- Minecraft: 1.12.2
- Forge: 14.23.5.2811
- Refined Storage: Refined Storage 1.6.14

Does this issue occur on a server? [yes/no]
yes(Same does however occur in singleplayer)

**Comment by Darkere** [comment]
Please run some profiling on the server when this happens to find out what causes this. Possibly another mods interacts badly with the system. I've had bigger systems plenty of times and have never had players get timed out due to them. 

https://refinedstorage.raoulvdberge.com/wiki/profiling

**Comment by CraftalotReloaded** [comment]
Even with just this mod it happends

**Comment by CraftalotReloaded** [comment]
And it ain't constant lag, it just locks everything up so badly that not even a profiler can spot it

**Comment by Darkere** [comment]
Good that probably makes it possible to fix the issue, if we can find out what causes it with the profiling info.

**Comment by CraftalotReloaded** [comment]
It are spikes which profilers do not manage to catch

**Comment by Darkere** [comment]
So the entire PC freezes when this happens? Only thing I can think of that could cause this is a broken or very slow hard drive/ssd? That would probably also cause other issues though so.. yeah not sure what could cause that.

**Comment by CraftalotReloaded** [comment]
No, it just turns the entire server unresponsive for quite a bit to the point that the profilers do not spot it

**Comment by raoulvdberge** [comment]
Can you give me reproduction steps, with just RS installed? And something less vague than "just insert a lot of items". Tell me exactly what you're doing.

**Comment by CraftalotReloaded** [comment]
Refined storage simply cannot handle a lot of items efficiently, simple as that
