### ISSUE TITLE
Another crafting performance issue

### ISSUE THREAD

**Issue by Darkere** [raoulvdberge/refinedstorage#2213]
I just realized that no one has created an issue for the crafting lag that was introduced when the crafting speed was changed in 1.6.12.

#### Issue description:
Tps lag when crafting with lots of crafting CPU's
#### What happens:
TPS goes down to 2.

#### Steps to reproduce:
1. Make Reborn Storage Autocrafter. (Mine is Max size 16x16x16 with 1 crafting storage the rest are cpus).
2. Setup pattern for Sextuple compressed cobblestone. 
3. Connect creative drawer with cobble.
4. Request 2 Sextuple compressed Cobblestone (Anything more gets caught by the complexity check for me)

#### Version (make sure you are on the latest version before reporting):

- Minecraft:1.12.2
- Forge:2815
- Refined Storage:1.6.14

Does this issue occur on a server? [yes/no]yes

#### Profiling
https://www.dropbox.com/s/xkcbyg9bgcomy0l/RSCraftingWithoutOpeningCraftingMonitor.nps?dl=0
Looking at that this might be on reborn Storage? Not sure if he can fix this with the current API but I will post on his git too.

https://www.dropbox.com/s/5y8owgth6nqirij/RSCraftingWithMonitor.nps?dl=0
That looks like the monitor is updating on every change instead of periodically. Related to #2132

**Comment by raoulvdberge** [comment]
Thanks, I will look into this when I have time.

**Comment by Theyoungster** [comment]
Got a similar issue. Server tries to kill itself when you send a huge processing load through (e.g. 55,000 orders).

If a crafter is pointed to a machine or chest with a processing recipe, and that machine or chest fills up while an extreme number of orders are in the backlog, the server pretty much kills itself.

**Comment by Darkere** [comment]
This is a separate Issue @Theyoungster I had 0 machines involved in this. If you could do some profiling and post another issue that would be great.

https://refinedstorage.raoulvdberge.com/wiki/profiling

**Comment by Theyoungster** [comment]
Alright. I suspect it's heavily related, but I'll post as a separate issue.

**Comment by Darkere** [comment]
My issue is mostly fixed in this https://github.com/TechReborn/RebornStorage/pull/149

Not sure if there are other things that can be done without changing how the crafting code works.
