### ISSUE TITLE
Release excess crafting material before the craft is done.

### ISSUE THREAD

**Issue by Darkere** [raoulvdberge/refinedstorage#2214]
#### Issue description:
In many crafts, some material is left over and not needed. It currently stays in the internal crafting memory hogging resources that can be used elsewhere.
#### What happens:
Excess resources are not accessible until craft finishes
#### What you expected to happen:
Resources that won't get used by the auto crafting system should be added to the storage.
#### Steps to reproduce:
1. Autocraft recipe that produces excess. For example sword.
2. Notice excess sticks and wood only appear after crafting is finished
3.
...

#### Version (make sure you are on the latest version before reporting):

- Minecraft:1.12.2
- Forge:2815
- Refined Storage:1.6.14

**Comment by raoulvdberge** [comment]
Sorry, this will be a wontfix. Only the root items go back in to the main inventory, from the initial craft.
