### ISSUE TITLE
Certain Processing Oredict patterns will redefine itemstacks in all mods

### ISSUE THREAD

**Issue by al132mc** [raoulvdberge/refinedstorage#2216]
#### Issue description:
When setting certain items (so far only gold ingots and iron ingots) to use processing oredict patterns with 2+ items in a single input slot, the itemstack will be redefined in all recipes, including modded recipes to use the same quantity. Regular crafting works okay in spite of this, but modded recipes that use the same input item will be re-defined to use whatever the quantity is in the pattern input which essentially breaks them, so this is not just a cosmetic inconvenience in JEI. **This bug will persist even after restarting the game** unless the pattern is changed.

#### What happens:
See above

#### What you expected to happen:
The item quantity will not be re-defined in all recipes

#### Steps to reproduce:
(Updated modpack instance with **only** most recent versions of RS, JEI, and Forge, no other mods)
1. Place down a controller (creative or regular + powered)
2. Place an adjacent pattern grid
3. Create a oredict processing pattern with 2+ gold or iron ingots in an input slot and anything in the output slot. Check JEI uses for that input item.
4. Re-defining the pattern to only use 1 input in a slot fixes this bug. Restarting the game without changing the pattern **does not fix this**

Curiously enough, I have only been able to reproduce this issue with gold or iron ingots as inputs so far.

[DEMONSTRATION](https://gfycat.com/hairyhighlevelazurewingedmagpie)

#### Version (make sure you are on the latest version before reporting):
- Minecraft: 1.12.2
- Forge: 14.23.5.2836
- Refined Storage: 1.6.14
- JEI: 1.12.2-4.15.0.276

Does this issue occur on a server? [yes/no]
Unsure, only tested in single player

**Comment by Genesiz13** [comment]
I've been having the same issue. However this only happens to me when i check the oredict option.

**Comment by CrossVas** [comment]
The same to me. I've been able to reproduce this.

**Comment by ThePoshTux** [comment]
Also been able to reproduce. The recipe crafts normally in a manual crafting bench but in an RS system the excess is voided. The stack size change also causes jei's stacks to become redifined (a possible lead, will test soon). even when specifically instructing a recipe that is not causing the issue to not use a stack, the pattern will still use that errored quantity. For example creating a processing pattern (another lead?) that takes 64 cobble and turns it into 64 gravel using an irrelevant method will cause ANY other recipe in RS or JEI to display 64 cobble. however manual crafting is completely unaffected. As a temporary workaround. perhaps disable the ability to vary the input amount of a pattern.
