### ISSUE TITLE
Weird Behaviour: 

### ISSUE THREAD

**Issue by STOKE-STER** [raoulvdberge/refinedstorage#2217]
#### Issue description:
Items appear to have more in the system than we have actually deposited.
#### What happens:
System says we have 10 apples, we go to remove 10, it gives us 5 and shows five still in the system it refuses to dispense.
#### What you expected to happen:
We expected to withdraw all 10 apples.
#### Steps to reproduce:
Unkown how to replicate bug, but it's happened to alot of different items.
...

#### Version (make sure you are on the latest version before reporting):

- Minecraft:1.12.2
- Forge:1.12.2
- Refined Storage:1.6.14

Does this issue occur on a server? [yes/no]
Yes
#### If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here]

**Comment by Darkere** [comment]
It would be important to know what you are using to store these items?

**Comment by STOKE-STER** [comment]
forge-14.23.5.2835

**Comment by STOKE-STER** [comment]
A server restart has not fixed this issue and it appears to now be happening to more items.

**Comment by STOKE-STER** [comment]
we're using 3 x 4k storage disks and 2 x 64k storage disks (yes they're item disks not fluid)

**Comment by STOKE-STER** [comment]
Update: Removing as many as the duplicated items as we can, removing all drives and putting them back in, fixes it for the specific items we removed. but the items we are unaware of having this bug remain "duplicated" and un removeable

**Comment by STOKE-STER** [comment]
https://www.youtube.com/watch?v=R8sROjpa5ac
Here's a video of the bug

**Comment by STOKE-STER** [comment]
Ended up being a disc drive that was bugged, we put the bugged disc into a disc manipulator to get our items off and destroyed the buggy disc, systems working again.
