### ISSUE TITLE
Crash On Startup (Single Player)

### ISSUE THREAD

**Issue by mechjacktv** [raoulvdberge/refinedstorage#2219]
#### Issue description:

I've been playing this save for a while now and after adding a bunch of new Crafters things went south. Now I can't even start my world without a crash.

#### What happens:

When I try to load the save it crashes.

#### What you expected to happen:

I can start and play my save.

#### Steps to reproduce:
1. Select my save from the Single Player menu
2. Crash with stack trace

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12.2
- Forge: 14.23.5.2815
- Refined Storage: 1.6.14

Does this issue occur on a server? no

#### If a (crash)log is relevant for this issue, link it here:

https://pastebin.com/pvsBPM8g

**Comment by mechjacktv** [comment]
Tested with latest Forge (14.23.5.2836) and the problem still occurs.

**Comment by raoulvdberge** [comment]
Discussion will continue in the other issue report (see above).
