### ISSUE TITLE
Autocrafting : Loss of items (Server)

### ISSUE THREAD

**Issue by Rouhol** [raoulvdberge/refinedstorage#2220]
#### Issue description:

When I run an autocrafting on my server, and I unload a chunk (Also when I disconnect). The craft is cancelled, the items are no longer in my system.

#### What happens:

The craft is cancelled, the items are no longer in my system.

#### What you expected to happen:

The craft continues when I reconnect

#### Steps to reproduce:
1. Create an autocraft system for yourself
2. Launch a craft on server
3. Unload the chunk or disconnect.
4. Reconnect to the server again.

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12.2
- Forge: 14.23.5.2768
- Refined Storage: 1.6.12

Does this issue occur on a server? YES

**Comment by Darkere** [comment]
This bug was fixed a few versions ago. Is it possible that you mixed up the versions?
I tried and could not reproduce this.
