### ISSUE TITLE
Destructors not being linked correctly to RS networks.

### ISSUE THREAD

**Issue by xxMattewxx** [raoulvdberge/refinedstorage#2222]
#### Issue description:
Before getting my crash (problem has been posted in a separate issue), I was unable to add destructors to the network, even though they were all connected.
#### What happens:
Inserting a lot of destructors do not work, you have to insert them either one-by-one or in small amounts.
#### What you expected to happen:
Adding destructors to work correctly.
#### Steps to reproduce:
1. Make a long array of connected destructors (in my case it was around 64 destructors)
2. Link these destructors to a RS network (in my case, I used a cable).
3. Destructors should not work at all in this step (they won't be breaking any block, I mean.)

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12.2
- Forge: 14.23.5.2815
- Refined Storage: 1.6.12

Does this issue occur on a server? [yes/no] not tested.

I believe it has a connection to the https://github.com/raoulvdberge/refinedstorage/issues/2221 issue. Maybe breaking the destructors that were not correctly linked causes the crash? I'll look into that soon when I have time.

**Comment by raoulvdberge** [comment]
I guess it is linked to your linked issue.
