### ISSUE TITLE
Autocrafting with Artisan's Worktable tools consumes full tool.

### ISSUE THREAD

**Issue by Thyrial** [raoulvdberge/refinedstorage#2224]
#### Steps to reproduce:
1. Autocraft a recipe that uses Artisan's Worktable tools in a pack that uses them. (Dungeons and Dragons and Space Shuttles is a good example.)

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12.2
- Forge: 14.23.5.2822
- Refined Storage: 1.6.14

Does this issue occur on a server? yes

#### If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here]

**Comment by Darkere** [comment]
This is the intended behavior. Not a great solution to just delete the item but if it was easy to detect such things, making them work would be easy...

1.13/1.14 will change the way reusable items work completely and as such implementing a solution for 1.12 that needs to be ripped out right after is not something people want to spend their time on.
