### ISSUE TITLE
Fluids Disappear when inserted into grid, imported by importer

### ISSUE THREAD

**Issue by LordMZTE** [raoulvdberge/refinedstorage#2225]
#### Issue description:
Fluids Disappear when i try to get them into the system
#### What you expected to happen:
I'm able to take out fluids but when i try to put them into the fluid grid or import them with an importer, they simply disappear no matter of they are stored on a drive or externally
#### Steps to reproduce:
1. Insert Fluid into Fluid grid or import with an importer
#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12.2
- Forge: 14.23.5.2825
- Refined Storage: 1.6.14

Does this issue occur on a server? [yes/no]
yes
#### If a (crash)log is relevant for this issue, link it here:
not crashing

im using the all the mods 3 modpack on version 5.12.1

**Comment by Darkere** [comment]
Working just fine for me. Check if you have a high priority external storage somewhere.

**Comment by LordMZTE** [comment]
> 
> 
> Working just fine for me. Check if you have a high priority external storage somewhere.

i do but its whitelisted to only XP and it gets destroyed too
