### ISSUE TITLE
Industrial Craft 2 Forge Hammer bug

### ISSUE THREAD

**Issue by NegativeIQ** [raoulvdberge/refinedstorage#2228]
#### Issue description: 
Industrial craft Forge Hammer is not being reused.
#### What happens:
If i try to craft a recipe that requires Forge Hammer (directly or as subitem - same problem) it tries to use unused/undamaged Hammer (or craft it since i have recipe for that).
#### What you expected to happen:
Use damaged tools first (in my case Forge Hammer), and only then use or craft new ones.
#### Steps to reproduce:
1. Get latest release of IC2 and Refined Storage for MC 1.12.2
2. Create forge hammer and IC2 Basic Machine Casing patterns
3. Try crafting iron plate or basic machine casing (its 8 iron plates). You will notice it tries to use same amount of forge hammers as amount of iron plates that are needed (using one Forge Hammer for each plate instead of damaging existing ones)
Here is how it looks on my MC [Imgur](https://i.imgur.com/kNq0Opw.png)

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12.2
- Forge: 1.4.23.5.2836
- Refined Storage: 1.6.14
- IC2: 2.8.125-ex112
Does this issue occur on a server? [yes/no]
No idea, im testing without server

#### If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here]

**Comment by Darkere** [comment]
Duplicate of #2224

**Comment by NegativeIQ** [comment]
Thx, closing these one for easier tracking
