### ISSUE TITLE
Many issues with SpongeForge

### ISSUE THREAD

**Issue by Alleluid** [raoulvdberge/refinedstorage#223]
Several things are messed up. The grid GUI is acting very strangely, I put it 5 buckets it shows 10, I take one out it shows 8, stuff like that. If I configure an interface to keep one bucket in it, I can't remove that bucket from the GUI. There are probably more issues that I don't know about.

**Comment by raoulvdberge** [comment]
I do not support SpongeForge

**Comment by Alleluid** [comment]
Alright, well I don't know how I'm going to have a server on 1.10 then.

**Comment by JorVaCoding** [comment]
Was spongeforge on the client or the server?

**Comment by Alleluid** [comment]
Uh, server.

**Comment by gabizou** [comment]
@Alleluid If you can open an issue on [SpongeForge's](https://github.com/SpongePowered/SpongeForge/issues/new) repo with all the version details preferably, and make sure that you're using the very latest build for 1.10.2 (which is 1601). Please note the full mod list and plugin list and preferably a way to reproduce in order.

**Comment by raoulvdberge** [comment]
I'm going to close this issue, please report a bug at SpongeForge's side.

**Comment by FiveEYZ** [comment]
> Several things are messed up. The grid GUI is acting very strangely, I put it 5 buckets it shows 10, I take one out it shows 8, stuff like that.

never happen after a few days of usage ( with and without sponge)


> If I configure an interface to keep one bucket in it, I can't remove that bucket from the GUI. 

this also happen without sponge, here is a from the log: http://pastebin.com/raw/H49VPqFF
