### ISSUE TITLE
If I work with some MODs, Minecraft crashes at load.

### ISSUE THREAD

**Issue by byron10000** [raoulvdberge/refinedstorage#2230]
### If I work with some MODs, Minecraft crashes at load.
###Main Mods（Abbreviation）:
Mek 
IC2
RS(1.16.4)
IE(0.12--89)
JEI
AA
CRT
CS4
OC
Cyclic
MM
RFT
FTBu
[crash-2019-05-05_18.31.30-client.txt](https://github.com/raoulvdberge/refinedstorage/files/3145436/crash-2019-05-05_18.31.30-client.txt)

**Comment by Darkere** [comment]
This has nothing to do with Refined Storage why are you posting here?

You either need to downgrade Mcjtylib or update xnet.

**Comment by byron10000** [comment]
Thank you.


On 05/05/2019 21:31, Darkere wrote:

This has nothing to do with Refined Storage why are you posting here?

You either need to downgrade Mcjtylib or update xnet.
