### ISSUE TITLE
remove or add config in gui sort by InvTweaks .Please !

### ISSUE THREAD

**Issue by Taokyla** [raoulvdberge/refinedstorage#2231]
#### Issue description:
using sort by invtweak will freeze the game.just
#### Steps to reproduce:
1.having 300+ diff item
2.using sort by invtweak in gui
3.game down!
...

#### Version (make sure you are on the latest version before reporting):

- Minecraft:1.12.2
- Forge:14.23.5.2836
- Refined Storage:1.6.14

Does this issue occur on a server? [yes/no]
no
#### If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here]

**Comment by raoulvdberge** [comment]
Not much we can do here, RS falls back to InvTweak's algorithm for comparing stacks.
