### ISSUE TITLE
Only work on Redstone tick activation.

### ISSUE THREAD

**Issue by Farlarzia** [raoulvdberge/refinedstorage#2232]
Issue description:
Playing using Direwolf20 1.12 v2.5.0
Refined storage interfaces (Specifically tested with constructor and destructor) which have options to only work while receiving a redstone signal do not work, if the redstone pulse is only 1 tick in length. Furthermore, even pulses above 1 tick can be inconsistent in activating the linked system, unless the pulse is of a certain length.

What happens:
Systems set to activate on redstone signal not activating on short redstone pulses.
What you expected to happen:
Systems set to activate on redstone signal to active on short redstone pulses

Steps to reproduce:
1.Create a short redstone pulse (sequencer, EnderIO redstone conduit  timer filter, etc)
2.Link a refined storage system set to redstone only to the redstone
3.Watch as the linked systems do not activate

Version:
- Minecraft: 1.12.2
- Forge: 14.23.5.2821
- Refined Storage: 1.6.12 (I understand this is not the latest version, but the 2 change logs don't mention anything relevant to this issue as far as I can see. If I'm mistaken I apologise).

Does this issue occur on a server? [yes/no]
Yes

**Comment by raoulvdberge** [comment]
RS devices can only detect whether it can run when it can according to it's speed rules. Your redstone signal needs to be long enough so it can be picked up, since the device needs to be eligible for an update according to the amount of speed upgrades.
