### ISSUE TITLE
 Fluid Support - Storage Monitor

### ISSUE THREAD

**Issue by mrdeadlocked** [raoulvdberge/refinedstorage#2234]
#### Steps to reproduce:
1. Try to put fluid in storage monitor.
...

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12.2
- Forge: 14.23.5.2836
- Refined Storage: 1.6.14

Does this issue occur on a server? [yes/no] yes

#### If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here]
![image](https://user-images.githubusercontent.com/461352/57549449-92808a00-7331-11e9-89ff-74b4499c66ca.png)

**Comment by raoulvdberge** [comment]
Implemented for 1.15.2

**Comment by TrayHard** [comment]
Hello, I'm playing FTB Sky Adventures (v1.5.0 with minecraft v 1.12.2) with Refined Storage (1.6.12). Do I understand correctly that I don't have this feature in my version?

**Comment by Darkere** [comment]
Yes. It is only available in 1.15 and higher.
