### ISSUE TITLE
Game crashing when displaying reborn storage

### ISSUE THREAD

**Issue by Testo0987** [raoulvdberge/refinedstorage#2239]
#### Issue description:
I opened the Crafting Manager which was connected to a reborn storage max size multiblock

#### What happens:
The game just force closes into a the multiplayer page for some reason, even though i'm in singleplayer

#### What you expected to happen:
I expect to be able to access the inventory of it

#### Steps to reproduce:
1. Start a network
2. Make a max size (16x16x16) reborn storage multiblock
3. Fill it with some crafting storages.
...

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12.2
- Forge: v2815
- Refined Storage: 1.6.14

Does this issue occur on a server? [yes/no]
No, singleplayer

#### If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here]

**Comment by Testo0987** [comment]
Instead of having about 64 crafting storage blocks, i now have 1 and the rest CPUs and it loads fine now. I'm not a coder, but i think if the crafting manager would only load what was being shown, instead of all thousands of slots at a time, it wouldn't crash.

**Comment by Darkere** [comment]
Can you post the log of the disconnect? Would make finding the issue much easier.
