### ISSUE TITLE
[Suggestion] Crafter manager button for only crafting recipe slots

### ISSUE THREAD

**Issue by Darkere** [raoulvdberge/refinedstorage#2240]
The ability to shift click items into the crafter manager is quite nice. However making sure that the patterns actually arrive in a crafter made for crafting and not for processing recipes is hard as the order is determined by the crafters position in the world.

My idea is to add a button to the crafter manager that makes it only display crafters that are either empty or do not have a processing pattern in them.

**Comment by raoulvdberge** [comment]
No, sorry.
