### ISSUE TITLE
Crafting performance- Processing Edition

### ISSUE THREAD

**Issue by Darkere** [raoulvdberge/refinedstorage#2243]
#### Issue description:
Long Craftingqueues for processing patterns cause significant performance issues.
#### Steps to reproduce:
1.Setup Autocrafting with Mek elite factories
2. request a few thousand items
3.
...

#### Version (make sure you are on the latest version before reporting):

- Minecraft:1.12.2
- Forge:2825
- Refined Storage:1.6.14

I tried to replicate @theyoungsters issue and this is the result:
https://sparkprofiler.github.io/#GWZTTP4QkF

This is just 3 Machines.
Gonna look into it tomorrow.

**Comment by raoulvdberge** [comment]
@Darkere  Was this fixed with your PR?

**Comment by Darkere** [comment]
Yep
