### ISSUE TITLE
Destroyer not working with FTB utilities

### ISSUE THREAD

**Issue by CallMeSage** [raoulvdberge/refinedstorage#2245]
#### Steps to reproduce:
1. Place destroyer in claimed chunk
2. Destroyer does not work
3.
...

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12.2
- Forge:14.23.5.2821
- Refined Storage: 1.6.14

Does this issue occur on a server? [yes/no] Yes

**Comment by Darkere** [comment]
Should work if you have FakePlayers enabled in the team settings.
