### ISSUE TITLE
Ore Dictionary Support for Patterns

### ISSUE THREAD

**Issue by gr4y** [raoulvdberge/refinedstorage#225]
This is more of a feature request, not an bug report. 

I just wanted to autocraft a Chest and I made a Pattern with Oak Wood Planks yesterday, but since them I ran out of Oak Planks, but I have Birch and Spruce Planks in the system. I really would love to have Patterns that use the Ore Dictionary to use any Planks for the Chest.

**Comment by raoulvdberge** [comment]
Nah, just make multiple chest patterns. When you request a chest it'll take the one that has the most ingredients available.
