### ISSUE TITLE
getItem() from OpenComputer doesn't work for all items

### ISSUE THREAD

**Issue by Alexis3741** [raoulvdberge/refinedstorage#2250]
#### Issue description:
Using OpenComputer, getItem(stack:table[, compareMeta:boolean[, compareNBT:boolean]]):table function doesn't work for all item.

#### What happens:
I tried to get the number of uranium ingots from the Immersive Engineering mod (Modpack Direwolf20 v2.5.0) and the function returns "nil", works perfectly with ExtremeReactor's yellorium.
And rs.getItems() work fine too.
ps:(only tested for Uranium Ingot from Immersive Enginneering, there may be other items that don't work)

#### What you expected to happen:
Get the number of Uranium in the system

#### Steps to reproduce:
1.Put uranium in the storage
2.Connect a computer to the storage
3.Use the computer to get the number of uranium : rs.getItem({name="immersiveengineering:metal"})
...

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.11.2
- Forge mod loader : 8.0.99.99
- Minecraft Forge : 14.23.5.2821
- Refined Storage: 1.6.12
- OpenComputer: 1.7.4.153
- Modpack : Direwolf20 v2.5.0

Does this issue occur on a server?  Yes

#### If a (crash)log is relevant for this issue, link it here:
Demo program for OC : https://pastebin.com/AJ9cAGBb
(only put yellorium from bigreactor and uranium from immersive engineering in the storage to made it work.

Result :
![uranium](https://user-images.githubusercontent.com/21088319/58701310-da2f8a00-83a2-11e9-85ee-a727f940e252.png)

**Comment by Darkere** [comment]
The uranium seems to have metadata did you try with ignoring that?

**Comment by Alexis3741** [comment]
> 
> 
> The uranium seems to have metadata did you try ignoring that?

I've try : rs.getItem({name="immersiveengineering:metal",false,false}) but I got the same result : nil

**Comment by raoulvdberge** [comment]
Probably related to #2253
