### ISSUE TITLE
Checking recipe with JEI causes client crash

### ISSUE THREAD

**Issue by ccapfer** [raoulvdberge/refinedstorage#2251]
#### Issue description:
Client crash when checking items' recipes with JEI
#### What happens:
Client crash
#### What you expected to happen:
Show recipe of item
#### Steps to reproduce:
1. Have JEI and RS installed
2. Click on recipe to check requirements
3. Every once in a while, on different items, game crashes
...

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12.2
- Forge: 14.23.5.2768
- Refined Storage: 1.6.14

Does this issue occur on a server? [yes/no]
yes
#### If a (crash)log is relevant for this issue, link it here:

https://gist.github.com/ccapfer/a14d4b0c385673adb3bc6bdfa8a3d1dd

This issue was not happening before installing Refined Storage on the server, so when it happened pretty soon after installing I assumed it was because of this mod. I'm not great at reading/understanding the crash logs, so let me know if I'm barking up the wrong tree.

**Comment by Darkere** [comment]
You are using an ancient version of JEI. Update that.
