### ISSUE TITLE
Crash when trying to start server

### ISSUE THREAD

**Issue by ireece1** [raoulvdberge/refinedstorage#2252]
#### Issue description:
Crash when trying to start server

#### What happens:
Server crashes during startup
#### What you expected to happen:
Server not crashing on startup
#### Steps to reproduce:

1. cd forgeserver; java -jar -Xms1024M -Xmx8192M forge.jar
2. "It's starting!!"
3.  *red wall of text, kicked back to terminal*
...

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12.2
- Forge: 1.12.2-2838
- Refined Storage: 1.16.3

Does this issue occur on a server? YES

#### If a (crash)log is relevant for this issue, link it here:

https://pastebin.com/bVPUHUmf

**Comment by Darkere** [comment]
Update to 1.6.14
