### ISSUE TITLE
Error when auto-crafting the MOX fuel rod from IC2.

### ISSUE THREAD

**Issue by ExplodingONC** [raoulvdberge/refinedstorage#2259]
#### Issue description:
Error when auto-crafting the MOX fuel rod from IC2. There is a correct output, but the auto-crafting process gets stuck until manually cancelled.
#### What happens:
When starting the auto-crafting of the fuel rod, the RS system can correctly insert the material into the corresponding canning machine, but after the machine finishes the processing and output the fuel rod back to the RS network, the RS network won't recognize it, thus causing the system to wait for the process infinitely (and totally destroys the keep-in-stock function, since the system won't start a new crafting process if there is a same process on-going). 
This seems to have something to do with the NBT data, as the exporter won't recognize the MOX fuel rod with NBT sensitive on.
#### What you expected to happen:
The RS network will recognize the fuel rod when it's finished processing and sent back, and then finishes the auto-carfting. Or just auto cancels the crafting when the execution times out
#### Steps to reproduce:
1.Get an empty fuel rod and a piece of MOX fuel, and put them in the storage network;
2.create a processing pattern for the MOX fuel rod, and put it in the crafter next to an IC2 canning machine;
3.click craft in the grid, and after a while, the fuel rod appears in the grid, but the crafting process is still waiting for an output.

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12.2
- Forge: 14.23.5.2838
- Refined Storage: 1.6.14
- Industrial Craft: 2.8.158 and 2.8.159

Does this issue occur on a server? [yes/no]
Yes.

**Comment by Darkere** [comment]
Replace the output of the processing pattern with the fishished product instead of the item that came from JEI.

**Comment by ExplodingONC** [comment]
> Replace the output of the processing pattern with the fishished product instead of the item that came from JEI.

Ah, you are right. Problem solved, although it's not so convenient...
