### ISSUE TITLE
[0.8.12] Client crash while crafting cobalt ore

### ISSUE THREAD

**Issue by kreezxil** [raoulvdberge/refinedstorage#226]
client crash report: http://pastebin.com/PcPwuQQD

The dedicated server didn't crash, however, it did catch a fatal:

latest.log: https://gist.github.com/6bfbbfc34a242e74931a75d21fd081b9

**Comment by raoulvdberge** [comment]
Does this crash happen 100% of the time?

Does it also happen in other crafting tables (like the one from Tinkers for example)?

**Comment by kreezxil** [comment]
you can close the issue, found out after posting to your page that it was
happening 100% of the time in any crafting grid. Actually managed to locate
the offending mod too.

**Comment by raoulvdberge** [comment]
Thas what I was thinking. Thanks for reporting anyway.
