### ISSUE TITLE
RS interface doesn't export anymore in Integrated tunnels items exporters

### ISSUE THREAD

**Issue by lepouletsuisse** [raoulvdberge/refinedstorage#2261]
#### Issue description:

According to Integrated Tunnels (IT) Mod Spotlight (See https://www.youtube.com/watch?v=zTUBv2uuA00 ), it is possible to use a Refined Storage (RS) interface to import/export items in our IT system by adding a IT item interface on a RS interface.

#### What happens:

While testing it, it seems there is no problem to import items from an IT item importer to the RS system but it seems impossible to export items from our RS system to a chest (for exemple) with a IT item exporter.

I already opened an issue on IT side but it seems its a bug due to a change from the way RS interface export items (see https://github.com/CyclopsMC/IntegratedTunnels/issues/168 ).

#### What you expected to happen:

There should be the content of our RS system that goes in the chest but nothing is coming.

#### Steps to reproduce:
1. Build a simple RS system and add some ressource inside.
2. Build a simple structure like the following image:
![image](https://user-images.githubusercontent.com/8804334/59301965-24faad00-8c93-11e9-83c2-34d8eb9faa25.png)
IT item exporter on the chest and IT item interface on RS interface.
3. Add a variable in the exporter for "Export All Items"

#### Version (make sure you are on the latest version before reporting):

- Refined Storage: 1.6.14
- Minecraft: 1.12.2
- Forge: forge-14.23.5.2838
- Integrated Tunnels: IntegratedTunnels-1.12.2-1.6.9

Does this issue occur on a server? yes

**Comment by raoulvdberge** [comment]
RS no longer exposes the inventory through an interface for performance reasons.

You'll have to export the items explicitly in the interface.
