### ISSUE TITLE
Wireless grids fail to find wireless transmitter 1.5k blocks away

### ISSUE THREAD

**Issue by Mr-Pyro** [raoulvdberge/refinedstorage#2266]
#### Issue description:
Wireless grids fail to find wireless transmitter 1.5k blocks away. (despite using infinite wireless transmitter (addon mod), or the normal transmitter configured with max possible range (via config))
#### What happens:
When within 100's of blocks wireless grids work without issue (not sure on exact distance). When beyond a thousand blocks the wireless grids fail to find the transmitters and does not open. I have also tried chunk loading the transmitter both with ftb utils and chicken chunks.
#### What you expected to happen:
Wireless grids to open.
#### Steps to reproduce:
1. setup rs system with wireless transmitter
2. fly 1k+ blocks away (don't teleport. If you teleport then wait a little while)
3. attempt to use any of the wireless grids.
...

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12.2
- Forge: 14.23.5.2838
- Refined Storage: 1.6.14

Does this issue occur on a server? [yes/no]
no, single player world
#### If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here]

**Comment by Darkere** [comment]
You need to chunk load the controller.

**Comment by Mr-Pyro** [comment]
> I have also tried chunk loading the transmitter [entire rs system] both with ftb utils and chicken chunks.

**Comment by Mr-Pyro** [comment]
I have no idea what is wrong. I duplicated my RS system in a new world and its works perfectly fine, but still does not work in the other world.
