### ISSUE TITLE
Refined Storage - Filters not working correctly with certain mods' items

### ISSUE THREAD

**Issue by Danekjovax** [raoulvdberge/refinedstorage#2268]
**Issue description:**
When applying a filter to a crafting grid, sometimes the items specified in the filter aren't being specifically displayed the items list, but the whole mod's of related items instead.  For example, I place a lead ingot from Thermal Foundation into the filter's items list, then place it into the crafting grid, the grid then shows all of the Thermal Foundation items in the system.  I will note that the mod filter option is not checked when this happens.  
Screenshots attached.
(originally posted at https://github.com/Freebi85/Dungeons-Dragons-Space-Shuttles/issues/205 -referred here by modpack author)

**What happens:**
When placing the filter into the crafting grid's filter slot, the items displayed do not show the expected item(s) filtered.

**What you expected to happen:**
The list of items should only match the items placed into the activated filter. (with mod filter not checked).

**Steps to reproduce:**
1) Have a Refined storage system running with various mod's of items in it.
2) Make sure the RS system includes a crafting grid.
3) Get an RS filter and place an item from one of the mods into it (see below for observed mods displaying this problem).
4) Place the filter into one of the (4) filter slots of the crafting grid.
5) You should see that the items listed do not specifically match what was placed in the filter.

**Version (make sure you are on the latest version before reporting):**
Minecraft: 1.12.2
Forge: 14.23.5.2836 (latest recommended version for the Dungeons Dragons and Space Shuttles modpack)
Refined Storage: 1.6.14
Does this issue occur on a server? YES

Known mods' which items are showing this:
Tech Reborn, ProjectRed Core, Thermal Foundation, Mystical Agriculture, NuclearCraft, Actually Additions, Mekanism

![2019-06-19_22 06 25](https://user-images.githubusercontent.com/10191173/59890243-0afd5080-939e-11e9-909f-22a05a53e8f7.png)
![2019-06-19_22 06 36](https://user-images.githubusercontent.com/10191173/59890244-0cc71400-939e-11e9-86ac-2a2904f3d103.png)
![2019-06-19_22 06 43](https://user-images.githubusercontent.com/10191173/59890247-0df84100-939e-11e9-85f4-7092f5e96d69.png)

**Comment by Darkere** [comment]
Play around with the damage/NBT options. Many mods register their items with the same name but different metadata or NBT. 

There is not really a way to make it work well in 1.12 and the issue will mostly resolve itself in 1.14 so this will probably not get fixed.

**Comment by Danekjovax** [comment]
I'll relay this back to the modpack author.  Thank you.
