### ISSUE TITLE
Items disappearing in Grids

### ISSUE THREAD

**Issue by MrLuxALot** [raoulvdberge/refinedstorage#2274]
#### Steps to reproduce:
1. Play RS
2. Have a Quantum Storage with 500k+ Items
3. Continue to play RS
...

#### Version (make sure you are on the latest version before reporting):

- Minecraft: Minecraft Version: 1.12.2
- Forge: forge-14.23.5.2806
- Refined Storage:r efinedstorage-1.6.14.jar

Does this issue occur on a server? [no]

#### If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here]

**Comment by Darkere** [comment]
Restarting and/or deleting playerdata usually fixes this.
