### ISSUE TITLE
item transfer/ ui bugged

### ISSUE THREAD

**Issue by TailsForLife** [raoulvdberge/refinedstorage#2277]
#### Steps to reproduce:
1. have a full system
2. add all the drives you want
3. place a or multiple of a item
4. log out then back in
5. check your system and now its multiplied (you can take out the amount you put in)

#### Version (make sure you are on the latest version before reporting): 

- Minecraft: 1.12.2
- Forge: 14.23.5.2779
- Refined Storage: 1.6.12

Does this issue occur on a server? [yes/no]
not sure

#### If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here]
https://youtu.be/uSLxdZHmBTQ

**Comment by raoulvdberge** [comment]
I can't reproduce this.
