### ISSUE TITLE
Attempting to cast Refined Storage Class throws exception

### ISSUE THREAD

**Issue by Mr-Pyro** [raoulvdberge/refinedstorage#2278]
https://github.com/KnightMiner/Inspirations/issues/128

#### What happens:
Game crashes
#### What you expected to happen:
not crash
#### Steps to reproduce:
1.play game
...

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12.2
- Forge:
- Refined Storage:

Does this issue occur on a server? [yes/no]

#### If a (crash)log is relevant for this issue, link it here:
https://paste.ubuntu.com/p/yhKBTxfMpW/
[pastebin/gist/etc link here]

**Comment by Darkere** [comment]
duplicate of #2215
