### ISSUE TITLE
[Request] External Storage Feature

### ISSUE THREAD

**Issue by blackheart612** [raoulvdberge/refinedstorage#228]
Hoping for the ability to snapshot/partition the contents of the chest to the filter of the external storage feature. As well as the ability to upgrade the amount of slots in the filter of it just like in AE. Ender IO already has a lot of slots by default but having more slots through upgrade is fine too.

**Comment by raoulvdberge** [comment]
I'm very confused as to why suddenly an issue from 2016 (that has not even been tagged) comes up.

I think GitHub did something weird?
