### ISSUE TITLE
Controller crashes Game when powered

### ISSUE THREAD

**Issue by MrLuxALot** [raoulvdberge/refinedstorage#2280]
#### Issue description:
When I place the Controller and power it, it crashes my Game
#### What happens:
I place the Controller and it crashes
#### What you expected to happen:
I could join my World, with a powered Controller
#### Steps to reproduce:
1. Join into World (With or without optifine)
2. Place Controller
3. Power it
...

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12.2
- Forge:  forge-14.23.5.2838
- Refined Storage: Refined Storage 1.6.14

Does this issue occur on a server? [yes/no]
no
#### If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here]
https://pastebin.com/65enmQvp

**Comment by Darkere** [comment]
You have Fluid with Amount 0 in storage. Try removing fluid disks/storage before powering up the controller again. 

The only way to "save" the fluid disk might be to go in and edit the disk with NBT Explorer.

**Comment by MrLuxALot** [comment]
Still crashes

**Comment by MrLuxALot** [comment]
No longer crashes, bc i took also the Storage disks out before I repowered my Controller
