### ISSUE TITLE
Server Crashing when placing Fluid storage block

### ISSUE THREAD

**Issue by STOKE-STER** [raoulvdberge/refinedstorage#2281]
#### Issue description:
Trying to place a fluid storage block onto an industrial foregoing animal rancher via thermal dynamics fluiduct.
#### What happens:
Placing the block instantly crashes the server
#### What you expected to happen:
I expected the block to be placed in order to have milk sent into it.
#### Steps to reproduce:
1.Place animal rancher
2.connect animal ancher to refined storage fluid storage block via hardened fluiduct
...

#### Version (make sure you are on the latest version before reporting):

- Minecraft:1.12.2
- Forge:14.23.5.2838
- Refined Storage:1.6.14

Does this issue occur on a server? [yes/no]
yes

#### If a (crash)log is relevant for this issue, link it here:
https://pastebin.com/ZfMVzgfA
[pastebin/gist/etc link here]

**Comment by Darkere** [comment]
Not how it works at all. But ofc it shouldn't crash. 

RS only has digital storage meaning you cannot just pipe fluid into it. You need a running system with a fluid storage, then you can import fluid with an importer or by piping it into a fluid interface.

**Comment by raoulvdberge** [comment]
This one should be fixed by 5bc750812e210a3ad0faae893ab66cf3191e8bda
