### ISSUE TITLE
Tech Reborn & RS Storage issue.

### ISSUE THREAD

**Issue by IppSwitch** [raoulvdberge/refinedstorage#2282]
https://github.com/kreezxil/World-of-Dragons/issues/277

Possible Issue between Tech Reborn and RS storage.
(Undergoing more testing)

**Comment by Darkere** [comment]
The Controller is a standard Power acceptor (with a maximum amount to accept set in the config).

It does not influence in any way where that energy comes from.

**Comment by raoulvdberge** [comment]
I'm assuming this isn't an RS issue?
