### ISSUE TITLE
[refinedstorage] Found status: OUTDATED Target: 1.6.15

### ISSUE THREAD

**Issue by Recorpse** [raoulvdberge/refinedstorage#2287]
#### Issue description:
I simply tried making a server with this mod on and I got this issue. im using forge-1.12.2-14.23.5.2838-universal which is the same version in using for my game and that works fine
#### What happens:
 I get this at the end of my server log "[refinedstorage] Found status: OUTDATED Target: 1.6.15"
#### What you expected to happen:
 I expected the server to not tell me that my forge is outdated since I use the same version of forge on my game and it works fine. I only get this when trying to start a server
#### Steps to reproduce:
1. set up forge server of same version
2. put this mod in mods folder(I have many other mods also in the mods folder though)
3. start the server
...

#### Version (make sure you are on the latest version before reporting):

- Minecraft: yes
- Forge: yes but not really because im using the stable version, the same one I use for my game which works fime
- Refined Storage: I don't know. all I know is im using the right version for my forge and game version

Does this issue occur on a server? [yes/no]
yes, it only happens on my server

#### If a (crash)log is relevant for this issue, link it here:
SERVER LOG
https://pastebin.com/4yJSAvBw

**Comment by raoulvdberge** [comment]
Which Refined Storage version are you running?

The OUTDATED warning message simply says that your Refined Storage installation is outdated and that there is a newer version available, in this case 1.6.15.

**Comment by Recorpse** [comment]
I got the latest version for 1.12.2

**Comment by raoulvdberge** [comment]
Which one is that? Can you check your mods folder.

**Comment by Recorpse** [comment]
1.6.15 although I am getting an issue now where it says "Found status: UP_TO_DATE Target: null"

**Comment by raoulvdberge** [comment]
That means you updated RS after creating this issue.

UP_TO_DATE is fine, it's normal to log that. It means what it says.

**Comment by Recorpse** [comment]
why does it still stop though?
sometimes it says up to date and other times its the same message but with out of date instead

**Comment by Recorpse** [comment]
and sometimes it says Ahead. its different every time
