### ISSUE TITLE
Autocrafting cost more than it should

### ISSUE THREAD

**Issue by Kamereon99** [raoulvdberge/refinedstorage#2289]
#### Issue description:
When encoding in the patterns, certain crafts such as (in my case) tin gears takes more resources. In my case it need 2 iron ingot instead of 1. It's not a big deal on this one but the copper gear takes three times the amount of copper normally required !
#### What happens:
In the crafting grid, itemstacks with size greater than one are required for crafting.

#### What you expected to happen:
Just one item should be required (and used).

#### Steps to reproduce:
I don't know how to reproduce it :/

#### Version (make sure you are on the latest version before reporting):

I'm playing on the modpack FTB Revelation 3.0.1
- Minecraft: 1.12.2
- Forge: 14.23.5.2836
- Refined Storage: 1.6.14

Does this issue occur on a server? yes

#### If a (crash)log is relevant for this issue, link it here:

Picture of the pattern :
https://imgur.com/a/jPV4DoR

**Comment by CrossVas** [comment]
Try the latest version of RS

**Comment by Darkere** [comment]
don't

**Comment by Kamereon99** [comment]
What do you mean by "using the bug" ?

**Comment by Darkere** [comment]
Here is a video that shows how to fix it. https://gfycat.com/jealousseriousleech

The last update fixed the bug that changes the itemstacks in recipes. It will not fix the recipes though so unless you are one of the lucky ones that can get it fixed by restarting, fix it first then update.

**Comment by Kamereon99** [comment]
Ok, I'll try ;) Thank you for your reactivity, that's awesome :D
