### ISSUE TITLE
Solderer not placing items in correct spots.

### ISSUE THREAD

**Issue by Zetharion** [raoulvdberge/refinedstorage#229]
I'm running 0.8.12 in the FTB Unstable 1.10.2 (version 4.2.5) modpack.  I have four EnderIO item conduits attached to it.  One on the left (which is supposed to be the top slot), one on the top (which is supposed to be the middle slot), one on the right (which is supposed to be the bottom slot) and one on the bottom for extracting the output.  Each of the three input conduits have an appropriate item filter in them for whitelisting the correct item for a certain slot.  The source of the items is a chest at the start of the EnderIO conduits.

In my experience though the Solderer just inserts whatever it is given in what ever slot it seems to feel like placing it in.

Is there a particular game play reason for requiring items to only be inserted using a certain side, or for the items to be placed in a specific order? It may be less headache to allow all items to be inserted from one side and let the crafting happen regardless of the order of the components in the three input slots.

Or stick with the design decision and just work on getting the items to reliably insert into the correct input slot.  Either way just thought I would report my experience.

**Comment by raoulvdberge** [comment]
Well, the direction (left or right) is relative with the direction you placed it to.

Are you sure you are inserting items *left* from the direction you placed it to?

**Comment by Zetharion** [comment]
So rotating with a wrench messes everything up?  I thought the sides were relative to the position as shown in the photo in the wiki.  So I rotated them so that the side with the one laser looking thing was facing me.  Will break and replace to see if the crafting becomes more reliable.

**Comment by raoulvdberge** [comment]
It might not be that clear, but the solderer *is* directional. You can see it by rotating it, the lasers will change position.

**Comment by Zetharion** [comment]
I tried placing it from behind so that the side with the single laser is facing outwards.  Items are inserted from the correct direction, but only the top (middle slot) inserts correctly every time.  The first crafting request goes correctly, but every craft after that, the Solderer reverses the top and bottom items even though they are being inserted from the correct side.  So I rotated the Solderer 180 degrees using the wrench (so the single laser side is now facing away from me) thinking it would reverse the order its placing items in the top and bottom slots (inside the machine) but it still swaps them.

So I tried changing the direction from which I was inserting and swapped the left and right conduit inputs.  The Solderer is still placing what should go in the top slot (printed improved processor) into the bottom slot and placing what should go in the bottom slot (printed silicon) into the top slot.  This happens whether I place the Solderer while facing the RS Cable that attaches at the back of the machine, or place from behind the RS cable.

I hope I am able to convey what I am trying out.  I can try and grab some screenshots to illustrate tomorrow afternoon.

**Comment by raoulvdberge** [comment]
This makes me think there is something wrong with your conduit setup, but to be sure I'll take a look tomorrow, as it's late now.

**Comment by Zetharion** [comment]
![solderer](https://cloud.githubusercontent.com/assets/8367380/17267501/9ec52978-55d0-11e6-93d5-cc120f1cc1ad.png)

This is the Solderer I'm working on.  The source chest is the 4th one up on the left hand stack, extracting using the purple channel.  I placed this one looking this way and wrenching it around 180 degrees.  The issue I have is the same even when placed from the opposite side.

This is the left conduit:

![left conduit](https://cloud.githubusercontent.com/assets/8367380/17267510/ed8ff36c-55d0-11e6-8b91-9cd2843ba60b.png)

This is the top conduit:

![top conduit](https://cloud.githubusercontent.com/assets/8367380/17267513/f6826b58-55d0-11e6-9751-62f628a6a720.png)

This is the right conduit:

![right conduit](https://cloud.githubusercontent.com/assets/8367380/17267514/fca2a944-55d0-11e6-9207-83485832214f.png)


The first time I load up the game the first crafting request works just fine no problems.  Each request afterwards results in the following happening:

![incorrect placement by machine](https://cloud.githubusercontent.com/assets/8367380/17267535/68634b02-55d1-11e6-972b-b177f840b09e.png)

So for testing purposes I swapped the whitelists of the left and right conduits to see if that would result in the correct placement of items but get the same result regardless of whether the machine is facing forwards or backwards.

Don't worry about this tonight.  I'm heading to bed and wont be home until tomorrow afternoon.

**Comment by Zetharion** [comment]
O saw that in 0.8.13, insertion is no longer side specific.  Where you able to re-create my issue or was it just my setup?

**Comment by Zetharion** [comment]
I tried my setup in creative and it works reliably when I conduit into hoppers that are connected to the solderer.  For some reason when using the conduit directly into the solderer, the top and bottom slots are placed populated randomly.

**Comment by digitalseraphim** [comment]
I'm using EnderIO Conduits and am not having this issue. I've had other issues, but it's purely based on the way RS handles crafting (sending partial recipes before it has all of the items for a crafting step)

**Comment by raoulvdberge** [comment]
I suppose this is an EIO issue that might be fixed now?

**Comment by Zetharion** [comment]
I have no problems when using hoppers or ExU transfer nodes so maybe.

**Comment by raoulvdberge** [comment]
@digitalseraphim is not having this issue. Are you on an up to date EIO version?
