### ISSUE TITLE
Crash apon initalization, No class def found

### ISSUE THREAD

**Issue by Bakaistic** [raoulvdberge/refinedstorage#2290]
#### Steps to reproduce:
1. Install mods that have been pre-installed before installing refined storage and addons
2. Load up minecraft
3. Profit
...

#### Version (make sure you are on the latest version before reporting):
[crash-2019-07-25_16.01.40-client.txt]

- Minecraft: 1.12.2
- Forge: 14.23.5.2915
- Refined Storage: 1.6.15

Does this issue occur on a server? [yes/no] Not tested on server

#### If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here]
[crash-2019-07-25_16.01.40-client.txt](https://github.com/raoulvdberge/refinedstorage/files/3433133/crash-2019-07-25_16.01.40-client.txt)

**Comment by Darkere** [comment]
Update forge.

**Comment by Bakaistic** [comment]
Thank you.
