### ISSUE TITLE
Memory Leak

### ISSUE THREAD

**Issue by zauberparacelsus** [raoulvdberge/refinedstorage#2292]
There appears to be a memory leak when Refined Storage is installed.  Gradually over the course of the session as I move around and explore, memory usage will start at about 700mb and stay below 900 between GC runs.  over time, however, the memory usage will steadily climb in excess of 1.3gb.  Without Refined Storage installed, memory never climbs above a gigabyte.

#### Version:
- Minecraft: 1.12.2
- Forge: 14.23.5.2838
- Refined Storage: 1.6.15

I have only tested this on single player.  Server is untested.

**Comment by raoulvdberge** [comment]
Sorry, you haven't provided enough proof that this is in fact caused by RS.

**Comment by raoulvdberge** [comment]
Is RS the only mod in your pack? How are you sure there is a correlation between RS installed / not installed and memory usage? Analyzing memory usage issues isn't always as simple as "I added X, memory usage has increased, so X is to blame". Memory usage can be attributed to many factors, many outside RS' control.
