### ISSUE TITLE
Exporter exports different ores 

### ISSUE THREAD

**Issue by Vapervop** [raoulvdberge/refinedstorage#2294]
#### Issue description: 
I want to export tin ore and copper ore in the pulveriser but if I turn OFF the damage filter it exports all the ores: lead, gold, etc. If I turn ON the damage filter it exports only a type of tin, since I use IC2, mekanism, thermal foundation, I have "different ores" of the same type (for example: IC2 copper ore, mekanism copper ore, galacticraft copper ore, etc.) 
I can't use the same exporter filter for each ore of the same type, it would be a mess to do...

#### What happens: 
I can't export the ores of the same type

#### What you expected to happen: 
Exporting the same type of ore with the same filter.

#### Steps to reproduce:
1.Take a chest
2.Put an exporter on the chest
3.Trying to export that ores. 
...

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12.2
- Forge: 14.23.5.2838
- Refined Storage: 1.6.15

Does this issue occur on a server? 
no

**Comment by raoulvdberge** [comment]
This is intended. Specify every ore you want to export.
