### ISSUE TITLE
Security station doesn't work for opped players

### ISSUE THREAD

**Issue by runi215** [raoulvdberge/refinedstorage#2296]
#### Issue description:
When a opped player interacts with a refined storage system the security system is bypassed.

#### What happens:
See above. I can understand that this is preferred on bigger servers.

#### What you expected to happen:
I would like to see a config option, so we get can decide for our self if we want this override.

#### Steps to reproduce:
1. Op a player
2. Set security options 
3. See that the player can still access the storage system

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12.2
- Forge: 14.23.5.2838
- Refined Storage: 1.6.14

Does this issue occur on a server? [yes/no]
Yes

**Comment by raoulvdberge** [comment]
Intended
