### ISSUE TITLE
crash with GTCE-1.12.2-1.8.4.432

### ISSUE THREAD

**Issue by Krysinski** [raoulvdberge/refinedstorage#2301]
#### Issue description:
game crash
#### What happens:
after update mod gregtech CE from version gregtech-1.12.2-1.8.4.419 to *432 i get crash on a server
#### What you expected to happen:
no crash
#### Steps to reproduce:
1.
2.
3.
...

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12.2
- Forge: 14.23.5.2838
- Refined Storage: 1.6.15

Does this issue occur on a server? [yes/no]
yes
#### If a (crash)log is relevant for this issue, link it here:
https://pastebin.com/FSBzhY7F
[pastebin/gist/etc link here]
https://github.com/GregTechCE/GregTech/issues/943

**Comment by Krysinski** [comment]
https://github.com/GregTechCE/GregTech/issues/943

**Comment by raoulvdberge** [comment]
#2227
