### ISSUE TITLE
No way to remove set items from the export list?

### ISSUE THREAD

**Issue by Paul17041993** [raoulvdberge/refinedstorage#2302]
In the interface block, you have an import inventory bar, export item list bar, and export inventory bar. You put items into the export list bar to tell them to be exported, clicking on existing items opens a UI to set the stack size to export.

However; _all three mouse buttons_, open the stack size UI, and none of them allow the item to be removed from the export list bar. Setting the stack size to 0 doesn't work either, as it's clamped 1-64.

I would expect middle click and right click (b3 b2) to remove the item, left (b1) to remain as the stack size UI button.

- Minecraft: 1.12.2
- Forge: 14.23.5, build 2838
- Refined Storage: 1.6.15

**Comment by CrossVas** [comment]
SHIFT + Left Click
