### ISSUE TITLE
Stoneblock crash when using Autocrafting

### ISSUE THREAD

**Issue by Methatsall** [raoulvdberge/refinedstorage#2304]
#### Issue description:
I've been playing through Stoneblock. I tried to auto craft some stuff, i had been doing so perfectly well for ages with no issues, i tried to make enriched alloy and instantly my game freezes, and i can't open it again without first loading a different save file up, then exiting and reentering my game then it loads and crashed again soon after.

#### What happens:
minecraft window freezes and stops responding

#### What you expected to happen:
Minecraft to not stop responding

#### Steps to reproduce:
1. Open game
2. Look around 

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12.2
- Forge:14.23.5.2836
- Refined Storage:1.6.14 

Does this issue occur on a server? [yes]
tried it on a server as well and it still crashed so it happens on both.

#### If a (crash)log is relevant for this issue, link it here:

Solo
https://pastebin.com/DZf53mVB

Server
https://pastebin.com/TU2nJZPN

**Comment by Darkere** [comment]
This issue is from Mekanism (it is crashine while conduits are inserting items into a mekanism machine).

This issue should already be fixed in newer versions of mekanism.

Regardless it has nothing to do with Refined Storage.

**Comment by Methatsall** [comment]
My mistake, i assumed it was refined storage cos of what i was doing.
ok thank you, i guess i'll have to wait for an update to play the game then :(
