### ISSUE TITLE
Wrong displayed number of stored items

### ISSUE THREAD

**Issue by Hundifan33** [raoulvdberge/refinedstorage#2305]
#### Issue description:
In the modpack that I am playing (Dungeons Dragons and Space Shuttles) I am having a problem with my RefinedStorage system, namely that the number to indicate the amount of a certain Item is way higher than the ammount that is actually stored.
#### What happens:
Sometimes a certain Item (like 64 redstone) when deposited in the rs system will at some point in time show that there are 200 redstone in the system, I can only remove 64 of it (the items that are really there) but after that it still shows that there are 136 Redstone in the system. This has happenen to multiple items in my rs system now, and it seems to occur randomly (does not need to be 64), increased the displayed number of items by a random value (or at least it seems like that) and once occured it stays in the system permanently (At least to my current knowledge). 
#### What you expected to happen:
For this not to occur.
#### Steps to reproduce:
1.Put some items in system
2.wait for random chance
#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12.2
- Forge: 14.23.5.2838
- Refined Storage: 1.6.15
- Modpack Version (Just in case) : 5.5a

Does this issue occur on a server? [yes/no]
yes, it occurs on a self hosted server with 2 (3max) persons online

**Comment by Darkere** [comment]
Do you happen to have that redstone stored via external storage?

**Comment by Hundifan33** [comment]
No, there is no external storage connected, only one importer for inferium (from mystical aggriculture). It is also not only happening with redstone but with allmost every item in the system, even ones I only have one of. Also the number it displays seems to be somewhat related to the original itemcount (when I put in 1 it will, if the bug occurs jump to 193, and when I take the real item out it will still show 192 items but I cant take any of them). The issue also occurs on a new independant refinedstorage system with only one grid, drive and controller next to each other. Taking a disk from the old system to the new test one still shows a wrong number on most items even if they arent in the system anymore. So far reconnecting the drives, rebuilding the controller and so forth did not fix this issue, but so far none of the "real" items have dissappeared or any new appeared (Only fake ones that I cant take out of the system)

**Comment by Hundifan33** [comment]
Closing this, as the issue has been resolved. There were some disks with identical ids in the network probably either due to jei or by duplicating drives in creative with disks inside them (ctrl+middle mouse button). It would probably be possible to refuse working when there are 2 disks with the same id in the system, or delete (or change the id) of all but one if them. Why the nonexistant items didn't vanish from the system even after the original (real) items were removed is probably due to a logic/timing issue.
