### ISSUE TITLE
Storage disk not working

### ISSUE THREAD

**Issue by calebjway** [raoulvdberge/refinedstorage#2307]
Issue description: Appears that some disks are not working in my disk drive

What happens: I insert them into my disk drive and although I can see them in the GUI it does not affect the total storage or update the block texture

What you expected to happen: Storage disk to hold items and display on block

Steps to reproduce:
1. Have Storage disk with no 0/XXXX stored.
2. Put into disk drive
3.

Minecraft: 1.12.2
Forge: 14.23.5.2838
Refined Storage: 1.6.15

Does this issue occur on a server? LAN server and Singleplayer

**Comment by Darkere** [comment]
What kind of disk are you trying to insert into the drive?

**Comment by calebjway** [comment]
Two 16K Storage Disks and two 256K Fluid Storage Disks. I am playing the current version of FTB Academy if that helps.

**Comment by raoulvdberge** [comment]
I can't reproduce this.
