### ISSUE TITLE
The storage can be duped 

### ISSUE THREAD

**Issue by Ewallee** [raoulvdberge/refinedstorage#2308]
#### Issue description:
The storage can be **duped** 

#### What happens:
The storage (with all its contents) will be duped.
Same happens with the small discs.

#### What you expected to happen:
Storage shouldn't be duped

#### Steps to reproduce:
1.Place a fully charged controller.
2.Place a storage near the controller.
3.Place another charged controller on the other side.
4.The storage (with all its contents) will be duped.

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12.2
- Forge: forge-1.12.2-14.23.5.2838
- Refined Storage: refinedstorage-1.6.14

Does this issue occur on a server? [yes/no]
yes

**Comment by Darkere** [comment]
Like this? https://gfycat.com/TheseEasyEarwig
