### ISSUE TITLE
placement of import/export/interface

### ISSUE THREAD

**Issue by tomevoll** [raoulvdberge/refinedstorage#231]
Might wanna make the interface you place point towards the face you point at when holding shift and placing it, and opposite of what you point at when not holding shift.

Lets say i place a machine 1 block above the floor and want to put a import bus under it, being able to target the floor under it and by that it will point up if i dont hold shift would be really nice, i had a really hard time placing a export on top of machines to, it seems to not really wanna point down but rather one of the sides, maybe add a check so it will target a inventory when placed or the most likely inventory closest to what im aiming at in case of multiple

Also visually cables connect to the top and sides of the wireless transmitter but its not really a valid connection, anything connected to that cable in the other end is not connected to the network.

**Comment by raoulvdberge** [comment]
True! (and Tom, you're alive! :D)

**Comment by tomevoll** [comment]
yes :) been away for a while :) played some other stuff hehe

**Comment by raoulvdberge** [comment]
How is Router Reborn going?

**Comment by tomevoll** [comment]
its updated to 1.9.4 and 1.10.2 now, but im having some sync issues with the cable on 1.10, im not sure why, something changed in 1.10, sometimes it sync other times it dont

**Comment by raoulvdberge** [comment]
Ah cool... I was really waiting for RR for 1.10 ;)

**Comment by tomevoll** [comment]
Ah :) im considering trying to make a base mod that the main mod extends so i can use the same source in all versions, and just use different bases, not sure if i will, but it sure would be nice to only update the base as a new version is released. suppose it would need to be something in the line of a wrapper

**Comment by raoulvdberge** [comment]
Why not just update 1 mod instead of having to maintain 2 mods (the wrapper and the base)? Players would have to update anyway.

I'm really careful myself with making too many assumptions about the MC codebase (like making wrappers), because if MC updates whole your wrapper can be broken, requiring 2 updates to the wrapper AND the mod.

Just some advice.. :P

**Comment by tomevoll** [comment]
yes, but now i would have to update all the blocks/items, if i based them off the base mod, i would only need to update the basemod, and the main mod should still work, so a lot less work, and adding new features in 1.10 would make those available across all versions

**Comment by tomevoll** [comment]
not sure its even doable, well within reason, might be to extensive todo, and might be less work just maintaining the main mod then to make the basemod

**Comment by raoulvdberge** [comment]
Et voila:

http://imgur.com/a/6i2Bm

**Comment by tomevoll** [comment]
nice :D
