### ISSUE TITLE
Cant autocraft with redstone bucket

### ISSUE THREAD

**Issue by wafebreaker** [raoulvdberge/refinedstorage#2311]
#### Issue description:

The system does not recognize a Redstone bucket

#### What happens:

If I want to make any recipe with a Redstone Bucket for auto crafting, he says the bucket is missing. But with a waterbucket everything works. I didnt test any further fluids.

#### What you expected to happen:

That i can autocraft with redstone buckets

#### Steps to reproduce:
1. Create a recipe which use a redstone bucket
2. Insert a redstone bucket into the system
3. Try to craft the recipe
4. Wonder why the system tells you there is a redstone bucket missing

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12.2
- Forge: 14.23.5.2836
- Refined Storage: 1.6.15

Does this issue occur on a server? yes

**Comment by Darkere** [comment]
Disable Oredict on the recipe that uses the bucket.

**Comment by wafebreaker** [comment]
Unbelievable i didnt try this on my own. Thanks for helping. But this is still a bug isnt it? Or is this intended?

**Comment by Darkere** [comment]
Known bug. Duplicate of #2122
