### ISSUE TITLE
external storage capacity

### ISSUE THREAD

**Issue by KumaSamaVII** [raoulvdberge/refinedstorage#2312]
#### Steps to reproduce:
1.attach external storage to storage drawer controller
2.
3.
...

#### Version (make sure you are on the latest version before reporting):

- Minecraft:1.12
- Forge:14.23.5.2838
- Refined Storage:1.6.15

Does this issue occur on a server? [yes/no]no

#### If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here]

**Comment by Darkere** [comment]
This issue is with storage drawers reporting wrong numbers. The numbers are purely visual and as such can be safely ignored.
