### ISSUE TITLE
getStorageSize()/getUsedStorage() functions for OC or Detector mode

### ISSUE THREAD

**Issue by LordMZTE** [raoulvdberge/refinedstorage#2313]
These functions would return the total amount of storage available in the network and the total used storage in the network, it might also be helpful to have an optional argument that will limit them to a certain type of storage (drive/external), that could be useful as with some external inventories  (such as the drawer controller), the available storage doesn't get read correctly.

It could be very useful for things like quarries made with frames such as the ones from funky locomotion so that it would stop once there isn't any more space in the system to prevent it from breaking.

This could also be implemented as a mode to the Detector so that it will emit a signal if there is less then a certain amount of space.

**Comment by Darkere** [comment]
The integration already has these two functions that can be used to calculate this. 
getItems():table | Gets a list of all items in this network.
getStorages():table | Gets a list of all connected storage disks and blocks in this network.

Comparator support like requested in #972 makes more sense than adding more functionality to the detector.
