### ISSUE TITLE
Constructors do not replace fluids

### ISSUE THREAD

**Issue by LordMZTE** [raoulvdberge/refinedstorage#2314]
#### Issue description:
constructors should replace fluid but don't.
#### What happens:
a constructor will not do anything if there's a block in front of it
#### What you expected to happen:
the constructor will place the selected block, replacing the fluid
#### Steps to reproduce:
1. set up a basic network with some blocks (any one will work) and add a constructor to it
2. place a fluid in front of it
3. set it to any block

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12.2
- Forge: 14.23.5.2838
- Refined Storage: 1.6.15

Does this issue occur on a server? [yes/no]
probably, but not confirmed

#### If a (crash)log is relevant for this issue, link it here:

---

**Comment by raoulvdberge** [comment]
This is fixed for 1.14. This bug is very minor however, so it won't be fixed in 1.12.
