### ISSUE TITLE
Change pattern grid mechanic for patterns in processing mode

### ISSUE THREAD

**Issue by raoulvdberge** [raoulvdberge/refinedstorage#2315]
- Per slot basis for exact mode
- Choosing which tags should be matched

**Comment by Darkere** [comment]
Idea: Change it from a 3x3 Grid to a list and add Fluid/Item Slots progressively depending on what is added.

**Comment by raoulvdberge** [comment]
Fixed in https://github.com/raoulvdberge/refinedstorage/pull/2344
