### ISSUE TITLE
Automatically switch between Crafting and Processing when clicking in JEI

### ISSUE THREAD

**Issue by Darkere** [raoulvdberge/refinedstorage#2316]
Make the pattern grid change mode depending on what type of recipe you click on in JEI.

It might be necessary to add a different indicator of what type of recipe you are making. New players may get confused. Depending on how #2315 plays out that might already be enough.

**Comment by Darkere** [comment]
Similarly, the pattern grid should also switch between Crafting and Processing when inserting a pattern into its output slot depending on what type of pattern it is.

**Comment by raoulvdberge** [comment]
Fixed in https://github.com/raoulvdberge/refinedstorage/pull/2344
