### ISSUE TITLE
All items disappeared

### ISSUE THREAD

**Issue by XiNaru** [raoulvdberge/refinedstorage#2317]
I use the mod on the version 1.12.2 and have not had any problems until now. In addition, I use the Mod Ultimate Remote.

So, I've built, keep accessing the ME system and then, all of a sudden, all the items are supposed to be gone. Even if I put a NEW item in the system, the interface remains empty. A hard disk is full, and remove the hard disks and reinvent again has brought nothing. Even if I insert an empty disk, the problem persists.

I use the normal 64k hard drives.

**Comment by Morpheus1101** [comment]
Just got this issue myself...It occured to me while is making gold ingots form nuggets and the storage was saying i had 31k odd nuggets when in fact i only had 3
