### ISSUE TITLE
Few suggestions

### ISSUE THREAD

**Issue by brnicot** [raoulvdberge/refinedstorage#2318]
Hi, I had no idea where to put suggestion so here we go ;)

- Portable grid as a placeable block : like the ME Chest in AE1, its really cool to use it for small separated & specific networks or at the beginning of the game

- Possibility to tweak disks : give them a name and/or a color, and allow the player to put filters on this disk, as a blacklist or a whitelist. Like the disk manipulator but only for the given storage disk.

Also I have a question about the crafting upgrade, would it be possible to update the wiki with an example as we cannot understand what it is doing ?

Thanks for your work !

**Comment by Darkere** [comment]
The portable grid can already be placed. 

You should be able to name a disk with an anvil. For filtering single storages there are the storage blocks that you can use. 

The crafting upgrade can go into the exporter and the interface. For the interface, it only has an effect if it is set to export an item. In both, the crafting upgrade will cause a crafting request for the exported item if there are none (or not enough) of the specified items in storage.

**Comment by brnicot** [comment]
Wow, didn't expect an answer that fast !
Feel like stupid to not have thought of all that...

Thanks a lot ;)
