### ISSUE TITLE
Refined storage covers don't support connected textures

### ISSUE THREAD

**Issue by Renari** [raoulvdberge/refinedstorage#2320]
#### Issue description:
Put a refined storage cover next to a block that supports connected textures.
#### What happens:
The textures do not connect.
#### What you expected to happen:
The textures to connect.
#### Steps to reproduce:
1. Put a cover on a refined storage cable next to a block that supports connected textures.
...

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12.2
- Forge: 14.23.5.2836
- Refined Storage: 1.6.15

Does this issue occur on a server? [yes/no]
yes

#### If a (crash)log is relevant for this issue, link it here:

![javaw_2019-10-01_13-24-30](https://user-images.githubusercontent.com/1839179/65984942-d2661c00-e44e-11e9-8383-06f36e3911d3.png)

**Comment by raoulvdberge** [comment]
Yes, this is going to be a wontfix since covers are gone in 1.14.
