### ISSUE TITLE
Pack Comparer is broken

### ISSUE THREAD

**Issue by n30phyte** [raoulvdberge/refinedstorage#2322]
#### Issue description:

Pack Comparer doesn't show anything for any modpack

#### What happens:

It's blank with 0 mods

#### What you expected to happen:

Shows comparison between modpacks

#### Steps to reproduce:
1. Go to https://refinedstorage.raoulvdberge.com/packcomparer.php
2. Use preset
3. Click compare
4. Nothing happens

![image](https://user-images.githubusercontent.com/1177311/66093409-628a8b00-e54d-11e9-9e02-a95f78970ba0.png)

**Comment by Darkere** [comment]
Duplicate. Already posted here:  https://github.com/raoulvdberge/refinedstorage-website/issues/38
