### ISSUE TITLE
Whenever trying to make Actually Addition lamps the colors come out of the wrong place making crafting get stuck

### ISSUE THREAD

**Issue by GenSmicer** [raoulvdberge/refinedstorage#2323]
#### Issue description:
Whenever making a lamp that requires 2 dyes mixed into 1 dye it seems to just randomly drop the ingredients or the mixed dye end result on the wrong location. Making the color itself seems to go well, but whenever make the lamps from Actually Addtion some ingredients go elsewhere then they are supposed to.

#### What happens:
 I have automated my Atomic Reconstructor from Actually Additions and it get's feeded by a precision dropper that has a crafter attached to it with patterns in it for making leather(rotted flesh drops), Void crystal(Dropping coal), Prismarine shard(Drops quartz), Palis crystal(Drops lapis lazuli) and Redstonia Crystal(drops redstone). 

But when I make the Lamps from Actually Additions that require some color to be mixed with different dyes, not all of it get's made and some of the ingredients to mix the color get dropped on my atomic Reconstructor that is nowhere near the crafter of the patterns with the dye crafting recipies. The vacuumhopper is also not configured to pick it up so it just remains stuck and is unable to finish the remaining lamps it was supposed to make.

#### What you expected to happen:
That it works like when it's just the colors being mixed. Cause it makes the colors on it's own fine, the lamps just seem to think it needs to go elsewhere with some of them. 

#### Steps to reproduce:
1. Make pattern with some mixing color(I tried both oredict and without, same result, Non processing as it's just crafting)
2. Have a setup for the Atomic Reconstructor. I had a string with tripwire hooks that go to a red alloy line(with an inverter) that then activates the atomic reconstructor whenever something is dropped on it. The automatic precision dropper is used to drop it there which has a crafter on it with just the 5 mentioned recipies in it mentioned in what happens. The Color recipies are in a different crafter than the one connected to the precision dropper.
3. Make the corresponding colored lamp from Actually Additions and see a random amount go on the atomic reconstructor and thus get stuck in crafting process(I usually made 24 lamps and usually ended up with at least 2 to 3 items going wrong).

- Minecraft:1.12.2
- Forge:14.23.5.2836
- Refined Storage: 1.6.14(not saw anything in the changelog that seemed related to this for the next version)

Does this issue occur on a server? yes

As a side note, the color mixing recipies have been there way longer then the lamp ones and I never had these issues with them before, but since the crafter is doing the delivery I not see how it could be another mod doing this.

**Comment by Darkere** [comment]
Which pack is this?
Do you have some pictures of your setups and recipes?
I imagine some oredict thing is breaking this.

**Comment by GenSmicer** [comment]
FTB Revelation 3.0.1

I put recipies in both oredict and without and result remained unchanged.

The Setup
https://imgur.com/snW8m9X
It's being powered by flux cables underneath.

The Recipies in the crafter in the setup
https://imgur.com/Hn36RBD
Nothing color related besides the lapis maybe.

Location of the Purple Dye Recipies pattern
https://imgur.com/mxOQcPD
Is about 6 blocks down and 15 blocks further from the setup so not really near it.

Purple Dye recipy
https://imgur.com/2Bhm7AK
It makes purple on it's own fine.

Purple Lamp Recipy
https://imgur.com/TOZki9P
Whenever I try that one it goes all out of wack. But it's located in 1 of those crafters where the purple dye is near too so not sure why I even comes out of the Dropper near the Atomic reconstructor.

Red dye dropped wrongly in action, 5 more in the dropper
https://imgur.com/oSeJPSn

Hope this is enough of an idea?

**Comment by Darkere** [comment]
This happens when the lapis -> palis recipe has oredict enabled. 

From memory, there are 2 potential causes I can think of. Either the actual craft disregards the preferred item from the oredict list. Or the lapis was not yet in internal storage available for use so that the craft switches to the next best thing. Either way, should get fixed once the crafting overhaul happens.

**Comment by GenSmicer** [comment]
Hmm, not sure why lapis and red dye would get confused though, unless all dyes are considered the same thing in some manner. Also when my storage drawers weren't connected due to server restart and I ran the lamp constructions it just dumped in the ink sacs which had nothing to do with the whole recipy.

And why would the purple dye(as in sometimes those just got thrown out) crafting get mixed up in making the palis crystals then? They are 2 different craftings right? Cause sometimes it was just dropping the purple dye out too which seems weird :p.

But yeah when I put the lapis to palis without oredict it seems to work. Wasn't oredict there so that multiple things can be used that are similar? But then that would mean all Dyes are considered the same for what seemed to be happening. Or is there something with the combination of processing and oredict that maybe scrambles it? 

But yeah, I'm prolly going to get it updated eventually just working out some other issues first before I get to other versions.

**Comment by Darkere** [comment]
Something in that pack adds and Oredict tag called Dye which has all dyes in it. Any other dye could get used.

Autocrafting has 2 steps. One where the number of items that are needed are calculated. Here it will first check if you have lapis and if you don't it will check for all other oredicted options. So if it cannot find any lapis it will use any other dye for the calculation too. In that case, it should be visible in the crafting preview and monitor though. 

Then it will go to the actual crafting where all items are basically chucked into a pool and each crafting/processing will attempt to craft. Here the other two mix-ups I mention could happen. Any dyes part of the craft could get used instead of lapis.
