### ISSUE TITLE
Items Not Visible

### ISSUE THREAD

**Issue by One-Man-Taco-Apocalypse** [raoulvdberge/refinedstorage#2327]
#### Issue description:
(Playing on a server hosted by myself) I was working on a project. running between my crafting grid to make a machine, and run back to keep working when, one of times, I go back to find no items are shown in the crafting grid or fluid grid. so i thought id try my wireless grid. and same problem nothing. then i thought id try my portable grid where there was no items shown and finally a friends system and none of his items are showing up. he has not been on yet to know if he is experiencing the same issue or not. i know the system itself is working as i can watch the drives change how many items are in them (auto farms and crafting) i have tried a backup world file to a state i knew the system was working and the problem was still there.
#### What happens:
every thing is operational but no items are being shown
#### What you expected to happen:
to have access to my items
#### Steps to reproduce:
1. unsure of what might have "triggered" this problem
2.
3.
...

#### Version (make sure you are on the latest version before reporting):
(Playing on FTB Academy 1.1.0 latest stable version)
- Minecraft: 1.12.2
- Forge:14.23.5.2846
- Refined Storage:1.6.15

Does this issue occur on a server? [yes]

#### If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here]

**Comment by Darkere** [comment]
check the drives do they show 0/0 or numbers?

**Comment by One-Man-Taco-Apocalypse** [comment]
![72463931_2447861045448825_4356699659809325056_n](https://user-images.githubusercontent.com/56775729/67152515-e8286d80-f2a5-11e9-8b24-b7bd5d9b8c0d.jpg)

**Comment by Darkere** [comment]
Good, that means the files are fine. Try just restarting the client first.

**Comment by One-Man-Taco-Apocalypse** [comment]
ok, I will let you know what that does!

**Comment by One-Man-Taco-Apocalypse** [comment]
so restarting my client, that did not fix it however i thought id try to reinstalled the mod pack and that did fix it! thanks for the suggestion!

**Comment by Likqez** [comment]
> 
> 
> so restarting my client, that did not fix it however i thought id try to reinstalled the mod pack and that did fix it! thanks for the suggestion!

You mean reinstalling the client not the server?
