### ISSUE TITLE
Severe Frame Lag with priorety system

### ISSUE THREAD

**Issue by ozhound** [raoulvdberge/refinedstorage#233]
To replicate this;

Solderer with 2 exporters and load Redstone and silicon ready to place when the slots are drawn from to create processors.

connect an external storage interface to the storage drawer controller from storage drawers. With a priority different to the disk drive there is significant frame lag. Note that there is Redstone in the storage drawer network

This goes away if you remove the Redstone from the exporter or the storage drawer network or if you set the priority the same as the disk drive. 

Evidently the External Storage interface and exporter is fighting for priority of the Redstone. I would assume that this would be the case no matter what item or what machine it would be feeding into.

**Comment by raoulvdberge** [comment]
What leads you to think that the issue is in the priority system, rather than lag issues with Exporter / Storage Drawers combo?

**Comment by ozhound** [comment]
Just a guess based on the fact that until you change the priorety system
everything is fine.

**Comment by raoulvdberge** [comment]
Because if you change the priority, it won't take from the storage drawer anymore but from the disk (which apparently causes no lag)

**Comment by ozhound** [comment]
I realise that and I could keep several thousand restone in the rs system
and this would bypass the issue but the issue still remains does it not
On 1 Aug 2016 1:20 am, "Raoul" <notifications@github.com> wrote:

>

> Because if you change the priority, it won't take from the storage drawer
anymore but from the disk (which apparently causes no lag)
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
<https://github.com/raoulvdberge/refinedstorage/issues/233#issuecomment-236443214>,
or mute the thread
