### ISSUE TITLE
RS + Dank Null (1.12.2)

### ISSUE THREAD

**Issue by Moobien** [raoulvdberge/refinedstorage#2333]
#### Issue description:
I have an importer under a dank null docking station. I have ores set to extract all except 1. When the importer has 4 speed upgrades the behaviour is correct. When you replace 1 speed upgrade with a stack upgrade  the importer removed ALL items that have less than 1 stack in it.

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12.2
- Forge: 14.23.5.2847
- Refined Storage: 1.6.15

**Comment by raoulvdberge** [comment]
Dank Null issue. RS just uses the normal IItemHandler interface.

**Comment by Moobien** [comment]
No worries
