### ISSUE TITLE
[1.10.2] Crash on server startup

### ISSUE THREAD

**Issue by kwpugh** [raoulvdberge/refinedstorage#234]
Forge: 2044
Mod: refinedstorage-0.8.14.jar

Crash report: http://pastebin.com/raw/WuSzMWrj

**Comment by Bartz24** [comment]
I can confirm this crash is happening, but mine is happening with the controller

**Comment by raoulvdberge** [comment]
Fixing it now

**Comment by raoulvdberge** [comment]
0.8.15 will be up in a few minutes

**Comment by raoulvdberge** [comment]
Thanks for reporting!
