### ISSUE TITLE
[1.14.4-1.7] System Forgetfulness

### ISSUE THREAD

**Issue by kreezxil** [raoulvdberge/refinedstorage#2346]
## Issue description:
crafters forget recipes

## What happens:
crafters forget recipes

## What you expected to happen:
system to not forget what is in the pattern crafters

## Steps to reproduce:
it seemed to happen after the system got about 4 pattern crafters in it. Then every time i put a new patter in a free crafter slot, when i got to see if I can craft it, no crafting pattern shows up. I then have to break a refined storage block, any will do and place it back. This apparently refreshes the system and all the pattern crafting recipes are back for use including the new recipe that was just added.

## Version :
Minecraft: 1.14.4
Forge: 28.1.79
Refined Storage: 1.7
Does this issue occur on a server? [yes/no]
yes it's happening on a server, the server has no crash report

## If a (crash)log is relevant for this issue, link it here:
[pastebin/gist/etc link here]
client latest.log: http://sprunge.us/4ELtSh
server latest.log: http://paste.ubuntu.com/p/k4kJBPMgk4/

**Comment by raoulvdberge** [comment]
1.14.4 is no longer supported. I  wonder if this still happens on 1.15?
