### ISSUE TITLE
Can't Autocraft Thermal's expansion blends

### ISSUE THREAD

**Issue by Gi-Coast** [raoulvdberge/refinedstorage#2350]
#### Issue description:
I can't auto craft blends like signalum, resonant... I used to be able, don't know what happened
#### What happens:
See, I have the entire recipe set, magma crucible, and everything. I am able to request crafting of the bucket used for the craft but I can't ask for the signalum blend because it says it's missing the redstone bucket
#### What you expected to happen:
I'm in FTB academy and this procedure used to work, I updated the pack version, not sure this is it

#### Steps to reproduce:
1. Do the whole step by step on crafters, magma crucible, pulverizer, fluid tranposer
2. Request the bucket to be made (Destabilized Redstone in case). The system got this part, ok
3. Request the blend and it tells you the bucket is missing, I think it is not able to do a recipe that doesn't consume the bucket
...

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12.2
- Forge: 14.23.5.846
- Refined Storage: 1.6.15, Addons 0.4.4

Does this issue occur on a server? [yes/no]

No

#### If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here]
![image](https://user-images.githubusercontent.com/57675745/68685644-2cc3c380-0549-11ea-90c8-9542c71aad6a.png)
![image](https://user-images.githubusercontent.com/57675745/68685883-8af0a680-0549-11ea-938a-b7a5d3d29f00.png)
![image](https://user-images.githubusercontent.com/57675745/68685937-a0fe6700-0549-11ea-8c41-a659e392da51.png)

Thanks anyway

**Comment by Darkere** [comment]
Try disabling Oredict on the recipe that uses the bucket.
