### ISSUE TITLE
Crash: Refined Storage Portable Crafting Grid

### ISSUE THREAD

**Issue by Tarlin83** [raoulvdberge/refinedstorage#2353]
#### Issue description:

When looking inside of the portable crafting grid provided by refined storage, and another player breaks the grid to pick it up, forces the player looking in the inventory to crash.

#### What happens:

The client of the player looking in the inventory crashes.

#### What you expected to happen:

The gui display of the inventory to disappear as if closing your own vanilla inventory and to be able to play without crashing.

#### Steps to reproduce:
1.Create a portable crafting grid
2.Place it down and have a player open it up to look at inventory
3.Have a 2nd player break the grid while the first player is looking in it
4.First player crashes, good game.
...

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.14.4
- Forge: 28.1.87
- Refined Storage: 1.7

Does this issue occur on a server? [yes/no]

Yes, "World of Dragons - New Age" by Kreezxil, but does not crash the server, only the client.

#### If a (crash)log is relevant for this issue, link it here:

https://paste.ubuntu.com/p/DsvssvGz67/

Crosslinked to:
https://github.com/kreezxil/World-of-Dragons-A-New-Age/issues/58

**Comment by Tarlin83** [comment]
Any feedback besides adding a label of "bug" as to whether or not you are working on a resolution for this?

**Comment by raoulvdberge** [comment]
I don't owe you an instant reply, you'll have to be patient and wait for the moment when I get time to work on this issue.
