### ISSUE TITLE
Item Count Exagerations

### ISSUE THREAD

**Issue by roseykitten** [raoulvdberge/refinedstorage#2354]
#### Issue description:
Items are steadily increasing by double or triple amounts in storage disks but keeping the correct number of items in the system.
#### What happens:
The disks are filling up with nonexistent items but players can only take the correct amount of items
#### What you expected to happen:
The disks to hold the correct number of items and accurately count them
#### Steps to reproduce:
1. Put a stack of items into the grid
2. Walk away for a few minutes
3. Open the grid and try to take out your stack of items
...

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.14.4
- Forge: 28.1.87
- Refined Storage: 1.7

Does this issue occur on a server? [yes/no]
Not Confirmed
#### If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here]

**Comment by MelanX** [comment]
Did you try in creative mode?
Did you "copy" the disks with middle mouseclick after having one in inventory?

**Comment by roseykitten** [comment]
I've mostly been doing this in creative mode, which is how I spotted the problem and confirmed it. 

I don't have an NBT viewer to answer that.

It looks like the disks are all reading the items and trying to store them simultaneously. Is this a priority issue?

**Comment by MelanX** [comment]
Try this with taking fresh disks and not just copying them. If you copy the disks with middleclick, the NBT will be copied and they are all the same.

**Comment by Darkere** [comment]
The disks ID should show on the tooltip if you enable advanced tooltips with F3+h. Having multiple disks with the same ID would create the behavior you described.

**Comment by raoulvdberge** [comment]
Did you have this issue with the External Storage or only disks?

**Comment by roseykitten** [comment]
It was because of the same item number. Thank you!
