### ISSUE TITLE
[1.14.4 - 1.7.1] [BUG] Crafting Grid isnt showing any items

### ISSUE THREAD

**Issue by Strixter** [raoulvdberge/refinedstorage#2356]
Crafting grid is not showing any items on connected disk drives or connected external storages. I am playing on singleplayer if that matters at all. Please help!

**Comment by Darkere** [comment]
Please use the proper template to make bug reports.

**Comment by Strixter** [comment]
#### Issue description: Crafting Grid or any grid is not showing any of the items in my disk system or external storages

#### What happens: Crafting Grid or any grid is not showing any of the items in my disk system or external storages

#### What you expected to happen: I expect to see all of the items i put in. I did not move the grid or anything. Just closed the inventory menu and opened it again and they were gone.

#### Steps to reproduce:
1. Install Refined Storage 1.7.1
2. Im not quite sure honestly
...

#### Version (make sure you are on the latest version before reporting): 1.7.1

- Minecraft: 1.14.4 (FTB Unstable 1.14)
- Forge: 28.1.61
- Refined Storage: 1.7.1

Does this issue occur on a server? No, I'm playing singleplayer

#### If a (crash)log is relevant for this issue, link it here: N/A

[pastebin/gist/etc link here] N/A

**Comment by raoulvdberge** [comment]
Did you try restarting mc?

**Comment by Strixter** [comment]
Yes I have restarted multiple times. Still no luck

**Comment by Darkere** [comment]
It's also similar to #2338 ,#2327 ,#2326 and more. 

Try breaking the controller/taking the system down. And then restart. Also, try creating another system in the same world to see if it is also affected.

**Comment by Strixter** [comment]
I tried breaking the system and logging out, restarting, and then logging back in and reassembling with no success. I also put it in another system in the same world it is also affected.

**Comment by gravysamich** [comment]
i am having the exact same issue. i am pretty sure the issue happens once you hit a certain threshhold of items in the network.

**Comment by Darkere** [comment]
@Strixter any chance you have the potion capsule mod in your game?

**Comment by Strixter** [comment]
Yes I do have the potion capsule mod. Heres the log:
[latest.log](https://github.com/raoulvdberge/refinedstorage/files/3934744/latest.log)

**Comment by Darkere** [comment]
Well then.. The Potion Amulet/pendant from that mod is what causes this issue. 
You should be able to export it with exact mod off.

**Comment by Strixter** [comment]
OMG!!!! Thank you so much this fixed it I can't thank you enough for the help ♥️♥️♥️

**Comment by raoulvdberge** [comment]
#2362
