### ISSUE TITLE
Can't connect chest to system 1.14.4

### ISSUE THREAD

**Issue by tiphilou17** [raoulvdberge/refinedstorage#2357]
#### Issue description:
Items are not send with exporter connecting chest.
I cant connect, **exporter dont export** but external storage connect chest directly.
#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.14.4
- Forge: lastest
- Refined Storage: 1.7.1

**Comment by Darkere** [comment]
Latest is not a version!

Please post pictures of your setup. Have you specified what the exporter should export?

**Comment by Strixter** [comment]
From what I can gather. Typically, the exporter will not send items to a chest or other inventory unless you have specified what items to send in the exporters filter. External storages and interfaces don't really face this problem.

**Comment by tiphilou17** [comment]
i'm so confused, i mix up exporter and importer.
