### ISSUE TITLE
Problem with whitelists/blacklists

### ISSUE THREAD

**Issue by gcaliber** [raoulvdberge/refinedstorage#236]
If the whitelisted/blacklisted items are named XXX YYY, then any item that matches the YYY in its name gets used.

As an example, setup an exporter for Advanced Processor and it will export every refined storage processor. You can replicate this with most items that are named similarly from the same mod.

After working on this for a long time I did finally figure out that if I turned on Compare Damage in the importer/exporter it then seemed to work correctly when it came to the items name.

**Comment by raoulvdberge** [comment]
Whitelists/blacklists don't compare on name, they compare on the actual item.

Sometimes, several items share the same item ID, thats why it would take the wrong item & thats why you have to compare on damage.
