### ISSUE TITLE
Reader/Writer eating items?

### ISSUE THREAD

**Issue by Chupp4-Jo3** [raoulvdberge/refinedstorage#2360]
#### Issue description:
Reader/Writer with TD Itemducts casuing items to disappear

#### What happens:

I pull a lever, servo gets power. Item goes int reader, nothing shows up at the other end
#### What you expected to happen:

Items to appear at the item duct connected to the writer (and go on into the Reborn Storage crafter or the chest I put at the end of the line in case that (the crafter) was the issue.
#### Steps to reproduce:
1. RS system with an inventory at one end (I used the pattern encoder grid) and an inventory on the other end (again I used the RebS multi-block crafter, but i also had a chest as well)
2. pipe items into the reader (inv -> servo on duct -> rest of ducting to reader -> reader -> writer -> duct -> destination inv)
3. I'd say profit but losing items is the opposite so...

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12.2
- Forge: 14.23.5.2847
- Refined Storage: 1.6.15

Does this issue occur on a server? [yes/no]
n/a

note: I entered the channel name in the writer then selected it from the list in the reader (only have 3 channels) so I'm sure they're on the same one.

**Comment by Chupp4-Jo3** [comment]
So I put a retriever on the duct at the end and all the missing items appeared in the chest. I have no idea what happened, could they have gotten stuck in the 'ether' between the reader/writer? and if so why would they enter and then not get picked up by the crafter?

**Comment by Chupp4-Jo3** [comment]
So more testing later.
Seems the writer functions as 'storage' while items are in CoFH's itemducts; you need something to pull them out at the other end. Could you make the writer 'push' items into itemducts easily/can this be done on their end or is it impractical?

**Comment by raoulvdberge** [comment]
No that is how the reader/writers behave.
