### ISSUE TITLE
Draining energy

### ISSUE THREAD

**Issue by owmii** [raoulvdberge/refinedstorage#2361]
#### Issue description:
It seems like the energy gets drained from your machines.

#### Suggestion:
Make `BaseEnergyStorage#canExtract` returns false and/or `BaseEnergyStorage#maxExtract` to 0

#### Version:
- Minecraft: 1.14.4
- Forge: 28.1.96
- Refined Storage: 1.7.1

Does this issue occur on a server? [yes/no]
Both Sides

**Comment by Darkere** [comment]
Please be more clear in future reports :)

From what I understand it's possible to extract energy from the Controller and the suggestion is to prevent that from happening?

**Comment by zeroneye** [comment]
Yes exactly. :)
