### ISSUE TITLE
Server Crash

### ISSUE THREAD

**Issue by cauliflower69** [raoulvdberge/refinedstorage#2364]
https://pastebin.com/PKC5YmrH 

Using the latest All The Mods 4

**Comment by Darkere** [comment]
Watchdog crash. Meaning a lag spike was too long so that the game decided to crash here right now. 

Unlikely that it had anything to do with RS at all. 

Also please use the issue template !

**Comment by cauliflower69** [comment]
Removal of Refined Storage fixes the issue. Server is up and running perfect

**Comment by Darkere** [comment]
If you changed the max-tick-time to -1 you will not crash like that so would need a new crashlog :)

It's possible to figure out what is lagging so badly with a mod like [Spark](https://github.com/lucko/spark) but unless you are certain that RS is at fault this is the wrong place.

**Comment by cauliflower69** [comment]
Hope this helps the mod devs in some way. If you want me Raoul I'll be on Discord

**Comment by ftog-thorgal** [comment]
We are experiencing the same issue and I believe to have it narrowed down to the External Storage bus being the cause of it. If we use just a Controller, Crafting Grid, and Drive then there are no problems. But as soon as we add a External Storage and leave the area the server times out and crashes.

Crash report: https://gist.github.com/ftog-thorgal/962cca6999fc4774a0c72feeae07d856

**Comment by raoulvdberge** [comment]
I can't do anything with this report unfortunately.
