### ISSUE TITLE
Server Disconnect - Payload may not be larger than 1048576 bytes

### ISSUE THREAD

**Issue by Soutemumb** [raoulvdberge/refinedstorage#2365]
Server Disconnect on grid interaction gives message "payload may not be larger than 1048576 bytes"

I'm not sure how to reproduce this reliably.
But removing disks until you can access the grid normally fixes the issue, the effected disks cannot be opened by grid, wireless, or portable.

- Minecraft: 1.14.4
- Forge: 28.1.102
- Refined Storage: 1.7.1

Does this issue occur on a server? Yes

#### If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here]
[latest.log](https://github.com/raoulvdberge/refinedstorage/files/3919201/latest.log)
![2019-12-03 (1)](https://user-images.githubusercontent.com/37351266/70098972-334ad580-15f3-11ea-85dc-778d3c6ea210.png)

**Comment by raoulvdberge** [comment]
#1790

**Comment by Louisthornton** [comment]
I have this issue too when accessing my fluid grid and using JEI to craft
