### ISSUE TITLE
Updating p455w0rdslib causes Refined Storage to crash

### ISSUE THREAD

**Issue by tankcr** [raoulvdberge/refinedstorage#2368]
#### What happens: Launcher crashes
crash log: https://pastebin.com/Y2pEhmwV

#### What you expected to happen:
finish launching

#### Steps to reproduce:
1. Roll back p455w0rdslib
2. No crash
3. Reinstall p455w0rdslib-1.12.2-2.3.161 and immediate crash
...

#### Version (make sure you are on the latest version before reporting):

- Minecraft:
- Forge:
- Refined Storage:

Does this issue occur on a server? [yes/no]

#### If a (crash)log is relevant for this issue, link it here:

[https://pastebin.com/Y2pEhmwV]

**Comment by Darkere** [comment]
https://github.com/p455w0rd/p455w0rds-Library/issues/61

**Comment by raoulvdberge** [comment]
I'm assuming this is fixed?

**Comment by tankcr** [comment]
all good ty!
