### ISSUE TITLE
System can run off  1 RF/T

### ISSUE THREAD

**Issue by Rubijox** [raoulvdberge/refinedstorage#2369]
#### Issue description: My refined storage setup can currently run off 1RF/T no matter how large it gets

Note that making it work this way displays nothing in the controller
Autocrafting also works just fine

#### Steps to reproduce:
1.Build RS system(any size will do).
2.Power the rs system with enough RF that it detects everything.
3.Cut the power
4.Supply Exactly 1RF/T to the controller
5. Profit.
6. slap the controller with power again when adding cables/interfaces/etc to make sure it detects them.

#### Version (make sure you are on the latest version before reporting):

- Minecraft:1.14.4
- Forge:28.1.102
- Refined Storage:1.7.1

Issue present client-side

Sorry i cant figure out spoilers for the screenshots
![image](https://user-images.githubusercontent.com/32174232/70398304-01b57e00-19e8-11ea-9463-943936e4c522.png)
![image](https://user-images.githubusercontent.com/32174232/70398308-12fe8a80-19e8-11ea-977f-674e4bc94bee.png)
![image](https://user-images.githubusercontent.com/32174232/70398313-198d0200-19e8-11ea-958a-cbbad3027429.png)
![image](https://user-images.githubusercontent.com/32174232/70398314-1db91f80-19e8-11ea-95f2-4cc73f13123b.png)

**Comment by raoulvdberge** [comment]
I can't reproduce this bug...
