### ISSUE TITLE
TiCon Smeltery Automation

### ISSUE THREAD

**Issue by ray73864** [raoulvdberge/refinedstorage#2373]
So i'm trying to autocraft using the TiCon smeltery, I have most of it working but either i'm stupid, or TiCon isn't giving outputs like it should, or RS isn't seeing things like it should.

Playing Dungeons, Dragons, and Space Shuttles (1.12 pack).

In the pack, I want to make Terrax, it is made of 3 fluids, Jauxum, Karmesine, and Ovium.

Jauxum Ingot = 144mB
Karmesine Ingot = 144mB
Ovium Ingot = 144mB

1mB of each of the 3 creates 2mB of Terrax.

I have a pattern set up to do: 1 of each ingot when alloyed = 244mB of Terrax Fluid.

I put a crafter onto the smeltery controller, put the pattern in it, and requested terrax fluid, all good, everything works.

I put an external storage onto the smeltery drain, and I crafted a new pattern that takes 144mB of Terrax Fluid and turns it into 1 Terrax ingot, I put that pattern in another crafter and put it on a NuclearCraft ingot former, which turns the fluid into an ingot.

Now, when I request that the network makes a terrax ingot, it correctly deals with the smeltery, but it never sees the final terrax fluid in the smeltery (despite having an external storage), if I cancel the task and then tell it to make the ingot again, it correctly sucks out the fluid and sends it to the NC ingot former.

So it can see that the alloy is in the smeltery, it just can't see that it is in there during the overall task of going from 3 ingots to 1 alloy to 1 ingot.

Is there something i'm missing?

**Comment by Darkere** [comment]
In autocrafting the output of the recipe needs to make its way into the network through an Importer or an Interface. Using an external storage will bypass that system. 

Please do not use Github for anything that is not a bug. Join us on discord for discussion all around RS https://discordapp.com/invite/VYzsydb.

**Comment by ray73864** [comment]
I don't understand Discord at all :( Have never used it before.
