### ISSUE TITLE
[SUGGESTION] Storage readable by other mod

### ISSUE THREAD

**Issue by Alby02** [raoulvdberge/refinedstorage#2374]
Can you make the storage readable via interface or other block by another mod like LgisticPipe (Provider Piepe).
Like the external storage but in the opposite direction.

- Minecraft:1.12.2

**Comment by Darkere** [comment]
https://www.curseforge.com/minecraft/mc-mods/logistics-bridge

**Comment by Alby02** [comment]
Ok but if I want to use it with Project Red transportation

**Comment by Darkere** [comment]
You can export items with an exporter or interface and interact with those. Any other ways would need an addon mod like the one I posted above.

**Comment by Alby02** [comment]
Ok but i don't think there is an addonn for every mod and the exporter has a limited ammount of Item that it can export
