### ISSUE TITLE
[1.14.4] Refined Storage crash when re-entering world

### ISSUE THREAD

**Issue by Gbergz** [raoulvdberge/refinedstorage#2375]
#### Issue description:
A Refined Storage crash to the client when re-entering a world.

#### What happens:
The Gameclient crashes when trying to re-enter a existing world.

#### What you expected to happen:
Being able to enter the world without issues.

#### Steps to reproduce:
1. Enter the world
2. Wait
3. Crash
... Game closed.

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.14.4
- Forge: 28.1.104
- Refined Storage: 1.7.1

Does this issue occur on a server? [yes/no]
Not that i know of, no.

#### If a (crash)log is relevant for this issue, link it here:
[https://pastebin.com/tA4VxS6V](https://pastebin.com/tA4VxS6V)

**Comment by Zeoic** [comment]
I am getting the same error with the refined storage controller when restarting my dedicated server after setting up a refined storage system.

Using the All The Mods 4 Modpack.

https://pastebin.com/MwSKF24X

**Comment by raoulvdberge** [comment]
Thx for reporting. This issue will continue under #2381
