### ISSUE TITLE
[1.14]Portable Grid loses its texture when you face south

### ISSUE THREAD

**Issue by jinkhya** [raoulvdberge/refinedstorage#2376]
#### Issue description:
Hello,
When you place the portable grid facing south, it loses its texture and renders underground.

#### What happens:
When you place the portable grid facing south, it loses its texture and renders underground.
https://i.imgur.com/ObQ7RLo.png

#### What you expected to happen:
Not to lose its texture.

#### Steps to reproduce:
1. Have your character face south
2. Place the portable grid in the world

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.14.4
- Forge: 103
- Refined Storage: 1.7.1

Does this issue occur on a server? [yes/no]
yes

#### If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here]

**Comment by raoulvdberge** [comment]
I can't reproduce this. Are you using a resource pack?

![java_2019-12-28_22-03-11](https://user-images.githubusercontent.com/10358424/71549451-e1ad2500-29bd-11ea-9c5b-a2a764d3d60e.png)

**Comment by jinkhya** [comment]
It looks like it's related to another glitch that I can't reproduce either. Sometimes after a while, I can't open the portable grid in inventory anymore. I have to place it on the floor to be able to use it. That's when it gets rendering issues. I haven't figured out how I manage to "glitch" it. I tried placing, charging in different mod machines, shifting, not shifting etc, I can't do it on purpose. 
That doesn't really helps...
Maybe @Darkere has more infos on it. I know he was trying to check something with nbt tags but not sure what the conclusion was.

**Comment by jinkhya** [comment]
and no I was not using a resource pack

**Comment by Darkere** [comment]
Probably a side effect of #2378 then

Although the portable grid is entirely invisible when placed when using optifine :). Probably gonna need to report that there though...
