### ISSUE TITLE
"Wireless Crafting Grid" Voiding items

### ISSUE THREAD

**Issue by Pelemesh** [raoulvdberge/refinedstorage#2377]
#### Steps to reproduce:
1. In my case I have SolarfluxReborn panel with dispersive upgrade wirelessly charging my grid
2. When in radius of wireless charging open "grid" and leave items in crafting 3x3 grid
3. Close and open again, items are gone
...

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.14
- Forge: 28.1.107
- Refined Storage: refinedstorage-1.7.1

Does this issue occur on a server? [yes/no] Yes, didn't test in ssp

#### If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here]

**Comment by raoulvdberge** [comment]
Logs please.

**Comment by suprra** [comment]
Sorry for the extreme necro but it seems I'm having this problem too, using worlds of god pack with chargers mod. While I had this block placed, when closing the grid without clearing the crafting interface it would void whatever was in the table.

Where would I find useful logs to help with this? Thanks :)
