### ISSUE TITLE
[Suggestion/Request] Mod Filtering

### ISSUE THREAD

**Issue by praetoras** [raoulvdberge/refinedstorage#238]
A lot of times I like to keep things organized, and as such would like to have separate storage for the items of different mods, especially those mods I intend to use a lot of. RFTools Dimensions is a grand example. I frequently run out of space just from all the dimlets I'm trying to store.

It would be great if, in addition to the other filtering options, you added the ability to "match mod" with the item(s) in the filter array, so that any item from the same mod would be exported/imported.

**Comment by raoulvdberge** [comment]
I'd rather do a compare damage / compare NBT on filters, then you can target all dimlets at once

**Comment by raoulvdberge** [comment]
Done for the next version. 
- Each Grid Filter can now only filter 9 items
- Each Grid allows 4 Grid Filters instead of 1
- Grid Filters can now be configured to compare on NBT and/ or damage
