### ISSUE TITLE
Full Indicator

### ISSUE THREAD

**Issue by charliegc4** [raoulvdberge/refinedstorage#2383]
Would love to see some external way for storage blocks to indicate when they are full. Maybe changing color, or something like that. A real chore to go clicking on each to see what it's status is.

Or even some way to see what my total usage of the combined storage blocks are.

**Comment by raoulvdberge** [comment]
I don't think this is needed

**Comment by charliegc4** [comment]
How do you know then what your combined storage capacity is and how much you are using?
