### ISSUE TITLE
1.12 can't craft fluid when storage contains some already

### ISSUE THREAD

**Issue by Spongman** [raoulvdberge/refinedstorage#2384]
there's no 'Display Mode' button in the Fluid Grid, so it's impossible to see the crafting item in the grid when there's already some of that fluid in the storage.

#### Version (make sure you are on the latest version before reporting):
FTB Academy
- Minecraft: 1.12.2
- Forge: 14.23.5.2846
- Refined Storage: 1.6.15

Does this issue occur on a server? yes

**Comment by Darkere** [comment]
You can ctrl + shift click to craft even when there is already an item/fluid of that type in the system.

**Comment by Darkere** [comment]
The issue has been remedied in the 1.14 version of the mod. The feature may or more likely may not be ported over to the older 1.12 version.

**Comment by Spongman** [comment]
> You can ctrl + shift click to craft even when there is already an item/fluid of that type in the system.
doh! thanks for that.
