### ISSUE TITLE
1.12 fluid crafting gets confused

### ISSUE THREAD

**Issue by Spongman** [raoulvdberge/refinedstorage#2385]
i'm not really sure what's going on here, but here's what i have:
- an RS Crafter pointing into a Portable Tank. the Crafter contains:
  - fluid processing recipe `0.2 B Liquefacted Coal -> 0.1 B Naptha`
  - fluid processing recipe `0.15 B Naptha -> 0.1 B Refined Fuel`
- pulling from the tank, a fractionating still, and fluiducts pumping the output back into an RS Interface.
- several buckets of Liquefacted Coal in the RS storage

when I craft `1000mb Refined Fuel` in the Fluid Grid, the amount of Naptha goes down 1 bucket, and then slowly increases back to the original value. no Refined Fuel is created.

#### Version (make sure you are on the latest version before reporting):
FTB Academy
- Minecraft: 1.12.2
- Forge: 14.23.5.2846
- Refined Storage: 1.6.15

Does this issue occur on a server? yes

the logs show the folloing repeated several times:

````
[13:56:53] [Server thread/WARN] [com.raoulvdberge.refinedstorage.apiimpl.autocrafting.task.CraftingTask]: null unexpectedly didn't accept items, the remainder has been voided!
````

**Comment by Darkere** [comment]
That sounds like the naptha is being put into the tank and then imported without ever going through the fractioning still. Make sure to watch the process to see what is happening. 

The error message says items and that means some inventory is reporting it is able to accept items but then does not. As your described pattern only contains fluids it can not be the reason for that message. 

Images are always a good idea to share when looking at logistical issues. Pictures of your setup would go a long way towards making sure I don't have to ask unnecessary questions.

**Comment by Spongman** [comment]
i don't think it's being imported from the tank. I tried watching it in the crafting monitor, but i don't really understand what it's telling me.

that error message only occurs when i try the fluid crafting recipe., and it starts exactly after i click 'Start' on that recipe, and repeats 10 times and then stops.

here's a pic:

![image](https://user-images.githubusercontent.com/1088194/71328057-aa261080-24c5-11ea-96bf-77562b62a296.png)

in the foreground you can see the underside of the crafter pointing into the portable tank, the fluiduct pulls from the tank into the side of the still, and the other fluiduct pulls from the bottom of the still away to a fluid interface off to the right. [[ i originally had the crafter point into the back of the still, but that didn't work either, so i added the tank. ]]

**Comment by Darkere** [comment]
The problem is most likely the servo at the bottom of the machine extracting from the input. Almost all thermal machines do automatically output as long as they are configured normally. Also make sure that the sides are configured correctly. (left side blue bottom orange nothing else). 

Double-check your recipe to see if there are any items on it that could cause that message.

**Comment by Spongman** [comment]
i'm going to close this, as i now think it's a thermal issue. i removed all the RS stuff and it still acts weirdly... it's pumping the input out from the bottom even though it's not configured to do this. thanks for your help!

![image](https://user-images.githubusercontent.com/1088194/71328373-19523380-24cb-11ea-9cc1-5c57a379f93f.png)

**Comment by Spongman** [comment]
incidentally, it was the servo on the bottom of the still that was causing the issue. even though the still's bottom side was only bound to the output tank, the servo on that side was pulling from the input. removing the servo and enabling auto-output fixed the issue....

**Comment by Darkere** [comment]
Thanks that's actually really helpful. Not the first time I've seen similar issues. Kinda glad to know it's thermal that is the problem.
