### ISSUE TITLE
The imort bus does not work if an item is inside

### ISSUE THREAD

**Issue by Lice2** [raoulvdberge/refinedstorage#2386]
#### Steps to reproduce:
1. if the import bus is empty, everything works
2.when an item is in it nothing works
3.
...

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.14.4
- Forge: 1.14.4-forge-28.1.87.jar
- Refined Storage: refinedstorage-1.7.1.jar

Does this issue occur on a server? [yes/no] yes

#### If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here]

**Comment by raoulvdberge** [comment]
Be more specific
