### ISSUE TITLE
Feature request: exporting excess items

### ISSUE THREAD

**Issue by gelraen** [raoulvdberge/refinedstorage#2389]
I want to have something like this: "keep 1000 eggs in storage, dump the rest into IC2 recycler".

Currently configuring an exporter to export eggs doesn't allow keeping a certain amount stashed, and the simplest existing way of achieving this I can think of - write a program for OpenComputers to remove excess items from the network completely and process them separately.

**Comment by CrossVas** [comment]
You can do this using [Detector ](https://refinedstorage.raoulvdberge.com/wiki/detector).
1. Place the Detector. Configure it to "Emit redstone signal when above the amount".
![image](https://user-images.githubusercontent.com/25727222/71544390-8bbd8a80-2987-11ea-9b64-b8cd6047017f.png)
2. Place the Exporter and configure it to export only with redstone signal.
![image](https://user-images.githubusercontent.com/25727222/71544396-ad1e7680-2987-11ea-9ce5-58fb0ffa1db7.png)
3. Profit.
![image](https://user-images.githubusercontent.com/25727222/71544407-c32c3700-2987-11ea-8e61-6ab1b3e1b481.png)

**Comment by gelraen** [comment]
Oh, thanks, that's indeed simpler than using OpenComputers :) One problem though: redstone signal doesn't differentiate between items, so separate detectors and exporters are needed for every item type.

**Comment by raoulvdberge** [comment]
I think this is fine as is.
