### ISSUE TITLE
my me system broke and i set it back up but when i put my storage disk in my me system and the items won't show up

### ISSUE THREAD

**Issue by Smdub80** [raoulvdberge/refinedstorage#2391]
#### Steps to reproduce:
1.
2.
3.
...

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge: 3.0.15
- Refined Storage: I dont know

Does this issue occur on a server? [yes/no]

#### If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here]

**Comment by raoulvdberge** [comment]
1) 1.10.2 is unsupported
2) Follow the issue template
3) You are playing Refined Storage, there is no such thing as "ME"
