### ISSUE TITLE
[1.6.15] Wrong fluid recipe retrieved from JEI 

### ISSUE THREAD

**Issue by itanshi** [raoulvdberge/refinedstorage#2393]
#### Issue description:
Wrong fluid recipe retrieved from JEI

#### What happens:
glowstone smelting recipe also makes fiery essence

https://cdn.discordapp.com/attachments/96117418585247744/663240064624754699/2020-01-04_22-38-42.gif

https://cdn.discordapp.com/attachments/96117418585247744/663247801362284545/2020-01-04_23-09-33.gif

#### What you expected to happen:
only smelted redstone and smelted ender pearls.

#### Steps to reproduce:
1. Refined storage setup with a fluid disc
2. use jei to add recipe to a processing pattern
3. 
...

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12
- Forge: 14.23.5.2846
- Refined Storage: 1.6.15

Does this issue occur on a server? [yes/no] 
yes

#### If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here]

**Comment by Darkere** [comment]
Couple things:
You can change the view to see the fluids in the pattern by pressing the last button on the left. 

If the pattern grid adds fluids that are not strictly part of the recipe then that's on the person who made those recipes. Someone defined those as output. There is nothing RS can do about that.

**Comment by itanshi** [comment]
The pack is ftb revelations and i don't see any recipe changes for refined storage

http://itanshi.com/recipe_changes.txt
http://itanshi.com/unification.txt 

Otherwise, ty, i can work around this

**Comment by Darkere** [comment]
The recipe changed would be the one you selected in JEI.
