### ISSUE TITLE
Autocrafting with Filled-Buckets - Feature Request.

### ISSUE THREAD

**Issue by LezChap** [raoulvdberge/refinedstorage#2395]
https://refinedstorage.raoulvdberge.com/wiki/autocrafting-with-filled-buckets

This is currently the accepted "process" for crafting buckets of fluids for other patterns.  However, this requires an external mod which can accept both a fluid and a bucket, and fill it...or a more complicated setup (example: https://github.com/AllTheMods/ATM-4/issues/116#issuecomment-572228186).  I don't believe this process should require an external mod or mods, because of the feature of the Fluid Grid.

The Fluid Grid has a feature where if you don't have a bucket in your inventory, it'll search the system for an empty bucket to fill, in order to give the player a bucket of the requested fluid.  I think this process should be a part of processing patterns which require a bucket of a given fluid, be built into Refined Storage itself, so it doesn't require the use of external mods...mods which may not always be available to the player.  And given the feature already seems built-in to the Fluid Grid, it makes sense that Refined Storage should be able to do it in auto-crafting.  The only extra step that may be needed to added is if a bucket is unavailable, the auto-crafting calculator will craft one too.

**Comment by raoulvdberge** [comment]
No, I think it's fine this way.
