### ISSUE TITLE
Network Receiver drops if Network Card gets inserted into Network Transmitter

### ISSUE THREAD

**Issue by Sheldor5** [raoulvdberge/refinedstorage#2398]
#### Issue description:

Network Receiver drops if Network Card gets inserted into Network Transmitter - interdimensional Networks are impossible

#### Steps to reproduce:
1. setup Controller + Transmitter in Dimension 2 "Aroma Mining World"
2. setup Controller + Receiver in Dimension 0 "Overworld"
3. link Network Card to Receiver in Dimension 0 "Overworld"
4. insert Network Card into Transmitter in Dimension 2 "Aroma Mining World"
5. go back to Dimension 0 "Overworld" and see that the Receiver is laying on the ground as item drop

everything is chunkloaded properly and everything else (Thermal Foundation machines, Environmental Tech machines, etc.) is working properly

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12.2
- Forge: 14.23.5.2846
- Refined Storage: 1.6.15

Does this issue occur on a server? yes, FTB Revelation 3.2.0

**Comment by Darkere** [comment]
This happens if you have controller on both sides of the connection. There can only ever be one controller in a network.

**Comment by Sheldor5** [comment]
Ah thanks thats it.
This should be mentioned in the Wiki :)
