### ISSUE TITLE
Not Displaying correct amount of items.

### ISSUE THREAD

**Issue by trolio** [raoulvdberge/refinedstorage#2399]
#### Issue description:
Refined Storage System not showing correct amount of items.
#### What happens:
Ill set up a farm to auto create items for me and ill leave the server over night when I get up the next morning and get on the server it will say a random number like 53.8k when in reality there is only a few stacks of that item.
#### What you expected to happen:
I expect this issue is caused by having way to many items in my system.
#### Steps to reproduce:
1. create automatic farm
2. make it run at max capacity
3. auto import all items into system.
...

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12.2
- Forge: 14.23.5.2846
- Refined Storage: 1.6.15

Does this issue occur on a server? [yes/no]
Yes
#### If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here]

**Comment by bloodscon** [comment]
What other mods are in the pack (list the mod name if downloaded of twitch), are the items being stored directly in RS or a mod like storage drawers, YABBA, filing cabinets used.  (I have come across problems with RS storage interface not reporting the correct storage with drawers (even worse if using compacting drawers) and refusing to pull from filing cabinets).

**Comment by raoulvdberge** [comment]
Extremely bad reproduction steps. You expect me to make an automatic farm to verify this?
