### ISSUE TITLE
Inventory Tweaks Support

### ISSUE THREAD

**Issue by efinder2** [raoulvdberge/refinedstorage#240]
At the moment I move my chest storage system in the System. It would be nice if shift + Space and all the other shortcuts from Inventory Tweaks would work.

**Comment by choekstr** [comment]
And mousewheel support for using the mousewheel to roll and have it subtract/add items from RS grid to inventory and back.

**Comment by IMarvinTPA** [comment]
Also, add a sort option to have the terminal sort by the inventory tweaks tree, like AE2 has.  I have been maintaining a tree file for modded minecraft that I play.

**Comment by Seyeght** [comment]
Any movement/thoughts on this feature? Would be nice if the Space + Click functionality  or Shift + Double click worked.

**Comment by raoulvdberge** [comment]
I've looked into this, but it seems like the InvTweaks API doesn't allow this...

**Comment by efinder2** [comment]
AE2 have done this in the 1.7.10 version. I haven't played the 1.11 version, but i think they have also implemented this.

**Comment by choekstr** [comment]
AE2 might have implemented it themselves instead of relying on invtweaks to handle it.

Raoul, if this isn't super hard to add some hotkey and behaviors it would be really nice to have implemented for the community.  Understandable if it isn't an easy thing to do.  You might be able to leverage the relevant code from InvTweaks with appropriate permission.

**Comment by raoulvdberge** [comment]
Shift + double click seems to work fine here:

![x](https://raoulvdberge.com/jm8Pfv)

**Comment by choekstr** [comment]
That's helpful.  If you can get mousewheel support that would be epic!  We already have the shift middleclick for single items but mousewheel is so darn convenient...

**Comment by raoulvdberge** [comment]
I'm closing this issue now because:

- Shift + double click works already out of the box
- Item scrolling should work if said item scrolling mod implemented their stuff correctly
