### ISSUE TITLE
[1.15.2] wish i knew more java...

### ISSUE THREAD

**Issue by Rumpelstiltskinny** [raoulvdberge/refinedstorage#2408]
MC 1.15.2 SP
forge 31.0.1
RS 1.8

was hoping to find a working storage system for 1.15.2, yours is best :)

attempted loading in a fresh singleplayer world and found this:

java.lang.NoSuchMethodError: net.minecraft.item.Item$Properties.setTEISR(Ljava/util/function/Supplier;)Lnet/minecraft/item/Item$Properties;
	at com.raoulvdberge.refinedstorage.item.PatternItem.<init>(PatternItem.java:52)
...etc etc etc

**Comment by Darkere** [comment]
For now you can find one here: https://jenkins.raoulvdberge.com/job/refinedstorage-mc1.15/

Should be released on CF soonish
