### ISSUE TITLE
weird jei update

### ISSUE THREAD

**Issue by MasterSloth1** [raoulvdberge/refinedstorage#2410]
#### Issue description:
storage disk when bookmarked gets updated without updating the bookmark
#### What happens:
when you book mark a 64k storage disk that has items stored inside that disk and then take items out of the disk the nbt of the book marked item updates 
#### What you expected to happen:
the bookmarked item to not get updated so it stays the same
#### Steps to reproduce:
1. place items inside 64k storage disk
2. book mark said storage disk
3. remove items from storage disk and look at bookmarked item
...

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.14.4
- Forge: 28.1.114
- Refined Storage: refinedstorage-1.7.3.jar

Does this issue occur on a server? [yes/no]
yes
#### If a (crash)log is relevant for this issue, link it here:
N/A
[pastebin/gist/etc link here]
storage disk before
![image](https://user-images.githubusercontent.com/34207969/73240482-ef93d700-4203-11ea-8ed5-25f9ab489aad.png)

storage disk after 32 items where taken out (I am NOT re-book marking the storage disk that is the original bookmark from the start)
![image](https://user-images.githubusercontent.com/34207969/73240526-0b977880-4204-11ea-9bb7-4c08eca7cc1d.png)

**Comment by raoulvdberge** [comment]
That's logical, this isn't a bug
