### ISSUE TITLE
1.15.2-1.8 crashes dedicated server Forge 1.15.2 build 31.0.1

### ISSUE THREAD

**Issue by kreezxil** [raoulvdberge/refinedstorage#2411]
Issue:  1.15.2-1.8 crashes dedicated server Forge 1.15.2 build 31.0.1

Notes:
     loading failed exception

crash report:
http://paste.ubuntu.com/p/Sf3dWjPkwg/

fml server latest:
http://paste.ubuntu.com/p/BqrtR2M7ry/

**Comment by Darkere** [comment]
RS update to 1.15.2 is currently only available via Jenkins https://jenkins.raoulvdberge.com/

**Comment by kreezxil** [comment]
interesting, it was allowed to be pulled in via the twitch launcher and tagged for 1.15.2

**Comment by raoulvdberge** [comment]
The latest RS on curse is tagged as 1.15.1, not for 1.15.2.

**Comment by kreezxil** [comment]
Interesting, that means Twitch screwed up, because twitch allowed me to
install it in a 1.15.2 pack that I created.

**Comment by kreezxil** [comment]
and by allow I'm saying through the browse and add a mod feature, not the
download and drop it in the mods folder that so many newb pack devs
actually do.

**Comment by Darkere** [comment]
Would be quite a case... as far as I know twitch doesn't support 1.15.2 yet.

**Comment by kreezxil** [comment]
I stand corrected. I meant to say the GD Launcher from https://gdevs.io allows you to make 1.15.2 mod packs.
