### ISSUE TITLE
Importer cant pull out items from OEM Ender Chest

### ISSUE THREAD

**Issue by carlucci9660** [raoulvdberge/refinedstorage#2412]
#### Steps to reproduce: Can't reproduce as it doesnt work to begin with
1.
2.
3.
...

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.14.4
- Forge: 28.1.115
- Refined Storage: 1.7.3

Does this issue occur on a server? [yes/no]

#### If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here]

**Comment by Darkere** [comment]
The Vanilla ender chest does not implement any item handlers as such RS importers are unable to pull items from them. You will notice that other item transport methods and even the vanilla hopper have the same problem.

**Comment by carlucci9660** [comment]
thanks for the quick response. you are top notch. let me ask you this, anyway to create a chest on your end that functions like an ender chest, with a ender bag or backpack to solve this issue. happy to donate your cause so im not just demanding something and you get nothing in return.

**Comment by Darkere** [comment]
For 1.14 I've only found https://www.curseforge.com/minecraft/mc-mods/dimstorage
for cross-dimensional item transfer. 

RS can do it on 1.12 but the functionality hasn't made it into the 1.14/1.15 versions yet.

**Comment by carlucci9660** [comment]
ok so ill check it out, but does that mean you wouldnt be willing to add an item such as ender chest that can import items out, it would be a nice addition to your amazing creation.
