### ISSUE TITLE
[1.14.4] Server's hanging, blames Refined Storage.

### ISSUE THREAD

**Issue by Gbergz** [raoulvdberge/refinedstorage#2414]
#### Issue description:
Server goes online, immediately "freezes/hangs" then crashes.

#### What happens:
Server crashes for whatever weird reason. Wish I could give you more info.

#### What you expected to happen:
Server stays on.

#### Steps to reproduce:
1. Have my Server open for a little bit.
2. Wait..
3. Server Hangs & then leads to crash.
4. Profit.

#### Version:

- Minecraft: **1.14.4**
- Forge: **28.1.107**
- Refined Storage: **1.7.3**

Does this issue occur on a server?
- **Yes.**

#### If a (crash)log is relevant for this issue, link it here:
https://gist.github.com/Gbergz/be04fc3a88982b7fac141923366c7b4d

**More info**
I've tried disabling the ServerHangWatchdog, though same issue is present.

**Comment by Darkere** [comment]
The crash is a watchdog crash. That, unfortunately, means that whatever was running at the time appears in the crash log... not necessarily the thing that is actually causing the problem. 

If you've tried disabling the watchdog then what happens if you do?

**Comment by Gbergz** [comment]
If I disable the watchdog it just stays frozen until it eventually turns off.

**Comment by Darkere** [comment]
Ok figured. 
I afraid is not much I can do for you. 

The crashreport indicates a setup with an RFtools builder inserting items into a Dank with an external storage attached. I don't think that would be particularly laggy.. But like I said chances are it's not what is causing the actual issue. 

To figure that out you would need to do some profiling with a program like Visualvm.

**Comment by raoulvdberge** [comment]
It's most likely a deadlock
