### ISSUE TITLE
Strange Refined storage texture issue

### ISSUE THREAD

**Issue by icebolt9000** [raoulvdberge/refinedstorage#2415]
#### Issue description:
texture issue
#### What happens:
Server crashed and reconnected i got this everytime
admin changed forge setting to delete the blocks causing issues
because server kept crashing
#### What you expected to happen:
fix texture issue

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.15.1
- Forge: forge-30.0.42
- Refined Storage: 1.8

Does this issue occur on a server? [yes/no]
yes
#### If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here]
https://i.imgur.com/4yHA5A0.png
By me

https://cdn.discordapp.com/attachments/671376747157258250/672161733095456768/2020-01-30_05.30.07.png
by other player

**Comment by Darkere** [comment]
Have you restarted your own game yet? I believe this may occur when reloading textures.

**Comment by icebolt9000** [comment]
i re loaded and re installed pack did not work
