### ISSUE TITLE
When autocrafting, keeps asking for bucket of liquids even when fluid is kept in the system

### ISSUE THREAD

**Issue by carlucci9660** [raoulvdberge/refinedstorage#2417]
#### Steps to reproduce:
1.
2.
3.
...

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.14.4
- Forge: 28.1.117
- Refined Storage: Latest build

Does this issue occur on a server? [yes/no]

#### If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here]

**Comment by Darkere** [comment]
https://refinedstorage.raoulvdberge.com/wiki/autocrafting-with-filled-buckets

**Comment by carlucci9660** [comment]
ok, i got the idea, but when making the pattern....how do put the liguid form into the pattern (1000 mB of the fluid of your choice) when i place it in the pattern via a bucket, it comes up as fluid in a bucket ?

also Im running 1.14.4, thermal exampsion is not ported over, what machine can i use to fill it with >?

**Comment by Darkere** [comment]
On the left side of the pattern GUI is a button that switches between item and fluid view. 

You can create a bucket filling machine using vanilla dispensers in combination with a constructor.  For 1.14 I've gone with silent mechanisms pump instead of the dispenser but it works the same way.

**Comment by carlucci9660** [comment]
how did you use the pump from Silent Mech's ? I placed it, put a crafter to it, put my liquid patterns in there and for some reason it keeps pulling water into it.....can you show me or explain how you set this up, please....
