### ISSUE TITLE
Feature Request: Dual Priority Option for Bi-directional Interfaces

### ISSUE THREAD

**Issue by Cheata** [raoulvdberge/refinedstorage#2419]
It would be really handy to be able to set a different priority for input vs output on Bi-directional interfaces such as the External Storage Module.

For example: 
I have a chest slowly filling up with cobblestone automatically, attached to a network via an External Storage Module and a 1k drive on the same system to handle overflow. 
I have a High priority set on the external storage so that any cobblestone I put in the system manually tries to go to the External Storage First and any overflow ends up on the 1k drive.

However because of the high priority when I pull cobblestone from the system it grabs it from the chest first and not the overflow in the 1k drive. The end result is that the overflow eventually fills up.

Ideally I would like to be able to pull from the overflow drive first then from the external storage while still having cobblestone i put in the system going back into the external storage first.

**Comment by raoulvdberge** [comment]
It's fine as is

**Comment by Cheata** [comment]
LOL no its not but thats fine i perfer AE2 anyway :P
