### ISSUE TITLE
crash on client back to desktop when on server 1.9.4

### ISSUE THREAD

**Issue by SDUBZ** [raoulvdberge/refinedstorage#242]
forge:1.9.4-1990
refined storage: refinedstorage-0.7.19
crashlog:
[crash-2016-08-03_16.40.43-client.txt](https://github.com/raoulvdberge/refinedstorage/files/398801/crash-2016-08-03_16.40.43-client.txt)

**Comment by raoulvdberge** [comment]
Sorry, Refined Storage for MC 1.9.x is no longer being updated. Please update to MC 1.10, the update is painless.
