### ISSUE TITLE
[Feature Request] A block that act as both an interface and a crafter

### ISSUE THREAD

**Issue by changhe3** [raoulvdberge/refinedstorage#2420]
Many machines in many "core" tech mods have auto-eject capability. Currently you cannot make use of this in autocraft setup because a crafter don't have an internal inventory. It would be nice to be able to have a block that can both send a recipe into an machine and receive the crafted product and import them back into the RS network.

**Comment by raoulvdberge** [comment]
No

**Comment by changhe3** [comment]
I only want this because it would look nice and has less wires all over the place this way. Regardless, thank you for your mod and keep up with the good work in 1.15
