### ISSUE TITLE
Server crash: IllegalArgumentException - Should not be connected to another controller

### ISSUE THREAD

**Issue by RisingInIris2017** [raoulvdberge/refinedstorage#2421]
#### Issue description:
I have RS mod installed on my server. The server suddenly crashed.
#### What happens:
Server crashed.
#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12.2
- Forge: 14.23.5.2847
- Refined Storage: refinedstorage-1.6.15

Does this issue occur on a server? [yes/no]
Yes.
#### If a (crash)log is relevant for this issue, link it here:
https://paste.ubuntu.com/p/QgYqNqKYKD/

**Comment by raoulvdberge** [comment]
Weird, as the reproduction steps are  non existent I can't fix this.
