### ISSUE TITLE
Please add feature: "Craft as many as resource is available" in autocraft feature

### ISSUE THREAD

**Issue by LordHellscream** [raoulvdberge/refinedstorage#2424]
Often time we really want to craft as many of a kind of items as resource is available.
It's incredible painful to calculate how many I can make when autocraft says certain thing is missing. Will be great if such a feature can be added.

Many thanks for such a incredible mod.

**Comment by raoulvdberge** [comment]
Thx for the compliment but i don't like the idea

**Comment by LordHellscream** [comment]
or may be display how many you can craft with the number of resource you
have available?
