### ISSUE TITLE
Autocrafting with Mekanism doesnt work properly

### ISSUE THREAD

**Issue by MrLuxALot** [raoulvdberge/refinedstorage#2427]
#### Issue description:
When i want to autocraft a Induction Cell from Mekanism it says i am missing the energy cubes, wich arent missing
#### What happens:
I try to autocraft a Induction Cell. The Crafting Manager says the energy cubes are missing or arent craftable
#### What you expected to happen:
That my system can autocraft it successfully
#### Steps to reproduce:
1. Try to autocraft a Induction Cell

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12.2
- Forge: forge-14-23-5-2847
- Refined Storage: refinedstorage-1.6.15.jar

Does this issue occur on a server? [no]

**Comment by raoulvdberge** [comment]
Please use the search function on this issue tracker
