### ISSUE TITLE
[1.15.2] RS Loading improperly and crashing other mods

### ISSUE THREAD

**Issue by RViper80** [raoulvdberge/refinedstorage#2429]
#### Issue description:

Running the Forager 1.15.2 modpack, the game fails to load and blames BonsaiTrees.
Created a post on an issue over at https://github.com/thraaawn/BonsaiTrees/issues/146 , and was directed to post it here,

Disabling the Refined Storage mods makes the game load fine with BonsaiTrees.

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.15.2
- Forge: 31.1.1
- Refined Storage: 1.8.1

Does this issue occur on a server? [no]

#### If a (crash)log is relevant for this issue, link it here:

[Full log](https://pastebin.com/g7rsVqbp) - RS Error on line 157

**Comment by raoulvdberge** [comment]
Not sure what this means.

**Comment by raoulvdberge** [comment]
RS works fine on my machine, if constructing the mod would fail I wouldn't be able to launch it on my computer.

**Comment by RViper80** [comment]
Unfortunately, I no longer have the modpack files installed, so don't remember which version of the pack I was trying to run.

I assume it was 1.15.2-1 based on the date I made this, but I redownloaded the pack and it's working fine now, so must have just been something with my computer.  (I have since formatted and upgraded to Win10 from Win7)
