### ISSUE TITLE
I can't craft in my celestial altar!

### ISSUE THREAD

**Issue by akika47** [raoulvdberge/refinedstorage#2430]
Its suddenly happened a week ago. There is no problem with the structure or the starlight levels. The crafting recipe can't be wrong because i copied it from JEI. Here is the photo: 
![image](https://user-images.githubusercontent.com/61090999/74592352-a1167300-5020-11ea-8a81-e70f1b31c1f6.png)

**Comment by Darkere** [comment]
This is the issue tracker for refined storage...

Are you lost?

**Comment by akika47** [comment]
> This is the issue tracker for refined storage...
> 
> Are you lost?

Oh i see :D I did not saw the title
