### ISSUE TITLE
Request to add round robin to export

### ISSUE THREAD

**Issue by Edivad99** [raoulvdberge/refinedstorage#2432]
Hi, I wanted to ask you if it was possible to add to export the option to export objects in round robin mode.
I thought of something like I take 64 Items of the first object inserted in the export filter, then I take 64 of the next and so on.

**Comment by raoulvdberge** [comment]
The exporter already uses round robin to cycle between the export configuration.

**Comment by TronWoWGamer** [comment]
Round Robin is needed on the interface so when limiting the number of exported items, it cycles through multiple items that are needed for an RFTools crafting operation.
