### ISSUE TITLE
[1.12.2] Crash when using Mouse Tweaks item scrolling in pattern grid

### ISSUE THREAD

**Issue by JeffersonDoan** [raoulvdberge/refinedstorage#2436]
#### Issue description:
Crash when scrolling over items (with Mouse Tweaks installed) in the pattern grid.

#### What happens:
With pattern grid set to "process" and an item in the ingredient field, scrolling while hovering over the item will crash the game.

#### What you expected to happen:
Ignore Mouse Tweaks trying to increase/decrease the item stack size if being used as a processing ingredient in the pattern grid.

Optionally allow increasing/decreasing stack size by scrolling provided item are available in the system?

#### Steps to reproduce:
1. Place creative controller and pattern grid in the world.
2. In the pattern grid, check "processing" and place any item in the input field.
3. While hovering over the input item, scroll in any direction.
...

#### Version (make sure you are on the latest version before reporting):
- Minecraft: 1.12.2
- Forge: 14.23.5.2847
- Refined Storage: 1.6.15
- Mouse Tweaks: 2.10

Does this issue occur on a server? 
Yes

#### If a (crash)log is relevant for this issue, link it here:
https://paste.dimdev.org/kaboxahago.rb

**Comment by raoulvdberge** [comment]
duplicate #2247
