### ISSUE TITLE
Grid not letting me store items

### ISSUE THREAD

**Issue by Karanmbt** [raoulvdberge/refinedstorage#2437]
#### Steps to reproduce:
1.
2.
3.
...

#### Version (make sure you are on the latest version before reporting):

- Minecraft:1.15.2
- Forge:31.1.12
- Refined Storage:1.8.1

Does this issue occur on a server? [yes/no]
no
#### If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here]

**Comment by Darkere** [comment]
Check the drives. Either the disks are full or you've changed the mode on the left to whitelist.

**Comment by Karanmbt** [comment]
> Check the drives. Either the disks are full or you've changed the mode on the left to whitelist.

it worked thanks @Darkere
