### ISSUE TITLE
[1.15.2] Mekanism Cardboard box and Cyclic Sack of Holding breaking stuff.

### ISSUE THREAD

**Issue by Quu1337** [raoulvdberge/refinedstorage#2439]
#### Issue description:
Mekanism Cardboard box and Cyclic Sack of Holding can take secured/protected RS network blocks.
Both of them can rip Security Manager out of connected networks, cardboard box removes all Security Cards from it, making it useless.

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.15.2
- Forge: 31.1.14
- Refined Storage: 1.8.1

Does this issue occur on a server? [yes/no] yes.

https://github.com/mekanism/Mekanism/issues/5899#issuecomment-590409035

"Due to how tags work I would say the modpack developer should be disabling things like the refined storage security manager. (Or refined storage themselves could just include things they don't think should be picked up in our tag, which would only make it do anything when both mods are loaded)."

https://github.com/Lothrazar/Cyclic/issues/1321

**Comment by raoulvdberge** [comment]
Crazy. You'd think that RS blocks would immediately rip through cardboard...

**Comment by Lothrazar** [comment]
Hey dev of cyclic here.

Should i check if its "unbreakable", or whats the best way to check "Can player harvest this"

**Comment by raoulvdberge** [comment]
@Lothrazar  RS uses the BlockEvent.BreakEvent and cancels that if the block can't be broken.
