### ISSUE TITLE
[1.12.2] Processing Patterns That Use the Resin Funnel Augment in [Thermal Foundation] Sawmill Machine Have the Wrong Input/Output

### ISSUE THREAD

**Issue by Runzugirl** [raoulvdberge/refinedstorage#2441]
#### Steps to reproduce:
1. Open up the pattern grid.
2. Add any log into planks recipe that uses the Resin Funnel augment.
3.  Switch type button between Item and Liquid and sap is mistakenly on the input side.
...

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12.2
- Forge: 14.23.5.2847
- Refined Storage:1.6.15
- Thermal Foundation 2.6.3.27

Does this issue occur on a server? [yes/no] Don't know. I only play SP.

**Comment by Darkere** [comment]
Not an RS issue. Thermal Expansion is adding them as input to JEI. RS can only read what JEI knows.

**Comment by KingLemming** [comment]
No, we are not doing that actually. They are very correctly being added as what they should be - outputs.

**Comment by Darkere** [comment]
So I've double-checked with a debugger and can confirm that JEI is giving us the Resin with the input flag set to true.
![image](https://user-images.githubusercontent.com/4283717/75634050-73c5e980-5c0a-11ea-8dc0-29127ab3b14d.png)

This is actually not the only recipe I can think of where this happens. Any chance that JEI sets the input flag on the outputs if no input fluid is provided?

**Comment by KingLemming** [comment]
I honestly don't know. I'm doing this, for reference:

https://github.com/CoFH/ThermalExpansion/blob/1.12/src/main/java/cofh/thermalexpansion/plugins/jei/machine/sawmill/SawmillRecipeWrapper.java#L102
