### ISSUE TITLE
[1.15.2] - zh_cn.json

### ISSUE THREAD

**Issue by EnterFor** [raoulvdberge/refinedstorage#2444]
There are a lot of mistakes
It has been corrected and completed

[zh_cn.zip](https://github.com/raoulvdberge/refinedstorage/files/4274847/zh_cn.zip)

**Comment by raoulvdberge** [comment]
hi, please create a pull request for this. so I can see the actual changes.

**Comment by raoulvdberge** [comment]
Normally I accept language changes in issues too, but there is a chance your changes would conflict with https://github.com/raoulvdberge/refinedstorage/pull/2418
