### ISSUE TITLE
[1.15.2] Payload max size disconnect

### ISSUE THREAD

**Issue by Rumpelstiltskinny** [raoulvdberge/refinedstorage#2445]
_#### Issue description:_ Accessing either crafting grid & wireless crafting grid (RS addons) with millions (no exaggeration) of items causes client to disconnect from dedicated server.

_#### What happens:_ client disconnect

_#### What you expected to happen:_ Remain connected to dedicated server when accessing RS grid that contains too many items while utilizing a maximum packet size.

_#### Steps to reproduce:_
1.Allow RS system (creative controller & disk) to accumulate millions of items through various auto collecting means...e.g. farming, quarries, mob grinders **(suspected cause is too many different items that aren't stacking)** etc
![Refined Storage disk](https://user-images.githubusercontent.com/5091432/75822035-1b9afe80-5d54-11ea-9297-2046851ac431.jpg)

2.Access RS grid
3.Disconnect
...

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.15.2
- Forge: 31.1.18
- Refined Storage: refinedstorage-1.8.1 & refinedstorageaddons-0.6.1

Does this issue occur on a server? [yes/no] Yes

_#### If a (crash)log is relevant for this issue, link it here:_ Unable to locate any reference to this issue in client/server logs (neither debug nor latest), only a screenshot of payload error msg

![Refined Storage payload](https://user-images.githubusercontent.com/5091432/75819554-bfce7680-5d4f-11ea-9efb-b0799e2b1d9c.jpg)

[pastebin/gist/etc link here]

**Comment by raoulvdberge** [comment]
Please check for duplicates before making an issue
