### ISSUE TITLE
[0.8.15] Some item not showing up in Grid until searched

### ISSUE THREAD

**Issue by oitsjustjose** [raoulvdberge/refinedstorage#245]
As the title says, some items (while stored in the network flawlessly) don't show up in the grid until they're searched!

These items are in standard 4k Disks, so I can't imagine that it's a problem with how I've got my system set up.

Before search (these are all my 1 x stacking items):

![ss 2016-08-04 at 05 12 42](https://cloud.githubusercontent.com/assets/3887324/17420176/de35cb40-5a66-11e6-8729-5105b4e69659.png)

After search:

![ss 2016-08-04 at 05 14 13](https://cloud.githubusercontent.com/assets/3887324/17420182/ea9cd27a-5a66-11e6-9f33-b4e0c8abca17.png)

Notice that neither the Chisel chisel, nor the Chisels n Bits Chisel and Bit Bag showed up without searching first. This bug only occurs when sorting by Quantity

**Comment by raoulvdberge** [comment]
this is an offset issue in the scrollbar code
