### ISSUE TITLE
another "network receiver won't work in the nether" post

### ISSUE THREAD

**Issue by systemshaper** [raoulvdberge/refinedstorage#2451]
#### Issue description:
I've searched through past issues and found a couple similar to this, but none with a resolution I am able to apply to my situation. I am unable to create a network connection across dimensions. I can successfully make connections within two nether networks or within two overworld networks, but not between an overworld and nether network. I am placing a chunk loader in each location, and I have already personally experienced that this chunk loader works (because I use it for multiple distant farms and power generators that I have confirmed are working when I'm in different dimensions or logged out of the server entirely). 

#### What happens:
The network receive never receives power.

#### What you expected to happen:
The network receive would receive power once I used the network card to connect it back to the network transmitter, as with the other network connections I've made in the same world.

#### Steps to reproduce:
1. load a chunk in the overworld and nether, such as by placing a chunk loader block.
2. place a network transmitter and a powered controller in the overworld
3. place a network receiver in the nether, and right click it with a network card.
4. place the network card into the transmitter in the overworld.
5. return to find the receive in the nether still grey and unpowered.

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.14.4
- Forge: 1.40.4 28.2.0
- Refined Storage: 1.7.3

Does this issue occur on a server? Yes this issue was originally observed on my server, but I have performed most of my testing in single player worlds.

MODS:
The only mods I am using (besides Refined Storage itself) are the following chunk loader mods, each of which I've tested.
chunkloader-1.14.4-1.0.0
PersistentBits-1.14.4-2.0.2
ChunkNoGoByeBye-1.14.4-1.0.3

#### If a (crash)log is relevant for this issue, link it here:
N/A

**Comment by Darkere** [comment]
Cross dimensional network connections do not work in 1.14 or 1.15 yet.

**Comment by systemshaper** [comment]
Thanks, it's good to have confirmation at least.
