### ISSUE TITLE
[1.12.2] Can't work well with mod Avaritia [Avaritia]

### ISSUE THREAD

**Issue by papadave66** [raoulvdberge/refinedstorage#2452]
#### Issue description:
Can't add thousands of input in a single pattern
#### What happens:
Add a recipe for Singularity of avaritia
![add_recipe](https://user-images.githubusercontent.com/14260128/76675979-2417f280-65fa-11ea-9007-fb0ea29a6284.png)
but after wrote into the pattern .  The input amount is not same as it need. It's just one
![wrong_input](https://user-images.githubusercontent.com/14260128/76676007-4c9fec80-65fa-11ea-94e6-060a5243a010.png)

#### What you expected to happen:
Input item as it need
#### Steps to reproduce:
1. write a recipe for avaritia
2. input number alway 1
3.
...

#### Version (make sure you are on the latest version before reporting):

- Minecraft:1.12.2
- Forge:14.23.5.2847
- Refined Storage:1.6.15

Does this issue occur on a server? [yes/no] YES

**Comment by Tahakk** [comment]
it really does not work that way. U got to have exporters controlled by redstone. Or at least that's how it worked back in the days.
