### ISSUE TITLE
[1.12.2] There was a severe problem during mod loading that has caused the game to fail

### ISSUE THREAD

**Issue by MusicMaestro123** [raoulvdberge/refinedstorage#2454]
#### Steps to reproduce:
1. Get refined storage
2. Open the minecraft launcher
3. Press play
...

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12.2
- Forge: 14.23.5.2768
- Refined Storage: 1.6.15

Does this issue occur on a server? yes and no

#### If a (crash)log is relevant for this issue, link it here: [Minecraft crash log](https://pastebin.com/NV4MPXKc)

[pastebin/gist/etc link here]

**Comment by Darkere** [comment]
Update forge
