### ISSUE TITLE
Disk manipulator gone after server crash

### ISSUE THREAD

**Issue by ValonInc** [raoulvdberge/refinedstorage#2458]
#### Issue description:

the disk manipulator block is gone (together with the disks and upgrades inside) after a server crash.

#### What happens:

Ive used the disk manipulator until the server crashed. After restarting the server I have seen the disk manipulator went missing.

#### What you expected to happen:

I expected the disk manipulator to be be still there, or the server not crashing at all.

#### Steps to reproduce:

1. use the disk manipulator

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12.2
- Forge: forge-14.23.5.2847
- Refined Storage: refinedstorage-1.6.15

Does this issue occur on a server? [yes/no]

yes

#### If a (crash)log is relevant for this issue, link it here:

https://pastebin.com/uxwUUMUZ

#### UPDATE:

Everything just got a little bit  weirder.
I copied my playerdata from a backup where I had the disks in my inventory to the current world (stopped the server, copied the files, started the server) and just have seen a Disk Manipulator in my old RS(at an older base). after placing it down I saw that the upgrades and Disk were still in there.

If this is intended behaviour maybe add a sign that will be placed at the destoryed block that says what happend I.e. "there was a crash, this machine has ben put (with its content) to the RS system at: x, y, z

**Comment by raoulvdberge** [comment]
I can't reproduce this
