### ISSUE TITLE
Splitting a storage block gives extra processor

### ISSUE THREAD

**Issue by Darkere** [raoulvdberge/refinedstorage#2459]
#### Issue description:
Removing the storage part from a storage block gives you an extra basic processor for some reason...

#### Steps to reproduce:
1. Shift-click with empty storage block
2.
3.
...

#### Version (make sure you are on the latest version before reporting):

- Minecraft:1.15.2
- Forge: 31.1.18
- Refined Storage: 1.8.1

**Comment by raoulvdberge** [comment]
Well, that's pretty normal considering storage blocks are made with a basic processor in the recipe?

**Comment by raoulvdberge** [comment]
Err, actually, it doesn't. So weird. It might've been that way in the past.
