### ISSUE TITLE
unable to interact with mobs

### ISSUE THREAD

**Issue by CaptStabbyPants** [raoulvdberge/refinedstorage#2462]
#### Steps to reproduce:
1.start new map
2.try to kill a mob
3.cant interact with them at all.
...

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12.2
- Forge:1.12.2-14.23.5.2847
- Refined Storage:1.16.5

Does this issue occur on a server? [yes/no] I noticed it first on my server with a bunch of mods so i tested it in single player and the bug was still present so i removed mods one by one until refined storage was the only mod running and it was still doing it, and tested with all the mods but refined storage and i can kill mobs milk cows ect

## If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here]

**Comment by raoulvdberge** [comment]
not RS

**Comment by CaptStabbyPants** [comment]
Not rs but when I uninstalled rs suddenly it went away.
