### ISSUE TITLE
Reproduction of 2241

### ISSUE THREAD

**Issue by ian-rampage** [raoulvdberge/refinedstorage#2464]
#### Issue description:
See issue 2241

#### What happens:
Hard crash when attached world leads, with abstract method error, latest version of ultimate alechmy.

#### What you expected to happen:
World to load successfully 

#### Steps to reproduce:
1. Launch ultimate alchemy 0.1.0 (latest).
2. Import linked world.
3. Attempt to start in world.

#### Version:

- Minecraft: 1.12.2
- Forge: 14.23.5.2796
- Refined Storage: 1.6.2 with add ons 0.4.3

Does this issue occur on a server? No

#### If a (crash)log is relevant for this issue, link 

filebin.net/hf955f3utffkorqj - or request an email attachment from me.

With the lockdown I cant look into this properly now (I'm separated from my dev box), mostly making this to remind myself to look into it more later.
P.s. feel free to assign this to me, and I'll look into it when I can.

**Comment by raoulvdberge** [comment]
Thx. This is a duplicate issue so I'll tag: #2241
