### ISSUE TITLE
[1.15.2] Feature request for couple OP commands.

### ISSUE THREAD

**Issue by Quu1337** [raoulvdberge/refinedstorage#2465]
#### Issue description:
Players autocrafting large RS addons disks cause server to basically halt, running 1-3 TPS for the duration of the craft, usually 30min-2hours.

#### What you wanted to happen:
Add OP command to cancel (or pause) all active crafts, preferably with args to stop only one player eg. /refinedstorage autocrafting stop playername/all
Maybe even own command to stop crafts from offline/online players?

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.15.2
- Forge: 31.1.27
- Refined Storage: 1.8.1

**Comment by Darkere** [comment]
How about fixing the lag issue instead?

**Comment by Quu1337** [comment]
Yeah. Slowing down crafts that drops TPS would be ideal, like AE2 does it. But as that is probably not easy to "fix", stopping them crafts with commands is good enough for me.

**Comment by raoulvdberge** [comment]
We'll be looking at autocrafting fixes to fix the underlying actual issue

**Comment by Ryonez** [comment]
This was a horrible idea to deny. We're facing this exact issue on a server, and I'm currently struggling to get to the damn crafting monitor to clear another players queue.

We could really use this.

**Comment by Darkere** [comment]
This actually got added. Also autocrafting is no longer causing TPS problems in 1.15+ so it shouldn't be needed.

**Comment by Ryonez** [comment]
Ahh. Sadly, a lot of servers are running older versions, the most common being 1.12.2, like the one ours is running on.

If this has been added, a backport would be a good idea.

**Comment by tth05** [comment]
The 1.12.2 is no longer being maintained here. I have a fork for 1.12.2 with many improvements that you can check out.
