### ISSUE TITLE
Importers and Exporters stop working RS 1.6.15, FTB Academy 1.1.0 cables fine

### ISSUE THREAD

**Issue by Barberfluids** [raoulvdberge/refinedstorage#2466]
#### Issue description: 
Using FTB Academy 1.1.0; RS 1.6.15 displays inventory items, so all connections are intact and cables work fine, however importers and exporters suddenly stop working on all machines and dynamos after use for four months.  The only thing I have done different is open up the single player instance on my LAN so my son can play on my build. After he logged in, we used the /quit_school command on Day One to drop him into the Overworld where he was playing with no issues.  He logs out and now the importers and exporters have stopped working. 

#### What happens: 
Importers and Exporters not working; materials (items or fluids) are not going into machines or being removed; I do notice the controller never lights up although it appears to have power because inventory of importers and exporters and cables are all showing in the display. 

#### Steps to reproduce:
1. Player 1 Creates a world using RS with importers and exporters
2. Open it up on a LAN
3. Player 2  downloads FTB Academy 1.10; clicks on multiplayer and selects world on the LAN.
4. Player 2 creates things and logs out.
5. Player 1 closes down world and logs in later.
6. Player 1 finds exporters and importers are not working but cables are working fine. 
...

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12.1
- Forge: 14.23.5.2846
- Refined Storage: 1.6.15
- FTB Academy: 1.1.0
- Java: 1.8.0_241

Does this issue occur on a server? [yes/no] Yes and also in single player. 

#### If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here]

**Comment by raoulvdberge** [comment]
The reproduction steps are not really helpful.
