### ISSUE TITLE
Duplication of steel

### ISSUE THREAD

**Issue by closeshot** [raoulvdberge/refinedstorage#2467]
#### Steps to reproduce:
1. place crafter
2. place barrel under crafter
3. place logistical transporter
4. place metallurgic infuser
5. placed interface for output items.
...

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.15.2
- Forge: 31.1.27
- Refined Storage: 1.8.1

Does this issue occur on a server? [yes/no] Don't have a server 

#### If a (crash)log is relevant for this issue, link it here: No crashes

[pastebin/gist/etc link here]

**Comment by Darkere** [comment]
This is only an RS issue if the barrel itself receives more items than there are in storage/on the pattern or only 1 item is inserted into the interface and 2 arrive in the storage. Otherwise, report to mekanism.
