### ISSUE TITLE
1.12 - Issue with JEI / NEI: Pattern Grid shows weird slots

### ISSUE THREAD

**Issue by D3nnis3n** [raoulvdberge/refinedstorage#2468]
#### Issue description:
When the search bar is activated slot overlay looks weird.

#### What you expected to happen:
Slot overlay should not look weird.

#### Steps to reproduce:
1. Open pattern grid
2. Activate JEI/NEI searchbar.

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12.2
- Forge: 2847
- Refined Storage: 1.6.15

Does this issue occur on a server? [yes/no]
yes

**Comment by Darkere** [comment]
Do you have a screenshot of how it looks?
"Weird" doesn't help.

**Comment by D3nnis3n** [comment]
I swear i added one, lol. I add it as soon as i'm back.

**Comment by D3nnis3n** [comment]
![refinedstorage](https://user-images.githubusercontent.com/25908592/78321729-10aed600-756d-11ea-9ff7-9bd31c9fc784.png)

**Comment by Darkere** [comment]
Looks like you have the item search feature from More Overlays enabled. Try double clicking the JEI search bar.

**Comment by D3nnis3n** [comment]
I don't have more Overlays, but i used JEI and NEI in conjunction with each other and that was indeed it. I didn't even know that "feature" existed. I've thrown out NEI and am happy now. Sorry for stealing your time and thanks! :)
