### ISSUE TITLE
Frame lag from supposed caching/sorting problem w/Chisels & Bits

### ISSUE THREAD

**Issue by BootyToast** [raoulvdberge/refinedstorage#247]
After going through the motions apparently there is some sort of compatibility issue with C&B that is causing frame drops while in any Grid interface that has a C&B block. Algorithm uses some fancy words to describe the exact problem here. Just scroll on down! 

https://github.com/AlgorithmX2/Chisels-and-Bits/issues/116#issuecomment-237938772

**Comment by raoulvdberge** [comment]
Interesting! Let me see if I can add sorting on demand instead of every frame, must be very doable.

**Comment by BootyToast** [comment]
Thanks for the help!
