### ISSUE TITLE
[1.15.2] Default interdimensionality doesn't work across dimensions

### ISSUE THREAD

**Issue by billyma6** [raoulvdberge/refinedstorage#2471]
#### Steps to reproduce:
1. set up a controller in one dimension
2. attach a network transmitter to the controller
3. place a network receiver in another dimension
4. connect the transmitter to the receiver through the network card and place it in the transmitter
5. attach a device to the receiver end
6. the device doesn't work

#### Version (make sure you are on the latest version before reporting): 

- Minecraft: 1.15.2
- Forge: 1.15.2-forge-31.1.27
- Refined Storage: refinedstorage-1.8.1

Does this issue occur on a server? [yes/NO], this is my singleplayer work

#### If a (crash)log is relevant for this issue, link it here: 

N/A

**Comment by Neurom707** [comment]
No cross dimensions currently. 

Its on the list to fix: https://github.com/raoulvdberge/refinedstorage/issues/2306

**Comment by raoulvdberge** [comment]
This is a known issue indeed
