### ISSUE TITLE
[1.12.2]-Creafter Issue 

### ISSUE THREAD

**Issue by BeaterHouba** [raoulvdberge/refinedstorage#2474]
Are you limiting the speed of Reborn sotrage addon Multiblock structure crafting PC?

https://github.com/TechReborn/RebornStorage/issues/158

Multiblock Crafter is too slow (I am using more than 32 crafting CPU and 1 crafting of piston takes about 1s )-(MC ver. 1.12.2)
Addon Core ver. 3.18.1.514
Addon ver. 3.3.4.1

Refined Storage ver. 1.6.15
Refined Storage addons ver. 0.6.1

And devs of Reborn storage said that it must be on your side.

Its pain because its making Multiblock crafter utterly useless. But the storage for patterns is nice (I have about 158 patterns and fitting this into crafters is pain)

Fix will be appreciated (i don't know if you still support older ver. but i hope you are)

Thank's for your hard work.

**Comment by raoulvdberge** [comment]
no, reborn storage can decide how fast it needs to be.
