### ISSUE TITLE
TPS Crash on crafter with full target inventory

### ISSUE THREAD

**Issue by lucasmontec** [raoulvdberge/refinedstorage#2476]
#### Issue description:

If the crafter doesn't have space on the target inventory, it destroys server TPS.

#### What happens:

Place a crafter with a small output buffer. Schedule a huge craft. TPS will fall to less than one.

#### What you expected to happen:

The check if the inventory is full is probably allocating memory or checking too many times per frame. It should instead listen to block updates on the target inventory and check only if changes were detected or after a long while (or even manually after a few failed tries).

#### Steps to reproduce:
1. Place a crafter with a small output buffer.
2. Schedule a huge craft. 
3. TPS will fall to less than one.

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12.2
- Forge: 14.23.5.2846
- Refined Storage: 1.6.15

Does this issue occur on a server?
yes

**Comment by Darkere** [comment]
Fixed in #2406
