### ISSUE TITLE
Controller still consumes baseUsage when turned off.

### ISSUE THREAD

**Issue by Darkere** [raoulvdberge/refinedstorage#2478]
#### Issue description:
When changing the Server config so that a controller has a base power usage larger than 0 it will continue using power when turned off. 
#### What happens:
consumes power while turned off

#### Steps to reproduce:
1. change config
2. place, charge and turn off the controller. 
3. watch power bar go down
...

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.15.2/1.14.4
- Forge:31.1.36
- Refined Storage: 1.8.1

**Comment by NillerMedDild** [comment]
Thanks!

**Comment by raoulvdberge** [comment]
Np!
