### ISSUE TITLE
[1.15.2] Disk Drive Lighting Issue

### ISSUE THREAD

**Issue by ocram9** [raoulvdberge/refinedstorage#2479]
#### Issue description:
When placing disk drives next to each other they get darker the more you add them. I do not have optifine or any other lighting mod (except mods that add light sources) installed. I have also tested this with just the refined storage mod and the issue persists.

#### Steps to reproduce:
1. Place disk drives next/on top of each other

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.15.2
- Forge: 31.1.41
- Refined Storage: 1.8.1

#### Does this issue occur on a server? [yes/no]
Yes.

#### Screenshots:
My setup on one side of the room (that black wall are disk drives):
![2020-04-09_03 32 35](https://user-images.githubusercontent.com/49008532/78848886-50653a00-7a13-11ea-8047-92c00409dc52.png)

Setup on the other side:
![2020-04-09_03 32 42](https://user-images.githubusercontent.com/49008532/78848936-712d8f80-7a13-11ea-8418-478e0dac7f8d.png)

Example of the issue outside setup:
![2020-04-09_03 35 13](https://user-images.githubusercontent.com/49008532/78848978-89051380-7a13-11ea-867e-83aa25e33106.png)

**Comment by Darkere** [comment]
This is a forge issue. An experimental version of the fix is in the latest version. Not sure if it needs any code changes to work

**Comment by raoulvdberge** [comment]
Update to the latest Forge and set "experimentalForgeLightPipelineEnabled = true" in the forge-client.toml config
