### ISSUE TITLE
[1.12.2] Unable to auto-craft fireworks

### ISSUE THREAD

**Issue by RRyyas** [raoulvdberge/refinedstorage#2481]
#### Issue description:
Fireworks cannot be crafted in RS autocrafting system
#### What happens:
The Start button in the "Craft Amount GUI" greys out whenever you try to click it to craft fireworks with a long flight duration
#### What you expected to happen:
The autocrafting GUI continues to the material preview GUI when you press the start button
#### Steps to reproduce:
1. Create a controller, a crafting grid, crafter and a pattern grid, along with a blank pattern
2. Create a crafting pattern with 3x gunpowder and a piece of paper, place the pattern in a crafter
3. Insert 3 gunpowder and 1 paper in the grid.
4. Attempt to craft the fireworks with the "Craft" selection in the crafting grid  

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12.2
- Forge: 2847
- Refined Storage: 1.6.15

Does this issue occur on a server? Is playing on singleplayer

#### If a (crash)log is relevant for this issue, link it here:

https://pastebin.com/TPzDXSQx

**Comment by Darkere** [comment]
Try turning off oredict if you have it enabled. Not sure if that will help. 
This issue was fixed in 1.15.

**Comment by RRyyas** [comment]
> Try turning off oredict if you have it enabled. Not sure if that will help.
> This issue was fixed in 1.15.

I also made a gfycat video explaining the issue and how to exactly reproduce it: https://gfycat.com/hiddenconventionallhasaapso

**Comment by raoulvdberge** [comment]
wontfix for 1.12
