### ISSUE TITLE
Item duplication and texture bug

### ISSUE THREAD

**Issue by THEAN24** [raoulvdberge/refinedstorage#2483]
#### Issue description: #
After few hours of gameplay I notice that a single diamond sword just duplicated to 128 and when ever I take the swords I only get one and there is still 127 in the system. Also I notice that when ever I place two Disk Drive next to each other the texture seems to darken.

Here is a vid link for reference: https://drive.google.com/file/d/1p2eDn-i1stDpws89iVdW40os5SQ2d4Wm/view?usp=sharing

#### Steps to reproduce:
1. Put a single item in the system
2. leave it for few minutes or leave and reconnect to the world
3. check the item if duplicated
...

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.15.2
- Forge: 31.1.46
- Refined Storage: 1.8.1 (beta / latest)

Does this issue occur on a server? [yes/no] No

#### If a (crash)log is relevant for this issue,

[pastebin/gist/etc link here]

**Comment by Darkere** [comment]
Did you copy disks or disk drives in some way?

The texture bug is known and being worked on by the forge team.

**Comment by THEAN24** [comment]
> 
> 
> Did you copy disks or disk drives in some way?
> 
> The texture bug is known and being worked on by the forge team.

No I just leave it for several hours when I farm then when I come back it just multiplied

**Comment by THEAN24** [comment]
I just tried another test and when I rejoin the world it seems to do the same thing again.

Reference vid: https://drive.google.com/file/d/1yDFG-X814lk-3F0AEuBhu80OHxteM-PR/view?usp=sharing

**Comment by Darkere** [comment]
Hmm are you in the overworld?

**Comment by THEAN24** [comment]
> 
> 
> Hmm are you in the overworld?

Yes

**Comment by MelanX** [comment]
@Darkere They are copied, he gave me the world and all disks have the same uuid
