### ISSUE TITLE
About Autocarfting

### ISSUE THREAD

**Issue by Skealkik** [raoulvdberge/refinedstorage#2485]
#### Issue description:
about 
Thermal Expansion 
    alchemical imbuer

#### What happens:
alchemical imbuer have a augment Reagent Recovery
have chance to not consume reagent
then if use this augment to build an automated production line.it will be stuck.
#### What you expected to happen:
Remaining reagent can be auto remove or other useful plan.
#### Steps to reproduce:
1.put an alchemical imbuer
2.Upgrade it 
3.put Augment:Reagent Recovery
4.set an automated production line about potion
5.start this production.

#### Version (make sure you are on the latest version before reporting):

- Minecraft:1.12.2
- Forge:14.23.5.2847
- Refined Storage:refinedstorage-1.6.15

Does this issue occur on a server? [yes/no]
maybe
#### If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here]

**Comment by Darkere** [comment]
What are you using to get the fluids from the alchemical Imbuer into your RS system?

**Comment by Skealkik** [comment]
> What are you using to get the fluids from the alchemical Imbuer into your RS system?
RS self's Importer.
and i found Thermal Expansion induction smelter have same issue.
induction smelter have an augment.Augment:Metallurgical Recovery
have chance to not consume metallurgical.
but induction smelter only have 2 kinds of useful metallurgical.and only one step.
alchemical imbuer have more than 10 diffrent reagent,and for brewing potion it have atlest 3 step.

**Comment by Darkere** [comment]
For the alchemical imbuer you will need to either filter the importer or put a tank of some sort between the importer and the imbuer. There is a bug/feature with thermal where it allows extraction from the input through the output side. 

For the Induction smelter. RS is unable to handle "chance". Anything chance based needs to happen outside what RS auto crafting specifies or you will likely run into problems.

**Comment by Skealkik** [comment]
> For the alchemical imbuer you will need to either filter the importer or put a tank of some sort between the importer and the imbuer. There is a bug/feature with thermal where it allows extraction from the input through the output side.
> 
> For the Induction smelter. RS is unable to handle "chance". Anything chance based needs to happen outside what RS auto crafting specifies or you will likely run into problems.

Ok i understand.THX
