### ISSUE TITLE
[1.15.2] Client crash by clicking on priority  

### ISSUE THREAD

**Issue by zerlix** [raoulvdberge/refinedstorage#2486]
#### Issue description:
If I want to change the priority  (External Storage / Disk Drive), the client crashes

#### What happens:
When I click on Priority  the client crashes

#### Steps to reproduce:
1. Connect a external Storage / Disk Drive
2. Open the GUI and click on priority
3. Client Crash

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.15.2
- Forge: 31.1.46
- Refined Storage: 1.8.1

Does this issue occur on a server? [yes/no]

#### If a (crash)log is relevant for this issue, link it here:

https://pastebin.com/S4cujUk6

**Comment by Darkere** [comment]
Crash due to the quickstack mod. I happen to know that the issue was reported to the mod author already. 
It doesn't appear to be reported on their github though so check there.

**Comment by zerlix** [comment]
I deactivated Quickstack and have no more crashes. Thank you
