### ISSUE TITLE
Crafting Lag

### ISSUE THREAD

**Issue by someaddons** [raoulvdberge/refinedstorage#2487]
#### Issue description:
One player has been autocrafting some disks and its using up ~40% of the servers tick time, causing serverwide lag. See https://spark.lucko.me/#3TR4Kg7iDy onPostWorldTick
#### What happens:
Server lags
#### What you expected to happen:
Crafting to not be that laggy, and preferably happen within the TE tick instead of world tick
#### Steps to reproduce:
1.
2.
3.
...

#### Version (make sure you are on the latest version before reporting):

- Minecraft:1.15.2
- Forge:
- Refined Storage:

Does this issue occur on a server? [yes/no] yes

#### If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here]

**Comment by Darkere** [comment]
Fixed in #2406
