### ISSUE TITLE
[Suggestion] Operators in Crafting Request

### ISSUE THREAD

**Issue by DownLoude** [raoulvdberge/refinedstorage#2488]
#### Suggestion description:
Allow us to put operators in the crafting request menu.

#### What happens:
When you put * it will multiply the numbers, / will integer divide, - subtract, + add and possibly ^ will power it. Would follow basic operation order, allow brackets etc. This is useful when, for example you want to build multiple of the same multiblock structure and you want to do it easily.

#### Steps to reproduce:
1. Place the numbers in with the operators
2. Press craft
3. Will craft that amount

#### Version:
- Minecraft: Any/All
- Forge: Any/All
- Refined Storage: Any/All

**Comment by raoulvdberge** [comment]
I like the idea, but it's more work than it's worth.
