### ISSUE TITLE
Drawer Extraction Bug

### ISSUE THREAD

**Issue by SgtSnipey** [raoulvdberge/refinedstorage#2493]
#### Steps to reproduce:
1. Place a compacting drawer
2. Pump Coal, Redstone, Lapis into the controller
3. Try and extract it from the Storage Drawer controller you will receive nothing 
...

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.14.4
- Forge: 28.2.4
- Refined Storage: 1.7.3
- Storage Drawers: 6.0.7

Does this issue occur on a server? [yes/no] Yes

#### If a (crash)log is relevant for this issue, link it here: No crash

[pastebin/gist/etc link here]

**Comment by Darkere** [comment]
What did you use to insert into the drawer and what did you use to try to extract the items?

**Comment by SgtSnipey** [comment]
Importer and Exporter on the drawer controller, Tried to import and export directly from each drawer but when I put Import buses on them it would only extract the items not the blocks.

**Comment by Darkere** [comment]
Did you filter the importer to import Blocks?

**Comment by SgtSnipey** [comment]
I tried it had no effect it just ignored and kept taking items out and the export bus would put them back in and created a loop

**Comment by Darkere** [comment]
Make sure you set the importer to whitelist blocks, or to blacklist ingots. Default is an empty black list.

**Comment by SgtSnipey** [comment]
I did check

**Comment by SgtSnipey** [comment]
Okay now I feel dumb it works on the drawer Directly, and they do end up in the system.

**Comment by SgtSnipey** [comment]
The first bug report is still valid FYI
