### ISSUE TITLE
Game Crashes when im using the mod

### ISSUE THREAD

**Issue by StixxerTV** [raoulvdberge/refinedstorage#2494]
#### Issue description:
whenever i try to use the mod it crashes
#### What happens:
i load and it wont even load into the mojang screen, then crashes
#### What you expected to happen:
to load
#### Steps to reproduce:
1. MultiMC
2. Install forge and add refined storage
3. load up
...

#### Version (make sure you are on the latest version before reporting):

- Minecraft:
- Forge:
- Refined Storage:

Does this issue occur on a server? [yes/no]

#### If a (crash)log is relevant for this issue, link it here:

https://pastebin.com/2sNedPN8

**Comment by Darkere** [comment]
Update Forge. You are close to 100 versions behind.
