### ISSUE TITLE
[mc1.12.2][1.6.16] Importer in liquid mode doesn't pull fluids from Thermal Innovation

### ISSUE THREAD

**Issue by Heimdell** [raoulvdberge/refinedstorage#2495]
#### Issue description:

Importer in liquid mode doesn't pull fluids from Thermal Innovation.

#### What happens:

1. I set up magma crucible
2. I fed it with 10 redstone.
3. I configured back to be the output, checked if the back texture has orange square.
4. I put an importer, set it to liquid mode, connected it to the network.
5. Nothing happens, liquified redstone remains in crucible.

#### What you expected to happen:

5. Liqufied redstone is pulled into the system.

#### Steps to reproduce:

See above.

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12.2
- Forge: 14.23.5.2847
- Refined Storage: 1.6.16
- Thermal Foundation: 2.6.7.1
- Thermal Innovation: 0.3.6.1

#### Does this issue occur on a server?

I did not tested, I am making a server modpack locally. Though, strictly speaking, it happens on _internal_ server, does it count?

#### If a (crash)log is relevant for this issue, link it here:

It did not crash.

**Comment by Darkere** [comment]
Do you have storage space for liquids in your system?

**Comment by Heimdell** [comment]
Oh

**Comment by Heimdell** [comment]
Anywaaaay, I've "solved" it by exproting buckets into Fluid Transposer. But I'll craft some fluid disks to check as well.
