### ISSUE TITLE
[1.12.2][1.6.16] Instrument usage in craft breaks autocrafting

### ISSUE THREAD

**Issue by Heimdell** [raoulvdberge/refinedstorage#2496]
#### Issue description:

If an instrument is used in craft, then crafter will search for one with the same damage.

#### What happens:

Crafter only uses pristine instrument in craft. Also, it requires 1 instrument PER OPERATION, despite it lasting a bit lot longer then one use.

#### What you expected to happen:

I expect it to see the instrument as if it was a stack with the quantity equal to its hit points **unless** it is used in a processing recipe.

I also expect crafter to not ignore instrument after a single point of damage was received by it.

#### Steps to reproduce:

(Draw plate is an instrument with 512 uses)

1. Install `ProjectRed Base` and `ProjectRed Core`
2. Set up recipe: (copper ingots + draw plate) -> copper wire.
3. Put one draw plate and 64 copper ingots.
4. Attempt to craft 64 copper wires.
5. Observe that 63 draw plates are missing and 1 available.
6. Craft 1 copper wire.
7. Attempt to craft 63 copper wires.
5. Observe that 63 draw plates are missing and 0 available.
8. Re-enter inventory grid and observe that draw plate _is_ there, but it has 511 out of 512 durability.

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12.2
- Forge: 14.23.5.2847
- Refined Storage: 1.6.16
- Thermal Foundation: 2.6.7.1
- Thermal Innovation: 0.3.6.1
- Project Red *: 4.9.4.120

#### Workaround

The ProjectRed autocrafting table with an instrument pre-loaded and a plan in can be used, with said instrument blacklisted in the importer.

I didn't manage to make it restock the instrument. How do I do it?

**Does this issue occur on a server?** Yes.

**Comment by Darkere** [comment]
Use an exporter with a crafting upgrade to stock the instrument. 

Auto crafting not working with reusable items is known.
