### ISSUE TITLE
[1.12.2] Draconic Evolution auto crafting unable to find item

### ISSUE THREAD

**Issue by BrianPetkovsek** [raoulvdberge/refinedstorage#2498]
#### Issue description:

Seems to be a problem with JEI. After placing them items manually it was able to detect the item.

Draconic Evolution there is weapons and armor you can upgrade.
when you take a pattern and try to automate the upgrade process it is unable to fine the item to upgrade.

#### What happens:
Bow is not being detected from automated crafting

#### What you expected to happen:
Bow being detected from automated crafting and allowing to craft the item

#### Steps to reproduce:
1.  create a crafting pattern for the Draconic Evolution bow or another weapon or armor 
2.  try to craft the item in the system
3. supply the items necessary to craft the recipe
4.  crafting monitor says unable to find item(weapon/armor) that you want to upgrade even though the item is in the crafting system

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12.2
- Forge: 1.12.2-forge1,12,2-14.23.5.2847
- Refined Storage: 1.6.15

Does this issue occur on a server? [yes/no]
YES

**Comment by raoulvdberge** [comment]
Duplicate. RS doesn't hande reusable items.
