### ISSUE TITLE
1.15.2 Bad pattern for Autocrafting 

### ISSUE THREAD

**Issue by Ibirtem** [raoulvdberge/refinedstorage#2499]
It looks like this problem has returned:
https://github.com/raoulvdberge/refinedstorage/issues/1937

Same issue with Pattern slots in Chemical Combiner.

Forge: 31.1.63
Refined: 1.8.3

How it need be:
![image](https://user-images.githubusercontent.com/54157950/80665389-0adfde00-8aa2-11ea-81ee-8486c3763f64.png)

How they drop items in slots:
![image](https://user-images.githubusercontent.com/54157950/80665367-f69be100-8aa1-11ea-83b9-6d4eeac78fde.png)

**Comment by raoulvdberge** [comment]
That problem hasn't "returned", the issue you're referencing is still open. That means it hasn't been fixed yet in the first place and now you're making duplicate issues.
