### ISSUE TITLE
0.8.15 No face on crafter. Correction, Face is on far side.

### ISSUE THREAD

**Issue by Whosur** [raoulvdberge/refinedstorage#250]
![2016-08-08_18 07 17](https://cloud.githubusercontent.com/assets/20894298/17501395/188335a6-5d93-11e6-8fbc-c1ad2b13f27e.png)

I am on FTB Unstable 4.2.X the newest update with your release of 0.8.15.

"Can not use crafter  for automating machines due to no face to indicate direction"
Correction, I could not see the face do to it being on the far side when placed, Did you change how the crafter is placed for a reason?
The pattern is recognized but once operation of process is started it finishes project with no results
works fine with existing crafters that have faces before update
this faceless crafter will process regular crafting functions

![2016-08-08_18 27 22](https://cloud.githubusercontent.com/assets/20894298/17501670/c9562a08-5d95-11e6-8c92-76d57c075837.png)
crafter placed on the right to show no face unlike pre placed crafters on the left
face is against wall where I was looking when I placed the crafter

**Comment by raoulvdberge** [comment]
this is already fixed in dev
