### ISSUE TITLE
[1.15.2] Optifine crash

### ISSUE THREAD

**Issue by ocram9** [raoulvdberge/refinedstorage#2504]
#### Issue description:
Optifine 1.15.2 for forge just released but the game crashes when loading a world. I looked at the crash report and saw Refined Storage was causing it (I'm not sure about this it could also be optifine but I decided to post an issue here first). I tested this on a server, not in singleplayer. Using OptiForge and optifine 1.15.2 pre-13 did work.

#### What happens:
The game crashes when loading a world.

#### Steps to reproduce:
1. Start Minecraft
2. Load a world with blocks from refined storage in ot (or place them down)..
3. Game crashes

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.15.2
- Forge: 31.1.63
- Refined Storage: 1.8.3
- Optifine pre-14

Does this issue occur on a server? [yes/no]
Yes

#### If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here]
https://gist.github.com/ocram9/9926451f8017a9bec68f29a13e46bf0e

**Comment by leetscooby** [comment]
Same issue, instant crash when placing a controller in the world.

**Comment by Watercrown123** [comment]
I can also confirm that it crashes upon loading my world that currently has 2x grids, 2x controllers, 2x disk drives, and 12 various drive items within it.

**Comment by ocram9** [comment]
Updating to 1.15.2 Optifine-pre15 fixes this issue.
