### ISSUE TITLE
[1.15.2] Crafting Monitor Crashing Server

### ISSUE THREAD

**Issue by Mig979** [raoulvdberge/refinedstorage#2508]
Sometimes when using a crafting monitor to see the current auto-crafting processes it will crash the server, didn't test on singleplayer. Seems to be easily reproduced by just opening the crafting monitor and hovering around the processes.

- Minecraft: 1.15.2
- Forge: 31.1.49
- Refined Storage: 1.8.3

https://pastebin.com/fLZ4xHxE

**Comment by Darkere** [comment]
Happens whe  you awach a new autocrafting being created in the crafting monitor while a secondary task updates.

Fixed in dev

**Comment by Mig979** [comment]
Thanks for the update, will be looking forward for the next version!

**Comment by raoulvdberge** [comment]
I'll try to do a release that contains this bugfix tonight.
