### ISSUE TITLE
1.15.2 server crashing on start up

### ISSUE THREAD

**Issue by SDUBZ** [raoulvdberge/refinedstorage#2509]
forge: 1.15.2-31.1.74
Rf: refinedstorage-1.8.3

#### Issue description:
loading it crashes during loading
#### What happens:
[com.raoulvdberge.refinedstorage.apiimpl.network.NetworkManager/]: Error while reading network
java.lang.StackOverflowError: null
#### What you expected to happen:
it to load like it did with a virtual server with testing
#### Steps to reproduce:
1. not sure how to reproduce

Does this issue occur on a server? [yes/no]
YES
#### If a (crash)log is relevant for this issue, link it here:
crash reports:
[crash-2020-04-30_16.48.04-client.txt](https://github.com/raoulvdberge/refinedstorage/files/4581189/crash-2020-04-30_16.48.04-client.txt)

logs:
[debug.log](https://github.com/raoulvdberge/refinedstorage/files/4581185/debug.log)
[latest.log](https://github.com/raoulvdberge/refinedstorage/files/4581188/latest.log)

**Comment by Darkere** [comment]
None of the logs you posted contain the error you were describing?

**Comment by SDUBZ** [comment]
sorry must not overwrote the past version here is the right ones sorry
[debug.log](https://github.com/raoulvdberge/refinedstorage/files/4582005/debug.log)
[latest.log](https://github.com/raoulvdberge/refinedstorage/files/4582008/latest.log)

**Comment by Darkere** [comment]
This launch happened with a rather large amount of mods removed. Not certain if that was the cause though. 

The crash appears when RS is reading the data of an item from the mod Tetra. The item just happens to be inside an RS network. Report to Tetra.
