### ISSUE TITLE
[0.8.15] Storage Drawer Quantities not updating properly on Void Drawers

### ISSUE THREAD

**Issue by oitsjustjose** [raoulvdberge/refinedstorage#251]
[Footage of the bug](http://puu.sh/qv15Y/69262412bd.mp4)

Best described by the video really. 

- Refined Storage 0.8.15

- Forge 12.18.1.2046

- Storage Drawers 3.2.1

My storage network doesn't seem to be taking into account the quantities of items if they're going to a void drawer and being voided after a certain quantity

**Comment by raoulvdberge** [comment]
I know the cause of this but won't be able to fix it for the next release.

Luckily, this is no dupe bug. It just displays the wrong count. If it gets too annoying you can just break + replace the controller.

**Comment by oitsjustjose** [comment]
Right, or do what I did in the video :) an extra utilities user might even
be an automated way to fix this.

**Comment by raoulvdberge** [comment]
Love the look of your base btw :p

**Comment by NarigudoBR** [comment]
the user has to be in activate block, right?

**Comment by oitsjustjose** [comment]
I'm actually experiencing a bug with ExU2 Grid Power right now, so I couldn't even test unfortunately :(
