### ISSUE TITLE
Incorrect Autocrafting / Reusable Items, MC 1.15.2 / RS 1.8.3

### ISSUE THREAD

**Issue by MonsterActual** [raoulvdberge/refinedstorage#2510]
#### Issue description:
Items that should be marked as reusable/not consumed by Crafting are not calculating correctlyu

#### What happens:
Recipe that uses Lava Buckets tries to craft / asks for the total number of buckets it would need instead of reusing buckets. (Mystical Agriculture recipe for Lava Buckets is being used in this case, 4 Fire Essence + Bucket.)
![image](https://user-images.githubusercontent.com/64934524/81241097-5d0b8c80-8fd7-11ea-87c2-39c6216386b5.png)

Recipe that uses Master Infusion Crystals (Mystical Agriculture 3.0.3) tries to craft / asks for 1 Infusion Crystal per craft instead of reusing the crystal.
![image](https://user-images.githubusercontent.com/64934524/81240119-837bf880-8fd4-11ea-9c4f-92cac804d7bb.png)

#### What you expected to happen:
Recipes that use Lava Buckets would reuse buckets based on the available quantity of buckets.

Recipes that use Master Infusion Crystals would recognize the Master Infusion Crystal is reusable.\

#### Steps to reproduce:
1. Instruct RS Network to craft something that uses many of the above items (more than you have stored of buckets / infusion crystals)

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.15.2
- Forge: 31.1.63
- Refined Storage: 1.8.3

Does this issue occur on a server?
Yes

**Comment by Darkere** [comment]
It's on the TODO list.

**Comment by Mochnant** [comment]
+1 to this improvement.

**Comment by jkieberking** [comment]
this is also bugged on Refined Storage 1.9.12
