### ISSUE TITLE
Refined Storage Crafters caching with interfaced machines results in some machines being unable to be used directly

### ISSUE THREAD

**Issue by utoc** [raoulvdberge/refinedstorage#2513]
#### Issue description:
The crafter will not insert into Pneumaticcraft's Inlet of the Pressure Chamber when using the multiblock to autocraft.

#### What happens:
The crafter is caching what is and is not allowed to be inserted into the inlet.  The inlet has two states: one allowing items and one not allowing items and it flips back and forth depending on if the inlet is open to the world or open to the inside of the chamber.  

#### What you expected to happen:
The crafter should accept the items as the inlet allows them to be inserted

#### Steps to reproduce:
1. Build Pressure Chamber with an autocrafting recipe for a turbine blade.  Make a crafter point at the inlet.  Pattern in the crafter for the blade.  
2. Request the turbine blade
3. Check the crafting monitor, the red exclamation reads "Machine doesn't accept item"

My current workaround is a crafter->chest->hopper->inlet. 

#### Version (make sure you are on the latest version before reporting):
- Minecraft:1.15.2
- Forge:31.1.74
- Refined Storage:1.8.3

Does this issue occur on a server? [yes/no]
Yes and this has also been tested in SSP with the same results.

This was first sent to Pneumaticcraft and was suggested to post here:  https://github.com/TeamPneumatic/pnc-repressurized/issues/467

The mod author says:

> I think my RS theory was correct: 
> https://github.com/raoulvdberge/refinedstorage/blob/mc1.15/src/main/java/com/raoulvdberge/refinedstorage/apiimpl/autocrafting/task/v6/CraftingTask.java#L781

> You could ask Raoul about this and see if he has any ideas, but I think he could also validly argue that RS isn't doing anything wrong; it's reasonable to mark an inventory as "faulty" if it doesn't accept the items it's supposed to. It just doesn't account for the fact that the pressure chamber interface isn't always open :)

Pics here: https://user-images.githubusercontent.com/11995956/81295538-2fa1fb80-9036-11ea-8110-81564a4bce5c.png
https://user-images.githubusercontent.com/11995956/81295540-303a9200-9036-11ea-9f43-602122917162.png

**Comment by desht** [comment]
As Darkere pointed out in the other issue:
>However, RS only inserts if it can insert all items specified in the pattern at once. Not sure if the interface allows for that?

It doesn't, since it's a 1-slot inventory.  So a buffer (e.g. hopper) is the way to go here.  I think this can be considered a non-issue?

**Comment by utoc** [comment]
It is a non-issue.  Thanks again!
