### ISSUE TITLE
[1.15.2] Crash on world load

### ISSUE THREAD

**Issue by DuelMonster** [raoulvdberge/refinedstorage#2514]
#### Issue description:
Game crashes when loading a world intermittently.
Restarting the game and trying again will eventually let me in.

I'm guessing it's due to Optifine because it seems to be fine without it.

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.15.2
- Forge: 31.1.77
- Refined Storage: 1.8.3
- Optifine: HD_U_G1_pre16

Does this issue occur on a server? [untested]

#### If a (crash)log is relevant for this issue, link it here:

https://gist.github.com/DuelMonster/91ca0f4be221762c7ac3c8e3ece8eb16

**Comment by Darkere** [comment]
I would wager this is caused by optifine. There haven't been any reports of this before.

**Comment by raoulvdberge** [comment]
Please report this to Optifine
