### ISSUE TITLE
0.8.16 - non-instantaneous item crafting

### ISSUE THREAD

**Issue by c0rn3j** [raoulvdberge/refinedstorage#252]
Server forge 2046, client 2049.

When crafting a stack of something(by hand) the storage first buffers up and then gives me the item (for example 64x lapis lazuli block). I do not see this change mentioned in the change log, is this by design?

**Comment by raoulvdberge** [comment]
I have no idea what you are talking about

What do you mean with "buffers up"?

**Comment by c0rn3j** [comment]
Actually just got an error and got kicked out of a server because I crafted about 20 stacks of ingots, I clicked the error away in the client, only recall something about broken pipes, but here's a server log...

> Aug 09, 2016 7:20:30 PM io.netty.channel.AbstractChannelHandlerContext invokeExceptionCaught
WARNING: An exception was thrown by a user handler's exceptionCaught() method while handling the following exception:
io.netty.handler.timeout.ReadTimeoutException

**Comment by c0rn3j** [comment]
>What do you mean with "buffers up"?
I'll get you a youtube video in a minute.

**Comment by raoulvdberge** [comment]
I can do nothing with the error you just posted, its incomplete

**Comment by c0rn3j** [comment]
https://www.youtube.com/watch?v=bJUnkZQRpts

I'd expect this to be instant, and it used to be instant.

**Comment by raoulvdberge** [comment]
Your server is having lag issues, whats the TPS?

**Comment by c0rn3j** [comment]
I can't find a way to check for the tickrate, any help?

**Comment by c0rn3j** [comment]
Stable 20 even when doing the exact same thing I did on the video. 
http://i.imgur.com/X4w23P5.png
Doesn't really seem to be a CPU issue.

> /forge tps
[19:38:35] [Server thread/INFO]: Dim 53 : Mean tick time: 0.029 ms. Mean TPS: 20.000
[19:38:35] [Server thread/INFO]: Dim 52 : Mean tick time: 0.004 ms. Mean TPS: 20.000
[19:38:35] [Server thread/INFO]: Dim 51 : Mean tick time: 0.004 ms. Mean TPS: 20.000
[19:38:35] [Server thread/INFO]: Dim 50 : Mean tick time: 0.003 ms. Mean TPS: 20.000
[19:38:35] [Server thread/INFO]: Dim -343800852 : Mean tick time: 0.004 ms. Mean TPS: 20.000
[19:38:35] [Server thread/INFO]: Dim -1 : Mean tick time: 0.820 ms. Mean TPS: 20.000
[19:38:35] [Server thread/INFO]: Dim 1 : Mean tick time: 0.006 ms. Mean TPS: 20.000
[19:38:35] [Server thread/INFO]: Dim 0 : Mean tick time: 4.944 ms. Mean TPS: 20.000
[19:38:35] [Server thread/INFO]: Overall : Mean tick time: 6.836 ms. Mean TPS: 20.000

**Comment by raoulvdberge** [comment]
@c0rn3j Think I got this one fixed. Can you try out this debug build (rename .zip to .jar):
[refinedstorage-0.8.17-debug.zip](https://github.com/raoulvdberge/refinedstorage/files/409634/refinedstorage-0.8.17-debug.zip)

**Comment by Moustik2002** [comment]
i'm encountering the same lag issue on my server, I'm gonna try your fix

**Comment by Moustik2002** [comment]
i confirm it is fix with this update :)

**Comment by raoulvdberge** [comment]
Okay, I'll release this fix later tonight ;)

**Comment by raoulvdberge** [comment]
0.8.17 is out!
