### ISSUE TITLE
Storage "fake" dupe

### ISSUE THREAD

**Issue by WisterOnline** [raoulvdberge/refinedstorage#2522]
#### Issue description:
When I try to take my 67 redstone, it take only 17 and the 50 other can't be taken, that's the same with some other items
#### Steps to reproduce:
1.
2.
3.
...

#### Version (make sure you are on the latest version before reporting):

- Minecraft:1.12.2
- Forge:14.23.5.2846
- Refined Storage:1.6.15

Does this issue occur on a server? [yes/no]
Yes
#### If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here]
https://youtu.be/x6rwn5mjyOE

**Comment by raoulvdberge** [comment]
there are no reproduction steps.

**Comment by Darkere** [comment]
Start by figuring out where these items are coming from. Most likely some external storage?

**Comment by WisterOnline** [comment]
I didn't fill reproduction steps because I wasn't knowing why that was happening, but i figure that my disk drive was all the same (maybe a bad movement) so know it's repair
