### ISSUE TITLE
[Suggestion] Ignore NBT switch for patterns

### ISSUE THREAD

**Issue by TheK0tYaRa** [raoulvdberge/refinedstorage#2526]
How about that? It solves a lot of issues with recipes that have charge-able items or similar.
Switch could be placed in the Pattern Grid with two others.

**Comment by Darkere** [comment]
Duplicate of #565

This is unfortunately not as easy as it sounds. Mainly because NBT is a lot more than just metadata about an item. 2 items with different NBT values could have completely different uses.
