### ISSUE TITLE
external storage not cooperating with storage drawers drawer controller

### ISSUE THREAD

**Issue by DarkxAnger** [raoulvdberge/refinedstorage#2527]
#### Issue description:
useing storage drawers controller via the external storage but the storage shows as over full
#### What happens:
no items will go into the drawers due to the storage showing over 100% full even though there is only one or a few of each item per drawer
#### What you expected to happen:
expected to use storage drawers to accept the items assigned
#### Steps to reproduce:
1. build a basic rs system with priority 0
2.build a drawer system and set a few items (controller with some drawers)
3. put a external storage system with a negative priority
...

#### Version (make sure you are on the latest version before reporting):
playing the FTB omnia 1.4.0 pack
- Minecraft: 1.15.2
- Forge: 31.1.87
- Refined Storage: 1.8.3
- storage drawers 1.15.2-7.0.2

Does this issue occur on a server? yes

#### If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here]
![2020-05-18_23 25 30 storage drawer bug](https://user-images.githubusercontent.com/42459123/82289819-977c0e80-9973-11ea-968d-9dbb29cf9d9a.png)

**Comment by Darkere** [comment]
Higher Priority get inserted first. 

Also, the numbers there are purely visual. They have no impact on whether items may be inserted.

**Comment by DarkxAnger** [comment]
Did I mix up mods. Does the priority number in rs have to be higher in value or lower? Cuz I set my external storage to -10 and the main storage to 0

**Comment by Darkere** [comment]
Higher priority storage get considered first.  So you want +10 not -10.
