### ISSUE TITLE
[0.8.17]crash when right cliking an covered cable with a wrench [C&B]

### ISSUE THREAD

**Issue by Tsukiumy** [raoulvdberge/refinedstorage#253]
refined storage 0.8.17
forge 12.18.1.2049
the crashlog
http://pastebin.com/cc8xsnpB

more as a alert than a bugreport, but you cant change the orientation of the cover after placed. that/\ will happen, i almost reported incorrectly because i forgot that i was with the wrench in the offhand(because morphing tool) as i was making the cover.

**Comment by raoulvdberge** [comment]
This is a C&B issue, please report it on their issue tracker
