### ISSUE TITLE
No Multipart Colision

### ISSUE THREAD

**Issue by darknife25** [raoulvdberge/refinedstorage#255]
When a cable is used with chisel and bits, the bits can be placed right through the cable. the cable does not collide with them. 

This is most noticeable, when placing bits in connected plane, most cables ie. Mekanism the plane will go round the cable. but with refined storage it goes through the cable as if the cable did not exist .

if a complete block is made of the bits, with the cable through it, it will reform into the original block. as if the cable was not there.

MC 1.10.2
Refined storage 0.8.17
chisel and bits 11.9
MC multipart 1.2.1
Forge 12.18.1.2046

**Comment by Utildayael** [comment]
I've had the same issue but if I accidently put a bit through the cable, the cable breaks.

**Comment by ilordnightmarei** [comment]
for me a full chisl and bits block makes it become a cover witch i consider a feature more than a bug and thing still has the cable in it for me so i think its awesome but ya  never had them break tho cause of it

**Comment by aionys** [comment]
I'd like cables to be treated as filled bits by Chisels & Bits, actually. There's some noticeable texture conflict when they overlap that I find mildly annoying.

**Comment by raoulvdberge** [comment]
This bug is irrelevant now that MCMP2 is coming out soon.
