### ISSUE TITLE
[Bug] Redstone condition with detector

### ISSUE THREAD

**Issue by Moustik2002** [raoulvdberge/refinedstorage#256]
Hello,

It happens with the new detectors i place on my world. When i choose to set condition to emit when it is above the amount, when i get back to detector, it comes back to default status (emit when the amount).

**Comment by raoulvdberge** [comment]
this is already fixed

**Comment by Moustik2002** [comment]
i'm on v17 you mean it will be resolved on the version 18?

**Comment by raoulvdberge** [comment]
yes, this will be fixed in 18
