### ISSUE TITLE
Item dupe with external storage on alloy smelter

### ISSUE THREAD

**Issue by Fey142** [raoulvdberge/refinedstorage#258]
I have a setup where I constantly export the materials for energetic alloy (glowstone, redstone, gold) and have an external storage thing connected to it so I always have a stack handy. When I try pulling the items out from the grid (the ingots inside the alloy smeltry) it gives me a stack and goes into negative inside the grid. If I close it and reopen I have the ingots inside again like I never pulled anything out. Furthermore I can continue pulling out even when the grid shows negative amount of items this way.

**Comment by raoulvdberge** [comment]
This isn't a dupe, but just a bug when displaying the itemcount. Am I correct?

**Comment by Fey142** [comment]
nope it actually makes the items.

**Comment by Fey142** [comment]
I tried reproducing it in a flat test world but I couldn't. I'm 100% sure It did dupe in my active world because after puting the ingots back in I had 1,2k available xD - I'll report if I find a reason why it's happening.

**Comment by raoulvdberge** [comment]
I think you were able to retrieve the items because they were technically still there, but just displaying a negative count. The stuff you see in the grid is merely a cached version of your storage for display. When you pull or push it gets it from the real storage.

**Comment by Fey142** [comment]
ok so... best I could do are screenshots - 1) here you can see the inventory of the alloy smelter (64) http://prnt.sc/c4g4t6, I can pull them out continously (http://prnt.sc/c4g56z) to no limit (pulled out 2 iron chests owrth of ingots (http://prntscr.com/c4g6np). After the alloy smeltry makes a new ingot the "debt" in the system resets and shows I have 66 still available (http://prntscr.com/c4g7ta).

Furthermore, If I break the external storage the system says I have 0 (none), when I reapply it it again says I have 64 available (even though the alloy smeltry hasn't produced any yet) - ???

**Comment by Fey142** [comment]
So ye  you can easily reproduce it even in singleplayer - set up one alloy smeltry for vibrant alloy (export pearls and energetic alloy and an external storage connector on top - unlimited energetic alloy in system.

**Comment by raoulvdberge** [comment]
Can you try to reproduce this on a vanilla machine like a furnace?

**Comment by raoulvdberge** [comment]
Ah, think I got this reproduceable on a vanilla furnace (ext storage on output slot + export lava bucket that was in the output slot = infinite lava buckets)

**Comment by raoulvdberge** [comment]
@Fey142 Can you try this build and let me know if the issue is still there? (rename .zip to .jar)

[refinedstorage-0.8.19-debug.zip](https://github.com/raoulvdberge/refinedstorage/files/413837/refinedstorage-0.8.19-debug.zip)

**Comment by Fey142** [comment]
Ok so the version you provided semi-fixed it. The system still sees the energetic alloy in the input slot as it was in the output slot but I cannot pull it out from the grid anymore.

Additionally, the external storage thing now acts like an importer (only on vibrant alloy) into the system??, and the exporter no longer want to input energetic alloy into the alloy smeltry. Besides that It's also voiding some of the items that it think it exported. weird :O

**Comment by Fey142** [comment]
emm wtf is going on :O one of the external storages just started making energetic alloy on its own without a recipe or anything xD (not even an exporter attached)

**Comment by raoulvdberge** [comment]
> Ok so the version you provided semi-fixed it. The system still sees the energetic alloy in the input slot as it were in the output slot but I cannot pull it out from the grid anymore.

That is because EIO expose that slot to inventory readers. Not much that I can do about that.

> Additionally, the external storage thing now acts like an importer (only on vibrant alloy) sucking the smelted ingot into the system??

Are you absolutely sure about that? Did it take it out of the inventory? I have a hard time believing that.

> and the exporter no longer want to input energetic alloy into the alloy smeltry. 

Is the item available? And are you putting it in the right slot?

**Comment by Fey142** [comment]
It's weird because the slot is only "exposed" to be read when there is energetic alloy inside it, any other item does not appear (is not seen by the system).

Can I send you the save and you try it for yourself?
everything is acting really strange.

world save: https://www.dropbox.com/s/66s8ow21fe1u9yf/Test%20Flat%20world.zip?dl=0
mod folder: https://www.dropbox.com/s/v2gr5gtt027j5f0/mods.zip?dl=0
forge: latest - 2050

**Comment by raoulvdberge** [comment]
Nah, I can't repro this on my own test world and I don't feel like download all that, so, I'd appreciate it more if you'd answer my questions.

**Comment by Fey142** [comment]
I'm not sure what else to do, how are you trying to reproduce it? I'll try it with only ender io and refined storage then, if that's what you're doing and it's fine for you.

**Comment by raoulvdberge** [comment]
Sure

What I did
- Ext storage on alloy smelter
- Exporter

I can indeed see the ingredients (not able to take them out, which I clarified earlier), and can take the stuff from the output slot out. But I cannot insert the stuff back in (which makes sense since the ext storage is connected to the output slot)

**Comment by Fey142** [comment]
Ok so:
 1) http://prntscr.com/c4jcng
The vibrant alloy that is made is still magically getting imported - second alloy smelter.

2) Everything else seems to be behaing ok-ish for now, gonna do more testing later, but it looks like another mod was causing the rest of the problems.

**Comment by raoulvdberge** [comment]
What machine is behind those alloy smelters? An importer, or an exporter?

**Comment by Fey142** [comment]
Both machines have an exporter behind them.
