### ISSUE TITLE
Ore dictionary problem

### ISSUE THREAD

**Issue by Frontrider** [raoulvdberge/refinedstorage#259]
The silicon in this mod is registered in the same way as the ender io silicon, but I can't use it in the solderer.

**Comment by Frontrider** [comment]
checking again when I can.

**Comment by raoulvdberge** [comment]
you can use it in the solderer, JEI doesn't show it though

**Comment by Frontrider** [comment]
Yeah, right after I hit post, I was thinking that I might have powered it wrong (don't say a word, i'll figure it out). Should stop being used to the "plug it in, works" systems from 1.7.

**Comment by raoulvdberge** [comment]
(wiki)
