### ISSUE TITLE
Console Spam

### ISSUE THREAD

**Issue by Redlotus99** [raoulvdberge/refinedstorage#260]
I am unsure if this is IC2 or Refined Storage, but I am getting a lot of console spam.

http://pastebin.com/RzLpdd2m

If you need more information please let me know.

**Comment by raoulvdberge** [comment]
On which version are you?

**Comment by raoulvdberge** [comment]
(RS version)

**Comment by Redlotus99** [comment]
0.8.18

**Comment by Redlotus99** [comment]
Just to give a little more information.

This is occurring with:

Forge: 2065
Refined Storage:  0.8.19
Minecraft: 1.10.2

I may troubleshoot this some with a new world to see if it still occurs.

**Comment by raoulvdberge** [comment]
Does this still occur on the latest IC2 / RS?

**Comment by raoulvdberge** [comment]
I'm assuming this is fixed?
