### ISSUE TITLE
[Issue] Grid crashes client

### ISSUE THREAD

**Issue by Moustik2002** [raoulvdberge/refinedstorage#261]
Hi Raoul, here is the crash log : http://pastebin.com/HtYftBz3

**Comment by Fey142** [comment]
http://pastebin.com/KenSmruq

Same issue

**Comment by raoulvdberge** [comment]
It only occurs really rarely, right?

**Comment by Fey142** [comment]
Like every 15-30 minutes depends on how many times I open the grid

**Comment by BootyToast** [comment]
Getting this crash as well, my dude. http://pastebin.com/8NaaFaNi

**Comment by raoulvdberge** [comment]
I'm really busy with the fluid storage update (tm), but I'll see if I can squeeze an update in tomorrow!

**Comment by BootyToast** [comment]
It does only happen every once and a while so don't stress. Thanks!

**Comment by raoulvdberge** [comment]
This should be fixed now! I'll be releasing 0.8.19 in a few minutes

**Comment by raoulvdberge** [comment]
0.8.19 is out!
