### ISSUE TITLE
Grid crash

### ISSUE THREAD

**Issue by Fey142** [raoulvdberge/refinedstorage#266]
I'm sorry to inform you but the 0.8.19 did not fix the issue - http://pastebin.com/PSQfy1NU

Reference https://github.com/raoulvdberge/refinedstorage/issues/261

**Comment by raoulvdberge** [comment]
![x](https://media1.giphy.com/media/l41lK5NQjKm0uqPDO/200_s.gif)

**Comment by Fey142** [comment]
Gotta mention that it does happen A LOT less frequently - only happened once whole day., so you did fix something! :D
