### ISSUE TITLE
Not reading Quantum Storage inventory

### ISSUE THREAD

**Issue by CommYutzy** [raoulvdberge/refinedstorage#267]
I have tried placing the external storage on the side, top, and bottom of a quantum storage unit. It works fine for placing the item into the unit, but it then disappears from the grid and won't read what is in the storage unit.

Refined Storage 0.8.19
Quantum Storage 3.1.2
Forge 2048

**Comment by JohnC94** [comment]
Do you have more than a stack in the QSU? You need more than 1 stack for the RS system to see anything in the QSU.

**Comment by CommYutzy** [comment]
Ahh that did it. Still a little buggy, it won't let you pull the last stack out using the grid. Also noticing at times it'll still register the last stack that was in the Quantum Storage even if you pull it out of the unit itself. Occasionally even stacking if you repeat (i.e. shows 128 in grid when there isn't any).

**Comment by raoulvdberge** [comment]
Can't reproduce and the fact that a stack remains is normal behavior
