### ISSUE TITLE
Priority Settings Reset with Re-logging

### ISSUE THREAD

**Issue by jondan1986** [raoulvdberge/refinedstorage#270]
Every time I set a priority setting on an external storage module it resets back to 0 whenever I re-log, thus causing my items to store in the disk drives before my storage drawers.

**Comment by raoulvdberge** [comment]
version number please

**Comment by jondan1986** [comment]
0.8.15
I'm running FTB Unstable 1.10

**Comment by jondan1986** [comment]
Updating worked. FTB needs to update their pack I guess
