### ISSUE TITLE
Detector only allows double digit number for level

### ISSUE THREAD

**Issue by Winrylive** [raoulvdberge/refinedstorage#272]
#### Issue description:

Detector only allows double digit number for level

#### What happens:

If you add a 3 digit number it truncates the 1st digit when reopening the gui

#### What you expected to happen:

I expected the detector to accept more than a 2 digit number

#### Steps to reproduce:
1. Open detector gui
2. Type in 3 digit number
3. Close and reopen
...

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge: 12.18.1.2053
- Refined Storage: 0.8.19

#### If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here]

**Comment by raoulvdberge** [comment]
It accepts 3 digits, it only displays 2. If you click the input textfield and move your cursor, you'll see your input is still there. But I'm sure I can make the inputfield a bit bigger.
