### ISSUE TITLE
[Request] Hold Crafting Materials Until Ready

### ISSUE THREAD

**Issue by thejereman13** [raoulvdberge/refinedstorage#273]
Currently, when autocrafting an item, the system will gather the materials for whatever requested and send them on their way to whatever machine is set up, and then if it needs to craft one of those materials, it will add that craft job to the queue. This causes issues with machines with multiple inputs (specifically the Metallurgic Infuser, but I'd imagine this is the same for the solderer) that are used for both of the crafting jobs, as the system will send one of the materials to the machine, but then won't be able to craft the other item it needs now that something is already there.
I suppose the easiest solution would be to just hold the materials until all of them are accounted for before sending them to a machine, although changing the algorithm to start from the bottom of the crafting tree would also work.

**Comment by raoulvdberge** [comment]
This is done for 1.0!
