### ISSUE TITLE
Crash when looking at "grid" item

### ISSUE THREAD

**Issue by Zettt** [raoulvdberge/refinedstorage#274]
#### Issue description:
When items that show the grid of items, the client crashes.

#### What you expected to happen:
It not to crash.

#### Steps to reproduce:
1. Click on Grid, or open remote grid.

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge: 2065
- Refined Storage: 0.8.19

#### If a (crash)log is relevant for this issue, link it here:

http://pastebin.com/5bbLDh8Q

**Comment by raoulvdberge** [comment]
Already fixed in dev
