### ISSUE TITLE
Wireless transmitter (Wireless grid) not working in another dimension

### ISSUE THREAD

**Issue by Fey142** [raoulvdberge/refinedstorage#276]
#### Issue description:
I set up "new" transdimensional network. When I use the crafting gid (in another dimension) everything is fine, but the wireless transmitter that I also connected in that dimension has no effect (whan trying to open the gui (wireless grid) nothing happens - not even an error message like there is one in overworld (out of range or something).
#### What you expected to happen:
Open grid like in overworld.
#### Steps to reproduce:
1. Go to another dimension and connect the refined storage system with netword receiver/transmitter.
2. Add wireless transmitter.
3. Open wireless grid - nothing happens

setup: http://prntscr.com/c7ootz
...

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge: 12.18.1.2065
- Refined. Storage: 0.8.20

#### If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here]

**Comment by raoulvdberge** [comment]
There, fixed :)

![fixed](http://i.imgur.com/ORC3B3T.png)
