### ISSUE TITLE
Client gameRender lag with storage drawers + external storage

### ISSUE THREAD

**Issue by linuxdemon1** [raoulvdberge/refinedstorage#277]
Possibly same issue as #233 
According to the F3 debug chart, the render lag appears under root.gameRender.level.terrain_setup. After testing, determined the RS system was the source, specifically the external storage attached to the drawer system. While attempting to reproduce, I determined it occurs when my disk drive has a differing priority form the external storage, and an exporter is exporting items contained in the drawers

- Minecraft: 1.10.2
- Forge build 2066
- Refined Storage: 0.8.20
-Storage Drawers: 3.2.5

**Comment by RehabOholic** [comment]
Same here. I thought it was an item in my storage draws, but after removing 1 draw at a time my performance never got better. The only way is if I cut of the connection to the external storage and everything runs fine.

**Comment by raoulvdberge** [comment]
Send me a .nps profiling file so I can see where the bottleneck is, thanks.

**Comment by linuxdemon1** [comment]
[profile](https://drive.google.com/file/d/0B9A7bEFwW5EvQWwtTEZWOHpHUWs/view?usp=sharing)
sorry, took me a bit to get back, github didn't send a notification email :/

**Comment by McBossKiller** [comment]
This still happens on the latest version of this mod

**Comment by Alaberti** [comment]
I think what happened is OP managed to hit the performance threshold of what a binary sort can handle; you may want to use a more scalable algorithm.

**Comment by way2muchnoise** [comment]
And where would this binary sort be?

**Comment by raoulvdberge** [comment]
Looking at the nps file, it seems like Storage Drawers is triggering render updates, which would cause the client lag.

**Comment by raoulvdberge** [comment]
I can't reproduce this on the latest Storage Drawers & RS Beta versions...
