### ISSUE TITLE
[1.10.2] Cannot rotate Crafting Grid, Pattern Grid, Solderer or Crafting Monitor

### ISSUE THREAD

**Issue by shortybsd** [raoulvdberge/refinedstorage#280]
#### Issue description:
Cannot rotate Crafting Grid, Pattern Grid, Solderer or Crafting Monitor using Yeta wrench from EnderIO.
#### What happens:
Server console is spammed with errors.
#### What you expected to happen:
For it to rotate the block.
#### Steps to reproduce:
1. Place Pattern Grid or Crafting Grid and it will always face down.
2. Use any type of wrench on it to rotate the block.
3. Boom... error

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge: forge-1.10.2-12.18.1.2056-universal
- Refined Storage: refinedstorage-0.8.20

#### If a (crash)log is relevant for this issue, link it here:
http://pastebin.com/u3Zhtvia
[pastebin/gist/etc link here]

Do note that the wrench works on all of the other blocks for rotation, e.g. Disk Drive, Controller and Crafter. Placing down a machine, you have to look straight down for it to place correctly.

**Comment by raoulvdberge** [comment]
When I place a grid down it doesn't face down...
