### ISSUE TITLE
[Request] Storage Disk Partitioning? 

### ISSUE THREAD

**Issue by RehabOholic** [raoulvdberge/refinedstorage#281]
Would you be able to add the ability to partition a storage disks to whitelist items? Basically a chests worth of slots to add only what you what per disk? 

If not, It's still a great mod. Thanks for the hard work you have put in.

**Comment by raoulvdberge** [comment]
no, there is a whitelist / blacklist option. just configure it before you use the storage

**Comment by RehabOholic** [comment]
Thanks for your time, and sorry for the dumb request. It really is a great mod.

**Comment by raoulvdberge** [comment]
It isn't a dumb request, and I'm glad you enjoy it  :-)
