### ISSUE TITLE
Refined storage on 1.10.2 crashing when Controller loads

### ISSUE THREAD

**Issue by azurewyvern** [raoulvdberge/refinedstorage#285]
When a chunk loads with a controller the game fatally crashes.  Updated to most recent version yesterday, also most recent version of forge (.73) in an attempt to resolve the issues.  We are also having issues where various parts (most notably controller and grid) will randomly not render when a chunk loads if it doesn't crash the server, it still functions however and if you place a new one and break it you get both back.

- Minecraft: 1.10.2
- Forge:  .73
- Refined Storage: 0.8.20

http://pastebin.com/f2t1m6ZW

**Comment by raoulvdberge** [comment]
Are you using network transmitters / receivers?

**Comment by raoulvdberge** [comment]
Also, did you remove a dimension recently?

**Comment by azurewyvern** [comment]
Yes I am using transmitters and recievers and yes I did remove a dimension recently, however the dimensions removed had nothing in them.

**Comment by raoulvdberge** [comment]
Aha! There is the problem :P

**Comment by raoulvdberge** [comment]
Are you able to re-add the dimension until I release the next update?

**Comment by azurewyvern** [comment]
Possibly, I can see if a backup has copies that can be readded.  If RFTools accepts the backups it would be fine, otherwise I can see if the person who created them knows which dimlets were used.

**Comment by azurewyvern** [comment]
Was the issue an old network link to a different dimension which no longer exists?  If this is the case I believe only one ever had a link to it and it should be an easy one to restore.  If it is just passingly related to an old dimension then it may be more problematic.  (Let me know as if its the first I can easilly restore that one)

**Comment by raoulvdberge** [comment]
What you could also do is remove the problematic Wireless Transmitter (the one that holds the Network Card to the missing dimension) in MCEdit

**Comment by raoulvdberge** [comment]
@azurewyvern this is fixed for 0.9

If you aren't able to get the transmitter away with MCEdit, I can still release 0.8.21 if you want that.

**Comment by azurewyvern** [comment]
@raoulvdberge Yeah having issues getting a backup to load in a state that the dimension is active and so it keeps crashing.  (All the dimlets to remake the dimension) are stored in the storage system which is causing the issue).  If you can release 0.8.21 it would be appreciated.

**Comment by raoulvdberge** [comment]
@azurewyvern 0.9.1 is out, that version should fix it ;)
