### ISSUE TITLE
RS not recognizing storages, exporters, importers over long distances

### ISSUE THREAD

**Issue by Zettt** [raoulvdberge/refinedstorage#287]
#### Issue description:
RS doesn't "see" its devices anymore over long distances. Distances are about 20-40 cables apart from the last RS machines exit point. 

I tried the new transmitter and receiver blocks, but they didn't change the overall behavior.

Oddly enough, placing another grid right to affected blocks, makes the devices become online but the grid then doesn't see the items from the main storage. It appears like those two systems are disconnected. And before you ask, yes I have double-checked to see if the two systems are actually connected.

#### What happens:
Affected devices (external storage, importer, exporter) don't work anymore. External storage doesn't recognize the blocks in front of it, exporters don't export anymore. It's almost as though these devices are unpowered.

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge: 2073
- Refined Storage: 0.8.20

**Comment by raoulvdberge** [comment]
Is your controller chunkloaded? Controller has to remain loaded to see new machines.

**Comment by Zettt** [comment]
Yes, it is. As written in the above statement. The other machine is only 20 cable pieces away. Som barely crossing a chunk or two.

**Comment by choekstr** [comment]
Still using 0.8.15 (FTB Unstable stock) I just ran a 50 cable run to my compacting drawers with an external storage and all works correctly and I can see all the items properly.  The run spans 3 chunks but they are all chunkloaded.

**Comment by Zettt** [comment]
As mentioned, it is not the length of the cables, nor is it affected by chunkloaded chunks. I have chunkloaded them but they still go offline after, say, half an hour or so. They do work for a brief period of time.

**Comment by raoulvdberge** [comment]
I've been able to repro this issue and it's very weird. I'll need some time to find what causes this.

**Comment by raoulvdberge** [comment]
@Zettt Please try out this build and let me know if it works better now (rename .zip to .jar as GH doesn't allow .jar uploads):

[refinedstorage-0.9.3-debug.zip](https://github.com/raoulvdberge/refinedstorage/files/439387/refinedstorage-0.9.3-debug.zip)

**Comment by raoulvdberge** [comment]
@Zettt Actually, try this one:

[refinedstorage-0.9.3-debug2.zip](https://github.com/raoulvdberge/refinedstorage/files/439472/refinedstorage-0.9.3-debug2.zip)

**Comment by raoulvdberge** [comment]
Please try 0.9.3 and let me know if it works

**Comment by raoulvdberge** [comment]
I had to revert the "fixed" I did in 0.9.3 because they were buggy. I have to find a better solution.

**Comment by Zettt** [comment]
Thanks for looking into this. Glad you were able to reproduce the issue. Can you tell me why this happens and a possible intermedia workaround?

I wasn't able to check out your temporary fixes because I'm out and about at the moment.

**Comment by raoulvdberge** [comment]
1) Controller builds a network graph, finds a grid very far away in a unloaded chunk and puts the tile entity in its graph
2) You go to that grid, but because the chunk was unloaded it loads a new grid in.
3) The grid in the controller graph list is now mismatching with the real grid in the world

**Comment by Winrylive** [comment]
So @raoulvdberge would a temp workaround until our server updates (because I have the same problem) be to break and replace the controller? Would it force it to build a new network graph?

**Comment by raoulvdberge** [comment]
Yes you can also cause a block update next to the controller and it will also do it

**Comment by raoulvdberge** [comment]
Should be fixed by 809baddd88535309a76be2214b2082a8ec5b5755
