### ISSUE TITLE
Compacting drawer from Storage Drawers

### ISSUE THREAD

**Issue by DirkSch** [raoulvdberge/refinedstorage#288]
#### Steps to reproduce:
1. connect a compacting drawer over a drawer controlen with a external storage.
2. put by example emerald, diamands or lapiz in the compact drawer. you kann only see the blocks in the top slot from the compacting drawer.
with extra utilities 2 are also compresed cobble, compresed gravel and compresed dirt not to see in the network
3. if is a ingot can you see the ingot, the nugget and the block.
...

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge: 12.18.1.2072
- Refined Storage: 0.8.20
- Storage Drawer:  1.10.2 - 3.2.6

#### If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here]

**Comment by ThexXTURBOXx** [comment]
It's happening for me, too, but I don't think it's a bug, because in my eyes it's a nice feature to take only the item, which you want. If you want a nugget, take a nugget. If you want an ingot, take an ingot.
I wouldn't fix this, because I personally like this ^^

**Comment by raoulvdberge** [comment]
Also, this is something I can't really do anything about, as the things you see in a grid are the things that the Storage Drawer API gives me back.

**Comment by ThexXTURBOXx** [comment]
That's right, and there is no "bug", because:
If you take an nugget, it will count it as a 1/9 Block and the item gets removed in the barrel as well, so everything works alright.

**Comment by DirkSch** [comment]
every compacting drawers must have a own external storage than its work, but not over the drawer controler. for 10 compacting drawer must have 10 external storage. 
on AE must have a drawer controler an 1 external storage. not on refined storage.

**Comment by raoulvdberge** [comment]
I have no idea what you mean.

**Comment by raoulvdberge** [comment]
You can just hook up a external storage on a drawer controller, what is the problem?

**Comment by DirkSch** [comment]
a little picture what I mean
https://pl.vc/17r3h2
in the waila interface see you what is in the compacting drawer. it's a example. any items works like coal, other items are not working like compressed cobble stone or lapiz 
you can also see the configuration of the simplest network.

**Comment by raoulvdberge** [comment]
Don't think this is an RS issue, like I said, you see what the API gives me

**Comment by ThexXTURBOXx** [comment]
Well, we could at least take a look at this: [Waila Integration Code for Storage Drawers](https://github.com/jaquadro/StorageDrawers/blob/1cfcecf3a57ff079cfb2e72a377c9d307d79df4e/src/com/jaquadro/minecraft/storagedrawers/integration/Waila.java)

**Comment by JCMais** [comment]
Can this bug be revisited? It makes impossible to use Compacting Drawers with RS. The iteration between them is really non-intuitive.
