### ISSUE TITLE
Importers not working when changing facing with a wrench

### ISSUE THREAD

**Issue by krelios** [raoulvdberge/refinedstorage#29]
I have an importer connected to a Creative Controller (it shows up in the GUI, so I know it's working correctly); however, it will not pull items from a chest placed next to it's input face.

**Comment by raoulvdberge** [comment]
Did you connect a storage device like a storage block or drive with a disk in?

**Comment by krelios** [comment]
Yes, a drive with disks. I had a functioning network and could add or remove items through the crafting grid.

**Comment by raoulvdberge** [comment]
Do they work again when you break and replace them? If not, can you share a screenshot of your setup?

**Comment by krelios** [comment]
http://imgur.com/a/r5y5Z

**Comment by raoulvdberge** [comment]
Thanks, will try to reproduce this.

**Comment by raoulvdberge** [comment]
Does it work with a normal chest (so not an iron one)?

**Comment by krelios** [comment]
I've tried with regular, trapped, and iron. None of them are working for me.

**Comment by raoulvdberge** [comment]
I'm unable to reproduce this. Are you sure that:
- there is still space in your system (check the disk drive GUI)
- you are on the latest version

**Comment by krelios** [comment]
Yes to both, I added 8 16k storage and I've only filled a handful of slots and I'm running 0.5.5.

My best guess at this point is a mod conflict so I'll try to do some more testing.

**Comment by raoulvdberge** [comment]
This is my setup used in testing:

![setup](http://i.imgur.com/R4rfJUE.png)

**Comment by krelios** [comment]
Ah ha! It works if I place the importer face up but if I place it facing horizontally and then use the wrench to change the input to face up it doesn't!

**Comment by raoulvdberge** [comment]
There we go :) I'll investigate this.

**Comment by raoulvdberge** [comment]
From what mod is the wrench you were using?
