### ISSUE TITLE
[Bug] Can´t pull out items from the Wireless Grid

### ISSUE THREAD

**Issue by Greg9711** [raoulvdberge/refinedstorage#292]
After a couple of minutes in another Dimension i couldn´t pull out items from my Wireless Grid (The controller is in the overworld and its loaded), but a normal crafting Grid works.
I havent tested it in the newest version 0.91 because it says nothing about that in the changelog.

- Minecraft: 1.10.2
- Forge: Don´t know
- Refined Storage: refinedstorage-0.9

**Comment by raoulvdberge** [comment]
the issue template states clearly to always try the latest version, no matter what. and guess what, it's fixed in 0.9.1.

**Comment by raoulvdberge** [comment]
0.9.2 on Curse (as soon as it's accepted) should fix this issue

**Comment by Greg9711** [comment]
Thanks :)
