### ISSUE TITLE
Can't put 512k Fluid storage disk into the disk drive

### ISSUE THREAD

**Issue by Fey142** [raoulvdberge/refinedstorage#298]
#### Issue description:
The disk drive won't accept the disk (unable to be placed inside) - only happens with the 512k!
#### What you expected to happen:
Put the disk inside
#### Steps to reproduce:
1.
2.
3.
...

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge: 2073
- Refined Storage: 0.9.2

Does this issue occur on a server? [yes/no]
yes
#### If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here]

**Comment by 0blu** [comment]
Can't confirm.
1. Maybe you put a "512k Fluid Storage Part" in it?
2. Did you craft the Fluid Storage Disk or did you cheat it by using the creative mode?

**Comment by Fey142** [comment]
I crafted it and the disk - http://prntscr.com/cartpe

**Comment by 0blu** [comment]
3) could you try to restart the server?
4) can you execute "/blockdata ~ ~-1 ~ {}" while standing on the Disk drive -> Send output
5) can you cheat a 512k Fluid Storage Disk an put it in?

**Comment by Fey142** [comment]
Second, I'll try all of them.

**Comment by Fey142** [comment]
3) restarting fixed nothing
4)The data tag did not change: {Redstone mode:0,Priority:0,Mode:0,Direction:4,Type:0,Inventory_0:[0:Slot:0,id:"refinedstorage:fluid_storage_disk",Count:1b,tag:{Fluids:[],Stored:0,Protocol:1},Damage:2s}],Inventory__1:[],Invenotory_2[],x:2029,y:58,z:319,Compare:0,id:"refinedstorage:disk_drive"}
5)Cheating it in and placing it inside worked. (Donno if it is relevant but the ones that are broken were autocrafted by the refined storage autocrafters

**Comment by 0blu** [comment]
5: This could be the reason :(
Just to make it sure,
can you put an auto crafted disk into a empty chest and execute
``/blockdata ~ ~-1 ~ {}``
again (while standing on the chest)
The chest may only contain the disk

PS: you can screenshot the output
Example: http://i.imgur.com/GiYWYVF.png

**Comment by raoulvdberge** [comment]
Does the fluid disk you are trying to insert have a "stored: x / x" tooltip?

**Comment by Fey142** [comment]
I does not, the one that I cheat in does.

**Comment by Fey142** [comment]
Here's the chest output you requested https://scontent-vie1-1.xx.fbcdn.net/v/t35.0-12/14054469_10209078105981391_782880213136777989_o.jpg?oh=d2b9a3b17639863cacc6a814ef993ff6&oe=57C37911

**Comment by raoulvdberge** [comment]
The crafting recipe gives back NBT tags for item storage disks, I just fixed this in dev

**Comment by raoulvdberge** [comment]
Fixed 3b76ae8dbac68749af66491a9ee40c6f560ec7f0
