### ISSUE TITLE
[Request] Leverage player inventory when shift clicking recipe

### ISSUE THREAD

**Issue by choekstr** [raoulvdberge/refinedstorage#299]
#### Issue description:
It would be really nice to have the RS Crafting Grid look in the players inventory as well as its own inventory when matching a recipe that is shift clicked.  

#### What happens:
If one has an item from a recipe only in inventory but not in the RS system the recipe fails to shift click into the crafting grid.

#### What you expected to happen:
Whether the items are in the RS system or in the player inventory the recipe should match and allow the item to be crafted.

#### Steps to reproduce:
1.  Put a vital component to a recipe ONLY in inventory.
2.  Look up recipe in JEI
3.  Shift-Click to put recipe in crafting grid
4.  Recipe fails if item is only in inventory and not in RS system first.

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge:  12.18.1.2046 (FTB Unstable)
- Refined Storage:  0.8.15

Does this issue occur on a server? [yes/no]
yes

#### If a (crash)log is relevant for this issue, link it here:
N/A

**Comment by 0blu** [comment]
Would take a look in https://github.com/raoulvdberge/refinedstorage/blob/33e4c4a38d527c9650b3c0cb11ff4e5debbd54a8/src/main/java/refinedstorage/tile/grid/TileGrid.java#L336
