### ISSUE TITLE
[0.9.3] External Storage not using priority

### ISSUE THREAD

**Issue by autumnfire** [raoulvdberge/refinedstorage#302]
#### Issue description:
External Storage doesn't seem to be using the priority I've set at all.

#### What happens:
I've tried the Drawer Controller from Storage Drawers, the Small Storage Crate from Actually Additions, and even a vanilla Chest. I'm able to read the contents of the storage just fine but no items will go back to these storage blocks even though the priority on the External Storage is set to 10 and my Disk Drive is set to 0. Did not used to have this problem in previous versions.

#### What you expected to happen:
Items should be routed to the correct storage based on priority.

#### Steps to reproduce:
1. Connect Disk Drive and External Storage linked to storage block on the network.
2. Set priority on External Storage higher than 0.
3. Put item in the linked storage block
4. Take item out through Grid then put it right back.
5. Check linked storage and item will NOT be there.

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge: 2073
- Refined Storage: 0.9.3

Running All the Mods modpack 1.17

Does this issue occur on a server? yes

#### If a (crash)log is relevant for this issue, link it here:

No crash log necessary.

**Comment by raoulvdberge** [comment]
Fixed for 0.9.4

**Comment by autumnfire** [comment]
Just tested 0.9.4. When I first connect to the server after starting the client it's the same behavior as before: items go straight to the drive. If I disconnect and reconnect, everything works properly. Is item routing being handled on the client instead of the server?

**Comment by raoulvdberge** [comment]
I can't repro this. If this is still an issue in the latest version, please let me know
