### ISSUE TITLE
[0.9.4] Interface exports wrong ores

### ISSUE THREAD

**Issue by FlyingBoat** [raoulvdberge/refinedstorage#303]
#### Issue description:
The interface exports other things then the ones I specified on the GUI
#### What happens:
I have an interface which i want to export all type of ores. So I put all 8 different types in the interafce export slots, but it exports wrong ores.

![2016-08-28_17 10 33](https://cloud.githubusercontent.com/assets/14994463/18034674/36e5aec4-6d43-11e6-9eb0-4992e08151af.png)

From left to right i want copper(IndustrialCraft 2), bauxite(Immersive Engineering), nickel(IE), tin(IC2), iron, lead(IC2), silver(IE), gold, to be exported but for all modded ores it exports something else e.g uranium for all IC2 ores and bauxite for all IE ores.
It doesn't matter if compare NBT is on or off. 

#### Version:

- Minecraft: 1.10.2
- Forge: 1.10.2 - 12.18.1.2073
- Refined Storage: 0.9.4

Does this issue occur on a server? [yes/no]
Did not test the issue on a server.

**Comment by raoulvdberge** [comment]
Not a bug. Click the "compare damage" sidebutton so it says "Yes". These ores are technically the same item, thats why you have to enable damage value compare.

**Comment by rishenko** [comment]
Hi! I realize this issue is closed, but could you add that piece of information to the wiki for the Interface and Exporter? I have spent a significant amount of time today trying to troubleshoot this and stumbled upon this report via serendipitous google searching.

**Comment by raoulvdberge** [comment]
@rishenko This is not needed, already for a while now compare nbt & damage are both set to "yes" by default.
