### ISSUE TITLE
[Request] shift hover over an item and drag'n drop a nugget from it

### ISSUE THREAD

**Issue by 0blu** [raoulvdberge/refinedstorage#304]
I saw https://github.com/raoulvdberge/refinedstorage/issues/288 and thought it would be very cool if you can shift hover over an item(in the grid) and drag'n drop a nugget from it.
See this: http://i.imgur.com/PmFtl5Zg.png

**Comment by raoulvdberge** [comment]
Idea seems cool initially, but:
1) you can autocraft them already in whatever form you want
2) wouldn't work with ingots from other mods
