### ISSUE TITLE
Controller Not Obeying RS Signal Preference

### ISSUE THREAD

**Issue by Winrylive** [raoulvdberge/refinedstorage#305]
#### Issue description:
Applying redstone via lever to controller does not turn controller, and thus the whole network off, when mode is set to "Work Only Without RS signal"

#### What happens:

Nothing.

#### What you expected to happen:

Controller and all connected devices that use RS power should turn off, right?

#### Steps to reproduce:
1. Change controller mode to "work only without rs signal"
2. Apply lever and turn on
3. See that nothing happens.
...

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge: 12.18.1.2073
- Refined Storage: 0.9.3

Does this issue occur on a server? [yes/no] Yes

#### If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here]

**Comment by raoulvdberge** [comment]
I can't reproduce this, please try on the latest version. If the issue is still there, let me know
