### ISSUE TITLE
Solderer gives the wrong printed processor for the Gold Ingot

### ISSUE THREAD

**Issue by jokish63** [raoulvdberge/refinedstorage#307]
What happens: The Solderer returns Printed Basic Processor for the Gold Ingot 
What you expected to happen: Printed Improved Processor

- Minecraft: 1.10.2
- Forge: 12.18.1.2076
- Refined Storage: 0.9.4

Does this issue occur on a server? [I'm just play in Single Player Mode]
If a (crash)log is relevant for this issue, link it here: the game does not crash -  so - no crash log

**Comment by raoulvdberge** [comment]
Can't reproduce, please DOUBLE CHECK before you report. Thanks.

![2016-08-30 14_37_31-minecraft 1 10 2](https://cloud.githubusercontent.com/assets/10358424/18089273/6148856a-6ebf-11e6-9501-ca90fc6b8911.png)

**Comment by jokish63** [comment]
I have made a more detailed check and found the problematic mod (GrimPack). I have examined these more closely and still found more problems. I removed that thing and my private Pack worked slightly better. Sorry for wasting your time
regards jokish
