### ISSUE TITLE
Fluid Storage Not Acting Appropriately with Adv. Generators

### ISSUE THREAD

**Issue by JathTyki** [raoulvdberge/refinedstorage#308]
#### Steps to reproduce:
1. Create Syngas and import it into the Refined Storage Fluid Cell (at least the 128k Fluid Storage Disk)
2. Create Exporter, provide a item that has Syngas in it to export it, and export it to a large container
3. Even if you only imported 1 bucket, it will continuously export until the external storage device is full.
...

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge: 2075
- Refined Storage: 0.9.4

Does this issue occur on a server? [yes/no] Yes

#### If a (crash)log is relevant for this issue, link it here: N/A

[pastebin/gist/etc link here]

**Comment by raoulvdberge** [comment]
To which container are you exporting the gas to? Also, if you export another liquid to that container, does it get drained or is it Syngas exclusive?

**Comment by JathTyki** [comment]
It is almost Syngas exclusive. It is the Advanced Generator's Gas Generator. I have not attempted to do it to another tank - let me try that now actually.

**Comment by JathTyki** [comment]
I can't reproduce now after I upgraded Refined Storage but now it won't accept Syngas as a fluid.

Please ignore, it seems it was "fixed" in 0.9.4. My apologies for not testing it in this version beforehand. I got a little hasty.

**Comment by raoulvdberge** [comment]
> but now it won't accept Syngas as a fluid 
So there is still a bug? What do you mean by this?

**Comment by JathTyki** [comment]
Yes, there is still a bug.

So here's what happens. Advanced Generators doesn't recognize the Refined Storage importer as a storage device it seems. When I attach it to the fluid out valve, it won't export it to the system. So I need to export it to an external tank (in this case Mekanism's basic fluid tank) and then import it. Now it won't import it whatsoever, even if I try other mod's storage containers like Ender IO's fluid tank.

**Comment by raoulvdberge** [comment]
1) Use a Fluid Interface if you want to use stuff like valves
2) Are you sure you didn't blacklist the fluid in your disk drive / storage block?

**Comment by JathTyki** [comment]
Sorry for the delay. Been a hectic week.

1) I will make sure to use a fluid interface in the future.
2) It seems the infinite liquid thing is back. I had an issue with exporting fluids but figured it out. Now, I'm trying to export Rocket Fuel and it continues to output, creating an infinite source. I was exporting to Mekanism's Basic Fluid tank, and I also tried with Ender IO's Fluid Tank. I don't have a whole lot of tank options but even when I exported it to the Advanced Generator tank it did the same.

It's weird, I'm not sure why it is happening. But it is definitely reproducible on my side at least.

**Comment by ilordnightmarei** [comment]
does same thing for cresorite oil  from immersive engineering it switches between values of 00.8 to00.2 or00.5 in the fluid storage grid so that could maybe be an issue of  fluid math or something

**Comment by raoulvdberge** [comment]
Think I fixed this for 1.0, but I'll leave this open because I'm not sure if its the actual fix

**Comment by raoulvdberge** [comment]
Closing this now, if it isn't fixed please let me know
