### ISSUE TITLE
feature request range  upgrades usable in constructor/deconstructor

### ISSUE THREAD

**Issue by ilordnightmarei** [raoulvdberge/refinedstorage#309]
#### What happens: add 1 range upgrade  adds range to constructor/deconstructor by couple blocks
ad of course power usage increases

#### What you expected to happen: range increased by x factor in front of  constructor/deconstructor
 a toggle button for rectangle mode and line mode using straight or cube mode in front of constructor/deconstructor but ether is fine my idea wold be the size of the area increases with upgrade amout so if a cube then it make a 3 by 3 cube on 1 upgrade and if line it wold do a 3 by 1 line
line mode wold be <=constructor /deconstructor x=range break area for line mode example: {<xxx}

#### Steps to reproduce:
1.place upgrade in  constructor/deconstructor
2.profit
3.
...

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge:na
- Refined Storage:na

Does this issue occur on a server? [yes/no]

#### If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here]

**Comment by raoulvdberge** [comment]
How would the range increase? In a rectangular area, straight in front of the con/destructor, ..?

**Comment by ilordnightmarei** [comment]
hmm id have to say  a toggle button for rectangle mode and line mode  using straight or cube mode  in front of constructor/deconstructor  but ether is fine   my idea wold be  the size of the area increases with upgrade amout so if a cube then it make a 3 by 3 cube on 1 upgrade and  if line it wold do a 3 by 1 line
line mode wold be  <=constructor /deconstructor   x=range break area for line mode  example: {<xxx}

**Comment by raoulvdberge** [comment]
I won't be accepting this request as this would be replacing Buildcraft, which is out of scope for a storage mod.
