### ISSUE TITLE
[Feature Request] Infinite range upgrade

### ISSUE THREAD

**Issue by mttprvst13** [raoulvdberge/refinedstorage#311]
I think it would be cool, if RS had an infinite wireless range upgrade, so you don't have to worry about putting down all of those wireless "relays". I just think this would improve the gameplay a little bit, like for example, what if you are in the nether, do not have the stuff for a "relay", but are building a massive structure, or accidentally left your advanced charm of dislocation in the system? I just think that would make a better gameplay.

**Comment by mttprvst13** [comment]
I just got another idea on this topic. Maybe you have to make a special wireless terminal that takes in the infinite range upgrade. Then you would just make those two things harder to make than the normal wireless stuff.

**Comment by raoulvdberge** [comment]
No, whatever you do to make it "more costly", this idea stays way too overpowered. I won't be adding a infinite range upgrade (of course, addon mods are free to do this).
