### ISSUE TITLE
JEI cannot find wireless grid model

### ISSUE THREAD

**Issue by LousyLynx** [raoulvdberge/refinedstorage#312]
#### Issue description:
When I tried to make an addon to RS, JEI is giving me this error:
`[JEI]: Couldn't get ItemModel for Refined Storage itemStack 1xitem.refinedstorage:wireless_grid@0 refinedstorage:wireless_grid`
#### What happens:
When I run the runClient task on my gradlew I get this error:
`[JEI]: Couldn't get ItemModel for Refined Storage itemStack 1xitem.refinedstorage:wireless_grid@0 refinedstorage:wireless_grid`
#### What you expected to happen:
No errors with anything
#### Steps to reproduce:
1. Create new forge project
2. Add RS, JEI, and MCMultiPart as mods, and RS as a dependency
3. Run the runClient task on gradlew
4. Open the inventory

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge: 12.18.1.2011
- Refined Storage: 0.9.4

Does this issue occur on a server? N/A

#### If a (crash)log is relevant for this issue, link it here:
N/A

**Comment by mttprvst13** [comment]
UPDATE: I found, when you scroll down in any inventory to see the Wireless Grid, the client crashes. I have a crashlog here: [Link](http://pastebin.com/wMZhUfcZ). The steps to reproduce are the same, but you just scroll down in the RS creative inventory tab. My versions for forge are the latest version(Not recommended anymore), and the RS version is 1.0(I compiled it myself)

**Comment by raoulvdberge** [comment]
Can't reproduce, you probably did something wrong while setting up an RS instance
