### ISSUE TITLE
Provide obfuscated builds on Bintray

### ISSUE THREAD

**Issue by KristjanKr** [raoulvdberge/refinedstorage#315]
#### Steps to reproduce:
1. Download latest dev build 
2. Remove stable build
3. Add the dev build to mods list
4. Hit start.
5. Crash :(
   ...
#### Version (Make sure you are on the latest version before reporting):
- Minecraft: 1.10.2
- Forge: 2076
- Refined Storage: refinedstorage-1.0-15

Does this issue occur on a server? [yes/no] no
#### If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here]

https://paste.ee/p/FYohT

**Comment by TheSeven** [comment]
This seems to be due to the builds on bintray not being obfuscated, so you can't run them in a normal forge client.
You can rebuild from the source code manually and grab the obfuscated jar file from that build, which seems to work just fine.

**Comment by raoulvdberge** [comment]
I need to also get the obf build on there, but this Bintray stuff is kinda new to me so I have to figure it ask.

**Comment by rubensworks** [comment]
Adding this snippet to your build file could help: https://github.com/CyclopsMC/CyclopsCore/blob/master-1.9/gradle/dev.gradle#L11-L15

If that doesn't work, you may want to use a maven plugin to publish to bintray, like I do here: https://github.com/CyclopsMC/CyclopsCore/blob/master-1.9/gradle/deploy.gradle#L41-L99
I think this may have been the reason why I chose to not use the bintray plugin.

**Comment by raoulvdberge** [comment]
I'm planning to move to Jenkins soon so this can be closed.
