### ISSUE TITLE
Erroneous Controller Explosion

### ISSUE THREAD

**Issue by crawford42** [raoulvdberge/refinedstorage#317]
#### Issue description:

I had a network with controller, external storage (connected to storage drawers), soldering station, disk drive (no disks, was crafting one), and crafting grid. While working with the crafting grid, the controller exploded.

#### What happens:

Controller exploded, destroyed some other elements of the network.

#### What you expected to happen:

Didn't expect a controller explosion without a second controller.

#### Steps to reproduce:

Haven't tried yet.

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge: 12.18.1.2069
- Refined Storage: 0.9.4

### Does this issue occur on a server? [yes/no]

No

**Comment by raoulvdberge** [comment]
Can't repro this. Are you sure it isn't a creeper or something?
