### ISSUE TITLE
[Feature Request] Power Exporter

### ISSUE THREAD

**Issue by MacGynan** [raoulvdberge/refinedstorage#319]
Currently i have to have two cables running through the base. One of which is RS and Power. Adding a exporter of RF/TESLA that with upgrades can put out infinite amounts of energy would solve my problems. 
(I am aware about the Ender IO support feature request) Ender IO cannot transfer infinite power.

**Comment by TeamSpen210** [comment]
It'd make more sense to limit the power output significantly (even with upgrades). Data cables can't really transfer much power normally. It should produce enough power to allow for some basic machines to be used, but you'd need proper cables to run anything particularly energy-intensive.

**Comment by MacGynan** [comment]
Since the mod is Multipart compatible, there could be a cable that can run underneath/around the cables. The main reason i want Infinite FR/t is because i have Extreme Reactors installed + other power gen which output loads of power on 1 cable. Ender cables aren't able to handle it.

**Comment by raoulvdberge** [comment]
No, RS is a storage mod and the cables have a single responsiblity: transfering a network signal. RS does NOT handle energy.
