### ISSUE TITLE
Modpack users claim items are dissapearing

### ISSUE THREAD

**Issue by iPencil** [raoulvdberge/refinedstorage#321]
#### Issue description:
I would usually not report such a thing because I don't think there is much to report, but after the 4th person has reported items disappearing in their RS system I feel like I must at least pass it on.

#### What happens:
A couple of people on my server have claimed that items mysteriously dissapear, somtimes stacks of it. One person has also had previously used up resources reappear in his system. We are using a chunk claim system and those people play alone, on a whitelisted server so the amount of people on there are limited. Nobody can access these systems.

#### Steps to reproduce:
This is the problem, so I'm asking if there is any way I can enable some kind of logging or anything to be able to produce a  more valuable report? I know this is pretty useless right now but I'm not sure how I can get more info on this.

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge: 2072
- Refined Storage: 0.9.4

Does this issue occur on a server? [yes/no]
 yes

I would love to have something I can tell these players.

Thanks!

**Comment by raoulvdberge** [comment]
Probably related to #310

**Comment by iPencil** [comment]
@raoulvdberge I doubt it is because one of the users in question had only a single controller, a grid and a disk storage right next to each other. He didn't even use cables.

**Comment by raoulvdberge** [comment]
doesn't matter, if the disk drive or whatever is in another chunk it could still break

if that isn't the issue then I highly suspect something is wrong with your server (e.g. saving being broken) or a crossmod interaction preventing saves.

**Comment by iPencil** [comment]
I'll check if the machines are in one or multiple chunk.

I'm not sure what I can say. We're actually on a very minimalistic modpack, only a handful of mods and those are typically the most stable ones/have been out the longest and are in 99% of the mainstream packs out there.

I have also not had any issues with saving at all, so I doubt it's that. We've been running tons of servers on that same machine in the exact same setting and have never had any issues like that.
