### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by KristjanKr** [raoulvdberge/refinedstorage#324]
#### What happens: Crash
http://paste.ee/p/kfNkP

#### Steps to reproduce:
1. Get latest dev build: refinedstorage-1.0-30.jar
2.Remove old build
3.Add that dev build
4. Hit play and crash
...

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge: build 2077
- Refined Storage: refinedstorage-1.0-30.jar

Does this issue occur on a server? [yes/no] idk(it just gave me crashlog)

#### If a (crash)log is relevant for this issue, link it here: http://paste.ee/p/kfNkP

[pastebin/gist/etc link here]

**Comment by raoulvdberge** [comment]
You reported this issue already? #315
