### ISSUE TITLE
Huge TPS hit with External Storage on Colossal Chests

### ISSUE THREAD

**Issue by Mattabase** [raoulvdberge/refinedstorage#325]
#### Issue description:

Huge TPS issue while using the External storage on a really big inventory.
#### What happens:

http://i.imgur.com/h7UeXjH.png
#### What you expected to happen:

N/A
#### Steps to reproduce:
1. Place an External Storage on a Large Inventory ( Colossal chest in my case.)
   ...
#### Version (Make sure you are on the latest version before reporting):
- Minecraft: 1.10.2
- Forge: 2076
- Refined Storage: 0.9.4

Does this issue occur on a server? [yes/no]

Yes
#### If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here]

**Comment by aaronmallen** [comment]
Having the same issue on a Storage Drawer network that can hold 27M items... Disconnecting external storage completely removes frame rate lag.

**Comment by aaronmallen** [comment]
Workaround: I moved my storage drawer network approx 5 chunks away and connected it with a wireless transmitter/receiver.  TPS has been restored to normal levels.

**Comment by Time6628** [comment]
Here's an expanded warmroast as I was asked to provide in #852 
![WamRoast](http://i.imgur.com/tpPC23N.png "WarmRoast")

While it may seem little in warmroast, it can eventually get so bad, I cannot even warmroast the server. 
Here's the TPS of a few players having external storages, 
![EXTTPS](https://cdn.discordapp.com/attachments/122793141316091904/268929466305085441/tpsreport1.jpg "EXTTPS")

**Comment by raoulvdberge** [comment]
That is indeed the https://github.com/CyclopsMC/CyclopsCore/issues/35 issue. Not an RS issue

**Comment by Time6628** [comment]
It's not just a cyclops issue, it happens with storage drawers. In fact, the second screenshot is from HermitPack, which does not have colossal chests, only storage drawers.

**Comment by way2muchnoise** [comment]
@Time6628 without a nps file we can't do anything about it. You should profile it and deliver said file. A picture is as use full as me scratching my ass.

**Comment by raoulvdberge** [comment]
If the a Cyclops item is stored in a drawer, the issue will persisT.

**Comment by raoulvdberge** [comment]
Fixed for the next 1.10 and 1.11 versions

**Comment by way2muchnoise** [comment]
Relevant commits 3c7f16a6ca2051a4bcba14c6ac5f302b7ca1d029 and 1c764e3ab328f92cda1d81dcd112071a736f555a
