### ISSUE TITLE
Ingame Config

### ISSUE THREAD

**Issue by LousyLynx** [raoulvdberge/refinedstorage#326]
Hey, I just finished making an ingame config editor. It is not a separate mod, but its when you go into mods on the title screen, and press the config button on a mod. If you would like to see my code, it is right over [here](https://github.com/LousyLynx/Infinity-Storage/tree/master/src/main/java/infinitystorage/integration/ingameConfig), and to register that, add this line to your `init` function, in your `CommonProxy` file:

    MinecraftForge.EVENT_BUS.register(new IngameConfigEventHandler());
You also need to add this to your `@Mod` annotation:

    guiFactory = "refinedstorage.integration.ingameConfig.GuiFactoryIngameConfig"

**Comment by raoulvdberge** [comment]
done by @way2muchnoise in 5cfe09282fd1444c13d94a7b0fbc183d39883c43
