### ISSUE TITLE
External Storage Dupe

### ISSUE THREAD

**Issue by MrBuddha19** [raoulvdberge/refinedstorage#328]
#### Steps to reproduce:
1. Place network transmitter/receiver and an external storage.
2. Unload chunks and see if receiver is red 
3. Then look in main storage and the chest with original items.
...

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge: 12.18.12076
- Refined Storage: 0.9.4

Does this issue occur on a server? [yes/no]
yes
#### If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here]

**Comment by raoulvdberge** [comment]
Is this issue still present in version 1.0?

**Comment by MrBuddha19** [comment]
I don't know yet I only realized there was an update after I posted.
