### ISSUE TITLE
[Feature request] Emit redstone signal on crafting/activity

### ISSUE THREAD

**Issue by bondgb** [raoulvdberge/refinedstorage#329]
Loving 1.0! I just had one feature request: something similar to the emitter/redstone upgrade from AE2, making it possible to emit a redstone signal when the crafter is operating for example. It could be a extension of the detector block or a upgrade card that makes it emit the signal. Could have a lot of cool applications, but I'll just mainly use it to turn on lights when stuff is being crafted ;)

**Comment by raoulvdberge** [comment]
So, essentially a "emit redstone signal when item is crafting"?

Aditionally, I can also make it so if you leave the item slot in the Detector empty and that mode is selected it'll emit a signal when ANYTHING is crafting.

**Comment by bondgb** [comment]
That would be perfect!

**Comment by Karmacopper** [comment]
I know this is a 3yo post, however is this still a feature (1.12.2)? It does not seem to be available.

**Comment by Darkere** [comment]
With the autocrafting rework (that is now also over a year old) this feature did not make it back.

**Comment by Karmacopper** [comment]
Is there any kind of workaround? Example usage, auto crafting Blood Magic slates.

**Comment by Darkere** [comment]
See here for some ways: https://www.reddit.com/r/feedthebeast/comments/f2sqlk/trying_to_automate_slates/
