### ISSUE TITLE
Massive FPS loss whilst controller is filling with power

### ISSUE THREAD

**Issue by b0bst3r** [raoulvdberge/refinedstorage#33]
And I mean massive from 120 FPS to 10 FPS, once the controller is full of power it's ok.

If you break the controller whilst it's filling up the FPS is regained, if you place it back down again the FPS is lost until it fills up so it's def the controller.

Forge 1865
refinedstorage-0.5.5

**Comment by b0bst3r** [comment]
Not your issue this is the mod which is powering the controller

**Comment by b0bst3r** [comment]
Sorry after further tests it is the controller which is causing this.  It seems the constant texture drawing is hitting FPS hard.   What made me close it was I went to use another machine and my FPS dropped, thinking it was the power gen mod.  But by draining power using this other machine it made the controller power indicator flicker causing FPS loss.

So I broke the power connection to the controller and my FPS dropped until it ran out of power, this most definitely concludes that the controller texture redrawing is causing the issue.

**Comment by raoulvdberge** [comment]
Do you have any machines connected? If so, how much?

**Comment by b0bst3r** [comment]
I do but it does it with just the controller on it's own.

Currently have Solderer, controller, disk drive and grid and 1 cable.

**Comment by raoulvdberge** [comment]
I'm pretty sure this issue is not about texture redrawing, all the controller status textures are pre-baked when MC launches.

**Comment by raoulvdberge** [comment]
Try to disconnect all the machines, is the controller still laggy?

**Comment by b0bst3r** [comment]
Well if you've managed to make a block lose 100 FPS and it's not about the textures that's a new one on me lol :D 

Have a video on the issue specially just made for you - https://youtu.be/dGM9AQmjsT4 unedited so excuse the interruption lol

**Comment by raoulvdberge** [comment]
Thanks, I know where the issue is and will solve this for the next version.

**Comment by raoulvdberge** [comment]
The issue was not really a texture bug -- more like a "me causing a chunk update when energy level changes" bug :P

**Comment by raoulvdberge** [comment]
Fixed (I hope :P)

**Comment by raoulvdberge** [comment]
I released a 0.5.6 version on Curse that fixes this error.
