### ISSUE TITLE
Wiki update

### ISSUE THREAD

**Issue by Badcholo** [raoulvdberge/refinedstorage#330]
#### Issue description:
Not knowing how to use the solder.
#### What happens:
the solder did not work
#### What you expected to happen:
i connected the solder to power and tried giving it a redstone signal.
#### Steps to reproduce:
1.I tried everything, but couldn't get the solder to work. checked the wiki and it said nothing about connecting it to a controller. I think it's an important piece of information to place in the wiki or in game tool tip. It took me a while and testing to figure it out.
2.
3.
...

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge:
- Refined Storage:

Does this issue occur on a server? [yes/no]
yes
#### If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here]

**Comment by raoulvdberge** [comment]
The wiki literally states you have to connect the solderer to the controller:

![2016-09-13 15_18_14-getting started raoulvdberge_refinedstorage wiki](https://cloud.githubusercontent.com/assets/10358424/18475104/8ce9af58-79c5-11e6-924b-1f034060bd63.png)

https://github.com/raoulvdberge/refinedstorage/wiki/Getting-Started

**Comment by raoulvdberge** [comment]
I've reworked the getting started guide a bit, so it should be more clear.

**Comment by Badcholo** [comment]
Awesome Ty, Also I'm unsure of what machines i can use the upgrades in. I made some upgrades that wouldn't work with the solder, such as the stack upgrade. not expensive and very useful, but being new to the mod, it's a little bit of a hassle to figure out what upgrades go where.
Thank you so much for your awesome mod. I'm enjoying it very much on my private server. Feel free to check out the modpack. 
http://www.technicpack.net/modpack/krazyglue.891423

**Comment by raoulvdberge** [comment]
Every wiki page of the machines state the upgrades they take
