### ISSUE TITLE
Storage module tablet displaying wrong maximum amount of items stored

### ISSUE THREAD

**Issue by phantomholo** [raoulvdberge/refinedstorage#331]
#### Steps to reproduce:
1. Place storage module tier 1 into remote storage (remote id:3)
2. Place another storage module tier 3 in second remote storage slot(remote id:2)
3. Place remote storage module beside tier one storage module to obtain remote id of 3
4. Place the same remote storage module in the slot beside tier 3 storage module to obtain remote id of 2
5. Open the storage module tablet and click cycle, number sometimes stays at 100 for both pages or stays at 300 on both pages

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge: 12.18.1.2076
- Refined Storage: 1.0

Does this issue occur on a server? Singleplayer world

**Comment by raoulvdberge** [comment]
Storage module tablet is an RFtools item, not a Refined Storage item. Report this on the RFTools issue tracker, not here
