### ISSUE TITLE
Few Suggestions

### ISSUE THREAD

**Issue by Darkere** [raoulvdberge/refinedstorage#333]
As you seem really bored adding Forge energy support? Here is a bit of stuff I'm missing in your mod :)

- this is actually kinda really needed : Give out finished items before having finished the whole job
- more than 500 items at a time ? ok why is this a thing? "MAX_CRAFTING_PER_REQUEST = 500;"
- See needed materials for a crafting job
- Fluid Crafting
- Shortcut to take out all of one item
- crafting with multiple inventories

**Comment by raoulvdberge** [comment]
> As you seem really bored adding Forge energy support? 

lol

> this is actually kinda really needed : Give out finished items before having finished the whole job

I don't understand what you mean by this

> more than 500 items at a time ? ok why is this a thing? "MAX_CRAFTING_PER_REQUEST = 500;"

To avoid people trashing their items when they accidently enter too much, you can just open the crafting GUI several times though. There is no actual limit on how much tasks can run at the same time, it's just like that in the GUI.

> See needed materials for a crafting job

Nah

> Fluid Crafting

Already in there, autocrafting can fill buckets from your fluid storage

> Shortcut to take out all of one item

???

> crafting with multiple inventories

???

**Comment by Darkere** [comment]
If I craft 1000 stone bricks I want to be able to take out a stack before the crafting is finished so that I can start working ...

I meant a keyboard shortcut so that when you click an item in the grid you get your inventory filled with that item.

oh does it automatically fill buckets when autocrafting? thats cool

Autocrafting for example with a vanilla furnace. It needs the coal inserted on a side and the ore on the top. right now you would need an extra chest and filter in by hand/pipes.

**Comment by raoulvdberge** [comment]
> If I craft 1000 stone bricks I want to be able to take out a stack before the crafting is finished so that I can start working ...

You want your items before they are crafted?!

> I meant a keyboard shortcut so that when you click an item in the grid you get your inventory filled with that item.

Don't think that deserves a keyboard shortcut

>  Autocrafting for example with a vanilla furnace. It needs the coal inserted on a side and the ore on the top. right now you would need an extra chest and filter in by hand/pipes.

Just export coal to the furnace, it's faster. Also, handling that doesn't belong in a storage mod
