### ISSUE TITLE
Crashing on Level Load

### ISSUE THREAD

**Issue by don287** [raoulvdberge/refinedstorage#336]
[crash-2016-09-13_21.53.39-client.txt](https://github.com/raoulvdberge/refinedstorage/files/470661/crash-2016-09-13_21.53.39-client.txt)
#### Issue description:
log attached
jei dosn't seem to be the issue
without it crashes when i try to open the tab for rs in creative
same with RS 1.0

#### Steps to reproduce:
simply load the world and it crashes

- Minecraft: 1.10.2
- Forge: 12.18.1.2076
- Refined Storage: 1.0.1

**Comment by way2muchnoise** [comment]
This crash usually occurs when a bad RF api is loaded in. Try cutting down on some mods and find the culprit. (This crash might not always happen, as when there are multiple mods including the api it can be a good or bad one being loaded in)

**Comment by don287** [comment]
unfortunately i cant't find any mod using rf in my list..  accept rs

**Comment by way2muchnoise** [comment]
Try adding enderIO, they have a pretty debug line for errors like this one

**Comment by raoulvdberge** [comment]
Yup, some other mod is bundling a bad RF api. See #114 for an example of this

Not an RS issue, so i'll close.

**Comment by don287** [comment]
ok i've found the faulty pack
in my case it was NuclearControl
