### ISSUE TITLE
Request: Solderer to allow stacks of items on output slot

### ISSUE THREAD

**Issue by b0bst3r** [raoulvdberge/refinedstorage#34]
I don't see why it wont stack items in the solderer when the items themselves stack ok, you have to remove 1 before the next will process.

Forge 1865
refinedstorage-0.5.5

**Comment by raoulvdberge** [comment]
Will be fixed for the next version.

**Comment by raoulvdberge** [comment]
Fixed in master

**Comment by raoulvdberge** [comment]
I released a 0.5.6 version on Curse that fixes this error.

**Comment by Harith163** [comment]
May I suggest you make an upgraded solderer that does the above while maintaining the original solderer?

**Comment by raoulvdberge** [comment]
Why do you want that? The behaviour suggested here makes sense to me.

**Comment by Harith163** [comment]
I want that because it adds a level of complexity to a neat mod. If you make it so that you have to craft a basic solderer first, use the processors and cores to craft an advanced soderer, it would make it feel more worth it.

**Comment by raoulvdberge** [comment]
You certainly have a point, but I am hesitant to revert this because it's supposed to be consistent with MC's current inventory behaviour: items of the same type should stack.

**Comment by Harith163** [comment]
Then how about this... Consider a few end game items like maybe a wireless crafting grid that always has charge. It could have a range of 1024 blocks and it would require a 4 printed nether stars, 4 beacons and a normal wireless grid. Of Course the complexity of the recipe is up to your imagination. The printed nether star would require a tier 2 solderer which in turn would have a crazy recipe(something along the lines of enriched diamond blocks and enriched iron blocks?).

**Comment by raoulvdberge** [comment]
I like the idea, but I just do not want to add needless complexity to it, that is for modpack authors.

Also, in the dev version it is already possible to extend the Wireless Grid's range.
