### ISSUE TITLE
Feature Suggestion Destroy pipe

### ISSUE THREAD

**Issue by Badcholo** [raoulvdberge/refinedstorage#341]
#### Issue description:
I have a lot of garbage that is collected from a tree farm and other such things. I could use a Export Destroy pipe. Something that i can configure to destroy items. I have 45k fletching from tinkers and can't destroy those fast enough from my tree farm. It could be very useful for other such things i don't want filling up my System.
#### Steps to reproduce:
1.
2.
3.
...

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge:
- Refined Storage:

Does this issue occur on a server? [yes/no]

#### If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here]

**Comment by raoulvdberge** [comment]
Just export with speed and stack upgrades to a bin / trashing block from another mod.

**Comment by Badcholo** [comment]
Some modpacks don't have a bin or trash can that you can pipe into. Luckly it's a private server. Thanks anyways.
