### ISSUE TITLE
negetave items on disk and possibly exporter holding items with stack upgrade

### ISSUE THREAD

**Issue by ilordnightmarei** [raoulvdberge/refinedstorage#343]
#### Steps to reproduce:
1. unknown 
2.most likely inventory related maybe
3.exporter holding items with stack upgrade 
...

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge: .2086
- Refined Storage:1.0
- modpack: allthemods

Does this issue occur on a server? [yes/no]
 yes

#### If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here]

**Comment by raoulvdberge** [comment]
what happens if you break+replace the controller?

**Comment by ilordnightmarei** [comment]
its the disk when i remove the disks and put them back in the negative items go away  but breaking the controller wont do very much

**Comment by LousyLynx** [comment]
Could there possibly be negative items? I know I have seen negative amounts of items in Minecraft 1.10 I believe. I have not looked far into the code, but based on the way you count a number of items, I would think that negative items might cause a negative amount in the drive...
