### ISSUE TITLE
1.0.2 Crafting recipies which uses items that take durability damage

### ISSUE THREAD

**Issue by redparry** [raoulvdberge/refinedstorage#344]
#### Issue description:
When auto crafting items which use an item with durability(e.g. IC2 plates), the crafter recreates the tool so that the metadata matches the one in the crafting pattern.

#### What happens:
New tools are created for each crafting operation

#### What you expected to happen:
The tool is used until it runs out of durability

#### Steps to reproduce:
1.Install Refined Storage and IC2.
2.Creating crafting setup which created IC2 plates from a full durability hammer.
3.Request 2 or more of that craft.
(4.If you recreate the pattern with the slightly damaged tool the crafter uses that tool)

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge:2088
- Refined Storage:1.0.2
-IC2 2.6.61-ex110
Does this issue occur on a server? [yes/no]
yes

#### If a (crash)log is relevant for this issue, link it here:

**Comment by raoulvdberge** [comment]
Not a bug... autocrafting always takes the identical item as specified in the pattern. To automate IC2 stuff, use a rolling machine.

**Comment by redparry** [comment]
While this may be true of IC2, that was merely an example of one such tool. Another example, which probably would have been better to pick in the first place, is the extra utilities 2 glass cutter. This has no alternative machine that I know of so the only way auto crafting could be possible is if the crafter supports tools.

**Comment by raoulvdberge** [comment]
For the glass cutter, I'm sure there are blocks from other mods (like the ExU User) that simulate player actions. With a processing pattern, this is trivial to automate.

**Comment by TeamSpen210** [comment]
It's not used in-world in this case, it's used to cut ender pearls in the crafting grid (using up durability).

**Comment by PapiDimmi** [comment]
@raoulvdberge It would be neat if you could fix this. I assume you can make tools lose one point of durability whenever autocrafting is done.

**Comment by PapiDimmi** [comment]
Crafting with items that use durability, such as Actually Additions’ knife, Immersive Engineering’s hammer, IC2’s cutter, EU2’s glass cutter, _etc._ does not work properly; items don’t lose durability as they should.

Is this not on your to-do list? Lots of items that are necessary to auto-craft use durability, so I'd assume that this would be one of the high-priority issues.

**Comment by PapiDimmi** [comment]
@raoulvdberge Crafting with items that use durability, such as Actually Additions’ knife, Immersive Engineering’s hammer, IC2’s cutter, EU2’s glass cutter, _etc._ does not work properly; items don’t lose durability as they should.

Is this not on your to-do list? Lots of items that are necessary to auto-craft use durability, so I'd assume that this would be one of the high-priority issues.

**Comment by way2muchnoise** [comment]
@PapiDimmi that used to be a working feature I have no clue where it went wrong, nor do I have the time to fix things right now.

**Comment by PapiDimmi** [comment]
@way2muchnoise Aw, all right. I hope it’ll be fixed in the future.
