### ISSUE TITLE
Server crash and missing disks/items on reboot

### ISSUE THREAD

**Issue by shikyo13** [raoulvdberge/refinedstorage#346]
#### Steps to reproduce:
1. Unsure, happened when no one was logged into the server. 

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge: forge-1.10.2-12.18.1.2073-universal.jar
- Refined Storage: refinedstorage-1.0.1.jar

Does this issue occur on a server? Yes

#### If a (crash)log is relevant for this issue, link it here:

http://pastebin.com/UXVRGyKH

**Comment by IchigoGames** [comment]
i do not think this has been fixed
