### ISSUE TITLE
Error matching of meta/nbt for jei + click

### ISSUE THREAD

**Issue by jco2641** [raoulvdberge/refinedstorage#348]
#### Issue description:
When a recipe requires an item with a damage value or NBT data, a matching item in the storage (or player) inventory won't be found on clicking the JEI +, or by a refined storage crafter attempting to craft the item.   

However, after placing the items into the crafting grid manually, and then taking out the finished item, the correct items in the storage network *do* refill the crafting grid.

#### What you expected to happen:
The grid and crafter should be able to find the matching item that exists in the storage network under all circumstances.

#### Steps to reproduce:
1.  Open crafting grid UI
2.  Click into JEI recipe view of an item whose ingredients have meta/nbt values  (e.g. Mekanism Basic Energy cube)
3.  Click + button in JEI
4.  Grid is filled with all items **except** the ones with meta/nbt
5.  Find correct item in the storage network with the grid
6.  Place item into appropriate spaces in recipe
7.  Click to remove crafted item
8.  Grid is refilled with all items in recipe, **including** the ones with meta/nbt

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge: 12.18.1.2087
- Refined Storage: 1.0.2

**Comment by raoulvdberge** [comment]
Not much I can do about that. The JEI recipe says it takes / needs a full durability item. So I do what JEI says. There is no way for me to detect if said mod allows to be autocompleted with a mod with a different damage value.

**Comment by jco2641** [comment]
It doesn't look like the JEI recipe is specifying a full-damage item.  The damage bar and the nbt tooltip match exactly between what is in JEI and what is in the network.   

![recipeview](https://cloud.githubusercontent.com/assets/278093/18587494/33a7e3f6-7bd7-11e6-93eb-764f5e3c4cd8.png)
![netcontents](https://cloud.githubusercontent.com/assets/278093/18587495/33c1a5a2-7bd7-11e6-8ff9-bfbd06af782d.png)
