### ISSUE TITLE
Disk Drive takes control of keyboard input

### ISSUE THREAD

**Issue by b0bst3r** [raoulvdberge/refinedstorage#35]
Please make it so the Priority box is not selected automatically when you open the DD GUI and can you also make it so that it's deselectable (click anywhere off the priority box).  As it stands you have to press ESC to close the GUI and I'm always typing e in the priority box.

Same with "grid"

**Comment by raoulvdberge** [comment]
There are some more blocks that have the priority field autoselected, will change that.

For the grid, I am not too sure. It is very handy that that field is autoselected, but I might make it an option.

**Comment by b0bst3r** [comment]
Yeah could always give the JEI button a 3rd option to not search.

**Comment by raoulvdberge** [comment]
Fixed in master

**Comment by raoulvdberge** [comment]
I released a 0.5.6 version on Curse that fixes this error.
