### ISSUE TITLE
[Request] Auto crafting item check

### ISSUE THREAD

**Issue by Udary** [raoulvdberge/refinedstorage#358]
#### Issue description:
When selecting an item to auto craft display a window showing all the items needed for the craft so you can check if there are enough to make the request.

#### What happens:
Currently just accepts the craft and shows the craft as stalled in the crafting window if not all items required are available

#### What you expected to happen:
If a required item is missing for the craft you should not be able to continue

#### Steps to reproduce:
1. Create pattern to craft something (workbench)
2. Have 3 of 4 wood in the inventory
3. In the grid select [Craft] for the patterned workbench
4. Select 1 and press Start
5. Check status on the crafting grid, item stalls at 75%

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge: 12.18.1.2089
- Refined Storage: 1.0.2

**Comment by way2muchnoise** [comment]
#374 might be interesting here

**Comment by raoulvdberge** [comment]
Merged
