### ISSUE TITLE
More filtering options in the Grid Filter.

### ISSUE THREAD

**Issue by CyaNox** [raoulvdberge/refinedstorage#359]
I'd love to see a few more filtering options in the grid Filter namely:
- Ore Dictionary (Toggle).
- Mod filter (Makes it list all items from the mod you enter an item in there).
- Block versus Item toggle (If this is even possible).
- Inverted toggle (making it so that what matches the filter is not shown).

Also would love to see more filter slots but with the above options this may not be too necessary.

It would be nice to also get the following filter options but they may be not too easy to make work across all the different mods or should be in a separate upgrade:
- Consumables
- Plantables
- Armors
- Weapons
- Tools

**Comment by raoulvdberge** [comment]
> Ore Dictionary (Toggle).

OK

>  Mod filter (Makes it list all items from the mod you enter an item in there).

OK

> Block versus Item toggle (If this is even possible).

I don't know what you mean by this one

> Inverted toggle (making it so that what matches the filter is not shown).

OK

> It would be nice to also get the following filter options but they may be not too easy to make work across all the different mods or should be in a separate upgrade:

Nah

**Comment by CyaNox** [comment]
>> Block versus Item toggle (If this is even possible).

> I don't know what you mean by this one

A toggle option to set the filter to: only show blocks, only show items or show blocks and items.

> Nah

 Heh, I expected as much, no biggy ;)

**Comment by aionys** [comment]
Searching @mod is possible, might be something I get for having JEI installed.

I'd much prefer a mod sorting option like the inspiration for this had.

**Comment by raoulvdberge** [comment]
New options in the grid filter:
- mod filter
- oredict filter
- whitelist/blacklist
