### ISSUE TITLE
Crash when building network

### ISSUE THREAD

**Issue by BrokenHearted2** [raoulvdberge/refinedstorage#36]
I was building my normal AE like network set-up, 3 drives on top, grid, crafting grid, grid, 2 drives on the bottom with the controller in the middle. I guess your mod doesn't like that set-up since this crash happens. I have tried it with the creative controller and the normal one, same type of crash. Using refinedstorage-0.5.5.

[pastebin](http://pastebin.com/ZuDiETZ8)

**Comment by raoulvdberge** [comment]
Thanks for reporting, I think I found the cause. Just to be able to reproduce, can you share a screenshot of your setup?

**Comment by raoulvdberge** [comment]
I released a 0.5.6 version on Curse that fixes this error.
