### ISSUE TITLE
Non-Vanilla Ores in Compacting drawers not displaying correctly

### ISSUE THREAD

**Issue by choekstr** [raoulvdberge/refinedstorage#361]
#### Steps to reproduce:
1.  Compacting drawer with osmium or yellorite ingots
2.  External storage on drawer controller
3.  Look in RS grid and only see blocks
...

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge: 2084
- Refined Storage: 1.0.1

Does this issue occur on a server? [yes/no]  YES

**Comment by raoulvdberge** [comment]
Is this an RS issue? Do other mods show the same results as RS? It might be that the storage drawers base mod doesn't recognize Mekanism stuff.

**Comment by choekstr** [comment]
I can't determine if it is an RS issue but both ExtremeReactors Yellorite and Mekanism Osmium show up properly in the compacting drawers as both ingots and blocks and allow me to take out either one at will.  This is why I thought it was an RS tweak that needed to be made.

I just tested with steel.  IC2 steel in a compacting drawer looks proper in RS with both ingots and blocks as does Mekanism steel and I can remove either of those in ingots or blocks and the respective other version (block or ingot) decreases accordingly.

So I would say it isn't all non-vanilla metals and items.  So far only found this with Yellorite and Osmium.

Have any thoughts on what this could be?

**Comment by raoulvdberge** [comment]
I'm gonna go ahead and say this is not an RS issue.

**Comment by choekstr** [comment]
After spending time importing all my ores into RS today I just now would agree.  I think this is a storage drawer issue as I saw some issues with Osmium in a drawer without it connected to RS.  Sorry for worrying you about this but I just found out the issue seems to be in the drawer instead.
