### ISSUE TITLE
[1.0.2] Priorities not working correctly

### ISSUE THREAD

**Issue by Belgabor** [raoulvdberge/refinedstorage#364]
Priorities are not working (what I consider) correctly. Items go into high priority storage first (which is fine), but are also pulled from high priority storage first (which is not). This makes moving items from one storage to another harder than it (imo) should be. Items need to be pulled from low priority first.

**Comment by way2muchnoise** [comment]
Next release should have the Disk Manipulator which you can use to fill and empty drives. Like the IO port in AE. That should help you out.

**Comment by raoulvdberge** [comment]
For moving stuff, use the manipulator coming in next release like @way2muchnoise said.

I'd rather keep the behavior for both pushing and pulling consistent, so I won't change this.
