### ISSUE TITLE
[1.0.2] Importer and Exporter should have their recipes swapped

### ISSUE THREAD

**Issue by Belgabor** [raoulvdberge/refinedstorage#365]
Currently the exporter uses a destruction core and the importer a construction core, to me it seems as if it should be the other way around.

**Comment by raoulvdberge** [comment]
Exporter destructs items from your system to the chest

Importer constructs items in your system from a chest

**Comment by raoulvdberge** [comment]
Actually, you can look at it from both ways. But to be consistent with the constructor / destructor blocks, I'll change this
