### ISSUE TITLE
[1.0.2] Metadata export issue

### ISSUE THREAD

**Issue by Belgabor** [raoulvdberge/refinedstorage#366]
I'm trying to export brown hardened clay from the system (metadata 12), but the system exports light gray hardened clay (metadata 8) instead. Same happens if I configure it for red hardened clay (14).
Orange (1) works fine.

**Comment by raoulvdberge** [comment]
There is this button on the side of the GUI "compare damage". Toggle that to "yes".

**Comment by Belgabor** [comment]
Ah, I missed that. Still what I said holds somewhat true, it is inconsistent. Configured for Orange clay it exports orange clay, configured for brown or red it exports light gray. If it truly ignores metadata it should export the same type no matter what I configure it with.

**Comment by way2muchnoise** [comment]
It isn't inconsistent at all. Since the only thing differentiating colours for clay is the metadata. So ignoring meta data will export any clay block.

**Comment by Belgabor** [comment]
How is getting different results with different metadata if said metadata should be ignored not inconsistent?

**Comment by way2muchnoise** [comment]
Meta data ignored means that it won't give a fuck about what it is. In the case of wool, clay, ... (most coloured blocks) this means the colour is ignored. You need to match the meta data to take colour in consideration.
