### ISSUE TITLE
Auto crafting gets ahead of itself

### ISSUE THREAD

**Issue by PancakesMan** [raoulvdberge/refinedstorage#367]
#### Issue description:
Auto crafting will try to craft 1 item in the middle of crafting another, and it halts the auto crafting process completely.
#### What happens:
When crafting a improved processor, I had no printed silicon and no printed improved processors. I started auto crafting an improved processor, and the system started making the printed silicon first, so it put the gold into the center slot of the solderer and started making the printed improved processor, then it put in the silicon and started making the printed silicon. About half way through the printed silicon it decided to start making the improved processor, and added the printed improved processor and redstone to the solderer. This completely stalled it as the center slot was filled with silicon and the recipe was no longer valid.
#### What you expected to happen:
I should be able to click start auto crafting and leave my system alone for 30 mins while I do other stuff and not come back to nothing having been auto crafted because it got stuck half way through (I have noticed it do it with other recipes too, I am a lazy man and usually just let the system create every component from complete scratch, the basest of base materials)
#### Steps to reproduce:
1. Put silicon, gold, and redstone in the system
2. Add an autocrafter facing a solderer with recipes to create the printed silicon, printed improved processor, and improved processor.
3. Craft a decent amount ( tested with 10+ )
4. Right click solderer and wait for it to mess up

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge: 12.18.1.2092
- Refined Storage: 1.0.4

Does this issue occur on a server? [yes/no]
Single Player and LAN Server

Image of solderer inventory: https://i.imgur.com/qDlD7DK.png

**Comment by raoulvdberge** [comment]
Will fix this ASAP for the next release
