### ISSUE TITLE
[1.10.2] Crafting is eating items it should be returning

### ISSUE THREAD

**Issue by b0bst3r** [raoulvdberge/refinedstorage#368]
#### Issue description:

I only have 1 example so not sure if it's isolated to this or will affect other things too.  If you use an Agricultural Revolution Juicer to  make say apple juice it eats the juicer when it should be returned.

#### What happens:

The juice crafts but eats the juicer when it should be returned.

#### What you expected to happen:

The juicer should be returned as it is not consumed in the recipe.

#### Steps to reproduce:
1. Put juicer, bottle and apples in the Refined Storage Crafter
2. Pull out the apple juice
3. Lose the juicer
...

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge: 12.18.1.2088
- Refined Storage: 1.0.4

Does this issue occur on a server? [yes/no] Yes

**Comment by raoulvdberge** [comment]
Is probably fixed in dev

**Comment by raoulvdberge** [comment]
Should be fixed in latest version
