### ISSUE TITLE
Infinite liquids withdrawal

### ISSUE THREAD

**Issue by vhd** [raoulvdberge/refinedstorage#369]
#### What happens: 
Extracting liquid from system with < 1000 mb yields more liquid

#### What you expected to happen: 
No liquid in storage

#### Steps to reproduce:
1. Have fluid storage block with 350 mb (any liquid, any amount < 1000mb)
2. Attach an exporter in liquid mode to any tank 

At single cycle tank will be filled with 350 mb, but 650 mb will remain in system

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge: .2092
- Refined Storage: 1.04

Does this issue occur on a server? [yes/no]
yes

#### If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here]

**Comment by raoulvdberge** [comment]
Does this happen to really *any* tank? Which ones did you try?

**Comment by vhd** [comment]
Yes, with any of IC2, Mekanism and TiCon

setup preview
![bug1](https://cloud.githubusercontent.com/assets/487056/18675784/281d6e6a-7f5c-11e6-9615-b4cb802d7508.png)
![bug2](https://cloud.githubusercontent.com/assets/487056/18675783/281c4404-7f5c-11e6-8ea2-b268f8c1915f.png)
notice filled tanks
![bug3](https://cloud.githubusercontent.com/assets/487056/18675782/2815550e-7f5c-11e6-8f5e-e6fa0c0c28d6.png)

**Comment by vhd** [comment]
...Fluid Interface?

https://github.com/raoulvdberge/refinedstorage/blob/mc1.10/src/main/java/refinedstorage/tile/TileFluidInterface.java#L122

**Comment by raoulvdberge** [comment]
Whoops, thanks
