### ISSUE TITLE
[0.5.6] Crafting Grid "half craft"

### ISSUE THREAD

**Issue by Xiaminou** [raoulvdberge/refinedstorage#37]
1. When crafting with the Crafting Grid if you right click a recipe that gives multiple items it will only give you half of them but use all of the crafting ingredient (stone bricks > right click > get 2 stone bricks instead of 4).

2. If you double click an item in your inventory to regroup it it will also pick up the output of the craft.

Additionally it would be nice if there was the "standard search" from AE2 which does not automatically select the search box, it's what I like to use.

**Comment by raoulvdberge** [comment]
Thanks for reporting.

So I was thinking about these grid modes:
- standard search
- standard search, autoselected
- jei synchronized search
- jei synchronized search, autoselected

What do you think?
