### ISSUE TITLE
Autocrafting and Importbus not working on server

### ISSUE THREAD

**Issue by vanAndesen** [raoulvdberge/refinedstorage#371]
#### Issue description:
Importbus and autocrafting in Crafter does not work on server, but works fine in creative world.

#### What happens:
When making a Pattern and putting it into a Crafter, then asking the system to craft it, nothing happens, nothing in the Crafting monitor and no mats being taken for the process.
All materials are there, the whole system is hooked up.

Have an Importbus hooked up to a central crate for collecting, but the Import bus will not import anything from the crate.

#### What you expected to happen:
Crafting of the item. 
Importing the items into the system.

#### Steps to reproduce:
1. 
2.
3.
...

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge:12.18.1.2092
- Refined Storage: 1.0.4

Does this issue occur on a server? [yes/no] YES

#### If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here]

**Comment by ShaCraft** [comment]
Did you reboot the server/client? Try breaking and replacing the blocks as a workaround.

**Comment by raoulvdberge** [comment]
In which block did you make that pattern?

**Comment by vanAndesen** [comment]
@ShaCraft 
Reboot tried, taking the whole system apart and rebuilding it tried, even tried disconnecting anything except from the needed blocks.

@raoulvdberge 
Pattern Grid, as from experience the Processing Pattern Encoder is for use, if you use the crafter onto a machine, ie. Alloy Smelter from EIO.

The server owner is going to test to see if Sponge is making problems, as it has with a lot of stuff lately.
It all worked last week with ATM v1.25 on the server, currently we run v1.27.

**Comment by raoulvdberge** [comment]
So you are having this issue on a Sponge server?

**Comment by vanAndesen** [comment]
Yes, SpongeForge server.

**Comment by raoulvdberge** [comment]
I don't support SpongeForge.

**Comment by vanAndesen** [comment]
So what you are saying is that the mod is kinda only ½ way usefull if people use a Spongforge server?

**Comment by raoulvdberge** [comment]
So what you are saying is that I am supposed to support 2 modding platforms? You really think I have time to support 2 platforms at the same time, when I only work on RS during my free time?
