### ISSUE TITLE
Server Crash with Enderio at refinedstorage.tile.TileSolderer$3.insertItem(TileSolderer.java:50)

### ISSUE THREAD

**Issue by ProsperCraft** [raoulvdberge/refinedstorage#373]
See issue here - 
https://github.com/SleepyTrousers/EnderIO/issues/3713

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge: 2092
- Refined Storage: refinedstorage-1.0.4

Does this issue occur on a server? [yes/no]
Yes

#### If a (crash)log is relevant for this issue, link it here:

See Enderio github issue.

**Comment by raoulvdberge** [comment]
The crash log tells me nothing about what happened, so I'm not sure what I can do about this
