### ISSUE TITLE
There's a conflict going on.. 

### ISSUE THREAD

**Issue by tacogerbil** [raoulvdberge/refinedstorage#376]
#### Issue description:
crashes, seems to conflict with other mods..... until you rename refined storage so it loads first.
#### What happens:
1. server crashes.
2. I rename the jar file from refinedstorage-1.0.5.jar to `refinedstorage-1.0.5.jar so it loads first.
3. Server loads.
#### Steps to reproduce:
1.install in server wait for crash
2.rename file so it loads first
3.no crash
...

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge: Forge Mod Loader version 12.18.1.2090
- Refined Storage: refinedstorage-1.0.5

Does this issue occur on a server? yes

#### If a (crash)log is relevant for this issue, link it here:

Crash log: http://pastebin.com/uqeL19xS

**Comment by way2muchnoise** [comment]
Crashes at `szewek.mcflux.wrapper.ic2.EUInjectRegistry.wrapEUTile` doesn't seem at all like a RS crash.
Also`BungeeCord/SpongeForge`, there is no support for SpongeForge

**Comment by raoulvdberge** [comment]
Not an RS issue, please contact whatever `szewek.mcflux.wrapper` is!

**Comment by tacogerbil** [comment]
I removed spongeforge.. The folders are still set up like they were.. Right now it's just a plain forge server..  No sponge or related plugins running.
still does it.... Only reason I brought it here is because the thread shows refinedstorage as being the one to error out..
	UCE	refinedstorage{1.0.5} [Refined Storage] (refinedstorage-1.0.5.jar) 
http://pastebin.com/1PJ0c6zC

FULL fml-server-latest.log
http://pastebin.com/UKhkcKad

**Comment by way2muchnoise** [comment]
It isn't RS  go and report it at the [MC flux repo](https://github.com/Szewek/Minecraft-Flux)

**Comment by tacogerbil** [comment]
will do ;)  thx ;)
