### ISSUE TITLE
Fluid Interface Not Allowing Removal

### ISSUE THREAD

**Issue by Boundarybreaker** [raoulvdberge/refinedstorage#377]
#### Issue description:
Once you put fluids into a network, you can't extract them
#### What happens:
If you put a fluid in the "out" section of a fluid interface, it won't let you pipe the fluid out using Ender IO fluid conduits or Extra Utilities fluid transfer nodes, even if the conduits are set to extract.
#### What you expected to happen:
You should be able to remove fluids from an RS network using the fluid interface
#### Steps to reproduce:
1. Put fluid into an RS network using the fluid interface
2. Set the fluid you just put in on the "out" area of the interface
3. Connect an Ender IO fluid conduit, an XU fluid transfer node, or other fluid-piping method
4. Nothing happens

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge: 12.18.1.2092
- Refined Storage: 1.0.5

Does this issue occur on a server? [yes/no]

#### If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here]

**Comment by raoulvdberge** [comment]
Like the regular interfaces, you can only extract fluid from the fluid interface from the bottom side. Does that fix it?

**Comment by Boundarybreaker** [comment]
Yes it does! Thanks for clarifying!
It seems that if you're only able to extract from one side, it might be nice to have a method of rotating the interface to choose what side to extract from. Do you think that could be added in sometime?

**Comment by raoulvdberge** [comment]
No, I think it's fine this way
