### ISSUE TITLE
Enhancement: allow to trigger autocraft even if there are items 

### ISSUE THREAD

**Issue by DoomSquirter** [raoulvdberge/refinedstorage#379]
#### Issue description:
AE allowed you to middle click an item and trigger the crafting menu even if there were items for it.

#### What happens:
If I have one or more items but it is auto-craftable, I'd want to hit middle click or something to allow me to autocraft more of said item.  AE also had a option to show just crafting but not items.  using "Only Craftables" does only show the items that are craftable but it also shows the items alongside it.

#### What you expected to happen:
See above

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge: 2093
- Refined Storage: 1.05

Does this issue occur on a server? [yes/no]
yes

**Comment by raoulvdberge** [comment]
Already possible, CTRL + SHIFT

https://github.com/raoulvdberge/refinedstorage/wiki/Grid#inputs
