### ISSUE TITLE
Payload may not be larger than 32767 bytes

### ISSUE THREAD

**Issue by b0bst3r** [raoulvdberge/refinedstorage#38]
refinedstorage-0.5.6
jei_1.9-3.3.2.197
Forge 1865

Clicking recipe (the +) in JEI for RFtools shield template or Iron chests gold upgrade causes client disconnect with the following message - http://i.imgur.com/hrBQ5c3.png BUT only on the Refined storage crafting grid, the above recipes work fine in normal crafting table or Neotech Duel crafting tables.

Log traps the following - http://i.imgur.com/TpOpnzX.png

No crash log generated.

**Comment by b0bst3r** [comment]
FYI - Tried with Forge 1887 and this still happens

**Comment by raoulvdberge** [comment]
Will fix this for the next version, for now I recommend to not use the recipe transfer button on those recipes.

**Comment by raoulvdberge** [comment]
Should be fixed in 9fd1fc865b31c97896811ab575cb142e8dc94c53

**Comment by raoulvdberge** [comment]
I assume you've been playing the mod for a while now, so I'm curious: what do you think of it?

**Comment by b0bst3r** [comment]
Pretty decent although the trapping of the cursor in the search box (on all terminals) still bugs the hell out of me, waiting patiently for the crafting update :) everyone on the server keeps asking too, since you teased us on reddit.

**Comment by raoulvdberge** [comment]
Heh, cool. The trapping is fixed in the next version, decided not to add it for 0.5.6 because it was quite a diff (only wanted small fixes in there).

**Comment by bugreporter0** [comment]
Have same issue unfortunatelly, with exact same logs. One recipe that bugs out is botania's documentation book.
