### ISSUE TITLE
Server Crash CraftingTaskProcessing.writeToNBT

### ISSUE THREAD

**Issue by utoc** [raoulvdberge/refinedstorage#381]
Pastebin: http://pastebin.com/jL7dSNnm

Cause: Unknown. Experienced chunk corruption during this crash and had to revert from backup
Full forge log unavailable due to the server continually restarting itself from corruption crashes

Running FML 2092, RS 1.0.4, MCMultipart 1.2.1

Additionaly when we tried to restore from a backup at 1005, we got this error (which may be due to RefinedStorage's ability to hold lots of unique items): http://pastebin.com/RHs9QvcZ but I think that MAYBE one thing lead to the other but I can't verify it and the crash report doesnt give ANY good information to know what might have caused it.

Sorry for the abbreviated (and very incomplete) crash report, its a total mystery to us what caused the initial crash and we have no working world to dissect to try to get to the bottom of it.

**Comment by raoulvdberge** [comment]
I'm guessing this is because two patterns depend on each other, so they loop around. I'll investigate

**Comment by raoulvdberge** [comment]
Fixed with 0a89d0318f91c3725bc697cb93f68381cbdfcd40
