### ISSUE TITLE
Crash with JEI (recipes)

### ISSUE THREAD

**Issue by DarkIceXD** [raoulvdberge/refinedstorage#384]
#### Issue description:
- crash when loading world

#### Version:
- Minecraft: 1.10.2
- Forge: 12.18.1.2094
- Refined Storage: 1.0.5
- JEI: 3.11.0.269

#### If a (crash)log is relevant for this issue, link it here:
[http://pastebin.com/bfAmDM7M](url)

**Comment by raoulvdberge** [comment]
Fixed for the next version coming within 1-2 days

**Comment by AlphaKintari** [comment]
JEI 3.11.1.270 does not resolve the issue. Might need to wait for another update.
http://paste.ee/p/962iq

**Comment by way2muchnoise** [comment]
The issue isn't the JEI version. It is RS using JEI internals that changed. Next update of RS should fix that.
