### ISSUE TITLE
Crash with JEI [FIXED FOR NEXT UPDATE, COMING TODAY/TOMORROW] [DOWNGRADE JEI FOR NOW]

### ISSUE THREAD

**Issue by AstroCat2Space** [raoulvdberge/refinedstorage#388]
The game crashes when I create or enter a world with JEI and Refined Storage.

 **Version (Make sure you are on the latest version before reporting):**

- Minecraft: 1.10.2
- Forge: 12.18.1.2094
- Refined Storage: 1.0.5
- JEI: 3.11.1.273

**If a (crash)log is relevant for this issue, link it here:**

[http://pastebin.com/6gTAsrmT]

**Comment by Hjaldar** [comment]
Crash also occurs with JEI 3.11.1.275. It doesn't happen with JEI 3.10.0.268.

**Comment by UnRealDinnerbone** [comment]
Can Confirm im geeing the same crash

**Comment by BlakeDarwinXE** [comment]
Minecraft: 1.10.2
Forge: 12.18.1.2094
Refined Storage: 1.0.5

I tested JEI versions listed below.
Crashes
JEI: 3.11.1.276
JEI: 3.11.1.275
JEI: 3.11.1.274
JEI: 3.11.1.273
JEI: 3.11.1.272
JEI: 3.11.1.271
JEI: 3.11.1.270
JEI: 3.11.1.229

Works
JEI: 3.10.0.268

JEI Bug report link: https://github.com/mezz/JustEnoughItems/issues/461
Refined Storage Bug report link: https://github.com/raoulvdberge/refinedstorage/issues/388
Crash Log: http://pastebin.com/R5M75Uk8
[gist](https://gist.github.com/BlakeDarwinXE/4fb402a409b738bb501cd6d02ca6e46e)

**Comment by mezz** [comment]
Already fixed here: https://github.com/raoulvdberge/refinedstorage/pull/385

**Comment by raoulvdberge** [comment]
An update of RS that fixes this comes out soon. Just downgrade JEI for the time being

**Comment by AlphaKintari** [comment]
can confirm that RF v1.1 fixes the issue.
