### ISSUE TITLE
Storage Disk Manipulator

### ISSUE THREAD

**Issue by raoulvdberge** [raoulvdberge/refinedstorage#39]
Allows transfer of storage disk -> network or network -> storage disk.

Has 2 automation settings:
* Move to output when done
* Move to output when storage is full

**Comment by psychofad** [comment]
Was just about to suggest this!  I have players on my server that started out making the storage blocks but wanted to convert over to using the storage disks for space reasons but currently there is no easy way to move items from one to the other, this would be ideal.  I am assuming this would work similar to how the ME IO Port did in AE2, which is exactly the kind of thing we need.

**Comment by way2muchnoise** [comment]
Functionality finished in 423ecee0996fca203099fc69735878f45b541f46

**Comment by raoulvdberge** [comment]
TODO recipe / texture
