### ISSUE TITLE
Storage disk not completely emptying out 

### ISSUE THREAD

**Issue by phantomholo** [raoulvdberge/refinedstorage#391]
#### Steps to reproduce:
1. place 4k disk into disk manipulator set to insert into system in the "in" section
2. items start clearing from disk into system
3. at a certain point disk stops inserting items into system and doesn't want to insert items into system when I try to place it back in the "in" section 
...

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge: 12.18.1.2088
- Refined Storage: 1.0.5

Does this issue occur on a server? no, I'm on singleplayer

#### If a (crash)log is relevant for this issue, link it here: no crash log

**Comment by raoulvdberge** [comment]
Is your system full?

**Comment by way2muchnoise** [comment]
Or do you have any filter set?

**Comment by phantomholo** [comment]
nope, my system has lots of space left and i removed the filters and tested it but got the same result

**Comment by way2muchnoise** [comment]
Could it be that you storage network is filtered and there is no "what ever" space left?

**Comment by phantomholo** [comment]
Don't think so, since I put 3 64k storage disks in my system and none of them are full yet

**Comment by way2muchnoise** [comment]
Can you see what items are in it? Maybe it is some odd glitch somewhere else?

**Comment by phantomholo** [comment]
Nope is there a way to see what items are in the disks? Hmm it may be a bug

**Comment by way2muchnoise** [comment]
You make a separate network with just a terminal, controller and a disk drive. Insert just that buggy disk. And see what is in it through the terminal.

**Comment by phantomholo** [comment]
Ah its kinda getting late in my area here so I think I'll test tomorrow and let you know.

**Comment by phantomholo** [comment]
Ok. Can confirm, not working on the separate network as well, it just gives me back the same disk

**Comment by way2muchnoise** [comment]
And can you see any items on the disk if you just pop in a drive (no the manipulator).

**Comment by phantomholo** [comment]
Oh I totally forgot about that let me just quickly check and get back to you

**Comment by phantomholo** [comment]
Hmm, the disks don't have any items in them when I check the grid

**Comment by phantomholo** [comment]
might be bugged disks?

**Comment by way2muchnoise** [comment]
Jup, I guess something went wrong somewhere. So it might not have been the disk manipulator.

**Comment by phantomholo** [comment]
So I guess I can't really do anything about those 2 disks for now?

**Comment by phantomholo** [comment]
Thanks for the help :)

**Comment by phantomholo** [comment]
Ok, so I realised that a 4k storage disk inside of my system has the same problem when trying to clear it, it gets stuck at about 600+ items. When I try to place it in a separate system like how I did for the 2 bugged disks, I realise that there's actually nothing inside... just like the 2 bugged disks.

**Comment by raoulvdberge** [comment]
I'll move this to #440

**Comment by NoahFlowa** [comment]
I'm having the same problem.  Items from 4K and 1K Storage disks are not moving to my 64K Disks I just made. I tried putting the problem disks into another disk drive that's connected to a different controller and crafting grid and now the items in the disks are not showing.  If you need me to provide photos, server files or videos let me know.
