### ISSUE TITLE
[1.1] Server crash on startup

### ISSUE THREAD

**Issue by Anteater46** [raoulvdberge/refinedstorage#392]
#### Issue description:
Server crashes on startup with Refined Storage v1.1 installed. I noticed this with other mods installed at first, and then tested it with the mod alone and the crash still occurred.
I am using the latest version of MCMultipart, Forge and Refined Storage.
#### What happens:
Server crashes during startup.
#### What you expected to happen:
Server to start.
#### Steps to reproduce:
1. Start server with Refined Storage and MCMultipart installed.

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge: 12.18.1.2094
- Refined Storage: 1.1

Does this issue occur on a server? [yes]

#### If a (crash)log is relevant for this issue, link it here:

http://pastebin.com/F2zKm5cZ

**Comment by OldManCraft** [comment]
I'm Having the same issue.
Caused by: java.lang.NoClassDefFoundError: net/minecraft/client/gui/GuiScreen
	at refinedstorage.proxy.CommonProxy.preInit(CommonProxy.java:73)
	at refinedstorage.RefinedStorage.preInit(RefinedStorage.java:55)

**Comment by UniversalMigrator** [comment]
I"m getting the same issue as well, running a dedicated server. Issue does not occur in the client. I believe the mod is trying call on a class only present in the client, not the dedicated server.
