### ISSUE TITLE
Network Transmitter huge frame drop

### ISSUE THREAD

**Issue by BillboardEric** [raoulvdberge/refinedstorage#393]
#### Issue description:
Using the Network Transmitter and Receiver at a long distance (tested at 500 blocks or so) causes a huge frame rate drop

#### What happens:
Frame rate tanks.
Before network card placed
![2016-09-28_00 29 57](https://cloud.githubusercontent.com/assets/8685981/18900816/5241abb8-8513-11e6-8b95-15d98e33cbf7.png)
After
![2016-09-28_00 30 10](https://cloud.githubusercontent.com/assets/8685981/18900817/576a29ee-8513-11e6-8eee-37c8f15802c3.png)

#### What you expected to happen:
No frame rate drop, if not very minuscule.

#### Steps to reproduce:
1. Place a Transmitter attached to your network
2. Place a Receiver far away and link to network card
3. Place card in Transmitter

#### Version (Make sure you are on the latest version before reporting):
- Minecraft: 1.10.2
- Forge: 12.18.1.2092
- Refined Storage: 1.1

Does this issue occur on a server? Unsure

**Comment by ShayBox** [comment]
Can confirm, lots of lag and i crash when breaking it

**Comment by raoulvdberge** [comment]
Gimme a crashlog then

> Also getting a lot of lag from most of the new textures

I highly doubt that

**Comment by ShayBox** [comment]
I don't care enough to go get a log, and it causes a lot of lag. I usually get 120-130 in my void world, but the new update is spiking to 40 fps... And can confirm, breaking all refined storage blocks remove all lag

**Comment by raoulvdberge** [comment]
If you can't even get a log for me, I can't do much.

**Comment by raoulvdberge** [comment]
If you break the disk drive, does it fix the lag?

**Comment by ShayBox** [comment]
Sorry i cant test, server admin rolled back to the old version, :(

**Comment by raoulvdberge** [comment]
@BillboardEric Do you have something that is causing block updates next to the controller?

**Comment by raoulvdberge** [comment]
closing this as noone is responding, and i can't reproduce this
