### ISSUE TITLE
[1.1.1] Client crash when autocrafting

### ISSUE THREAD

**Issue by Gepett0** [raoulvdberge/refinedstorage#395]
#### Issue description:
Tried to autocraft 32 Atomic Alloy from Mekanism.
Insert the amount clicked "Start", Preview Screen didn't show up, client crashed.
#### What happens:
Client crashed.
#### What you expected to happen:
No crash :-D
#### Steps to reproduce:
Can't reproduce. Tried 1, 10, 32 after relog, went fine.

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge:12.18.1.2093
- Refined Storage: refinedstorage-1.1.1

Does this issue occur on a server? [yes/no]
Yes. But only client crashes.
#### If a (crash)log is relevant for this issue, link it here:

http://pastebin.com/BLYHRHxz

**Comment by RealGrep** [comment]
Just hit that crash while trying to autocraft a draconic energy core. Same versions of everything as Gepett0. My log from the console: https://www.dropbox.com/s/andaoix85gjsisb/rs-crash1.log?dl=0

Right before the "Rendering screen" stack trace, I got a ConcurrentModificationException that seems to have something to do with JEI, and it's present in the next stack trace as well. Possibly still something wrong with the new JEI code, I would hazard a guess.

**Comment by Gepett0** [comment]
Same crash as RealGrep now.
Using JEI 1.10.2-3.12.0.282 FYI

**Comment by raoulvdberge** [comment]
The ConcurrentModificationException is already fixed, however I have to look in the NullPointerException you got, @Gepett0.

**Comment by Gepett0** [comment]
Thanks in advance! 
Nice new textures btw!
