### ISSUE TITLE
Not returning tools from autocrafting

### ISSUE THREAD

**Issue by kaytrim** [raoulvdberge/refinedstorage#396]
#### Steps to reproduce:
1. Make pattern
2. added to crafter
3. requested fruit salad
...

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge: 12.18.1.2088
- Refined Storage: 1.0.5

Does this issue occur on a server? [yes/no]
unknown
#### If a (crash)log is relevant for this issue, link it here:
no crash log
[pastebin/gist/etc link here]

**Comment by raoulvdberge** [comment]
Upgrade to 1.1.x
