### ISSUE TITLE
[Exporter] Exports by oreDict instead of Item Name

### ISSUE THREAD

**Issue by Lukas45** [raoulvdberge/refinedstorage#397]
#### Issue description:
It attempts to export items via oreDict, instead of ItemStack (Item name/ID).
I have Exporters set up to different autocrafters (non-RS ones) and Storage Drawers (for those items that can't be compressed), but it has trouble exporting specific items.
I have 3 exporters to 3 different Storage Drawers with:
Granite (oreDict: stoneGranite)
Diorite (oreDict: stoneDiorite)
Andesite (oreDict: stoneAndesite)
When I hook an Exporter to the storage drawers with the 3 stones, it doesn't export anything, despite me filtering the specific stones to each Exporter.
If I took everything out of the Storage Drawers, it began to export Stone (oreDict: stone) into it.
Same thing happened with the Crafter (EnderIO), when I wanted it to making Lapis Lazuli Block's - It exported nothing. But when I tried to hook it to the shared destination chest, it began exporting everything that shared oreDict with the Lapis Lazuli (dyeBlue, **dye**, gemLapis)

Also happens with blocks with no oreDict, but different Meta levels (ie coloed hardened clay)

#### What happens:
It attempts to export Stone to the Storage Drawers
It attempts to export any dye to the EnderIO Crafter
It picks a random Colored Hardened Clay from your system to export
#### What you expected to happen:
It should export the correct stone to the storage drawers, as the filter is set to
It should only export Lapis Lazuli to the Crafter, as the filter is set to
It should export the specific Colored Hardened Clay that I put in the Exporter (meta data)
#### Steps to reproduce:
Easy steps to reproduce:
1. Have lots of different dyes in the system (most have oreDict "Dye")
2. Put an Exporter to a chest, and ask it to export a specific dye (maybe specificly Lapis Lazuli?)
3. Watch as it exports everything with the oredict "Dye" - If the destination only accepts Lapis Lazuli, or other specific dye, the exporter will become stuc

1. Make a Storage Drawer with Granite/Diorite/Andesite in it
2. Hook an Exporter to the Storage Drawer, and filter it to export said material from above
3. Watch as it gets stuck - if you empty the Drawer, it will begin to fill it with Stone (make sure that's in the system for testing)

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge: 12.18.1.2092
- Refined Storage: 1.0.5

Does this issue occur on a server? [yes/no]
Yes
#### If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here]

#### Additional Information?
This happened out of nothing (in 1.0.4 I believe? May have been over our update to 1.0.5). It was set to export 2k of each stone to the 3 Storage Drawers. It all went well and I put 4 Speed Upgrades in each of them. After one of them reached 22 stacks (aprox), they started bugging out, to the issue above.

**Comment by raoulvdberge** [comment]
Is compare damage set to "yes"? (sidebuttons on the right)

**Comment by Lukas45** [comment]
no, they're all set to "No"

**Comment by raoulvdberge** [comment]
Does it fix it if you set it to "yes"?

**Comment by Lukas45** [comment]
It has indeed.
However, the button does seem mis-leading like it refers to tools only, by the look of icon and description (and I think it should be like that).

**Comment by raoulvdberge** [comment]
Some items and blocks share the same ID, like hardened clay. That's why you were getting other types of clay, as it's technically the same item. So, if you compare on damage it'll also care about the damage value.

The latest version has this turned on by default, so it should fix it.

**Comment by Lukas45** [comment]
I would argue that "Compare Damage" is a bit misleading for comparing metadata (since not all items uses metadata for damage, like stone/colored items), but that's up for your consideration.

Anyways, cheers again.
