### ISSUE TITLE
Make subjobs multithreaded

### ISSUE THREAD

**Issue by Darkere** [raoulvdberge/refinedstorage#401]
The only thing that makes Autocrafting annoying is the fact that you are faster if you queue ingredients than if you queue results. e.g. Crafting 3 16k disks and then crafting the 64k disk is almost 3 times faster than just queueing the 64k disk.

Probably a good idea to makes this some sort of upgrade so that complex jobs don't start making millions of threads :)
Just capping the amount o threads per crafting job also might work.

**Comment by raoulvdberge** [comment]
This is closely related to #412, so I'll close this
