### ISSUE TITLE
Storage Drive Duplication Glitch

### ISSUE THREAD

**Issue by ShayBox** [raoulvdberge/refinedstorage#402]
#### Issue description:
If you install everything blocks mod, compress storage disks into a block, then uncraft it. it gives you a stack of 9, not just 9 drives. then you can shift click that into a drive bay, put items in your system, then separate that stack and all 9 have the same item.
#### What happens:
Duplicate items
#### What you expected to happen:
Not duplicate items
#### Steps to reproduce:
1.Install Everything Blocks Mod (Or any way to stack items)
2.Make a block of 1k storage disks
3.Uncraft that block
4.Shiftclick the stack of 9 into the storage drive bay
5.Put items in the system
6.Seperate the stack
...

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge: Something
- Refined Storage: 1.1.1

Does this issue occur on a server? [yes/no]
Yes

P.S. I also contacted the Everything Blocks dev about adding a blacklist or not uncrafting into stacks, but he is not very active. so maybe you could implement a way to detect if the stack is more than one, and separate them like the old AE did.

**Comment by way2muchnoise** [comment]
This seems like an issue that needs to be fixed on Everything Blocks Mods side. As they are creating the ItemStack. The drive has a max stack size of one and that is something that mod should respect.

**Comment by ShayBox** [comment]
It does have a stack of one limit when i click the stack in and not shift click, but shift clicking in does not separate them like it did with AE1/2. but yea i contacted the mod dev of everything blocks but hes not active really at all. https://minecraft.curseforge.com/projects/everything-blocks/issues/11

**Comment by raoulvdberge** [comment]
Not an RS issue

**Comment by ShayBox** [comment]
kinda is, you everything blocks is not the only mod that can stack items... but its easy for you to impliment

**Comment by way2muchnoise** [comment]
We can't change how recipes work in an other mod. The Everything Blocks is creating invalid ItemStacks. There is no such things as separating them while crafting that is handled by the recipe, but usually they respect the max itemstack.

**Comment by ShayBox** [comment]
You are supposed to make them un-stack when you shift click into the storage drive, not craft/uncraft. AE fixed the issue when they had it, you can too, your just fucking lazy

**Comment by ShayBox** [comment]
Fix it so when you shift click disks into a drive it un-stacks them like AE did. also. 
if any server admins want a craft tweaker script to fix this, let me know. its a good temporary fix

**Comment by way2muchnoise** [comment]
That isn't a fix, it is a work around. There is no point in fixing a bug that an other mod introduces. It is like saying you fridge should fix the packaging issues of fruit. It makes no sense what so ever.

**Comment by ShayBox** [comment]
But its not the other mods fault......... tons of other mods stack items, but your mod should not allow you to put stacks of drives in the bay, or be duplicating the items onto all the drives. although you don't think so, this is your bug. but i'm starting to think you cant code, your just a script kiddie

**Comment by way2muchnoise** [comment]
@ShayBox Oh is this where we are taking this now? I'm the one that can't code? I feel like you should lookup what mods I and go back to playing on your PvP server.
