### ISSUE TITLE
Interdimensional Networks

### ISSUE THREAD

**Issue by Korvynus** [raoulvdberge/refinedstorage#403]
#### Issue description:

I was very happy to see an interdimensional networks feature for this mod. So I immediately jumped on it. I've done everything right and both side of the network is chunk loaded. But the Network Receiver wich inside the Nether is offline and I can't reach my network wich in the Overworld.

#### What happens:

The interdimensional feature of the network transmitter doesn't work at all.

#### What you expected to happen:

To be at least able to acces the grid block from the other side of my network wich is inside the Nether.

#### Steps to reproduce:

1. Put Network Transmitter next to Controller (currently in Overworld).
2. Put Network Receiver and a Grid in another world (currently tested in Nether).
3. Right-clicking the Network Receiver with a Network Card.
4. Fill the network card slot of the Network Transmitter with that card.
5. Fill the upgrade slot of the Network Transmitter with Interdimensional Upgrade.
6. Network Receiver is offline and the Grid next to that receiver show nothing obviously.

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge: 2092
- Refined Storage: 1.1.1

Does this issue occur on a server? Yes and client too.

#### If a (crash)log is relevant for this issue, link it here:

Fortunately, no crash.

**Comment by raoulvdberge** [comment]
Are you 100% sure the chunkloaders are working?

**Comment by Korvynus** [comment]
Well... everything is working now. Maybe I did something wrong the first time. Who knows.
