### ISSUE TITLE
Suggestion: add an option to only allow empty storage movement

### ISSUE THREAD

**Issue by LemADEC** [raoulvdberge/refinedstorage#405]
#### Issue description:
In a PvP context, it's way too easy to pack your base into storage containers and keep it in your inventory while being offline.

#### What happens:
see above

#### Steps to reproduce:
1. Fill a storage block/drive
2. try to break it => break is cancelled
3. try to explode it => content is lost or dropped on the ground
4. Fill a storage drive
5. try to break/explode the drive bay => same as storage block
6. try to remove the drive from the bay => item is locked or empty itself into other storage
...
alternately:
1. Have an empty inveotry
2. Try to pickup a filled storage => ok, players get slowness I
3. pick another one => slowness II
4. pick another one => item is dropped back on the ground

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge: forge1.10.2-12.18.1.2094
- Refined Storage: refinedstorage-1.1.1

Does this issue occur on a server? [yes/no]

**Comment by way2muchnoise** [comment]
There is a lot of other mods that provide a way to store your base into your inventory. This is a request that is very specific to PvP servers and will annoy a lot of regular players. imo it would be a lot of code/work for a feature that will rarely be used (as it will have to be a setting).

**Comment by raoulvdberge** [comment]
I agree with @way2muchnoise, such functionality is only needed for very specific gamemodes. Closing
