### ISSUE TITLE
[1.10.2] Feature Request: Stackable Upgrades

### ISSUE THREAD

**Issue by Morpheus1101** [raoulvdberge/refinedstorage#409]
Would you consider making the speed upgrades and/or other upgrades stack-able?  Presently i'm finding for my current use to import into the RS storage system with 4 upgrades is not churning the items out fast enough to keep up with the demand i have.

**Comment by raoulvdberge** [comment]
3 Speed upgrades + 1 stack upgrade is fast enough. Also if I make it stackable then you can make stuff infinitely fast.
