### ISSUE TITLE
Making a stack issues

### ISSUE THREAD

**Issue by MrTubzy456** [raoulvdberge/refinedstorage#41]
Normally making a stack works perfectly except when a stack of one item is 8 instead of the normal 64. I made an item that stacks with the 8 and shift-clicked expecting just a stack like all the other times. Well it tried making 64, it didn't finish because it used all my gold.

**Comment by raoulvdberge** [comment]
Can you describe your issue a bit better?

So you have an itemstack with a max stacksize of 8. You press shift when crafting. What did you expect and what did you get?

**Comment by MrTubzy456** [comment]
I expected to get a single stack of 8. Instead I got 6 and a half stacks.

Here's one, buckets stack 16 in one stack. Put the recipe in and shift+click and instead of just a stack coming out, you get 4 stacks.
