### ISSUE TITLE
Grid interface pushed leftward after viewing a recipe w/ JEI

### ISSUE THREAD

**Issue by Californ1a** [raoulvdberge/refinedstorage#411]
#### Issue description:
As the title says, if you open the grid interface (any - regular grid, crafting grid, etc.) and then click on an item in JEI to view the recipe, and then return to the grid interface, then it has pushed the grid interface left slightly and JEI is compressed more rightward. If you keep viewing recipes in JEI and returning to the crafting grid (as you usually do for more advanced recipes), eventually JEI disappears+crafting grid is pushed far on the left side and you have to close/reopen the crafting grid to reset the positioning.

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge: 12.18.1.2094
- Refined Storage: 1.1.1

**Comment by raoulvdberge** [comment]
already fixed, read the changelog
