### ISSUE TITLE
EU Convertion is wrong

### ISSUE THREAD

**Issue by Speiger** [raoulvdberge/refinedstorage#413]
As i am telling it always. EU to RF convertion is wrong... Its not 1-4. Its a higher value.

Here is a link with the values in all cases:
https://www.reddit.com/r/feedthebeast/comments/4pak8h/i_compared_all_coal_generators/

The important line which was defining the Original Convertion rate...
Steam Dynamo - not augmented - (Thermal Expansion) for 44000 RF (If not heated) or 48000 RF (if heated) both at 80 RF/t 

Lets say 44000 RF is the base value we talk with. a basic coal generator produces 10 EU per tick. and a single piece of coal has a burntime of 1/4 of the normal burntime. Which means out of 1600 Ticks burntime we gain only 400 Ticks of burning. with the 10 EU production per tick we land at 4000 EU per piece of coal... So thats a 1 EU = 11RF... Thermal Expansion did the mathing 100% wrong... So please adjust your convertion rate...

**Comment by raoulvdberge** [comment]
RS uses the conversion rate that Forestry uses, and last time I checked Forestry still has 1:4.

**Comment by raoulvdberge** [comment]
However, I am willing to make the conversion a config option if that is wished.

**Comment by Speiger** [comment]
@raoulvdberge yeah but even forestry is wrong... Forestry should fix it ioo

**Comment by Speiger** [comment]
default it at least to a higher value. 1-10 is totally fine as default.

**Comment by Speiger** [comment]
its simply rapings IC2s Balance...

**Comment by raoulvdberge** [comment]
Last time I talked to Player, I believe he told me the conversion is 1:4.

**Comment by Speiger** [comment]
No its wrong... I proved to you that its wrong... And player was just repeating Kinglemming... And he did the math wrong...

**Comment by raoulvdberge** [comment]
But... Player is the author of IC2? Doesn't he decide what the default conversion is?

**Comment by Speiger** [comment]
No. KingLemming did decide when he made TE3 it. Based of a Single Piece of coal & the Current BC To EU convertion without validating it...

**Comment by raoulvdberge** [comment]
You aren't answering my question. My assumption is that since Player maintains IC2, he obviously decides what the default conversion rate is.

**Comment by Speiger** [comment]
No he didnt... (as i told last time)

**Comment by raoulvdberge** [comment]
Why not? I saw your calculations, and they make sense. But, at the end of the day it's still the authors of IC2 that decide the wished conversion.

**Comment by Speiger** [comment]
Well lazyness? I mean would you go to every mod that works with your mod and say: "these are forced things"?

**Comment by raoulvdberge** [comment]
What do you mean with lazyness? I don't believe in forcing people / API consumers of *my* mod to do things my way, but, when it is about energy conversions, I choose to respect the wishes of the original authors.

**Comment by Speiger** [comment]
well what if the devs werent asked in the first place?

**Comment by raoulvdberge** [comment]
But the devs agree with the conversion someone else chose. If Player agrees with KingLemming's idea, what is the problem?

**Comment by Speiger** [comment]
What if he said: Do what you want its your mod?

**Comment by Speiger** [comment]
Anyway the convertion is wrong... That is all what counts... So please adjust it^^

**Comment by raoulvdberge** [comment]
I'd still go for his preferred conversion.

**Comment by Speiger** [comment]
So you continue supporting raping EU balance?

**Comment by raoulvdberge** [comment]
Why do you think I'm raping EU balance if Player says the conversion is fine?

**Comment by Speiger** [comment]
Is player always right?

**Comment by raoulvdberge** [comment]
Yes, he maintains the mod. So he decides how the conversion works, IMO.

**Comment by Speiger** [comment]
Also look at the convertion Player did at his converter mod... Its not 1EU-4RF

**Comment by raoulvdberge** [comment]
I'll take a look, thanks for letting me know.

**Comment by Speiger** [comment]
Player is a modder who overcomplex stuff a lot. He does things that are unnessery and thinks never to be wrong... See the Enet he made needs still to be finished. Aroma took the old Enet but its far from to be good. So sry if i question his competence...

**Comment by raoulvdberge** [comment]
You may question his competence, but he still remains the maintainer doesn't he?

**Comment by Speiger** [comment]
Well he is the maintainer... But you see since most of the original team is left the mod starts to fall apart...

**Comment by raoulvdberge** [comment]
That is not relevant to this issue.

**Comment by Speiger** [comment]
Actually it is..

**Comment by raoulvdberge** [comment]
"IC2 falling apart" (according to you) still doesn't justify me changing my opinion about respecting original conversions.

**Comment by Speiger** [comment]
Well i am classics dev so that uses the same eu with the same kind of balance. Shouldnt that call enough for that? I mean i try to rebalance what the devs of Exp did fuck up...

**Comment by raoulvdberge** [comment]
I understand that, but most people still play the original IC2.

**Comment by Speiger** [comment]
True because classic is not as known... But if you compare the rating of Classic to Exp then classic has a way higher rating..

**Comment by raoulvdberge** [comment]
Yes, Classic might have a higher rating but IC2 still has a larger playerbase.

**Comment by Speiger** [comment]
Well good to know. Thanks... So i have to know that you are not interesting of fixing a bug that was created because nobody wanted to... Thanks anyway...

**Comment by raoulvdberge** [comment]
This is not a bug, this is a feature request.

**Comment by Speiger** [comment]
It is a bug!
A bug is because its converting the energy wrong. Making wrong side extremly weak to provide energy but overpowering it when it comes to adding energy to it... So do not claim it as none bug!

**Comment by raoulvdberge** [comment]
It is a bug according to *you*. It's not a bug according to *me* and the IC2 maintainer.

**Comment by Speiger** [comment]
Well since players word does not count since he has two answers to it makes your side not as strong...
Its a bug and if you want to see more proof...
Here: People agreeing with me more then you think.
https://www.reddit.com/r/feedthebeast/comments/55pdhj/rf_to_eu_convertion_is_wrong/

Also people who downvote me. Thanks xD

**Comment by Speiger** [comment]
So please tell me again: "Hey its not a bug when i see people say: "This is an issue""

**Comment by raoulvdberge** [comment]
For me personally, changing a conversion rate isn't a bug.

**Comment by Speiger** [comment]
well we will see how long it stays not as a bug. Or how long the convertion will be possible...

**Comment by amadornes** [comment]
Honestly... this sounds like Soni and his attempts at replacing all standards with his all over again :P

**Comment by way2muchnoise** [comment]
Is this where we come out of the shadows?

**Comment by amadornes** [comment]
Pfft... He can hover over the emojis and see who used them, we never were under cover :P

**Comment by Speiger** [comment]
true. But honestly. If you dont fix bugs as easy as those i doubt your competence as coders anyway... Luckly TileEntites are hackable today without using ASM or reflection. So dissabling your convertion is not an issue at all..

**Comment by amadornes** [comment]
Yeah... but if you do this nobody's ever going to want to play with your mod so... good luck ¯\_(ツ)_/¯

**Comment by Speiger** [comment]
xD Really you think that? Cool. Thanks xD

**Comment by raoulvdberge** [comment]
I don't mind you hacking in my mod, here is the class you want:

https://github.com/raoulvdberge/refinedstorage/blob/mc1.10/src/main/java/refinedstorage/integration/ic2/IntegrationIC2.java#L10-L16

**Comment by Speiger** [comment]
Actually not its not that class xD I told you its a tileEntity class

**Comment by Speiger** [comment]
So if you dont understand as easy parts as these then good luck

**Comment by raoulvdberge** [comment]
If you want to change how the conversion works, why would you hook in the tile entities? All the TE's use those 2 methods.

**Comment by Speiger** [comment]
No i dont want to change your convertion anymore.. I dissable your EU support on Classics side to 100% and you can do nothing about that.

**Comment by raoulvdberge** [comment]
Ah, okay. That is your call.

**Comment by raoulvdberge** [comment]
But I'll still add a config option, though.

**Comment by Ghezra** [comment]
So much time in arguing about a different mod.

Mekanism also uses the 1:4 EU:RF conversion.
Gendustry's Dev pointed out its pretty much universal with 'somewhat standard' values leading to 4RF:1EU.
https://www.reddit.com/r/feedthebeast/comments/2l4rr6/1710_conversion_rates_for_rfeumj/
The Power Converters mod uses 1:4, since FTB Monster
https://ftbwiki.org/Power_Converters
The FTB Wiki's own definitions of the different power systems:
https://ftbwiki.org/Power_Systems

Let's get back to making Refined Storage great again. I have faith in you and your choices raoulvdberge! I love how Refined storage has changed from .8 to 1.1.

**Comment by asiekierka** [comment]
EnetBridge uses 3:25.

@Speiger This is not your mod and you have zero say in how they do things. If you don't like it, fork it, but don't spam an author who is clearly disinterested in your vision of balance.

**Comment by raoulvdberge** [comment]
The EU conversion is now configurable, so this can be closed.
