### ISSUE TITLE
Request (1.10.2) Make some of the recipe a bit more early game-friendly?

### ISSUE THREAD

**Issue by LordHellscream** [raoulvdberge/refinedstorage#414]
Really want to use this mod, but often time the recipes are little too expensive for early game. It would be cool if some of them (such as external storage cable -- large amount of work to hook up just 1 container, or the lower tier disks) can be cheaper/easier to make so it would help us to easing-into the mod.
Because often time early game I had to pick a solution and it ended up to always pick some of the cheaper alternative but late game when I want to switch to Refined Storage it ended up being too much work (moving all the items into a new system or rewire the base etc).

Thanks for your consideration!

**Comment by raoulvdberge** [comment]
Well, to be honest, RS isn't meant to be a early-game mod.

**Comment by Ghezra** [comment]
I actually always find it liberating when midgame I can ditch the storage drawer network I've been amassing and throw everything into a central location, wire up access points everywhere and then be happy.
