### ISSUE TITLE
Exporter upgrade for External Storage (or vice-versa)

### ISSUE THREAD

**Issue by Californ1a** [raoulvdberge/refinedstorage#416]
Just a QoL/design feature request...

If you have a large amount of one item that it better kept in a barrel/drawer/bin/etc., like cobble or mob drops for example, then you use the external storage, but if you obtain said item from many places throughout the world and from various bases where you have your storage systems set up then you probably want to feed it into the storage system and have it export to that external storage.

Right now you can use both an exporter and an external storage, but it doesn't look very clean since it requires two sides of the drawer be occupied instead of just one (not as easy to hide), it'd be really nice to be able to stick an upgrade into either the external storage or the exporter so it gains the functionality of both.

**Comment by JohnC94** [comment]
Why not set your external storage at a higher priority than the rest of your storage? You can add the specific item you want in the barrel to the whitelist on the external storage so it will only store that item in the barrel. I have ~30 quantum storage units setup this way for my refined storage system, all are set at priority 99 while my disk drives are priority 5-10.

**Comment by Californ1a** [comment]
Does setting a higher priority automatically export to the external storage container without an exporter? I honestly hadn't thought of using the priority system - having both the external storage and the exporter on the same container made more sense to me.

If it does auto-export to the external storage, then maybe the recipe for the external storage should include the exporter (and importer) so it's more intuitive that an exporter isn't required alongside the external storage. Alternatively, maybe newly-placed external storage should by default be set to a higher priority than the current top priority settings. This way it can be changed to a lower priority if desired, but would also by default prefer the external storage if there is one (potentially only have the priority set at higher default if the attached block is a "single-item" storage, if it's possible to detect that i.e. barrel/drawer/etc.).

**Comment by raoulvdberge** [comment]
Just set the priority of the ext storage. As simple as that.
