### ISSUE TITLE
Out of Memory Error when loading Minecraft after installing RS.

### ISSUE THREAD

**Issue by WarMind666** [raoulvdberge/refinedstorage#417]
#### Steps to reproduce:
1. Install mod through curse
2. run Minecraft
3. Watch crash
...

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge: 2094
- Refined Storage: 1.1.2

Does this issue occur on a server? [yes/no]
not sure, trying to get to work on single player prior to putting it on a server.

#### If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here]
http://pastebin.com/mZxATHPX

**Comment by Ghezra** [comment]
How much memory do you have allocated to your minecraft client? Any custom java arguments?

**Comment by WarMind666** [comment]
Set up for 4 GB of RAM, was working fine with Refined Storage until the
latest update.  No custom Java args

**Comment by raoulvdberge** [comment]
@WarMind666 Please try the latest version
