### ISSUE TITLE
Thaumcraft Integration

### ISSUE THREAD

**Issue by Sorbe** [raoulvdberge/refinedstorage#418]
#### Issue description:

[Feature Request][Long Term][Cross mod]
You've got nearly everything necessary to win over ALL of the AE2 folks.  This mod looks great, the only thing I would suggest is that you make sure to do proper integration with other major mods like Thaumcraft.  By integration, I mean support for Vis, Essentia(like a fluid), and Monitors/Crafting terminals, etc.. While this would be very welcome, I would certainly agree that it should be a lower priority request than the core RS work.

Great job so far, I'm seriously impressed!

**Comment by raoulvdberge** [comment]
Is Thaumcraft even out for MC 1.10.2?

**Comment by Sorbe** [comment]
https://www.reddit.com/r/feedthebeast/comments/545eol/will_1102_thaumcraft_be_another_edition/

**Comment by raoulvdberge** [comment]
RS will not get this kind of integration.
