### ISSUE TITLE
RS power export

### ISSUE THREAD

**Issue by Sorbe** [raoulvdberge/refinedstorage#419]
#### Issue description:
[Feature Request]
One of the problems with AE2 was that it no longer allowed power to be exported to adjacent machines.  If this is not supported yet, please consider exporting as well as importing to all the power types.  This will eliminate any need to ever do "P2P RF Tunnel" solutions or endless Tesseracts to power RS connected machines.

**Comment by raoulvdberge** [comment]
> One of the problems with AE2 was that it no longer allowed power to be exported to adjacent machines.

I don't understand this. You can just place machines next to each other, it'll work?

> This will eliminate any need to ever do "P2P RF Tunnel" solutions or endless Tesseracts to power RS connected machines.

Why would you need endless tesseracts? Power input only needs to be in the Controller.

**Comment by Sorbe** [comment]
In AE2, at least, the AE power was only passed to AE devices.  Any other mods had to get power RF/EU power separately, via Tesseracts, Fluxducts, Conduits, etc.

**Comment by raoulvdberge** [comment]
RS doesn't, and never will transmit RF or any sort of power / energy through the network.

**Comment by Sorbe** [comment]
So, no AE2 P2P like tunnels either?

**Comment by raoulvdberge** [comment]
No, strictly storage only. Maybe as an addon mod.
