### ISSUE TITLE
Provide a Voiding Option for Disk Storage

### ISSUE THREAD

**Issue by Sorbe** [raoulvdberge/refinedstorage#420]
#### Issue description:
[Feature Request]
Please consider adding a storage option to "void" excess materials / fluids once a storage device is full.
I cannot tell you how many times, I've added void upgrades to barrels and drawers to deal with excess materials -- I can safely say that this is a very useful storage feature.

**Comment by Darkere** [comment]
This is already possible with a detector and an exporter.

**Comment by choekstr** [comment]
There is a 1.8.9 version and I hear there Azanor is actively working on the 1.10.2 version.  Someone said about a month away but I wouldn't take that as definitive.

**Comment by raoulvdberge** [comment]
- [x] Item storage tiles
- [ ] Fluid storage tiles
- [ ] Disk drive

**Comment by raoulvdberge** [comment]
Implemented
