### ISSUE TITLE
Botania Integration

### ISSUE THREAD

**Issue by Sorbe** [raoulvdberge/refinedstorage#421]
#### Issue description:
[Feature Request][Cross Mod][Long Term]
When you get around to trying RS with Botania, please test out using RS with the Botanical Brewery, Petal Apothecary, Runic Altar, etc..  Like many of the Botania "devices", they can easily get jammed up if you request multiple items rather than just one.  

The issue is that the Botania devices require you to "drop" items onto them using blocks like Open Crates.  This means that there is no reliable way to tell that the "device" is done other than to check for the output product arriving back into the system.   That, in fact, is the solution -- provide a flow control method that gates the next crafting operation based on the product being returned from the machine.

**Comment by way2muchnoise** [comment]
Making RS "smart" enough to do that would kill the complexity (and fun) of botania (and in-world crafting in general).

**Comment by Sorbe** [comment]
I've already done this with AE2, but I had to add extra non-functional items to recipes and use them as "tokens" to ensure that each recipe completed before the next item request was sent.   That works, but it was huge pain and only Botania had this sort of non-sense.   That was NOT fun.

**Comment by way2muchnoise** [comment]
But it would destroy the whole "difficulty" of the mod (eg. Botania)

**Comment by Sorbe** [comment]
Oh please, you're not here to police whether other players use RS or AE2 or any other mods WITH each other.  

That's a mod pack developer choice OR a player choice of what game he wants to play.  Saying that type of game/gaming will "destroy" the mod is nonsense and frankly none-of-your-business.

**Comment by raoulvdberge** [comment]
whatevah, i'll do what i want

**Comment by Sorbe** [comment]
Of course you will, it’s your mod.  I wasn’t even replying to you with that last comment.  Apologies if you thought it was for you.

I was speaking to the other guy who thinks he should decide which mods are together in a mod pack, because they ‘destroy’ each other.   He is an idiot – it’s not his call.

**Comment by way2muchnoise** [comment]
Adding something to a mod that breaks most of the uniqueness of an other mod is just a dick move. Also it is as much the modders choice as it is the player (or pack makers, who is just a player sharing his instance).

And for the record I'm not "just a gamer". I made a decent amount of contributions to RS and have been doing  MC modding for quite some time.

**Comment by VT-14** [comment]
Vazkii made a design choice with Botania.  Most mods will not go out of their way to bypass something that is clearly intentional.

I'm pretty certain Vazkii has said before that Botania is fully automate-able with only Vanilla Minecraft and Botania.  It should be pretty darn simple to strap on something like RS or AE on top of that.  Spend some time figuring out how to do that, rather than complain that a mod hasn't added a "screw Vazkii's decision" option.

A lot of people out there find the in-world crafting of Botania to be an interesting challenge and quite fun to try to figure out.  If you don't find that fun, then clearly you are not part of the intended audience.

**Comment by raoulvdberge** [comment]
@Sorbe Please  show some respect to other people contributing to this issue. I'll be locking this issue for now, as I think that everything that has to be said has been said.
