### ISSUE TITLE
[refstor 1.1.1] Items disappearing from soldering inventory

### ISSUE THREAD

**Issue by xenoflot** [raoulvdberge/refinedstorage#423]
#### What happens:

Building a new sub-base 100-120 blocks away from the refstor controller. Left some items building to check something at the new base, came back to find the solderer inventory slots were empty. Tried it again in another solderer, same result.

Area is chunkloaded by xutils2 and according to my sugarcane farm, it's working fine.

Broke and replaced a solderer and the problem has disappeared. Well, poop.
I'm not sure what to say now. I'll let you know if it happens again :-/
#### Steps to reproduce:
1. Take FTB Unstable 1.10, add a couple of other mods like Mekanism and FastLeafDecay
2. Have your solderers in place for about 2 weeks
3. Set some solderer builds running
4. Teleport ~100 blocks away
5. Come back, soldered inventory empty
   ...
#### Version (Make sure you are on the latest version before reporting):
- Minecraft: 1.10.2
- Forge: 12.18.1.2088
- Refined Storage: 1.1.1 (1.10.2)

Does this issue occur on a server? [yes]
#### If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here]

**Comment by DBArcAngel** [comment]
I too have had this happen (pack: Advant 3, refinedstorage: 1.1.3, forge: 12.18.2095, server: yes) I do not have the area chunkloaded(yet), Yes it is within the same chunk and not on the boundary. I walked away(teleporting of any kind) from the chunk and then went back and the stuff was still there but it seems it only happens when the chunk is unloaded quickly.

**Comment by JustNireon** [comment]
I have the same problem with autocrafting (System is chunk loaded). when i disconnect and reconnect the crafting is gone and every item is gone(that i was busy  crafting with0. Modpack (HermitPack 1.1) I got them chunk loaded with chunk loading ward (extra util2).

**Comment by Zetharion** [comment]
I playing Hermitcraft 1.2.1 that has version 1.1.3 of Refined Storage.  It is set to auto-restart at a certain time.  I have 4 solderers that each had 32 Iron, 32 redstone, and 32 printed silicon crafting Basic Processors.  Each of them was down to being in the middle of crafting the last one when the server shuts down and restarts.  Upon logging back in after the restart each of the Solderers lost all but one or 2 of the Basic Processors that it had finished crafting.

**Comment by StevenB83** [comment]
Hi, running my own pack using version 1.2.4.
Every time the server restarts everything in the solderers output slot vanishes. Seems to me it doesn't get saved somehow.
Let me know if I can do any more testing for you. Thanks for a great mod!

Steven.
