### ISSUE TITLE
Increasing the fluid input/output limit

### ISSUE THREAD

**Issue by brad18** [raoulvdberge/refinedstorage#424]
**Feature Request**

Hi,
I've been playing around with pressure pipes and refined storage and noticed that refined storage does not allow an input/output rate of greater than 1000mb/t.

Would it be possible to remove this limit on the RS side and input/output according to the pipes of the mod I'm using or perhaps increasing the limit to something similar to the mekanism reactor(100,000-300,000 mb/t)?

Thanks

**Comment by raoulvdberge** [comment]
I suppose I could add support for the stack upgrade which would transfer 64 000 MB/t.

Also, you can use speed upgrades already to export faster.

**Comment by brad18** [comment]
That would be great. Thanks

Also I was getting the 1000mb/t out of an exporter with 4 speed upgrades. Is it meant to be faster than that?

**Comment by raoulvdberge** [comment]
It doesn't work like that, it exports 1000 mb/t every x ticks. With speed upgrades the x ticks amount is decreased, so it's faster, but doesn't export more.

**Comment by brad18** [comment]
Ah ok I get it. Thank you very much.
