### ISSUE TITLE
[1.10.2] Gold ingot produces basic processor

### ISSUE THREAD

**Issue by kwpugh** [raoulvdberge/refinedstorage#428]
#### Issue description:
Recipe for an improved processor does not work correctly
#### What happens:
A gold ingot in the Solder should produce an improved processor, but it produces a basic processor

#### Steps to reproduce:
1.place a gold ingot in a powered Solder
2.wait
3.a basic processor is produced
...

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge: 2095
- Refined Storage: 1.1.2
Modpack: https://minecraft.curseforge.com/projects/pughland-plethora

Does this issue occur on a server? [yes/no] YES

#### If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here]

**Comment by Darkere** [comment]
This is a bug that comes together with another mod called grim pack he does something weird to the ore dictionary i believe.

**Comment by psychofad** [comment]
Using the ore dictionary converter mod I cannot substantiate that.  So are users of Grimpack just SOL?

**Comment by accessdenied0** [comment]
I use Grimpack, too. And I have the feeling it is because the OD entry: IngotMetal. 

Anyway if this is true is this issue caused by OD and in this case it is this mods fault and not Grim's.

**Comment by Darkere** [comment]
I have not tested or anything might just be a config that can be changed. You might wanna try removing mods for testing purposes or look into the config of ore dictionary converter.

**Comment by grim3212** [comment]
Yeah I was adding both iron ingots and gold ingots to ingotMetal. I ended up just removing gold.

**Comment by accessdenied0** [comment]
If this is a OD thing, isn't this issue not a problem in RefinedStorage?

**Comment by grim3212** [comment]
I thought that was the case already.

**Comment by accessdenied0** [comment]
According to this issue not. I'm not sure if he looked into it. There is no update nor a answer, yet. Only a Closed issue. (@raoulvdberge closed it.)

**Comment by raoulvdberge** [comment]
This is not an RS issue
