### ISSUE TITLE
Feature Request: RS Interface Terminal

### ISSUE THREAD

**Issue by robertm1771** [raoulvdberge/refinedstorage#429]
Would be great to access the pattern and import and export inventories of the crafters and interfaces from a remote terminal. Also if you could name the crafters and interfaces so that label could be seen in this terminal.

This would let you change things about the RS system without having to run to a location to correct a pattern or add an item to an export bus or interface.

Thanks for you work on this mod.

**Comment by raoulvdberge** [comment]
Use an RFtools storage scanner for easy access to the crafters

**Comment by robertm1771** [comment]
I hope to always have RFtools available to do that :) thanks for looking at it anyway
