### ISSUE TITLE
EU->RS Conversion/(Buffer?) not working properly

### ISSUE THREAD

**Issue by Berekhalf** [raoulvdberge/refinedstorage#432]
#### Issue description:

The controller will max out the EU/t in a cable even if its internal storage is full.  The problem stops when the controller is no longer using up any RS/t (e.g. there is nothing else on the system) Thus, when connecting an EU Energy Bank to a Controller it will drain it as fast as possible till the Energy Bank is empty.

http://puu.sh/rA9nM.jpg
http://puu.sh/rA9pn.jpg
http://puu.sh/rA9qy.jpg
#### What happens:

RS controller maxes out IC2 lower tier cabling and continues to void energy, even if the controller's buffer is full(as there's something else in the network using up RS, even if it is only 1RS/t)
#### What you expected to happen:

That EU input would be throttled to match the current use of RS*4 instead of maxing out the cable and voiding rest of the energy.
#### Steps to reproduce:
1. Fill an Energy Bank
2. Connect it with any tier of wire at and below the energy bank
3. Have your RS system use at least 1RS/t
#### Version (Make sure you are on the latest version before reporting):
- Minecraft: 1.10.2
- Forge:12.18.1.2095
- Refined Storage:1.1.2

Does this issue occur on a server? [yes/no]
Don't know, only found in single player
#### If a (crash)log is relevant for this issue, link it here:

No crashes!

**Comment by mister-man** [comment]
Hallo together,

Does this issue occur on a server? [yes/no]
yes

I testet it on a Sponge Forge Server as part of an Bungee network. Its the same error, The controller use the max power tier of the generator or the energie storage.

**Comment by granack** [comment]
This issue makes RS quite expensive with IC2 power.

**Possible workaround:** Give the controller its own eu storage (batbox if <=8 RF/t, cesu if 9-32 RF/t, etc) and accept a full power constant drain from it. Not pleasant.

**Comment by raoulvdberge** [comment]
I'm not quite sure what causes this... IC2 is a block box in lots of cases :P

**Comment by raoulvdberge** [comment]
This issue is no longer relevant for RS MC1.11 as we have no IC2 support there anymore
