### ISSUE TITLE
Client crash

### ISSUE THREAD

**Issue by zweris955** [raoulvdberge/refinedstorage#434]
#### Issue description:
Client crash
#### What happens:
Whenever I move my mouse cursor over these items my client crash.
![image](https://cloud.githubusercontent.com/assets/22690835/19206448/c85ec52a-8cf1-11e6-8f0a-185bf434546b.png)

My speculation would be that there is some deleted items from other mods and refined system do not delete them and when I try to look at it them I'm crashing

#### What you expected to happen:
To not crash

#### Steps to reproduce:
1. Make RS system to remove deleted items if that was the case.
2.
3.
...

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge: latest
- Refined Storage: latest

Does this issue occur on a server? [yes/no]
yes

#### If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here]

http://pastebin.com/xdd8MSvW

**Comment by raoulvdberge** [comment]
Does it happen when you just have the items in your inv as well?

**Comment by zweris955** [comment]
idk what item is that and I can't look at them they just sitting in rs system

**Comment by raoulvdberge** [comment]
They are Tinkers construct tool parts. Try exporting them out of your system and see if they crash in your regular inventory.

**Comment by zweris955** [comment]
they are not stone scythe head becouse they don't crash me when I'm crafting them

**Comment by zweris955** [comment]
I can't figure out any other tinker's tool part I made 44 times

**Comment by zweris955** [comment]
As I sad that could be deleted item from the mod

**Comment by raoulvdberge** [comment]
Please report this to Tinkers Construct
