### ISSUE TITLE
crafting/storage interaction

### ISSUE THREAD

**Issue by kurokuno** [raoulvdberge/refinedstorage#439]
when crafting from the Grid and inventory is full any chance of the items being stored inside of storage if there is room rather than just spitting on the ground =D

**Comment by raoulvdberge** [comment]
When using shift click, you mean?

**Comment by kurokuno** [comment]
yeah thats the one if you spam click items out of a grid and you're inventory fills up it starts spitting onto the ground once you're player inventory is full rather than refusing to craft or storing it internally

**Comment by raoulvdberge** [comment]
In the latest version, it doesn't drop stuff anymore when shift clicking *items* out of the grid. However, when *crafting with shift* it still does.
