### ISSUE TITLE
Items disappearing

### ISSUE THREAD

**Issue by MrTubzy456** [raoulvdberge/refinedstorage#44]
When you shift+left click+right click all at onceon an item in the system the items just vanish from the system. Don't ask me how he figured that out but I was able to replicate it and it does happen.

**Comment by raoulvdberge** [comment]
lol

**Comment by raoulvdberge** [comment]
I cannot reproduce this.

You mean shift pressing + left mouse click + right mouse click all at the same time, right?

**Comment by MrTubzy456** [comment]
Yeah, all three at the same time, while trying to pull an item out. It took me a try or two but I did get it to reproduce.

**Comment by raoulvdberge** [comment]
Thanks for reporting, managed to reproduce it :P

There was clientside protection built for the bug you got but not serverside, thats why it only happened rarely.
