### ISSUE TITLE
Server crash during large crafting operation

### ISSUE THREAD

**Issue by brad18** [raoulvdberge/refinedstorage#443]
#### Issue description:
Server crash due to large crafting operation
#### What happens:
Set up a 10k tnt craft and the server crashed and won't reload
#### What you expected to happen:
Craft to complete
#### Steps to reproduce:
1.Start a 10k tnt craft
2.Crash
3.
...

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge: 12.18.1.2095
- Refined Storage:1.1.2

Does this issue occur on a server? [yes/no]
Yes
#### If a (crash)log is relevant for this issue, link it here:
[crash-2016-10-08_15.42.11-server.txt](https://github.com/raoulvdberge/refinedstorage/files/517938/crash-2016-10-08_15.42.11-server.txt)

Also since the server will now not load, do you know anyway of cancelling the task without reverting to a backup?

Thanks

**Comment by way2muchnoise** [comment]
Damn watchdog.... Guess we'll have to make it faster

**Comment by Darkere** [comment]
you can try deleting the controller that might help, or revert to a backup

Also, this won't get fixed as the crafting system is in the process of being reworked...

**Comment by brad18** [comment]
Yeah we had to revert to a backup. Hopefully the new crafting fixes it eventually.

**Comment by raoulvdberge** [comment]
I'll close this as this is irrelevant anyway with the new crafting system

**Comment by utoc** [comment]
Is this new system present in the current release?

**Comment by raoulvdberge** [comment]
Not yet
