### ISSUE TITLE
crash with chisel n bits 

### ISSUE THREAD

**Issue by ilordnightmarei** [raoulvdberge/refinedstorage#444]
#### Steps to reproduce:
1. type b then o crashes u
2.
3.
...

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge:2095
- Refined Storage:1.1.2

Does this issue occur on a server? [yes/no]
yes
#### If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here]
http://pastebin.com/jFqAD1Zs

**Comment by raoulvdberge** [comment]
Please report this to Chisel&Bits

**Comment by ilordnightmarei** [comment]
i sent it to both of u lol and ya ty
