### ISSUE TITLE
Can't Place Wireless Transmitter

### ISSUE THREAD

**Issue by SpeedCuber1** [raoulvdberge/refinedstorage#452]
#### Issue description:
Can't place wireless transmitter
#### What happens:
It won't let me place the wireless transmitter on any cable/machine
#### What you expected to happen:
It places properly
#### Steps to reproduce:
1.Build rs system
2.Place wireless transmitter
#### Version (Make sure you are on the latest version before reporting):
- Minecraft: 1.10.2
- Forge:
12.18.2.2098
- Refined Storage:
1.1.3
Does this issue occur on a server? [yes/no]

#### If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here]

**Comment by raoulvdberge** [comment]
You have to place it on a cable
