### ISSUE TITLE
Ex Nihilo Omnia and Ex Compression Issues

### ISSUE THREAD

**Issue by InkDragon** [raoulvdberge/refinedstorage#453]
#### Steps to reproduce:
1. Install both Refined storeage and Ex Nihilo Omnia(Ex compression is Optional)
2. Set up a crucible to generate lava, by placing it over a heat source and placing cobblestone within it. 
3. Set up a system to extract lava from the crucible with an importer into the refined storage system, note that no lava is moved into the system.

Test can also be done by adding Ex compression and using a wooden crucible and saplings. However as no heat is needed one can place the importer on the underside of the crucible as well.

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge: 1.10.2 - 12.18.2.2098
- Refined Storage: Refined Storage 1.1.3

Does this issue occur on a server? Unknown, only tested in SSP

**Comment by raoulvdberge** [comment]
Not an RS issue
