### ISSUE TITLE
autocraft does not work with chargeable items, for example, with Energy Tablet, Energy Cubes from Mekanism

### ISSUE THREAD

**Issue by KAHTOP** [raoulvdberge/refinedstorage#455]
#### Steps to reproduce:
1. Build Autocrafting system.
2. Make a pattern describing recipe of an Induction Provider Basic
3. Begin craft.

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge: 12.18.1.2094
- Refined Storage: 1.1.3

Does this issue occur on a server? [yes/no] yes

#### If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here]

![image](https://cloud.githubusercontent.com/assets/22776271/19283640/5bc47826-8ffb-11e6-9952-0882a44a66d2.png)

![image](https://cloud.githubusercontent.com/assets/22776271/19283669/747178c4-8ffb-11e6-8265-2ae70aaaac36.png)

**Comment by raoulvdberge** [comment]
already working on this for next release

**Comment by nosknut** [comment]
Hows it commig with the chargable crafting?
