### ISSUE TITLE
Pulling out a lot of items quickly gives me different items

### ISSUE THREAD

**Issue by MrTubzy456** [raoulvdberge/refinedstorage#46]
For example: I was grabbing a lot of stacks of dirt. I searched for dirt and started shift+clicking them into my inventory. When I was done I had been given a stack of diamonds and a stack of coralium.

**Comment by raoulvdberge** [comment]
Are you sorting based on quantity? If the dirt quantity gets lower, the dirt will shift to the right, which causes you to pick other items.

**Comment by MrTubzy456** [comment]
No, I always sort by name for that very reason actually.

**Comment by raoulvdberge** [comment]
Then this probably due to lag.
