### ISSUE TITLE
Processing patterns that are able to actually insert fluids in machines

### ISSUE THREAD

**Issue by raoulvdberge** [raoulvdberge/refinedstorage#461]

**Comment by dovahkiin4991** [comment]
just a question, is this being worked on? sorry to sound impaticent, but I'm just wondering, no offense intended.

**Comment by way2muchnoise** [comment]
Not currently as I have a lot of IRL stuff going on

**Comment by Saklad5** [comment]
Any update on this? Judging by the issues you’ve closed as duplicates of this, this request includes having fluids as autocrafting outputs.

Thermal Expansion would be a _lot_ less painful if you could tell Refined Storage how to use a damn Magma Crucible. I doubt it is the only mod that could use fluid crafting.

**Comment by raoulvdberge** [comment]
I have started working on this, it is scheduled for release in v1.6.1 (next release).

**Comment by raoulvdberge** [comment]
This has been implemented for v1.6.1! Documentation on how to use this will be coming to the wiki soon.
