### ISSUE TITLE
Servercrash while placing 64k Storage Blog.

### ISSUE THREAD

**Issue by mister-man** [raoulvdberge/refinedstorage#464]
#### Issue description:
If you place a 64k Storage Block, the Server crash.

#### What happens:
If you place a 64k Storage Block, the Server crash.

#### What you expected to happen:
-

#### Steps to reproduce:
1. Craft a 64k Storage Blog
2.Place it into your RS-System

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge: forge-1.10.2-12.18.2.2098-universal
- Refined Storage: refinedstorage-1.1.3

Does this issue occur on a server? [yes/no]
yes, Sponge (spongeforge-1.10.2-2098-5.0.0-BETA-1788)

#### If a (crash)log is relevant for this issue, link it here:
-

**Comment by raoulvdberge** [comment]
where is your crashlog?

**Comment by mister-man** [comment]
I try to find it today,  on the server is Industrialcraft 2 installed with an logging error. So the log file is 30 GB big. My Tablet can't handle it,  so I post the log next time at my computer.

**Comment by raoulvdberge** [comment]
Please don't post the 30GB, just send the actual crash log

**Comment by raoulvdberge** [comment]
I'll close the issue, if you have the log, feel free to post and I'll take a look.
