### ISSUE TITLE
Failure to find resources to continue a crafting/processing chain

### ISSUE THREAD

**Issue by jtb1313** [raoulvdberge/refinedstorage#466]
#### Issue description:
When I attempt to use the auto crafting feature to craft steel ingots from Mekanism it refuses to see resources that were just processed (in a batch of 8) to continue the chain to smelt the ingots

#### What happens:
when processing products are returned to the RS system weather it be one by one are all at once the system does not see that the items are now there

#### What you expected to happen:
I ask for steel ingots and one compressed carbon and 8 iron enter the Metallurgic Infuser and get processed to be enriched iron then are placed in a chest then into the RS system via an importer.  then one compressed carbon and eight enriched iron enter the Metallurgic Infuser and get processed to be Steel Dust that goes back into the RS system and then the steel dust goes into a smeltery and back into the system.

#### Steps to reproduce:
1.See above

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge: 12.18.2.2099
- Refined Storage: 1.1.3

Does this issue occur on a server? Unknown, probably

**Comment by raoulvdberge** [comment]
fixed in dev

**Comment by jtb1313** [comment]
cool, now I have to go bug the Mekanism dev because the thermal evaporation tower locks up my game :/
