### ISSUE TITLE
crashes when opening inventory tab in creative

### ISSUE THREAD

**Issue by Mulakulu** [raoulvdberge/refinedstorage#467]
#### Issue description:
"read title"
#### What happens:
the game crashes when I attempt to find refined storage items
#### What you expected to happen:
that I can see refined storage items
#### Steps to reproduce:
1.open your creative inventory
2.click on the "refined storage" tab
3.crashes the game
...

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge:
- Refined Storage:

Does this issue occur on a server? [yes/no]
I don't know, haven't checked
#### If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here]

**Comment by raoulvdberge** [comment]
crash log please!!!!!!!!!!!!!

**Comment by Mulakulu** [comment]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  ShetiPhian-ASM (shetiphiancore-1.10.0-3.3.1.jar)
  CodeChickenCorePlugin (CodeChickenCore-1.10.2-2.2.1.80-universal.jar)
  LoadingPlugin (RandomThings-MC1.10.2-3.7.6.jar)
  EnderCorePlugin (EnderCore-1.10.2-0.4.1.56-beta (1).jar)
  CCCDeobfPlugin (unknown)
  CCLCorePlugin (CodeChickenLib-1.10.2-2.3.1.88-universal.jar)
Contact their authors BEFORE contacting forge

// I let you down. Sorry :(

Time: 10/15/16 4:28 PM
Description: Updating screen events

java.lang.IllegalAccessError: tried to access field net.minecraft.item.ItemStack.field_77990_d from class cofh.api.energy.ItemEnergyContainer
	at cofh.api.energy.ItemEnergyContainer.receiveEnergy(ItemEnergyContainer.java:66)
	at refinedstorage.item.ItemWirelessGrid.func_150895_a(ItemWirelessGrid.java:96)
	at net.minecraft.creativetab.CreativeTabs.func_78018_a(CreativeTabs.java:289)
	at net.minecraft.client.gui.inventory.GuiContainerCreative.func_147050_b(GuiContainerCreative.java:450)
	at net.minecraft.client.gui.inventory.GuiContainerCreative.func_146286_b(GuiContainerCreative.java:427)
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:558)
	at net.minecraft.client.gui.inventory.GuiContainerCreative.func_146274_d(GuiContainerCreative.java:539)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:517)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1700)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1055)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at cofh.api.energy.ItemEnergyContainer.receiveEnergy(ItemEnergyContainer.java:66)
	at refinedstorage.item.ItemWirelessGrid.func_150895_a(ItemWirelessGrid.java:96)
	at net.minecraft.creativetab.CreativeTabs.func_78018_a(CreativeTabs.java:289)
	at net.minecraft.client.gui.inventory.GuiContainerCreative.func_147050_b(GuiContainerCreative.java:450)
	at net.minecraft.client.gui.inventory.GuiContainerCreative.func_146286_b(GuiContainerCreative.java:427)
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:558)
	at net.minecraft.client.gui.inventory.GuiContainerCreative.func_146274_d(GuiContainerCreative.java:539)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:517)

-- Affected screen --
Details:
	Screen name: net.minecraft.client.gui.inventory.GuiContainerCreative

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['Mulakulu'/27, l='MpServer', x=1104.17, y=56.00, z=-445.86]]
	Chunk stats: MultiplayerChunkCache: 254, 254
	Level seed: 0
	Level generator: ID 01 - flat, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (960,4,-501), Chunk: (at 0,0,11 in 60,-32; contains blocks 960,0,-512 to 975,255,-497), Region: (1,-1; contains chunks 32,-32 to 63,-1, blocks 512,0,-512 to 1023,255,-1)
	Level time: 6209 game time, 6209 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 29 total; [EntityVillager['Villager'/3, l='MpServer', x=1068.39, y=56.00, z=-465.31], EntityVillager['Villager'/4, l='MpServer', x=1057.50, y=57.00, z=-453.95], EntityVillager['Villager'/5, l='MpServer', x=1057.49, y=57.00, z=-453.05], EntityVillager['Villager'/6, l='MpServer', x=1071.50, y=55.94, z=-459.30], EntityVillager['Villager'/7, l='MpServer', x=1060.60, y=56.00, z=-448.52], EntityVillager['Villager'/8, l='MpServer', x=1057.65, y=57.00, z=-457.33], EntityVillager['Villager'/9, l='MpServer', x=1057.50, y=57.00, z=-394.50], EntityVillager['Villager'/10, l='MpServer', x=1071.67, y=57.00, z=-399.23], EntityVillager['Villager'/11, l='MpServer', x=1075.58, y=56.35, z=-471.50], EntityVillager['Villager'/12, l='MpServer', x=1082.29, y=56.00, z=-449.57], EntityVillager['Villager'/13, l='MpServer', x=1084.28, y=56.00, z=-443.74], EntityVillager['Villager'/14, l='MpServer', x=1081.51, y=56.00, z=-413.67], EntityVillager['Villager'/15, l='MpServer', x=1077.50, y=56.00, z=-401.50], EntityVillager['Villager'/16, l='MpServer', x=1088.34, y=56.94, z=-469.32], EntityVillager['Villager'/17, l='MpServer', x=1090.53, y=56.00, z=-454.31], EntitySquid['Squid'/18, l='MpServer', x=1092.99, y=47.65, z=-427.60], EntitySquid['Squid'/19, l='MpServer', x=1092.31, y=46.69, z=-426.40], EntitySquid['Squid'/20, l='MpServer', x=1092.38, y=55.61, z=-427.23], EntitySquid['Squid'/21, l='MpServer', x=1093.60, y=56.59, z=-427.57], EntityVillager['Villager'/22, l='MpServer', x=1089.53, y=57.00, z=-422.36], EntityVillager['Villager'/23, l='MpServer', x=1089.56, y=57.00, z=-408.50], EntityVillager['Villager'/24, l='MpServer', x=1095.50, y=57.00, z=-402.68], EntityVillager['Villager'/25, l='MpServer', x=1094.61, y=56.00, z=-411.51], EntityVillager['Villager'/26, l='MpServer', x=1095.74, y=56.00, z=-386.71], EntityHorse['Horse'/29, l='MpServer', x=1183.13, y=56.00, z=-505.94], EntityPig['Pig'/30, l='MpServer', x=1181.52, y=56.00, z=-481.45], EntityPig['Pig'/31, l='MpServer', x=1175.43, y=56.00, z=-480.75], EntityPig['Pig'/36, l='MpServer', x=1175.35, y=56.00, z=-486.45], EntityPlayerSP['Mulakulu'/27, l='MpServer', x=1104.17, y=56.00, z=-445.86]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:415)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2660)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:392)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.10.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1426482752 bytes (1360 MB) / 2449870848 bytes (2336 MB) up to 8589148160 bytes (8191 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx8G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn8M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.32 Powered by Forge 12.18.2.2099 22 mods loaded, 22 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.10.2-12.18.2.2099.jar) 
	UCHIJAAAA	Forge{12.18.2.2099} [Minecraft Forge] (forge-1.10.2-12.18.2.2099.jar) 
	UCHIJAAAA	CodeChickenCore{2.2.1.80} [CodeChicken Core] (minecraft.jar) 
	UCHIJAAAA	chisel{MC1.9.4-0.0.6.33} [Chisel] (Chisel-Mod-1.10.2.jar) 
	UCHIJAAAA	endercore{1.10.2-0.4.1.56-beta} [EnderCore] (EnderCore-1.10.2-0.4.1.56-beta (1).jar) 
	UCHIJAAAA	JEI{3.12.6.304} [Just Enough Items] (jei_1.10.2-3.12.6.304.jar) 
	UCHIJAAAA	Waila{1.7.0} [Waila] (Waila-1.7.0-B3_1.9.4.jar) 
	UCHIJAAAA	EnderIO{1.10.2-3.0.1.120_beta} [Ender IO] (EnderIO-1.10.2-3.0.1.120_beta.jar) 
	UCHIJAAAA	EnderStorage{2.1.4.78} [EnderStorage] (EnderStorage-1.10.2-2.1.4.78-universal.jar) 
	UCHIJAAAA	shetiphiancore{3.3.1} [ShetiPhian-Core] (shetiphiancore-1.10.0-3.3.1.jar) 
	UCHIJAAAA	endertanks{1.4.2} [EnderTanks] (endertanks-1.10.0-1.4.2.jar) 
	UCHIJAAAA	zerocore{1.10.2-0.0.8.0} [Zero CORE] (zerocore-1.10.2-0.0.8.0.jar) 
	UCHIJAAAA	bigreactors{0.4.5.17} [Extreme Reactors] (ExtremeReactors-1.10.2-0.4.5.17.jar) 
	UCHIJAAAA	mantle{1.10.2-1.0.0.jenkins170} [Mantle] (Mantle-1.10.2-1.0.0.jar) 
	UCHIJAAAA	randomthings{3.7.6} [Random Things] (RandomThings-MC1.10.2-3.7.6.jar) 
	UCHIJAAAA	mcmultipart{1.2.1} [MCMultiPart] (MCMultiPart-1.2.1-universal.jar) 
	UCHIJAAAA	refinedstorage{1.1.3} [Refined Storage] (refinedstorage-1.1.3.jar) 
	UCHIJAAAA	rftools{5.53} [RFTools] (rftools-1.10-5.53.jar) 
	UCHIJAAAA	rftoolsdim{4.42} [RFTools Dimensions] (rftoolsdim-1.10-4.42.jar) 
	UCHIJAAAA	tconstruct{1.10.2-2.5.5.jenkins393} [Tinkers' Construct] (TConstruct-1.10.2-2.5.5.jar) 
	UCHIJAAAA	XaeroMinimap{1.10.9} [Xaero's Minimap] (Xaeros_Minimap_1.10.9_Forge_1.10.2.jar) 
	Loaded coremods (and transformers): 
ShetiPhian-ASM (shetiphiancore-1.10.0-3.3.1.jar)
  shetiphian.core.asm.ClassTransformer
CodeChickenCorePlugin (CodeChickenCore-1.10.2-2.2.1.80-universal.jar)
  codechicken.core.asm.TweakTransformer
  codechicken.core.asm.DelegatedTransformer
  codechicken.core.asm.DefaultImplementationTransformer
LoadingPlugin (RandomThings-MC1.10.2-3.7.6.jar)
  lumien.randomthings.asm.ClassTransformer
EnderCorePlugin (EnderCore-1.10.2-0.4.1.56-beta (1).jar)
  com.enderio.core.common.transform.EnderCoreTransformer
CCCDeobfPlugin (unknown)
  
CCLCorePlugin (CodeChickenLib-1.10.2-2.3.1.88-universal.jar)
  codechicken.lib.asm.ClassHeirachyManager
  codechicken.lib.asm.RenderHookTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 369.09' Renderer: 'GeForce GTX 560 Ti/PCIe/SSE2'
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
		- WailaIntegration (Enabled/Not Forced)

	CodeChickenCore: ignoreInvalidMCVersion state: false
	EnderIO: Found the following problem(s) with your installation (That does NOT mean that Ender IO caused the crash or was involved in it in any way. We add this information to help finding common problems, not as an invitation to post any crash you encounter to Ender IO's issue tracker. Always check the stack trace above to see which mod is most likely failing.):
                  * The RF API that is being used has no API annotation. This may lead to problems.
                 This may (look up the meaning of 'may' in the dictionary if you're not sure what it means) have caused the error. Try reproducing the crash WITHOUT this/these mod(s) before reporting it.
	Detailed RF API diagnostics:
                  * RF API class 'EnergyStorage' is loaded from: jar:file:/C:/Users/Mulakulu/AppData/Roaming/.minecraft/mods/extrautilities-1.2.12%20(1).jar!/cofh/api/energy/EnergyStorage.class
                  * RF API class 'IEnergyConnection' is loaded from: jar:file:/C:/Users/Mulakulu/AppData/Roaming/.minecraft/mods/extrautilities-1.2.12%20(1).jar!/cofh/api/energy/IEnergyConnection.class
                  * RF API class 'IEnergyContainerItem' is loaded from: jar:file:/C:/Users/Mulakulu/AppData/Roaming/.minecraft/mods/extrautilities-1.2.12%20(1).jar!/cofh/api/energy/IEnergyContainerItem.class
                  * RF API class 'IEnergyHandler' is loaded from: jar:file:/C:/Users/Mulakulu/AppData/Roaming/.minecraft/mods/extrautilities-1.2.12%20(1).jar!/cofh/api/energy/IEnergyHandler.class
                  * RF API class 'IEnergyProvider' is loaded from: jar:file:/C:/Users/Mulakulu/AppData/Roaming/.minecraft/mods/extrautilities-1.2.12%20(1).jar!/cofh/api/energy/IEnergyProvider.class
                  * RF API class 'IEnergyReceiver' is loaded from: jar:file:/C:/Users/Mulakulu/AppData/Roaming/.minecraft/mods/extrautilities-1.2.12%20(1).jar!/cofh/api/energy/IEnergyReceiver.class
                  * RF API class 'IEnergyStorage' is loaded from: jar:file:/C:/Users/Mulakulu/AppData/Roaming/.minecraft/mods/extrautilities-1.2.12%20(1).jar!/cofh/api/energy/IEnergyStorage.class
                  * RF API class 'ItemEnergyContainer' is loaded from: jar:file:/C:/Users/Mulakulu/AppData/Roaming/.minecraft/mods/extrautilities-1.2.12%20(1).jar!/cofh/api/energy/ItemEnergyContainer.class
                  * RF API class 'TileEnergyHandler' is loaded from: jar:file:/C:/Users/Mulakulu/AppData/Roaming/.minecraft/mods/extrautilities-1.2.12%20(1).jar!/cofh/api/energy/TileEnergyHandler.class
	Detailed Tesla API diagnostics:
                  * Tesla API class 'Tesla' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.Tesla)
                  * Tesla API class 'TeslaCapabilities' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.capability.TeslaCapabilities)
                  * Tesla API class 'ITeslaConsumer' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.ITeslaConsumer)
                  * Tesla API class 'ITeslaHolder' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.ITeslaHolder)
                  * Tesla API class 'ITeslaProducer' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.ITeslaProducer)
                  * Tesla API class 'BaseTeslaContainer' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.implementation.BaseTeslaContainer)
                  * Tesla API class 'BaseTeslaContainerProvider' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.implementation.BaseTeslaContainerProvider)
                  * Tesla API class 'InfiniteTeslaConsumer' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.implementation.InfiniteTeslaConsumer)
                  * Tesla API class 'InfiniteTeslaConsumerProvider' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.implementation.InfiniteTeslaConsumerProvider)
                  * Tesla API class 'InfiniteTeslaProducer' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.implementation.InfiniteTeslaProducer)
                  * Tesla API class 'InfiniteTeslaProducerProvider' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.implementation.InfiniteTeslaProducerProvider)

	Launched Version: 1.10.2-forge1.10.2-12.18.2.2099
	LWJGL: 2.9.4
	OpenGL: GeForce GTX 560 Ti/PCIe/SSE2 GL version 4.5.0 NVIDIA 369.09, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 4x AMD A10-7870K Radeon R7, 12 Compute Cores 4C+8G

is this what you mean?

**Comment by way2muchnoise** [comment]
Yes and you are using a XU version for 1.7.10. That is your issue.

**Comment by Mulakulu** [comment]
XU?

**Comment by Mulakulu** [comment]
what do you mean by XU?

**Comment by Mulakulu** [comment]
oh, extra utileties, right. just a sec

**Comment by Mulakulu** [comment]
it worked now. thank you so much way2muchnoice :)
