### ISSUE TITLE
Missing explosion parameters

### ISSUE THREAD

**Issue by LemADEC** [raoulvdberge/refinedstorage#469]
#### Issue description:
Missing explosion parameters
#### What happens:
Explosions happens without a warning nor way to control their range.

#### What you expected to happen:
Configuration parameters to adjust the strength of explosion, eventually disable it.

#### Steps to reproduce:
1.
2.
3.
...

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge: Forge Mod Loader version 12.18.1.2095
- Refined Storage: refinedstorage-1.1.2

Does this issue occur on a server? both

#### If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here]

**Comment by raoulvdberge** [comment]
No, you can't disable explosions. Multiple controllers on the same network cause buggy behavior.

**Comment by LemADEC** [comment]
so I guess blowing all your storage and loosing all your stuff because of a misplaced controller is normal for you?

**Comment by LemADEC** [comment]
you could at least put some explosion resistance on the drive blocks

**Comment by raoulvdberge** [comment]
storage disks and storage blocks no longer despawn when in item form in the world

**Comment by LemADEC** [comment]
as of 1.1.2 there's no item drops when it explodes
