### ISSUE TITLE
Using ExtraUtils 2 Trash Can as external storage displays invalid number of items

### ISSUE THREAD

**Issue by LepkoQQ** [raoulvdberge/refinedstorage#470]
#### Issue description:
Using ExtraUtils 2 Trash Can as external storage displays invalid number of items until you try to pull some of the items out of the RS system

#### What happens:
I was using a Storage Drawer and an ExtraUtils 2 Trash Can as an external storage to basically void excess items when the drawer fills up. The problem is if you add more items in the grid and they are inserted in the trash can the item count goes up even though the items are not accessible back from the trash can for obvious reasons. If you try to pull the items back out from the grid the item count correctly recalculates.

#### What you expected to happen:
The item count should not count the items that are inserted in to the trash can.

#### Steps to reproduce:
1. storage drawer full of cobblestone as external storage priority 1
2. trash can as external storage priority 0
3. insert cobble in to the grid
4. the item count goes up even tho the cobble is voided in the trash can
5. when you try to pull the cobble out from the grid the count is corrected

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge: 12.18.2.2099
- Refined Storage: 1.1.3

#### Does this issue occur on a server?
yes

**Comment by raoulvdberge** [comment]
Fixed in #478
