### ISSUE TITLE
Detector Outputs Constantly After 117 Items as Amount

### ISSUE THREAD

**Issue by cjburkey01** [raoulvdberge/refinedstorage#473]
#### Issue description:
When looking inside of the Detector block, and it is set to output when below, and the value typed in is 118 or larger, it constantly outputs a signal.  At 117, it outputs based on contents, but at 118, it doesn't stop.

#### What happens:
Even if 1k items are in the system it will output as if it were below 118.

#### What you expected to happen:
The signal was supposed to turn off at 118, but only works on 117 and below.

#### Steps to reproduce:
1. [**THIS**](http://i.imgur.com/OjkSdu5.png) image shows my setup, below the solderers are import buses.  In front of them are export buses for each type of printed processor.  (Plain text link: http://i.imgur.com/OjkSdu5.png)

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge: 12.18.1.2095
- Refined Storage: 1.1.3

Does this issue occur on a server? **yes**

#### If a (crash)log is relevant for this issue, link it here:
Naw

**Comment by raoulvdberge** [comment]
show the detector gui please

**Comment by cjburkey01** [comment]
![2016-10-16_13 21 30](https://cloud.githubusercontent.com/assets/9255643/19419357/cabb38a4-93a3-11e6-988d-6b8b8f1aa5c0.png)
I've also noticed it seems to emit a redstone signal even if it's set to 117, but the torch looks like it's turned off.

**Comment by raoulvdberge** [comment]
I can't reproduce this on the betas anymore.
