### ISSUE TITLE
External storage too slow transferring items

### ISSUE THREAD

**Issue by th4umiel** [raoulvdberge/refinedstorage#474]
#### Issue description:
Basically what the title says.
#### What happens:
I have a RFTools quarry, connected to an Ender Chest connected to the RS network (interface) through 3 EnderIo item conduit with maxed out speed upgrades. When the network has to move cobble to the external storage is incredibly slow, clogging the quarry and the network itself, because the excess cobble is stuck in the interface slots.
#### What you expected to happen:
The transfer to the external storage should be immediate, pretty much like the transfer of the items in a normal storage disk (like ae2 used to do)
#### Steps to reproduce:
1. select an external storage and connect it to the network 
2. transfer large quantities of items to RS network via interface
3. The tems clog the interface and the external storage is too slow to handle the transfer 
...

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge:12.18.1.2095
- Refined Storage: 1.1.3

Does this issue occur on a server? [yes/no] Don't know

#### If a (crash)log is relevant for this issue, link it here:
No crashlog necessary
[pastebin/gist/etc link here]

**Comment by raoulvdberge** [comment]
Ummm, the external storage is instant. I think your **importer** from quarry to system is the bottleneck. Did you add speed + stack upgrades?

**Comment by th4umiel** [comment]
To the interface you mean? No, I try it now. But I can't really follow: basically are you saying that the slow speed of the transfer to the external storage is determined by the interface transfer speed?

**Comment by raoulvdberge** [comment]
Yes, because the interface is the block that inserts stuff to your system, not the ext storage.

**Comment by th4umiel** [comment]
Thanks a lot, it works, and sorry for the dumb question :)

**Comment by tomasdev** [comment]
Stack upgrades and Speed Upgrades worked like a charm ! thanks
