### ISSUE TITLE
java.lang.NoSuchFieldError: VARINT

### ISSUE THREAD

**Issue by Shadowhunter82** [raoulvdberge/refinedstorage#479]
#### Issue description:
Client crash during mod loading on Client and Server

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge: 12.18.2.2099
- Refined Storage: 1.2-326

Does this issue occur on a server? [yes/no]
Client and Server
#### If a (crash)log is relevant for this issue, link it here:
http://pastebin.com/FBJXid1d
[pastebin/gist/etc link here]

**Comment by raoulvdberge** [comment]
That is because the builds on Bintray currently work in a non-obf environment. We'll fix this in the future
