### ISSUE TITLE
server crash: java.lang.NullPointerException: Exception while updating neighbours

### ISSUE THREAD

**Issue by PlacidK** [raoulvdberge/refinedstorage#48]
Servercrash after 0.6 update

crash report --> http://pastebin.com/PPJpJLV1

**Comment by raoulvdberge** [comment]
You got this error as soon as you loaded the world with 0.6?

**Comment by raoulvdberge** [comment]
I'll be publishing 0.6.1 that fixes this issue now.

**Comment by raoulvdberge** [comment]
Fixed in 0.6.1

**Comment by PlacidK** [comment]
Thnx, i'll check after work.
