### ISSUE TITLE
AE2 integration

### ISSUE THREAD

**Issue by raoulvdberge** [raoulvdberge/refinedstorage#481]
Connecting an ext storage to an AE2 interface will give access to your AE inventory from RS.

The other way round too, connecting a AE2 storage bus should give access to your RS items from AE2.

**Comment by Wii505** [comment]
Will that integration include AE2's fluid inventory that Extra Cells 2 adds?

**Comment by raoulvdberge** [comment]
Probably not. Maybe.

**Comment by TheUnderTaker11** [comment]
Still waiting for the feature, was just googling around to find if this was possible, since I want to use Refined storage for everything, but then be able to use the wireless crafting terminal to access the storage from anywhere.

**Comment by raoulvdberge** [comment]
AE2 is still alpha.

**Comment by TheUnderTaker11** [comment]
Sorry if I made that seem like a "Come on do it now!" type comment, I was just trying to point out that it isn't something that should be forgotten since there is still a desire for this type of thing. I know I would forget or not bother to do stuff like this all the time, especially if it didn't seem like many/any people wanted it.

**Comment by raoulvdberge** [comment]
This can be added only if AE2 goes out of alpha, since API changes may still happen

**Comment by SpeedySpy52** [comment]
In that case, are there any plans to improve the wireless grids? The short range of 48 blocks for the transmitter seems pretty useless, especially compared to AE2's wireless.

**Comment by raoulvdberge** [comment]
What are you talking about?

1) You are supposed to spread multiple transmitters over your world, not just one
2) You can increase the range in the configs

**Comment by raoulvdberge** [comment]
Not gonna happen anymore

**Comment by raoulvdberge** [comment]
Not needed anymore. In 1.12 you can just connect an AE bus to an RS interface.

**Comment by Joshwoo70** [comment]
1.12??

**Comment by raoulvdberge** [comment]
Well, if AE for 1.12 ever comes out.

**Comment by Norway174** [comment]
I'm guessing this won't work in 1.10.2 FTB Beyond? Just tried connecting the AE Storage Bus to an RS Interface.

It doesn't give me access to my RS storage. It seems to be using the RS Interface as the storage itself. And I can manually specify a few items to be kept in there, which RS will then keep supplying.

Is that the intended feature? Or is there a way to get access to all the items in the RS network trough AE?

**Comment by raoulvdberge** [comment]
I did say this is for 1.12.

**Comment by Norway174** [comment]
Ah, okay. Thanks for the confirmation.

**Comment by AgentA1cr** [comment]
That works to allow AE2 to access RS, but it doesn't seem to be working the other way around for me. I'm using the latest versions that are on curseforge of both mods.

**Comment by raoulvdberge** [comment]
That's not an RS problem.

**Comment by Prygrama185** [comment]
So... is it going to be added?

**Comment by raoulvdberge** [comment]
No

**Comment by Unjustifiable** [comment]
So, technically speaking, AE2 AND Refined Storage can work together without you guys having to change code?
