### ISSUE TITLE
[BUG?]Grid DO NOT support Chinese search

### ISSUE THREAD

**Issue by TartaricAcid** [raoulvdberge/refinedstorage#482]
#### Issue description:  
When I use grid to search items, I find that I can't type any Chinese in search bar.

#### What you expected to happen:
The grid can support Chinese to search items.

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge: 12.18.2.2099
- Refined Storage: 1.1.3

**Comment by raoulvdberge** [comment]
I can't reproduce this.

![x](https://raoulvdberge.com/bv67XL)
