### ISSUE TITLE
Suggestion: JEI Support for Uses and Recipes while in the Terminal.

### ISSUE THREAD

**Issue by KaneHart** [raoulvdberge/refinedstorage#484]
Would be nice we could use the U/R keys while inside the Terminal. It's really annoying to have to pull items out to see what recipes or usages they have.

Thanks :)

**Comment by InusualZ** [comment]
You could use JEI Syncronized search and use those shortcut in the JEI "View"

**Comment by raoulvdberge** [comment]
This will require a change in JEI, it's on their roadmap.

mezz/JustEnoughItems/issues/536
