### ISSUE TITLE
Blocking autocrafting mode

### ISSUE THREAD

**Issue by raoulvdberge** [raoulvdberge/refinedstorage#485]

**Comment by Nonsanity** [comment]
I'd like to give my hypothetical votes to this feature. There are many mods that have unique crafting mechanics (Botania, Actually Additions, Thaumcraft, Witchery, etc) where processing has to happen one batch at a time. Attempting to add more than one recipe's worth of ingredients spoils the craft.

I've been trying to think up a work-around all evening for Botania, and it is getting more and more complicated—and it's still not there yet. I miss this feature of AE, and I'm glad you yourself added this feature request... so you must know how important it is. :)

**Comment by Ellpeck** [comment]
MAKE THIS HAPPEN RIGHT NOW

**Comment by raoulvdberge** [comment]
#785
