### ISSUE TITLE
Limit power on network transmitters

### ISSUE THREAD

**Issue by masterX244** [raoulvdberge/refinedstorage#487]
Currently the controller has a limit of 32k rf/tick with its internal buffer so you got a limit on the long distance links you could set up. a block that would act like the AE1 power relay

**Comment by choekstr** [comment]
Are you really reaching the upper limit of the power input?  Why don't you use the network transmitter and receiver.  IIRC it has a max of 1k rf/t, even goes inter-dimensional, and would cut down on very long runs and the power that it takes.  Or is your base and network that big that you need all those cables connected to machines?

**Comment by masterX244** [comment]
The 1k limit seems to only apply on interdimensional transmits . Got a 2k block distance one without and usage was 7,5k.

**Comment by raoulvdberge** [comment]
I'll  limit the power to 1K
