### ISSUE TITLE
Autocrafting with certain processing patterns causes too many prerequisites to be made

### ISSUE THREAD

**Issue by momerathe** [raoulvdberge/refinedstorage#488]
#### Issue description:

If I have a crafting set up where one of the steps is a processing pattern that has produced more than one item, that processing pattern will be executed too many times.

#### What happens/Steps to reproduce:
For example, suppose I want to craft Mekanism speed upgrades; I have a crafting pattern with this recipe. Each one requires one Energized Alloy. For efficiency purposes it's best to craft Mekanism alloys in batches of 8, so I have a processing pattern that says "1 Compressed Redstone + 8 iron = 8 Energized Alloy"

Now, suppose I ask for 8 speed upgrades. The confirmation screen correctly says 8 alloys to craft. However, when executing the recipe, the Energized Alloy recipe is executed *once per speed upgrade*, meaning that 64 energized alloys are crafted instead of 8.

#### What you expected to happen:

The pattern should only be executed once, because that's enough to satisfy the prerequisites for the whole job.

The problem gets exponentially worse the more steps you have. I asked for a stack of Basic Universal Cable, and if I hadn't realised what was going on the system would have crafted 8,192 energized iron, instead of 128.

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge: 1.10.2 - 12.18.2.2099
- Refined Storage: 1.1.3

Does this issue occur on a server? [yes/no]

Have not tested, only in singleplayer.

**Comment by yutang13** [comment]
So glad this is fixed! Literally have made the same thing and found out the same way (well actually through making steel).

I have also found the opposite problem where not enough glass was smelted for my speed upgrades.

**Comment by acidjazz** [comment]
release already!! so happy to see its fixed

**Comment by raoulvdberge** [comment]
We can't release yet, its not yet done.

**Comment by acidjazz** [comment]
@raoulvdberge oh, is that what indev means? in the process of fixing?

**Comment by raoulvdberge** [comment]
indev means it's fixed in the dev branch, but not yet released

**Comment by acidjazz** [comment]
can we just pull these fixes out for a patch release then @raoulvdberge ?

**Comment by way2muchnoise** [comment]
[A beta has been released like an hour ago](https://minecraft.curseforge.com/projects/refined-storage/files/2338804).

**Comment by yutang13** [comment]
Have you pulled down the beta or something?

The link gives me a file not found error and nothing new is showing up on the curse page since the 7th

**Comment by way2muchnoise** [comment]
@yutang13 yeah the beta got pulled due to really bad performance. Most of it has been fixed, a new beta will be out soon.
