### ISSUE TITLE
Larger item abbreviations.

### ISSUE THREAD

**Issue by yutang13** [raoulvdberge/refinedstorage#490]
When you have over 100k items the number of items overflows slightly. To have 0.1M is better than 100k IMO. A result M (million) B (billion) and T (trillion) labels should be implemented.

(Sorry if they are already present, can't be bothered to wait to have a million cobble to find out 😆)

**Comment by raoulvdberge** [comment]
Trillion isn't possible due to the integer limit. 1M already works, but I'll make it so it can display 0.1M too.

**Comment by yutang13** [comment]
Question:
So what would happen if I had over a billion items? At what point would something overflow when I have enough items?

**Comment by way2muchnoise** [comment]
Max signed integer would be an issue so: 2,147,483,647 (2 billion something)

**Comment by yutang13** [comment]
An interesting way to get around it would be to create a second "stack" of items when it reaches 2 billion. So if I had 3 billion cobble I'd see a 2B stack and a 1B stack in the grid.

**Comment by raoulvdberge** [comment]
What are the chances of you reaching more than a billion times though?

**Comment by yutang13** [comment]
Not impossible. :grin: cobble generators can be scaled up pretty well. Compacting storage drawers hold a lot of items. Works very well backwards, say I have a million iron blocks, that's 9 million ingots and 81 million nuggets. Super circuit maker adds tiny pile of redstone which is 1/9th of a redstone.

**Comment by raoulvdberge** [comment]
It won't be possible either way, even if I split them up. It still has to combine them. And RS uses MC itemstacks which have the integer limit.

**Comment by yutang13** [comment]
OK, thanks. I won't try to get over 2 billion cobble then 😛

**Comment by raoulvdberge** [comment]
I can probably make it so it doesn't overflow, and stays at INT_MAX.

**Comment by raoulvdberge** [comment]
There ^ It will no longer overflow and stay at the maximum value if you go over the limit.
