### ISSUE TITLE
TPS Cut in half when using external storage on Actually Additions small storage crates.

### ISSUE THREAD

**Issue by ProsperCraft** [raoulvdberge/refinedstorage#492]
With the setup in the attached picture the tps is cut in half.  When the controller is removed tps instantly jumps to 20.
![2016-10-21_17 25 11](https://cloud.githubusercontent.com/assets/4427684/19614845/25643722-97b6-11e6-98ca-20134d82fa21.png)
![2016-10-21_17 25 16](https://cloud.githubusercontent.com/assets/4427684/19614847/256515ca-97b6-11e6-8a5e-9885e4a6a3c0.png)
![2016-10-21_17 25 21](https://cloud.githubusercontent.com/assets/4427684/19614849/25698f2e-97b6-11e6-9b32-4bc313992931.png)
![2016-10-21_17 25 24](https://cloud.githubusercontent.com/assets/4427684/19614846/256482d6-97b6-11e6-8858-a2604ac59d94.png)
![2016-10-21_17 25 33](https://cloud.githubusercontent.com/assets/4427684/19614844/256357f8-97b6-11e6-8ee3-31729d504931.png)
![2016-10-21_17 25 39](https://cloud.githubusercontent.com/assets/4427684/19614848/2569adba-97b6-11e6-8095-072c82611d1e.png)
![2016-10-21_17 25 55](https://cloud.githubusercontent.com/assets/4427684/19614850/25716d5c-97b6-11e6-999b-c22e73b5bc83.png)
![2016-10-21_17 26 00](https://cloud.githubusercontent.com/assets/4427684/19614851/2572f0e6-97b6-11e6-9c07-0b2b8b9e8f70.png)

#### Version (Make sure you are on the latest version before reporting):  Unable to change version its in a modpack, but the latest version changelog doesn't show anything that would affect.

    Minecraft: 1.10.2
    SpongeAPI: 6.0.0-SNAPSHOT-cebc736
    SpongeForge: 1.10.2-2098-6.0.0-BETA-1823
    Minecraft Forge: 12.18.2.2099

- Refined Storage: refinedstorage-1.1.2

Does this issue occur on a server? Yes

Find also attached the warmroast showing a profile of the problem.
![refinedstoragewarmroast](https://cloud.githubusercontent.com/assets/4427684/19614860/3fe43ce6-97b6-11e6-8eb8-aa4c2a7afe59.png)

**Comment by bloodmc** [comment]
@ProsperCraft Does this issue occur WITHOUT Sponge? Make sure you test that.

**Comment by ProsperCraft** [comment]
Verified its not only Sponge - With Sponge-
![2016-10-22_12 59 30](https://cloud.githubusercontent.com/assets/4427684/19622016/c43ef386-985c-11e6-8fd9-1e89fca0caf0.png)

WIthout Sponge-
![2016-10-22_12 59 08](https://cloud.githubusercontent.com/assets/4427684/19622018/d1b7103e-985c-11e6-8544-9a9ec34bddb4.png)

**Comment by Zettt** [comment]
I'm here to report a similar issue. I'm also using external storages. However my are connected to a couple basic drawers. 

I had really bad lag in my world, and didn't know what caused it. Today I found out that I have the external storages connected to the drawers with a priority of 1, i.e. I wanted RS to store everything that comes into the system in the drawers instead of the disks. When I change the priority to 0, the lag goes away.
