### ISSUE TITLE
Opening Grid or Breaking Disk drive causes connection lost or game crash

### ISSUE THREAD

**Issue by Nathanxcollins** [raoulvdberge/refinedstorage#493]
#### Issue description:
When i try to access my disk drive to see the capacity, it will kick me, same thing if i break the block, and now it wont let me open the crafting grid 
#### What happens:
I get kicked from the game with a lost connection internal error:
#### What you expected to happen:
For my disk drive to open up 
#### Steps to reproduce:
Fill the RS system with with shields from zombie mob drops
2.disk drive with 2x 64k storage disks 1x 32k sotrage
3.break disk drive or
4.open disk drive
...

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge:1.38b
- Refined Storage: 1.1.3

Does this issue occur on a server? [yes/no]
Yes
#### If a (crash)log is relevant for this issue, link it here:
http://i.imgur.com/MQg0X7F.jpg
[pastebin/gist/etc link here]

**Comment by way2muchnoise** [comment]
Somerhing, something, we might need packet fragmentation.

**Comment by Darkere** [comment]
Try taking some stuff out of the drive. The items nbt data is too big. This happened to me when I accidently put 3 64k disk into another 64k disk.

**Comment by Nathanxcollins** [comment]
Server log
https://0x0.st/epK.log
Personal Crash Log
[crash-2016-10-26_08.23.45-client.txt](https://github.com/raoulvdberge/refinedstorage/files/553891/crash-2016-10-26_08.23.45-client.txt)

**Comment by Nathanxcollins** [comment]
I Figured out what caused it when I was scrolling through my second RS system and started trying to scroll through the section with shields it lagged so I started exporting them to a trash can and it resolved my issue

**Comment by raoulvdberge** [comment]
This can be fixed if MinecraftForge/MinecraftForge#3342 is merged
