### ISSUE TITLE
crash when searching in grid

### ISSUE THREAD

**Issue by d0wns3t** [raoulvdberge/refinedstorage#494]
#### Issue description: 

crash when searching in grid

#### What happens:

several keys, particularly "r" cause me to crash if i search for something in either the wireless or crafting grid

#### Steps to reproduce:
1. go into wireless gird
2. click in search field
3. press "r"
...

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge: 1.10.2-12.18.2.2107
- Refined Storage: 1.1.3

Does this issue occur on a server? [yes/no]

yes

#### If a (crash)log is relevant for this issue, link it here:

http://pastebin.com/n18vv54T

**Comment by momerathe** [comment]
This has been happening to me too - only in my case it's when I type "co"

**Comment by d0wns3t** [comment]
i just had it again from "b"

**Comment by way2muchnoise** [comment]
`net.blay09.mods.craftingtweaks.client.ClientProxy.onGuiKeyboardEvent(ClientProxy.java:93)`  
The issue seems to be with crafting tweaks.

**Comment by raoulvdberge** [comment]
@blay09

**Comment by blay09** [comment]
This was fixed a month ago already, update to Crafting Tweaks v6.1.16

**Comment by d0wns3t** [comment]
Disabled crafting tweaks and it worked, thankyou!

**Comment by d0wns3t** [comment]
Thankyou blay09 I will update crafting tweaks

**Comment by momerathe** [comment]
I don't have crafting tweaks installed. should I open a new ticket?

**Comment by raoulvdberge** [comment]
yes
