### ISSUE TITLE
IC2 Console Spam

### ISSUE THREAD

**Issue by lilmoefow** [raoulvdberge/refinedstorage#496]
#### Issue description:  
There is an ENet issue spamming the console causing the sevrer tps to dip slightly
#### What you expected to happen:  
It to not spam the console.
#### Steps to reproduce:
1. Not sure to be honest sorry, will Ask players on my server if any are using Refined Storage.  I didnt think any of them actually had Storage systems set up yet

#### Version (Make sure you are on the latest version before reporting):
- Minecraft: 1.10.2
- Forge: forge-1.10.2-12.18.2.2098-universal.jar
- Refined Storage: refinedstorage-1.1.3.jar
- IC2: industrialcraft-2-2.6.87-ex110.jar
- Sponge : spongeforge-1.10.2-2098-5.1.0-BETA-1814.jar (including this cause I am using it on my server)

Does this issue occur on a server? [yes/no]
Yes
#### If a (crash)log is relevant for this issue, link it here:

Not a crash log but a FML server log
https://gist.github.com/lilmoefow/8032533c48462c4b6e9be32e713324c2

**Comment by raoulvdberge** [comment]
Please report to IC2 as well, as I have no idea what could cause this

**Comment by lilmoefow** [comment]
Talked to Players on my server, and  Only one has a Refined Storage system set up and it is powered by Immersive Engineering's Water Wheels conected to Ender IO conduits..

**Comment by raoulvdberge** [comment]
This issue is no longer relevant for RS MC1.11 as we have no IC2 support there anymore

**Comment by lilmoefow** [comment]
Sorry, I forgot about this issue.  I have not noticed it happening as of late any how so that is fine by me.
