### ISSUE TITLE
item-of-doom causes grid to crash

### ISSUE THREAD

**Issue by momerathe** [raoulvdberge/refinedstorage#498]
#### Issue description:

~~Typing certain strings in the grid interface causes the client to crash. I keep running into new ones, but so far they include "co", "br", and "one"~~

After a bit more testing, it seems it's not typing the string - it's displaying a certain item on screen. I can repeat the crash just by scrolling the grid display down far enough. I can't work out of a way to remove the offending item.

#### What happens:

Game crashes.

#### What you expected to happen:

Not to crash.

#### Steps to reproduce:
1. open the grid
2. cause item-o-doom to display in the grid, either by searching or scrolling

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge: 1.10.2 - 12.18.2.2095
- Refined Storage: 1.1.3

Does this issue occur on a server? [yes/no]

Have not tested, only in singleplayer.

#### If a (crash)log is relevant for this issue, link it here:

http://pastebin.com/QFGsjmhC

**Comment by raoulvdberge** [comment]
This is a forestry issue, please report to them
