### ISSUE TITLE
[Feature Request] Crafting Satellites

### ISSUE THREAD

**Issue by zanges** [raoulvdberge/refinedstorage#500]
Basically, like in Logistics Pipes and maybe an advanced crafter to go with them.

**Comment by raoulvdberge** [comment]
Can you be more specific to what you are *exactly* suggesting?

**Comment by way2muchnoise** [comment]
And why you would be needing this?

**Comment by zanges** [comment]
In the recipe you could specify x items to go to the satellite and which satellite(by id) and then when you autocraft the item the specified items will go to the satellite instead of the crafter.

this would be useful for multiblock crafting and would eliminate the requirement of additional item transport to split crafting components in those cases.

**Comment by raoulvdberge** [comment]
Out of scope for RS
