### ISSUE TITLE
[Feature Request] Mod Sorting Mode in Grids

### ISSUE THREAD

**Issue by zanges** [raoulvdberge/refinedstorage#502]

**Comment by raoulvdberge** [comment]
You can use @ prefix for looking up mod items. If you want mod filter in the grid filters, that is already suggested.

**Comment by zanges** [comment]
I mean to allow sorting by mod name instead of name or amount.

so you have 3 options:
- Name
- Quantity
- Mod(Mod Name)

AE2 had the same sorting.
