### ISSUE TITLE
[Beta 1.2] Storage Drives Really Dark/Shadowed

### ISSUE THREAD

**Issue by cjburkey01** [raoulvdberge/refinedstorage#503]
#### Issue description:

The storage drives appear extremely shadowed, nearly black.

#### What happens:

When placing a storage drive next to a block in a Refined Storage system network, it appears really, really dark, but only if it is placed next to a block connected to the network.

#### What you expected to happen:

It should not be black.

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge: 12.18.1.2095
- Refined Storage:

Does this issue occur on a server? Yes, but it seems client side.

Here's an image:
![Image](http://i.imgur.com/cRocX7G.png)

**Comment by raoulvdberge** [comment]
Are you using optifine?

**Comment by cjburkey01** [comment]
Yes, I am, is that the issue?

**Comment by raoulvdberge** [comment]
Yes

**Comment by raoulvdberge** [comment]
Please report this to them, and link them this class (it's responsible for the disk rendering):

https://github.com/raoulvdberge/refinedstorage/blob/mc1.10/src/main/java/com/raoulvdberge/refinedstorage/render/BakedModelDiskDrive.java

**Comment by sp614x** [comment]
This may be related to https://github.com/sp614x/optifine/issues/298 and https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/2489

**Comment by raoulvdberge** [comment]
@sp614x would moving this stuff to a FastTESR fix it?
