### ISSUE TITLE
[Feature Request] Security

### ISSUE THREAD

**Issue by QuantumSheep** [raoulvdberge/refinedstorage#505]
Hi,

Can you add in future versions a security system? (Like AE2)?

Thanks,
Reguards,

**Comment by raoulvdberge** [comment]
I found the security system from AE2 pretty useless, as it doesn't protect anything

**Comment by QuantumSheep** [comment]
On little server, that's pretty useful to prevent robbers ;)

**Comment by raoulvdberge** [comment]
There are always ways to circumvent the security anyway
