### ISSUE TITLE
[1.2-beta2] Autocrafting 64k storage drive with pattern made in wrong machine. Cancel loses all materials.

### ISSUE THREAD

**Issue by RealGrep** [raoulvdberge/refinedstorage#507]
#### Issue description:
Using a pattern that should be made in the pattern grid, but was derpily made in the processing pattern encoder. Canceling the job when it halts with "No machine found" fails to return the significant amount of materials it has made up to then.

#### What happens:
Accidentally made the pattern for making a 64k storage drive in the processing pattern encoder (yeah, I know, derp). The materials are not in main storage at this point, but have been created and presumably removed for the next step. Clicking "Cancel" for it cancels it, but all materials it has made up to that point are not returned. Granted, strong element of user error here, but it probably shouldn't lose the materials and fail more gracefully, so I felt it worth reporting.

Seem to have another issue with it jamming up with normal crafting (not processing patterns), but I need to run and do some RL things. I think two simultaneous jobs using the same produced material are clashing, but I'll try and get a good test case and see if I can figure out what's going on later tonight.

#### What you expected to happen:
For it to return the materials it has produced up to that point, and optionally reach out of my computer and smack me upside the head for making the pattern in the wrong machine. lol

#### Steps to reproduce:
1. Make pattern like 64k storage drive one in processing pattern encoder instead of pattern grid, and feel stupid while doing so.
2. When it blocks with "No machine found", select job and click "Cancel".
3. Kiss goodbye to a lot of materials.

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge: 2107
- Refined Storage: 1.2-beta2

Does this issue occur on a server? [yes/no] Yes

**Comment by way2muchnoise** [comment]
They should have been inserted into what ever inventory was in front of your crafter. Could you add some screens of your setup?

**Comment by RealGrep** [comment]
Only an air block in front of the crafter.

https://www.dropbox.com/s/jyk3hibwsakvp1a/2016-10-25_14.10.11.png?dl=0

Which makes me wonder if it has no inventory to insert into for a processing pattern, if the items just get deleted.

**Comment by way2muchnoise** [comment]
Alright then the code I pushed fixes that. Now the task will just be stuck cause it can't do the processing :D

**Comment by RealGrep** [comment]
Thanks! Not a problem, I've cancelled them. Don't miss the materials. I'm at end game in the testing of this mod pack. I have tons of materials. XD
