### ISSUE TITLE
[1.2-beta2] Unexpected item duplication/amount increase after updating to beta2.

### ISSUE THREAD

**Issue by VT-14** [raoulvdberge/refinedstorage#511]
I would like to apologize in advance for not having the time to properly track the problem down right now.  I noticed this shortly before going to bed, and I'm working most of the day tomorrow.  I will be looking into this tomorrow night, unless the problem is found before then.

#### Issue description:
I updated to beta2 on a personal modpack earlier today.  After the update, I noticed I seemed to have significantly more of certain items than I expected  I assumed it was maybe an error from the update.  After playing a few more hours, I noticed that some items appeared to have duplicated.  Shortly before getting off for the night, I noticed that my storage was completely full (8 64x drives).  Before updating, I had only filled up the first drive and had made some progress on the second drive.

Before the update, I had been running an Extra Utilities 2 Quantum Quarry.  I would estimate that I had under 30k Iron Ingots, and the auto-processing line I had set up was quick enough to not have any significant backlog of dusts/powders/etc.

After updating, I noticed that I had far more dusts than I expected.  I turned off the quarry to stop ore income.  I think I had roughly 1k osmium and tin dusts at that time.

A few hours later, this is what was in my system:
![2016-10-24_23 31 36](https://cloud.githubusercontent.com/assets/12564251/19672444/892f8866-9a44-11e6-949f-0504e6f6353a.png)

In that picture, I would say that there is far too many Iron Ingots, Copper Ingots, Gold Ingots, Tin Ingots, Osmium Ingots, Osmium Dust/Powder (9.8K), maybe Nickel Grit (8.9K), Tin Dust/Powder (7.9K), and diamonds (2.3K)

On top of that, I am absolutely certain I should not have 2.8k Electrical Steel or 1.2K Flour.  I'm also doubtful that I would have 3.7K and 3.2K slime dirt, but I wasn't paying attention to the odds and ends the quarry picked up.

One of the reasons I don't have time to test random ideas I have is due to this being my current system:
![2016-10-24_23 33 04](https://cloud.githubusercontent.com/assets/12564251/19672621/3e4d0876-9a46-11e6-9c3c-ed52132ae339.png)

I think it's worth mentioning that all of the auto-processing of dusts and ingots go through interfaces (with 1 stack and 3 speed upgrades). The only things that wouldn't have gone through one of those are the slime dirt, leaves, and snow; and those might be from the Quarry and me not paying enough attention.

It's also worth mentioning that I ordered a few Electrical Steel Ingots, and manually tossed wheat in the SAG Mill (which dumps into that interface) to make flour earlier that day, so that is where I would/will start troubleshooting.

Also, a separate issue that you might be able to see in that picture: My RS system hasn't been pushing excess items into a Storage Drawers Drawer Controller to use the void upgrades in the individual drawers (via the External Storage, which is hidden from view in that picture).  I added the Exporter shortly before taking that picture to deal with the overflow in my system.  I assume you will want that to be a separate report (if I can reproduce it with only RS and SD, and it hasn't been reported already).

...

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge: 12.18.2.2111
- Refined Storage: 1.2-beta2
Lots of other mods.

Does this issue occur on a server?
Noticed on Survival Single Player

#### If a (crash)log is relevant for this issue, link it here:

Manual debug crash: https://gist.github.com/VT-14/05bc001780f9f33d073d1def6de85e8f
fml-client-latest.log: https://gist.github.com/VT-14/efa5acc5df513aac35947d7114827d3b

**Comment by raoulvdberge** [comment]
Are the itemcounts back to normal if you break + replace the controller?

**Comment by s11ence** [comment]
I use one interface with one stack upgrade and three speed upgrades. The stack upgrade makes it so that the interface takes the one item i give it and makes it into a full stack.
I ordered 2048 gravel to be made and ended up with 40k+ of them before i canceled the order.

**Comment by VT-14** [comment]
I'll check about breaking the controller when I get home (about 8 hours).  I noticed that the drives themselves were shown as full.


Stack Upgrades could certainly be the issue.  I have a stack upgrade in my Importer (from the Quarry) and one in all the interfaces related to the auto-processing line.  If my quarry picked up 1 Iron Ore, put 64 in the system, ore tripped (on average) through the SAG Mill, put in 64 for each dust, then smelted 64 from each of those dusts...

That would explain the slightly high Slimey Dirt, Leaves, Snow, etc; the really high number of dusts, Flour, and Electrical Steel; and the ludicrously large supply of ingots.

**Comment by raoulvdberge** [comment]
It was the interace causing this. Fixed in aeeac1cc1ed4275ad990a373df8da69ad2bce5e8

Thanks for reporting
