### ISSUE TITLE
Crash on autocrafting with ore dict enabled

### ISSUE THREAD

**Issue by tivec** [raoulvdberge/refinedstorage#513]
#### Issue description:
This bug occurs and is 100% reproducible in the modpack AllTheMods version 1.39.

I was attempting to autocraft a Solderer using a pattern for a sticky piston in the crafting chain. This pattern had Oredict enabled. On pressing craft, I noticed it tried to use a blue slime ball from tCon(slimeballBlue) to craft the sticky piston. Pressing start produces the crash in the link below.

Switching the recipe to not use oredict, and instead use slimeballGreen (minecraft standard), the pattern works fine, same if it uses the blue slimeball. There could be something wrong with the oredict here

It SEEMS like it has finished crafting one of the sticky pistons when I restart the server.

#### What happens:
Crash.

#### What you expected to happen:
No crash, autocraft finishes fine.

#### Steps to reproduce:
1. Create a sticky piston pattern with oredict enabled in AllTheMods pack 1.39.

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge: 12.18.2.2112
- Refined Storage: 1.2-beta2

Does this issue occur on a server? 
Yes.

#### If a (crash)log is relevant for this issue, link it here:
https://gist.github.com/4f7d80efd27f98e0b5dd0741be40c253

**Comment by Alec-WAM** [comment]
That may be that the output is somehow null.

**Comment by tivec** [comment]
Possible, but the recipe is definitely there (I can craft it if I leave oredict off).

**Comment by tivec** [comment]
I can also report that this seem to happen on other oredict recipes. This last time with one using just wood and wood sticks to make a trim from the Storage Drawers mod: http://i.imgur.com/CUFtKXf.png

With oredict, it crashes, without it works just fine.
