### ISSUE TITLE
Feature request: Faster disk manipulation

### ISSUE THREAD

**Issue by tivec** [raoulvdberge/refinedstorage#518]
I've been "defragmenting" my disks by emptying them into the system using the disk manipulator. However, even with three speed upgrades and one stack upgrade (which seems to be the fastest method), it still takes roughly 2 minutes 30 seconds to empty out a single 64k disk. 

In my system, I have several drives and many 64k disks, so this takes an incredible amount of time to complete. I am aware that I can have multiple disk manipulators working in tandem, but perhaps adding another tier of stack/speed upgrades could be an option here?

Just throwing it out here for you to peruse and look over, feedback and comments appreciated. Keep up the great work, love the mod!

**Comment by raoulvdberge** [comment]
64k are 64.000 items, I think the 2:30 minutes is reasonable.
