### ISSUE TITLE
Feature request: Let the disk drive emit a redstone signal when full.

### ISSUE THREAD

**Issue by tivec** [raoulvdberge/refinedstorage#521]
What it says on the tin: This could be useful for automation (extract disks, insert disks) and other things. It should probably be an option, just like the detector has options for = < > etc.

Suggestion: Let the player specify "output redstone signal at <operator> <value> fill level"
If < 50% full
if == 100% full
if > 90% full 
etc etc :)

**Comment by Darkere** [comment]
the detector with no item targeted supposedly does this. Haven't tried though.

**Comment by raoulvdberge** [comment]
Detector with no item targeted checks the amount given, not fullness levels

**Comment by tivec** [comment]
Well, the idea is that the disk drive would emit, not the detector since
you can only pick an item target, not a nearby block's status.

**Comment by raoulvdberge** [comment]
Nah, I want to keep everything using the detector.

**Comment by tivec** [comment]
But can you use the detector to see the fill level of a specific disk drive, or your system in total?

**Comment by raoulvdberge** [comment]
System in total. I don't like the idea of checking individual disks. Not worth the effort

**Comment by tivec** [comment]
Not individual disks, but disk DRIVES (the 8 slot ones you place in the world). They already output the information on the interface for each, but it would be great to have, say, indicator lights on a central screen of your base or something, showing the disk drive status.

That said, if I can use a detector to show fill level of the entire system, I suppose I can use that too. Do I just leave the detector blank without any item specified?

**Comment by raoulvdberge** [comment]
Yes
