### ISSUE TITLE
1.2 Beta 3 -- game crash when searching items in a craft grid.

### ISSUE THREAD

**Issue by LordHellscream** [raoulvdberge/refinedstorage#524]
#### Issue description:
When pressed q in the search box, the game crashes
#### What happens:
Game crashes
#### What you expected to happen:
Game not crashing 
#### Steps to reproduce:
1. Press "q" in the search box (was looking for a black quartz ore) in crafting grid
2. Game crash

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Refined Storage: 1.2 beta 2

#### If a (crash)log is relevant for this issue, link it here:

http://pastebin.com/uVGR31MH

**Comment by raoulvdberge** [comment]
```
Stacktrace:
    at com.raoulvdberge.refinedstorage.gui.grid.GuiGrid.updateJEI(GuiGrid.java:470)
```
Weird, seems like the JEI runtime is unavailable, even though the mod is loaded.

**Comment by LordHellscream** [comment]
yea, this happened on beta 2 also, i put the release version back and it stopped happening.

**Comment by utoc** [comment]
I am not seeing this behavior in Beta4... did you update JEI past 328?  There were some changes.

**Comment by LordHellscream** [comment]
ill check tonight.

**Comment by LordHellscream** [comment]
looks like JEI updated to latest version fixes this issue.
