### ISSUE TITLE
1.2 beta2 - major issues

### ISSUE THREAD

**Issue by acidjazz** [raoulvdberge/refinedstorage#525]
Gotcha.

Just wanted to report that I've been testing this version with a pretty big setup for a good while, 60+ patterns, half processing, mixing this with mekanism, botania, ic2, other various mods.

The improvements in this version are very impressive, all of the processing crafting that was broken is working really well, love how you show the status of if the machine is in use or not to help make sure things are still moving along in massive jobs,

Excellent work.

**Comment by raoulvdberge** [comment]
Thanks for testing
