### ISSUE TITLE
Autocrafting efficiency

### ISSUE THREAD

**Issue by pagameba** [raoulvdberge/refinedstorage#526]
#### Issue description:

Autocrafting could be more efficient when a recipe has a dependency on multiples of another autocrafted component.  My use case is with Mekanism induction cells.  The basic tier requires 4 energy tablets.  These get crafted one after the other rather than 4 simultaneously.  If I manually request 4 tablets, they get made simultaneously.

#### What happens:

Multiple identical components of a crafting recipe get crafted sequentially rather than simultaneously.

#### What you expected to happen:

They would be crafted simultaneously.

#### Steps to reproduce:
1. set up the recipes for a mekanism basic induction cell
2. request one
3. the energy tablets get made one after the other rather than simultaneously
...

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge: 12.18.0.2010
- Refined Storage: 1.1.3

Does this issue occur on a server? [yes/no]

yes

#### If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here]

**Comment by way2muchnoise** [comment]
Could you share a screenshot of your setup? Cause there shouldn't be a difference. The crafting speed is based upon the amount of speed upgrades in a the crafter holding the pattern.

**Comment by pagameba** [comment]
Wow, so much awesome! You guys are great ...

**Comment by way2muchnoise** [comment]
Yeah, 1.2 has quite the feature set :D

**Comment by pagameba** [comment]
I'll check it out in single player, the server I'm on probably won't get this update for a while
