### ISSUE TITLE
External crafting tends to lose an accurate count on incoming items

### ISSUE THREAD

**Issue by utoc** [raoulvdberge/refinedstorage#528]
We've come into an issue in the new betas where external crafting tasks are getting "stuck" trying to complete even after all the items requested have made it into the system.  For the example here, we're running a crafting job to request 640 cobble.

@brad18 figured it out though; its counting whole stacks as singles.  If we remove the cable from the import chest until the job is done, when we put the cable back it will count 1 item for each stack it imports.

Example external crafting result chest: http://i.imgur.com/Vv0EZXC.png
And the result when we put the cable back: http://i.imgur.com/BrtrRtd.png

And another chest result (640 gravel): http://i.imgur.com/LGKHiWe.png
And the crafting monitor: http://i.imgur.com/TsfE4Yz.png

We're running RS Beta4, FML 2109.

**Comment by brad18** [comment]
It would appear that the system is counting a single import operation as a single item irregardless of the size of stack it pulled in. So say it pulled in 5 items or 43 items or 64 items, each import would count as a single item.

**Comment by choekstr** [comment]
Ahh, this would explain why sometimes I have to craft or put an item it is expecting into the system to register it has completed.

**Comment by RealGrep** [comment]
Yeah, that would also explain some of the things I've been seeing. Interesting.
