### ISSUE TITLE
Feature Request: Increase the speed at which the crafter exports items for external crafting

### ISSUE THREAD

**Issue by brad18** [raoulvdberge/refinedstorage#529]
At the moment the crafter seems to output items to a chest etc quite slowly in batches of 5-20 ish (depending on speed upgrades), would it possible to have the crafter export in stacks at a time?

Thanks

**Comment by way2muchnoise** [comment]
I guess you can speed it up by just making it do something like (32 of X -> 32 of Y) as a pattern. Or there should be some crazy expensive upgrade adding even more speed :p

**Comment by yutang13** [comment]
Lol, an upgrade upgrader so you can add speed upgrades to your speed upgrades.

Or just a tier 2 speed upgrade... By combining two speed upgrades with an advanced processor in a solderer.

**Comment by raoulvdberge** [comment]
It is fine how it is.

I agree with what @way2muchnoise said.

Additionally, from IRC:
<raoulvdberge> speed upgrade tier 2 i don't really like
<raoulvdberge> do insertion times really matter though? like if you request 1000 sand to be made from cobble
<raoulvdberge> the machine will be processing anyway
<raoulvdberge> so it can insert while it's processing
