### ISSUE TITLE
[1.2-Beta4] Crafting task collision

### ISSUE THREAD

**Issue by InusualZ** [raoulvdberge/refinedstorage#530]
#### What happens:
If you set the pattern for the basic processor and it's component to the same solderer the system it's going to push the component all at the same time. Causing the solderer to not work.

#### What you expected to happen:
Do one crafting task at a time, If it need to craft the Basic Processor wait until the printed basic processor "sub-task" finish and then start crafting the Basic Processor

#### Steps to reproduce:
1. Craft all the pattern required for the Basic Processor to be crafted in the solderer
2. Put all of those pattern in the same solderer
3. Craft 10 Basic Processor
4. Jackpot!!!

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge: 12.18.2.2099
- Refined Storage: 1.2-beta4

Does this issue occur on a server? yes

**Comment by raoulvdberge** [comment]
Hmm, this shouldn't be happening, as it checks if *all* items go in the machine. If not, it shouldn't even start the other one.

**Comment by InusualZ** [comment]
I'm going to test it again tomorrow.
