### ISSUE TITLE
Autocrafting ore dictionary 

### ISSUE THREAD

**Issue by returnzork** [raoulvdberge/refinedstorage#532]
#### Issue description:

Autocrafting with ore dict checked does not always show an error
#### What happens:

The start button is disabled in the grid, and nothing happens
#### What you expected to happen:

To show the preview pane with an error if it unable to craft
#### Steps to reproduce:
1. Create a pattern for the Open Computers raw circuit board while having the ore dict marked
2. Click craft in the terminal
3. The start button becomes disabled

#### Version (Make sure you are on the latest version before reporting):
- Minecraft: 1.10.2
- Forge: 12.18.2.2107
- Refined Storage: 1.2-beta3

Does this issue occur on a server? [yes/no]
yes
#### If a (crash)log is relevant for this issue, link it here:

Server does not crash, but this is displayed in the console when I click the start button
[RS crafting calculation/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: java.lang.NullPointerException

The recipe I am using is the open computers raw circuit board, which uses 1 cactus green, 1 gold ingot, and 1 block of clay.

The easiest way to fix this (for someone playing) is to not have the ore dictionary button checked when making this pattern (as it cannot use different dye), but I think it would be better if the grid at least showed some kind of error on why it is unable to craft, instead of just disabling the start button and staying on that screen.

**Comment by way2muchnoise** [comment]
Could you add some screenshots of your setup? What patterns, some system contents? Might be kinda related to #509 . Try creating patterns with the actual items instead of using JEI transfer (If you did that), it might help as well.

**Comment by raoulvdberge** [comment]
> [RS crafting calculation/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: java.lang.NullPointerException

We can do nothing with this, link the full log please.

**Comment by returnzork** [comment]
@raoulvdberge here's the fml server log
https://gist.github.com/returnzork/618d760b97d5362dc27ccc5c3ebe05d5
@way2muchnoise I tried creating the pattern without using jei transfer, but the same issue occurs

I was able to get it to work using both ways (making the pattern and with and without ore dict marked), so it could be something strange with how my base is setup on the server, I'll strip it down and try again.

**Comment by way2muchnoise** [comment]
I'm pretty sure it is just take some other dye, because of the ore dict. Guess you'll have to not use ore dict patterns for now. I'll see what I can do in the mean time.

**Comment by returnzork** [comment]
Ok, I removed pretty much everything from my setup, all that is left is the controller, 1 disk drive (with 2 64k disks), 1 crafter (with only the raw circuit board pattern), 1 crafting monitor, and 1 pattern grid.
It still happens.
I tested removing different combinations of the 64k disks, and it seems to happen when the nearly filled drive is inserted, removing that one (or both disks) the correct preview window appears
As I remove items from that disk, as soon as I remove the clay block the preview window starts appearing
![2016-10-27_16 03 10](https://cloud.githubusercontent.com/assets/1441365/19788730/ee8081f4-9c5e-11e6-9e02-6f48adb7eae7.png)
![2016-10-27_16 03 54](https://cloud.githubusercontent.com/assets/1441365/19788736/f8b116f2-9c5e-11e6-8435-768d333b6b06.png)

![2016-10-27_16 04 35](https://cloud.githubusercontent.com/assets/1441365/19788751/13f6c15a-9c5f-11e6-84b0-a97c014696e7.png)
![2016-10-27_16 04 38](https://cloud.githubusercontent.com/assets/1441365/19788755/168e4adc-9c5f-11e6-8882-8368ec9f4514.png)

**Comment by utoc** [comment]
A user was trying to craft a 64K disk and noticed the item preview was empty.  We noticed the following in the server console: http://pastebin.com/rVnWTXF4

The lesser items for the 64K disk worked fine when trying to autocraft.  The workaround was to turn oreDict off for the glass in the recipe, after that the items showed up and there was no console NPE.  The user reported that any oreDict recipes would not craft until oreDict was turned off.

We're running RS beta5 on FML 2116

**Comment by way2muchnoise** [comment]
Should be fixed in feff7464318210474ab4ce15ce232126451b3b16
