### ISSUE TITLE
Detector&Exporter - Suggestion

### ISSUE THREAD

**Issue by SpawnFallen** [raoulvdberge/refinedstorage#535]
Hi everyone, (sorry for my poor English)

#### Issue description:
Exporter with some items in slots filter and Detector with the following condition : X(item) > N(quatity) emit redstone signal to the Exporter.

#### What happens:
When the Detector emit a redstone signal, the Exporter export all items in slots filter in a Furnace or Crushing ect.

#### What you expected to happen:
Unfortunately, we could filter only one item in the Detector. So when it emit a redstone signal to the Exporter, this last export every items in a slot filter without check if all items respect the quantity condition.

- We could use a Slot Upgrade in a Detector to have more items in slot filter.
- We could check if all items in Exporter slot filter respect the Detector condition 
- A minecraft And Gate could be use, but it isn't compact.

#### Steps to reproduce:
1. Basic system - Controller & Grid
2. Crusher(or other thing) with one Exporter (and Importer) slot filter : Seed/Wheat/Beetroot seed
3. Detector with condition - Seed (Exemple) > 128 emit redstone signal
So wheat and Beetroot seed quantity aren't check

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: ModPack - AllTheMods 1.10.2
- Forge: 12.18.2.2112
- Refined Storage: 1.2 - Beta2

**Comment by raoulvdberge** [comment]
I don't understand the issue. Please rephrase

**Comment by SpawnFallen** [comment]
I'm really sorry. Clearly, I've a crushing (to get Biomass) and an Exporter with Seed/Wheat/Beetroot Seed in slot filter. A Detector emit a restone signal to the Exporter with the following condition : Wheat >128 emit redstone signal. But the signal is only true with the wheat.

Exemple:
In the system : Controller/Grid/Drisk Drive

- Quantity : Wheat 130 / Seed 115 / Beetroot Seed 60
- Detector : Condition Wheat > 128 emit signal on Exporter 
- After Quantity : Wheat 128 / Seed 113 / Beetroot Seed 58

So in this exemple, the Exporter export two Wheat in the Crushing, but two seeds and two beetroot seeds are export too. However, I would like to export only when Wheat AND Seed AND Beetroot seed are >128 to have always the same Wheat/seed/beetroot seed quantity in the system.

I'm really sorry for my issue and my poor English (I'm French.... sorry)

**Comment by raoulvdberge** [comment]
No need to say sorry that much times, not everyone speaks English perfect :)

What I suggest you to do is to create a redstone circuit with a few detectors and make a redstone AND gate. That way, you can set up multiple conditions for the exporter.

**Comment by SpawnFallen** [comment]
Thank you very much. I though about it, and I was hoping there was a simplest solution.  ^^. Thank again for your help. Have a nice evening.
