### ISSUE TITLE
Controller Randomly Loses Power

### ISSUE THREAD

**Issue by justStacyB** [raoulvdberge/refinedstorage#538]
At random moments, the controller will lose power. All power sources are still functioning appropriately, no cable breaks. Restarting MC will fix the problem, but then it happens again. At first I thought it was a chunk issue, but it has happened while standing in front of the controller, using the grid. I have since switched the the creative controller. No problems so far, but only tested for 20 minutes. 

I really don't know what to do to reproduce the issue. As I said, the issue happens randomly. *shrug*

#### Version:

- Minecraft: 1.10.2
- Forge: 12.18.1.2099
- Refined Storage: 1.1.3

Does this issue occur on a server? No

**Comment by raoulvdberge** [comment]
Very incomplete bug report. What power are you feeding in, are you sure your power isn't going low, are you sure some RS machine doesn't need more power at times, ...

**Comment by raoulvdberge** [comment]
Closing due to lack of information. I'll reopen if you come back with more information
