### ISSUE TITLE
Game Breaking Bug with interface and external storage

### ISSUE THREAD

**Issue by DennisBengel** [raoulvdberge/refinedstorage#539]
#### Issue description:
My server crashes when I place a interface next to an external storage to keep craftable items stored as a kind of buffer.

#### What happens:
The server crashes when ticking the interface...

#### What you expected to happen:
To keep items stocked in an interface and to pull them out with a storage bus.

#### Steps to reproduce:
1. Place an interface with a crafting upgrade in it and to keep items stocked inside the interface.
2. Place an external storage on the bottom.
3. Let the crashing begin...

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge: 12.18.1.2095
- Refined Storage: 1.1.2

I'm playing on the FTB pack HermitPack 1.0.1

Does this issue occur on a server? [yes/no]
Yes

#### If a (crash)log is relevant for this issue, link it here:
http://pastebin.com/QxUA09hF

**Comment by raoulvdberge** [comment]
Please share a screenshot of the problemetic setup.
