### ISSUE TITLE
Backport to 1.8.9?

### ISSUE THREAD

**Issue by felixangell** [raoulvdberge/refinedstorage#54]
<img src="https://cloud.githubusercontent.com/assets/6254332/15335211/4318c918-1c69-11e6-886a-59fa8321933e.png" width="696969">

**Comment by raoulvdberge** [comment]
![ugh](https://images.encyclopediadramatica.se/thumb/6/65/Richard_Stallman_straining_his_bowels.jpg/300px-Richard_Stallman_straining_his_bowels.jpg)

**Comment by felixangell** [comment]
![screen shot 2016-04-29 at 22 59 31](https://cloud.githubusercontent.com/assets/6254332/15336876/97c05a74-1c70-11e6-8dd9-8f6aab9c2ab3.png)
