### ISSUE TITLE
[Feature] ExtraUtils drums

### ISSUE THREAD

**Issue by Lukas45** [raoulvdberge/refinedstorage#544]
at the moment, Drums from ExtraUtils2 can not be emptied into the Fluid Grid, meaning I have to manually transfer 256 buckets of fluids from it :(
Well in general, the EU2 drums are not compatible with very many things, but this would be a nice one to get in.
#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge:
- Refined Storage: 1.1.3

**Comment by raoulvdberge** [comment]
For stuff like drums you use an importer in fluid mode.

**Comment by Lukas45** [comment]
Well now I feel stupid.
Cheers man
