### ISSUE TITLE
Wrench

### ISSUE THREAD

**Issue by raoulvdberge** [raoulvdberge/refinedstorage#545]
Used to copy configurations over and rotation stuff.

**Comment by hron84** [comment]
Call it as wrench and make it able to wrench up cables and machines too 😄

**Comment by raoulvdberge** [comment]
Good idea

**Comment by hron84** [comment]
@raoulvdberge check how Ender IO's wrench work in terms of mode changing. Sneak + mouse wheeling is a good idea to change between wrench mode and copy mode.
