### ISSUE TITLE
[1.2 Beta 4] Crashing on world load (maybe from an overloaded system)

### ISSUE THREAD

**Issue by yutang13** [raoulvdberge/refinedstorage#546]
#### Issue description:
I had requested an ultimate induction provider to be crafted. A very very large recipe with tonnes of recursion. It was making loads of the simple components and I was just babysitting it to make sure everything was Ok. I noticed my importer was being too slow so I requested  4 speed upgrades for it and installed them. Re-opened the machine and crashed. 
Previous to that I had noticed that inside the GUI was very laggy for some reason and just generally performance was somewhat less. 
Update!:
I crash 2 seconds after loading the world now :(
#### What happens:
Well, I crashed :P
#### What you expected to happen:
To not crash
#### Steps to reproduce:
Honestly not sure how  to reproduce this

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge: 1.10.2-12.18.2.2098
- Refined Storage: 1.2 beta 4

Does this issue occur on a server? [yes/no]

#### If a (crash)log is relevant for this issue, link it here:

http://pastebin.com/BW5QTxR4 -- Just the crash

http://pastebin.com/ctz0WrAn --The game output from when I logged in to when it crashed (includes crash log)

**Comment by yutang13** [comment]
Looking at what the crash says is it just that I overloaded your autocrafting system? I'm guessing it's reached a point where so much is going on it crashes?

**Comment by way2muchnoise** [comment]
You didn't overload it. But it seems like something did go wrong somewhere. I added an extra check, so it shouldn't happen again. Beta5 should be out soon™.

**Comment by yutang13** [comment]
Nice and quick! Thank you

**Comment by way2muchnoise** [comment]
Crashlogs always help :D

**Comment by way2muchnoise** [comment]
Real fix added in 10e56a5b3d196da44403b1b735e86c582aa36b4b and cc20647cf67b1131e6e1938bf9dcf621ee854efa

**Comment by yutang13** [comment]
I have beta 5 installed but I still crash :(

Seems to be the same crash log but I'll link it anyway
http://pastebin.com/XYYM0Ypy

Unsure if this means you didn't fix it or it is fixed but I need to restore from a backup

**Comment by way2muchnoise** [comment]
Related to #556
