### ISSUE TITLE
Server crashes with an interface -> external storage -> autocrafting setup

### ISSUE THREAD

**Issue by Merec** [raoulvdberge/refinedstorage#547]
#### Issue description:
Server crashes with an exception after setting up a "keep-in-stock" interface with crafting card and an external storage.

#### What you expected to happen:
The system crafts items to keep them in stock.

#### Steps to reproduce:
I have set an external storage to the bottom side of an Interface. Added a crafting card to the Interface and added some items to the external part to keep them in stock (processors and so on). The items show up in the grid. After I took some processors (half, richt click) from a grid, the server crashes and is now unable to start again. I was able to reproduce it in a creative world.

#### Version (Make sure you are on the latest version before reporting):
- Minecraft: 1.10.2
- Forge: 12.18.2.2099
- Refined Storage: 1.1.3

Does this issue occur on a server?
Yes. Modpack: "FTB HermitPack"

#### If a (crash)log is relevant for this issue, link it here:
http://pastebin.com/qQMRduMC

**Comment by way2muchnoise** [comment]
@raoulvdberge you fixed this in dev right? (#539)

**Comment by Merec** [comment]
Oh, seems like I overread that ticket. Sorry.

**Comment by raoulvdberge** [comment]
already fixed indeed
