### ISSUE TITLE
Startup chat messages

### ISSUE THREAD

**Issue by BinaryCrafter** [raoulvdberge/refinedstorage#548]
Please would you consider adding an option to disable the startup messages that the mod puts into chat when the game starts/world loads. As a modpack creator, I'd like nothing more than to prevent all the mods in my packs from doing this, as typically, the messages are related to version updates, which players of modpacks have no control over. It can be quite overwhelming for players to be subjected to many many lines of messages when the game loads.

**Comment by raoulvdberge** [comment]
The startup chat message you  are getting from RS is stating you're playing on a beta version that can cause serious damage if you don't take backups. Most people don't realise this, and frankly, you shouldn't be including beta versions in packs.

**Comment by BinaryCrafter** [comment]
Understood, thanks.
