### ISSUE TITLE
Nullpointer on crafting

### ISSUE THREAD

**Issue by MakerTim** [raoulvdberge/refinedstorage#549]
#### Issue description:

I tried to craft a storage housing, with a crafter
crafter has no inventory linked to it, 
nullpointer on crafting.

#### What happens:
Server crash, needed to mcedit the crafter to stop crash loop

#### What you expected to happen:
It crafting my crafting and not crash

#### Steps to reproduce:
1. Create a recipe with the Processing Pattern Encoder 
2. Place it into a crafter (facing top) towards a air block
3. enyoy the nullpointer on every startup
...

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge: 2114
- Refined Storage: 1.2-beta2

Does this issue occur on a server? [yes/no]
YES

#### If a (crash)log is relevant for this issue, link it here:

Error stacktrace:
http://pastebin.com/VDpSGYSS

full report:
http://pastebin.com/c5zre8ss

**Comment by way2muchnoise** [comment]
If you are going to use a beta at least use [the latest one](https://minecraft.curseforge.com/projects/refined-storage/files/2339809).
