### ISSUE TITLE
Fluid Storage

### ISSUE THREAD

**Issue by raoulvdberge** [raoulvdberge/refinedstorage#55]

**Comment by 4rz0** [comment]
Will this include a complete fluid system with inserters/extractors and support for crafting as well?

**Comment by raoulvdberge** [comment]
Yes there will be inserters and extractors

Crafting I'm not sure if that is even possible?

**Comment by Harith163** [comment]
I think that he was thinking along the lines of alloying. If that is the
case then it would be way too op.

**Comment by 4rz0** [comment]
How is it op to automate things that you can do in your crafting grid?
Cause that's what this mod already does.

**Comment by Harith163** [comment]
How exactly can you alloy fluids in your crafting table? The only methods
that come to mind for me are Tinker's smelting and casting, and something
like an alloy smelter. Am I missing something?

**Comment by raoulvdberge** [comment]
The crafter could output fluids, but then it wouldn't be able to output items on the same side.

**Comment by 4rz0** [comment]
I'm sure there are other machines that can take both; IC2 Canning Machine for example.

**Comment by JCMais** [comment]
About the crafting, one feature that would be wonderful is the possibility to autofill buckets from the fluids storage, when crafting recipes that require such liquid. Like some foods from Pam for example, which requires water bucket. The system could get a available bucket and fill it with water (if there is water in the system) automatically.

**Comment by 4rz0** [comment]
Jup, that's pretty much what I meant.

**Comment by Wii505** [comment]
http://mods.curse.com/mc-mods/minecraft/229218-extracells2

**Comment by raoulvdberge** [comment]
- Fluid Disk Drive
- Fluid Storage Disk
- Fluid Constructor
- Fluid Destructor
- Fluid Importer
- Fluid Exporter
- Fluid Interface

**Comment by raoulvdberge** [comment]
All the features in the post above are implemented!

**Comment by 4rz0** [comment]
Awesome, thanks!
