### ISSUE TITLE
Fluid Crafting appears broken (v1.2 beta4)

### ISSUE THREAD

**Issue by Anaerin** [raoulvdberge/refinedstorage#551]
#### Issue description:
When crafting Lava + Water into Obsidian (pattern:

Col 1 | Col 2 | Col 3
--- | --- | ---
Lava Bucket | Lava Bucket | --
Water Bucket | Water Bucket | --
-- | -- | --

) with 4 empty buckets (and a recipe to autocraft buckets in the system as well), along with 25 buckets of both liquids stored in the fluid storage.
#### What happens:
Auto-crafting states there aren't enough lava and water buckets in the system

#### What you expected to happen:
Getting obsidian crafted.

#### Steps to reproduce:
1. Set up pattern
2. Put pattern in crafter
3. Ensure you have lava and water stored, and at least 4 empty buckets.
4. Request Obsidian crafted
...

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge: 12.18.2.2099
- Refined Storage: 1.2 beta4

Does this issue occur on a server? [yes/no]
Yes

~~I'm going to attempt to update the server and modpack to 1.2 beta 4 and see if this fixes it.~~

Updated to 1.2 beta4, recreated the pattern from scratch and it is still broken.

**Comment by way2muchnoise** [comment]
beta5 will be out soon™ and will probably be the last beta. So if it still happens in beta4 (or beta5 in like 12 to 24 hours after this comment) then you should keep this open.

**Comment by Anaerin** [comment]
Just checked in Beta 4, and it still does it:
![2016-10-29_16 04 49](https://cloud.githubusercontent.com/assets/989271/19833044/c04aef1a-9df1-11e6-9e14-4af2e12bd270.png)
![2016-10-29_16 05 05](https://cloud.githubusercontent.com/assets/989271/19833045/c04c1778-9df1-11e6-8e06-7d6eb4ee3dfa.png)
![2016-10-29_16 05 17](https://cloud.githubusercontent.com/assets/989271/19833046/c04f22f6-9df1-11e6-9dbc-86d288d4c892.png)
![2016-10-29_16 05 22](https://cloud.githubusercontent.com/assets/989271/19833047/c0aa2bb0-9df1-11e6-84bc-52d1db5f019c.png)
