### ISSUE TITLE
Percentage Values

### ISSUE THREAD

**Issue by Dolinmyster** [raoulvdberge/refinedstorage#552]
Some crafting recipes have the requirement of a percentage. For instance Silicone from EnderIO has a 50% chance to be made from Sag Milling sand. Would it be possible to add in an option that would say "Keep sending sand until Silicone is received" or something similar? 

http://puu.sh/s0kMt/ec1af66dc0.png

**Comment by way2muchnoise** [comment]
I guess either creating a 4 -> 1 (or something like it would work). Or wait for the rescheduler (#550) to kick in. As doing things like percentage based is really hard and will just make the whole system slower because of the checks.
