### ISSUE TITLE
Can't autocraft Speed Upgrades / Range Upgrades / ...

### ISSUE THREAD

**Issue by raoulvdberge** [raoulvdberge/refinedstorage#553]
As soon as I start the autocraft, it says the solderer that is supposed to make the upgrade is in use. Said solderer isn't in use, as it's the only crafting task. Nothing is inserted either.

**Comment by way2muchnoise** [comment]
Should be fixed in 0d6aaca8d6dd939022e6f807fcdddb1dc61d5a19
