### ISSUE TITLE
[Suggestion] External storage: Ore dictionary matching

### ISSUE THREAD

**Issue by hron84** [raoulvdberge/refinedstorage#554]
#### Issue description:
It would be good if the external storage can match stuff against ore dictionary since there is no way to provide different ore types. For example, I use Storage Drawers (compacting drawers) to store ingots and gems but the different version of Copper, tin delivers to the disks instead of the drawer.

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge:  2099
- Refined Storage: 1.1.3

**Comment by way2muchnoise** [comment]
Try out one of the [betas](https://minecraft.curseforge.com/projects/refined-storage/files). Ore dict will be added in 1.2

**Comment by hron84** [comment]
@way2muchnoise i'll definitely check it out.
