### ISSUE TITLE
Autocrafting causing NPE

### ISSUE THREAD

**Issue by way2muchnoise** [raoulvdberge/refinedstorage#556]
http://pastebin.com/LQWp5eUD

Happened when @Darkosto was in the end. Dunno if it has anything to do with it.

**Comment by way2muchnoise** [comment]
Likely related to #509 and #532

**Comment by raoulvdberge** [comment]
Other report from someone after joining world:

https://dl.dropboxusercontent.com/u/3944645/crash-2016-10-31_09.49.04-server.txt

**Comment by utoc** [comment]
We came across this today; it was a reoccurring crash

Crash here: http://pastebin.com/gbexux79

Playing with RS Beta 5 on FML 2116.  Player just left the end, teleporting into their base
