### ISSUE TITLE
Disk Drives don't render properly

### ISSUE THREAD

**Issue by vlce-versa** [raoulvdberge/refinedstorage#557]
#### Issue description:
The Disk Drive and the Disk Manipulator don't render properly, they are very dark compared to the other blocks.
#### What happens:
See screenshot https://i.imgsafe.org/70bced6f83.png
#### What you expected to happen:
To render properly
#### Steps to reproduce:
1.
2.
3.
...

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge:12.18.2.2116
- Refined Storage:1.2-BETA5

Does this issue occur on a server? [yes/no]
Yes

**Comment by raoulvdberge** [comment]
This is because of an Optifine bug.

See sp614x/optifine#302
