### ISSUE TITLE
Shift triple click timer too short.

### ISSUE THREAD

**Issue by Darkere** [raoulvdberge/refinedstorage#558]
Basically, the Shift triple click function works only every 5th time I try it. I hope this is not a problem with my mouse.

Also, config option to set it to double instead of triple click ? ;)

- Minecraft: 1.10.2
- Forge:2116
- Refined Storage: 1.2 beta 5

**Comment by raoulvdberge** [comment]
Then something is definitely wrong with your mouse ;)

![x](https://raoulvdberge.com/lp2fMx)
