### ISSUE TITLE
Insert Item check causes some lag

### ISSUE THREAD

**Issue by Darkere** [raoulvdberge/refinedstorage#559]
#### Issue description: 
I believe this to be an issue when a crafting job tries to fill an inventory which is full. A function checks whether or not there is space in the inventory and whether the item can be inserted, depending on the block this takes a lot of time.

#### What happens: 
Tick time goes up significantly up to tps issues with Machines from other mods

#### Steps to reproduce:
1. Set up autocrafting for glass
2. Craft 1k glass
3. check forge tps
 Depending on the furnace you may need some speed upgrades in the crafter.

 I used a red matter furnace from project E but the exu2 furnace had the same problem with a bit less lag. 

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge:
- Refined Storage:1.2 beta 5

**Comment by raoulvdberge** [comment]
nps file please

https://github.com/raoulvdberge/refinedstorage/issues/523#issuecomment-256419502

**Comment by Darkere** [comment]
one of the more extreme cases here
https://sharedat.allions.net/?LZLSmwqY.nps

**Comment by way2muchnoise** [comment]
They just use an extremely inefficient way of checking if the item can be inserted. I guess the best you can do is add some buffer chest and insert it into the machine some other way.

**Comment by Darkere** [comment]
Here is the same thing happening when only using solderer. 
https://sharedat.allions.net/?g5odtEFX.nps

**Comment by raoulvdberge** [comment]
Hmmmm

![x](https://raoulvdberge.com/70Ui1r)

**Comment by way2muchnoise** [comment]
This solves the slowness in comparing patterns, but there is no way we can improve the insert methods of other mods.
