### ISSUE TITLE
[1.9] Controller world crash

### ISSUE THREAD

**Issue by dirtyfargo** [raoulvdberge/refinedstorage#56]
Forge: 12.16.1.1907
Version: Tested on both 0.6.4 & 0.6.5
Description: When I had a hopper going into a disk drive and attempted to import items into storage this way, I got a server crash and the world crashed on startup again until I used mcedit to remove the controller block.
[Crash Report ](https://gist.github.com/dirtyfargo/3890e2135433d712be3fb71b1ea26ef1)

**Comment by raoulvdberge** [comment]
Thanks for reporting, this is fixed for the next version.

**Comment by dirtyfargo** [comment]
Thanks for the quick reply =)

**Comment by raoulvdberge** [comment]
This bug also works on a bunch of other machines, so I'm very happy I know about this.

**Comment by felixangell** [comment]
![1463408435029](https://cloud.githubusercontent.com/assets/6254332/15375782/1150c792-1d49-11e6-9e0f-8634d72ade88.gif)
Great work!

**Comment by raoulvdberge** [comment]
[Version 0.6.6 fixes this](http://minecraft.curseforge.com/projects/refined-storage/files/2301021)
