### ISSUE TITLE
Feature Request: Network Transmitter MAX energy use.

### ISSUE THREAD

**Issue by Selbram** [raoulvdberge/refinedstorage#560]
Currently, if you place a receiver in another dimension you get hit with a 1000 RF/t maintenance. This is reasonable and can easily be achieved. The issue I ran into was with a receiver ~10,000 blocks away from my base in the overworld. The power cost was astronomical. Having some sort of cap on cost as a config option would be nice. Having a default cap of say 5000 RF/t is really high but still achievable. Or no cap at all like the current config. 

OR

Some way to increase efficiency / reduce the cost of having a transmitter at range. Maybe using the existing range upgrades in a different way in the network transmitter.

**Comment by raoulvdberge** [comment]
The beta's have already a power cap of 1000 RS/t

**Comment by Selbram** [comment]
Ha, I submit this and then looked at closed issues. Thanks for the wonderful mod.
