### ISSUE TITLE
Stack Upgrade Duplication Bug

### ISSUE THREAD

**Issue by ssblur** [raoulvdberge/refinedstorage#563]
#### Issue description:
When using a Stack Upgrade in an interface, then pumping in single items, stacks are inserted into the network.

#### What happens:
Same as above.

#### What you expected to happen:
When one item is inserted into an interface with a Stack Upgrade, I expect one item in my storage network.

#### Steps to reproduce:
1. Build and power refined storage system.
2. Add interface with stack upgrade
3. Add Hopper / Item Conduits / etc.
4. Use Hopper / Item Conduits / whatever to insert a stack with a size less than 64
5. Observe as a whole stack enters your network.

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge: 12.18.2.214
- Refined Storage: 1.2- beta 2

Does this issue occur on a server? yes

#### If a (crash)log is relevant for this issue, link it here:

Irrelevant. No console output.

**Comment by Darkere** [comment]
You are not on the newest version at all. Please test if this will work on beta 5

**Comment by raoulvdberge** [comment]
This was fixed in beta-3 I think. You are on beta-2. The current version is beta-5.

**Comment by ssblur** [comment]
New version does fix it, apologies.
