### ISSUE TITLE
Feature Request - Greater wireless range

### ISSUE THREAD

**Issue by NosajDraw** [raoulvdberge/refinedstorage#564]
The maxed out wireless range of 48 blocks is very small, in AE I was happy to keep stacking the range upgrades till it reached out at least 500 blocks often more (I think the biggest range I ever made was around 1500 blocks) sure it cost me lots of power, but lots of power I have.

**Comment by raoulvdberge** [comment]
Did you know that you can spread the transmitters out in your base?
