### ISSUE TITLE
[Request] Ignore-NBT (option?) in autocrafting

### ISSUE THREAD

**Issue by xenoflot** [raoulvdberge/refinedstorage#565]
#### Issue description: Autocrafting does not appear to ignore NBT in the case of turning ingots to plates, and plates into wires, for Immersive Engineering. I'm assuming something similar will happen with IC2 plates. 

edit: It also happens with extrautils2's glass cutting knife (used to slice enderpearls to make screens)

edit2: I've also noticed when shift-clicking IE's recipes in JEI, that when using the Crafting Grid, a damaged cutter/hammer is not moved to the grid. Damaged cutters _do_ get shift-clicked in with a vanilla crafting table, so I'm assuming this is a related issue.

#### What happens: I created a recipe to combine a new Engineers Hammer with a metal ingot to create a metal plate. Similarly, a metal plate with new Cutters to create wire. After autocrafting a few stacks, I found there are some 400 hammers and 400 cutters in my RS, each use by only a single point of durability.

After removing the Hammer recipe, I'm unable to autocraft because the RS doesn't consider a slightly used hammer to be adequate.

Tested with iron, copper and aluminium ingots and plates.

#### Steps to reproduce:
1. 
2.
3.
...

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge: 2107
- Refined Storage: 1.2-beta4

Does this issue occur on a server? [yes/]

#### If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here]

**Comment by raoulvdberge** [comment]
Toggle the required pattern to use oredict, it's literally there for that use case

**Comment by xenoflot** [comment]
I noticed that and tried it. The problem remains.

**Comment by xenoflot** [comment]
@raoulvdberge Not sure if you get notifications on closed issues, so just a quick bump. I _did_ try the oredict option, in both the pattern grid and the processing grid. It didn't help.

**Comment by raoulvdberge** [comment]
> I created a recipe to combine a new Engineers Hammer with a metal ingot to create a metal plate. Similarly, a metal plate with new Cutters to create wire. After autocrafting a few stacks, I found there are some 400 hammers and 400 cutters in my RS, each use by only a single point of durability.

Are you 100% sure the Metal Plate recipe has oredict turned on? Also, are you sure there aren't 2 the same Metal Plate recipes in your Crafters?

Having 400 hammers in your grid is a symptom of not having oredict turned on... please double check this.

**Comment by xenoflot** [comment]
I double-checked before I replied to make sure I wasn't telling fibs :)   I made sure that I was unable to autocraft aluminium plates (IE no existing recipes), then I created a recipe in the normal pattern grid using a well-damaged hammer and ensuring that oredict was checked. I dropped that in a crafter and it appeared in the grid. When attempting to use the recipe, it says that it's missing a hammer, despite there being plenty of nearly-new hammers in the RS.

I just triple-checked now by repeating that process.

**Comment by xenoflot** [comment]
FWIW this is on a server. I haven't tested this in SMP although I can do so if you feel it would be helpful.

**Comment by way2muchnoise** [comment]
Might be fixed in feff7464318210474ab4ce15ce232126451b3b16

**Comment by way2muchnoise** [comment]
Should work with most tools now. IE has been notified about the issue and how to fix it. So hopefully they will do that soon.

**Comment by xenoflot** [comment]
That's great, thanks!
