### ISSUE TITLE
Random Autocrafting crash

### ISSUE THREAD

**Issue by 3Pixel** [raoulvdberge/refinedstorage#568]
#### Issue description:
well the server is crashing randomly when there is any kind of autocrafting going on.

it had happened with 3 different RS systems. all had some kind of autocrafting going on.

#### What happens:
Server is sometimes crashing if there is any autocrafting going on.

#### What you expected to happen:
that the server does not crash?

#### Steps to reproduce:
1. start a autocrafting process
2. wait?
3. server might crash after a while
...

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge: 12.18.2.2114
- Refined Storage: 1.2 Beta 5

#### Does this issue occur on a server? [
Yes

#### If a (crash)log is relevant for this issue, link it here:

here is the latest crash log: http://pastebin.com/GGgmRyHb

there are more crashed but they are the same.

**Comment by raoulvdberge** [comment]
already fixed

**Comment by way2muchnoise** [comment]
See #556
