### ISSUE TITLE
Destructor destroying Mekanism Blocks

### ISSUE THREAD

**Issue by dbridle** [raoulvdberge/refinedstorage#569]
#### Issue description:

When placing any Mekanism block in front of the Destructor, instead of storing, they are destroyed.  I have tried blocks from various types of Mods and the rest seem ok (Hermitpack Modpack)

#### What happens:

Placing any Mekanism block in front of the Destructor causes it to be destroyed.

#### What you expected to happen:
The block to be stored or pushed into the world if no storage available.

#### Steps to reproduce:
1. Place a destructor, connected to a refined storage network with space available
2. Place any Mekanism Block  for example Basic Gas Tank
3.
...

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge: 12.18.2.2099
- Refined Storage: 1.1.3

Does this issue occur on a server? Only using single player

#### If a (crash)log is relevant for this issue, link it here:

No crash occurs

**Comment by raoulvdberge** [comment]
We might need to use a fake player for this...

**Comment by dbridle** [comment]
I'm not quite sure what that means!

**Comment by raoulvdberge** [comment]
Not an RS issue. We use `Block#getDrops`, Mekanism should work with that.
