### ISSUE TITLE
Server crash autocrafting

### ISSUE THREAD

**Issue by ProsperCraft** [raoulvdberge/refinedstorage#572]
https://gist.github.com/ProsperCraft/5dcf71e37fa593c7e15c02e6ab69f513

I am trying to track down what the users were doing at the time of the crash.

**Comment by ProsperCraft** [comment]
Here is another after that last one.
https://gist.github.com/ProsperCraft/27a81a2c11067fb4321e0ed185f3992d

**Comment by BlackMist1035** [comment]
trying to craft combustion generator 
http://pastebin.com/Gi5pkdAq

**Comment by raoulvdberge** [comment]
It is already fixed in dev

**Comment by way2muchnoise** [comment]
See #556 and probably also #532
