### ISSUE TITLE
How do I automate the Solderer? (Not so much a bug report, but a request for help)

### ISSUE THREAD

**Issue by clmurphy74** [raoulvdberge/refinedstorage#574]
So far YT vids have been useless in helping me with this issue.  I have tried almost every way I can think of to automate crafting in the solderer, but still get the Machine Not Found message in the crafting monitor.  I have placed the solderer in front of, next to, on top of, underneath, and linked with cables (from the mod pack, as I'm having separate issues with another mod in the custom pack) to both the crafter and solderer (it is also linked to the system).  I have noticed that only one crafter seems to show up in the main controller.  I don't know if the system can only support one crafter at a time, but have seen YT vids (from those playing the hermitcraft hermitpak) that show multiple crafters and solderers being used and that they worked (somewhat).  Other than that, autocrafting is working but is only limited to what the one crafter can do...so crafting a 64k drive from scratch isn't possible.

BTW, this a custom pack created through the Curse App.  In this pack there are other mods installed.  So far Refined Storage is not giving me any other issue than this.  :) Very happy with it, but would like to automate the creation of disk drives, such as the 64k storage drive, as I need them.

#### Issue description:  
No auto crafting taking place in the solderer

#### What happens:  
Nothing happens and the crafting monitor shows Machine Not Found message

#### What you expected to happen:  
Auto crafting taking place in the solderer....Such as silicon being turned into printed silicon, diamonds turned into printed advanced processors...etc

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge: .2118 as of 11/2/2016
- Refined Storage: 

Does this issue occur on a server? [yes/no] No...Single player world

#### If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here]

**Comment by raoulvdberge** [comment]
have you watched this?

https://github.com/raoulvdberge/refinedstorage/wiki/Automating-the-Solderer

also, is the crafter facing the solderer?

**Comment by clmurphy74** [comment]
I'm assuming the side with the square in the middle that lights up is the front...  I took some screen shots as I may not be describing the problem correctly.  http://imgur.com/a/lzsP8

I did notice that the controller has updated and is showing the 2nd crafter....also does the importer need to be connected to the solderer or the crafter?  And if it is the solderer, does it feed from any side, or one specific side (such as the top, bottome, left or right side)?

**Comment by raoulvdberge** [comment]
Insertion in solderer is at any sides besides the bottom side.

You extract from the bottom side.

**Comment by clmurphy74** [comment]
Would not having an exporter cause it to not craft?

**Comment by raoulvdberge** [comment]
I have no idea what an exporter has to do with this. Did you watch the video I linked you?

**Comment by clmurphy74** [comment]
Yep....Still its not crafting, and the patterns are showing up and the crafting monitor is showing that they can be crafted, but the solderer still remains empty and not functioning unless I manually place the items in.  :(

**Comment by way2muchnoise** [comment]
So @clmurphy74 seems like you actually stumbled on a bug that was in since beta6. It is fixed in b175de68a4899a334f7cae765f447b75a2670cdc

**Comment by raoulvdberge** [comment]
Please try beta 8 as soon as it comes out
