### ISSUE TITLE
Refined Storage not using Silicon from other mods in Beta8?

### ISSUE THREAD

**Issue by clmurphy74** [raoulvdberge/refinedstorage#576]
#### Issue description:  
Have over 300 silicon produced in the SAG Mill from EnderIO and it is not being used in the Refined Storage recipes.  If placed in solderer manually, it disappears entirely.  Also this was not an issue until this update.

#### What happens:  
When using the auto crafting feature, crafting monitor will state that silicon is missing even though I have over 300+ silicon (made using sand processed through an EnderIO SAG Mill).  Also if the EnderIO silicon is placed in the solderer, it disappears and does not reappear in Refined Storage inventory.

#### What you expected to happen:  
The auto crafting to use the silicon already in my system and not to have to process nether quartz (which is rather expensive) to produce silicon.  Also this was working fine before updating to Beta8

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge: 2118
- Refined Storage: Beta8

Does this issue occur on a server? [yes/no] No, single player

#### If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here]

**Comment by way2muchnoise** [comment]
Are you sure you turned on the ore dict on the pattern?

**Comment by way2muchnoise** [comment]
Fixed in 1ef9975196b20f31f0275a1d84871926e1cb75b0. Seems like I messed up with the ore dict stuff :D
