### ISSUE TITLE
[Suggestions] Diskstorage

### ISSUE THREAD

**Issue by accessdenied0** [raoulvdberge/refinedstorage#58]
Hey @raoulvdberge,

I have a few requests/suggestions for this mod, manly about the Disk-storage... I know this mod is just alpha but I personally think the storage is too small. I crafted for example a 4k Disk.
After I put one Stack in, I noticed it used actually 64 of the 4000 up... 
I feel like this is a bit too small...
In special in compartment with the actually AE [4k-Storage-cell](http://ae-mod.info/4k-ME-Storage-Cell/). (4000/64 = 62.5 Stacks of one Item < 508-206 Stacks) of course this is type limited, but I would like to adjust the amount of storage with an option or simply a bit higher storage possibilities...

The second suggestion is possibly already planned so you might ignore that, but: A Storage-Bus... (all said)

I hope for your response,

access_denied

**Comment by raoulvdberge** [comment]
I'm not going to add larger storage options, you can just keep making storage disks and keep adding disk drives. Also, the 64000 disk drive is *a lot*.

The storage bus is already in there, it's called a external storage.

**Comment by accessdenied0** [comment]
Sorry to say that, but this makes your system less useful. It "wastes" more resources that it can handle.
But well....

[To the Storage-Bus... are you sure you mean the same as I mean](http://ae-mod.info/ME-Storage-Bus/)?

**Comment by raoulvdberge** [comment]
Place an inventory in front of an external storage, it will behave like an AE storage bus.

**Comment by accessdenied0** [comment]
Thank you @raoulvdberge ,

I was stupidly the impression it is a kinda "ME-Chest"... This would be useful, too, but I the Storage Bus is indeed more useful. Well done!

I have one more question: Do you have planned a kinda "Import"-button to the Interfaces like the "External Storage"? What I mean you can "Import" the items in a Inventory to setup the filter more easily. It might be just a small feature but you might considered it....
