### ISSUE TITLE
weird autocrafting

### ISSUE THREAD

**Issue by Andre--D** [raoulvdberge/refinedstorage#581]
I have a weird behavior with autocrafting

#### What happens:

autocrafting 1 cake gives me 4 cakes back
milk buckets are not consumed 
empty buckets dissapearing
with ore dic autocrafting on the behavior is ok, but milk buckets are also not consumed 

autocraft sticks with spurcewood planks will not craft
- missing oakwood planks
workaround is use ore dictonary autocrafting

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge: 2119
- Refined Storage: 1.2.1

**Comment by way2muchnoise** [comment]
If you don't turn on ore dict only the wood in the pattern can be used. If you turn on ore dict it'll use what ever piece of wood.

**Comment by Andre--D** [comment]
@way2muchnoise 
Pattern making with 2 spurcewood planks

testing a little bit and it seems that
autocrafting cakes don´t consumíng milk buckets only appear with forestry 
testing  forestry_1.10.2-5.2.16.314.jar and 
            forestry_1.10.2-5.2.16.310.jar

**Comment by raoulvdberge** [comment]
No need to close this issue.
