### ISSUE TITLE
[1.2.4] Autocrafting crash

### ISSUE THREAD

**Issue by chris54721** [raoulvdberge/refinedstorage#586]
#### Issue description:
The server crashed while an autocrafting job was running.
#### What happens:
The server crashes with the following stacktrace:
```
java.lang.NullPointerException: Ticking block entity
	at com.raoulvdberge.refinedstorage.apiimpl.autocrafting.CraftingPattern.getOutputs(CraftingPattern.java:203)
	at com.raoulvdberge.refinedstorage.apiimpl.autocrafting.task.CraftingStepCraft.execute(CraftingStepCraft.java:121)
	at com.raoulvdberge.refinedstorage.apiimpl.autocrafting.task.CraftingTask.update(CraftingTask.java:351)
	at com.raoulvdberge.refinedstorage.tile.TileController.func_73660_a(TileController.java:269)
	at net.minecraft.world.World.func_72939_s(World.java:1804)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:619)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:709)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
	at java.lang.Thread.run(Thread.java:745)
```

#### What you expected to happen:
No crash :P

#### Steps to reproduce:
I don't know exactly what may have caused this since the autocrafting job had been running for some time already. My guess would be a recipe containing an item which doesn't get used up and there aren't any output slots for it. In this case the job involved [IC2 Iron Plates](https://ftbwiki.org/Iron_Plate_(IndustrialCraft_2)).

#### Version:
- Minecraft: 1.10.2
- Forge: 12.18.2.2151
- Refined Storage: 1.2.4

I'm using the "All the Mods" modpack.
The issue occured on a server.

#### If a (crash)log is relevant for this issue, link it here:
http://hastebin.com/ujigakizew

**Comment by way2muchnoise** [comment]
[Try 1.2.1 ](https://minecraft.curseforge.com/projects/refined-storage/files/2342059 )that should fix this

**Comment by chris54721** [comment]
Getting the same crash after updating: http://hastebin.com/gelayumezu

**Comment by way2muchnoise** [comment]
You might have to [MCedit](http://www.mcedit.net/) away the controller. If that crash was on startup at least.

**Comment by chris54721** [comment]
Same crash happened on latest version (1.2.4)
http://hastebin.com/ujigakizew.scala

**Comment by chris54721** [comment]
Just happened again on latest All the Mods, updated issue accordingly. /cc @raoulvdberge

**Comment by raoulvdberge** [comment]
@way2muchnoise I think this one is fixed?

**Comment by way2muchnoise** [comment]
Dunno, I know what crashes but I have never been able to reproduce it.

**Comment by random51** [comment]
Not sure if this is the same issue, crash report looks a bit different. Autocrafting ic2 reactor and all sub-components causes server crash, version 1.2.4 in direwolf20 modpack.

http://hastebin.com/awipaqahem.scala

**Comment by random51** [comment]
I turned off use oredict on all patterns and made sure each of them were using ic2 plates and not ie plates, although the Pattern Grid/JEI is always putting in IE plates with the "+" button. The Processing pattern block on the other hand mirrors whatever is in JEI when you hit the button.

Anyway, after making those changes I can autocraft a nuclear reactor without crashing the server. Thought that info might come in handy in figuring out what is going on.

**Comment by way2muchnoise** [comment]
kinda odd that is ic2 related.

**Comment by random51** [comment]
I think that might have more to do with more people using autocrafting for lategame IC2 machines using oredict plates than people using autocrafting for earlygame IE machines using oredict plates.

I build all my IE stuff by hand, for example, but IC2 reactors in particular involve a ton of microcrafting so i automate it if possible.

**Comment by way2muchnoise** [comment]
@chris54721 @random51 when it crashed the server, did it display the preview correctly? Also does this still occur on something after 1.2.5 ?

**Comment by random51** [comment]
Yes. It showed all the required items and allowed me to start the process. I don't believe it crashed until it tried to make an iron plate or tried to request an iron plate to make the electronic circuit. I narrowed it down to that point by slowing working from the reactor down to each part, crashed all the way down to the electronic circuit. It could craft the parts for the circuit without crashing but try to craft the circuit and it'd would crash.

**Comment by chris54721** [comment]
Same here.

**Comment by way2muchnoise** [comment]
So I guess this can be hunted down to either the pattern being tagged ore dict and taken some plate it shouldn't take. Or Something is going very wrong somewhere. Is there a 100% reproducible scenario?

**Comment by annihone** [comment]
It is 100% reproducible. Recreated the pattern multiple times. Turning off ore dict helps.

**Comment by way2muchnoise** [comment]
Made it all little robuster with a null check. Should help out. Your craft might have the rescheduler kick in, but that will happen automatically :D

**Comment by annihone** [comment]
I'm not sure that hiding the exception is the solution actually. Is the ItemStack parameter truely expected to be null in some cases?

**Comment by raoulvdberge** [comment]
Way2muchnoise exposed.

**Comment by way2muchnoise** [comment]
The issue that I guess people abuse the oreDict pattern, maybe I should add some extra enforcing there. We'll see how this goes first. :D
