### ISSUE TITLE
Mekanism integrarion

### ISSUE THREAD

**Issue by BurovB** [raoulvdberge/refinedstorage#588]
#### What you expected to happen:I expected that will be add a new terminal and storage disks for working with gases

**Comment by BurovB** [comment]
What you expected to happen:Gas Interface.

**Comment by raoulvdberge** [comment]
nah, we're already doing a bunch of ugly hacks throughout the code for mekanism, we will certainly not add gasses support. (those gasses should be real fluids in the first place)

**Comment by hron84** [comment]
@BurovB also, you can still store mekanism gases as fluids with rotary condensator and fluids are already fully supported by RS.

**Comment by BurovB** [comment]
Ok(( I want to storage my gases in RS network because for storage gases now I must turn in into fluids by rotary candensator and back for using((((

**Comment by BurovB** [comment]
Think about it and when mod will be stable and you add something from your own ideas, please add this

**Comment by raoulvdberge** [comment]
We won't do a features that require loads of work for very little benefit.

**Comment by hron84** [comment]
I think same. There is no actual benefit for it and when you reach the state you need to store gases mass-creating rotary condensator is not a problem.

Also this fits with the original intention of Mekanism. Mass-storing gasses is designed about rotary condensators and gas tanks in the vanilla Mekanism and it should not be broken. ExtraCells2 under 1.7.10 did it and I didn't liked it.

**Comment by BurovB** [comment]
Ok
