### ISSUE TITLE
Crashes, issues and stuff.

### ISSUE THREAD

**Issue by Harith163** [raoulvdberge/refinedstorage#59]
Control middle clicking a wireless transmitter in creative mode with full upgrades crashes the game.

Also, shift clicking upgrades into the upgrade slot doesn't work consistently/ at all.

I can't find processing patterns at all in JEI. The wiki is not being all that clear on how to get processing patterns.

Crash log
A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at refinedstorage.tile.TileMachine.func_145841_b(TileMachine.java:177)
	at refinedstorage.tile.TileWirelessTransmitter.func_145841_b(TileWirelessTransmitter.java:33)
	at net.minecraft.client.Minecraft.func_184119_a(Minecraft.java:2525)
	at net.minecraftforge.common.ForgeHooks.onPickBlock(ForgeHooks.java:438)
	at net.minecraft.client.Minecraft.func_147112_ai(Minecraft.java:2517)
	at net.minecraft.client.Minecraft.func_184117_aA(Minecraft.java:2176)
	at net.minecraft.client.Minecraft.func_184118_az(Minecraft.java:1955)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['<PROFILE NAME>'/3, l='MpServer', x=10.61, y=4.25, z=8.46]]
	Chunk stats: MultiplayerChunkCache: 625, 625
	Level seed: 0
	Level generator: ID 01 - flat, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (8,4,8), Chunk: (at 8,0,8 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 1883652 game time, 3631849 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 2 total; [EntityPlayerSP['<PROFILE NAME>'/3, l='MpServer', x=13.33, y=-330.46, z=8.35], EntityPlayerSP['<PROFILE NAME>'/3, l='MpServer', x=10.61, y=4.25, z=8.46]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:453)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2647)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:395)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:310)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:395)
	at org.multimc.EntryPoint.listen(EntryPoint.java:170)
	at org.multimc.EntryPoint.main(EntryPoint.java:54)

-- System Details --
Details:
	Minecraft Version: 1.9
	Operating System: Mac OS X (x86_64) version 10.11.3
	Java Version: 1.8.0_73, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 933606616 bytes (890 MB) / 2388656128 bytes (2278 MB) up to 4772593664 bytes (4551 MB)
	JVM Flags: 2 total; -Xms512m -Xmx5120m
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.23 Powered by Forge 12.16.1.1906 Optifine OptiFine_1.9_HD_U_B1 93 mods loaded, 93 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAAAAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAAAAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.9-12.16.1.1906-universal.jar) 
	UCHIJAAAAAAAAA	Forge{12.16.1.1906} [Minecraft Forge] (forge-1.9-12.16.1.1906-universal.jar) 
	UCHIJAAAAAAAAA	CodeChickenCore{2.0.1.53} [CodeChicken Core] (minecraft.jar) 
	UCHIJAAAAAAAAA	regionalwater{1.7.10-1.0} [Regional Water] (minecraft.jar) 
	UCHIJAAAAAAAAA	autopackager{1.6.1} [AutoPackager] (autopackager-1.6.1.jar) 
	UCHIJAAAAAAAAA	bagginses{2.3.0b} [Bagginses] (Bagginses-1.9-2.3.0b.jar) 
	UCHIJAAAAAAAAA	basemetals{2.2.2} [Base Metals] (BaseMetals_1.9-2.2.2.jar) 
	UCHIJAAAAAAAAA	Baubles{1.2.0.2} [Baubles] (Baubles-1.9-1.2.0.2.jar) 
	UCHIJAAAAAAAAA	baublesstuff{2.0.8} [Baubles Stuff] (baublesstuff-2.0.8.jar) 
	UCHIJAAAAAAAAA	bdlib{1.11.0.14} [BD Lib] (bdlib-1.11.0.14-mc1.9.jar) 
	UCHIJAAAAAAAAA	betterbuilderswands{0.6.1} [Better Builder's Wands] (BetterBuildersWands-0.6.1-1.9r128+baa0aff.jar) 
	UCHIJAAAAAAAAA	JEI{3.3.3.200} [Just Enough Items] (jei_1.9-3.3.3.200.jar) 
	UCHIJAAAAAAAAA	BloodMagic{1.9-2.0.0-38} [Blood Magic: Alchemical Wizardry] (BloodMagic-1.9-2.0.0-38.jar) 
	UCHIJAAAAAAAAA	bookshelf{1.2.0.237} [Bookshelf] (Bookshelf-1.9-1.2.0.242.jar) 
	UCHIJAAAAAAAAA	Botania{r1.8-304} [Botania] (Botania-unofficial.r1.8-304.jar) 
	UCHIJAAAAAAAAA	Chameleon{1.9-2.1.3} [Chameleon] (Chameleon-1.9-2.1.3.jar) 
	UCHIJAAAAAAAAA	ChickenChunks{2.0.1.26} [ChickenChunks] (ChickenChunks-1.9-2.0.1.26-universal.jar) 
	UCHIJAAAAAAAAA	chisel{@VERSION@} [Chisel] (Chisel-MC1.9-0.0.4.14.jar) 
	UCHIJAAAAAAAAA	mcmultipart{1.1.1} [MCMultiPart] (MCMultiPart-1.1.1-universal.jar) 
	UCHIJAAAAAAAAA	chiselsandbits{9.18} [Chisels & Bits] (chiselsandbits-9.18.jar) 
	UCHIJAAAAAAAAA	cookingforblockheads{2.0.10} [Cooking for Blockheads] (CookingForBlockheads-mc1.9-2.0.10.jar) 
	UCHIJAAAAAAAAA	CustomMainMenu{2.0} [Custom Main Menu] (CustomMainMenu-MC1.9-2.0.jar) 
	UCHIJAAAAAAAAA	ElecCore{1.4.270} [ElecCore] (ElecCore-1.9-1.4.270.jar) 
	UCHIJAAAAAAAAA	deepresonance{1.1.4beta30} [DeepResonance] (deepresonance-1.9.0-1.1.4beta30.jar) 
	UCHIJAAAAAAAAA	eggs{1.0} [Eat the Eggs!] (Eat the Eggs-1.9-0.9 beta.jar) 
	UCHIJAAAAAAAAA	poweradvantage{2.1.1} [Power Advantage] (PowerAdvantage_1.9.0-2.1.1.jar) 
	UCHIJAAAAAAAAA	electricadvantage{2.0.3} [Electric Advantage] (ElectricAdvantage_1.9-2.0.3.jar) 
	UCHIJAAAAAAAAA	eplus{4.1.0.86} [Enchanting Plus] (EnchantingPlus-1.9-4.1.0.97.jar) 
	UCHIJAAAAAAAAA	EnderBags{1.0.2} [EnderBags] (EnderBags-1.9-1.0.2.jar) 
	UCHIJAAAAAAAAA	endercrop{1.9-1.2-1836} [Ender Crop] (endercrop-1.9.1.3.jar) 
	UCHIJAAAAAAAAA	enderthing{0.6.6} [Enderthing] (enderthing-1.9-0.6.6.jar) 
	UCHIJAAAAAAAAA	excore{1.5.3} [EXCore] (Excore-1.5.3-1.9.jar) 
	UCHIJAAAAAAAAA	ezstorage{1.0} [EZ Storage] (ezstorage-1.9-1.2.1.jar) 
	UCHIJAAAAAAAAA	fastleafdecay{1.6} [Fast Leaf Decay] (FastLeafDecay-1.9-1.6.jar) 
	UCHIJAAAAAAAAA	fluxducts{1.0.3} [Flux Ducts] (fluxducts-mc1.9-1.0.3.jar) 
	UCHIJAAAAAAAAA	fe{1.2} [Food Expansion] (FoodExpansion1.2-mc1.9.jar) 
	UCHIJAAAAAAAAA	Forestry{5.0.0.11} [Forestry] (forestry_1.9-5.0.0.11.jar) 
	UCHIJAAAAAAAAA	moreoverlays{1.3.1} [MoreOverlays] (moreoverlays-1.3.1-mc1.9.jar) 
	UCHIJAAAAAAAAA	FEI{1.0.10} [Forever Enough Items] (ForeverEnoughItems-1.0.10-1.9.jar) 
	UCHIJAAAAAAAAA	pressure{1.3.1.13} [Pressure Pipes] (pressure-1.3.1.13-mc1.9.jar) 
	UCHIJAAAAAAAAA	advgenerators{0.9.20.9} [Advanced Generators] (generators-0.9.20.9-mc1.9.jar) 
	UCHIJAAAAAAAAA	grapple_hooks{1.0.8} [Grapple Hooks] (Grapple Hooks-1.9-1.0.8.jar) 
	UCHIJAAAAAAAAA	gravestone{1.2.4} [Gravestone] (Gravestone Mod 1.2.4 .jar) 
	UCHIJAAAAAAAAA	Harvest{1.9-1.0.1-3} [Harvest] (Harvest-1.9-1.0.1-3.jar) 
	UCHIJAAAAAAAAA	HardcoreQuesting{5.0.0alpha1} [Hardcore Questing Mode] (HQM-New Heights-5.0.0alpha1.jar) 
	UCHIJAAAAAAAAA	inventorysorter{0.7.14+32} [Simple Inventory sorting] (inventorysorter-1.9-0.7.14+32.jar) 
	UCHIJAAAAAAAAA	IronChest{6.0.133.777} [Iron Chest] (ironchest-1.9-6.0.133.777.jar) 
	UCHIJAAAAAAAAA	itemscroller{0.4.3} [Item Scroller] (itemscroller-1.9-0.4.3.jar) 
	UCHIJAAAAAAAAA	japta{1.5.1} [JAPTA] (JAPTA-1.9-1.5.1.jar) 
	UCHIJAAAAAAAAA	journeymap{1.9-5.2.0b1} [JourneyMap] (journeymap-1.9-5.2.0b1-unlimited.jar) 
	UCHIJAAAAAAAAA	jeresources{0.4.5.27} [Just Enough Resources] (JustEnoughResources-1.9-0.4.5.27.jar) 
	UCHIJAAAAAAAAA	Login_Shield_MC1.9{1.2-21-g08fa29a} [Login Shield] (Login_Shield_MC1.9-1.2-21-g08fa29a.jar) 
	UCHIJAAAAAAAAA	mantle{1.9-0.10.0.jenkins132} [Mantle] (Mantle-1.9-0.10.0.jar) 
	UCHIJAAAAAAAAA	Morpheus{1.9-3.0.2} [Morpheus] (Morpheus-1.9-3.0.2.jar) 
	UCHIJAAAAAAAAA	MouseTweaks{2.6.2} [Mouse Tweaks] (MouseTweaks-2.6.2-mc1.9.jar) 
	UCHIJAAAAAAAAA	netherportalfix{1.0} [Nether Portal Fix] (netherportalfix-mc1.9-3.0.6.jar) 
	UCHIJAAAAAAAAA	nmsot{1.1.3-mc1.9} [No Mob Spawning on Trees] (NoMobSpawningOnTrees-1.1.3-mc1.9.jar) 
	UCHIJAAAAAAAAA	notenoughwands{1.3.3} [Not Enough Wands] (notenoughwands-1.9.0-1.3.3.jar) 
	UCHIJAAAAAAAAA	fodc{1.8.1} [Ore Dictionary Converter] (OreDictionaryConverter-1.8.1.jar) 
	UCHIJAAAAAAAAA	packingtape{0.5.1} [Packing Tape] (Packing Tape-0.5.1.jar) 
	UCHIJAAAAAAAAA	progressiveautomation{1.6.42} [Progressive Automation] (ProgressiveAutomation-1.9-1.6.42.jar) 
	UCHIJAAAAAAAAA	Psi{beta-31} [Psi] (Psi-beta-31.jar) 
	UCHIJAAAAAAAAA	quantumflux{2.0.6} [QuantumFlux] (quantumflux-1.9-2.0.6.jar) 
	UCHIJAAAAAAAAA	Quark{beta-18} [Quark] (Quark-beta-18.jar) 
	UCHIJAAAAAAAAA	randomthings{3.7} [Random Things] (RandomThings-MC1.9-3.7.jar) 
	UCHIJAAAAAAAAA	reborncore{2.2.0.77} [RebornCore] (RebornCore-1.9-2.2.0.77-universal.jar) 
	UCHIJAAAAAAAAA	redstonepaste{1.7.3} [Redstone Paste] (redstonepaste-mc1.9-1.7.3.jar) 
	UCHIJAAAAAAAAA	refinedstorage{0.6.6} [Refined Storage] (refinedstorage-0.6.6.jar) 
	UCHIJAAAAAAAAA	ResourceLoader{1.5} [Resource Loader] (ResourceLoader-MC1.9-1.5.jar) 
	UCHIJAAAAAAAAA	rftools{4.48} [RFTools] (rftools-1.9.0-4.48.jar) 
	UCHIJAAAAAAAAA	rftoolsdim{4.23beta38} [RFTools Dimensions] (rftoolsdim-1.9.0-4.23beta38.jar) 
	UCHIJAAAAAAAAA	Roguelike{1.5.0} [Roguelike Dungeons] (RoguelikeDungeons-1.9-1.5.0.jar) 
	UCHIJAAAAAAAAA	routerreborn{1.9-4.0.1.11b_universal} [Router Reborn] (RouterReborn-1.9-4.0.1.11b_universal.jar) 
	UCHIJAAAAAAAAA	SaltMod{1.8.c} [Salty Mod] (SaltyMod-1.9-1.8.c_beta-1.jar) 
	UCHIJAAAAAAAAA	shadowmc{3.1.0} [ShadowMC] (ShadowMC-1.9-3.2.1.jar) 
	UCHIJAAAAAAAAA	SimpleLabels{0.0.1} [SimpleLabels] (simplelabels-0.0.2.jar) 
	UCHIJAAAAAAAAA	simpleretrogen{2.2.3+4} [Simple Retrogen] (simpleretrogen-1.9-2.2.3+4.jar) 
	UCHIJAAAAAAAAA	SleepingBag{1.1.0} [Sleeping Bag] (SleepingBag-1.9-1.1.0.jar) 
	UCHIJAAAAAAAAA	soulshardstow{1.9-2.3.9-25} [Soul Shards - The Old Ways] (SoulShards-TOW-1.9-2.3.9-25.jar) 
	UCHIJAAAAAAAAA	steamadvantage{2.0.3} [Steam Advantage] (SteamAdvantage_1.9-2.0.3.jar) 
	UCHIJAAAAAAAAA	StorageDrawers{1.9-3.1.6} [Storage Drawers] (StorageDrawers-1.9-3.1.6.jar) 
	UCHIJAAAAAAAAA	tconstruct{1.9-2.3.0.jenkins193} [Tinkers' Construct] (TConstruct-1.9-2.3.0.jar) 
	UCHIJAAAAAAAAA	techreborn{1.1.0.258} [TechReborn] (TechReborn-1.9-1.1.0.258-universal.jar) 
	UCHIJAAAAAAAAA	Trashcans{2.0.2} [Trashcans] (Trashcans-1.9-2.0.2.jar) 
	UCHIJAAAAAAAAA	Waila{1.7.0} [Waila] (Waila-1.7.0-B2_1.9.jar) 
	UCHIJAAAAAAAAA	wailafeatures{@MAJOR@.@MINOR@.@REVIS@} [WAILA Features] (WAILA-features-1.9-0.3.1.6.jar) 
	UCHIJAAAAAAAAA	WailaHarvestability{1.1.7} [Waila Harvestability] (WailaHarvestability-mc1.9-1.1.7.jar) 
	UCHIJAAAAAAAAA	ICSE{1.0.0.0} [I Can See Everything] (Wawla-1.9-2.2.0.186.jar) 
	UCHIJAAAAAAAAA	wawla{2.2.0.178} [What Are We Looking At] (Wawla-1.9-2.2.0.186.jar) 
	UCHIJAAAAAAAAA	Woot{1.9-0.6.1-beta} [Woot] (woot-1.9-0.6.1-beta.jar) 
	UCHIJAAAAAAAAA	worldedit{6.1.2} [WorldEdit] (worldedit-forge-mc1.9-6.1.2-dist.jar) 
	UCHIJAAAAAAAAA	WorldEditCuiFe{1.0.2} [WorldEdit CUI Forge Edition] (WorldEditCuiFe-v1.0.2-mf-1.9-12.16.1.1887.jar) 
	Loaded coremods (and transformers): 
LoadingPlugin (Quark-beta-18.jar)
  vazkii.quark.base.asm.ClassTransformer
CodeChickenCorePlugin (CodeChickenCore-1.9-2.0.1.53-universal.jar)
  codechicken.core.asm.TweakTransformer
  codechicken.core.asm.DelegatedTransformer
  codechicken.core.asm.DefaultImplementationTransformer
NowWithRendering (redstonepaste-mc1.9-1.7.3.jar)
  net.fybertech.nwr.NowWithRendering
CCLCorePlugin (CodeChickenLib-1.9-2.0.1.6-universal.jar)
  codechicken.lib.asm.ClassHeirachyManager
  codechicken.lib.asm.RenderHookTransformer
FldLoadingPlugin (FastLeafDecay-1.9-1.6.jar)
  com.olafski.fastleafdecay.FldTransformer
LoadingPlugin (RandomThings-MC1.9-3.7.jar)
  lumien.randomthings.asm.ClassTransformer
RegionalWaterCore (RegionalWater-1.9.0-1.0.1.jar)
  com.velleth.regionalwater.RWClassTransformer
Reborn Core ASM (RebornCore-1.9-2.2.0.77-universal.jar)
  reborncore.asm.RebornClassTransformer
CCCDeobfPlugin (unknown)
  
LoadingPlugin (ResourceLoader-MC1.9-1.5.jar)
  lumien.resourceloader.asm.ClassTransformer
CCLCorePlugin (CodeChickenLib-1.9-2.0.1.23-universal.jar)
  codechicken.lib.asm.ClassHeirachyManager
  codechicken.lib.asm.RenderHookTransformer
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)

	List of loaded APIs: 
		* Baubles|API (1.1.1.0) from Baubles-1.9-1.2.0.2.jar
		* BloodMagic|API (@VERSION@) from BloodMagic-1.9-2.0.0-38.jar
		* BotaniaAPI (78) from Botania-unofficial.r1.8-304.jar
		* ChiselAPI (0.0.1) from Chisel-MC1.9-0.0.4.14.jar
		* ChiselAPI|Carving (0.0.1) from Chisel-MC1.9-0.0.4.14.jar
		* ChiselsAndBitsAPI (1.8.1) from chiselsandbits-9.18.jar
		* CoFHAPI (1.8.9R1.2.0B1) from RebornCore-1.9-2.2.0.77-universal.jar
		* CoFHAPI|block (1.8.9R1.2.0B1) from ProgressiveAutomation-1.9-1.6.42.jar
		* CoFHAPI|energy (1.8.9R1.2.0B1) from refinedstorage-0.6.6.jar
		* CoFHAPI|tileentity (1.8.9R1.2.0B1) from ProgressiveAutomation-1.9-1.6.42.jar
		* DR-API (1.0.4-Beta) from deepresonance-1.9.0-1.1.4beta30.jar
		* ElecCore|Abilities (#API_VER#) from ElecCore-1.9-1.4.270.jar
		* ForestryAPI|apiculture (4.8.0) from forestry_1.9-5.0.0.11.jar
		* ForestryAPI|arboriculture (4.2.1) from forestry_1.9-5.0.0.11.jar
		* ForestryAPI|circuits (3.1.0) from forestry_1.9-5.0.0.11.jar
		* ForestryAPI|core (5.0.0) from forestry_1.9-5.0.0.11.jar
		* ForestryAPI|farming (2.1.0) from forestry_1.9-5.0.0.11.jar
		* ForestryAPI|food (1.1.0) from forestry_1.9-5.0.0.11.jar
		* ForestryAPI|fuels (2.0.1) from forestry_1.9-5.0.0.11.jar
		* ForestryAPI|genetics (4.7.1) from forestry_1.9-5.0.0.11.jar
		* ForestryAPI|greenhouse (5.0.0) from forestry_1.9-5.0.0.11.jar
		* ForestryAPI|hives (4.1.0) from forestry_1.9-5.0.0.11.jar
		* ForestryAPI|lepidopterology (1.3.0) from forestry_1.9-5.0.0.11.jar
		* ForestryAPI|mail (3.0.0) from forestry_1.9-5.0.0.11.jar
		* ForestryAPI|multiblock (3.0.0) from forestry_1.9-5.0.0.11.jar
		* ForestryAPI|recipes (5.4.0) from forestry_1.9-5.0.0.11.jar
		* ForestryAPI|storage (3.0.0) from forestry_1.9-5.0.0.11.jar
		* ForestryAPI|world (2.1.0) from forestry_1.9-5.0.0.11.jar
		* jeresources|API (0.4.5.27) from JustEnoughResources-1.9-0.4.5.27.jar
		* journeymap|client-api (1.2-SNAPSHOT) from journeymap-1.9-5.2.0b1-unlimited.jar
		* journeymap|client-api-display (1.2-SNAPSHOT) from journeymap-1.9-5.2.0b1-unlimited.jar
		* journeymap|client-api-event (1.2-SNAPSHOT) from journeymap-1.9-5.2.0b1-unlimited.jar
		* journeymap|client-api-model (1.2-SNAPSHOT) from journeymap-1.9-5.2.0b1-unlimited.jar
		* journeymap|client-api-util (1.2-SNAPSHOT) from journeymap-1.9-5.2.0b1-unlimited.jar
		* JustEnoughItemsAPI (3.1.0) from jei_1.9-3.3.3.200.jar
		* McJtyLib (1.9.0-1.8.4) from mcjtylib-1.9.0-1.8.4.jar
		* pressureAPI (1.3.1.13) from pressure-1.3.1.13-mc1.9.jar
		* PsiAPI (2) from Psi-beta-31.jar
		* reborncoreAPI (2.2.0.77) from RebornCore-1.9-2.2.0.77-universal.jar
		* SoulShardsTOW|API (0.1.5) from SoulShards-TOW-1.9-2.3.9-25.jar
		* StorageDrawersAPI (1.7.10-1.2.0) from StorageDrawers-1.9-3.1.6.jar
		* StorageDrawersAPI|config (1.7.10-1.2.0) from StorageDrawers-1.9-3.1.6.jar
		* StorageDrawersAPI|event (1.7.10-1.2.0) from StorageDrawers-1.9-3.1.6.jar
		* StorageDrawersAPI|inventory (1.7.10-1.2.0) from StorageDrawers-1.9-3.1.6.jar
		* StorageDrawersAPI|pack (1.7.10-1.2.0) from StorageDrawers-1.9-3.1.6.jar
		* StorageDrawersAPI|registry (1.7.10-1.2.0) from StorageDrawers-1.9-3.1.6.jar
		* StorageDrawersAPI|render (1.7.10-1.2.0) from StorageDrawers-1.9-3.1.6.jar
		* StorageDrawersAPI|storage (1.7.10-1.2.0) from StorageDrawers-1.9-3.1.6.jar
		* StorageDrawersAPI|storage-attribute (1.7.10-1.2.0) from StorageDrawers-1.9-3.1.6.jar
		* techrebornAPI (1.1.0.258) from TechReborn-1.9-1.1.0.258-universal.jar
		* WailaAPI (1.3) from Waila-1.7.0-B2_1.9.jar
	Launched Version: MultiMC5
	LWJGL: 2.9.1
	OpenGL: NVIDIA GeForce GT 650M OpenGL Engine GL version 2.1 NVIDIA-10.8.14 310.42.15f01, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because ARB_framebuffer_object is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: No
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: DurzoCraft_WIP_1-9_Snapsho.zip, DurzoCraft_CT-Add-on.zip (incompatible), CodeCrafted Custom 1_9.zip
	Current Language: English (UK)
	Profiler Position: N/A (disabled)
	CPU: 8x Intel(R) Core(TM) i7-3615QM CPU @ 2.30GHz
	OptiFine Version: OptiFine_1.9_HD_U_B1
	Render Distance Chunks: 12
	Mipmaps: 0
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 2.1 NVIDIA-10.8.14 310.42.15f01
	OpenGlRenderer: NVIDIA GeForce GT 650M OpenGL Engine
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 8
[21:14:09] [Client thread/INFO]: [net.minecraft.init.Bootstrap:func_179870_a:557]: #@!@# Game crashed! Crash report saved to: #@!@# /Users/VS/Desktop/MC/MultiMC.app/Contents/MacOS/instances/1.9/minecraft/crash-reports/crash-2016-05-19_21.14.07-client.txt
AL lib: (EE) alc_cleanup: 1 device not closed
Process exited with code 255.
MultiMC: Log upload triggered at: 19 May 2016 21:14:23 +0530
MultiMC: Log upload failed!
MultiMC: Log upload triggered at: 19 May 2016 21:24:38 +0530
MultiMC: Log upload failed!

**Comment by raoulvdberge** [comment]
There is no "processing pattern" item. A processing pattern is just a type of pattern. You can make that type of pattern in the processing pattern encoder. You give that block normal patterns.

I'll investigate the crash

**Comment by raoulvdberge** [comment]
Fixed in latest version, the shift clicking has a very low priority for now.
