### ISSUE TITLE
Removing item from Storage Drawers Compacting Drawer connected via External Storage increases count of related items

### ISSUE THREAD

**Issue by VoidDaemon** [raoulvdberge/refinedstorage#591]
#### Issue description:
Removing items from a compacting drawer connected via external storage will increase the number of related items, i.e. removing a gold ingot will increase the gold nugget count by 9, and removing 9 nuggets will increase the ingot count by 1.
The numbers don't reflect the actual state - the compacting drawer shows the correct counts, and I can only remove items via the grid if they actually exist.
Breaking and replacing the external storage connector will reset to the correct counts.

#### What you expected to happen:
The numbers should properly reflect those of the compacting drawer.

#### Steps to reproduce:
1. Place 1 Gold Ingot in Compacting Drawer
2. Connect Compacting Drawer to RS system (Controller + Grid) via External Storage
3. In Grid, see 1 Gold Ingot and 9 Gold Nuggets
4. Remove Gold Ingot via Grid
5. Gold Ingot is removed, but number of Gold Nuggets increases to 18

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge: 12.18.2.2121
- Refined Storage: 1.2.3
- Storage Drawers: 1.10.2-3.4.2

Does this issue occur on a server? Not tested - I have a single player world.

#### If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here]

**Comment by moRt1MC** [comment]
I have same problem made a little video of the problem:

https://www.youtube.com/watch?v=ux0mw4a3ibs
