### ISSUE TITLE
Crashing on Server not much info but have 2 logs. 

### ISSUE THREAD

**Issue by KaneHart** [raoulvdberge/refinedstorage#593]
Don't have much info as people will not fess up lol.

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge: forge-1.10.2-12.18.2.2122-universal.jar
- Refined Storage: refinedstorage-1.2.3.jar

Does this issue occur on a server? [yes/no]
yes

#### If a (crash)log is relevant for this issue, link it here:
http://pastebin.com/6sf5BTcf
http://pastebin.com/CFrxYs4N

**Comment by Noobsloth** [comment]
Hiya KaneHart,

I don't know if you've found a solution or not. But in the log for this type of crashes there's always a snipit of information about the block being ticked. Here is that informaiton.

```
-- Block entity being ticked --
Details:
    Name: refinedstorage:controller // com.raoulvdberge.refinedstorage.tile.TileController
    Block type: ID #2734 (block.refinedstorage:controller // com.raoulvdberge.refinedstorage.block.BlockController)
    Block data value: 0 / 0x0 / 0b0000
    Block location: World: (-1412,65,-751), Chunk: (at 12,4,1 in -89,-47; contains blocks -1424,0,-752 to -1409,255,-737), Region: (-3,-2; contains chunks -96,-64 to -65,-33, blocks -1536,0,-1024 to -1025,255,-513)
    Actual block type: ID #2734 (block.refinedstorage:controller // com.raoulvdberge.refinedstorage.block.BlockController)
    Actual block data value: 0 / 0x0 / 0b0000
Stacktrace:
    at net.minecraft.world.World.func_72939_s(World.java:1282)
    at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:713)
```

You can see the block that's causing you're issue is at World: (-1412,65,-751), Chunk: (at 12,4,1 in -89,-47; contains blocks -1424,0,-752 to -1409,255,-737), Region: (-3,-2; contains chunks -96,-64 to -65,-33, blocks -1536,0,-1024 to -1025,255,-513).

All you need to do is kill that block, server will come back. 

My server had this issue, it seems to a import/export issue.

**Comment by way2muchnoise** [comment]
33e01ceb67f1a190b94ca1b030e908319445cdef and f33bf78226369168e64f535efc16d1cc1f209d4c might be a fix here as well.

**Comment by VallenFrostweaver** [comment]
Server crash from similar issue:

http://pastebin.com/SQSeQVQx

**Comment by Noobsloth** [comment]
@VallenFrostweaver You have a couple options...

First and a less risky, change your location to the block in question and change your gamemode to creative via editing your player.data file through NBT editor. You can download that out there on the interwebs. If it's crashing on boot, then this one won't help. But if it isnt, you can try to log in and punch it with creative mode. But you probably have a millisecond window to do this. So you need a decent PC so the boot time wont be too much. This is the elegant way but requires lots of luck.

Second which is a little more risky, so backup everything. Do this at your own risk. You can use the NBT editor to delete the tile entity from the region file. So to find the region file you look at the error location, but you'll need more info from this string as well... 

`Block location: World: (**-2713,183,2343**), Chunk: (at 7,11,7 in **-170,146**; contains blocks -2720,0,2336 to -2705,255,2351), Region: (**-6,4**; contains chunks -192,128 to -161,159, blocks -3072,0,2048 to -2561,255,2559)`

So you need to download region -6, 4. Open it up in NBT editor. There will be numbers listed to the right side of the column numbering the chunks. Go down to -170,146. Expand that tree, then expand the "Level" tree. Then go into the "TileEntities" there should be entries there, if there isnt then you have the wrong chunk or region file so go back and check that. Go through each one of those entries and find the entry that is at the coords -2713, 183, 2343 and delete the entire entry. The coordinates are listed within the entries' children. Click save, delete the region file thats on the server and reupload the one you just edited to the server and waaaalaa the tile entity is deleted. 

So r.-6.4.mca > Chunk [x,y] in world at (-170,146) > Level > TileEntities > (Broken Tile Entity [Delete this when you found the right one.]) > (x,y,z listed here)

If you need help, join my discord server discord.gg/5DM9T2Z

LAST RESORT, but you 100% should be able to do it with the NBT editor. Backup your server map. Delete Refined Storage from your mods folder. Launch your server and do /fml confirm. This will remove all of refined storage's blocks and items, so this is the very last ditch attempt. This used to only do loaded chunks, but i've been seeing some not so normal behavior from 1.10.2. So just count on a Refined storage wipe. If you have your entire base in Refined storage, I would honestly just chill and wait for way2muchnoise to push a fix.

Hope this helps.

**Comment by VallenFrostweaver** [comment]
Thank you for the thorough response!

**Comment by raoulvdberge** [comment]
I closed this issue because it has been fixed in dev
