### ISSUE TITLE
Redstone signal on crafter cancels task instead of pausing

### ISSUE THREAD

**Issue by brad18** [raoulvdberge/refinedstorage#596]
#### Issue description:
Crafting task cancelled if redstone signal is applied to the crafter.
#### What happens:
The craft gets cancelled after the first set of items are pushed.
#### What you expected to happen:
The first craft is sent, then the redstone signal pauses the craft then the craft resumes again.
#### Steps to reproduce:
1.Set up a crafter on a chest to output items for a crafting operation
2.Request an item to craft
3.Use a redstone signal to pause craft
...

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge: N/A
- Refined Storage:1.2.3

Does this issue occur on a server? [yes]

Hi, I am trying to autocraft some items with the enderio alloy smelters and I've ran into a problem. The enderio conduits don't round robin perfectly so I've worked out that if I put a certain number of items into a chest, it will work fine. Say that I want to make energetic alloy and I have 4 alloy smelters, I would then output 4 redstone ,4 glowstone  and 4 gold and it will put the items in the right place. In order to do this, I have the recipe to output 4 of each item then I pause the craft using a redstone signal and wait till the chest is empty again. The problem is that when the first batch of items goes in, the redstone signal will cancel the entire task instead of pausing it. I don't know if this intended or a bug so I thought I'd let you know.

Aside: Perhaps a feature similar to the AE blocking mode could be a useful addition.

**Comment by raoulvdberge** [comment]
Redstone signals on crafter don't pause it? They start a task...
