### ISSUE TITLE
Autocrafting not tracking incoming items correctly

### ISSUE THREAD

**Issue by brad18** [raoulvdberge/refinedstorage#597]
#### Issue description:
When autocrafting an item, the autocrafting will clear the task before all the items have returned
#### Steps to reproduce:
1.Set up some form of external autocrafting
2.Request item and watch the crafting monitor
3.The craft will clear from the monitor before all the items have returned

It's possible this could be linked to the run away autocrafting in a previous report.

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge: N/A
- Refined Storage: 1.2.3

Does this issue occur on a server? [yes]

**Comment by way2muchnoise** [comment]
I tracks all items incoming into the system. So you could have inserted them yourself or just some other task doing the same items. But yeah the tracking can be quite derpy. It is something that is being looked at.

**Comment by way2muchnoise** [comment]
Fixed in https://github.com/raoulvdberge/refinedstorage/issues/592#issuecomment-262097502
