### ISSUE TITLE
Modded 1.10.2 Crashed

### ISSUE THREAD

**Issue by ParshwaS** [raoulvdberge/refinedstorage#598]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  LoadingPlugin (Quark-r1.0-59.jar)
  IC2core (industrialcraft-2-2.6.87-ex110.jar)
  LoadingPlugin (RandomThings-MC1.10.2-3.7.6.jar)
  Default Options (DefaultOptions_1.10.2-6.1.5.jar)
  EnderCorePlugin (EnderCore-1.10.2-0.4.1.58-beta.jar)
  LoadingPlugin (ResourceLoader-MC1.9.4-1.5.1.jar)
  NWRTweak (redstonepaste-mc1.9.4-1.7.4.jar)
  FMLPlugin (InventoryTweaks-1.61-58.jar)
  TransformerLoader (OpenComputers-MC1.10.2-1.6.0.3-rc.1.jar)
  ShetiPhian-ASM (shetiphiancore-1.10.0-3.3.3.jar)
Contact their authors BEFORE contacting forge

// I just don't know what went wrong :(

Time: 08/11/16 11:54
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderException: java.lang.IllegalAccessError: tried to access field net.minecraft.item.ItemStack.field_77990_d from class cofh.api.energy.ItemEnergyContainer
	at net.minecraftforge.fml.common.LoadController.transition(LoadController.java:186)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:802)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:324)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:520)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:351)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.IllegalAccessError: tried to access field net.minecraft.item.ItemStack.field_77990_d from class cofh.api.energy.ItemEnergyContainer
	at cofh.api.energy.ItemEnergyContainer.receiveEnergy(ItemEnergyContainer.java:66)
	at com.raoulvdberge.refinedstorage.item.ItemNetworkItem.func_150895_a(ItemNetworkItem.java:117)
	at vazkii.botania.client.core.handler.CorporeaAutoCompleteHandler.updateItemList(CorporeaAutoCompleteHandler.java:61)
	at vazkii.botania.client.core.proxy.ClientProxy.postInit(ClientProxy.java:238)
	at vazkii.botania.common.Botania.postInit(Botania.java:215)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:600)
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:239)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:217)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:142)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:800)
	... 10 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.10.2
	Operating System: Windows 8 (amd64) version 6.2
	Java Version: 1.8.0_40, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 11210136 bytes (10 MB) / 1060372480 bytes (1011 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.32 Powered by Forge 12.18.2.2122 83 mods loaded, 83 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJ	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJ	FML{8.0.99.99} [Forge Mod Loader] (forge-1.10.2-12.18.2.2122.jar) 
	UCHIJ	Forge{12.18.2.2122} [Minecraft Forge] (forge-1.10.2-12.18.2.2122.jar) 
	UCHIJ	OpenComputers|Core{1.6.0.3-rc.1} [OpenComputers (Core)] (minecraft.jar) 
	UCHIJ	actuallyadditions{1.10.2-r70} [Actually Additions] (ActuallyAdditions-1.10.2-r70.jar) 
	UCHIJ	autopackager{1.6.3} [AutoPackager] (autopackager-1.6.3.jar) 
	UCHIJ	Psi{r1.0-41} [Psi] (Psi-r1.0-41.jar) 
	UCHIJ	Quark{r1.0-59} [Quark] (Quark-r1.0-59.jar) 
	UCHIJ	AutoRegLib{1.0-2} [AutoRegLib] (AutoRegLib-1.0-2.jar) 
	UCHIJ	Baubles{1.3.2} [Baubles] (Baubles-1.10.2-1.3.2.jar) 
	UCHIJ	betterbuilderswands{0.6.5} [Better Builder's Wands] (BetterBuildersWands-0.6.5-1.10r138+8595fc7.jar) 
	UCHIE	Botania{r1.9-337} [Botania] (Botania r1.9-337.jar) 
	UCHIJ	Chameleon{1.10-2.1.7} [Chameleon] (Chameleon-1.10-2.1.7.jar) 
	UCHIJ	JEI{3.13.2.360} [Just Enough Items] (jei_1.10.2-3.13.2.360.jar) 
	UCHIJ	mcmultipart{1.3.0} [MCMultiPart] (MCMultiPart-1.3.0-universal.jar) 
	UCHIJ	chiselsandbits{12.7} [Chisels & Bits] (chiselsandbits-12.7.jar) 
	UCHIJ	cookingforblockheads{4.2.26} [Cooking for Blockheads] (CookingForBlockheads_1.10.2-4.2.26.jar) 
	UCHIJ	MineTweaker3{3.0.13} [MineTweaker 3] (CraftTweaker-1.10.2-3.0.13.jar) 
	UCHIJ	ctgui{1.0.0} [CT-GUI] (CraftTweaker-1.10.2-3.0.13.jar) 
	UCHIJ	CustomMainMenu{2.0.2} [Custom Main Menu] (CustomMainMenu-MC1.10.2-2.0.2.jar) 
	UCHIJ	cyclicmagic{1.8.2} [Cyclic] (Cyclic-1.10.2-1.8.2.jar) 
	UCHIJ	ElecCore{1.6.328} [ElecCore] (ElecCore-1.10.2-1.6.328.jar) 
	UCHIJ	IC2{2.6.87-ex110} [IndustrialCraft 2] (industrialcraft-2-2.6.87-ex110.jar) 
	UCHIJ	OpenComputers{1.6.0.3-rc.1} [OpenComputers] (OpenComputers-MC1.10.2-1.6.0.3-rc.1.jar) 
	UCHIJ	deepresonance{1.2.9} [DeepResonance] (deepresonance-1.10-1.2.9.jar) 
	UCHIJ	defaultoptions{6.1.5} [Default Options] (DefaultOptions_1.10.2-6.1.5.jar) 
	UCHIJ	StorageDrawers{1.10.2-3.4.2} [Storage Drawers] (StorageDrawers-1.10.2-3.4.2.jar) 
	UCHIJ	bitdrawers{0.32} [Drawers & Bits] (DrawersBits-1.10.2-0.32.jar) 
	UCHIJ	endercore{1.10.2-0.4.1.58-beta} [EnderCore] (EnderCore-1.10.2-0.4.1.58-beta.jar) 
	UCHIJ	shetiphiancore{3.3.3} [ShetiPhian-Core] (shetiphiancore-1.10.0-3.3.3.jar) 
	UCHIJ	endertanks{1.4.3} [EnderTanks] (endertanks-1.10.0-1.4.3.jar) 
	UCHIJ	EnderZoo{1.10-1.2.3.43} [Ender Zoo] (EnderZoo-1.10-1.2.3.43.jar) 
	UCHIJ	valkyrielib{1.10.2-0.10.5d} [Valkyrie Lib] (valkyrielib-1.10.2-0.10.5d.jar) 
	UCHIJ	environmentaltech{1.10.2-0.10.5g} [Environmental Tech] (environmentaltech-1.10.2-0.10.5g.jar) 
	UCHIJ	ExtraUtils2{1.0} [ExtraUtils2] (extrautils2-1.10.2-alpha-1.2.2.jar) 
	UCHIJ	zerocore{1.10.2-0.0.8.1} [Zero CORE] (zerocore-1.10.2-0.0.8.1.jar) 
	UCHIJ	bigreactors{0.4.5.19} [Extreme Reactors] (ExtremeReactors-1.10.2-0.4.5.19.jar) 
	UCHIJ	fastleafdecay{v11} [Fast Leaf Decay] (FastLeafDecay-v11.jar) 
	UCHIJ	flatcoloredblocks{mc1.10-v4.2} [Flat Colored Blocks] (flatcoloredblocks-mc1.10-v4.2.jar) 
	UCHIJ	flighttweaks{0.0.6-alpha} [Flight Tweaks] (flighttweaks-1.10.2-0.0.6-alpha.jar) 
	UCHIJ	ftbl{0.0.0} [FTBLib] (FTBLib-1.10.2-3.1.2.jar) 
	UCHIJ	ftbu{0.0.0} [FTBUtilities] (FTBUtilities-1.10.2-3.1.2.jar) 
	UCHIJ	gravestone{1.5.8} [Gravestone] (GraveStone Mod 1.5.8.jar) 
	UCHIJ	guideapi{@VERSION@} [Guide-API] (Guide-API-1.10.2-1.9.4.jar) 
	UCHIJ	hopperducts{1.4.8} [Hopper Ducts] (hopperducts-mc1.9.4-1.4.8.jar) 
	UCHIJ	inventorytweaks{1.61-58-a1fd884} [Inventory Tweaks] (InventoryTweaks-1.61-58.jar) 
	UCHIJ	ironchest{1.10.2-7.0.11.797} [Iron Chest] (ironchest-1.10.2-7.0.11.797.jar) 
	UCHIJ	journeymap{1.10.2-5.2.4} [JourneyMap] (journeymap-1.10.2-5.2.4-unlimited.jar) 
	UCHIJ	jeresources{0.5.1.56} [Just Enough Resources] (JustEnoughResources-1.10.2-0.5.1.56.jar) 
	UCHIJ	mantle{1.10.2-1.1.1.194} [Mantle] (Mantle-1.10.2-1.1.1.jar) 
	UCHIJ	mercurius{1.0.1} [Mercurius] (Mercurius-1.10.2-1.0.1.jar) 
	UCHIJ	ModNameTooltip{1.6.0} [Mod Name Tooltip] (modnametooltip_1.10.2-1.6.0.jar) 
	UCHIJ	Morpheus{1.10.2-3.1.9} [Morpheus] (Morpheus-1.10.2-3.1.9.jar) 
	UCHIJ	mousetweaks{2.6.4} [Mouse Tweaks] (MouseTweaks-2.6.4-mc1.10.2.jar) 
	UCHIJ	multistorage{1.2.5} [Multi-Storage] (multistorage-1.10.0-1.2.5.jar) 
	UCHIJ	notenoughwands{1.4.0} [Not Enough Wands] (notenoughwands-1.10-1.4.0.jar) 
	UCHIJ	harvestcraft{1.9.4-1.10.2g} [Pam's HarvestCraft] (Pam's HarvestCraft 1.9.4-1.10.2h.jar) 
	UCHIJ	platforms{1.2.1} [Platforms] (platforms-1.10.0-1.2.1.jar) 
	UCHIJ	reborncore{2.8.1.64} [RebornCore] (RebornCore-1.10.2-2.8.1.64-universal.jar) 
	UCHIJ	quantumstorage{3.2.7} [QuantumStorage] (QuantumStorage-1.10.2-3.2.7.jar) 
	UCHIJ	randomthings{3.7.6} [Random Things] (RandomThings-MC1.10.2-3.7.6.jar) 
	UCHIJ	rangedpumps{0.3} [Ranged Pumps] (rangedpumps-0.3.jar) 
	UCHIJ	reborncore-mcmultipart{2.8.1.64} [reborncore-MCMultiPart] (RebornCore-1.10.2-2.8.1.64-universal.jar) 
	UCHIJ	redstonepaste{1.7.4} [Redstone Paste] (redstonepaste-mc1.9.4-1.7.4.jar) 
	UCHIJ	refinedstorage{1.2.3} [Refined Storage] (refinedstorage-1.2.3.jar) 
	UCHIJ	xreliquary{1.10.2-1.3.3.585} [Reliquary] (Reliquary-1.10.2-1.3.3.585.jar) 
	UCHIJ	ResourceLoader{1.5.1} [Resource Loader] (ResourceLoader-MC1.9.4-1.5.1.jar) 
	UCHIJ	rftools{5.59} [RFTools] (rftools-1.10-5.59.jar) 
	UCHIJ	rftoolsdim{4.45} [RFTools Dimensions] (rftoolsdim-1.10-4.45.jar) 
	UCHIJ	roots{0.204} [Roots] (roots-1.10.2-0.204.0.jar) 
	UCHIJ	shadowmc{3.4.9} [ShadowMC] (ShadowMC-1.10.2-3.4.9.jar) 
	UCHIJ	Signals{1.0} [Signals] (Signals-1.10.2-0.5.0-universal.jar) 
	UCHIJ	simplegenerators{1.10.2-0.10.5b} [Simple Generators] (simplegenerators-1.10.2-0.10.5b.jar) 
	UCHIJ	SleepingBag{1.3.0} [Sleeping Bag] (SleepingBag-1.10.2-1.3.0.jar) 
	UCHIJ	soundfilters{0.9_for_1.9} [Sound Filters] (SoundFilters-0.9_for_1.9.4.jar) 
	UCHIJ	tconstruct{1.10.2-2.5.6b.jenkins424} [Tinkers' Construct] (TConstruct-1.10.2-2.5.6b.jar) 
	UCHIJ	techreborn{1.4.10.95} [TechReborn] (TechReborn-1.10.2-1.4.10.95-universal.jar) 
	UCHIJ	theoneprobe{1.2.2} [The One Probe] (theoneprobe-1.10-1.2.2.jar) 
	UCHIJ	TinkersAddons{1.0.3} [Tinkers' Addons] (Tinkers' Addons-1.10.x-1.0.3.jar) 
	UCHIJ	tinkertoolleveling{1.10.2-1.0.1.DEV.f5def58} [Tinkers Tool Leveling] (TinkerToolLeveling-1.10.2-1.0.1.jar) 
	UCHIJ	Torcherino{4.2s} [Torcherino] (Torcherino-4.2s.jar) 
	UCHIJ	usefulnullifiers{1.2.1} [Useful Nullifiers] (usefulnullifiers-1.2.1.jar) 
	UCHIJ	weaponcaseloot{4.0.1} [WeaponCaseLoot] (weaponcaseloot-1.10.2-4.0.1.jar) 
	Loaded coremods (and transformers): 
LoadingPlugin (Quark-r1.0-59.jar)
  vazkii.quark.base.asm.ClassTransformer
IC2core (industrialcraft-2-2.6.87-ex110.jar)
  
LoadingPlugin (RandomThings-MC1.10.2-3.7.6.jar)
  lumien.randomthings.asm.ClassTransformer
Default Options (DefaultOptions_1.10.2-6.1.5.jar)
  net.blay09.mods.defaultoptions.coremod.DefaultOptionsClassTransformer
EnderCorePlugin (EnderCore-1.10.2-0.4.1.58-beta.jar)
  com.enderio.core.common.transform.EnderCoreTransformer
LoadingPlugin (ResourceLoader-MC1.9.4-1.5.1.jar)
  lumien.resourceloader.asm.ClassTransformer
NWRTweak (redstonepaste-mc1.9.4-1.7.4.jar)
  net.fybertech.nwr.NWRTransformer
FMLPlugin (InventoryTweaks-1.61-58.jar)
  invtweaks.forge.asm.ContainerTransformer
TransformerLoader (OpenComputers-MC1.10.2-1.6.0.3-rc.1.jar)
  li.cil.oc.common.asm.ClassTransformer
ShetiPhian-ASM (shetiphiancore-1.10.0-3.3.3.jar)
  shetiphian.core.asm.ClassTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 361.43' Renderer: 'GeForce GT 610/PCIe/SSE2'
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
		- chiselsandbitsIntegration (Enabled/Not Forced)
		- theoneprobeIntegration (Enabled/Not Forced)

**Comment by raoulvdberge** [comment]
This is not an RS bug, some other mod is shipping an invalid RF api.
