### ISSUE TITLE
Autocrafting deletes items if power is lost

### ISSUE THREAD

**Issue by kayila** [raoulvdberge/refinedstorage#599]
#### Issue description:

It appears that if autocrafting is working on a long process and power is lost to the controller block, any materials that had been pulled out of the system to support the crafting are erased. It's worth noting that my storage was full when the power went out.

#### What happens:
Items are are deleted from the crafting buffer when the system loses power

#### What you expected to happen:
Crafting to continue where it paused when power has been restored

#### Steps to reproduce:
1. Start several long multi-stepped crafting jobs
2. Cut power to the controller block and let it run out
3. Supply power to the controller block
4. Check the crafting monitor, no jobs are running
5. Look for materials in the crafting grid, materials were not retuirned

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge: 1.10.2-12.18.1.2094
- Refined Storage: 1.1.3

Does this issue occur on a server? yes

**Comment by way2muchnoise** [comment]
Move to 1.2.3 that fixes this issue. As autocrafting was completely rewritten
