### ISSUE TITLE
Autocrafting crash - save now crashes on startup and cannot be loaded

### ISSUE THREAD

**Issue by momerathe** [raoulvdberge/refinedstorage#600]
#### Issue description:

I had finished setting up the crafting patterns for IC2 electronic circuits. I order one to craft, and the game crashes. Now if I try to reload the world, it crashes immediately.

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge: 12.18.2.2120
- Refined Storage: 1.2

Does this issue occur on a server? [yes/no]

Single player

#### If a (crash)log is relevant for this issue, link it here:

initial crash (when I triggered the autocraft): http://pastebin.com/p6WMnWZA
subsequent crash (on world load): http://pastebin.com/gfWts8EZ

**Comment by momerathe** [comment]
I upgraded to 1.2.3 just to be sure - crash still happens.

http://pastebin.com/bYnRsLmJ

**Comment by way2muchnoise** [comment]
You'll have go use a tool like [MCEdit](http://www.mcedit.net/) to remove your controller from the world.

**Comment by momerathe** [comment]
The previous advice worked, but it's happened again, and this time I can't seem to recover from it.

I was, again, trying to autocraft IC2 stuff. I deleted the controlled in MCEdit (including deleting tick updates), and the game loaded - but when I place back a new controlled the game immediately crashed again.

http://pastebin.com/PC383uZ2

**Comment by way2muchnoise** [comment]
This was fixed in a61770a80d43fd04bc25a5a4e8fec2f25be019f7
