### ISSUE TITLE
Ender IO Tank Derpness

### ISSUE THREAD

**Issue by PONYRYDE** [raoulvdberge/refinedstorage#601]
#### Issue description:
Buckets and other fluid containers both empty and full get inserted into Ender IO Tanks on External Storage and are visible but may not be accessible via the grid.

#### What happens:

http://imgur.com/a/2egts

#### What you expected to happen:
None of the above.

#### Steps to reproduce:
1.
2.
3.
...

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge: 2119
- Refined Storage: 1.2.3

Does this issue occur on a server? [yes/no]

Unknown.

#### If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here]

**Comment by raoulvdberge** [comment]
More info please, e.g. how are your external storages on the tank configured..?

**Comment by PONYRYDE** [comment]
Okay. So it would appear to involve a third party as in a fresh install of just RS and EIO I can not reproduce it but in the Spilled Juice https://www.atlauncher.com/pack/SpilledJuice you just need a controller, grid, external storage -> tank. Any buckets thrown in the grid go into the tank and yes the external storage is set to fluid mode.

You probably have a better idea of the likely offenders but I'll try and narrow down the interaction as I have time.

The new disk drive model is great btw.

**Comment by raoulvdberge** [comment]
Are you sure your external storage is in fluid mode?

**Comment by PONYRYDE** [comment]
Mod interaction wasn't a thing just a coincidence.

If the priority of external storage (in fluid mode :p) is higher, then the fluid containers get stored there.
If the priority is the same, then where they get stored seems based on another factor (distance from controller maybe?) hence my initial failure to reproduce in a test world,

**Comment by PONYRYDE** [comment]
Same issue with a Forestry Bottler which also filled with water (I was importing) while the External Storage was still in item mode. It's almost a feature though it unfortunately disregards fluid filters.

**Comment by raoulvdberge** [comment]
So what is the issue here now? I have no idea what the problem is / you are suggesting?

**Comment by PONYRYDE** [comment]
To reiterate.

Ender IO Fluid Tanks are treated as item storage for any fluid containers (buckets, tanks, bottles etc.), either empty or full, when connected with an External Storage set to fluid mode.

For example. If I have a EIO Fluid Tank of water connected with an External Storage set to fluid mode and whitelisted for water only and I then put a bucket of lava into the RS system it will store the bucket of lava in the input slot of the EIO Fluid Tank. I can see it in the grid but cannot get it out and after I remove it from the tank it still remains visible in the grid.
