### ISSUE TITLE
Mod search should work with names instead of ID

### ISSUE THREAD

**Issue by xenoflot** [raoulvdberge/refinedstorage#602]
#### Issue description:
Working with a crafting grid. If I search @bota or @bloo then I get items from Botania and Blood Magic as expected. However @tin... doesn't return anything and I _definitely_ have plenty of TiCo items in my RS.

JEI is filtering correctly.

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge: 2122
- Refined Storage: 1.2.3
- tconstruct-1.10.2-2.5.6b

Does this issue occur on a server? [yes/]

#### If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here]

**Comment by raoulvdberge** [comment]
Currently it looks for mod ID instead of mod name, I might want to change this yes.

**Comment by way2muchnoise** [comment]
Maybe we should just abuse the JEI filter?

**Comment by raoulvdberge** [comment]
That would make JEI a dependency, I'd rather roll my own. I can write a quick parser for it.
