### ISSUE TITLE
Lighting Glitch

### ISSUE THREAD

**Issue by lixyth** [raoulvdberge/refinedstorage#603]
#### Issue description:

The more blocks are adjacent to the disk drive or the disk manipulator, the darker they get. As soon as at least 4 sides are covered, both RS blocks appear almost completely black.

#### Steps to reproduce:
1. Place disk drive / disk manipulator
2. Attach blocks on 3 or more sides

#### Version:

- Minecraft: 1.10.2
- Forge: 12.18.2.2120
- Refined Storage: 1.2.3

Does this issue occur on a server? - Yes

#### Screenshot:

http://i.imgur.com/q0Hs1op.png

**Comment by lixyth** [comment]
This seems to appear because smooth lighting is on.

**Comment by raoulvdberge** [comment]
optifine issue
