### ISSUE TITLE
Disk manipulator loses inventory on chunk unload

### ISSUE THREAD

**Issue by ewanm89** [raoulvdberge/refinedstorage#606]
Unloading chunk on server causes disk manipulator to lose it's inventory including it's disk drives.

- Minecraft: 1.10.2
- Forge: 12.18.2.2116
- Refined Storage: 1.2-beta5

Does this issue occur on a server? yes (wyldlife test server for wlyd's subs)

**Comment by raoulvdberge** [comment]
Any logs?

**Comment by SlagHoedje** [comment]
got this problem too, found an error in the logs: http://pastebin.com/hqHpXm8k

**Comment by raoulvdberge** [comment]
Great, then 1e01243973a73bd8d4ced4942a3799f201d2311e fixes this, thanks.
