### ISSUE TITLE
Server Calculation Crash

### ISSUE THREAD

**Issue by Kris6699** [raoulvdberge/refinedstorage#607]
#### Issue description:
Calculating Autocrafting for Enviromental Tech Solar Panel Tier 4 Crashes my Server.
#### What happens:
Server crahes.
#### What you expected to happen:
Autocrafting calculation to be shown.
#### Steps to reproduce:
1. Created autocrafting reciepes to craft Enviromental tech Tier 4 Solar Panel.
2. Ask to craft, 
3. Wait...
...

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge: 12.18.2.2116
- Refined Storage: 1.2.1

Does this issue occur on a server? Yes

#### If a (crash)log is relevant for this issue, link it here:
https://gist.github.com/Kris6699/632bba78bfbc8151cc1f2860a0981179
[pastebin/gist/etc link here]

**Comment by Kris6699** [comment]
Just updated to newest version.. Still happens

**Comment by Kris6699** [comment]
Now I get this whenever I try to craft "Stuff"

`b28f-b898605ade6d
09.11 20:58:18 [Server] INFO Exception in thread "RS crafting calculation" [20:58:18] [RS crafting calculation/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: java.lang.NullPointerException
09.11 20:58:18 [Server] RS crafting calculation/INFO [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at com.raoulvdberge.refinedstorage.api.util.IItemStackList.remove(IItemStackList.java:40)
09.11 20:58:18 [Server] RS crafting calculation/INFO [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at com.raoulvdberge.refinedstorage.apiimpl.autocrafting.task.CraftingTask.calculate(CraftingTask.java:225)
09.11 20:58:18 [Server] RS crafting calculation/INFO [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at com.raoulvdberge.refinedstorage.apiimpl.autocrafting.task.CraftingTask.calculate(CraftingTask.java:184)
09.11 20:58:18 [Server] RS crafting calculation/INFO [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at com.raoulvdberge.refinedstorage.apiimpl.autocrafting.task.CraftingTask.calculate(CraftingTask.java:85)
09.11 20:58:18 [Server] RS crafting calculation/INFO [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at com.raoulvdberge.refinedstorage.apiimpl.network.grid.ItemGridHandler.lambda$onCraftingPreviewRequested$0(ItemGridHandler.java:150)
09.11 20:58:18 [Server] RS crafting calculation/INFO [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.lang.Thread.run(Thread.java:745)`

**Comment by Kris6699** [comment]
For a few things this appears in my server log and auto crafting calculation doesn't show up `b28f-b898605ade6d
09.11 20:58:18 [Server] INFO Exception in thread "RS crafting calculation" [20:58:18] [RS crafting calculation/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: java.lang.NullPointerException
09.11 20:58:18 [Server] RS crafting calculation/INFO [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at com.raoulvdberge.refinedstorage.api.util.IItemStackList.remove(IItemStackList.java:40)
09.11 20:58:18 [Server] RS crafting calculation/INFO [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at com.raoulvdberge.refinedstorage.apiimpl.autocrafting.task.CraftingTask.calculate(CraftingTask.java:225)
09.11 20:58:18 [Server] RS crafting calculation/INFO [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at com.raoulvdberge.refinedstorage.apiimpl.autocrafting.task.CraftingTask.calculate(CraftingTask.java:184)
09.11 20:58:18 [Server] RS crafting calculation/INFO [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at com.raoulvdberge.refinedstorage.apiimpl.autocrafting.task.CraftingTask.calculate(CraftingTask.java:85)
09.11 20:58:18 [Server] RS crafting calculation/INFO [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at com.raoulvdberge.refinedstorage.apiimpl.network.grid.ItemGridHandler.lambda$onCraftingPreviewRequested$0(ItemGridHandler.java:150)
09.11 20:58:18 [Server] RS crafting calculation/INFO [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.lang.Thread.run(Thread.java:745)`

**Comment by way2muchnoise** [comment]
33e01ceb67f1a190b94ca1b030e908319445cdef and f33bf78226369168e64f535efc16d1cc1f209d4c might be a fix here as well.
