### ISSUE TITLE
Pattern Items Not Rendering Models

### ISSUE THREAD

**Issue by InsomniaKitten** [raoulvdberge/refinedstorage#609]
**Models aren't being rendered on the "shift view" for pattern items.**
TESR related?

Mod version: **[1.2.3](https://minecraft.curseforge.com/projects/refined-storage/files/2342285)**
Minecraft version: **[1.10.2](https://mojang.com/2016/06/minecraft-1101/)**
Forge version: **[12.18.2.2122](http://files.minecraftforge.net/maven/net/minecraftforge/forge/1.10.2-12.18.2.2122/forge-1.10.2-12.18.2.2122-changelog.txt)**

![2016-11-10_20 28 55](https://cloud.githubusercontent.com/assets/9869940/20193147/a3909bbc-a784-11e6-98ab-9c6ffa2ef7a9.png)
![2016-11-10_20 29 06](https://cloud.githubusercontent.com/assets/9869940/20193148/a39bd90a-a784-11e6-81d3-b8af432d8c42.png)

**Comment by raoulvdberge** [comment]
It seems like this happens with TESRs, the current code only supports models.

**Comment by way2muchnoise** [comment]
Given that the vanilla chest or a skull is a TESR we might want to look for fix.

**Comment by way2muchnoise** [comment]
`TileEntityItemStackRenderer` seems to be the issue here. Will have to discuss with fry when he gets back.

**Comment by BrianEdmonds** [comment]
I've obviously been seeing this for some time as well. How "long term" is this expected to be?

**Comment by raoulvdberge** [comment]
No idea, I think this is a Forge bug, or something in Forge that at least stops us of fixing this.

**Comment by way2muchnoise** [comment]
It is something in mc, which isn't patched to make sense by forge.
