### ISSUE TITLE
Problems with keep in stock system

### ISSUE THREAD

**Issue by r3pbl4** [raoulvdberge/refinedstorage#610]
#### Issue description:
A problem of creating keep in stock system using interface with crafting upgrade and external storage.
#### What happens:
It request much more items then it should.(It should request 64 sticks or 16 crafting operation, but it seems that it requesting 64, and making 256 sticks)
#### What you expected to happen:
I expect to have N number of items allways in the system. If I have less the interface with crafting upgrade should request to craft the amount of item to refill itself up to N items.
#### Steps to reproduce:
1. Make a system that have some wood, have autocrafting that know how to turn wood logs into sticks. 
2. Place down an interface, and the external storage at the down of interface. Insert to interface crafting upgrade.
3. Say to keep 64 sticks in the interface
Images:
Result of issue:
http://imgur.com/a/7EtI4
Interface configuration:
http://imgur.com/a/0qII2
A look on the system:
http://imgur.com/a/gyXZe
...

#### Version (Make sure you are on the latest version before reporting): 

- Minecraft: 1.10.2
- Forge: 12.18.2.2120
- Refined Storage: 1.2.3

Does this issue occur on a server? [yes/no] Yes.

#### If a (crash)log is relevant for this issue, link it here: 

[pastebin/gist/etc link here]

**Comment by raoulvdberge** [comment]
next RS version will block external storages on network items as this causes buggy behavior

**Comment by r3pbl4** [comment]
So u wont be able to make keep in stock system like in AE?

**Comment by raoulvdberge** [comment]
maybe in the future!
