### ISSUE TITLE
Tabs in monitors feature request

### ISSUE THREAD

**Issue by r3pbl4** [raoulvdberge/refinedstorage#611]
I have a good idea. There is a view cell, that are good, I used them to blacklist uranium from ic2, but there can be better thing like a tabs!

The general idea is in screenshot:
http://imgur.com/a/iBmPv

So u can make a TAB CARD, and filter it by saying which items; which items from mod; oredictionary for ores u should see when u open a tab. And u can also search in the tab, add a picture of a block for a tabs...

This will be very cool and useful feature for fast switching between a group of items.

How I see the usage of it:
1) If I want to fast check some of my resources, I need creating a TAB CARD, saying to it show only iron, copper, tin, redstone, glowstone.... I also probably want to say that some of the resources should be oredicted.

2) I can use 1 monitor for showing me all my stuff without Uranium, and at the new tab I can see only uranium.

3) U can favorite ur the most searchable mods.

**Comment by raoulvdberge** [comment]
I actually quite like this idea.

**Comment by r3pbl4** [comment]
Btw, forgot to notice. There also options like sorting by/display mode/.... can be local for every tab. For example:

1) I want to see ingots tab sorting by quantity.
2) I want to see magic mods tab stuff sorting by name.
3) I want to see just craftable items, but in new tab.

And also the ULTIMATE GRID, in which u can see both fluids and items in different tabs.
It can be crafted from both monitor + TAB CARD in solderer, and have 2 basic tabs - fluid and item one.


And also some of my sick fantasy - delete all grids blocks, and have only 1 block of monitor.

So the idea to add to the monitor certain GRID TABS to make it from block that do nothing block that will do something. So U will able really have some ULTIMATE GRID with crafting grid, pattern grid, crafing monitor grid, fluid grid all in one + custom tabs.

**Comment by BrisingrAerowing** [comment]
I like this idea as well. I would find it SO useful! Thumbs up from me! 👍

**Comment by Kithros** [comment]
Maybe a item , like a "Tab Cell" that you can put multiple view cell filters in. and when you insert that into the grid it creates the new tab. This way you can customize it the way you want it, and it takes resources to get there. not just as an option, but as a progression... or make an advanced grid with this functionality

**Comment by raoulvdberge** [comment]
This has been implemented!

It reuses the grid filter system, assign an icon to a grid filter to make it a tab.

![x](https://pbs.twimg.com/media/CzGXyJAWgAABwyg.jpg:large)

![x](https://pbs.twimg.com/media/CzGX7piXUA0Fhpj.jpg:large)
