### ISSUE TITLE
Autocrafting Storage Disk

### ISSUE THREAD

**Issue by justinjrichards** [raoulvdberge/refinedstorage#612]
#### Steps to reproduce:
1. create recipe for 1k storage part and insert in crafter.
2. create recipe for 4k storage part and insert in crafter.
3. create recipe for 4k storage disk and insert in crafter.
4. order a 4k storage disk from the grid screen. it shows that storage housing is a missing ingredient but they are in fact present in the system.
...

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge: 12.18.2.2120
- Refined Storage: refinedstorage-1.2.jar

Does this issue occur on a server? [yes/no] yes

#### If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here]

**Comment by justinjrichards** [comment]
![2016-11-10_17 47 52](https://cloud.githubusercontent.com/assets/22295299/20199102/f1c886bc-a76d-11e6-8d2b-834f8e9048ed.png)
![2016-11-10_17 47 59](https://cloud.githubusercontent.com/assets/22295299/20199100/f1c69b4a-a76d-11e6-8b5b-3f9d9282fef7.png)
![2016-11-10_17 48 02](https://cloud.githubusercontent.com/assets/22295299/20199101/f1c84422-a76d-11e6-97f8-863e1e3050b7.png)
![2016-11-10_17 48 14](https://cloud.githubusercontent.com/assets/22295299/20199099/f1c5f14a-a76d-11e6-9141-c0c1fbfe4fbf.png)
![2016-11-10_17 48 19](https://cloud.githubusercontent.com/assets/22295299/20199103/f1cb07b6-a76d-11e6-883a-e06e2cf46e8b.png)

**Comment by way2muchnoise** [comment]
Could you share pictures of your patterns? For example did you have ore dict turned on?

**Comment by raoulvdberge** [comment]
Maybe he doesn't have enough materials for the storage housing?

**Comment by justinjrichards** [comment]
![2016-11-11_10 02 04](https://cloud.githubusercontent.com/assets/22295299/20221239/2bbf215e-a7f6-11e6-88ae-c76823f23902.png)
![2016-11-11_10 02 15](https://cloud.githubusercontent.com/assets/22295299/20221238/2bbec89e-a7f6-11e6-823c-a6125c4bbb07.png)
![2016-11-11_10 02 27](https://cloud.githubusercontent.com/assets/22295299/20221237/2bbdb774-a7f6-11e6-9a6b-98bf8e028fa5.png)
![2016-11-11_10 02 35](https://cloud.githubusercontent.com/assets/22295299/20221241/2bc15316-a7f6-11e6-8b23-b16b0d51ba4d.png)
![2016-11-11_10 02 58](https://cloud.githubusercontent.com/assets/22295299/20221240/2bc0a0c4-a7f6-11e6-864d-9692e55b5b4f.png)

**Comment by justinjrichards** [comment]
i remade all these recipes making sure oredictionary was turned on but it still shows that im missing the housings. still have them premade sitting in storage as well.

**Comment by justinjrichards** [comment]
just noticed that if i try crafting from JEI using the "move items" button with recipes that include the storage housing, such as the disk manipulator, that it doesnt move them to the crafting grid even though they are in the storage system. im assuming something with the ore dictionary or id for the storage housing.
