### ISSUE TITLE
Crash on world load

### ISSUE THREAD

**Issue by Flibio** [raoulvdberge/refinedstorage#613]
I'm trying to load a world in my modpack, but upon loading RefinedStorage appears to crash. This may be caused by RandomThings or Ender IO, just let me know.

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge: 12.18.2.2123
- Refined Storage: 1.2.4

[Log](http://hastebin.com/lenudujato.scala)

**Comment by way2muchnoise** [comment]
Seems to be a randomthings issue. But it is really odd as he tries to cast one of our TE's to one of his. Meaning he should really have a check there. You should go and report it at random things.
