### ISSUE TITLE
Autocraft with Bloodmagic

### ISSUE THREAD

**Issue by Emby93** [raoulvdberge/refinedstorage#614]
#1 Bloodmagic Autocraft Patterns : Any pattern that requires a Blood Orb, if attempted to be crafted multiple times, ends up with getting stuck crafting requests, also adding to it making more slates when there's already slates in the grid. Basically it'll attempt to craft a blood rune, get stuck, proceed with crafting slates even when not needed, but not actually craft a blood rune.

#2 Connected Grid : I play on a server with a few friends, and we notice items that just vanish. Sometimes it'll be items missing, other times it'll be crafts missing. Taking out a wire and "plugging it back in" seems to work, but kind of annoying to have to do. 

Sorry if my explanation of whats going on with the blood magic isn't the best, I'm not very good with wording on issues.

**Comment by way2muchnoise** [comment]
Getting stuck is a really broad explanation that doesn't really help us track down the actual issue. I will add Blood Magic to my dev env and take a look. But if you could add some pictures, videos, ... of this issue that would be helpful.

Also don't make 2 issues as one. Please edit the second one out and make it its own issue.

**Comment by Emby93** [comment]
Pictures : http://imgur.com/a/tNMlQ

the first picture shows the requirements, it counts as missing blood orbs, but shows one. Typically in mods with auto-crafting, it would finish the first craft, and then put the blood orb back in, and then pull it back out for the next. However after the second to third one it stops putting the orb back in, causing it to "stick" at that point. This was done with a 10x craft. The second picture shows where it ends, it crafts the Slates needed usually, though occasionally it'll hang with the bloodorb and either stop crafting them or keep crafting them past the point.

**Comment by raoulvdberge** [comment]
upgrade to 1.2.x

**Comment by raoulvdberge** [comment]
FYI, it's good practice to check if you're on the latest version before updating.....

**Comment by Emby93** [comment]
Maybe you should contact the pack owner of Infinity Lite then.

**Comment by raoulvdberge** [comment]
No, I shouldn't. You need to look if you're on latest before reporting.
