### ISSUE TITLE
Disk Drive inventory desync

### ISSUE THREAD

**Issue by TotalHamman** [raoulvdberge/refinedstorage#615]
#### Steps to reproduce:
1. Open Disk Drive
2. Pick up Storage Disk
3. Place in empty slot in drive
4. Disk does not drop off cursor

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge: 12.18.2.2123
- Refined Storage: 1.2.3

Does this issue occur on a server? [yes/no]  Yes

#### If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here]

**Comment by raoulvdberge** [comment]
This is not an RS issue as I can't reproduce this. This is most likely something with your server or crossmod interference.
