### ISSUE TITLE
Extreme lag in grid window

### ISSUE THREAD

**Issue by SubsterNL** [raoulvdberge/refinedstorage#616]
#### Issue description:
Dragging items in your inventory on the (crafting) grid window causes a lot of lag to the point where it is hard to even drag something.

Refined storage 1.2.1 with latest forge on 1.10.2 in a unstable type modpack but most mods updated to latest version

Using jei_1.10.2-3.13.2.361

**Comment by raoulvdberge** [comment]
Please create a profiling report, because I can't do *anything* with this.

Explanation here:

https://github.com/raoulvdberge/refinedstorage/issues/523#issuecomment-256419502

**Comment by raoulvdberge** [comment]
Closing due to lack of extra info. If you send us the report, I'll reopen.
