### ISSUE TITLE
Crafting only ever uses 1 machine and not all available for that craft

### ISSUE THREAD

**Issue by SubsterNL** [raoulvdberge/refinedstorage#617]
#### Issue description:
Example. 4 Sag mills with 4 crafters coupled to it. If I try to sagmill 300 ore from 2 different types it only ever uses 1 of the sag mills. Same applies to alloy smelters or any other machine that you use. It appears crafting in refined storage can only ever use 1 type of machine.

Crafting is extremely buggy and not very logical at all.. It always waits for 1 thing to complete before moving on even though there are more machines capable of continuing. 

Latest 1.2.1 version of RS and latest forge etc. Been happening on all version of forge and mods I've been using.

**Comment by raoulvdberge** [comment]
Crafting uses 1 machine only. It doesn't spread out its tasks, yet.

**Comment by SubsterNL** [comment]
Thx for clearing that up.
