### ISSUE TITLE
Milk not exportable

### ISSUE THREAD

**Issue by MainFreak** [raoulvdberge/refinedstorage#618]
#### Steps to reproduce:
1. Put Milk in any kind of Tank.
2. Import Milk with a Fluid Interface
3. Try to pull it out with a Grid or any kind of pipe f.e. EnderIO Fluid Conduits

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2 ( Hermitpack )
- Forge: 12.18.2.2099
- Refined Storage: 1.1.3

Does this issue occur on a server? Yes

#### If a (crash)log is relevant for this issue, link it here:
No Crashes

**Comment by raoulvdberge** [comment]
don't just check the changelog.. try the version before reporting -.-

**Comment by rendragnet** [comment]
So this still appears to be an issue..   No combination of trying to click, shift-click, dropping, etc, a milk bucket into/over the output slot of a Fluid Interface will let me get Milk exporting :\ Is this not possible?  Or am I just totally missing something obvious? :)  Thanks :)

Refined Storage 1.8.8 on MC 1.15.2  (FTB Omnia)
