### ISSUE TITLE
External StorageBus+OsmiumOre+QuantumStorage=No Ore in System

### ISSUE THREAD

**Issue by Drahnier016** [raoulvdberge/refinedstorage#622]
Don´t know where to go with that issue becouse there are 3 Mods Involved so i start here.

Issue description: External StorageBus attached to a Quantumstorage (Item)+to the Ref.Stor.System
                             Put (Mekanism) Osmium Ore Into the Quantum Storage.
                             Set The Filter of the Bus for Osmium Ore.
I was testing a bit and if i put the Ore into another Storage like DiamondChest, the System CAN see the Ore. 

What happens: The Ref.Stor.System can´t see the Ore

What you expected to happen: the Opposit of corse ^^

Steps to reproduce: 
1. Fill QuantumStor. with some (Mekanism) OsmiumOre 
2. Atach a Ext.StorageBus to the QuantumStor.
3. Set the Filter For OsmiumOre
4. Take a look in the Ref.System

Version 1.1.3

- Minecraft: 1.10.2
- Forge:
- Refined Storage:

Does this issue occur on a server? Yes

**Comment by way2muchnoise** [comment]
You should really update to a later release as 1.1.3. See [CurseForge](https://minecraft.curseforge.com/projects/refined-storage)
