### ISSUE TITLE
Interdimensional Network not working

### ISSUE THREAD

**Issue by darkshadow543** [raoulvdberge/refinedstorage#623]
#### Issue description:
If I try to place a network receiver in a different dimension, it does not work after upgrading the transmitter.
#### What happens:
I was using a mod called "utility worlds" and created a new dimension, I right clicked the receiver with a network card, and went back to my base.  I put the network card in the transmitter and went back to the transmitter.  When I got back to the dimension, I found that the receiver was still dark 
#### What you expected to happen:
For the transmitter and receiver to link.
#### Steps to reproduce:
1.  Set up a basic system with a controller and a transmitter and put an interdimensional upgrade in the transmitter.
2.  Set a receiver in another dimension and right click it with a network card(  The dimension ID this bug was occurring in was 32.)
3.Go back to the system and place in the network card.  Go back to the dimension and the receiver is still dark(attaching a grid, or causing a block update does not work, and the grid will not work either).
#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge: Most Recent
- Refined Storage: Most Recent

Does this issue occur on a server? [yes/no]

#### If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here]

**Comment by raoulvdberge** [comment]
Are both areas chunkloaded?

**Comment by robertm1771** [comment]
I seem to have same type problem tried a couple options to keep chunks loaded as well as a number of ways to get the network to function as above with no luck. But am using an rftools dim. Transmitter shows proper dimension in its UI as well as link location on card is correct

**Comment by darkshadow543** [comment]
The main controller and transmitter were chunk loaded, and then entered the world. One other note When I reset the transmitter, by turning it off and on, by moussing through the Redstone modes, It eventually connected.

**Comment by raoulvdberge** [comment]
This will be fixed when #370 is fixed

**Comment by tomasdev** [comment]
Having this same bug, but can't fix it with changing the redstone mode on the transmitter, sadly. :(
