### ISSUE TITLE
Feature Request / bug maybe

### ISSUE THREAD

**Issue by lordshade88** [raoulvdberge/refinedstorage#624]
Would it be a pain to put in something like Formating a disk? like right cliking the disk or on a special workbench create a filter to allow just some items to go into the disk. 

So to have 1 disk for ores 1 disk for monster loot 1 for food, etc.
i think AE 1 or 2 had like a formating bench.

Also i got the filter upgrades to put on diferent grids and i was going to have a some to just see what i wanted in each grid like ores other for food etc, but the grid didnt show anything of what i had filtered. like it wasnt working right.

**Comment by raoulvdberge** [comment]
you can already filter a disk, look at the top slots in the disk drive
