### ISSUE TITLE
Acces to Disk Drives out of Network *feature request*

### ISSUE THREAD

**Issue by jelaw21** [raoulvdberge/refinedstorage#625]
#### Issue description:
I was wondering if it would be possible to make the disc drive accessible out of network, like right clicking them from hotbar. Then we could load item on the discs and plug them into the network. Otherwise, their is no difference between blocks and discs other than space saving.

**Comment by raoulvdberge** [comment]
So you want to insert disks by just clicking on the disk drive?

**Comment by jelaw21** [comment]
No I would like to be able to put items on the disks then put the disc into
the drive.

**Comment by raoulvdberge** [comment]
Nah, don't think that feature is needed.
