### ISSUE TITLE
no machine found error

### ISSUE THREAD

**Issue by Tntdruid** [raoulvdberge/refinedstorage#627]
#### Issue description:
no machine found when crafting a stick
#### What happens: 
Crafting get stuck whit "no machine found"
#### What you expected to happen:
Get 4 Sticks?
#### Steps to reproduce:
1. make an pattern
2. try craft a stick
3.
...

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge:12.18.2.2123
- Refined Storage: 1.2.4

Does this issue occur on a server? [yes/no]
no
#### If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here]
http://imgur.com/5XspAH1

**Comment by way2muchnoise** [comment]
You need to make a crafting pattern in the pattern grid. Not a processing pattern (which is made in the encoder). Processing patterns are only for machine. Crafting tasks are crafting patterns.

**Comment by Tntdruid** [comment]
Ah, thanks, first time playing whit this mod :)
