### ISSUE TITLE
[Feature Request] Autocrafting when the item already exists

### ISSUE THREAD

**Issue by GameSlayar** [raoulvdberge/refinedstorage#628]
## Feature description:
There's currently no way (unless I'm horribly mistaken, in which case this will be deleted/closed) to autocraft an item in grid __IF__ that item already exists in the network. In _AE2_ this is usually middle click, but I've tried many combinations of CTRL and ALT, middle clicks and all - and I can't seem to find a way to conveniently _make __more___ of something.

#### If this doesn't exist yet, please add it c:

**Comment by way2muchnoise** [comment]
ctrl + shift + click will force open the crafting thing
