### ISSUE TITLE
[Request] Make transmitter/receiver setup great again

### ISSUE THREAD

**Issue by Alaberti** [raoulvdberge/refinedstorage#630]
Currently, to set-up a remote system requires placing the receiver, pairing the network card, returning to the controller sit and putting it into the transmitter, and the returning to the remote site. If you move the receiver , you have to pair it with the transmitter by travelling back to the main system again. 

This feels very cumbersome - instead, would it be possible to have a transmitter set at the controller that you point your remote receiver to (allowing immediate setup of a new facility without backtracking)? Also, while I'm fine with them being in a one-to-one pair system, it would be much more scalable if there was a many-to-one system, allowing me to have multiple receivers at remote sites pointed to one transmitter at the controller site. 

That said, I'm _happily_ having what the kids call a #firstworldproblem with your work.

**Comment by raoulvdberge** [comment]
I like the current way more.
