### ISSUE TITLE
Crash caused by a clash between multipart and refined storage

### ISSUE THREAD

**Issue by TheMprs** [raoulvdberge/refinedstorage#632]
#### Steps to reproduce: 
i honestly don't know
...

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge: 12.18.2.2123
- Refined Storage: 1.2.4

Does this issue occur on a server? im playing on a singleplayer world

#### If a (crash)log is relevant for this issue, link it here:
http://pastebin.com/3KQdJM8V

**Comment by raoulvdberge** [comment]
After talking with ama for a very brief period of 5 minutes, we've both come to the conclusion that some other mod that utilises the MCMP API didn't update yet to utilise new API features.

A big suspect is Chisel&Bits. But Algo is fixing that apperently. So I can close this.
