### ISSUE TITLE
Horrible performance (30 FPS drop) with larger networks..

### ISSUE THREAD

**Issue by SubsterNL** [raoulvdberge/refinedstorage#633]
Any 1.10.2.

On a good computer with a GTX 1060 I started noticing that my framerates where starting to become horribly choppy and chugging along.

I thought it might have something to do with RS since it isn't even tested on larger networks (the author said so himself). And my network isn't even large. Only about 100 64K disks and my entire network is grouped together.. No interdimensional stuff, nothing. 100x 64K disks is nothing in modded MC today.

Hopefully RS will get some major opimisation because right now I'm done with it.

Killing my RS Controller (thus taking everyhting offline) immidiately gave me back my 30 FPS and at 60 FPS solid again. (CPU usage down from 99% to 25%)

And not doing any autocrafting as it is way to buggy at its current state.

**Comment by way2muchnoise** [comment]
You might want to create a profiling thing, see https://github.com/raoulvdberge/refinedstorage/issues/523#issuecomment-256419502

Otherwise we can't locate the issue. Also what RS version are you on?

**Comment by raoulvdberge** [comment]
> I thought it might have something to do with RS since it isn't even tested on larger networks (the author said so himself).

Where did I say this?

> Hopefully RS will get some major opimisation because right now I'm done with it.

Get a profiling report because I'm done with your report, as it's useless without NPS file.

> And not doing any autocrafting as it is way to buggy at its current state.

We're working on it, man. Don't forget you're playing a mod which we make for FREE in our PART TIME. Show some respect.

**Comment by SubsterNL** [comment]
Uhm???

I love RS. Don't think I was disrespectful but since it was more a general performance hit I didn't think it was needed to include any files. And not everone might be as good in troubleshooting, providing reports from several tools. If you are simply going to ignore any issue report then we might as well not report anything.  I will see what will happen this week and add a report when I can be more specific on the problem. 

Again, apologies if it was seen as disrespectful. I do greatly appreciate the free time that is spent creating a great mod.

**Comment by raoulvdberge** [comment]
You sound very disrespectful and rude, so instead of putting words in my mouth (which you are doing for the second time already with "If you are simply going to ignore any issue report then we might as well not report anything", I NEVER said I was going to ignore your issue) provide the nps file.

**Comment by SubsterNL** [comment]
Likewise.

**Comment by raoulvdberge** [comment]
I'm closing this issue due to a missing profiling report, if you post it i'll reopen.
