### ISSUE TITLE
Request: make items autocraftable even if there are already some in the system

### ISSUE THREAD

**Issue by Yadokingu** [raoulvdberge/refinedstorage#636]
In Ae2 you could middle click on an item and it would bring up the auto crafting option, when there was a pattern set up for it, regardless if there were already some of the items in the system or not. I've searched a lot but can't find a compareable option for refined storage, which leads me to believe that it doesn't exist.
It's inconvenient, since sometimes you just want to stock up on something, without clearing that item out completely first. 
Also in botania for example there are recepies that double items. Those can never be auto crafted with refined storage, since you need at least one exemplar of the item in the sytem to dupe it, yet can't have one in there to start a crafting job.

**Comment by VT-14** [comment]
"ctrl + shift + click will force open the crafting thing"

#628

**Comment by Yadokingu** [comment]
Thx. I thought I tried every combination. Seems not. Would be good if this would be in the documentation somewhere.

**Comment by way2muchnoise** [comment]
[Added it to the wiki](https://github.com/raoulvdberge/refinedstorage/wiki/Autocrafting#requesting-a-craft-when-the-item-is-already-in-the-system)
