### ISSUE TITLE
[Request] Ender IO compatibility

### ISSUE THREAD

**Issue by ForsakenHarmony** [raoulvdberge/refinedstorage#638]
Would be super cool if you or @SleepyTrousers could add support for the refined storage cables, because rn there doesn't seem to be a way to hide cables

AE2 has support
Open Computers as well

**Comment by ProfessorProspector** [comment]
#135

**Comment by JohnC94** [comment]
Refined Storage cables use MCMultiPart, you can use Chisels & Bits to hide them.
