### ISSUE TITLE
Server Crash

### ISSUE THREAD

**Issue by Rozzers** [raoulvdberge/refinedstorage#640]
When player attempts the below description.

From the player: "im using the crafter on a solderer but i dont have an import on it yet. it crashed when i tried to craft something in it. "

[crash-2016-11-16_00.39.40-server.txt](https://github.com/raoulvdberge/refinedstorage/files/594109/crash-2016-11-16_00.39.40-server.txt)

Thats the crash report.

**Comment by way2muchnoise** [comment]
Could you or "the player" run some profiling? See https://github.com/raoulvdberge/refinedstorage/issues/523#issuecomment-256419502

**Comment by Rozzers** [comment]
That is something needed to run while He is repeating the crash?

**Comment by way2muchnoise** [comment]
@Rozzers That would be ideal

**Comment by raoulvdberge** [comment]
@Rozzers Any update on this?

**Comment by raoulvdberge** [comment]
Closing due to missing extra info. If you provide the profiling report, I'll reopen
