### ISSUE TITLE
Refined Storage lags the game

### ISSUE THREAD

**Issue by Tyranuss** [raoulvdberge/refinedstorage#641]
#### Issue description: 
Not really a big game breaker or something that is wrong with RS itself, but Refined Storage is lagging my game.  My PC is a toaster (2GB RAM, 32-bit Windows).
Can someone please give me some advice as how to reduce the lag a bit? I was looking around but couldn't find anything. I know I have a bad PC and I'm in a severe need for a new one, but I can't actually do that now. :S 

Right now using 12 mods:
 1. Chisel-MC1.10.2-0.0.7.3
 2. Cyclic-1.10.2-1.7.3
 3. extrautils2-1.10.2-alpha-1.0.1
 4. InventoryTewaks-1.61-58
 5. jei_1.10.2-3.13.3.373.
 6. Mantle-1.10.2-1.1.1
 7. MCMultiPart-1.3.0-universal
 8. Pam's HarvestCraft 1.9.4-1.10.2f
 9. refinedstorage-1.2.4
 10. TConstruct-1.10.2-2.5.6b
 11. Tinkers-Tool-Leveling-Mod-1.10.2
 12. Wawla-1.10.2-2.3.1.213.

I know this is not this mods fault (it's my PC) but I would really like some help pretty please. :( 
#### What happens: 
I get loads of fps drops ever since I installed the mod and It's a bit annoying, every few seconds.

#### What you expected to happen:
 I expected a bit of lag but not on this scale. 

#### Steps to reproduce:
1. Get a shitty PC and woila :)
2.
3.
...

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge: Tried on three versions: release 1.10.2-forge1.10.2-12.18.1.2076, 2116 and newest one 2125
- Refined Storage: refinedstorage- 1.2.4

Does this issue occur on a server? [yes/no] NO

#### If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here]

P.S. I'm a total newb to modded. So this is all new to me.

**Comment by InusualZ** [comment]
I'm not even ask how you can play Minecraft in that setup. But yeah you can expect a "heavy" mod like RS to lag a little bit your PC. It had to do a lot of calculation and that kind of stuff.

**Comment by Tyranuss** [comment]
It's the same. 
I thought It's gonna be heavy mod. Right now I have basic set-up (Controller, Disk Drive, Grid, Crafting Grid and Disk Manipulator), Drives have 16k cards in it. Now is it possible that having all those machines (albeit essential) lags my game? Would it remove the lag, or lower it if I take out for example Solderers and Disk Manipulator? 
Or is it the mod itself that is lagging the game? 

If it's the mod, is there a way to remove it without breaking my game? 

Ugh...

**Comment by InusualZ** [comment]
Disk Manipulators and Disk Drive may cause fps drops because they render their disk. That's why I ask you. Maybe if you hide them or use Storage Block may help a little bit. Other than that I can't do much. But you should wait for the official response from the maintainers.

PD: If you want to uninstall the mod, just extract all the items from your RS System and then just disable the mod. But make sure that you extract ALL THE ITEMS first.

**Comment by way2muchnoise** [comment]
Can you run some profiling? See https://github.com/raoulvdberge/refinedstorage/issues/523#issuecomment-256419502

With that info we can see where a lot of CPU time is lost.

**Comment by Tyranuss** [comment]
Thank you for your help guys. 
I think it all comes down to my PC. Without it the game doesn't lag much (few fps drops from time to time). 
Same thing happened when I had Biomes O'plenty. So it's not how complex or buggy the mod is, it all about my "amazing" PC. :) 
I guess I'll have to refrain from using RS or any other bigger mod. Sigh.
