### ISSUE TITLE
Silicon oredict issue

### ISSUE THREAD

**Issue by xenoflot** [raoulvdberge/refinedstorage#643]
#### Issue description:
Unable to autocraft storage part with silicon, when there is more than one type of silicon, and not enough of one type. (Yes, pretty specific)

#### What happens:
I had just 2 EnderIO silicon and ~300 RS silicon in my RS. I created 4 patterns, with and without OreDict, and with EIO silicon and with RS silicon. Regardless of which pattern I used, when attempting to autocraft, the job detail showed EIO silicon and refused to proceed because I only had 2 EIO silicon available.

I crafted a 1k storage part manually which used up the 2 EIO silicon, and now it's happy to autocraft with the RS silicon.

#### Steps to reproduce:
1. Have 2 EIO silicon in the RS and plenty of RS silicon
2. Attempt to autocraft a 1k storage part (fail)
3. Remove EIO silicon
4. Re-attempt autocrafting a 1k storage part (success)
...

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge: 2122
- Refined Storage: 1.2.4

Does this issue occur on a server? [yes/]

#### If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here]

**Comment by iChippy** [comment]
I read the fix and stuff but im still getting the issue where it will pull from my storage but NEEDS ender io silicon :C

**Comment by Darkere** [comment]
This? #1954
