### ISSUE TITLE
INetworkNode needs to be a capability

### ISSUE THREAD

**Issue by raoulvdberge** [raoulvdberge/refinedstorage#644]

**Comment by Volune** [comment]
Hi @raoulvdberge 

I was having a look at this issue (before I try to have a look at enderio cables), and I'd like to suggest a few refactoring on the `INetworkNode`:
- Remove `getNodeWorld()` and add `getDimension()` to `IWirelessTransmitter`
- Remove `canConduct(...)` and use `tile.hasCapability(...)` instead (it has face check)
- Remove `getPosition()` and replace with `getItem()`

And at last one I'm not really sure about:
- Remove `isConnected()`, replace with getNetwork() != null


I can work on a pull request for that if that helps.

**Comment by raoulvdberge** [comment]
How is getItemStack() a valid replacement for getPosition()?

getNodeWorld() is needed

**Comment by Volune** [comment]
`getNodeWorld()` is only used to get the dimension of a IWirelessTransmitter. That's why I'd like to remove it after putting `getDimension()`

`getPosition()` is only used to get the item of a node, for displaying in the controller UI, so I think a `getItemStack()` would be more appropriate - maybe with a better name.

**Comment by raoulvdberge** [comment]
Ah. Good point. You were ahead of me there :)

In that case, feel free to work on the PR but wait til I make the 1.11 branch in that case (which should be later today).

**Comment by Volune** [comment]
My current work is [there](/Volune/refinedstorage/tree/inetworknode-capability)
I'm waiting your new branch to rebase and open a pull request.

The changes were pretty big regarding the refactoring of `isConnected()`, and rework of `rebuild()` to integrate the capability. By the way, is there an actual need to `getConnectableConditions()` ?

**Comment by raoulvdberge** [comment]
At first sight, most changes seem OK (I like the network graph refactor). However, a proper PR will be needed for further review.

For the justification of the connectable conditions see #650

**Comment by raoulvdberge** [comment]
@Volune The 1.11 branch is now public
