### ISSUE TITLE
Separate and make two patterns: crafting pattern & machine pattern

### ISSUE THREAD

**Issue by monkeybutt32** [raoulvdberge/refinedstorage#645]
#### What you expected to happen:
1. Logic built in to warn user craftable item being written to pattern in encoder. and vice versa for machine pattern.

2. Add another line to wiki to explain that using the wrong pattern will cause the system to not work.

or 3. If there were two types of patterns, a  machine pattern and crafting pattern, they could be limited to which pattern generating machine they can be inserted into.

#### Steps to reproduce:
1.
2.
3.
...

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge: 2147
- Refined Storage: 1.2.4

Does this issue occur on a server? [yes/no] don't know, play single player

**Comment by InusualZ** [comment]
When you craft the pattern encoder, in the tooltip clearly said what you are requesting

**Comment by monkeybutt32** [comment]
Okay, But, keep in mind what I stated about the youtube. There are many others that have this issue that spotlight the mod on youtube and end it with problems and autocrafting not working. I think a little effort to streamline this would help.

**Comment by way2muchnoise** [comment]
I don't know who you watched on YT but Direwolf20 always does very detailed tutorials and has one (in 2 parts) about RS. [See part two](https://www.youtube.com/watch?v=pMHww6qpABA) for more info about autocrafting.
