### ISSUE TITLE
Support storing gases in gas storage disk

### ISSUE THREAD

**Issue by GuylainGreer** [raoulvdberge/refinedstorage#646]
#### Issue description:
Right now the Mekanism mod adds a bunch of new items, fluids and gases.  The items and fluids are stored quite excellently in a RS system, but gases get left out of the equation.  I would like to request that storage disks and related options also support gases.
I imagine it only makes sense to enable these options when gases are present in the game, so the options/items could possibly be disabled if no gases are available.
I don't think I can tag these issues myself or I would add the "Feature Request" tag.

**Comment by InusualZ** [comment]
This have been requested many times, @raoulvdberge have said no, Why? because you can convert Mekanism gases into liquid, plus he don't want to :)

**Comment by GuylainGreer** [comment]
@InusualZ Why wouldn't he want to?  I would have imagined that after doing all the legwork to support items and fluids that supporting gases would not have been that much more work.  Or is there some other reason?
As for converting the gases to liquids, it was precisely after converting gases to liquids and back to gases that I wrote up this request because of how clunky and unfun that was.

**Comment by InusualZ** [comment]
Well, I think that fluids are accepted in RS because there are crafting (bench) recipe that use fluids as component. So I think that since gases are only used in Mekanism (I think) and on their own "crafting" proccess its not worth it. But, I cant speak for @raoulvdberge so wait for his reponse.

**Comment by raoulvdberge** [comment]
No, read here why: #588
