### ISSUE TITLE
Crash when rendering items in Creative inventory

### ISSUE THREAD

**Issue by tripl3dogdare** [raoulvdberge/refinedstorage#647]
#### Issue description:

When I view some items in the Creative inventory or through JEI (namely anything built on `ItemNetworkItem`), my game crashes.

#### What happens:

Crash.

#### What you expected to happen:

Actually be able to use the mod.

#### Steps to reproduce:
1. Open the Creative inventory
2. Click the Refined Storage tab
3. Watch as your hopes and dreams come crashing down around you (pun intended)

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge: 12.18.2.2125
- Refined Storage: 1.2.4

Does this issue occur on a server? [yes/no]
Probably, though I'm finding it in singleplayer.

#### If a (crash)log is relevant for this issue, link it here:

https://gist.github.com/tripl3dogdare/ebc7c697548cdd72b9e8e24e24b44077

**Comment by way2muchnoise** [comment]
You have a bad RF api in some mod. Check if you have some old jar just sitting in there or try swapping out some mods. You could always install enderio, since they report the loaded RF api when something like this happens.

**Comment by tripl3dogdare** [comment]
After following your advice and digging around for a while, it turns out I was using Extra Utilities and not Extra Utilities 2. No idea how a 1.8 mod even loaded at all on 1.10, but apparently it did. Thank you!

**Comment by way2muchnoise** [comment]
np, yeah the mod that provides the api doesn't even have to be loaded. Glad it worked out!
