### ISSUE TITLE
[Suggestion] JEI Solderer Recipes From GUI

### ISSUE THREAD

**Issue by InsomniaKitten** [raoulvdberge/refinedstorage#648]
**- The ability to left-click the processing arrow in the Solderer GUI to view all solderer recipes in JEI.**
**- With a mouse-over tooltip saying something along the lines of "View Recipes".**

**Comment by way2muchnoise** [comment]
How is this not already there :p

**Comment by raoulvdberge** [comment]
Won't this interfere with the progress tooltip?

**Comment by way2muchnoise** [comment]
Don't think so, JEI does that "View Recipes" tooltip. Should test tho
