### ISSUE TITLE
Unable to craft extrautils golden lasso in crafting grid

### ISSUE THREAD

**Issue by xenoflot** [raoulvdberge/refinedstorage#649]
#### Issue description:
A few items in extra utils 2 have an XP component in addition to the materials. If the XP requirement is not met, the output slot remains empty. When attempting to craft a golden lasso in an RS crafting grid, no output is displayed, despite meeting the XP requirements. When using a tconstuct crafting station, I was able to create them without a problem.

#### Steps to reproduce:
1.
2.
3.
...

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge: 2122
- Refined Storage: 1.2.4
- xu2: extrautils2-1.10.2-alpha-1.2.2

Does this issue occur on a server? [yes/]

#### If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here]

**Comment by raoulvdberge** [comment]
This requires the grid to be unique per-player, however, due to the grids nature this isn't possible.
