### ISSUE TITLE
Disk Manipulator destroys non disk items

### ISSUE THREAD

**Issue by Rafujin** [raoulvdberge/refinedstorage#652]
#### Issue description:
Shift clicking items into the disk manipulator that are not disks destroys the item(s) when u try to shift-click it out again.
Note: Only tested on a server.

#### What happens:
Destroys item.

#### What you expected to happen:
To not be able to put the non disk item into the disk manipulator.

#### Steps to reproduce:
1.Open the disk manipulator (does not need to be connected to the network)
2.Shift-click item(s) into inventory (will go into the bar on top)
3.Try to shift-click the item(s) back out of the bar on the top

#### Version (Make sure you are on the latest version before reporting):
Direwolf20 1.10.2 - 1.0.0
- Minecraft: 1.10.2
- Forge:
- Refined Storage: 1.2.4

Does this issue occur on a server? [yes/no] yes

#### If a (crash)log is relevant for this issue, link it here: 

[pastebin/gist/etc link here]

**Comment by raoulvdberge** [comment]
This is because the DiskManip container has the wrong indexes specified.
