### ISSUE TITLE
Random server crash - possibly autocrafting related

### ISSUE THREAD

**Issue by xenoflot** [raoulvdberge/refinedstorage#655]
#### Issue description:
Server crashed for no apparent reason. Crash report mentions RS autocrafting.

One user said she was trying to use the FlatColoredBlocks tool but I think that's coincidence as plenty of people have been using that.

Not sure if there's enough to identify the problem from the attached crash report. I can provide the main server log on request. Otherwise just close and ignore.

Cheers!

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge: 2122
- Refined Storage: 1.2.4

Does this issue occur on a server? [yes/]

#### If a (crash)log is relevant for this issue, link it here:

http://pastebin.com/qkCbNezh

**Comment by raoulvdberge** [comment]
Something went wrong while copying an ItemStack, so I'm assuming some other external mod is breaking that. So I'll close it, as I don't think this is an RS issue.

**Comment by way2muchnoise** [comment]
This was the watchdog stoping the main thread because something hang. But that could be anything since it just prints what ever it had on the stack at the moment the watchdog killed it.
