### ISSUE TITLE
Auto-crafting a Mekanism Speed Upgrade Fails

### ISSUE THREAD

**Issue by jasonmicron** [raoulvdberge/refinedstorage#656]
#### Issue description:
Auto-crafting a Mekanism Speed Upgrade fails due to a hard requirement for Tinker's Construct Clear Glass.

#### What happens:
Receive an error that the glass is not available, no matter the type, unless you have an auto-crafting recipe set up for Tinker's Construct Clear Glass (the actual recipe takes any available glass).  Manually doing this works fine; it is only autocrafting that does not work.

It does appear that if you set it to auto-craft a number of upgrades that you actually have in your system, then cancel, then go back and tell it to craft more where you need to craft more glass than you currently have, the issue goes away.

#### What you expected to happen:
I expect to be able to auto-craft a Mekanism Speed Upgrade using Refined Storage on the first try whether I have all of the glass or not, as long as I have a recipe available to auto-craft the missing glass.

#### Steps to reproduce:
1. Set up an auto-crafting recipe to create a Mekanism Speed Upgrade using either Vanilla Glass or EnderIO Quite Clear Glass
2. Try to autocraft and specify a value higher than any available amount of glass, especially any Tinker's Clear Glass.
3. See the error warning that there are missing resources, even though they can also be auto-crafted just fine individually (the glass, in this case - both Vanilla glass and Quite Clear Glass from EnderIO)
4. Try to craft a single upgrade, assuming you have enough resources and do not require any other machines - just straight crafting
5. Cancel step 4 
6. Try step 2 again, and it appears to work fine going forward

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- HermitPack:  1.4.0-1.10.2 Beta [Latest]
- Forge: 12.18.2.2124
- Refined Storage: 1.2.4
- Mekanism:  9.2

Does this issue occur on a server? [yes/no] Likely - though in this case, it is a local game.  I have not tested this, though I doubt it makes much of a difference.  The issue is very much likely the same. 

#### If a (crash)log is relevant for this issue, link it here:
N/A

**Comment by raoulvdberge** [comment]
I think @way2muchnoise fixed this in dev yesterday, is that true?

**Comment by way2muchnoise** [comment]
Yeah most likely fixed in #643
