### ISSUE TITLE
Add support for Forestry Circuits

### ISSUE THREAD

**Issue by brad18** [raoulvdberge/refinedstorage#660]
#### Issue description:
Refined Storage is unable to "move items" in jei for forestry circuits (potentially other forestry items) or use the circuits in autocrafting.

#### What happens:
Jei "move item" does not fill in the circuit in the grid table and autocrafting reports that the circuit is unavaliable

#### What you expected to happen:
Circuit to be used in crafting.

#### Steps to reproduce:
1.Put forestry circuit in system
2.Try to autocraft with it or "move items" in jei for a recipe it is used in.

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge: 1.10.2-12.18.2.2125
- Refined Storage: 1.2.4

Does this issue occur on a server? [yes/no]
yes

**Comment by way2muchnoise** [comment]
Works fine for me.

![](http://puu.sh/sqXQF/b41fe2bd0d.gif)

**Comment by InusualZ** [comment]
Maybe his circuit have NBT and that is causing the issue.

**Comment by brad18** [comment]
Hrm, it looks like forestry stuff works but it isn't working with Utocs custom recipes with minetweaker.

**Comment by raoulvdberge** [comment]
It's because grid autocompletion expects the EXACT stack that JEI specifies. We might get away with ignoring NBT data though.

**Comment by raoulvdberge** [comment]
We might not. JEI autocomplete needs exact item, including NBT data.
