### ISSUE TITLE
OreDict Issues (oak, dark oak)

### ISSUE THREAD

**Issue by Darkosto** [raoulvdberge/refinedstorage#661]
#### Issue description:
When not using OreDict. the autocrafter chooses Oakwood over Dark Oak even when Dark Oak is in the pattern
#### What happens:
It chooses the wrong wood
#### What you expected to happen:
For it to choose the right wood.
#### Steps to reproduce:
1. Make pattern with Dark oak
2. Don't select ore dict
3. Profit
4. Success
5. Bugs
...

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge: 2151
- Refined Storage: 1.2.4

Does this issue occur on a server? [yes/no]
I don't know because other mods are crashing the server because they call client side code on the server. Thx Obama
#### If a (crash)log is relevant for this issue, link it here:
no log, sorry
[pastebin/gist/etc link here]

**Comment by way2muchnoise** [comment]
Darkoaksto :D
