### ISSUE TITLE
Dupe bug with interface, external storage, and drawer controller

### ISSUE THREAD

**Issue by xannor** [raoulvdberge/refinedstorage#662]
#### Issue description:
I started and issue over at Storage Drawers for a duplication bug I have run across.
https://github.com/jaquadro/StorageDrawers/issues/366

#### What happens:
If I import with an interface, more than one item, with no upgrades, and have an external storage on a drawer controller, some items will duplicate upon insertion. This does not seem to happen when using the grid or other means of insertion. Also adding a stack upgrade to the network interface solves the problem.

#### What you expected to happen:
The exact number of items inserted.

#### Steps to reproduce:
1. create an RS network with an interface and external storage connected to a drawer controller
2. add one item and see it show up on the drawer
3. add more than one item and see the difference duplicated in the drawer.
...
serious profit!

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge: 2151
- Refined Storage: 1.2.4
- Storage Drawers: 3.4.6
Does this issue occur on a server? yes, have only tested on a server.

**Comment by way2muchnoise** [comment]
Just tried this with Storage drawers 3.4.7 and can't reproduce. Gif of my setup below.

http://puu.sh/srUwi/331b2111d1.gif (can't preview a gif this large it seems)

**Comment by raoulvdberge** [comment]
@way2muchnoise But what does the drawer itself say?

**Comment by xannor** [comment]
I just tried both in single player and in creative on my server, without updating mods, and I cannot reproduce the bug with a simplified setup, only my original one, I even tried breaking and replacing the controller but no luck. Since it seems to not be reproducible, I have to assume it is something about my setup in my world that is causing this though I cannot figure out what and I do not want to tear the whole thing apart to find out. I can work around it by making sure I have a stack upgrade so it is not an issue for me.
