### ISSUE TITLE
Search bar replacing space ' ' with or '|' in item search bar

### ISSUE THREAD

**Issue by NeosGhost** [raoulvdberge/refinedstorage#663]
#### Issue description:
Search bar replacing space ' ' with or '|' in item search bar in grid and crafting grid gui.
#### What happens:
![refined storage 1 2 4](https://cloud.githubusercontent.com/assets/16095247/20511438/1a36900c-b03e-11e6-9923-46001ec6c2b5.png)
![refined storage 1 2 4 2](https://cloud.githubusercontent.com/assets/16095247/20511439/1c0e01e4-b03e-11e6-9e52-f8e541502b65.png)

#### What you expected to happen:
![refined storage 1 2 3](https://cloud.githubusercontent.com/assets/16095247/20511427/0a974222-b03e-11e6-889b-436bb2da0e1d.png)
![refined storage 1 2 3 2](https://cloud.githubusercontent.com/assets/16095247/20511434/16930412-b03e-11e6-933c-ca66992ee595.png)

#### Steps to reproduce:
1. add items with a 2 word name and then search eg. oak wood & birch wood, iron ingot & gold ingot
2.
3.
... was not present in version 1.2.3

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge: 12.18.2.2124
- Refined Storage: 1.2.4

Does this issue occur on a server? [yes/no]
both SSP and SMP
#### If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here]

**Comment by raoulvdberge** [comment]
Already fixed in dev

**Comment by NeosGhost** [comment]
tx
