### ISSUE TITLE
storage and crafting grid not searching

### ISSUE THREAD

**Issue by theonlygrime** [raoulvdberge/refinedstorage#664]
#### Issue description:
The storage and crafting grids won't let me search any more
#### What happens:
When I try to search in the grids, nothing happens
#### What you expected to happen:
Usually a search on the grid will find the item I am looking for.
#### Steps to reproduce:
1. Open Grid of any kind
2. Try to search for something
3. Nothing happens
...

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge:
- Refined Storage:

Does this issue occur on a server? [yes/no]
haven't tried
#### If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here]

**Comment by way2muchnoise** [comment]
This report is very incomplete. What version if RS? Other mods installed? Does it happen with just RS installed?

**Comment by raoulvdberge** [comment]
Rather unclear and incomplete issue. Reopening when you have more info.

**Comment by theonlygrime** [comment]
It's really not that hard to understand. Nothing incomplete or unclear about it.

-------- Original message --------

**Comment by theonlygrime** [comment]
Nah you just don't want to try to fix the issue. Generic form letter response from someone who doesn't want to be bothered.

-------- Original message --------

**Comment by theonlygrime** [comment]
Tell me how it is incomplete when I answered every question you saw fit to put into the form?

-------- Original message --------

**Comment by theonlygrime** [comment]
As for version - all I see is 1.2.4. No idea but I assume it's the latest version. No other mods. My computer isn't the issue.

-------- Original message --------

**Comment by way2muchnoise** [comment]
Did you supply enough power to the controller? Do you have any disk drive? Or storage blocks.

**Comment by theonlygrime** [comment]
Well. Considering that I stated that I had been using it prior I would come to the conclusion that it means I have power and storage disks. I didn't say that nothing shows up. I said that the search doesn't work.

-------- Original message --------

**Comment by way2muchnoise** [comment]
If this is consistently happening are you capable of making a screenshot or a vid/gif. Cause I have never had this happen.

**Comment by theonlygrime** [comment]
I can. But it will be tomorrow before I get to my computer again.

-------- Original message --------
