### ISSUE TITLE
Shouldn't pull from solderer inputs

### ISSUE THREAD

**Issue by Zaflis** [raoulvdberge/refinedstorage#666]
#### Issue description:
I put Importer cable to Solderer machine but it pulls everything out before materials have time to start processing.

#### What you expected to happen:
Only pull from Solderer's output slot. This would be consistent with all other mods, like when smelting wood to charcoal, no pipe ever pulls wood out from furnaces.

I was not able to solve it by whitelisting importer either. It doesn't pull certain items out even if they are not whitelisted.

#### Version (Make sure you are on the latest version before reporting):
- Minecraft: 1.10.2
- Forge: 2124
- Refined Storage: 1.2.4

Does this issue occur on a server? [yes/no]
yes

**Comment by way2muchnoise** [comment]
Sides are for items and the bottom is for the result. So connect your pipe/extractor/... to the bottom.

**Comment by Zaflis** [comment]
Thanks that works. Being new to mod anyway i didn't even think to try that. Would it be better if all sides worked the same or is it a limitation in API's?

**Comment by way2muchnoise** [comment]
All sides output is kinda counter intuitive compared to other things. Output is usually bottom slot.
