### ISSUE TITLE
Destructor not breaking blocks

### ISSUE THREAD

**Issue by Skar78** [raoulvdberge/refinedstorage#667]
#### Issue description:
Destructor does not agree to do his job.

#### What happens:
Nothing

#### What you expected to happen:
Breaks the block.

#### Steps to reproduce:
1. Build Destructor and connect to rs system
2. Check in controller if its indeed detected (yes)
3. Whitelist the lapis ore (yes)
3. Place lapis ore in front of it (facing red side, yes)
4. nothing 

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2 
- Forge:
- Refined Storage: 1.2.4

Does this issue occur on a server? [yes, hermitpack 1.4]

**Comment by way2muchnoise** [comment]
Claimed chunks? via the FTBU thing

**Comment by Skar78** [comment]
Yes, solved the problem - but it was my chunklaoding mechanism oO

**Comment by Skar78** [comment]
Side note: Could this also be related to an issue where i cannot place crafting upgrades into crafters? (before i open a new ticket.)

**Comment by way2muchnoise** [comment]
Yeah, it is an issue that is know and being worked on by FTBU iirc.

On the side node that seems rather odd if you place them yourself.

**Comment by Skar78** [comment]
Thank you very much for your help.
