### ISSUE TITLE
Unable to place Crafting Upgrade into Crafter

### ISSUE THREAD

**Issue by Skar78** [raoulvdberge/refinedstorage#668]
#### Issue description:
Cant place "Crafting Upgrade" into Crafter. 

#### What happens:
Just nothing, item cant be placed in the slot.

#### What you expected to happen:
Place upgrade into crafters upgrade slot.

#### Steps to reproduce:
1. Creating Crafting Upgrade
2. Open Crafter GUI
3. Desperately try to add crafting upgrade.
...

Tried with and without ressource pack loaded, restarted server, 
Unlcaimed and unloaded chunks via FTBU.

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge:
- Refined Storage: 1.2.4

Does this issue occur on a server? [yes, hermit Pack]

#### If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here]

**Comment by way2muchnoise** [comment]
Now that I think about it, why would you need a crafting upgrade in a crafter? The only valid ones are speed upgrades

**Comment by Skar78** [comment]
The crafter does not seem to craft sub-craft processes. So I thought i need a craft upgrade so that he starts up to craft missing materials. Example 64k disk recipe with 64k memory + housing. Crafter does do the 64k memory thingie but not the housing.

**Comment by way2muchnoise** [comment]
Could you explain the process you go true for crafting? As maybe some screenshots? Cause I'm kinda confused as to what you are doing/expecting exactly

**Comment by Skar78** [comment]
The 64k disk recipe is a 64k memory chip + a disk housing. I would expect the crafter to either craft with available parts or check if patterns are available for missing parts. However the crafter will not craft a disk housing, even though there is a pattern for it available.

I assumed this would be the case because there is no crafting upgrade, so without crafting upgrade the crafter only crafts with available materials and does not start sub-crafting processes for missing materials.

**Comment by way2muchnoise** [comment]
Yeah there is some issue with housing. I was fixed in #612

**Comment by Skar78** [comment]
Well the generic issue is that a required material does not get crafted, despite a pattern being present.

Example: Void Upgrade pattern from StorageDrawers.

It requires an Upgrade Template and that requires a basicDrawer.

Despite having working patterns in the system to craft that the crafting system says components missing and does not allow to start the autocrafting order.

**Comment by way2muchnoise** [comment]
There is some issue miss matching nbt data, I will have to do some research on the best fix for this

**Comment by Skar78** [comment]
I try to experiment a bit - as this behavior seem to not always (as in for all patterns with sub-crafting) happens.

 I feel like StorageDrawers recipes are especially vulnerable - but unsure why and if that is really true for most of them. (Got Upgrade Template, Emerald and Void upgrade patterns with the issue).

I am setting up a bigger autocraft area currently, and hermitpack seems to have not so many alternatives. However if this is a general issue I would expect loads of issues reporting.

**Comment by way2muchnoise** [comment]
The what patterns are you using? Cause I can craft all of those items in my dev env. @Skar78

**Comment by Skar78** [comment]
Tested more.

The Pattern for the Storage Drawer basicDrawer (oak, 1x32) is not used when another pattern requires it.

Further it is not even recognized when the basicDrawer is "on stock".

I redid the pattern with oredict enabled and it works now.

**Comment by way2muchnoise** [comment]
Interesting will look into the non-oredict issue.
