### ISSUE TITLE
EnderIO ItemConduit Insert/Extract

### ISSUE THREAD

**Issue by leglerm** [raoulvdberge/refinedstorage#669]
#### Issue description:

Basically set up an interface to provide some items and to pump items back into the system. Provided wheat for the animal farm and pump meat back in with an enderio itemconduit connected to an interface.
The issue is that the refined storage doesnt accept inserting and extracting through the same side at the same time. I have different setups for the conduits on other machines without this issue occuring.

#### What happens:
Items were not able to get into the interface

#### What you expected to happen:
Items do get into the interface import part

#### Steps to reproduce:
1. Setup Interface + itemconduit + inventory
2. Configure Insert/extract with different items on the interface
...

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge: 12.18.2.2122
- Refined Storage: 1.2.4

Does this issue occur on a server? yes

**Comment by InusualZ** [comment]
This cant be posible since interface are sided and interface have 2 "inventories". One for output, one for input.

**Comment by leglerm** [comment]
Attached my little setup. I had to connect that additional cable on the front. It didnt worked for dual from the bottom but as soon as i attached the 2nd one on the side configured for insert only it did instantly fill the interface with the items that were supposed to go in.

I thought at first i had my whitelist/blacklist wrong and removed the itemfilter to test that out but even then it didnt worked. No other cables have been adjusted before i added the solo insert cable. 


![2016-11-22_22 28 31](https://cloud.githubusercontent.com/assets/13408657/20542702/0d26b232-b103-11e6-864a-8da097becd92.png)

**Comment by leglerm** [comment]
I did another test basically and now the issue is the other way around. 

I set up an interface to provide cobble and two chests. One chest as input for the cobble and the other chest with different items that should go into the interface. Now the items from the interface do net get sorted out but the ones from the chest get sorted into it. 

I tested it with a chest aswell to see if the problem is related to the insert/extract function from EiO conduits but it did work there as expected.

![2016-11-22_22 36 26](https://cloud.githubusercontent.com/assets/13408657/20542996/69c8e996-b104-11e6-99ce-e983b796b917.png)

![2016-11-22_22 36 17](https://cloud.githubusercontent.com/assets/13408657/20542993/671d39e0-b104-11e6-9356-0404b9314f94.png)

**Comment by InusualZ** [comment]
What you can do is to set a color for each "operation". 
Example: Insert(Green), Extract(Blue)

**Comment by leglerm** [comment]
Tried that even though that would have been just a workaround and not the actual problem. As expected it didnt worked. 

Furthermore what i noticed is that the extract function pulled items out of the "Interface Import" slots with the extract conduit.

**Comment by algul** [comment]
You can only extract items for bottom side of the interface and can't insert into bottom side. https://refinedstorage.raoulvdberge.com/wiki/interface

**Comment by raoulvdberge** [comment]
^
