### ISSUE TITLE
Server crash - Block detector on Interface

### ISSUE THREAD

**Issue by Hirsu** [raoulvdberge/refinedstorage#671]
#### Issue description:

I want to put a crystallized canola seed into a detector block. As soon as I do so, my server crashes with [this error](http://pastebin.com/5spcGHji). Restarting the server produces the same error from then on. I can only resolve this by loading the world in MCEdit and removing the block detector. The crash is reproducable (I've tried this 3 times now with the same result - instant crash as soon as the seed goes into the gui slot of the block detector).

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge: 2151
- Refined Storage: 1.2.4

Does this issue occur on a server? [yes/no] Yes

#### If a (crash)log is relevant for this issue, link it here:

Same as [above](http://pastebin.com/5spcGHji). Let me know if you need any other logs.

Edit:

I've tested this scenario in a few different settings. To start off with, I simply placed the block detector elsewhere and then tried inserting different items. I had no issues there, not even with the cyrstalized canola seeds. I then placed the block detector back on its original location - on top of an interface - and the crash reoccured by inserting an item in the GUI slot. This was reproducable for any item. So it seems like the crash isn't caused by canola seeds specifically but rather by the block detector's location and - more probably- its relation to/interaction with the surrounding blocks.

I made a short [Youtube video](https://www.youtube.com/watch?v=VGZcKwohAb0) to demonstrate how I can cause this crash to happen.

**Comment by raoulvdberge** [comment]
This is a `lumien.randomthings` issue:

```
Caused by: java.lang.NullPointerException
    at lumien.randomthings.tileentity.redstoneinterface.TileEntityRedstoneInterface.getRedstonePower(TileEntityRedstoneInterface.java:50) ~[TileEntityRedstoneInterface.class:?]
    at lumien.randomthings.handler.AsmHandler.getRedstonePower(AsmHandler.java:303) ~[AsmHandler.class:?]
```
