### ISSUE TITLE
solderer eating some items sometimes

### ISSUE THREAD

**Issue by ash1688** [raoulvdberge/refinedstorage#672]
#### Issue description:
A player on my server was saying that when he was using the solderer it would eat some or all of the iron and gold he had put into there.

#### What happens:
he would put iron and gold in there and and would come back to find either the printed processors gone or not all there.
I tried it with mine but didn't have any problems, I then tried it with his a few times so times the amount i put in came back out but the last time i tried it i put a stack in 2 and when finished it only returned 70 .
I made sure that the solderers weren't connected to importers or anything else which they weren't.
#### What you expected to happen
to get the correct amount of processed items back.

#### Steps to reproduce:
1.place solderer 
2.insert iron, gold, diamond or silicon in 
3.wait for it to be processed
4. come back once it's done processing to see if all or some are there

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge: 12.18.2.2124
- Refined Storage: 1.2.4
- the server is running hermitpack 1.4.0
Does this issue occur on a server? YES

#### If a (crash)log is relevant for this issue, link it here:
No crashlog
[pastebin/gist/etc link here]

**Comment by raoulvdberge** [comment]
This is fixed in dev
