### ISSUE TITLE
Kicked from server when opening my crafting grid - Payload may not be larger than 1048576 bytes

### ISSUE THREAD

**Issue by ProsperCraft** [raoulvdberge/refinedstorage#673]
#### Issue description:
I have a storage full of bees, and saplings from Forestry.  Recently after adding more bees and saplings to it, I stated getting kicked when opening the crafting grid.

#### Steps to reproduce:
1. breed lots of random bees, and trees
2. insert them into the system
3. keep adding until you can't open the system.
...

- Minecraft: 1.10.2
- Forge: forge-1.10.2-12.18.2.2123-universal.jar
- Refined Storage: refinedstorage-1.2.4.jar

Does this issue occur on a server? yes

May be related to this-
https://github.com/raoulvdberge/refinedstorage/issues/195

**Comment by raoulvdberge** [comment]
A temporary workaround would be to export all bees out with NBT compare off.

**Comment by way2muchnoise** [comment]
fragmented packets and stuff :'( Guess that'll be fun to code

**Comment by raoulvdberge** [comment]
We'll have to chain the grid update packet instead of sending it at once.

**Comment by EvilNotion** [comment]
raoulvdberge, would doing so reduce the amount of lag introduced to the system when you break power to your Controller and then reconnect?  I have millions of items (lots in external Quantum Storage) and when I move my system or lose RF to it it tends to lag the server pretty badly.

**Comment by way2muchnoise** [comment]
No @EvilNotion that is related to #566

**Comment by phit** [comment]
I just ran into this myself in 1.10.. supposedly a player queued up a big crafting task.

**Comment by fattness5** [comment]
This is happening to me in SkyFactory 3 whenever i look at my disk drives/controller.

**Comment by raoulvdberge** [comment]
@fattness5 Update HWYLA, this is not an RS issue.

**Comment by exetico** [comment]
We see the same error here at Sky Factory 3 with Refined Storage 1.2.18:
TranslatableComponent{key='disconnect.genericReason', args=[Internal Exception: java.lang.IllegalArgumentException: Payload may not be larger than 1048576 bytes], siblings=[], style=Style{

Triggered here by ordering a large amount of items and using `Ctrl` + `Shift` to force it to que it. We have multiple other autocrafting task running, but everytime we using the that feature, the server crashed. 

We also see it after creating other smaller tasks, but that is not very often.

![image](https://cloud.githubusercontent.com/assets/3549445/23800352/560a9cb8-05ac-11e7-95cf-cf3cd926b59f.png)
Log here: http://pastebin.com/gp197nXZ

**Comment by raoulvdberge** [comment]
Why don't you update your SF3 instance before coming to the issue tracker? @exetico

**Comment by exetico** [comment]
@raoulvdberge - Oh, damn. I just forgot that my current setup didn't update the instance by itselves. Sorry for taking your time.

**Comment by raoulvdberge** [comment]
No problem, @exetico.

**Comment by raoulvdberge** [comment]
I can no longer reproduce this on 1.11+.

**Comment by roboderpy** [comment]
plz
![grid](https://i.dbot.serealia.ca/2018/04/javaw_2018-04-11_16-23-44.png)

**Comment by GianniKoch** [comment]
I still have this issue till this day and idk what it is causing it. anyone that got wiser?

**Comment by smiba** [comment]
Having this issue on ATM6 as well

"Payload may not be larger than 1048576 bytes" when opening the terminal. A lot of items such as armour are in our storage system, not sure if that matters? 

@raoulvdberge could you reopen this problem?

**Comment by smiba** [comment]
Never mind, this belongs in #1790 

We did fix it by extracting all the tools and armour out of the system. There was a LOT in there. Because these don't stack (enchantments / varying levels of wear) they all show up as a separate item, likely making the item list massive.
