### ISSUE TITLE
Crash with Mek's McMultiPart and Refined Storage exporter

### ISSUE THREAD

**Issue by DuskFalls** [raoulvdberge/refinedstorage#674]
Same as here : https://github.com/aidancbrady/Mekanism/issues/4011

Was just placing pipes and it looks like one was placed next to an exporter, which causes the world to crash every time I open it
[crash-2016-11-24_22.42.12-server.txt](https://github.com/raoulvdberge/refinedstorage/files/612259/crash-2016-11-24_22.42.12-server.txt)

**Comment by way2muchnoise** [comment]
Mekanism uses an old outdated version of multipart. We can't stay behind just because mekanism decided to.

**Comment by raoulvdberge** [comment]
This doesn't even look like an RS issue, but rather Mekanism doing something wrong internally.
