### ISSUE TITLE
Can't craft with fluids under specific scenario

### ISSUE THREAD

**Issue by bsaksida** [raoulvdberge/refinedstorage#675]
#### Issue description:
I am trying to autocraft empowered oil bucket from acutally additions. Recepies requires to place a liquid in a world and drop specific items with dropper.

#### What happens:
Since i want to attempt to craft without any loss so i am trying to get into a chest bucket of oil, Empowered canola seed and Crystalized canola seed. The problem lies in Oil bucket. Refined storage does not output to chest and does not take oil from Refined storage

#### What you expected to happen:
I am expected to get a Nececeary items to a chest, so that i route it to deployers and dropers. I am expecting this, to only attempt to aoutcraft when all items are awaible.

#### Steps to reproduce:
1. Place crafter with a patteren: Bucket of oil, empowered canola seed and crystalized canola seed. Output should be Empowered oil bucket
2. Place chest at the end of crafter
3. Request empowered oil bucket

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10
- Forge: 12.18.2.2124
- Refined Storage: 1.2.5 ( I am using Direwolf20 1.10 pack, manualy updated mod)

Does this issue occur on a server? [yes/no] 
yes

**Comment by way2muchnoise** [comment]
Does the preview correctly display the needed items?

**Comment by way2muchnoise** [comment]
Now that you name. Processing patterns aren't capable of filling buckets. Need to add that. It was something that got pushed since it'll need special handling if the fluids needs to be pumped into the machine
