### ISSUE TITLE
The Exporter in fluid mode crashes

### ISSUE THREAD

**Issue by dirk251272** [raoulvdberge/refinedstorage#676]
#### Issue description:
The games crashes while loading a save game.
#### What happens:
When an Exporter in fluid mode is connected to machines from Advanced Rocketry and Actually Addition the game crashes while loading a save game.
#### Steps to reproduce:
1.
2.
3.
...

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge: 2122
- Refined Storage: 1.2.5

Does this issue occur on a server? [yes/no]

#### If a (crash)log is relevant for this issue, link it here:

http://pastebin.com/SCfa83rR

**Comment by InusualZ** [comment]
I think you should report this issue to the developer of ActuallyAddition since it's crashing on their side

**Comment by dirk251272** [comment]
It crashes with more mods than just Actually Additions. It was just an example.

**Comment by way2muchnoise** [comment]
The only way this can crash is when the passed FluidStack would be null. Will investigate.

**Comment by raoulvdberge** [comment]
```java
                                FluidStack took = network.extractFluid(stack, toExtract, compare, true);

                                if (took != null) {
                                    int filled = handler.fill(took, false);
                                    took = network.extractFluid(stack, filled, compare, false);
                                    handler.fill(took, true);
                                    break;
                                }
```
The NPE happens at `handler.fill(took, true);`.

What I think happens here is: if `filled` is 0, it'll try and extract 0 fluid of that type which returns null.
