### ISSUE TITLE
Suggestion: Fill bottles in the Fluid Terminal.

### ISSUE THREAD

**Issue by RustyXXL** [raoulvdberge/refinedstorage#677]
It would be nice to be able to fill waterbottles and similar items in the fluid terminal, i.e. for alchemy etc. tried it last night in 1.2.4, and had to run to my watersource to fill them.
Dunno if the fluid terminal works for other similar containers, like the ic2 cans or forestry capsules and/or other fluids that go in these "containers", but if not, it would be nice to be able to fill them in a fluid terminal, too.

**Comment by raoulvdberge** [comment]
No, I dislike this type of functionality.

**Comment by RustyXXL** [comment]
What kind of functionality?
Being able to fill a container in a fluidterminal, which can also be achieved by rightclicking a water source with the container in the world? ;P
The only difference is, that the bucket would consume the water source in the world, while the bottle wouldn't. ;) Seems inconsequential to me. ;)
Anyway, it's your mod. Not complaining, just expressing my confusion, as you already are able to fill buckets in the fluid terminal.
