### ISSUE TITLE
TPS drop during large crafting tasks

### ISSUE THREAD

**Issue by brad18** [raoulvdberge/refinedstorage#678]
#### Issue description:
Significant tps drop when large crafting tasks are running.

#### What happens:

Tps dropped to 1-2tps during the task and bounced back immediately after the task was cancelled.
#### What you expected to happen:

TPS to remain stable at 20tps

#### Steps to reproduce:
1. Craft 16 mekanism ultimate induction cells or any large task
2.Watch tps plummet

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge: 1.10.2-12.18.2.2151
- Refined Storage: 1.2.5

Does this issue occur on a server? [yes]

@utoc Will post a sample file soon.

@way2muchnoise Same problem as before. Is it RS or just the nature of such large tasks?

**Comment by utoc** [comment]
Warmroast Screenshot: http://i.imgur.com/AbSuYBm.png

Sampler report: http://bbqsauce.terron.com/refinedstorage/lag1.nps

Strangely enough, the first iteration of this crafting task brought us down to 1.1TPS

`Dim 0 : Mean tick time: 843.279 ms. Mean TPS: 1.186`

**Comment by way2muchnoise** [comment]
Need to work on some linking system so it doesn't check tasks that still have tasks before it.

**Comment by way2muchnoise** [comment]
thb the AE2 way of "fixing" this was adding the "RAM" needed for the crafters :p

**Comment by raoulvdberge** [comment]
Well, he only crafted 16 induction cells. :P

**Comment by brad18** [comment]
Pushing RS to its limits all the time :P

**Comment by brad18** [comment]
I was going for 64 but it froze whilst calculating :(
