### ISSUE TITLE
External Storage cant read Interface content

### ISSUE THREAD

**Issue by leglerm** [raoulvdberge/refinedstorage#679]
#### Issue description:
As the title says the external storage cannot read the content of an Interface. In 1.7.10 i used to put down an Interface with a crafting upgrade to provide me items and connect an storage to it so basically items get crafted and provided by the interface and available in the storage by the external storage which was set to extract only mode.

#### What happens:
Items in the interface are not available in the storage (grid)

#### What you expected to happen:
Items are available

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge: 12.18.2.2122
- Refined Storage: 1.2.4

**Comment by raoulvdberge** [comment]
This is the wanted behavior, external storages on network blocks cause unstable behavior. A block to keep x items in stock will be coming in the future.
