### ISSUE TITLE
[0.6.11] Constructor not placing cake

### ISSUE THREAD

**Issue by DarkIceXD** [raoulvdberge/refinedstorage#68]
Hello,
the constructor cant place cake.
Greetings

**Comment by raoulvdberge** [comment]
Will take a look, thanks.

**Comment by raoulvdberge** [comment]
Note to self: check for ItemBlockSpecial.

**Comment by raoulvdberge** [comment]
This is fixed for the next MC 1.9.4 version, I'll backport the fix soon for a new MC 1.9 version.

**Comment by DarkIceXD** [comment]
Thanks
