### ISSUE TITLE
Autocrafting: Crafted item not detected

### ISSUE THREAD

**Issue by Lako007** [raoulvdberge/refinedstorage#680]
Does autocraft 16k Storage Block, but does not detect when crafted. Tried to take it out of system and back in, still not detecting. Didn't seen problem on other items, but dint tested on other storage blocks.

- Minecraft: 1.10.2
- Forge: 12.15.2.2151
- Refined Storage: 1.2.6

**Comment by way2muchnoise** [comment]
@raoulvdberge related to some NBT weirdness when inserting RS items that can store items in the grid. Eg. when inserting a storage disk the `protocol:1` tag will vanish. Or when inserting a storage block its tag will go from `{Storage:{Items:[], stored:0}}` to `{Items:[], stored:0}`. This is what breaks the insert checks.
