### ISSUE TITLE
Autocrafting with Fluids on SMP hanging indefinitely

### ISSUE THREAD

**Issue by ShneekeyTheLost** [raoulvdberge/refinedstorage#683]
#### Issue description:  
Autocrafting with Fluids hanging on Multiplayer server
#### What happens: 
Refined Storage attempts to create, recognizes it has everything it needs, but crafting is 'in progress' indefinitely
#### What you expected to happen: 
crafting of items
#### Steps to reproduce:
1. set up Crafter with recipe that includes fluid
2. attempt to use this recipe to craft with

Issue #670 is resolved, in that it no longer consumes all fluids, however it still won't actually craft. It seems to recognize that it has everything it needs, including bucket in network, and will recognize when it needs a bucket in the network to process, however in the Crafting Monitor, it shows a status of 'crafting' indefinitely, over a period of ten minutes. This was tested with Treated Wood from Immersive Engineering.

This is only appearing on multiplayer, and does not occur in SSP.
...

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge: 2151
- Refined Storage:1.2.5

Does this issue occur on a server? [yes/no] Yes (only)

**Comment by way2muchnoise** [comment]
Might be related to #680

**Comment by ShneekeyTheLost** [comment]
In that bug, the item is being crafted, but it doesn't detect that it is. In this bug, the item is simply not being crafted. Might be related, but two different issues. 

Also have had some strangeness in autocrafting of sticks when multiple wood types are present in the system and oredict is set to true on the recipe, where it will attempt and hang and not create sticks. This again only happens SMP, in SSP it works just fine. I'm wondering if the two issues aren't related, because both issues involve oredict and multiple types of wood present in the system and autocrafting is hanging in both cases.

**Comment by way2muchnoise** [comment]
Try and update RS, that multiple wood type was fixed some time ago, on mobile so can't find the issue or commit right now

**Comment by ShneekeyTheLost** [comment]
As of 1.2.8 this bug still persists

**Comment by ShneekeyTheLost** [comment]
This appears to be an OreDict problem. Recipe in Crafter is set to OreDict, but uses Oak Wood Planks in the recipe. When Oak Wood Planks are present in the system, it crafts without issue. When they are not, even when there are nearly 2k jungle wood planks in the system, it will hang indefinitely. 

This is as of Refined Storage 1.2.8 for SMP

**Comment by way2muchnoise** [comment]
Could you share some screenshots of your setup/patterns?

**Comment by ShneekeyTheLost** [comment]
I'll do you one better. Have a video <https://youtu.be/cAxUV51xg_M> showing
my setup, patterns, demonstrating the bug in question with both treated
wood and with sticks, and also a couple of minor things to do eventually.
Roughly 10 minute video.

**Comment by way2muchnoise** [comment]
I just tried it on a server in my dev env with acania wood like in the video and it all works. I can't for the life of me reproduce it :/

**Comment by ShneekeyTheLost** [comment]
Odd. 

Here's what I have done in the meantime. I've removed the recipes, and turned off oredict. Now it properly requests oak log to make planks to make sticks and treated wood, no problem. 

Not sure what is happening here or why, but I'll use this workaround until the reason can be found.

**Comment by way2muchnoise** [comment]
Is this still an issue with later versions?

**Comment by way2muchnoise** [comment]
@ShneekeyTheLost have you had a change to test with a later build?
