### ISSUE TITLE
Exporter regulator mode

### ISSUE THREAD

**Issue by raoulvdberge** [raoulvdberge/refinedstorage#684]
E.g. be able to specify that 20 iron needs to be available in an inventory.

**Comment by DuskFalls** [comment]
Exporter priority would be nice too, so you have a disk drive full of cobble with priority 1, then excess is sent to an exporter with priority 0 for example

**Comment by raoulvdberge** [comment]
You could do the same with external storages...

**Comment by DuskFalls** [comment]
You can? Ignore me then, i'll use them then

**Comment by BrewAndCode** [comment]
Raol; this is something I had always wished AE/AE2 supported.  I always got around it by using large chains of exports set with crafting enabled/redstone enabled,  going back into inventory, and an item limit redstone stick (forgot what that was called)

This would be a huge feature -- I mean who doesn't want to keep a few 100 glass in stock to speed up crafting, but doesn't want all their sand auto-smelted into glass.

An alternative to this would be to allow an API (maybe via an interface block) to be exposed to either Open Computers (Or CC when it comes to speed) that would allow the monitoring of Inventory levels and the calling of processing/crafting. Then let some LUA code jockeys write up some tools to have it controlled externally.  It sure would be easier than handling the management of it internally.

**Comment by raoulvdberge** [comment]
@BrewAndCode 

You can do the same thing already with interfaces (to keep things in stock). They won't automatically autocraft missing items unless it has a Crafting Upgrade.

But it seems handy to have it automatically exported, which is why I also really want this feature myself.

For the OpenComputers API, someone is working on it :)

https://github.com/davidog23/Refined-Storage-OCDrivers

**Comment by codewarrior0** [comment]
Any chance of this getting backported to 1.10.2?

**Comment by raoulvdberge** [comment]
Maybe!

**Comment by helldragger** [comment]
Is a backport of this feature planned anytime soon? my friends and I would love to use it on 1.10.2!

**Comment by raoulvdberge** [comment]
No, 1.10 wont receive updates anymore.
