### ISSUE TITLE
German translation for 1.2.6

### ISSUE THREAD

**Issue by dirk251272** [raoulvdberge/refinedstorage#685]
http://pastebin.com/W244tAvm #80

**Comment by way2muchnoise** [comment]
You might wanna look into creating a pull request for this one

**Comment by raoulvdberge** [comment]
Nah, I can add it myself too.

**Comment by raoulvdberge** [comment]
Thanks @dirk251272! I'll add the translation for 1.2.7 (next MC 1.10.2 version) and 1.3 (next 1.11 version).
