### ISSUE TITLE
Disk Drive and Storage Disk issue in server environment.

### ISSUE THREAD

**Issue by GodNero** [raoulvdberge/refinedstorage#686]
#### Issue description:
Disk Drive and Disk Manipulator will not accept Storage Disks (any type/size) in a 'storage' slot or 'in' slot respectively while playing in a server environment, this issue is not present in Single Player environments.

All other aspects of the mod 'seem' to be reacting/working as they should be in both environments.

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge: 12.18.2.2151
- Refined Storage: 1.2.6
- MCMultiPart: 2.0.0_88
- JEI: 3.13.3.381

Does this issue occur on a server? [yes/no]
Yes

**Comment by jennykitten78** [comment]
Same issue here, same versions too! Works fine in single player but not on a server.

**Comment by raoulvdberge** [comment]
Do you have any server logs when it didn't accept the disks by any chance?

**Comment by iamomicron** [comment]
A few of my modpack users have been suffering from this; and some have even crashed client side.

**[Here's a client Forge log](https://cdn.discordapp.com/attachments/105689603133935616/252838650151305217/fml-client-1.log)**

I don't have a server one to hand, but I'll try and recreate it and report back.
