### ISSUE TITLE
Unable to triple click items into a grid.

### ISSUE THREAD

**Issue by Harith163** [raoulvdberge/refinedstorage#69]
This is a bug that affects all versions where I am unable to triple click all stacks of an Item in my inventory into a grid. It is a minor bug that is quickly solved with a chest and an importer, but it is a vanilla functionality that should remain in my opinion.

**Comment by raoulvdberge** [comment]
What exactly should I do to triple click? I keep trying it in a vanilla chest, sometimes it works but sometimes it doesn't... what is the exact shortcut?

**Comment by Harith163** [comment]
With some item picked up, mouse over the item which has multiple stacks (in
your inventory) and triple click. It should all go in.

**Comment by Harith163** [comment]
The more important question is, how come this functionality did not work originally? Is it a bug with forge not supporting this vanilla functionality?

**Comment by raoulvdberge** [comment]
It doesn't work because the inventory you see in the grid isn't a real inventory!

**Comment by Harith163** [comment]
aha! I figured there was some trickery going on here :). Correct me if I am wrong but, what you do is you detect when the player shift clicks an item , you then delete the stack from that inventory and place it into the RS system? Can we do something similar for the triple click?

**Comment by raoulvdberge** [comment]
I could, but the clean solution would be to make the slots actually work.

**Comment by Harith163** [comment]
maybe we could refer some ae2 code?

**Comment by raoulvdberge** [comment]
We don't, I know how to do it myself. It'll just take a little time.

**Comment by Harith163** [comment]
Awesome!

**Comment by raoulvdberge** [comment]
https://twitter.com/vdbergeraoul/status/743067947065872384

;)
