### ISSUE TITLE
Item Deletion when Crafting

### ISSUE THREAD

**Issue by himdo** [raoulvdberge/refinedstorage#690]
#### Issue description:
when shift clicking to craft items in the crafting grid to be crafted it uses up the items in the system even if there is no room in your inventory to put it. there for deleting the "crafted" items
#### What happens:
deletes items when (using shift clicking) crafting with no room for that item in inventory
#### What you expected to happen:
not to craft items and leave resources in the system
#### Steps to reproduce:
1. have a full inventory
2. choose a crafting recipe that takes up a spot that you don't have
3. shift left click the item in the grid
4. check resources in system.. and they are gone

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge: 12.18.2.2147
- server Forge: 12.18.2.2147
- Refined Storage: 1.2.6

Does this issue occur on a server? [yes/no]
yes, I'm not sure if it happens in single player. haven't tested

#### If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here]

**Comment by raoulvdberge** [comment]
Are you in creative mode?

**Comment by himdo** [comment]
I have double checked my game mode and it happens when I'm in either creative or in survival mode. I am op on the server if that info helps any

**Comment by himdo** [comment]
So i just tested this out with a new pack involving just this mod and it appears that the excess items goes back into the system. and what ever doesn't fit fall to the ground. so I'm thinking that a separate mod i have installed has created the issue with your mod

**Comment by raoulvdberge** [comment]
Are you sure the excess items didn't go in your storage on your server?

**Comment by raoulvdberge** [comment]
I am pretty sure the excess items went back in your storage, so I'll close this.
