### ISSUE TITLE
Shift rightclick to take out single item

### ISSUE THREAD

**Issue by phit** [raoulvdberge/refinedstorage#691]
In AE you can take single items out of the terminal with shift + rightclick, I would love to see this added for grids.

**Comment by raoulvdberge** [comment]
Use middle click. You can combine it with shift + middle click to push it directly to your inv, or just middle click to put in your cursor.

**Comment by phit** [comment]
cool, didn't know about middle click! thanks

**Comment by raoulvdberge** [comment]
We also have a wiki, where all the grid interactions are shown:

https://refinedstorage.raoulvdberge.com/wiki/grid
