### ISSUE TITLE
Game crashes when right clicking an exporter with a block (yellorium ingots)

### ISSUE THREAD

**Issue by Kevincav** [raoulvdberge/refinedstorage#692]
#### Issue description:
My game crashes (but not the server I think) when I right click an exporter with a yellorium ingot (potentially others).  I believe this actually may not be a RS problem but more of trying to place an ingot down as well as opening the exporter at the same time.

#### What happens:
Game crashes

#### What you expected to happen:
The exporter opens

#### Steps to reproduce:
1. Place an enderlink chest (I had another one going into an extreme reactor)
2. Place an exporter into the chest
3. Right click the exporter with an ingot in hand (my ingot has always been yellorium)
...

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge:
- Refined Storage: 1.10.2

Does this issue occur on a server? [yes/no]  Yes but only the client crashes (I think)

#### If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here]
pastebin.com/PPeC3GQ9

**Comment by raoulvdberge** [comment]
This is not an RS issue, this is a `com.primetoxinz.stacksonstacks` (StacksOnStacks) issue. Please report it to them.
