### ISSUE TITLE
Solderer not auto crafting Version 1.2.4

### ISSUE THREAD

**Issue by GothCartel** [raoulvdberge/refinedstorage#694]
#### Issue description: Solderer not being found by crafters, the controller can see the solderer and the crafters, it can see the inporter attached to the solderer
![2016-11-30_13 46 45](https://cloud.githubusercontent.com/assets/17881804/20758671/732c275a-b712-11e6-928f-b688bb7ccb75.png)
![2016-11-30_13 47 05](https://cloud.githubusercontent.com/assets/17881804/20758669/732bac3a-b712-11e6-94a8-807ad704cfda.png)
![2016-11-30_13 47 13](https://cloud.githubusercontent.com/assets/17881804/20758672/732cd77c-b712-11e6-89c3-166a1d99e48f.png)
![2016-11-30_13 47 22](https://cloud.githubusercontent.com/assets/17881804/20758670/732c0a04-b712-11e6-9d9a-53e31a9555a4.png)

#### Steps to reproduce:
1.
2.
3.
...

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge: FTB Hermitpack 1.4
- Refined Storage: 1.2.4

Does this issue occur on a server? [Yes]

#### If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here]

**Comment by way2muchnoise** [comment]
You need to place a crafter facing against the solderer. Patterns in that crafter will now be inserted into the solderer. Also you can only extract the output from the bottom of the solderer. So you'll need to relocate that importer.

**Comment by way2muchnoise** [comment]
You might want to read up on [autocrafting on the wiki](https://refinedstorage.raoulvdberge.com/wiki/autocrafting) or watch some youtube videos on it. (Would advice [LHS Buster](https://www.youtube.com/watch?v=J16-w1gDV7g) or [Direwolf](https://www.youtube.com/watch?v=pMHww6qpABA))

**Comment by GothCartel** [comment]
Tried it with the crafter facing it, didn't work. Also if you watch any of the hermitcraft videos no one has the crafter behind the solderer it's always next to or above which I have tried both ways

**Comment by raoulvdberge** [comment]
> didn't work

Tell us more than "didn't work" please

**Comment by GothCartel** [comment]
It simply will not craft the item it keeps saying machine not found. I've even tested in a creative world with 2 crofters pointing into a solderer just a simple pattern in . Both with a full set of speed upgrades in. That time it said it was processing but nothing happens.  No raw materials fed into the solderer even though I tried importers on every side one at a time then after that as many sides as I could. Still no soldering.

**Comment by GothCartel** [comment]
Unless I'm doing something monumentally stupid I can't seem to figure the problem out. I've worked with mods for many years even created a few packs myself. I've got an IQ of 158 and it's got me utterly vexed
