### ISSUE TITLE
Server crash upon startup

### ISSUE THREAD

**Issue by topher2010** [raoulvdberge/refinedstorage#695]
#### Issue description:
Updated to version 1.2.7 (latest on curseforge) and getting a server crash on startup.

#### What happens:
Crashes on server startup

#### What you expected to happen:
Server to start.

#### Steps to reproduce:
1. Redownloaded current mod file
2. Started server

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge: 12.18.2.2151
- Refined Storage: 1.2.7

Does this issue occur on a server? [yes/no]
Yes

#### If a (crash)log is relevant for this issue, link it here:

http://pastebin.com/J45Kp0qa

**Comment by demethan** [comment]
followup ...  we found it is an interaction between Deep Resonance and Refined storage. 

https://github.com/McJty/DeepResonance/issues/145

**Comment by way2muchnoise** [comment]
Related to #566, you are not supplying sufficient power to some controller and thus the graph keeps rebuilding

**Comment by demethan** [comment]
I disagree in this case. the controller is connected to a RF Cell and it is fully power with a 4000 rf/t system supplied by a 6GigaRF battery­. 

Also the crash is on server bootup.

**Comment by way2muchnoise** [comment]
Well, alright I though you were powering it with a Deep Resonance crystal and that was doing something odd or so. My bad

**Comment by demethan** [comment]
No worries

**Comment by demethan** [comment]
It was working fine until I slapped a bus on a deep resonance machine.

**Comment by raoulvdberge** [comment]
Don't think this is an RS issue. Something in DeepResonance takes too long when reading the inventory.
