### ISSUE TITLE
NullPointerException in CraftingPattern.getOutputs

### ISSUE THREAD

**Issue by annihone** [raoulvdberge/refinedstorage#696]
#### Issue description:
NPE when crafting IndustrialCraft Advanced Circuit via Pattern in Crafter. Normal Circuit does not throw Exceptions. I guess ItemStack can be null?

#### What happens:
Server shuts down with NPE at com.raoulvdberge.refinedstorage.apiimpl.autocrafting.CraftingPattern.getOutputs(CraftingPattern.java:203) (not sure why there's a curly in the current code at this line but i definitely just downloaded the latest version an hour ago)

#### What you expected to happen:
Item gets crafted... I guess?

#### Steps to reproduce:
1. Try to craft Pattern of IndustrialCraft Advanced Circuit in Crafter

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge: 1.10.2-12.18.2.2124
- Refined Storage: 1.2.7 (updated from 1.2.4 in Direwolf's 1.10 pack)

Does this issue occur on a server? [yes/no]
yes

#### If a (crash)log is relevant for this issue, link it here:
http://pastebin.com/1BtZ1qFE

#### Full MC crash report just in case
http://pastebin.com/n7FVMCWj

**Comment by way2muchnoise** [comment]
Same as #586, fix incoming
