### ISSUE TITLE
Solderer sucks item back into itself

### ISSUE THREAD

**Issue by furraver** [raoulvdberge/refinedstorage#697]
#### Steps to reproduce:
1. go to a world place down a solderer and refine storage system so it can work
2.put in a ingot or diamond let it process 
3.0it will then shift it to the left top slot after its done making
...

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge:12.18.2.2099
- Refined Storage:1.1.3

Does this issue occur on a server? [yes/no] yes and solo creative world

#### If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here]

**Comment by raoulvdberge** [comment]
It can only be pulled out frm the bottom side.
