### ISSUE TITLE
Search for tooltip in the grid (maybe even NBT)

### ISSUE THREAD

**Issue by DigitalSketch** [raoulvdberge/refinedstorage#698]
I was trying to find a location to put a feature request, but haven't been able to find a place.  Hope this is OK to put here.

I think it would be nice to be able to search NBT data, so when you're looking for say, an enchanted book, you could search for the enchant you want, and it will find them in the system :)

**Comment by raoulvdberge** [comment]
Can't you just do `#efficiency` to find for example efficiency enchanted tools?

**Comment by DigitalSketch** [comment]
Holy crap that works :)  I didn't realize!!! Thanks!
