### ISSUE TITLE
Shift-clicking and inputing drives issue

### ISSUE THREAD

**Issue by frogalo** [raoulvdberge/refinedstorage#699]
I cant put discs into drives. (They are staying in my inventory and i see ghost disc icons on the to slot of drive)
Also i have problems with shift clicking stuff into system.

**Comment by Fragmentd** [comment]
This as well is happening to me. Pack is the Direwolf20 1.10. Tried creative and survival world. When shift clicking the drive goes into the top row (Filter row I believe). Can not place disks in no matter what I've tried.

**Comment by way2muchnoise** [comment]
Most likely due to an old version of RS. What version are you using?

**Comment by Fragmentd** [comment]
Curse says 1.2.4

**Comment by raoulvdberge** [comment]
This issue was fixed in the last version of RS

**Comment by frogalo** [comment]
also ghost discs?
