### ISSUE TITLE
Improving automation for machines

### ISSUE THREAD

**Issue by Harith163** [raoulvdberge/refinedstorage#70]
I ordered 256 iron ingots from this set up. The pattern is one ore to one ingot.
https://imgur.com/a/2Xa1l
The request goes to only one furnace and it is not even the first furnace in order from the controller. It is also not on any chunk border.

I was thinking that when a request>1 is made it sends that many requests into the furnace at the same time. the system could also detect if there are multiple machines (say furnaces) connected to a system with multiple crafters with the same processing pattern. It could then evenly spread it across all furnaces that have crafters attached with the requested pattern.the remainder could go into any random one.

**Comment by raoulvdberge** [comment]
No, this will make the code way too complex.
