### ISSUE TITLE
More complex auto crafting

### ISSUE THREAD

**Issue by dancoool** [raoulvdberge/refinedstorage#704]
#### Issue description:
When i try to put same pattern to multiple crafter, only one crafter will do the work
#### What you expected to happen:
i think the system only choose where is the nearest then only do with that

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge:latest
- Refined Storage:lates

Does this issue occur on a server? [yes/no]no

Please fix this bug -/\-

Thanks before

#### If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here]

**Comment by chameleoon** [comment]
+1
Just tried this last night, the only way to do this is by dumping from crafter to a chest and than using item conduits with round robin for smelting/crushing recipes across multiple smelters/crushers

**Comment by TheVanoq** [comment]
+1, desperately needed.

A feature like this would make this mod even better than AE2, IMO.
Any idea on the ETA?

**Comment by way2muchnoise** [comment]
It does need to be the exact same pattern, same inputs, same outputs and other settings (blocking, oredicted)
