### ISSUE TITLE
[1.11] External Storage Client Crash

### ISSUE THREAD

**Issue by hugeblank** [raoulvdberge/refinedstorage#707]
#### Issue description:
The issue occurs when I connect things to my storage system. Both cause the client to crash, but the server remains fine.

#### Steps to reproduce:
For crash report 1 I did:
1. Place down External storage on a storage means
2. Connect storage system to it from the controller to the External storage (or vice versa, only tested connecting from storage system to the External storage)
For crash report 2 I did:
1. Place Crafting Grid on top of controller

### Expected and Actual Results
Expected result: Everything connects just fine
Actual result: Client side crash (log below)

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.11
- Forge: 1278 
- Refined Storage: 1.3.1

Does this issue occur on a server? [yes]

#### If a (crash)log is relevant for this issue, link it here:
Report 1: http://pastebin.com/ja3VRQwu
Report 2: http://pastebin.com/usrdHAJb
By the way, great mod! It has added a whole new dimension to 1.11 as far as storage solutions :D

**Comment by raoulvdberge** [comment]
Thank you for trying out 1.11, this bug has been fixed and will be in the next release.

**Comment by hugeblank** [comment]
@raoulvdberge Thank you so much! 
Off topic: I've had my fair share of 10 year olds being assholes on the internet, but holy crap did McSassy just top them all off! I am very sorry for that degrading asshole, and the fact that you had to deal with him. I hope that issue gets resolved so you can shut his/her (I'm pretty sure they are either gay or a girl) whiny ass up. I'm working towards getting a job over the summer (at the latest), and I will make sure to slap a crisp 100 down, because DAMN do you deserve it. Note: sassy is an adult, given they had a husband...
