### ISSUE TITLE
Fluid interface can't be autocrafted

### ISSUE THREAD

**Issue by MrPatience** [raoulvdberge/refinedstorage#708]
First of all , I know i'm not on latest version , if it is fixed i must say i'm sorry but i play on a public modpack and SMP , I can only wait for modpacks updates (Playing Hermitcraft modpack btw)

#### Steps to reproduce:
1. Set up a crafter on top of a solderer, 
2.put inside the recipe pattern.
3.There you go.
...

#### Version (Make sure you are on the latest version before reporting): 

- Minecraft: 1.10.2
- Forge: 12.18.2.2123
- Refined Storage: 1.2.4

Does this issue occur on a server? Yes

**Comment by raoulvdberge** [comment]
Yes this is fixed, you'll have to recreate your pattern though

**Comment by raoulvdberge** [comment]
This is not really a problem with the autocrafting, I'll have to change the recipe I think

**Comment by MrPatience** [comment]
Okay then , keep up the good work :heart:

**Comment by raoulvdberge** [comment]
@MrPatience Can you try if this issue persist in the latest 1.10.2 version?

**Comment by MrPatience** [comment]
I'm on it , wait a few mins

**Comment by MrPatience** [comment]
Still not working , same issue
