### ISSUE TITLE
Autocrafting with Ender IO machine

### ISSUE THREAD

**Issue by noobyaran9** [raoulvdberge/refinedstorage#711]
#### Issue description:
Autocrafting on Ender IO Slice'n'Splice fail.
RS storage doesn't detect Soul Vial with content in it when autocrafting.

#### What happens:
When I was trying to autocraft using Ender IO Slice'n'Splice, the system took all the item but it doesn't send the item over to the machine. And on the crafting monitor it shows that it is crafting the item. After I cancel the crafting task, the items that is used in the crafting process was voided.

I try to autocraft ender crystal from Ender IO which requires a vibrant crystal and a soul vial with enderman in it, but the task confirmation window show that there is no such Soul Vial in the system when i have like 20 in my system.

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge:12.18.2.2171
- Refined Storage:1.2.8

**Comment by StevenB83** [comment]
When I tried automating ender crystals it would work some times, but other times complain about not having Enderman soul vials.
I worked around this by having a separate soul binder for it and just export soul vials and liquid xp to it and have crafting recipe be vibrant crystal = ender crystal.

As for Slice'n'Splice all the recipes I have put in has worked just fine after build 136 of EnderIO, which fixed items going into the correct slots.

**Version (Make sure you are on the latest version before reporting):**

- Minecraft: 1.10.2
- Forge: 12.18.2.2179
- Refined Storage: 1.2.8

**Comment by raoulvdberge** [comment]
Can you try recreating your Soul Binder patterns (and dependant patterns) in the latest build and see if it works again?

**Comment by StevenB83** [comment]
Hi, remade the patterns, but it still says missing Soul Vial Enderman.
Tried making it directly via JEI with and without oredict enabled (just to be sure), also tried replacing the Soul Vial Enderman with a vial from the system in both oredict and without.
So in total 4 different patterns with the same results.
The exporter finds the soul vials without any issues if I disable NBT matching, which will break it if I keep other soul vials in the system. It would seem to me that the issue has to do with NBT matching, tho the recipe in pattern or whitelist on exporter doesn't even work with the specific vial I make the pattern/whitelist with.
Hope this can assist you in tracking it down.

Steven.

**Comment by noobyaran9** [comment]
I've tried updating Ender IO and Ender Core to the latest version (ver138 and ver60).
This still doesn't fix the Slice'n'Splice problem. I remember that on Refined Storage version 1.2.4, this autocrafting worked.

For the Soul Binder, recreating the pattern with the soul vial i have on hand and not using JEI to set the pattern still doesn't work.

**Comment by JaRyCu** [comment]
I'm having a similar issue with the Slice'N'Splice.  I'm trying to make the Z Controller which takes a zombie head, a redstone, 2 soularium, and 2 silicon balls.  I've tried crafting the recipe as a "shapeless" recipe, and I've tried actually doing the correct shape, and my results are similar to noobyaran9's except I don't lose the stuff when I cancel the recipe.  I have the SNP connect to the crafter with the recipe in it and an importer coming out the bottom of the SNP.  I also checked the SNP's config and set it to pull from the back (crafter) and push the output out the bottom (importer).  That's how my Alloy Smelter and SAG Mill are both setup and they work fine, as do all 4 of my solderers with the same setup.

The extra piece of info that I can add is that the first time I tried to create the recipe pattern, it also added in the axe & shears that normally just sit in the Slice'N'Splice.  I had to manually click those out.  Could that have something to do with it?

**Comment by way2muchnoise** [comment]
Issue here seems to be the oredict flag. It takes what ever other skull so it won't actually craft.

**Comment by way2muchnoise** [comment]
@JaRyCu that is something we can't handle, as JEI only has either input or output slots. I base the pattern on that and all non input slots are thus tagged output.

**Comment by way2muchnoise** [comment]
@StevenB83 crafting Ender Crystals works fine for me. Also tried Sentient Ender, again no issues. It might have been related to my fix in 555256ece809cad3df67ef0328d24a1e4ab29332

**Comment by way2muchnoise** [comment]
Although an issue that could happen is the hp of the mod in the vial. As I did try it with cheated in materials.

**Comment by StevenB83** [comment]
Yes, cheated in would work just fine as they have literally no nbt data compared to the "real" thing.

cheated in: http://imgur.com/rwhaCAN
captured: http://imgur.com/xXX3QBv

**Comment by ariosos** [comment]
I've had a similar issue with Ender Crystals (due to the soul vial). Turns out I had to use an actual Endermen soul vial instead of the one from JEI. Maybe try putting items through an Interface or a chest? I just tested putting the items into a chest, and it did put in an enderman head. So, that's a work-around. (Reminds me of old AE1 setups).

**Comment by JaRyCu** [comment]
I never used AE1, so I'm unfamiliar with the "chest method" you're describing above.  Are you saying just to use a chest as a buffer of sorts...like tell the system if it throws X of this and Y of that into a chest, it can get Z of the result back out of it?  The set the machine to just pull from the chest the raw ingredients and push the final result back into it?  (Or maybe stick a filter item conduit in-between to make sure there are no hiccups?)

**Comment by ariosos** [comment]
The "chest method" I was referencing was in a old Direwolf20 video. Basically, putting items into a chest, then sorting that into the correct machine (which accepts more than 1 item at a time).

**Comment by JaRyCu** [comment]
I think I watched Hypnotizd doing that tonight on Hermitpack actually.  It seemed simple enough that I think I could do it easily.
