### ISSUE TITLE
disk can't be put into the disk drive[FTB DW20 1.10pack]

### ISSUE THREAD

**Issue by RoyalShooter** [raoulvdberge/refinedstorage#712]
#### Issue description:
I am playing with my frind in our own server,with direwolf20 mod 1.10 mod pack,we are tring to upgrade the storage system and use refinedstorage.after we make all the parts we find we have no way to put the storage disk into the disk drive.

#### What happens:
we place down the controller and the diskdrive and the grid.when we try to put the disk into the drive ,it wont let us to do it.we have try to craft a new drive or cheat one,it just not working.

we have tried 1k and creative disk.both not working....

befor we cheat or craft the disk,the item description look like this:http://imgur.com/dwUpPer
but after we craft it or spawn it OUT,it look like this:http://imgur.com/zPm64Be
#### What you expected to happen:
we should be able to put the disk into the disk drive......

#### Steps to reproduce:
1.FTB:direwolf20 1.10 pack
2.
3.
...

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge:
- Refined Storage:

Does this issue occur on a server? yes

#### If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here]

**Comment by StevenB83** [comment]
I just tested on the stable DW20 and the latest beta, I can put the disks in the drive both in SP and on server.
The stable DW20 has 1.2.5 of RS and use Forge 2124 and the latest beta has 1.2.8 and Forge 2171.
Both work just fine for me in SP and on a server.

**Comment by raoulvdberge** [comment]
I can't reproduce this either.

@RoyalShooter Which version of RS are you running? Always important to state that in an issue.

**Comment by RoyalShooter** [comment]
ok,well I tried again and yes the bug is still here and I have no idea why

**Comment by raoulvdberge** [comment]
Version of RS please....

**Comment by Lpfreaky90** [comment]
I've come across the same issue, also with the Direwolf20 pack.
The refined storage version I'm using: refinedstorage-1.2.4

This happened for me when I tried to move my storage system. I can't re-insert my existing (64k) storage drives, nor new ones created in Creative (any size). My friend was still able to use his storage system properly, until I asked him to take a look at my system, at which point it broke for him as well.

I rebooted the server, removed my playerfile (and rebooted) and the problem persists. 
Just loading up the game in creative mode (without the server) allows me to use it properly.

**Comment by raoulvdberge** [comment]
What if you update to the latest RS version for 1.10.2?

**Comment by Lpfreaky90** [comment]
I just did that, and I seem to be able to interact with stuff again.
Unfortunately my old storage disks don't get recognized at all.

**Comment by RoyalShooter** [comment]
I have tri to open a new singleplayer world and it work find with no ploblems....I will try to tell my friend to update the server side RS,and see will it work

**Comment by aelfwyne** [comment]
I just hit the same bug. Ejected my 64k storage disks (Three of them!!!) and moved to a new location. Tried to insert the disks, and they refuse to go in the drive. This is 100% a bug, and is not user error. Sorry you can't reproduce it, but it exists.

The person who stated that upgrading "worked" also said old storage disks no longer get recognized. This is a disaster, 3 64k disks, nearly 60% full, is everything I have. 

I knew I shouldn't have trusted this mod.

**Comment by aelfwyne** [comment]
Another update: I went through the trouble of moving the ENTIRE INVENTORY (after updating RS) to a Storage Block instead of a Storage Disk. Picked up and placed the storage block, no problem. Picked up the storage block and brought it to my new base, plopped it down, and the fscker is EMPTY.

**Comment by raoulvdberge** [comment]
> I knew I shouldn't have trusted this mod.

Get out.

**Comment by raoulvdberge** [comment]
I tested this myself:
- open a new world with RS 1.2.4 (from the latest stable)
- have both a storage disk / storage block, insert some stuff from Extra Utils and vanilla
- close MC
- update RS to latest, and remove Extra Utils as a stresstest to see what happens
- open MC
- storage block and disks are still there, can re-insert / break them, and items from vanilla are still there.

**Comment by raoulvdberge** [comment]
Small question, did you guys close your server forcefully? Or did it crash? If it closes forcefully, your disk drive might have not the chance to save the disk state, causing the corruption.

**Comment by raoulvdberge** [comment]
Also, can you guys reproduce this when updating from RS 1.2.4 -> 1.2.9 on the **latest Forge**?

**Comment by Lpfreaky90** [comment]
Yeah, it's likely a very unfortunate combination of events.

It happened with normal use randomly in 1.2.4, since upgrading to 1.2.9 **with** the latest forge I can use RS properly again, but my old disks are indeed corrupted.

**Comment by Properpeanut** [comment]
Try going into creative with the drives in inventory and then back to survival. In 1.2.4 the disk drive wont recognize any drives that has been taken from creative nor carried in inventory during creative...

**Comment by raoulvdberge** [comment]
@Properpeanut 1.2.9 fixed this, please update and see what happens. Take a backup to be sure.

**Comment by hsim-bml** [comment]
@raoulvdberge Not sure whether to re-open new issue or provide here, but recently had a disk corrupt, could put it inside the disk drive, but it would show 0/0 space and couldn't be used, mind you this was on a 1024k drive from the Extra Storage mod.

Not too sure exactly what array it's talking about due it to being in anonymous functions, but hopefully it should help!

Here's the logs of the corruption:
[error.log](https://github.com/refinedmods/refinedstorage/files/7111250/error.log)
