### ISSUE TITLE
Autocrafting does not work properly

### ISSUE THREAD

**Issue by Darkere** [raoulvdberge/refinedstorage#714]
#### Issue description: 
Pressing start on autocrafting operation greys out the button and does nothing instead of showing the expected required items. Not entirely sure  what causes it because another recipe I tried worked once then not anymore.

#### Steps to reproduce:
1. Create patter for crafter.
2. Try autocrafting the crafter.
3.
...

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.11
- Forge:13.19.0.2180
- Refined Storage:1.3.2

Does this issue occur on a server? yes

#### If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here]

**Comment by raoulvdberge** [comment]
Normally when this happens the server should have an error or exception the log, can you send that to us?

**Comment by Darkere** [comment]
Tried it in Singleplayer no output on the console.

**Comment by raoulvdberge** [comment]
For which item do you have this bug? Does it happen on every item?

**Comment by InusualZ** [comment]
I think the problem is that he is using RS 1.3.2 for MC 1.10

**Comment by Darkere** [comment]
no im on 1.11

**Comment by Darkere** [comment]
On the server it was with the crafter this time i tried a construction core.

**Comment by InusualZ** [comment]
you put the wrong version in the issue

**Comment by raoulvdberge** [comment]
Can you give me the output that the server gives on the console....
