### ISSUE TITLE
Suggestion: Mekanism gas storage/interaction?

### ISSUE THREAD

**Issue by MrPatience** [raoulvdberge/refinedstorage#715]
I don't know if it is planned and i don't see it on the github , so i'll ask there.
Could you implement gas storage and interaction ? I'd love it because right now neither ae2 nor ender io can transfer gas , and i'm really bored using my floor as a "all cables here" (ender io/refined storage cables/ mekanism gas pipes with different gas ) , as I "create" gas at one "production plant" and then distribute it everywhere in my basement.

**Comment by raoulvdberge** [comment]
No for the reason see #588
