### ISSUE TITLE
Mouse-over visibility on where an item is stored

### ISSUE THREAD

**Issue by EvilNotion** [raoulvdberge/refinedstorage#716]
When mixing disk drives, storage blocks, and external storage, it would be nice if we could see (on mouseover) where items are stored.  This is probably a large task and a silly request but sometimes you end up with things like Iron ingots in both disk drive and Quantum Storage (for example).  It would be nice to know where things are so we can be sure all of an item is where it should be.

**Comment by raoulvdberge** [comment]
No, this is a lot of work for very little benefit. Just turn storages on or off to see where stuff is stored.
