### ISSUE TITLE
External Storage attached to a controller causes the controller to break (becomes an item)

### ISSUE THREAD

**Issue by wylderhoads1809** [raoulvdberge/refinedstorage#717]
#### Steps to reproduce:
1. Place controller, grid and 1k storage module (network 1) and place another controller, grid and 1k storage module (network 2).
2. Attach network 1 controller to network 2 controller via external storage.
3.
...

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge:1.10.2-forge1.10.2-12.18.2.2166
- Refined Storage: refinedstorage-1.2.8

Does this issue occur on a server? [yes/no] idk

#### If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here]

**Comment by raoulvdberge** [comment]
There aren't subnetworks in RS, so this should be a feature request, not a masked feature request under a bugreport. And no, we won't add subnetworks to RS unfortunately.

**Comment by wylderhoads1809** [comment]
Apologies, I didn't realize that the controller breaking was a feature and
not a bug.
