### ISSUE TITLE
Tooltip is too big to fit -_-

### ISSUE THREAD

**Issue by Darkosto** [raoulvdberge/refinedstorage#719]
#### Issue description:
I love tooltips just as much as the next guy. But, this one is a little too large for me!
#### What happens:
https://sx.artdude.uk/hotlink-ok/darkosto/Cf6n-96b10-1481134960.png
#### What you expected to happen:
Not to have a mile long tool tip
#### Steps to reproduce:
1. Mouse over Solderer
2. ???
3. Profit
...

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge: 2185
- Refined Storage: 1.2.9

Does this issue occur on a server? [yes/no]
probably!
#### If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here]

**Comment by way2muchnoise** [comment]
But don't you just love tooltips that cover your whole screen?

**Comment by raoulvdberge** [comment]
The only reason that tooltip is there because I was getting so much "issue" reports about it (aka users just not understanding that you need a Controller first). But it can use some extra lines yes :P
