### ISSUE TITLE
Destructors not working with Botania

### ISSUE THREAD

**Issue by EvilBastard** [raoulvdberge/refinedstorage#723]
#### Issue description:
Destructors aren't working on living wood and living rock.
#### What happens:
Nothing happens. That is the problem. I even have the correct items in the destructors filters
#### What you expected to happen:
For them to pick up the living rock and wood and deposit them in the chest I have attached to an external storage bus.
#### Steps to reproduce:
1. Create stand alone RS network in the 1.10.2 Direwolf20 pack
2.  Set down constructors and destructs upon logs or rock. 
3.  Set their filters appropriately. Hook to RS controller.
4.  Watch logs and rock being placed.  
5.  Once living wood and rock have been made, watch nothing happen.
...

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge:  Laest
- Refined Storage:  1.2.8

Does this issue occur on a server? [yes/no]

#### If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here]

**Comment by raoulvdberge** [comment]
Try turning NBT / damage compare off in the sidebuttons?

**Comment by EvilBastard** [comment]
Did that and still not working.  Trying to upgrade to the 1.2.9, but can't find where to update forge mod loader in the DW20 1.10 pack.

**Comment by raoulvdberge** [comment]
If you remove the filters, does it work then @EvilBastard? E.g. does the destructor do anything at all?

**Comment by EvilBastard** [comment]
Still didn't work. I even tried it with a piece of dirt and a piece of cobble and it wouldn't break and pick up either one. Even after trying all the various options.

**Comment by InusualZ** [comment]
Are you using FTB Utilities?

**Comment by raoulvdberge** [comment]
FTB utilities' protection feature blocks the Refined Storage fake player from destroying blocks.

Try this command and let me know if it worked:

/ftb team config ftbu.fake_players true

**Comment by EvilBastard** [comment]
That worked!   Might want to add that to the guide for Refined Storage or somehow work around it.

**Comment by raoulvdberge** [comment]
Cool, added it to the wiki.
