### ISSUE TITLE
Constructors and Botania Flowers

### ISSUE THREAD

**Issue by Drakkim** [raoulvdberge/refinedstorage#724]
#### Issue description:
"Botania flower" placed instead of Hydroangeas when placed by a Refined Storage Constructor.

#### What happens:
"Botania flower" placed

#### What you expected to happen:
Hydroangeas  placed

#### Steps to reproduce:
1. Set a constructor to place a Hydroangea on a dirt block

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge: 12.18.2.2171
- Refined Storage: 1.2.8
- Botania: r1.9-339
- Direwolf20 1.1.2

Does this issue occur on a server? yes

#### If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here]

Cross-posted to the Botania tracker as well: https://github.com/Vazkii/Botania/issues/2063

**Comment by raoulvdberge** [comment]
What is a "botania flower"? Is it the generic flower?

**Comment by ArukaAlter** [comment]
An empty flower, they all use the same id and are defined by NBT.
They are getting placed with a blank tag.

**Comment by raoulvdberge** [comment]
Thank you, I will look into it.

**Comment by raoulvdberge** [comment]
This is not a Botania issue, @Drakkim. You can close your issue on their tracker, if you want.
