### ISSUE TITLE
RFTools Dimentions support (Direwolf20 ftb 1.10 pack)

### ISSUE THREAD

**Issue by WhiteWinds98** [raoulvdberge/refinedstorage#725]
#### Issue description:
The network transmitters and recevers are not supporting de worlds created by RFtools Dimentions.
#### What happens:
If I make a network card, and set it to the new dimention, it sets it to the appropriate coördinats in the overworld, and not the once in the Dimention. 
#### What you expected to happen:
It counting as the 1k RS cost like for nether or end.
#### Steps to reproduce:
1. Make a dimention via RFTools Dimentions
2. Put a recever in the new Dimention.
3. Link it via a network card to your network in the overworld.
4. Recever in the new world not activating.
...

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge:
- Refined Storage:

Does this issue occur on a server? [yes/no]
Yes
#### If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here]

**Comment by raoulvdberge** [comment]
Are both areas chunkloaded?

**Comment by WhiteWinds98** [comment]
Yes, I'm using Ic2 chunkloaders in both places

**Comment by raoulvdberge** [comment]
This will be fixed when #370 is fixed
