### ISSUE TITLE
Void excess fluids Issue

### ISSUE THREAD

**Issue by Predatorino** [raoulvdberge/refinedstorage#726]
#### Issue description:
Fluid Cells get negative value when using Void excess fluids 
I set up a infinite water generator that outputs into the system and assigned a 64k fluid cell with a high priority and put water into the filter and also enabled void excess fluids later i added more 64k fluid cells for other liquids

#### What happens:
The other cells are showing negative values and the fluid grid shows more and more water although it should only go into one of the 64k cells the liquids i stored in the other 2 cells are still accessible.
The only workaround i found is to set a filter for every storage cell not to accept water and then to connect them after that

#### What you expected to happen:
The water cell with the high priority should fill up until its full and void the excess water while the others cells (with low priority) should stay untouched. And the system should not be able to store more then 192 buckets as i only have 3 64k cells

#### Steps to reproduce:
1.Place destructor under infinite water source
2.Place 64k cell and set high priority and void excess fluids
3.Wait until the cell filled up and place a second cell
4.Observe the stored bytes of the second cell as they turn negative
5.Observe more water available in your fluid grid that you have storage

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge:12.18.2.2171
- Refined Storage: 1.2.8 (cant find a way to update forge in the Pack im using but i searched if this error was reported and checked the changelog ... sry for that)
- Direwolf20 1.1.3 

Does this issue occur on a server? [yes/no]
Happened on Server and Singleplayer 

![2016-12-08_17 24 27](https://cloud.githubusercontent.com/assets/24459340/21018632/d59fac7a-bd6d-11e6-9494-a4f6aafcbcc7.png)
![2016-12-08_17 24 15](https://cloud.githubusercontent.com/assets/24459340/21018634/d92b3c92-bd6d-11e6-89c1-e833a3304ebb.png)

**Comment by raoulvdberge** [comment]
Note to self: this bug is not present in 1.11.
