### ISSUE TITLE
Option to change enriched iron recipe?

### ISSUE THREAD

**Issue by Ash70** [raoulvdberge/refinedstorage#730]
I have a request. The one thing that bugs me about rs is the enriched iron recipe. For some reason it "feels" out of place for me. Would it be possible to change it to another recipe using e.g. the alloy smelter from ender io, perhaps as an option?

**Comment by way2muchnoise** [comment]
This is something you could easily do yourself with Minetweaker/Crafttweaker

**Comment by Ash70** [comment]
Ah, ok... didn't know that. I'll give it a try. Thanks.
