### ISSUE TITLE
Block entity being ticked -> Crash

### ISSUE THREAD

**Issue by Orcinuss** [raoulvdberge/refinedstorage#733]
#### Issue description:
The server is unable to update a block. Not sure which exactly, but it causes a crash.
I think this has to do with sponge so I posted there first but since your mod is also in the report, i reported it here too. 
https://github.com/SpongePowered/SpongeForge/issues/1100

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge: 12.18.2.2171
- Refined Storage: 1.2.8

Does this issue occur on a server?
yes
#### If a (crash)log is relevant for this issue, link it here:
http://pastebin.com/ygfhrhbg

**Comment by raoulvdberge** [comment]
not an RS issue
