### ISSUE TITLE
Ore Dictionary Doesn't Allow Some Recipes To Complete

### ISSUE THREAD

**Issue by Darkosto** [raoulvdberge/refinedstorage#734]
#### Issue description:
When selecting Ore Dictionary on patterns for auto-crafting, patterns with items that do not have an ore-dictionary alternative item (ex. fishing pole) will not complete when auto-crafting. They sit in the crafting monitor and show no signs of working.

#### What happens:
Make patterns with ore-dictionary selected, choose autocraft, doesn't work

#### What you expected to happen:
I expect the auto-craft operation to work.

#### Steps to reproduce:
1. Create pattern for fishing pole
2. Select Ore-dictionary
3. Autocraft
4. Check crafting monitor
5. ???
6. Profit.. without a fishing pole
...

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge: 2185
- Refined Storage: 1.2.9

Does this issue occur on a server? [yes/no]
Probably, I assume it does. Most likely. Although, I didn't really test it on a server.

#### If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here]

**Comment by way2muchnoise** [comment]
It works fine for me? Tested it with the latest SF on the repo. All ore dict patterns.

**Comment by way2muchnoise** [comment]
Also works just fine on SF from the repo. All patterns oredict again.

**Comment by Darkosto** [comment]
OKAY! Apparently, it works. I don't know what kind of voodoo magic you've used on my modpack, but it just started working all of sudden. IT HAS NOTHING TO DO WITH MY PATTERNS OR WHETHER I DERPED IN MAKING THEM. It has everything to do with you casting some type of black magic spell onto my game. THX OBAMA!

**Comment by raoulvdberge** [comment]
I'm closing this issue now, *and I'll silently judge you now too*.
