### ISSUE TITLE
Autocrafting causes server to slow down then stop.

### ISSUE THREAD

**Issue by ProsperCraft** [raoulvdberge/refinedstorage#735]
#### Issue description:
Server goes to 1 tps then watchdog kicks in and reboots it.
#### What happens:
Server starts to crawl then watchdog kicks in and crashes the server.

at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:230)

#### Steps to reproduce:
1. Run a large server with a lot of people playing on it.
2.
3.
...

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge:  12.18.2.2171
- Refined Storage:refinedstorage{1.2.8} [Refined Storage] (refinedstorage-1.2.8.jar) 

Does this issue occur on a server? Yes

#### If a (crash)log is relevant for this issue, link it here:
https://gist.github.com/ProsperCraft/8d9ff185aa207fc11ae55e2e1b66938f

**Comment by ProsperCraft** [comment]
https://gist.github.com/ProsperCraft/11d8e6875ba9d56e27338d8dfc4226f2
Happened again same version.

**Comment by InusualZ** [comment]
Can you run some profiling? See #523 (comment)

**Comment by raoulvdberge** [comment]
Try this please:

https://refinedstorage.raoulvdberge.com/wiki/profiling

**Comment by way2muchnoise** [comment]
Likely related to #678

**Comment by raoulvdberge** [comment]
Fixed
