### ISSUE TITLE
Exploding controller

### ISSUE THREAD

**Issue by jezzen** [raoulvdberge/refinedstorage#736]
#### Issue description:
The controller of my network exploded when I tried using an advanced power cube from Calculator as a power buffer (It has 64KRF in/out, which may or may not be related to the problem)

#### What happens:
I set up the power cube to output, placed down the controller and it causes a small explosion destroying the controller, and breaking the adjacent cable, and a piece of polished stone (ExtraUtils2) located a block out and below from the controller.

I tested it several times, you never get the controller back, and the broken blocks have a small chance of being lost. In one case, the cable was lost and I placed the controller anyways, it didn't explode. After a little more testing, it seemed like having a consumer in the network is the trigger.

#### What you expected to happen:
There is nothing in the documentation talking about the controllers exploding except for having multiple on the network, so I would expect it to act normally.

#### Steps to reproduce:
1. Place a Calculator advanced energy cube, changing a side to output
2. Place a controller block on the output
3. Place a Refined Storage energy consumer

#### Version (Make sure you are on the latest version before reporting):
Refined storage 1.2.9, though i didn't see this mentioned in the changelogs

In the modpack, All The Mods v1.50

Does this issue occur on a server? [yes/no]
Not tested

**Comment by raoulvdberge** [comment]
Controller don't explode anymore, they just drop on the ground when multiple are connected. So I don't know what causes these explosions...

**Comment by jezzen** [comment]
I've already said, it's not that I have 2 controllers. It's exploding when I supply it with power from Calculator's advanced power cube

**Comment by raoulvdberge** [comment]
That isn't possible from a RS standpoint, there is zero code that causes explosions...

**Comment by jezzen** [comment]
Well, I'm not sure then. The explosion is certainly centered on the controller, and will explode immediately in a power cube, controller, consumer arrangement. After a quick look, there is also no mention of exploding in the Calculator wiki [https://github.com/SonarSonic/Calculator/wiki/Advanced-Power-Cube](url)

**Comment by raoulvdberge** [comment]
I'm closing this as it's simply not possible, try contact the calculator mod author.
