### ISSUE TITLE
Crafting upgrade in a Constructor does not work

### ISSUE THREAD

**Issue by Darkere** [raoulvdberge/refinedstorage#740]
#### Issue description: 
Crafting upgrade inside a constructor does not create a task visible on the crafting monitor. Crafting upgrade inside an exporter works fine.

- Minecraft: 1.11
- Forge:2188
- Refined Storage:1.3.4

Does this issue occur on a server? yes

**Comment by InusualZ** [comment]
I can't reproduce this bug

**Comment by raoulvdberge** [comment]
No, this bug is only happening in "item dropping" mode as it's missing the crafting schedule call there. Easy fix.

**Comment by raoulvdberge** [comment]
Fixed
