### ISSUE TITLE
Lock solderer to only hold one item of each (parallel automation)

### ISSUE THREAD

**Issue by TheVanoq** [raoulvdberge/refinedstorage#745]
I would love to have the option to only hold one of each item in a solder (toggleable).

The reason why I would love this feature is, I am currently automating the solderer to work in parallel. To do that, I split the items with item conduits. The problem that occurs is this:

Let's say, I want to make 10 processors and have 3 solderers in parallel. The extracting item conduit splits the items and roundrobbins them into the solderers. Now, 10/3 has a remainer of 1. This means that the items will not be split the right way in each solderer (4/3/3 of each item in each solderer), but unevenly.

The automation: https://i.imgur.com/ttmDxuA.png
The result: http://imgur.com/a/NaTS4 (something alike, the items are split unevenly)

The ability to toggle a "single item mode" for the solderer COULD fix this issue.

Any other input/ideas are greatly appreciated!

**Comment by raoulvdberge** [comment]
Won't be needed if we do #704
