### ISSUE TITLE
Add the ability to autocraft things that already are in the system

### ISSUE THREAD

**Issue by TheVanoq** [raoulvdberge/refinedstorage#746]
Let's say I already have a couple of "Item X" in the system. But I want the system to craft even more for me without having to remove all of "Item X" from the system before starting the crafting task. 

Maybe SHIFT+Click for "Craft this item" in the grid?

**Comment by raoulvdberge** [comment]
![x](https://raoulvdberge.com/HYYQhF)

https://refinedstorage.raoulvdberge.com/wiki/grid
