### ISSUE TITLE
Disk Drive GUI Not Updating

### ISSUE THREAD

**Issue by InsomniaKitten** [raoulvdberge/refinedstorage#747]
#### Issue description:
The GUI tooltips/icons do not update when left-clicking on buttons.
Will only update if the user closes and re-opens the GUI.

#### Steps to reproduce:
1. Open up a disk drive GUI
2. Select the buttons and see them not respond
3. Re-open the GUI to cause them to update

#### Versions:

- Minecraft: 1.11
- Forge: [13.19.1.2188](http://files.minecraftforge.net/maven/net/minecraftforge/forge/1.11-13.19.1.2188/forge-1.11-13.19.1.2188-changelog.txt)
- Refined Storage: [1.3.4](https://minecraft.curseforge.com/projects/refined-storage/files/2354411)

#### Does this issue occur on a server?
Yes

**Video example:** [streamable/gvhc](https://streamable.com/gvhc)

**Comment by raoulvdberge** [comment]
This issue is a side effect of #370, closing
