### ISSUE TITLE
Autocrafting with IC2 Forge Hammer doesn't use up durability properly

### ISSUE THREAD

**Issue by jdratlif** [raoulvdberge/refinedstorage#748]
#### Issue description:

Autocrafting with the IC2 forge hammer is keeping more of the hammer's durability than it should.

#### What happens:

If you make a pattern, say for Iron Plates, using the IC2 forge hammer and an iron ingot, it should consume one "use" of the hammer for every plate made. However, every autocrafting operating (one thing you told it to build, no matter how many plates are made, only one "use" of the hammer is counted.

#### What you expected to happen:

The hammer should lose durability with respect to the number of items made.

#### Steps to reproduce:
1. Make pattern with forge hammer (Iron Plate = Forge Hammer + Iron Ingot shapeless)
2. Request two or more iron plates.
3. Profit!
...

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge: 2185
- Refined Storage: 1.2.11

Does this issue occur on a server? [yes/no]

YES
#### If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here]

**Comment by raoulvdberge** [comment]
Did you set it to an oredict pattern?

**Comment by jdratlif** [comment]
I'm pretty sure I did not have oredict checked.

**Comment by raoulvdberge** [comment]
Check oredict
