### ISSUE TITLE
Soldering station lost ability to pipe in/out in 0.6.11

### ISSUE THREAD

**Issue by DoomSquirter** [raoulvdberge/refinedstorage#75]
refinedstorage-0.6.11
Forge 1907

Using 0.6.10 and previous, I was able to pipe into the top and out of the bottom of the soldering station, but cables do not connect now in 0.6.11.  Piping 'in' didn't help a whole lot really but piping out did.

**Comment by raoulvdberge** [comment]
Which pipes are you using? Neotech pipes don't support IItemHandler in a good way yet, so this isn't the fault of the mod. You can check this by using hoppers. If it works with hoppers, it should work with other pipes too, if not, those pipes are broken.

**Comment by DoomSquirter** [comment]
using inductive automation pipes which worked prior to upgrade.  Reason I know is that I had it already setup and when we restarted server with update, the pipes weren't connected anymore.  

We had updated both mods so who knows, possibly something screwed up on their end or yours.  Will try hoppers next time I'm on server.

**Comment by raoulvdberge** [comment]
Ah, since 0.6.10 I am using Forge's capability system for inventories. Inductive Automation still depends on IInventory. So, the issue is at Inductive Automation.

**Comment by raoulvdberge** [comment]
I report this on their issue tracker.

**Comment by DoomSquirter** [comment]
Thanks for doing that.  I appreciate it.  :)
