### ISSUE TITLE
RF Tools Storage Scanner support

### ISSUE THREAD

**Issue by pagameba** [raoulvdberge/refinedstorage#750]
Not sure if this is possible but it would be really nice if the rftools storage scanner could see items inside an RS system, perhaps via an interface?

**Comment by raoulvdberge** [comment]
Unfortunately, this is not possible RS side. RFTools can add integration for RS though.

**Comment by pagameba** [comment]
I've looked through the RFTools code and the storage scanner will pick up any TileEntity that implements IInventory or the ItemHandler capability (CapabilityItemHandler.ITEM_HANDLER_CAPABILITY).  A quick search through the RS code base doesn't seem to reveal anything that implements either of these (is this right?)  I think it then uses these interfaces to list, extract and insert item stacks.  My interpretation of this is that the integration might most easily be obtained by adding the ITEM_HANDLER_CAPABILITY or implementing IInventory in an existing TileEntity in RS or to create a new TileEntity for this purpose?  I assume that this is similar to what would need to be done to integrate with AE.

Would you accept a PR along these lines if I was able to get something working?

**Comment by InusualZ** [comment]
Uhmm, RS doesn't expose all of his item through a IItemHandler. What @raoulvdberge meant by adding RFTools adding integration for RS is that RFTools could add a block that act as a INetworkNode and get the list of item, since know it's part of the network

**Comment by pagameba** [comment]
Ok.  I can try that approach also.  I was thinking too about how in AE you can connect a storage bus to an interface to create storage subnetworks and that the AE inventory might act as an IInventory at least for this purpose and that adding IInventory capability to the RS interface might provide a way of interconnecting with AE as well (at least from a storage point of view).

**Comment by raoulvdberge** [comment]
I think transforming the RS inventory to an IItemHandler is generally a bad idea. Does AE do the same thing?

**Comment by pagameba** [comment]
I just tried in creative, interfaces behave similarly with respect to RF Tools storage scanner.  They are seen as inventories, but you can see items set for export in the AE interface where you can't see them in the RS one.  You can, however, see a stack of items placed in the import section (and watch it disappear).

I'm starting to think this isn't as good an idea as I thought it might be :)

**Comment by raoulvdberge** [comment]
In which RS version did you try this? Normally, you should see the export slots as well.

**Comment by pagameba** [comment]
I was running the DW20 1.10 pack, looks like its 1.2.8

**Comment by raoulvdberge** [comment]
In the latest version you can see the export slots too.

**Comment by Azutte** [comment]
Did this end up going anywhere? I see "wontfix" on this issue but has it become, like, accidentally possible in the meantime? I've tried an external storage thing on a storage scanner but that doesn't seem to be the way to go, was hoping I was just doing it wrong but this old issue has me thinking I should give up on the matter.

**Comment by raoulvdberge** [comment]
It was possible for a while but my suspicion was correct, it wasn't performant. So, it was removed again.
