### ISSUE TITLE
API Request

### ISSUE THREAD

**Issue by skywalker3271** [raoulvdberge/refinedstorage#753]
Hello. I was attempting a build in Minecraft that involved Refined Storage and RFTools. It involved having the Storage scanner read the inventories of the storage disks. I thought it possible since AE and AE2 had an an API that allowed logistics pipes to read theirs. I asked McJty if it was possible and he stated that he was not certain there was an API for that. My question is does such an API exist and if not, will one exist in the future? Loving the mod. Thank you for your time.

**Comment by InusualZ** [comment]
The mod have a API. You have to know what you are looking for :)
But yeah, the API expose a way to get every item in the system. You have to implement the NetworkNode capability to your block.

**Comment by raoulvdberge** [comment]
And then implement IStorageProvider on your block. That should be a capability, by the way. Let me work on that.

**Comment by skywalker3271** [comment]
Thank you both :)
