### ISSUE TITLE
Refined Storage autocrafting causing Server lagg

### ISSUE THREAD

**Issue by Whazaaaaa** [raoulvdberge/refinedstorage#757]
#### Issue description:
When autocrafting with items that are waiting to be created the server starts to lagg because of this autocraft process that isnt happening. The more tasks the more lagg

#### What happens:
The server starts to lagg

#### What you expected to happen:
Server not to lagg because of this

#### Steps to reproduce:
1. Create Refined Storage System with autocrafting
2. Start autocrafting an item that needs more tiems than the system has
3. Start the lagg
For example craft 20K glass when you only have 5K sand
...

#### Version (Make sure you are on the latest version before reporting):
Correct me if im wrong but it doesnt seem like this has been looked at in the last few versions so I still think it has a use to make an issue

[NPS file+Screenshot Sponge timings.zip](https://github.com/raoulvdberge/refinedstorage/files/655936/NPS.file.Screenshot.Sponge.timings.zip)

- Minecraft: 1.10.2
- FTBserver-1.10.2-12.18.2.2171-universal
- refinedstorage-1.2.8

Does this issue occur on a server? [yes/no]
yes

I have included a nps file of when this was happening
And a screenshot of what SpongeForge shows in its timings report.

**Comment by raoulvdberge** [comment]
This might be fixed for the next 1.10 version, isn't it @way2muchnoise?

**Comment by kragnoth** [comment]
I can confirm that it is working now.  However, it seems to randomly drop tasks.  I'll start crafting a tier VI solar panel from flux reborn, and after walking away for 30 seconds it will drop the task that turns gravel into sand in the ender IO sag mills.  It will still have all the other 'crafting' tasks, but none of the style tasks that feed into secondary machines.  Lag is 100% better though.  I was pulling 9tps with it before the patch, patched and reran task, and it was back to 20tps

**Comment by Whazaaaaa** [comment]
Good to know (waiting for Hermitpack/Direwolf20 to update)

**Comment by raoulvdberge** [comment]
@kragnoth Please make a seperate issue for this

**Comment by kragnoth** [comment]
can't confirm issue persists after restarting my server, so disregard for now until I get a reproduction and log
