### ISSUE TITLE
can't autocraft higher tiers of simply jetpacks items

### ISSUE THREAD

**Issue by jdratlif** [raoulvdberge/refinedstorage#758]
When trying to craft tier 2 (or higher) jetpacks from 'Simply Jetpacks' mod, the system doesn't think it is capable of making the lower tier jetpack required in the crafting recipe. I've tried with and without ore dictionary in the pattern.

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge: 2185
- Refined Storage: 1.2.11

Does this issue occur on a server? [yes/no]

Yes

**Comment by raoulvdberge** [comment]
Do you have the lower tier jetpacks as a pattern as well?

**Comment by way2muchnoise** [comment]
Might be related to bc7ead20debbb89002bfb54f54c59c4f5e71a6c3 and needs something to be ignored

**Comment by jdratlif** [comment]
Raoul: yes, I have the patterns for all tiers and all sub items.

Way2muchnoise: This is what I think as well. There's some NBT data that doesn't work. You can't shift-click with + button from JEI in RS crafting grid either. I will try and test that patch from the 1.10 branch in git and let you know what happens.

**Comment by raoulvdberge** [comment]
That patch will do nothing as long as we didn't add any ignore rules for simply jetpacks...

**Comment by way2muchnoise** [comment]
@jdratlif if you would be so kind to find out what tag it is? :D I do plan to make the pruning some config so you can at least fix your own (or config like as it should be appended to our defaults)

**Comment by jdratlif** [comment]
@way2muchnoise not sure how to see what NBT tags are on an item. suggestions on doing that?

**Comment by way2muchnoise** [comment]
iirc actually additions has a config to show them on holding controll, other mods might do as well

**Comment by jdratlif** [comment]
If you look at the crafting recipe in JEI, the item it "wants" only has a single NBT tag, which looks like maybe it is the default properties for the item (how many energy can be stored, particles, etc). This is the sjData tag, which is a dictionary. The tags in this dictionary seem duplicated in the actual item, which is probably the actual current properties of the item (actual energy stored, etc).

Although I'm not sure if you can see all the tags on the actual item since it runs off the end, it looks like they just duplicate the tags individually outside the sjData structure.

PackOn
JetpackHoverModeOn
JackpackEHoverOn
JetpackParticleType (not sure this on is duplicated -- afaik you can't change particle types outside crafting a new item, so this wouldn't need to be a changeable property)
Energy

I've attached screenshots of the actually additions stuff I saw.

http://games.technoplaza.net/temp/jei-recipe.png
http://games.technoplaza.net/temp/item-nbt.png

**Comment by jdratlif** [comment]
This does work in the latest github (2016-Dec-23 17:00 UTC-5). Thanks.

**Comment by SCLeoX** [comment]
Broken again in FTB beyond.

**Comment by raoulvdberge** [comment]
1.10.2 is unsupported so don't bump old threads.
