### ISSUE TITLE
Autocrafting IC2 10K Cooling Cell crash

### ISSUE THREAD

**Issue by Svenskunganka** [raoulvdberge/refinedstorage#761]
#### Issue description:
Autocrafting IC2 10K Cooling Cell results in a crash.

#### What happens:
Placing the crafting recipe for IC2 10K Cooling Cell in the Crafter and turning on "autocrafting" when a redstone signal is present, then continuing to provide the Crafter with a redstone signal results in a crash. Trying to load into the game again results in the same crash  & error.

#### What you expected to happen:
The item being crafted.

#### Steps to reproduce:
(HermitPack latest with latest version of Refined Storage for MC 1.10.2)
1. Place [IC2 Tin Plates](http://wiki.industrial-craft.net/index.php?title=Tin#Tin_Plate) & [IC2 Universal Fluid Cells](http://wiki.industrial-craft.net/index.php?title=Universal_Fluid_Cell) filled with Coolant (the ones seen [here](http://wiki.industrial-craft.net/index.php?title=Coolant_(Fluid))) into Refined Storage.
2. Create a crafting recipe pattern (with or without OreDict) for the [IC2 10K Cooling Cell](http://wiki.industrial-craft.net/index.php?title=Coolant_Cell) and place it in a Crafter.
3. Turn on autocrafting with redstone signal in the Crafter (important step!)
4. Proceed to give the Crafter a redstone signal and a crash should occur.

(Don't forget to inspect the crafting pattern and you should see that it says it requires `-24 Universal Fluid Cell` to craft)

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge: 12.8.3.2185
- Refined Storage: 1.2.11

Does this issue occur on a server?

**Comment by PWTordenskiold** [comment]
Autocrafting it from grid does not work either, but no crash. Start-button gets grayed out when you click it, but nothing happens from there even if all resources are in the system.

**Comment by PWTordenskiold** [comment]
As a temporary fix, make the pattern manually by inserting the universal coolant cell with IC2 coolant in it. Not sure if its JEI or Refined Storage messing it up.

This also affects normal autocrafting, but it does not crash the game if you let JEI make the recipe. If you hit start it gets grayed out and just sits there with nothing happening.

**Comment by Svenskunganka** [comment]
@PWTordenskiold Good catch, that worked like a charm! My guess is that it's JEI that is messing it up, but it would be good to look into if there's a way to sidestep the crash on Refined Storage's side.

**Comment by way2muchnoise** [comment]
Seems to be some bad JEI transfer there is some safeguard in place now.
