### ISSUE TITLE
#BlameRaoul Konami Code Fail MEEMEES ARE BROKEN!

### ISSUE THREAD

**Issue by Darkosto** [raoulvdberge/refinedstorage#763]
#### Issue description:
I was showin everyone the cool memaws with Refined Storage and used the Konaaami code and mah game crashed!

#### What happens:
The game crashed! http://pastebin.com/0yjK5x8t

#### What you expected to happen:
Sweet, dank meemaws in mah game. And I would probably enjoy it if the game didn't crash, too.

#### Steps to reproduce:
1. Open up Refined Storage Crafting Grid
2. Use Konaaaami code
3. ???
4. Modpack Crashes
5. Profit
...

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge: 2185
- Refined Storage: i.d.k. whatever the latest on curse be

Does this issue occur on a server? [yes/no]
uhhh, maybe? I'm too lazy to spin up a server.

#### If a (crash)log is relevant for this issue, link it here:
http://pastebin.com/0yjK5x8t

https://clips.twitch.tv/darkosto/BrainyLeopardHotPokket

**Comment by starg09** [comment]
#FuckKonami at its finest.

**Comment by raoulvdberge** [comment]
hahahahahahahaha

**Comment by raoulvdberge** [comment]
Whoops, the easter egg code didn't care about resizeable grids yet...

**Comment by Myknakryu** [comment]
Actually it also crashes 1.11

**Comment by way2muchnoise** [comment]
Good thing @raoulvdberge only fixed it in the 1.11 branch :+1:

**Comment by raoulvdberge** [comment]
I'll also backport this for 1.10
