### ISSUE TITLE
[1.11]Some server bugs

### ISSUE THREAD

**Issue by Myknakryu** [raoulvdberge/refinedstorage#764]
#### Issue description:
Autocrafting with crafters does not work. Also after disconnecting from server and connecting Crafting Grid loses connection but other grids does not except pattern grid.
#### What happens:
Requesting item to craft does not work. You can request but request doesn't get made.
#### What you expected to happen:
To make some items that are requested.
#### Steps to reproduce:
1. Make crafter
2. Make some patterns
3. Put them in crafter
4. Try using autocraft feature in grid
#### Version (Make sure you are on the latest version before reporting):
- Minecraft: 1.11
- Forge: 2189
- Refined Storage: 1.3.5

Does this issue occur on a server?
yes and only on server as i tested.

Video:
https://youtu.be/y3DqwZzBVnA

**Comment by Myknakryu** [comment]
All of the sudden it works... But sometimes it does not....

**Comment by way2muchnoise** [comment]
Likely related to #370

**Comment by Myknakryu** [comment]
Well the solution works, but starts to be irritating when you reconect to server every hour or so. Another thing is that picking up and placing that crafter when autocrafting does not work, doesn't help.
