### ISSUE TITLE
[1.10.2] Autocrafting halt on manually inserting items

### ISSUE THREAD

**Issue by PWTordenskiold** [raoulvdberge/refinedstorage#765]
#### Issue description:
When you autocraft something that you have in your inventory and insert those items into the system, autocrafting stops/finishes.
#### What happens:
Autocrafting finishes with items remaining in crafting job.
#### What you expected to happen:
Autocrafting ignoring insertion of items into the system.
#### Steps to reproduce:
1. Set up a recipe for coal blocks, craft a few and put in your inventory.
2. Start autocrafting a large order of it, then insert your coal blocks into the system.
3. Autocrafting stops no matter the amount remaining.
...

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge: 12.18.3.2185
- Refined Storage: 1.2.12

Does this issue occur on a server? [yes/no]
No.

**Comment by way2muchnoise** [comment]
This is an issue with the tracking, when you manually insert stuff into the grid that also gets taken into account for the running crafting task.

**Comment by PWTordenskiold** [comment]
Yes that is noticed(wish it wasn't), but it doesn't matter if I say order 5,000 coal blocks and then insert 10, it stops the crafting.

**Comment by way2muchnoise** [comment]
I should just subtract 10 from the current order. I'll see what there can be done about.

**Comment by raoulvdberge** [comment]
fixed in dev

**Comment by way2muchnoise** [comment]
fixed in f3bb7fc117117fca5027efcf874597cc5076ddc5 and related to #766
