### ISSUE TITLE
[1.10.2] Autocrafter failing larger jobs

### ISSUE THREAD

**Issue by PWTordenskiold** [raoulvdberge/refinedstorage#766]
#### Issue description:
Hard to pinpoint exact cause, but happens most often on large(amount of resources needed) jobs.
#### What happens:
Lets say you want to make Quantum Solar Panel, 4 of them. What "always" happens in this case is it trodding along(ignoring lagspike from large jobs here), and ends up crafting 3 out of the 4 with the fourth failing to ever craft if you just leave the crafting job be("Waiting for items"). If you cancel and then order a new Solar Panel, it needs to craft some items that are not listed in the crafting window prior(when stuck waiting) but finishes OK. 
Also see this issue with fast machinery on large jobs, I suspect Refined Storage is not accurately recognizing items entering if it goes "too fast", as the machine will finish(lets say a Metal Former from IC2 with 14 overclocker upgrades) and items enter the system in the right amount(verified by looking at amount in grid before and after) but the crafter does not recognize this amount.
(Set it up with for instance Item Conduit with full speed upgrade into a chest with 3-4 import busses)
#### What you expected to happen:
Autocrafter finishing the amount, or looping back and rechecking dependencies after a certain time.
#### Steps to reproduce:
1. Set up a large multi-craft operation, recommend Advanced Solar Panels and Ultimate or Quantum panels as those give it consistently for me.
2. Start the crafting job(lets say 4 Quantum)
3. Wait a minute or two and you should see a remaining that will not finish.
...

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge: 12.18.3.2185
- Refined Storage: 1.2.12

Does this issue occur on a server? [yes/no]
No.

**Comment by way2muchnoise** [comment]
I should recalculate when stuck and just craft the needed items. Are you 100% you didn't mess up any patterns? (eg. 2 x make 1 y while it actually needs 3 x)

**Comment by PWTordenskiold** [comment]
The entire process is automated, and works fine if I order one and sometimes two panels instead. The system has crafted 24 panels successfully at this point.  
There is a loop present with steel(ingot->dust->ingot) but I bypass it by manually ordering that up so the crafter doesn't panic from it.

**Comment by way2muchnoise** [comment]
Loops might choke out the process when it recalculates and you didn't order them manually.

**Comment by PWTordenskiold** [comment]
I am aware which is why I mention it and that I manually make sure the amount of steel is sufficient. I'll try remove the loop as a quick test now and see if it still halts.

**Comment by PWTordenskiold** [comment]
Ok I believe this is a problem touching on two different bugs:
One might be related to having multiple steps in a complex recipe in the same crafter. For instance Irridium-Iron Plate -> Reinforced Iridium Iron Plate -> Irradiant Reinforced Plate -> Advanced Solar Panel. I had all those in the same crafter along with Irradiant Glass Pane(Another step in Advanced Solar Panel) and it would "always" stop on those. Now that I have spread it out over multiple crafters I do not see a crafting operation getting stuck on crafting-grid items any longer.

The other relates to multiple machines outputting material fast. I have tested many times now inputting a certain amount and seeing that amount output to chest. But when auto-crafting big orders like 1024 Advanced alloy(requires Mixed Metal Ingot in a compressor, which itself requires 1526 Tin Plate, Iron Plate and Bronze Plate which itself requires tin and copper dust of equal amount), something vanishes along the way. Mind you the processing patterns are correctly setup as I've probably sixtuple checked at this point and removed all oredict for everything IC2-related just to make sure. In the case of Advanced Alloy everything is 1-1 except for Mixed Metal Ingot which is a crafting-grid operation 3-2, yet on a large order I most of the time end up with a remnant of single- to double-digit deficiency of Advanced Alloy. That deficiency is not there on smaller orders.

**Comment by jdratlif** [comment]
I'm seeing similar things, but it seems to happen for me only when the system is importing simultaneously.

Example: I have a recipe for making bread. Ender IO Sag Mill wheat into flour, and cook flour in a Mystical Agriculture Supreme Furnace. Ender IO item conduit goes to an Ender Storage Ender Chest which is Ender IO item conduit'ed into three Iron Chests gold chests attached to importers. If I request a stack of bread, I usually end up with only about 17 of them. Disable the import of items however, and it crafts the entire stack.

This is also happening when requesting dark glass in an Ender IO Alloy Smelter. It just stops the recipe after 15 or so of a stack.

Downgrading to 1.2.11 has resolved this issue for me for the time being.

**Comment by jk1895** [comment]
Same here! I order 64 Graphite Bars (Extreme Reactors) and get only 7! Other try 5. Then 3... 5...
Or I order 64 dust (SAG mill) and get only a few... this is really annoying :-(

**Comment by way2muchnoise** [comment]
Could any of you try out the dev build from the [bintray repo](https://bintray.com/raoulvdberge/dev/refinedstorage/1.2.13-742#files/refinedstorage/refinedstorage/1.2.13-742)? And see if it fixes it?

**Comment by raoulvdberge** [comment]
@way2muchnoise They can't, the builds on the bintray repo aren't obfuscated...

**Comment by Haddadmj** [comment]
is there a new build in the way to fix this ??/
