### ISSUE TITLE
Moving storage block or drive forgets its config

### ISSUE THREAD

**Issue by Zaflis** [raoulvdberge/refinedstorage#769]
#### Issue description:
What i'm trying to do is place 16k storage block down and configure it to whitelist cobblestone and void excess, and set it higher priority. Then break it and attach to my main item network. 

#### What happens:
When i break and put the storage block back down, none of the changes i made were stored. I also tested the same thing with Disk drive and it forgets configs too.

Items that were put in storage block do remain inside though.

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge: 12.18.2.2171
- Refined Storage: 1.2.8
I went through all changelogs after this version but none were related to issue. This version is used in the latest DW20's modpack.

Does this issue occur on a server? [yes/no]
yes

**Comment by raoulvdberge** [comment]
This is not a bug. RS blocks in general don't remember their config, use a wrench for that.

**Comment by Zaflis** [comment]
Then it seems like compatibility problem with EnderIO's yeta wrench, i didn't know you can do that.

**Comment by raoulvdberge** [comment]
No, I meant the Refined Storage wrench.

**Comment by Zaflis** [comment]
You do yes, but i dislike using 10 different wrenches :p It's propably a feature request on their end to make yeta able to pick those blocks too.

**Comment by KlutzLament** [comment]
@Zaflis Have you heard of Morph-O-Tool?

**Comment by Zaflis** [comment]
No? I did try the wrench from this mod too, but it could only save the config. That's useless to me also, when i expected a shift-right click to break the block, like AE2 and all the other mods lets us. If you place a storage block connected to system, within 1 tick some unrelated item could already slip inside it before you get a chance to set the configs.

**Comment by way2muchnoise** [comment]
Morph-O-Tool just mimics other tools so it won't help in @Zaflis case. I mean you could just not connect the storage yet before setting up some black/whitlelist.

**Comment by Zaflis** [comment]
You can of course, but if same storage will connect to say cobblestone storage that is voiding it, you'd get alot of stone in the other drives then. It's just messy when you need to stop all quarries then too. How difficult is it to store configs in the broken block?
