### ISSUE TITLE
Crafter Does not Give Byproducts Back

### ISSUE THREAD

**Issue by homemmakako** [raoulvdberge/refinedstorage#77]
While using the automated crafting system from the mod I noticed that you don't receive byproducts from recipes back, such as empty buckets or tools used for crafting from other mods.

**Comment by raoulvdberge** [comment]
Fixed for the next version. When you update you'll have to recreate the pattern though.

**Comment by homemmakako** [comment]
thats ok, thanks for the quick fix.
