### ISSUE TITLE
[Feature Request] Allow More filter options on Exporter and Importer

### ISSUE THREAD

**Issue by AGWeeB** [raoulvdberge/refinedstorage#770]
It seems there are only 9 slots that allow you to white list what you want to be spit out using an exporter.  I generally use these slots to white list Ores to be spit out for automatic processing, but there are more than 9 ores I would like the exporter to export. It would be great it there was a way to allow more to be added to the white list. Same for the importer as well.

**Comment by raoulvdberge** [comment]
Nah, just add more exporters
