### ISSUE TITLE
[1.10.2 - Minor] Performance issue caused by renderupdates from disk-drives(?)

### ISSUE THREAD

**Issue by Rudolpher** [raoulvdberge/refinedstorage#771]
#### Issue description:
In a larger system with lots of disks and drives, larger crafting operations cause a lot of render updates because of the lights flickering between full and near-full.
Mind you I do not know the exact impact it has on performance, I've just been taught that if csampler shows something continuously red![continuously red](https://cloud.githubusercontent.com/assets/24588620/21337635/5935f346-c66f-11e6-85bc-706fa8a3c773.png) it is usually bad. The operation pictured is with no machines running nearby(loaded chunk outside render distance), and quarries turned off so the system has nearly no extra I/O. 
#### What happens:
Light show.
#### What you expected to happen:
Less of a light show.
Maybe a more conservative cap be set on how often it updates?

Maybe auto-defragmenting drives as well, but suspect that is more complicated than it sounds.
Is this one of the reasons AE2 decided to go the route of forcing a max amount of types per drives?

#### Steps to reproduce:
1. Large system with many drives and resources
2. Order something that is 1-1 conversion
3. Watch the light show and fancy colors with csampler
...

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge: 12.18.3.2185
- Refined Storage: 1.2.12

Does this issue occur on a server? [yes/no]
No

As an addendum: Considering the render-updates signifies way more going on behind the scenes and that I do not know anything about it, I thought it'd be safer to report in hopes it might be a piece of the puzzle in regards to performance issues on larger crafting jobs.

**Comment by InusualZ** [comment]
Yeah, Disk Drive and Drive Manipulator can cause FPS drop since their are rendering their drive. For now, hide your drive until Raoul fine a better way to address this issue.

**Comment by raoulvdberge** [comment]
Those need to be TESRs, ideally.

**Comment by malakai97** [comment]
Note this isn't limited to just disk drives if your incoming power is slightly less than what your RS system uses.  My whole system is flickering.

**Comment by raoulvdberge** [comment]
This is no longer an issue in MC 1.12. Turn on Forge threaded chunkrendering.
