### ISSUE TITLE
autocraft hangs on actually additions greenhouse glass

### ISSUE THREAD

**Issue by jdratlif** [raoulvdberge/refinedstorage#772]
#### Issue description:

When trying to autocraft actually additions greenhouse glass, even when the system has all the ingredients, it will hang on actually crafting the glass, which is a simple crafting table recipe.

This occurs when you select ore dictionary on the recipe and use vanilla oak tree saplings. I only have forestry apple oak saplings, which are ore dictionary'd as 'treeSapling'. If I deselect ore dictionary and specify the forestry sapling in the recipe, the crafting works.

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge: 2185
- Refined Storage: 1.2.11

Does this issue occur on a server? [yes/no]

Yes

#### If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here]

**Comment by PWTordenskiold** [comment]
Which saplings exactly? Tested with Apple Oak, Dark Oak and Lemon saplings and they work when pattern is set to ore dictionary vanilla oak sapling.  

Try update RS to [1.2.12](https://minecraft.curseforge.com/projects/refined-storage/files) and replicate it?

**Comment by jdratlif** [comment]
Did you have other saplings in your RS system? It worked for me using IC2 rubber tree saplings when I had vanilla oak saplings in the pattern, but just hung when it ran out of everything other than forestry apple oak saplings.

As for 1.2.12, I'll try to test with that later, but it breaks autocrafting, so I'm waiting on a build that fixes that.

**Comment by PWTordenskiold** [comment]
No, I removed all other saplings.

**Comment by way2muchnoise** [comment]
I can't reproduce this, might be fixed in dev since I have done some other fixes in the meanwhile.

**Comment by way2muchnoise** [comment]
[Relevant commits](https://github.com/raoulvdberge/refinedstorage/compare/f3bb7fc11711...db9e0055b439)

**Comment by jdratlif** [comment]
Yes, this was fixed by one of those commits. I tried the git version before 1.2.14 came out.

Thanks.
