### ISSUE TITLE
Feature Request: Extracting Storage Parts and Upgrading to a higher storage part with data saved... just.. just read the description

### ISSUE THREAD

**Issue by Darkosto** [raoulvdberge/refinedstorage#774]
#### Feature description:
Consider the following:
I think it would ABSOLUTELY THE BOMB.NET if when you extract a storage part from a housing and use it to craft a high tier storage part and have the data transferable. Instead of needing to extract the items first and then craft with empty storage parts.

#### What WILL happen:
What would happen is, besides tons of cash and fame, you could combine the storage part (that has the data NBT attached) and use it to craft a higher tier storage part to save like THOUSANDS OF HOURS of time you would have normally wasted by transferring items out of the disk,

#### What you expect to happen:
I expect people to love you and want to use your mod in more projects because you think of the people first and how you can save them a boatload of time when making better disks.

#### Steps to reproduce:
1. Have the ambitions to make Refined Storage great, again!
2. Add in some code to let storage parts retain nbt data of their contents
3. Allow end-users to combine them for better disks
4. Save like buttloads of time when crafting
5. ???
6. Make better disks!
7. ???
8. Profit!

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge: 2185
- Refined Storage: Idk! I'm using the latest one! The one that's on curse!

Does this issue occur on a server? [yes/no]
It could occur on a server!

#### If a (crash)log is relevant for this issue, link it here:

I suspect this will not crash anything and will not cause ANY ISSUES WHAT-SO-EVER! I have the support of the United States Navy and the office of the Prime Minister of Australia behind me. PLEASE MAKE THIS MOD GREAT AGAIN! 

I love you!
Darkosto

**Comment by iChun** [comment]
+1

**Comment by Ludi87** [comment]
I support this feature request.

**Comment by Shinoow** [comment]
+rep
Good request.

**Comment by SephirothWS** [comment]
+1

**Comment by kojul** [comment]
+1

**Comment by gigabit101** [comment]
just remember to remove the nbt tags if @Darkosto uses the recipe ;)

**Comment by Tkdriverx** [comment]
11/10 will feature request again
+1

**Comment by scootz** [comment]
+1

**Comment by Turkey2349** [comment]
+=1

**Comment by raoulvdberge** [comment]
I'm concerned this will render the disk manipulators semi-useless

**Comment by raoulvdberge** [comment]
So here's the catch: I wont implement this. But you can! If you PR the code, I will merge it. Do you accept the challenge?

**Comment by Turkey2349** [comment]
wait, sooo does this mean darko has to pr it?

**Comment by raoulvdberge** [comment]
*disclaimer: **YOU** means *Mr. Dark, Osto**

**Comment by kojul** [comment]
Probably, but does he have to write it?

**Comment by Turkey2349** [comment]
because if not guarantee you gets one us his code monkeys todo it Kappa

**Comment by way2muchnoise** [comment]
If this isn't PRed by @Darkosto I'll code-nazi the PR

**Comment by tyra314** [comment]
![challenge-accepted](https://cloud.githubusercontent.com/assets/16997177/21408665/8a02d6fc-c7d6-11e6-8524-d96db5e618a7.png)

No it got a meme

**Comment by raoulvdberge** [comment]
**disclaimer 2: you cannot let Turkey change his name to Mr. Dark, Osto and let him still PR it anyway**

**Comment by way2muchnoise** [comment]
We'll need dev stream proof @Darkosto stream on https://www.twitch.tv/darkosto

**Comment by Turkey2349** [comment]
Forever love you raoul!

**Comment by raoulvdberge** [comment]
@Darkosto 

He broke your heart
He took your soul
You're hurt inside
Because there's a hole
You need some time
To be alone
Then you will find
What you always know
I'm the one who really loves you baby
I've been knocking at your door
As long as I'm living, I'll be waiting
As long as I'm breathing, I'll be there
Whenever you call me, I'll be waiting
Whenever you need me, I'll be there
I've seen you cry
Into the night
I feel your pain
Can I make it right
I realized there's no end inside
Yet still I'll wait
For you to see the light
I'm the one who really loves you baby
I can't take it anymore
As long as I'm living, I'll be waiting
As long as I'm breathing, I'll be there
Whenever you call me, I'll be waiting
Whenever you need me, I'll be there

**Comment by Joshwoo70** [comment]
-100
reason : description is too clickbaity.
