### ISSUE TITLE
Autocrafting .. craft with oredict

### ISSUE THREAD

**Issue by Haddadmj** [raoulvdberge/refinedstorage#776]
#### Issue description:

When i request to craft 64 sticky pistons .. I have the oredictionary for the pattren.

#### What happens:
it craft only one sticky pistion and continue with the crafting without giving the result
#### What you expected to happen:
i expect to have 64 sticky pistons in my RS System.. but what happend is i have only one.
#### Steps to reproduce:
1. make the pattren for it with oredict
2. request it from RS System
3. Wholla ... only one sticky piston is crafted
... 

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge:Latest
- Refined Storage:Latest

Does this issue occur on a server? [yes/no]

#### If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here]

**Comment by way2muchnoise** [comment]
related to #766 , which has been fixed in dev.
