### ISSUE TITLE
Crash when : modalloader block refinedstorage:constructor

### ISSUE THREAD

**Issue by DHand333** [raoulvdberge/refinedstorage#778]
Crash when loading

 Modpack doesent startup, crashes when it says ModalLoader blocks refinedstorage:constructor

What you expected to happen: Modpack Starting up

Steps to reproduce:
1.Install a modpack that contains the mod
2.Load Minecraft
3.Doesent load
...

Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge:
- Refined Storage:

Does this issue occur on a server? Dont think So
[crash-2016-12-23_01.45.12-client.txt](https://github.com/raoulvdberge/refinedstorage/files/670232/crash-2016-12-23_01.45.12-client.txt)

[fml-client-latest.txt](https://github.com/raoulvdberge/refinedstorage/files/670234/fml-client-latest.txt)

If a (crash)log is relevant for this issue, link it here:

Crash log : http://pastebin.com/n03QaPeD
FML lastest thingy : (It was too big so its only the last quarter of it) http://pastebin.com/pSG5Ffe9

**Comment by raoulvdberge** [comment]
`java.lang.OutOfMemoryError: GC overhead limit exceeded`

Your MC crashed because it ran out of memory. This is not an RS issue, assign more RAM to Minecraft.
