### ISSUE TITLE
Texture flicker

### ISSUE THREAD

**Issue by Louis-9902** [raoulvdberge/refinedstorage#78]
In the latest version of refinedstorage, there is a texture flickering when you have a whole stack of items in the Soderer. After it processed one of the stack the texure changes very fast to off and then to on [green -> red -> green]. This causes also chunk updates.

- **Version:** 0.6.14
- **Optifine installed**
- **Forge Mod Loader version:** 12.16.1.1907

**Comment by raoulvdberge** [comment]
I've noticed this too, will try to push a fix tomorrow for both 1.9 and 1.9.4.

**Comment by raoulvdberge** [comment]
Fixed in 0.6.15 / 0.7.5. Thanks for reporting
