### ISSUE TITLE
Network Receiver Stops Working upon Restart

### ISSUE THREAD

**Issue by darman84** [raoulvdberge/refinedstorage#780]
#### Issue description:
I play in single player, and whenever I restart the world/exit to main menu/close the game, when I return to the save, my network receiver, which is in a rftools dimension, stops working, and the network card must be relinked and replaced into the network transmitter in order for it to work again. (I do have a interdimensional upgrade with plenty of power)
#### What happens:
The refined storage system is offline in the rftools dimension
#### What you expected to happen:
The system should be online
#### Steps to reproduce:
1. Wirelessly link to rftools dimension using network transmitter and receiver and network card
2. Once it is working exit game or go to main menu
3. Once you reenter the world the bug appears
(probably only works in single player, same result might occur if server restarts on a multiplayer server
...

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge: 1.10.2 - 12.18.3.2185
- Refined Storage: 1.2.12

Does this issue occur on a server? [yes/no]
no

**Comment by raoulvdberge** [comment]
fixed in 1.11
