### ISSUE TITLE
Server crash with 1.2.13

### ISSUE THREAD

**Issue by xannor** [raoulvdberge/refinedstorage#781]
#### Issue description:
NoSuchMethodException on server startup

#### What happens:
At some point during the load up the server will crash-log with a NoSuchMethodException

#### What you expected to happen:
Things working as normal

#### Steps to reproduce:
1. Install 1.2.13

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge: 2185
- Refined Storage: 1.2.13

Does this issue occur on a server? [yes/no] Yes

#### If a (crash)log is relevant for this issue, link it here:
https://gist.github.com/xannor/564da8e11062d3ab5b13143d88b1a697

Edit: Also want to confirm that stepping back to 1.2.12 prevents the issue from occurring.

**Comment by raoulvdberge** [comment]
@way2muchnoise what are you doing, Item#getSubItems and Item#getCreativeTab is client side only.....

**Comment by way2muchnoise** [comment]
Whoops, lemme go change that
