### ISSUE TITLE
Destructors in Claimed Chunks

### ISSUE THREAD

**Issue by Pontiac76** [raoulvdberge/refinedstorage#782]
#### Issue description:
Destructors do not destroy blocks if a chunk is claimed via FTBs claiming system.  But Constructors DO place blocks

#### What happens:
NoOp while chunk is claimed.  Blocks break when unclaimed.  (Video URL provided below)

#### What you expected to happen:
Blocks placed in front of a destructor should be broken and pulled into system regardless of chunk ownership.

#### Steps to reproduce:
1. Construct minimal RS system with a small amount of storage, built entirely within a single chunk
2. In the FTB map, claim the chunk as your own.  No need to chunk load
3. Place down any block (Cobblestone, dirt, etc)
4. Point the destructor at the block placed
5. Connect the destructor to the RS system
*NOTHING HAPPENS*
6. Unclaim the chunk
*Block breaks almost immediately*

#### Version (Make sure you are on the latest version before reporting):
- Minecraft: 1.10.2
- Forge: 12.18.3.2185
- Refined Storage: 1.2.12

Does this issue occur on a server? Yes

#### If a (crash)log is relevant for this issue, link it here:
No crash log.

#### Video of bug in action
https://youtu.be/iDxP_S5FO3s

**Comment by Joshwoo70** [comment]
enable fake players. you need to do so.

**Comment by way2muchnoise** [comment]
@Pontiac76 Yeah, I don't know the command by hard but there is a way to allow fake players (like the destructor) to place/break blocks in your claimed chunks.

**Comment by Pontiac76** [comment]
That command seems to have worked.  Putting that on my wiki so I know what to do next time I rebuild of the world.

I would have figured that placing and breaking would have been an equal standing.  My boys couldn't do anything in any of my chunks until I became allies with them.  When I first ran into the issue with blocks not breaking, then seeing them being placed, I wasn't sure where to put the blame, be it on FTB or RS.

**Comment by raoulvdberge** [comment]
This is on the wiki, guys:

https://refinedstorage.raoulvdberge.com/wiki/constructor
https://refinedstorage.raoulvdberge.com/wiki/destructor

**Comment by Pontiac76** [comment]
Thanks, but as my video shows, constructor and destructor should have been denied placing blocks.  But the constructor placed without issue while the chunk was owned by me.  Hence the confusion.
