### ISSUE TITLE
[Requset] Supplier or Keep-n-stock system

### ISSUE THREAD

**Issue by r3pbl4** [raoulvdberge/refinedstorage#783]
A long time ago I pasted here report about issue with making keep-n-stock system, that crashing servers https://github.com/raoulvdberge/refinedstorage/issues/610. U fixed that by disabling entire feature, and said that u will make that in a future... So its time to remind to u...

So I like how its work in logistics pipes: http://rs485.network/wiki/Logistics_Supplier_Pipe

Make a SUPPLIER that will request: 
1) Specified amount of items from the system, blacklisting that inventory on which it connected.
2) If there is no items in system it will request for crafting if system have a recipe, without crafting upgrade.*
3) Supplier provide inventory to the RS system.

*I think the recipe can be like EXTERNAL STORAGE + CRAFTING UPGRADE + DIAMOND PROCESOR  in solderer.
It will explain the properties of this item -> 
a) It dont require crafting upgrade to request craftings because its already used in recipe
b) It will connect to the system inventory on which it connected like external storage
c) The diamond processor is improving external storage, allowing him specify amount of items that need to be supplied. Its should be easy to say keep big amount of items, using only one slot of filter.

Thats how DW(that one which the 20) solve problem with craftable items, using crafter from rftools: https://youtu.be/EV3880OjZBg?t=1004

But there is no solution with items that have processing recipe.

**Comment by raoulvdberge** [comment]
The exporter has a "regulator mode" now (in 1.11) which keeps a certain amount in stock in a inventory. You can hook up an ext storage to that inventory.

**Comment by TheJaymoe** [comment]
Can you add this to the 1.10 =D ?

**Comment by Tahakk** [comment]
As 1.10 is no longer supported or developed (hope I'm right) I'm guessing short answer: "no"
