### ISSUE TITLE
Crash on Launch

### ISSUE THREAD

**Issue by APixelVisuals** [raoulvdberge/refinedstorage#784]
#### Steps to reproduce:
1. **Install** Refined Storage + Forge
2. **Launch** Minecraft
3. **Crash**
...

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: **1.10.2**
- Forge: **12.18.3.2185**
- Refined Storage: **1.2.14**

Does this issue occur on a server? **No**

#### If a (crash)log is relevant for this issue, link it here: http://pastebin.com/amFgFgbm

**Comment by raoulvdberge** [comment]
you ran out of memory. not an rs issue

**Comment by APixelVisuals** [comment]
So do I give the game more RAM? Sorry im new to this :/

**Comment by raoulvdberge** [comment]
no, you contact the modpack authors

**Comment by APixelVisuals** [comment]
Alright I see, thanks :)
