### ISSUE TITLE
External Storage ignores access type with Storage drawers

### ISSUE THREAD

**Issue by StingrayNine** [raoulvdberge/refinedstorage#786]
#### Steps to reproduce:
1. Use drawer controller + drawer.
2. Attach external storage cable to drawer controller
3. set priority higher than 0 with extract only
4. ?????
5. Failure
...

**Comment by raoulvdberge** [comment]
exact rs version please

**Comment by raoulvdberge** [comment]
ah thanks for closing this issue without saying what version you are on first

**Comment by StingrayNine** [comment]
No need for snark. Was on 1.2.8 as was the stable DW20 pack. Updated to 1.2.14 and it no longer puts ingots into the extract only drawer system.

**Comment by raoulvdberge** [comment]
then say something before you close, as this obviously leads to snark.
