### ISSUE TITLE
autocrafting regression in 1.2.14 re: @Storage Drawers:Compating Drawer w/ oredict enabled

### ISSUE THREAD

**Issue by jdratlif** [raoulvdberge/refinedstorage#787]
#### Issue description:

I had a pattern for compacting drawers that worked fine in 1.2.11, but it stopped working in 1.2.14. When I try to craft it, it tells me I am missing a basic storage drawer, one of the recipe components. However, it knows how to make these. Additionally, even if it has one in the system, it will say it is missing it.

If I change the compacting drawer pattern to not use ore dictionary, it works, with that specific drawer, not any other kind of basic storage drawer.

Even if oredict was not working for substituting drawers, I feel it should definitely work when the exact type of drawer that was in the pattern is in the system or craftable.

- Minecraft: 1.10.2
- Forge: 2185
- Refined Storage: 1.2.14

Does this issue occur on a server? [yes/no]

Server and single player.

Thanks.

**Comment by tetious** [comment]
This seems to break silicon too, in a similar way. If a pattern (ore dict on in all cases) calls for the RS silicon, and I have a processing pattern to make the EnderIO version, I can't craft the pattern that depends on it, as it says silicon is missing.

However, for me, if I use the existing processing pattern manually to craft some EnderIO silicon, the dependent pattern will consume the oredict silicon just fine. This differs from @jdratlif 's report.

Hope this extra info helps. :)

**Comment by jdratlif** [comment]
That's interesting, because when we originally tried to oredict silicon on my server, it didn't take (it wanted RS silicon and we only had EIO silicon -- even though the pattern was oredict'd), so we changed all the silicon patterns to Ender IO silicon and no oredict. However, I do not recall what version we were using when we encountered this and I haven't ever gone back to those patterns.

**Comment by tetious** [comment]
I don't think I ever had a problem with it until now, though I only set up the server about a month ago. I've only ever used EIO silicon, as the recipe is cheaper. :)

One more datapoint: version 1.2.12 doesn't have the problem with either storage drawers or silicon, at least for me.

**Comment by jdratlif** [comment]
I think I've noticed something else that is related.

I can't craft binder composite anymore, either. Binder composite can use either sand or red sand, but if ore dict is checked, it just sits there trying to make it but never actually doing it. Then it tells me the machine I want to cook the binder composite in is in use, even though it never crafted the thing it seems to think it put in there.

I redid the pattern without ore dict and it's working again.

**Comment by way2muchnoise** [comment]
Should be all fixed as of 6fdff3e0f70301a2ba590f5e6483ef254fe65ee7
