### ISSUE TITLE
autocrafting issue with mystical agriculture supremium

### ISSUE THREAD

**Issue by jdratlif** [raoulvdberge/refinedstorage#788]
Refined Storage is having some difficulties autocrafting mystical agriculture essence.

The recipe uses an infusion stone, and the one I have has unlimited durability, so it is never used up by the recipe or changed in any way, really.

If I try to craft the tier 5 essence (supremium essence), it says I need 84 infusion crystals. This seems to be related to the fact it needs 4 of each tier to get to the next tier, and that would lead to 84 crafting operations.

I've tried with and without oredict checked in the pattern.

I have just the tier 1 essence (180,000 roughly) and the master infusion stone in the system. I don't have any of the intermediate essence tiers.

Picture of the crafting issue: https://postimg.org/image/mb1mtiirn/

Thanks.

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge: 2185
- Refined Storage: 1.2.14

Does this issue occur on a server? [yes/no]

Yes

**Comment by jdratlif** [comment]
Something else interesting I just noticed. Thought I was going crazy for a minute because I was sure I saw at times it could craft tier 4 essence and lower, but never tier 5. Then I noticed the issue gets weirder if you have multiple infusion stones in the system. For some reason, we have two.

If you have a second stone in the system, you can make tier 4 essence. It still says it will need more than it has, but it's okay with that. However, it still can't do tier 5.

Request 1 Tier 4 Essence with 1 stone in system - https://postimg.org/image/66yucrgcd/ -- It says no
Request 4 Tier 4 Essence with 2 stones in system - https://postimg.org/image/n1w8setdd/ -- It says no PROBLEM.

**Comment by way2muchnoise** [comment]
This is an issue regarding the fact you can keep reusing that stone. At some point in the recursion of building the crafting task it goes deeper before adding the stone back as a byproduct thus needing an extra stone. Will see if I can fix this at some point, but with finals coming up in January (yeah it sucks) I don't have that much time on hand.

**Comment by way2muchnoise** [comment]
You'll either need a stone per depth level. Or just force start the task (using ctrl+shift to activate the start button, as show on its tooltip). The force will work just fine.
![](http://puu.sh/t73WE/c4b99c9ddb.png)

**Comment by KaLul** [comment]
I can tell that this bug is present in every recipe from mystical agriculture. Whatever pattern i create which uses items from this mod the autocrafting is nor possible. (Sky Factory 3 - 3.0.4)

**Comment by raoulvdberge** [comment]
Is oredict turned on on those patterns?

**Comment by KaLul** [comment]
how do i check or do it?

**Comment by way2muchnoise** [comment]
Oredict can be turned on with the check mark when creating the pattern, and checked upon holding shift while hovering the stack (some where in the tooltip). Also what do you mean with not possible, is it like I described above (the depth related issue) or is it something else?

**Comment by KaLul** [comment]
ah ok i tried it checked and unchecked.No change... 
Yes way2muchnoise but for my usage no recipe is possible. i put 9 diamond essence in it and it will normaly remove these 9 to craft 1 diamond. so no item is usable again in this recipe.

**Comment by way2muchnoise** [comment]
Could you share some screenshots of your setup @KaLul ?

**Comment by KaLul** [comment]
![2017-01-24_18 27 10](https://cloud.githubusercontent.com/assets/815562/22258792/3d8c85f0-e263-11e6-98bc-cf93aae92b58.png)
![2017-01-24_18 27 05](https://cloud.githubusercontent.com/assets/815562/22258809/4bb7ef2a-e263-11e6-9bca-ee9fb54200a1.jpg)
![2017-01-24_18 27 18](https://cloud.githubusercontent.com/assets/815562/22258819/50c2dce6-e263-11e6-98a5-b2acbcd16314.jpg)
![2017-01-24_18 27 36](https://cloud.githubusercontent.com/assets/815562/22258828/53b67bf6-e263-11e6-9fcd-488c32a34132.jpg)
hope this is all you need

**Comment by way2muchnoise** [comment]
And you can't shift + ctrl + left click that stack to start a crafting operation?

**Comment by KaLul** [comment]
Yes.... yes i can Oo 
i have looked in every youtube video and wiki or forum page but it never sayd shift AND ctrl :/ 
Thank you!

**Comment by way2muchnoise** [comment]
It is on our wiki https://refinedstorage.raoulvdberge.com/wiki/autocrafting :D glad I could help
