### ISSUE TITLE
Unable to craft Fortune III upgrade

### ISSUE THREAD

**Issue by misric** [raoulvdberge/refinedstorage#791]
#### Issue description:

In SP and MP, I'm unable to craftin solderer Fortune III upgrade from a Fortune III enchanted book created in anvil from 2x Fortune II. Still working with native Fortune III book.

#### What happens:

Fortune III book won't fit in solderer slot if created in anvil

#### What you expected to happen:

create fortune III upgrade

#### Steps to reproduce:
1. Create 2x Fortune II enchanted book ( /give <player> enchanted_book 2 0 {StoredEnchantments:[{id:35,lvl:2}]} )
2. Merge in an anvil to get a fortune III
3. Trying to create Fortune Upgrade in solderer

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge: 12.18.3.2185
- Refined Storage: 1.2.9

Does this issue occur on a server? yes

**Comment by raoulvdberge** [comment]
update your RS version before creating an issue
