### ISSUE TITLE
Autocrafting IC2 cables as part of another crafting job does not craft all of them.

### ISSUE THREAD

**Issue by bloxgate** [raoulvdberge/refinedstorage#798]
#### Issue description:
I have a bunch of IC2 machines autocraftable in my RS system, many of which require insulated cables to craft. When I start the crafting job the system says its able to make all the required cables, but once the job starts it never makes all of them and hangs
#### What happens:
The system autocrafts 1 ingot into 3 uninsulated wires and imports them into the system. Then crafts 1 or 2 insulated cables, and refuses to craft the third. For some larger crafting jobs, this can cause the system to get stuck waiting for 20 cables while it has all the ingredients required to craft them.
#### What you expected to happen:
The autocrafting system makes all 3 of the cables.
#### Steps to reproduce:
1. Add the recipe for IC2 solar panels and all of their components to the system
2. Attempt to autocraft 8 solar panels
3. System will get stuck waiting for cables

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge: 12.18.3.2185
- Refined Storage: 1.2.14

Does this issue occur on a server? [yes/no]
Yes

**Comment by PWTordenskiold** [comment]
See #766.

**Comment by way2muchnoise** [comment]
Should be all fixed as of 6fdff3e0f70301a2ba590f5e6483ef254fe65ee7
