### ISSUE TITLE
Controller taking as much EU as possible

### ISSUE THREAD

**Issue by tenjaa** [raoulvdberge/refinedstorage#799]
#### Issue description:
We are playing with Industrial Craft and the Controller takes as much EU as possible.

#### What happens:
The controller says it needs 74 RS/t. That should be ~19 EU/t.
When connected to a CESU (max output: 128 EU/t) the controller takes 128EU/t. With a LV-Transformator (max output: 32EU/t) the controller just takes 32 EU/t.

#### What you expected to happen:
The controller should take 19 EU/t.

#### Steps to reproduce:
1. Plant a controller and some things that consume RS.
2. Build a CESU and put an advanced Battery in it to charge it.
3. Connect the Controller with the CESU by Copper Cables.
4. Measure the EU Out/Input with an [EU-Reader](http://wiki.industrial-craft.net/index.php?title=EC-Meter). It says 128 EU/t.
5. Put an LV-Transformater between Controller and CESU.
6. Repeat step 4 and you see 32 EU/t.

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge: 12.18.3.2185
- Refined Storage: 1.2.14
- Industrial Craft 2: 2.6.140-ex110

Does this issue occur on a server? yes

I can provide screenshots, if required.

**Comment by tenjaa** [comment]
I addition to this we noticed that the output of an LV-Transformer is (always enough).
The controller says it needs 226 RS/t (56.5EU/t). The LV-Transformer has a max output of 32EU/t.
But the controller wont go empty.
The in- and output was again verified by the EU-Reader.

**Comment by raoulvdberge** [comment]
I have no idea what causes this bug. We are using the IC2 api correctly, and I can do nothing to fix it because IC2 is closed-source. Also, IC2 support is removed in the 1.11 version of the mod so I'm going to tag this as wontfix.
