### ISSUE TITLE
Blocks become inepte after a while

### ISSUE THREAD

**Issue by ExDomino** [raoulvdberge/refinedstorage#800]
#### Issue description:

Sometimes, blocks from your mod (ex.: Grid, Relay, Solderer, ...) ceases to work and need to be destroyed and replaced. For example if I place a lever next to the controller to turn it on or off, the lever ceases to work after a while and the system stay on or off. And the Solderer is no longer working. I don't really have to destroy and replace Disk Drives but the issues is related to Grids, Controllers, Relay and Solderer.

I think the true problem is that the system ceases to understand the levers states and acts like it's off while it shows it's on. I don't know if it's only a visual glitch or not, but my Solderer ceased to work when my lever was in position to make the system online.

To fix the problem, I have had to destroy the controler and the relay and then place them again. For the relay, I think it just ceased to understand the lever state in staying online without the possibility to shutting it down with the lever before I destroyed it and replaced it again. The chunk where the system is placed is chunkloaded.

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge: 12.18.2.2166
- Refined Storage: 1.2.8

Does this issue occur on a server? yes

#### If a (crash)log is relevant for this issue, link it here:
N/A

**Comment by ExDomino** [comment]
In order to be able to craft another thing in my network, I have had to break the core and then replace it again, else nothing works in the network.

**Comment by raoulvdberge** [comment]
fixed in 1.11

**Comment by ExDomino** [comment]
This is fixed for minecraft 1.11 but not for minecraft 1.10, so it's NOT fixed! I don't know if you know this reality, but when you play minecraft with mods on a server, you CANNOT update minecraft to a new version and keep your players because they DO NOT want their work gone just to fix a bug. Can you make a version for 1.10 with this bug fixed please?

**Comment by raoulvdberge** [comment]
the amount of work to get this bug fixed was: 7+ hrs of work, 10 000 + lines of code changed. You expect me to backport this?

**Comment by ExDomino** [comment]
Can you help me to identify the problem? What we can do in 1.10 to prevent the bug to affect us or to be the lest affected by it? As you said, you can't really fix the bug for the 1.10.2 but you can tell us what to do to reduce the chance that the bug occur again. Chunkloading the zone for example? We're using FTBUtilities that has the problem that it unloads chunk when a player logout.

**Comment by raoulvdberge** [comment]
just make sure the chunks where your RS system is are ALL loaded. We might get the fix in 1.10.2 as well hopefully, we'll see.
