### ISSUE TITLE
[1.10.2] - Client Crash Instead of Missing Mods Page

### ISSUE THREAD

**Issue by MafooHamhead** [raoulvdberge/refinedstorage#802]
#### Issue description: 
Minecraft Client crashes with a error log rather than displaying Missing Mods page.

#### What happens: 
Placing Refined Storage in my custom modpack (with other mods in it) causes it to crash when MCMultipart is not included. (At least, the correct version. More on that later.)

#### What you expected to happen:
I expected the Missing Mods page to appear or a more resourceful error log to appear... It was really tedious to narrow down what was happening.

#### Steps to reproduce: (This isn't a 100% way to reproduce it. Not sure EXACTLY what I did)
1. Install a selection of mods (at least a handful, all latest versions)
2. Install Refined Storage (latest version) without MCMultipart of any kind.
3. Run Minecraft.
...

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge: 12.18.3.2185
- Refined Storage: 1.2.14

Does this issue occur on a server? [yes/no]
#### If a (crash)log is relevant for this issue, link it here:

http://pastebin.com/3b4w8waS

#### Notes:

This is NOT an OptiFine issue. I tested it in my selection of mods with and without it. I've also noticed that a certain mod (I want to say either yours or Super Circuit Maker) installs an experimental version of MCMultipart. Which one or the other does not support(?).. I believe one of them actually ends up replacing the latest CurseForge MCMultipart version with 'MCMultiPart-experimental-2.0.0_88-universal.jar' in a 1,10,2 folder inside the mods folder itself. 

I'm not entirely sure what's going on... but this crash has been annoying me for quite some time and I finally narrowed it down partially. Was hoping some insight or solution could be found at some point about it. Love your mod, though. Keep up the great work! 👍

**Comment by way2muchnoise** [comment]
Something want to access `streams.client.package` which is not something Refined Storage needs. Can you reproduce this with only refined storage installed?

**Comment by MafooHamhead** [comment]
>

**Comment by MafooHamhead** [comment]
No, I cannot. In my testing I took out Refined Storage **ONLY** (without MCMultipart in the mods folder) and Minecraft successfully booted. I put it back in and the crash log I provided occurs. (Fails to boot)

I tried it with just Refined Storage and it says Missing Mods, AKA it requires MCMultipart. I tried it with JUST  Super Circuit Maker, MCMultiPart 1.3.0, and Refined Storage. Worked fine. I added several of mods and then I noticed that MCMultiPart 1.3.0 was **removed** from the mods folder and replaced with a 1.10.2 folder with the experimental version inside that folder. Oddly enough everything works flawlessly. I think I only get the error log if I don't have MCMultiPart in the mods folder with some other mod or library. Again it works as intended by itself by showing the Missing Mods page.

Also, sorry for closing and reopening the issue. Kinda new to GitHub and accidentally clicked the wrong button. D:

**Comment by raoulvdberge** [comment]
Seems like the Streams mod is causing the issue, hence the error at `streams/client/package`.

Also, you seem to be using the 1.9.4 version of that mod?
```
    U   streams{0.3} [Streams] (Streams-1.9.4-0.3.jar)
```

**Comment by MafooHamhead** [comment]
I know how to read a crash log partially, so I saw "streams" and thought the same thing. The thing that doesn't make sense is if I take out the Refined Storage mod, the error goes away. I put in MCMultiPart and the error goes away. I tried looking for solutions on that specific crash and nothing came up. 

**I just tried a new setup. I put Streams and Farseek (the library for Streams) into a modpack by itself. Booted fine. I added Refined Storage WITHOUT MCMultiPart next. I get the exact same crash log I posted. I put in MCMultiPart next. The crash goes away.

I'm not trying to blame you or belittle you, but the **Missing Mods page** should pop up here. MCMultiPart is required for your mod. Why would Streams crash/fail to boot the game if the missing mod wasn't even connected to it?

I'm using the 1.9.4 version because that's the latest the mod author has released. And it's labeled as a "1.10.2" download. And it DOES work as intended too. No massive errors from the mod, just the weird crash when combined with mods that require MCMultiPart but don't have it.

**Comment by way2muchnoise** [comment]
The mod missing part isn't something Forge provides and we use correctly ([See code](https://github.com/raoulvdberge/refinedstorage/blob/mc1.10/src/main/java/com/raoulvdberge/refinedstorage/RS.java#L26))

So there isn't anything we can do at this point. It is just some bad interaction between some of the mods. The fact streams crash before it even gets to the mod missing screen means that is going wrong somewhere in their stuff. They might be shading some MCMultipart stuff or just install some bad version. The fact the missing class is not either MCMultipart or Refined Storage means we can do nothing on our end as we have no interaction with either Streams or Farseek.

**Comment by MafooHamhead** [comment]
I see. So something on their end is practically breaking the error reporting before it even gets a chance to display the Missing Mods page? Like I said, the mods were perfectly fine together so it's not like I can't have them both. Just thought I would share this error where I thought it was appropriate.

Thanks for the help though, you two! Hopefully they sort out their issues.
