### ISSUE TITLE
wiki edit suggestion: cable

### ISSUE THREAD

**Issue by NealHicks** [raoulvdberge/refinedstorage#803]
### Issue description:
I would suggest on the wiki page for Cable that there be a minor mention of the fact that no power or network signal passes through the Processing Pattern Encoder Block (PPEB.)  While the wiki page for the PPEB implies this by saying it doesn't have to be included in the network (it can stand alone and still function,) the wiki entry for Cable by saying "as long as the machines are next to each other in any direction a connection will be established as well," this wording skims past the fact there is one block in the mod for which this is not true.  I think a small edit to the Cable page would be informative for those of us who are new :)
#### What happens:
A new user of the mod like me can have parts of a network on the far side of a PPEB and wonder what I am doing wrong for an embarrassing length of time, as those blocks refuse to function.
#### What you expected to happen:
for all connected blocks to share power and signal from the controller as is implied.
#### Steps to reproduce:
1.  Place any network blocks past a PPEB.  
#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge: 12.18.3.2185
- Refined Storage: 1.2.11 (part of MoonDew Valley modpack from the Curse launcher.)

Does this issue occur on a server? [yes/no]
I play survival single player.

**Comment by raoulvdberge** [comment]
You are right, I changed this in https://refinedstorage.raoulvdberge.com/wiki/cable/a02f509db87e6f908c5754fb034782ad
