### ISSUE TITLE
Failure on SMP When complete power loss and no one on the server

### ISSUE THREAD

**Issue by phantom1004** [raoulvdberge/refinedstorage#806]
#### Issue description:
Catastrophic Failure on SMP When complete power loss and no one on the server
#### What happens:
Catastrophic Failure on SMP When complete power loss and no one on the server, Loses all information stored for Imports/exports, Terminals refuse to "refresh" once power is resupplied, introduction of new interfaces work but existing remain broken, screenshot below
#### What you expected to happen:
Logged off of my SMP server that i recently started, chunkloaded but apparently doesnt work, power emptied from the system and when i return i am presented by https://i.gyazo.com/87b4da252c74f440b7e1086942078ae3.png

More photos will follow

#### Steps to reproduce:

Not quite sure but this is what i did

1.Build system
2.log off
3.log back on when power is completely gone
...

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge: 12.18.3.2185
- Refined Storage:1.2.12

Does this issue occur on a server? [yes/no]
Yes
#### If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here]

gonna link as many on topic photos as i can to help
https://i.gyazo.com/a8568afb4842ffa0dc80df1c76ddada7.png Connected Devices and "apparent" system being functional however in the background you can see the blacked out screens

https://i.gyazo.com/3cea4f285aa97e8d48f5512daf274c19.png View of the system thru the eyes of the terminal

https://i.gyazo.com/aff2ff729f7dacdfc4918482da5a611a.png added a terminal that is attached to a "blacked out" pattern terminal, works without an issue

As stated, Import refuse to import, Export the same, crafters are seen and recipes inside them work however when requested nothing happens

**Comment by phantom1004** [comment]
Update:
1. Relogged
2. Crafting Terminal still off, Pattern Terminal Working and Crafting Monitor working
3. Autocrafting still inactive

**Comment by raoulvdberge** [comment]
Fixed in 1.11. might get backport to 1.10 at some point
