### ISSUE TITLE
Ability to expan number of upgrade slots via config

### ISSUE THREAD

**Issue by Joshwoo70** [raoulvdberge/refinedstorage#807]
The amount of upgrade slots feels limited. i think it is possible to increase the limit of them. Howerver it depends on the upgrades in question if they are able to scale linearly or not.

**Comment by way2muchnoise** [comment]
In the case of expanding. I can see things like the manipulator being slow and might need some defragment upgrade (Some thing that does the whole drive in a couple passes). And maybe some heat upgrade for the solderer as that can be slow as well. But do we really need expanding?

**Comment by Joshwoo70** [comment]
yes can see an issue where you can have a few quantun quarries and thry fill up a ender chest quite fast. the importers may not be able to catch up to pull items out fast enough.

**Comment by Joshwoo70** [comment]
allos speaking of defragging we are assuming those disk drives are Hard disks right? :P

**Comment by way2muchnoise** [comment]
Yeah, isn't a stack + 3 speed upgrades enough to follow the quarries? Also I guess you could do multiple importers.

**Comment by raoulvdberge** [comment]
I've said this multiple times, we don't need multiple filter slots. And you can just add more importers/exporters if needed.

**Comment by Joshwoo70** [comment]
filter slots? you miss read... UPGRADE slots...

**Comment by raoulvdberge** [comment]
Whoops, I'm an idiot. Yeah, still not sure about more upgrade slots.

**Comment by jdratlif** [comment]
I wouldn't be against letting the upgrades stack up to to a certain number, possibly even with a config option and allowing them in the same GUI you have now, similar to how industrialcraft overclockers work. You can put one in each slot, or you can put 8 (or more, not sure what the limit is, probably 16 or 64, whatever the stack size is on overclockers) in a single slot.

I've simply been buffering. A single ender chest (from Ender Storage) goes back to my base which is extracted using Ender IO conduits with speed upgrades into three gold chests all with importers with stack and speed upgrades in them. You could buffer into the ender chest, too if it was the other side that needed faster importing. I haven't tried extra utilities transfer nodes with speed upgrades; could be faster, but idk.

**Comment by LousyLynx** [comment]
I feel like there should be a toggleable amount or a new toggleable upgrade that adds to the amount of usable upgrade slots.

**Comment by raoulvdberge** [comment]
I'm leaving it as is. It's fine this way.
