### ISSUE TITLE
AutoCrafting With Hoppers, Open Crates, etc.

### ISSUE THREAD

**Issue by H3lpM3** [raoulvdberge/refinedstorage#808]
#### Issue description:
I was trying to automate Botania crafting, and I tried facing a crafter at a Botania Open Crate.
I also tried vanilla hoppers and ExtraUtil2's mini chest.

#### What happens:
Nothing. Items will not move from the system, and the recipe will stay in the crafting monitor.

#### What you expected to happen:
The items specified in the recipe to be sent to these blocks.
(Also, I tried outputting to a chest, and that worked)
I don't know if this is intentional, or not, so I thought I'd post it here.

#### Steps to reproduce:
1. Create a recipe in the proccessing pattern encoder
2. Put it in a crafter
3. Stick a hopper/Open Crate/Mini Chest in front of the hopper
4. Attempt to autocraft

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge: 12.18.3.2185
- Refined Storage: 1.2.12
- FTB Infinity Lite: 1.4.1

Does this issue occur on a server? [yes/no]
Yes, this was done on my locally hosted sever.

**Comment by way2muchnoise** [comment]
Could you share some pictures of the setup and patterns?

**Comment by H3lpM3** [comment]
I think I figured it out. The crafter won't output unless all of the ingredients can be sent. I don't know if this is quite a bug, but it does kind of prevent autocrafting for botania. (I'm guessing the open crate only has 1 storage slot)

[This was my setup](https://www.dropbox.com/s/q8awgf3k9scqzwo/2017-01-01_22.50.39.png?dl=0)

[Everything was also tested on this](https://www.dropbox.com/s/jd4o6mo6nyauugd/2017-01-01_22.48.18.png?dl=0)

[This recipe did not work for me](https://www.dropbox.com/s/dtfkrcpbu9mscmo/2017-01-01_23.15.58.png?dl=0)

[This recipe worked for me](https://www.dropbox.com/s/7tqwt6f96ylfz20/2017-01-01_22.46.03.png?dl=0)
(By work, I mean it outputted into the hopper/crate)

However, after [replacing the Open Crate/Hopper with a chest,](https://www.dropbox.com/s/2fxrhhdha3sfo7i/2017-01-01_22.51.39.png?dl=0)
[it would start working with anything I input](https://www.dropbox.com/s/hi4ecovu57m8y2n/2017-01-01_23.19.01.png?dl=0)



I then tried random recipes with varying amounts of input items:

= Only works with Chest=
[6 Items](https://www.dropbox.com/s/v0mqgwkz0z56ped/2017-01-01_23.34.13.png?dl=0)

= Works with chests and hoppers =
[5 Items](https://www.dropbox.com/s/uuute15xpz4hdnn/2017-01-01_23.34.18.png?dl=0)
[4 Items](https://www.dropbox.com/s/c4d8rlvkmyz3yz1/2017-01-01_23.34.20.png?dl=0)
[3 Items](https://www.dropbox.com/s/7kejuow8gbsf0r2/2017-01-01_23.34.22.png?dl=0)
[2 Items](https://www.dropbox.com/s/utyldgeygioeh1z/2017-01-01_23.34.24.png?dl=0)

= Works with chests/hoppers/open crates/mini chests/dirt chests/pretty much anything I threw at it =
1 Item Recipes

**Comment by way2muchnoise** [comment]
Yeah, the crafter expects that all items can be put into the inventory. If we wouldn't do that you could get really odd interactions with other mods. I guess you'll need to take that into account. You would always put the crafter against a hopper and have that move into the Open Crate.

Anyways this is an other quality report that can go on my list of examples of how to report bugs :+1:

**Comment by lclark1975** [comment]
I have set this up as follows. Mini chest into hopper, I then have an exporter with a crafting upgrade. As long as the resonator has a crafter and importer connected this will automate Botania.

For the initial setup of Botania check out Direwolf20 S8 lets play 


![2017-02-06_17 04 57](https://cloud.githubusercontent.com/assets/22301957/22657479/886a9d9a-ec4b-11e6-9e9d-7c14533fd365.png)
![2017-02-06_17 05 07](https://cloud.githubusercontent.com/assets/22301957/22657478/8861b6e4-ec4b-11e6-87ca-6c88a309e47a.png)
