### ISSUE TITLE
Issue pulling recipes from JEI into crafting grid

### ISSUE THREAD

**Issue by JathTyki** [raoulvdberge/refinedstorage#809]
#### Issue description:
When attempting to pull recipe from JEI into crafting table, console errors out and items don't appear.

#### What happens:
Only 1 item came when attempting to pull recipe from JEI/RS Network for Ender IO's Double-Layer Capacitor

#### What you expected to happen:
All items to come from Grid/RS storage and to show in the crafting grid.

#### Steps to reproduce:
1. Search Double-Layer Capacitor in JEI and click on it.
2. Click on + to put into crafting grid based on items in RS Network
3. Only one item will come out, giving below error.
...

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge: 12.18.3.2185
- Refined Storage: 1.2.14
- Ender IO: 3.1.156
- Quantum Storage: 3.2.17

Does this issue occur on a server? [yes/no]

#### If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here]
http://pastebin.com/a6VE1EYn

**Comment by JathTyki** [comment]
I want to make a correction in my title too. Not really pulling the recipe from JEI... It's more pulling the items from the network into the crafting grid. It errors on specifically on the quantum storage unit, which I did put that version number in there too.

**Comment by raoulvdberge** [comment]
Does this happen 100% of the time?

**Comment by raoulvdberge** [comment]
Closed as reporter is not responding.
