### ISSUE TITLE
Exporters exporting wrong item or not exporting at all.

### ISSUE THREAD

**Issue by varukasalt** [raoulvdberge/refinedstorage#81]
Original bug was after programming an exporter with TechReborn Silver ore, Ruby ore was exported instead. When attempting to reproduce, nothing is exported. TR Lead ore will also not export. Vanilla and other ores seem to export properly. I am exporting into an Ender IO SAG mill. Manually inserting TR ores does work.

**Comment by raoulvdberge** [comment]
> exporter with TechReborn Silver ore, Ruby ore was exported instead
Did you compare on damage?

**Comment by raoulvdberge** [comment]
Going to close this as not reproduceable. Please reopen if you have the same issue on latest EnderIO...
