### ISSUE TITLE
Rendering Issue

### ISSUE THREAD

**Issue by JathTyki** [raoulvdberge/refinedstorage#810]
#### Steps to reproduce:
1. I attempted to convert a copper block to ingots in Grid's crafting grid.
2. Crashed
3.
...

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge: 12.18.3.2185
- Refined Storage: 1.2.14

Does this issue occur on a server? [yes/no] Yes

#### If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here]
http://pastebin.com/bRSXZBjC

**Comment by way2muchnoise** [comment]
It seems like minetweaker is chocking on some tooltip. You might want report it to them. Or check your minetweaker scripts or mod pack issue tracker.
