### ISSUE TITLE
Color change for construction core

### ISSUE THREAD

**Issue by Ash70** [raoulvdberge/refinedstorage#811]
This might be a bit nitpicky but the construction core has the same blue color as the advanced processor which can be confusing. Would it be possible to change it to green. That would also fit better as the opposite of the red destruction core.

**Comment by CyanideX** [comment]
Not nitpicking at all. Your request is reasonable and something I should've noticed earlier. I'll have to change the Constructor block color as well.

Perhaps I can change the processor in another way? I know @raoulvdberge likes his blues. ;)

**Comment by Ash70** [comment]
Perhaps a greenish blue? ;-)

**Comment by raoulvdberge** [comment]
I really like my blues indeed. I don't think this should be changed.

**Comment by CyanideX** [comment]
On second look, the core and processor color are completely different! :P You might want to double check that next time, @Ash70. 😋
