### ISSUE TITLE
cable not connecting to the network

### ISSUE THREAD

**Issue by DoomSquirter** [raoulvdberge/refinedstorage#813]
Edit: noticed that nothing for cables are working (importer, exporter).  None show up on the network list in the controller.

#### Issue description:
the cable is not passing power from the controller to other blocks nor are they connecting to network.
#### What happens:
the cable is not passing power from the controller to other blocks
#### What you expected to happen:
power to be passed from the controller to other blocks

#### Steps to reproduce:
1. placed controller down, hooked it to solars for power
2. controller gets power, ran cable under the controller to where I put my solderer
3. solderer didn't get any power.  wouldn't work
4. moved controller to behind solderer, got my bits made, assumed solderer now needed to be connected to controller
5.  put disk drives in place I had intended for controller, hooked it up (and verified cable is connected many times)
6. No power is reaching the 2 disk bays and crafting grid I placed.  
...

#### Version (Make sure you are on the latest version before reporting):
running skyfactory 3 on curse
- Minecraft: 1.10.2
- Forge: 12.18.3.2185
- Refined Storage: refinedstorage-1.2.14

Does this issue occur on a server? [yes/no]
SSP
#### If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here]

**Comment by way2muchnoise** [comment]
Could you add a screenshot of your setup? Also is the solar power enough to power the system?

**Comment by DoomSquirter** [comment]
restarted client twice and problem resolved itself.  

It's a real simple setup, I've used refined storage quite a few times, so not my first setup.  

Really at a loss here.  this must have been my 4th or 5th restart while trying to figure this out.  nothing in logs mention refined storage, zilch.

**Comment by DoomSquirter** [comment]
ok, so I don't have to restart client, just save/quit to menu and reload world (this is on ssp).  But, I have to do this each time I add another cable to the network to get the controller to see the connected device on my network.

**Comment by DoomSquirter** [comment]
I'm truly wondering if something in the pack is causing this.  again, I've used refined storage quite a few times.  I've had issues before but none like this.  and the problem does seem a bit erratic in that it'll work fine a few times (moving out of chests into RR) and I'll hook up an importer and it'll suck all the items from the chest, then move onto next chest and break importer replace it on new chest, works fine, third chest tho which I have to add some more cables to it, won't work and I waited 30-60 seconds to see if it's just some sort of delay while it calculates the network but no.  quit/load and everything's working.  do this again and add more cable and it works immediately this time.  really sorry I don't have any useful info for you guys.

**Comment by way2muchnoise** [comment]
Could there be any ram related issue? Or something slowing down the tick rate maybe?

**Comment by DoomSquirter** [comment]
have 6 gbs allocated, using mmc.  not using any java args tho.  haven't monitored tps, will do that and update if tps seems to be an issue, tho that's a good call and possibly would explain the intermittent behavior.

**Comment by renzhentaxi** [comment]
http://imgur.com/a/4EAas

Heres me with the issue
It fixes itself with a server restart but happens every 3-4 hours.
Ithink i has something to do with the blocks not updating

**Comment by way2muchnoise** [comment]
Likely related to #370

**Comment by raoulvdberge** [comment]
fixed in 1.11. might get backported to 1.10
