### ISSUE TITLE
Better search options

### ISSUE THREAD

**Issue by renzhentaxi** [raoulvdberge/refinedstorage#814]
Sometimes when I want to search for all the dusts in my storage, I would have type dust and then powder and then grit and ..... Which is really annoying. Also sometimes when i want to find ore i would get stuff like core, and etc. 
Basically I really want to search by ore-dictionary and regular expression kinda like jei and nei.
Thank you for your time.

**Comment by raoulvdberge** [comment]
So something like `dust|power|grit` to find those 3?

**Comment by renzhentaxi** [comment]
Not exactly. All dust, powder, and grit have the same ore-dictionary name.
E.g. copper dust, copper powder and copper grit are all considered as dustCopper.
So maybe something like `%dust` would give all the dust powder and grit and `%dustCopper`would give copper dust, copper powder and copper grit.

**Comment by raoulvdberge** [comment]
So basically oredict search. We can do that.
