### ISSUE TITLE
Server Crash on Storage Drawer Controller Break

### ISSUE THREAD

**Issue by aaronmallen** [raoulvdberge/refinedstorage#815]
#### Issue description:
When an external storage is connected to a Storage Drawers Drawer controller, and the draw controller block is broken a server crash occurs.

#### What happens:
Server Crashes

#### What you expected to happen:
Not having the server crash

#### Steps to reproduce:
1. Connect an external storage to a Storage Drawers drawer controller.
2. Break The Drawer Controller
...

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge: 12.18.3.2185
- Refined Storage:  1.2.14

Does this issue occur on a server? [yes/no]
yes

#### If a (crash)log is relevant for this issue, link it here:
https://gist.github.com/aaronmallen/433b9ce71db185ee565fb23f3e7ef008

**Comment by john01dav** [comment]
I have this same issue on my server running FTB Direwolf20 1.2.2 without anything being broken. In any case, is there any chance I could get a backport of the fix to the version running in that pack?

**Comment by raoulvdberge** [comment]
My fix was applied to the 1.10 branch, it's in the latest RS version published today.

**Comment by john01dav** [comment]
@raoulvdberge The modpack I am using has version 1.2.14. I can't updated it because I don't have control over the clients mod versions. Is there any chance I could get backport of the fix to version 1.2.14 so my players can use drawers with Refined Storage until the modpack decides to update (which has been slow since the pack was published)?

**Comment by raoulvdberge** [comment]
This bug was fixed in version 1.2.15. If you don't update to 1.2.15, you can't get the fix.

**Comment by raoulvdberge** [comment]
Obviously, I cannot magically modify your 1.2.14 installation to get the bug fixed there. You have to update.

**Comment by aaronmallen** [comment]
damn @raoulvdberge that was fast!
