### ISSUE TITLE
Crafter tiers

### ISSUE THREAD

**Issue by raoulvdberge** [raoulvdberge/refinedstorage#816]
Not sure about this one yet:

- Basic Crafter (9 slots, 1 advanced processor + 1 basic processor)
- Improved Crafter (18 slots, basic crafter + 1 improved processor)
- Advanced Crafter (27 slots, improved crafter + 1 advanced processor)

**Comment by MrPatience** [comment]
I feel like the recipes for the improved and advanced seems quite easy if it only needs processors ? Maybe It should use mid game and end game items ?

**Comment by VT-14** [comment]
How about:
All of them -> 4 Quartz Enriched Iron + 1 Construction Core + 1 Destruction Core
Basic Crafter -> 1 Machine Casing + 2 Basic Processors
Improved Crafter -> Basic Crafter + 2 Improved Processors
Advanced Crafter -> Improved Crafter + 2 Advanced Processors

Alternatively, keep the current recipe (4 QEI, 1 Con/Des Core, 2 Advanced Processors) and only replace the Machine Casing for the next level.

**Comment by raoulvdberge** [comment]
Turns out I don't want this feature anymore.
