### ISSUE TITLE
autocrafting not working

### ISSUE THREAD

**Issue by cham326** [raoulvdberge/refinedstorage#818]
#### Steps to reproduce:
1. request something 
2 .check in the crafting monitor 
3. nothing happens
...

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge: 8.0.99.99
- Refined Storage: 1.2.8

Does this issue occur on a server? [yes/no]
yes
#### If a (crash)log is relevant for this issue, link it here:
no log
[pastebin/gist/etc link here]
in the direwolf 1.10 mod pack
![2017-01-03_14 11 45](https://cloud.githubusercontent.com/assets/24901376/21621464/c5668e5e-d1be-11e6-9a2f-b349815afc1e.png)
![2017-01-03_14 11 54](https://cloud.githubusercontent.com/assets/24901376/21621468/c7ae334c-d1be-11e6-97c4-6463d6d227d8.png)

**Comment by raoulvdberge** [comment]
update your rs version

**Comment by cham326** [comment]
I'm in a mod pack and a server with out dated server

**Comment by way2muchnoise** [comment]
Then you should report it to your server owner/pack maker.

**Comment by way2muchnoise** [comment]
The new release version of dw20 being 1.2.2 has RS 1.2.14 which should solve a lot of issues.

**Comment by cham326** [comment]
my brother bought a server from mcprohosting and they have not put away to update it to the newest version

**Comment by ktole1999** [comment]
the host doesnt control pack version. owner does. host just controls minecraft version it supports.

**Comment by cham326** [comment]
I now but it does not show the newest updated version for the direwolf 1.10 pack it only goes to 1.1.4

**Comment by ktole1999** [comment]
then server owner should be able to upload the version being used. sounds like host is trying to make it easy but may not be up to date with latest.

**Comment by way2muchnoise** [comment]
The release version might just have been tagged like a couple of hours tho. Can't you access the beta versions of the pack?

**Comment by cham326** [comment]
well he can't upload it right now he is at work 

we were using the 1.1.2 version of the pack before I notice the system not working
