### ISSUE TITLE
Crafting Recipies that require experience from the player with the crafting grid

### ISSUE THREAD

**Issue by Sayomie** [raoulvdberge/refinedstorage#819]
#### Issue description:
A recipe that requires experience from that player can not be crafted on the crafting grid.

#### What happens:
It does not work.

#### What you expected to happen:
It to work.

#### Steps to reproduce:
(I am using the latest version of the direwolf20 pack so it is not the latest version of refined storage but looking through your patch notes I did not see anything referencing a update for this)
1. Locate a item you want to craft that requires experience (Something like "Golden Lasso" from ExtraUtils2)
2. Try and craft the recipe for said item.
3.  Nothing happens

- Minecraft: 1.10.2 (Direwolf20 Pack)
- Forge:
- Refined Storage:
- Many other mods

Does this issue occur on a server? [yes/no]
Unknown

**Comment by raoulvdberge** [comment]
This is not possible since the grid crafting view isn't unique to the player.

**Comment by way2muchnoise** [comment]
The RS grid isn't a per player GUI so it just doesn't work. It is kind of a mechanic XU added for this reason.
