### ISSUE TITLE
Importers remove from all slots on Ender IO machines

### ISSUE THREAD

**Issue by varukasalt** [raoulvdberge/refinedstorage#82]
Importers remove everything from every slot of Ender IO machines, including upgrades. This happens even if the machine has been programmed with specific inputs / outputs in the Ender IO machine GUI. Behaviour also occurs on unprogrammed machines, regardless of which side the Importer is placed on.

**Comment by raoulvdberge** [comment]
Do hoppers also extract from every slot?

**Comment by varukasalt** [comment]
No Hoppers perform as expected. They only pull from the bottom or output
slots.

**Comment by raoulvdberge** [comment]
Weird, it shouldn't be doing it. It uses the same logic as for furnaces, where it works correctly. I'll take a look at it.

**Comment by raoulvdberge** [comment]
I can't seem to reproduce this with a dev build of EnderIO. Check this gif where I tried this on the sagmill. The importer only extracts from the output slot.

http://i.imgur.com/j70WKkz.gifv

http://ci.tterrag.com/job/EnderIO-1.9.4/

**Comment by varukasalt** [comment]
Sorry going to be out of touch for a little while. Family medical
emergency. Everything will be OK and I'll be back soon.

**Comment by raoulvdberge** [comment]
No problem, good luck!

**Comment by varukasalt** [comment]
Closing because I can no longer reproduce the error. They seem to be working fine now. Must have been something on my end. Sorry for the hassle.
