### ISSUE TITLE
All exporters and importers on network suddenly stop working

### ISSUE THREAD

**Issue by sp823** [raoulvdberge/refinedstorage#822]
Not sure of the exact cause, it is just something that happens after the server has been up for a bit. Breaking and replacing controller does not help. Breaking and replacing the exporters/importers one by one does - they will start working again once placed. If I shutdown the server and bring it back up they will also start to work again. Neither is a really great workaround. This issue does not seem to affect external storage at all - that continues to work when the importers and exporters stop.

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge: build 2185
- Refined Storage: 1.2.14

Does this issue occur on a server? yes

**Comment by way2muchnoise** [comment]
Likely related to #370

**Comment by raoulvdberge** [comment]
fixed in 1.11. might get backported to 1.10

**Comment by Fusty** [comment]
Definitely hoping this gets backported to 1.10.  It's a frequent hitch currently.

**Comment by ShadowDrakken** [comment]
Given that SkyFactory is huge right now, it'd be nice to have the backport for the sake of everyone's sanity :)

**Comment by camosborn21** [comment]
In case anyone stumbles onto this post months after the fact like I just did, I fixed the issue by moving around some hard drives in the disk storage system.
