### ISSUE TITLE
Cable not connecting to the network and drives dead

### ISSUE THREAD

**Issue by Tawnyman** [raoulvdberge/refinedstorage#823]
Cable not connecting to the network

Ok this is a hell of a bug on sf3 we are using v1.2.14 and the cables will not connect link to screen shots at the bottom you can see that when I link with a cable nothing works when you link with a crafter it will work. I have also run into the bug with drives showing the item count but not being able to see them in a grid they may have been corrupted there was no server crash but I did have them in my inventory when going into and out of creative  

Steps to reproduce:
in link at bottom of page

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge:12.18.3.200010085
- Refined Storage: v1.2.14

Does this issue occur on a server? [yes]

#### If a (crash)log is relevant for this issue, link it here:
http://imgur.com/a/2jrBX

**Comment by way2muchnoise** [comment]
Related to #370

**Comment by raoulvdberge** [comment]
fixed in 1.11. might get backported to 1.10
