### ISSUE TITLE
Crash with External Storage

### ISSUE THREAD

**Issue by nikita488** [raoulvdberge/refinedstorage#824]
#### Issue description:
I played in Singleplayer, in Nether i teleport to my RFTools Void Dimension and i just get this crash, i see something about External Storage in crash, i have 3 on my base, 1 on Storage Drawer Controller, 1 on Item Interface from Actually Additions and 1 on sorting Chest.
#### What happens:
Crash
#### What you expected to happen:
Not having crash
#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge: 12.18.3.2185
- Refined Storage: 1.2.15

Does this issue occur on a server? [yes/no]
Yes
#### If a (crash)log is relevant for this issue, link it here:
https://gist.github.com/nikita488/4d3b3d4fd6eb813148333623a04d742b

**Comment by way2muchnoise** [comment]
Seems like #815 either broke or didn't fix it

**Comment by nikita488** [comment]
It's didn't fix it, cause i have same issue when i have 1.2.14

**Comment by raoulvdberge** [comment]
This still has to be backported to 1.11
