### ISSUE TITLE
Latest build not 1.10.2 compatible?

### ISSUE THREAD

**Issue by TheVanoq** [raoulvdberge/refinedstorage#825]
#### Issue description:
The latest build (1.4-818) requires Forge 13.19.1.2188 which is not available for Minecraft Version 1.10.2.
Would it be possible to make the build backwards compatible with 1.10.2?

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge:  12.18.3.2202
- Refined Storage: 1.4-818

**Comment by raoulvdberge** [comment]
1) The 1.4 series is for Minecraft 1.11
2) Use the 1.2.x series for 1.10.2 builds
3) The latest 1.10.2 build is on Curseforge
4) The builds from Bintray don't work in a MC environment yet.
