### ISSUE TITLE
[1.11] 1.3.5 - Server sided crash (log indicates something to do with autocrafting)

### ISSUE THREAD

**Issue by Minizbot2012** [raoulvdberge/refinedstorage#827]
#### Issue description:
Autocrafting - server crash
#### What happens:
Server side crash - caused by attempting to auto craft oredictionary recipes
#### What you expected to happen:
Server not to crash
#### Steps to reproduce:
I don't have much here, if you want the modpack I am able to provide the multimc instance, this is a world we've been working on for the past few weeks (this is a legit survival world) I can also provide the world that causes the crash.

EDIT:
Further experimenting with this seems to link this to oredict crafting greenhouse glass from actually additions.

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.11
- Forge: 1.11-13.19.1.2199
- Refined Storage: 1.3.5

Does this issue occur on a server? [yes/no]
yes

#### If a (crash)log is relevant for this issue, link it here:
https://gist.github.com/Minizbot2012/3a4d5de9e85623a4bc8caaea6fed6753

**Comment by raoulvdberge** [comment]
@way2muchnoise isn't this already fixed?

**Comment by way2muchnoise** [comment]
Maybe? Could be. Dunno really, have done a lot of work on autocrafting.

**Comment by raoulvdberge** [comment]
I'll close this, if the issue persists with recent versions, please reopen.
