### ISSUE TITLE
Fluid storage block going into negative capacity causing FPS lag

### ISSUE THREAD

**Issue by wathman** [raoulvdberge/refinedstorage#828]
#### Issue description: 
Fluid storage block going into negative capacity when filled then drained with water. 

#### What happens:
If reprioritizing water from fluid storage block to fluid disk storage, it drains the fluid storage block and keeps draining into negative capacity. Was causing bad fps lag and found the source was the fluid storage block showing that it was filled negatively with water. 
#### What you expected to happen:
When drained, fluid storage block should have a capacity of 0 and stop. 
#### Steps to reproduce:
1.Add fluid storage block to network and fill with water completely
2.Add fluid storage disk larger than fluid storage block
3.reprioritize water to disk, and drain the block
...
Only caused this to happen once, and did not want to try to reproduce again

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge:
- Refined Storage:
Version included with Direwolf20 1.10 pack 1.3.1

Does this issue occur on a server? [yes/no]

#### If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here]

**Comment by raoulvdberge** [comment]
Nope, gimme your RS version or I'll close. I don't want pack versions.

**Comment by wathman** [comment]
1.2.14

**Comment by raoulvdberge** [comment]
How did you drain the fluid block?

**Comment by wathman** [comment]
I placed a fluid disk that was larger into my disk drive also on the same network as the fluid block, and set the priority for water higher there

**Comment by raoulvdberge** [comment]
> I placed a fluid disk that was larger into my disk drive also on the same network as the fluid block, and set the priority for water higher there

That doesn't drain a fluid block... Can you be more clear in your steps to reproduce because I can't reproduce this.

**Comment by wathman** [comment]
I just went into a creative world and tried to recreate as well, couldn't get it to happen again either, so maybe something changed within my mod pack.  Something odd did happen in the past though as I still have the oddly behaving fluid block:
![2017-01-12_21 08 44](https://cloud.githubusercontent.com/assets/24937173/21916047/bc2ef944-d90b-11e6-8703-99f83e0cfc2e.png)

when it happened, I was able to fill it up again with water and as it shows it has just over 95 buckets and is 149% full. 
Since I can't get it to happen again, it may be best to just close
