### ISSUE TITLE
Shortcut/Hotkey for focusing search in grids

### ISSUE THREAD

**Issue by shabble** [raoulvdberge/refinedstorage#829]
#### Issue description:
Feature request: a keyboard shortcut for selecting search/filter mode in grids.

I'm calling it a request rather than a bug that R/U is swallowed on autoselect since I seem to recall in the past it didn't and was annoying for some people, and might have been changed intentionally. 

#### What happens:
A grid with search in autofocus mode (both JEI & non-JEI) will also eat certain (NEI? JEI?) hotkeys such as R and U for showing recipes/uses for the item under cursor.

Using search without autoselect means clicking in search bar to focus it first.

#### What you expected to happen:
Some non-mouse way to focus (and maybe defocus?) search field in grid UIs.

Since if you're searching you're going to need the keyboard anyway, a shortcut key/combo would be convenient.

Either a fixed binding like Tab or something bindable through usual MC methods, complexity & usability permitting.

#### Steps to reproduce:
1. open grid (with search set to not autoselect)
2. look longingly at search field
3. mash random keys
4. give up and click
5. searching occurs...

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge: 12.18.3.2185
- Refined Storage: 1.2.14 (SF3 pack via Curse)

Does this issue occur on a server? [yes/no]

Presumably.  Tested singleplayer only.

**Comment by raoulvdberge** [comment]
Which shortcut are you proposing?

**Comment by shabble** [comment]
My initial suggestion would be TAB, but I can't remember if that shows online player list even inside GUIs for MP. I'm almost exclusively singleplayer atm so not sure. Basically anything that isn't [A-Za-z] and isn't going to clash with other contextual keys (JEI, NEI, etc) would be fine with me.

Also not sure on technical limitations of what key/combos can be used (iirc why virtually everything uses [sneak]+X), but Ctrl-S or something would also work.

Thinking about it more, ideally it would work like TAB to change focus in other software - so it cycles through the controllable options, in this case probably toggle normal -> search, search -> not-search (so you can search for a thing, and then deactivate so 'R' or 'U' give you usage/recipe)

**Comment by raoulvdberge** [comment]
There you go.
