### ISSUE TITLE
Object : Translation Refined Storage French fr_FR.lang

### ISSUE THREAD

**Issue by Leventovitch** [raoulvdberge/refinedstorage#83]
Maybe it can help.

//pastebin.com/embed_js/grpJH5Ki

[fr_FR.zip](https://github.com/raoulvdberge/refinedstorage/files/292323/fr_FR.zip)

**Comment by raoulvdberge** [comment]
Merci! I'll be adding your translation to the next version!

**Comment by raoulvdberge** [comment]
Added, thank you. Also added you to the CREDITS.md file.

**Comment by Leventovitch** [comment]
here is an update.

//pastebin.com/embed_js/AR0NinCY

[fr_FR.zip](https://github.com/raoulvdberge/refinedstorage/files/645841/fr_FR.zip)

**Comment by raoulvdberge** [comment]
Your translation is not up to date with the current translation keys.

https://github.com/raoulvdberge/refinedstorage/blob/mc1.10/src/main/resources/assets/refinedstorage/lang/en_US.lang

For example, latest has:
```
block.refinedstorage:solderer.tooltip.0=Needs to be connected with a %s
block.refinedstorage:solderer.tooltip.1=by placing it adjacent to it or
block.refinedstorage:solderer.tooltip.2=by connecting it with %s.
```
Yours just has:
```
block.refinedstorage:solderer.tooltip=À besoin d\'être connecté avec un(e) %s en le plaçant adjacent à ou en le connectant avec %s.
```

**Comment by Leventovitch** [comment]
Sorry, my version was too old.

This one is up to date with the translation keys you've send me.

//pastebin.com/embed_js/AR0NinCY

[fr_FR.zip](https://github.com/raoulvdberge/refinedstorage/files/646868/fr_FR.zip)

**Comment by raoulvdberge** [comment]
Thank you very much @Leventovitch!

The updated translation will be included starting from these RS versions:
- MC1.10.2: RS 1.2.12
- MC1.11: RS 1.3.5
