### ISSUE TITLE
Network dose not take certian liquids

### ISSUE THREAD

**Issue by shivachirr** [raoulvdberge/refinedstorage#830]
#### What happens:

 hook up an importer and it dose not pull the fluid out for certain types

#### What you expected to happen: 

its post to pull out the liquid

#### Steps to reproduce:
1. get a Immersive engineering fermenter built and fill it with melons to make ethanol
2.put a importer setup on it and fluid storage
3. then it dose not pull out the ethanol

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge: 12.18.3.2202
- Refined Storage: 1.2.16

Does this issue occur on a server? no

**Comment by way2muchnoise** [comment]
Got some screenshots of your importer? And RS setup, any blacklists, whitelists, accidental redstone setting.  Also iirc the fermenter can only extract on a certain block.

**Comment by shivachirr** [comment]
![2017-01-06_08 04 40](https://cloud.githubusercontent.com/assets/9361172/21718666/f4644aa0-d3e6-11e6-8b33-159196e1233a.png)
![2017-01-06_08 04 46](https://cloud.githubusercontent.com/assets/9361172/21718667/f464c87c-d3e6-11e6-9cc4-5a2e2ee2ef07.png)
![2017-01-06_08 04 49](https://cloud.githubusercontent.com/assets/9361172/21718668/f4668d06-d3e6-11e6-9fe6-2694b59751dd.png)

**Comment by shivachirr** [comment]
all things are setup properly

**Comment by shivachirr** [comment]
also i relize that the importer is set to items in the screen shot i just put it back down and forgot the fix it also i t appear biodeisle form IE dose not work either

**Comment by shivachirr** [comment]
but it started to take it once i put a fluid grid on weri the bio deasle i mean

**Comment by shivachirr** [comment]
same for the ethanol

**Comment by way2muchnoise** [comment]
So once you had a a fluid grid it worked? That seems like an issue tho

**Comment by shivachirr** [comment]
yeah it started working once i did and made sure to put the importer with fluids and put the filter of the fulid type like i had to make sure it only could pull out ethanol but when it came to the IE plant oil it worked just fine not need for a fluid grid or setting the filter on the importer

**Comment by raoulvdberge** [comment]
So I assume it works fine now?

**Comment by shivachirr** [comment]
not fully it works but still buggy becuse you require a fluid grid and to filter the excat liquid in the importer for it ro work

**Comment by raoulvdberge** [comment]
are you 100% sure your importer was in fluid mode?

**Comment by shivachirr** [comment]
yes and eveyr thing is right because i used the same setup just the controller and fluid storage and the importer on IE plant oil and it worked fine there but when it came to the ethanol and biodiesel no

**Comment by raoulvdberge** [comment]
i'm guessing this is related to #370

**Comment by shivachirr** [comment]
not really i think because that was on a server im on a sp world and i have a massive RS systemand everything worked fine till this

**Comment by shivachirr** [comment]
and what is shown in the pic is a separate system to fill the fluid storage up before putting it in place of the main system
