### ISSUE TITLE
Wireless Import cable, or bug?

### ISSUE THREAD

**Issue by DaveJK** [raoulvdberge/refinedstorage#831]
**Issue description:** Wireless Importer?

**What happens:**  I place down a Solderer next to my Controller, with Disk Drive located above controller and one 4k Storage disk, and throw gold in the solderer for Printed Processors. I was getting ready for Autocrafting so I had an Importer just sitting on the side of the solderer ahead of time. It's connected to nothing on the output side, only the Solderer on the input side. Gold started disappearing 4 Ingots at a time per Printed Processor operation with 4 speed upgrades inside the Solderer. 3 Gold Ingots would transfer back into the 4k Storage Disk while 1 Ingot would turn into Printed Processor.

**What you expected to happen:** No import operations until the output side of the Importer is connected to a Refined Storage block via cable.

**Version (Make sure you are on the latest version before reporting):**

- Minecraft: 1.10.2
- Forge: 12.18.3.2185
- Refined Storage: 1.2.14

Does this issue occur on a server? [yes/no] unknown

**Comment by way2muchnoise** [comment]
Output for the solder is on the bottom. You won't be able to import anything even if it had finished. Also every block is basically a cable (node) in RS so "magic" importer is more like a feature as a bug.
