### ISSUE TITLE
[Suggestion] Various Solderer Recipe Rearrangements.

### ISSUE THREAD

**Issue by VT-14** [raoulvdberge/refinedstorage#832]
The Solderer supports Shift clicking fairly nicely, except some components can be inserted into multiple slots.  This causes some minor annoyances with manual use or simple automation (like hoppers).  A few recipes could be rearranged to remove the more common one(s), or changes to many recipes to remove all but one of them.

Current Conflicts as of Refined Storage 1.3.5:
Redstone (All Processors and All Upgrades)
Crafting Table (Crafting Grid and Crafting Upgrade)
Basic Processor (Storage Blocks and Interface)
Buckets (Fluid Interface, Fluid Grid) - Impossible to fix without changing the ingredients of the Fluid Interface

Possible Change 1:  Minor, only fixes Redstone and optionally Crafting Tables.
All Upgrades: 
A) Blank Upgrade on top, Redstone in the middle, and special material on the bottom.  Solves both Redstone and the Crafting Table conflicts.
B) Special Material on top, Redstone in the middle, and the blank Upgrade on the bottom.  This would be similar to crafting Processors, but would leave the Crafting Table conflict in.

Possible Change 2: Major (I think this removes all conflicts except the Fluid Interface)
Top Slot: Special Materials (Chests, Crafting Tables, Ender Pearls, Sugar, buckets, etc.), Printed Processors, Importer, Storage Parts
Middle Slot: Redstone, All Processors, Diamond, Gold, Iron, silicon.  Interface for Fluid Interface.
Bottom Slot: Machine Casings, Grids, blank Upgrades, Exporter, Printed Silicon.  Bucket for Fluid Interface.

**Comment by raoulvdberge** [comment]
Thanks for the good report, listing all conflicts. This made it easier for me to fix.

Can you double check these changes for me:
- the redstone for upgrades is now in the middle slot
- the crafting table for the crafting grid is moved to the top slot, to stop conflict with upgrades
- pattern in pattern grid is moved to the top slot as well, for consistency
- bucket in fluid grid is moved to the top slot as well, for consistency
- interface processor is now on top, to stop the conflict with the storage blocks
- fluid interface now takes a bucket, redstone in the middle, and an interface on the bottom.

**Comment by VT-14** [comment]
Looks good.  The only change I would still suggest is Chest in Disk Drive should be moved to the top slot as well, for consistency.  ~line 290

**Comment by raoulvdberge** [comment]
Fixed, thanks.

**Comment by VT-14** [comment]
Oh, wait. whoops.  With that rearrangement, Machine Casings can go in either the middle or bottom (Storage Blocks vs Grid/Disk Drive)

**Comment by VT-14** [comment]
I think I found the places to change the recipes.  Pull Requests #840 and #841.

I've only taken introductory programming classes and am not sure how to test to make sure that won't mess something up, so you will probably want to double and triple check those pull requests.
