### ISSUE TITLE
Can't autocraft Mekanism Advanced Solar Generator

### ISSUE THREAD

**Issue by Jomik** [raoulvdberge/refinedstorage#834]
#### Issue description:
I am unable to autocraft Mekanism's Advanced Solar Generator, even though all the recipes are set up.
#### What happens:
Nothing, RS claims that the normal solar generators are missing, at that there is no recipe for them, though their clearly is.
#### What you expected to happen:
I expected it to craft the generator, and recognize that the 4 solar generators are there.
#### Steps to reproduce:
1. Make recipe for every product required for all steps of the generator.
2. Try to craft the advanced generator.
3. Note it claims that it is missing the earlier tier.
...

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge: 12.18.3.2185
- Refined Storage: refinedstorage-1.2.16

Does this issue occur on a server? [yes/no]
Yes

#### Images
[![https://gyazo.com/2e92bea0ca1752455ed51bc1b8ff0a65](https://i.gyazo.com/2e92bea0ca1752455ed51bc1b8ff0a65.png)](https://gyazo.com/2e92bea0ca1752455ed51bc1b8ff0a65)
[![https://gyazo.com/a39c0780c6380f083d7d73f467c0f622](https://i.gyazo.com/a39c0780c6380f083d7d73f467c0f622.png)](https://gyazo.com/a39c0780c6380f083d7d73f467c0f622)
[![https://gyazo.com/ac51756e94bf124cad6d6769171efb92](https://i.gyazo.com/ac51756e94bf124cad6d6769171efb92.png)](https://gyazo.com/ac51756e94bf124cad6d6769171efb92)

Tried to craft the solar generators directly, which works through autocrafting.
[![https://gyazo.com/360d154efaa776a47d118b6f0348e9ef](https://i.gyazo.com/360d154efaa776a47d118b6f0348e9ef.png)](https://gyazo.com/360d154efaa776a47d118b6f0348e9ef)
[![https://gyazo.com/fd37c127a866d7aafb63452788b3f6a2](https://i.gyazo.com/fd37c127a866d7aafb63452788b3f6a2.png)](https://gyazo.com/fd37c127a866d7aafb63452788b3f6a2)
[![https://gyazo.com/ad3f75c2162d7a3a472ec22a38f2b3f1](https://i.gyazo.com/ad3f75c2162d7a3a472ec22a38f2b3f1.png)](https://gyazo.com/ad3f75c2162d7a3a472ec22a38f2b3f1)
[![https://gyazo.com/4682383daf2a4cfe2cc83809e88574fc](https://i.gyazo.com/4682383daf2a4cfe2cc83809e88574fc.png)](https://gyazo.com/4682383daf2a4cfe2cc83809e88574fc)

**Comment by Jomik** [comment]
I'm not sure if this is related. But there is also trouble getting JEI to fill in some Mekanism items. I mainly notice it with their machines, and the energy tablets. I guess the solar generators are probably the same case. May that be the reason?

**Comment by PWTordenskiold** [comment]
Last tested on 1.2.12(MC1.10.2): the same with all Mekanism crafting operations that require previous machines. AE2 also struggled with it in 1.7.10 if the required machine was already in the system, however if the required machine was constructed in the same crafting job it worked. Assumed it had to do with Mekanism's ownership on blocks back then.

**Comment by PWTordenskiold** [comment]
Last tested on 1.2.12(MC 1.10.2) - This is/was the case for all Mekanism machines that require a lower-tier machine, with owner tag, in its crafting recipe. 
AE2 struggled with it in 1.7.10 as well. Failed to craft if there was already a required machine in the system, however if it was all crafted in one crafting job it worked fine. Suspected back then it was related to the owner tag(?).

**Comment by way2muchnoise** [comment]
Mekanism save a lot of crap into the NBT data. Could you try and see if there is any weird tags set in the recipes? [Actually Additions](https://minecraft.curseforge.com/projects/actually-additions) adds a shift+ctrl advanced tooltip with the tags when hovering a stack.

**Comment by Jomik** [comment]
Sadly, I am unable to add Actually Additions to the modpack.
However, the solar generators (tier 1) are freshly crafted through RS. I didn't take them to my inventory, or anything. So there shouldn't be any difference between what you see and I do.
I think the only tags they set are stuff like, rf storage, owner, security information.
What do you mean with "weird" tag?

**Comment by way2muchnoise** [comment]
You likely transferred them from JEI and that might include some NBT tags that are bogus or different from when you actually craft them. I'll just try this in my own env at some point when I have the time.

**Comment by Jomik** [comment]
As I wrote, the tier 1 solar generators are auto crafted by RS, using a pattern. So I didn't touch them.

**Comment by Jomik** [comment]
Amazing 😄

**Comment by bhechinger** [comment]
Has this returned? With 1.6.15 (1.12.2) I'm having this very same issue trying to autocraft the various tiers of Fluid Tanks.

**Comment by Darkere** [comment]
There is currently no intention of introducing a fix for this. 

Replace the problematic items in the recipe with actually crafted items to make it work.

**Comment by bhechinger** [comment]
What do you mean by an actually crafted item?

**Comment by Darkere** [comment]
For each recipe that requires a fluid tank, craft a fluid tank and make the pattern use that tank instead of the complete recipe from JEI.

**Comment by bhechinger** [comment]
That doesn't help.

**Comment by Darkere** [comment]
Like this: https://gfycat.com/CooperativeSophisticatedBittern

**Comment by bhechinger** [comment]
Yes, that's exactly what I did, it's still not working.

**Comment by Darkere** [comment]
There could be other mods interfering with it. Try turning off oredict if you have that on. Make sure the tank has never been in use. 

That's all the ideas I have. After that, you would have to look at the actual NBT data to see what might be up.

**Comment by bhechinger** [comment]
Turning off oredict didn't help. Thanks for trying though!
