### ISSUE TITLE
Crash on dedicated server

### ISSUE THREAD

**Issue by carstorm** [raoulvdberge/refinedstorage#835]
#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge: 12.18.3.2185
- Refined Storage: 1.2.16

Does this issue occur on a server? Yes, only on dedicated server.

#### If a (crash)log is relevant for this issue, link it here:

http://pastebin.com/f143bmw5

**Comment by raoulvdberge** [comment]
I can't reproduce this. The crash report doesn't make sense either. Can you reproduce this bug with just RS installed?

**Comment by carstorm** [comment]
Can't reproduce with just RS, will hold off updating it since old version worked fine.

**Comment by way2muchnoise** [comment]
Real odd, maybe try re-downloading the mod? Might be some weird issue.

**Comment by raoulvdberge** [comment]
I don't think this is an RS issue, someone is modifying existing Forge classes...

**Comment by carstorm** [comment]
The crash gave a world coordinate so I went there and discovered its a importer connect to a "stone separator" from the "calculator" mod. Here is an image on the working, in production server:
![image](https://cloud.githubusercontent.com/assets/7497589/21757514/a4bd847e-d5f5-11e6-98da-3dcf060685f3.png)

**Comment by raoulvdberge** [comment]
The crash says:
```
java.lang.AbstractMethodError
    at com.raoulvdberge.refinedstorage.tile.TileImporter.updateNode(TileImporter.java:75)
```
Which points at this line:
```java
ItemStack stack = handler.getStackInSlot(currentSlot);
```
The `java.lang.AbstractMethodError` either means:
- the method `IItemHandler#getStackInSlot` doesn't exist
- the method takes different arguments

Either way, that doesn't make sense.

**Comment by xilcoy** [comment]
FYI in case somebody else encounters this...

Someone on my server just hit this too.
I upgraded Sonar-Core (used by Calculator). Guessing this is the commit that fixed it: https://github.com/SonarSonic/Sonar-Core/commit/6f085a263223a4efc84a0d29018af996494d8d0a
