### ISSUE TITLE
Feature Request - Stack Upgrade on Constructor / Destructor when in Drop Block (item) mode.

### ISSUE THREAD

**Issue by EvilNotion** [raoulvdberge/refinedstorage#836]
It would be great if the Constructor could drop stacks of items if a Stack upgrade was put into it.  When set to redstone mode, a simple button push could dispense a stack of Ender Pearls, for example.  Mixing button types (pulse length) and Speed upgrades could give different results (perhaps you want 2 stacks dispensed on a single button push).

On the same note, a Destructor picking up stacks (like a hopper) would be great too.

**Comment by raoulvdberge** [comment]
Destructor can already pick up stacks.
