### ISSUE TITLE
[1.10.2] Mekanism Bins are unable to get removed from RSS

### ISSUE THREAD

**Issue by hugeblank** [raoulvdberge/refinedstorage#839]
#### Issue description:
I run a... you get it. Some of the users reported an issue with another mod being incompatible with your mod, Mekanism. There's these blocks called 'bins' in the mod that allow you to have bulk storage, with easy access. 
#### What happens:
The players went and crafted a few of the basic ones, and couldn't get them out of the storage system. A few other players have done some testing, and said that this occurs for all the types of bins.
#### What you expected to happen:
Bins get taken out of storage system
#### Steps to reproduce:
1. Install mekanism and refined storage
2. craft a bin (or cheat it in), just make sure it gets into the storage system.
3. Attempt to take it out
4. Fail
5. Be sad... and bin-less

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge: 2185
- Refined Storage: 1.2.14
- Mekanism Version: 9.2.1.295
Does this issue occur on a server? 
Yes, however I don't think that is relevant.

**Comment by raoulvdberge** [comment]
This is a mekanism issue, but sadly the author isn't doing anything about it

**Comment by hugeblank** [comment]
Alright, I'll poke the author :P
Thank you!

**Comment by Nuinethir** [comment]
If I remember correctly, bins only import from the top and export from the bottom, so maybe try using import/export interfaces?

I saw he added some larger ones since 1.7.10, but back then I asked him to consider import/export from multiple sides and he said he wouldn't do it. Needless to say, I don't use them anymore. MFR DSUs and QuantumStorage seems to fit the bill nicely.

**Comment by hugeblank** [comment]
@Nuinethir haha, you're misunderstanding the issue. the issue is that if you have a bin inside the storage system, like literally inside a drive, you cannot grab it out of the grid.
