### ISSUE TITLE
Disk priority when removing items from a disk drive is backward (FIFO vs LIFO)

### ISSUE THREAD

**Issue by OhiraKyou** [raoulvdberge/refinedstorage#84]
When items are stored in a disk drive, they are added from left to right, top to bottom. And, when items are removed, they are also removed left to right; the first in is the first out. As such, it is entirely possible to have, for example, one disk at 219/1000 and another at 564/1000, even when they are both filled with a single type of item.

In addition, stacks aren't split between disks. For example, adding a stack of coal to a 1K disk when it is at 999/1000 capacity will skip the first disk, leaving it at 999/1000, and move to the next, filling it to 64/1000.

Currently, 64K disks have more space than I could practically imagine filling (if you actually need that many items, you should be consuming them too), and 16K disks are not far behind. This makes the most significant advantage to using disks (which require an extra diamond due to the drive, regardless of the quality of disks used used) over blocks their ability to be dismantled and upgraded. And the above two situations add extra management to removing an otherwise clean disk for upgrading.

**Comment by raoulvdberge** [comment]
> As such, it is entirely possible to have, for example, one disk at 219/1000 and another at 564/1000, even when they are both filled with a single type of item.

Why is this an issue?

> In addition, stacks aren't split between disks. For example, adding a stack of coal to a 1K disk when it is at 999/1000 capacity will skip the first disk, leaving it at 999/1000, and move to the next, filling it to 64/1000.

I'm going to look into this, thanks.

> This makes the most significant advantage to using disks (which require an extra diamond due to the drive, regardless of the quality of disks used used) over blocks their ability to be dismantled and upgraded. And the above two situations add extra management to removing an otherwise clean disk for upgrading.

I'm not able to parse this. What exactly is the suggestion / issue? Do you want storage blocks to be upgradeable?

**Comment by OhiraKyou** [comment]
Let us assume there are two 1K disks, both dedicated to coal (as filtering separate disks in the same drive is impossible). The first, which is in the top leftmost slot, has 1000/1000. The second, beside it, has 500/1000. Then, we use 500 coal. Now, we have two 500/1000 disks instead of one 1000/1000 disk and one empty disk beside it. So, instead of having an empty disk in the drive that we can take out to use elsewhere or upgrade, we have to manually clean the disk out first. If disks are only good for sitting in a drive, they might as well be blocks.

So, assuming players will want to use disks as reusable storage expansions, a last in, first out order is more user friendly than a first in, first out order, which leaves more fragmentation in drives. Manually defragging disks to empty them out is awkward.

On a related note, being able to dedicate specific disks in a single drive to specific items would make them much more useful.

**Comment by raoulvdberge** [comment]
I'll make it so the storage disk with highest amount of items gets priority in drive.

The drive will always support 1 filter for all 8 storage disks, for balancing. It already saves a lot of space.

**Comment by raoulvdberge** [comment]
Closing this for #86 and #85

**Comment by OhiraKyou** [comment]
> It already saves a lot of space.

This is where I strongly disagree and a point I was trying to make in the last paragraph of the opening post. A single 64K disk is more storage space than I could possibly imagine using for any purpose, **because anyone who needs 64K items should also need to consume those items**. In other words, there's no reason to have a huge amount of items that you do not intend to use, which means your storage should never be close to full at any given time.

What that ultimately means is that there is absolutely no functional difference between a 64K (or even a 16K) block and a 64K or 16K disk. They both take exactly the same amount of space, and both, even at 16K, have more storage space that anyone could use without storing items they have no intention of consuming. For example, anyone who has build the infrastructure to farm and store 1K wood should also have a reason to consume that much wood, meaning the amount in storage should never actually reach 1K.

And, if you somehow manage to obtain more than 64K items, you should have enough resources to build a single extra 64K block, which should be more than enough to sustain even the most ridiculously over the top playthrough possible. There's no way that a single extra block in the most extreme case is worth balancing a system around.

After a playthrough with a friend, every item we ever collected, including enough wood and coal to power huge generators literally for weeks, only ever amounted to around 5K items, all stored in single a 64K disk with 92%+ capacity remaining. The large quantity of ores and other resources we collected, _we actually used_. Even with a 16K disk, we'd still have around 69% capacity remaining.

So, I fundamentally and strongly disagree that disks save any space at all. Therefore, given that the space saving argument is invalid, the real reason to use disks, which always require a diamond to craft over blocks due to needing a drive, is that they can be filled with specific materials and taken elsewhere. However, unless you build a drive for each set of items, which is exactly the same as building a block for each set instead since they have the same filtering capabilities built in, with the addition of a diamond per drive, this process is unwieldy. 

As such, drives should support this singular advantage of modularity and portability by making the filling of disks with specific items easier. Otherwise, there is absolutely no reason to use them over blocks.

**Comment by raoulvdberge** [comment]
I see that you really care about this issue, so I'll take a look at having a filter per disk.
