### ISSUE TITLE
Importer/Destructor treat empty whitelist as empty blacklist

### ISSUE THREAD

**Issue by charlesbevans** [raoulvdberge/refinedstorage#842]
Sky Factory 3 v3.0.1 SSP, RS 1.2.14 (fix not mentioned in newer changelogs)
When I set the importer or destructor to an empty whitelist (when setting up crafting recipes) they take anything presented. Once I add an item to the filter they only take the item added.

**Comment by way2muchnoise** [comment]
This isn't really a bug, more of a feature. Anyway it can't really be changed any more as it would break all existing setups.
