### ISSUE TITLE
Items vanishing after using the disk manipulator

### ISSUE THREAD

**Issue by KaiKamakasi** [raoulvdberge/refinedstorage#843]
Issue description: items 'vanish' after using the disk manipulator

What happens: twice now i have used a disk manipulator to consolidate my items only to find that upon putting the disks back i've lost thousands of items in the process despite the disks claiming to be at half or full capacity

What you expected to happen: for my items to consolidate into various storage rather than have 6 bays full of 64k drives (using external storage bus and storage draws)

Steps to reproduce:
1. have well established RS network
2. external storage
3. place disks in disk manipulator
4. put disks back into system

Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge: 12.18.3.2185 
- Refined Storage: 1.2.14
- Sky Factory 3.01

Does this issue occur on a server? [yes]

If a (crash)log is relevant for this issue, link it here:N/A

[pastebin/gist/etc link here]

**Comment by way2muchnoise** [comment]
Could you make some video of sorts when this is happening? Cause I never had this happen and have no clue how to reproduce it.

**Comment by darthsandmann** [comment]
Same problem here..
All the mods 1.10.2 latest version

**Comment by jk1895** [comment]
I could swear to have the same issue. Storage drawers with controller were involved.

**Comment by InusualZ** [comment]
We haven't been able to reproduce the bug. So please if you are able to reproduce it, record yourself so we can debug it and fix it

**Comment by KaiKamakasi** [comment]
while i'm unsure i've been able to recreate my exact issue, i did notice something else which may be related, i have several 16k drives which are full, when placed into the left hand slot they just instantly jump over to the right hand slot and no items appear on them, which admittedly i didn't record putting them in to my test system but here are some screenshots, the attached video however shows the 3 drives skipping over and also that i have several half full and even completely empty 64k drives in my system, i'll continue trying to recreate this issue exactly however literally all i did was remove the 16k drives, made sure there was space for the items elsewhere and placed them in the manipulator.

video link: https://youtu.be/vfxS0-g2hdc

![2017-01-08_17 24 29](https://cloud.githubusercontent.com/assets/13232285/21751960/a7cb0c3c-d5c7-11e6-86fa-0f073809ab73.png)
![2017-01-08_17 24 44](https://cloud.githubusercontent.com/assets/13232285/21751962/ab4a7b72-d5c7-11e6-8b4e-c0b1ead49009.png)
![2017-01-08_17 25 00](https://cloud.githubusercontent.com/assets/13232285/21751963/ad27a032-d5c7-11e6-92c2-b3c3389f8519.png)
![2017-01-08_17 25 58](https://cloud.githubusercontent.com/assets/13232285/21751964/af2ace5e-d5c7-11e6-9cd1-4736dcb4813f.png)
![2017-01-08_17 26 02](https://cloud.githubusercontent.com/assets/13232285/21751965/b01d4a80-d5c7-11e6-8389-33d124d15266.png)
![2017-01-08_17 26 08](https://cloud.githubusercontent.com/assets/13232285/21751966/b0e3d902-d5c7-11e6-985a-50959e473717.png)
![2017-01-08_17 26 12](https://cloud.githubusercontent.com/assets/13232285/21751967/b1c6bb3c-d5c7-11e6-95e1-9d62cdee8734.png)

**Comment by himdo** [comment]
A similar thing happened to me when i broke the disk drive then replaced it with the same disks. I can send you my save file that has the broken disk drives. this also accrued on a server and when moving the save to single player the bug was still there and didn't fix anything. the only config i changed was that it doesn't use power. also when trying to export items that i knew where in that system (oak logs) it doesn't export the items. the client was using optifine how ever the server did not have it.
something that could have caused it was the server was running spongeForge (https://www.spongepowered.org/) however I'm not sure if that is what caused it.

Save: https://dl.dropboxusercontent.com/u/42746351/Broken%20Save.zip

**Comment by raoulvdberge** [comment]
This is a Forge bug.
