### ISSUE TITLE
Refined storage auto-crafting destruction core

### ISSUE THREAD

**Issue by Krucked1** [raoulvdberge/refinedstorage#844]
#### Issue description:
3.0.4 ver. i am attempting auto craft destruction core i was able to auto craft all the other main parts basic processor and printed basic processor -printed silicon
doing them all alone works fine but if i do a destruction core makes all the things but stops on destruction core says item processing 1x Destruction core in red hover over it says machines in process but it's just basic processor and quartz a crafting recipe and all items it craft prior are in the system
#### What happens:
don't finish crafting the destruction core
#### What you expected to happen:
destruction core to apear in my refined storage system
#### Steps to reproduce:
1.used the alloy smelter 
mode set all smelting

2.Pattern -basic processor slot 6
pattern - destruction core slot 7
in the crafter facing the solderer

3.pattern- basic processor
pattern- printed silicon
in crafter facing the alloy smelter 
...

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge:
- Refined Storage: Refined storage 1.2.16

Does this issue occur on a server? [yes/no]
don't know
#### If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here]

**Comment by VT-14** [comment]
Machine Crafting -> Processing Pattern Encoder.
Vanilla 3x3 crafting -> Pattern Grid.

**Comment by Krucked1** [comment]
Oh okay i see it's working now thanks !
