### ISSUE TITLE
[REQ] RS/RF export bus.

### ISSUE THREAD

**Issue by Rusketh** [raoulvdberge/refinedstorage#848]
I think we should get an export bus for RS/RF energy with an interface where you can set the RS/tick that it will output. This would be really useful as it would reduce the amount of cabling you would have to do, you could have 1 cable for items/liquids and energy. Alternatively I was thinking we could get an upgrade card that would allow existing importers/exports/external storage buses, to export RS with an 3 different tiers for varied RS/tick output. I personalty would find a lot of uses for both, sometimes you may wish to export energy into a block that has no inventory (hence the exporter) and in others you may want to pipe items or fluids in from one side but you also need energy pumped into the same block face.

**Comment by raoulvdberge** [comment]
That is what the reader/writers will do. 1.11 only. No I won't backport them to 1.10.
