### ISSUE TITLE
Cannot connect a disk drive or external storage to a controller with a cable

### ISSUE THREAD

**Issue by KodiakJak** [raoulvdberge/refinedstorage#850]
#### Steps to reproduce:
1. Place controller, supply power
2. Place disk drive 2 blocks away, put 1K drive into disk drive
3. Connect cable from controller to disk drive
4. Disk drive does not light up or connect to network
5. Same issue with external storage block
...

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Skyfactory 3.0.4 (with refined storage manually updated to latest release)
- Forge: 12.18.3.2202
- Refined Storage: refinedstorage-1.2.16.jar

#### Screenshot - http://imgur.com/a/kuzwG

Does this issue occur on a server? [yes/no] dunno

#### If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here]

**Comment by KodiakJak** [comment]
**Update**

If I quit SkyFactory completely to the desktop and restart, it is now working.

**Comment by maiconimortal** [comment]
I playing the modpack FTB Infinity Lite 1.10 and I need the compatibility beetwen refined storage and the network conduit by Ender IO.

**Comment by InusualZ** [comment]
This is known bug, an is fixed in 1.11. The authors of RS are thinking on porting it to 1.10 or not.

**Comment by raoulvdberge** [comment]
No, this is another bug.
