### ISSUE TITLE
button to request missing items in crafting grid

### ISSUE THREAD

**Issue by tod** [raoulvdberge/refinedstorage#854]
#### Feature request description:

Whenever you want to craft a final product, you either have to make a full pattern card or go and request each component be crafted individually. 

I'd like to be able to go into jei and use the + button and have ghost items (highlighted somehow) appear in the crafting grid when the actual item isn't available. I'd then also want a button that will request any of those missing items be crafted and auto populated into the grid when they're available. The Logistics Pipes request table has this feature with the ~ button. I know that table works different with the inventory and only ghost items in the grid, but I  would think it would be possible to do in the RS crafting grid.

**Comment by raoulvdberge** [comment]
I'm kinda meh to this idea

**Comment by VT-14** [comment]
How about a ghost item in the crafting grid that you can use to initiate auto-crafting (possibly with Shift and/or Control click)?  Ideally once crafting is done, one item is moved to the grid to replace the ghost item crafting link.

**Comment by raoulvdberge** [comment]
I don't think this feature is worth it, sorry.
