### ISSUE TITLE
Pattern already has items, unable to create more

### ISSUE THREAD

**Issue by stevojhall** [raoulvdberge/refinedstorage#855]
#### Issue description:
cannot create Quartz Enriched Iron if you have some in network

#### What happens:
So i want x amount of quartz enriched iron but because i have some in my network it wont let me create more unless i remove them from my network, not a major issue but really annoying (esp when you need a lot but you don't have patterns for what you need them for) 

#### What you expected to happen:
to be able to create the item even if i have them in the network like i can with other items

#### Steps to reproduce:
1. create a pattern for quartz enriched iron
2. place pattern in a crafter
3. place quartz enriched iron in the network
4. check grid for quartz enriched iron pattern
...

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge: forge-12.18.3.2185
- Refined Storage: 1.2.14 (sorry i know you want latest version but could not see the specific fix in the change log and im on direwolf20 1.2.2 modpack and server population want to wait for next major stable release of the dire pack before i update so thought id report it.) 

Does this issue occur on a server? [yes/no]
yes

#### If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here]

**Comment by raoulvdberge** [comment]
ctrl+shift on the item
