### ISSUE TITLE
Autocrafter can't insert back to itself 

### ISSUE THREAD

**Issue by perryprog** [raoulvdberge/refinedstorage#857]
#### Issue description:
The Crafter cannot insert back to it's own inventory.
#### What happens:
Crash, or does not save that you selected 'Int'. (Yes, I hit apply.)
#### What you expected to happen:
The button will change to 'Int', operate as expected, and stay that way.
#### Steps to reproduce:
1. Place Crafter tier 1, 2, 3 (all of them)
2. Open each one up and click on the 'Ext' button. As the the tooltip says, you must click 'Apply' after that.
3. Each one will either crash, or not save that you clicked the button (close the GUI and open it again)

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge: Latest (not sure what it is)

If it helps, I'm using the Curse launcher with the latest version of the Direwolf20 1.10 pack.

Does this issue occur on a server? [yes/no] Don't know, I play single player.

#### If a (crash)log is relevant for this issue, link it here:

[Crash log](http://pastebin.com/xzdU6ca5)

**Comment by perryprog** [comment]
Oh, I'm stupid. You do that per recipe. Not sure what the crash is, but closing anyway.

**Comment by InusualZ** [comment]
The crafter that is crashing is from RFTools not from RS.

**Comment by perryprog** [comment]
HAHA! I posted this on the wrong repo... no wonder it asked for RS storage. Sorry a bout that.
