### ISSUE TITLE
[1.10.2] Cyanite + Steel ingot not visible in Grid through External Storage Bus (Quantum Storage)

### ISSUE THREAD

**Issue by Protheus** [raoulvdberge/refinedstorage#858]
**#### Issue description:**
I have a quantum storage unit with 10 cyanite from Extreme Reactors. The QSU is connected with an external storage. In the crafting grid the cyanite inogts (ingotCyanite) isn't visible. Same goes for railcraft steel (ingotSteel)

When I put both ingots in a vanilla chest and connect it to a external storage they become visibile in the grid.

When you put 64 cyanite ingots in the QSU it is still not visible in the crafting grid.
When you place 65 ingots in the QSU only 1 ingot is visible, the other 64 aren't
Other ingots (iron, gold, Osmium (mekanism), Yellorite (extreme reactors) are working fine.

**#### What happens:**
Cyanite (Extreme Reactor, ingotCyanite) + Steel (Railcraft, ingotSteel) isn't visible in a grid, only when you have above the 64 items and then it will only count the numbers after 64. Alle below 64 will not be visible.

Sofar only Cyanite and Steel ingots have got this issue.. no other items yet but then again I have not connected them all yet.

**#### What you expected to happen:**
When Cyanite en Steel are placed in the QSU and connected to an external storage bus it should display the total ingots and not "forget" the first 64 ingots of Cyanite and Steel

#### Steps to reproduce:
1. add 10 Cyanite ingots in a QSU
2. connect the QSU with an external Storage bus
3. setup your RF grid and view the amount of Cyanite ingots
4. it will not show you any
5. increase to 66 
6. you will see only 2 ingots in the grid and not the other 64
7. add the ingots in a chest and it will display all into correctly

**#### Version (Make sure you are on the latest version before reporting):**

- Minecraft: 1.10.2
- Forge: 2202
- Refined Storage: refinedstorage-1.2.16

**Does this issue occur on a server? [yes/no]:** '
no, SSP, dont have a server

**#### If a (crash)log is relevant for this issue, link it here:** 
- No error in console
- No crash occured

**Some screenshots to  show the issue:**

The QSU with an external storage and the ingot:
![2017-01-12_21 38 22](https://cloud.githubusercontent.com/assets/1455178/21907926/044f2b8a-d912-11e6-821e-9b31c72c4843.png)

The crafting grid with no cyanite:
![2017-01-12_21 38 04](https://cloud.githubusercontent.com/assets/1455178/21907953/1bf56178-d912-11e6-8d5f-d93b6ef55ab8.png)

The ext storage on a chest with the cyanite ingot:
![2017-01-12_21 41 16](https://cloud.githubusercontent.com/assets/1455178/21907994/4c989d0e-d912-11e6-8334-6c99bd1ec463.png)

The crafting grid, it will show the 10 cyanite ingots:
![2017-01-12_22 03 07](https://cloud.githubusercontent.com/assets/1455178/21908177/004f0ba8-d913-11e6-9070-5736b73186e9.png)

66 ingots in the QSU and the display of the crafting grid
![2017-01-12_22 00 08](https://cloud.githubusercontent.com/assets/1455178/21908075/9b049092-d912-11e6-80db-93e5ea7871e2.png)

![2017-01-12_21 59 56](https://cloud.githubusercontent.com/assets/1455178/21908078/a030c7fc-d912-11e6-8ffe-de9090f15ac1.png)

**Comment by Protheus** [comment]
Additional Info:
- It seems that in all the QSU the first 64 items are not added to the total amount.

**Screenshot:**
A QSU with 350 yellorium
![2017-01-12_22 14 18](https://cloud.githubusercontent.com/assets/1455178/21908586/90b9a5e4-d914-11e6-87cf-97b1d898fda9.png)

The grid tells me it only sees: 286
![2017-01-12_22 14 25](https://cloud.githubusercontent.com/assets/1455178/21908602/a072adb4-d914-11e6-921f-20e28d942cc1.png)

QSU with **7958** Iron
![2017-01-12_22 16 04](https://cloud.githubusercontent.com/assets/1455178/21908654/dfc6d15c-d914-11e6-9924-5f8ec06c2d07.png)

Grid (pres shift) with a total of: **7894** 
![2017-01-12_22 16 24](https://cloud.githubusercontent.com/assets/1455178/21908690/05acf1da-d915-11e6-92ce-423d63c455dc.png)

So the first 64 items are not added to the total amount displayed in the grid

**Comment by raoulvdberge** [comment]
Not a refined storage issue. The quantum storage unit itself only exposes stacks >64. File this bug to the Quantumstorage authors.
