### ISSUE TITLE
java.lang.Class.getSimpleName() performance problems on large RS networks

### ISSUE THREAD

**Issue by rYanGap** [raoulvdberge/refinedstorage#859]
#### Issue description: 
Massive performance problems with large Refined Storage networks. Profiler shows 50% or more of server ticks going to java.lang.Class.getSimpleName()

#### What happens: 
Several players on my server have large Refined Storage networks with millions of items. When their RS networks are operational, server CPU usage increases by 50% or more. Disconnecting the controllers reduces CPU proportionally. Warmroast shows java.lang.Class.getSimpleName() is the function that is causing the issues.

#### What you expected to happen: 
Larger networks would be more computationally expensive, but I did not expect that half of server resources would go to maintaining the RS network.

#### Steps to reproduce:
1. Create a RS network. Populate with millions of items (can use storage buses connected to Quantum Storage units if desired)
2. Profile with the RS network on and off. (it takes over 11000 ms for the RS network to reconnect after being disconnected!)

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge: 12.18.3.2185
- Refined Storage: 1.2.14

I'm on the newest version of FTB Infinity Lite (1.5.1)

Does this issue occur on a server? yes

If you want profiler info, let me know whether screenshots from warmroast are good enough. If you'd like something else then just let me know.

By the way, thanks for an awesome mod =D I love it! I just wish we could figure out this tps issue.

**Comment by raoulvdberge** [comment]
send us the profiling info please, anything could call Class#getSimpleName

**Comment by rYanGap** [comment]
Here's the profile information. I can't open it but I hope it yields some good info. Thanks!
[11217.zip](https://github.com/raoulvdberge/refinedstorage/files/703351/11217.zip)

**Comment by way2muchnoise** [comment]
The call `Class#getSimplename` is something the profiler will call to get the names for the methods. Although it seems like it is calling it a lot, which profiler do you you use? This might be a hardware issue, don't know if this is server you have full control over or some hosting thing, but it might be that? Also you might want to try and up RS to some later version ([See CF](https://minecraft.curseforge.com/projects/refined-storage)).

**Comment by rYanGap** [comment]
I've been using warmroast for a few years. I have full control over the server, but the mod pack that I'm using is released by the Feed the Beast folks. I would hesitate to force all of the clients to work with a custom mod pack, since I've done it in the past and it resulted in over half of people not being able to connect.

**Comment by raoulvdberge** [comment]
We can't do much with that NPS, so I'm closing this unfortunately.
