### ISSUE TITLE
Solderer Automation issue

### ISSUE THREAD

**Issue by Guybrush0** [raoulvdberge/refinedstorage#860]
when trying to automate upgrades, if redstone is inserted first it goes in the middle slot breaking the automation, is it possible to add a button to the solderer to make it respect sided input

v1.2.16, mc1.10.2

**Comment by way2muchnoise** [comment]
Update to a later version the recipes where changed a little to prevent this. See #832 #840 #841. [RS 1.7.17 is up on CF](https://minecraft.curseforge.com/projects/refined-storage/files/2367474) with that change.
