### ISSUE TITLE
Server crash caused by ItemStorageDSU

### ISSUE THREAD

**Issue by thejims** [raoulvdberge/refinedstorage#861]
#### Issue description:
Server randomly crashes, my guess is whenever the chunk in question is unloaded

#### Version (Make sure you are on the latest version before reporting):
- Modpack: InfinityLite 1.5.1
- Minecraft: 1.10.2
- Forge:         Forge{12.18.3.2202} [Minecraft Forge] (forge.jar)
- Refined Storage:         refinedstorage{1.2.14} [Refined Storage] (refinedstorage-1.2.14.jar)

Does this issue occur on a server? yes

#### If a (crash)log is relevant for this issue, link it here:
http://pastebin.com/sZ9MwC34

It is a repeating issue if you would like more crash logs

**Comment by thejims** [comment]
Also occurs with extracting items:
http://pastebin.com/rMcN7sgq

And getStored:
http://pastebin.com/Sn1cfHG7

**Comment by way2muchnoise** [comment]
likely the same as #824 and was fixed in e73ed819a991c9a5b5ee87bd4f2d9253d5e29871

**Comment by way2muchnoise** [comment]
So updating to [RS 1.2.17](https://minecraft.curseforge.com/projects/refined-storage/files/2367474) should fix it.
