### ISSUE TITLE
I have two options for crafting iron, the system only uses one

### ISSUE THREAD

**Issue by Novian3002** [raoulvdberge/refinedstorage#862]
#### Issue description:
I am playing on SkyFactory 3 and told my system to craft iron through the iron essence from mystical agriculture and/or get it by smelting iron dust from sag milled iron chunks (recipe is in a crafter pointed at a alloy smelter).

#### What happens:
The system only uses the Mystical Agriculture recipe, even if there is zero essence
 
#### What you expected to happen:
The system should use both ways of crafting/choose the one avaiable if one is out of resources

#### Steps to reproduce:
1.Build a ME System with 2 crafters, one pointed at a alloy smelter set in smelting mode, another one in "standalone" mode.
2.Put the 2 Patterns in them (1 for crafting iron out of iron essence, 1 for smelting it out of iron dust)
3.Try to request iron when there is no iron essence.
...

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge: 12.18.3.2202
- Refined Storage: 1.2.16

Does this issue occur on a server? [yes/no] 
yes

#### If a (crash)log is relevant for this issue, link it here:
---

**Comment by raoulvdberge** [comment]
Why did you close this issue?
