### ISSUE TITLE
client was coming off the production storage

### ISSUE THREAD

**Issue by tuckypetr** [raoulvdberge/refinedstorage#865]
#### Issue description: 
When you try to remove the storage of the finished table falls client. Server goes 

#### What happens: 
It is not possible from the table when you insert all components being sent to remove the item. Falls client.

#### What you expected to happen: 
removing the finished product

#### Steps to reproduce:
1.insert the component on the table
2.removing the final product from the table
3.immediate downfall client does not have a message, a message is displayed whether to go for servers selection
...

#### Version (Make sure you are on the latest version before reporting): 
- Minecraft: 1.10.2
- Forge: 1.10.2-12.18.3.2202
- Refined Storage: 1.2.17

Does this issue occur on a server? [yes]

#### If a (crash)log is relevant for this issue, link it here: 

[pastebin/gist/etc link here]

**Comment by raoulvdberge** [comment]
I don't understand what you mean.

**Comment by raoulvdberge** [comment]
Are you getting an item out of the crafting grid and it crashes?

**Comment by tuckypetr** [comment]
Crashlog not do it. Directly disconnects from the server. I enclose a link to the video.  https://ulozto.cz/!zjySWWT97Kvo/capture-sat-jan-14-14-08-40-mkv

**Comment by tuckypetr** [comment]
Here on YouTube https://youtu.be/QwdayPmLu6M

**Comment by raoulvdberge** [comment]
Can you see in your MC launcher console if there are any errors?

**Comment by tuckypetr** [comment]
The only thing that emerged is  [Netty Client IO #1/ERROR]: java.lang.NullPointerException . For this has nothing else is.

**Comment by raoulvdberge** [comment]
Yes, can you send me the full error log.

**Comment by tuckypetr** [comment]
http://pastebin.com/wGe7MYde

**Comment by tuckypetr** [comment]
http://pastebin.com/ChZaUw4G .
Here is the error found by the server http://pastebin.com/3SQq7zu8

**Comment by raoulvdberge** [comment]
Thanks for the video. I'll look into it, but I'm not sure if this is an issue caused by RS. Are you playing a pack by any chance?

**Comment by tuckypetr** [comment]
Yes, I got more mode. I try to disable them and see who hates mod.

**Comment by tuckypetr** [comment]
The single is OK. It's just doing server in multiplayer

**Comment by tuckypetr** [comment]
So it really does only on the server. tested well with Forge 1.10.2-12.18.2.2179 universal.jar.  Inserted only necessary mods JEI, classic storage, refined storage and MCmultipart 2.0.0_88.

**Comment by way2muchnoise** [comment]
classic storage doesn't seem like a necessary mod (it isn't needed to run RS). It might actually be the root of the issue.

**Comment by raoulvdberge** [comment]
Can you try to remove Classic Storage and see if the error persists?

**Comment by tuckypetr** [comment]
Ok, it looks like it's doing the classic storage. After removing it stopped.  I'll try more mods.

**Comment by ProfessorProspector** [comment]
I have no clue why that would happen, but tbh my only suggestion is to stop using Classic Storage

**Comment by tuckypetr** [comment]
Without the classic storage it works. It is interesting that if I give classic storage so it requires refined storage, but the reverse is not needed. Thanks for the help. Maybe it will help others.
