### ISSUE TITLE
Repetitive manual crafting using fluid buckets in grid fails?

### ISSUE THREAD

**Issue by shabble** [raoulvdberge/refinedstorage#866]
#### Issue description:
 
**Feature request/behaviour clarification.**

When manually crafting a recipe in a Crafting grid that involves some fluid bucket, it's not possible to quickly repeat the craft by (shift-) clicking on the output because the grid retains the empty buckets, breaking the recipe.

#### What happens:

After crafting a non-consumed bucket of fluid recipe, the full buckets in the crafting 'pattern' are replaced with empty ones, breaking the recipe for subsequent manual crafts.

#### What you expected to happen:

Not sure if this is a bug or intended behaviour, since it's relatively easy to  create a proper autocrafting pattern and stick it in a crafter, and then everything works happily, with bonus liquid storage magic. But occasionally there are some crafts you might want a few of, but without the pattern-making/inserting/crafting/maybe-removing/clearing overhead. Alternatively +-filling the recipe from JEI each time isn't the worst, but is marginally more difficult than it could be.

If this is a valid complaint, I'd probably expect the crafting grid to clear the empty buckets back into the storage, and replace them with filled ones if available. Maybe leaving them empty or just missing if there aren't enough filled ones present.

I probably wouldn't expect it to use fluid storage to autofill any buckets like true crafter autocrafting would, though I wouldnt' complain if it did :-)

#### Steps to reproduce:
1. Open crafting grid
1.5 Ensure enough filled buckets of fluid for next step.
2. prepare recipe that includes fluid but non-consumed buckets (tiny progressions cobblegen in my case)
3. shift-click output to craft and place in inv.
4. output clears because recipe is no longer valid (empty buckets where full ones should be)
...

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge:  12.18.3.2185
- Refined Storage: 1.2.14 (SF3 pack via Curse)

Does this issue occur on a server? [yes/no]

unknown. presumably yes.

#### If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here]

**Comment by raoulvdberge** [comment]
This is intended behavior.
