### ISSUE TITLE
Ability to hide items in crafting monitor

### ISSUE THREAD

**Issue by Californ1a** [raoulvdberge/refinedstorage#867]
It would be awesome if it were possible to hide specific items from the crafting monitor, specifically anything you have set up to automatically autocraft with an exporter. Maybe something similar to the grid filter, so you could have one crafting monitor set for non-automated tasks (anything you manually requested to be crafted) and another set to show the automated tasks.

**Comment by raoulvdberge** [comment]
That might be interesting yes. I'm not sure how to integrate the automated/non-automated functionality into the existing grid filter, though.

**Comment by shabble** [comment]
Might it be possible to tag certain patterns (or crafting upgrades), maybe crafting with dye colours, and then have the grid filter option to include/exclude certain pattern colours?

**Comment by raoulvdberge** [comment]
No.

**Comment by Californ1a** [comment]
I'd assume the network knows which items need to be autocrafted (when using a crafting upgrade). Would it be possible to pull that full list of (top-level) items and have a toggle button on the crafting monitor UI to hide those items along with any of the indented subitems below it/them? As long as it only hides the top-level items and not items when they are a subitem within another crafting process.

This wouldn't give nearly as much control over it as something like a grid filter could do, but it would at least allow hiding the items that are being created using a crafting upgrade.

**Comment by uecasm** [comment]
Maybe allow grid filters to be a blacklist rather than a whitelist?  Or have an advanced filter that lets you hide by typed-in name/oredict wildcard?  (Someone was asking in another issue for a way to hide all nuggets, for example.)
