### ISSUE TITLE
Bug with Curseforge...

### ISSUE THREAD

**Issue by Xiaminou** [raoulvdberge/refinedstorage#869]
This is not exactly a bug with your mod per se, but a bug with updating it through Curse's damned launcher.
Every time I update your mod with Curse Launcher it deletes itself instead of updating.
Now you might be wondering why I'm posting here and not reporting to Curse. Well I have, and as with the tons of bugs I reported to them it got ignored. I have no way of knowing if I'm the only one having this issue because their bug reporting is simply god awful. Anyway enough ranting, my point being that as a mod author they might actually listen to you.
Feel free to close this issue once you've read it.

**Comment by raoulvdberge** [comment]
I reported this myself numerous times.

**Comment by raoulvdberge** [comment]
I'll close this, as this is not really an RS issue.

**Comment by ZeldoKavira** [comment]
Xiaminou please add me on Curse and we can chat about this. This issue was reported a few weeks back and was fixed.

**Comment by Xiaminou** [comment]
Done, but I don't usually leave Curse open so it's gonna be hard to get in touch.
