### ISSUE TITLE
Weird behavior between external storages and basic drawers from storage drawers

### ISSUE THREAD

**Issue by Kazzamkablam** [raoulvdberge/refinedstorage#87]
I noticed some weird behavior from external storages when they are connected to  basic drawers, first of all they show capacity of drawers wrong (won't affect game play). In addition they seem to cause barely noticeable lag spikes every few seconds when near them. (Noticeable if you watch torch smoke).

Refined Storage 0.7.6
Forge: 1936

**Comment by raoulvdberge** [comment]
Was the system idle (not importing / exporting, pushing / taking stuff from storage)?

**Comment by Kazzamkablam** [comment]
it was hooked to tree farm so it wasn't constantly doing stuff

**Comment by raoulvdberge** [comment]
I'll take a look at it, but I have a suspicion it's the drawers doing it, since the only thing the external storage does is reading inventory slots...

**Comment by raoulvdberge** [comment]
I added special integration for Storage Drawers. It should now work correctly and show the correct amount of items in it. Also, Drawer Controllers work too now!
