### ISSUE TITLE
solder not pulling materials from grid

### ISSUE THREAD

**Issue by ExtremeBuddha** [raoulvdberge/refinedstorage#872]
#### Issue description:
connected solder to grid will not pull materials from grid
#### What happens:
placed solder beside grid and when I asked for it to make a basic processor by clicking the plus it told me items not available had to take items out of grid and have in my inventory for it to craft also could not make a craft pattern for solder crafting recipes
#### What you expected to happen:
I expected to be able craft with materials in grid and make a crafting pattern for items made with a solder
#### Steps to reproduce:
1.
2.
3.
...

#### Version (Make sure you are on the latest version before reporting):
sky factory 3 - 3.0.4 
- Minecraft: 1.10.2
- Forge: 12.18.3.2202
- Refined Storage: 1.2.16

Does this issue occur on a server? [yes/no]
not on a server
#### If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here]

**Comment by way2muchnoise** [comment]
You might want to read up on how [autocrafting](https://refinedstorage.raoulvdberge.com/wiki/autocrafting) works and how to [automate the solderer](https://refinedstorage.raoulvdberge.com/wiki/automating-the-solderer)

**Comment by way2muchnoise** [comment]
The solderer isn't a capable of pulling items from the network by itself.
