### ISSUE TITLE
Unable to connect cables directly to controller

### ISSUE THREAD

**Issue by DocAnguus** [raoulvdberge/refinedstorage#877]
#### Issue description:

Unable to connect cables directly to a controller.  You must place another block next to the controller and connect cables to that.

#### What happens:

Any cables connected directly to the controller do not connect with other blocks.

#### What you expected to happen:

Cables connect to controller and network with other RS blocks.

#### Steps to reproduce:
1. Place down controller.
2. Connect cables to controller.
3. Connect cables to some other block (solderer, grid, etc...).  Controller does not show other blocks present on the network.
4. Break that setup and place another RS block directly next to controller.  I placed a grid on top of the controller.
5. Connect cables to the Grid.
6. Connect cables to rest of network and controller shows the other blocks present.

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge: 2202
- Refined Storage: 1.2.16

Does this issue occur on a server? [yes/no]

On single player.  Unknown if it happens on a server.

**Comment by raoulvdberge** [comment]
fixed in 1.2.17. update your RS installation
