### ISSUE TITLE
[0.7.6] Crafter not pulling finished items from vanilla chest

### ISSUE THREAD

**Issue by OhiraKyou** [raoulvdberge/refinedstorage#88]
Minecraft 1.9.4
Forge 1.9.4-12.17.0.1932
Refined Storage 0.7.6

EnderIO 1.9.4-3.0.0.36_alpha

After seeing a screenshot you recently posted showing the crafter working with a chest attached to a solderer with EnderIO conduits, I tried it with a chest attached to a furnace. Everything worked until the result was placed in the chest, which wasn't removed.

Edit: Oh! And, I'm using a separate crafter to craft planks and sticks when needed, which worked; two sticks were added to the chest, which were used by the furnace to smelt the gold.

I know that I can just use an importer, but is the crafter also intended to pull results out where possible?

[Screenshots](http://imgur.com/a/S27cw) (in the last shot, there was already a result ingot; I just filled in the rest to check if the slot was the problem)

[World Save (2.18 MB)](http://www.mediafire.com/download/z4uwpn6mrmzp7p9) (there are other mods installed, but only EnderIO is relevant here)

**Comment by raoulvdberge** [comment]
Hey, the crafter doesn't pull items no, you'll need a Importer :). This for various reasons including balancing and the single responsibility principle. Thanks for the good (bug)report though!
