### ISSUE TITLE
Disk Drive Textures Appear Purple

### ISSUE THREAD

**Issue by Joshwoo70** [raoulvdberge/refinedstorage#881]
mmm missing texures....
(64k Storage Disk)
![2017-01-18_21 07 01](https://cloud.githubusercontent.com/assets/7894419/22065210/2c96f10e-ddc2-11e6-968e-ebeb01c318b9.png)
Version 1.2.17 of Refined Storage
12.18.3.2221 of Forge.

**Comment by raoulvdberge** [comment]
weird. any logs about missing textures in the console?

**Comment by Joshwoo70** [comment]
i need to check when i get back home...

**Comment by Joshwoo70** [comment]
`https://gist.github.com/Joshwoo70/079713c42322a9b4cadca103d3acc9df/raw/0ccbfadd9e9afa0f79f7373c9faf5752cf1ebacf/fml-client-latest.log`

**Comment by DietmarKrause** [comment]
i can see this issue too. seemed to have no functional consequences, though. The drive is working.

**Comment by Joshwoo70** [comment]
> i can see this issue too. seemed to have no functional consequences, though. The drive is working.

yeah that's the case it works but not aesthetically pleasing...

**Comment by raoulvdberge** [comment]
Don't see anything about missing textures in the logs.

**Comment by raoulvdberge** [comment]
I can't reproduce this.

**Comment by kevinblockhead** [comment]
I too have this issue. It started when I updated to forge 2221.  The issue was not present with forge version 2185 which I was previously running.

**Comment by DuelMonster** [comment]
I too have this issue with latest Forge.  Thought it may have been Optifine or FoamFix, but remains the same when removing them.

**Comment by DietmarKrause** [comment]
not sure if it is important. But found this in forge changelog: "Build 1.11.2-13.20.0.2220:
	LexManos:
		New client config option to force all chunk rendering off the main
		thread. This may help FPS issues, but may also result in world
		holes/rendering issues. Also fix Forge configs not saving properly.
". Related? Perhaps different Options lead to not reproducable results

**Comment by shortybsd** [comment]
I can confirm this also.

Minecraft 1.11.2
Forge 2223
refinedstorage-1.3.5
[http://imgur.com/pdcZyxk](url)

**Comment by raoulvdberge** [comment]
This is due to a change in Forge, I'll be investigating this.

**Comment by shortybsd** [comment]
Awesome, thank you very much!
