### ISSUE TITLE
How do you autocraft things that you already have in your system?

### ISSUE THREAD

**Issue by Hund** [raoulvdberge/refinedstorage#882]
How do you autocraft things that you already have in your system? With AE you just used the third mouse button, but here it just picks up one item. I've tried every possible way I could think of. :/

**Comment by raoulvdberge** [comment]
ctrl+shift

please read the wiki before creating an issue first

https://refinedstorage.raoulvdberge.com/wiki/grid

**Comment by Hund** [comment]
Thanks! I checked the wiki, but it's pretty much empty: http://imgur.com/a/xpSHM.

**Comment by raoulvdberge** [comment]
did you try clicking "blocks" in the sidebar? And is your JS enabled?

**Comment by Hund** [comment]
Yes and yes. :)

**Comment by raoulvdberge** [comment]
that is weird. which browser & os are you using?

**Comment by Hund** [comment]
Arch Linux with qutebrowser (and the Qt WebEngine backend).
