### ISSUE TITLE
Feature : A chest that uses disk drives similar to a ME Chest

### ISSUE THREAD

**Issue by llloyd4** [raoulvdberge/refinedstorage#884]
Just a feature request. :D So, how about your version of an ME Chest. Even after, in 1.7.10, I had a full on ME network I still used a single ME Chest when looking at full disks and seeing exactly what was on them so I would have a good idea what I need to pull off to external deep storage. So in that sense they are very useful. Even with the Grid set to sort most to least the nuggets from the Storage Drawers 'Compacting Drawer" is drowning out the first row or so. >.< Nor do I see a way to disable, temporarily, the display of external storage items with out physically breaking the connection.

**Comment by uecasm** [comment]
You can toggle external storage to Insert Only (if you can see the connector) and it will hide things from the grid.  Or you can make an isolated controller+drive+grid to let you insert one drive and see only what's on that.

**Comment by raoulvdberge** [comment]
no
