### ISSUE TITLE
Oredict patterns don't work with external storage drawers

### ISSUE THREAD

**Issue by uecasm** [raoulvdberge/refinedstorage#885]
#### Issue description:

When trying to craft something using an Oredict pattern with some ingredients stored in external storage on a Storage Drawer network, nothing happens.  This did work in a previous version of the mod(s).

Putting the ingredients directly in the network or using a non-Oredict pattern does work as expected (but then it won't substitute oredict-compatible items).

Not sure if the bug is in RS or in Storage Drawers, but something seems to be going wrong in the interaction between them.

#### What happens:

The item to be crafted remains listed in the Crafting Monitor, but nothing else happens.

#### What you expected to happen:

The items should be crafted.

#### Steps to reproduce:
1. Place some Storage Drawers containing gravel, clay balls, and sand.
2. Place a Drawer Controller next to the drawers.
3. Place an External Storage on the Drawer Controller.
4. Place an RS controller and drive network with some storage.
5. Place a Crafter with a pattern for Binder Composite, with Oredict ticked.
6. Attempt to craft some Binder Composite.

Note that even though the exact correct items are available, it doesn't craft.  (The preview is correct, it just doesn't do anything once started.  This suggests that it knows the items are there, but is somehow unable to extract them from the drawer network?)

Repeat without oredict ticked, then it works.  (But then doesn't work with red sand, which was the goal of enabling oredict in the first place.)
Repeat with oredict and the items in internal storage, or in a chest on external storage, and it works.  (But wastes drive space for bulk storage items, which was the point of using drawers.)

#### Version:

- Minecraft: 1.10.2
- Forge: 12.18.3.2185
- Refined Storage: 1.2.17
- Storage Drawers: 3.5.17

(Modpack: Direwolf20 1.4.1 single player)

**Comment by raoulvdberge** [comment]
Is that still broken?

**Comment by uecasm** [comment]
Another slightly odd behaviour is that if you request crafting something that uses the Binder Composite (ie. you make a processing pattern for Conduit Binder), then the crafting monitor stays stuck on "machine in use" on 8 Conduit Binder, and not that it's failing to craft the Binder Composite in the first place.

**Comment by LukeLonas** [comment]
I can say that I have personally run into this issue.  I was previously using a colossal chest with an external storage, and that worked 100% fine with the oreDict patterns.  I moved over to a Storage Drawer system with an external storage and now they all get stuck and don't craft.  From this, it seems like it might be an interaction issue between Storage Drawers and RS.
