### ISSUE TITLE
Items are vanishing upon insert via any method.

### ISSUE THREAD

**Issue by AryuSyrius** [raoulvdberge/refinedstorage#887]
#### Issue description: 
I've been running a SkyFactory 3 server for several days now and just two days ago the RS system stopped accepting items most of the time. I have an interface connected to an EIO farm and the items are being sent to the interface and they disappear but are not appearing in the RS system. Manually inputting items into the RS system may put 0, some, or all of the items in seemingly at random.

I have the following RS blocks:
2x Interface
25x crafter
3x importer
1x solderer
2x disk drive
2x exporter
11x 1k storage block
95x cable
1x crafting grid
1x pattern grid
1x crafting monitor
1x controller

#### What happens: 
Items deposited into the RS system are vanishing.

#### What you expected to happen: 
I put in items, and I am able to take out items.

#### Steps to reproduce:
1. Not quite sure. It started happening randomly, but it's currently happening every time I try to deposit items.
2.
3.
...

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge: 12.18.3.2202
- Refined Storage: 1.2.16
- SkyFactory 3: 3.0.4

Does this issue occur on a server? yes

#### If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here]

**Comment by raoulvdberge** [comment]
You sure some storages aren't in "insert-only" mode?

**Comment by AryuSyrius** [comment]
I did see another post regarding missing items that mentioned checking if anything was set in insert only mode so I did check the disks and the 1k storage blocks. They were not set in insert only mode.

**Comment by raoulvdberge** [comment]
Check again please. It's the only way this issue can occur.

**Comment by AryuSyrius** [comment]
I will do so. Let me ask are the disks and storage blocks the only blocks that I would need to check.

**Comment by raoulvdberge** [comment]
Also external storages if you have any. Also note that exporters can be removing items from your storage and exporting them elsewhere.

**Comment by AryuSyrius** [comment]
Ok, sorry for wasting your time. Someone on my server fixed it. Not sure how they did it yet. Thank you for your help.
