### ISSUE TITLE
RS Destructors are not properly handling exutils2 drums 

### ISSUE THREAD

**Issue by mahldcat** [raoulvdberge/refinedstorage#888]
#### Issue description:
RS Destructors are losing information from exutils2 drums that have fluid in them, and there is no way to detect a full drum from an empty one.

#### What happens:
There are several problems
1) The RS system is unable to determine a full drum from an empty one.
2). When you do fiddle with the destructor's "ignore nbt" settings...it will finally start breaking both full and empty drums.
3) If the drum contains any fluid, once it gets broken, it is brought back into the system as an empty drum.

Note I also tried placing a silk touch upgrade in the destructor, which made no difference

#### What you expected to happen:
I would expect the setup I tried building to break a full drum, and once it did, RS should be able to import the drum with the proper fluid levels

#### Steps to reproduce:
0. Have an RS system configured with inventory that has 8-10 drums, and fluid storage with some fluid to export
1. Place a drum in world
2. Place a constructor on one side of the drum, a destructor on the other side, and an exporter on the 3rd side 
3.  Configure the export to export the fluid you setup in step 0.  
4. Change the Constructor to place empty drums
5. Change the Destructor to to remove full drums

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge: 12.18.3.2209
- Refined Storage: 1.2.17

Does this issue occur on a server? (yes)

Here is a shot of the basic build I'm using:

![2017-01-20_00 50 19](https://cloud.githubusercontent.com/assets/1320535/22140577/7333a1dc-deaa-11e6-8517-deaa2536a5c6.png)

**Comment by way2muchnoise** [comment]
So construction and filtering works fine now. The issue with breaking is on XUs end. `Block#getDrops` doesn't return the filled drum ItemStack, I tested the breaking with a Actually Additions as well and it also returns an empty barrel. So the breaking is not going wrong on our end.

**Comment by mahldcat** [comment]
@way2muchnoise I'm in the process of bugging the empty barrel bug....do you happen to recall which AA block you used to break the barrel?

**Comment by way2muchnoise** [comment]
The block breaker, and we also pinged tema about this so lets hope it gets resolved soon™
