### ISSUE TITLE
[0.7.6] Constructor/destructor not working with sugar canes

### ISSUE THREAD

**Issue by OhiraKyou** [raoulvdberge/refinedstorage#89]
Minecraft 1.9.4
Forge 1.9.4-12.17.0.1932
Refined Storage 0.7.6

Neither the constructor nor the destructor work with sugar canes (on valid planting blocks, such as sand adjacent to water). They do, however, seem to work with flowers, such as the white tulip.

**Comment by raoulvdberge** [comment]
Thanks, will investigate this...

**Comment by OhiraKyou** [comment]
Looks like the constructor still can't handle sugar canes. Although, they do work with river canes from Biomes O' Plenty.

**Comment by raoulvdberge** [comment]
Is there water next to the sand block? It works here.

**Comment by OhiraKyou** [comment]
Yeah, it is. Here's an album of it failing with sugar cane and working with river cane:
http://imgur.com/a/QAsM7

And, here's a basic example world (608.42KB, ignore the other mods):
https://www.mediafire.com/?9gvsq5txphupei8

**Comment by raoulvdberge** [comment]
Ugh, thanks for reporting, will try to fix it.

**Comment by OhiraKyou** [comment]
Looks like it extends to cacti as well; the destructor will take them, but the constructor cannot place them.

**Comment by raoulvdberge** [comment]
Cacti can not be placed because it cannot have any blocks at its sides.

**Comment by OhiraKyou** [comment]
Well, balls. I even had the destructor facing down for that exact reason but forgot to do the same for the constructor.

**Comment by raoulvdberge** [comment]
Okay, I should have fixed this now. As an added bonus, it is now also possible to place seeds. Minecraft special cases a lot of stuff so I have to handle all those exceptions.

**Comment by Harith163** [comment]
ooh automated farms? also does bonemeal in a constructor bonemeal said crop?
