### ISSUE TITLE
items rotating and disconecting

### ISSUE THREAD

**Issue by CamaroKing59** [raoulvdberge/refinedstorage#890]
#### Issue description:
so the drives and the grid rotate and the grid rotates and disconnects
#### What happens:
i teleport in and out of the area it happens
#### Steps to reproduce:
1.teleport in the area fix things
2.teleport out
3.then come back and have to fix it again
...

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge:12.18.3.2185
- Refined Storage:1.2.17

Does this issue occur on a server?
yes

#### If a (crash)log is relevant for this issue, link it here:
Before: https://gyazo.com/5d1a0787d7614a8a8aae2b7bae619e03

After: https://gyazo.com/c7948f943a9447293b414813c9cb8148
[pastebin/gist/etc link here]

**Comment by CamaroKing59** [comment]
https://gyazo.com/abbb330f6d096b225a806705e70abced this is the external storage things they were atached to the quantum storage and now there not

**Comment by raoulvdberge** [comment]
log please

**Comment by CamaroKing59** [comment]
client side log or latest

**Comment by CamaroKing59** [comment]
what part of the log do you need

**Comment by CamaroKing59** [comment]
Latest Log: http://pastebin.com/xMvnhA6D

**Comment by raoulvdberge** [comment]
wat
```
Caused by: java.lang.IllegalArgumentException: No enum constant net.minecraft.util.EnumFacing.
    at java.lang.Enum.valueOf(Enum.java:238) ~[?:1.8.0_25]
    at net.minecraft.util.EnumFacing.valueOf(EnumFacing.java:13) ~[ct.class:?]
    at com.insane.simplelabels.tile.TileLabel.func_145839_a(TileLabel.java:248) ~[TileLabel.class:?]
```

remove SimpleLabels and see if it fixes it

**Comment by CamaroKing59** [comment]
it worked thank you everything is fixed

**Comment by raoulvdberge** [comment]
Glad to hear! Don't forget to report this issue on SimpleLabels' issue tracker instead, though.

**Comment by MikeLydeamore** [comment]
Incidentally, this is hopefully fixed in https://github.com/MikeLydeamore/SimpleLabels/commit/e5111dcc644f946ff724758f8875683d03013d0a
