### ISSUE TITLE
Can't clear item from interface export

### ISSUE THREAD

**Issue by jeridan** [raoulvdberge/refinedstorage#893]
#### Issue description:
After putting item into interface export, you can't clear it without overwriting it with something else.
#### What happens:
Right-clicking increases the amount exporting, left-clicking will decrease it to one but will not remove it.
#### What you expected to happen:
Left-click to remove once at a single item.
#### Steps to reproduce:
1.Place interface
2.Put item in interface export slot
3.Click to clear item from export slot
...

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge: 12.18.3.2185
- Refined Storage: 1.2.17

Does this issue occur on a server? [yes/no]
Playing SSP, not sure
#### If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here]

**Comment by raoulvdberge** [comment]
Shift.

https://refinedstorage.raoulvdberge.com/wiki/interface

"To clear an exported item configuration use SHIFT and click on the item to clear. Use the left and right mouse buttons to increment or decrement the amount that has to be exported."
