### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by Tyrantin** [raoulvdberge/refinedstorage#894]
#### Issue description: 
multi block function & facades

#### What happens: 
removes bulkie configurations and hides cables

#### What you expected to happen: 
less space required for autocrafting and cleaner looking bases

**Comment by Tyrantin** [comment]
If you wish to blow past the "other" competition. This would be the next logical step and one that a lot of ppl would love to see!

**Comment by way2muchnoise** [comment]
You can use [Chisel & Bits](https://minecraft.curseforge.com/projects/chisels-bits) or any [MCMultipart](https://minecraft.curseforge.com/projects/mcmultipart) to cover cables. A multiblock crafter is available in [RebornStorage](https://minecraft.curseforge.com/projects/rebornstorage).

**Comment by Tyrantin** [comment]
OK I guess I didn't phrase it the correct way. What I am referring to is make the grid machines more like the applied energistics monitors also make the imports and exports able to occupy the same block spac.

**Comment by raoulvdberge** [comment]
no
