### ISSUE TITLE
[1.10.2] Won't auto-craft/detect FluxNetworks Storage

### ISSUE THREAD

**Issue by Rudolpher** [raoulvdberge/refinedstorage#895]
#### Issue description:
[Claims missing items](http://imgur.com/a/WUY7h) when auto-crafting tier 2 or tier 3 FluxNetworks Storage, dependency on previous crafting tier.
It does not matter [if I already have Basic Flux Storage](http://imgur.com/a/kaSYV) in the system, it still claims it's missing.

#### What you expected to happen:
Auto-crafting tier 3 Gargantuan Flux Storage

#### Steps to reproduce:
1. Set up patterns for each tier storage (Basic, Herculean, Gargantuan).
2. Order tier 2 or 3 Storage.
3. System claims items missing.
...

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge: 12.18.3.2215
- Refined Storage: 1.2.17

Does this issue occur on a server? [yes/no]
SSP

**Comment by way2muchnoise** [comment]
NBT tag issue, just need to add them to the ignore list.

**Comment by Rudolpher** [comment]
[Second NBT when configured and taken down](http://imgur.com/a/PR96p).
