### ISSUE TITLE
p2p tunnels

### ISSUE THREAD

**Issue by JJSax** [raoulvdberge/refinedstorage#896]
I really miss the p2p feature in Applied Energistics.  

- Minecraft: 1.10.2
- Forge: 12.18.3.2202
- Refined Storage: 1.2.17

I'm really trying to find how to tag this as feature request.

**Comment by way2muchnoise** [comment]
But why?

**Comment by raoulvdberge** [comment]
that's the reader/writer feature. not finished yet
