### ISSUE TITLE
Importer and exporter models

### ISSUE THREAD

**Issue by dylanwi** [raoulvdberge/refinedstorage#90]
Would it be cool to see models for the importer and exporter similar to the models of ae1 import and export buses to make it clearer which way they are pointing from any side other than the one they are pointing. 
If this isn't possible, I heard that 1.8+ made models...different...maybe some some sort of arrow on the sides for clarity.

**Comment by raoulvdberge** [comment]
I agree, unfortunately I'm not that good with models... gonna spawn @GustoniaEagle for this one.

**Comment by GustoniaEagle** [comment]
I can make models, but we're probably as good as each other when it comes to the code. Will sort sometime with you.

**Comment by raoulvdberge** [comment]
This is added for the next version! :)

http://imgur.com/a/AxmLa
