### ISSUE TITLE
Issue with the IDeepStorage Api

### ISSUE THREAD

**Issue by gigabit101** [raoulvdberge/refinedstorage#900]
#### Issue description:
In ItemStorageDSU.java you get the stored ItemType from the IDeepStorageApi but
do not grab the rest of the Tiles Inventory this is also a limitation of the api only allowing returning
of a ItemStack.
#### What happens:
Your RS system will not detect Items in the input/output slot;
#### What you expected to happen:
Items in the input/output slot should show
#### Steps to reproduce:
1.Attach a External Inventory block to QuantumStorage unit
2.Add 1 stack of Items to QuantumStorage unit
3.Look in RS System that stack is missing
...

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge:
- Refined Storage:

Does this issue occur on a server? [yes/no]
yes
#### If a (crash)log is relevant for this issue, link it here:
n/a
[pastebin/gist/etc link here]

**Comment by Darkosto** [comment]
Yep, this one has been reported to me on my forums, too. Let me know if there's anything I can help with.

**Comment by raoulvdberge** [comment]
AFAIK the API doesn't expose those slots.

**Comment by gigabit101** [comment]
no it dose not but its still just a normal tile and I cant return the rest of the slots with the api so there is nothing I can do my side

**Comment by gigabit101** [comment]
I suggest just getting the Tiles inv like any other Tile as well as grabbing the stored item using the api.
I do not allow access to the storeditem using normal methods anyways so there should be no issue with it grabbing the storeditem twice

**Comment by raoulvdberge** [comment]
My opinion on that course of action: meh

**Comment by gigabit101** [comment]
The only other thing I can think of doing is changing the IDeepStorage api to allow me to pass the rest of the Inv but that will break things...

**Comment by raoulvdberge** [comment]
Couldn't you implement the storage drawers API? Then it would work instantly with RS

**Comment by raoulvdberge** [comment]
Closing this as wontfix.
