### ISSUE TITLE
Feature Request - Grid Filter mod filter support for 1.10 (SkyFactory 3)

### ISSUE THREAD

**Issue by KodiakJak** [raoulvdberge/refinedstorage#906]
#### Issue description: 
Request Grid Filter mod filter support for 1.10 (SkyFactory 3)

#### What happens: 
Option doesn't exist

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge: 12.18.2215
- Refined Storage: 1.2.17

**Comment by raoulvdberge** [comment]
Maybe!
