### ISSUE TITLE
Destructor Not functioning

### ISSUE THREAD

**Issue by thegamehunter09** [raoulvdberge/refinedstorage#913]
#### Steps to reproduce:
1.
2.
3.
...

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge: 12.18.3.2.2185
- Refined Storage:

Does this issue occur on a server? [yes/no] yes

#### If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here]

**Comment by VT-14** [comment]
Claimed Chunks?  FTB Utilities?

If yes, I believe the command to fix that is:
/ftb team config ftbu.fake_players true

If I got that wrong, then you can find the correct command on the wiki page for the Destructor.

**Comment by thegamehunter09** [comment]
Thanks that literally fixed my problem.
