### ISSUE TITLE
RS is Becoming slow?

### ISSUE THREAD

**Issue by TimelordGuardian** [raoulvdberge/refinedstorage#919]
#### Issue description:
Slow when placing and removing Items from system
#### What happens:
Wen I removed or place items in system it takes a few seconds to do, for just one item.
#### What you expected to happen:
I expect it to be instant.
#### Steps to reproduce:
1. System has over 200k items
2. Place or remove items 
3. It start getting slow
...

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge: 12.18.3.2215
- Refined Storage:1.2.18

Does this issue occur on a server? [yes/no]
No clue, its singleplayer
#### If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here]

**Comment by raoulvdberge** [comment]
What storage mediums are you using (disk drive, external storage, ...). Please list them all, and if they are connected to an External Storage, also mention to which storage they are connected.

**Comment by TimelordGuardian** [comment]
I'm using both external storage and disk drive. If I disconnect the disk drives every thing is fine again. The external storage is connected to drawer controller.

**Comment by raoulvdberge** [comment]
Can you do this while trying to extract / insert?

https://refinedstorage.raoulvdberge.com/wiki/profiling

**Comment by raoulvdberge** [comment]
@TimelordGuardian Did you have time to try this yet?

**Comment by raoulvdberge** [comment]
Author is not responding.
