### ISSUE TITLE
[0.7.7] Constructor tries to place items like torches on invalid surfaces

### ISSUE THREAD

**Issue by OhiraKyou** [raoulvdberge/refinedstorage#92]
Minecraft 1.9.4
Forge 1.9.4-12.17.0.1932
Refined Storage 0.7.7

While gathering info for #89 I tested the constructor with vines. I noticed that they _appeared_ to be placed on the front of the constructor. However, unlike when players place vines on a constructor, when the block next to a constructor-placed vine is updated (e.g., by placing a dirt block next to it), the vine disappears. My guess is that the vine is actually being placed on the air below it, which is invalid.

So, I tested them with torches. The constructor will place them even if surrounded by air or with stairs underneath, causing them to immediately pop off as an item.

**Comment by raoulvdberge** [comment]
I can't do anything about this, I'm calling `canPlaceBlockAt` already, but that doesn't handle every case. I could add special handlers for every case, but that would make the code really ugly.
