### ISSUE TITLE
Missing Texture

### ISSUE THREAD

**Issue by CamaroKing59** [raoulvdberge/refinedstorage#922]
#### Issue description:
Missing Texture
#### What happens:
just loaded with missing texture
#### Steps to reproduce:
1.loaded AlliedKingdom 2 pack
2.
3.
...

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge:12.18.3.2221
- Refined Storage:1.2.12

Does this issue occur on a server? [yes/no]
yes
#### If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here]
https://gyazo.com/934086a2bb9cc41ba9f11f75cc4739d3

**Comment by way2muchnoise** [comment]
Duplicate of #881
