### ISSUE TITLE
TileCable should avoid being ticked

### ISSUE THREAD

**Issue by sfPlayer1** [raoulvdberge/refinedstorage#924]
Besides decoration, cables and pipes are typically the most commonly used tile entities by a large margin. Since every ticking TE comes with a substantial cost for every tick and during chunk loads/unloads, TileCable shouldn't implement ITickable if at all possible.

**Comment by raoulvdberge** [comment]
It doesn't do anything when ticking, is the cost that high?

**Comment by sfPlayer1** [comment]
Per my most recent observation on FC's SF3 instance roughly 35% of the total tick time go towards mere te quantity/management overhead, excluding any actual work in te.update(). RS cables are ~17% of the ticking te quantity.

That suggests quite heavily that having thousands of TEs tick is a bad idea, especially if they don't serve any purpose. I've also had quite some success with this kind of optimization before, e.g. some fake light blocks for long range lights killed servers despite not doing anything of significance in updateEntity().

**Comment by raoulvdberge** [comment]
I'll look into removing them being a TE, then.

**Comment by calloatti** [comment]
Ignore if nonsense, but [xnet ](https://github.com/McJty/XNet) cables are not TE, maybe you could check it out for inspiration.

**Comment by raoulvdberge** [comment]
This issue has been fixed
