### ISSUE TITLE
White List Behavior Incorrect

### ISSUE THREAD

**Issue by mthomas768** [raoulvdberge/refinedstorage#925]
#### Issue description:

.A whitelist is a list of allowed items, and a storage object in whitelist mode should abide by these restrictions. An empty whitelist indicates nothing is acceptable.

#### What happens:

An empty whitelist accepts all items/fluids.

#### What you expected to happen:

An empty whitelist should not accept any items/fluids. Ideally, an empty blacklist (which indicates unacceptable items) would allow all items to pass.

#### Steps to reproduce:

1. Set any storage block or drive to an empty whitelist.
2. Add items to the system.
3. The storage accepts all items.

Tested with storage blocks, disk drives, and fluid blocks. I haven't tested importers, exporters or external storage.

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge: 12.18.2.22022
- Refined Storage: 1.2.16

Does this issue occur on a server? [yes/no]

Yes - not tested in single player.

#### If a (crash)log is relevant for this issue, link it here:

N/A

**Comment by raoulvdberge** [comment]
We know about this, but can't fix this due to backwards compatability. If we change this, essentially all machines stop working.

**Comment by mthomas768** [comment]
Thanks for the fast response. Any chance this could be documented in the wiki? It would save some head scratching. :)
