### ISSUE TITLE
Add the ability to partition or preset storage disks?

### ISSUE THREAD

**Issue by jadeonking** [raoulvdberge/refinedstorage#926]
If there is one thing I wish that could be done is the ability to preset the storage disks themselves to accept certain items or maybe even extending the amount of slots for whitelisting or blocklisting on disk drives would be nice as I would like to set disk drives or disks up to hold "categories" of items if not possible its cool loving the mod

**Comment by raoulvdberge** [comment]
No, disk drive has filter slots
