### ISSUE TITLE
cable causing client/server crash

### ISSUE THREAD

**Issue by aaronmallen** [raoulvdberge/refinedstorage#928]
#### Issue description:
Cable is causing a server crash

#### What happens:
Server crashes on log in or single player client crashes on block break
#### What you expected to happen:
Not that ^
#### Steps to reproduce:
¯\_(ツ)_/¯

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge: FTBserver-1.10.2-12.18.3.2215-universal
- Refined Storage: refinedstorage-1.2.18

Does this issue occur on a server? [yes/no]
yes

#### If a (crash)log is relevant for this issue, link it here:
[crash-2017-01-25_23.32.00-server.txt](https://github.com/raoulvdberge/refinedstorage/files/734360/crash-2017-01-25_23.32.00-server.txt)

**Comment by raoulvdberge** [comment]
Why are you saying that you are on Refined Storage 1.2.18 while the crashlog says you're on 1.2.17?

UCHIJAAAA	refinedstorage{1.2.17} [Refined Storage] (refinedstorage-1.2.17.jar) 

Update to 1.2.18, it fixed the issue.

**Comment by aaronmallen** [comment]
Sorry the crash report is from Refined Storage 1.2.17 but it is also occurring on 1.2.18... this bug is still very much valid.

**Comment by aaronmallen** [comment]
[crash-2017-01-26_23.26.37-server.txt](https://github.com/raoulvdberge/refinedstorage/files/735686/crash-2017-01-26_23.26.37-server.txt)

**Comment by raoulvdberge** [comment]
That is another issue.

**Comment by raoulvdberge** [comment]
Nope, it occurs in another place. So it's an other issue.

**Comment by aaronmallen** [comment]
It seem to have something to do with a cable BEFORE a cable connected to crafters, but I'd take the reports word for it not mine ;)

**Comment by raoulvdberge** [comment]
Even though they look identical (same error) they are ocurring at another place in the code. That's why it's important to absolutely include the crashlog from the latest version, not an older one.

**Comment by aaronmallen** [comment]
yeah I'm not sure why I attached the 1.2.17 one, that's my bad... hopefully you can get it sorted, I was a hardcore AE fan and not immediately sold on RS, but tbh I love it man. Keep up the good work.

**Comment by raoulvdberge** [comment]
Thank you, shouldn't be hard to fix. Expect a release this weekend.
