### ISSUE TITLE
looking at a bugged drive causes a kick from the server.

### ISSUE THREAD

**Issue by darkmdbeener** [raoulvdberge/refinedstorage#929]
#### Issue description:
skyblock 3.0.6

#### What happens:

when looking at a Refined Storage drive on a server you will crash out.

#### What you expected to happen:

not crash

#### Steps to reproduce:
1. set multiple drives
2. put in some disks into one
3. look at them
...
This being said I think it is something unique in the item that is in my RS system that is causing the issue.

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge: 12.18.3.2215
- Refined Storage: 1.2.12

Does this issue occur on a server? [yes/no]

yes

#### If a (crash)log is relevant for this issue, link it here:

https://u.nya.is/uldukh.log

Might have to do with hwyla, or wawla

**Comment by TehNut** [comment]
https://github.com/TehNut/HWYLA/issues/42
