### ISSUE TITLE
More cable from current cable recipe.

### ISSUE THREAD

**Issue by Dracon1023** [raoulvdberge/refinedstorage#93]
The current cable recipe is quite expensive for only six cable pieces.  In AE2, the recipe would give you three quartz fiber, and then four cable for each fiber, totaling at twelve.  Twelve seems like a reasonable number to get from the current recipe in Refined Storage.

**Comment by raoulvdberge** [comment]
I'm not sure about this, I'd need some more opinions from other people too.

**Comment by Harith163** [comment]
In my opinion, cable isn't something we should worry about. I say go ahead
and make it 48. Screw balance!

**Comment by Mohron** [comment]
Lets go with a power of 2 and pick 8!

**Comment by raoulvdberge** [comment]
I want it to be a power of 6 because the recipe uses 6 QEI's, so I might just go for 12...

**Comment by Dracon1023** [comment]
The main reason I suggested the increase was that I found it a little expensive early on to run cable to forestry farms to automate them with a logistics system.

**Comment by Mohron** [comment]
I'd agree with more is better, after all they're just cables.

**Comment by raoulvdberge** [comment]
I must add that AE2 cables are cheaper to create because they are more limited than RS cables (because of channels). They are cheaper so you could create more dense cables.

However, your point is still valid and I'm going to increase the amount to 12.
