### ISSUE TITLE
Destructors Working Inconsistently With Water

### ISSUE THREAD

**Issue by 7OOTnegaTerces** [raoulvdberge/refinedstorage#930]
#### Issue description:
Fluid destructors working inconsistently.

#### What happens:
I have a row of destructors facing down over the center of a 3x12 bed of water, set to turn on when they receive a redstone signal and paired with detectors set to go on when the level of water in the system goes below a certain point.  When the water drops down below the threshold the detectors all begin emitting a redstone signal.  However only three, or occasionally four of the destructors will turn on at a time and suck up any water into the system.  It's generally always the same ones, but it does vary every so often.  Neither trying to force all the destructors to turn on by telling them to ignore redstone signals, nor trying to space them out into their own individual walled in 1x3 troughs of water fixed the problem.

#### What you expected to happen:
All of the destructors to activate and suck up water into the system until the detectors turn off.

#### Steps to reproduce:
1. Create a 3x12x1 pool of water.
2. Place destructors facing down along the middle of the pool, set to pick up fluids and activate on a redstone signal.
3. Pair up each destructor with a detector and set it to turn on when the water in the system goes below a particular threshold.
4. Reduce the water in the system well below the threshold.
...

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge: 2185
- Refined Storage: 1.2.12

Does this issue occur on a server? [yes/no]
No.

**Comment by 7OOTnegaTerces** [comment]
I just tried placing each destructor at the center of it's very own walled in 3x3x1 pool of water.  I still can't get even 8 of them to turn on simultaneously.  And it's NOT a power issue, I've got nearly ten times as much power as I'm currently using.

**Comment by raoulvdberge** [comment]
I will try to reproduce this tomorrow.

**Comment by 7OOTnegaTerces** [comment]
Thank you!  The individual 3x3 solution takes up 4x as much space!!!

**Comment by raoulvdberge** [comment]
Works here:

![x](https://raoulvdberge.com/w8LWMa)
