### ISSUE TITLE
Bucketless Fluid Integration

### ISSUE THREAD

**Issue by 7OOTnegaTerces** [raoulvdberge/refinedstorage#931]
#### Issue description:
Some mods (i.e. Mekanism) don't have buckets for all their fluids, but because of how RS works you can only manipulate fluids that do have bucket (i.e. item) forms.  No bucket means no exporting or fluid level detection, which basically means that RS is unable to do anything but store such fluids, much like a black hole.  Not Very Useful.

Now while their are easily hundreds or thousands of items (depending on how many mods you are running), there really aren't that many fluids.  Even with all the mods I have, I have less than 50.  As an alternative to using buckets to select a fluid type in an importer/exporter/detector/etc. what if there was a pop-up or new window that lists all the fluids (like a chest of fluid blocks) that RS can find and you just click on one to select it.  Then it wouldn't matter whether or not the other mod creator included a bucket version for their fluid or not (I've no idea if Mekanism purposely left out the buckets for some design scheme/paradigm/realism/balancing reason), RS would still be able to work with it.

- Minecraft: 1.10.2
- Forge: 2185
- Refined Storage: 1.2.12

**Comment by 7OOTnegaTerces** [comment]
I was able to get some Mekanism Liquid Chlorine into an ender tank, but when I tried to use the tank's ender bucket, RS didn't recognize the fluid and did nothing.  It would be nice if the fluid selection field worked with unusual buckets, like ender tank linked ender buckets...

**Comment by raoulvdberge** [comment]
Interesting. But I don't know what to think about that selection screen, I don't think it's that good of a solution.

**Comment by 7OOTnegaTerces** [comment]
Come on!!!  Throw me a bone here!  How ELSE are you going to ensure that your mod can work with any fluid, even if the mod doesn't provide a bucket for said fluid?!?  If I can't pick up and hold the fluid in my hand in any way, then that only leaves some sort of selection method.  You could always have it as an alternate method that has to be activated in the config before it will work (though if you do, please include a way to activate it by console command so that I don't have to restart my game, that takes about eight minutes with all the mods I have!).

Oh, and don't forget that I was able to get some bucketless Mekanism fluids into one of Shetiphan's Ender Tank linked ender buckets, so you could make your mod work with his so that it could correctly read the linked bucket and set the fluid selector with it.  I was about to suggest implementing your own wireless bucket instead of using Shetiphan's, but that wouldn't work since you couldn't select the fluid for the wireless bucket so that your mod could select bucketless fluids until you implemented some way for your mod to select bucketless fluids.

**Comment by 7OOTnegaTerces** [comment]
This remined me of many other issues I've had with fluids and RS, so I started another issue slip, but now that one's overlapped this one, so don't forget to check it out.  If you really HATE the idea of a 'selection screen' then I think your only other option (though I COULD be wrong) is to implement the suggestion I made over there.

**Comment by raoulvdberge** [comment]
You don't need a bucket per se, **you could use any fluid container**. The fluid grid only mandates a bucket because it's a standard.
