### ISSUE TITLE
Bucketless Fluid Integration

### ISSUE THREAD

**Issue by 7OOTnegaTerces** [raoulvdberge/refinedstorage#934]
#### Issue description:
First, let me just apologize for my Better Fluid Support post.  I would have fixed it now (after getting an obviously much needed nights sleep), and left this comment there, but you locked me out.  I did finally manage to get my fluid monitor to input and output fluids, my mistake in the past when following the wiki's directions was to pick up the bucket and click/shift click with it in the fluid grid, Exactly as I would do with the regular item grid, rather than leaving it in my inventory.  I'm also really happy to hear that there is a wireless fluid grid in 1.11, but that really doesn't do me any good in 1.10.2.  *Sigh*, oh well, I guess I'll just have to wait!

Second, and the reason for me reopening this issue (and _yes_, I did go and read the solution you suggested there and try it first), is that while I did eventually get this to work using one of EnderIO's fluid tanks, I now have to keep said filled tank somewhere (and not use its contents) so I can use it whenever I wish to work with _that particular_ bucketless fluid in the future.

I don't know about the technical difficulties that might have kept you from allowing the fluid grid to fill any fluid container, but if they are high, then could you implement your own RS bucket that can be filled with any fluid from the fluid monitor, even and especially those that don't have buckets, so that I don't have to keep a bunch of filled tanks for each and every bucketless fluid?  It could be an optional feature that you have to turn on in the config or something.

**Comment by raoulvdberge** [comment]
> fluid grid to fill any fluid container

I don't like that mechanic, it's convoluted.

And I already said no to the RS bucket thing.
