### ISSUE TITLE
[Issue] Network suddenly broken

### ISSUE THREAD

**Issue by accessdenied0** [raoulvdberge/refinedstorage#936]
#### Issue description:
Storage Disks and External Storages are all broken. "Share" Items and seem to unaccessable.

#### What happens:
Access over a Grid and try to move items causes first a "server crash" in my case a dc from my client world ("Lost Connection") after reloading some resources doesn't show up, the complete Network seem only to work partly (External Storages doesn't show up in Grid).

After reconnecting: The Item I tried to pull out lies on the ground and by to accessing the grid again, the game freezes. In addition again some of the resources doesn't show up. (After breaking the Controller and replacing it doesn't seem to solve it. Items only refresh if you access the grid.)

Long story short: no matter what I do (changing Disks, deleting stuff, exporting items, replacing Controller) in my world is RS broken and I can't access my items. Not even on other networks and renewed ones)

#### What you expected to happen:
Access to my Disks without crash.

#### Steps to reproduce:
I have no idea. This issue first appears after I rewired some cabled (while lagging) and a Game freeze after autocrafting something (Storage Drawer)

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge: v12.18.3.2215
- Refined Storage: refinedstorage-1.2.18 or 1.2.17
- Refined Storage addtions: RebornStorage-1.10.2-1.0.0.22 or 1.0.1.27, WirelessCraftingGrid-1.10.2-1.0.0, Growable Cells-0.3.2, ocrsdriver-1.0.0 (Open Computers Refined Storage Driver)

Does this issue occur on a server? [yes/no]
no idea

#### If a (crash)log is relevant for this issue, link it here:
No crashlog. Just unusual exceptions in console while loading up first time: 
Clip from Console: http://pastebin.com/Jx2rD6SD
Forge log: http://paste.ee/p/xEJ8M

**Comment by accessdenied0** [comment]
I figured out, that the disks you obtain from Growable Cells-0.2.1 seem to cause massive Storage issues and maybe the cause of it. I updated later on and this didn't fixed the issue in my old world. I recreated the world before the state of corruption and tried it with Growable Cells-0.3.2.

I'm not sure it seem to work with this version but I can't say for sure. Further testing is required.

**Comment by raoulvdberge** [comment]
Can't do anything without any logs. Also your description of what happens is very vague and all-over-the-place.
