### ISSUE TITLE
External Storage cables are deleting my items

### ISSUE THREAD

**Issue by GamingWithAGoose** [raoulvdberge/refinedstorage#937]
#### Issue description: 
RS external storage cables are deleting all of the items out of my vast storage blocks.

#### What happens:
I have external storage cables connected to 9 vast storage blocks. When playing yesterday there was no issue involving the disappearance of items. Yesterday I re logged into my world multiple times but everything was fine. When logging into today, I see that all of my items have been deleted out of the vast storage blocks.

#### What you expected to happen: 
I expect all of my items in my vast storage to not be deleted.

#### Steps to reproduce: 
I'm not entirely sure but this is what I presume.

1. Have a basic RS system set up, involving vast storage blocks connected to it with external storage cables
2. Put items into the vast storage blocks
3. Log out and into world until items are gone
...

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge: 12.18.3.2215
- Refined Storage: 1.2.18

Does this issue occur on a server? [yes/no] Unknown

#### If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here]

**Comment by raoulvdberge** [comment]
Why are you connecting external storages to a storage block???

**Comment by raoulvdberge** [comment]
Also which storage block are we talking about? RS storage block or  what?? Confusing report.

**Comment by GamingWithAGoose** [comment]
Vast storage unit, I mentioned it multiple times. I saw Sevadus the twitch streamer connect the external storage cable to the vast storage item and it looked like the same principal as connecting a storage bus from AE2 to a Deep Storage unit from MFR. Plus in your wiki it states "The External Storage is a block that provides the system with storage of the inventory or fluid tank in front of the device." Going by your words, I'm doing everything correctly.

**Comment by raoulvdberge** [comment]
What is a Vast storage block? I thought with "vast" you were referring to a storage block that is vast perhaps?

**Comment by raoulvdberge** [comment]
But I heard Simple Labels had some issues with chunk NBT corruption. So I'm suspecting this is a Simple Labels issue. Are you on their latest version?

**Comment by GamingWithAGoose** [comment]
I originally thought it was a simple labels problem too. But I saw this issue happen a lot more with RS previously. I'll switch over to quantum storage and see if it happens.

**Comment by GamingWithAGoose** [comment]
However, I did hear that someones quantum storage items were deleted recently as well

**Comment by raoulvdberge** [comment]
That might be because Simple Labels caused NBT corruption, making the Quantum Storage go corrupt as well.
