### ISSUE TITLE
Wireless Grid + inventorysort of hotbar dupes grid, maybe nukes items

### ISSUE THREAD

**Issue by shabble** [raoulvdberge/refinedstorage#939]
#### Issue description:

When [cpw/inventorysorter](https://github.com/cpw/inventorysorter) is present and user middle-clicks on hotbar while the RS wireless grid is open, grid may be duped and may replace other items in the hotbar.

#### What happens:

Initial Inventory (already duped once by mistake):
![rs-griddupe-inv](https://cloud.githubusercontent.com/assets/97020/22406510/4f303198-e64c-11e6-9984-0a59f1c1bc7e.png)

Sorting hotbar makes moar grids

![rs-griddupe-some](https://cloud.githubusercontent.com/assets/97020/22406512/4f33527e-e64c-11e6-9a75-f352796c5b8b.png)

They're Everywhere!

![rs-griddupe-many](https://cloud.githubusercontent.com/assets/97020/22406511/4f308c4c-e64c-11e6-92bb-f596267e8382.png)

#### What you expected to happen:
 
Grid should remain happily single.

#### Steps to reproduce:
1. install + enable inventorysorter middle-click sort.
2. place wireless grid in hotbar with various other items
3. open grid
4. middle-click anywhere(?) on hotbar.
5. proud owner of a new shiny grid.
...

Note: disabling middle-click sort in inventorysorter config prevents bug from occurring.

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge: 2215
- Refined Storage: 1.2.18
- inventorysorter: 0.10.5+46

Does this issue occur on a server? [yes/no]

unknown. tested in SSP.

#### If a (crash)log is relevant for this issue, link it here:

cross-posted bug report from https://github.com/cpw/inventorysorter/issues/30 until I realised it only seemed to happen with my RS grid.

**Comment by raoulvdberge** [comment]
This is not an RS issue
