### ISSUE TITLE
multiple recipies

### ISSUE THREAD

**Issue by Harith163** [raoulvdberge/refinedstorage#94]
If I have two or more recipies registered for autocrafting the same Item, which pattern will be used?

**Comment by raoulvdberge** [comment]
I have no idea, actually... I might need to make a selecton menu?

**Comment by raoulvdberge** [comment]
Hm, but how will the system know what pattern to take when a subtask is created in another crafting task?!

**Comment by Harith163** [comment]
Taking a cue from the projectE mod, each recipe could have a net value and
the cheaper recipe could be tasked.
The realistic solution will be to detect when the player puts in two of the
same recipe and set a priority.
Higher priority recipes will be prefered but if materials are missing it
would move on to the second recipe in the priority list.
This should be done BEFORE another subtask is scheduled in the primary
recipe.

**Comment by Dracon1023** [comment]
You could have it use the most available resource for the recipe. For instance I 200 spruce wood planks and 10 oak wood planks with both recipes for sticks registered.  It could use the spruce wood one due to the abundance of resources.

**Comment by raoulvdberge** [comment]
Good idea @Dracon1023, this is what I'll most likely be going for.
