### ISSUE TITLE
[Immersive Engineering] Engineer's Hammer Auto Crafting

### ISSUE THREAD

**Issue by AragurDEV** [raoulvdberge/refinedstorage#941]
#### Issue description:
Negative number of Engineer's Hammer appears in storage system if crafting metal plates.

#### What happens:
Autocrafting is not using Enigineer's Hammer (doesn't get damaged) but spawning a negative "ghost" version of it. (Dissapers after reopening the grid)

#### What you expected to happen:
Use Hammer durability and don't spawn this "ghost" items.

#### Steps to reproduce:
1. Install Immersive Engineering
2. Create Autocrafting Recipe for (Electrum) plates.
3. Craft and search in grid for hammer
...

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge: 12.18.3.2215
- Refined Storage: 1.2.18
- Immersive Engineering: 0.10-54

Does this issue occur on a server? [yes/no] yes

#### Screenshot
http://i.imgur.com/H8V3WIJ.png

**Comment by raoulvdberge** [comment]
I can no longer reproduce this in Refined Storage 1.5.24.
