### ISSUE TITLE
Weirdness with Storage Drawers

### ISSUE THREAD

**Issue by fartcannon** [raoulvdberge/refinedstorage#942]
#### Issue description: 
RS prioritizes the closest open storage drawer for placing items, even if there is a further drawer that already has the item in it with open space.

#### What happens:  
Item is placed in closest open drawer to controller regardless of if there is room in the further drawer.

#### What you expected to happen: 
Item is placed in drawer that already contains the item.

#### Steps to reproduce:
1. Place storage controller and drawers (we put 10 down in a 5x2 grid).  Attach to basic RS setup.
2. Put 1 iron ingot into furthest drawer manually.
3. Use RS grid to place a stack of iron into storage - this will place it into the closest drawer instead of the one that already has the iron.
...

Note:  This does not seem to be a Storage Drawer issue.  If you do the above with an AE2 or Actually Additions setup (or even using a chest with an Ender IO item conduit dumping items into the drawer), you will end up with all of the iron in the drawer that already has iron in it instead of the above.

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge: 12.18.3.2185
- Refined Storage: 1.2.14
- Storage Drawers: 3.5.16

Does this issue occur on a server? [yes/no]  Yes.

**Comment by raoulvdberge** [comment]
That is intended behavior, just change the priority.

**Comment by VT-14** [comment]
How does the priority factor in when the setup only has 1 external storage on a drawer controller?

**Comment by raoulvdberge** [comment]
First available inventory. I'm not changing this to guarantee consistent behavior across the mod, just lock the drawers / prefill them to avoid these types of situations.
