### ISSUE TITLE
Server Crash due to potion autocrafting

### ISSUE THREAD

**Issue by CamaroKing59** [raoulvdberge/refinedstorage#943]
#### Issue description:
Server Crash due to a potion pattern 
#### What happens:
the server lags out then restarts
#### What you expected to happen:
don't know
#### Steps to reproduce:
1. n/a
2.n/a
3.have no idea its a server crash not something i did 
...

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge:12.18.3.2185
- Refined Storage:1.2.18

Does this issue occur on a server? [yes/no]
yes
#### If a (crash)log is relevant for this issue, link it here:
Crash Report : http://pastebin.com/4521vMbR
[pastebin/gist/etc link here]

**Comment by way2muchnoise** [comment]
`Description: Watching Server`  It is the watch dog killing the server. It happens when something is taking to long. With out a [profile](https://refinedstorage.raoulvdberge.com/wiki/profiling) of what you are doing there isn't much to do, sadly.

**Comment by CamaroKing59** [comment]
is there any way around it?

**Comment by way2muchnoise** [comment]
Without knowing the exact issue not really. Generally speaking these could happen on large crafting tasks, but I've seen them happen before on automated crafting tasks (either using craft on redstone signal or using the crafting upgrade) as those will happen on the main thread.

**Comment by raoulvdberge** [comment]
Closing due to missing profiling report.
