### ISSUE TITLE
Search Box Focus

### ISSUE THREAD

**Issue by FireBall1725** [raoulvdberge/refinedstorage#944]
#### Issue description:
When you open any of the terminals, the default focus is on something other than the search text box

#### What you expected to happen:
I think it would flow better if the search box has focus by default when you open the terminal, this way you can just right click and type, instead of having to click on the search box.

#### Steps to reproduce:
1.
2.
3.
...

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge:
- Refined Storage:

Does this issue occur on a server? [yes/no]

#### If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here]

**Comment by way2muchnoise** [comment]
You just need to change the mode of the text box with one of the buttons of the left hand side when opening the grid. Either `normal (autoselected)` or `JEi (autoselected)` will do exactly what you need. You can always consult the [wiki for more information](https://refinedstorage.raoulvdberge.com/wiki/grid).
