### ISSUE TITLE
Weird item stack sizes and drive usages

### ISSUE THREAD

**Issue by Anaerin** [raoulvdberge/refinedstorage#945]
#### Issue description:
Some disks are being emptied too far. For example, I have a 64k storage disk with "Stored: -103/64000"
![2017-02-01_09 38 34](https://cloud.githubusercontent.com/assets/989271/22513568/3c0245b2-e862-11e6-9786-4bc65712e117.png). 

![2017-02-01_09 39 42](https://cloud.githubusercontent.com/assets/989271/22513646/70ab1f14-e862-11e6-8554-d12fdf0af3d2.png)

And sometimes Interfaces become clogged with 0-item stacks (literally, red number saying 0 ![2017-02-01_09 33 43](https://cloud.githubusercontent.com/assets/989271/22513477/f8a944fa-e861-11e6-860c-e1a007f06f4f.png)).

#### What you expected to happen:
Well, not that.

#### Steps to reproduce:
Difficult to say, but EIO and IC2 machines both make the 0-item stacks (in fact, EIO made some -100 stacks, which could be picked up repeatedly as full item stacks, so something is very wrong there - integer overflow on stack sizes?)

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge: 12.18.3.2185
- Refined Storage: 1.2.17

(DireWolf20 1.10 pack v1.4.1)

Does this issue occur on a server? yes

#### If a (crash)log is relevant for this issue, link it here:

No crashing, fortunately.

**Comment by raoulvdberge** [comment]
The disk issue is a duplicate of #520 and the 0 stack issue is caused by an external mod inserting invalid stacks in the inventory? I don't see how that is an RS issue.

**Comment by Anaerin** [comment]
Except that the 0 stacks are coming from both IC2 and EnderIO. Which have nothing in common, that I'm aware of, and this doesn't happen with items being inserted into any other mod.

**Comment by raoulvdberge** [comment]
RS doesn't transform stacks into 0-size stacks, something is inserting an invalid stack into the RS inventory.
