### ISSUE TITLE
For 1.11 branch

### ISSUE THREAD

**Issue by raoulvdberge** [raoulvdberge/refinedstorage#946]
- [x] Backport 75e3d69ccf45b0655d929f166e2bd7e21c548d8c
- [x] Backport 7ceea1d6a6b9e40ed7ba889e7180fb9b313fb2c6
- [x] Investigate the Cyclops insertion issue (external storage + disk manip lag, only happens on 1.11 apparently?)

Thank you ^.^

**Comment by way2muchnoise** [comment]
24f8c88f7e905f228176910d55a003a8f9d23b80 and afd38354e308bad62a93c0a104e22132fea93f09
