### ISSUE TITLE
Refined Storage update bug?

### ISSUE THREAD

**Issue by linktlh** [raoulvdberge/refinedstorage#947]
#### Issue description:
Refined storage systems Wrong
#### What happens:
After bringing over data Enderio EnderStorage playerdata SimpleAchievements stats level.dat level.dat_old then placing down RS systems either nothing is in the drives or none of the items are correct what we did as a server was reset the map but carried over items when testing bags and other items that allow storage they worked flawlessly RS seemed to work but after putting it on the server.. well it happened. I'm sorry if this is a waste of time for you to look at I may have not pulled over a refined storage file or something.. but everything else worked for bringing over items
#### What you expected to happen:
Everything in the RS systems to be there and work fine.
#### Steps to reproduce:
1. Create RS system
2. Put stuff into the drives
3. Take data playerdata stats level.dat and level.dat_old and put it into a world file
4. put the world file into a fully reinstalled server
5. load server
6. place RS system down
7. Look inside

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge: 1.10.2-12.18.3.2215
- Refined Storage: refinedstorage-1.2.17 updating to refinedstorage-1.2.18

Does this issue occur on a server? yes

**Comment by linktlh** [comment]
Turns out it was a bug of some sort I don't think its part of RS.

**Comment by raoulvdberge** [comment]
That isn't a bug, the drives have to be in a player inventory to correctly transfer them when using player.dat files. Otherwise, you have to transfer the chunk with the disk drive tile entity.

**Comment by linktlh** [comment]
I did close it because it didn't seem to be a bug but it was in our inventorys I'm still not really sure what happened.

**Comment by raoulvdberge** [comment]
Did you force quit the server after inserting them in your inventory? Then your server might not have saved correctly the data to disk.

**Comment by linktlh** [comment]
Of course not, we saved off the server the. Shut it down then took the player.dats and the other key files that are required to keep the IDS the same and it just happened.

**Comment by raoulvdberge** [comment]
Weird. The drives should still be in your inventory after transferring the player data, but I still don't think it would be an RS issue.

**Comment by linktlh** [comment]
No the drives where there, but everything in them where gone or had this weird thing basically everyone had the exact same things in the drives weird numbers of thing 4.2k creative turbines ect removing the world and adding a few other unneeded files for some weird reason fixed it.

**Comment by raoulvdberge** [comment]
Then there was an ID mismatch.

**Comment by linktlh** [comment]
That's what I though.. At first but as I looked into people's RS Systems they had EXACTLY the same items.. Same numbers same everything either that or they where empty if you Tryed to take anything out of the systems you'd be kicked instantly
