### ISSUE TITLE
[Feature Request] Crafter Priorities / Parallel Auto-crafting

### ISSUE THREAD

**Issue by vsSchweitzer** [raoulvdberge/refinedstorage#948]
I had an idea in mind that Crafters could have a priority, so when you order to craft something that is present in multiple crafters, the system first looks for crafters in higher priority, so if you have two ways of making a resource, but one is cheaper you can make that one in a higher priority and the other recipe will only be used when you don't have the resources for it. But another nice feature that can come with this system is that crafters with the same priority split the crafting, so if I order 10 cobblestone and there are 5 crafters that have the same priority and the cobblestone recipe, each of them handles 10/5 which is 2, making the process parallel and so speeding it up.

**Comment by raoulvdberge** [comment]
I don't like the crafter priority idea, but the parallel auto-crafting is already implemented in 1.11.

**Comment by NIKITAzed** [comment]
How come you don't like this idea ? I was hoping for something like this too, with Mystical Agriculture and Ender IO alloys, so it can alloy what it can and use mystical agriculture as overflow

**Comment by SkyDev125** [comment]
I dont think the crafters should have a priority specifically for that reason, but I think the PATTERs (recipes) should have a priority, so when the system goes and looks after the correct recipe to make the material you requested, it can then see "oh I have many ways of doing this material, what is the highest priority of it?  this one! so it is the preferred method! I'm gonna do it then"


I think this is possible to do, and would be a good idea,

giving priority to patterns that is.
