### ISSUE TITLE
Fatal error when looking at Disk Drive

### ISSUE THREAD

**Issue by scerion** [raoulvdberge/refinedstorage#949]
#### Issue description:
Sky Factory 3.0.6, I had my disk drive that had 5 64k drives in it, once 3 of them go completely full, if you *look* at the block (not even open it, but when Waila pops up its tag) you get an immediate crash, and will loop until you can manage to look away from the block.  Turning off Waila will allow you to look at the drive.  
#### What happens:
java.lang.RuntimeException: Tried to read NBT tag that was too big; tried to allocate: 2097157bytes where max allowed: 2097152
Fatal error, client crashes but not server.  Will continue to loop until you can look away or turn off Waila
#### What you expected to happen:
Be able to look or access the disk drive
#### Steps to reproduce:
1. At least 3 completely full 64k drives. 
2. Look at disk drive with Waila turned on.

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge: 12.18.3.2215
- Refined Storage: 1.2.18

Does this issue occur on a server? [yes/no]
Yes
#### If a (crash)log is relevant for this issue, link it here:
Game Output window log: http://pastebin.com/z6Qsx3i2
Couldn't find a log file that contained the crash info.  Please let me know if you need more and I will do my best to provide.

**Comment by raoulvdberge** [comment]
This is most likely HWYLA

https://github.com/TehNut/HWYLA/issues/42

Can you try updating that mod?

**Comment by scerion** [comment]
Ah dangit! I tried looking for a dupe ticket in here :(  Will try here momentarily and report back.

**Comment by scerion** [comment]
Hooray! All is working well, my apologies for mixing up where the issue was coming from.  Thanks!

**Comment by raoulvdberge** [comment]
Don't worry!

**Comment by darkmdbeener** [comment]
just a note Raoulvdberge this happens with other mods also. Such as the Ironbackpacks https://github.com/gr8pefish/IronBackpacks/issues/148 not that it is on you but just so you know if someone brings it up later.
