### ISSUE TITLE
Crash on opening crafting grid

### ISSUE THREAD

**Issue by GoldenZdude** [raoulvdberge/refinedstorage#950]
#### Steps to reproduce: Honestly I dont know if you will be able to reproduce this issue with refined storage alone. I will provide a link to an imgur album with all the mods I have installed on the intance
1. 
2.
3.
...

#### Version (Make sure you are on the latest version before reporting): 

- Minecraft: 1.10.2
- Forge: 12.18.3.2221
- Refined Storage: 1.2.20

Does this issue occur on a server? [yes/no] no

#### If a (crash)log is relevant for this issue, link it here:

http://pastebin.com/pMycsXfE

Modlist: http://imgur.com/a/qvvnC

**Comment by raoulvdberge** [comment]
This crashed is caused by Bibliocraft. RS tries to get the item name, but Bibliocraft crashes. You might want to report this to them.
