### ISSUE TITLE
Constructor not working in "All the mods 2" pack

### ISSUE THREAD

**Issue by Maskeno** [raoulvdberge/refinedstorage#951]
#### Issue description:
The constructor is not placing any blocks in front of it while set up properly (even looked at youtube videos to make sure I was doing it right.)

#### What happens:
Nothing

#### What you expected to happen: 
The constructor to place the block it's set to from my inventory as defined by the interface option. IE: I set it to place stone, I have plenty of stone, it doesn't place stone. Same with dirt, wood, etc.

#### Steps to reproduce:
1.Place constructor
2.link to storage system
3.tell it to place blocks
...

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.11.2
- Forge:latest
- Refined Storage:latest

Does this issue occur on a server? [yes/no]
No
#### If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here]

**Comment by raoulvdberge** [comment]
Can you send me a screenshot of your setup?

**Comment by Joshwoo70** [comment]
yes.. Forge : latest RS version : latest... it is very helpful *sarcasm*

**Comment by InusualZ** [comment]
They maybe using FTB Utilities of some sort maybe?

**Comment by raoulvdberge** [comment]
https://refinedstorage.raoulvdberge.com/wiki/constructor

"My Constructor isn't doing anything!"

**Comment by Bakamon0** [comment]
Constructor not placing block when hooked up to a Security Manager with a card inside.  Works with no card in.  Is there a config or other option I need to enable to make it work with the card inside?

**Comment by raoulvdberge** [comment]
Create a new issue please!
