### ISSUE TITLE
Crash on world load

### ISSUE THREAD

**Issue by raoulvdberge** [raoulvdberge/refinedstorage#952]
```
java.lang.NullPointerException: Ticking block entity
	at com.raoulvdberge.refinedstorage.apiimpl.network.node.NetworkNode.hashCode(NetworkNode.java:200)
	at java.util.HashMap.hash(Unknown Source)
	at java.util.HashMap.put(Unknown Source)
	at java.util.HashSet.add(Unknown Source)
	at com.raoulvdberge.refinedstorage.apiimpl.network.NetworkNodeGraph.lambda$rebuild$0(NetworkNodeGraph.java:54)
	at com.raoulvdberge.refinedstorage.apiimpl.network.NetworkNodeGraph.rebuild(NetworkNodeGraph.java:66)
	at com.raoulvdberge.refinedstorage.tile.TileController.func_73660_a(TileController.java:264)
	at net.minecraft.world.World.func_72939_s(World.java:1801)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:621)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:720)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:624)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:149)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:482)
	at java.lang.Thread.run(Unknown Source)
```
It's rebuilding the graph, trying to put the network node in the map, but there is no world present......

**Comment by ibedek** [comment]
Had similar issue. Put bunch of recursive autocrafting, got outOfMemory exception, restarted world and after some time got this:

Description: Ticking entity

> 
> java.lang.ClassCastException: com.raoulvdberge.refinedstorage.tile.TileWirelessTransmitter cannot be cast to com.raoulvdberge.refinedstorage.tile.TileMultipartNode
> 	at com.raoulvdberge.refinedstorage.block.BlockCable.hasConnectionWith(BlockCable.java:158)
> 	at com.raoulvdberge.refinedstorage.block.BlockCable.func_176221_a(BlockCable.java:133)
> 	at com.raoulvdberge.refinedstorage.block.BlockCable.addCollisionBoxToListDefault(BlockCable.java:232)
> 	at mcmultipart.block.BlockCoverable.func_185477_a(BlockCoverable.java:134)
> 	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_185908_a(BlockStateContainer.java:438)
> 	at net.minecraft.world.World.func_184144_a(World.java:1252)
> 	at net.minecraft.entity.Entity.func_70091_d(Entity.java:639)
> 	at net.minecraft.entity.EntityLivingBase.func_70612_e(EntityLivingBase.java:1795)
> 	at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:2217)
> 	at net.minecraft.entity.EntityLiving.func_70636_d(EntityLiving.java:577)
> 	at net.minecraft.entity.monster.EntityMob.func_70636_d(SourceFile:47)
> 	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2013)
> 	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:295)
> 	at net.minecraft.entity.monster.EntityMob.func_70071_h_(SourceFile:52)
> 	at ganymedes01.headcrumbs.entity.EntityHuman.func_70071_h_(EntityHuman.java:161)
> 	at net.minecraft.world.World.func_72866_a(World.java:1964)
> 	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:839)
> 	at net.minecraft.world.World.func_72870_g(World.java:1934)
> 	at net.minecraft.world.World.func_72939_s(World.java:1750)
> 	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:620)
> 	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:709)
> 	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387)
> 	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
> 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
> 	at java.lang.Thread.run(Thread.java:745)

Had same issue with External Storage, Exporter and Crafting monitor, after deleting them with NBTExplorer, got crash few seconds after starting server

> Description: Ticking entity
> 
> java.lang.NullPointerException: Ticking entity
> 	at mcmultipart.block.BlockCoverable.func_185477_a(BlockCoverable.java:139)
(and many more lines)

I can post entire crash log with world save (before messing with NBTExplorer

**Comment by raoulvdberge** [comment]
Update to the latest RS version, it fixes the cable crashes.
