### ISSUE TITLE
Dupe with Storage Drawers, Actually Additons

### ISSUE THREAD

**Issue by dredhorse** [raoulvdberge/refinedstorage#953]
#### Issue description: 

Looks like duping occurs, Item routed strange ways together with Storage Drawers:

#### What Happens:

Item (Crystalized Canola Seeds) where pushed via EnderChest - > EnderIO Conduit -> Actually Additions Item Interface via Laser into Storage Drawer Controller. Refined Storage was hooked up via Interface to Lasergrid and via external Storage to Slave Controller. Result is lots of items. Same goes for Carrots, Netherwart, Ender IO Conduits.

Note: Non of those are in the Storage Drawers.

#### What you expected to happen:

100 Into Enderchest, 100 into Grid.

#### Steps to reproduce:

Not able too :-(

#### Version (Make sure you are on the latest version before reporting):

Direwolf20 ModPack 1.4.1

Does this issue occur on a server? [yes/no]

yes

**Comment by raoulvdberge** [comment]
Can you take a video of this? I'll reopen as soon as you do. The issue description is very confusing, and you're not providing any good steps to reproduce this.

**Comment by dredhorse** [comment]
Understandable, as I said, I can't reproduce it.

I have just stacks of carrots, item conduits, netherwarts etc as proof :-) I also don't have the setup anymore. As it is a server we didn't really notice this issue till we already changed a lot, we just wondered where the 2,5 K crystalized canola came from as we only had made 2 stacks or so.
