### ISSUE TITLE
Strange Behavior with Storage Drawers

### ISSUE THREAD

**Issue by dredhorse** [raoulvdberge/refinedstorage#954]
#### Issue description:

External Storage attached to Storage Drawer Controller / Slave with Priority 10 and 5 (two Sets of Storage Drawers)

#### What happens:

Not all items which are able to go into the drawers go into the drawers. It may be that this happens together with Void Upgrades and the Storage Drawers being "full".

Pulling Items out of the Grid will also pull items from higher priority first.

#### What you expected to happen:

All items go into drawers if possible even if voided, if pulling from grid items from grid should be pulled first than the storage with higher priority.

#### Steps to reproduce:
1. Create Storage Drawer with Controller
2. Attach External Storage Connector to Controller
3. Increase Priority
4. Add amount of items
5. Check if all items are in the drawer.
6. Add void upgrade to drawer
7. Add more items to grid
8. Check if more items are in grid than in the drawer.
...

#### Version (Make sure you are on the latest version before reporting):

Direwolf20 Mod Pack 1.4.1

Does this issue occur on a server? [yes/no]

yes

**Comment by blackdrag** [comment]
I see this too on SF3

**Comment by raoulvdberge** [comment]
This is intended behavior. If you increase the priority, it will insert into the drawers first. And if the drawer is voiding, it simply removes the items.
