### ISSUE TITLE
RS General Poor Performance

### ISSUE THREAD

**Issue by Rob5Underscores** [raoulvdberge/refinedstorage#955]
#### Issue description:
RS causes huge TPS issues running SkyFactory 3 (3.0.6)
#### What happens:
Autocrafting, external storage (on colossal chests and other things) cause lag.

As far as I can tell, since I've asked as many players as I can to remove their autocrafting setups, the lag must be from something else - as elaborated on below.

#### Steps to reproduce:
Unlike, I assume most, of the reports I have backported the newest RS build 20 to 18 so that it will run in the hopes of getting the fabled performance boost, no such luck. There are already plenty of issues noting the poor performance but posting this with my data + telling you that not resolved on build 20. (also backported CC). This has been entirely stable -> fixed the null storage stuff.

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge: 2202
- Refined Storage: 1.2.20
- CommonCapabilities: 1.3.1 (backported to 1.3.0)

Does this issue occur on a server? yes

#### If a (crash)log is relevant for this issue, link it here:
https://gyazo.com/155bb46d74f1fb231d3605a90151778a
Where most of the unexpected TPS drop comes from.

**Comment by way2muchnoise** [comment]
Why are you backporting features? And a screenshot is worth next to nothing, please share the nps file so I can actually see what is going wrong.

**Comment by Rob5Underscores** [comment]
Not sure what an NPS is or how to get it from warmroast.
Here's the warmroast.

I backported because I wanted to see if it was fixed, which it wasn't. Most mod developers ignore issues that aren't present in latest build (despite me being tied to whatever the modpack uses).

**Comment by way2muchnoise** [comment]
I have no access to that warmroast. No clue if warmroast has any export options? Otherwise you might want to read our [wiki page about profiling](https://refinedstorage.raoulvdberge.com/wiki/profiling).

And I still have no clue what you have done when you say "backported"

**Comment by Rob5Underscores** [comment]
I will install that and get you results ASAP. In the meantime (5 minutes) would you be willing to look at the warmroast again - it didn't work because I had terminated the process, running again now.

By backported, I mean: compiled source from build 20 with 18 version number. I know you will hate this but it has been absolutely necessary to fix things ahead of pack updates, especially in 1.10 (with many) where there are so many issues.

**Comment by raoulvdberge** [comment]
How does compiling the source of .20 with another version number matter? Why don't you just use .20?

**Comment by way2muchnoise** [comment]
Why would you do that? Compile build 20 with version 18, that makes no sense at all. 

Also I still don't have access to that page with the warmroast. I get a refused connection.

**Comment by Rob5Underscores** [comment]
Because then players must also change to build 20 to be able to join. This isn't a private server, I can't very well expect people to do it themselves. Sometimes getting them on one version of SkyFactory is challenge enough.

**Comment by raoulvdberge** [comment]
That might be potentially dangerous: if the client <-> server protocol changed in those 2 versions, you'd end up getting in trouble.

**Comment by Rob5Underscores** [comment]
@raoulvdberge not sure what sort of danger you mean. If you mean crash-wise, the crashes have been improved (as I mentioned some of the storage null crashes I had were fixed). If you mean potential data-loss-wise then I test the stuff before I put it on production servers and perform regular backups so not worried on that front.

@way2muchnoise link should be populated now. Profiler has run for a few mins (old profile was run for a bit longer).

**Comment by raoulvdberge** [comment]
It's not only about crashes or data-loss, sometimes clients send requests to servers and if the server doesn't anticipate the request correctly, it might cause performance issues.

Thus, this makes your profiling report unreliable. But we'll look at it.

**Comment by Rob5Underscores** [comment]
@raoulvdberge My server is about to have an automated restart. I've reverted to RS 18 and CC 1.3.0.

I'll re-run profiles and sampler will be added too, so I can give .nps

**Comment by raoulvdberge** [comment]
Sorry, RS 18 doesn't have the collosal chests performance fixes yet. We're only interested in profiling reports from the latest version.

**Comment by way2muchnoise** [comment]
You do know that the heaviest TE is the RF crafter
![](http://puu.sh/tN68R/b47cc7a865.png)

Also `isAreaLoaded` takes 20% of the main thread time, and I have no clue why not even remotely related to RS. (I don't wanna blame SpongeForge, but I have never seen this issue before)
![](http://puu.sh/tN6mu/b8637b19b3.png)

**Comment by Rob5Underscores** [comment]
@raoulvdberge are you kidding me?

I provide RS 20 data - it's unreliable. I switch to RS 18 and it's invalid.

The external storage/colossal storage lag issue does exist on RS 20.

**Comment by raoulvdberge** [comment]
We want RS 20 data for clients that are on 20 (not 18).

**Comment by way2muchnoise** [comment]
Then actually produce it with the builds we provide. We can't just have anyone building their own code and just say it is .20.

Although if you have issues please profile them like it states on the wiki and make an issue.
