### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by TH3GOD88** [raoulvdberge/refinedstorage#956]
#### Issue description: 
When two crafters are set-up with the same recipe for printed silicon or other printed items from AE2.

#### What happens: 
They will not send to both inscribers.

#### What you expected to happen: 
For them to send to both inscribers.

#### Steps to reproduce:
1. Make a two of the same crafting recipe
2. Place two inscribers down with crafters connected to them
3. Order for printed silicon or other printed things.
...

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge: 12.18.3.2215
- Refined Storage: 1.2.20

Does this issue occur on a server? No

#### If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here]

**Comment by TH3GOD88** [comment]
This is with having each inscriber set to one type of item.

**Comment by way2muchnoise** [comment]
There is no parallel crafting in 1.10.2, that is a 1.11.2 feature.
