### ISSUE TITLE
Crash on Constructor Placing Heads

### ISSUE THREAD

**Issue by Meek97** [raoulvdberge/refinedstorage#958]
When ever a constructor tries to place a head down, it crashes the game
Once this happens I can't load the world, becuase it tries to place the head, but can't causing the game to instantly crash.

- Minecraft: 1.10.2
- Forge: 1.10.2 - 12.18.3.2221
- Refined Storage: 1.2.20

Crashlog:
http://pastebin.com/Q3mAWuAS

**Comment by raoulvdberge** [comment]
I'll look into this, remove the block with MCedit for now.
