### ISSUE TITLE
REQ: Crafters (1.10.2)

### ISSUE THREAD

**Issue by JFMillerUSA** [raoulvdberge/refinedstorage#959]
Requesting for Crafters, either logic system for repeat patterns for same item with different recipes. (ie. Iron Ingot, pattern 1 crush Iron Ore then smelt Iron Dust if no Iron Ore use pattern 2 craft from Iron Essence if no Iron Essence use pattern 3 craft from Iron Block or Iron Nuggets.)

Or maybe add Priority system on Crafters.

And I know there is a separate mod out there but can you add Wireless Crafting Grid

TIA

**Comment by raoulvdberge** [comment]
I don't understand your first suggestion. Can you clarify?

**Comment by VT-14** [comment]
If I understand correctly, he wants a crafting priority system similar to #948 (which you said no to).

He also asked for a Wireless Crafting Grid, and you have said no to that several times already.
