### ISSUE TITLE
I can't put items into RS system with grid or import bus

### ISSUE THREAD

**Issue by ytteentech** [raoulvdberge/refinedstorage#961]
#### Issue description: 
I can't put items into RS system with grid or import bus

#### What happens: 
When I Shift-Click items in my inventory while in a grid, they do not go into the drives. I tried picking the item up and clicking into the grid but that didn't work either. I tried putting them into a chest (which worked :P) that was attached to an import bus but the import bus wouldn't pull them in. I have more than enough space to put the items in the drive. I can also take items out.

#### What you expected to happen: 
the items were supposed to go into the drive...

#### Steps to reproduce:
1. Right-Click on Grid
2. Shift-click on item in your inventory
3.
...

#### Version (Make sure you are on the latest version before reporting): 
1.2.17 (Direwolf20 1.10 Pack Version 1.4.1 and 1.3.2 (issue happened in both versions)

- Minecraft: 1.10.2
- Forge: 12.18.3.2185
- Refined Storage: 5 lines up

Does this issue occur on a server? [yes/no]
no
#### If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here]

**Comment by way2muchnoise** [comment]
Could you share a screenshot of your setup?

**Comment by ytteentech** [comment]
![2017-02-06_11 36 40](https://cloud.githubusercontent.com/assets/25568624/22658897/5246464a-ec61-11e6-80b4-d60bc6793fbf.png)
![2017-02-06_11 36 06](https://cloud.githubusercontent.com/assets/25568624/22658898/52490ef2-ec61-11e6-9fde-a8b3058ce11d.png)
![2017-02-06_11 36 36](https://cloud.githubusercontent.com/assets/25568624/22658899/52494cbe-ec61-11e6-9786-34f4aa45bc6f.png)

**Comment by way2muchnoise** [comment]
Could it be a keybinding issue? To be fair I never had this one happen :p

**Comment by ytteentech** [comment]
It was working with no problems then all the sudden it stopped working. All my keybindings related to this are fine.

**Comment by ytteentech** [comment]
Update: I can shift-click in stuff if it goes to an external storage but not the drives

**Comment by ytteentech** [comment]
Update: I am an idiot, My drives were whitelisted instead of blacklisted
