### ISSUE TITLE
Worldcrash on autocrafting

### ISSUE THREAD

**Issue by kinglibero** [raoulvdberge/refinedstorage#962]
#### Issue description:

My world just crash if i try to autocraft something big like a 64k storage cell

#### What happens:

I just want to autocraft a 64k storage cell and it worked, so i tried to craft 3 of them and it also stared but than the game crashed. 
Also happends on a server, i tried after the crash
now the world crash on every try to open the world. 

#### Steps to reproduce:
1. Start a big crafting recipe no matter what just big
2. see your world crashing
3. cannot open the world again 
R.I.P:
...

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge: forge-12-18-3-2215
- Refined Storage: 1.2.20

Does this issue occur on a server? [y]

#### If a (crash)log is relevant for this issue, link it here:

http://pastebin.com/swp2p5uJ

**Comment by raoulvdberge** [comment]
Update HWYLA.

**Comment by kinglibero** [comment]
Thanks a lot ! very nice mod btw. :) #fixed
