### ISSUE TITLE
64K storage Disk & Storage Part giving circular dependency EDIT: also other parts

### ISSUE THREAD

**Issue by Muszkal** [raoulvdberge/refinedstorage#963]
#### Issue description:

When trying to auto-craft 64k disk and part, i get the error circular dependency.
can auto-craft all of the lower tiers

EDIT: when crafting for example speed upgrades(from refined storage), I can craft 1 but 2 gives me the same circular dependency issue.

EDIT2: found the issue. i need iron for the recipe and i have 2 autocrafting. one is ingot to block and on is block to ingots. didn't have either so that what caused the loop.

#### What happens:
i can't craft them.
#### What you expected to happen:
autocraft them.
#### Steps to reproduce:
1. get patterns for all the parts for the 64k disk
2. try to autocraft it
3. get error.
...

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge: 7.1.6235.2434
- Refined Storage:1.2.18

Does this issue occur on a server? [yes/no]
no

**Comment by raoulvdberge** [comment]
Watch this:

https://www.youtube.com/watch?v=02ueSqlzsow
