### ISSUE TITLE
Automatically Filling Bottles for Crafting Recipes

### ISSUE THREAD

**Issue by amethystdragon** [raoulvdberge/refinedstorage#964]
It would be nice to automatically craft bottles of water similar to how the Refined Storage system can automatically craft buckets of water.

**Comment by raoulvdberge** [comment]
Sidenote: it's important that the conversion from water -> bottle doesn't consume the water, it doesn't use up the water when doing this manually either.

**Comment by bcrotty** [comment]
Does this not work in 1.2.26? I'm playing SkyFactory 3, and it's not working for me.

**Comment by raoulvdberge** [comment]
1.10.2 is unmaintained.

**Comment by bcrotty** [comment]
@raoulvdberge I don't expect a fix if it doesn't work, but I'm just wondering if I'm doing something wrong or if I shouldn't expect it to work in 1.10.2.

**Comment by raoulvdberge** [comment]
This feature does not work on 1.10.
