### ISSUE TITLE
exporter to interface creates network

### ISSUE THREAD

**Issue by blackdrag** [raoulvdberge/refinedstorage#966]
#### Issue description:
using an exporter to export to a network unifies two networks

#### What happens:
using an exporter to export to a network unifies two networks

#### What you expected to happen:
having the networks still separate

#### Steps to reproduce:
1. crate two separate networks N1 and N2
2. let an exporter from N1 export to an interface of N2
3. one of the controllers drops, because the networks become one

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge: 12.18.3.2215
- Refined Storage: 1.2.18

Does this issue occur on a server? yes

**Comment by raoulvdberge** [comment]
Not a bug, use a buffer chest or something.
