### ISSUE TITLE
RS system refuses to craft pistons / crafting tables and other certain items

### ISSUE THREAD

**Issue by kenbarby** [raoulvdberge/refinedstorage#968]
#### Issue description:
Somewhere during our playthrough our RS system stopped autocrafting certain items. Most prominent of which are the pistons / crafting tables, but other items seem to be affected in a similar way.

#### What happens:
When autocrafting pistons / crafting tables the recipy gets prepared by the RS system and can be viewed in the crafting monitor, but will not finish the step in the crafting proces that will produce the actual pistons / crafting tables. The crafting queue can be cancelled, but will reproduce the bahaviour if tried again. Other items will be crafted as per normal.

#### What you expected to happen:
For the RS system to finish the steps in the crafting queue for pistons / crafting tables.

#### Steps to reproduce:
I am unsure as to the steps to reproduce this behaviour as it surfaced after many hours played. Possibly interactions with other mods (like Storage Drawers or Storage Reborn) may have contributed to the issue. We are still in the process of dismantling our RS system to the point where we can perform meaningful (isolated) tests.

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge: unsure
- Refined Storage: 1.2.18
- Modpack: FTB Presents Skyfactory 3 (v3.0.6)

Does this issue occur on a server? [yes/no]
yes, i can arrange for access if it will help debugging.

#### If a (crash)log is relevant for this issue, link it here:

There is a thread on the Feed The Beast subreddit discussing the issue. it contains a link to an imgur album with screenshots of someone else experiencing the exact same issue:
https://www.reddit.com/r/feedthebeast/comments/5rin9v/problems_autocrafting_in_sf3/

**Comment by way2muchnoise** [comment]
Likely an issue between Storage drawers and ore dict autocrafting. See #885

**Comment by kenbarby** [comment]
This seems to be the issue. Thank you for a speedy response!

**Comment by kenbarby** [comment]
This seems to be the issue. Thank you for a speedy response!

**Comment by raoulvdberge** [comment]
This was fixed in 1.2.19
