### ISSUE TITLE
Crafting Hangs up when crafting multiple items.

### ISSUE THREAD

**Issue by varukasalt** [raoulvdberge/refinedstorage#97]
Crafting randomly stops after sending materials to machines for processing. IE, gold dust is sent to be smelted into an ingot, ingot is smelted and reimported back into the system, but crafting does not continue. Manually removing the item and placing it back in the system will make crafting resume. Happens randomly (doesn't happen every time) but consistently (happens often). Items are being reimported into the system using EnderIO Item Conduits attached to and Interface.

**Comment by raoulvdberge** [comment]
Can't repro on the dev version, when I'll release it let me know if it's fixed

**Comment by raoulvdberge** [comment]
You still having this issue, @varukasalt ?

**Comment by varukasalt** [comment]
Seems to no longer be a problem in the current release.
