### ISSUE TITLE
Disk Drive Lighting Issue

### ISSUE THREAD

**Issue by lurr** [raoulvdberge/refinedstorage#970]
#### Issue description:
The Disks in Disk Drives lose lighting when the block behind has a light value of zero.

#### What happens:
The Disks front face (with smooth lighting enabled) goes dark.

#### What you expected to happen:
I expected the disks front face to obey lighting from the front side.

#### Steps to reproduce:
1. Enable Smooth Lighting
2. Place down Disk Drive
3. Insert some disks
4. Place blocks to make the block behind have a light value of zero.

Demonstration of the bug: [YouTube](https://youtu.be/pdi4gtr2HNM)

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge: 12.18.3.2221
- Refined Storage: 1.2.21

Does this issue occur on a server? [yes/no] This is clientside.

**Comment by mlwyatt** [comment]
This happens with the Disk Manipulator too

**Comment by raoulvdberge** [comment]
@shartte Sorry for pinging you this way, but since you did something similair for the models in AE, would you know what causes this?

**Comment by shartte** [comment]
Uh good question...
How exactly did you implement this? Can you point me to the source?

**Comment by raoulvdberge** [comment]
The baked model:
https://github.com/raoulvdberge/refinedstorage/blob/mc1.11/src/main/java/com/raoulvdberge/refinedstorage/render/BakedModelDiskDrive.java

The regular model:
https://github.com/raoulvdberge/refinedstorage/blob/mc1.11/src/main/java/com/raoulvdberge/refinedstorage/render/ModelDiskDrive.java

**Comment by shartte** [comment]
Okay it's hard to tell from just glancing at the code. I don't know how you are rotating the models around. When the rotation is applied, it's necessary to make sure that the quad facing is correctly rotated as well.

**Comment by roboderpy** [comment]
Pure Optifine issue

With optifine installed:
![blame optifine](https://i.dbot.serealia.ca/2017/12/6fe38c2faa_javaw_2017-11-26_16-45-49.png)
Without optifine installed:
![gud](https://i.dbot.serealia.ca/2017/12/95f2fd37ee_javaw_2017-12-13_22-02-07.png)
![gud2](https://i.dbot.serealia.ca/2017/12/23434c09be_javaw_2017-12-13_21-56-14.png)

**Comment by roboderpy** [comment]
@sp614x do you know why this happens?

**Comment by sp614x** [comment]
This happens because OptiFine disables the Forge lighting pipeline which breaks way too many Optifine features.

More details:
https://github.com/raoulvdberge/refinedstorage/issues/503
https://github.com/sp614x/optifine/issues/298
https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/2489
https://github.com/sp614x/optifine/issues/302

**Comment by raoulvdberge** [comment]
Is there anything I can do RS side?

**Comment by raoulvdberge** [comment]
Closing as this is a optifine issue.

**Comment by ChaoticLogic** [comment]
Workaround:  face south when you place your disk drive.  For whatever reason, the lighting issue with optifine only manifests if you're facing the other 3 directions.

**Comment by lvondevon** [comment]
No, its not just a optifine issue, i hava not installed optifine, and i have too this issue, and much more bigger than that.

**Comment by lvondevon** [comment]
Here is the screenshot:
![2023-01-06_11 48 44](https://user-images.githubusercontent.com/122089126/210975978-693cda73-43f2-4690-b249-ed4c9ee52fd2.png)

I have 281 mods installed :D, maybe some mod causing this??
