### ISSUE TITLE
Filter slots not enough for modpacks

### ISSUE THREAD

**Issue by J4YD3D** [raoulvdberge/refinedstorage#973]
#### Issue description:
As you stated in the answer to another issue, the disk drive has filter slots, but for people playing with modpacks this just isn't enough slots for filtering a whole mod into a drive. You'd need multiple (3) drives just to add in 27 different items, and that's silly. i would like to suggest adding the ability to craft a mod filter or something to put into the filter slots and it will only allow things from that mod into all disks on the drive. though adding a cell workbench-like thing would be great too, as you've stated that AE2 is an inspiration. **Thanks for your time and response, its very much appreciated, and i absolutely love the mod, because i loved AE2**
**EDIT**
In a better view of why i submit this, I've got two networks, one only having Mystical crops stuff going into its storage and the other getting the rest of my items, many different mods. when i use the network transmitter/receiver, it then puts the other mod items into the purely crops storage if i try to put items in via the grid, because there's no way to filter this, and it has got me incredibly frustrated, as i wish to have the networks connected such that i can take and place anything right from one grid, but have the items immediately put into the respective cells. Priority doesn't fix this because then the crops get put into my non crop storage and the only possible fix is either some incredibly complicated workaround that I'm trying to find as of right now, or just have two separate networks, which is disappointing as there's no channel limit, giving the option for one incredibly huge network. 
#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge:12.8.3.2215
- Refined Storage:1.2.18 (using Sky Factory 3)

**Comment by joshuafcole** [comment]
It looks as though the fix for this has been removed? The functionality doesn't appear to work in either importers or external storage anymore, in any of the four combinations of whitelist/blacklist.

Is there any chance to see this (or something similar) return in the future?

**Comment by alexschrod** [comment]
Can confirm, filters are not respected, leaving us with no way to keep enough items out of drives.
