### ISSUE TITLE
Disk Manipulator Big Bug

### ISSUE THREAD

**Issue by PyroSyndicate** [raoulvdberge/refinedstorage#974]
#### Issue description: 
Disk Manipulator bugged my drives.

#### What happens: 
I had drives on my refined system and I wanted to put the drives in one-by-one to check what was on them, so I inserted a 64k disk in the drive and then continued to place all the smaller (16k and 4k) drives with my items on them into the disk manipulator.They were being processed straight away yet the item count was still on them, so I inserted them into the drive. Yet when I checked the Grid the items were gone yet the size available thing on the drive was still indicating they had the data on them, and the items are nowhere to be seen...

#### What you expected to happen: 
I expected my data from my drives to transfer over to the larger 64k drive and the drives I inserted to come out empty.

#### Steps to reproduce:
1. Shift-click drives into the disk manipulator
2.place them into a drive
3.at this point the item count still says your items are on the original disks yet they are bugged with an item count and no items....
...

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- ForgeML: 8.0.99.99
- MC Forge: 12.18.3.2185
- Refined Storage: 1.2.14

if it helps I am playing on the FTB Presents DW20 pack at version 1.3.2

Does this issue occur on a server? [yes/no] Yes 

#### If a (crash)log is relevant for this issue, link it here:
I can not see any reporting server or client side. Not an error or warning and there was no crash.
[pastebin/gist/etc link here]

**Comment by codeurge** [comment]
+1 Actually had this happen to me last night, same pack version; had to rollback a couple hours and won't bother trying this through the disk manipulator again for now.

**Comment by raoulvdberge** [comment]
This is a Forge bug: #843

**Comment by PyroSyndicate** [comment]
The same thing just happend to every fricken disk in my whole network
(x127) all my items are gone. And it happend just by having the bugged
drive in my inv... how do I fix my drives??

**Comment by PyroSyndicate** [comment]
Could you please try and provide a way for me to fix this? or who do i contact from the forge team... this is weeks of work just wasted.....

**Comment by raoulvdberge** [comment]
Restore from backups. If you  don't take backups of your world, you are doing something wrong. And no, I can't tell a way to fix this since I have no idea what causes the problem in Forge.

**Comment by PyroSyndicate** [comment]
We have world file backups and even when running from them the discs have still some how not been working.
