### ISSUE TITLE
Unable to join world 

### ISSUE THREAD

**Issue by pixar02** [raoulvdberge/refinedstorage#978]
#### Issue description:
server crash due crafting overload?

#### What happens:
I recentely asked my Refined storage system to craft Quaddouble compressed cobblestone. I know form expirience that I can't put all the patterns in the same crafter becaus it will overload the crafter and crashes (for some reason). So I split the patterns in 3 crafters. asked for it to craft and I see the double and triple compressed apreing but then it crashes. I lose my conection on my singelplayer world. Every time I try to join the world now I loe conection again. Every time I do so I can see the textures of the RS-sytem. and it looks like my disks are full. Could this be a bug?

#### What you expected to happen:
Some way to get back in my world.

#### Steps to reproduce:
Read the above.
1. ... 
2. ...
3. ...
...

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2 (Skyfactory 3)
- Forge: 12.18.3.2215
- Refined Storage: 1.2.18

Does this issue occur on a server? [yes/no]
Yes and no.

#### If a (crash)log is relevant for this issue, link it here:
[http://pastebin.com/8FBmgzzh]

**Comment by phit** [comment]
#673
