### ISSUE TITLE
Ticking block entity error caused by relay crashes client/server

### ISSUE THREAD

**Issue by iansheridan** [raoulvdberge/refinedstorage#979]
#### Issue description:

Server crashes due to `Ticking block entity`. 

#### What happens:

Two relays are activated by a redstone signal sent over EnderIO conduit connectors. The first relay activates fine, but with a 60 tick delay for the second relay. The Server Crashes when the second relay is activated.

[screenshoot](https://www.dropbox.com/s/dc2fs6leet6lmsr/Screenshot%202017-02-11%2008.19.34.png?dl=0)

#### What you expected to happen:

of note, this was working with previous versions.

This is a Wither mob farm where I have constructors building a Wither.

#### Steps to reproduce:

1. place two relays both set i only be active with restone signal
2. the first replay is activated right away and the second one is activated after 60 ticks. Done by any means you can. (I've tried multiple mods including vanilla)
3. send a redstone signal
4. server crashes

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge: 12.18.3.2185
- Refined Storage: 1.2.20

Does this issue occur on a server? yes

#### If a (crash)log is relevant for this issue, link it here:

https://gist.github.com/iansheridan/62f627b0c4e934b6bbeb9c28ed8bc078

**Comment by raoulvdberge** [comment]
This was fixed in 1.2.21, update please

**Comment by iansheridan** [comment]
Oh, thank you. I rely on `nodecraft.com` and `FTB` team for updates of this nature. good to know that it's fixed. I will bug the FTB team and nodecraft.com.
