### ISSUE TITLE
Energy system

### ISSUE THREAD

**Issue by raoulvdberge** [raoulvdberge/refinedstorage#98]
To support as much energy systems as possible, RS needs an energy unit. Every type of power (RF, EU) would then automatically be converted to my system.

This system will be very simple and will just be used for energy stored in controllers and wireless grids.

- What would the conversion rules be for EU (RF would be 1/1)?
- What name would the unit have?

**Comment by dylanwi** [comment]
refined watts(RW)

**Comment by Harith163** [comment]
how about kilogram meter^2 per second ^2 or refined Joules?

**Comment by Dracon1023** [comment]
I like where Harith went with tying it to Einstein's equation of E = mc^2. I think a simplified version of that would be nice.  Maybe like MU for matter unit.

**Comment by raoulvdberge** [comment]
Absolutely no formulas for simplicity sake. As I said, the energy unit would be 1/1 with RF.

**Comment by escman1999** [comment]
why not just make it use RF, instead of making a new energy type?

**Comment by Dracon1023** [comment]
I didn't mean that you should use the formula E=mc^2. I meant having the name for the energy unit be related to that. Such as matter unit, or MU, representing the link between matter and energy. Also I think there should be a new energy type. If RF is used, then it would come into question why the cables can't also power machines that use RF from other mods. Refined Storage should be a purely storage mod, not one used to power other mods.

**Comment by raoulvdberge** [comment]
@escman1999 I don't want to make a new energy type, however I have to. Adding a new energy type will allow easy support for other energy types like EU because I can convert EU/RF to the RS energy system. 

Refined Storage will NEVER add any blocks to get energy out of the controller. It's just used for storage in controllers to allow for EU support.

**Comment by raoulvdberge** [comment]
It would be similair to applied energistics, which has the AE energy unit.

**Comment by Dracon1023** [comment]
@raoulvdberge The base conversion of EU to RF of Forestry's electric engine is 6 EU/t to 20 RF/t.  This can change due efficiency upgrades to a max efficiency of 2 EU/t to 20 RF/t.  I think it may be wise to take this into account when making your EU conversion.

**Comment by Dracon1023** [comment]
Sorry, the previous numbers are incorrect due to FTB forestry wiki being outdated.  It is currently 1 EU becomes 4 RF and with efficiency upgrades it becomes 1 EU to 5 RF in the newest release of Forestry.

**Comment by Dracon1023** [comment]
I tested it myself just now.

**Comment by raoulvdberge** [comment]
thanks

**Comment by 4rz0** [comment]
What about this Tesla API thing?
It already seems to do what you need.

**Comment by JCMais** [comment]
@raoulvdberge you really should take a look at the [Tesla API](https://github.com/Darkhax-Minecraft/Tesla/)

**Comment by raoulvdberge** [comment]
If there is demand for Tesla, I can add it easily with the new system.

**Comment by raoulvdberge** [comment]
Okay, I added support for Tesla. What mods are using it currently, so I can test?

**Comment by JCMais** [comment]
@raoulvdberge Are you answering via email? Because from the looks of it the comments are not being posted here.

About which mods uses Tesla, https://github.com/TechReborn/TechReborn currently does, check the configs for option "Use Tesla" or something like that.

**Comment by 4rz0** [comment]
It's not about "supporting the Tesla power system", but more because that the Tesla API has the ability to support any other power system you throw at it.
That's why I suggested looking at it.

**Comment by raoulvdberge** [comment]
Hm, but that requires the Tesla mod to be installed right?

**Comment by raoulvdberge** [comment]
This has been implemented

https://github.com/raoulvdberge/refinedstorage/wiki/RS-energy
