### ISSUE TITLE
[1.10.2] Dupe in crafting grid returns

### ISSUE THREAD

**Issue by xSparky911x** [raoulvdberge/refinedstorage#981]
#### What happens:
When crafting items in the crafting grid that have more than one item in the recipe and result, you get the result item quantity over and over for each remaining set of items in the recipe grid. For example I was crafting Dark Pressure Plate's (silent). I put 3 wool and 3 Dark Pressure Plates into the crafting grid. If I click the result 3 times I get 6 silent pressure plates back. If I put 3 wool and 50 pressure plates in, I get 147 silent pressure plates back

#### What you expected to happen:
The crafting grid result window should only show 1 item and not how many it is going to make. I feel if it only returned 1 item at a time this would fix the issue while still allowing shift clicking and so on.

#### Steps to reproduce:
1. Put 3 Wool and 3 Dark Pressure Plates from Ender IO in the recipe grid
2. Click the result 3 times
3. You get 6 Silent plates instead of 3
...

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge: 2221
- Refined Storage: 1.2.20

Does this issue occur on a server? [yes/no] Yes

**Comment by way2muchnoise** [comment]
I just takes items out of your RS storage system. It is intended behaviour of the crafting grid.

**Comment by xSparky911x** [comment]
Except I dont have those item in my storage so incorrect. I will link a video later

**Comment by xSparky911x** [comment]
Ok I was unable to get home to record a video on it so I had one of my mods do it for me. Same server, same storage system...

https://youtu.be/FHqxbBBX_MI

**Comment by raoulvdberge** [comment]
Do you have this in a regular crafting table as well? This is probably the recipe itself that is borked.

**Comment by xSparky911x** [comment]
Confirmed. Bug is not isolated to RS. Thank you. Question. What would be the cause of this? I tried removing the recipe with Minetweaker and re-adding. Ender IO would be the cause? Doens;t seem to happen with the regular non silent pressure plate

**Comment by raoulvdberge** [comment]
I have no idea. A bad recipe.
