### ISSUE TITLE
Option to auto-craft missing items in the Crafting Grid

### ISSUE THREAD

**Issue by m3dragos** [raoulvdberge/refinedstorage#982]
This is a feature request, sorry if the format is wrong.

#### Problem:
Imagine trying to craft a chest in your Crafting Grid. You click the "shift-click" the recipe from JEI. You realize you don't have enough wood planks, however the system knows how to auto-craft planks from wood. So you have to go into the search box, search for wood planks and click the item to auto-craft, and then craft it.

#### Solution:
It would be nice to have a button instead of the missing item that, when pressed, auto-crafts that item (assuming the system has the recipe and knows how to auto-craft it).

Here's a picture that might express better what I'm trying to say:
![2017-02-13_00 25 59](https://cloud.githubusercontent.com/assets/17458988/22866706/8252d1ec-f183-11e6-8a00-74eeb46987d4.png)

**Comment by raoulvdberge** [comment]
No, just create a pattern for it.

**Comment by m3dragos** [comment]
"assuming the system has the recipe and knows how to auto-craft it" - What I meant by this is that there already was a pattern in a crafter, so the "Craft" option was already there when searching for items, and it would've been nice if it was also there when trying to create an item and the item was missing.

Not trying to insist, but I think you didn't understand what I meant. If you understood and think it's a bad idea anyway then ignore this :)

**Comment by raoulvdberge** [comment]
I'm talking about the chest in the context of your image. If you need a chest and you don't have enough planks, start a task for a chest.

**Comment by m3dragos** [comment]
Ok, I see. It's just that I often find myself in this situation when crafting something that "isn't worth" creating a pattern for. Like a machine or something that I won't craft again.

**Comment by AEnterprise** [comment]
could maybe a fake itemstack (with size 0) be an option to be added to the grid? this would allow to easely see exactly what's missing instead of having to pull up the recipe again
