### ISSUE TITLE
Can't choose dismantling mode

### ISSUE THREAD

**Issue by KSIxxr3b3l** [raoulvdberge/refinedstorage#987]
#### Issue description: 
when using the wrench it won't switch to dismantling mode

#### What happens: 
I can only switch between rotation and configuration modes

#### What you expected to happen: 
the 3rd mode, dismantling mode isn't working

#### Steps to reproduce:
1. right click with wrench
2. won't go into dismantling mode
3.
...

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge:
- Refined Storage:

Does this issue occur on a server? [yes/no] yes

#### If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here]

**Comment by raoulvdberge** [comment]
This feature is only available on MC1.11
