### ISSUE TITLE
Storage blocks should work with the disk manipulator

### ISSUE THREAD

**Issue by postal291** [raoulvdberge/refinedstorage#988]
Storage blocks (1k, 4k, 16k, 64k) should keep their configuration when broken.
**When breaking storage blocks the whitelist, priority and settings (void excess, etc..) aren't kept.

Storage blocks with items in them (which aren't part of the white list) can be a pain to manage for the OCD storage nerds among us.  Perhaps allowing them to work like a storage disk in the disk manipulator would be the perfect solution?
**Having to build a secondary refined storage network specifically for the purpose of moving these objects to a disk in order to use in a disk manipulator seems like extra unnecessary steps.

Unless of course I'm missing a simple solution to these issues...

**Comment by raoulvdberge** [comment]
> Storage blocks (1k, 4k, 16k, 64k) should keep their configuration when broken.

Use a Wrench in Dismantling mode for this in 1.11 ... except don't because it will void your items (this is already fixed :P)

But Storage Blocks should work with Disk Manipulator yeah, I'm changing your issue title to reflect this.

**Comment by raoulvdberge** [comment]
I changed my mind on this. It's called disk manipulator for a reason. The storage blocks can remain "stupid" blocks.
