### ISSUE TITLE
server crashes

### ISSUE THREAD

**Issue by SodaSpartan** [raoulvdberge/refinedstorage#989]
I've been running a dedicated server with no problems for a while. a day or two ago i build a refined storage system and some time after i started using it my game started getting really laggy. now, for the first time, it actually crashed.

basically my game has been very unstable and when i right clicked my crafting grid the game just crashed. though the crash report blamed the disk drive so call me confuzzled.

#### Steps to reproduce:
1. to reproduce the lagginess all i have to do is play and it persists. ive not been able to reproduce the crash though. 
2. and once i remove the controller to deactivate the network the lag pretty much stops.
3. but as long as the network is active so is the lag

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge: FTBserver-1.10.2-12.18.3.2215-universal
- Refined Storage: 1.2.18

Does this issue occur on a server? yes

**Comment by raoulvdberge** [comment]
For lag issues we need a  profiling report:

https://refinedstorage.raoulvdberge.com/wiki/profiling

**Comment by SodaSpartan** [comment]
thanks for the info, ill remember that next time. fortunately, though i cant explain why. the lag has just vanished! If you like i can still submit a profiling report but I'm not sure it'd do much good now.

**Comment by raoulvdberge** [comment]
Not anymore I guess!
