### ISSUE TITLE
Unable to break the solderer

### ISSUE THREAD

**Issue by andrejsavikin** [raoulvdberge/refinedstorage#99]
**Refined Storage version:** 0.7.8
**Problem description:** When breaking the solderer using a pickaxe(diamond one in my testing) while in survival game mode, the solderer disappears, but nothing drops. After rclicking the space where the solderer was broken, it appears again and it's usable.
**What I expected to happen:** The solderer drops as an item when broken with pickaxe

**Comment by Harith163** [comment]
This reminds of ghost blocks. Is your RS system very extensive or is your
computer unable to handle it?

**Comment by andrejsavikin** [comment]
This is on a server which is well able to handle it, while my RS system is only the solderer. Nothing else from RS is placed in the world

**Comment by andrejsavikin** [comment]
This line seems to have something to do with it, but can't really check in detail atm https://github.com/raoulvdberge/refinedstorage/blob/mc1.9.4/src/main/java/refinedstorage/block/BlockBase.java#L146

**Comment by Lordmau5** [comment]
So basically, this is the crash happens:
http://pastebin.com/4urDDEUB

It seems you're assuming that the `EnumFacing` parameter of `getCapability` is always, **ALWAYS** set.

Just wanted to tell you that it is in-fact marked as `@Nullable`, which means that it *can* be `null`.

You are not checking for that in the code:
https://github.com/raoulvdberge/refinedstorage/blob/mc1.9.4/src/main/java/refinedstorage/tile/TileSolderer.java#L204

I don't know if you have any other tiles that you aren't checking for `null` on the facing, but I suggest you to do that.
___
I've *moaned* at the FortuneOres author already to move his method-call for the capability with a `null` facing underneath the checks **with** a facing.
Code in question:
https://github.com/DemoXinMC/FortuneOres2/blob/master/src/main/java/com/demoxin/minecraft/fortuneores/OreSwapper.java#L36

~ Greets.

**Comment by raoulvdberge** [comment]
Thanks for letting me know. Didn't know it could be null.

**Comment by Lordmau5** [comment]
Came in pretty recent, afaik :)

**Comment by raoulvdberge** [comment]
Fixed in ce367608f7f3b05dc680061ad8104c8154d84bea, however I think the solderer not breaking is a different issue

**Comment by andrejsavikin** [comment]
It's the same thing probably, gonna do the build and try

**Comment by raoulvdberge** [comment]
I highly suspect this is fixed
