### ISSUE TITLE
[Request] Exporter ignores External Storage on the same block

### ISSUE THREAD

**Issue by codewarrior0** [raoulvdberge/refinedstorage#990]
This is basically a request for an old LogisticsPipes feature.

An LP Supplier module or pipe attached to an inventory that also has an LP Provider attached will not use that provider to fulfill its requests. This can be used to keep a given amount of an item in the storage, automatically crafting it if the amount drops below the level set in the Supplier.

An Exporter should be able to decide that there is an External Storage servicing the same inventory, and avoid extracting items from it to fulfill the item export. Like with LP, this would be especially useful with the Exporter's Regulator mode.

**Comment by raoulvdberge** [comment]
I don't think so, this brings needless complexity.
