### ISSUE TITLE
Game crash when using constructor 

### ISSUE THREAD

**Issue by Muszkal** [raoulvdberge/refinedstorage#991]
#### Issue description:
Wanting to spawn the wither, I Placed 7 constructors with the top ones being skulls and bottom soul sand. To each I connected a Detector and set it when my stars are below 3.
#### What happens:
Just when i connected it to my system, the game crash,

#### What you expected to happen:
place heads and soul sand

#### Steps to reproduce:
1. Setup 7 constructors with each having a detector
2. Filter top to be wither skulls and bottom to be soul sand
3. connect to the system
4. Crash!
...

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge: 7.1.6251.1229 Beta
- Refined Storage:1.2.20

Does this issue occur on a server? [yes/no]
No, local

#### If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here]
[http://pastebin.com/LG1BAB6W](url)

**Comment by raoulvdberge** [comment]
Update your RS, this was fixed in 1.2.21.
