### ISSUE TITLE
Compare Metadata

### ISSUE THREAD

**Issue by Speiger** [raoulvdberge/refinedstorage#993]
#### Issue description:
RS cant see the difference in items that have metadata & itemdamage split (and yes thats possible inside of MC and no its not a hack. ItemDamage goes into NBT while metadata == itemStack.itemDamage)

#### What happens:
It cant see the difference in them. Even crafting recipes cant be seen if there is a metadamage item..
It really dislikes it.

#### What you expected to happen:
That your mod checks for metadata with the function getMetadata. Like MC does.

#### Steps to reproduce:
1. Use a MetaDamage item in any request that is not metadata 0 and see what happens.
...

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge: Not latest but its not a forge bug
- Refined Storage: Not latest but sourcecode in both versions compared and the sourcecode is equal.

Does this issue occur on a server? [yes/no]
Yes.

#### If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here]
http://imgur.com/a/CSjKy

**Comment by raoulvdberge** [comment]
While I think you are right, further investigation is required to check possible side-effects of this change.

**Comment by Speiger** [comment]
Well look into minecrafts recipe class which i think should be the basement of Setputs.
Yes its true mc is not always right on the other hand forge should not be trusted blindly...
I fixed it on my side by removing damage access from the items in other words you can only see the metadata in getMetadata() and getItemDamage since that solves the issue but no longer allows to compare damage...

Your mod is not the only mod that has the issues.
- Forestry,
- EnderIO,
- Basicly Any mod that uses getItemDamage to compare metadata.
So to solve this issue a lot of mods need to be fixed and i doubt that this will happen in 1.10.2 or further.

**Comment by raoulvdberge** [comment]
This issue is irrelevant in 1.13.
