### ISSUE TITLE
Autocrafting causes NBT tag out of range, crashes minecraft 

### ISSUE THREAD

**Issue by postal291** [raoulvdberge/refinedstorage#994]
#### Issue description: Autocraft order of 150 units from storage reborn (the heat sync looking blocks) causes the follow error; http://pastebin.com/stSEdVjJ
This error happens as soon as the world loads, so I'm banished from my single player game ATM.

#### What happens:
World loads, autocrafting request causes crash, world unloads.

#### What you expected to happen:
I would expect the world to load, and autocrafting to chug away at the crafting request.

#### Steps to reproduce:
1. Setup a crafter with reborn storage block recipes
2. Request 48 frame blocks, 150 inner-outer blocks (framing blocks for a 7x7x7 setup)
3. Watch in agony as your world dies leaving you locked out.
...

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge:12.18.3.2215
- Refined Storage:1.2.18

Does this issue occur on a server? [no, SSP]

Entire log is larger than the 512kb limit...  The pastebin I linked above is the relevant portion of the log.

Is there a way to cancel the request directly from the files?

**Comment by postal291** [comment]
Update: Attempted to recreate the issue in a creative world... Nope.  Seems to only be affecting my single player SF3 (3.0.6) world, looks like I'm restarting :(

**Comment by raoulvdberge** [comment]
Update HWYLA, this is not an RS issue.
