### ISSUE TITLE
(1.10.2) Unable to automate the upgrade of a Draconic Evolution tool

### ISSUE THREAD

**Issue by itanshi** [raoulvdberge/refinedstorage#995]
#### Issue description:

I am unable to automate the upgrade of a Draconic Evolution tool as it does not recognize the tool.

https://www.youtube.com/watch?v=uT707TO-qso

#### What happens:
See video

#### What you expected to happen:
See video

#### Steps to reproduce:
See video

...

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge: 12.19.3.2221
- Refined Storage: 1.2.21

Does this issue occur on a server? [yes/no] yes as well

#### If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here]

**Comment by raoulvdberge** [comment]
Err, why wasn't this closed automatically by that commit...
