### ISSUE TITLE
Fluid Interface Does Not Drop Upgrades

### ISSUE THREAD

**Issue by Trcx528** [raoulvdberge/refinedstorage#997]
#### Issue description:
When broken, a fluid interface does not drop upgrades contained within.  This is unlike the (item) interface that drops it's contents and upgrades.  

#### What happens:
Only the fluid interface drops.  

#### What you expected to happen:
The fluid interface should drop, along with any upgrades.  

#### Steps to reproduce:
1. Place a fluid interface
2. Put a speed upgrade in the fluid interface.
3. Break the fluid interface.   Only the fluid interface drops.  

#### Version

- Minecraft: 1.10.2
- Forge: 12.18.32221
- Refined Storage: 1.2.18
- Modpack: FTB Infinity Lite: 1.6.0

I realize that newer version of RS exist, but there is nothing in the change logs, no recent issues and no commits that appear relevant to this issue.  

Does this issue occur on a server? Yes

**Comment by Meryl** [comment]
I can confirm this bug to be in 1.2.21 as well, and if I may be so bold, I think it's because NetworkNodeFluidInterface has no getDrops() method.

**Comment by raoulvdberge** [comment]
Indeed, I forgot about that one!
