### ISSUE TITLE
Exporter with crafting upgrade crafts unnecessary items

### ISSUE THREAD

**Issue by Meryl** [raoulvdberge/refinedstorage#998]
#### Issue description:
An exporter that has been set to export a certain item will send a signal to the system to craft that item, even if it doesn't need that item (i.e. the target inventory is full), as soon as the item reaches 0 in the system.

A side effect of this is that when you are exporting a certain item multiple times using different exporters, you only ever need one crafting upgrade. The exporters without a crafting upgrade will use the items called for by the exporter with the crafting upgrade.

#### What happens:
I have setup the system to autocraft item X. Elsewhere in the system, I've got an exporter with a crafting upgrade set to export item X into a chest. When the chest is completely filled, and I reduce the amount of item X in the system to zero (by any means, be it by hand, exporter, interface, etc.) the system automatically crafts a new item X, even though the chest to which it is set to export that item is already full.

#### What you expected to happen:
I expect the exporter not to send a crafting signal until the item is necessary.

#### Steps to reproduce:
1. Create a small network with an autocrafting recipe for an item
2. Have the network export that item through an exporter with a crafting upgrade into an applicable inventory, wait for that inventory to fill completely.
3. Remove the remaining items from the network by *any* means.
4. The system will automatically craft a new item whenever it reaches zero items.

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge: 12.18.3.2221
- Refined Storage: 1.2.21

Does this issue occur on a server? **Yes**

#### If a (crash)log is relevant for this issue, link it here:

N/A

**Comment by raoulvdberge** [comment]
This is intended behavior, the system will always keep an extra in stock.
